### ISSUE TITLE
delete cannons from follow-leader-races

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1014]
**Author: rubberduck7**

delete cannons(like in farm the rolling hay bails or in fortmagma the big "ball")

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/958

**Comment by Alayan-stk-2** [comment]
Marking as solved with the additional time added to the countdown when the leader is hit by an explosion or rescued. Entirely removing dynamic obstacle from tracks in FTL race is not desirable.
