### ISSUE TITLE
Keep track of input state while game is paused

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1021]
**Author: btdavis**

Currently, the player controller resets all inputs (that is, it considers all buttons to be "not pressed") after a pause. However, it is sometimes natural to keep a button held down as the game unpauses, in particular the accelerate key.

The attached diff makes changes such that the player controller always receives actions while in game mode, but buffers those actions during a pause. Then after the pause, instead of resetting, the controller is updated and any relevant actions are performed (and only the most recent input state is used, to prevent spamming/accidentally triggering actions).

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/965 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/965 )

**Comment by Alayan-stk-2** [comment]
For many inputs, it is irrelevant to not keep the button pressed when resuming after a pause : nitro, powerup...

For others, namely acceleration and turning left or right, it is really easy to correct after getting out of pause, with negligible losses.

Drifting is the only exception, as pause interrupts the drift. However, in online play pauses don't interrupt the game, so the issue of interrupted drifting only really exists in local play... But in single player, it's also very easy to just wait a second or two before pressing the pause button.

So the only meaningful use case for such a change would be splitscreen multiplayer, when one player suddenly pauses while the other is drifting. This is a very limited situation, and even then the impact is very minor. For reference, I did a test and with 10 scheduled pause at specific times, I lost a total of 3 seconds from interrupted drifts compared to no pause. That's around 0.3s / pause on average, some more, some less.

If this minor discrepancy bothers some players, it is simple enough to not pause... If two players playing together in splitscreen are concerned about the other pausing abusively, the game trying to make resuming afterwards fairer should not be their first concern either.
