### ISSUE TITLE
Easy short-cut in xr591

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1023]
**Author: unitraxx**

One can easily ride under the arrow signs.
See screenshot for more information.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/967 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/967 )

**Comment by qwertychouskie** [comment]
Or just move the arrows down a bit...
