### ISSUE TITLE
Scores overlay weird in split-screen with 3 players

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1041]
**Author: auria**

See attached screenshot. Not sure what to do. I've always found that overlay ugly so maybe this is a good opportunity to find a better way to make the text readable

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/985 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/985 )

**Comment by hiker** [comment]
Postponed, not a release blocker.

**Comment by Alayan-stk-2** [comment]
Here is how it looked like (embedding attached picture for easier viewing) : 
![3-players-result](https://user-images.githubusercontent.com/25536748/40274145-e8cc4c0c-5bcf-11e8-84c0-9a4d5c96d39d.jpg)

Here is how it looks in the latest master : 
![3-players-result](https://user-images.githubusercontent.com/25536748/40274150-f12b03ca-5bcf-11e8-99d1-ccd9fa9972cb.png)

**Comment by auriamg** [comment]
It could still look prettier, though the original issue no longer exists
