### ISSUE TITLE
~1k lines of duplicated code

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1042]
**Author: curaga**

The copy-paste detector report is attached.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/986 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/986 )

**Comment by auriamg** [comment]
This seems outdated, I can no longer find significant overlap between the 2 files
