### ISSUE TITLE
Fort magma could use more arrows/signs

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1043]
**Author: curaga**

Many parts of fort magma are unclear, see http://postimg.org/image/c7abbpeav/

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/987

**Comment by Alayan-stk-2** [comment]
Not relevant anymore with the current Fort Magma being replaced by New Fort Magma in 2.0.
