### ISSUE TITLE
Bug with ignore light flag and LOD

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1052]
**Author: samuncle**

When a LODed object use the flag ignore light its affect only the first object.

You can see this bug in Blackhill's mansion with pumpkins 

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/996

**Comment by auriamg** [comment]
This happened in irrlicht and AFAIK is no longer relevant in the new engine
