### ISSUE TITLE
Crash when changing resolution

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1056]
**Author: kroartem**

Stk r[12862], Ubuntu 13.04 64-bit
changed resolution.
wanted to change custom settings -> crash
```
supertuxkart: /home/kroartem/SVN/supertuxkart/src/guiengine/widgets/spinner_widget.cpp:348: void GUIEngine::SpinnerWidget::setValue(int): Assertion `new_value < (int)m_labels.size()' failed.
  (  )
```
Cannot reproduce it now. Also don't know where to dig.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1000

**Comment by qwertychouskie** [comment]
This was a non-reproducible crash in a over-two-year old version of STK, can this be closed?
