### ISSUE TITLE
Restarting on the wrong place after falling into the river in Green Valley

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1063]
**Author: konstin**

If you create a new race in Green Valley and then directly drive into the river on the right side, the referee will take your kart and teleport it a place on the other side of the map. In version 0.8, there was a different - but also unwanted - behavior of the game. Details about the old bug can be found in [#839](https://sourceforge.net/apps/trac/supertuxkart/ticket/839)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1007

**Comment by qwertychouskie** [comment]
I checked, and couldn't reproduce this bug.  This can probably be closed.
