### ISSUE TITLE
Support shader for karts

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1064]
**Author: samuncle**

Currently you can only choose shaders for track.

It would be useful to have this feature also for karts

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1008

**Comment by auriamg** [comment]
This is not required for 0.8.2

**Comment by auriamg** [comment]
Outdated, in the new rendering engine shaders work everywhere
