### ISSUE TITLE
Hide/show widget

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1075]
**Author: xenux**

Currently, only few widget can be hidden/showed. We should add a universally way to hide/show widget, so we can use this feature anywhere in a gui.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1019

**Comment by auriamg** [comment]
Closing as outdated, if we find issues with specific widgets we can fix those or create more specific tickets
