### ISSUE TITLE
Overworld splatmap inefficiency

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1082]
**Author: curaga**

- overworld's splat map is far too big: 128x128 produces the exact same result with much less vram use
- it's duplicated for no reason (splat.png is identical to splat2.png)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1026

**Comment by auriamg** [comment]
Splat map is now a lot smaller, can be closed
