### ISSUE TITLE
hacienda has an embedded sky sphere

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1083]
**Author: curaga**

Hacienda (at least, maybe other tracks too) includes a sky sphere in the track itself.

It (and other such tracks) should be converted to a normal, XML-specified sky. This is because when included like that, it gets handled and lit like a normal mesh in the new pipeline.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1027

**Comment by samuncle** [comment]
it should be corrected now. I enabled the IBL + a real skybox.

You can always reopen it if there is a problem
