### ISSUE TITLE
Engine sound when burning Nitro

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1087]
**Author: totoplus062**

We don't currently have a sound when using nitro.

The idea is to activate engine_nitro.ogg instead of engine_small.ogg (not engine_large) when Nitro key is activated. 

Here is the file:
http://sendbox.fr/pro/t3voevjvomrk/engine_nitro.ogg.html

Totoplus62

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1031 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/1031 )

**Comment by qwertychouskie** [comment]
Can this be closed now that STK has a nitro sound?
