### ISSUE TITLE
Add support for destroyable objects

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1090]
**Author: samuncle**

In every race game when you hit a traffic light for example the post is destroyed and you have pieces flying everywhere. 

For destroyable objects you have:

An instance (like LOD).
A normal object, fixed
A destroyed object, movable by the player

When the normal object is hit it's replaced by the physical/destroyed object.

Of course to not overload the physical engine we can remove after a time the physical object.

For example in the track sub sea there is pillar. The normal object will be a pillar and when the player hit this pillar it will be replaced by several pieces flying everywhere.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1034

**Comment by qwertychouskie** [comment]
Support seems to exist now (http://i.imgur.com/rJmqSKL.png), can this be closed?
