### ISSUE TITLE
Kart flicker bug

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1099]
**Author: marclennart**

Before the race starts, some karts flicker. For example in the track Alpine-2. It's not very bad, but it's better if you fix the bug. Thanks!

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1043 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/1043 )

**Comment by hiker** [comment]
Is this still an issue with our recent beta2?

**Comment by deveee** [comment]
Maybe it is related to #1548?

**Comment by auriamg** [comment]
Yes it still happens, though it's not a new issue, it's been in there for a long time and is probably a culling bug in irrlicht. It's however quite minor and should not stop a release

**Comment by qwertychouskie** [comment]
Is this still an issue?

**Comment by qwertychouskie** [comment]
I have never noticed, it was probably fixed with Antarctica.  Unless someone has seen this issue recently, this should be closed.

**Comment by auriamg** [comment]
Closing as outdated
