### ISSUE TITLE
Screen flickers when you set multiplayer mode in main menu

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1102]
**Author: deveee**

Look at the video:
http://youtu.be/mI5igKZF92Y

When you click single player everything is ok. When you click multiplayer mode, screen flickers.

I noticed it only in old laptop with windows vista.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1046

**Comment by deveee** [comment]
Not a release blocker.

**Comment by deveee** [comment]
It only happens with old pipeline and buggy drivers on very old hardware in debug mode, so I'm closing it as invalid.

**Comment by deveee** [comment]
Not sure why it's still open :P
