### ISSUE TITLE
"Sky Vibe - High Frequency" license questioned

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1104]
**Author: onpon4**

Someone pointed me to this thread:

http://forum.jamendo.com/index.php?p=/discussion/comment/3036672#Comment_3036672

It's full of dead links, but basically, among some other stuff, someone suggests that this composition is not actually under CC BY-SA. It looks to me like baseless speculation, but perhaps an investigation and/or a clarification here would be a good idea.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1048

**Comment by qwertychouskie** [comment]
Doesn't it seem like a copyright issue should get more than a P3: normal?  Seems pretty important to me...

**Comment by auriamg** [comment]
@qwertychouskie your comment is not helpful here, we need a replacement first. OzoneOne/Krobonil will provide one when they are ready and your comment won't make that come any sooner

**Comment by qwertychouskie** [comment]
According to http://wayback.archive.org/web/20120728083029/http://speedsoundrec.com/aboutus/, their email is xvibe.com@gmail.com.  Maybe someone can contact them to confirm the license?

**Comment by qwertychouskie** [comment]
Turns out as of that post, a replacement already existed: https://forum.freegamedev.net/viewtopic.php?f=18&t=6012&hilit=alien&start=25#p62071

As per my previous post, their email address is (or at least was) xvibe.com@gmail.com, can someone contact them via the STK email account?  If there is no reply, it would be best to just use OzoneOne's track.

**Comment by Alayan-stk-2** [comment]
It appears that the reporter of this issue wrote at the time:
> I did a search on STK's bug tracker, and although nobody has reported any music as being wrongly licensed, I did find this bug report that mentioned Speedsound's music.[1] It suggests that the music from Speedsound is taken from an old album that was licensed under CC BY-SA, and it's the newer albums that are under a different license (CC BY-NC-SA). It also suggests that Speedsound stopped distributing this old music under CC BY-SA, but that would not void a previously existing license grant.

Based on https://github.com/supertuxkart/stk-code/issues/741 where someone complained that some artists dared to use different licensing for their new productions:

> Music by the bands The Dead Rocks and Speedsound is no longer free and should be replaced. Although **old albums still remain CC-By-SA**, newer albums are now CC-By-NC-SA. Even if those stay free, it could be seen as an endorsement to non-free media.

The claim that this music's license is incorrect appears to be baseless speculation, mostly relying on the fact that, many years after the fact, some parts of the Internet are lost or changed, making it difficult to check things.

But there is no reason to believe that licensing information was wrong when the track was added to the game.
