### ISSUE TITLE
Greek font is partially unreadable

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1119]
**Author: skarmoutsos**

All greek letters that have an accent, do not show up on STK. Their position is blank.

All other non accent characters are OK.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1063 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/1063 )

**Comment by hiker** [comment]
In our latest beta I see accented Greek characters - and while I can't verify that it is correct it at least means that the font is fixed now.
