### ISSUE TITLE
Egg hunt : controls stuck when finishing

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1141]
**Author: auria**

When finishing easter egg hunts, you kart will keep going with whatever you pressed when ending. So if you were skidding when getting the last egg, it will keep on skidding forever

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1085

**Comment by qwertychouskie** [comment]
I think the current condition is good enough, can this be closed, as the original issue was fixed?
