### ISSUE TITLE
Crash when you enter to garage

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1144]
**Author: deveee**

Little hard to reproduce. When you enter to garage in overworld and very quickly press escape (before kart selection screen is displayed), it causes crash.

It's easier to reproduce when you change action in track_object_presentation.cpp. There are lines:
    if (m_action == "garage")
    {
        new RacePausedDialog(0.8f, 0.6f);
        //dynamic_cast<OverWorld*>(World::getWorld())->scheduleSelectKart();
    }
When you will change action to scheduleSelectKart, then you can run to garage with constantly escape pressed and it most probably will cause crash.

Backtrace in attachment.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1088 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/1088 )

**Comment by deveee** [comment]
I'm not able to reproduce it anymore.
