### ISSUE TITLE
Size of Gnu

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1150]
**Author: hikerstk**

A follow up of #1023 (to be assigned after 0.8.1): apparently gnu's b3d file size doubled when re-exported a while ago, and I noticed that gnu's carpet is 116 KB, which appears a bit much for a model of 28 vertices (8 floats each) and 5 bones for 20 frames (5_20_8 floats). Yes, there are additional indices, and strings, textures, but I am not sure if this adds up to this size, it's worth checking imho.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1094

**Comment by qwertychouskie** [comment]
> it's worth checking imho.

Apparently not, since it hasn't been in 2 1/2 years. :P  Can probably be closed, or at least marked as "P6: pathetically trivial". :)
