### ISSUE TITLE
bluetooth support unconditionally built

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1168]
**Author: dimstar**

Seems bluetooth support (wii support) is built without verifying if the bluetooth headers are available.

This resulted in my first tests in a build failure too far down in the build

If this is mandatory, it is expected that CMake verifies on it's presence and aborts at before actually building the code or bluetooth support is disabled if not detected.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1112

**Comment by deveee** [comment]
Check for libbluetooth library was added in 6b8f12b1b5b4f668cbf5db505dcf5b682f146265. Works for me now.

**Comment by leper** [comment]
It still fails quite late in the build process instead of doing the checks as early as possible, so if you use multiple jobs to build you might miss the error.
