### ISSUE TITLE
Make STK 'updateable' in game

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1171]
**Author: hikerstk**

It would be a nice feature to be able to update stk (or parts of stk) in game. Some thoughts:

1) data files:
they could be updated by making the file manager a bit more intelligent: if it tries to open a file X in the data package, it would first check if there is a file in '.../addons/update/X', and if so transparently load that newer file. Some work would be required to enable this feature for textures loaded from b3d models.
2) Executable: STK should be started from a script. This script will check for a new binary in '.../addons/update/bin' - and if so start that binary instead of the installed one. If STK exits with a certain return code, that script would automatically restart (which is used to download a new binary in game, then restart STK with the new binary). Security would be crucial, i.e. it should get a hash sum from a different server to make sure it is really an official binary.

The current addon server can then be used to install new updates in '.../addons'.

Some care must be taken of inconsistencies (e.g. some data is loaded from the installed directory, then an update is installed --> there might be some incosnsitencies now between updated and already loaded files). Also there must be a way of removing files (not from the install location, but from a previous update) to avoid taking up too much space on disk.

This is more of a long term goal, or a potential GSOC project.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1115

**Comment by qwertychouskie** [comment]
At a minimum, STK should notify the user when a new version is available with something like this:
![dialog](https://user-images.githubusercontent.com/13989090/26904933-4f595f34-4b99-11e7-8a5a-646bb9a6ab11.png)
Implementation should be simple, just have a plaintext https://addons.supertuxkart.net/CurrentVersion that has the latest version number, e.g. `0.9.3`.

**Comment by SuicSoft** [comment]
on Linux we should only check if it is up to date and not try to update it since Linux already has a package manager

**Comment by qwertychouskie** [comment]
That's the idea, just let the user know a new version is available for download from the website.

**Comment by qwertychouskie** [comment]
PR https://github.com/supertuxkart/stk-code/pull/2855 opened.

**Comment by qwertychouskie** [comment]
Should probably be closed as it seems this is no longer wanted (see #2855, #2924).
