### ISSUE TITLE
Arabic letters are not connected and others

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1173]
**Author: safaalfulaij**

The Arabic letters are not connected, they are separated.
See this image:
http://img62.imageshack.us/img62/451/kn53.png
The words right Story mode.
This is from 0.8:
http://img138.imageshack.us/img138/3517/xyq3.png
(The font is the old font)
Also the two files "rasheeq3.png" and "rasheeq4.png" are not neccessry because we use now a new font.
The font name is kacstone, so "rasheeq" should be change to "kacstone"

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1117

**Comment by auriamg** [comment]
Closing as outdated since the freetype branch was merged. Please open new issues if there are still issues with the freetype render
