### ISSUE TITLE
Freeze when activating sound effects

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1175]
**Author: auria**

If sound effects are intially disabled, STK will freeze for a few seconds when enabling them. May be worth showing some kind of "loading" screen to communicate that STK hasn't crashed

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1119

**Comment by qwertychouskie** [comment]
On my system (and I should note I have relatively slow HDD) it took a whopping 1/4 of a second to load. ;)  Can probably be closed.
