### ISSUE TITLE
Cross-compiling does not work correctly.

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1190]
**Author: jontom**

When I try to cross compile, I set the CMAKE_FIND_ROOT_PATH value to my rootfs for my target platform.

CMakeFiles/supertuxkart.dir/flags.make correctly has a -I option for the usr/include under my target's rootfs directory. All the flags.make files for all the libraries do not.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1134

**Comment by deveee** [comment]
Cross-compile works on Ubuntu with installed mingw and with downloaded STK dependencies.

You need to use in build directory:
cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw.cmake

If you need, you can modify toolchain file for your compiler.
