### ISSUE TITLE
Too much bots for toplist

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1192]
**Author: usul1**

Currently STK allows 18 opponents. Sadly this number is to big and during the race the opponent list at the OSD does only dislay the very first players, but not all that take part at the current race. But after the race, the toplist scales well.

I use STK at 1376x786px. 

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1136

**Comment by qwertychouskie** [comment]
Maybe two rows when needed?

**Comment by Alayan-stk-2** [comment]
Honestly, when racing, it's hard to keep an eye on this list as we have other things to do. But it's cool to know when an opponent is hit with the exploding icon, or when he has some special item.

Allowing all 20 karts to be there would probably clutter the screen too much. A two rows solution would be horrendous.

But I see a small issue with the current config. In some ways, it would be cool to know what's happening to the karts around you, and this doesn't happen if you are >12th. I don't know if it is possible to conciliate this with the fact that when the first finishes a lap, the list is used to display times.
