### ISSUE TITLE
xmas cap is displaced at some cars

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1193]
**Author: usul1**

Hi, the christmas cap is a really nice tweak and easteregg :)

Unfortunatly, some karts don't seem to support it well, as the cap is placed off the mascott itself and maybe flickering.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1137

**Comment by auriamg** [comment]
This ticket only mentions pidgin, which is now fixed.  If we notice issues with more karts we can open new tickets
