### ISSUE TITLE
Completing the final challenge at lower difficulties first doesn't give all points when solving at Expert

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1196]
**Author: magned**

From IRC:

<GottfriedHofmann> bug is: I cannot get all 240 points in story mode
<GottfriedHofmann> first I played all levels in silver, then in gold
<GottfriedHofmann> but after defeating the castle villain, there where graphics glitches and I only could restart or leave the race
<GottfriedHofmann> now all places on the map are golden, but the points are still 239 with one silver trophy
<GottfriedHofmann> after restarting all is fine
<GottfriedHofmann> let me check wether it happens again if I set fortmaga hard to false and win again
<GottfriedHofmann> yep, same thing
<GottfriedHofmann> there is no "you completed a challange"-animation
<GottfriedHofmann> I can only restart or go back to challenge selection
<GottfriedHofmann> where the fort becomes golden on the map
<GottfriedHofmann> but the points are just 239

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1140

**Comment by auriamg** [comment]
Closing as outdated, we can reopen with details if it happens again
