### ISSUE TITLE
Animated meshes cannot use normal maps

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1206]
**Author: auria**

The golf balls from minigolf are loaded as animated meshes. Apart from being slower, animated meshes cannot have normal maps, which breaks normal maps rendered on them

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1150

**Comment by Benau** [comment]
You can use normal maps on animated model (karts, library object) now
