### ISSUE TITLE
EXC_BAD_ACCESS when closing the main window

### ISSUE THREAD

**Issue by 3rr3s3v3n** [supertuxkart/stk-code#1220]
Good Afternoon to everybody, I hope I don't have duplicated this issue ;)
When I close the main window it crashes on 
[Window setIsVisible:FALSE];
into void CIrrDeviceMacOSX::closeDevice()
defined in ClrrDeviceMacOSX.mm.
It says EXC_BAD_ACCESS, maybe due to unmanaged release of the window object, but I'm not sure...

**Comment by hiker** [comment]
@3rr3s3v3n is this still an issue with our beta2? Afaik stk should be running fine now.

@auriamg Not sure if you could recreate it in the past, and can verify if it is fixed now?

**Comment by auriamg** [comment]
I can confirm this bug still exists. It seems to be a bug in irrlicht, the windows has already been closed and freed but the device still tries to close it
