### ISSUE TITLE
Reset karts when stucked

### ISSUE THREAD

**Issue by Ryuno-Ki** [supertuxkart/stk-code#1242]
Hello,

as already stated [on the mailinglist](http://sourceforge.net/p/supertuxkart/mailman/message/32098497/) I encountered multiple time AI karts to get stucked when leaving the driving line too far. I've got a jungle.replay file (1.3 MB) and [uploaded it in a Gist](https://gist.github.com/Ryuno-Ki/9550690) (thanks GitHub =)). It was mentioned to compromise it, but I have no idea, how to do this cleverly (zipping?).

It could be a duplicate of #639.

![stk-jungle-kart-stucked](https://f.cloud.github.com/assets/3097194/2422715/2ee07630-ab91-11e3-9e1a-ea591b640010.png)
![stk-kart-got-stucked-in-jungle](https://f.cloud.github.com/assets/3097194/2422727/5f6420ae-ab91-11e3-866e-3f02d4352f58.png)

STK v0.8.1 on Sabayon Linux.

**Comment by Benau** [comment]
Now the timer is fixed and this issue is fixed too, before void AIBaseController::crashed(const Material *m) won't work if the timer is counted backwards (in FTL), so won't reset karts
