### ISSUE TITLE
Hide linked textures in the blender exporter

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1258]
Currently when an object is linked its textures are available in the texture list of the exporter. This is not intended it shouldn't be possible to modify a generic texture in a track.

The easy solution is to hide/don't export option from texture that aren't in the same repository than the track

**Comment by auriamg** [comment]
Ability to automatically cleanup old B3D files has been added (it needs to be enabled in plugin options first)

**Comment by baptx** [comment]
Do you have an idea where we can we find the latest B3DExport.py Blender addon so we can export animations to B3D files for Irrlicht game engine? (not necessarily for SuperTuxKart)
It looks like the addon has been removed from SuperTuxKart, the latest version I found is here: https://sourceforge.net/p/supertuxkart/code/17107/tree/media/trunk/blender_25/B3DExport.py
Someone shared a download link https://www.rtsoft.com/forums/showthread.php?7509-Blender-B3D-2-6x-Export-script but I guess it is outdated?
There is also another repository but I don't know if it is the official latest version: https://github.com/RainWarrior/B3DExport

**Comment by qwertychouskie** [comment]
@baptx As far as I know https://sourceforge.net/p/supertuxkart/code/17112/tree/media/trunk/blender_25/B3DExport.py is the last version of the B3D exporter, afterwards STK switched to its own in-house file format (SPM) for faster load times and smaller file sizes.

**Comment by baptx** [comment]
@qwertychouskie thanks for the information, is the last version of the B3D exporter you mentioned specific to SuperTuxKart or can it be used for any Irrlicht game?
Would it be possible to merge back to Irrlicht the work that has been done on the new SPM format (and maybe other features like Antarctica graphics renderer) or it is limited and specific to SuperTuxKart assets?

**Comment by qwertychouskie** [comment]
Not sure if it can be used for other games, but I would guess so (I think Minetest may use an old version of this exporter.  SPM may be portable to Irrlicht (https://github.com/supertuxkart/stk-editor was ported to use SPM, and uses a mostly pure Irrlicht, see https://github.com/supertuxkart/stk-editor/commit/4b80247485e00478d061089fa0fc7dab5409de8d), but Antarctica as a whole is pretty tight with STK itself.  IMO if you are starting a new game it would be better to use Godot or Ogre3D as Irrlicht has very little development happening anymore (the last major Irrlicht release was in 2012).

**Comment by baptx** [comment]
Godot looks interesting also but it does not have a complete C++ documentation and examples at the moment and I had some performances issues (https://github.com/Regalis11/scpcb/issues/80#issuecomment-416521176). Ogre3D may be interesting. I also heard of Armory3D and Urhor3D as an alternative to Blender Game Engine but they are not used a lot for the moment.

**Comment by auriamg** [comment]
I think this is complete enough, if more issues remain, a separate issue can opened to track them easier
