### ISSUE TITLE
Change colour of bubble gum to indicate remaining time

### ISSUE THREAD

**Issue by Ryuno-Ki** [supertuxkart/stk-code#1274]
STK has a new bubble gum protective shield now. However, as driver it's hard to estimate the remaining time, until the gum is dropped.

I thought, the colour could get desaturated (that is, turn from pink to gray) or changed, e.g. into brown.
This would remind on the colour, bubble gum gets when aging :D

**Comment by auriamg** [comment]
A pull request implementing this was merged
