### ISSUE TITLE
Closing stk window on race generate memory leaks.

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1284]
When closing stk while on a track in windowed mode, there are a lot of reported memory leak.
Closing this way seems not to trigger the correct exit callback in stk.

**Comment by hiker** [comment]
Online accounts are properly logged out, so this ticket is not important anymore. Will do some minor fixes for 0.9.2

**Comment by hiker** [comment]
Fixing the GUI leaks is not trivial (e.g. closing the window while the in-race dialog is open), and memory leaks do not matter when closing a window,so we won't fix this.
