### ISSUE TITLE
trivial: delete unused branches

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#1293]
There are many branches which are up to 2000 commits behind master (e.g. next_gen ,ai and rewind) and which can't be merged anymore. It would make sense to delete these because they have no use anymore.

**Comment by qwertychouskie** [comment]
Obsoleted by #2583, can be closed.

**Comment by Benau** [comment]
@deveee  can gles branch be deleted? (If so this can be closed too)

**Comment by Benau** [comment]
Thank you

**Comment by deveee** [comment]
Ok, removed. 

The EGL branch could be removed either because it just allows to create EGL context, which is already available in GLES2 driver. Context creation should be moved to separate class so that other devices (for example OpenGL 3 + Wayland) will be able to use it.
