### ISSUE TITLE
Crash after exiting a race

### ISSUE THREAD

**Issue by solistice** [supertuxkart/stk-code#1323]
Following stacktrace is given when exiting a race (either with the Exit Race or closing the application altogether): http://pastebin.com/GeteBbgV

Easily reproducible by exiting the game in any given way. I have no knowledge wether this only occurs on Mac OS, but it happens every time

**Comment by solistice** [comment]
Tried to reproduce and never occurred anymore! Think this is fixed, but since this was not always 100% reproducable, I'm going to leave it open for now

**Comment by hiker** [comment]
Appears to be a duplicate of #1938 .
