### ISSUE TITLE
(X360) Controller button mapping is weird

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1344]
The button mapping on XInput device (like the official x360 pad) is weird. The left stick is used for acceleration and brake whereas usually RT and LT (ie "R2" and "L2" on PS like pad) are used for these purpose. Start button does nothing while RB ("R1") open the menu. Right stick does nothing, it could be used to rotate the camera to some extent.

**Comment by auriamg** [comment]
Default mapping was modified some time ago, it's probably okay now
