### ISSUE TITLE
Kart AI issues

### ISSUE THREAD

**Issue by solistice** [supertuxkart/stk-code#1345]
After testing some different values for kart properties, I came to the conclusion that even normal AI needs rescues / drives through bananas when driving alone. I did 5 test runs, where every run was 10 laps. This makes a total of 50 laps:
City: 1 rescue, 24 bananas
Farm: 6 rescues, 76 bananas
FortMagma: 14 rescues, 1 banana
GreenValley: 2 rescues, 1 banana (but drives against rock in middle of the road)
Hacienda: 0 rescues, 0 bananas
IslandTrack: 19 rescues, 20 bananas
Jungle: 45 rescues, 1 banana
Lighthouse: 0 rescues, 0 bananas
Mansion: 24 rescues, 50 bananas

I, for obvious reasons, left out the tracks under construction, and I didn't test every other track, but this is just an overview.

All karts drove on mode=3, the "advanced" AI. I think they should really be able to drive the road and avoid bananas :)

**Comment by qwertychouskie** [comment]
Is this still an issue?  Most of those track have been/are being replaced...

**Comment by Alayan-stk-2** [comment]
The current AI has issues with driving into bananas, but this report about a very old AI version is not helpful anymore.
