### ISSUE TITLE
Font misalignment and font tool defaults

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#1370]
There are some issues with the font creation and/or loading in the game. Mainly, some fonts get letters such as g, y and similar misaligned in the game (too high compared to the rest, so it kinda looks like "MultiPlaYer").

Also, the font tool options could get better defaults.
Size should default to 24 or 32.
Checkboxes "AA", "Alpha" and "Export used characters only" should be on by default.
Max width and height should default to 512.
File Format should default to png.

**Comment by auriamg** [comment]
The freetype branch has been merged so this issue is now obsolete. Please open new tickets if you find issues in the freetype render
