### ISSUE TITLE
Visualize Slip Stream Progress

### ISSUE THREAD

**Issue by JohannesRitz** [supertuxkart/stk-code#1379]
There is no visual feedback that indicates that the slipstream bonus boost is reached. I hardly use slipstream, because I never know how well I am doing when trying to follow the kart in front of me. Always at least one question remains: How much longer does it take to receive the bonus?

I suggest to either (temporarily) show a slipstream progress bar in the HUD or at least to indicate that a kart received the bonus boost by showing some sparks at the kart's exhaust pipe.

**Comment by Benau** [comment]
Slipstresm mesh is no longer re-upload each frame
