### ISSUE TITLE
launchpad ppa didn't move to git

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#1415]
The launchpad daily ppa (https://launchpad.net/~stk/+archive/ubuntu/daily) is still using svn and therefore doesn't create new builds - The latest is 32 weeks old. It also doesn't contain builds for the new ubuntu releases.

**Comment by konstin** [comment]
I've successfully created a ppa that can do daily builds from current git and svn (https://code.launchpad.net/~konstin/+archive/ubuntu/stk-nightly-ii). It can be installed normally through the package manager, but when I try to launch, it fails because it doesn't find the assets.
The problem is that STK remembers the absolute path where the assets were installed (`[info   ] [FileManager]: Data files will be fetched from: '/build/buildd/supertuxkart-0.8.2-source+10339-assets+4349/debian/tmp/usr/share/supertuxkart/data/'`) because of some cmake magic I don't understand. 

It would therefore be great if someone could tell me which CMake options I have to set to make STK find its assets. I'm currently using [this](http://bazaar.launchpad.net/~konstin/stk/debian-files/view/head:/debian/rules) rules file for building.

**Comment by deveee** [comment]
I think that path to data directory should be relative. It would also
solve problems with "make install DESTDIR=local/path" command.

**Comment by auriamg** [comment]
Setting to 0.8.2 since we'll need to sync translations before release

**Comment by konstin** [comment]
This has nothing to do with translations; But I still think that this should be done for 0.8.2 because we need a debian package for Ubuntu and the old build system can't be used anymore.

**Comment by auriamg** [comment]
Oh sorry, I missed the PPA part

**Comment by deveee** [comment]
@konstin It search data files in "/build/buildd/supertuxkart-0.8.2-source+10339-assets+4349/debian/tmp/usr/share/supertuxkart/data/" because stupid install prefix was used (other than true install dir). In typical case it should be -DCMAKE_INSTALL_PREFIX=/usr or eventually /usr/local. If you need to install it in debian/tmp, you can try to use "make install DESTDIR=../debian/tmp/usr" command (it should be handled probably somewhere in rules file).

Actually we can't use relative path because game can be executed from different base directories :( I don't have better solution atm.

**Comment by konstin** [comment]
I tried to override install but it didn't work. propably because I'm not using `dh` but mainly http://www.simonschneegans.de/?p=346 ...

Do you think that just allowing to manually override `STK_INSTALL_DATA_DIR_ABSOLUTE` could solve the problem? I'ld change
```
    # Set data dir (absolute or relative to CMAKE_INSTALL_PREFIX)
    get_filename_component(STK_INSTALL_DATA_DIR_ABSOLUTE ${STK_INSTALL_DATA_DIR} ABSOLUTE)
    if(${STK_INSTALL_DATA_DIR_ABSOLUTE} STREQUAL ${STK_INSTALL_DATA_DIR})
        add_definitions(-DSUPERTUXKART_DATADIR=\"${STK_INSTALL_DATA_DIR_ABSOLUTE}\")
    else()
        add_definitions(-DSUPERTUXKART_DATADIR=\"${CMAKE_INSTALL_PREFIX}/${STK_INSTALL_DATA_DIR}\")
    endif()
```
to
```
    # Set data dir (absolute or relative to CMAKE_INSTALL_PREFIX)
    if(NOT STK_INSTALL_DATA_DIR_ABSOLUTE)
        get_filename_component(STK_INSTALL_DATA_DIR_ABSOLUTE ${STK_INSTALL_DATA_DIR} ABSOLUTE)
        if(${STK_INSTALL_DATA_DIR_ABSOLUTE} STREQUAL ${STK_INSTALL_DATA_DIR})
            add_definitions(-DSUPERTUXKART_DATADIR=\"${STK_INSTALL_DATA_DIR_ABSOLUTE}\")
        else()
            add_definitions(-DSUPERTUXKART_DATADIR=\"${CMAKE_INSTALL_PREFIX}/${STK_INSTALL_DATA_DIR}\")
        endif()
    else()
        add_definitions(-DSUPERTUXKART_DATADIR=\"${STK_INSTALL_DATA_DIR_ABSOLUTE}\")
    endif()
```

**Comment by deveee** [comment]
I'm 100% sure that it is possible to do without modifying SUPERTUXKART_DATADIR. Just look at rules files in other projects.

-DCMAKE_INSTALL_PREFIX is cmake equivalent to ./configure --prefix and should be set to /usr.

**Comment by konstin** [comment]
The problem is that `-DCMAKE_INSTALL_PREFIX` has to be set to `../debian/tmp/usr` because you can't write to `/usr` on the build machine. When you install the final debian package, everything from `../debian/tmp/usr` will be copied to your machine's `/usr`.

And I'm also not modifying `SUPERTUXKART_DATADIR`, but `STK_INSTALL_DATA_DIR_ABSOLUTE`, because the relative paths are correct, but the absolute path is generated in some chroot or container in launchpad and therefore not valid on your computer.

This is the script I'm currently using for the ppa, and it's the first version that makes STK finally work (although it's in `/usr/bin/supertuxkart` and not in `/usr/share/bin/supertuxkart`, but that's no problem imo). Note that it's heavily based on http://www.simonschneegans.de/?p=346 because this was the only really helpfull guide I could find with google:
```
#!/usr/bin/make -f

BUILDDIR = build_dir

# secondly called by launchpad
build:
	# normal STK version doesn't work so let's "patch" it ...
	rm CMakeLists.txt
	mv debian/cmakelistsoverride.txt CMakeLists.txt  # <- the modified version of CMakeLists.txt
	mkdir $(BUILDDIR);
	cd $(BUILDDIR); cmake .. -DUSE_WIIUSE=0 -DCMAKE_INSTALL_PREFIX=../debian/tmp/usr -DSTK_INSTALL_DATA_DIR_ABSOLUTE=/usr/share/supertuxkart
	make -C $(BUILDDIR) -j4


# thirdly called by launchpad
binary: binary-indep binary-arch

binary-indep:
	# nothing to be done

binary-arch:
	cd $(BUILDDIR);  cmake -P cmake_install.cmake
	mkdir debian/tmp/DEBIAN
	dpkg-gencontrol -psupertuxkart
	dpkg --build debian/tmp ..

# firstly called by launchpad
clean:
	rm -rf $(BUILDDIR)

.PHONY: binary binary-arch binary-indep clean
```

**Comment by deveee** [comment]
As I said relocate installation can be done by DESTDIR:
http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

Game binaries in Debian/Ubuntu are usually installed in /usr/games. This can be changed by modifying STK_INSTALL_BINARY_DIR. It can be /usr/bin path, but certainly not /usr/share/bin.

I will try to build it today or tomorrow.

**Comment by deveee** [comment]
Based on Hedgewars files, I was able to build STK on my local machine with following rules file:
```
#!/usr/bin/make -f

%:
	dh $@

override_dh_auto_configure:
	dh_auto_configure -- 	-DCMAKE_INSTALL_PREFIX=/usr/ \
				-DCMAKE_BUILD_TYPE=STKRelease

```

Btw. In dependencies I suggest to use libcurl4-gnutls-dev >= 7.32.0.
Openssl is not needed now because it works fine also with gnutls (which is used more frequently and which we use also on Windows iirc). And version older than 7.32.0 crashes STK.

**Comment by konstin** [comment]
Finally, everything works as intended. I've moved the final ppa to https://launchpad.net/~konstin/+archive/ubuntu/supertuxkart-nightly. Still, there are a few points I wanted to mention:
 - The make file using `dh` unfortunately doesn't work when building in the special environment ppa's are using.
 - If you agree, I'ld like to overtake https://launchpad.net/~stk/+archive/ubuntu/daily and delete https://launchpad.net/~stk/+archive/ubuntu/dev (last activity there was over one year ago)
 - The binary is installed in `/usr/bin/supertuxkart`, while the assets are in `/usr/share/supertuxkart`. ' Guess that's good because those are the cmake-defaults.
 - Somehow people need to be told about this ppa. Maybe include it in the next blog post or start a topic in the forum?

**Comment by auriamg** [comment]
Hi, if you want to take the ppa, I see no objections. And indeed we should advertise this, maybe some place on the wiki too - there is a section at the bottom of http://supertuxkart.sourceforge.net/Downloads (not very visible I know)

**Comment by deveee** [comment]
@konstin dh doesn't work for you because you don't have ```debhelper``` package in dependencies :)

**Comment by qwertychouskie** [comment]
The PPA is now outdated again, version in the PPA is 0.8.2.

**Comment by konstin** [comment]
That's because the [import from github to launchpad](https://code.launchpad.net/%7Estk/stk/trunk-git) is [failing](http://launchpadlibrarian.net/219045415/stk-stk-trunk-git.log) due to a [bzr-git bug](https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403). Until that bug is fixed, the ppa can't be updated.

**Comment by qwertychouskie** [comment]
Some people mentioned a fast export/fast import as a workaround: https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403/comments/9

**Comment by konstin** [comment]
afaik this doesn't help because the source for nightly builds should be imported automatically.

**Comment by qwertychouskie** [comment]
Maybe a SH script with a cron job for running it?

**Comment by konstin** [comment]
No, the import is done by launchpad, so neither you use cron nor shell scripts for importing. A launchpad ppa has to their default import script, so I'm pretty sure there's no easy way to fix this. I also don't know any good (and free) alternatives to launchpad that we could switch to without much additional work.

**Comment by qwertychouskie** [comment]
Maybe a Raspberry Pi for the conversion to bzr using fast export/fast import, then make Launchpad grab code from the Raspberry Pi using bzr?  The Raspberry Pi 3 is $35 (http://www.mcmelectronics.com/product/83-17300), just add a cheap power cable and MicroSD card.

**Comment by qwertychouskie** [comment]
Also, I have an RPi that runs 24/7 as a web server using Lighttpd, and I would be happy to let it be used for the conversion to bzr, if you can tell me what files to put where and what commands to run.

**Comment by qwertychouskie** [comment]
I have installed git, bzr, git-bzr and bzr-fastimport on my RPi.  What command do I run to download the git repo and convert it?

**Comment by qwertychouskie** [comment]
I ran: `cd /home/$USER/stk-code && git checkout && git fast-export -M --all --signed-tags=warn | (cd /var/www/stk-code-bzr-repo; bzr fast-import -)`

The results are at:
http://jacobspctuneup.tk/stk-code-bzr-repo/

Could someone set the Launchpad PPA to pull from this repo to see if it will work?  If so, I will add the command as a cron job.

If it works, **this will fix the problem.**

**Comment by qwertychouskie** [comment]
Also, the data at https://code.launchpad.net/~stk/stk/stk-assets will need to be updated.

**Comment by qwertychouskie** [comment]
The update of https://code.launchpad.net/%7Estk/stk/stk-assets is failing:

bzrlib.plugins.svn.errors.TextChecksumMismatch: checksum mismatch: '2ae3a88106aa221ba27a415eb84decbe' != '8af1f21f487f3cadacc3eb5a6ec3faf7' in stk-assets:16358

http://launchpadlibrarian.net/251414603/stk-stk-stk-assets.log

**Comment by qwertychouskie** [comment]
Any way to tell which file is asset 16358?

**Comment by qwertychouskie** [comment]
Found http://stackoverflow.com/questions/10352934/svn-checksum-mismatch-while-updating.  This may fix the problem.

**Comment by qwertychouskie** [comment]
Started a fresh test import: https://code.launchpad.net/~asdfghrbljzmkd/stk/trunk

**Comment by qwertychouskie** [comment]
The test import worked, https://code.launchpad.net/%7Estk/stk/stk-assets just needs a fresh import (delete imported files and re-import).

**Comment by konstin** [comment]
I'ld suggest you to request joining the stk-team on launchpad (https://launchpad.net/~stk). This should give you the privileges to make the required changes yourself. Once you updated the branches, the ppa will automatically be updated (You can find the recipe used for building at https://code.launchpad.net/~konstin/+recipe/stk-git-daily)

**Comment by deveee** [comment]
Could someone fix or disable it for now? Because I get messages about 
failed builds from launchpad every day.

W dniu 03.04.2016 o 13:06, konstin pisze:

**Comment by qwertychouskie** [comment]
Sorry about the emails, working on the fix.

**Comment by qwertychouskie** [comment]
Good news, got the `supertuxkart-data` package working, now for the binary...

**Comment by qwertychouskie** [comment]
I wasn't so far off with the sh script idea... the debian/rules file is run like an sh script!  The PPA should have a binary package soon...

**Comment by qwertychouskie** [comment]
fatal: unable to access 'https://github.com/supertuxkart/stk-code.git/': Could not resolve host: github.com
Can't seem to access the internet at that point...

**Comment by deveee** [comment]
@qwertychouskie Maybe try to make it working on private repository first? People started complaining about spamming their emails:
http://forum.freegamedev.net/viewtopic.php?f=17&t=6875&sid=e057221a7ed4e670e4a8ad60ab1c8bbc
We were translating STK on launchpad in the past and some people may still have there accounts.

**Comment by KroArtem** [comment]
Please do not use this repo as a testing one or restrict email notifications, it's very annoying to get bunches of these useless emails.

**Comment by KroArtem** [comment]
Thanks for your understanding, you damn idiot. Left the team, it's much easier than to wait for adequate reaction.
@auriamg , @hiker , you should raise your entry level requirements.

**Comment by auriamg** [comment]
Please make sure it works in a private repository first before doing any more builds in the official one. I've disabled automated builds for now, let's please only re-enable them when they're shown to work

**Comment by qwertychouskie** [comment]
Sorry about that, for some reason I thought creating a PPA for testing was way more complicated then it actually was, so it got low on my priority list.  There shouldn't be any problems now.

**Comment by qwertychouskie** [comment]
At this point, the plan is to have the 'supertuxkart' package contain a cron job to download and compile Supertuxkart automatically every so often.

**Comment by qwertychouskie** [comment]
The test version can be found at this PPA: https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test.  Any comments and suggestions are welcome.

**Comment by qwertychouskie** [comment]
Just updated:

Download zip instead of `git clone`
Check if version downloaded is newer than version installed, and exit if not
Change frequency to hourly

 Any comments and suggestions are very much wanted.

**Comment by qwertychouskie** [comment]
If no one objects, I will add the package to the official PPA.

**Comment by konstin** [comment]
I do object for two reasons:

First of all, you **really shouldn't** release a package that has to be compiled by the client. This Ubuntu and not Arch linux.

In addition to that, the installed version is broken because you're depending on supertuxkart-data without providing a matching version, so some . You should really provide all required packages for SuperTuxKart.

**Comment by qwertychouskie** [comment]
The `supertuxkart-data` package is already in https://launchpad.net/~stk/+archive/ubuntu/daily.  Also, compile-on-install seems to be the only way, unfortunately.  I personally would rather have a non-optimal package that works available than no package.

**Comment by konstin** [comment]
> The supertuxkart-data package is already in https://launchpad.net/~stk/+archive/ubuntu/daily.

ok, that does solves the first issue.

> Also, compile-on-install seems to be the only way, unfortunately.

Why? What's the problem with compiling everything once on a server and then putting the binary into the package?

**Comment by qwertychouskie** [comment]
Because of https://github.com/supertuxkart/stk-code/issues/1415#issuecomment-199188762 and https://github.com/supertuxkart/stk-code/issues/1415#issuecomment-199323092.

**Comment by qwertychouskie** [comment]
And I couldn't figure out how to https://github.com/supertuxkart/stk-code/issues/1415#issuecomment-199347524 either.

**Comment by qwertychouskie** [comment]
I committed another update (http://bazaar.launchpad.net/~stk/stk/stk-code-downloader-debdata/revision/51) to https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test, could I get an opinion?  If I get the OK, I will put the package in the PPA and change the first part of the PPA description to:

This PPA contains a package that, upon installation, downloads and compiles the latest version of Supertuxkart, and adds a cron job that checks for updates hourly and install them whenever they become available.  Note that due to limitations in the update script, it will download an approx. 35 MB file each check.  This PPA also contains daily builds of the supertuxkart-data package for SuperTuxKart, which contains the assets. These builds are for people who want or need the latest version of SuperTuxKart but don't want to compile it themselves.

**Comment by qwertychouskie** [comment]
In the meantime, I updated the official PPA's description to point to https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test.
