### ISSUE TITLE
Green valley in 0.8.1 in reverse mode has unexpected shortcut

### ISSUE THREAD

**Issue by cim--** [supertuxkart/stk-code#1428]
Drive around the track normally until you get to the bit with four bananas surrounding a box. Carry on through them but rather than turning right along the track, just head straight on up the hill, then keep going over the top, and you'll come out near the race start, at which point you'll get the lap complete notice as you head back down into the valley. Drive under the bridge, then turn left up the hill back on to the road, to continue the race.

**Comment by auriamg** [comment]
Fixed in svn
