### ISSUE TITLE
Manually added resolutions in options screen video

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1437]
In options_screen_video.cpp file there are three manually added resolutions:
800x600
1024x640
1024x768

This is not exactly true in some cases... For example my laptop and external monitor don't have 1024x640 resolution. I also had netbook which didn't have 1024x768 resolution.

I suggest to remove this part of code where they are added if not exist. They should be added by irrlicht anyway.

**Comment by Benau** [comment]
Now u can resize in option, and sdl2 is better than irrlicht for getting screen sizes?

**Comment by Alayan-stk-2** [comment]
Having those resolutions (1280x720 and 1024x768 are the two resolutions added manually) always available for windowed mode if the screen doesn't report them is actually quite useful. The possibility to resize manually windows is nice but it has also some disadvantages compared to getting a fixed resolution.

Removing the code adding these resolutions wouldn't simplify the codebase enough to be worth it.

The only thing that would justify their removal in my opinion would be a way for the user to type in a resolution, have it saved in config and get it added to the list of resolutions to pick from.
