### ISSUE TITLE
No particle effects (windows, hd3000)

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1476]
I don't get any particle effects (e.g. skidding, slip stream, zipper), even though I have animated scenery enabled.

**Comment by hiker** [comment]
OK, not sure which issue to reopen - I used #1808 , but if this is nitro only, it's indeed not urgent.

I just bisected, and:
9dcdd5342562b4d84145b388b4dbfe823df39a52 is the first bad commit
commit 9dcdd5342562b4d84145b388b4dbfe823df39a52
Author: Vincent Lejeune <vljn@ovi.com>
Date:   Fri Jan 23 01:00:05 2015 +0100

    Add advanced pipeline GR to hd3000

:040000 040000 357445951a6a0ded371c89dc479e2fe5d09e5f8f 820de68eaf116511ab9c111cc7fe7a4a7f5c30a2 M      data
:040000 040000 c6f0c7ef1ca3d3872f65c99d61c2359107327b4e 3a5b006a5c3adbc4c2b6b9f8b183f240067988e9 M      src

I'll have a look at that and update this ticket later.

**Comment by hiker** [comment]
OK, the bisecting gave wrong results because graphical options got changed during bisection (I assume due to changes in the graphical restriction). What I have atm:
beta1: particle affects if I enable advanced pipeline, no particle affects if the advanced pipeline is disabled (in any case I had scenery animated).
beta2:no particles in any case.
master: no particle effects

I also noticed in the graphical restriction that advanced pipeline for hd3000 on windows is disabled.Does this mean that advanced pipeline should not at all be selected with this card? I can still select it (even with a clean config file).
I can probably bisect the missing particles with the advanced pipeline, but since the skidding effects are essential for gameplay, we also need to find out the problem without advanced pipeline (I think, unless we can force the advanced pipeline on this platform).

**Comment by hiker** [comment]
Looks like the above bisect was actually correct. Reason is CentralVideoSettings::isDefferedEnabled(): 9dcdd5342562b4d84145b388b4dbfe823df39a52 changes this function to also not have advanced pipeline disabled in the graphical restriction, and it disables this setting for hd3000 on windows.

So my config setting for dynamic light is true, but the definition in graphical restrictions is disabled, causing isDefferedEnabled() now to return false (--> no particle) instead of yes (particles).
And if I change isDeferredEnabled() to always return true, particles work (obviously independent of advanced pipeline being disabled or not).

**Comment by hiker** [comment]
So far I only had particles working because I was using the advanced pipeline (which would crash on cocoa). So we need to fix the non-advanced pipeline particles.

**Comment by hiker** [comment]
The following line causes the particles not to work when I disable advanced pipeline:
````C++
        if (!CVS->isDefferedEnabled())
            glEnable(GL_FRAMEBUFFER_SRGB);
````
If I use if(0), I get particles. But:
- the tracks are dark (inside of pyramid basically black)
- the skidding effect appears to be a bit too far behind the kart and too low:
![farm-2015 02 17_23 42 28](https://cloud.githubusercontent.com/assets/6138652/6228401/97589538-b6ff-11e4-940d-7499f7918dde.png)
- in cocoa and Paradiso the effects were so far behind that I actually couldn't see them at all.
- interestingly, #1914 also goes away - the tracks stay the same dark all the time.
@vlj does this help?

**Comment by hiker** [comment]
This is a 'minimal' patch to fix the issue for me (adding a glEnable/glDisable):
```
diff --git a/src/graphics/glwrap.cpp b/src/graphics/glwrap.cpp
index 842ca1c..876b10f 100644
--- a/src/graphics/glwrap.cpp
+++ b/src/graphics/glwrap.cpp
@@ -227,6 +227,7 @@ FrameBuffer::~FrameBuffer()

 void FrameBuffer::Bind()
 {
+    glDisable(GL_FRAMEBUFFER_SRGB);
     glBindFramebuffer(GL_FRAMEBUFFER, fbo);
     glViewport(0, 0, (int)width, (int)height);
     GLenum bufs[] = { GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1, GL_COLOR_ATTACHMENT2 };
diff --git a/src/graphics/render.cpp b/src/graphics/render.cpp
index 40e3986..7c1f832 100644
--- a/src/graphics/render.cpp
+++ b/src/graphics/render.cpp
@@ -383,6 +383,7 @@ void IrrDriver::renderScene(scene::ICameraSceneNode * const camnode, unsigned po
       // We need a cleared depth buffer for some effect (eg particles depth blending)
       m_rtts->getFBO(FBO_NORMAL_AND_DEPTHS).Bind();
       glClear(GL_DEPTH_BUFFER_BIT);
+      glEnable(GL_FRAMEBUFFER_SRGB);
       glBindFramebuffer(GL_FRAMEBUFFER, 0);
     }
```
Minimal means: if I move the glDisable one statement down (after glBindFramebuffer), I don't get particles. Without the glEnable, the inner of the pyramid is black. If I move the glEnble up (before glClear) - nothing is shown except the start screen, and stk appears to hang.

@vlj : I would suggest to add this as a graphical restriction - let me know if you have a better idea.The 'screen darker before ready' bug is still present with this work around.

**Comment by vlj** [comment]
Why not addind glDisable(GL_FRAMEBUFFER_SRGB); before m_rtts->getFBO(FBO_NORMAL_AND_DEPTHS).Bind(); ?
Putting it Inside FrameBuffer::Bind is likely to break Advanced pipeline.

**Comment by hiker** [comment]
Yes, of course it will go one level up (not in Bind) - I should have mentioned that. I just moved it there to find the exact statement that causes the problem, in case it rings a bell :)
