### ISSUE TITLE
Really unlucky gift box misplacement in Minigolf track

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#1494]
The Minigolf track has a stupid design flaw / bug:

It is possible that one of the karts is able to collect a gift box even before the race has started.
The bug becomes visible if you start a race with 20 karts on Minigolf (forward) and you are on position 20 (as usual). One of the karts is in a very lucky position where it collects a gift box at the very beginning …

There is another box annoyingly near the start, but it is not auto-collected.

I am talking about those two gift boxes which are left of the minigolf hole, when facing into track direction.

I think these two gift boxes should either be removed or placed somewhere else.

**Comment by Wuzzy2** [comment]
Since the Minigolf track has been updated, here are some news for you:

In version 0.9, the forward direction does not look so seriously bad anymore, but in the backwards direction, I see some power-ups “conveniently” placed between all these (20) karts.

**Comment by auriamg** [comment]
Fixed in svn
