### ISSUE TITLE
Licenses to check

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1512]
1) Check  http://supertuxkart.sourceforge.net/Supertuxkart:Copyrights (as requested by Konstin)
2) We also need to check the licenses of the dependency packages.

**Comment by Benau** [comment]
license file for freetype:

http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/docs/FTL.TXT

we need to add freetype website in https://github.com/supertuxkart/dependencies/blob/master/windows/sources too

**Comment by hiker** [comment]
Dependency package information was updated with freetype license and url, so am closing this ticket.
