### ISSUE TITLE
Please install the supplied AppData file

### ISSUE THREAD

**Issue by hughsie** [supertuxkart/stk-code#1545]
Please consider installing this AppData file: https://raw.githubusercontent.com/hughsie/fedora-appstream/master/appdata-extra/desktop/supertuxkart.appdata.xml

This is used in GNOME and KDE software installers to add the application description and some screenshots. We'd love to showcase more applications, but without the extra data file we can't. The AppData file needs to be installed to /usr/share/appdata/ on Linux and the basename needs to match the .desktop basename. It would also be great if you could integrate the file with your translation system (e.g. intltool) to make the descriptions translated.

See http://people.freedesktop.org/~hughsient/appdata/ for more details; thanks!

Richard

**Comment by qwertychouskie** [comment]
Screenshots are already available: http://supertuxkart.sourceforge.net/, see side.  Although they are for 0.9.1, there were not a lot of visual changes between 0.9.1 and 0.9.2.  Will create a PR.
