### ISSUE TITLE
Flames from nitro bottles are still rendered after using swapper

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1550]
![](http://img42.com/lP8vM+)

**Comment by auriamg** [comment]
Can you still reprouce this? I am unable to reproduce, it may have been fixed

**Comment by stkAnon** [comment]
It seems to be fixed in 0.9.1.

IIRC someone also mentioned fixing it on IRC some months ago.

**Comment by auriamg** [comment]
CLosing as fixed, please reopen if it still happens
