### ISSUE TITLE
Twisted crescent crossing ghost

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#157]
**Author: auria**

The ghost of crescent crossing, when seen in STK, is not quite as seen in blender, it's kind of twisted

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/101

**Comment by auriamg** [comment]
We no longer have that ghost. We can reopen it if we ever meet this issue again, but the new way of doing things with library objects should make it a lot easier to avoid the weird edge cases anyway.
