### ISSUE TITLE
gameplay minor problems and boost calibration

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1574]
Since we have karts with different parameters we should reduce slightly the average speed for intermediate, expert and supertux difficulties.

With the fastest kart and the fastest difficulty IMHO it's a bit too fast and too much difficult to control the kart.

Also since I'm starting to calibrate booster in chocolate I have many difficulties to find a good value that work well for all difficulties.

I suggest to add 2 different parameters (one for easy + intermediate and one for expert + supertux difficulties).

**Comment by Alayan-stk-2** [comment]
Min-speed works well for ground-zippers which need to guarantee a minimum speed to get across the gap (of course, it should be tested with a light novice kart staring at 0 speed just before the zipper, as once the min-speed is reached, different karts will accelerate differently until they leave the zipper texture).

As for changing the speeds of some difficulties, this is something very contentious - some wish it slower, while some wish it faster (if not [much faster](https://www.youtube.com/watch?v=8MEG6dgGNKU)...) - generally along the lines of "This is too hard" or "This is too easy/boring" (each time "for me"). And nobody has hard data on what is used to support their preference. Expanding the ranges of available speeds is already unlikely, but shrinking it just wouldn't happen without much outcry and dissatisfaction.

So, closing.
