### ISSUE TITLE
God rays effect works only first time

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1578]
As in title. When I start the track first time, everything is ok. When I return to menu and start it second time, effect doesn't work.

Here are the screenshots:
![zrzut ekranu z 2014-09-27 20 44 00](https://cloud.githubusercontent.com/assets/5108558/4431770/8125def4-4677-11e4-89e3-c38fd1063cff.png)
![zrzut ekranu z 2014-09-27 20 44 17](https://cloud.githubusercontent.com/assets/5108558/4431769/8122b6e8-4677-11e4-9fe0-c41bb8ef3747.png)

I also noticed that god rays effect doesn't work in multiplayer game at all.

deve@deve:~$ optirun glxinfo | grep Open
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 635M/PCIe/SSE2
OpenGL core profile version string: 4.3.0 NVIDIA 331.89
OpenGL core profile shading language version string: 4.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.4.0 NVIDIA 331.89
OpenGL shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:

**Comment by deveee** [comment]
Actually it works, but it has much less power when you run it second time. Easy to see in Farm track.
First time it works:
![zrzut ekranu z 2015-01-14 19 08 20](https://cloud.githubusercontent.com/assets/5108558/5744422/ff1d5edc-9c20-11e4-958b-9b58d93fbede.png)
Second time sun is barely visible:
![zrzut ekranu z 2015-01-14 19 08 46](https://cloud.githubusercontent.com/assets/5108558/5744423/ff2170bc-9c20-11e4-9f87-e9da2ab4ad8c.png)

**Comment by auriamg** [comment]
Vlj has recently pushed a fix, can you confirm if this is fixed?

**Comment by deveee** [comment]
Fixed.
