### ISSUE TITLE
Entered names not showing up while registering and creating user

### ISSUE THREAD

**Issue by shantanusingh10** [supertuxkart/stk-code#1591]
While making account I entered my username but the entered name was not coming up on the screen just complete blank . I think the problem is only with the on screen issues because it is comparing the emails that I wrote(without showing)  .  

![image](https://cloud.githubusercontent.com/assets/6254324/4478196/9cab1e14-4983-11e4-8694-73ab7a84b49f.png)

**Comment by Benau** [comment]
Try to change setting of non-Unicode programs in win8 to match the input method language, then see if the correct chars can be displayed? (like in #2112?)

**Comment by voronamanga** [comment]
Hi, I just installed the last release of STK in W10 on my laptop Asus X751L (graphic cd Nvidia Geforce 940M) and got the same issue. I worked around by copy/paste ; I don't know how to changeinput method language, and by the way, I'm not sure it would fix the problem since I'm using a classic french AZERTY keyboard.

**Comment by Benau** [comment]
Did you try to enter french with your keyboard?

**Comment by voronamanga** [comment]
Sorry for my late answer. My keyboard input is in French. I had'nt understood at once what was input method language but now OK, in fact I just do it usually. I wanted to try to add another user to STK just to check the input (in French or English) but on the dialog page which is displayed for that, there is no problem with text fields, so... it was a fleeting issue ...

**Comment by Benau** [comment]
Hi, stk rc 0.9.2 has just been releaaed, can you give that a try? It should have better internationalization support.

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/

**Comment by voronamanga** [comment]
Till now I have switched language to English in W10 (I had to learn how to do, most of the time I'm on Ubuntu) and noticed that I could enter characters in the text fields of the "add user" page (which was impossible in French).

Now I'm gonna download 0.9.2 and try the same thing with the French keyboard map.

**Comment by voronamanga** [comment]
Sorry, the problem remains the same. Moreover, the name of your own kart appears in oriental fonts, maybe Japanese or Chinese.

**Comment by auriamg** [comment]
If you see chinese where unexpected, could you please give us more info? That may be a seperate bug

**Comment by Benau** [comment]
I try to reproduce by changing win8 language to french and using a awerty on-screen keyboard, but seems to work fine for me
![test](https://cloud.githubusercontent.com/assets/3252341/16140420/e19c16f4-3482-11e6-847e-a942a59e35b5.jpg)

Regarding "oriental fonts" you see, do you see the character "쳌"?
http://www.unicodemap.org/details/0xCCCC/index.html

**Comment by voronamanga** [comment]
It's not this character ; the best thing is to provide you with screenshots, you will find them attached. In second and third screen I am unable to enter any character.
![stk1](https://cloud.githubusercontent.com/assets/18719592/16148950/3c9ef88a-349e-11e6-8531-138477ad0262.png)
![stk2](https://cloud.githubusercontent.com/assets/18719592/16148954/43c74a86-349e-11e6-852a-83ab0683474b.png)
![stk3](https://cloud.githubusercontent.com/assets/18719592/16148961/50339108-349e-11e6-880c-f94deffba1f0.png)
![stk4](https://cloud.githubus
![stk5](https://cloud.githubusercontent.com/assets/18719592/16149101/6168b984-349f-11e6-9d03-c1b6dce18cc9.png)
ercontent.com/assets/18719592/16148964/543cb39c-349e-11e6-8890-9abe74019fb9.png)

**Comment by Benau** [comment]
... I am unable to enter any character:

Did you try to enter "Vorona" and the in text field box, it showed empty / chinese-like words instead?

**Comment by voronamanga** [comment]
"Vorona" is already there (I entered it at first launch by copy/pase from a text editor) and I can't neither change it or enter password, typing has simply no effect ; the same in the following screen. So yes it shows empty (or impossible to edit for "Vorona"), instead of "chinese-like" characters.

**Comment by auriamg** [comment]
I tested with a french keyboard layout on Windows 10, I am unable to reproduce, everything works correctly for me

**Comment by voronamanga** [comment]
I am unfortunately unable not to reproduce, and not skilled enough to have the least idea about where it comes from !

**Comment by Benau** [comment]
Can u try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20190629/supertuxkart-win-git20190629.zip/download

And see if it should work for you (Now stk is more unicode friendly for windows)...

**Comment by qiuyifengs** [comment]
Rrrrrr

**Comment by Benau** [comment]
outdated after sdl2 is used ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif)
