### ISSUE TITLE
GP editor displays GP list differently after changing dialog

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-code#1610]
In chronological order, the intresting differnce between the GP list in the first andd thir picture:
![1](https://cloud.githubusercontent.com/assets/6826232/4579225/0caf476a-4fcb-11e4-962d-70015835ea85.png)
![2](https://cloud.githubusercontent.com/assets/6826232/4579304/b7045bf6-4fcb-11e4-86b1-958e7166186b.png)
![3](https://cloud.githubusercontent.com/assets/6826232/4579320/d4e41512-4fcb-11e4-84b4-3613ae47231f.png)

**Comment by deveee** [comment]
When tracks count didn't change it always displays the same number of rows. When tracks count has changed, it computes new best number of rows. It wasn't able to display all 5 GPs and it decided that better to show you bigger screenshots :) So it IMO works as it should.
