### ISSUE TITLE
Particle corruption in old pipeline

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#1647]
The issue goes away if I enable Advanced Pipeline in graphics options, but due to #1639 I can't use the advanced pipeline.
![particle_corruption](https://cloud.githubusercontent.com/assets/5515261/4834644/9ece5e62-5faf-11e4-9ec1-cb95e082224a.jpg)

**Comment by hiker** [comment]
Is this still an issue with our second beta?

**Comment by Flakebi** [comment]
Yes

**Comment by Flakebi** [comment]
I think that's fixed now @Arthur-D can you confirm please?

**Comment by auriamg** [comment]
Confirmed fixed by Arthur
