### ISSUE TITLE
Getting two copy of an item

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1664]
Basically, having the possibility to get say 2 bowling balls or 2 zippers or... in addition of 1 & 3.
That's not a definitive suggestion, more a thought which may be (or not) a good idea.

Forum thread : http://forum.freegamedev.net/viewtopic.php?f=18&t=5956&p=60684#p60684

**Comment by deveee** [comment]
In STK you get 1 or 3 objects by design and I don't see any reason to change it.

**Comment by Alayan-stk-2** [comment]
Done in the Evolution branch with https://github.com/supertuxkart/stk-code/commit/c6868aefc7124955ee469071a90ba1e290388bae
