### ISSUE TITLE
Finer-grained items weight list

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1667]
The priority is moderate ; that's in background and is taken as a given by most players, but it has direct influence on global balance

Add finer-grained items weights list so weights will be adapted no matter the number of karts. Include adding a new position_class for finer-grained weights with high number of karts.
Should be flexible enough so the number of divisions and their range (for kart numbers, e.g. 16 to 20 karts)  would be 100% in powerup.xml, making thus future maintaining easier.

Actual values for powerup.xml will then have to be determined with help of several tests, making sure it works well on the various tracks.
Focus will be given to something working well on SuperTux difficulty, with the assumption it will work correctly for lower ones (some tests to confirm this will be needed). Adding per difficulty weights would be obviously overkill.

**Comment by deveee** [comment]
@Alayan-stk suggests also separate items weight list for Follow the leader mode:
https://github.com/supertuxkart/stk-code/issues/1688
