### ISSUE TITLE
emit map

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1668]
Currently stk solid shader is almost complete :). We have specular/glossy +IBL etc.
It's awesome but we need something more, an emit map.

Red chan = specular map
Green chan = gloss map
Blue chan = emit map

An emit map is used to simulate a surface that is lit by a light. Currently I use a strong light source just near an object that need to be lit. The problem with that is for some little objects it's overkill in light (like a TV screen) and if we are too far, the light might be switch off because it won't included in the 16 lights near the player.

If we do a mansion for instance it would be nice to have some strange lights in the distant. If it's made with an emit map, they will be always lit and cost "almost nothing" to the render.

**Comment by Benau** [comment]
Now we use PBR / texture slot, so not necessary anymore
