### ISSUE TITLE
Ruler not adapted to reverse in Oliver's math class

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1673]
There is one ruler on which you should be able to go to then gather powerups you just can't because it kept its thickness.

Otherwise, the first ruler needs to turn too quickly in normal mode to go on it. Its height is maybe also too big to make it reallisticaly accessible in race ; may be fun for nitro gathering challenge still.
The second has 2 nitro but only the first can be gathered if you go at a good speed (may be considered as a bug that items/nitro aren't gathered if you go through them but not touching what they are on)

**Comment by deveee** [comment]
This is subjective. You are not able to collect one nitro in the track when driving in reverse, but you have more interesting and better looking object, from which you can jump. It doesn't prevent you to drive this track in reverse.
