### ISSUE TITLE
Rescued karts appears in middle of road without any warning

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1675]
This causes karts behind to bump them and lose all their speed. There is no way to avoid that except knowing where rescued tracks may be released and avoid that part of road (not practically doable, and won't stop AI to be tricked with that)
I took a look on MK to see how it is managed, and there the rescue animation happens over the road with a little time before the rescued kart is released; In STK, the rescue animation is done where thunderbird rescue the kart, and then it appears instantly on the road.

**Comment by auriamg** [comment]
A fix for this was merged
