### ISSUE TITLE
Cup and race page display the cup icon

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#168]
**Author: guillemin**

The problem is that the user will think they won the cup because of that icon which is also used in the challenges place for won challenges. Races and Cups titles already display information about what is a cup and what is a race.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/112

**Comment by auriamg** [comment]
Closing as outdated, I have no idea what this is about. The challenges have been improved a lot since 2014 so presumably this is outdated
