### ISSUE TITLE
Library object geometry stretched with AoMap enabled

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1691]
This is supposed to be a fighter jet.

![](https://cloud.githubusercontent.com/assets/8258259/4985950/2ad6b51c-6933-11e4-8e1d-7ae3c3116180.png)

It only renders like this when I have an UV layer in Blender called "AoMap", to which I've assigned an ambient occlusion map.

[Here](https://drive.google.com/file/d/0B5y5RxsQIjSWbGljSEs2Zk16dTg/view?usp=sharing)'s the source file to the library object. Let me know if more files, such as the track or exported library object folder, are needed.

**Comment by qwertychouskie** [comment]
AO is rendered in real-time now, can this be closed?
