### ISSUE TITLE
Improving GP points distribution

### ISSUE THREAD

**Issue by Alayan-stk** [supertuxkart/stk-code#1699]
The current version define how much difference in points there is between positions in a given range (e.g. ; with the actual stk_config, first and 2nd have 3 points more than the next ; 3rd and 4th 2 points more than the next, and then 1)
That system is really limited. It gives ugly numbers with very few karts, but more importantly there is no way to tweak the values to have something that works well with all kart numbers. Atm, with 20 karts, doing 5th and 20th is rewarded the same way than 12th and 13th which is wrong (only the very few better place have a decent extra). However something working with 20 would likely be bad with 10.

So the deal is more or less to limit the tweaking possibilities in stk_config to be able to have a good default system adapted for all values. Having raw data for each possible number of karts would be overkill imo.

I did a table with the goal of promoting good performance. e.g. ; 5th and 20th rewards one point more than 10th + 11th and 50% more than 12th + 13th so the 5th place has a true bonus. 1st/2nd seems to be a bit less helped than before but that is mostly a contrast effect.
The table is adapted for all kart numbers and could even be expanded up to 30 karts without issue. Simple formulas allow to describe it.
![image](https://cloud.githubusercontent.com/assets/9522948/5019457/124da7e2-6ac0-11e4-8a0e-484cd9748373.png)

**Comment by Alayan-stk-2** [comment]
Fixed with #2765
