### ISSUE TITLE
shader clean up

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1702]
It seems that some shader present in the shader folder are old shader and/or aren't used anymore.
We should remove them because I just lost 1h trying to tweak an unused shader :o 

Since I'm not the shader guy, vlj please can you quickly review what do we need to keep and what can be removed :)

Thank you

**Comment by vlj** [comment]
I think the only shader unused now is skinning.vert but it will be used later. Otherwise all shaders are used.
