### ISSUE TITLE
Only wheels visible in some parts of some tracks

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#1710]
This is a bug I noticed with cocoa, the bodys of the karts seem to disappear sometimes. I cannot tell why this happens or under what circumstances, though. Tried with fullscreen and windowed mode and I think they're the same.

**Comment by qwertychouskie** [comment]
Is this still an issue?

**Comment by auriamg** [comment]
The old pipeline is no longer used, so closing as outdated
