### ISSUE TITLE
Why specular gloss was changed ?

### ISSUE THREAD

**Issue by MatthewsSam** [supertuxkart/stk-code#1730]
I had several issues with my HDD but thankfully everything is now recovered.
I also updated ubuntu and I discovered that the glossiness was different. At first I thought it was a NVIDIA driver issue but after a while I realized that stk way of using the glossmap was different
![screenshot - 21 11 2014 - 12 22 44](https://cloud.githubusercontent.com/assets/6406045/5141758/a349b24e-7179-11e4-887a-5c490d556f3e.jpg)

This isn't really an issue but a question. I spend COUNTLESS HOURS trying to tweak the glossiness of each new material (like the metal, mud, rocks, etc). Making a good looking glossmap isn't trivial especially when you have noway of preview what you are doing except by loading the whole game. You can't just adjust the slider and check the result. It's a long process. Behind each gloss map there is around 15min of adjustments etc. 

The gloss now seems way too sharp. Everything looks like shiny metal surface. I'm worried because this mean for me; keeping it like or redoing each glossmap one by one. Considering we are close to the beta I would prefer to spend my time on things more interesting than adjusting something that was already perfectly working.

Why the formula was changed ? Is there any good reason of changing that ? Isn't another way of doing it ?
I'm not sure if I have the motivation of redoing each glossmap just because one formula was changed. It's easy to change the formula, but tweaking again each glossmap is a long process.

Sam

**Comment by CodingJellyfish** [comment]
I'm sorry samuncle. The old STK BRDF shader is unbearably inaccurate. To prepare for 2.0, the shader would be changed before 1.5, and all gloss would look different.
