### ISSUE TITLE
Textures too dark w/ splatting if both UVMaps are identical

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1732]
![untitled](https://cloud.githubusercontent.com/assets/8258259/5152089/7b752abc-719e-11e4-90eb-dba327995393.png)
![untitled2](https://cloud.githubusercontent.com/assets/8258259/5152091/7b7833ce-719e-11e4-923c-5ada0a93195d.png)
![untitled3](https://cloud.githubusercontent.com/assets/8258259/5152090/7b768a6a-719e-11e4-955f-076cce010299.png)

The resulting image seems to be the original texture normalized to 1 and multiplied by itself.

As a result, it should be possible to work around this for now by making one of the textures pure white or by simply not assigning it.

**Comment by Benau** [comment]
Probably srgb issue, please make sure same texture is not assigned to both sampling srgb / non-srgb in sps_*.xml
