### ISSUE TITLE
Multiplayer graphic bugs

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1734]
I encountered these bugs (with the old pipeline):
* The speedometer gets filled wrongly (the first car moves in the screenshot, the second car changes nothing)
* When the first kart moves, the skybox rotates (only for the first kart, the second isn't affected)
![stk3](https://cloud.githubusercontent.com/assets/6499211/5154554/85f2bbd2-7264-11e4-8ba8-67f207cdd727.png)

**Comment by hiker** [comment]
Done on request of Seebi

**Comment by hiker** [comment]
Is this still an issue with our second beta?

**Comment by Flakebi** [comment]
Yes, the skybox is still rotating when the kart moves on the top half, the bottom half works ok.

**Comment by Flakebi** [comment]
It's fixed now.
