### ISSUE TITLE
Font: Question mark looks different

### ISSUE THREAD

**Issue by krobonil** [supertuxkart/stk-code#1736]
In some languages a question mark comes in the start-sequence.
For ex. in German there is a "Fertig?" for "Set!"

Unfortunately it doesn't fit to the rest of the text
Solution: Change size, replace or remove

![bildschirmfoto](https://cloud.githubusercontent.com/assets/9907631/5156208/6087b2e6-72b2-11e4-82d7-5c156dd6507a.png)

**Comment by auriamg** [comment]
This should be better now that the freetype branch has been merged
