### ISSUE TITLE
Track exporter only exports four decimals for Y-speed of animated textures

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1740]
The track exporter will clip off any digits after the ten thousandths place when saving the "dy" property for objects with animated textures, making it necessary to edit scene.xml by hand for some animation frame counts.

**Comment by Benau** [comment]
auria do you really need more digit?

it internally use half-float in shader (see texture_trans), so it's 2^-10 (which is 1 / 1024) fixed interval.

if you really need more we can use normalized short which is 1 / 32728, otherwise i don't think this ticket has a sense.

**Comment by Benau** [comment]
actually in c3d0db9 I changed it to normalized short, so the smallest next-update will be (-)1 / 32767

This make the "flight board" in gran island as smooth as before

and  (-)1 / 32767 will always be the minimum digit, otherwise we need more bytes per-instanced data

**Comment by stkAnon** [comment]
For the record, requiring five decimal digits was due to a use case where I used the per-frame offset of a texture to do flipbook-style animation across a spritesheet. So when it truncated the last digits, the offsets no longer added up to a whole multiple of the spritesheet's length, and the animated features appeared to glide and wrap across the geometry when they should have been staying still.

**Comment by auriamg** [comment]
@stkAnon I have tweaked the exporter in svn to export a few more decimals, this should hopefully help a bit
