### ISSUE TITLE
Graphical issues on osx, gt 120

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1748]
I compiled stk on osx 10.9.5 with an nvidia gt120, 256 MB (advanced shaders disabled). Most tracks look like this:

![screen shot 2014-11-25 at 11 42 13 pm](https://cloud.githubusercontent.com/assets/6138652/5200664/2f364f7e-75bc-11e4-989c-ab6233637eb9.png)
One exception was math class, which looked fine (except for a 'pink-ish' tint now and again).
The only problem in stdout.log I noticed:

```
[debug  ] translation: Env var LANGUAGE = 'en_AU.UTF-8'.
[debug  ] translation: Language 'English (Australia)'.
[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: NVIDIA GeForce GT 120 OpenGL Engine
[info   ] IrrDriver: OpenGL version string: 3.3 NVIDIA-8.24.16 310.90.9.05f01
[info   ] irr_driver: GLSL supported.
```

Not sure which shaders they are (internal to irrlicht?) - 'our'  shaders later do not show any probem.

**Comment by qwertychouskie** [comment]
Is this still an issue with 0.9.2?
