### ISSUE TITLE
Ambient Occlusion artifacts on Intel HD4000

### ISSUE THREAD

**Issue by matthewharvey** [supertuxkart/stk-code#1751]
Turning on Ambient Occlusion causes the following artifact:
![ambientocclusionissue](https://cloud.githubusercontent.com/assets/1594441/5226070/94b6069e-76b8-11e4-9120-b0502095a20e.png)

I'm assuming that those artifacts underneath the kart and at the upward edges of the road aren't supposed to be there.

The console continuously prints the following lines while this is going on:
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawElements(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)

This is on an Intel HD4000 using the latest code and assets. I tried it on both a 'next gen' and a 'standard' track with the same result in both. I also tried turning other graphics features on and off, but the only thing that seemed to affect the artifacts was Ambient Occlusion.

**Comment by hiker** [comment]
Is this still an issue in our second beta?

**Comment by matthewharvey** [comment]
Instead of testing with the beta, I tested against the latest code. Let me know if you think it's relevant to use the beta package instead. Also, I tested it on both the latest code and the 10.3.2 release of Mesa, with the same results on each.

It's not as pronounced anymore, but it's still obvious and distracting.
![screenshot from 2015-02-05 00 51 36](https://cloud.githubusercontent.com/assets/1594441/6055642/6eff94c0-acd1-11e4-8225-c3491a72bbef.png)

Also, I've noticed that it is highly dependent on camera distance. When the camera is far away from the kart, it disappears totally, and as the camera comes closer it becomes more pronounced. This is true for the artifacts under the kart and the ones that sometimes appear on other objects.

**Comment by hiker** [comment]
@vlj any ideas?

**Comment by auriamg** [comment]
Can you please test if it still happens with STK 0.9.1? There have been quite a few fixes since that issue was created

**Comment by matthewharvey** [comment]
![screenshot from 2015-10-20 20-10-22](https://cloud.githubusercontent.com/assets/1594441/10624618/4a27e9ba-7768-11e5-90f9-806b4282bb25.png)

Latest code, latest mesa git code.

I've still been seeing it for a while, but it seems to have turned black to kind of look like a shadow. Unfortunately, I have shadows turned off and it gets lighter the further away the camera is from the kart, so I'm pretty sure it isn't supposed to be there. With ambient occlusion turned off, it goes away.

This admittedly isn't that big an issue, but it is definitely still an issue.

In the interest of completeness, here is the stdout from a race with AO enabled. Also, before that huge long thing runs off into the distance, I want to say how clear it is that so much work has gone into this game. It's a huge step forward from what it was just a year ago, and the entire community should be proud.

[verbose  ] main: Error messages and other text output will be logged to /home/matto/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: '../data/'
[info   ] [FileManager]: Data files will be fetched from: '../data/../../stk-assets/'
[info   ] [FileManager]: User directory is '/home/matto/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/matto/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/matto/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/matto/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../data/shaders/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../data/skins/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../data/ttf/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.utf8'.
[verbose  ] translation: Language 'English (United States)'.
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
Adding language fallback en
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
Irrlicht Engine version 1.8.0
Linux 4.1.0-2-amd64 #1 SMP Debian 4.1.6-1 (2015-08-23) x86_64
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

Mesa: User error: GL_INVALID_ENUM in glGetString(GL_EXTENSIONS)
Mesa: User error: GL_INVALID_ENUM in glHint(target)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
Mesa: User error: GL_INVALID_ENUM in glGetString
[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


Mesa: User error: GL_INVALID_OPERATION in unsupported function called (unsupported extension or deprecated function?)
[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Ivybridge Mobile 
[info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 11.1.0-devel (git-876d07d)
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: ARB Multi Draw Indirect Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] irr_driver: GLSL supported.
[info   ] Freetype Environment: Successfully loaded all fonts.
[info   ] ScalableFont::loadTTF: Created 13 glyphs supporting 15 characters for high-res digits font Sigmar at 28 dpi using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 91 glyphs supporting 148 characters for bold title font Ubuntu at 25 dpi using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu at 19 dpi using 1 glyph page(s).
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : texturedquad.frag
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : uniformcolortexturedquad.frag
[info   ] shader: Compiling shader : colortexturedquad.vert
[info   ] shader: Compiling shader : colortexturedquad.frag
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
[info   ] GrandPrixManager: Loading Grand Prix files from ../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/matto/.local/share/supertuxkart/grandprix/
[info   ] addons: Using cached addons.xml.
[info   ] ClientNetworkManager: Host initialized.
[info   ] ClientNetworkManager: Ready !
[info   ] shader: Compiling shader : coloredquad.vert
[info   ] shader: Compiling shader : coloredquad.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : object_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : normalmap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_object_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_normalmap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/DiffuseIBL.frag
[info   ] shader: Compiling shader : utils/SpecularIBL.frag
[info   ] shader: Compiling shader : IBL.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/SunMRP.frag
[info   ] shader: Compiling shader : sunlight.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlight.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : linearizedepth.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : ssao.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : bilateralH.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : bilateralV.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : object_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : objectref_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : object_unlit.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : splatting.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : objectpass_spheremap.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : detailed_object_pass2.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_objectref_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : instanced_object_unlit.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : instanced_objectpass_spheremap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_detailed_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : glow_object.vert
[info   ] shader: Compiling shader : glow_object.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : glow.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : passthrough.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : tonemap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_color1.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_blend2.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_neigh3.frag
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[verbose  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'redwhite.png'
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : importance_sampling_specular.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : fog.frag
[info   ] shader: Compiling shader : sky.vert
[info   ] shader: Compiling shader : sky.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlightscatter.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : gaussian6v.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : gaussian6h.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparentfog.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : bloom.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : bloomblend.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : lensblend.frag
[info   ] shader: Compiling shader : pointemitter.vert
[info   ] shader: Compiling shader : particle.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : particle.frag
[info   ] shader: Compiling shader : primitive2dlist.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : motion_blur.frag
[info   ] This work was NOT networked: This is NOT a network world.
[info   ] Singleton: Destroyed singleton.
[info   ] Freetype Environment: Successfully destroy all fonts.
[info   ] STKHost: Listening has been stopped
[info   ] Singleton: Destroyed singleton.
[warn   ] STKHost: Packet logging file has been closed.
[info   ] Singleton: Destroyed singleton.

**Comment by deveee** [comment]
This is still an issue. I was looking at this recetly, but I found also this issue: https://github.com/supertuxkart/stk-code/issues/2403. I will try to find the reason.

**Comment by deveee** [comment]
Should be fixed in this commit: https://github.com/supertuxkart/stk-code/commit/cdae5957244c3624497f27e587fd36ae2bd91399

**Comment by matthewharvey** [comment]
Yep. Fixed for me.
