### ISSUE TITLE
Strange flash during skidding

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1755]
Here is another strange annoying bug :P.

Sometime during races there is a little flash. It's maybe one or two frame that are actually different compared to "regular frame". It's very difficult to see what is it exactly (trying to slow down the FPS result in a white screen).

It seems caused by shadows. Sometime the game starts without any problem sometime there is this flash. It's very disturbing while racing and very annoying. 
To trigger this problem you have to skid. Once you start skidding (pressing v + turning) the bug appears. It doesn't seems to appear otherwise
I tried to take a video of the problem. You can see it here: https://drive.google.com/file/d/0B9jjDvqB8YxFQ3J4YjhYczV4c28/view?usp=sharing

Here is a detailed picture by picture view of the mysterious problem
![screenshot - 30 11 2014 - 23 08 43](https://cloud.githubusercontent.com/assets/6406045/5239570/4ca77362-78e6-11e4-8d78-8297ae28f7f4.jpg)

This isn't sure but the bug might be related to another strange artifact. Sometime when I start stk I have the shadows bugged and the first cascade that fails and other that are 100% black. 
A screenshot of the problem: https://i.imgur.com/jfiMIka.jpg

The configuration of the computer: 
OS: Xubuntu Utopic Unicorn 64 bits
Supertuxkart: master last version
GPU: Nvidia GTX 660
Driver: 340.58

**Comment by deveee** [comment]
Similar problem with shadows was fixed some time ago.

**Comment by vlj** [comment]
Looks like no one complained about it for a while, closing
