### ISSUE TITLE
Priority track tasks

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#1757]
* Use the new music contributed on the forum for the island track
* There is a hole at the entrance of STK enterprise
* Close the holes in Cocoa Temple
* Make houses and barrels physical in Cocoa Temple
* Build the new mansion track into an acceptable state, or delay it until next release

**Comment by hiker** [comment]
Enterprise should have its own directory name, not use star track.

**Comment by samuncle** [comment]
Update:
Remaining tasks (for rc)
* Polish up the beach
* Add reset area where there is water

**Comment by Flakebi** [comment]
I want to add some more things in cocoa:
- Make hay bales and lanterns solid
- Most of the environment at the beginning of the temple isn't solid (that's maybe related to reset areas)
- There are two missing planes inside the temple

![stk_plane](https://cloud.githubusercontent.com/assets/6499211/6338292/1cb08954-bbae-11e4-943f-d1cd14514fac.png)

**Comment by samuncle** [comment]
The planes are now corrected. The only thing missing is probably the reset stuff

**Comment by samuncle** [comment]
Reset plane now are working
