### ISSUE TITLE
Reducing the amount of options in the exporter

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1760]
Hi

I'm making the track maker guide 2 and while I was checking what kind of object we have I think we have too much.

I took a screenshot
![biglist](https://cloud.githubusercontent.com/assets/6406045/5290178/e63660fa-7b44-11e4-83bc-9f658d89d7f0.jpg)
That's a lot and it's confusing. Imagine selecting something in that big list.

 I propose to group them. For instance you have only the option "camera" in the drop down menu and then you have several other options
end camera
cutscene camera
etc

My group proposal:
* Object & LOD
-> LOD standalone
-> LOD model
-> LOD instance
-> Object

* Lights & sun
-> sun (for light & shadows)
-> light shaft (god rays emitter)
-> light

* Items
-> Nitro (small)
-> Nitro (big)
-> Easter egg
-> banana
-> Item (gift box)

* Cameras
-> end camera (look ahead)
-> end camera (fixed)
-> cutscene camera

* Special effects
-> Particle emitter
-> sound emitter
-> billboard

* Trigger & AI
-> start position (for battle mode)
-> lap line
-> goal line (soccer mode)
-> driveline main
-> checkline
-> cannon end
-> cannon start
-> action trigger

* None

And finally the "ignore" option is outside this big list. Why ? because it's always available and if you want to make a test and ignore an object it's just a quick checkbox. You don't have to go through a big dropdown menu.

**Comment by auriamg** [comment]
The current state is close enough, we can open separate tickets if we have other more specific ideas
