### ISSUE TITLE
Display allow stk to connect to internet when player try to download addons

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1763]
Hi 

While I was testing stk I found this rather annoying thing. If you don't allow stk to connect to internet the first time, later you might open the addons and have no clue why you can't download them.

The easiest and user friendly way of doing it would be to simple display to users the popup that is shown the first time
![connect](https://cloud.githubusercontent.com/assets/6406045/5310934/33c02c5a-7c3c-11e4-9bb7-44150ae8a361.jpg)

**Comment by hiker** [comment]
Is this actually an issue? I just tried it, and if you click on addons, you get a popup window telling you what you need to enable. I think that is good enough. I would consider this a 'Wont' fix".

**Comment by hiker** [comment]
It is indeed more user friendly, but not necessary for 0.8.2, so postponing it.

**Comment by auriamg** [comment]
Fixed in #2605
