### ISSUE TITLE
Karts and track not showing up properly

### ISSUE THREAD

**Issue by shantanusingh10** [supertuxkart/stk-code#1773]
When I start a race . Only shadows of the karts can be seen . Only background image of the tracks can be seen. 

![image](https://cloud.githubusercontent.com/assets/6254324/5377463/551cd7ac-80a8-11e4-8ee1-b4a30463391a.png)

![image](https://cloud.githubusercontent.com/assets/6254324/5377512/cfd39af8-80a8-11e4-850e-7910966ae741.png)

![image](https://cloud.githubusercontent.com/assets/6254324/5377523/ebda210e-80a8-11e4-8880-c2d79659905f.png)

**Comment by qwertychouskie** [comment]
Is this still an issue?

**Comment by deveee** [comment]
STK generally works fine with ivybridge/haswell, so most probably it's not an issue anymore. At least I didn't saw similar bug report since 2014.
