### ISSUE TITLE
Login screen bug

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#1778]
Sometimes the login screen opens as follows, if I open STK with an offline user then click the big "Login" button. Not sure in which cases it happens or not

Notice that "online" is checked but the password field is missing

![login_bug](https://cloud.githubusercontent.com/assets/4296971/5421694/aa1de09a-8236-11e4-9944-012a17ff7f41.jpg)

**Comment by hiker** [comment]
suggested solution: instead of making the 'password' field invisible, replace the label with 'password remembered'  (technically that's wrong, since only the token is remembers, but good enough imho).

**Comment by Flakebi** [comment]
In my opinion it would be better to show the password field when logging in at startup has failed. If you click on OK, it's shown anyway with the message that the token is invalid now.

**Comment by hiker** [comment]
Agreed with the 2nd part, iirc atm if the token has expired (or is invalid for other reasons), you would not notice that you are not logged in.

**Comment by hiker** [comment]
Going to login screen (if still on main menu) or at least an error message if automatic login failed was implemented in e56b4e3. 
@Arthur-D Do you feel to make a special error notification texture (similar to achievement and friend)? And adjust the existing textures for the Ocean skin - for now I used the same (orange-ish coloured) textures.

**Comment by Arthur-D** [comment]
How's this?
![error](https://cloud.githubusercontent.com/assets/5515261/6366104/3419af4e-bcc1-11e4-96d8-9299a34f805c.png)
![achievement](https://cloud.githubusercontent.com/assets/5515261/6366114/3df0e140-bcc1-11e4-86ca-3addd64c7d76.png)
![error](https://cloud.githubusercontent.com/assets/5515261/6366112/3de642c6-bcc1-11e4-81fb-72a4d0fde5e3.png)
![friend](https://cloud.githubusercontent.com/assets/5515261/6366113/3de971c6-bcc1-11e4-9df6-ca06db9f3f65.png)

**Comment by hiker** [comment]
All applied in b21dafc. @Arthur-D please add the original files to the media directory. Once this is done, this ticket can be closed.

**Comment by hiker** [comment]
Arthur has added the xcf file to media, f347cd0 updated the license file in stk-code.
