### ISSUE TITLE
Shader Compilation Improvement

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1787]
1) Most shaders are compiled when the kart selection screen is shown, which causes a noticeable delay. I am aware that shaders can not be (easily) compiled in a separate thread, but it would be better if the shaders could be started to be compiled while the main menu is shown (e.g. one per frame or so). 
2) I have seen that same shaders are actually compiled at race time. This should be done earlier as well.

**Comment by hiker** [comment]
At run time I saw at least particle.frag, most likely also particle.vert and utils/getPosFromUUDepth.frag.Reassigning to 0.8.2, I think it should be very easy to do the instancing earlier.

**Comment by hiker** [comment]
Not really a release blocker.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/90a556fe9cb3de22404df12210b8eb5d38e5a04e

According to GL specification https://www.opengl.org/sdk/docs/man/html/glAttachShader.xhtml, we can attach a shader object to more than one program object.

I've tested on linux + windows intel hd4000 and radeon, both works and no artifacts. Now shader loading in RTT screen is significantly faster, @deveee any idea?

Actually after this clean up, I think hardware skinning is ready

**Comment by deveee** [comment]
@Benau From my understanding, it works mostly in the same way as standard compilation. You compile separate objects, and then you are linking it as a program.

What I was doing was for every shader:
```
    GLuint shader = glCreateShader(type);
    glShaderSource(shader, 1, &CodePtr, &length);
    glCompileShader(shader);
    ...
```
And then for creating final program:
```
    GLuint program = glCreateProgram();
    glAttachShader(program, vertex_shader);
    glAttachShader(program, fragment_shader);
    glLinkProgram(program);
    ...
```
I don't remember if I tested using single shader for multiple programs, but it should work.

Though maybe we should just create a list with already compiled shaders? So that we will still execute:
```
        loadProgram(OBJECT, GL_VERTEX_SHADER, "object_pass.vert",
                             GL_FRAGMENT_SHADER, "colorize.frag");
```
and the loadProgram will search the "object_pass.vert" in the list, detect that it was already compiled and will use it.
Because the
```
        loadProgram(OBJECT, GET_SS(SharedObject),
                             GL_FRAGMENT_SHADER, "colorize.frag");
```
seems to be not communicative. It's hard to say which vertex shader it uses, or if it's a vertex shader or something other. Also all new shaders need to be handled in shared shaders separately.

But general idea is IMO good :)

**Comment by Benau** [comment]
Because i want to preload and identify shaders file only duplicated or better to be loaded before kart selection screen.

And sorry i was making a quick result demonstration product, if you like this approach, maybe i can pick a better name 

SSVertexObjectPass?

**Comment by deveee** [comment]
I'd  say that at least:
```
        loadProgram(OBJECT, GL_VERTEX_SHADER, "object_pass.vert",
                             GL_FRAGMENT_SHADER, "colorize.frag");
```
and in loadProgram something like this:
```
if (isSharedShader(shader_name))
    GET_SS(shader_name)
else
    compileShader()
```
In this way we keep consistency in loadProgram and we know which shaders it actually uses.

But still when someone will add some new shaders in future, they won't be automatically the shared shaders. It would be better if all duplicated shaders could be compiled only once. If they are precompiled on startup or before kart selection screen, then it will just detect in loadProgram that this shader has been already compiled.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/4477dbb0fbc56ea5b7c94ce24062e1d087a7e665
good for you?

**Comment by deveee** [comment]
It looks great now, thanks!

I made a (very) quick test of your branch on nvidia 635m and intel hd 4000 and I didn't notice aany issues.

**Comment by deveee** [comment]
Sorry for closing, it has been accidentally pressed on my phone.

**Comment by Benau** [comment]
Delay no more
