### ISSUE TITLE
Font Tool does not work anymore

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1789]
Several issues:
- [ ] On linux I had to add -lXrandr
- [ ] On linux it then only shows an empty screen.
- [ ] On windows it shows the gui, but all characters are just black blocks.
Not a release blocker, since we can run the 0.8.1 font tool.

**Comment by cap44** [comment]
font tool cannot be built on my end (using latest commit). build log: http://pastebin.com/q5fmueGk

**Comment by auriamg** [comment]
Font tool is no longer needed since the freetype branch was merged
