### ISSUE TITLE
Skybox issue on imac, gtx 780M

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1792]
Ob an imac:
[info   ] IrrDriver: OpenGL version: 4.1
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: NVIDIA GeForce GTX 780M OpenGL Engine
[info   ] IrrDriver: OpenGL version string: 4.1 NVIDIA-10.0.43 310.41.05f01
[info   ] irr_driver: GLSL supported.
I noticed the following.
![screen shot 2014-12-17 at 2 00 05 pm](https://cloud.githubusercontent.com/assets/6138652/5466281/ed6415d6-85fb-11e4-9e1e-8d49af4d5118.png)
Not sure if this is a driver bug, a skybox bug, or what.

**Comment by samuncle** [comment]
hiker is it still the case ?
It should be corrected now

**Comment by hiker** [comment]
I can't test on that machine, but I'll assume that you have fixed that, thanks!
