### ISSUE TITLE
Ability to toggle (some) bananas and gifts selectively

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1797]
It feels like playing with boxes, because a contestant can pass on a TNT bomb.

**Comment by kapilkd13** [comment]
I think this problem is not solved as I am still getting time bomb. I am new and I would like to work on this bug. Please tell me do we have to remove all the bananas or just time bomb.

**Comment by GreenLunar** [comment]
Remove all the bananas.

**Comment by deveee** [comment]
Hiker said:
```Probably not remove the bananas, but just don't give a bomb in case of time trial.```

**Comment by kapilkd13** [comment]
ok.

**Comment by GreenLunar** [comment]
If you will not remove bananas, then make another race mode available with no bananas at all.

**Comment by nado** [comment]
Why not being more generic and add the possibility to remove, at choice, all gifts, all bananas, only some kind of gifts, only some kind of bananas, nitro ?
Then we could decide all the race parameters, like when you can choose what items can be dropped in a super smash bros map.

**Comment by GreenLunar** [comment]
@nado, this is a good idea! particularly, the ability to disable some bananas, which would ease STK on youngsters between 3 - 6 years of age.

I have changed the title, accordingly.

**Comment by Benau** [comment]
@DavidsonLamarre seems that you are working on this issue, so let's have a look together:

For the "ability to disable some items", it may make gameplay config too complex? Also remove (some) items in game before start is not meant for beginners...

Now some tips for the real task if anyone is interested for your (first) STK PR:

In attachment.cpp:287, there is a new_attachment = m_random.get(3), which "draw" 0 , 1 or 2.

So you just need to make it draw one less number if we are in time trial mode, although you will need to re-arrange the orders of number-to-attachment below.

For the determination of current game mode, we have race_manager->getMinorMode()

The answer is obvious...

**Comment by GreenLunar** [comment]
This fork? https://github.com/supertuxkart/stk-code/issues/1797

**Comment by Benau** [comment]
https://github.com/Cav098/stk-code-fix_1797

**Comment by GreenLunar** [comment]
I meant this https://github.com/Cav098/stk-code-fix_1797

**Comment by Benau** [comment]
yes

**Comment by GreenLunar** [comment]
Thanks

**Comment by GreenLunar** [comment]
This does not entirely solve this issue.

**Comment by Benau** [comment]
I don't think we want to make a race without banana, or allow user remove some items before start.

Sorry about that

**Comment by GreenLunar** [comment]
> I don't think we want to make a race without banana, or allow user remove some items before start.

Why so?

**Comment by Cav098** [comment]
So, should this issue be marked as something else?

**Comment by GreenLunar** [comment]
I don't know.

@nado has suggested to be "more generic and add the possibility to remove, at choice, all gifts, all bananas", and enable or disable any type of banana or any type of gift, which sounds very good.  See https://github.com/supertuxkart/stk-code/issues/1797#issuecomment-188171744

Also, removing all gifts would make players to learn how to use drifting to accelerate, and not hope for an gift with acceleration to do so.

**Comment by auriamg** [comment]
Sorry, we indeed have no plans to make a race mode without bananas. STK is a karting game with goodies/baddies, not a racing simulator, so baddies that need to be avoided are part of STK's identity and are unlikely to go away

**Comment by GreenLunar** [comment]
> STK is a karting game with goodies/baddies, not a racing simulator

Offering ability to toggle any good banana or gift does not contradict your statement.

> so baddies that need to be avoided are part of STK's identity and are unlikely to go away

I did not suggest to remove any of them.

**Comment by koopafou** [comment]
Goodies/baddies or not, Time Trial is Time Trial. This obviously means nothing random should occur. At least make it trivially deterministic. 
Online/Multiplayer is more debatable though. Who are the goodies and the baddies here ?

Now, the issue Benau tried to fix isn't completely satisfying, because you will obtain a time bomb (not randomly, it's guaranteed) if you touch a second banana before your parachute/anvil drops. But he just said on IRC that he will fix it.

**Comment by auriamg** [comment]
Maybe a better fix would be that bananas always give anchors in time trial mode? No random, simple and straightforward

**Comment by GreenLunar** [comment]
That would still not solve this issue.

Why do you insist not to provide a generic type of time trial mode?

**Comment by hiker** [comment]
Because bananas are an important part of the track design - they provide an easy and less punishing way of making a track more difficult.

**Comment by Benau** [comment]
Notice: "because you will obtain a time bomb (not randomly, it's guaranteed) if you touch a second banana before your parachute/anvil drops" should be fixed

**Comment by koopafou** [comment]
I don't mind if they always give the same item.
