### ISSUE TITLE
Windows OSD graphic issue

### ISSUE THREAD

**Issue by Matthias84** [supertuxkart/stk-code#1800]
Hi, I tried to start 0.8.2beta on Windows7 but had massive visual problems:
![stk 0802 win crash](https://cloud.githubusercontent.com/assets/217511/5472978/ffad595a-8605-11e4-9dcf-11e485e7d527.jpg)

This is a laptop running uptodate Win7 x64 with intel onboard graphic. I tried also the XP compability mode, but no success :-/

**Comment by qwertychouskie** [comment]
Fixed (see https://github.com/supertuxkart/stk-code/issues/2596), can this be closed?
