### ISSUE TITLE
CREDITS file has a wrong encoding and can't get loading by the "About" feature

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#1804]
On STK 0.8.2-beta, with the data installed system-wide in /usr/share/games/supertuxkart (`STK_INSTALL_DATA_DIR` in CMake).

When I click "About" in the main menu, the game segfaults and outputs:

> [error  ] CreditsScreen: Could not read anything from CREDITS file!

The file is correctly installed, but most likely it isn't referenced properly in the code.

```
-rw-r--r-- 1 root root 6512 déc.  17 01:10 /usr/share/games/supertuxkart/data/CREDITS
```

**Comment by akien-mga** [comment]
I'm still faced with the same bug with STK 0.8.2-beta2. Was the fix backported to the corresponding branch?

**Comment by akien-mga** [comment]
Actually it might not be an encoding issue this time:
```
$ file /usr/share/games/supertuxkart/data/CREDITS 
/usr/share/games/supertuxkart/data/CREDITS: UTF-8 Unicode text
```

Here is my log: http://paste.fedoraproject.org/178313/14226197/

**Comment by akien-mga** [comment]
Well it's still an encoding issue actually. I downloaded the credits file from master, and it's in UTF-16LE:
```
$ file CREDITS
CREDITS: Little-endian UTF-16 Unicode text
```
I replaced the 0.8.2-beta2 CREDITS file with the one from master, and then the issue is fixed, the credits display fine.

**Comment by deveee** [comment]
I'm not on linux atm, but CREDITS file in linux beta2 package has UTF-16LE
encoding. Actually Notepad++ says that it is UCS-2 LE.

I checked this file on Windows and it works for me.

**Comment by deveee** [comment]
More interesting for me is this line:
[warn   ] Graphics: Can not find version for '3.3 (Core Profile) Mesa
10.4.3' 'Mesa DRI Intel(R) Ivybridge Mobile ' - ignored.

Does it mean that graphics restrictions don't work for you?

**Comment by akien-mga** [comment]
Nevermind, I must have messed up something when packaging and installing 0.8.2-beta2, it seems I still had leftovers from 0.8.2-beta.

**Comment by akien-mga** [comment]
> More interesting for me is this line:
[warn ] Graphics: Can not find version for '3.3 (Core Profile) Mesa 10.4.3' 'Mesa DRI Intel(R) Ivybridge Mobile ' - ignored.
> 
> Does it mean that graphics restrictions don't work for you?

I don't know how the graphics restrictions are supposed to work. If it's about automatically downgrading the graphics settings depending on the hardware, it does not seems to work for me (the settings are set to the maximal values). But it's worth noting that I have an optimus laptop, so I set those settings while using my Nvidia GPU, so maybe the graphics restrictions do not override user-defined parameters?

**Comment by deveee** [comment]
In graphical_restrictions.xml you can add for example:
  <card contains="Mesa"           os="linux"    version="<10.6"
disable="DriverRecentEnough"/>

You should get popup message that your mesa drivers are too old. If it
won't be displayed, then something is wrong.

**Comment by akien-mga** [comment]
My mesa drivers are not too old, mesa 10.4.3 is the last upstream release from 5 days ago :-)

**Comment by deveee** [comment]
I know that your mesa drivers are not too old :) But in your logs I saw
that STK probably didn't find your mesa version.

**Comment by akien-mga** [comment]
@deveee Actually the graphical restrictions work fine, I believe I had installed the beta2, but I was still testing the first beta actually, hence this very bug hitting me again and the graphical restrictions not working.

With 0.8.2-beta2, it works fine.
