### ISSUE TITLE
Do not capture "screenshot saved to" text

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1806]
![greenvalley-2014 12 16_09 45 02](https://cloud.githubusercontent.com/assets/2053884/5476494/11374882-862b-11e4-89c8-10f9ad1abf32.png)

**Comment by seowyanyi** [comment]
Hmm is this bug fixed? I can take screenshots on my Dell using the default fn + printscreen (this takes screenshot of the whole screen too, not sure whether there's a separate hotkey purely for stk). The screenshots saved to ~/.cache/supertuxkart/screenshots do not have the text inside.

Running ubuntu 14.04.

**Comment by kapilkd13** [comment]
I think the problem is solved as I can take screenshots on windows 8.1

**Comment by NalinG** [comment]
Yeah , the bug is fixed.
