### ISSUE TITLE
No visual feedback for nitro if low graphic settings are used

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1808]
If you can't use the higher graphic settings or need to use the lowest settings, then you don't have visual feedback for nitro. 

In my opinion there should be some kind of visual feedback for those with weak computers. 

Unanimated blue cones at the exhaust pipes would be fine, even if they only use 4 vertices.

**Comment by auriamg** [comment]
This fix doesn't work on graphical level 1

**Comment by auriamg** [comment]
Okay seems like what I did is useless for level 1 since at this level, the shaders in user simply don't support particles. Am I right @vlj ?

**Comment by auriamg** [comment]
Should be fixed in 13393ef04bc364534cd0a1b134eecddcff5dc67c

**Comment by hiker** [comment]
Sorry, have to reopen, it doesn't work for me on hd3000, windows. The transparent textures used for the particles create an opengl error:
    [error  ] Irrlicht: GL_INVALID_FRAMEBUFFER_OPERATION
    [error  ] Irrlicht: Could not bind Texture
    [error  ] Irrlicht: GL_INVALID_FRAMEBUFFER_OPERATION
    [error  ] Irrlicht: Could not bind Texture
Let me know what other information you need.

**Comment by vlj** [comment]
Will be automatically fixed in 0.9.1

**Comment by hiker** [comment]
The nitro effect itself is not a release blocker, but I suspect it's the same reason as #1476 - so leaving this for 0.8.2 for now.
The error message (which will be fixed later) is most likely a red herring for the missing particles.

**Comment by hiker** [comment]
Fixed when #1476 was fixed.
