### ISSUE TITLE
Major graphic issues on low graphical effect level

### ISSUE THREAD

**Issue by pb-programmer** [supertuxkart/stk-code#1809]
I just installed stk 0.8.2 beta and encountered a major graphic issue (see pics below)

STK: precompiled 0.8.2 beta
System:
OS: Win7 64bit
CPU: Intel Core i7-3520M @ 2,90GHz
Grapics: none / Intel Graphics 4000

The issue arised while trying to play a normal race (not story mode)
1.effect-level: 1 (was selected first time running stk)
![olivermath-2014 12 17_22 35 40](https://cloud.githubusercontent.com/assets/9591354/5479712/24f5c686-8640-11e4-9adf-be56a32107c5.png)
2. effect-level: 5 (low fps)
![olivermath-2014 12 17_22 36 04](https://cloud.githubusercontent.com/assets/9591354/5479717/2fcf2a8e-8640-11e4-9cd2-4ef6106a3551.png)
3. effect-level: 4 (medium fps, after 5 was selected for one race)
![olivermath-2014 12 17_22 38 08](https://cloud.githubusercontent.com/assets/9591354/5479727/43697978-8640-11e4-9352-77413a42de32.png)
4. effect-level: 3 (good fps, after 5 was selected for one race)
![olivermath-2014 12 17_22 41 26](https://cloud.githubusercontent.com/assets/9591354/5479733/515d13e6-8640-11e4-9648-4605bd193188.png)
5. effect-level: 2 (after 5 was selected for one race)
![olivermath-2014 12 17_22 42 07](https://cloud.githubusercontent.com/assets/9591354/5479748/6b9ce81c-8640-11e4-93a6-1eb2cf41a131.png)
6.effect-level: 1 again (after 5 was selected)
![olivermath-2014 12 17_22 42 35](https://cloud.githubusercontent.com/assets/9591354/5479770/8a011c88-8640-11e4-8646-84127f0e6ce9.png)

So hope that helps fixing the issue. If you need further information, let me know.
(And excuse my bad english, haven't wrote any english text for a while)

Greetings and keep up the good work,
Christoph

**Comment by auriamg** [comment]
Can you try again with the latest version? vlj did some recent fixes that may help

**Comment by pb-programmer** [comment]
Sorry, posted a lot of stuff to the wrong issue (screw you multitab browsers ;) )
However: I installed beta2 now from the precombiled binaries (it uninstalled beta1 automatically).
Since it kept my previous sceen settings I can't tell wether the "first startup" work fine or not, but manually adjusting the GEL unfortunatly caused the same error as with beta1...

Graphics Effect Level 1 (vanilla startup, no previous GEL > 3 selected):
![olivermath1-gfx1_01](https://cloud.githubusercontent.com/assets/9591354/6081832/d216c244-ae1c-11e4-8a32-4a2dbe21b2d5.png)
![olivermath1-gfx1_02](https://cloud.githubusercontent.com/assets/9591354/6081833/d217b460-ae1c-11e4-9fc7-6613fa9cd2cf.png)

Graphics Effect Level 2:
![olivermath1-gfx2_01](https://cloud.githubusercontent.com/assets/9591354/6081841/da915d94-ae1c-11e4-95ed-c51da3a50823.png)
![olivermath1-gfx2_02](https://cloud.githubusercontent.com/assets/9591354/6081840/da906ace-ae1c-11e4-86fb-f76e4e895887.png)
![olivermath1-gfx2_03](https://cloud.githubusercontent.com/assets/9591354/6081842/da92d926-ae1c-11e4-9ca1-e51f99226849.png)

Graphics Effect Level 3:
![olivermath1-gfx3_01](https://cloud.githubusercontent.com/assets/9591354/6081846/dee97660-ae1c-11e4-82a3-aa5a2959c442.png)
![olivermath1-gfx3_02](https://cloud.githubusercontent.com/assets/9591354/6081845/dee81ca2-ae1c-11e4-9abe-7590813c6c3d.png)

Graphics Effect Level 4:
![olivermath1-gfx4_01](https://cloud.githubusercontent.com/assets/9591354/6081848/e4447db2-ae1c-11e4-9b57-1070e55a4129.png)
![olivermath1-gfx4_02](https://cloud.githubusercontent.com/assets/9591354/6081849/e4453c98-ae1c-11e4-9ac8-360a96275881.png)

Graphics Effect Level 5:
![olivermath1-gfx5_01](https://cloud.githubusercontent.com/assets/9591354/6081854/e82936ac-ae1c-11e4-9842-b59795bcad77.png)
![olivermath1-gfx5_02](https://cloud.githubusercontent.com/assets/9591354/6081855/e82948b8-ae1c-11e4-8a30-710d155b29fa.png)

Graphics Effect Level 1 (after GEL 5 was selected for one race):
![olivermath1-gfx1pre5_01](https://cloud.githubusercontent.com/assets/9591354/6081885/036ee8ee-ae1d-11e4-9116-7cb336ab059d.png)
![olivermath1-gfx1pre5_02](https://cloud.githubusercontent.com/assets/9591354/6081883/036c587c-ae1d-11e4-9821-1e2c6149b8e2.png)
![olivermath1-gfx1pre5_03](https://cloud.githubusercontent.com/assets/9591354/6081884/036cb2d6-ae1d-11e4-928b-49136f055a67.png)


The game was 1600x900 px (native screen resolution) in fullscreen mode.

My system specs:
CPU:                Intel Core i7 3520M
Mainboard:      Lenovo 2353CTO (Intel QM77 Southbridge)
                        BIOS: G7ETA1WW 2.61 (dated 09/01/2014)
RAM:               8GB (2 à 4GB Hyundai Electornics) @ 800MHz
Graphics:        Intel HD Graphics 4000
                       GPU-BIOS: 2161_RYan PC 14.34 (dated 12/07/2012)
                       Driver Version: igdumdim64 9.18.10.3359 / Win7 64 
                                              (latest as stated by "Lenovo Solution Center)
                       Clock: 650MHz GPU (~950MHz during a race) / 800MHz Memory
                       ROPs: 4       TMUs: 8           Unified Shaders: 16
                       Supports DX11, ShaderModel 5.0, OpenCL, DirectCompute 5.0

I hope that helps you fix the bug. Please also note the quied bad FPS values. STK 8.1.0 seemed to be a lot more fluently although i have no FPS evidence, just the general feel :/

If you need more information, feel free to ask :)

**Comment by auriamg** [comment]
Okay thanks for testing, but actually this was fixed after beta 2. So if you don't build the game from source, could you please test again when the next build is released?

**Comment by hiker** [comment]
Closing this for now, since we assume it has been fixed after beta2. Please reopen or comment on this ticket if it should still be an issue with the RC.

Thanks for the report!
   Joerg
