### ISSUE TITLE
Graphic glitch with Intel HD 4000 and Debian Jessie

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1810]
When change the graphic setting to the preset "2" i get some graphic problems. With 3 and above it works okay.

Video: http://videobin.org/+8e2/b7z.ogg

It is a Intel HD 4000 under Debian Jessie .

Graphic HW details: 

    00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09)
	Subsystem: Lenovo Device [17aa:21f7]
	Kernel driver in use: i915

     xserver-xorg-video-intel                                    2:2.21.15-2+b2 

Please ask for more detailed informations about hardware or drivers.

**Comment by Flakebi** [comment]
The issue looks similar to #1647, switching from graphic level 2 to 3 means enabling the advanced pipeline.

**Comment by hiker** [comment]
Is this still an issue with our second beta?

**Comment by hiker** [comment]
Closing this now,since we had no feedback.

**Comment by lightonflux** [comment]
Compiled the newest version and updated the assets and it seems to work now.
