### ISSUE TITLE
Terms and agreement text cut on the right side

### ISSUE THREAD

**Issue by kneekoo** [supertuxkart/stk-code#1812]
The images is self explanatory.

![Screenshot](http://i.imgur.com/ced1rT3.png)

nicu@nicu-pc ~ $ inxi -SGx
System: Host: nicu-pc Kernel: 3.12.8-031208-generic x86_64 (64 bit gcc: 4.6.3) Desktop: MATE 1.6.1 (Gtk 3.4.2) 
Distro: Linux Mint 13 Maya 
Graphics:  Card: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller bus-ID: 00:02.0
Display Server: X.Org 1.11.3 driver: intel Resolution: 1920x1080@60.0hz
GLX Renderer: Mesa DRI Intel Ivybridge Desktop GLX Version: 3.0 Mesa 9.2.0 Direct Rendering: Yes

nicu@nicu-pc ~/git/stk/stk-code $ ./cmake_build/bin/supertuxkart 
Irrlicht Engine version 1.8.0
Linux 3.12.8-031208-generic #201401151952 SMP Thu Jan 16 00:53:39 UTC 2014 x86_64
[info   ] IrrDriver: OpenGL version: 3.0
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Ivybridge Desktop 
[info   ] IrrDriver: OpenGL version string: 3.0 Mesa 9.2.0
[info   ] GLDriver: ARB Texture Storage enabled
[warn   ] Graphics: Can not find version for '3.0 Mesa 9.2.0' 'Mesa DRI Intel(R) Ivybridge Desktop ' - ignored.
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[info   ] GUIEngine: scale: 0.512000

**Comment by auriamg** [comment]
The main issue is that this dialog uses a list widget instead of a text widget, presumably to enable it to scroll.

So I see 2 possibilities, either implement proper word wrap in list widgets, either implement proper scrolling widgets

**Comment by hiker** [comment]
We also need to update the terms as well!

**Comment by auriamg** [comment]
Clipping part fixed in 758eb6e0034c945efc1d72c4195b02262272d471 . The actual text still remains to be written

**Comment by hiker** [comment]
Assigning to arthur to do some research about t&c.

**Comment by hiker** [comment]
http://stkaddons.net/privacy  appears to contain already some information which imho could be used as t&c(?)

I found some information about T&C and privacy policy:
http://www.wikihow.com/Make-Terms-and-Conditions-and-Privacy-Policies-for-a-Business

**Comment by hiker** [comment]
I've created a terms&conditions and a privacy page on the wiki for now. Once they are finalised they should be used on the addons web page directly (to avoid any issues with people editing it later).
http://supertuxkart.sourceforge.net/Privacy
http://supertuxkart.sourceforge.net/Terms
@auriamg ,  @Arthur-D , @samuncle , @leyyin , @stephenjust  - feedback need!

We also need redirects from our main web page (supertuxkart.net/privacy, supertuxkart.net/terms ?)

**Comment by hiker** [comment]
The remaining issues are assigned to the addons:
supertuxkart/stk-addons#50
