### ISSUE TITLE
Proposed Hebrew fonts for bold red/yellow titles

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1814]
Either use Arial or DejaVu Sans.

![untitled 1](https://cloud.githubusercontent.com/assets/2053884/5484092/a031bfe0-868a-11e4-89d2-4746e6ea5295.png)

**Comment by GreenLunar** [comment]
bump!

**Comment by Flakebi** [comment]
It looks like it's the same as #1736 where brackets and question marks aren't bold too.

**Comment by auriamg** [comment]
This is a limitation of our current font system, making fonts for all languages is quite time consuming for us so sorry, it's unlikely we'll make a custom hebrew-title font unless it's contributed (want to get involved?) Also, the current situation is not that bad, so not excessively urgent.

**Comment by GreenLunar** [comment]
Is there a guide for beginners that you know of?

**Comment by auriamg** [comment]
The title font, I'm afraid, is made by hand (including the associated XML file). We have a font tool, but it can't generate the title font since this one uses effects

**Comment by GreenLunar** [comment]
CC @cap44

**Comment by cap44** [comment]
@auriamg can you assign this to me? i'll try to tackle it this or next week

**Comment by cap44** [comment]
the comix font looks nice,  no need to create another font just for the title

**Comment by GreenLunar** [comment]
This is not just for the title.

**Comment by Benau** [comment]
![2015-10-13 08-53-14](https://cloud.githubusercontent.com/assets/3252341/10442810/c69ffef0-7188-11e5-9ad8-a6a6993f123e.png)
good?

**Comment by GreenLunar** [comment]
I like it!

@cap44, what do you think?

**Comment by cap44** [comment]
Hey,  I cannot say anything about this for now,  as I am away from my
computer.  I will check it out later today

**Comment by GreenLunar** [comment]
From the screenshot @Benau, STK in Hebrew looks very good.

@cap44, if you plan to compile the [freetype](https://github.com/Benau/stk-code/tree/freetype) branch of @Benau, please also check if using FreeType fonts has an affect on #1823

**Comment by cap44** [comment]
I will check it out later today,  as again,  I do not have access to my
computer.  And will report if  @Benau's work on implementing Free Type into
STK works and fix #1814 and #1823.

On Oct 13, 2015 9:05 AM, "GreenLunar" <notifications@github.com> wrote:
>
> From the screenshot @Benau, STK in Hebrew looks very good.
>
> @cap44, if you plan to compile the freetype branch of @Benau, please also
check if using FreeType fonts has an affect on #1823

**Comment by cap44** [comment]
Hey @Benau, Nice work on the freetype font render engine. 
@GreenLunar the fix doesn't affect issue #1823 because that issue was in fact fixed in commit 819156106d26b3ef3bba7da05c4a699860641edd (Pull Request 2107).

Yes, STK does look better with the freetype render engine.

**Comment by auriamg** [comment]
The freetype branch has been merged, so closing this issue as fixed
