### ISSUE TITLE
Reversed RTL text (track name) in unlocked track screen

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1815]
neercs kcart dekcolnu ni (eman kcart) txet LTR desreveR

**Comment by deveee** [comment]
@GreenLunar Maybe it was workarounded directly in translations. Tracks names can't be workarounded because they are displayed in different palces.

Anyone from Arabia? :P

**Comment by GreenLunar** [comment]
No workarounds in Hebrew translation as far as I can see.

I have seen a clever RTL workaround in SMPlayer, where strings that appear both in MPlayer (where RTL strings get reversed like in some parts in STK as reported above) AND Qt (SMPlayer) interface are translated like םולש and have LRO mark to reverse them in Qt interface to שלום.

**Comment by auriamg** [comment]
I would recommend against writing translations in reverse, this seems especially unclean. I know there's no one available at the moment, but getting some contributor speaking an RTL language is still the best option

**Comment by auriamg** [comment]
We have recently merged RTL fixes from Seebi, could you please confirm if it's now fixed?

**Comment by cap44** [comment]
Looks good on my end: 
![overworld-2015 03 30_07 44 57](https://cloud.githubusercontent.com/assets/8017401/6890293/eb2a6c9c-d6b0-11e4-8502-47d0260a02f5.png)

@GreenLunar is it fixed for you?

**Comment by GreenLunar** [comment]
It seems so.  Thank you @Seebi

**Comment by GreenLunar** [comment]
Or @ Flakebi

**Comment by GreenLunar** [comment]
Or @Flakebi

**Comment by GreenLunar** [comment]
Texts within `%s` in `Completed achievement "%s".` is reversed.
