### ISSUE TITLE
Cocoa Temple: Fall through the map

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1817]
There is an area in the Cocoa Temple Map where you can fall through the map and see it from below.

I think there the muddy water should trigger auto recovery to prohibit this.

Video: http://videobin.org/+8e6/b83.ogg

**Comment by Flakebi** [comment]
That's more or less the same as #1839, only at another place.
There's the same problem with the new island track too.

**Comment by samuncle** [comment]
it's now corrected. Reset plane are done

**Comment by nado** [comment]
We can reopen it, it is happening again at the same place.
This is the git version with --root option set on datas from the 0.9 src package.
https://videobin.org/+8xo/bvt.html

**Comment by samuncle** [comment]
This is a minor bug IMHO. You don't get any advantage and you can't really cheat by going under the map. Great for all people who want to play to indiana jones

**Comment by samuncle** [comment]
duplicate of #2114
