### ISSUE TITLE
Grand prix victory animation fade out problem

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1819]
It looks like the fade out is broken. It repeats until you click on the "Weiter" (forward) button and end the animation.

Video: http://videobin.org/+8e7/b84.ogg

**Comment by auriamg** [comment]
Oops wrong ticket number, this one is not fixed!

**Comment by auriamg** [comment]
I am unable to reproduce this bug, do you have any more information on how to reproduce it? Are you able to test the latest development version to make sure it's still there?

**Comment by lightonflux** [comment]
Tested and it is fixed.
