### ISSUE TITLE
Treasure chest animation empty (no trophy)

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1820]
If you finish a race and get a trophy then the animation after the race shows a treasure chest with a trophy emerging. But in this beta the chest just opens and is empty.

**Comment by auriamg** [comment]
@lightonflux: just to clarify, do you experience the same issue as Flakebi, or a different one? i.e. does the  cutscene fade out too early before anything had time to go out of the chest? Or was there sufficient time for something to come out of the chest and it really didn't? (in case you're not sure, normally the cutscene is supposed to wait until you click "continue" or press some keyboard key before exiting, so if it exited without any input then it's a case of "ends too soon")

**Comment by lightonflux** [comment]
> @lightonflux:  does the cutscene fade out too early before anything had time to go out of the chest? 

I think so.

Video proof (newest git version at the time): http://videobin.org/+8ff/b9k.ogg

**Comment by auriamg** [comment]
Should be fixed in c87531fc1bde4ad22dda803ca7575d158ec58570

If anyone can test to confirm it's really 100% fixed that would be nice! On my computer it seems to work though so I'm pretty confident I fixed it

**Comment by lightonflux** [comment]
Works for me (current git).
