### ISSUE TITLE
[RTL] Wrapped text appears from bottom to top.

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1823]
from bottom to top.
Wrapped text appears

![screenshot - 141214 - 140847](https://cloud.githubusercontent.com/assets/2053884/5491859/2d61a9ca-86e5-11e4-8de8-e2816f4de40c.png)

**Comment by GreenLunar** [comment]
@cap44 is this problem fixed?

**Comment by cap44** [comment]
Looks like a wrapping problem

**Comment by hiker** [comment]
Could you provide some hint exactly what the problem is? I mean, I don't even know what screen that might be - ideally the English text would be useful ;) 

Is the first line cut off? Or do you mean it should be wrapped more evenly?

**Comment by cap44** [comment]
"Are you sure you want to remove player <%s>? " is what that line says in Hebrew

**Comment by GreenLunar** [comment]
> Could you provide some hint exactly what the problem is? I mean, I don't even know what
screen that might be - ideally the English text would be useful ;)

This is the problem:
> screen that might be - ideally the English text would be useful ;)
Could you provide some hint exactly what the problem is? I mean, I don't even know what

**Comment by cap44** [comment]
@GreenLunar Try again?

**Comment by cap44** [comment]
I can try to work around this problem by modifying the actual string and not the wrapper code, but I'm not sure how hiker or auria will react to this. 

@hiker, @auriamg, opinions?

**Comment by GreenLunar** [comment]
> @GreenLunar Try again?

I am not willing to compile STK.  Please post screenshots.

> I can try to work around this problem by modifying the actual string and not the wrapper code, but I'm not sure how hiker or auria will react to this.
> 
> @hiker, @auriamg, opinions?

GTK+ and Qt implement RTL best.  I want to point out that the wrapping effect of RTL in STK appears to be exactly like wrapping effect of RTL in XTerm (and most other terminal emulators).

**Comment by GreenLunar** [comment]
I think such work around is ineffective due to different screen resolutions.

**Comment by Flakebi** [comment]
We tried to improve the line wrapping by dynamically detecting if a string is RTL text or not and use this to wrap the text (that's actually done in irrlicht). This seems to work when deleting a keyboard configuration (the question mark appears in the second line), but not when deleting a user account.

**Comment by GreenLunar** [comment]
I did not know that STK 0.9 has been released.  I will compile and check.

THIS POST WILL BE DELETED.

**Comment by cap44** [comment]
hang on, @GreenLunar are you running the game in 800x600 resolution?

**Comment by GreenLunar** [comment]
No, 1024x640 (16:10).

I am unable to compile:
```
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CBoneSceneNode.d CBoneSceneNode.cpp
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CSkinnedMesh.d CSkinnedMesh.cpp
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CB3DMeshFileLoader.d CB3DMeshFileLoader.cpp
make: *** התיינבל םיללכ ןיא ךא ,`CBSPMeshFileLoader.o' תשרוד `libIrrlicht.a' הרטמ.  Stop.
```

**Comment by Flakebi** [comment]
I probably found out why fribidi detects RTL text sometimes right and sometimes wrong: The label tests, if text is RTL or not, but at this time, the text has already gone through fribidize which means it is reverted and the RTL marks are missing (I'm not completely sure about the marks).
If this text is passed to fribidi, it examines the "first" characters (`?'1'` in the example from the first comment) which is clearly LTR.

At the moment there is no way to get the the original string from a translated string. Maybe a `stringw` can have a property that saves if it is RTL (or its original string before it was fribidized).

**Comment by GreenLunar** [comment]
Can you imitate the Help dialog? All paragraphs in Help dialog are wrapped perfectly.

**Comment by Flakebi** [comment]
It should work now, every text containing at least one RTL character should be using the correct line wrapping.
It would be nice if someone could confirm that it's working now :-)

**Comment by cap44** [comment]
Confirmed on my end

**Comment by auriamg** [comment]
Thanks! So it looks like this is fixed. Please reopen this issue if you find more problems
