### ISSUE TITLE
Story mode + graphics on 5 = crash

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1828]
I have completed all challenges and am ready to beat the bad nolok. 

So i exited the story mode and set the graphic settings on the preset "5" , enabled the music again and then in the main menu selected story mode. On button press stk crashes.

Here the relevant log info:

        [info   ] Singleton: Destroyed singleton.
        [info   ] OptionsScreenAudio: Music is now on
        [debug  ] RaceManager: Nb of karts=1, ai:0 players:1

        [warn   ] GLWrap: OpenGL debug callback - API
        [warn   ] GLWrap:     Error type : OTHER
        [warn   ] GLWrap:     Severity : MEDIUM
        [warn   ] GLWrap:     Message : FBO incomplete: framebuffer attachment layer mode is inconsistent [-1]

        supertuxkart: /home/moritz/Spiele/stk-code/src/graphics/glwrap.cpp:215: FrameBuffer::FrameBuffer(const std::vector<unsigned int>&, GLuint, size_t, size_t, bool): Zusicherung >>result == 0x8CD5<< nicht erf?llt.

If i start the game again and select story mode → crash.

I use an Intel HD 4000 on Debian Jessie:

    00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09)
    Subsystem: Lenovo Device [17aa:21f7]
    Kernel driver in use: i915

Xorg driver:
       xserver-xorg-video-intel                                    2:2.21.15-2+b2

**Comment by lightonflux** [comment]
Were the rules added? 

Because this issue wasn't closed i  can't crash stk anymore by upping the graphics.

**Comment by auriamg** [comment]
A lot of graphical fixes happened since that was posted. So if you can't reproduce the issue anymore I will consider this fixed :) please reopen the ticket if more problems are found
