### ISSUE TITLE
stk crashes sometimes

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1829]
Intel HD 4000 on Debian Jessie.

    00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09)
    Subsystem: Lenovo Device [17aa:21f7]
    Kernel driver in use: i915

xorg driver: 
     xserver-xorg-video-intel                                    2:2.21.15-2+b2 

Log (compiled with debug):

http://paste.ubuntu.com/9564933/

**Comment by lightonflux** [comment]
supertuxkart: /home/lightonflux/Spiele/stk-code/src/utils/log.hpp:93: static void Log::fatal(const char*, const char*, ...): Zusicherung >>false<< nicht erf?llt.
        Program received signal SIGABRT, Aborted.
        0x00007ffff47aa107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        56	../nptl/sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.




        (gdb) bt
        #0  0x00007ffff47aa107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        #1  0x00007ffff47ab4e8 in __GI_abort () at abort.c:89
        #2  0x00007ffff47a3226 in __assert_fail_base (fmt=0x2095ee8 "%s%s%s:%u: %s%sZusicherung >>%s<< nicht erf?llt.\n%n", 
            assertion=assertion@entry=0x1100eb7 "false", file=file@entry=0x1100e88 "/home/lightonflux/Spiele/stk-code/src/utils/log.hpp", 
            line=line@entry=93, 
            function=function@entry=0x1103640 <Log::fatal(char const*, char const*, ...)::__PRETTY_FUNCTION__> "static void Log::fatal(const char*, const char*, ...)") at assert.c:92
        #3  0x00007ffff47a32d2 in __GI___assert_fail (assertion=0x1100eb7 "false", file=0x1100e88 "/home/lightonflux/Spiele/stk-code/src/utils/log.hpp", 
            line=93, 
            function=0x1103640 <Log::fatal(char const*, char const*, ...)::__PRETTY_FUNCTION__> "static void Log::fatal(const char*, const char*, ...)")
            at assert.c:101
        #4  0x00000000009457cc in Log::fatal (component=0x12d1233 "STKMesh", format=0x12d12d8 "Missing texture for material transparent")
            at /home/lightonflux/Spiele/stk-code/src/utils/log.hpp:93
        #5  0x0000000000c5bcea in InitTexturesTransparent (mesh=...) at /home/lightonflux/Spiele/stk-code/src/graphics/stkmesh.cpp:360
        #6  0x0000000000c7890d in STKMeshSceneNode::updateGL (this=0x2323b020) at /home/lightonflux/Spiele/stk-code/src/graphics/stkmeshscenenode.cpp:199
        #7  0x0000000000cc7e3a in IrrDriver::PrepareDrawCalls (this=0x18f0f80, camnode=0x24ceabb0)
            at /home/lightonflux/Spiele/stk-code/src/graphics/stkscenemanager.cpp:621
        #8  0x0000000000d30d5c in IrrDriver::renderScene (this=0x18f0f80, camnode=0x24ceabb0, pointlightcount=2, 
            glows=std::vector of length 30, capacity 32 = {...}, dt=0.0280000009, hasShadow=true, forceRTT=false)
            at /home/lightonflux/Spiele/stk-code/src/graphics/render.cpp:345
        #9  0x0000000000d30120 in IrrDriver::renderGLSL (this=0x18f0f80, dt=0.0280000009) at /home/lightonflux/Spiele/stk-code/src/graphics/render.cpp:189
        #10 0x0000000000d241d2 in IrrDriver::update (this=0x18f0f80, dt=0.0280000009) at /home/lightonflux/Spiele/stk-code/src/graphics/irr_driver.cpp:2111
        #11 0x0000000000aaf368 in MainLoop::run (this=0x269f920) at /home/lightonflux/Spiele/stk-code/src/main_loop.cpp:151
        #12 0x0000000000a64c63 in main (argc=1, argv=0x7fffffffe4e8) at /home/lightonflux/Spiele/stk-code/src/main.cpp:1401

**Comment by auriamg** [comment]
This error is usually associated with a specific track or addon, which track produces this error?
