### ISSUE TITLE
Crash on startup with some add-ons karts

### ISSUE THREAD

**Issue by cpcbegin** [supertuxkart/stk-code#1838]
I download the christmas beta and I run on my i7 under my Ubuntu 14.04 bits but it crashed:
...
[info ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info ] GrandPrixManager: Loading Grand Prix files from /home/bobu/.local/share/supertuxkart/grandprix/
[error ] Kart_Model: Missing wheel information 'front-left' for model 'sara the racer.b3d'.
[error ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error ] material: Cannot find texture 'motif.png'.
[error ] material: Cannot find texture 'shoes_gloves.png'.
Segmentation fault (core dumped)

I also try to run using gdb (export LD_LIBRARY_PATH=./lib-64;gdb ./bin-64/supertuxkart) and I get these output:
Starting program: /home/bobu/Descargas/stk/supertuxkart-0.8.2-beta-linux/bin-64/supertuxkart 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Irrlicht Engine version 1.8.0
Linux 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64
[debug  ] main: Error messages and other text output will be logged to /home/bobu/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is '/home/bobu/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/bobu/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/bobu/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/bobu/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[debug  ] translation: Env var LANGUAGE = 'es_ES'.
[debug  ] translation: Language 'Spanish (Spain)'.
tinygettext: jbo.po: warning: ignoring, unknown language
tinygettext: sco.po: warning: ignoring, unknown language
Adding language fallback es
tinygettext: jbo.po: warning: ignoring, unknown language
tinygettext: sco.po: warning: ignoring, unknown language
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadMatch (invalid parameter attributes)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: GeForce GT 610/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 3.3.0 NVIDIA 304.125
[info   ] GLDriver: ARB Base Instance enabled
[info   ] GLDriver: ARB Draw Indirect enabled
[info   ] GLDriver: ARB Texture Storage enabled
[info   ] irr_driver: GLSL supported.
[info   ] GUIEngine: scale: 0.512000
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/uniformcolortexturedquad.frag
[info   ] player_manager: A new players.xml file will be created.
[Nuevo Thread 0x7fffebf16700 (LWP 4094)]
[Nuevo Thread 0x7fffe9e83700 (LWP 4095)]
[Thread 0x7fffe9e83700 (LWP 4095) terminado]
[Nuevo Thread 0x7fffe9e83700 (LWP 4096)]
[Nuevo Thread 0x7fffe5681700 (LWP 4097)]
[Nuevo Thread 0x7fffe4e80700 (LWP 4098)]
[Nuevo Thread 0x7fffdffff700 (LWP 4099)]
[Nuevo Thread 0x7fffdf7fe700 (LWP 4100)]
[Nuevo Thread 0x7fffdeffd700 (LWP 4101)]
[Nuevo Thread 0x7fffde7fc700 (LWP 4102)]
[Nuevo Thread 0x7fffddffb700 (LWP 4103)]
[Nuevo Thread 0x7fffdd7fa700 (LWP 4104)]
[Nuevo Thread 0x7fffdcff9700 (LWP 4105)]
[warn   ] track: Music information file 'mysteriousbarricades.music' not found for track 'Doing the Dishes' - ignored.

[warn   ] track: Music information file 'TheDeadRocks-GreenSecretFromAmazonia.music' not found for track 'Lost Speedway' - ignored.

[warn   ] track: Music information file 'ChillCarrier-Druckverlust.musi' not found for track 'NIght by the Sea' - ignored.

[warn   ] track: Music information file 'TheDeadRocks-GreenSecretFromAmazonia.music' not found for track 'Traditional Shifting Sands' - ignored.

[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/bobu/.local/share/supertuxkart/grandprix/
[error  ] Kart_Model: Missing wheel information 'front-left' for model 'sara the racer.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] material: Cannot find texture 'motif.png'.
[error  ] material: Cannot find texture 'shoes_gloves.png'.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5d6ae8e in std::string::assign(std::string const&) ()
   from ./lib-64/libstdc++.so.6
(gdb) bt full
#0  0x00007ffff5d6ae8e in std::string::assign(std::string const&) ()
   from ./lib-64/libstdc++.so.6
No symbol table info available.
#1  0x0000000000919c48 in KartProperties::operator=(KartProperties const&) ()
No symbol table info available.
#2  0x0000000000917bc3 in KartProperties::copyFrom(KartProperties const*) ()
No symbol table info available.
#3  0x0000000000917f31 in KartProperties::load(std::string const&, std::string const&) ()
No symbol table info available.
#4  0x00000000009192f9 in KartProperties::KartProperties(std::string const&) ()
No symbol table info available.
#5  0x000000000091c71a in KartPropertiesManager::loadKart(std::string const&)
    ()
No symbol table info available.
#6  0x000000000091cd1b in KartPropertiesManager::loadAllKarts(bool) ()
No symbol table info available.
#7  0x00000000006c86aa in main ()
No symbol table info available.
(gdb) bt full
#0  0x00007ffff5d6ae8e in std::string::assign(std::string const&) ()
   from ./lib-64/libstdc++.so.6
No symbol table info available.
#1  0x0000000000919c48 in KartProperties::operator=(KartProperties const&) ()
No symbol table info available.
#2  0x0000000000917bc3 in KartProperties::copyFrom(KartProperties const*) ()
No symbol table info available.
#3  0x0000000000917f31 in KartProperties::load(std::string const&, std::string const&) ()
No symbol table info available.
#4  0x00000000009192f9 in KartProperties::KartProperties(std::string const&) ()
No symbol table info available.
#5  0x000000000091c71a in KartPropertiesManager::loadKart(std::string const&)
    ()
No symbol table info available.
#6  0x000000000091cd1b in KartPropertiesManager::loadAllKarts(bool) ()
No symbol table info available.
#7  0x00000000006c86aa in main ()
No symbol table info available.

Also I run lspci to show my hardware:
00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1c.5 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #6 (rev d5)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation C220 Series Chipset Family H81 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
01:00.0 VGA compatible controller: NVIDIA Corporation GF119 [GeForce GT 610] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GF119 HDMI Audio Controller (rev a1)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
04:00.0 Network controller: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)

**Comment by deveee** [comment]
I checked few karts from your website and it works for me. Could you write precisely steps how to reproduce it?

**Comment by deveee** [comment]
I assume that there was something wrong with add-on kart. I'm not able to fix this without more information because I have no idea what could be the reason.

**Comment by cpcbegin** [comment]
We follow these instructions to make the karts (on Spanish sorry) http://es.tente3d.wikia.com/wiki/A%C3%B1adir_Tente_3D_a_SuperTuxKart

By the way the Tente karts are now in http://cpcbegin.nixiweb.com/tente/index.en.php?pagina=stuxkart

**Comment by auriamg** [comment]
Could you please point us to one specific addons that has this issue?
