### ISSUE TITLE
SuperTuxKart sometimes crashes when finishing a race

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1843]
It happens that stk crashes when I finish a race and the kart is staggering accross the finishing line (maybe stk tries to rescue it?).
I'm not sure if this stacktrace is really related to the problem because it's not similar to the other crashes, but it happend under the same circumstances.

[Stacktrace](https://gist.github.com/Flakebi/cd29aff61189aaed0346)

Last lines:
```
[info   ] This work was NOT networked: This is NOT a network world.
[error  ] MusicOgg: [MusicOggStream] OpenAL error at alBufferData : AL_INVALID_NAME (40961)

[error  ] MusicOgg: [MusicOggStream] OpenAL error at alSourceQueueBuffers : AL_INVALID_NAME (40961)

*** Error in `/home/sebi/Dokumente/Dateien/Programme/SuperTuxKart/graphics/cmake_build/bin/supertuxkart': malloc(): memory corruption: 0x00007fff7d187220 ***
```

**Comment by hiker** [comment]
Seeing the music messages before, I wonder if this is a side effect of some incorrect audio code. Could you try to reproduce this again, I just fixed some bugs in the audio code.

**Comment by Flakebi** [comment]
I wasn't able to reproduce this with some tests. It's difficult to get this (or these?) bug, so maybe I had no "luck" to crash stk, but probably it's working now.
