### ISSUE TITLE
Addon : UI improvement

### ISSUE THREAD

**Issue by mathsoft-dev** [supertuxkart/stk-code#1844]
Hello,
I thought about a small UI improvement for addons. At the moment, you have to click on every addon to see the details and a pop up appears and you have to close it everytime. I think it would be faster for the user to find the addon that he likes by 1- replacing the box(with the heart) at the left with the preview picture of the kart/map and/or 2- to do something like in the picture. The user could move with up and down arrow or gamepad and see the infos of the addon without clicking on it and having a pop up. You save some clicks/time and could make a difference after looking at 10-20 addons in a row.

If you think it's worth it, I will work on it.

![idea](https://cloud.githubusercontent.com/assets/9955284/5519382/80533078-891e-11e4-8585-95c287b0cbcf.png)

**Comment by qwertychouskie** [comment]
Maybe use this mode when using a widescreen aspect ratio (e.g. 16:9), but not when using a square-ish one (e.g. 4:3)?

**Comment by mdeguzis** [comment]
To add to this, I would very much like a way to preview assets like karts. You can't see the kart itself until you install it. I only see the icon in the preview when I click on it.

**Comment by CodingJellyfish** [comment]
The addon menu needs rework, but this solution is definitely far from perfect, as stated by Auria a long time ago.
