### ISSUE TITLE
In the intro cut scene, GNU stays in the air when Nolok's shuttle goes away

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1845]
At the beginning of the cutscene, GNU gets absorbt by Nolok's plane. When the shuttle leaves the scene, GNU stays in the air, he should disappear or move with the plane, but not be visible.
![gnu](https://cloud.githubusercontent.com/assets/6499211/5531979/f4d285a2-8a31-11e4-9176-0373bcef0f4b.png)

**Comment by auriamg** [comment]
Fixed in svn
