### ISSUE TITLE
Improve graphic setting usage

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1851]
A new file containing all the graphic setting logic was introduced in f644543bc1f48d4e8a8277494ce797f5d468ca3e
The purpose of this file is to gather the user graphic settings, the driver reported capability and graphic restriction system approval for this capability.

Ideally for all the "isEXTENSIONUsable" function declared in this file there should be an option in config.xml to override graphic setting value. For instance a "OverrideARBUniformBufferObject" field which could take "no" "true" or "false" value, "no" meaning that graphic restriction system will be used, "false" meaning that if the driver reports ARB Uniform Buffer Object support it won't be used, and "true" meaning that if the driver reports ARB Uniform Buffer Object support it will be used even if graphic restriction system doesnt approve it.
While this could be done manually I think a macro system would make this much more clean.
Additionnaly it would be nice if all gfx settings declaration for UserConfigParams were movable there.

**Comment by deveee** [comment]
Not really sure if it has a sense. Most features can be already disabled in graphics restrictions file, so that people can fix the game without recompiling. Enable some features even if extensions don't exist seems to be useful only for developers. In this case it doesn't really matter if you change it in config.xml or CVS.

**Comment by qwertychouskie** [comment]
Agreed, too much effort for too little gain.

**Comment by Benau** [comment]
I don't think we should abuse the use of opengl extension, esp for some of them it is just going to bloat stk with little or no performance gain (proven in SP)
