### ISSUE TITLE
Implement ngettext support

### ISSUE THREAD

**Issue by gunchleoc** [supertuxkart/stk-code#1852]
Some strings need proper plural forms. A case in point is:

src/online/online_player_profile.cpp:406
%d friends are now online.

Plural forms can be achieved by ngettext, which tinygettext doesn't support though.

The roblem is that the Gaelic forms only become idential for numbers > 19, and with Slavic languages like Russian, numbers ending in 1, 2 or 4 have special forms http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html. Battle for Wesnoth has ngettext support and I think they use tinygettext as well, maybe they can help.

**Comment by leper** [comment]
See #1877. Since values are already inserted into translated strings the only thing missing was a call to translate_plurals().
