### ISSUE TITLE
"Log in/out" or "Sign in/out"?

### ISSUE THREAD

**Issue by gunchleoc** [supertuxkart/stk-code#1853]
At the moment, we use both "Log in" and "Sign in" for the same thing. This is confusing for the users, so we should pick one and stick with it. I'll be happy to take care of it, but we need to make up our minds first which terminology we perfer.

**Comment by hiker** [comment]
That was fixed a while ago  520625adaeb89b7ae0e6a0b62fbe2ef062ba9306.
