### ISSUE TITLE
Add a separate frame to kart animations to be used in kart selection screen

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#186]
**Author: hikerstk**

E.g. a driver with long ears might have the ears modeled to point backwards while driving, but that might look odd in the kart selection screen. So if necessary add a special animation marker specifying which frame to use in the kart selection screen.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/130

**Comment by Benau** [comment]
Our wilber / hexley animator suggests we play win animation for karts in kart selection screen. what do you think (try this branch?)

**Comment by hiker** [comment]
I would still suggest to add a special animation tag to be used in the kart screen. We just need to check if it's possible to set two labels on the same frame (i.e. if the exporter handles it correctly). We can make the win animation the default in case that no kart-selection animation is defined.

**Comment by Benau** [comment]
Yes that was what he suggested before!

**Comment by hiker** [comment]
OK, sorry - I thought it was supposed to replace that idea ;)
