### ISSUE TITLE
Challenge timer replaced with red stripes if you take too long

### ISSUE THREAD

**Issue by BinkyToo** [supertuxkart/stk-code#1864]
During a race, when the time to complete the challenge is up, the timer is replaced by red diagonal stripes. This was during a "collect nitro" challenge.
![screenshot1](https://cloud.githubusercontent.com/assets/7592459/5593697/7c7fb980-921a-11e4-8d66-ffa148c55a2f.png)

**Comment by auriamg** [comment]
This is caused by using a font that contains only numbers
