### ISSUE TITLE
Slider doesnt react to mouse click

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1866]
It's currently not possible to set a value by clicking on the slider bar, one has to use the left/right Arrow (on screen or on the keyboard). This makes their usage quite tedious especially in debug mode where usually track creators want to quickly change values.

**Comment by NalinG** [comment]
Hi, I would love to work on this bug.
Well if we just add the mouse click event, will it solve the bug..?

**Comment by konstin** [comment]
Yes. It's just registering for the mouse click event and then setting the new value depending on the position of the click. But imo the value should only be adjustable with the mouse for gauge spinners, so you also have to check that.

**Comment by NalinG** [comment]
Are you refering spinners as slider..?

**Comment by konstin** [comment]
Yes, a slider is internally represented by `class SpinnerWidget` (`src/guiengine/widgets/spinner_widget.hpp`)

**Comment by auriamg** [comment]
This has now been done
