### ISSUE TITLE
Make possible to reload texture on the fly

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1867]
There is no tool to see the impact of a specular map outside of STK. This makes them difficult to draw despite being able to greatly enhance tracks visuals.

One solution is to allow stk to reload textures on the fly. While reloading all textures may take a couple of second it is much faster than restarting STK and allow to see changes inplace.

There is a "texture cache" located somewhere in Irrlicht code that holds a pointer to all textures. Auria should know better than me how it works.
We also have our own texture caches in graphics/texturemanager.cpp : AlreadyTransformedTexture and unicolor_cache.
The former is used to avoid compressing a texture twice (maybe not necessary anymore ?) and the latter to store textures with a single color. I don't think they need to be modified to implement texture reloading.

In order to make reload texture possible, one has to iterate textures in Irrlicht cache and load files as image. Then OpenGL textures content can be reuploaded using glTexSubImage2D :
https://www.opengl.org/sdk/docs/man/html/glTexSubImage2D.xhtml

The OpenGL part is quite simple :
glBindTexture(GL_TEXTURE_2D, texture_id);
glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width, height, GL_RGB(A), format, pointer);
glGenerateMipMap(GL_TEXTURE_2D);
glBindTexture(GL_TEXTURE_2D, 0);

where texture_id (returned by "getOpenGLTextureName()"), width and height are stored by ITexture implementation. The format variable is not readily avaible but is deduced by the ECF_\* format of the object as well as alpha channel presence.
In order for this to work it should be noted that texture compression must be disabled : there is no way to determine if a texture is compressed or not from irrlicht side since it's done in STK. In addition texture compression takes time and probably not necessary when doing several fast iteration.

**Comment by hiker** [comment]
Not sure that I would call this for beginners: you basically need to run through the whole display re-initialisation procedure, since there are objects active that store textures (e.g. gui elements, karts). They all need to be re-loaded.

**Comment by Noxygen13** [comment]
Hi everyone, I'm completely new to the project, I'd just like to give a try on this one. Seems complicated, I'll see. 

Btw, I met one of you at "Japan Impact EPFL", but I forgot his nickname, if someone know about which guy I'm talking about, I'd appreciate your help!

**Comment by auriamg** [comment]
Removing the "for beginners" tag since it's indeed not that easy. If anyon still wants to tackle this then why not ;) But that should probably not be worked on before we merge elderme's work since that would affect the engine quite a bit

**Comment by Noxygen13** [comment]
Okay I understand, what beginner tagged todo would be a good choice at the moment which wouldn't be affected by current work ?

**Comment by Benau** [comment]
Since 67b6c3bf059a709a1b85fc29925c03aca6a82eb4 it is possible, I tried linux + windows

Please re-open if there is any issue found
