### ISSUE TITLE
Black box around skidding effect

### ISSUE THREAD

**Issue by siadyhr** [supertuxkart/stk-code#1869]
When skidding there is a black box around the normal skidding effect, looking very ugly.
The image itself is right, and changes color from orange to red (red pictured below). Might it be something to do with alpha-channels in the image?
![4p04zwv](https://cloud.githubusercontent.com/assets/8537104/5597659/810a6392-92a6-11e4-862b-2c905f957dd2.jpg)

My graphics card is a intel GMA X3100, I'm using xf86-video-intel as graphics driver. I'm running linux.

**Comment by auriamg** [comment]
Can you post the terminal output? I suspect your GPU/driver does not support OpenGL 3 and you are running on the old OpenGL 2 fallback

**Comment by siadyhr** [comment]
I guess it's only the OpenGL part you need:
```
    [info   ] IrrDriver: OpenGL version: 2.1
    [info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
    [info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) 965GM 
    [info   ] IrrDriver: OpenGL version string: 2.1 Mesa 10.4.1
```
So OpenGL <3 is just not supported anymore? That's a bit sad, but I guess that's how it is.

**Comment by hiker** [comment]
@vlj do we get a warning message popping up if the opengl version is too old (as opposed to the driver version being too old)? If there is a warning now, that can be closed

**Comment by hiker** [comment]
Potentially a release blocker - too old opengl versions should (try to) display an error message (at least to stdout)

**Comment by auriamg** [comment]
Should be fixed
