### ISSUE TITLE
"You need more points" text overflow in story mode

### ISSUE THREAD

**Issue by siadyhr** [supertuxkart/stk-code#1870]
If you hit a challenge bubble in story mode you haven't unlocked yet, a text stating "YOU NEED MORE POINTS TO ENTER THIS CHALLENGE! CHECK THE MINIMAP FOR AVAILABLE CHALLENGES." If you hit it again, a new text appears below and so on, at last overflowing the screen. They do disappear after a while, though.
Maybe change so only one is displayed at a time?
![screenshot from 2015-01-02 17 36 00](https://cloud.githubusercontent.com/assets/8537104/5597707/5772e7ce-92a7-11e4-9b3e-47749d9d85a2.png)

**Comment by auriamg** [comment]
The text should not appear more than once, and should perhaps use a smaller font

**Comment by math07** [comment]
I'm gonna fix this.
