### ISSUE TITLE
Deprecate random boxes into specifics

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1872]
* Specific boxes: Instead of random weapons, make alternatives for current boxes with specific weapon for each alternative form of box (for example: Ball for a bowling ball).
* Amplifiers (two extra levels): By itself, an amplifier is not usable as weapon, and thus is not a weapon, but when an amplifier is collected with a Ball, user would have a blowing cake, with 2 amplifiers, user would have a basket ball.

This is an idea. Please comment and post your suggestions on top of it.

**Comment by auriamg** [comment]
Hi, suggestions are better posted on the forum, the issue tracker is more about tasks that have been approved by the core team

For the record, we are currently happy with random boxes

**Comment by GreenLunar** [comment]
Please correct post location if incorrect http://forum.freegamedev.net/viewtopic.php?f=17&t=6803 Brand nitro pickups with OpenUserJs logo and colors.
