### ISSUE TITLE
Last round sound does not work

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1873]
Last round sound does not work when music is disabled.

**Comment by Flakebi** [comment]
Duplicate of #1613.

**Comment by auriamg** [comment]
@Flakebi I don't think it's a duplicate, I think he's talking about the little jingle that plays when starting the last lap

However, since it's a little music, I don't think it's a bug that disabling music should remove it

**Comment by GreenLunar** [comment]
> However, since it's a little music, I don't think it's a bug that disabling music should remove it

Then disable the start music, too.
