### ISSUE TITLE
More contestant voices

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1874]
Add funny voices to contestants when being up (*laugh* or Yes!) down (Hey!! or Oh, no!) in position. and when bombing (Yeah!), being bombed (Ouch!) and almost being bombed (Woah!).

**Comment by konstin** [comment]
There are already some sound effects for karts possible and some are also used, but currently this isn't really used because there's no one making good sound effects (those that are not annoying even after you heard them a dozen times). Another task is to enable per-kart sounds (#1535).

**Comment by hiker** [comment]
Using a single voice effect for all karts is way too repetitive (we had that in the past), and quickly abandoned it. So #1535 is necessary, and it includes all of this ticket, so I am closing this.
