### ISSUE TITLE
Prefer basketball over contestant

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1875]
When using a cake with B pressed, STK shoots it on a closer contestant instead of closer basketball.

**Comment by hiker** [comment]
I don't understand this. With 'B pressed' you mean looking backwards? Why should it use a basket ball insteat of a cake??

**Comment by GreenLunar** [comment]
The scenario is as follows:

* User is placed 1st.
* Contestant launches a basketball.
* Basketball is behind 1st place, before 2nd place.
* User fires a cake or plunger while holding `B` key.
* Cake or plunger hits a contestant (instead of basketball).
  * When a contestant was not nearby, cake or plunger would hit the basketball.

**Comment by lightonflux** [comment]
I agree, there should be more possibilities to defeat the basketball (not only gum shield). E.g. with cake, plunger or even bowling ball (needs very good timing).

**Comment by GreenLunar** [comment]
Gum shield is not the only way. You can avoid basketball by skidding; you can defeat basketball with bowling ball (most difficult), plunger (lesser difficult) or cake (easiest).

There is an auto aiming feature in STK that prefers nearby karts over nearby basketballs.

**Comment by hiker** [comment]
No powerups aim at balls or so. You can be lucky to hit it, but I don't think that the cake should be make even stronger by hitting the balls.

**Comment by GreenLunar** [comment]
Then make no preference when distance of basketball is X.
