### ISSUE TITLE
Warn youngsters when entering Audio/Video settings

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1876]
Show warning dialog:
*Warning: You are about to change how STK works. If you are unsure about these settings, ask an older person for help.*

![lego_racers_older_person](https://cloud.githubusercontent.com/assets/2053884/5598668/004ca9b4-92c3-11e4-9d0d-604431d48183.png)
Using VirtualBox without DirectX installed.
Taken from LEGO Racers (1999)

**Comment by konstin** [comment]
What's the problem with kids playing around with the settings? The dialogs should anyway prevent you from destroying anything (except performance).

**Comment by vlj** [comment]
I highly doubt that children don't understand what audio/gfx settings are especially if they play on a computer. 
We may have a warning in the audio menu that high volume may harm ears sensitivity and a warning about epilepsy somewhere if necessary and display a message that online experience may be child unfriendly (all games in Europe says that the "online experience is not covered by ESRB rating").

**Comment by auriamg** [comment]
```
We may have a warning in the audio menu that high volume may harm ears sensitivity 
```

that is so obvious that IMO it is pointless to mention. It's like food that says "will be hot when heated"

**Comment by GreenLunar** [comment]
It would be relevant when a graphics card has limitations https://github.com/supertuxkart/stk-code/labels/C%3AGraphics

**Comment by hiker** [comment]
We are working on improving the graphics, and otherwise I'll agree with the others - esp. since it would also inconvenience the majority of players who want to test settings.

**Comment by GreenLunar** [comment]
Perhaps adding a mechanism that would lock settings.  This mechanism would be enabled when restriction of settings is set up.  The password may be stored in plain text in STK configuration file.

**Comment by konstin** [comment]
I'm still in favor of leaving the settings open and rather add a mechanism that prevents you from accidentally breaking something.
