### ISSUE TITLE
Drifting makes you immune to cupcakes

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1883]
Drifting makes you immune to cupcakes

At least that is what i experienced. Not sure if there was some collision i couldn't see. But it is a bit hard to reproduce in normal gameplay.

**Comment by lightonflux** [comment]
*Fast drifting (red sparks)

**Comment by hiker** [comment]
This is not done on purpose, but I think it's fine if there is a way to escape a cake.
