### ISSUE TITLE
No hit messages

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1884]
In older version you saw a message when one player hit another with a weapon/special. In the current git i don't see them anymore. 

Were they removed?

**Comment by deveee** [comment]
They were removed here 05607e862eda50680312d3abcbe4bce6eed62671

**Comment by lightonflux** [comment]
Will they be replaced/reintroduced?

**Comment by lightonflux** [comment]
Any plans to give players feedback on successful hits?

**Comment by auriamg** [comment]
The messages themselves are probably not coming back, it had quite a bit of UI clutter, translation work, general lack of screen space and general noise. Finding other ways to notify players of successful hits may be considered (though the kart icons on the left do indicate when a kart is hit)
