### ISSUE TITLE
Parachute too weak!?

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1885]
I have the feeling that the parachute is much weaker than in the current stable. 

Were there any changes, or is it just the new driving physics?

Nevertheless… IMHO the parachute has too little effect on the player. It should stay longer, or have more braking effect. I would prefer if it would stay longer with the player. In the past it was too similar to the anchor which has a big effect in a short time. The parachute should have a medium braking effect but longer.

**Comment by deveee** [comment]
Only one change for parachutes which I remember is that they occur a bit 
more frequently for large number of oponents (actually now with the same 
frequency for every oponents number).

You can try this patch if you want (parachutes are even weaker but stay 
longer)
https://github.com/supertuxkart/stk-code/pull/1696

**Comment by solistice** [comment]
I made some changes to parachutes a while back (https://github.com/supertuxkart/stk-code/pull/1213), which made requested changes to parachutes. The parachute "strength" was since then influenced by the speed of the kart at the moment of receiving. Instead of needing to drop a certain amount of speed, you now had to drop a % of speed

**Comment by Flakebi** [comment]
That explains some bad experiences: One time my kart was nearly standing still and I got a parachute which didn't go away for a very long time (I felt like racing hours with it ;) ). So I don't think parachutes fade away too early, they're sometimes staying too long. It looks like the pull request by @Alayan-stk adds this.

**Comment by Alayan-stk-2** [comment]
Alayan there (lost the password of my previous account).

I guess this parachute issue is still present as it has not been marked fixed. If the team is interested (answer me to confirm), I may check again my code, update it if needed to make it compatible with the newer release, and do another pull request for this specific change. I'd like to finally solve it for the 0.9.3.

The goal is, to be clear, to make parachute less penalizing when at slow speed (where they are too much right now) but more penalizing at high speed (where they are barely an annoyance right now).

**Comment by Alayan-stk-2** [comment]
Fixed with #2768.
