### ISSUE TITLE
AI karts shouldn't use the players kart

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1886]
So i was racing against 3 AI karts and my kart was emule. Another AI player had the same kart, which looked a bit weird on the winner's stand.

stk should choose random karts, and only reuse the players kart if there are more players then karts. Or even better only select the players kart for AI when every other kart is 2 times in a race, which would be the case with 32 AI karts.

But maybe it is easier to implement that the random selection never puts the players kart in the subset of usable karts for AI.

**Comment by hiker** [comment]
This should already be the case: depending on what tab you select the karts from, the AI will only pick karts from that tab, and try to avoid using duplicated karts. So with only 3  karts used a duplicate should only happen if you selected e.g. your kart in addons, and there were only 3 karts in the addons. Selecting the kart in the 'standard' (or 'all') tab should avoid this issue.

Please reopen this ticket if you picked the kart from a group with enough karts. Then we would need more details, esp. if you can reproduce it, and what did you do (what kind of race, story mode or GP, race, FTL, ...). Also what STK version are you using, you should at least be using our beta (or current git version).

**Comment by lightonflux** [comment]
I picked emule from the "all" (25 karts)  or "standard" (17 karts) tab and got an emule as opponent. I only have 8 karts in add-ons, but even with 4 karts in the race it shouldn't have happened and emule is clearly default.

It only happened with a grand prix, maybe that's relevant.

I can't reopen the issue.

**Comment by deveee** [comment]
It is probably possible when you:
  - play grand prix
  - exit grand prix after 2-3 races
  - change a kart
  - continue grand prix

AI karts are restored, but player can choose which kart he want.
