### ISSUE TITLE
Konqi numberplate issue

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#1887]
I don't lknow what's causing it, but you can see a problem with the numberplate of the konqi kart. 

I use graphics level 3 on an Intel HD4000.

Video:

http://videobin.org/+8g6/bak.ogg

**Comment by qwertychouskie** [comment]
Is this still an issue?

**Comment by lightonflux** [comment]
Yes just tested with 0.9.2 on the same system.

**Comment by qwertychouskie** [comment]
Hmm, for me, completely gone... (Intel HD 3000, Mesa devel)

**Comment by SuicSoft** [comment]
I can see this sometimes on my laptop (Radeon HD 7640g , Mesa devel) but not always

**Comment by Benau** [comment]
Fixed when adding headlight
