### ISSUE TITLE
Music stops for a moment when loading track selection screen for the first time

### ISSUE THREAD

**Issue by marcoll** [supertuxkart/stk-code#1892]
When the track screen is loaded for the first time it has to read all tracks' screenshots from disk and turn them into textures, all at the same time. This makes music stop for a moment, which is kind of annoying.

The solution is as simple as populating irrlicht's texture cache during startup. If someone thinks this is worth including in the upcoming release I can send a pull request with the required change.

**Comment by auriamg** [comment]
This sounds good to me, track screenshots are going to get loaded sooner or later so I see no harm in preloading them

**Comment by hiker** [comment]
This should be fixed by the above pull request.
