### ISSUE TITLE
STK problem with libgl.so on xubuntu

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1893]
When I try to build the master I have this error:

samy@emilia:/home/jmclemencon/MyProjects/new_stk/stk-code/build$ make -j10
[  0%] Built target glew
[  2%] Built target wiiuse
[  3%] Built target enet
[  4%] Built target bulletmath
[  6%] Built target bulletdynamics
[ 10%] Built target angelscript
[ 22%] Built target bulletcollision
[ 54%] Built target stkirrlicht
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'bin/supertuxkart'.  Stop.
CMakeFiles/Makefile2:98: recipe for target 'CMakeFiles/supertuxkart.dir/all' failed
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
samy@emilia:/home/jmclemencon/MyProjects/new_stk/stk-code/build$

**Comment by hiker** [comment]
Does:
http://techtidings.blogspot.com.au/2012/01/problem-with-libglso-on-64-bit-ubuntu.html

help?

**Comment by hiker** [comment]
And http://www.blender.org/forum/viewtopic.php?t=21867&sid=880baaed9b6fc7fb52876390328ac836
at the very end has a similar link

**Comment by samuncle** [comment]
It's on my regular computer so no idea what changed

1) I tried the first link but I have no /usr/lib/libGL.so.1
2) in the second it says: 
samy@emilia:/home/jmclemencon/MyProjects/new_stk/stk-code/build$ sudo apt-get install libgl1-mesa-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgl1-mesa-dev is already the newest version.
The following packages were automatically installed and are no longer required:

**Comment by hiker** [comment]
Apparently cmake already fails, not only linking:
```
$ cmake ..
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- No build type selected, default to STKRelease
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'bluez'
--   found bluez, version 4.101
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found OggVorbis: /usr/include  
-- checking for module 'fribidi'
--   found fribidi, version 0.19.6
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenGL.cmake:161 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:157 (find_package)
 
 
-- Configuring incomplete, errors occurred!
See also "/home/jmclemencon/MyProjects/new_stk/stk-code/build/CMakeFiles/CMakeOutput.log".
 ```

**Comment by hiker** [comment]
Apparently a problem with samuncle's environment

**Comment by hiker** [comment]
Oops - forgot to document samuncle's steps: Apparently the following link was missing in /usr/lib/x86_64-linux-gnu/mesa/:
libGL.so -> libGL.so.1
(which is a link go libGL.so.1.2.0).
Then libglu1-mesa-dev  was missing. And a reboot in between as well.

**Comment by samuncle** [comment]
I confirm. During an update, some stuff were broken (it was a minor update, so I'm quite angry by the mess it caused)

Anyway it should be okay now :). Sorry for inconvenience
Sam
