### ISSUE TITLE
Document what to change when adding or renaming a kart or track.

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1894]
Atm it's not documented what needs to be checked if a track or kart is added (or renamed0.

**Comment by samuncle** [comment]
And maybe it's time to have a better system ? that allows to change stuff a bit more easily. But not sure how.

Also tracks like stk enterprise shouldn't be placed in old folder like star track. This is counter intuitive

**Comment by hiker** [comment]
Fixed, documented on the page:
http://supertuxkart.sourceforge.net/File_naming_conventions

Note that at this stage we do not follow at least the track convention for most tracks :(
