### ISSUE TITLE
Loose transparency in story mode points requirements

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1897]
Hey,
This is a very minor bug so please tell me if you prefer that I don't report minor bugs in the future. I don't want to make you loose your time.
![overworld-2015 01 09_22 14 12](https://cloud.githubusercontent.com/assets/9955284/5690285/33406146-984d-11e4-8a13-827c7061f9c9.png)

To reproduce it : 
1. Open the game in windowed mode. (if you go in story mode the number will have transparency)
2. Make the game full screen.
3. Start the story mode. (no more transparency black number)

If you exit stk and start the game again you have transparency in full screen.

**Comment by vlj** [comment]
I think that making the game full screen reset the OpenGL context and some part of the code behaves oddly.

**Comment by vlj** [comment]
I think that we'll need to get rid of the irr_driver->getShader(...) calls to solve this but materials.hpp/cpp need some work.

**Comment by Flakebi** [comment]
For me, the numbers aren't transparent too, but not only if I change something. I didn't manage to get them transparent, it seems like my graphical settings aren't important (deactivating advanced pipeline didn't change it).

**Comment by hiker** [comment]
I have this problem on windows with intel hd3000. I just need to uncheck high res textures (see #1908), start overworld, and I have non-transparent numbers. That's with or without advanced pipeline (but no advanced option selected).

**Comment by auriamg** [comment]
This was probably caused by our change to use absolute paths for material names
