### ISSUE TITLE
Speed weighted objects export issue

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#1900]
Testable with Adiumy. The key on the side of the egg is a speed weighted object. It does not export correctly if the key and its armature are not centered at 0,0,0 (the key rotates weirdly in-game)

**Comment by Benau** [comment]
See b09eec4

Make sure in blender the center mass of armature and objects are the same, instancing (using alt-d) works too, so you can do animate hair of head in kart using speed weighted object, or even for example like this:
![screenshot](https://user-images.githubusercontent.com/3252341/30529221-b9ff2760-9c2a-11e7-944e-7491e07ef0f1.jpg)
