### ISSUE TITLE
Floor in the 'Cave X' arena is white

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1901]
The floor of the 'Cave X' arena (the second one that's in the standard arenas) is completely white.
Additionally I can't see tires that karts lost (but I can see their shape in the physic debug view).

**Comment by auriamg** [comment]
I am unable to reproduce, do you see any warning on the terminal? What graphical level, what OS, etc. may also help

**Comment by Flakebi** [comment]
Ok, I thought it was reproducible, so here are more details.

I'm on Arch linux with a NVidia gtx 750, driver version 343.36.
The only error I get in the terminal is:
```
[error  ] Irrlicht: Could not load texture: ../data/../../stk-assets/
[error  ] irr_driver: Texture '../data/../../stk-assets/' not found.
[error  ] icon_button: add() : error, cannot find texture ''.
```

Apparently there's a texture called ''.

This are my graphical settings, changing them to the lowest or highest doesn't affect the floor:
![stk-settings](https://cloud.githubusercontent.com/assets/6499211/5735203/86228718-9bc2-11e4-952f-e204744f0a18.png)
How the track looks:
![stk-white-floor](https://cloud.githubusercontent.com/assets/6499211/5735220/cc8fdc64-9bc2-11e4-9221-ae692a9bc6d4.png)
How a lost wheel looks (or not...):
![stk-invisible-wheel](https://cloud.githubusercontent.com/assets/6499211/5735222/dca28fc0-9bc2-11e4-8e26-34bfc7914bfc.png)

**Comment by hiker** [comment]
Does this only happen in split screen? If you enable artist debug mode you can run an arena with a single kart.

Does it help to reduce the settings further?

**Comment by Flakebi** [comment]
It happens in singleplayer mode too and changing the graphical settings to the lowest or highest doesn't change anything.

**Comment by hiker** [comment]
Can you add your stdout.log?  What happens if you copy the file cavex_rock.jpg to ground.jpg ? cavex_rock appears in your screen, rock.jpg doesn't.

**Comment by Flakebi** [comment]
ground.jpg exists in my assets and copying cavex_rock.jpg to that name doesn't change anything.
[Here](https://gist.github.com/Flakebi/b2c4c20ca4ec1c948247) is my output.

**Comment by hiker** [comment]
There are quite a few warning messages about
 Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
etc. Is this self compiled, a package, or our static binary?

I would suspect it's a packaging problem (e.g. incorrect image handling lib linked in?) Our static library should use the right version, could you test this (in case that you haven't done this)?

**Comment by Flakebi** [comment]
Yes, the previous output is from a self-compiled one.
I downloaded the beta 2 linux package from sourceforge and it has no more warnings like the ones before, but it doesn't work too ([output](https://gist.github.com/Flakebi/5ada2a511e98ffae3c52)).
Neither the static 32-bit binary, nor compiling in release mode, nor using clang helps.

Beside that, I don't miss textures in other tracks, but it worked perfectly on windows when I tried (with the beta 2 installer).
The ICC warnings appear when starting stk, so before the track is loaded.

**Comment by hiker** [comment]
It appears the wheel and texture issue have a different reason: the missing wheel was reproduced, see #2000. This issue is probably going to be postponed, since I see no chance of finding it (and I would mention our usual suspect ... driver bugs ;) ).

**Comment by Flakebi** [comment]
@leyyin has the same issue, @Arthur-D hasn't and we all have an nvidia gpu and used linux (different distributions) for testing.

**Comment by leyyin** [comment]
Actually I was experiencing this issues on intel 4000 on linux with mesa 10.1.3.

**Comment by Flakebi** [comment]
It seems like the cause of this problem is related to the object `BasePaths` in the `.blend` file (in the 9th layer).
When I remove this object I can see the floor.

**Comment by deveee** [comment]
Thanks for finding it. I just removed this layer in blend file because it shouldn't be displayed anyway. Now it should work fine.

**Comment by hiker** [comment]
I think that's the mesh for the battle mode AI. It should not be removed, it should either be marked to be ignored, or as a special type and be ignored by the exporter

**Comment by hiker** [comment]
Auria fixed this in r16103; ticket #2019 keeps track of future work for the battle AI.

**Comment by deveee** [comment]
I looked at svn history and last modification in Cave X was from May 2011
(except porting to new engine). I don't see there anything about battle AI.
And first commits done by nixt are from 2013 IIRC.

I thought that this layer simply was used during creating arena and it
wasn't cleaned when it was finished.

**Comment by hiker** [comment]
Thanks, good point, my mistake then. Well, anyway, with that object now marked to be ignored,we are safe :)
