### ISSUE TITLE
1-800-555-0101 is not a fictional phone number

### ISSUE THREAD

**Issue by xfix** [supertuxkart/stk-code#1904]
http://supertuxkart.blogspot.com/2014/12/merry-christmas-and-beta.html has a screenshot with phone number 1-800-555-0101. However, 1-800-555-0101 [is not a fictional phone number](https://en.wikipedia.org/wiki/555_%28telephone_number%29), if your intent was to put a fictional phone number. For 800 area code, only 1-800-555-0199 is reserved.

**Comment by samuncle** [comment]
Hum interesting I didn't know that. So as far as I understood the 1-800 should be removed right ?

**Comment by xfix** [comment]
Removed or replaced with some real fictitious phone number (for example 1-800-555-0199).

**Comment by samuncle** [comment]
@xfix  I was wondering if I use another prefix something like 311-555-0xxx, is it okay ? or any 555 with a prefix will be valid ?

**Comment by xfix** [comment]
`xxx-555-01yy` would be fine, as long `xxx` is not `800`.

**Comment by samuncle** [comment]
![stkflag_oceanicairlinesad_a](https://cloud.githubusercontent.com/assets/6406045/6140217/6eab80e2-b195-11e4-8e26-241f910850d1.png)
Done, now the number should be 100% fictional

Thanks for the bug report :)
