### ISSUE TITLE
Make install is broken

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1906]
After last changes make install is broken again. It's because we use now libstkirrlicht.so as external library.

This can be probably done by install it to LIBRARY_OUTPUT_DIRECTORY in the same way as data files. But I didn't check yet what is the current state on Windows.

**Comment by konstin** [comment]
zlib, libpng and jpeglib are also external dependencies since 057709955190754b4b54f827b0f1fe1abe978407. This should be added in the wiki and Install.md.

**Comment by vlj** [comment]
Should be fixed

**Comment by deveee** [comment]
Btw. if you already made some changes with these libraries, maybe we could use external zlib, libpng and libjpeg also on Visual Studio? It will make compilation process a bit faster. I don't see any reason to compile it every time.

It probably should work with libraries which I added to mingw dependencies. Though I didn't check it with VS.

**Comment by vlj** [comment]
Because it requires some "bundling" work : finding/building the lib, zipping them and put them on sourceforge. I think it's safer not to do that right before a release.

**Comment by deveee** [comment]
Libraries available for example here:
http://gnuwin32.sourceforge.net/packages/jpeg.htm
http://gnuwin32.sourceforge.net/packages/libpng.htm
http://gnuwin32.sourceforge.net/packages/zlib.htm

But as I said, I didn't check it with VS.

Make install is now working, so ticket can be closed.

**Comment by vlj** [comment]
And I don't have the right to put a release on sourceforge so it's up to hiker or Auria.

**Comment by vlj** [comment]
Thank for the links
