### ISSUE TITLE
Plane not moving in Island Track

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1910]
I see a plane in island track that is not moving ( I still see a plane taking off).
![20_island-2015 01 20_20 55 10](https://cloud.githubusercontent.com/assets/6138652/5815886/2c1d107c-a0ee-11e4-8a4a-cfde012700c9.png)

**Comment by hiker** [comment]
I think this image might show it better: to the left the plane that moves.
![20_island-2015 01 20_20 56 52](https://cloud.githubusercontent.com/assets/6138652/5815906/79af8676-a0ee-11e4-9e2d-55b496254a32.png)

**Comment by hiker** [comment]
Got an even better screenshot:
H![Uploading 20_island-2015.01.20_21.55.36.png . . .]()
Three planes. The one in front and at the back not moving, the one in the middle is landing.

**Comment by vlj** [comment]
It's not a bug in code, these planes are static in the assets.

**Comment by samuncle** [comment]
It's corrected now
