### ISSUE TITLE
Supertuxkart crashes GTK apps during copy-paste

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1911]
Reported in the forum post:
http://forum.freegamedev.net/viewtopic.php?f=17&t=6045&sid=6d31e53bf3cb0e6dbaf9c9fe8640f7d5&start=50#p62074

It's actually bug in GTK, which crashes when we use deprecated method. But it should be easily workarounded.

It's caused by XConvertSelection() function, original bug report here:
https://bugzilla.gnome.org/show_bug.cgi?id=740613

**Comment by vlj** [comment]
What is the newer method ?

**Comment by deveee** [comment]
In Gnome bugzilla they said that XConvertSelection is fine, but it can't contain None as an argument.

SDL2 does it in this way
```
Atom selection = X11_XInternAtom(display, "SDL_SELECTION", False);
X11_XConvertSelection(display, XA_CLIPBOARD, format, selection, owner,
    CurrentTime);
```

Though paste text from external application doesn't work for me at all in STK.

**Comment by Arthur-D** [comment]
Den 20.01.2015 21:03, skrev Deve:
>
> In Gnome bugzilla they said that XConvertSelection is fine, but it 
> can't contain None as an argument.
>
> SDL2 does it in this way
>
> |Atom selection = X11_XInternAtom(display, "SDL_SELECTION", False);
> X11_XConvertSelection(display, XA_CLIPBOARD, format, selection, owner,
>      CurrentTime);
> |
>
> Though paste text from external application doesn't work for me at all 
> in STK.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/supertuxkart/stk-code/issues/1911#issuecomment-70722600>.
>
Hi, just wanted to note that being able to paste passwords from a 
password manager could be wanted functionality, so breaking it (I've 
used it in the past) shouldn't happen unless we have to. Just wanted to 
throw that in there. :)

**Comment by deveee** [comment]
Arthur, does copy-pase work for you when you copy text from external (non GTK3) application? It doesn't work for me, I can just copy text only internally in STK.

I have it almost working. I mean, it works, but when I get SelectionNotify event, it returns always false. I must find a reason.

**Comment by deveee** [comment]
Should work in current git.
