### ISSUE TITLE
Usage of normal maps requires second UV layer to be created.

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1912]
Right now, you have to create a second UV layer for every object in your track that uses a normal mapped texture. This is really quite inconvenient, as it applies not only to normal maps defined in tracks/trackname/materials.xml, but also those defined globally in stk-assets/textures/materials.xml. So if you want a dirt road, a cobblestone floor, rock wall, wooden hut, etc, you have to make a second UV layer to keep your track from crashing.

IMHO, it would be better to have the game use the first UV layer for normal mapping if there isn't a dedicated layout. AFAICT, basically every normal map in the game has been created to use the same mapping as the diffuse texture anyways.

**Comment by stkAnon** [comment]
After re-exporting chocolate without any problems and finding the cause of my temple arena's crashes, I'm not sure that this is actually an issue. Leaving open for devs to decide.

**Comment by Benau** [comment]
Now please don't even add a 2nd texture coordinate if not using decal, because .spm will discard 2nd TC if no texture is used
