### ISSUE TITLE
Track to dark at start

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1914]
When I start a race, the track is very dark. It becomes bright again the moment 'ready' is shown. I removed all text output (ready, set, go, time, rank, ...). Then the track stays dark till the start of the race (green light). If I try to take a screenshot in-game, the screenshots are all bright (related to showing the text perhaps??). I had to take screenshots of the whole screen to capture the effect:
![dark](https://cloud.githubusercontent.com/assets/6138652/5834508/939937b6-a1b2-11e4-9cd2-1cee255033fc.jpg)
![bright](https://cloud.githubusercontent.com/assets/6138652/5834507/8de5e5d0-a1b2-11e4-86af-91570ec4dda0.jpg)

**Comment by hiker** [comment]
Reverse effect in the intro video: they are bright during the fade in, then get dark. When fading out, it gets brighter again till the new image is shown (i.e. during fade out/int), then it gets dark again). As soon as the subtitles from nolok are shown, the image gets bright again. It gets darker for a split second when the next subtitles are shown.

**Comment by deveee** [comment]
Is this still an issue? Is this on intel HD3000 on windows?

**Comment by qwertychouskie** [comment]
@hiker Is this still an issue?

**Comment by deveee** [comment]
IIRC it was on intel HD3000 and assuming that srgb framebuffer was the reason, it shouldn't be too dark now.
