### ISSUE TITLE
Compiler errors on Mac OS X 10.10

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#1915]
[ 18%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CZipReader.cpp.o
In file included from /Users/tobiasmarkus1/workspace/supertuxkart/stk-code/lib/irrlicht/source/Irrlicht/CZipReader.cpp:24:
/Users/tobiasmarkus1/workspace/supertuxkart/stk-code/lib/irrlicht/../zlib/zlib.h:86:5: error: unknown type name 'z_const'; did you mean
      'const'?
    z_const Bytef *next_in;     /* next input byte */
    ^~~~~~~
    const
/Users/tobiasmarkus1/workspace/supertuxkart/stk-code/lib/irrlicht/../zlib/zlib.h:94:5: error: unknown type name 'z_const'; did you mean
      'const'?
    z_const char *msg;  /* last error message, NULL if no error */
    ^~~~~~~
    const
/Users/tobiasmarkus1/workspace/supertuxkart/stk-code/lib/irrlicht/../zlib/zlib.h:1332:31: error: expected ';' after top level declarator
ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
                              ^
                              ;
/Users/tobiasmarkus1/workspace/supertuxkart/stk-code/lib/irrlicht/../zlib/zlib.h:1731:15: error: unknown type name 'z_crc_t'
ZEXTERN const z_crc_t FAR * ZEXPORT get_crc_table    OF((void));
              ^
4 errors generated.
make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/CZipReader.cpp.o] Error 1
make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
make: *** [all] Error 2

**Comment by vlj** [comment]
AFAIK Auria managed to build on osx

**Comment by auriamg** [comment]
Can you show me how you are building? I recently built on OSX 10.10 without problems

**Comment by tobbi** [comment]
Build log: http://pastebin.com/whm295b3

**Comment by tobbi** [comment]
I don't know what exactly I did, but I managed to build supertuxkart now. Not sure. I will reopen if the problem reoccurs.
