### ISSUE TITLE
Small horizontal lines flickering HD4600

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1916]
If I enable advanced pipeline on HD 4600 latest driver and latest git, I always get small horizontal lines while playing. They change place but they are almost always there flickering (which you can't really see on a screenshot). It's worse on track like Blackhill Mansion and it's always almost the top half of the screen and the bottom half is mostly right.
The game is still pretty beautiful and100% playable so I wouldn't disable advanced pipeline on HD4600. It's not a huge issue for the player, a little bit annoying on some tracks more than others, not that much . I don't know if it's related to another issue.

Zoom + turn on luminosity on your screen and look where the bird is:
![gp](http://i.imgur.com/biYnrnM.png)
![bh](http://imgur.com/LVJJJPa.png)
![addon_paradise-peaks-2014 12 26_14 13 17](https://cloud.githubusercontent.com/assets/9955284/5836955/f319e2a4-a148-11e4-91ae-e148dd2f4f97.png)

**Comment by vlj** [comment]
Do you have any settings enabled beside advanced pipeline?

**Comment by vlj** [comment]
(on Windows right?)

**Comment by math07** [comment]
It's on Windows and it does it anytime advanced pipeline is checked (without any other settings and with other settings).

**Comment by MTres19** [comment]
I have the same problem, but it doesn't seem quite as severe. It seems to appear mostly around where there are point lights in a dark track (like the lanterns above the track in _Old Mine_).

**Comment by deveee** [comment]
Could you post your stdout.log file? It can be found in %appdata%\supertuxkart\0.8.2 directory.

**Comment by MTres19** [comment]
Here you go:
`[info   ] [FileManager]: Data files will be fetched from: 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/'
[info   ] [FileManager]: Data files will be fetched from: 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/'
[info   ] [FileManager]: User directory is 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/po/'.
[verbose  ] translation: GetLocaleInfo langname returns 'en'.
[verbose  ] translation: GetLocaleInfo tryname returns 'US'.
[verbose  ] translation: Env var LANGUAGE = 'en_US'.
[verbose  ] translation: Language 'English (United States)'.
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_no.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
[warn   ] tinygettext: jbo.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_no.po: warning: ignoring, unknown language
[warn   ] tinygettext: sc.po: warning: ignoring, unknown language
[warn   ] tinygettext: sco.po: warning: ignoring, unknown language
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: Intel
[info   ] IrrDriver: OpenGL renderer: Intel(R) HD Graphics 4600
[info   ] IrrDriver: OpenGL version string: 4.3.0 - Build 20.19.15.4424
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: ARB Multi Draw Indirect Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] irr_driver: GLSL supported.
[info   ] Freetype Environment: Loading fonts...
[info   ] Freetype Environment: DPI for Normal Font is 21.
[info   ] Freetype Environment: DPI for Title Font is 36.
[info   ] Freetype Environment: DPI for Digit Font is 32.
[info   ] ScalableFont::loadTTF: Created 15 glyphs supporting 16 characters for high-res digits font Sigmar using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 93 glyphs supporting 150 characters for bold title font Ubuntu using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu using 1 glyph page(s).
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : texturedquad.frag
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : uniformcolortexturedquad.frag
[info   ] shader: Compiling shader : colortexturedquad.vert
[info   ] shader: Compiling shader : colortexturedquad.frag
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
[info   ] addons: Downloading updated addons.xml.
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/assets.xml
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/images/857358965734d813e4cd1.jpg
[warn   ] TrackManager: Track '20_harvest' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 6).
[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_luna/
[error  ] irr_driver: Texture 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_luna/' not found.
[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_mansion/screenshot.jpg
[error  ] irr_driver: Texture 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_mansion/screenshot.jpg' not found.
[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_newton/screenshot.jpg
[error  ] irr_driver: Texture 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_newton/screenshot.jpg' not found.
[warn   ] track: Music information file 'jumping_to_the_stars.music' not found for track 'Las Dunas Stadium' - ignored.

[warn   ] TrackManager: Track 'addon_medieval-cave' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 6).
[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/tracks/test1/screenshot.jpg
[error  ] irr_driver: Texture 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/tracks/test1/screenshot.jpg' not found.
[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/grandprix/
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : object_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : normalmap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_object_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_normalmap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/DiffuseIBL.frag
[info   ] shader: Compiling shader : utils/SpecularIBL.frag
[info   ] shader: Compiling shader : IBL.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/SunMRP.frag
[info   ] shader: Compiling shader : sunlight.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlight.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : object_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : objectref_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : object_unlit.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : splatting.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : objectpass_spheremap.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : detailed_object_pass2.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_objectref_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : instanced_object_unlit.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : instanced_objectpass_spheremap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_detailed_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_grass_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : passthrough.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : tonemap.frag
[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_luna/
[error  ] irr_driver: Texture 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_luna/' not found.
[error  ] icon_button: Texture 'C:\Users\matth_000\Downloads\SuperTuxKart\stk-codeRelease\bld\bin\Release/../../../data/../../stk-assets/wip-tracks/20_luna/' not found!

[warn   ] Irrlicht: Could not open file of texture: C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/tracks/test1/screenshot.jpg
[error  ] irr_driver: Texture 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/tracks/test1/screenshot.jpg' not found.
[error  ] icon_button: Texture 'C:\Users\matth_000\AppData\Roaming/supertuxkart/0.8.2/../addons/tracks/test1/screenshot.jpg' not found!

[verbose  ] RaceManager: Nb of karts=4, ghost karts:0 ai:3 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] ModelDefinitionLoader: LOD group 'pineTree1' is empty
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : importance_sampling_specular.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : fog.frag
[info   ] shader: Compiling shader : sky.vert
[info   ] shader: Compiling shader : sky.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlightscatter.frag
[info   ] shader: Compiling shader : gaussian6v.comp
[info   ] shader: Compiling shader : gaussian6h.comp
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparentfog.frag
[info   ] shader: Compiling shader : pointemitter.vert
[info   ] shader: Compiling shader : particle.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : particle.frag
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[warn   ] SFXManager: Throttling sfx - queue size 101
[info   ] shader: Compiling shader : primitive2dlist.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : billboard.vert
[info   ] shader: Compiling shader : billboard.frag
[info   ] shader: Compiling shader : coloredquad.vert
[info   ] shader: Compiling shader : coloredquad.frag
[info   ] Singleton: Destroyed singleton.
`
And another screenshot...

![zengarden-2016 06 06_21 07 03](https://cloud.githubusercontent.com/assets/18179456/15842915/5262d77a-2c2b-11e6-93ec-59b25ede9b22.png)

It seems to me that it's appearing where fog is being lit by points, but I could be wrong. I also don't think this showed up before I "upgraded" to Windows 10.

**Comment by deveee** [comment]
The log unfortunately doesn't say anything interesting. I will try to reproduce it on my Intel HD4000.

Also you can try to make your drivers more verbose, so that it reports to the console some errors like this:
```
[info   ] shader: Compiling shader : importance_sampling_specular.frag
Mesa: User error: GL_INVALID_VALUE in glTexSubImage2D(xoffset+width)
```
But I have no idea how to enable it on Windows ;) Maybe enable opengl debug context would be enough...

**Comment by MTres19** [comment]
Okay, I installed Arch on a flash drive and compiled STK git and ran it. The lines don't show up, so I think it's a Windows driver problem. Effects level 4 in STK.

`$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
`

**Comment by MTres19** [comment]
Reported on [Intel Communities](https://communities.intel.com/thread/104464).

**Comment by Intel-Engineer** [comment]
Hello,

I have been trying to duplicate this issue, as reported on Intel Communities. Using the same base Graphics driver (.4474) for Win10 64bit, I could not see the issue. I tested with Effects level up to level 6 (no visible graphics issue, yet FPS performance did suffer a bit). My test rig consisted on an Intel NUC6i5SYH (Iris Graphics 540), 16GB DDR4, connected to an Acer B286HK (3840x2160@60hz), yet for the game I was running it at 1920x1080@60hz. 

Upon further analysis, it appears that the game needs to be better optimized for HD Graphics 4600 hardware, since our driver .4474 is unified (designed for 4th, 5th and 6th generation graphics controllers). We'll continue to investigate from our end, and if we find further updates will add them here.

Adding some screen shots for comparison.
![abyss-2016 08 05_09 18 33](https://cloud.githubusercontent.com/assets/20862918/17443405/bb340dc8-5af7-11e6-9c13-f670fdf31fab.png)
![abyss-2016 08 05_09 18 41](https://cloud.githubusercontent.com/assets/20862918/17443413/c671269e-5af7-11e6-9a46-e452520bef60.png)
![menu-2016 08 05_09 19 23](https://cloud.githubusercontent.com/assets/20862918/17443416/ca63c75c-5af7-11e6-921c-718b81cd4d5e.png)

**Comment by MTres19** [comment]
As I mentioned on Intel Communities, no artifacts show up on Linux with the Mesa drivers, on the exact same hardware. But perhaps @deveee would have a better idea what's going on.

**Comment by mathusummut** [comment]
I am experiencing the same issue, so far it has only happened on one track for me, the BlackHill Mansion track. I am running it on Windows 10 on Intel HD 4600. It also happens whenever I enable the "Advanced Pipeline". Here is a screenshot:

![mansion-2016 11 18_13 07 10](https://cloud.githubusercontent.com/assets/7263324/20429599/f78ad230-ad8f-11e6-86e6-fbe13393b679.png)

**Comment by deveee** [comment]
I'm looking at this bug and there are two shaders that may cause it - fog.frag and pointlightscatter.frag. It's most probably the first one, because skybox is unaffected.

@MTres19 Could you confirm it? You can change the last line in fog.frag from:
```FragColor = vec4(fog, factor);```
to for example
```FragColor = vec4(1.0, 0., 0., 0.);```
and look if you still see the horizontal lines. You need to reload shaders in artist debug mode or restart the game.

If yes, then you can do the same in pointlightscatter.frag - set fog to for example:
```Fog = vec4(1.0, 0., 0., 0.);```

There are some computations with exponential functions, so maybe in some cases we get there too small or too big values and then we get a precision error.

**Comment by MTres19** [comment]
I tested both modifications independently and together, but there was no
change besides turning almost everything a dark pink. Maybe the second
change reduced it slightly, but it was very minor if anything at all. I'm
still convinced it's a driver bug.

**Comment by deveee** [comment]
This may be a driver or hardware bug, but we can try to make a workaround or at least disable this feature.

The fog.frag fits perfectly with these screenshots because these horizontal lines start at the fog position and also affect only objects and not skybox. Atm. I don't have any better idea.

**Comment by qwertychouskie** [comment]
Are you sure in doesn't show on the skybox?:
![f78ad230-ad8f-11e6-86e6-fbe13393b679](https://cloud.githubusercontent.com/assets/13989090/22807115/430a71da-eeda-11e6-9a98-40b01fde091b.png)

**Comment by Benau** [comment]
disable computer shader seems to fix this issue

**Comment by MTres19** [comment]
Disabling compute shaders fixed the problem, as Benau suggested.

**Comment by deveee** [comment]
@Benau If you are able to reproduce it, you can return constant value in compute shaders to see if it's a problem with some computations or with compute shaders feature in general. If constant value still causes this issue, then it should be just added to graphics restrictions.

**Comment by Benau** [comment]
Make gaussian6v.comp imageStore(dest, iuv, sum); to imageStore(dest, iuv, vec4(0.0)); works too, but there seems to be nothing wrong about this shader

**Comment by deveee** [comment]
The only difference between gaussian6v and gaussian6h that I found is that the first one has ```glMemoryBarrier(GL_TEXTURE_FETCH_BARRIER_BIT);``` set, and the second one ```glMemoryBarrier(  GL_TEXTURE_FETCH_BARRIER_BIT | GL_SHADER_IMAGE_ACCESS_BARRIER_BIT);```

If you have no idea what's wrong, then just add it to graphics restrictions. I will upgrade my drivers on windows, maybe current version already supports compute shaders, so I will see if HD4000 is affected too.

**Comment by deveee** [comment]
What happens if you add ```memoryBarrierShared();```  before barrier() in the shader?

**Comment by Benau** [comment]
sorry adding memoryBarrierShared() before barrier() doesn't work

Do we GR?

**Comment by deveee** [comment]
I installed current drivers version and unfortunately it still doesn't have compute shaders support, so I can't look how it works for HD4000.

I think yes, just add a GR. Could you make a commit?
