### ISSUE TITLE
CPU @ 100% + strange crash

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#1918]
I have a friend who tested supertuxkart beta with his new computer.

The CPU is at 100% all the time in game (not in menus). Even in tracks like math class
Sometimes stk crash and the following message is displayed
https://nvidia.custhelp.com/app/answers/detail/a_id/3007

The computer used is quite powerful. Here is the configuration
* OS: windows seven
* Motherboard: MSI X99S GAMING 7
* Graphic: ASUS STRIX GTX970-DC2OC-4GD5
* Processor: Intel Core i7-5820K (3.3 GHz)
* Memory: G.Skill RipJaws 16 Go (4x 4 Go) DDR4 2666 MHz
* CPU Cooling: Be Quiet ! Dark Rock 3
* HDD System:
* Samsung SSD 840 EVO 250 Go
* HDD 1To

Any idea why this is happening ? Maybe we should wait beta 2 to be released and retest if the problem was corrected or not

**Comment by samuncle** [comment]
More information about the crash 
http://nvidia.custhelp.com/app/answers/detail/a_id/3007

http://pastebin.com/M9s7K1pE

**Comment by hiker** [comment]
As suggested on irc: try running very  sleepy (http://www.codersnotes.com/sleepy) on stk while it is running. First select the supertuxkart process, then the thread(s) that have a high load, and let it run for a while (10 seconds at least to get a large sample size). This will impact the performance.

A high cpu load can apparently be triggered by the CPU waiting for the GPU (CPU is busy waiting before it can start working on the next frame), so I am not too worried about that.  How do you determine the 100% cpu load? Using the task manager? Running the task manager might be useful to spot any other problems (e.g .swapping - in case of something else is running on the computer).

**Comment by vlj** [comment]
Using as environment variable OMP_WAIT_POLICY=passive reduces the cpu usage for me to 10% (maybe at the cost of performance but it's hard to tell).
Unfortunatly I don't know a "good way" to use env var on Windows outside of VS...

**Comment by hiker** [comment]
In options_screen_ui.cpp we use 
```
#ifdef WIN32
            std::string s=std::string("LANGUAGE=")+selection.c_str();
            _putenv(s.c_str());
...
```
to change the language. Can you try if you can use the same to modify this behaviour at runtime?

**Comment by hiker** [comment]
No feedback received, closing this ticket. Please reopen or comment if this is still an issue.

Thanks!
   Joerg

**Comment by Flakebi** [comment]
It is still an issue, but solving doesn't look trivial because setting `OMP_WAIT_POLICY=passive` doesn't help if it's done after starting stk. One way to solve this issue is setting the environment variable from a launcher or updater.

A quicker way which solves this is setting the variable globally when installing stk. Maybe we should make this optional because it can affects other OpenMP applications too.
