### ISSUE TITLE
Drivers recent enough restriction problem

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1923]
As I see in graphical_restriction.xml, mesa drivers can't be in version lower than 10.3.
  <card contains="Mesa"           os="linux"    version="<10.3"    disable="DriverRecentEnough"/>

I have mesa drivers in version 10.3.2, but when I run STK with using intel graphics card, I see popup window "Your driver version is too old (...)".

[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Ivybridge Mobile 
[info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.3.2

Other thing is that display this popup every time is a bit annoying. Sometimes update mesa is not that easy (for example in current stable Debian) and some people may decide to play it with disabled advanced pipeline.

**Comment by hiker** [comment]
I am testing a similar case in the unit tests:
    assert(Version("1.2.3") <  Version("1.2.3.1"));
and that appears to work. But I'll have a look. f it works without advanced pipeline, then of course the graphical restrictions should just disable the advanced pipeline, and don't show a message.

Re frequency: in my experience with unexperienced people they will miss messages. Eg.. can't remember what the message was when you ask, or their kid has seen and ignored it. So there is a reason for showing it more than once. Perhaps adding an option to disable this message might be good - at least the user then has acknowledged that he is on his own :)

**Comment by deveee** [comment]
Both:
```
    assert(Version("10.3.2")     <  Version("10.3"));
    assert(Version("10.3")     <  Version("10.3.2"));
```
in unit testing return true. Though it fails at:
```
    assert(Version("10.3")     ==  Version("10.3.2"));
```
so it's not that bad.

Probably the easiest workaround is to use ```version="<10.3.0"``` in xml file.

**Comment by deveee** [comment]
Should be fixed in 07dffdcbc2bf35e090c9f681ff3bea5fddd906a2

**Comment by hiker** [comment]
I've added test cases as well. I'll also reopen the ticket, since if it works with mesa and advanced pipeline disabled, then that's what stk should do.

**Comment by hiker** [comment]
Oops, I misread the content, it's fixed.
