### ISSUE TITLE
Expected int but found 'true' for attribute 'enable_high_definition_textures' of node 'Video'

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1924]
I keep getting this message when I start my debug build of 6d7adcf08d37a01362c56f7a1a013728c5384f78:
```
[warn   ] [XMLNode]: WARNING: Expected int but found 'true' for attribute 'enable_high_definition_textures' of node 'Video' in file /home/tomreyn/.config/supertuxkart/0.8.2/config.xml
```

That's even after editing this configuration file, changing the value of this option from "false" to "0". I.e. the game appears to rewrite the configuration file at startup, then goes into interpreting it, which is where this warning is printed.

This warning does not occur when you manually edit the configuration file to set the value of "1".

**Comment by hiker** [comment]
That message should only be shown once (assuming that you quit stk properly and it does not crash or you abort without stk writing the config file). I've changed that attribute from bool to int, but checked that reading the boolean value gives the expected results.

Please reopen if this message should be shown more often - and then also what platform you are on.

Thanks!
   Joerg

**Comment by tomreyn** [comment]
Looks good now (but this option - "enable_..." - is a misnomer).
