### ISSUE TITLE
MusicOggStream Segfault

### ISSUE THREAD

**Issue by Popolon** [supertuxkart/stk-code#1925]
OS : Ubuntu 14.04
Mesa : 10.1.3-ubuntu-0.3

Need to disable texture compression to avoid a display bug (white things near everywhere), Tried different env variables to enable texture compression, no solution works.

On the Egyptian level (shifting sands), the system often (everytime ?) crash at the end line (after the 3rd round), here is the debug output after the crash :
--------------------------------------
Running 64-bit version...
Irrlicht Engine version 1.8.0
Linux 3.13.0-32-lowlatency #57-Ubuntu SMP PREEMPT Tue Jul 15 04:08:59 UTC 2014 x86_64
[debug  ] main: Error messages and other text output will be logged to /home/popolon/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is '/home/popolon/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/popolon/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/popolon/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/popolon/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[debug  ] translation: Env var LANGUAGE = 'fr_FR:fr:zh_CN:en'.
[debug  ] translation: Language 'French (France)'.
tinygettext: jbo.po: warning: ignoring, unknown language
tinygettext: sco.po: warning: ignoring, unknown language
Adding language fallback fr
tinygettext: jbo.po: warning: ignoring, unknown language
tinygettext: sco.po: warning: ignoring, unknown language
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

ATTENTION: option value of option force_s3tc_enable ignored.
[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:

[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:

[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:

[info   ] IrrDriver: OpenGL version: 3.1
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Sandybridge Desktop 
[info   ] IrrDriver: OpenGL version string: 3.1 (Core Profile) Mesa 10.1.3
[info   ] GLDriver: ARB Base Instance enabled
[info   ] GLDriver: ARB Texture Storage enabled
[warn   ] Graphics: Can not find version for '3.1 (Core Profile) Mesa 10.1.3' 'Mesa DRI Intel(R) Sandybridge Desktop ' - ignored.
[info   ] irr_driver: GLSL supported.
[info   ] GUIEngine: scale: 0.512000
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/uniformcolortexturedquad.frag
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/popolon/.local/share/supertuxkart/grandprix/
[info   ] addons: Downloading updated addons.xml.
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/assets.xml
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/images/37944831254c35dccc1ad2.png
[error  ] Kart_Model: Missing wheel information 'front-left' for model 'sara the racer.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] material: Cannot find texture 'motif.png'.
[error  ] material: Cannot find texture 'shoes_gloves.png'.
[error  ] Kart_Model: Missing wheel information 'front-right' for model 'blinky.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'front-left' for model 'blinky.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'rear-right' for model 'blinky.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'rear-left' for model 'blinky.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[warn   ] EventHandler: Error while loading kart 'Chinchila':
[warn   ] Irrlicht: Could not open file of texture: chinch-fur.rgb
[warn   ] EventHandler: Error while loading kart 'Chinchila':
[warn   ] Irrlicht: Could not open file of texture: chinch-skin.rgb
[error  ] Kart_Model: Missing wheel information 'front-right' for model 'nayo.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'front-left' for model 'nayo.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'rear-right' for model 'nayo.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] Kart_Model: Missing wheel information 'rear-left' for model 'nayo.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[info   ] ClientNetworkManager: Host initialized.
[info   ] ClientNetworkManager: Ready !
[info   ] GLWrap: Compiling shader : data/shaders/colortexturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/colortexturedquad.frag
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/encode_normal.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass1.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/encode_normal.frag
[info   ] GLWrap: Compiling shader : data/shaders/objectref_pass1.frag
[info   ] GLWrap: Compiling shader : data/shaders/grass_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/encode_normal.frag
[info   ] GLWrap: Compiling shader : data/shaders/objectref_pass1.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/encode_normal.frag
[info   ] GLWrap: Compiling shader : data/shaders/normalmap.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/decodeNormal.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/DiffuseIBL.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/SpecularIBL.frag
[info   ] GLWrap: Compiling shader : data/shaders/IBL.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/decodeNormal.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/SpecularBRDF.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/DiffuseBRDF.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/sunlight.frag
[info   ] GLWrap: Compiling shader : data/shaders/pointlight.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/decodeNormal.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/SpecularBRDF.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/DiffuseBRDF.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/pointlight.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass2.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/objectref_pass2.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/object_unlit.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/splatting.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/objectpass_spheremap.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/detailledobject_pass2.frag
[info   ] GLWrap: Compiling shader : data/shaders/grass_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getLightFactor.frag
[info   ] GLWrap: Compiling shader : data/shaders/grass_pass2.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/transparent.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getRGBfromCIEXxy.frag
[info   ] GLWrap: Compiling shader : data/shaders/utils/getCIEXYZ.frag
[info   ] GLWrap: Compiling shader : data/shaders/tonemap.frag
[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'grass.jpg'
[warn   ] SFXManager: Throttling sfx - queue size 42
[warn   ] SFXManager: Throttling sfx - queue size 43
[warn   ] SFXManager: Throttling sfx - queue size 44
[warn   ] SFXManager: Throttling sfx - queue size 45
[warn   ] SFXManager: Throttling sfx - queue size 46
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/importance_sampling_specular.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/fog.frag
[info   ] GLWrap: Compiling shader : data/shaders/pointlight.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/pointlightscatter.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/gaussian6v.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/gaussian6h.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/sky.frag
[info   ] GLWrap: Compiling shader : data/shaders/object_pass.vert
[info   ] GLWrap: Compiling shader : data/shaders/transparentfog.frag
[info   ] GLWrap: Compiling shader : data/shaders/billboard.vert
[info   ] GLWrap: Compiling shader : data/shaders/billboard.frag
[info   ] GLWrap: Compiling shader : data/shaders/pointemitter.vert
[info   ] GLWrap: Compiling shader : data/shaders/particle.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/particle.frag
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.frag
[info   ] Singleton: Destroyed singleton.
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[info   ] GLWrap: Compiling shader : data/shaders/primitive2dlist.vert
[info   ] GLWrap: Compiling shader : data/shaders/transparent.frag
[info   ] GLWrap: Compiling shader : data/shaders/screenquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/utils/getPosFromUVDepth.frag
[info   ] GLWrap: Compiling shader : data/shaders/motion_blur.frag
[info   ] This work was NOT networked: This is NOT a network world.
[info   ] Singleton: Destroyed singleton.
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'grass.jpg'
[info   ] Singleton: Destroyed singleton.
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[info   ] This work was NOT networked: This is NOT a network world.
[info   ] Singleton: Destroyed singleton.
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'grass.jpg'
[info   ] Singleton: Destroyed singleton.
[debug  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
Segmentation fault (core dumped)
--------------------------------------

Crashed one time with follower course at the time where you loose is displayed a gdb bt give :

(gdb) bt
#0  0x00007ffff7527c80 in mdct_backward () from ./lib-64/libvorbis.so.0
#1  0x00007ffff75395ff in ?? () from ./lib-64/libvorbis.so.0
#2  0x00007ffff731d300 in ?? () from ./lib-64/libvorbisfile.so.3
#3  0x00007ffff731fbf5 in ov_read_filter () from ./lib-64/libvorbisfile.so.3
#4  0x00007ffff7320014 in ov_read () from ./lib-64/libvorbisfile.so.3
#5  0x000000000099456b in MusicOggStream::streamIntoBuffer(unsigned int) ()
#6  0x000000000099478f in MusicOggStream::update() ()
#7  0x0000000000998cfb in SFXManager::reallyUpdateNow(SFXManager::SFXCommand*) ()
#8  0x0000000000999565 in SFXManager::mainLoop(void*) ()
#9  0x00007ffff7bc4182 in start_thread (arg=0x7fffd6ffc700) at pthread_create.c:312
#10 0x00007ffff536c00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by hiker** [comment]
Hmm - I wonder if the crash might be in a different thread, Can you reproduce this issue, and if so, do a '" thread apply all backtrace all" (iirc) in gdb? This should give the stack trace for all threads, and also local variables.

**Comment by deveee** [comment]
Very similar crash to this bug:
https://github.com/supertuxkart/stk-code/issues/1746#issuecomment-69813883
with this backtrace:
https://gist.github.com/Flakebi/5539eebd0cfa4771bdcc

**Comment by hiker** [comment]
Should be fixed in c37e1eec0df53433cf1cffdd0b263bbcd8169179 to 1e994748cc3f7c86ead7c9d58084bb20f97389ea
Please reopen with new stack trace if it should still happen.
