### ISSUE TITLE
Xue oriented incorrectly during jumps

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1926]
![screenshot from 2015-01-24 19 58 09](https://cloud.githubusercontent.com/assets/8258259/5890160/5ea440a2-a403-11e4-8981-c7e2663229d8.png)

**Comment by vlj** [comment]
I did the animation on purpose. If xue was above the kart her animation would be barely visible at all.

**Comment by hiker** [comment]
While I agree with the reasons, I find this animation quite ... difficult to see. To me it looked more like Xue is made of rubber which is pulled in different direction than what it actually is (holding on with one hand ... I think). Imho the animation is way too fast.

**Comment by stkAnon** [comment]
IHMO the animation was fine when it was only vertical movement. I think I was able to tell what was happening basically immediately after seeing it for the first time, especially since I could look backwards at the kart.

This one would probably be cooler were it not for the fact that it gets cut into and out of without any kind of transition. As it is right now, I thought that some kind of armature glitch rotated her by 90 degrees.

That's just my experience playing the game though.

**Comment by hiker** [comment]
Postponing - while it is indeed pretty bad looking, it's not a release blocker.

**Comment by Benau** [comment]
you can see if now looks better ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)![](https://cdn.lihkg.com/assets/faces/mouse/bye.gif)
