### ISSUE TITLE
Missing face in chocolate

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#1928]
![screenshot from 2015-01-24 20 02 09](https://cloud.githubusercontent.com/assets/8258259/5890174/fbc2b332-a403-11e4-903f-c368f0815574.png)
![screenshot from 2015-01-24 20 02 18](https://cloud.githubusercontent.com/assets/8258259/5890175/fcb4ea3a-a403-11e4-8e6c-1961a698a4bc.png)

**Comment by auriamg** [comment]
Hi, maybe you couldcomment a bit what is the issue? Looking at the screenshots I'm not sure what the issue is. In the first screenshot the rock is oddly-shaped but there doesn't seem to be missing faces. In the second screenshot I'm not sure what is the problem

**Comment by stkAnon** [comment]
In the first screenshot, you can see the sky through underside of the ramp because there's no face there. The second screenshot is just to make the location clearer.

**Comment by samuncle** [comment]
Hi, I checked out. Apparently the face was there at the beginning but then removed probably because I selected its with other stuff and deleted them without realizing it.

Now it's corrected and commited
Thanks for the reporting stkAnon
