### ISSUE TITLE
Model 20_sara_the_wizard lacks shoes_gloves.png

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1930]
```
[warn   ] Material: Cannot determine texture full path : <shoes_gloves.png>
[error  ] material: Cannot find texture 'shoes_gloves.png'.
```

The 20_sara_the_wizard model lacks a copy of the shoes_gloves.png material file it references. sara_the_racer and the snowmountain track also reference this file and actually have it available.
```
tomreyn@atibox:~/SCM/stk-assets$ svn info | grep ^Rev
Revision: 15983

tomreyn@atibox:~/SCM/stk-assets$ rgrep -IF --exclude-dir=.svn 'shoes_gloves.png' .
./karts/20_sara_the_wizard/materials.xml:  <material name="shoes_gloves.png" gloss-map="shoes_gloves_gloss.png"/>
./karts/20_sara_the_racer/materials.xml:  <material name="shoes_gloves.png" gloss-map="shoes_gloves_gloss.png"/>
./tracks/snowmountain/materials.xml:  <material name="shoes_gloves.png" gloss-map="shoes_gloves_gloss.png"/>
./tracks/snowmountain/materials.xml:  <material name="shoes_gloves.png" gloss-map="shoes_gloves_gloss.png"/>

tomreyn@atibox:~/SCM/stk-assets$ find . -name shoes_gloves.png
./karts/20_sara_the_racer/shoes_gloves.png
./tracks/snowmountain/shoes_gloves.png

tomreyn@atibox:~/SCM/stk-assets$ 
```
(Blank lines added to improve readability.)

**Comment by akien-mga** [comment]
I confirm this with 0.8.2-beta2.

**Comment by samuncle** [comment]
It's a known issue :(.
Sara the wizard has no gloves but for some reason the reference is kept in
blender and exported.

Only sara with the blue racing suit use it

**Comment by akien-mga** [comment]
@samuncle Note that I edited my above post, I get more error messages than just missing gloves:
```
[error  ] Kart_Model: Missing wheel information 'front-left' for model 'sara the racer.b3d'.
[error  ] Kart_Model: This can be ignored, but the wheels will not rotate.
[error  ] material: Cannot find texture 'motif.png'.
[error  ] material: Cannot find texture 'shoes_gloves.png'.
```

**Comment by hiker** [comment]
Afaik the exporter was fixed and we only need to re-export (or perhaps we need to dig into blender to find the reference)? For now assigning to @samuncle , please let me know if this is an issue in stk.

**Comment by samuncle** [comment]
I have re exported sara the wizard and apparently it doesn't work :(

**Comment by samuncle** [comment]
edit I finally edited manually the values in blender and now it's okay :)
