### ISSUE TITLE
Shared high score for Egg Hunt

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#1933]
Make high score of Egg Hunt common/shared to all levels of difficulty, because it is never different from one level of difficulty to another.

**Comment by deveee** [comment]
In every one difficulty level (Easy, Medium, Hard), eggs are placed (or at least can be placed) in different places. Only some eggs are common. Shared highscore doesn't have sense because collect eggs on hard difficulty level can take much more time than on easy.
