### ISSUE TITLE
Build STK with gcc/MinGW on Windows: "internal compiler error: Segmentation fault"

### ISSUE THREAD

**Issue by CreativeForge** [supertuxkart/stk-code#1934]
I'm using Code::Blocks on Windows. I'm not able to build STK with gcc.

Console output:
||=== Build: all in SuperTuxKart (compiler: GNU GCC Compiler) ===|
K:\Name\GitHub\SuperTuxKart\stk-code\lib\bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp||In member function 'virtual void btConnectivityProcessor::processTriangle(btVector3*, int, int)':|
K:\Name\GitHub\SuperTuxKart\stk-code\lib\bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp|310|internal compiler error: Segmentation fault|
K:\Name\GitHub\SuperTuxKart\stk-code\lib\bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp|310|internal compiler error: Aborted|
lib\bullet\CMakeFiles\bulletcollision.dir\build.make|654|recipe for target 'lib/bullet/CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj' failed|
CMakeFiles\Makefile2|150|recipe for target 'lib/bullet/CMakeFiles/bulletcollision.dir/all' failed|
K:\Name\GitHub\SuperTuxKart\stk-code\build\Makefile|116|recipe for target 'all' failed|
||=== Build failed: 5 error(s), 0 warning(s) (0 minute(s), 2 second(s)) ===|

**Comment by deveee** [comment]
This is bug in compiler. You must compile it without optimizations (debug version) or use mingw-w64, which has gcc in more recent version (4.9.2 iirc). It can be downloaded here:
http://sourceforge.net/projects/mingw-w64/files/latest/download

**Comment by deveee** [comment]
Can you confirm that it works for you with newer compiler version?

**Comment by CreativeForge** [comment]
Yep it works like a charm!
