### ISSUE TITLE
Zipper effect is not assigned properly in multiplayer game

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#1937]
When first player uses zipper, effect is displayed for both players. When second player uses zipper, effect isn't displayed at all.

![zrzut ekranu z 2015-01-27 19 46 04](https://cloud.githubusercontent.com/assets/5108558/5924619/8dc6d438-a65d-11e4-8cfc-a831c1519bfa.png)
![zrzut ekranu z 2015-01-27 19 47 49](https://cloud.githubusercontent.com/assets/5108558/5924620/8dcbde06-a65d-11e4-9352-4712db3146a9.png)

**Comment by vlj** [comment]
Postponed for 0.8.3, easy fix with cam = Camera::getActiveCamera()->getIndex() doesnt work so code need non trivial fix

**Comment by Flakebi** [comment]
It works now better for both players, so the original issue is fixed.
But the zipper effect looks still more ugly (and wobbly) than in singleplayer.
