### ISSUE TITLE
Strange lighting in the kart preview of the kart selection screen

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#1943]
I'm seeing this with 0.8.2-beta2, both using my Intel chipset (mesa/intel) and Nvidia GPU (nvidia 346.35).
OS: Mageia 5 64bit, kernel 3.18.3, mesa 10.4.3

![stk-beastie png](https://cloud.githubusercontent.com/assets/4701338/5977961/75e899a0-a89c-11e4-92de-ebb314763248.jpg)
![stk-puffy png](https://cloud.githubusercontent.com/assets/4701338/5977962/775979da-a89c-11e4-8138-f38db8d8c641.jpg)
![stk-wilber png](https://cloud.githubusercontent.com/assets/4701338/5977966/78ee5e32-a89c-11e4-83a9-bd9920cf326c.jpg)

The lighting looks just fine in game, but there seems to be something off in the kart selection menu.

**Comment by MarkkusCraft123** [comment]
This happens on my computer, the karts have to be redone to have the new lighting.

**Comment by auriamg** [comment]
The kart selection screen does not use exactly the same lighting settings as are used in-game, we could probably tweak kart selection screen parameters to make it look closer to what it looks like in-game. But also note that no 2 tracks have the exact same lighting, anyway

**Comment by deveee** [comment]
It should look better now
