### ISSUE TITLE
Black textures or full black screen

### ISSUE THREAD

**Issue by Matthias84** [supertuxkart/stk-code#1944]
Hi,

thank you folks for giving STK such great eyecandy, this is pretty awesome! :)
Unfortunatly one of my PCs has the problem, that either the whole screen is black (if you enable additional effects) or that at least the textures have black artifacts (if effects disabled)
![bildschirmfoto vom 2015-01-31 11 06 12](https://cloud.githubusercontent.com/assets/217511/5989980/02600f44-a99c-11e4-9e9a-f3d911aeace6.png)
![bildschirmfoto vom 2015-01-31 11 02 45](https://cloud.githubusercontent.com/assets/217511/5989981/0827a086-a99c-11e4-9734-3f091181c8ad.png)

If I can help to find the problem, please give me a ping.

This happens on a Linux Mint 17.1 x64 with AMD/ATI Turks PRO [Radeon HD 6570/7570/8550] using xserver-xorg-video-ati 1.7.3 and a dual screen setup. GLX details:
> OpenGL vendor string: X.Org
> OpenGL renderer string: Gallium 0.4 on AMD TURKS
> OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
> OpenGL core profile shading language version string: 3.30
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 10.1.3
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:

**Comment by hiker** [comment]
Same issue as #1945 - could you confirm this?

**Comment by hiker** [comment]
Closing this since we received no feedback (and updating the driver should fix it). Please comment on this ticket if it's still an issue.

Thanks!
   Joerg
