### ISSUE TITLE
Carts invisible at gallery

### ISSUE THREAD

**Issue by Matthias84** [supertuxkart/stk-code#1945]
Hi,

another bug I noticed, is that the karts aren't visible at the gallery where you usually pick them:
![bildschirmfoto vom 2015-01-31 11 02 01](https://cloud.githubusercontent.com/assets/217511/5989994/ce8dd66e-a99c-11e4-8f11-4a93d566c719.png)

This happens on a Linux Mint 17.1 x64 with AMD/ATI Turks PRO [Radeon HD 6570/7570/8550] using xserver-xorg-video-ati 1.7.3 and a dual screen setup. GLX details:
> OpenGL vendor string: X.Org
> OpenGL renderer string: Gallium 0.4 on AMD TURKS
> OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
> OpenGL core profile shading language version string: 3.30
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 10.1.3
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:

**Comment by hiker** [comment]
Your mesa appears to be too old, and @vlj

**Comment by hiker** [comment]
Closing since we received no feedback (and it should work as far as we know). Please comment on this ticket if this should still be an issue.

Thanks!
   Joerg
