### ISSUE TITLE
Add a reset password feature in game

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1946]
Hey,
Congratulation for releasing beta 2 !

1- As an improvement, I think an option in game to reset our password is important or at least a link to the stkaddons website.
2 - Are accounts still tied to the accounts website ? I reset my password on 
http://stkaddons.net/password-reset.php but the game still says the new password is invalid. This might be a bug.

**Comment by konstin** [comment]
to 2): Retry at http://addons.supertuxkart.net

**Comment by math07** [comment]
konstin :Thanks 2) isn't a bug then.

For 1), I see two options :
In those two screens, there could be a label Forgot password? with the website link or a button Forgot password? that opens a pop up in game to enter name/email/captcha and send the email.
![a1](https://cloud.githubusercontent.com/assets/9955284/5992683/597e1766-aa01-11e4-9404-14c5007a9c9e.png)
![a2](https://cloud.githubusercontent.com/assets/9955284/5992684/607b4a48-aa01-11e4-831e-c4d0a1d944bd.png)



In the login screen where there is the

**Comment by yehudaclinton** [comment]
but what if i forgot my username, so now i cant make new account with that email
is there any way to reset with just email address

**Comment by qwertychouskie** [comment]
Fixed in https://github.com/supertuxkart/stk-code/pull/3252.
