### ISSUE TITLE
Duplicate math class beta 2

### ISSUE THREAD

**Issue by math07** [supertuxkart/stk-code#1947]
Windows 8 beta 2, I don't know if math class 2 took the place of another map or if it's only a duplicate. I have 20 standard unique maps(which means 21 with the second math class).
![image](https://cloud.githubusercontent.com/assets/9955284/5992749/1b2646b6-aa04-11e4-8ce1-3cf9226985a8.png)

**Comment by deveee** [comment]
As I see it's just a packaging issue. In "data" directory you cen see "olivermath" and "olivermath1" directories. Someone probably copied it in his local system to test something and forgot about it during creating package.

**Comment by math07** [comment]
Great ! :)

**Comment by hiker** [comment]
Yes, I had an additional copy in my checked out repo (for testing the last-lap-faster music). So you can tell the difference by the music that is being played, olivermath1 uses iirc the cocoa music.

**Comment by hiker** [comment]
I'll close this once the faster-music warning is fixed (then I'll remove the second math class track).

**Comment by hiker** [comment]
OK, my work on last lap music is finished, and I have removed that test track :)
