### ISSUE TITLE
STK doesnt prevent 0x0 resolution

### ISSUE THREAD

**Issue by vlj** [supertuxkart/stk-code#1948]
If I set a 0 x 0 resolution from config file, STK will try to use it everywhere (and then crash) in windowed mode.
STK init code should ensure that the resolution is "valid" even in windowed mode.

**Comment by deveee** [comment]
Not sure if this is that important. It shouldn't happen if you don't modify manually config file.

We can just check in irr_driver if remembered size is larger than 0 and smaller than max available resolution.

**Comment by konstin** [comment]
If someone enters an invalid value in a config file and the program crashes, then it is definitely not the program fault.

**Comment by auriamg** [comment]
Removing "major" priority since manually modifying the config file is not normal use. If someone wants to add some validation, though, that can't hurt

**Comment by hiker** [comment]
Related to #2151 - we should just prevent any smaller resolutions than our minimum supported one (unless artist debug mode is enabled :) )

**Comment by deveee** [comment]
I think this is working now. I added some code just after 0.9 release in irr_driver to check if resolution is larger than (0, 0).
