### ISSUE TITLE
Addons: Profile URL can be javascript code

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1953]
The profile URL (users' homepage) can be a javascript: initiated URL. allowing users to inject client side script code into the DOM. Look at the homepage given for the "demo" user for an example.

**Comment by konstin** [comment]
This isn't a problem in the STK core but of [leyyin's stkaddons version](https://github.com/leyyin/stkaddons). But as there is no bug tracker in that repository, you can use https://github.com/supertuxkart/stkaddons for reporting bugs related to stkaddons.

**Comment by tomreyn** [comment]
Thanks for the hint, konstin, I've re-posted there so I guess we can close _this_ one.
