### ISSUE TITLE
Font cut off on the menu

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stk-code#1954]
On my 1680x1050 resolution (windowed mode, but this should not matter I guess), the menu text is sometimes cut off to the top:

![Screenshot](http://i.imgur.com/IAlm9mj.png)

**Comment by tomreyn** [comment]
This shows more menu rendering issues (maybe related):

http://i.imgur.com/uojeopn.png

**Comment by tomreyn** [comment]
Actually this _is_ related to whether it's windowed or full screen. Full screen does not show these issues, windowed does.

**Comment by deveee** [comment]
It's probably because you run it in windowed mode and you set max available resolution in settings. In practice your game window is smaller than your whole screen (for example because of decorations). But STK still thinks that window has dimensions 1680x1050.

When I looked at this last time, I didn't find easy way to get real window dimensions when it is already created. This would probably need modifications in irrlicht.

Can you confirm that 1680x1050 is your max availabie resolution? And what's your OS?

**Comment by tomreyn** [comment]
1680x1050 is indeed the highest resolution I have available, and the window does not fit the screen properly. But yes, it tries to, which seems to be the root cause. And your explanation sounds logical to me. (It also still sounds like a bug to me, if in Irrlicht and not STK).

**Comment by deveee** [comment]
This patch should solve it on linux:

```
diff --git a/src/graphics/irr_driver.cpp b/src/graphics/irr_driver.cpp
index a209d55..0e48bcd 100644
--- a/src/graphics/irr_driver.cpp
+++ b/src/graphics/irr_driver.cpp
@@ -478,8 +478,20 @@ void IrrDriver::initDevice()
     m_gui_env       = m_device->getGUIEnvironment();
     m_video_driver  = m_device->getVideoDriver();
     m_sync = 0;
-    CVS->init();
+    
+#if defined(__linux__) && !defined(ANDROID)            
+    const video::SExposedVideoData& videoData = m_video_driver->getExposedVideoData();
+    XWindowAttributes wa;
 
+    Display* display = (Display*)videoData.OpenGLLinux.X11Display;
+    Window window = videoData.OpenGLLinux.X11Window;
+
+    XGetWindowAttributes(display, window, &wa);
+    UserConfigParams::m_width = wa.width;
+    UserConfigParams::m_height = wa.height;
+#endif    
+
+    CVS->init();
 
     if (UserConfigParams::m_shadows_resolution != 0 &&
         (UserConfigParams::m_shadows_resolution < 512 ||

```

Though I really don't like to place linux-specific code to irr_driver. This everything should be done in irrlicht. Maybe I will write function to report current window dimensions.

And this change has one disadventage. Real window size will be remembered in config file instead of selected screen resolution. And then restored in next run.

**Comment by auriamg** [comment]
This patch is a good start, though the fact that it will save the wrong value is somewhat problematic

**Comment by auriamg** [comment]
A better fix would perhaps be to alter the code inside irrlicht that opens the window, so that the requested size is used for "inner window size" (not counting decorations)

**Comment by hiker** [comment]
Is this reproducible all the time? Samuncle just reported the same problem, and he does not change resolution, so it might be that we broke this recently somehow (though in samuncle's case it does not appear to be reproducible). If it's reproducible for someone, could you try to bisect it, e.g. see if it happened (say) 1 month ago, and if not, find the commit that introduced the problem.

**Comment by deveee** [comment]
It's not reproducible all the time. It depends on how window is created. Some window managers create window in max available space (smaller than screen size) and this causes issues. STK thinks that window has 1680x1050, but without decorations and panel it has for example 1600x1050. 
Other window managers create window in precisely this size which we declared (window with decorations is larger than screen size). It's better for us (STK has proper window size), but worse for player (part of window is not visible). 
And some window managers such as Gnome sometimes can create window larger than screen and sometimes not :)

**Comment by hiker** [comment]
How does the 3d rendering handle this? If the available/inner size is smaller than expected, is part of the race GUI missing?

**Comment by deveee** [comment]
Yes, part of the gui is missing (eg. part of the map). Example screenshots:
![zrzut ekranu z 2015-02-17 17 46 07](https://cloud.githubusercontent.com/assets/5108558/6232578/35e5b8c6-b6cd-11e4-935a-49d478b22f4c.png)
![zrzut ekranu z 2015-02-17 17 45 49](https://cloud.githubusercontent.com/assets/5108558/6232582/44506a96-b6cd-11e4-9513-6e2397b932ab.png)

I have slightly better and simplier patch which should work also in other systems (we can just read width and height from irrlicht). But still there is a problem that UserConfigParams::m_width and UserConfigParams::m_height are override by real window size and then they are saved in config file. Any ideas what to do? Create m_width and m_height variables in irr_driver and use it in all places?

```
diff --git a/lib/irrlicht/include/IrrlichtDevice.h b/lib/irrlicht/include/IrrlichtDevice.h
index 9d4031e..173333a 100644
--- a/lib/irrlicht/include/IrrlichtDevice.h
+++ b/lib/irrlicht/include/IrrlichtDevice.h
@@ -181,6 +181,8 @@ namespace irr
 		//! Checks if the Irrlicht window is running in fullscreen mode
 		/** \return True if window is fullscreen. */
 		virtual bool isFullscreen() const = 0;
+		
+		virtual void getWindowDimensions(int* w, int* h) const = 0;
 
 		//! Get the current color format of the window
 		/** \return Color format of the window. */
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp
index 3ae35b2..19210ed 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp
@@ -343,6 +343,13 @@ bool CIrrDeviceStub::isFullscreen() const
 }
 
 
+void CIrrDeviceStub::getWindowDimensions(int* w, int* h) const
+{
+	*w = CreationParams.WindowSize.Width;
+	*h = CreationParams.WindowSize.Height;
+}
+
+
 //! returns color format
 video::ECOLOR_FORMAT CIrrDeviceStub::getColorFormat() const
 {
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.h b/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.h
index ce4229b..0747daf 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.h
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.h
@@ -112,6 +112,8 @@ namespace irr
 
 		//! Checks if the window is running in fullscreen mode.
 		virtual bool isFullscreen() const;
+		
+		virtual void getWindowDimensions(int* w, int* h) const;
 
 		//! get color format of the current window
 		virtual video::ECOLOR_FORMAT getColorFormat() const;
diff --git a/src/graphics/irr_driver.cpp b/src/graphics/irr_driver.cpp
index a209d55..f48aa26 100644
--- a/src/graphics/irr_driver.cpp
+++ b/src/graphics/irr_driver.cpp
@@ -478,6 +478,16 @@ void IrrDriver::initDevice()
     m_gui_env       = m_device->getGUIEnvironment();
     m_video_driver  = m_device->getVideoDriver();
     m_sync = 0;
+    
+    int w, h;
+    m_device->getWindowDimensions(&w, &h);
+
+    if (w > 0 && h > 0)
+    {
+        UserConfigParams::m_width = w;
+        UserConfigParams::m_height = h;
+    }
+
     CVS->init();
 
 
```

**Comment by auriamg** [comment]
This seems like a better approach, but there is still one concern : the value is saved to the user config file, which if I'm not wrong means the window may shrink a little everytime the game is opened. Maybe the proper fix is to have another set of variables "actual_width" and "actual_height", that we would use everywhere but not save to the config file. This way we can handle if the OS gives us a size different from what we asked. How does that sound?

**Comment by hiker** [comment]
I'd suggest that we do a thorough fix of that (see #1986): add a separate object that would store three resolutions: 
- resolution to request from the OS
- resolution (and position?) to use for GUI rendering (for #1986) - on "extra-wide" resolution where the gui would just look too odd, we would only use part of the screen (e.g. right monitor) for the GUI, the rest will just show the background.
- resolution to use for 3d rendering (including race GUI of course).
Since this change is quite a lot of work (I found 94 occurences of UserConfigParams::m_width, each needs to be changed with the 'right' width :(  ), and not really a release blocker, I'll postpone this till the next release.

**Comment by auriamg** [comment]
I have pushed changes to branch SpeedometerFix that help a lot on this front, any testing is welcome

**Comment by tomreyn** [comment]
Looks good to me, no more cut off fonts for what i can tell. Thanks!
