### ISSUE TITLE
A few music bugs

### ISSUE THREAD

**Issue by Odd0002** [supertuxkart/stk-code#1955]
Bugs encountered so far:
Music stops playing after finishing race
Music stops playing when starting 3rd lap

**Comment by hiker** [comment]
Re starting 3rd laps - which track, how many laps all in all?

**Comment by Odd0002** [comment]
Chocolate track, 3 laps in all, 3 other karts if I remember correctly.
Not sure if it still happens, haven't tested.

**Comment by Flakebi** [comment]
That's probably a problem with the last lap sound (as I commented [here](https://github.com/supertuxkart/stk-code/issues/1613#issuecomment-73054745)).
I think the music doesn't stop/get's quieter when the sound is deactivated (there are other issues then).

**Comment by hiker** [comment]
Could you try with latest master if this is still an issue? It was most likely related to the last-lap music, and I hope this is all fixed now. As is the missing music after finishing the race.

**Comment by hiker** [comment]
Appears to be fixed, so I am closing this now. Please comment on this ticket if there should still be an issue.

Thanks!
   Joerg
