### ISSUE TITLE
Game shows wireframes after resume on Lubuntu 14 - 64 bit

### ISSUE THREAD

**Issue by Aikidouke** [supertuxkart/stk-code#1965]
PC was suspended for several hours. On Wake, tried to play STK (supertuxkart      0.8.1-2) and all graphics were wireframe representations. GPU is NVIDIA GeForce 210.

**Comment by vlj** [comment]
This looks like a driver bug

**Comment by Aikidouke** [comment]
Ok. Thank you!

**Comment by hiker** [comment]
Closing this, I don't think there's much we can do about that.
