### ISSUE TITLE
Using Transifex for translation

### ISSUE THREAD

**Issue by SafaAlfulaij** [supertuxkart/stk-code#1970]
So, Launchpad isn't designed for localization uses, It's interface is really bad (for translating).
I suggest moving to Transifex as its main usage is localization. Many projects are in there.
I can help with a script to grab the translation files if you want.

**Comment by gunchleoc** [comment]
+1

Transifex does fuzzy matches, so when you fix a typo the translation won't be trashed. It is also pretty easy to do set uppushing/pulling, independent of the version control system.

Also, no timeout errors ;)

IMHO we should wait until after the current release though, because it might confuse the process for both developers and translators to do the move now.

**Comment by hiker** [comment]
Certainly no changes for the next release, after that we will have a look.

**Comment by auriamg** [comment]
Given that Launchpad is now crashing so often as to be almost completely unusable, I vote +1 for this

**Comment by gunchleoc** [comment]
Useful links:

http://docs.transifex.com/developer/client/

http://svn.wildfiregames.com/public/ps/trunk/source/tools/i18n/

The basic process is like this:

- Create a project on Transifex and upload the template
- Install the Transifex client on developers' local machines
- Create a .tx/config in the source code
- Add a configuration for the template.

Translation synchronization is then done with a few simple commands.

There is also an option to have an automatic pocess to pull translations off Transifex, but it will only trigger when translations reach 100%.

**Comment by auriamg** [comment]
I am already familiar with Transifex from another project, actually, and I agree it works a LOT better than launchpad.

To get the ball rolling, I have quickly setup a basic STK setup on Transifex : https://www.transifex.com/projects/p/supertuxkart/ . NOT OFFICIEL YET, please do not submit translations there at this time.

@hiker : I have completed the french translation on Launchpad, but the process was so painful that I think most translators will just give up translating... so even though we're super close to the release it may still be worth switching - in 10 minutes I got it fully working and it works so much better than launchpad that I think this gives us a much better chance at actually getting translations

**Comment by gunchleoc** [comment]
I am working on an automated script for Widelands (we have just moved). It is GPL2+, so please feel free to steal anything you can use from it. You will have to adapt the bazaar stuff to git in any case.

http://bazaar.launchpad.net/~widelands-dev/widelands/synchronize_translations/view/head:/utils/merge_and_push_translations.sh

The Widelands translators guide is here: https://wl.widelands.org/wiki/TranslatingWidelands/. Again, please feel free to copy anything useful for the STK Wiki.

**Comment by hiker** [comment]
Sorry, my comment yesterday didn't make it. I had no idea that launchpad is that unusable (I only downloaded translations, and that worked). Then we should indeed migrate.

**Comment by auriamg** [comment]
The transition to Transifex is now complete

**Comment by gunchleoc** [comment]
Thanks for moving :)

What about the addons translation? Or are you waiting until you get the new server up?

I think it would also be good to have a glossary for frequent terms. If you would give me the powers, I would take care of it.

**Comment by leyyin** [comment]
@gunchleoc the new server is up and running at http://addons.supertuxkart.net/.
Yes, I should generate the new locales strings for the addons server, as they are very old now.

**Comment by gunchleoc** [comment]
I was just thinking, if there are a number of common strings with the old add-on server, it might be worth it to load them to Transifex as well, as an archive. This way, the old translations willbe available in the translation memory and speed up the new translation.
