### ISSUE TITLE
Music is laggy and breaks sometimes when sounds are disabled

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1972]
When music is enabled but sound is disabled, there are some strange issues:
Mostly when sound should be played (e. g. from a bowling ball or a zipper), the music gets laggy or even stops completely and prints "Music not playing when it should be. Source state: 4116". The easiest way I found to reproduce it is racing in chocolate above the wooden bridge, where normally a wooden sound is played.

The problem can be reduced by adding `alGetError()` in audio/sfx_openal.cpp:L386 before the `if`, or commenting out that line. That still doesn't solve the problem, but it gets more unlikely that the music stops.

**Comment by hiker** [comment]
Yes, it appears some sfx is still played (well, tried to be played), which then messes up everything else. Appears to be triggered also by just skidding.
