### ISSUE TITLE
Crash when changing resolution to 1600 x 900

### ISSUE THREAD

**Issue by skeltont** [supertuxkart/stk-code#1974]
In version 0.8.2, on Windows 7 64-bit. Changed resolution and crash window came up. Prompt says to press Ctrl+C to copy problem description to post, but was not able to get it to work. 

I took a screenshot and attached it here. 

![resolution_crash](https://cloud.githubusercontent.com/assets/4512337/6142670/6db9b2b0-b16f-11e4-9a3f-f42afc950c55.JPG)

**Comment by auriamg** [comment]
Hi, was fullscreen enabled before/after the resolution change? i.e. was it a fullscreen-to-fullscreen change, windowed-to-fullscreen, fullscreen-to-windowed, windowed-to-windowed. (if you can test a few combinations, maybe you could test if all or only some of these combinations crash? also it it's related to some specific resolutions or if all of them crash)

**Comment by skeltont** [comment]
Hi Auria,

I'm sorry for the late reply, my main inbox didn't catch this notification.

I have been playing in windowed mode since I initially set it up, so fullscreen was never set or unset in this session. I've since been unable to recreate this bug, but I will spend some time here in the next couple days just running through some more resolution changes. I will post again on here with further information if I can. Thank you for the quick reply :)

**Comment by deveee** [comment]
This crash occured in beta or alpha version and also there is totally no information what could cause it.

Please reopen if you are able to reproduce it with current stable version 0.9.1. Also if you could provide backtrace log from debugger, this would help a lot.
