### ISSUE TITLE
English appears twice in language list

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#1984]
Probably US and UK english?

**Comment by deveee** [comment]
I have three different english languages in my language list:
![zrzut ekranu z 2015-02-15 09 03 18](https://cloud.githubusercontent.com/assets/5108558/6202537/9db76e78-b4f1-11e4-9313-c78970a64c1d.png)

Australia and Great Britain are added from .po files. And English which is default language (without .po file), manually added in translation.cpp file.

**Comment by auriamg** [comment]
Very weird, I don't see the same thing as you

![stk_langs](https://cloud.githubusercontent.com/assets/4296971/6204127/44be194a-b50d-11e4-970e-adfa8c806576.jpg)

**Comment by deveee** [comment]
Did you check it with original translations? I noticed that you were 
experimenting with Transifex. Maybe it has different header or file 
name? Though these names are hardcoded in tinygettext...
