### ISSUE TITLE
"Enable handicapped users" ?

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#1985]
I find the string "Enable handicapped users" confusing, it seems to mean "Enable handicapped users to play the game", i.e. it seems to activate accessiblity features for people with disabilities. I suggest "Enable per-player handicaps", how does that sound?

**Comment by gunchleoc** [comment]
I mistranslated this just as you stated. I don't really understand the second string either, what are these handicaps?

**Comment by Flakebi** [comment]
Auria, your suggestion is much better.

In multiplayer games, you can "handicap" players (they have less speed, it takes more time to rescue, etc.) so it makes more fun to play in multiplayer with uneven skilled friends or kids. There's a checkbox in the settings that enables or disables this feature with that label.
Putting an explanation in a comment would be nice to help translators.

There's also another string in the kart selection screen (iirc "%s (handicapped)")  that labels a player that will get a handicap in the game.
