### ISSUE TITLE
Supporting ultra-wide resolutions (Eyefinity)

### ISSUE THREAD

**Issue by thamlett** [supertuxkart/stk-code#1986]
Currently, when an Eyefinity resolution is used, the game throws the GUI out of whack.
![screenshot 66](https://cloud.githubusercontent.com/assets/6759957/6206767/3cc32f6a-b557-11e4-90cc-a01928f730d2.png)
![screenshot 67](https://cloud.githubusercontent.com/assets/6759957/6206766/3cc0ebf6-b557-11e4-813f-e457b0bf8888.png)

**Comment by hiker** [comment]
This is for 5040x1050 resolution. I am not sure that we can scale the gui that well, but one options would be to discover if the aspect ratio is larger than a certain ratio, to use only a certain subsection (right part of the screen). This could tie in with #1954 - add a new object that returns 'gui' resolution (vs. screen resolution) e.g. without decorations.

**Comment by dumaosen** [comment]
I don't know whether 5040x1050 is ok, but in 3840x1050 it looks great with https://github.com/supertuxkart/stk-code/pull/3881.

**Comment by dumaosen** [comment]
Now close it please. I think it has been fixed by me.
