### ISSUE TITLE
Kart stops accelerating when closing a dialogue box

### ISSUE THREAD

**Issue by Rnuomer** [supertuxkart/stk-code#1989]
When STK is configured to take a gamepad button as both "Accelerate" and "Select", and the game throws a dialogue window in your face (e.g. from pausing, tutorial message or pressing "fire" when near a track in story mode), the game will forget you still have Accelerate held down until you start pressing it again

**Comment by Rnuomer** [comment]
Also I should note I'm using 8.1, just from the Ubuntu repo

**Comment by hiker** [comment]
Afaik there's a similar issue when opening hte in-game menu. And I vaguely remember seeing a patch for that (probably before github).

**Comment by Alayan-stk-2** [comment]
Duplicate of #1021
