### ISSUE TITLE
Transparency doesn't work rightly with the bubbles in overworld

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#1990]
It looks like the water is rendered through the transparent bubbles which looks ugly.
![stk_bubbles](https://cloud.githubusercontent.com/assets/6499211/6278608/6d4f2654-b898-11e4-829b-87c652c0d676.png)

**Comment by vlj** [comment]
water should be opaque

**Comment by Flakebi** [comment]
It works now, thanks!
