### ISSUE TITLE
Animated Backround and Advanced Graphics Pipeline issue.

### ISSUE THREAD

**Issue by MarkkusCraft123** [supertuxkart/stk-code#1995]
Hi. I just got the SuperTuxKart beta and I am having some troubles with graphics.
On the "Cocoa Temple" (30_chocloate) the animated background (or scenery) reduces my performance a lot. I usually get about 20 FPS with the advanced graphics pipeline on, but on the track, I get about 5 FPS. The same thing is happening with the new island track. The water is drawn everywhere. (I got this by turning on the Artist Debug Mode and using the fly keys.) When I turn the animated background (or scenery) off, it still does the animated background (or scenery.)
My next issue is if I turn off the advanced graphics pipeline, I see nothing but the skybox. But I get 60 FPS and beyond.
I am using a Asus X551MA with Ubuntu 14.04. Everything has been updated.
P.S. The same problems are happening on Windows.

**Comment by vlj** [comment]
That's because cocoa temple and gran paradisio have a lot of skinned object and the engine is doing software skinning (which is slow).
Hardware skinning is implemented for the next release (0.9.1) though.
The other bug was fixed after beta 2 was released.

**Comment by hiker** [comment]
If it can be played without advanced pipeline in the next release, I'd say this ticket can be closed.

**Comment by hiker** [comment]
Thanks for the report!
   Joerg
