### ISSUE TITLE
Split screen not working on hd3000 / windows

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#1999]
Both screens are rendered in the lower half, i.e. one overwriting the other.

**Comment by vlj** [comment]
No fix until further notice.

**Comment by hiker** [comment]
Bisect:
13393ef04bc364534cd0a1b134eecddcff5dc67c is the first bad commit
commit 13393ef04bc364534cd0a1b134eecddcff5dc67c
Author: Vincent Lejeune <vljn@ovi.com>
Date:   Sat Feb 7 01:55:14 2015 +0100

    Fix 1808
