### ISSUE TITLE
Dropped tires in battle mode not visible

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2000]
Originally reported in #1901, Odd0002 could reproduce it on linux, I on windows.
It is apparently not always reproducible, from irc:
(14:23:05) Odd0002: this is cave, I got hit and a tire fell off
(14:23:06) hiker: Ah, then the first time was too quick after shooting
(14:23:16) Odd0002: and I could see the tire
(14:23:18) hiker: Oh :(
(14:23:29) Odd0002: but the second time it didn't appear

**Comment by hiker** [comment]
Note that #1902 mentions that the disappearing wheel only happens in cave arena.

**Comment by deveee** [comment]
It happens on every arena, at least for me. And it is random - sometimes you get visible wheel, sometimes not.

**Comment by Odd0002** [comment]
Some screenshots: 

Visible, Physics:
![screenshot-untitled window](https://cloud.githubusercontent.com/assets/1661457/6337019/7e1210ce-bb6c-11e4-837a-e60532a48b8e.png)
Visible, Bounding Box:
![screenshot-untitled window-4](https://cloud.githubusercontent.com/assets/1661457/6337094/23dfcc6c-bb6d-11e4-81f3-06de97dfbb80.png)


Invisible, Physics:
![screenshot-untitled window-1](https://cloud.githubusercontent.com/assets/1661457/6337020/7e1b3cee-bb6c-11e4-8703-79a4ea066e35.png)
Invisible, Bounding Box:
![screenshot-untitled window-2](https://cloud.githubusercontent.com/assets/1661457/6337063/e08a55e0-bb6c-11e4-9459-1c5224cc79bb.png)
