### ISSUE TITLE
[Enchancement] Limit/Reduce rendering framerate while the game is paused

### ISSUE THREAD

**Issue by Odd0002** [supertuxkart/stk-code#2003]
When the game is paused, the scene is still being rendered by the GPU, even though it is not changing.  If you move to another virtual desktop (on linux), the game starts being rendered offscreen, disabling VSync and rendering at its maximum framerate (even if the VSync option is checked), resulting in higher GPU and CPU usage.  This is very bad for laptops, as this uses more energy and generates more heat.

There are 2 possible solutions:
- Take a screenshot of the rendered scene and put it behind the pause menu as a static background.
  - This is the least resource intensive, but once network play is integrated, will not update the background image to show the action that is happening.
- Limit the framerate of the game while paused, similar to how the framerate of the rendering of the main menu is limited. 
  - This uses more resources than the previous solution, but will still allow people to see what is happening in front of them on an (eventually) networked game.

**Comment by qwertychouskie** [comment]
Or even better:
On a non-networked game, use solution 1;
On a networked game, use solution 2.

**Comment by Arthur-D** [comment]
I don't see the point in spending time on this. How often are you pausing a game and then switching desktops for prolonged amounts of time? Besides, turning the game off and on again normally takes little time, unless you have tens of addons installed (especially karts).

**Comment by auriamg** [comment]
In menus, the framerate is already limited to 30 FPS, hopefully that should be enough reduction to avoid your PC running at 100%. I don't really see any point in working in more than that on this
