### ISSUE TITLE
only background visible, no track, no carts

### ISSUE THREAD

**Issue by CHmuc** [supertuxkart/stk-code#2006]
After starting a race (in 0.8.2. beta, Win7) I can only see the static background of the map, but not the track itself or any carts. I tried different settings and video options, but can´t get it working.
Right now the beta is unplayable. :-(

I hope you can fix it, because the game is _great_ and my kid likes it a lot.

Regards
  Chris

![image](https://cloud.githubusercontent.com/assets/11198905/6378261/676e6998-bd2a-11e4-911b-fb3600b82845.png)
![image](https://cloud.githubusercontent.com/assets/11198905/6378267/71915f70-bd2a-11e4-9b2f-6b1a6bf08898.png)

**Comment by auriamg** [comment]
Hi, thanks for the report. This bug has been fixed after beta 2 and should be corrected in the next released build. If you still experience issues after the next build is out, please reopen this ticket.

Thanks
