### ISSUE TITLE
Kart looks badly after recent changes

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2007]
You can see the screenshot. 

![zrzut ekranu z 2015-02-25 20 23 58](https://cloud.githubusercontent.com/assets/5108558/6378598/b441148a-bd2c-11e4-99ac-6e676311bf85.png)

Tested on linux with nvidia 635m and 331.113 driver version.

**Comment by vlj** [comment]
No fix until further notice.

**Comment by deveee** [comment]
Seems to work fine now.
