### ISSUE TITLE
Second player has wrong camera view

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2008]
Look at the screenshot. Second player doesn't see almost anything. This means that multiplayer game is broken atm.

![zrzut ekranu z 2015-02-25 21 03 44](https://cloud.githubusercontent.com/assets/5108558/6379358/fd74525c-bd31-11e4-9558-9e1299ec39d6.png)

**Comment by vlj** [comment]
No fix until further notice.

**Comment by samuncle** [comment]
Hiker asked a screenshot of what I see 

my GPU is a gtx 660
![screenshot - 26 02 2015 - 04 33 59](https://cloud.githubusercontent.com/assets/6406045/6385906/f2a342a4-bd70-11e4-9913-82a27ef6f158.jpg)

**Comment by samuncle** [comment]
edit it happen with the last version in the master
![screenshot - 26 02 2015 - 04 46 19](https://cloud.githubusercontent.com/assets/6406045/6386008/94b1dab4-bd72-11e4-9829-3811ca3ccbca.jpg)

**Comment by deveee** [comment]
First bad commit is 06f0188a5b0f63a9a4d4c9302cbb512bac282401
