### ISSUE TITLE
registration fails with "the name msut be between 2 and 64 characters long"

### ISSUE THREAD

**Issue by titiger** [supertuxkart/stk-code#2009]
I cannot register as new user
git 988f5ea933c925fae1d4653bc89c1da4c99c2715

**Comment by titiger** [comment]
screenshot: http://titi.megaglest.org/screens/stkbug.jpg

**Comment by leyyin** [comment]
Should be fixed leyyin/stk-addons@e0811b0ad

**Comment by hiker** [comment]
I assume that this is fixed now, otherwise please comment on this ticket.

Thanks for the report!
   Joerg
