### ISSUE TITLE
Accelerators should slow down if going reverse

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2016]
beta 0.8.2
When we go the wrong way and take an accelerator, this one speed up our kart instead off slowing us down.

**Comment by samuncle** [comment]
Is it really a bug ? 

I'm just asking for feedback. In reality if you are in the wrong road and you accelerate the car will accelerate.

What could be done is if you fire the zipper while backward it slow you down. But not if you are in the wrong way

**Comment by deveee** [comment]
Maybe it has a sense because booster has texture with arrows which show
direction. But we can run track in reverse and we have the same
situation... Anyway I think that booster after skidding has much less sense
than this one ;)

**Comment by hiker** [comment]
Ideally the textures would be reversed when driving in reverse mode, but still: if you would go in the wrong direction it would still speed you up - and I think that's just fine (what if we have non-directional game modes, like Easter Egg Search, there would be no direction in which the karts would be pointing :)  ). So, imho that's a won't fix, but feel free to comment with suggestions how to handle those situations (I thought of rotating the texture depending on where the kart is coming from, but what if there are two karts approaching the texture at the same time?).
