### ISSUE TITLE
wrong speed effect on accelerator with 2 multiplayers

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2017]
beta 0.8.2
In multiplayer with 2 players. 
When the first player is on an accelerator the acceleration effect is done on the two players.
When the second player does the same, there is no acceleration effect.

**Comment by samuncle** [comment]
I'm not sure but I think this was already reported and corrected

**Comment by Flakebi** [comment]
Yes, it's mostly fixed, the original issue is here: #1937
