### ISSUE TITLE
Add support to embedded library object in a track directory 

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2018]
Currently many tracks use the library which is great and we won't go backwards more and more tracks will use them.

However if an addons use an object that isn't included in the released stk there is currently no way to make it works.

I suggest to add the support of embedded library nodes directly in the track directory so the track will carry everything needed in order to be opened by supertuxkart.

That would allows people to make their own library nodes and to share more easily their tracks.

**Comment by stkAnon** [comment]
Isn't this what named objects essentially are?

**Comment by hiker** [comment]
Yes, but the idea would be that those objects could be shared between different tracks I'd guess. Not sure how to handle those - short of including them in each tracks, and at install time in stk detect that it's already there (or the other way round: if at install time the library object is not there, request is to be downloaded;  or the addons.xml file would contain a list of library object required, and the missing library objects would be included in the download request) ... but seeing the complexity of any of this:
I'd say to just include them with each track. The amount of disk space/download amount is imho not big enough to be really a worry, at run time we can still decide to load an identically named object from the main library, but we won't have to worry about us removing any objects which would then break existing addons.

**Comment by samuncle** [comment]
Hi

@stkAnon nope. Basically with library nodes you have more flexibility. You can do complex objects like for instance a torch with sparks and a fire effect and a light emitter. And all of that with the simplicity of moving ONE object.
You probably wasn't there during the "old good days" but it was very anoying. If you wanted to just move a lantern you had to select the lantern, the glowing glass and the light emitter + eventually a billboard etc. It was time consuming, now it's just moving a lantern. Also if they are really good they can be included in the core game and then used in our tracks. 

@hiker 
I just saw you added this to the later millestone and I think it's important to have this ready for the upcoming version.
The easiest way of doing that would be to embedded nodes in the track file (in a specific directory like track/name_of_the_track/nodes
That would allow easily people to share their track and even use the addons website without complex redesign. Also the track embedded everything it needs to be open which is kinda cool.
It's exactly like textures, you can use generic textures but also have your own textures in the track directory.

sam

**Comment by hiker** [comment]
@auriamg can you have a look if this is feasible for the next release? If it's just adding another search path it might be reasonable easy to do.

**Comment by auriamg** [comment]
Done in ba773b8452e31c8bc96bbd18fb39758f2efcab0b
