### ISSUE TITLE
Handling of battle mode meshes in the exporter

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2019]
#1901 is actually caused because that .blend file has a mesh for the battle AI. Long term we need an option to export this data (in a way that the battle AI then can read).

**Comment by auriamg** [comment]
Doesn't the battle AI automatically generate a navmesh? I thought it was automatic, not manual. Though maybe I'm wrong

**Comment by hiker** [comment]
I think nixt used recast to create the navigational mesh from the full mesh, but I am not sure what is happening then: either that nav-mesh is added to the .blend (which I would prefer, since it allows us to easily tweak the mesh) and exported, or if the exported mesh is read directly by stk. I'll have a look when I try to merge this in, for now ... this ticket is mostly a reminder to merge in the battle AI :)

**Comment by auriamg** [comment]
Done in svn, the export is now done in the track export script
