### ISSUE TITLE
Hat position for both saras is too height

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2020]
The hat is set too height above sara in christmas time.

**Comment by deveee** [comment]
Not really a release blocker, but better totally remove hats for these karts than display it high in the air.

**Comment by hiker** [comment]
I've fixed the kart.xml file, and also fixed the spelling of the name (Racer and Wizard need to be capitalised). I only did the xml files, I am not sure if I can modify the .blends. So assigning this to samuncle to be done later.

**Comment by samuncle** [comment]
it should be corrected now
