### ISSUE TITLE
Problem with "Code" property in exporter

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2022]
It seems like "Code" property is not remembered when you save blend file. I created this field yesterday in Cave file, probably auria created it too. And I still see "Create missing property" button.

Other thing is that I'm not sure how it should exactly work...
- when I write "cave", data is exported to /home/deve/tracks/cave
- when I write "/home/Documents/cave" it creates directory "/home/Documents/cave", that's fine. But it writes the files directly in "/home/Documents". I mean "/home/Documents/track.xml" etc...

I suppose that there is something wrong with it.

**Comment by auriamg** [comment]
Hi Deveee, "code" is meant the be the name of the folder the track will be exported to. You should not write paths there, in fact we should probably disable any non-alphanumeric characters in the code.

As for the property not being saved, I am unable to reproduce this issue. Can you please try again and check if any special circumstances create this issue, or any error message is logged?

**Comment by deveee** [comment]
Okay, then it is exported to $HOME/tracks/cave by design? Maybe allow to write there full path?

Now when I saved and re-opened the file, it remembered this parameter. But I have information about missing parameter in every track modified by other people. For example your CaveX file, coca temple, gran paradiso...

Logs don't say anything interesting...
```
connect failed: No such file or directory
Read new prefs: /home/dave/.config/blender/2.73/config/userpref.blend
found bundled python: /home/Dokumenty/blender-2.73a-linux-glibc211-x86_64/2.73/python
fake_module: addon missing 'bl_info' gives bad performance!: '/home/dave/.config/blender/2.73/scripts/addons/convert.py'
(STK) Loading XML files from  /home/dave/.config/blender/2.73/scripts/addons/stkdata
(STK) Loading scene properties from  /home/dave/.config/blender/2.73/scripts/addons/stkdata/stk_panel_parameters.xml
(STK) Loading object properties from  /home/dave/.config/blender/2.73/scripts/addons/stkdata/stk_object_parameters.xml
(STK) Loading kart properties from  /home/dave/.config/blender/2.73/scripts/addons/stkdata/stk_kart_object_parameters.xml
(STK) Loading material properties from  /home/dave/.config/blender/2.73/scripts/addons/stkdata/stk_material_parameters.xml
read blend: /home/Dokumenty/linux/supertuxkart-media/tracks/caveX/cave.blend
Read library:  '/home/Dokumenty/linux/supertuxkart-media/library/lamps/stklib_bambooTorch_a/stklib_bambooTorch_a.blend', '//..\..\library\lamps\stklib_bambooTorch_a\stklib_bambooTorch_a.blend', parent '<direct>'
```

**Comment by auriamg** [comment]
In the "track exporter" panel is a folder selector, it will export there. What folder did you select there?

The reason why it's missing from most files is likely only because it's very recent and we haven't updated all blends yet

**Comment by deveee** [comment]
Assets path works fine :) I didn't find it before, thanks.

Ok, then I assume that you used older exporter without this parameter and this is the reason that I don't see it on my computer again.

**Comment by auriamg** [comment]
Was assets path empty? If so, this ticket should be reopened because the exporter should not accept to export without a path being selected

**Comment by deveee** [comment]
It was empty or invalid. I didn't set it before export.

**Comment by auriamg** [comment]
Hmm actually I can't reproduce the bug, with the assets path missing I get a "please select path" prompt instead of the export button. Unless you can find more information, I don't know what happened

**Comment by deveee** [comment]
I was using exporter few times before recent release and it was working without issues.

**Comment by deveee** [comment]
I have this problem again after installing newer blender version. Here is the message that I see when I try to set assets path:

![zrzut ekranu z 2016-05-21 00-23-55](https://cloud.githubusercontent.com/assets/5108558/15443710/b729678a-1eea-11e6-823e-3b301ea5598b.png)

Now I also don't see the "Create missing property" button.

**Comment by deveee** [comment]
Ok, I didn't select STK Panel in add-ons ;p
