### ISSUE TITLE
Automation script for developers? 

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2026]
I wrote a script that should help the developers (or testers) in acquiring the source code and data (or update it, if a new commit arrives) 

the script is located here: https://gist.github.com/cap44/1928bb199b6894662bf1 <-it might be buggy and flawed.

Can this script help with STK's development process?

**Comment by deveee** [comment]
Tbh. every developer can make its own automation script. And still better post it in the forum instead of as bug report.
