### ISSUE TITLE
Christoffel Columbus achievement should automatically know all tracks

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2032]
Atm the "Christoffel Columbus" achievement lists all tracks explicitly in data/achievements.xml. This is error prone (it needs to be updated when tracks are replaced or renamed), so it would be good if this could be filled automatically.

**Comment by Alayan-stk-2** [comment]
It now does so, though the logic to differentiate official tracks from other tracks is based on the track's prefix ("addon" or not), which isn't perfect as WIP typically don't have it.
