### ISSUE TITLE
"translator-credits" string and the move to Transifex

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2039]
Launchpad maintained a "translator-credits" pseudo-string with the name of all contributors, but Transifex doesn't. This string remained in place, however. We should decide what to do about it, either remove it, or find a Transifex equivalent to it (transifex places the credits in a comment at the top of the po file)

Also note that the credits display the translator-credits string, so either way we should at least fix the credits

**Comment by hiker** [comment]
STK includes a script "update_po_authors.py", which takes the transifex authors from the comments and adds them to the translator credits strings which is shown in game.
