### ISSUE TITLE
First person view issues

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2040]
I noticed some issues with fps camera:
- when I constantly move my mouse upwards or downwards, the camera stops working (values are probably too high or too low)
- when I press escape, the values aren't reseted. It means that when I use it again, I still have non-working fps camera.

Marked as minor because it's only for debugging.

**Comment by samuncle** [comment]
It's not only for debug but also for making videos and stuff like that.


Sometimes the rotation get stuck I'm not sure when it's happening if values are too low why not just reseting them ?
