### ISSUE TITLE
Crash when launching a race on Windows

### ISSUE THREAD

**Issue by Alan-Drouzig** [supertuxkart/stk-code#2044]
Hello,
I installed STK beta2 to finish my breton translation.
The installation was well done.
I chose a race in single mode and crashed.  I got that :
Call stack:

 DrvPresentBuffers
 DrvPresentBuffers
 DrvPresentBuffers
 <no symbol available>
 DrvPresentBuffers
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 asCreateLockableSharedBool
 BaseThreadInitThunk
 RtlInitializeExceptionChain
 RtlInitializeExceptionChain
---------------------------
OK   
---------------------------
My computer :
Win 7 Edition Familiale Premium
Pentium Dual-Core CPU E5300 @ 2.60GHz  1.80GHz
Ram : 4 Go
32 bits System
NVIDIA GeForce 9500 GT

Best regards,
Alan

**Comment by hiker** [comment]
Have you tried the official 0.9 release?

**Comment by hiker** [comment]
Closing due to missing feedback.
