### ISSUE TITLE
GPU drivers out of date.

### ISSUE THREAD

**Issue by MarkkusCraft123** [supertuxkart/stk-code#2047]
Everytime I launch STK, it says my GPU drivers are out of date, I am running Ubuntu 14.04 with the latest version of mesa. (I think.) I have baytrail hardware.

**Comment by deveee** [comment]
You should have at least mesa 10.3. Ubuntu 14.04 has mesa 10.1 IIRC.

You can check your mesa version by running in terminal:
glxinfo | grep Open

Other problem is that we should have ability to disable this popup message.
It's too late to create "Don't show again" button/checkbox (string freeze).
But maybe at least property in config.xml or command line parameter?

**Comment by deveee** [comment]
Now you can disable this popup message in config.xml (commit 5828dddde8360a2a5131f41a16f0a329b469c0a9).

We can't really do anything more atm. I think that add checkbox after upcoming release is good idea.

Please reopen it if you see this popup with mesa in version 10.3 or higher.
