### ISSUE TITLE
Fix non-hd option

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2048]
Atm the non-hd option only resizes textures that are in the track directory (i.e. no kart textures, no shared textures, no textures in library objects). That causes stk to crash on hd3000 on windows on certain tracks (because some kart textures are not resized).

Some of this is fixed in the 'fix_non_hd_option; branch (all textures except fonts are resized if too large). There are still a few issues:
- what to do with the cached, resized textures? The old approach (which resizes any(!) texture to 1/2x1/2 size) stores the resized textured. The new approach in the branch will only resize textures if they are larger as 512x512 (to 512x512 size) - which is better, any quality impact? Atm irrlicht will read the resized texture (and potentially resize them again, e.g. if there should be a 2048x512 texture, it will be cached as 1024x256, and then resized again to 512x256). We should either just remove the whole cache, or if not cache the textures in the right size to avoid scaling twice.
- if we leave the cache enabled, any user with an existing cache (e.g. from beta2) will still get the half sized textures that are cached from a beta/beta2 run).

Suggestion: for 0.8.2 just disable the cache, and find a proper solution later.

Difficulty: what if the user first caches all textures smaller, but then decided to run in HD? We need to either invalidate any cached files, or perhaps add the resolution to the cached filename (e.g. texture.png becomes texture.512x256.png).

**Comment by hiker** [comment]
Cache is disabled for now, so resizing smaller images doesn't happen again. Everything else can be improved for the next release.

**Comment by hiker** [comment]
And postponing again :)

**Comment by Benau** [comment]
not neccessary anymore
