### ISSUE TITLE
Textures are scaled wrongly with old pipeline and non-HD option enabled

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2050]
I looked at MAX_TEXTURE_SIZE parameter in irr_driver.cpp file.

When I set it to 16x16, it looks fine (more or less :-P) with opengl 3.x:
![2](https://cloud.githubusercontent.com/assets/5108558/6865952/9d0d363c-d473-11e4-93f7-2992e41d93cf.jpg)

But it doesn't work with old pipeline (can be reproduced with force_legacy_device property)
![1](https://cloud.githubusercontent.com/assets/5108558/6865968/bf78a242-d473-11e4-9ec9-2a7b21f5362f.jpg)

It's better shown what's wrong when I set MAX_TEXTURE_SIZE to 256x256:
![3](https://cloud.githubusercontent.com/assets/5108558/6865993/e9b8285c-d473-11e4-9c6d-43cc1367e4f5.jpg)

You can fix it if you know precisely what's wrong. Or I can look at this in the evening if you want.

**Comment by hiker** [comment]
Probably a mixup somewhere of using getOriginalSize instead of getSize of a texture - I might have missed some places when I replaced them.

If it's only on the non-shader pipeline, that's not important (since it's not supported, rtt for kart screen doesn't work atm), and the released version has the maximum size 512x512 hardcoded, so the logo will not be resized.

**Comment by deveee** [comment]
I tried to change every getOriginalSize in irrlicht to getSize (in CGUI* files and COpenGLDriver) and it seems to work fine.

Some of these changes are needed also for opengl 3.x because for example this part of gui is displayed incorrectly:
![zrzut ekranu z 2015-03-27 20 04 58](https://cloud.githubusercontent.com/assets/5108558/6875120/fd6f05de-d4bc-11e4-98ba-459a71644618.png)

**Comment by hiker** [comment]
The fixed pipeline is not officially supported, so this can be postponed till later

**Comment by qwertychouskie** [comment]
I think this can be closed (https://github.com/supertuxkart/stk-code/issues/2599#issuecomment-239531972).

**Comment by deveee** [comment]
It's not 100% perfect with extremely low texture size (some images are too small, i.e. back arrow), but it's certainly acceptable.
