### ISSUE TITLE
Difficult time requirements for some easy challenges

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2052]
I tried the challenges with Adiumy (a fast kart) and without skidding

- Shifting sands: I needed 4:08 with one rescue, 3:40 is needed
- Mines: I needed 3:57 (with one rescue) but 3:50 is the goal
- XR591: There is more than enough nitro but it took me 2:55 while 2:50 is needed to succeed the challenge
- Snow peak: I needed 3:22 but 3:20 is needed
- Northern Resort: I needed 3:22, 3:40 is the challenge so I think that can be reduced
- Around the Lighthouse: I needed 2:39 and 2:25 is the goal

The rest of the easy challenges with time limit (I hope I didn't forget one) is doable.

**Comment by auriamg** [comment]
All challenges you pointed out should now be fixed, thanks!

Now if anyone wants to help me review medium challenges,. help is welcome ;) I've already fixed a few of them
