### ISSUE TITLE
Requesting to push translation for he.po (enhancement?)

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2054]
Hi, I would like to update the contents of file: he.po inside /data/po with this file: https://github.com/cap44/stkh/blob/master/supertuxkart.he.po (rev 68a0052efb5544be9fdf40e45812fbdffa34d088) 

I don't use Transifex by the way

- i5150pc on FreeNode/#stk

**Comment by auriamg** [comment]
Hi, I'm sorry but Transifex is the official way to translate supertuxkart, could you please use our official tool? Transifex supports uploading po files by the way, though this is discouraged since you may overwrite other people's work

**Comment by cap44** [comment]
that's up (had to replace the forward slash -> / with a backslash -> \ to avoid a fatal error from Transifex) )

**Comment by auriamg** [comment]
Thanks, closing this issue as resolved

**Comment by cap44** [comment]
Of course not, i cannot mirror the language

**Comment by cap44** [comment]
If there are problems with the Hebrew translation, forward them here: https://github.com/cap44/stkh/issues as that's where I commit changes before pushing the translation to Transifex
