### ISSUE TITLE
physic only objects are displayed if used in a lib node

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2055]
If you set an object to physic only (a tree for instance should have collision only on the trunk) in a library nod it is displayed anyway in supertuxkart.

I have corrected ticket  #2014 however I can't commit since you see a big square around characters.

**Comment by auriamg** [comment]
A fix attempt has been committed in branch Fix_2055 ( 8deac178d0ebf9cf433ab642138af171e9a9c182 )

We can decide whether to merge after more testing

Note; this patch does not handle moving/animated library objects
