### ISSUE TITLE
Tweak graphics options

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2059]
Based on this post:
http://forum.freegamedev.net/viewtopic.php?f=17&t=6128&start=25#p63349
I think that we should modify default graphics levels a bit.

I suggest to enable low shadows in graphics level "4" (it gets similar fps number and looks much better). Or perhaps add something between "4" and "5" instead of graphics level "2" which is almost the same as "1".

What do you think about it?

**Comment by deveee** [comment]
Additional graphics level added by auria here: 70799539a66a4b356bcdd6461a9e9f1778854598

**Comment by auriamg** [comment]
Thanks, I had forgotten there was a ticket about this :)
