### ISSUE TITLE
Drive through houses in Northern Resort

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2061]
I noticed that you can drive through at least some of the houses in Northern Resort. They are admittedly off track, but that should probably be fixed.

**Comment by samuncle** [comment]
It's similar to #2014 . When I started to correct these issues the engine had a bug where objects flagged as "physic only" where show in the game (and they should be invisible).

I have close the other ticket and now we can use this one to report objects without physic.

A benchmark should be done to see:
How the shape flagged as exact impact performances
Should we merge non animated objects to improve performances ? I don't know much about this but in the rendering engine it's better when there is less objects.

**Comment by cap44** [comment]
Is it the 1st house on the right side of the track?

**Comment by Benau** [comment]
There is already physic-only box in woodlodge library object
