### ISSUE TITLE
Add a link to the documentation in the new addons website

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2062]
We should include links to resources for people who are interested in making tracks for the game. The best place IMHO is the new addons website.
Useful links:
Overview of the engine: http://supertuxkart.sourceforge.net/Antarctica:_Overview
Track maker guide: http://supertuxkart.sourceforge.net/Track_Maker%27s_Guide
Style guidelines: http://supertuxkart.sourceforge.net/Style_Guidelines

Also in the old addon website that will be changed to read only we should add a link to the new one. Something like:
The old version of the addon website is read only now.
-> new one addons.supertuxkart.net

**Comment by Alayan-stk-2** [comment]
The "contribute" button now direct to the "community page" which contains an overview of pages for programmers and artist willing to contribute.
