### ISSUE TITLE
new screenshot in the win installer

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2064]
Currently the win installer has an old screenshot of the island. It's a lying to people :o. The island has been removed from track shipped by default.

We should do a proper new screenshot with gran paradiso island

**Comment by samuncle** [comment]
Can you please provide me the resolution of the picture so I can create one.

It's not a big task it's a matter of minutes maybe one hour to do it well

**Comment by hiker** [comment]
164x314 px, but this is also included in #2329.

**Comment by hiker** [comment]
@samuncle I have the new installer all ready except for a new image. Can you update this ticket and indicate if you can make one? Otherwise we can postpone this ticket till later.

**Comment by qwertychouskie** [comment]
It has been over a month, so maybe this should be postponed.

**Comment by samuncle** [comment]
![installer](https://cloud.githubusercontent.com/assets/6406045/16400709/10999d38-3cde-11e6-8c28-25a3e8708b69.png)

Done with a modern and updated screenshot

**Comment by hiker** [comment]
While I have added this to the windows installer, I don't think this image is ideal: it is somewhat dark, and imho should show tux, not some other character. Reopening and leaving it for later ;)

**Comment by samuncle** [comment]
Arff :( can't you brighten a bit the picture?  If you have 30 min I can do one with tux :)

**Comment by hiker** [comment]
You can likely take your time, have problems uploading atm, might need to do it tomorrow.

**Comment by samuncle** [comment]
https://i.imgur.com/UjfGBBW.jpg

Would this one be ok?

**Comment by qwertychouskie** [comment]
That one is 5 pixels less in height than it should be.  Here is a very similar version I created that is the full res: http://i.imgur.com/zRrOV9v.png

**Comment by qwertychouskie** [comment]
It is also centered on the characters a bit better, GNU's hoof is not cut off anymore.

**Comment by qwertychouskie** [comment]
I can also provide the .xcf if you need it.

**Comment by samuncle** [comment]
I think we can close it
