### ISSUE TITLE
Remove unused stkgui files

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2066]
$ ./tools/find_unused.sh
Searching for unused stkgui files
---------------------------------
..................................................................
./challenges.stkgui appears to be not used.
./enter_player_name_dialog.stkgui appears to be not used.
./online/guest_login.stkgui appears to be not used.
./online/lobby_settings.stkgui appears to be not used.
./online/notification_dialog.stkgui appears to be not used.
./online/profile_overview.stkgui appears to be not used.
./options_players.stkgui appears to be not used.
./tutorial.stkgui appears to be not used.

**Comment by auriamg** [comment]
Removed a few files, I didn't thouch the network related ones though as I'm not familiar enough with the work being done there

**Comment by hiker** [comment]
I think that ticket can be closed by now, afaik all unused files were deleted.
