### ISSUE TITLE
Mine track missing texture

### ISSUE THREAD

**Issue by stafoo** [supertuxkart/stk-code#2067]
On the right, few meters after the start, you can fall down inside the pit here placed. No textures are shown at  the bottom.
Maybe add water or something?

![schermata del 2015-04-02 14 55 16](https://cloud.githubusercontent.com/assets/11771066/6964503/19af4f4c-d94a-11e4-9cc0-02b34ff6a3a8.png)

STK 0.9 RC1

**Comment by auriamg** [comment]
Fixed in SVN
