### ISSUE TITLE
Description hides statusbar of kartphysics (german!)

### ISSUE THREAD

**Issue by 115ek** [supertuxkart/stk-code#2069]
the description "Geschwindigkeit" hides the statusbar in the german version.
the english version is quite fine because "speed" consists of less characters
(0.9rc1 on windows 8.1)
![screenshot](https://cloud.githubusercontent.com/assets/11771774/6964849/4c9e44f0-d94d-11e4-9e05-4ec08a920b83.png)

**Comment by auriamg** [comment]
Workaround committed to branch fix_2069

**Comment by hiker** [comment]
For 0.9 I changed the German translation to be 'Tempo'

**Comment by hiker** [comment]
Closing this. We have #2065 to improve this permanently.
