### ISSUE TITLE
No way to create metallic materials?

### ISSUE THREAD

**Issue by stkAnon** [supertuxkart/stk-code#2070]
I did some quick tests of the Antarctica engine's behaviour at various glossmap values a week ago when I made a Blender material to simulate it.

![http://forum.freegamedev.net/download/file.php?id=9182&mode=view](http://forum.freegamedev.net/download/file.php?id=9182&mode=view)

One thing that I noticed was that no matter what specularity or roughness settings were used, the specular lighting would always be the colour of the lamp, while the specular reflection would always be the colour of the background. In real life, the specular highlights of metals tend to inherit their surface colours.

So, AFAICT, there doesn't seem to be any way to create metallic surfaces in STK right now.

**Comment by Benau** [comment]
Fixed by SP
