### ISSUE TITLE
Add Freedo

### ISSUE THREAD

**Issue by nicolasrpmaia** [supertuxkart/stk-code#2071]
Freedo is the mascot of Linux-libre, and would be basically Tux in blue color and with wings.

http://www.fsfla.org/ikiwiki/selibre/linux-libre/gnu-lux.png
and
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Freedo.svg/500px-Freedo.svg.png

**Comment by Legimet** [comment]
Actually the first one is "Lux" not Freedo, and Freedo doesn't have wings.

**Comment by hiker** [comment]
Please make suggestions like this in our forum (http://supertuxkart.sourceforge.net/forum), we don't have the man power to do custom karts. Once created the karts can be uploaded to our addons server (and then downloaded by everyone).
