### ISSUE TITLE
Track thumbnails are dark in GP results screen

### ISSUE THREAD

**Issue by stephenjust** [supertuxkart/stk-code#2075]
After a race in a GP, the thumbnails that appear for the other tracks seem darker than they should be.

I am running 0.9-RC.

```
[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Haswell Mobile 
[info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.5.2
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] irr_driver: GLSL supported.
```

![screenshot from 2015-04-04 17 18 00](https://cloud.githubusercontent.com/assets/3144757/6995092/1aa29f3e-daef-11e4-98ba-e0deb29f0d41.png)

[config.xml](https://gist.github.com/stephenjust/8c2159095c9dd2960511)

**Comment by deveee** [comment]
I checked it with your mesa version on intel HD 4000 and I can't reproduce it. I assume that this has been fixed. You can also try to run with clean config, or at least remove texture cache.

Please reopen if this bug still occurs.
