### ISSUE TITLE
Consistencty of assets and git source

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2077]
We need to find a way to make sure that the assets are in sync with the git sources. Example: make sure that a git version does not try to read files from stk 0.8.1 and vice versa.

Comments in #2073 discuss this problem and potential solutions, but I think this discussion merits its own ticket.

Also we should perhaps move the wip\* directory in their own repo: I can't remember where I heard/read it but I seem to remember that some packages exist that actually included wip tracks/karts. This is an easy-to-make mistake (atm we need to explicitly remove the wip directories, so doing nothing means the wip tracks are included),

**Comment by hiker** [comment]
Maybe also make sure that the assets are new enough, both stk-code/data as well as stk-assets (e.g. if stk-assets are outdated a message should be shown).

**Comment by konstin** [comment]
> I can't remember where I heard/read it but I seem to remember that some packages exist that actually included wip tracks/karts

My [Ubuntu PPA](https://launchpad.net/~stk/+archive/ubuntu/daily) includes the wip-tracks but that's intentional because ithose are nightly builds of STK.

**Comment by qwertychouskie** [comment]
This has been fixed with the `supertuxkart.version` file in the media repo, can be closed.

**Comment by qwertychouskie** [comment]
Fixed, see https://github.com/supertuxkart/stk-code/commit/78c592e4e5b816d02afea137e7f4021fd852db1e and https://github.com/supertuxkart/stk-code/issues/2073, can be closed.
