### ISSUE TITLE
Hotseat mode: HUD inverted

### ISSUE THREAD

**Issue by scrzbble** [supertuxkart/stk-code#2079]
Version: SuperTuxKart, 0.9-rc1
When in hotseat mode, the HUD is inverted between the two players: powerups, speed and position are displayed in the wrong player's HUD. Moreover, the "plunger on the face" debuff happens to the wrong player.

See screenshot: Ephlephant is second but his HUD claims he is first. Emule is first (and has a lot of nitro), but his HUD claims he is second. Emule's nitro also appears on Ephlephant's HUD.
![addon_the-island-2015 04 10_09 30 31](https://cloud.githubusercontent.com/assets/4055633/7077404/a34daf08-df64-11e4-923b-d73877712431.png)

**Comment by auriamg** [comment]
Thanks for the bug report, a fix has been committed
