### ISSUE TITLE
Game unexpectedly iconifies

### ISSUE THREAD

**Issue by scrzbble** [supertuxkart/stk-code#2080]
Version: SuperTuxKart, 0.9-rc1
OS: ArchLinux with XFCE.

The game window occasionally iconifies on its own during certain races, notably Oliver's Math Class, Subsea and Hacienda.

**Comment by deveee** [comment]
What do you mean by iconifies? Window begins to be minimized without a reason or something other? 

I didn't observe it at all. Maybe you occasionally press certain keys, which are your window manager shortcuts?

**Comment by scrzbble** [comment]
Yes! I apologise. I had assigned Control to fire, which messed with the desktop environment.
