### ISSUE TITLE
Hotseat mode player selection: right-hand player too big

### ISSUE THREAD

**Issue by scrzbble** [supertuxkart/stk-code#2081]
Version: SuperTuxKart, 0.9-rc1

See attached screenshot: ![screenshot_2015-04-10_09-21-30](https://cloud.githubusercontent.com/assets/4055633/7077264/6e5b5b8e-df63-11e4-9063-ed614b2e4924.png)

The right-hand player's Weight, Speed, Power gauges are much longer than the left-hand player's. In this way, it is hard to compare the two karts. The two sets of gauges should occupy the same space.

**Comment by Flakebi** [comment]
That's related to #2065, hiker proposed to replace the text by icons.

**Comment by auriamg** [comment]
Closing as duplicate, we will track this issue in #2065
