### ISSUE TITLE
Wiimote IR position not configurable (in-game)

### ISSUE THREAD

**Issue by PlasmaPower** [supertuxkart/stk-code#2082]
It is initialized to top/above [here](https://github.com/supertuxkart/stk-code/blob/a81f21a27a7ae278c87c2b4f15efb1afef308898/lib/wiiuse/wiiuse.c#L156), and never changed.

**Comment by hiker** [comment]
We don't use the IR at all, so that doesn't matter.

**Comment by PlasmaPower** [comment]
Sorry, I was confused by the default controls for the wiimote, and thought it was controlled by IR.
