### ISSUE TITLE
Issues with Sandtrack

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2084]
There are (at least) two locations in sandtrack that causes a severe slowdown of the kart.
1) As reported in the forum http://forum.freegamedev.net/viewtopic.php?f=17&t=6256&sid=a5e9d4c142c9d429805f0074ca9fc7d7#p63486 (or image: http://forum.freegamedev.net/download/file.php?id=9241&t=1)
2) driving in reverse just before entering the first pyramid - on the (somewhat large) triangle just before the interior.

**Comment by hiker** [comment]
I've just added debugging features for interpolated normals to the physics debug view (e8b8bbd). The bump at the entrance of the pyramid is (most likely) caused by incorrect normals of the triangle, see the white normals at the kart (tilted way to the right), and the white normal at the 'end' of the triangle:
![sandtrack-2015 04 15_07 49 58](https://cloud.githubusercontent.com/assets/6138652/7148292/ff047afa-e344-11e4-8f5d-cd403f3df948.png)

The bump in the shortcut appear not to be caused by the normals. Likely the '^' shaped track causes this (i.e. going up, then down) - I assume that the chassis just hits the tip of the ^ when the front wheels are already on the downhill section, and the rear wheels still at the uphill section.

In one case the collision is at: (XYZ in stk):
		[0]	-63.8356743	float
		[1]	-128.115341	float
		[2]	-158.374069	float
We should verify that this point is indeed on the top of the hill (^ shape). I also had collisions at around:
		[0]	-72.3313370	float
		[1]	-130.087616	float
		[2]	-165.494873	float

**Comment by samuncle** [comment]
It has been corrected by auria
