### ISSUE TITLE
Cocoa Temple unfair respawn 

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2085]
If you fall down the bridge you get respawned way back. And you have to catch up with the others. Other respawn a much closer to where you left the track.

Video: http://a.pomf.se/muzpkd.mkv

Sorry i don't know how to describe the position on the map, therefore the video. :)

**Comment by konstin** [comment]
> Sorry i don't know how to describe the position on the map, therefore the video. :)

You could activate Artist debug mod and then use the print kart position function but I guess it's fine when you say "on the bridge in Cocoa Temple" ;)

**Comment by samuncle** [comment]
I tried to correct it however it's a bit more difficult than that since reset should be adapted to be able to reset people correctly on the side wall. 

People will have to be careful :P until we correct this for the 0.9.1

**Comment by nado** [comment]
Or maybe for this map, we could respawn people on the main path ?

**Comment by nado** [comment]
Oh, so it was not a feature to make use of shortcuts harder and more rewarding ?

**Comment by Benau** [comment]
Fixed in latest asset
