### ISSUE TITLE
FTL in front of leader elimination

### ISSUE THREAD

**Issue by mrblarg64** [supertuxkart/stk-code#2088]
Being in front off leader when elimination happens causes you to be instantly eliminated regardless of how close you are to the leader, this is very annoying in my favorite gametype of 19 ai kart ftl which is very chaotic and sometimes i get bumped in front of the leader at exactly the wrong time. I have read that the "get in front of leader to break score" thing was modified but I have not found anything regarding this. If this is not intentional why not use the absolute distance from the leader as a way to measure whether you should be eliminated from the race. Sorry for the rambling im really tired right now, could edit but LEEEROOY JENNKINNS.

specs/build options
ver 0.8.1
19 ai player karts on gentoo
cpu: AMD piledriver (a10-5750m)
CFLAGS="-march=native -O2 -pipe"

**Comment by hiker** [comment]
Well, we agreed that FTL should work this way - so from this point of view we have no intention to change this.
Adding a new game mode ('being chased by nolok') where only the last kart is eaten by Nolok (and no leader at all) would be a good idea though. If you are interested in that, please open a ticket.
