### ISSUE TITLE
Check if OpenAL installer is needed

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2089]
In 99% this installer is not needed because we have this library in our dependency package and it exists in game directory.

The installer contains probably newer OpenAL version (it is larger), but STK doesn't use it anyway. It finds OpenAL32.dll in game directory, which has higher priority.

I checked it on two different systems (Win 7 and Win XP) and sounds work for me without installed OpenAL.

If we want to use OpenAL library from the installer, we need copy two files from system32 directory:
- OpenAL32.dll
- wrap_oal.dll

Edit:
Actually the OpenAL library available in our dependencies, depends on MSVCR90.dll, which doesn't have a sense. We should update our dependency package so that it will contain OpenAL32.dll and wrap_oal.dll from the official installer. And then installer won't be needed anymore.

**Comment by hiker** [comment]
I tried a few combinations:
1. removing 'our' openal from the install directory, stk will pick up openal from the installed openal packages and works.
2. uninstalling openal, stk will pick up the local version (i.e. in the install directory).
3. Copying the installed openal libraries (openal+wrap_oal) into the stk installation directory did not work for me. I would suspect (without further investigation) that this might be caused by the difference between the OpenAL32.lib file used when compiling (??)

So, I'd suggest we just remove the openal-installer from the stk installer, and keep our current (smaller) openal.dll in the stk install directory (which is already the case).

Deveee, are you ok with this?

**Comment by hiker** [comment]
I forgot to make the new dlls executable :(  Now the 'newer' version works for me as well.

So I'll try to only use the newer/non MSVCR90 dependent version for the next installer.

**Comment by deveee** [comment]
@hiker we shouldn't use our smaller openal dll (this one which depends on MSVCR90). There was a bug report somewhere that someone was not able to run STK because MSVCR90 was not available in his system.

We have two possibilities:
1. Remove openal32.dll (this one which depends on MSVCR90) from our local directory and keep openal installer
2. Remove openal32.dll from our local directory and copy two files (openal+wrap_oal) from installer to our local directory.

I prefer second solution because it makes installation process simpler and also we can be sure that we have all libraries that we need.

**Comment by hiker** [comment]
Ahh - I forgot to send this comment in minutes after my previous comment ... well, it's still useful:

I forgot to make the new dlls executable :(  Now the 'newer' version works for me as well.

So I'll try to only use the newer/non MSVCR90 dependent version for the next windows installer (i.e. without separate openal installer)

**Comment by hiker** [comment]
Hmm - strange, my openal version (extracted from the installer included previously) has a different size than the one you used in the mingw. Any idea why?

**Comment by deveee** [comment]
@hiker Our installer contains oalinst.exe in version 1.9.9. I downoaded current version from the website https://www.openal.org/downloads/ and it was version 2.0.7. So maybe these dlls are in slightly newer versions.

**Comment by hiker** [comment]
OK, should be mostly implemented. Todo:

- [ ] Update the windows dependency package to include the right openal libs.
- [ ] Get confirmation from an stk installation on a 'clean' system (no previous stk or vs or openal) installation to make sure sound does it indeed work on a non-dev system

**Comment by qwertychouskie** [comment]
When the new installer is ready, I would be happy to test it on an almost fresh install of Windows 7.

**Comment by qwertychouskie** [comment]
Supertuxkart 0.9.2-rc1, .exe installer, Win 7, sound works.

**Comment by qwertychouskie** [comment]
Can this be closed since it works?

**Comment by hiker** [comment]
Seems to work fine.
