### ISSUE TITLE
Big pictures on supertuxkart.net front page might overlap

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2091]
Big pictures on supertuxkart.net front page might overlap with the side section of screenshots.

We should fix that because it's kinda cool to have a "big" picture in the front page since we are a video game.

The culprit the css for the id screenshots
http://supertuxkart.sourceforge.net/Template:Main_page/Latest_Release#Last_Release:_0.9

I don't know how I'm supposed to access on that css

**Comment by auriamg** [comment]
CSS fixed, as long as image sizes remain reasonable
