### ISSUE TITLE
Options not documented in --help

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2095]
If you do `supertuxkart --help` you dont see any option to control the verbosity level.
That would be great since there is a lot of [info] mixed with the [warn].

**Comment by auriamg** [comment]
I believe there is option

```--log=1```

where the number is based on this enum

```
    enum LogLevel { LL_DEBUG,
                    LL_VERBOSE,
                    LL_INFO,
                    LL_WARN,
                    LL_ERROR,
                    LL_FATAL
    };
```

So it exists, just needs to be documented

**Comment by nado** [comment]
Oh, indeed, I didnt test it correctly.
Ok, so it only needs to be added in the --help section.

**Comment by nado** [comment]
Found out that `--root` is not documented either.

**Comment by auriamg** [comment]
Log option has already been added in commit adceb3581231e3d08a987703695335100cc0bcc6
