### ISSUE TITLE
Change the default gamepad buttonmaps, and have multiple default layouts for different gamepads

### ISSUE THREAD

**Issue by Jammyjamjamman** [supertuxkart/stk-code#2096]
The default gampad mapping in stk is currently unuseable. When using an xbox360 controller, steering and accelerating are mapped to the same joystick, so steering and accelerating are not possible at the same time (I didn't bother checking out what the other default keys were).

Idea for the xbox360 layout:
My current keymap is shown below. This might not be such a great default layout to use because it's possibly not be very intuitive and it's desgned for left handed people. This however, is the keymapping I found least strenuous on my fingers. 
![xbox360stkbuttonmap](https://cloud.githubusercontent.com/assets/6165871/7289044/4f6cfefe-e962-11e4-8d5e-1d5775167b0c.png)

the input config file is given here: https://drive.google.com/file/d/0B49RhfctJ_lvSGhCdFF4bmsxQ00/view?usp=sharing which uses this driver: https://github.com/raelgc/ubuntu_xboxdrv .

Default inputs for other devices/ better default inputs would also be worth suggesting. Maybe inverting the buttonmaps for lefthanded/righthanded people would be a good idea too.

**Comment by hiker** [comment]
While I agree with this ticket, just a clarification: steering and acceleration is not (or at least should not be) bound to the same direction: steering is left/right; acceleration/breaking forwards/backwards - so you can actually use it with a single stick.

**Comment by Jammyjamjamman** [comment]
Cheers, just for uberclarification, when only using one stick for all the movement, you can steer and you can accelerate with the joystick, but you can't accelerate and steer at the same time (at least it's noot really possible with an xbox controller) so your kart ends up slowing down as you steer.

**Comment by hiker** [comment]
Hmm - that's strange, since I tested it. Could you try starting stk fromt he command line with "--gamepad-visualization"? This will bring up a simple gui showing you which buttons and sticks are pressed. Then try moving the stick to the top left (well, actually all directions) - do you see two axis changing?

**Comment by MCMic** [comment]
Hello
I can confirm that having to maintain the stick forward to move is not a good default choice. No other games are configured like this.

My config is not the same one as Jammyjamjamman though, I use (if using an xbox pad):
A - forward
X - sharp turn
B - brake
LB - nitro
RB - fire
LT - look back (So you can fire at the same time)
start - pause
back - thunderbird rescue
(I do not use an xbox pad but a logitech one, it’s mostly the same)

**Comment by auriamg** [comment]
Also see #2438. The defaults have been changed and should be better on most gamepads. We don't have different defualts for different gamepads, though

**Comment by Benau** [comment]
Now we use sdl controller mapping so we have a fixed layout in the begining

Notice we change left, right, up, down (steering and acceleration) to 1 stick to make it compatible with old dpad only gamepad, and make it as compact as possible because not all sdl controller has trigger bound (like from android)

**Comment by Benau** [comment]
see #2438 for additonal discussion
