### ISSUE TITLE
STK 0.9 won't compile on Salix OS 14.1 (requires libIrrlicht.a)

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#2099]
Using a modified version of the following build script.
http://slackbuilds.org/slackbuilds/14.1/games/supertuxkart/supertuxkart.SlackBuild
http://slackbuilds.org/repository/14.1/games/supertuxkart/
```
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CBoneSceneNode.d CBoneSceneNode.cpp
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CSkinnedMesh.d CSkinnedMesh.cpp
g++ -I../../include -Izlib -Ijpeglib -Ilibpng -DIRRLICHT_EXPORTS=1 -MM -MF CB3DMeshFileLoader.d CB3DMeshFileLoader.cpp
make: *** התיינבל םיללכ ןיא ךא ,`CBSPMeshFileLoader.o' תשרוד `libIrrlicht.a' הרטמ.  Stop.
```

irrlicht is installed:
http://slackbuilds.org/repository/14.1/libraries/irrlicht/?search=Irrlicht
```
$ slapt-get --filelist irrlicht
/usr/
/usr/doc/
/usr/doc/irrlicht-1.8.1/
/usr/doc/irrlicht-1.8.1/aesGladman.txt
/usr/doc/irrlicht-1.8.1/bzip2-license.txt
/usr/doc/irrlicht-1.8.1/changes.txt
/usr/doc/irrlicht-1.8.1/irrlicht-license.txt
/usr/doc/irrlicht-1.8.1/irrlicht.SlackBuild
/usr/doc/irrlicht-1.8.1/jpglib-license.txt
/usr/doc/irrlicht-1.8.1/libpng-license.txt
/usr/doc/irrlicht-1.8.1/readme.txt
/usr/doc/irrlicht-1.8.1/source.txt
/usr/doc/irrlicht-1.8.1/upgrade-guide.txt
/usr/include/
/usr/include/irrlicht/
/usr/include/irrlicht/CDynamicMeshBuffer.h

<truncated ~180 lines>

/usr/include/irrlicht/vector3d.h
/usr/lib/
/usr/lib/libIrrlicht.so.1.8.1
```

```
$ ls -1 /usr/lib/*Irrlicht*
/usr/lib/libIrrlicht.so
/usr/lib/libIrrlicht.so.1.8
/usr/lib/libIrrlicht.so.1.8.1
```

**Comment by deveee** [comment]
Are you package maintainer or you just want to build it for your own use?

Why do you use Slackware build script for 0.8.1 version?

**Comment by nado** [comment]
You mustnt write specific rules for irrlicht, the engine is Antarctica and bundled in the src tarball. Just follow the compilation procedure and it should compile.

**Comment by GreenLunar** [comment]
I want to build STK for my own use.  I use a Slackware build script for 0.8.1 version because I do not know (too lazy, actually) how to write one by my own.

Changes I made in that script are:
```
-VERSION=${VERSION:-0.8.1}
+VERSION=${VERSION:-0.9}
```
```
-UNTARRED=SuperTuxKart
+UNTARRED=supertuxkart
```
```
-tar xvf $CWD/$PRGNAM-$VERSION-src.tar.bz2
+tar xvf $CWD/$PRGNAM-$VERSION-src.tar.xz
```
I have no idea what else to do =/

@ryanpcmcquen, any chance you provide an updated SlackBuild?

**Comment by ryanpcmcquen** [comment]
@GreenLunar I am working on the 0.9 update, you should see it soon, some changes need to be made from 0.8.1. If you just can't wait, go ahead and plop the binary release in your home directory and go to town.

**Comment by ryanpcmcquen** [comment]
@GreenLunar, also note this comment from the SlackBuild:

```
# First build the Irrlicht (static) library.
#  Note: This is a forked, modfied copy of irrlicht-1.8
#        The original irrlicht library cannot be used, but both
#        coexist without problems.
```

**Comment by GreenLunar** [comment]
I would appreciate you posting an updated SlackBuild script at this thread, too, if you will.

**Comment by ryanpcmcquen** [comment]
Just follow slackbuilds.org/cgit/.

**Comment by ryanpcmcquen** [comment]
:penguin:
http://slackbuilds.org/cgit/slackbuilds/commit/?id=7f2be9cfb

**Comment by GreenLunar** [comment]
Thanks.
