### ISSUE TITLE
Remove our modifications to enet

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#21]
Enet was modified as part of gsoc, but the needed functionality can be achieved even with a standard irrlicht. From irc:
(14:07:01) hilnius: when adress is NULL, you actually still want to call that bind function
(14:07:22) hilnius: when you're a client you define your address as NULL actually
(14:08:06) hilnius: so whithout changing the order, it just does not bind the socket. When you change the order it normally assigns the socket considering we'll be a client (no ports open)
(14:08:39) hiker: Could you just set address->port = 0, address->host = INADDR_ANY?

**Comment by nado** [comment]
So, where are we now ? (yup, old issues crawling :))
