### ISSUE TITLE
Support embeded videos on our wiki

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2108]
It's not ideal that watching the videos takes people away from our web page, so we should try to embed videos instead of just linking them.
Quick googling gave:
http://www.mediawiki.org/wiki/Extension:EmbedVideo

**Comment by konstin** [comment]
The problem with the plugin you metioned is that it requires at least mediawiki 1.19 while we have only version 1.16.

**Comment by qwertychouskie** [comment]
Can this be closed now? (See home page of site.)
