### ISSUE TITLE
Unlock all tracks in multi-player mode?

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2109]
For discussion.

According to irc feedback it is quite frustrating if you just want to play with friends, and you only have 5 tracks.

**Comment by Flakebi** [comment]
I would like that. At the moment a problem is also that the game master decides the available tracks, so if the "wrong" player is created first, you have less tracks available.

**Comment by auriamg** [comment]
And maybe just add a way to cheat and unlock everything... Many people seem to want that. Would also help when testing, with RCs

**Comment by deveee** [comment]
This would be much less burdensome if we could remember challenges progress in user's online account. You could use your login on the other computer and you would have unlocked everything because you finished everything once in the past.

**Comment by hiker** [comment]
75b24c9 unlocks all tracks in multiplayer mode.

**Comment by hiker** [comment]
c91f965 unlocks all karts.

**Comment by hiker** [comment]
Synching using online account would be a different ticket imho (since it wouldn't solve the original problem - you play for the first time with your friend). The rest appears to be fixed.
