### ISSUE TITLE
[Chinese translation] Text rendered out of area in serveral SuperTuxKart 0.9 prompts

### ISSUE THREAD

**Issue by Vdragon** [supertuxkart/stk-code#2110]
As the following screenshot:
![supertuxkart_507](https://cloud.githubusercontent.com/assets/1192163/7316590/cfb73522-eaaa-11e4-8745-99d99cdfce04.png)
![image](https://cloud.githubusercontent.com/assets/1192163/7316702/cdf8e5e0-eaab-11e4-8880-bbd3417bbae6.png)

#### OS
Ubuntu 14.04 x86(32-bit)

#### Locale
zh_TW.UTF-8

#### STK source
<http://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9/supertuxkart-0.9-linux.tar.xz/download>

#### Graphics
NVIDIA GTS-250 using proprietary driver 331.113 from Ubuntu 14.04 software source

#### Desktop Environment
KDE from KDE Backports PPA

**Comment by auriamg** [comment]
This happens because STK will only wrap line on whitespaces, but in Chinese there appear to be very long words without spaces, like 可能會連線到伺服器下載附加元件並提醒您更新資訊。我們也會收集匿名的硬體統計資訊以協助 . Not sure what can be done about this? I am not every sure how to determine where it is legal to wrap. Maybe soft-line-break characters could be added to indicate where it's okay to split words?

**Comment by auriamg** [comment]
Will need feedback from someone who speaks chinese to know how to fix this properly

**Comment by Benau** [comment]
I think it's a problems for the translation po files..

according to the po file, for english the long part are split already but not the chinese one:

#: src/main.cpp:1201
msgid ""
"SuperTuxKart may connect to a server to download add-ons and notify you of "
"updates. We also collect anonymous hardware statistics to help with the "
"development of STK. Please read our privacy policy at "
"http://privacy.supertuxkart.net. Would you like this feature to be enabled? "
"(To change this setting at a later time, go to options, select tab 'User "
"Interface', and edit \"Connect to the Internet\" and \"Send anonymous HW "
"statistics\")."

msgstr "SuperTuxKart 可能會連線到伺服器........" (one line only)

So just need to update the po files (both simplifed and traditional).

I can do that later.

**Comment by Benau** [comment]
Also it seems that when you use a bigger resolution, the chinese words will be placed correctly.

But the english words will be seperated itself in small resolution.

**Comment by Benau** [comment]
But that wasn't agood solution, chinese(even japanese or koraen) (CJK) can be split in no matter which postion.

I think we should change the way stk handle these words.

Let me have a look in src

**Comment by auriamg** [comment]
Adding spaces may be the simplest solution for now, I think splitting across lines is done by irrlicht and updating irrlicht to follow all unicode rules about line splitting would be quite difficult

**Comment by Benau** [comment]
when player choose a different resolution, the space for the words to display will be different.

sometimes even a little words won't fit in small resolution, which they are not suitable to add space.

screenshot provide later,i'm outside

in fact i i've found the place in irr to add spliting support. 

i will tell if any progress is made

**Comment by Benau** [comment]
![default](https://cloud.githubusercontent.com/assets/3252341/8937130/2c7a41b8-3589-11e5-803e-1a9fcaf3cfe4.png)
as you can see, the chinese words display out of the box, but they are not very long.

but for larger resolution they will be fit enough

**Comment by Flakebi** [comment]
If you add spaces (not newlines) the text will be split only if it's necessary (I think there's also a Unicode break character that works). That means if the resolution is big enough, the text won't be split, but on a tiny screen you still won't see the text out of bounds.

**Comment by Benau** [comment]
Ok work done, here's the patch:

http://pastebin.com/M8wHa2KK

Differents:

![2015-07-29 09-46-42](https://cloud.githubusercontent.com/assets/3252341/8948695/750bbef4-35dc-11e5-996f-6486a44b1e76.png)

![2015-07-29 09-47-11](https://cloud.githubusercontent.com/assets/3252341/8948699/7985e4be-35dc-11e5-913d-d7c0955e7943.png)

for koraen both have the same effect without out of range.

Only smallest resoultion showed, the big one should work as long as small one fits, which i tested too.

In fact in chinese (even jp and kr) we aren't normally add spaces between characters, especally for short sentences (like the multiplayer joining screen i showed). It should make translators to do less work.

For other languages, my patch shouldn't affect them, I tested on most languages.

Anyway tests and comments are welcome, I haven't written for more than 1 year.

If you like, i can do pull request with chinese translation update (both simplified and tranditional).

**Comment by Benau** [comment]
Btw the elwidth - 23, 23 is quite adjustable, maybe a smaller is better.

Because i find that with a smaller one (even without adjustment) the words sometimes go too close to the edge of displaying region.

But when too much some space will be wasted.

I would like to get more ideas from @auriamg

**Comment by auriamg** [comment]
Hi, I applied a modified version of your patch. The main change is that I'm pretty sure that
```
if ((Text[i] > CJK_START || Text[i] < CJK_END) 
```
should have been
```
 if ((Text[i] > CJK_START && Text[i] < CJK_END) 
```

Thanks for your contribution!
