### ISSUE TITLE
Scene rendered pale white when turn the graphics level to max.

### ISSUE THREAD

**Issue by Vdragon** [supertuxkart/stk-code#2111]
Refer the screenshot:
![overworld-2015 04 24_18 18 15](https://cloud.githubusercontent.com/assets/1192163/7317154/f8baf152-eaaf-11e4-945a-3accff5cecfe.png)
Issue can't be reproduced when I turn down the graphics level

#### OS
Ubuntu 14.04 x86(32-bit)

#### Locale
zh_TW.UTF-8

#### STK source
<http://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9/supertuxkart-0.9-linux.tar.xz/download>

#### Graphics
NVIDIA GTS-250 using nouveau driver from Ubuntu 14.04 software source

#### Desktop Environment
KDE from KDE Backports PPA

**Comment by deveee** [comment]
Could you attach stdout.log file? It should be in: ```$HOME/.config/supertuxkart/0.8.2/stdout.log```

**Comment by Vdragon** [comment]
@deveee Here you are.
https://gist.github.com/Vdragon/cfd97b0ba77092d7a36c

**Comment by Vdragon** [comment]
I can only trigger the issue when graphics level > 4

**Comment by auriamg** [comment]
Unfortunately, this is probably a driver bug, I have never seen this before, and no relevant error in the log as far as I can tell

**Comment by samuncle** [comment]
@Vdragon can you try instead of enabling graphic quality by level, to go in the advanced mode and enable each option one by one so we will be able to pinpoint exactly where the issue is :)

**Comment by samuncle** [comment]
Oh and it seems you are using nouveau, which is the open source driver. Can you try with the proprietary nvidia one please

**Comment by Arthur-D** [comment]
Yes, this must be a driver bug. I am using the same graphics card as you and have no problems with it using the proprietary NVIDIA driver. The nouveau drivers are not as feature complete or may contain other bugs.

**Comment by deveee** [comment]
We could at least add some graphics restrictions for nouveau driver. But I can't use my graphics card with nouveau driver at all :P

Could you check which option in graphics level 5 causes this issue? Also did you check if it works with stable mesa release?

And yes, using nvidia proprietary driver is highly recommended.

**Comment by Vdragon** [comment]
Hi, I've upgraded the kernel and X stack to utopic and I decided to close this issue until I have opportunity to test on the original environment.
Thanks for helping!

**Comment by Vdragon** [comment]
I no longer can reproduce this issue on utopic kernel + X stack, thus definitely it's a driver bug :P
