### ISSUE TITLE
Can't configure controller mapping

### ISSUE THREAD

**Issue by rcpoison** [supertuxkart/stk-code#2113]
Options -> Controls -> Microsoft X-Box 360 pad (x2):
(or any other controller entry)
clicking/double clicking binding won't bring up key binding dialog
![supertux-binding-menu](https://cloud.githubusercontent.com/assets/281286/7319405/98de0f4a-ea95-11e4-8081-a92926a2985c.jpg)

Works for: Options -> Controls -> Keyboard 0
![supertux-binding-menu2](https://cloud.githubusercontent.com/assets/281286/7319447/e2e0bd36-ea95-11e4-82ce-fa2db5b77e63.jpg)

No errors in console.

Tested with 0.9 and latest git (1cc3a0f0b8)

**Comment by hiker** [comment]
Did you try pressing the 'select' key on the controller (probably A).

**Comment by rcpoison** [comment]
Yes I did.
I am able to bring up the keybinding dialog for the keyboard using the controller, I am however not able to bring up the keybinding dialog for anything besides the keyboard using the mouse, keyboard or any attached controller.

**Comment by hiker** [comment]
I tried with a similar setup (a no-name gamepad and 2 xbox 360 controller), and had no problems setting them up. We would need some debugging help from someone who can reproduce this issue.

**Comment by krilbe** [comment]
Possibly related to my problem with two Xbox 360 controllers, one wireless and one wired? I am able to bring up the settings for them and key binding dialog too, but the setup seems to mix them up. Maybe some kind of (id?) clash behind the scenes that cause both problems?

**Comment by Fedik** [comment]
I got the same problem with some old Gamebird controller, and solution is: you need to "turn off" all other detected controllers. 
Open the controller configuration and push "turn it off". So in result you should have only 1 enabled controller and Keyboard.

**Comment by qwertychouskie** [comment]
@Fedik Was that with 0.9.2 or git?  A bunch of gamepad issues were fixed in git recently, it may be worth testing with git.  Or the 0.9.3 RC should be released in a couple of days, maybe test then.

**Comment by Fedik** [comment]
@qwertychouskie actually it was 0.9.1 😄  on Ubuntu 16.04
If I will not forget, I try to test again on 0.9.3 RC, when it will be available 😉

**Comment by qwertychouskie** [comment]
Sounds good.  If you add https://code.launchpad.net/~stk/+archive/ubuntu/dev you should get 0.9.3-rc1 very soon.

**Comment by Fedik** [comment]
so, I have tested with 0.9.3-rc1 and it works good, without requiring to disable unused/broken gamepad
thanks!

**Comment by qwertychouskie** [comment]
@Fedik Glad it worked, thanks for testing!
