### ISSUE TITLE
kart able to access portions of water without being rescued

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2114]
It's a minor bug that occurs in phase "cocoa temple", but it is perfectly accessible to anyone, that I discovered by chance in the same place you can access portions of water without the ransom is triggered automatically and also You can walk with head kart down. This is just the beginning, in the left lane, where it has a lead on the wall, see:

https://drive.google.com/file/d/0B-kzH29nQAeONjRSaTZtOGl1Mmc/view?usp=sharing

It was tested on arch linux (current version) and 0.9 SuperTuxKart end.
Note: Please if they need, copy the video link, for soon I will take my google drive.

**Comment by samuncle** [comment]
Okay ^^. People find creative way to go outside. I will correct this as soon as possible

**Comment by ianclever** [comment]
Thank you for your attention and congratulations new version is very pretty, I like to see.

I apologize for the poor quality of the video, the gtk-recordMyDesktop, has given me work ....

Then there is another similar bug in the same phase, there in the mill, tomorrow I'll post the video so you can see.

I have countless others that I knew in the previous version, but not yet RELEASE every stage of this version, so I'm releasing send some more. You suggest that send all inbutidos that same "issue" or the bug of each phase I find separately?

If I may, I have a suggestion to make which is already a standard for a long time in other commercial games: put a barrier (invisible) or something, around the entire stage preventing some curious as I able to take the kart beyond the phase boundaries and the kart fall for a long time to be rescued.

**Comment by samuncle** [comment]
To be honest I am not that harsh to prevent people from exploring. I absolutely hate when in modern games you have something like return to combat zone in 3, 2, 1..

There is already some invisible walls in this level and I know some tricks to get outside. However I will let them probably because they are quite hard to find and if someone is curious to explore the world why not :).

I try to prevent the vast majority of tricks but I feel if it's too prefect it kinda prevent the replaying value of the game trying to find ways to get outside and explore the world :)

Also since it doesn't give you an advantage it's okay I guess

**Comment by samuncle** [comment]
Oh and I have added something on the carnival version of cocoa :) (the map available with the gift for donators) when I discovered it was possible to go under the map. ^^

I think we all love exploration at some point

**Comment by ianclever** [comment]
the "cocoa temple" the mill bug as promised:
https://drive.google.com/file/d/0B-kzH29nQAeOVUZjMUgyYWJrWDQ/view?usp=sharing

**Comment by ianclever** [comment]
In the same part of the track where I showed the first bug, I suggest you do a general check of the area, I could "walk on water" from another point in that same cave.

Walking through the stage, in addition to two other bugs already reported it up, I found another one, but I'm not sure if it's even a bug or if it is deliberate. see:

https://drive.google.com/file/d/0B-kzH29nQAeOaFpsZ0RRcU1NN3c/view?usp=sharing

**Comment by Benau** [comment]
Fixed in latest asset
