### ISSUE TITLE
Achievement "Arch Enemy" does not unlock

### ISSUE THREAD

**Issue by cdw1978** [supertuxkart/stk-code#2118]
I tried unlocking this achievement, "hit the same kart at least 5 times in one race" in several ways.  I tried hitting the kart with items (bowling ball and cupcake), as well as running into the opponent kart from various direction.  

This could be a user issue (in that I'm not sure what a "hit" is.  This looks like a bug; however, if there is something I'm doing wrong please let me know.

**Comment by alketii** [comment]
I tested, same here.

**Comment by Wuzzy2** [comment]
I confirm this.

**Comment by hiker** [comment]
I broke that when I tried to avoid  a display like '6/5' as achievement progress.
