### ISSUE TITLE
Cyrillic font defects

### ISSUE THREAD

**Issue by meequz** [supertuxkart/stk-code#2121]
Hi,
I just started to translate SuperTuxKart to Belarusian, and I see three problems:

1) There is no "ў" in charset. It is a belarusian letter.
https://www.dropbox.com/s/if6pbzez6u3t6jt/stx-be-1.png?dl=0

2) Character "і" comes out of the line in bottom.
https://www.dropbox.com/s/kr5t5epf4kqn1gm/stx-be-2.png?dl=0

3) Cyrillic font at all is pretty weird compared to Latin.
https://www.dropbox.com/s/a112xmkdeaqz6bc/stx-be-3.png?dl=0

At least the first issue have to be fixed for my translation work.

**Comment by auriamg** [comment]
Hi, sorry for the late reply

I have fixed item 1 and improved a lot item 2 (it's not perfect but much better)

regarding item 3, we are working  with different fonts here, so unfortunately a mismatch is to be expected. Also making bitmap fonts for STK is a rather time-consuming process, so I'm afraid the font is not likely to change in the short term
