### ISSUE TITLE
kart getting access to the top of the buildings in phase "shiny suburbs"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2122]
The bug occurs when the shortcut right side of the viaduct, where the car to escape from above can walk on the buildings that are just below, without being redeemed automatically. see:

https://drive.google.com/file/d/0B-kzH29nQAeOcU13NHRqX3dsd0E/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by qwertychouskie** [comment]
Probably can be closed, as this is most likely going to be replaced be Candela City in 0.9.3.
