### ISSUE TITLE
Bad gift box placement on Shifting Sands for reverse direction

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2123]
If you start the Shifting Sands track on reverse direction with many karts (>=10), some gift boxes are placed directly on kart positions, giving them an unfair advantage.

STK version: 0.9

**Comment by gnutechs** [comment]
Even on normal direction track the gifts are way too close to the starting line, causing chaos at the start of the race.

**Comment by hiker** [comment]
The new FTL code now uses the rear starting positions, so we need to check all tracks (in both directions) to make sure no kart is starting on an item. We should use this opportunity to make sure we place at least three karts in one line (to reduce the length of the starting field).

**Comment by auriamg** [comment]
Fixed in SVN, thanks for reporting
