### ISSUE TITLE
Arch Enemy achievement appears to be impossible to get

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2126]
For me, the “Arch Enemy” achievement seems to be impossible to get: I have bombed the same kart way more than 5 times in a race and still did not get it.

Is it just me or have I spotted a bug?

STK version: 0.9

**Comment by cap44** [comment]
it's not just you, issue #2118

**Comment by Wuzzy2** [comment]
Oops, sorry. I am closing this as duplicate. :/
