### ISSUE TITLE
GUI displays only 5 extras when having more than 5 extras of a kind

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2127]
If you have more than 5 extras (i.e. 8 bowling balls) of a kind, the GUI still only shows 5 of them. Note that in Time Trial races with more than 5 rounds, you automatically have more than 5 turbo boosts.

My humble suggestion to fix this would be this: In case the player has more than 5 extras of one kind, display a number and then a (single) corresponding symbol next to it, like “8X”, where “X” stands for the symbol (for example, a bowling ball when you have 8 bowling balls).

STK version: 0.9

**Comment by nado** [comment]
We could also print the number of items greater than 1 if we do that.
Only one ball with a « x2 / x3 / etc »

**Comment by hiker** [comment]
The difficulties with this are translations - some languages might have the multiplier as prefix, not as postfix (?)

**Comment by nado** [comment]
So without multiplier ? Just the number and the item icon.

**Comment by Wuzzy2** [comment]
It gets even trickier if we go into languages which do not use arabic numerals. :-/

Another solution would be to make a hard limit of 5 extras, you cannot carry more. The problem is, this would limit the number of turbo boosts available in time-trial as well. :-(

**Comment by nado** [comment]
Then we could add an entry in the .po file ?

**Comment by auriamg** [comment]
STK only supports arabic numerals though, so that it is not really an issue

I think adding "x6" next to the icon would be a good solution. Some languages may favor other presentaitons, but considering that we already only support arabic numbers it would not be a regression to add more

Any taker?

**Comment by Benau** [comment]
Result:
![2016-01-31 10-10-13](https://cloud.githubusercontent.com/assets/3252341/12699765/e2e6dc84-c802-11e5-861d-3076f28e5a2f.png)
