### ISSUE TITLE
Very unfair track edge on Snow Peaks

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2129]
If you drive on the Snow Peaks track in reverse, there is a really nasty edge right on the track where you can sometimes get completely stop. This is very frustrating.

Here is a screenshot (it is located at the top of the track):

https://i.imgur.com/G60WOxl.png

(Note: If above link is broken, please contact me so I can fix it.)

See also: #2124

STK version: 0.9

**Comment by auriamg** [comment]
Fixed in SVN, thanks for reporting
