### ISSUE TITLE
Allow reverse direction for Gran Paradiso Island

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2130]
Is there any reason why the reverse direction on Gran Paradiso Island is prohibited? I can perfectly drive it in the reverse direction without problems. I can't drive on the wood bridge alternative path, however, but I don't think this is an issue, since the main path is fully drivable.

If there is no reason, please allow the reverse direction for this track.

STK version: 0.9

**Comment by samuncle** [comment]
done
