### ISSUE TITLE
Glitches on Shiny Suburbs

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2131]
There are some glitches in the landscape of Shiny Suburbs which become especially noticable if you drive in reverse. I am talking about poorly “closed off” areas where there should be terrain or an object but the background shines through.

Here are two screenshots (warning: >1 MiB in total):
- https://i.imgur.com/olEEFdS.png (this wall seems to be slightly floating on some other places as well; this is mostly noticable when you drive in reverse)
- https://i.imgur.com/aDXweYH.png (this is the start of the shortcut (not the wooden bridge) when viewed from the other direction)

STK version: 0.9

If the screenshots are gone, please contact me so I can re-upload them.

**Comment by fHachenberg** [comment]
I have removed the glitches. How can I contribute the modified blend file?
![city-2016 09 20_21 24 19](https://cloud.githubusercontent.com/assets/524304/18685547/d69f8c86-7f78-11e6-9d96-7dd060c3d9ba.png)

**Comment by auriamg** [comment]
You can upload it on the forum, or any other filesharing website and provide the link

**Comment by qwertychouskie** [comment]
You could use something simple like https://file.pizza/, it does not require accounts, etc.

**Comment by qwertychouskie** [comment]
Or put it in a zip file and drag&drop into the box where you write the comments.

**Comment by fHachenberg** [comment]
https://file.pizza/gorgonzola-whitebait-prawn-onion

**Comment by Wuzzy2** [comment]
@fHachenberg: Your link is dead.

**Comment by fHachenberg** [comment]
strange. Let's try again
https://file.pizza/beef-roquefort-avocado-marjoram

**Comment by qwertychouskie** [comment]
@fHachenberg You should read https://github.com/kern/filepizza#faq, or just put it in a zip file and drag&drop into the box where you write the comments.

**Comment by qwertychouskie** [comment]
Maybe I wasn't clear, that link is dead too.

**Comment by qwertychouskie** [comment]
Probably can be closed, as this is most likely going to be replaced be Candela City in 0.9.3.

**Comment by Benau** [comment]
@auriamg candela city track and blend is added, delete Shiny Suburbs (you?)

**Comment by auriamg** [comment]
Done
