### ISSUE TITLE
Missing translation strings in 0.9

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2132]
I have discovered some untranslatable strings in 0.9.

They are:
* “Mosquito Hunter”
* “Please select a Grand Prix”

Post here if you find more untranslatable strings in 0.9.

**Comment by hiker** [comment]
Please select a Grand Prix was fixed recently, and I do see Mosquito Hunter in the old pot file. What makes you think that this is not translatable?

I'll leave this ticket open for now so what we make sure that the next release will indeed include the fix for "Please select a Grand Prix".

**Comment by Wuzzy2** [comment]
Oops, I was indeed wrong about “Mosquito Hunter”.

**Comment by nado** [comment]
No, its just that the counter is not incremented until success, that could be interesting to update to the best while we dont get the achievement.

**Comment by hiker** [comment]
So it seems like it's all fixed ;)
Thanks!
   Joerg
