### ISSUE TITLE
Poorly placed start/finish line on a couple of tracks

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2134]
For some tracks, the start/finish line (or banner etc.) is poorly and incorrectly placed on a couple of tracks.

The offending tracks are (sorted from most serious to least serious offenders):
- Shifting Sands (actual finish is surprisingly far in front of the gate. Could be fixed by either moving the whole gate structure or by drawing a simple but well-visible line in the sand. Or both).
- Gran Paradiso Island (finish is placed way before the huge structure).
- Hacienda (the gate strongly suggests a start/finish but the finish is way before that. Could be fixed by drawing a line in the sand)
- STK Enterprise (has no actual marking, but since the word “START” is now used, this strongly implies the gate is the start/finish line, which it isn't. An additional drawn line might help)
- Old Mine (actual finish is a bit behind the banner)
- Zen Garden (slighty but notable in front of the gate)
- Snow Peaks (the finish is placed slightly, but still notably in front of the gate)
- Green Valley (slightly behind the banner)
- Nessie's Pond (very slightly in front of the flags. A road marking might help a lot)
- XR591

(My point of reference is always the forwards direction of a track.)

STK version: 0.9

I think most of the issues can be fixed by drawing a marking on the ground at the correct position. If neccessary, suggestive structures (such as banners) need to be moved as well.

Here is a TODO list for your convenience:
- [x] Shifting Sands
- [x] Gran Paradiso Island
- [x] Hacienda
- [x] STK Enterprise
- [x] Old Mine
- [x] Zen Garden
- [x] Snow Peaks
- [x] Green Valley
- [x] Nessie's Pond
- [x] XR591

**Comment by qwertychouskie** [comment]
Funny that XR591 hasn't been mentioned, it is one of the worst offenders...

**Comment by Wuzzy2** [comment]
OK.

**Comment by Benau** [comment]
In order not to break bundle game replay, some little adjustment has done to track structure

**Comment by Wuzzy2** [comment]
Why is this closed? Have ALL the offending tracks been fixed?
