### ISSUE TITLE
Old Mine graphical glitches in reverse mode

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2136]
I discovered two graphical glitches for the Old Mine track, they are mostly visible when driving in reverse or looking behind you:

* The finish banner is invisible when looking on it from the other direction
* You can clearly see a big black “hole” and clearly see the kart appearing out of thin air when you are driving towards the finish (when driving backwards).

STK version: 0.9

**Comment by auriamg** [comment]
Fixed in svn
