### ISSUE TITLE
Wiimote support disabled in OSX binary

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2138]
The 0.9 OSX binary doesn't have wiimote support. Investigate why and enable it back

**Comment by auriamg** [comment]
That is because it's looking for the 'bluez' package, would need to check to package it for OSX, or use regular (non-bluez) bluetooth stack on OSX. Not too interested in working on this for now...

**Comment by joewestcott** [comment]
Is this fixed in 0.91?

**Comment by auriamg** [comment]
No, as hinted in the comment I posted just above :)
Sorry about that, it's just that we have no one maintaining OSX at this time, I'm just doing builds but little more

**Comment by joewestcott** [comment]
No problem, feel free to ping me for OSX/wiimote testing :)

**Comment by qwertychouskie** [comment]
`wiiuse` 0.15.1 supports macOS (https://github.com/wiiuse/wiiuse/releases), maybe we should sync with upsteam?  At one point we had some changes to `wiiuse` but that might not matter anymore.

**Comment by qwertychouskie** [comment]
https://github.com/supertuxkart/stk-code/pull/3626 opened to update to upsteam.

**Comment by qwertychouskie** [comment]
Now that Wiiuse is updated, can this be looked at?  @MTres19 You have a mac now, right?

**Comment by MTres19** [comment]
I do not have a Wiimote

**Comment by qwertychouskie** [comment]
I just did a test with 0.10-beta1 and Wiimote support is indeed included in the binary.  This can be closed.
