### ISSUE TITLE
Bad russian font

### ISSUE THREAD

**Issue by laol** [supertuxkart/stk-code#2140]
Russian font in STK is now Garamond-like serif.

**Comment by auriamg** [comment]
Do you have any replacement font suggestions? It would need to be an open source one. It's hard for non-russian speakers to judge which font looks good

**Comment by Benau** [comment]
better now @laol ?

![2015-10-13 08-42-30](https://cloud.githubusercontent.com/assets/3252341/10442693/93a73c9e-7187-11e5-8cdf-53d5a3ca2ba1.png)

**Comment by laol** [comment]
Yes, it's better, but it's very far from english font. Why?

**Comment by Benau** [comment]
What do you mean by 'far', too different from?

It freesans, so after freetype stk is ready, only one font will be used for one language.

**Comment by laol** [comment]
Why do not you make english-font-based russian font?

**Comment by Benau** [comment]
It isn't made, but rendered by freetype (ttf file)

no need to make a font!

**Comment by auriamg** [comment]
The freetype branch has been merged, the font should be better now
