### ISSUE TITLE
Sand invisible on the stage "quicksand"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2142]
As the title suggests, the phase "quicksand" there is a visible location from the track, where part of the sand is invisible. see:

![areia_invisivel](https://cloud.githubusercontent.com/assets/12104659/7353217/682c3606-ece8-11e4-92e2-575ff3455107.png)

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by auriamg** [comment]
This track will eventually be remade, it's unlikely that any major effort will be spent on this track

**Comment by qwertychouskie** [comment]
I just checked, this issue is not present in the current git version, see ![http://i.imgur.com/2esvU2U.png](http://i.imgur.com/2esvU2U.png).  Can this be closed?
