### ISSUE TITLE
kart walking on water and flying off the track without automatic redemption at the stage "green valley"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2143]
The bug occurs in several track points where the terrain is too high, the kart escapes, but is not redeemed automatically.
In the same phase is also possible to walk into the water. see:

https://drive.google.com/file/d/0B-kzH29nQAeON2RBd25XZzZ6WnM/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by Benau** [comment]
fix with .spm
