### ISSUE TITLE
kart off the road and into the pocket without being redeemed automatically in phase "miniature"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2144]
In phase "miniature" kart off the road at a given point and is not redeemed automatically, but this point can not return the track without assistance.

In another point you can enter in the pocket without being redeemed automatically. see:

https://drive.google.com/file/d/0B-kzH29nQAeOYmdySW9DblNCMDA/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by Benau** [comment]
Fixed with spm
