### ISSUE TITLE
Trees and shrubs floating in "blackhill mansion"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2145]
Not a major problem and not very relevant, but in some stage of points "blackhill mansion" you can see some trees and shrubs "floating". see:
![arvore_flutuante1](https://cloud.githubusercontent.com/assets/12104659/7359706/090ae8fe-ed18-11e4-938c-b3b04da112ea.png)
![arvore_flutuante2](https://cloud.githubusercontent.com/assets/12104659/7359716/19629c9c-ed18-11e4-93a4-1046d686dfe7.png)

**Comment by qwertychouskie** [comment]
This can probably be closed, as the new mansion will be in the gift package for 0.9.3 and included in a version after that, so this old track probably will not be getting more fixes.

**Comment by auriamg** [comment]
@qwertychouskie please at least wait until the new track is committed to svn before posting these kinds of comments. Reminding us that we intend to replace the track (but it's not done yet) is just wasting our time. We can close the tickets when the new track is actually done and not based on future plans.

**Comment by Alayan-stk-2** [comment]
Same as #2235 

The track will be replaced in the next version.
