### ISSUE TITLE
Kart getting great advantage when accessing external area in phase "island of Gran Paradiso"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2146]
In the "island of Gran Paradiso" early on, if the kart go into a pool of water, it comes up a lot in front, thereby gaining huge advantage. see:

https://drive.google.com/file/d/0B-kzH29nQAeOSzEtVm5tWHBzV1E/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by Flakebi** [comment]
Are you sure that it's an advantage? If I finish the lap, I'm still in lap one which means I'm way behind the other karts. I think this is the same bug as #1063 and only happens before you drive a bit further (on the track).
Anyway, thanks for the report, that means that there are more users and tracks affected :-).

**Comment by ianclever** [comment]
In fact, it is actually a great disadvantage. :)

**Comment by qwertychouskie** [comment]
Yep, tested, seems a dupe.  Can we close this?

**Comment by auriamg** [comment]
Closing this ticket since it does not appear to provice any advantage
