### ISSUE TITLE
kart falls off the track and is not automatically redeemed at the stage "old mine"

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2147]
Over the bridge in several places kart falls without being redeemed automatically.

Later on you can hang with the kart into a hole without being rescued.

And you can still access an area where a train car comes out clearly from the wall where the kart falls into an abyss with no explanation. see:

https://drive.google.com/file/d/0B-kzH29nQAeOZ0JZOV9ydkI3a2s/view?usp=sharing

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by qwertychouskie** [comment]
It seem both the "water" and the reset plane are missing here...
