### ISSUE TITLE
Grid only visible from one side in Fort Magma

### ISSUE THREAD

**Issue by ianclever** [supertuxkart/stk-code#2148]
The bug is punctual, occurs only in a part of the bridge over the magma in the cave.

Another bug that occurs is the "ghost grid" :), call it so, for the outside of the mansion you can see a grid, but on the inside it is just invisible. you may notice that both the video as the images. see:

https://drive.google.com/file/d/0B-kzH29nQAeOZlpiX0pFOWI5bEk/view?usp=sharing

grill out:
![fonte_de_magma_fora](https://cloud.githubusercontent.com/assets/12104659/7362378/4bbc4244-ed3e-11e4-9206-361d5eea6761.png)

grid within:
![fonte_de_magma_dentro](https://cloud.githubusercontent.com/assets/12104659/7362381/629b5b58-ed3e-11e4-8458-b1be0886bc59.png)

tested in arch linux (current version) and SuperTuxKart (0.9)

**Comment by qwertychouskie** [comment]
@ianclever The fence has been fixed, though the rescue issue still exists.

**Comment by Alayan-stk-2** [comment]
Both issues still exist for me on the latest master and svn.

**Comment by Alayan-stk-2** [comment]
The rescue issue has been fixed, the fence issue persists.

**Comment by qwertychouskie** [comment]
The problem here is that textures with `alphatest` have backface culling enabled when in most situations this causes problems (vegetation, etc.).
