### ISSUE TITLE
Cocoa Temple crash at startup

### ISSUE THREAD

**Issue by Schweineschwarte** [supertuxkart/stk-code#2150]
My System:
OS: openSUSE 13.1 x86_64
gfxcard: NVIDIA GeForce GTX 550 Ti with driver 340.76

Every time I want to start the map Cocoa Temple supertuxkart crash (same procedure on story-mode or singleplayer).
If I start supertuxkart with the Terminal, it calls some warns.

Terminalmessage: https://pastee.org/jrskf
stdout.log (in .config/supertuxkart): https://pastee.org/dvx9z
My Hardware: https://pastee.org/49rj6

**Comment by auriamg** [comment]
Hi, could you please post the complete terminal output?

Also, I think this is the case from your paste, but are you able to confirm you are using the nvidia binary driver and not the Nouveau driver? Nouveau is not quite mature enough to play STK at this time

Also, do you think you would be able to run STK in gdb to obtain a stack trace? ( http://forum.freegamedev.net/viewtopic.php?p=31470#p31470 )

**Comment by Schweineschwarte** [comment]
Hello,
I use the nvidia binary.
At my test, rarely Cocoa could be start, but mostly it crashed.

Full Terminal output with crash: https://pastee.org/h4pn
Full Terminal output with NO crash: https://pastee.org/szh4h
Full gdb output with crash: https://pastee.org/89heq

**Comment by deveee** [comment]
Looks like the application process has been killed:
"Program terminated with signal SIGKILL, Killed.
The program no longer exists."

Here is some maybe useful info:
http://stackoverflow.com/questions/12288550/c-linux-binary-terminated-with-signal-sigkill-why-loaded-in-gdb

Do you have enough free RAM when you start the game?

**Comment by Schweineschwarte** [comment]
Oh, thats right... I looked into '/var/log/messages' and I find the process execution to kill supertuxkart.
https://pastee.org/539c4

But I have 2GB RAM and my graphiccard has 1536MB RAM, too. Why is it insufficient for Cocoa Temple?

**Comment by deveee** [comment]
On my computer STK needs 1,1 GiB just after start and 1,9 GiB when I
started Cocoa Temple with three oponents (1280x720, highest settings).
Plus operating system which needs maybe 1-2 GB...

I didn't think that Cocoa needs that much memory.

You can try to disable high resolution textures, maybe this will help.

And ticket probably can be closed.
