### ISSUE TITLE
Main menu graphical issues on 800×600 resolution

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2151]
When playing STK in a resolution of 800×600, there are some problems with the main menu.
I hope at least some of them can be resolved.

* The buttons (OK and cancel) in the grand prix editor after you clicked “add” are almost off-screen
* Many strings are simply too long in many of settings menus, especially advanced graphics settings and when using German as language. I am not sure how to fix that one, maybe smaller font or the extreme solution, simply cutting text off?

STK version: 0.9

**Comment by auriamg** [comment]
Sorry, 800x600 is not a supported resolution, minimum is 1024x768, if you use anything smaller it's "at your own risk".

Though we should probably not offer it in the menus
