### ISSUE TITLE
Possible to add reverse tracks in GP editor for tracks which are non-reversible

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2158]
It is possible to add reverse tracks in GP editor for tracks which are non-reversible, such as Cocoa Temple.

How to reproduce this:
* Start STK
* Open GP editor
* Add new GP
* Select any reversible track, such as “Oliver's Math Class”
* Tick the reversal checkbox
* Select Cocoa Temple
* Add this track to the GP
* Now look in the track list

Cocoa Temple *should* show “No” in the reverse column, but it shows “Yes”.

Luckily, when you actually play this GP, the game seems to ignore this and always forces the forwards direction, regardless what the GP dictated.

But it's still a minor bug in the GUI which can be irritating.

STK version: 0.9

**Comment by deveee** [comment]
It should work now.

There is still possible an inconsistency. For example I added a track which was available to race in both directions. Then someone has updated this track and now it's available to play only in one direction. But I already have added it in my GP. But it seems to be really minor issue.
