### ISSUE TITLE
Possible to repeat the same race in a GP as many times as you like

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2161]
In a Grand Prix (outside of Story Mode), it is possible to retry the same race over and over again without any penalty.

I have found 2 ways to achieve this.

Way 1:
* Start GP
* Finish some races (at least 2)
* Assume your last race was bad (ranked last, etc.)
* At one point, when asked to continue the GP or abort, choose “abort”
* Go into the singleplayer menu, choose the same GP and click the “load” button

Way 2:
* Start GP
* Finish some races (at least 2)
* Assume you are deciding your current race is going to be bad (you will probably rank last, etc.)
* Hit [Esc], select “Exit to main menu”
* Go into the singleplayer menu, choose the same GP and click the “load” button

After doing one of the steps described above, you will now be able to repeat the previous (bad) race again. You can repeat this as many times as you like.

This is bad IMO because this technically betrays the whole point of a GP.

This can be fixed by various means:
* If the player gives up a race, immediately save the GP status so the player will continue with the next track when continuing the GP.
* If the player leaves a race in mid-race (after the start signal), treat it as if the player has given up. Award 0 points for this race advance to the next race (if it was not the last race) and save the GP status
* I am unsure what should happen with the “abort GP” button which is shown after the end of a race. Since GP status is now automatically saved, it seems to be a bit inconsistent now. Maybe replace this with “Leave to main menu and save progress”? I am not sure about this, so what do you think?

(STK version: 0.9)

**Comment by konstin** [comment]
Imho this is no problem. If people want to cheat, they'll always find a way to do that and as saving GPs will always be only available in the offline single player, there's no point in preventing this very special case. If you want to repeat a difficult track over and over you could also e.g. copy the config and restore every time you had bad score. Even worse, as long as there is no way of saving the current state of a race (i.e. saving mid-race) you could simply kill STK, restart and try the track again

**Comment by hiker** [comment]
I agree with that, the convenience of saving is much more useful than preventing to try a race in a GP again.
