### ISSUE TITLE
Possible to switch kart after re-loading GP

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2162]
If you play a GP (not in Story Mode), leave at some point, then load the GP's progress again, you could have a kart different from the kart you started the GP.
It always takes the kart you have selected right before loading the GP rather than the kart you chose when you have started the GP.

I don't know if this intentional, but I do not think that players should be allowed to change their kart in mid-GP.

STK version: 0.9

**Comment by konstin** [comment]
> I don't know if this intentional, but I do not think that players should be allowed to change their kart in mid-GP.

Why not? In future releases, karts will have different properties (speed, weight, etc.) so a player might have the desire to change his kart later. Imho keeping this freedom is better than extra work to remove it.

**Comment by Wuzzy2** [comment]
It is because GPs become slightly more challenging this way.
Also, the kart-switching looks unintentional to me. Otherwise, the game would have exposed the possibility to switch karts in mid-GP more prominently, perhaps in the pause menu or in the menu after you finished a race. Currently, you have to jump through a couple of hoops until you actually switched your kart.
