### ISSUE TITLE
Arbitrary e-mail address length restriction of 50 characters

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2164]
According to a string I found while translating, STK 0.9 appears to reject e-mail adresses which are longer than 50 characters (bytes/octets/…). The string is question is “Email has to be between 4 and 50 characters long!”. I have not actually tested if STK actually rejects e-mail adresses of this length. But if this applies, this is a problem.
Because this is an abitrary restriction, because e-mail addresses can be much longer, although they are rarely encountered.

According to RFC5321 (and its errata), valid e-mail adresses can be up to 254 characters long, so SuperTuxKart should be prepared to handle such addresses.

Sources:
* https://tools.ietf.org/html/rfc5321#section-4.5.3.1
* http://www.rfc-editor.org/errata_search.php?rfc=3696 (refer to errata ID 1690)

Wikipedia's informal description:
* https://en.wikipedia.org/wiki/Email_address#Syntax

Also, is there any justification for the 4 character limit? I am not sure if such addresses are even possible, but if you can show me the shortest length of any possible e-mail adress, I am willing to accept it as mandatory lower bound.

**Comment by nado** [comment]
Well, in an intranet, a 4 characters address would be valid (even 3 : a@a), i dont really know what we should expect from users and/or future tld (a@x.y might be possible in a near future).
Maybe should we increase to a 5 characters address then ?

**Comment by Wuzzy2** [comment]
I suggest to drop the minimal limit entirely if you are not sure which is the shortest possible e-mail address. But when you are sure, about that and can point me to documents and stuff, then I am OK with enforcing the “minimal limit”.

**Comment by nado** [comment]
Well… A recipient might ben only « a », since you can send mail on the same host to another user. If you use an address with a « @ », then it is 3 : « x@y » on local domain, and if you are on internet, then you have « x@y.z ».
I dont know if there is a 1 letter tld yet, but one might appear one day since lots of new ones have been released these past few years.
