### ISSUE TITLE
Debian Jessie build fails nvidia libGl libGLEW not found

### ISSUE THREAD

**Issue by wayward4now** [supertuxkart/stk-code#2165]
Used both Debian supplied nvidia driver and the nvidia run style install. 
------------------------------------------------------------------------------
ric@iam:~/Downloads/supertuxkart-0.9/cmake_build/bin$ ./supertuxkart 
[verbose  ] main: Error messages and other text output will be logged to /home/ric/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: '../../data/'
[info   ] [FileManager]: User directory is '/home/ric/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/ric/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/ric/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/ric/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../../data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../../data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.utf8'.
[verbose  ] translation: Language 'English (United States)'.
Adding language fallback en
Irrlicht Engine version 1.8.0
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64
[warn   ] irr_driver: The window size specified in user config is larger than your screen!
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadValue (integer parameter out of range for operation)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_ConfigureWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_MapWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_ChangeProperty

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadDrawable

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not make context current.

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_GetGeometry

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_GetProperty

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreatePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreatePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateGC

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_PolyFillRectangle

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable (invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_PolyFillRectangle

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateCursor

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadGC (invalid GC parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreeGC

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: OpenGL driver version is not 1.2 or better.

[warn   ] [IrrDriver Temp Logger]: Level 2: Warning: OpenGL device only has one texture unit. Disabling multitexturing.

[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: (null)
[info   ] IrrDriver: OpenGL renderer: (null)
[info   ] IrrDriver: OpenGL version string: (null)
[fatal  ] GLEW: Glew initialisation failed with error Missing GL version
ric@iam:~/Downloads/supertuxkart-0.9/cmake_build/bin$

**Comment by wayward4now** [comment]
The binary failed in similar fashion first. So, I tried the src file. That build gave me these errors. Please ask for any input you need.

**Comment by Flakebi** [comment]
According to the output of SuperTuxKart, your video card only supports OpenGL 2.1 but stk needs at least 3.1, lower versions are unsupported.
If you think that your video card supports OpenGL 3.1 or better, please tell us your model. :-)

**Comment by deveee** [comment]
According to the output of STK, your video card does not support anything :P OpenGL version 2.1 is used by default, when we don't get any information about it from drivers. You also don't get information about drivers version, etc...

Try to run
```glxinfo | grep Open```
you should get something like:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 635M/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 340.76
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.4.0 NVIDIA 340.76
```

If you don't get something similar, then you don't have the drivers properly installed.

**Comment by wayward4now** [comment]
On 05/02/2015 05:25 AM, Seebi wrote:
> According to the output of SuperTuxKart, your video card only supports
> OpenGL 2.1 but stk needs at least 3.1, lower versions are unsupported.
> If you think that your video card supports OpenGL 3.1 or better, please
> tell us your model. :-)

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 520/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 346.59
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg 
compiler

Thanks! Ric
-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by deveee** [comment]
Do you have something specific in your system? For example non-typical window manager, resolution, multiple screens, modified xorg.conf ... It looks like we don't get information about screen resolution, and window can't be created at all:
```
[warn ] irr_driver: The window size specified in user config is larger than your screen!
[warn ] [IrrDriver Temp Logger]: Level 2: X Error: BadValue (integer parameter out of range for operation)

[warn ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateWindow

[warn ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)
```
Do you have this problem also with STK 0.8.1?

Also make sure that you don't have negative values for window width and height remembered in config.xml for some reason. Ideally try to remove ~/.config/supertuxkart directory.

**Comment by wayward4now** [comment]
On 05/03/2015 03:20 AM, Deve wrote:
> Do you have something specific in your system? For example non-typical
> window manager, resolution, multiple screens, modified xorg.conf ... It
> looks like we don't get information about screen resolution, and window
> can't be created at all:
>
> |[warn ] irr_driver: The window size specified in user config is larger than your screen!
> [warn ] [IrrDriver Temp Logger]: Level 2: X Error: BadValue (integer parameter out of range for operation)
>
> [warn ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateWindow
>
> [warn ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid Window parameter)
> |
>
> Do you have this problem also with STK 0.8.1?

No, not at all. I run quite a few openGL programs.

--------------------------------------------------
ric@iam:~/Downloads/supertuxkart-0.9/cmake_build/bin$ ./supertuxkart
[info   ] [FileManager]: Creating directory(ies) 
'/home/ric/.config/supertuxkart/0.8.2/'
[info   ] [FileManager]: Checking for: '/
[info   ] [FileManager]: Checking for: '/home/
[info   ] [FileManager]: Checking for: '/home/ric/
[info   ] [FileManager]: Checking for: '/home/ric/.config/
[info   ] [FileManager]: Checking for: '/home/ric/.config/supertuxkart/
[info   ] [FileManager]: Checking for: 
'/home/ric/.config/supertuxkart/0.8.2/
[info   ] FileManager: Creating directory 
'/home/ric/.config/supertuxkart/0.8.2/'.
[verbose  ] main: Error messages and other text output will be logged to 
/home/ric/.config/supertuxkart/0.8.2/stdout.log.
[error  ] UserConfig: Could not read user config file 
'/home/ric/.config/supertuxkart/0.8.2/config.xml'.
[info   ] [FileManager]: Data files will be fetched from: '../../data/'
[info   ] [FileManager]: User directory is 
'/home/ric/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 
'/home/ric/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in 
'/home/ric/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 
'/home/ric/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 
'../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 
'../../data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 
'../../data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US.utf8'.
[verbose  ] translation: Language 'English (United States)'.
Adding language fallback en
Irrlicht Engine version 1.8.0
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64
[warn   ] irr_driver: The window size specified in user config is larger 
than your screen!
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadValue (integer 
parameter out of range for operation)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid 
Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_ConfigureWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid 
Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_MapWindow

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid 
Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_ChangeProperty

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid 
Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadDrawable

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not make context current.

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_GetGeometry

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadWindow (invalid 
Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_GetProperty

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreatePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreatePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateGC

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_PolyFillRectangle

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadDrawable 
(invalid Pixmap or Window parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_PolyFillRectangle

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid 
Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_CreateCursor

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadGC (invalid GC 
parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreeGC

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid 
Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: BadPixmap (invalid 
Pixmap parameter)

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : X_FreePixmap

[warn   ] [IrrDriver Temp Logger]: Level 2: OpenGL driver version is not 
1.2 or better.

[warn   ] [IrrDriver Temp Logger]: Level 2: Warning: OpenGL device only 
has one texture unit. Disabling multitexturing.

[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: (null)
[info   ] IrrDriver: OpenGL renderer: (null)
[info   ] IrrDriver: OpenGL version string: (null)
[fatal  ] GLEW: Glew initialisation failed with error Missing GL vers
-----------------------------------------

By the way. Mariam Ruiz does not speak for the Debian Project. Some of 
us users are having a helluva time with her and her notion of moral 
content. If it were me, I'd tell her to go to hell. Checking here, she 
doesn't even maintain the package. 
https://packages.qa.debian.org/s/supertuxkart.html



-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by deveee** [comment]
Okay, I understend that your graphics drivers work. But we must find a way to reproduce this bug. If this is caused by for example window manager, then I could instal it on my machine and try to debug it. Otherwise it's really hard to say what's wrong because it works for most people.

At first please check:
- Does Supertuxkart 0.8.1 crash for you in the same way? (is this a regression or not?)
- Did you try to remove or rename ~/.config/supertuxkart directory? (maybe config.xml contains some invalid values). Or ideally attach your ~/.config/supertuxkart/0.8.2/config.xml file.

**Comment by hiker** [comment]
Hmm, your log file states:  Creating directory(ies) '/home/ric/.config/supertuxkart/0.8.2/' and other first-time running messages (so it was a clean start), but still the message that "The window size specified in user config is larger than your screen!", which means we could not create an opengl context with any settings (STK tries a couple of different settings). 

One other option to would be to try a vanilla irrlicht test program, just download the irrlicht package, and follow their instructions

**Comment by deveee** [comment]
I didn't notice log in your last commit, sorry about it.

Possible situation is that xrandr is not available in system for some reason (or has problems with some devices configuration (?)). Then we read display size and irrlicht returns values width: 0, height: 0. And we use these values for window size without checking if it's larger than 0 or not...

I added some additional checks, maybe it will allow you to run it at least in windowed mode:
commit f019f8622c93e57c12c0763dba44416c580f85a7

**Comment by wayward4now** [comment]
On 05/04/2015 01:04 AM, Deve wrote:
> Okay, I understand that your graphics drivers work. But we must find a
> way to reproduce this bug. If this is caused by for example window
> manager, then I could instal it on my machine and try to debug it.
> Otherwise it's really hard to say what's wrong because it works for most
> people.
>
> At first please check:
>
>   * Does Supertuxkart 0.8.1 crash for you in the same way? (is this a
>     regression or not?)

The pure Debian maintained package works just fine. I love the barnyard 
track!

>   * Did you try to remove or rename ~/.config/supertuxkart directory?
>     (maybe config.xml contains some invalid values). Or ideally attach
>     your ~/.config/supertuxkart/0.8.2/config.xml file.
Yes, I did. I'll attach the file. Thanks!! I am running Debian Jessie, 
with all updates, and XFCE desktop. Everything is fully updated, but I 
am now running the latest nvidia driver straight from nvidia, since I 
had this fail with the Debian driver install for nVidia. They both have 
crapped out on me. .Should I delete the .config/supertuxcat directory 
again and re-run 9.0 and see if there is a config.xml file to send?? Ric

p/s strange the new .config/supertuxkart directory has a directory named 
0.8.2 in it, and checking that out it has another config.xml file. So, I 
copied it to config.0.8.2.xml so you don't get confused. I have attached 
that and the stdout.log from 8.8.9 ...no error noted there.

-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by wayward4now** [comment]
On 05/04/2015 01:27 AM, hiker wrote:

> Reply to this email directly or view it on GitHub
> <https://github.com/supertuxkart/stk-code/issues/2165#issuecomment-98590777>.
I just tried. It failed at:

In file included from COpenGLDriver.h:25:0,
                  from COpenGLDriver.cpp:5:
COpenGLExtensionHandler.h:1236:3: error: ‘PFNGLBLENDEQUATIONPROC’ does 
not name a type
    PFNGLBLENDEQUATIONPROC pGlBlendEquation;
    ^
COpenGLExtensionHandler.h: In member function ‘void 
irr::video::COpenGLExtensionHandler::extGlBlendEquation(GLenum)’:
COpenGLExtensionHandler.h:2566:6: error: ‘pGlBlendEquation’ was not 
declared in this scope
   if (pGlBlendEquation)
       ^
<builtin>: recipe for target 'COpenGLDriver.o' failed
make: *** [COpenGLDriver.o] Error 1
ric@iam:~/Downloads/irrlicht-1.8.1/source/Irrlicht$
--------------------------
note: they depend on xrandr for full screen. No machine that uses nvidia 
handles xrandr well. Mine sems to refuse. But, I do have f86vidmode-dev 
installed. Please note I can run High Fidelity just fine and that was a 
bitch to build! I had no issues with my video setup however. Have you 
all built using nvidia and the nvidia driver? To be fair, I will rip ou 
the nvidia driver I installed, from nvidia (the .run file) and 
re-install the Debian nvidia package again. Ric



-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by wayward4now** [comment]
On 05/04/2015 05:26 AM, Deve wrote:
> I didn't notice log in your last commit, sorry about it.
>
> Possible situation is that xrandr is not available in system for some
> reason (or has problems with some devices configuration (?)). Then we
> read display size and irrlicht returns values width: 0, height: 0. And
> we use these values for window size without checking if it's larger than
> 0 or not...
>
> I added some additional checks, maybe it will allow you to run it at
> least in windowed mode:
> commit f019f86
> <https://github.com/supertuxkart/stk-code/commit/f019f8622c93e57c12c0763dba44416c580f85a7>
>

WORKS! YES! You and the rest are DA MAN! Ric



-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by wayward4now** [comment]
Funny that I can run version 8 in full screen, but not version 9. Even the option for full screen is greyed out. Meanwhile I think I'll re-install the official debian nvidia packages again.

**Comment by deveee** [comment]
> In file included from COpenGLDriver.h:25:0,
>                   from COpenGLDriver.cpp:5:
> COpenGLExtensionHandler.h:1236:3: error: ‘PFNGLBLENDEQUATIONPROC’ does
> not name a type

You won't be able to compile irrlicht 1.8.1 on current linux systems without patching it. Just don't care about it. You checked that STK 0.8.1 works for you and this information is enough.

> Funny that I can run version 8 in full screen, but not version 9

It is possible that 0.8 version works for you and 0.9 doesn't work, because in current version we use xrandr for handling resolutions. Previous versions (and also irrlicht by default) use vidmode instead of xrandr.

> No machine that uses nvidia handles xrandr well.

I personally have nvidia optimus laptop and I don't have any issues with libxrandr using bumblebee or nvidia-prime. It's even necessary to use xrandr application to make nvidia-prime working. Some people use nvidia directly and noone reported anything similar.

I will prepare simple application which should say if xrandr extension is available in your system at all or if the problem is in other place during creating resolutions list. You can also check if ```xrandr``` command typed in terminal gives you sensible output.

Vidmode implementation in irrlicht is rather poor (issues with multiple monitors, also with restoring resolution in some cases), but maybe we could use it as a fallback.

**Comment by deveee** [comment]
Please, try this:
http://deve.koliber.pl/stk/xrandr-test.cpp
and attach the output here.

It should be compiled using command:
```g++ xrandr-test.cpp -o xrandr-test -lXrandr -lX11```

If there is something wrong with xrandr, then it should say something more.

**Comment by wayward4now** [comment]
On 05/05/2015 03:43 AM, Deve wrote:
>     In file included from COpenGLDriver.h:25:0,
>     from COpenGLDriver.cpp:5:
>     COpenGLExtensionHandler.h:1236:3: error: ‘PFNGLBLENDEQUATIONPROC’ does
>     not name a type
>
> You won't be able to compile irrlicht 1.8.1 on current linux systems
> without patching it. Just don't care about it. You checked that STK
> 0.8.1 works for you and this information is enough.
>
>     Funny that I can run version 8 in full screen, but not version 9
>
> It is possible that 0.8 version works for you and 0.9 doesn't work,
> because in current version we use xrandr for handling resolutions.
> Previous versions (and also irrlicht by default) use vidmode instead of
> xrandr.
>
>     No machine that uses nvidia handles xrandr well.
>
> I personally have nvidia optimus laptop and I don't have any issues with
> libxrandr using bumblebee or nvidia-prime. It's even necessary to use
> xrandr application to make nvidia-prime working. Some people use nvidia
> directly and noone reported anything similar.

OK, got xrandr working. It's primitive as hell, right now, lacking a 
really good gui conf tool. I disabled xaminera in order to futz with it. 
But going back to configuring stuff by hand, editing config files, etc, 
is not good for me. So, I am happy to just have it work in window mode 
for now. You guys did a great job!! Ric




-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by wayward4now** [comment]
On 05/05/2015 08:26 AM, Deve wrote:
> Please, try this:
> http://deve.koliber.pl/stk/xrandr-test.cpp
> and attach the output here.
>
> It should be compiled using command:
> |g++ xrandr-test.cpp -o xrandr-test -lXrandr -lX11|
>
> If there is something wrong with xrandr, then it should say something more.

No need, I got xrandr working by disabling xinerama. Then it looks like 
a bobsled ride to hell, on greased rails, to configure multiple 
monitors. The last time I had to do all of that editing by hand for X 
was when I installed Slackware from a stack of floppies, before RedHat 
came out. I install lxandr and it only showed one monitor. So, I am 
quite happy to have your windowed display. Thank you very much!! Ric



-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html

**Comment by deveee** [comment]
Main issue has been fixed - now STK starts when it doesn't have information about original screen resolution, so ticket can be closed.

We could use vidmode as a fallback for changing resolutions if xrandr was not found, but it's a separate task. I'm also not in favour of this idea because it would require additional work for good vidmode support.

Btw. Is this really an issue to configure multiple monitors in your system? I was always using simple script which was detecting my monitors configuration and was doing something like:
```xrandr --output LVDS1 --auto --output HDMI1 --auto --left-of LVDS1```
Also Gnome should remember your monitors configuration. I don't know what about XFCE because I didn't use it longer time.

**Comment by wayward4now** [comment]
On 05/08/2015 05:57 AM, Deve wrote:
> Main issue has been fixed - now STK starts when it doesn't have
> information about original screen resolution, so ticket can be closed.
>
> We could use vidmode as a fallback for changing resolutions if xrandr
> was not found, but it's a separate task. I'm also not in favour of this
> idea because it would require additional work for good vidmode support.
>
> Btw. Is this really an issue to configure multiple monitors in your
> system? I was always using simple script which was detecting my monitors
> configuration and was doing something like:
> |xrandr --output LVDS1 --auto --output HDMI1 --auto --left-of LVDS1|
> Also Gnome should remember your monitors configuration. I don't know
> what about XFCE because I didn't use it longer time.


Oh heck, we're back to where it won't run, even just in windowed mode. 
Same error again.
[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: (null)
[info   ] IrrDriver: OpenGL renderer: (null)
[info   ] IrrDriver: OpenGL version string: (null)
[fatal  ] GLEW: Glew initialisation failed with error Missing GL version
ric@iam:~/Downloads/supertuxkart-0.9-linux$

The patched version worked a charm. Someone else is noting the same 
problem in the Debian list. Ric



-- 
My father, Victor Moore (Vic) used to say:
"There are two Great Sins in the world...
..the Sin of Ignorance, and the Sin of Stupidity.
Only the former may be overcome." R.I.P. Dad.
http://linuxcounter.net/user/44256.html
