### ISSUE TITLE
On-track arrows face in wrong direction when driving in reverse

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2167]
For some tracks, there are arrows showing the direction of the track (i.e. on signs or on the floor). But they only point into the correct direction if you drive forwards. If you drive the track in reverse mode, the arrows point into the wrong direction.

Affected tracks:

Major (well-visibly arrows):
* XR591
* Hacienda
* Nessie's Pond
* Fort Magma
* Snow Peaks
* Subsea

Minor (only subtle effects):
* STK Enterprise (the track hides this pretty well already)
* Shiny Suburbs (rolling direction of “turbo conveyor belts”)

A bugfix would mean that all on-track arrows are flipped and all animations go into the other direction when driving in reverse mode.

I know this is probably not trivial to fix but this is one of the minor things which irritate me in STK, so I posted it anyways. ;-)

STK version: 0.9

**Comment by hiker** [comment]
Added support for this to stk in 340dec3, and added two examples in r16360 of the assets.

To do: add support for this in the exporter (syntax: mirror-axis="U"  or 'V"), and update the blend of the tracks. Assigning to auria to update the exporter.

**Comment by auriamg** [comment]
Updated exporter committed

**Comment by hiker** [comment]
Assigning to samuncle to properly update the .blend files for the tracks listed here.

**Comment by hiker** [comment]
No release blocker.

**Comment by auriamg** [comment]
XR591, Hacienda, Fort Magma and Snow Peaks done.
I couldn't find any arrows in Nessie's Pond.
Subsea is no longer part of STK

I think this can be closed!

**Comment by Wuzzy2** [comment]
The arrows on Nessie's Pond are the turbo arrows at the pond near the end of the track.

**Comment by auriamg** [comment]
Nessie's pond done too
