### ISSUE TITLE
In-game help still features anchor as “weapon”

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2173]
The in-game help is slightly outdated.
It still shows anchor as a “weapon” and claims that it slows down the first kart. This is not true since ages anymore. The anchor is now only a banana penalty.

STK version: 0.9

**Comment by nado** [comment]
What would be the best, simply remove the Anchor from the help ? Or add a « States » tab ?

**Comment by Wuzzy2** [comment]
Clearly the latter case. And/or a “malus” page as well (for possible banana penalties, but this might be redundant).

**Comment by nado** [comment]
Malus feels better.

**Comment by auriamg** [comment]
Thanks, fixed. Now I agree that the help menu could use with more improvements, though I guess a separate task could created for that (that's not assigned to 0.9.1 milestone, and I guess some discussion should take place to decide what to do)
