### ISSUE TITLE
Better non-advanced pipeline graphics

### ISSUE THREAD

**Issue by HoboHacker** [supertuxkart/stk-code#2175]
The game's graphics without the advanced pipeline are just horrible. There isn't any lighting at all, and everything is dull and gray. In 0.8.1, there was SOME lighting. Could the non advanced pipeline look like the old graphics?

**Comment by auriamg** [comment]
While we would indeed like to have better fallbacks, the lowest graphical setting really is a last resort, and we hope that more and more people will be able to play at higher levels - both as people replace old hardware with newer/better one, drivers get bugfixes, and also as we continue optimizing of course.

If someone wants to work on that though, efforts are of course welcome

**Comment by HoboHacker** [comment]
Oh, sorry to

**Comment by auriamg** [comment]
Not sure if this was intended as sarcasm, but view it this way : we are few developers and we do what we can with out limited time. If someone wants to help us improve support for older/less powerful system we would gladly accept the help. Meanwhile we just aren't able to support so many systems

**Comment by HoboHacker** [comment]
Sorry if I appeared to be sarcastic, it's just that this sounds much more complicated than what I had thought.
