### ISSUE TITLE
Odd thunderbird behavior

### ISSUE THREAD

**Issue by HoboHacker** [supertuxkart/stk-code#2178]
When a track loads, if you pause the game right when it is finished loading, then unpause, Thunderbird will appear instantly instead of being delayed. Also, I think I may have encountered this issue before at random, though I'm not completely sure.

**Comment by auriamg** [comment]
Perhaps the timer controlling thunderbird is not stopped when the game pauses?

**Comment by auriamg** [comment]
I am unable to reproduce, this has probably been fixed since then. Please reopen if you can still reproduce
