### ISSUE TITLE
Track Making: Fog doesn't work on battlemaps

### ISSUE THREAD

**Issue by CreativeForge** [supertuxkart/stk-code#2179]
The fog parameter in scenes.xml is ignored on battlemaps but works fine on standart racetracks.

**Comment by stkAnon** [comment]
From my experience making my Temple arena, I can say that this does happen at least *sometimes*. 
Strangely enough though, it felt like fog had a higher chance of working immediately after I updated either my STK build or the track files.

vlj did also [mention](http://forum.freegamedev.net/viewtopic.php?f=18&t=5771&sid=3e01755400ac819f5b2f6685fe244539&start=25#p62430) fixing volumetric lighting.

**Comment by auriamg** [comment]
Thanks for the report, should now be fixed
