### ISSUE TITLE
Bug all maps, just skybox

### ISSUE THREAD

**Issue by born2gamingFR** [supertuxkart/stk-code#2180]
Salut,

J'ai parlé avec Sam IRL et il m'a dit de reporter mon erreur ici.
Donc comme sur ces images, il n'y a rien dans toutes les maps sauf la skybox, le hud et les effets de poussière du kart. (version 0.9 du jeu)
![supertuxkart 2015-05-06 20-20-01-94](https://cloud.githubusercontent.com/assets/10000043/7500386/98fea2cc-f42d-11e4-8d28-376ebff11cb3.png)
![supertuxkart 2015-05-06 20-20-06-77](https://cloud.githubusercontent.com/assets/10000043/7500385/98faaaf0-f42d-11e4-8d37-639d6b183dd3.png)
![supertuxkart 2015-05-06 20-20-09-96](https://cloud.githubusercontent.com/assets/10000043/7500387/9907a3d6-f42d-11e4-8087-751919903fb3.png)

Ma config (tous les drivers son à jour) :
Windows 8.1 Professionnel 64-bit
Processor: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 CPUs), ~3.4GHz
Memory: 8192MB RAM
DirectX Version: DirectX 11
NVIDIA GeForce GTX 560
Display Memory: 4042 MB
Dedicated Memory: 1226 MB
Shared Memory: 2815 MB
NVIDIA GeForce GTX 650
Display Memory: 4037 MB
Dedicated Memory: 965 MB
Shared Memory: 3072 MB

A+

**Comment by auriamg** [comment]
Bonjour,

malheureusement ce problème est mystérieux :( J'ai une nvidia GTX 680 sur
Windows 7 (donc un système quand même très semblable) sur lequel je ne
reproduis pas le problème. Est-ce que essayer d'autres niveaux graphiques
dans les options change quoi que ce soit?

-- Auria

2015-05-06 14:34 GMT-04:00 born2gamingFR <notifications@github.com>:

**Comment by born2gamingFR** [comment]
Oui,

j'ai essayé le niveau graphique 1 et 5 mais ça ne change absolument rien, Sam m'a parlé d'un fichier xml je crois avec une liste de carte graphique, peut-être que mes cartes graphique ne sont pas répertorier?

a+

**Comment by auriamg** [comment]
Hello,

le fichier XML en question sert simplement à auto-détecter les bons
réglages par défaut, en modifiant à la main les réglages graphiques on
obtient le même résultat. Peut-être essayer un niveau au centre, en 1 et 5?
Sinon j'ai bien peur que sans qu'on ait un dev capable de reproduire le
problème ça va être très difficile de déterminer le problème :S Je crois
qu'il n'y avait rien dans les logs? Peut-être si ce n'est pas déjà fait
créer un ticket sur github pour traquer le problème de manière un peu plus
organisée que par mail

-- Auria


2015-05-07 4:21 GMT-04:00 born2gamingFR <notifications@github.com>:

**Comment by born2gamingFR** [comment]
Salut,

J'ai essayé tous les niveaux graphique ça change rien, j'ai aussi essayé de lancer le jeu depuis la console et j'ai aussi donné tous les droits au programme (sous windows ça s'appelle : Grant Admin Full Control), mais malheureusement ça change rien...
Après je sais pas si c'est un indice, dans le menu solo, normalement on voit les karts quand on choisit un personnage, mais là ils n'apparaissent pas.
Et dans le stk editor par contre je vois tous les objets,...

Euh si non, les tickets c'est où sur votre github, je croyais que s'en était un ^^.

a+

**Comment by auriamg** [comment]
Oublie ma mention sur les tickets, j'ai répondu par email sans remarquer que c'était déjà sur github!

**Comment by auriamg** [comment]
Bonne nouvelle, une autre personne ayant le même problème que suite à une mise à jour récente du driver nvidia, le problème s'est réglé. Serait-il possible de mettre à jour le driver et de réeassayer?

**Comment by hiker** [comment]
@auriamg Should this be closed due to missing feedback?

**Comment by auriamg** [comment]
Yes, indeed, we believe this is fixed by latest nvidia drivers. Please reopen if issue still exists after updating drivers
