### ISSUE TITLE
Bomb problem

### ISSUE THREAD

**Issue by HoboHacker** [supertuxkart/stk-code#2183]
When you get a bomb from a banana, if the game is paused and unpaused while it is attached, the rotating hand will twitch.

**Comment by hiker** [comment]
This appears to be unrelated to pausing, I see the same effect without pausing.

**Comment by hiker** [comment]
Reason was that we manually set the frame to show, but irrlicht adds 'dt' when rendering (i.e. computing the next animation state). So if dt is big in one frame, it's added twice (once when stk computes the next frame, then again by irrlicht). But if the next dt is small, the overall next frame shown can be before the previous frame, resulting in the hand moving backwards. Example: assume time is 0, and dt=1. So stk requests frame 1, butr irrlicht adds another second, so frame from t=2 is shown. Next frame is at t=1, but if dt is then only 1/10, stk requests frame 1.1, to which irrlicht adds another 0.1, so showing the animation at t=1.2 - which is before the previous frame, so the arrow moves backwards.

Setting the animation speed to 0 means that irrlicht does not add its dt again, and a smooth animation.
