### ISSUE TITLE
Leader wins Follow The Leader

### ISSUE THREAD

**Issue by pelzflorian** [supertuxkart/stk-code#2184]
In Follow the Leader, when overtaking the leader after all opponents have been eliminated, the list at the end shows the leader's name at the top instead of the real winner.

1. play follow the leader
2. wait until all opponents have been eliminated
3. overtake the leader
4. look who is at the top of the list

The leader's name is in white, not red, so probably the game does not think that the leader really has won. Apparently, Supertuxkart displays the second cart at the top of the list, which is not necessarily the same as the winning cart.

**Comment by deveee** [comment]
We have pull request which should fix it:
https://github.com/supertuxkart/stk-code/pull/2058

but nobody looked at this yet...

**Comment by hiker** [comment]
That was fixed a while ago.

Thanks for the report!
   Joerg
