### ISSUE TITLE
turn left + any key combination

### ISSUE THREAD

**Issue by predkambrij** [supertuxkart/stk-code#2185]
Hi.

I noticed that I cannot use nitro (n key) when turning left, but I can when I'm turning right. If I press up + nitro + left then it will go straight with nitro. If I press up + left + nitro then it will go left without nitro. If I press up + right + nitro it works both (goes right with nitro). The same behaviour is when firing the stuff (space key). I noticed similar behaviour if I'm not wrong in Tony Hawk's Pro Skater 2 (years ago).

The version of the game is from Linux Mint 17.1 (0.8.1-2), Irrlicht Engine version 1.8.0.

Thanks

**Comment by baptx** [comment]
Hello, I've got the same problem when I tried the game 2 weeks ago on Xubuntu 14.04 LTS with SuperTuxKart 0.8.1-2.

**Comment by Flakebi** [comment]
Hi,
that is caused by the communication between keyboards and computers, there is a limited number of keys that can be pressed at the same time, and some special combinations don't work.
You should be able to fix that issue by remapping your movement keys (e.g. to WASD).

**Comment by auriamg** [comment]
Hi, this is not a supertuxkart bug but actually a physical limitation of your keyboards. You can find more information here : http://www.sjbaker.org/wiki/index.php?title=Keyboards_Are_Evil

You can work around by using different keys, using a gamepad, or using a gaming keyboard

**Comment by predkambrij** [comment]
Hi. Thank you for the explanation. For me works perfectly key mapping o,k,l and :/; instead of arrows with combination of other keys (space, n and v).

**Comment by baptx** [comment]
Interesting, thanks for the link! Maybe the game should change the default keys so users will not be confused that they can't turn left when using nitro.

**Comment by auriamg** [comment]
Actually, the current defaults have been chosen to minimize the conflicts - but the issue is that not all keyboards are the same so it's pretty hard (impossible?) to find a default that will work everywhere

**Comment by predkambrij** [comment]
Perhaps a little note with that link would help. At least I wouldn't ask if I would know that physical limitations exist.

**Comment by auriamg** [comment]
I have created a FAQ entry : http://supertuxkart.sourceforge.net/FAQ#Some_keyboard_keys_do_not_work_when_pressed_simultaneously

Not sure if it's possible/desirable to explain that in-game though

**Comment by predkambrij** [comment]
Most people would probably see the note if it would be in options -> controls -> keyboard and/or in tutorial drive when the instruction says for skid, using nitro and/or firing the weapons. That probably wouldn't overwhelm the user as he/she is setting up.

**Comment by ChemBro** [comment]
I'd like to point out, that I have the same issue, but I don't think, it is a hardware limitation, as I have no problem with, for example the indie game "Distance". In Distance, I have to constantly press up for gas, constantly press shift for nitro and of course have to steer. Also in Distance, you have more options to control the car. More options, more key presses, but there is never a problem with steering the car.

So I have no problem with steering the car in Distance, even though I have to press more keys simultaneously, but in SuperTuxKart it is less and I can't steer the kart anymore. Is there a way to figure out, why that is?

**Comment by nado** [comment]
I have this problem on a usb keyboard but none with a PS/2 keyboard connected at the same time.

**Comment by Flakebi** [comment]
Most keyboards are constructed awfully in this respect. As described previously, for many people it's possible to go to the `right` when pressing the `up arrow` and `n` but not to the `left`.

You can change the driving keys from the arrows to letters which will maybe work better. Also I think that using modifier keys (shift/control) should not be a huge problem.

Could you maybe try out to press the *exactly same* key combination from SuperTuxKart in Distance or vice versa around and see if that works? (You said it uses `shift` for nitro and not `n` like stk)

**Comment by ChemBro** [comment]
You are right, using N in Distance gives me the problem. If I use an other key like V for example, it works again. Same goes for SuperTuxKart.
