### ISSUE TITLE
Names of keyboard keys are not translatable

### ISSUE THREAD

**Issue by huftis** [supertuxkart/stk-code#2192]
The names of the keyboard keys (e.g., ‘left’, ‘right’, ‘right control’, ‘page up’, ‘backspace’) are not translatable, and are always shown in English in the UI.

They are used in the keyboard settings screen, but also in the tutorial mode, in strings like ‘Accelerate with <%s> and steer with <%s> and <%s>’ (the actual text here is translatable, but the <%s> names are always shown in English).

When making them translatable, I think it’s better to make them all Title Case (e.g., ‘Page Up’, not ‘page up’) at the same time. IMHO, the lowercase naming looks strange, and it’s not consistent with the names for mouse/gamepad buttons (which *are* translatable, and which starts with a capital letter).

**Comment by hiker** [comment]
Fixed in 2a56cc6. I did not offer the function keys F1-F22 for translation, I assume that this is not necessary.
