### ISSUE TITLE
Gnu gets stuck in chewing gum

### ISSUE THREAD

**Issue by huftis** [supertuxkart/stk-code#2193]
Gnu has a magic carpet that hovers some distance off the ground. Still he gets stuck in chewing gum puddles. This does not make sense! He should be able to fly over them without any trouble.

**Comment by MarkkusCraft123** [comment]
This is not a problem, just the way the game works, but this could bring a change to the gum model, perhaps making it taller.

**Comment by auriamg** [comment]
Gums affect every kart, otherwise gnu would have an unfair advantage. I agree it can look a little weird but we certainly don't want to give some karts advantages that may make the game unbalanced, just because graphically it looks slightly cheesy.
