### ISSUE TITLE
Public relation improvement with stk domains

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2197]
Hi everyone (this is following a discussion on IRC).

We pay currently for a lot of domain like stkblog.net which redirect to the blogspot URL, and the same thing for supertuxkart.net -> supertuxkart.sourceforge.net.

Since we already pay for them, I suggest to use them. It should be reversed. If you go to supertuxkart.net you should stay to supertuxkart.net and if you go to supertuxkart.sourceforge.net you should be redirected to supertuxkart.net.

It might seems a little detail but since we pay for those domain let's use them.

I have no access to do it but apparently it's possible to do with sourceforge. Here is some documentation I found.

http://sourceforge.net/p/forge/documentation/Custom%20VHOSTs/

Also as hiker pointed out on IRC
<hiker> samuncle: not sure about the vhost thing, we would need to check with arthur, since we also use some sub-domains to access other addresses

**Comment by Arthur-D** [comment]
Already the case for a while, closing.
