### ISSUE TITLE
Cannot run the program at all

### ISSUE THREAD

**Issue by Karelsforums** [supertuxkart/stk-code#2200]
Hello,
I have downloaded STK 0.9 for linux tar.gz file (supertuxkart-0.9-linux.tar.gz). Unpacked to user folder. When trying to run game using run_game.sh I can only see blinking screens for a second and then nothing. I'm trying on Wheezy 7.8 64 bit, ATI Grapihc card, ATI Catalyst Drive installed.
I presume, you'll need more detailed info and application log file if created on application fall. Please let me know how.
Thanks for the application and help. My children loves the karts.
Best regards,

Karel

**Comment by Flakebi** [comment]
Hi,
you should see some output when you start SuperTuxKart from a terminal. Also this output is logged to `.config/supertuxkart/0.8.2/stdout.log`. It would be nice if you could give us the contents of this log.

Nice to hear that your children like the game. :-)

**Comment by Karelsforums** [comment]
Hello, below you'll find the message when running from terminal and lower content of stdout.log file.


Running 64-bit version...
[info   ] [FileManager]: Creating directory(ies) '/root/.config/supertuxkart/0.8.2/'
[info   ] [FileManager]: Checking for: '/
[info   ] [FileManager]: Checking for: '/root/
[info   ] [FileManager]: Checking for: '/root/.config/
[info   ] [FileManager]: Checking for: '/root/.config/supertuxkart/
[info   ] FileManager: Creating directory '/root/.config/supertuxkart/'.
[info   ] [FileManager]: Checking for: '/root/.config/supertuxkart/0.8.2/
[info   ] FileManager: Creating directory '/root/.config/supertuxkart/0.8.2/'.
[info   ] FileManager: Creating directory '/root/.local/share/supertuxkart'.
[info   ] FileManager: Creating directory '/root/.local/share/supertuxkart/addons/'.
[info   ] FileManager: Creating directory '/root/.local/share/supertuxkart/addons/icons/'.
[info   ] FileManager: Creating directory '/root/.local/share/supertuxkart/addons/tmp/'.
[info   ] FileManager: Creating directory '/root/.cache/supertuxkart'.
[info   ] FileManager: Creating directory '/root/.cache/supertuxkart/screenshots/'.
[info   ] FileManager: Creating directory '/root/.cache/supertuxkart/cached-textures/'.
[info   ] FileManager: Creating directory '/root/.local/share/supertuxkart/grandprix/'.
[verbose  ] main: Error messages and other text output will be logged to /root/.config/supertuxkart/0.8.2/stdout.log.
[error  ] UserConfig: Could not read user config file '/root/.config/supertuxkart/0.8.2/config.xml'.
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is '/root/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/root/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/root/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/root/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'cs_CZ.UTF-8'.
[verbose  ] translation: Language 'Czech (Czech Republic)'.
Adding language fallback cs
Irrlicht Engine version 1.8.0
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64
[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[fatal  ] irr_driver: Couldn't initialise irrlicht device. Quitting.



And content of stdout.log

[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is '/home/uzivatel/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/uzivatel/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/uzivatel/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/uzivatel/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'cs_CZ.UTF-8'.
[verbose  ] translation: Language 'Czech (Czech Republic)'.
[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[warn   ] [IrrDriver Temp Logger]: Level 2: Could not create GLX rendering context.

[fatal  ] irr_driver: Couldn't initialise irrlicht device. Quitting.

**Comment by deveee** [comment]
Thanks for the log file. Could you write also what does ```glxinfo | grep Open``` say?

**Comment by nado** [comment]
Could it be related to the fact it seems run by root ?

**Comment by deveee** [comment]
This is the most probably problem in system configuration, because STK can't create glx context at all. But glxinfo should confirm it.

It may be caused for example by not installed glx-alternatives package. I also remember that someone had a problem with catalyst drivers that he had acceleration on his main account, but he didn't have it on second account (not sure what was the reason). If opengl doesn't work for you (can be tested by glxinfo and glxgears), then you can look into /var/log/Xorg.0.log file, maybe it shows some errors.

If opengl works for you, then we will try to find the reason on our side.

**Comment by hiker** [comment]
No more info, closing.
