### ISSUE TITLE
Stuck upside down on wooden bridge in Cocoa Temple.

### ISSUE THREAD

**Issue by gnutechs** [supertuxkart/stk-code#2201]
![stkupsidedown](https://cloud.githubusercontent.com/assets/12518502/7713315/fdc026e2-fe44-11e4-9133-51835e92d1eb.png)

Somehow I got under it. I think I was driving on the right side of the bridge and fell through, then my tires got stuck underneath because there's a hole with no invisible wall between the wooden beams.

**Comment by auriamg** [comment]
Actually this is probably the same issue as #2204, only upside-down this time
