### ISSUE TITLE
Driving on water in Cocoa Temple.

### ISSUE THREAD

**Issue by gnutechs** [supertuxkart/stk-code#2202]
![_2015-05-19_16-31-29](https://cloud.githubusercontent.com/assets/12518502/7713371/54785c16-fe45-11e4-95ad-7b05fee5520e.png)

Right after the big zipper jump there's water you can drive on beneath.

**Comment by Benau** [comment]
Fixed in latest asset

**Comment by SuicSoft** [comment]
@Benau Which commit ?  (I think assets are on SVN , they should move to GitHub)

**Comment by LoadingPleaseWait** [comment]
I believe @Benau fixed it in https://sourceforge.net/p/supertuxkart/code/16761/.
