### ISSUE TITLE
Able to go under level in some places of Cocoa Temple.

### ISSUE THREAD

**Issue by gnutechs** [supertuxkart/stk-code#2203]
![2015-05-19-192255_1024x768_scrot](https://cloud.githubusercontent.com/assets/12518502/7716144/dacad700-fe5c-11e4-8920-12dbdb10fc20.png)
![_2015-05-19_17-58-21](https://cloud.githubusercontent.com/assets/12518502/7716152/e3be52d8-fe5c-11e4-9ecf-1b2f10d9ffb2.png)
![2015-05-19-192425_1024x768_scrot](https://cloud.githubusercontent.com/assets/12518502/7716155/ecce6fca-fe5c-11e4-90ce-88d644bf740f.png)
![_2015-05-19_17-34-18](https://cloud.githubusercontent.com/assets/12518502/7716162/fa101706-fe5c-11e4-848d-a5b49dd6a028.png)
![_2015-05-19_18-03-01](https://cloud.githubusercontent.com/assets/12518502/7716166/02695c78-fe5d-11e4-8898-cf4f8e6f61c8.png)
![_2015-05-19_18-06-23](https://cloud.githubusercontent.com/assets/12518502/7716179/1b2c7d08-fe5d-11e4-9536-26ad05f5dcef.png)

**Comment by Coeur-Noir** [comment]
Same here…

**Comment by Benau** [comment]
Fixed in latest asset
