### ISSUE TITLE
Inadvertant sticky walls in Cocoa Temple.

### ISSUE THREAD

**Issue by gnutechs** [supertuxkart/stk-code#2204]
I think almost every flat wall you can stick on.
![_2015-05-19_18-03-01](https://cloud.githubusercontent.com/assets/12518502/7715414/4e9314de-fe55-11e4-82c0-c9b94b3c810d.png)
![_2015-05-19_18-06-23](https://cloud.githubusercontent.com/assets/12518502/7715611/463d91c2-fe57-11e4-8d27-f185aa44e534.png)
![_2015-05-19_18-53-52](https://cloud.githubusercontent.com/assets/12518502/7715729/86bca908-fe58-11e4-89d2-dee1d657efa2.png)
![_2015-05-19_17-59-26](https://cloud.githubusercontent.com/assets/12518502/7715418/53cb0272-fe55-11e4-89c5-c41721cb173f.png)
![_2015-05-19_17-55-21](https://cloud.githubusercontent.com/assets/12518502/7715420/5a2ccbfa-fe55-11e4-8718-ed531fd72d3d.png)
![_2015-05-19_18-43-57](https://cloud.githubusercontent.com/assets/12518502/7715596/1738293c-fe57-11e4-8d3a-b4233c697a8d.png)
![_2015-05-19_17-50-09](https://cloud.githubusercontent.com/assets/12518502/7715607/38c0940e-fe57-11e4-935a-5241b8921f2f.png)

**Comment by auriamg** [comment]
Discussion with samuncle revealed this is caused because magneticism is a property of textures, and not objects, so it's hard to accurately target what is magnetic and what isn't

**Comment by hiker** [comment]
@samuncle could you make a test track where a magnetic surface is exported as a separate mesh? If possible a small track to help me with loading/testing times.

**Comment by hiker** [comment]
Still don't have a test case, no release blocker, so postpone till 0.9.3

**Comment by Benau** [comment]
Actually I think "stktex_generic_concreteA.png" doesn't need to set has-gravity="Y" in materials.xml, cocoa temple only use "stktex_generic_cobbleStoneA.png" for the wall driving section

**Comment by MTres19** [comment]
I think this would be better solved with a way for tracks to override materials set in materials.xml in stk-assets.

**Comment by Benau** [comment]
Here is in latest materials.xml:
```
    <!-- Global sticking textures -->
    <material name="stkflag_orangeBooster_a.png" shader="alphatest" disable-z-write="Y" has-gravity="Y"/>
    <material name="stkflag_blueBooster_a.png" shader="alphatest" disable-z-write="Y" has-gravity="Y"/>
    <material name="stkflag_redBooster_a.png" shader="alphatest" disable-z-write="Y" has-gravity="Y"/>
    <material name="stk_generic_gridA.png" shader="alphatest" has-gravity="Y"/>
    <material name="stktex_generic_cobbleStoneA.png" has-gravity="Y" graphical-effect="normal_map" normal-map="stktex_generic_cobbleStoneA_nm.png"/>
    <material name="stk_generic_dirtRoad_a.png" has-gravity="Y" graphical-effect="normal_map" normal-map="stk_generic_dirtRoad_a_nm.png"/>
    <material name="stk_generic_sandRoad_a.png" has-gravity="Y"/>
    <!-- End of global sticking textures -->
```
Basically I remove some textures that are likely to be found in wall (like stktex_generic_concreteA.png)
. So to override locally, copy the desired textures to .blend folder and use "Replace Image in UV/Image editor with it, then you can configure it locally (Same technique has been done to las dunas arena / cornfield crossing)

**Comment by doutsh** [comment]
I had an issue that might be related - I almost fell of the bridge and got stuck on its side. 
Wasn't rescued and couldn't move anywhere, had to quit the race...

![stuck_on_bridge](https://user-images.githubusercontent.com/43576380/48305470-99ba0d00-e533-11e8-9c2a-8388158e8a1b.jpg)

**Comment by Alayan-stk-2** [comment]
This happens because the bridge has a "sticky gravity" texture, which also applies to the side and bottom. Definitely a bug, however. Open a new issue.

For your information, STK has a rescue button, which is useful to be rescued sooner when you fall off-track, and when the auto-rescue doesn't work.
