### ISSUE TITLE
Game does not start properly in Windows 7

### ISSUE THREAD

**Issue by Dovid-Levin** [supertuxkart/stk-code#2207]
Here is a picture of the opening screen:
![stkbug](https://cloud.githubusercontent.com/assets/12625268/7834146/354e090e-0475-11e5-821f-e697e6c613ed.png)

(The music does play.)

**Comment by auriamg** [comment]
Hi,

what is your GPU ? Are your drivers up to date? Could you post the contents of file stdout.log from directory %appdata%\supertuxkart\0.8.2 ? (you can paste that in the windows explorer path bar)

**Comment by hiker** [comment]
No feedback, closing since we don't have enough information.

**Comment by tobbi** [comment]
I'm getting the same thing on my Windows laptop. stdout.log: http://pastebin.com/mZEuRCwt
My drivers are up-to-date. 8.15.10.2900

In case this helps anything: Here is the system configuration as reported by Blender (which lists supported OpenGL extensions and such):
http://pastebin.com/FAPu5EAt

**Comment by hiker** [comment]
In the last case OpenGL is too old (2.1). And the non-shader implementation does not work good enough anymore. Basically, it's unsupported and known not to work - only question: should we properly abort in this case?
