### ISSUE TITLE
Last master crash when I try a race

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2214]
If I try to launch a race with the last master it crashes. Here is the log.

http://fpaste.org/231270/43405451/

**Comment by tobbi** [comment]
Crashes on OS X 10.10 as well!

**Comment by tobbi** [comment]
Culprit is likely 32edaa25fe6324cb63b5bf11b86997d5763b6ff7.

@auriamg Care to take a look?

**Comment by cap44** [comment]
Confirming crash on my end:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000c67ce4 in Scripting::ScriptEngine::compileLoadedScripts
(this=0x2a273210) at
/home/i5150pc/stk-bleeding/stk-code/src/scriptengine/script_engine.cpp:389
(gdb) bt
#0  0x0000000000c67ce4 in Scripting::ScriptEngine::compileLoadedScripts
(this=0x2a273210) at
/home/i5150pc/stk-bleeding/stk-code/src/scriptengine/script_engine.cpp:389
#1  0x0000000000be0bc0 in World::init (this=0x286e1f10) at
/home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:214
#2  0x0000000000beb49f in WorldWithRank::init (this=0x286e1f10) at
/home/i5150pc/stk-bleeding/stk-code/src/modes/world_with_rank.cpp:31
#3  0x0000000000be66df in LinearWorld::init (this=0x286e1f10) at
/home/i5150pc/stk-bleeding/stk-code/src/modes/linear_world.cpp:59
#4  0x0000000000946fc6 in RaceManager::startNextRace (this=0x494e800) at
/home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:493
#5  0x0000000000946634 in RaceManager::startNew (this=0x494e800,
from_overworld=false) at
/home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:406
#6  0x0000000000948204 in RaceManager::startSingleRace (this=0x494e800,
track_ident="stk_enterprise", num_laps=3, from_overworld=false) at
/home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:821
#7  0x0000000000d17e20 in TrackInfoScreen::onEnterPressedInternal
(this=0x2869a780) at
/home/i5150pc/stk-bleeding/stk-code/src/states_screens/track_info_screen.cpp:286
#8  0x0000000000d17ef2 in TrackInfoScreen::eventCallback
(this=0x2869a780, widget=0x25b078b0, name="buttons", playerID=0) at
/home/i5150pc/stk-bleeding/stk-code/src/states_screens/track_info_screen.cpp:298
#9  0x0000000000a3c37c in GUIEngine::EventHandler::sendEventToUser
(this=0x25df330, widget=0x25b078b0, name="buttons", playerID=0) at
/home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:528
#10 0x0000000000a3cca6 in GUIEngine::EventHandler::onWidgetActivated
(this=0x25df330, w=0x25b08640, playerID=0) at
/home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:568
#11 0x0000000000a3ba5e in GUIEngine::EventHandler::onGUIEvent
(this=0x25df330, event=...) at
/home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:613
#12 0x0000000000a3b45f in GUIEngine::EventHandler::OnEvent
(this=0x25df330, event=...) at
/home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:149
#13 0x0000000000f4810a in non-virtual thunk to
irr::gui::CGUIEnvironment::OnEvent(irr::SEvent const&) () at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:399
#14 0x0000000000faa49b in irr::gui::CGUIButton::OnEvent (this=<optimized
out>, event=...) at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:225
#15 0x0000000000faa513 in irr::gui::CGUIButton::OnEvent
(this=0x25a8fbb0, event=...) at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:215
#16 0x0000000000f4892c in irr::gui::CGUIEnvironment::postEventFromUser
(this=0x1a9f7e0, event=...) at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:570
#17 0x0000000000f0e4e2 in irr::CIrrDeviceStub::postEventFromUser
(this=0x1783210, event=...) at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:227
#18 0x0000000000f08581 in irr::CIrrDeviceLinux::run (this=0x1783210) at
/home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1277
#19 0x0000000000abea38 in IrrDriver::update (this=0x1782d00,
dt=0.0329999998) at
/home/i5150pc/stk-bleeding/stk-code/src/graphics/irr_driver.cpp:2086
#20 0x00000000009cd4f3 in MainLoop::run (this=0x49601e0) at
/home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:151
#21 0x00000000009d642d in main (argc=1, argv=0x7fffffffe068) at
/home/i5150pc/stk-bleeding/stk-code/src/main.cpp:1507

**Comment by tobbi** [comment]
Fixed with #2215. Please test it anyway, though.

**Comment by auriamg** [comment]
Thanks, should be fixed now. If there are more issues feel free to reopen
