### ISSUE TITLE
Kart selection screen : slow navigation between karts

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2216]
Quite a few people have reported that switching between kart s on the kart selection screen is slow, so I've started investiguating. It appears most of the time is spent uploading the mesh to the GPU, in method "PrepareDrawCalls", corresponding to profiler marker "Animations/Buffer upload". Not sure much can be done about that, but documenting my findings anyway so we don't lose that info

**Comment by hiker** [comment]
For me the slowness appears to be related to the line:
    // TODO: put this outside of the rendering loop
    irr_driver->generateDiffuseCoefficients();
Removing this lines doubles my fps in the kart selection screen (I have seen 8 to 12 fps with that function call, and 15 to 31 without that line - though I was using debug mode).

**Comment by Arthur-D** [comment]
I also experience slowness on my secondary machine with AMD Radeon HD 6750 graphics. Notably when entering the kart selection screen and hovering over another kart for the first time. I think the first thing, if not easily solvable, should be "worked around" by using the loading screen between. At the moment it just freezes in the main menu which made me question if it had crashed (not used to such long loading times on my main machine).

**Comment by hiker** [comment]
Some improvements were made (irr_driver->generateDiffuseCoefficients(); is not much of an issue anymore), but it could still be faster ;)

**Comment by Benau** [comment]
@Arthur-D still slowness now?

**Comment by Benau** [comment]
we can't reproduce since our latest changes
