### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by MarkkusCraft123** [supertuxkart/stk-code#2218]
I was compiling the project on Ubuntu 15.04 and I got this error.

[ 95%] Building CXX object CMakeFiles/supertuxkart.dir/src/scriptengine/script_physics.cpp.o
/home/markkus/STK/stk-code/src/scriptengine/script_physics.cpp: In function ‘void Scripting::Physics::registerScriptFunctions(asIScriptEngine*)’:
/home/markkus/STK/stk-code/src/scriptengine/script_physics.cpp:43:21: error: ‘class asIScriptEngine’ has no member named ‘SetDefaultNamespace’
             engine->SetDefaultNamespace("Physics");
                     ^
CMakeFiles/supertuxkart.dir/build.make:7391: recipe for target 'CMakeFiles/supertuxkart.dir/src/scriptengine/script_physics.cpp.o' failed
make[2]: *** [CMakeFiles/supertuxkart.dir/src/scriptengine/script_physics.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/markkus/STK/stk-code/src/scriptengine/script_gui.cpp: In function ‘void Scripting::GUI::registerScriptFunctions(asIScriptEngine*)’:
/home/markkus/STK/stk-code/src/scriptengine/script_gui.cpp:152:21: error: ‘class asIScriptEngine’ has no member named ‘SetDefaultNamespace’
             engine->SetDefaultNamespace("GUI");
                     ^
/home/markkus/STK/stk-code/src/scriptengine/script_gui.cpp: In function ‘void Scripting::GUI::registerScriptEnums(asIScriptEngine*)’:
/home/markkus/STK/stk-code/src/scriptengine/script_gui.cpp:164:21: error: ‘class asIScriptEngine’ has no member named ‘SetDefaultNamespace’
             engine->SetDefaultNamespace("GUI");
                     ^
CMakeFiles/supertuxkart.dir/build.make:7345: recipe for target 'CMakeFiles/supertuxkart.dir/src/scriptengine/script_gui.cpp.o' failed
make[2]: *** [CMakeFiles/supertuxkart.dir/src/scriptengine/script_gui.cpp.o] Error 1
/home/markkus/STK/stk-code/src/scriptengine/script_engine.cpp: In function ‘std::string Scripting::getScript(std::string)’:
/home/markkus/STK/stk-code/src/scriptengine/script_engine.cpp:109:18: warning: NULL used in arithmetic [-Wpointer-arith]
         if (c == NULL)
                  ^
/home/markkus/STK/stk-code/src/scriptengine/script_engine.cpp: In member function ‘void Scripting::ScriptEngine::runFunction(std::string, std::function<void(asIScriptContext*)>, std::function<void(asIScriptContext*)>)’:
/home/markkus/STK/stk-code/src/scriptengine/script_engine.cpp:282:69: error: invalid conversion from ‘int’ to ‘asIScriptFunction*’ [-fpermissive]
                 asIScriptFunction *func = ctx->GetExceptionFunction();
                                                                     ^
/home/markkus/STK/stk-code/src/scriptengine/script_engine.cpp:282:36: warning: unused variable ‘func’ [-Wunused-variable]
                 asIScriptFunction *func = ctx->GetExceptionFunction();
                                    ^
CMakeFiles/supertuxkart.dir/build.make:7368: recipe for target 'CMakeFiles/supertuxkart.dir/src/scriptengine/script_engine.cpp.o' failed
make[2]: *** [CMakeFiles/supertuxkart.dir/src/scriptengine/script_engine.cpp.o] Error 1
CMakeFiles/Makefile2:97: recipe for target 'CMakeFiles/supertuxkart.dir/all' failed
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by auriamg** [comment]
Maybe you are picking up system angelscript and it's the wrong version?

**Comment by auriamg** [comment]
Okay I have actually committed a change to the CMake build files, could you try getting the latest version and doing a clean build from scratch?

**Comment by MarkkusCraft123** [comment]
Okay, I'll try.

**Comment by MarkkusCraft123** [comment]
That fixed it! Thank you.
