### ISSUE TITLE
Change German translation for "Sarah the wizard"

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#2222]
Please translate the above string as "Sarah die Zauberin" instead of "Sarah die Hexe". When I hear Hexe I have an image of an old witch in my head. Zauberin however matches the elegance of the term "wizard".

Someone with a transifex account and access to the supertuxkart project please make that change. I don't want to get a member just for this small string fix.

**Comment by auriamg** [comment]
You could simply go on transifex and change it? Why create a ticket instead of directly fixing it :)

**Comment by tobbi** [comment]
Right, I forgot that I requested to be a member of the German team on Transifex and that my request was granted. Anyway, sorry for the bugspam.
