### ISSUE TITLE
Invisible items on certain maps

### ISSUE THREAD

**Issue by Lunruj** [supertuxkart/stk-code#2224]
I can't see any bonus items on Shifting Sands and nothing except a first pair of boxes on Cocoa Temple (and maybe there are problems on more, but most of the maps seems to be fine). It has happened to me that the items appeared on Cocoa Temple during the race, probably using the gifts into bananas bonus. Also it seems sometimes I can't see bubble gums on the track left by the bubble gum bonus.

I have Mageia 5, ati driver, graphic card ATI Mobility Radeon HD 4570. I get the warning that my OpenGL version appears to be too old.
STK 0.9

**Comment by hiker** [comment]
Could you post the content of stdout.log (see http://supertuxkart.sourceforge.net/FAQ#Where_does_STK_store_the_user_config_file.3F for the location of that file)

**Comment by Lunruj** [comment]
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/games/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/lunruj/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/lunruj/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/lunruj/.cache/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/lunruj/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/games/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/games/supertuxkart/data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/games/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/games/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/games/supertuxkart/data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/games/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/games/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/games/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/games/supertuxkart/data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/games/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/games/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/games/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/games/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/games/supertuxkart/data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en'.
[verbose  ] translation: Language 'English'.
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Gallium 0.4 on AMD RV710
[info   ] IrrDriver: OpenGL version string: 2.1 Mesa 10.5.7
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[warn   ] [IrrDriver Temp Logger]: Level 2: PNG warning: iCCP: known incorrect sRGB profile

[info   ] GUIEngine: scale: 0.512000
[warn   ] TrackManager: Track 'addon_coyote-canyon' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'addon_mystery-island' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'addon_secret-garden' is not supported by this binary, ignored. (Track is version 5, this executable supports from 6 to 6).
[info   ] GrandPrixManager: Loading Grand Prix files from /usr/share/games/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/lunruj/.local/share/supertuxkart/grandprix/
[warn   ] Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
[warn   ] Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
[warn   ] Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
[warn   ] Irrlicht: PNG warning: iCCP: profile 'ICC profile': 1000000h: invalid rendering intent
[warn   ] EventHandler: Error while loading kart 'Adiumy':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Amanda':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Amanda':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Amanda':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Amanda':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Amanda':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Emule':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: profile 'Photoshop ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Gavroche':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Hexley':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: profile 'Photoshop ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: profile 'Photoshop ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: profile 'Photoshop ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
[warn   ] EventHandler: Error while loading kart 'Konqi':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Tux':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Tux':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Tux':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[warn   ] EventHandler: Error while loading kart 'Tux':
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[info   ] ClientNetworkManager: Host initialized.
[info   ] ClientNetworkManager: Ready !
[warn   ] OpenGL: OpenGL version is too old!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[verbose  ] RaceManager: Nb of karts=5, ai:4 players:1

[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[warn   ] material: Track uses deprecated texture 'bumpy_surface.png'
[verbose  ] RaceManager: Nb of karts=5, ai:4 players:1

[warn   ] EventHandler: While loading track '/usr/share/games/supertuxkart/data/tracks/cocoa_temple/track.xml'
[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
[info   ] STKHost: Listening has been stopped
[verbose  ] Thread: Start waiting 1251862.665000
[verbose  ] Thread: Stop waiting 1251864.675000
[verbose  ] Thread: Waited for more than 2.000000 seconds for thread to become deleteable
[info   ] Thread: News manager not stopping, exiting anyway.
[info   ] Singleton: Destroyed singleton.
[warn   ] STKHost: Packet logging file has been closed.
[info   ] Singleton: Destroyed singleton.

**Comment by Arthur-D** [comment]
[info ] IrrDriver: OpenGL version: 2.1
[info ] IrrDriver: OpenGL vendor: X.Org
[info ] IrrDriver: OpenGL renderer: Gallium 0.4 on AMD RV710
[info ] IrrDriver: OpenGL version string: 2.1 Mesa 10.5.7
[warn ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)

According to this you are using drivers which doesn't support OpenGL 3. I suggest trying to reinstall the proprietary AMD driver to see if this may solve the issues.

**Comment by hiker** [comment]
Closing this ticket for now, please let us know if updating the drivers does not help.
