### ISSUE TITLE
STK treats quote marks inside Hebrew acronyms as a blank space

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2226]
SuperTuxKart treats quote marks inside Hebrew acronyms as a blank space.

When viewing addon size information, the string %s מ"ב  (that's %s MB - string 6)  looks like this: %s מ ב . a blank space. 

Could the comix font lack a character, or STK treats that string literally ?

**Comment by cap44** [comment]
also, the string is backwards

**Comment by Flakebi** [comment]
The quote character is missing in the font, it would be displayed if it was there (tested quick and dirty by spoofing the character from the xml file). The string is reversed one time too often, when it's reversed only once, it looks like this (for 1.9 MB and still without the quote mark):
![screenshot](https://cloud.githubusercontent.com/assets/6499211/8777097/25697180-2ef6-11e5-9d3c-a2c461576faa.png)
Is that the form that would be right or is there still something missing?

**Comment by cap44** [comment]
@Flakebi Yes, that's how it should be. Why is FriBiDi flipping the string twice?

**Comment by Flakebi** [comment]
Ok nice, thanks for the review.
It wasn't fribidi that flipped the string too often, but the text '%s MB' was reversed for the first time when it was translated, and reversed for the second time when it was inserted into the bigger string.
The fix can be found in #2244.

**Comment by auriamg** [comment]
#2244 has been merged, so that part should now be fixed :)

**Comment by cap44** [comment]
Looks good

**Comment by auriamg** [comment]
Hmm actually the reversed part was fixed but the missing character was not AFAIK, this was closed a little prematurely

**Comment by cap44** [comment]
the quote marks exist within the font - look at the lower part of the screenshot
![mines-2015 07 28_23 05 41](https://cloud.githubusercontent.com/assets/8017401/8942294/4377fe34-357d-11e5-80da-5964704b829f.png)

So why isn't that character rendered as part of the acronym?

**Comment by Flakebi** [comment]
Ok, interesting, the quote mark is not contained in the xml file so irrlicht/stk don't know that it exists.

**Comment by cap44** [comment]
Can it be added? because currently, it looks weird without the quote mark
