### ISSUE TITLE
No Game mode is able to run

### ISSUE THREAD

**Issue by Moaz93** [supertuxkart/stk-code#2227]
---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 <no symbol available>
 <no symbol available>
---------------------------
OK   
---------------------------

**Comment by Moaz93** [comment]
i didn't modify or recompile the game myself
i just did installed the game from the windows installer

**Comment by Moaz93** [comment]
i've red some other issues it may be pngs........ idont know?

**Comment by auriamg** [comment]
Hi, we will need a bit more information. What is your OS (including version), your GPU, and also the callstack doesn't seem to have copied/pasted correctly to the ticket

**Comment by Moaz93** [comment]
Thank you for commenting......
im running Windows 7 64 bit SP1 with intel HD 4000 GPU, Nvidia GT610M and 8 GB of RAM.......
and sorry i didn't understand what is the callstack, i'm new to this stuff.........
again sorry for my question.........

**Comment by deveee** [comment]
Try to run game using nvidia graphics card. It is probably as slow as integrated intel (or slower ;) ) but has better OpenGL support. Though it should also work using intel HD with current drivers...

Call stack is complete, but it is just displayed incorrectly on github. But still it says nothing...
---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 <no symbol available>
 <no symbol available>
---------------------------
OK   
---------------------------

**Comment by Moaz93** [comment]
Thank you my friend, it worked! i tried to force it to run using Nvidia card only and it worked perfectly fine, Thanks for all of you guys and your help.
I will close the issue now...........
