### ISSUE TITLE
Fort Magma: Alpha wall

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2230]
In fort magma there is an alpha wall that doesn't make any sense. Well it prevents people taking a shortcut. But you can't see it and just hang in the air.

A fence or skirting board would make it visible clear that people can't drive there and try the shortcut.

Image: 
![bildschirmfoto von 2015-07-06 22 13 32](https://cloud.githubusercontent.com/assets/1377943/8533668/d5288108-2436-11e5-9ffd-e2171729269d.png)

**Comment by hiker** [comment]
This track will be improved/replaced - not sure about the timelime at this stage.

**Comment by auriamg** [comment]
This ticket seems outdated, the area in the screenshot is different now, so I think this issue no longer exists

**Comment by qwertychouskie** [comment]
Can confirm fixed.
