### ISSUE TITLE
Mine Track (backwards): clipping and visual bug on a bridge

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2231]
If you drive the mine track backwards you can get stuck/ at the bridge behind the crossing lore. 

And it doesn't look too good either. Floating banana included.

Image:

![bildschirmfoto von 2015-07-06 22 21 57](https://cloud.githubusercontent.com/assets/1377943/8533735/6bb43180-2437-11e5-9edf-d30456903c50.png)
![bildschirmfoto von 2015-07-06 22 22 13](https://cloud.githubusercontent.com/assets/1377943/8533736/6bba81a2-2437-11e5-84a3-9a484b1f2efb.png)

**Comment by hiker** [comment]
Not sure if this track will be updated or replaced.

**Comment by samuncle** [comment]
The track will be replaced, but to be honest during a normal race, I'm not sure if you notice the issue. It's a very small detail.

I probably won't fix it unless hiker or auria tell me it's important.
