### ISSUE TITLE
Feature request: Looking back while start countdown is running

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2232]
At the moment it is not possible to look back while the start countdown is counting. This would be very handy in multiplayer so you know if your arch enemy is behind you, so you can prepare to be rammed or worse: overtaken!

BTW: it is possible to accel, brake, steer left and right, so why not turn your head?

**Comment by temeliak** [comment]
Hi! 

This is the first time I try to contribute to a project, so please excuse me if I do something wrong. 
So I found how to allow the player to look backward during the countdown : how can I submit the modification?

Thank you!

**Comment by deveee** [comment]
Fixed in current git
