### ISSUE TITLE
Detect new gamepads after start

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2233]
At the moment you have to restart Stk if you connect a new controller. It would be handy if stk would detect them automatically or provided a button in the key config screen to scan for connected controllers.

**Comment by deveee** [comment]
I have it more or less working, using reload button in options. It needed to fix few things. But still there is something wrong when I reconnect the same gamepad. In this case irrlicht receives gamepad events, the gamepad is shown in the list, but STK doesn't respond on its events anymore. I will look at this.

**Comment by Benau** [comment]
with sdl2 it is possible!
![](https://cdn.lihkg.com/assets/faces/pigxm/free.gif)![](https://cdn.lihkg.com/assets/faces/pigxm/free.gif)
