### ISSUE TITLE
Ghost villa (backwards): Minor graphical bugs

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2235]
If you drive the villa track backwards, so see some things in another light. So some aspects of the map are graphically lacking.

E.g. this transition into the tunnel look rather hard or harsh. The other way round looks much nicer, probably because you look from within a dark tunnel to the landscape that is enlighten by the moon. The other way round it just doesn't look right: 

![bildschirmfoto von 2015-07-06 22 26 28](https://cloud.githubusercontent.com/assets/1377943/8534216/8118c466-243a-11e5-9c32-08c5e2e3cccf.png)

Same for the start. You have this sand path that starts from nowhere. It wouldn't look that way if someone would use the path and step on the grass. This part is especially confusing as you have to turn left immediately after the start line. The paved grey path is just too tempting. Maybe one of those walls with animated arrows would be appropriate there. 

![bildschirmfoto von 2015-07-06 22 24 16](https://cloud.githubusercontent.com/assets/1377943/8534366/ef23939a-243b-11e5-88eb-08062fd4ca35.png)

Then there is this construction defect (upper left half):

![bildschirmfoto von 2015-07-06 22 27 02](https://cloud.githubusercontent.com/assets/1377943/8534377/1213e9a4-243c-11e5-9bfb-cd71beda5103.png)

Floating trees:

![bildschirmfoto von 2015-07-06 22 28 50](https://cloud.githubusercontent.com/assets/1377943/8534387/23b3aad2-243c-11e5-8ada-2911c7cca5ff.png)

In the villa there is the u-turn which is quite problematic when you drive backwards. First there is this step you have to drive up, then there is very little space to turn (especially with speed).

![bildschirmfoto von 2015-07-06 22 25 29](https://cloud.githubusercontent.com/assets/1377943/8534493/f9e483e2-243c-11e5-97be-b8fb9fcb7ec5.png)

And then there is this problem with the path again. It was definitely designed to be viewed from one side only.  

![bildschirmfoto von 2015-07-06 22 24 33](https://cloud.githubusercontent.com/assets/1377943/8534501/27cd1e7c-243d-11e5-8edb-caaa525a5de0.png)

You can see that the paths makes a hard stop, just like in the beginning. Even if you just drive over the bridge. 

But you can also drive around it on the left. If you drive from the other way there is the mushroom which blocks your way, but not from this side.

**Comment by auriamg** [comment]
Hi, this track is currently being redone, so most issues should disappear when the new version is ready

**Comment by hiker** [comment]
Tentatively scheduling for later, since most tracks will get replaced - hopefully by then.

**Comment by qwertychouskie** [comment]
This can probably be closed, as the new mansion will be in the gift package for 0.9.3 and included in a version after that, so this old track probably will not be getting more fixes.

**Comment by auriamg** [comment]
Delaying to a later version since this track will be replaced in a future version

**Comment by Alayan-stk-2** [comment]
This track will be replaced in the next version.
