### ISSUE TITLE
3 player karts stats

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2236]
What happens when you divide the screen width by 3 but forget that you have text to display? Stats that are hard to compare!

Idea for Solution: Show a pictogram/icon in front of every graph bar that indicates strength, weight or speed. Whatever strength means in context to karts. :) 

![bildschirmfoto von 2015-07-06 22 52 44](https://cloud.githubusercontent.com/assets/1377943/8534670/bfb54952-243e-11e5-9387-cc95b6b61544.png)

**Comment by lightonflux** [comment]
Also the "Standard" text on the button at the bottom is slightly off.

**Comment by lightonflux** [comment]
Just realised the problem is always present, with 2, 3 or 4 karts. Its always the same logical error.

**Comment by Flakebi** [comment]
This issue is already present here: #2065 but I admit that the existing report is hard to find :-)
Also it seems like "Tempo" isn't translated right (it should be all uppercase) that would also be fixed by using icons.

**Comment by auriamg** [comment]
Closing this as a duplicate, let's track this issue in #2065
