### ISSUE TITLE
3 players archivements banner render problem

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2237]
If you play with 3 players and one gets an achievement then the banner is displayed just fine, for some seconds. But then it slips behind the screen of the third player for some reason.

I have no screenshot or video and i can't reproduce achievements notifications so this gimped screenshot shows a visual approximation:

![stk-render-bug](https://cloud.githubusercontent.com/assets/1377943/8534890/24811620-2441-11e5-86af-e2cae609b406.png)

**Comment by auriamg** [comment]
Actually what happens for me is the opposite of your screenshot, can you confirm this is actually what you get?

![split_screen_bug](https://cloud.githubusercontent.com/assets/4296971/8864249/e0f54b62-316d-11e5-98ca-014364ae2930.jpg)
