### ISSUE TITLE
Football invisible drive backwards against it

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2239]
If you play football / kartball, then it happens often that you can look into the ball.

Not the best screenshot, but you see it a little bit on the right side.

![bildschirmfoto von 2015-07-07 01 00 30](https://cloud.githubusercontent.com/assets/1377943/8535195/d1f74ec6-2443-11e5-9754-63155142c3d0.png)

The things get worse when you drive backwards against the ball. You can't see it if you look forward. So you have no idea if you still have control over it. There should be some kind of indicator where the ball is. And no you can't always look back. Because you might need to see something else for a second, or because you use a keyboard and can only press 3 buttons at a time.

A arrow that moves at the screen edge and always points to the ball would be one idea for a visual representation. 

Symbolic screenshots: 

![bildschirmfoto von 2015-07-07 01 03 53](https://cloud.githubusercontent.com/assets/1377943/8535216/1036566e-2444-11e5-83b5-c9c1efade22e.png)

![bildschirmfoto von 2015-07-07 01 01 50](https://cloud.githubusercontent.com/assets/1377943/8535259/766890d2-2444-11e5-885e-5cf06b6c7755.png)

**Comment by deveee** [comment]
Actually we should add default ball model to data directory because now every arena needs to have its own ball model. And also every model can be marked as "ball" ;)

**Comment by Benau** [comment]
Notice: in current git if you play soccer field with navmesh (which supporting AIs), you can know where is the ball in the minimap

**Comment by Benau** [comment]
Actually it's more like a camera issue, which has more work to fix. So for now please use minimap for the location of ball, sorry about that.
