### ISSUE TITLE
Can't configure Dualshock 4 controller

### ISSUE THREAD

**Issue by Daimanu06** [supertuxkart/stk-code#2240]
Hello.

I'm currently installing a driver to use a Dualshock 4 (PS4) controller in order to use it in an emulator.
I test it with STK but it appears that I can't configure the controller in the options. When I press the X button, the "change button" window appears and disappears too quickly, and the X button is set for the action.

Of course I can change it manually in the input.xml file, but that'd be nice to safely set in in the game.

My config:
Ubuntu 15.04
STK 0.8.1
https://github.com/chrippa/ds4drv to bind the ps4 controller

PS: I know STK 0.9 is out, but I it is still not available in debian repository and I don't like download manually the game.

**Comment by auriamg** [comment]
Hi, we'll see what we can do though it's a little hard without having that specific gamepad to test with. Also there may have been improvements to this code since 0.8.1

**Comment by Daimanu06** [comment]
I checked in the 0.9 version. The problem is not fixed.

**Comment by hiker** [comment]
Do you have more than one gamepad controller? If so, could you try to only connect the dualshock and see if this helps?

**Comment by Daimanu06** [comment]
I only have the keyboard and the controller.
I'll try to unplug the keyboard to see if something changes.

**Comment by Alayan-stk-2** [comment]
No news for years, and I've seen someone reporting a Dualshock4 working correctly with the beta. Closing for now.
