### ISSUE TITLE
Remove random wheel rotation

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2241]
@auriamg  After a discussion with samuncle I've removed the random wheel parameter (all karts now have randomised wheel rotations). Can I just remove the settings for that in the exporter from stk_panel_parameters.xml:, or is any other change required (e.g. change to existing models or so)?

**Comment by auriamg** [comment]
We also need to modify stk_kart.py to clean it up there too, I can handle that if you wish

**Comment by auriamg** [comment]
Removed from exported
