### ISSUE TITLE
TrackSector::setLastTriggeredCheckline crash?

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2242]
SuperTuxKart just crashed with a segfault on TrackSector::setLastTriggeredCheckline

backtrace:
Program received signal SIGSEGV, Segmentation fault.
0x0000000000d9f5a2 in TrackSector::setLastTriggeredCheckline (this=0x14, i=1) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/track_sector.hpp:75
(gdb) bt
#0  0x0000000000d9f5a2 in TrackSector::setLastTriggeredCheckline (this=0x14, i=1) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/track_sector.hpp:75
#1  0x0000000000d9f28f in CheckLine::isTriggered (this=0x7fffb50b9ae0, old_pos=..., new_pos=..., kart_index=0) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/check_line.cpp:161
#2  0x0000000000d9925b in CheckManager::getChecklineTriggering (this=0x7fffc20dd220, from=..., to=...) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/check_manager.cpp:172
#3  0x0000000000d9421a in QuadGraph::computeChecklineRequirements (this=0x7fffc58f3ef0, node=0x7fffc58fc650, latest_checkline=0) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/quad_graph.cpp:248
#4  0x0000000000d94142 in QuadGraph::computeChecklineRequirements (this=0x7fffc58f3ef0) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/quad_graph.cpp:228
#5  0x0000000000d73559 in Track::loadTrackModel (this=0x249a530, reverse_track=false, mode_id=0) at /home/i5150pc/stk-bleeding/stk-code/src/tracks/track.cpp:1945
#6  0x0000000000be4c57 in World::init (this=0x7fffccf88860) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:177
#7  0x0000000000befa5f in WorldWithRank::init (this=0x7fffccf88860) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world_with_rank.cpp:31
#8  0x0000000000beac9f in LinearWorld::init (this=0x7fffccf88860) at /home/i5150pc/stk-bleeding/stk-code/src/modes/linear_world.cpp:59
#9  0x000000000094aa36 in RaceManager::startNextRace (this=0x57765a0) at /home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:493
#10 0x000000000094a0a4 in RaceManager::startNew (this=0x57765a0, from_overworld=false) at /home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:406
#11 0x000000000094bc74 in RaceManager::startSingleRace (this=0x57765a0, track_ident="cocoa_temple", num_laps=17, from_overworld=false) at /home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:821
#12 0x0000000000d1e5e0 in TrackInfoScreen::onEnterPressedInternal (this=0x7fffc6e0e580) at /home/i5150pc/stk-bleeding/stk-code/src/states_screens/track_info_screen.cpp:286
#13 0x0000000000d1e6b2 in TrackInfoScreen::eventCallback (this=0x7fffc6e0e580, widget=0x7fffc6cc4c00, name="buttons", playerID=0) at /home/i5150pc/stk-bleeding/stk-code/src/states_screens/track_info_screen.cpp:298
#14 0x0000000000a4037c in GUIEngine::EventHandler::sendEventToUser (this=0x25f52e0, widget=0x7fffc6cc4c00, name="buttons", playerID=0) at /home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:528
#15 0x0000000000a40ca6 in GUIEngine::EventHandler::onWidgetActivated (this=0x25f52e0, w=0x7fffc6cc5990, playerID=0) at /home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:568
#16 0x0000000000a3fa5e in GUIEngine::EventHandler::onGUIEvent (this=0x25f52e0, event=...) at /home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:613
#17 0x0000000000a3f45f in GUIEngine::EventHandler::OnEvent (this=0x25f52e0, event=...) at /home/i5150pc/stk-bleeding/stk-code/src/guiengine/event_handler.cpp:149
#18 0x0000000000f5047a in non-virtual thunk to irr::gui::CGUIEnvironment::OnEvent(irr::SEvent const&) () at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:399
#19 0x0000000000fb280b in irr::gui::CGUIButton::OnEvent (this=<optimized out>, event=...) at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:225
#20 0x0000000000fb2883 in irr::gui::CGUIButton::OnEvent (this=0x7fffc6e04ce0, event=...) at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIButton.cpp:215
#21 0x0000000000f50c9c in irr::gui::CGUIEnvironment::postEventFromUser (this=0x1ab49d0, event=...) at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CGUIEnvironment.cpp:570
#22 0x0000000000f16852 in irr::CIrrDeviceStub::postEventFromUser (this=0x179ac00, event=...) at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp:227
#23 0x0000000000f108f1 in irr::CIrrDeviceLinux::run (this=0x179ac00) at /home/i5150pc/stk-bleeding/stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp:1277
#24 0x0000000000ac2a08 in IrrDriver::update (this=0x175a2e0, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/graphics/irr_driver.cpp:2103
#25 0x00000000009d14b3 in MainLoop::run (this=0x77b9eb0) at /home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:151
#26 0x00000000009da4d5 in main (argc=1, argv=0x7fffffffe028) at /home/i5150pc/stk-bleeding/stk-code/src/main.cpp:1509

how did this happen?

**Comment by auriamg** [comment]
I presume this is latest git version, and not a stable release?

**Comment by cap44** [comment]
Yes

**Comment by auriamg** [comment]
Should now be fixed
