### ISSUE TITLE
Incorrect rescue in zipper-jump of STK Enterprise

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2246]
When you go on the zipper ramp before the long jump, sometimes the kart is rescued (incorrectly).

The kart apparently considers itself to be on "supp1k.png", which is a rescue-triggering texture (most likely the invisible rescue plane at the bottom). Strangely enough all 4 wheels are still on the ground (actually all on the zipper texture), but the separate raycast to find the terrain hits the rescue plane.

**Comment by hiker** [comment]
In short: the raycast to detect the terrain the kart is on could sometimes happens ahead of the actual wheels (if the kart is very fast, low FPS would make it more likely as well): the physics first determines wheel position, then wheel force, then moves the chassis - so the chassis is somewhat ahead of the wheels. In extreme circumstances the centre of the chassis could be ahead of the front wheels.

In this case, all wheels were on the ground on the ramp, but the raycast done slightly ahead of the front wheels could miss the ramp, and instead find the (invisible) rescue plane underneath: all 4 wheels on the ground, and the ground is auto-rescue --> the kart was rescued.
The problem is fixed in cefce31 by not using the centre of the chassis as origin of the raycast for terrain detection (since the chassis can be ahead of the wheels), but the centre point of all four wheels.

**Comment by auriamg** [comment]
Are you sure it truly is "supp1k.png" ? This texture contains moving arrows and only appears to be used on walls. It's incorrectly marked as a reset surface and that should be corrected, though I have no idea how that could be triggered near the ramp, this texture doesn't seem to be around the jump

**Comment by hiker** [comment]
samuncle told me that he would likely have re-used an existing rescue texture with transparency. But I admit ... I couldn't find that rescue plane in the blend file, but I guess that's just my limited blender knowledge.
