### ISSUE TITLE
Weird crash on latest commit?

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2247]
I have no idea why, but STK just crashed with a sigabrt (was Playing on Cocoa Temple with an addon kart)

Program received signal SIGABRT, Aborted.
0x00007ffff4914187 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
(gdb) bt
#0  0x00007ffff4914187 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4915538 in __GI_abort () at abort.c:78
#2  0x00007ffff490d126 in __assert_fail_base (fmt=0x7ffff4a42858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x114687f "!(sizeof (torque.getX()) == sizeof (float) ? __isnanf (torque.getX()) : sizeof (torque.getX()) == sizeof (double) ? __isnan (torque.getX()) : __isnanl (torque.getX()))", file=file@entry=0x113c5df "/home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h", line=line@entry=348, function=function@entry=0x114aa15 "void btRigidBody::applyTorqueImpulse(const btVector3 &)") at assert.c:92
#3  0x00007ffff490d1d2 in __GI___assert_fail (assertion=0x114687f "!(sizeof (torque.getX()) == sizeof (float) ? __isnanf (torque.getX()) : sizeof (torque.getX()) == sizeof (double) ? __isnan (torque.getX()) : __isnanl (torque.getX()))", file=0x113c5df "/home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h", line=348, function=0x114aa15 "void btRigidBody::applyTorqueImpulse(const btVector3 &)") at assert.c:101
#4  0x0000000000cab462 in btRigidBody::applyTorqueImpulse (this=0x7fffc3a8c250, torque=...) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:348
#5  0x0000000000ca7b0a in btKart::updateVehicle (this=0x7fffa7f91890, step=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/src/physics/btKart.cpp:460
#6  0x0000000000cabf82 in btKart::updateAction (this=0x7fffa7f91890, collisionWorld=0x7fffb54d1e70, step=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/src/physics/btKart.hpp:206
#7  0x0000000000de248f in btDiscreteDynamicsWorld::updateActions (this=0x7fffb54d1e70, timeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:448
#8  0x0000000000de2368 in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x7fffb54d1e70, timeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:347
#9  0x0000000000de20e9 in btDiscreteDynamicsWorld::stepSimulation (this=0x7fffb54d1e70, timeStep=0.0329999998, maxSubSteps=3, fixedTimeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:290
#10 0x0000000000cb219a in Physics::update (this=0x7fffe2582d60, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/physics/physics.cpp:155
#11 0x0000000000be8e0d in World::update (this=0x7fffc6ace9a0, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:948
#12 0x0000000000bec33c in LinearWorld::update (this=0x7fffc6ace9a0, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/modes/linear_world.cpp:155
#13 0x0000000000be86f6 in World::updateWorld (this=0x7fffc6ace9a0, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:825
#14 0x00000000009d1b44 in MainLoop::updateRace (this=0x77bd010, dt=0.0329999998) at /home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:107
#15 0x00000000009d1c6c in MainLoop::run (this=0x77bd010) at /home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:128
#16 0x00000000009dad75 in main (argc=1, argv=0x7fffffffe028) at /home/i5150pc/stk-bleeding/stk-code/src/main.cpp:1509

last 2 entries in the exec window: 

[warn   ] physics: Kart at (257.087006 21.009470 -155.320496) is too high above ground at (257.087006 11.987634 -155.320496)
supertuxkart: /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:348: void btRigidBody::applyTorqueImpulse(const btVector3 &): Assertion `!(sizeof (torque.getX()) == sizeof (float) ? __isnanf (torque.getX()) : sizeof (torque.getX()) == sizeof (double) ? __isnan (torque.getX()) : __isnanl (torque.getX()))' failed.

this happened to me yesterday. latest commit?

**Comment by hiker** [comment]
I assume this happened during a rescue? Do you remember which way you were driving (turning right when you arrived at the village, where you have a jump, or did you go straight)? Why were you rescued? And which addon kart did you use?

**Comment by cap44** [comment]
@hiker No, this wasn't during a rescue because the kart on on the track during the crash.
It was where the large gear was, i'm using this addon kart: http://stkaddons.net/karts/lamborghini-lp400 (yep, from the old STK addons website)

**Comment by hiker** [comment]
OK, so the message on stdout (" too high above ground") happened before then. So far I can't reproduce this. Did anything special happen before the crash? Were you rescued, hit a wall and were thrown around, hit by a cake?
Can you reproduce the crash?

**Comment by cap44** [comment]
@hiker Not really, it's kinda like a heisenbug  (sometimes you catch it, and sometimes you don't), i was rescued a lap or 2 before that, and got rammed into a wall from hitting the booster on the right side of the fork. that's all I know

**Comment by hiker** [comment]
Tried with the same addon kart (gee, that kart shakes like crazy). Still couldn't reproduce it. My suspicion is that you managed to tunnel into the wall (partially perhaps), which can happen at high speed. The actual NAN would occur somewhere before, but is only caught at that location.
Not sure what to do about this :(

**Comment by cap44** [comment]
@hiker I see, but here's the weird part: i managed to trigger the bug by crashing into the wall on the opposite side of the zipper, and ended up on the side (left wheels up), and later it crashed just before the exit of a small cave in the village. 

this is the full backtrace: 
(gdb) bt full
#0  0x00007ffff4914187 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 32495
        selftid = 32495
#1  0x00007ffff4915538 in __GI_abort () at abort.c:78
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fffffffe4b5, sa_sigaction = 0x7fffffffe4b5}, sa_mask = {__val = {140737297772082, 18073055, 348, 4, 140737488341792, 50449143088, 3206979375, 4294967296, 0, 0, 0, 21474836480, 140737297771599, 140737488341944, 140737354031104, 140737297786968}}, sa_flags = 18114687, sa_restorer = 0x114aa15}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff490d126 in __assert_fail_base (fmt=0x7ffff4a42858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x114687f "!(sizeof (torque.getX()) == sizeof (float) ? __isnanf (torque.getX()) : sizeof (torque.getX()) == sizeof (double) ? __isnan (torque.getX()) : __isnanl (torque.getX()))", file=file@entry=0x113c5df "/home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h", line=line@entry=348, function=function@entry=0x114aa15 "void btRigidBody::applyTorqueImpulse(const btVector3 &)") at assert.c:92
        str = 0x7fff90468890 ""
        total = 4096
#3  0x00007ffff490d1d2 in __GI___assert_fail (assertion=0x114687f "!(sizeof (torque.getX()) == sizeof (float) ? __isnanf (torque.getX()) : sizeof (torque.getX()) == sizeof (double) ? __isnan (torque.getX()) : __isnanl (torque.getX()))", file=0x113c5df "/home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h", line=348, function=0x114aa15 "void btRigidBody::applyTorqueImpulse(const btVector3 &)") at assert.c:101
No locals.
#4  0x0000000000cab462 in btRigidBody::applyTorqueImpulse (this=0x7fffa79bdef0, torque=...) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:348
No locals.
#5  0x0000000000ca7b0a in btKart::updateVehicle (this=0x7fffa79be680, step=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/src/physics/btKart.cpp:460
        kart_up = {m_floats = {0, 1, 0, 0}}
        terrain_up = {m_floats = {0, 1, 0, 0}}
        axis = {m_floats = {-nan(0x400000), -nan(0x400000), -nan(0x400000), 0}}
        av = {m_floats = {0, 0, 0, 0}}
        chassisTrans = @0x7fffa79bdef8: {m_basis = {m_el = {{m_floats = {-0.961341143, 0, 0.27535978, 0}}, {m_floats = {0, 1, 0, 0}}, {m_floats = {-0.27535978, 0, -0.961341143, 0}}}}, m_origin = {m_floats = {257.087433, 21.1333313, -155.320328, 0}}}
        forwardW = {m_floats = {0.27535978, 0, -0.961341143, 0}}
        needs_cushioning_test = false
        dif = 5
#6  0x0000000000cabf82 in btKart::updateAction (this=0x7fffa79be680, collisionWorld=0x7fffc762fd60, step=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/src/physics/btKart.hpp:206
No locals.
#7  0x0000000000de248f in btDiscreteDynamicsWorld::updateActions (this=0x7fffc762fd60, timeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:448
        i = 9
        __profile = {<No data fields>}
#8  0x0000000000de2368 in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x7fffc762fd60, timeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:347
        __profile = {<No data fields>}
        dispatchInfo = @0x7fffc762fd90: {m_timeStep = 0.0166666675, m_stepCount = 0, m_dispatchFunc = 1, m_timeOfImpact = 1, m_useContinuous = true, m_debugDraw = 0x7fffb433ef80, m_enableSatConvex = false, m_enableSPU = true, m_useEpa = true, m_allowedCcdPenetration = 0.0399999991, m_useConvexConservativeDistanceUtil = false, m_convexConservativeDistanceThreshold = 0, m_stackAllocator = 0x7fffc59cbbd0}
#9  0x0000000000de20e9 in btDiscreteDynamicsWorld::stepSimulation (this=0x7fffc762fd60, timeStep=0.0270000007, maxSubSteps=3, fixedTimeStep=0.0166666675) at /home/i5150pc/stk-bleeding/stk-code/lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:290
        i = 0
        clampedSimulationSteps = 2
        __profile = {<No data fields>}
        numSimulationSubSteps = 2
#10 0x0000000000cb219a in Physics::update (this=0x7fffc59cb680, dt=0.0270000007) at /home/i5150pc/stk-bleeding/stk-code/src/physics/physics.cpp:155
        p = {m_up = {, }, m_contact_point = {{<btVector3> = {m_floats = {4.27106355e-38, 0, 4.27106355e-38, 0}}, <No data fields>}, {<btVector3> = {m_floats = {4.27119808e-38, 0, 4.27104786e-38, 0}}, <No data fields>}}}
#11 0x0000000000be8e0d in World::update (this=0x7fffc5a92a50, dt=0.0270000007) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:948
        kart_amount = 32767
#12 0x0000000000bec33c in LinearWorld::update (this=0x7fffc5a92a50, dt=0.0270000007) at /home/i5150pc/stk-bleeding/stk-code/src/modes/linear_world.cpp:155
        kart_amount = 0
        pos_used = std::vector of length 0, capacity 35184366179302
#13 0x0000000000be86f6 in World::updateWorld (this=0x7fffc5a92a50, dt=0.0270000007) at /home/i5150pc/stk-bleeding/stk-code/src/modes/world.cpp:825
        e = @0x7fff90478c88: {<std::runtime_error> = {<std::exception> = {_vptr.exception = 0x7220657461647055}, _M_msg = <error reading variable: Cannot access memory at address 0x29286500656349>}, <No data fields>}
#14 0x00000000009d1b44 in MainLoop::updateRace (this=0x7a23280, dt=0.0270000007) at /home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:107
No locals.
#15 0x00000000009d1c6c in MainLoop::run (this=0x7a23280) at /home/i5150pc/stk-bleeding/stk-code/src/main_loop.cpp:128
        dt = 0.0270000007
        device = 0x179add0
#16 0x00000000009dad75 in main (argc=1, argv=0x7fffffffe028) at /home/i5150pc/stk-bleeding/stk-code/src/main.cpp:1509
        s = ""
        materials_file = "../data/../../stk-assets/models/materials.xml"
        important_message = {array = 0x7fffcd015250 L"", allocated = 1, used = 1, allocator = {_vptr$irrAllocator = 0x10f0870 <vtable for irr::core::irrAllocator<wchar_t>+16>}}
        e = @0x7ffff525c3d9: {_vptr.exception = 0x1040c708588948}

**Comment by cap44** [comment]
Crashed again, near the bridge at Cocoa Temple - was not rescued and on the 1st lap
