### ISSUE TITLE
FTL GP only shows points for one player

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2249]
I am just testing pull request #2058 , maybe it's related to that.

Also, it looks like the first player gets the number of points for 2nd rank etc.

**Comment by Flakebi** [comment]
I didn't notice any regression when comparing the master version to my branch, but I saw (probably) the same bugs as hiker:
 - When the points are added in the race result screen, the `+7` (or similar) column is only shown for the first kart. The other karts get points too, but they come out of nowhere.
 - When you are the best player you get the points for the 2nd rank. You can get more when you overtake the leader after the last kart got eliminated (so you have the completely first rank).

**Comment by hiker** [comment]
This is already partially fixed - the points are shown, but not the point-inrease-animation.
