### ISSUE TITLE
massive performance issue with master

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2250]
During my test I noticed a massive performance issue, STK runs at 20 FPS for cocoa temple (previously I was able to run the track at ~60 FPS).

It's probably not related to rendering because even if I disable everything (the advanced shader) I got 40 FPS, where previously I had 100.

I'm not sure at this point what's causing the issue.

However I can tell the issue was already present at the commit #8be383015c47f514cdf8d62e1f30517ae4b2f77a

I don't have the time right now to investigate further.

Config:
OS: Xubuntu
GPU nvidia GTX660
Resolution: 1920*1024

**Comment by samuncle** [comment]
![screenshot - 26 07 2015 - 06 20 08](https://cloud.githubusercontent.com/assets/6406045/8892564/6ca5ee18-335e-11e5-8c71-07b246b9e065.jpg)
Apparently it's seems to be the culling

**Comment by auriamg** [comment]
I am unable to reproduce, can you please check if this is debug or release mode?

**Comment by samuncle** [comment]
Okay so by updating ubuntu I had an older version of the drivers + I was in debug mode.

With a clean build + the last nvidia driver I have no performance issues.
