### ISSUE TITLE
command line does not work on windows 8

### ISSUE THREAD

**Issue by Cyrille37** [supertuxkart/stk-code#2251]
Hello

On Linux the command line works fine but on Windows I could not get it on:
> supertuxkart.exe --help
nore
> supertuxkart.exe -h
nore
> supertuxkart.exe /?

Shure I miss something ?

Cheers

**Comment by deveee** [comment]
Windows application must be compiled as console application to make stdout working. It will work on linux using wine, but won,t work on windows. I don't know any way to make it working without forcing to open console every time.

**Comment by Cyrille37** [comment]
Thank you.
Cheers.
