### ISSUE TITLE
build process edits pnglibconf.h file

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#2256]
During the build process, the pnglibconf.h file gets edited. This prevents merging with remote changes since you need to reset the tree to HEAD every time before you can merge.

I hope there's a way to fix it.

Here are the changes:
diff --git a/lib/libpng/pnglibconf.h b/lib/libpng/pnglibconf.h
index 8022a5a..49fcc8c 100644
--- a/lib/libpng/pnglibconf.h
+++ b/lib/libpng/pnglibconf.h
@@ -3,7 +3,7 @@
 
 /* pnglibconf.h - library build configuration */
 
-/* libpng version 1.5.4 - last changed on June 22, 2011 */
+/* Libpng 1.5.9 - February 18, 2012 */
 
 /* Copyright (c) 1998-2011 Glenn Randers-Pehrson */

**Comment by auriamg** [comment]
this file seems to be generated from a template ( /scripts/pnglibconf.h.prebuilt ), so that's not something we can stop. Probably it configures the library for the user's system

However, maybe this file should simply not be committed to git at all, and let it be generated on each system. However a quick test shows that at least on my computer it does not really work correctly if I just remove the file

**Comment by tobbi** [comment]
What about adding it to .gitignore?

**Comment by auriamg** [comment]
My point was actually that if you do that, the game won't be on a fresh checkout - so something would perhaps need to be fixed so that the build system properly generates it. On the test I did, if I deleted the file it was not regenerated

**Comment by tobbi** [comment]
Couldn't we simply leave out the version number from both of these files? It's really the only difference between the template and the actual file.

**Comment by auriamg** [comment]
I have no idea, this is linpng internals and I'm not familiar with it. Feel free to try, though

**Comment by deveee** [comment]
Where this file is generated in your case?

It should be generated in build directory:
```
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/scripts/pnglibconf.h.prebuilt
               ${CMAKE_CURRENT_BINARY_DIR}/pnglibconf.h)
```
and build directories are ignored in .gitignore file. In my case it is ```./supertuxkart-git/build-vs2015/lib/libpng/pnglibconf.h```

In the same way is generated also zconf.h file.

Maybe you use cmake in main directory instead of creating build dir?
