### ISSUE TITLE
STK doesn't compile with VS2015

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2257]
There is a problem that struct timespec is redeclared.

In pthread.h in our dependencies we have:
```
#ifndef HAVE_STRUCT_TIMESPEC
#define HAVE_STRUCT_TIMESPEC 1
struct timespec {
        long tv_sec;
        long tv_nsec;
};
#endif /* HAVE_STRUCT_TIMESPEC */
```

It is declared also in:
c:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h
But HAVE_STRUCT_TIMESPEC seems to be not defined by VS.

We could workaround it by adding
```
if (MSVC_VERSION EQUAL 1900)
    add_definitions(-DHAVE_STRUCT_TIMESPEC)
endif()
```
to our cmake file, but I'm not sure if this is safe enough.

And still there are some problems with linking wiiuse.

**Comment by deveee** [comment]
The problem with timespec structure redeclaration workarounded here:
https://github.com/supertuxkart/stk-code/commit/a0e54bb0b82fba8ab740e5aa2493931604392b60

Other projects solved it in mostly the same way, eg. they added this definition to pthread.h file.

And still wiiuse library needs to be recompiled to make it working with VS2015. It looks for me that it was compiled with openmp, which is not needed for this library.

**Comment by hiker** [comment]
You should be able to build wiiuse yourself in VS (WIIUSE_BUILD) - I am not sure how I built it (and sorry, I don't have time atm to install vs 2015)

**Comment by deveee** [comment]
Wiiuse can be built on VS2015 without problems. It should work now.
