### ISSUE TITLE
Several GPs saved, including 'random' (which can't even be continued)

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2258]
Afaik it should only be possible to save a single GP, I see several GPs saved, mostly 'random' ones.

Afaik random GPs can not even be continued (there information about which tracks are used etc is not even stored in the save data).

**Comment by hiker** [comment]
To clarify: several saved GPs for the same GP (with different number of karts). The number of karts is not used at all to select which GP to load.

Suggestion: only allow one saved GP for each GP, and do not save random Gps at all.

**Comment by deveee** [comment]
IIRC there was a while loop which was removing all saved GPs for your selected GP when you start it fom begin. So even if you have very old saved GPs for the same GP, they will be removed. I think it works fine in STK 0.9.

Random GPs indeed shouldn't be saved.

**Comment by hiker** [comment]
If there was such a loop, it didn't work :)  I had 3 copies of one GP saved (plus 5 or so random GPs). 
And the missing push is just coming through :) I left 'one save per GP and difficulty' in place.

**Comment by deveee** [comment]
@hiker the loop is in race_manager.cpp in startNew() function.

If we start new GP and not continue the previous one, there is:
```
            while (m_saved_gp != NULL)
            {
                m_saved_gp->remove();
                m_saved_gp = SavedGrandPrix::getSavedGP(
                                             StateManager::get()
                                             ->getActivePlayerProfile(0)
                                             ->getUniqueID(),
                                             m_grand_prix.getId(),
                                             m_player_karts.size());
            }
```

It removes all saves for selected GP for active player. It was possible to have several saves for the same GP if you had more than one user. And it seems to have sense that every player has its own saves.
