### ISSUE TITLE
Moved far back when rescuing in Green Valley

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2263]
Driving the first part of Green Valley, the rescuing works as expected, putting the kart a little back. Rescuing after the invisible checkline however, always moves the kart back to said checkline. How to easily reproduce: drive Green Valley as normal, and rescue when coming to the second or the last bridge.

There might be more tracks affected by this, but Green Valley is the one I'm certain of at the moment.

**Comment by hiker** [comment]
Should be fixed, please reopen if it still happens
