### ISSUE TITLE
Stop Screen Saver when using gamepad

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2275]
As reported in the forum (http://forum.freegamedev.net/viewtopic.php?f=17&t=6474) the X screen saver might start if the user is using a gamepad.

According to https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/30378/comments/9  xresetscreensaver can be used to avoid this.

**Comment by deveee** [comment]
Fixed in 78cd8efdd4bd0ae3f12d666a0b6c12d8b889de67
