### ISSUE TITLE
supertuxkart icon

### ISSUE THREAD

**Issue by rudrab** [supertuxkart/stk-code#2276]
Hi,
I am creating an icon theme for gnome3.x.
I tried to create an icon for stk but failed to create a svg of http://supertuxkart.sourceforge.net/site/skins/stk/images/head/logo.png

Do you have a svg in your repo? May you kindly send me that?

**Comment by konstin** [comment]
I can't help you with a svg of that image, but afaik normally a different icon is used. This icon is also used for http://supertuxkart.net.

**Comment by leyyin** [comment]
@rudrab This file in the media repo also contains the logo, maybe this helps http://sourceforge.net/p/supertuxkart/code/HEAD/tree/media/trunk/vector_art/menu%20icons%20by%20yekcim.svgz.

**Comment by deveee** [comment]
Seems to be nothing to do in STK
