### ISSUE TITLE
Blender Exporter Issues

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2277]
I tried to re-export stk-enterprise, but had a few problems:
- I got the message that 'code' is not defined. There is no indication that this is an STK (and not a blender) error message, and it is not explained in our docs. Additionally, if it's not defined but the name is, the name (after e.g. replacing spaces with _ etc) should be used as default. Besides ... what kind of name is 'code'? Perhaps call it 'directory name' (since this appears to be what it is). Additionally I think all current tracks in our media repo should work out of the box.
- After fixing the above issue, the exporter crashed. After a bit of fiddling around with the sources,it turns out that I need to set the path to stk-assets under user config (the crash was then caused because it could not create a directory somewhere). Again this appears to be undocumented, and obviously it should not crash (instead perhaps default to "." ?) Also it would be nicer if the path could be selected with a file selector gui, typing a long path manually is kind of annoying :)

**Comment by auriamg** [comment]
For point 2, this was using the menu, not the panel button. I expect that exporting through the panel button should be ok

**Comment by auriamg** [comment]
Just committed a few error management improvements to the exporter, in both of these cases there should now be a better error message. Not perfect but good enough IMO, can we close this?

**Comment by auriamg** [comment]
Getting no feedback, assuming fixed. Please reopen if you have more issues
