### ISSUE TITLE
Missed checkline in farm

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2281]
As reported in irc:
https://www.youtube.com/watch?v=fU1IYIvejnw
The kart misses checkline2, because the kart is 'hugging' the shed. It's a border case, but perhaps the checkline could be extended a bit (up to the shed wall)?

**Comment by auriamg** [comment]
Fixed in git/SVN, the issue was that the kart was too high above the checkline since there is a little hill, added a fence to prevent going there
