### ISSUE TITLE
STK doesn't find texture for library objects

### ISSUE THREAD

**Issue by CreativeForge** [supertuxkart/stk-code#2286]
I have multiple (2) objects in my library node. Both use the same texture which is in the folder of the library node (data/library/stklib_myObject_a/stklib_myObject_a.png). But only the main object (stklib_myObject_a_main) is textured -> the second one is not.
However, as soon as I put the texture in the main texture folder (data/textures/...) it works without problems -> both objects are textured.

stdout:
    [warn   ] Irrlicht: Could not open file of texture: stklib_railroadCrossing_a.png
    [warn   ] EventHandler: While loading track 'data/tracks/roadworks/track.xml'
    [warn   ] Irrlicht: Could not open file of texture: stklib_railroadCrossing_a.png

Both objects are flagged as "Object" type in the object panel and as said, both use the same texture file.
Have a look at the attached image (the non-textured object is the animated "light bulb"). You can download the library object here: http://creative-forge.ch/projectdata/roadworks.zip

As far as I know, Auria could not reproduce this problem. For me it persists even with the latest git.
![library_bug](https://cloud.githubusercontent.com/assets/10711264/9273710/51e3e630-428f-11e5-959c-17a3b6df7728.jpg)

**Comment by auriamg** [comment]
Hi, could you please also share the track where the issue appears? This way I can try with exactly the same setup as you

**Comment by auriamg** [comment]
Reported as no longer happening that OP, not sure what happened but issue seems to no longer occur
