### ISSUE TITLE
A commit make coco temple unplayable

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2289]
Using latest git of stk, playing in coco temple cause karts to crash like this:

https://vid.me/PeAC

Notes: there's more crash after when u by-pass using the shortcut in the left-hand-side.
Maybe the place where the wooden bottle (is it??) is placed leads to the bug.

I think i find the commit to blame is this one: 7b8da0ef342e1d22f19cfb9bbdfb7969a09ad68d

It relates to physics collision

I reverted the commit and played the track without anymore problems

Any ideas?

**Comment by auriamg** [comment]
This has been fixed in stk-assets (SVN), thanks for the report
