### ISSUE TITLE
Fix the ugly hack for Chinese display

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2297]
Hi!

I wrote a patch for stk/irrlicht to make it be able wrap line for CJK automatically in #2110 , but there're lots problem discovered later. 

Like space between chinese and english get ignored, incorrect linebreak, wrong wrapping position for english with chinese. 

Luckily, today I fully solved it by rewriting the print part of statictext, I posted the patch to irrlicht devs before, but getting no response, so I post here to hear comments.

Now stk/irrlicht can handle most utf breaking rules for CJK (can add more in utfwrapping.h) , like no opening brackets at ending line or punctuation mark at starting line. 

Here's screenshots:

![2015-08-26 16-19-56](https://cloud.githubusercontent.com/assets/3252341/9527341/263a81e6-4d21-11e5-96fd-bdb24c02ec8b.png)
As u can see, even the most complex combination of english, chinese and brackets, stk/irrlicht can print without wasting too much space *i copy the translation from another msgstr because i don't know how to print that box
![2015-08-26 16-39-24](https://cloud.githubusercontent.com/assets/3252341/9527343/26e4978a-4d21-11e5-8158-cf53a9cb0580.png)
As shown in the upper middle box, there's a unneeded newline for chinese, which fixed with the new patch.

Now some questions, is the code good enough? I don't know if I should add a extra .h for defination of 
brackets and punctuation. Do u think this should be included in irrlicht trunk too?

Patch: http://pastebin.com/zU7BQL9G

**Comment by auriamg** [comment]
Do you think you could submit that as a pull request? They are much easier to review and test than diffs

**Comment by Benau** [comment]
ok let me get more comments from the devs from irrlicht first, they say they may need more rewrite
(textwrapping should be in it's own class), but if you think that's beyond stk usage, I can do a pull reqest too.

overall the dev say that patch is ok.

see here for details:

http://irrlicht.sourceforge.net/forum/viewtopic.php?f=9&t=50938

**Comment by Benau** [comment]
Update!
From the latest post, they say textwrapping specific class is a larger topic, which I don't think it could be done in a short time.(even for me, i don't know very deeply about c++ like class/temples/constructor).

So I think it's better to make stk display chinese/jap/kr properly first, than improvement of irrlicht.

I will do pull request later.
