### ISSUE TITLE
new game console

### ISSUE THREAD

**Issue by lvilches21** [supertuxkart/stk-code#2303]
good,
my name is Luis Vilches, I am from Chile.

I am in the process of forming a team to develop a new video game based on the Linux operating system and I wonder if they will launch a version of the game, if so I hope to give support to the console that is developed or perhaps work together on this project, if you're interested of course.
Thank you

lvilches21@gmail.com

**Comment by auriamg** [comment]
Hi,

you are certainly welcome to use and distribute supertuxkart, and to ask us
specific questions if you meet problems. I don't think we will personnally
get involved with your project, however

Good luck,

-- Auria
