### ISSUE TITLE
Keyboard keys translations

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2306]
Recently translations for keyboard keys has been added. 99% of these names are non-translatable, at least in Polish. I can translate "Left arrow", "Right arrow" etc, but when I will translate other keys, such as "Escape", "Shift" and "Return", everybody will wonder what is this.

For me, only translating these keys have a sense:
- mouse buttons (are we using it?)
- keyboard arrows
- "left" and "right" words, eg. "Left Control", "Right Control"
- eventually "tab" and "space"

Are these translations really needed?

**Comment by Benau** [comment]
In other's translation, I see translator just copy the english (original) string to translated string.

Don't know if it's a good idea.(or quick way to fix this issue)

In fact that happens to player names too, like wilber, tux, but sara the racer "the racer" is translatable, maybe we should deal with left/right name like "the racer"?

**Comment by auriamg** [comment]
This is a bit debatable indeed, I think the original request was because some languages use different alphabets altogether (chinese, russian, greek, etc.) Translators from these languages have requested to be able to translate stuff to their own alphabet. I agree it doesn't make sense for all keys/languages

**Comment by deveee** [comment]
And another problem are possible conflicts between key names and gui
elements such as "play", "pause", "end", etc. Maybe at least add there
a context?

**Comment by deveee** [comment]
I added the context to keys translations. Example key names which were used in GUI in different places: "Accept", "Cancel", "Delete", "Help", etc...

Now this is acceptable for me. For non-translatable key names I just can leave original names.

Well, they actually are translatable, but everyone would wonder what is "Strona w górę" key :-P
