### ISSUE TITLE
Scores font in overworld sometimes has black background

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2308]
After few races I opened overworld and I noticed that scores font has non-transparent background. But I can't really reproduce it :(
![zrzut ekranu z 2015-09-05 15 18 00](https://cloud.githubusercontent.com/assets/5108558/9699418/76486fbe-53e2-11e5-9001-331f072d8913.png)

**Comment by Benau** [comment]
Sometimes happen to chinese fonts on "leader" translation. ie the chinese of leader above the ai player kart.

and yeah, cannot reproduce again recently, maybe a driver problem as I change to catalyst linux now.

I use open source radeonsi driver before...

**Comment by Flakebi** [comment]
I see the non-transparent font too, reproducible after I change the resolution. This happens on an nvidia gpu (with the proprietary driver).

**Comment by Benau** [comment]
Don't know if it could get fixed after full freetype loading is done in #2311

**Comment by auriamg** [comment]
Can you test if it still happens with latest git? The freetype branch was merged along with some improvements to the material manager so it might be fixed

**Comment by Flakebi** [comment]
This issue is still reproducible for me at faf697ef5 (shortly before the freetype merge).

Now the text stays transparent after I change the resolution which means it should be fixed :-).

**Comment by deveee** [comment]
It's working for me too.
