### ISSUE TITLE
Karts can't finish fortmagma track

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2309]
Probably rescue plane should be added. Or maybe also AI improved, because karts often fall in this place.
![zrzut ekranu z 2015-09-05 15 20 35](https://cloud.githubusercontent.com/assets/5108558/9699434/02ae70ac-53e3-11e5-9454-b496d27d09c6.png)
![zrzut ekranu z 2015-09-05 15 21 33](https://cloud.githubusercontent.com/assets/5108558/9699435/02b6c45a-53e3-11e5-9bf4-cc39272d8ab2.png)

**Comment by Alayan-stk-2** [comment]
The AI still isn't very good on the bridge, but it seems correctly rescued when I test the race. All 19 AIs managed to end a race. Should this be closed ?

**Comment by Alayan-stk-2** [comment]
Not an issue anymore in current git. Karts are rescued when they fall, and they don't fall all that often.
