### ISSUE TITLE
Harfbuzz usage

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2320]
![2015-09-26 09-06-12](https://cloud.githubusercontent.com/assets/3252341/10115017/1ce1812a-642e-11e5-870b-e88f628f34d5.png)

Compared to the bluefish-rendered text with stk.....

![2015-09-26 09-09-14](https://cloud.githubusercontent.com/assets/3252341/10115025/63f6b6a2-642e-11e5-8dac-95cee0cde04c.png)

When you add space between arabic, the orginal char which stk mis-rendered will shown.

Seems that arabic will have a different glyph when they are place at different position, I think we can deal with it with freetype+harfbuzz. But need one more libraries as deps.....

*NOTE I ain't an arabic speaker and just google around to know the basic rules in arabic

Fribidi on the other hand doesn't have enough docs which I can read, make me hard to fix.

Maybe anyone here who speaks arabic can give us some ideas too?

**Comment by Benau** [comment]
![2015-09-30 04-07-49](https://cloud.githubusercontent.com/assets/3252341/10176820/913e60bc-6729-11e5-86d0-a2b5105f1a93.png)

(you can compare the result to google translate, i copy the text directly from bluefish to the translation area)

Work on my freetype branch, I think I mostly intergrate stk with freetype + harfbuzz now, but as you can see, english is reversed so I think fribidi may need a fix.

I think the arabic now makes more sense.... let me see if I can get some idea from more (arabic speaking) people....

We can also make arabic a optional check-box in cmake, ie will not get linked if only selected enable.

**Comment by SafaAlfulaij** [comment]
I am an Arabic speaker! How can I help!?
(HUGE THANK FOR YOUR WORK! :+1:)

**Comment by Benau** [comment]
First, I want to know if the current display of arabic in stk is readable by a native arabic speaker or not....

![2015-10-02 00-19-23](https://cloud.githubusercontent.com/assets/3252341/10226638/47f2a292-689b-11e5-9667-1258a885f771.png)

Compared to the previous new-freetype-harfbuzz stk, which make sense?

Because stk devs want to avoid extra linking to new libraries (harfbuzz), but the displaying in my branch requires it....

Regarding the source code, I will push after i fix some unused function and bugs there, so @SafaAlfulaij you can actually help by just play the game. For the fonts, it can be easily change in the source as i used a ttf file, I will tell more details after the push, but give me some times....

**Comment by SafaAlfulaij** [comment]
It's doesn't make sense at all. The screenshot where Chrome/Chromium opened makes sense, even if it has no spaces at all :D
In my setup, This is how the text looks like:
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/10230774/9f501baa-6887-11e5-9f0e-53e475e0a749.png)
While it has several bugs, it is *somehow* readable.

**Comment by Benau** [comment]
seems that beside the arabic not being joined, there's issue with fribidi too

So to conclude, even if arabic isn't joined but in a correct LTR order, it is "somehow" readable by a native arabic speaker, but not perfect enough?

**Comment by auriamg** [comment]
I have just pushed a commit that should hopefully fix the LTR issue

**Comment by SafaAlfulaij** [comment]
@Benau No! I was saying that the Arabic text in my setup (The image I posted) is somehow readable even it has several bugs (Spaces between the same word, Wrong placed diacritics). Arabic **must** be joined so one can read it.

**Comment by Benau** [comment]
@SafaAlfulaij I think I almost do a pixel-to-pixel of arabic....
![2015-10-02 15-31-36](https://cloud.githubusercontent.com/assets/3252341/10241914/7ee1d596-691f-11e5-857f-810a9f3360eb.png)

You can actually test by build my branch from source to see if there's any missing glyph (or wrong rendering):

https://github.com/Benau/stk-code/tree/freetype

It's doesn't need harfbuzz as a dependency. Besides, you can also test gaming performance to see if freetype rendering affects fps, to me it doesn't as I have a fast pc.

For the fonts you recommend, I find them don't include basic latin which is require to display english in stk, currently my freetype stk use only 1 font to deal with 1 language, do you know any more (libre) fonts coming with basic latin glyph? In fact the freeserif (bold) have them but I find the arabic displayed by them is quite strange.

You can hack font and size here:

freetype_environment.cpp: 44 (name)
```
    assert(!FT_New_Face(ft_env.ft_lib,
          (file_manager->getAssetChecked(FileManager::TTF,
          "amiri-bold.ttf",true)).c_str(), 0, &(ft_env.ft_face[F_AR])));
```
TTF_handling.cpp:107 (size)
```
    if (langname.compare("el") == 0 || langname.compare("ar") == 0 || langname.compare("fa") == 0)
        ttf_file->size = (int)(28*scale); //Set lower size of font for Greek as it uses lots amount of space.
```
It can have one more if to deal with arabic about which size to use.

BTW, do you think Persian can use the same font of Arabic (amiri-bold)?

**Comment by SafaAlfulaij** [comment]
After I built the game, the supertuxkart bin reports an error: "[fatal  ] [KartProperties]: Missing default value for 'wheels radius' in '../data/stk_config.xml'." and I don't have any idea whats "wheel radius" :\

Looking at the last image, it's not correct 100%, but it solves the spacing in the words. The diacritics are placed in the wrong position, and the "Lam+Alif" combination is wrong (https://en.wikipedia.org/wiki/Arabic_alphabet#Ligatures)

And yes, Amiri supports Persian :)

**Comment by deveee** [comment]
@SafaAlfulaij It looks like you are trying to run older supertuxkart binary with current stk_config.xml. I see this error sometimes when I switch back from one of the older branches to master and forget about recompilation.

**Comment by Benau** [comment]
for the run error, you may try to uninstall old version of stk and install the new one again,

For the arabic display, current shaping of arabic is done by using fribidi, which lacks complex (or strict?) rules compared to harfbuzz. But the stk devs want to avoid linking an extra library so it isn't used.

Also it maybe related to the fribidi library in my linux, so it would be good if you are able to run it and test on different system.

Another way i can think of is to include a copy of fribidi into stk code, and then hack it with extra shape rules borrowed from harfbuzz. In fact current win32 build already has a standalone fribidi binary in the dependcies dir, so don't know if it is a good start.

If the stk devs don't like this idea, there's no further fix. Sorry for imperfect arabic display.

btw you can go to irc of stk in freenode for interactive chat!

**Comment by Benau** [comment]
![default](https://cloud.githubusercontent.com/assets/3252341/10266145/696eed7a-6a82-11e5-8f74-1fbcd4a98359.png)
Seems that the assert loading freetype will segfault if compiles in non-debug build, tested on win32 and archlinux!

will do push later

**Comment by Benau** [comment]
Now Noto Naskh Arabic UI is used on lazyloadchar branch, because this branch support "smart" loading char which know how to find glyph using different font file.

![2015-10-17 02-40-10](https://cloud.githubusercontent.com/assets/3252341/10550244/6b9c540c-7478-11e5-94c3-bfc4f13d8c36.png)

**Comment by khaledhosny** [comment]
Note that without HarfBuzz almost all Indic and many other Southeast Asian languages will be rendered badly, not to mention other languages using Arabic script that FriBiDi can’t shape (Pashto, for example). This while keeping in mind that FriBiDi’s shaping is subpar and obsolete, to begin with.

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/tree/harfbuzz

https://github.com/Benau/stk-code/commit/411a9977b0d8aaf7c1ae524690447b8f46d0fb68

Now harfbuzz support is added, it currently support linux only, and is suitable for translator who wants to test their work on stk, if it's a new language, just add language code, HB_SCRIPT_*** (find yourself) and the required font file in ft_environment.cpp, then it should work.

I think they need harfbuzz: (Even some are uncommon)
Arabic, Persian (for perfect shape comparing to fribidi)
Devanagari (Hindi)
Bengali
Gurmukhi
Gujarati
Oriya
Tamil
Telugu
Kannada
Malayalam
Sinhala
Khmer
Myanmar
Thai
Lao
Tibetan
Hebrew (Not strict required? But there's a hb-ot-shape-complex-hebrew.cc file, but in my src I don't do shaping for hebrew with harfbuzz)

It can also act as a example on how to display CTL languages with the least amount of deps, which is currently just fribidi+freetype+harfbuzz. (But don't know if there's anything wrong about the "harfbuzzize" part, feel free to point out if it's wrong)

Result:
Arabic:
![2015-10-22 12-15-45](https://cloud.githubusercontent.com/assets/3252341/10658408/27cc3292-78c9-11e5-833c-df2892ccfb16.png)
Bengali:
![2015-10-22 12-29-34](https://cloud.githubusercontent.com/assets/3252341/10658412/2bb84256-78c9-11e5-93aa-889505068be8.png)
The used glyph should be 100% correct, unless something wrong with my harfbuzz:(

Currently kerning is not supported, so some "space" comes out when the text is scaled. Is there a function from harfbuzz that can print advance.x,y  of hb_font with two glyph codepoint inputted?

-----------
As stk devs don't have time to build harfbuzz for mac and win32/64 (msvc and mingw), maybe some "genius" can help if more complex text layout language is added? Now translator should be more "willing" to translate stk into more language I think.

From here: https://github.com/libass/libass/issues/199, they say "harfbuzz had long been very easy to build on all major platforms including Windows, Linux and OS X. harfbuzz does not require GLib, ICU, Cairo or any other external library."

Or another way, should we avoid harfbuzz by rejecting the above language from getting into stk (transifex directly)? (not a good idea IMO)
Currently we have Arabic, Persian, Bengali and Hindi, although some of them are not very completed.

---------
I actually surprised that @khaledhosny would comment here, thanks for your font.

**Comment by Benau** [comment]
Finally:
https://github.com/Benau/stk-code/commit/99bdccfc3b96f406b2da94d5ccccde8e23427c9d

The use of harfbuzz seems not very "wanted", but I decide to finish it anyway, I don't like "unfinished business", even it may not be official.

Now I can produce 100% pixel to pixel arabic rendering, compared to the same text written in my setup of libreoffice (unless my harfbuzz setup is wrong):

![2015-11-08 15-36-21](https://cloud.githubusercontent.com/assets/3252341/11021619/c7e66e48-8682-11e5-863c-2f1d641bd815.png)

The glyph offsets are saved within the translated string, so i hack scalable_font to make it get and "translate" back into s32 offset, don't know if the convert works on all platform (I tested linux, windows msvc and mingw on XP). It doesn't affect gameplay too.

Let's try something more complicated:
![ms](https://cloud.githubusercontent.com/assets/3252341/11021650/54a4e886-8684-11e5-9afa-e8e7e37ef5c6.png)
Even XP works, which complains about old driver

![hacienda-2015 11 08_16 54 03](https://cloud.githubusercontent.com/assets/3252341/11021628/428ec2e4-8683-11e5-8cdb-59fe3c4e6aeb.png)
Billboard text with additional offset works too

Note that Thai translation is googled, just for testing, without harfbuzz the symbol about words will be placed incorrectly, also the the symbol above "harfbuzzied char" is another "char" with no advance (width) and different offsets, which means it isn't a "mixed" glyph, so it should not increase VRAM usage in any way.

In fact even current arabic translation there's only 480 unique glyphs are used with harfbuzz, all fit in 2 glyph pages in 1920x1080, still less than chinese. (For thai it's even only 87, how the symbol is placed varies, and harfbuzz will know that)

I write the language map with the most language supported by current font setup, so any new translation with correct language name code which require harfbuzz for proper display should auto-harfbuzzize.

Now, I don't if stk devs want to make stk to be the first (linux OSS) game in the world (is it ???) to support complex text with shaping by harfbuzz. I see the most matching search result about harfbuzz and game is unreal engine, which they are still on the way to support arabic:

https://forums.unrealengine.com/showthread.php?3924-CREATING-A-LOCALIZATION-READY-GAME-IN-UE4-Part-1-Text/page2&s=82efaab1000d15f1d023629eb550f7ca

https://answers.unrealengine.com/questions/179649/how-to-render-arabic-font-correctly.html

----------
Some fun facts also:
http://lists.freedesktop.org/archives/fribidi/2013-November/000710.html
It is still deprecated in the sense that nobody should be using Unicode
Arabic Presentation Forms shaping in 2013 AD.

Now it's almost 2016...

--------
Also after harfbuzz is used, the diacritics should be placed correctly no matter what font, so @SafaAlfulaij you can pick a "fancy" arabic font now (maybe ubuntu font too, they say hebrew and arabic font are "TBA")....

**Comment by Benau** [comment]
@khaledhosny 

```
+    bool need_harfbuzzize = false;
+    for (u32 h = 0; h < str.size(); ++h) //Prevent unneeded use of harfbuzz on basic latin only text
Is this really needed, do you have any measurements to share? HarfBuzz should be pretty fast for such text anyway, and you get kerning, ligatures and other nice typographic features.
```

Without it, something like this happen:
![2015-11-09 13-45-18](https://cloud.githubusercontent.com/assets/3252341/11026676/35edba26-86e8-11e5-8b17-6aa493f28406.png)

It's the limitation of STK which doesn't know how to determine LTR/RTL smartly when line breaking (after the strings are "harfbuzzized"), and also because of untranslated string.

Or do you want to make harfbuzz (or amiri font) "smartly" don't shape full stop to arabic form, when english is used but HB_SCRIPT_ARABIC is provided? Is there a "hb_feature_t" to config that??

**Comment by khaledhosny** [comment]
You need to do script itemization prior to shaping (and prior to applying bidi algorithm, as some common character might be split to separate RTL runs breaking proper script itemization) to determine which script common characters like the period belong to, which can only be inferred from the context.

As for paragraph alignment, it can be inferred from paragraph direction which can either be set by the user (the most reliable, like in LibreOffice), but if this is not possible then it can be determined by the bidi algorithm, fribidi has `fribidi_get_par_direction` that does that.

**Comment by Benau** [comment]
https://streamable.com/zosr9
Now even type in arabic works! (it may not make sense)

btw @khaledhosny it would be good if libraqm can:
1. Expose _raqm_allowed_grapheme_boundary, because the curosr positioning from libraqm is limited, for example i need something like this currently:
```
void CGUIEditBox::correctCursor(s32& cursor_pos, bool left)
{
    if (left)
    {
        if (cursor_pos >= (s32)m_edit_text.size())
            return;
        while (cursor_pos != 0 &&
            !Grahem::_raqm_allowed_grapheme_boundary(m_edit_text[cursor_pos - 1],
            m_edit_text[cursor_pos]))
            cursor_pos--;
    }
    else
    {
        while (cursor_pos != 0 && cursor_pos != (s32)m_edit_text.size() &&
            !Grahem::_raqm_allowed_grapheme_boundary(m_edit_text[cursor_pos - 1],
            m_edit_text[cursor_pos]))
            cursor_pos++;
    }
}
```
While in libraqm it always ++, and rq->text[*index], rq->text[*index + 1] overflow if it's the last index.

2. Add a delete word api, for example from what i see arabic you press backspace it can delete a diacritic only instead of a whole word (while _raqm_allowed_grapheme_boundary return false for them), or i can assume for emoji or country flag it can be deleted as a whole for a glyph?

3. Update _raqm_allowed_grapheme_boundary for emoji "ligature", for example for family emoji 👨‍👩‍👧‍👦 (combined with zero width joiner)
(or i can assume a glyph for each emoji is a word?)

4. btw as u see in video the "HK" flag becomes "KH" after a strong RTL character, in native android edittext it displays HK flag correctly, fribidi problem?

and @SafaAlfulaij can see if arabic ui in STK is better now and finish the translation!

**Comment by khaledhosny** [comment]
Please open issues against Raqm repository. Right now I don' have a working development setup to check this.

**Comment by Benau** [comment]
actually next release we will use 'sheenbidi' instead of libraqm because of better license, sorry khaledhosny...

and harfbuzz was used for a while, thank you and behdad for this wonderful software ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

**Comment by khaledhosny** [comment]
Libraqm has more than just using harfbuzz and fribidi, but whatever works for you.

I considered replacing fribidi with sheenbidi at some point, but it didn't pass ram test suite and I didn't have time to investigate further.
