### ISSUE TITLE
Fullscreen doesn't work properly in some cases

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2324]
I noticed that fullscreen option doesn't work as expected sometimes. You can see screenshots:

![zrzut ekranu z 2015-09-26 17 28 28](https://cloud.githubusercontent.com/assets/5108558/10118240/3f4cbed2-6474-11e5-868d-f7ac9aef645c.png)
![zrzut ekranu z 2015-09-26 17 28 32](https://cloud.githubusercontent.com/assets/5108558/10118241/3f51934e-6474-11e5-8f25-4147fc657c8a.png)

Additionally you can use "remember window location" option when "fullscreen" option is selected.

Atm. I have no idea if it's something wrong in our code or if it is regression in Xorg or Gnome. I didn't notice it anytime before. Now I see it in STK 0.9 as well as in current git with both nvidia and intel graphics cards.

**Comment by deveee** [comment]
It seems like calling XMoveWindow function shortly before sending _NET_WM_STATE_FULLSCREEN event causes this issue. 

I changed it to XMoveResizeWindow, which seems to solve this (I don't see this bug anymore). If it won't help, we can just add 100ms sleep after XMoveWindow call.

I also fixed deactivating "remember window pos" button.

**Comment by kostaldavid8** [comment]
I still have broken fullscreen with 0.9 (when I allow fullscreen, there is just window without borders and allow resolution and cancel buttons aren't working and are without text)

**Comment by deveee** [comment]
You mean 0.9 or current 0.9.1-rc1? I changed it few days ago, just before rc release.

**Comment by kostaldavid8** [comment]
I downloaded binary tgz 0.9.0 few hours ago for Linux, so it's probably just 0.9.0. Where I can get later version for Ubuntu? PPA won't let me download 0.9

**Comment by deveee** [comment]
Here is current release candidate:
http://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.1-rc1/supertuxkart-0.9.1-rc1-linux.tar.xz/download

Final version should be released soon.

It would be nice if you could test it. If fullscreen still isn't working for you, then I will try to find other solution.

**Comment by kostaldavid8** [comment]
Perfect, thank you very much. It works well.
