### ISSUE TITLE
Move libangelscript.a to build directory

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2325]
Atm. angelscript library is compiled in:
./lib/angelscript/lib/libangelscript.a

This shouldn't happen because you can compile a lot of different versions in separated build directories. When you compiled 32-bit version, and then you are trying to build STK 64-bit, it tries to link already compiled 32-bit angelscript version.

This is trivial to fix in cmake, but it should be probably commited upstream to avoid this problem after updating library.

**Comment by deveee** [comment]
Ok, fixed in this commit: f351c359fd9100910e7e5336086233e24f73abeb
But I'm leaving this open because I will try to contact them and explain the problem.

**Comment by qwertychouskie** [comment]
Can this be closed?

**Comment by deveee** [comment]
I created a bug report:
http://www.gamedev.net/topic/682745-compiled-library-is-not-placed-in-the-cmake-build-directory/

**Comment by deveee** [comment]
Already fixed upstream:
https://sourceforge.net/p/angelscript/code/2353/
