### ISSUE TITLE
Win Installer Improvements

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2329]
03:00:03 PM) MattDevo_: hiker: btw, is there a reason the windows installer requires a prebuilt install directory, rather than pulling directly from stk-code and stk-assets?

**Comment by hiker** [comment]
[supertuxkart.nis.txt](https://github.com/supertuxkart/stk-code/files/4903/supertuxkart.nis.txt)

**Comment by hiker** [comment]
MattDevo is working on it, waiting for a new icon from samuncle atm

**Comment by hiker** [comment]
Here a list of all items to be fixed/improved:
- [ ] Use stk-assets and stk-data/code from the installed directory (no need to copy data)
- [ ] Update icon file
- [ ] Compile icon file into executable
- [ ] Move windows_installer into tools directory

**Comment by hiker** [comment]
For new icon see #2064.

**Comment by cap44** [comment]
digital signature?

**Comment by hiker** [comment]
Most of this is now properly implemented (though not a digital signature, which is a much more involved process). The icon is tracked in #2064, so I am closing this ticket now

**Comment by cap44** [comment]
there's one small issue though, the Installer doesn't clean up upon uninstall, 

I could build a MSI package if needed

**Comment by hiker** [comment]
Hi,
for me the cleanup worked. What exactly was left over?
Also, did you have the editor installed? I'll a missing editor might cause the uninstall to abort.

**Comment by cap44** [comment]
@hiker the stk-editor.pdb file was left alongside the install folder (C:\Program Files (x86)\SuperTuxKart)

**Comment by hiker** [comment]
You need to update the editor repository, and do a clean build there. The editor files have all been renamed and are now called supertuxkart-editor.* . So likely this file is a left-over from a previous installation or an old file in the editor repo (though afaik it should not be installed then in the first place, a previous installation seems more likely).
Note that the uninstaller needs to list all files to remove, we can not uninstall INSTALL_DIR/*.* (what if someone installs STK in .../Program_files/  - i.e. no subdir? The uninstaller would remove all installed files there ;) ).

**Comment by cap44** [comment]
That file came from the supertuxkart installer, I didn't touch the
repository even. The Windows install is somewhat fresh, so no previous
install existed.
On Apr 28, 2016 5:32 AM, "hiker" <notifications@github.com> wrote:
>
> You need to update the editor repository, and do a clean build there. The
editor files have all been renamed and are now called supertuxkart-editor.*
. So likely this file is a left-over from a previous installation or an old
file in the editor repo (though afaik it should not be installed then in
the first place, a previous installation seems more likely).
> Note that the uninstaller needs to list all files to remove, we can not
uninstall INSTALL_DIR/. (what if someone installs STK in .../Program_files/
- i.e. no subdir? The uninstaller would remove all installed files there ;)
).

**Comment by hiker** [comment]
I just tried again, I added a dummy stk-editor.pdb and .exe file to the editor build directory, created a new installer and ran it installing into a new directory, and no stk-editor* there at all, and the uninstaller worked just fine, too. I even renamed the editor directory to stk-editor (with the above stk-editor* dummy files in RelWithDebInfo), and still everything worked.

I can't find any stk-editor in the .nsi installer (except for testing if a directory with this name exists, which I tested above).

Can you either email me or attach here the (potentially compressed) log file fron nsis? Which version of nsis are you using? Maybe something changed.

**Comment by cap44** [comment]
@hiker look inside the the release installer

**Comment by hiker** [comment]
What do you mean with release installer? Using a release (and not RelWithDebugInfo) mode? If so, for what (editor, stk, or both?) Or are you talking of the current 0.9.1 installer?

**Comment by cap44** [comment]
@hiker the current 0.9.1 installer (yeah, I know, it's somewhat old)

**Comment by hiker** [comment]
Closing this issue, if you test, please use the latest installer from github. This (should) fix all those issues.

Thanks for your help!
   Joerg
