### ISSUE TITLE
STK rc failed on clear xp

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2330]
After further investigation, seems the the openal32.dll bundled in mingw zip, requires msvcr90.dll which is not found in my system, I replace openal32.dll with the one provided by oalinst.zip and it runs.

Even so, it crashed when I tried to play, but it's a less important issues as it's a Vbox xp. But overall the gui display as properly as in linux/ normal windows.

Should we consider use the openal32.dll provided by oalinst.zip instead?

**Comment by deveee** [comment]
It's not possible to run STK on Virtualbox because of this issue:
https://github.com/supertuxkart/stk-code/issues/2326

The openal32.dll library is the same one, which is used in our VS package.
Indeed it would be nice to not depend on msvc libraries, even in old
versions. I will look what can be done.

**Comment by Benau** [comment]
Thank you for a quick reply!

**Comment by deveee** [comment]
After quick look, even libgcc depends on msvcrt.dll ;) But only OpenAL
depends on msvcr90.dll:
MSVCR90.dll =>
/cygdrive/c/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57/MSVCR90.dll
(0x72110000)

And indeed version which I have installed in system32 doesn't depend on
msvcr90.dll. I think that we should use it.

But I remember that OpenAL32 installer contains two libraries and both are
needed. Maybe I just were using newer installer from their website, and our
installer is in older version? I don't have any tool to unpack it atm.

**Comment by Benau** [comment]
![ms](https://cloud.githubusercontent.com/assets/3252341/10187400/e67b16a4-678a-11e5-8598-2137d6378507.png)

I used the latest oalinst.zip from offical website, do u find the screenshot useful?

**Comment by deveee** [comment]
Okay, I updated dependencies for mingw. Now it doesn't depend on msvcr90.dll. You can check it if you want:
https://github.com/supertuxkart/dependencies/tree/master/windows-mingw

Current OpenAL version needs both files: OpenAL32.dll and wrap_oal.dll. If you have only the first one, there is no sound in game. Actually I noticed that Blender uses only wrap_oal.dll library, but this would be a bit confusing.

I checked it on few different windows installations and it works for me.
