### ISSUE TITLE
STK enterprise is impossible

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2333]
The long jump in stk enterprise is impossible to do, the karts get immediately rescued when they are leaving the ramp before the long jump.

**Comment by MiroslavR** [comment]
You mean the booster ramp jump near the end of the track? I am unable to reproduce this with the latest revisions of stk-code and stk-data.

**Comment by cap44** [comment]
@Flakebi I cannot replicate that issue

**Comment by auriamg** [comment]
Cannot reproduce either. What version what OS, anything else relevant?

**Comment by Flakebi** [comment]
Ok, I can't reproduce too...
