### ISSUE TITLE
Missing screenshot/icons in in-game addons browser

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#2334]
I just checked all addons available in 0.9.1 RC1, and none have in-game screenshots or icon, for each addon you only get a question mark and some basic info about the download size and version:
![stk-addons](https://cloud.githubusercontent.com/assets/4701338/10273963/7203e39e-6b38-11e5-944c-1d214f06f7e9.jpg)

Looking at the addons website however, one can see that:
* all karts have at least an icon: http://addons.supertuxkart.net/addons.php?type=karts&name=python
* all tracks have a screenshot: http://addons.supertuxkart.net/addons.php?type=tracks&name=amazonian-journey

It would be very cool to at least be able to see those in the in-game addons manager.

Additionally, but this is more a guidelines issue: only two addons in the whole database have a description. All the others show with empty descriptions as in the screenshot above, and it would be very cool if it were fixed for 0.9.1.

**Comment by hiker** [comment]
The server was fixed recently (ticket 62 in stk-addons).
