### ISSUE TITLE
Display date in addons manager based on user locale

### ISSUE THREAD

**Issue by akien-mga** [supertuxkart/stk-code#2335]
In the addons manager, dates are displayed using the American format: MM/DD/YY, regardless of the system locale (at least, even though my locale is French and the rest of STK is properly translated).

![stk-addons2](https://cloud.githubusercontent.com/assets/4701338/10274012/0f3ff634-6b39-11e5-9baa-768d9d608146.jpg)

This format is quite hard to read for people accustomed to DD/MM/YY, especially since you can't be sure which format is used until you see a date corresponding to a day > 12, i.e. 04/14/15, which hints that the second number can't be MM :)

**Comment by auriamg** [comment]
Agreed, though we'll need to think about how to do it, C++ doesn't have built-in date formatting tools AFAIK unfortunately.

The method to change would be Addon::getDateAsString()

**Comment by auriamg** [comment]
Pushed possible fix to "TranslatableDateTime" branch. It's too late for 0.9.1, will merge for next release

**Comment by auriamg** [comment]
The branch has been merged into master, this should now be fixed
