### ISSUE TITLE
Randomly change colors (hue) for some objects

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2338]
To quote from http://forum.freegamedev.net/viewtopic.php?f=18&t=6532&p=66129#p66128

I feel that also could be helped with a shader that colorizes per channel. Saints Row 3 did it that way with a color mask, each channel being a color to mix (up to 3 pickable colors) and then these colors could be randomized or assigned by text and the shader would take care of the rest. It'll keep the texture requirements down and is probably the closest you can get to palettizing on modern hardware.

Ideally there would be a mask (probably in the alpha channel of the gloss map). The diffuse texture is just like a regular texture and the shader automatically shift hue randomly according to a range.

For instance:
Each tree model could have a slightly different green hue.
Each swimsuit in gran paradiso could have a different color
Hair color could be randomized
Etc

That would avoid to create 100 different model for each color
We should investigate to see if it's possible or not to do it.

**Comment by samuncle** [comment]
@Elderme I have no idea why I can't assign a ticket to you but I just quoted so you get a notification.

**Comment by Benau** [comment]
In https://github.com/supertuxkart/stk-code/tree/render_kart_driver_differently, it should be possible to change hue/saturation for specific item (even different parts in mesh)

Blue wilber
![2016-06-26 16-20-21](https://cloud.githubusercontent.com/assets/3252341/16361194/23c647d4-3b77-11e6-924d-c1b5f1ed0cd7.png)
"HOT" sara
![2016-06-26 16-21-11](https://cloud.githubusercontent.com/assets/3252341/16361197/324d81aa-3b77-11e6-8c51-ac30fcda066e.png)

To do that, in material.xml, add colorizable="true" for the texture which will be colorized.

**Comment by auriamg** [comment]
Looking at Benau's shader, I was wondering how efficient is it. Most notably, it's using "if" statements and from my limited shader knowledge I beleive that should be avoided. @deveee , @Elderme  is any of you knowledgeable enough about shaders to tell whether this might be innefficient?

**Comment by Benau** [comment]
Now i try to make my branch as efficient as possible, now we only need 1 float as parameter. Also I use a max() to adjust to saturation, so we can make a deeper blue/red without "colorizing the (almost) white part of texture too much".

Result:
![2016-06-27 13-14-20](https://cloud.githubusercontent.com/assets/3252341/16370070/3de857d2-3c2c-11e6-92a0-1e5cd521f17d.png)

**Comment by deveee** [comment]
@auriamg I was wondering about it too. Google said me that it's not that
big problem if you are using only uniform variables there. And hsv to rgb
conversion takes a time too. It's hard to say for me what will be faster.

Or maybe use two shaders: object_pass and colorized_object_pass or
something similar?

**Comment by Benau** [comment]
I have made some more improvements in my branch, so each mesh differs if its RenderInfo* is different when instanced rendering is used

So you play p World::getWorld()->getKart(Num)->getKartModel()->getRenderInfo()->setHue(New_Hue) in gdb and something like this will happen!

![2016-07-02 11-48-12](https://cloud.githubusercontent.com/assets/3252341/16538185/79b97cd6-400b-11e6-8487-d1dc6362fbb5.png)

By setting colorized_factor to 0, you can keep the texture original saturation with a new hue, so its original content is less affected

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/53374176ada2

add hue="x.x" after library object node should colorize them, with optional "colorization-mask" = picture, if not all area of texture will be colorized

result:
![screenshot](https://cloud.githubusercontent.com/assets/3252341/16848198/1ef041da-49e4-11e6-99fc-ef974cb07c23.jpg)

**Comment by auriamg** [comment]
I've had a chat with samuncle to clarify some things. what we'd need for the coloring shader is that the material would have a list of colors loaded from materials.xml, and each instance of objects using that material would pick one randomly

**Comment by Benau** [comment]
Try https://github.com/supertuxkart/stk-code/tree/fix_2338 and you should see rainbow-like beach girl (lol)

**Comment by Benau** [comment]
Branch merged
