### ISSUE TITLE
Make easter egg mode safer

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2342]
Atm. after modifications in the track, easter egg mode in zen garden is broken. Two eggs are impossible to collect, and others are now too hard to find.

Also when I was playing minigolf last time, I wasn't able to collect all eggs (not sure if this is a bug or they are hidden that well :P). Hacienda has been broken too before 0.9 release, but it has been fixed quickly.

I'm not sure if this is possible, but maybe try to check if a kart is able to collect the eggs? And if not, move the egg to random place in the track or at least write a warning to console?

**Comment by deveee** [comment]
Okay, only one egg  in zen garden was not possible to collect. It's fixed in svn.

But still, we can just modify the tree model in library and we will break it again. Some checks in code would be nice.

**Comment by hiker** [comment]
Any idea how to do this? We could try placing the kart to the closest driveline point, and let the ai steer towards the point, but this would only go along a more or less straight line :(

**Comment by Alayan-stk-2** [comment]
It is absolutely impossible to automate this with the AI, many eggs require tricks the AI can't be teached.

The only way is to manually make sure eggs are reachable when changing their location, or when doing major changes which may affect their reachability.

**Comment by deveee** [comment]
It should be possible to check if egg is inside solid object (if eg. tree model was modified). But it's probably not possible to check that someone made invisible wall somewhere and you can't collect the egg now. Anyway it's not that hard to check it manually before release, so maybe just close it as invalid?

**Comment by Alayan-stk-2** [comment]
The solid object check would be doable, but I expect that kind of issue to be a small minority of situations where an egg would become inaccessible, so probably not worth the effort to code.

Closing as invalid, then.
