### ISSUE TITLE
It's not possible to finish easter egg mode in mathclass

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2344]
@samuncle I'm creating a ticket because I don't know what you wanted to do.

Currently it's not possible to finish it because of this egg:
![zrzut ekranu z 2015-10-09 15 26 14](https://cloud.githubusercontent.com/assets/5108558/10395200/e16584fc-6e9b-11e5-8915-9a2882de9e35.png)

You added it recently in svn r16483. But this egg doesn't exist in the track in media repo. Version in stk-assets is newer than in stk-media? Or just this one file was accidentally changed?

**Comment by samuncle** [comment]
It should be correct in the last asset version (rev 16496). I added more rules to try to guide players.
