### ISSUE TITLE
Incorrect positionning of movables inside rotated library objects

### ISSUE THREAD

**Issue by CreativeForge** [supertuxkart/stk-code#2345]
Maybe a little bit difficult to explain, theres a test-case attached.

When replacing objects in a library node through the collision trigger, they appear not correctly rotated on the track.

I made a small test track (it's a battlemap named 'Test') and a simple library object (the ugly brick thing -> 'stklib_rotationBug_a'). I placed the linked object with a rotation of z:-90° on the track. When driving into it -> the "slivers" appear differntly rotated.

Get the files here:
https://app.box.com/s/4962er5voys9zx7f0ubuqht8h7u2okwh

**Comment by auriamg** [comment]
This is actually unrelated to scripting, this seems to be an incorrect handling of movables inside rotated library objects (tentive diagnostic : each movable in the rotated library object has the proper rotation but not the proper coordinate)

**Comment by auriamg** [comment]
Potential fix committed, I'm just not sure I understand what exactly is going on, should be investigated

**Comment by CreativeForge** [comment]
Looks fine to me. Is working well, tested with multiple library nodes.

**Comment by auriamg** [comment]
Closing as fix. I don't like not understanding why the fix works but oh well
