### ISSUE TITLE
"error: m_ip is a private member of TransportAddress" build failure

### ISSUE THREAD

**Issue by cap44** [supertuxkart/stk-code#2351]
build log from the updater script

remote: Compressing objects: 100% (43/43), done.
remote: Total 120 (delta 102), reused 95 (delta 77), pack-reused 0
Receiving objects: 100% (120/120), 57.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (102/102), completed with 53 local objects.
From https://github.com/supertuxkart/stk-code
   a615060..162bcce  master     -> origin/master
   53158cb..02517bc  0.9.1-rc1  -> origin/0.9.1-rc1
Updating a615060..162bcce
Fast-forward
 data/po/update_po_authors.py                         |  12 +++++-------
 src/network/client_network_manager.cpp               |   2 +-
 src/network/network_manager.cpp                      |   3 +--
 src/network/network_string.hpp                       |  11 ++++++++++-
 src/network/protocol_manager.cpp                     |   6 +++---
 src/network/protocols/client_lobby_room_protocol.cpp |  23 +++++++++++------------
 src/network/protocols/connect_to_peer.cpp            |  22 ++++++++++------------
 src/network/protocols/connect_to_server.cpp          |  36 ++++++++++++++++++++----------------
 src/network/protocols/controller_events_protocol.cpp |   4 ++--
 src/network/protocols/game_events_protocol.cpp       |   2 +-
 src/network/protocols/get_peer_address.cpp           |  13 +++++++++----
 src/network/protocols/get_public_address.cpp         |  16 +++++++---------
 src/network/protocols/kart_update_protocol.cpp       |   4 ++--
 src/network/protocols/quick_join_protocol.cpp        |  11 ++++++++---
 src/network/protocols/server_lobby_room_protocol.cpp |  72 ++++++++++++++++++++++++++++++++++++------------------------------------
 src/network/protocols/show_public_address.cpp        |   6 +++---
 src/network/protocols/start_game_protocol.cpp        |   2 +-
 src/network/protocols/start_server.cpp               |   6 +++---
 src/network/protocols/stop_server.cpp                |   6 +++---
 src/network/protocols/synchronization_protocol.cpp   |   4 ++--
 src/network/stk_host.cpp                             |  27 ++++++++++++---------------
 src/network/stk_peer.cpp                             |  24 ++++++++----------------
 src/network/stk_peer.hpp                             |   3 ++-
 src/network/types.hpp                                | 107 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------
 24 files changed, 252 insertions(+), 170 deletions(-)
Folder found: cmake-build. Building SuperTuxKart-git
/home/i5150pc/stk-bleeding/stk-code/cmake-build
-- Font tool deactivated, the font tool won't be built (only useful for developers)
-- Assets found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/i5150pc/stk-bleeding/stk-code
Building SuperTuxKart-git...
[  1%] Built target enet
[  2%] Built target bulletmath
[  5%] Built target bulletdynamics
[  5%] Built target glew
[ 20%] Built target bulletcollision
[ 23%] Built target wiiuse
[ 42%] Built target stkirrlicht
[ 46%] Built target angelscript
[ 47%] Built target font_tool
Scanning dependencies of target supertuxkart
[ 47%] Building CXX object CMakeFiles/supertuxkart.dir/src/race/history.cpp.o
[ 47%] Building CXX object CMakeFiles/supertuxkart.dir/src/utils/debug.cpp.o
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/race/race_manager.cpp.o
/home/i5150pc/stk-bleeding/stk-code/src/race/history.cpp:278:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
    if (!sscanf(s, "reverse: %c", &r) != 1)
        ^                             ~~
/home/i5150pc/stk-bleeding/stk-code/src/race/history.cpp:278:9: note: add parentheses after the '!' to evaluate the comparison first
    if (!sscanf(s, "reverse: %c", &r) != 1)
        ^
         (                                )
/home/i5150pc/stk-bleeding/stk-code/src/race/history.cpp:278:9: note: add parentheses around left hand side expression to silence this warning
    if (!sscanf(s, "reverse: %c", &r) != 1)
        ^
        (                            )
In file included from /home/i5150pc/stk-bleeding/stk-code/src/race/race_manager.cpp:44:
In file included from /home/i5150pc/stk-bleeding/stk-code/src/modes/three_strikes_battle.hpp:24:
In file included from /home/i5150pc/stk-bleeding/stk-code/src/tracks/track_object.hpp:27:
/home/i5150pc/stk-bleeding/stk-code/src/tracks/track_object_presentation.hpp:192:10: warning: 'TrackObjectPresentationLibraryNode::move' hides overloaded virtual function [-Woverloaded-virtual]
    void move(const core::vector3df& xyz, const core::vector3df& hpr,
         ^
/home/i5150pc/stk-bleeding/stk-code/src/tracks/track_object_presentation.hpp:155:18: note: hidden overloaded virtual function 'TrackObjectPresentationSceneNode::move' declared here: different number of parameters (4 vs 5)
    virtual void move(const core::vector3df& xyz, const core::vector3df& hpr,
                 ^
/home/i5150pc/stk-bleeding/stk-code/src/utils/debug.cpp:567:27: warning: unused variable 'console' [-Wunused-variable]
        ScriptingConsole* console = new ScriptingConsole();
                          ^
1 warning generated.
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/main_loop.cpp.o
1 warning generated.
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/main.cpp.o
1 warning generated.
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/slip_stream.cpp.o
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/lod_node.cpp.o
[ 48%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/referee.cpp.o
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.o
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/post_processing.cpp.o
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/skid_marks.cpp.o
/home/i5150pc/stk-bleeding/stk-code/src/graphics/post_processing.cpp:1234:11: warning: unused variable 'inv_height' [-Wunused-variable]
    float inv_height = 1.0f / in_fbo.getHeight();
          ^
/home/i5150pc/stk-bleeding/stk-code/src/graphics/post_processing.cpp:1233:11: warning: unused variable 'inv_width' [-Wunused-variable]
    float inv_width  = 1.0f / in_fbo.getWidth();
          ^
/home/i5150pc/stk-bleeding/stk-code/src/graphics/post_processing.cpp:1253:11: warning: unused variable 'inv_width' [-Wunused-variable]
    float inv_width = 1.0f / in_fbo.getWidth();
          ^
/home/i5150pc/stk-bleeding/stk-code/src/graphics/post_processing.cpp:1254:11: warning: unused variable 'inv_height' [-Wunused-variable]
    float inv_height = 1.0f / in_fbo.getHeight();
          ^
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/camera.cpp.o
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/network_world.cpp.o
4 warnings generated.
[ 49%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/event.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/network_string.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/game_setup.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocol.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocol_manager.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/client_network_manager.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/lobby_room_protocol.cpp.o
[ 50%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/kart_update_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/ping_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/controller_events_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/game_events_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/start_game_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/quick_join_protocol.cpp.o
[ 51%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/hide_public_address.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/client_lobby_room_protocol.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/get_public_address.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/get_peer_address.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/synchronization_protocol.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/connect_to_server.cpp.o
[ 52%] Building CXX object CMakeFiles/supertuxkart.dir/src/network/protocols/connect_to_peer.cpp.o
**/home/i5150pc/stk-bleeding/stk-code/src/network/protocols/connect_to_server.cpp:194:74: error: 'm_ip' is a private member of 'TransportAddress'
                                if (ntohl(sa->sin_addr.s_addr) == sender.m_ip) // this interface is ours**
                                                                         ^
**/home/i5150pc/stk-bleeding/stk-code/src/network/types.hpp:52:14: note: declared private here
    uint32_t m_ip;    //!< The IPv4 address**
             ^
**/home/i5150pc/stk-bleeding/stk-code/src/network/protocols/connect_to_server.cpp:195:44: error: 'm_ip' is a private member of 'TransportAddress'
                                    sender.m_ip = 0x7f000001; // 127.0.0.1**
                                           ^
**/home/i5150pc/stk-bleeding/stk-code/src/network/types.hpp:52:14: note: declared private here
    uint32_t m_ip;    //!< The IPv4 address**
             ^
2 errors generated. **
CMakeFiles/supertuxkart.dir/build.make:3614: recipe for target 'CMakeFiles/supertuxkart.dir/src/network/protocols/connect_to_server.cpp.o' failed
make[2]: *** [CMakeFiles/supertuxkart.dir/src/network/protocols/connect_to_server.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/supertuxkart.dir/all' failed
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by deveee** [comment]
Fixed by leyyin in this commit:
https://github.com/supertuxkart/stk-code/commit/8cfa2f925a083cf6dc599f19bcba4e51b9a5c810
