### ISSUE TITLE
Freetype include path not detected automatically on Mac OS X

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#2357]
For some reason, Freetype is not detected automatically on my Mac since the freetype changes.
In order to get it to compile, I had to specify -DFREETYPE_INCLUDE_DIRS=/opt/local/include/freetype2/

**Comment by auriamg** [comment]
STK on OSX uses frameworks, make sure to install the latest dependency pack

The CMake files could be modified to optionnally use a manually-installed freetype but the framework should always come first since that's what is used to package the game
