### ISSUE TITLE
Can't drift left 

### ISSUE THREAD

**Issue by adnidor** [supertuxkart/stk-code#2359]
I can't drive left while pressing the drift key. Pressing the drift key while driving left has no effect.

I tried multiple keyboard configurations and multiple OSes, the problem still persists

**Comment by auriamg** [comment]
Have you checked http://supertuxkart.sourceforge.net/FAQ#Some_keyboard_keys_do_not_work_when_pressed_simultaneously ? This is probably a case of limitations on your keyboard. Do you maybe have a gamepad?

**Comment by VOTProductions** [comment]
Unable to reproduce on Arch Linux. Holding down V and then holding down left works, as well as holding down left, and then holding down V (skidding).

Tested on a CM Storm Quickfire TK.

**Comment by deveee** [comment]
As auria said this is most probably keyboard limitation. I had this problem with some keyboards too, especially on laptops. But with other keyboards or other key bindings it works fine.

I'm marking it as works-for-me.
