### ISSUE TITLE
'Internet access is disabled' shown after re-enabling 'Connect to the Internet'

### ISSUE THREAD

**Issue by VOTProductions** [supertuxkart/stk-code#2361]
Minor GUI bug:
1. Start STK with Internet access disabled.
2. Try to create an online account - you will see that it asks you to enable internet access.
3. Tick 'Connect to the Internet'.
4. Try to create an online account - you will see 'Internet access is disabled', and yet it was enabled.

This happens on 0.9.1 as well as the latest Git.

There needs to be a check when creating an account, to see if internet access is enabled, and if it is, simply blank out the string. That would be a simple and effective way to fix this bug.

**Comment by auriamg** [comment]
I am unable to reproduce this issue, does it still happen?
