### ISSUE TITLE
version information for Arch linux is outdated on the Download page

### ISSUE THREAD

**Issue by nikin** [supertuxkart/stk-code#2362]
The version available from community is 0.9.1
```bash
#pacman -Ss supertuxkart
community/supertuxkart 0.9.1-1
    Kart racing game featuring Tux and his friends
```

**Comment by Arthur-D** [comment]
I'm fixing this, but as I'm currently adding torrent links which I have to wait to upload I'm waiting until later to save the page.

**Comment by Arthur-D** [comment]
Should be fixed.

**Comment by nado** [comment]
I made this issue about that… https://github.com/supertuxkart/stk-code/issues/2353
