### ISSUE TITLE
Almost impossible to get the big nitro at beginning of Hacienda

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2363]
At the very beginning of the track, there is a boost ramp but it sends us too high to get the nitro collectible. Could it be placed at a more adapted height ?

**Comment by brmbrmcar** [comment]
It is meant to be hard. But OK, I see your point.

**Comment by auriamg** [comment]
Do you mean the ramp inside the house? If so I agree it's a little too hard to reach, you can get it but need to slow down so much that you lose any advantage the nitro might give you

**Comment by nado** [comment]
Yup, this one, I think if we can place the nitro a bit higher it should be possible to get it without having to slow down.

**Comment by brmbrmcar** [comment]
Yes, but I guess with the nitro you can't crash so easily, so you have to see both sides.

**Comment by nado** [comment]
Crash ? What, you mean get in the wall after the ramp ? When you’re used to play, you dont crash so easily, but i never ever got the nitro without slowing down. I tried it once, then never again since you lose more speed getting the nitro than what you earn at full speed with the ramp.

Another friend played with me in multi, and after 1 race he said the same thing as me, I thought it isnt only from me and this nitro seems useless there.

**Comment by brmbrmcar** [comment]
Yes, but not all players are that good.

**Comment by nado** [comment]
But still, I dont see how the fact that you’d crash more often is a reason to give you less bonus.

**Comment by brmbrmcar** [comment]
Yes. It probably should be changed, but made into a small can.

**Comment by nado** [comment]
Sure, I dont really care the amount of nitro, it just bothered my friend and I about the usefulness of this item.
So probably a small higher nitro would be better.

**Comment by nado** [comment]
Any update ? I suppose this is far from top priority, but is it wanted by the team ?

**Comment by auriamg** [comment]
Yes, we are aware that a lot of our tracks could use improvements, but you need to understand that we only have one artist working part-time, so unfortunately there is no way we will be able to do all improvements we would like to

**Comment by Benau** [comment]
Not an issue since further tweaking in 02d3bd2c2bbc3695031daddb322b3d7322e9340f
