### ISSUE TITLE
Segfault on OS X 10.11.1

### ISSUE THREAD

**Issue by akospalfi** [supertuxkart/stk-code#2366]
Hi guys,

I just got a segfault with 0.9.1 on OSX 10.11.1. I was playing the game when suddenly the game got closed and a crash report has appeared..

This is the report:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

	Exception Type:        EXC_CRASH (SIGABRT)
	Exception Codes:       0x0000000000000000, 0x0000000000000000
	Exception Note:        EXC_CORPSE_NOTIFY

	Application Specific Information:
	abort() called
	*** error for object 0x7dc81b30: pointer being freed was not allocated
	 

	Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
	0   libsystem_kernel.dylib        	0x9db2862a __pthread_kill + 10
	1   libsystem_pthread.dylib       	0x9701e664 pthread_kill + 101
	2   libsystem_c.dylib             	0x9b8ed8c8 abort + 156
	3   libsystem_malloc.dylib        	0x9bd742a2 free + 433
	4   com.apple.audio.OpenAL        	0x00a80bc5 std::list<BufferInfo, std::allocator<BufferInfo> >::_M_erase(std::_List_iterator<BufferInfo>) + 57
	5   com.apple.audio.OpenAL        	0x00a80be9 std::list<BufferInfo, std::allocator<BufferInfo> >::erase(std::_List_iterator<BufferInfo>) + 27
	6   com.apple.audio.OpenAL        	0x00a7b97c BufferQueue::RemoveQueueEntryByIndex(OALSource*, unsigned long, bool) + 100
	7   com.apple.audio.OpenAL        	0x00a7b9f1 OALSource::FlushBufferQueue() + 61
	8   com.apple.audio.OpenAL        	0x00a7cc0b OALSource::~OALSource() + 67
	9   com.apple.audio.OpenAL        	0x00a765d0 OALContext::CleanUpDeadSourceList() + 90
	10  com.apple.audio.OpenAL        	0x00a7679a OALContext::AddSource(unsigned int) + 98
	11  com.apple.audio.OpenAL        	0x00a6c9a9 alGenSources + 151
	12  net.sourceforge.supertuxkart  	0x0007179f SFXOpenAL::init() + 47
	13  net.sourceforge.supertuxkart  	0x0006f7ed SFXManager::createSoundSource(SFXBuffer*, bool, bool) + 109
	14  net.sourceforge.supertuxkart  	0x0006f8d0 SFXManager::createSoundSource(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 80
	15  net.sourceforge.supertuxkart  	0x001fa93e Powerup::set(PowerupManager::PowerupType, int) + 206
	16  net.sourceforge.supertuxkart  	0x001fb68e Powerup::hitBonusBox(Item const&, int) + 270
	17  net.sourceforge.supertuxkart  	0x00215514 Kart::collectedItem(Item*, int) + 84
	18  net.sourceforge.supertuxkart  	0x001f8596 ItemManager::checkItemHit(AbstractKart*) + 406
	19  net.sourceforge.supertuxkart  	0x0021628e Kart::update(float) + 2286
	20  net.sourceforge.supertuxkart  	0x0024c12e World::update(float) + 414
	21  net.sourceforge.supertuxkart  	0x0023e408 LinearWorld::update(float) + 40
	22  net.sourceforge.supertuxkart  	0x0024bbee World::updateWorld(float) + 126
	23  net.sourceforge.supertuxkart  	0x00237179 MainLoop::updateRace(float) + 169
	24  net.sourceforge.supertuxkart  	0x0023729d MainLoop::run() + 253
	25  net.sourceforge.supertuxkart  	0x00235edc main + 5132
	26  libdyld.dylib                 	0x9e6c16ad start + 1

	Thread 1:: Dispatch queue: com.apple.libdispatch-manager
	0   libsystem_kernel.dylib        	0x9db298b2 kevent_qos + 10
	1   libdispatch.dylib             	0x9ec1e792 _dispatch_mgr_invoke + 234
	2   libdispatch.dylib             	0x9ec1e366 _dispatch_mgr_thread + 52

	Thread 2:
	0   libsystem_kernel.dylib        	0x9db284a2 __psynch_cvwait + 10
	1   libsystem_pthread.dylib       	0x9701c549 _pthread_cond_wait + 757
	2   libsystem_pthread.dylib       	0x9701e287 pthread_cond_wait$UNIX2003 + 71
	3   net.sourceforge.supertuxkart  	0x00274dec Online::RequestManager::mainLoop(void*) + 140
	4   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	5   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	6   libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 3:: com.apple.audio.IOThread.client
	0   libsystem_kernel.dylib        	0x9db2207a mach_msg_trap + 10
	1   libsystem_kernel.dylib        	0x9db21464 mach_msg + 68
	2   com.apple.audio.CoreAudio     	0x96ad2b44 HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned long, unsigned long, mach_msg_header_t*, bool, unsigned int) + 140
	3   com.apple.audio.CoreAudio     	0x96acbd52 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 72
	4   com.apple.audio.CoreAudio     	0x96aca1c0 HALC_ProxyIOContext::IOWorkLoop() + 1392
	5   com.apple.audio.CoreAudio     	0x96ac9b34 HALC_ProxyIOContext::IOThreadEntry(void*) + 156
	6   com.apple.audio.CoreAudio     	0x96ad5c8c ___ZN19HALC_ProxyIOContextC2Emj_block_invoke + 20
	7   com.apple.audio.CoreAudio     	0x96ac9a59 HALB_IOThread::Entry(void*) + 71
	8   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	9   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	10  libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 4:
	0   libsystem_kernel.dylib        	0x9db28886 __semwait_signal + 10
	1   libsystem_c.dylib             	0x9b90d632 nanosleep$UNIX2003 + 218
	2   libsystem_c.dylib             	0x9b90d4de usleep$UNIX2003 + 60
	3   net.sourceforge.supertuxkart  	0x0006e2c5 SFXManager::mainLoop(void*) + 885
	4   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	5   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	6   libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 5:
	0   libsystem_kernel.dylib        	0x9db287de __select + 10
	1   net.sourceforge.supertuxkart  	0x004176b1 enet_socket_wait + 257
	2   net.sourceforge.supertuxkart  	0x00416905 enet_host_service + 6453
	3   net.sourceforge.supertuxkart  	0x0026b164 STKHost::receive_data(void*) + 100
	4   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	5   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	6   libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 6:
	0   libsystem_kernel.dylib        	0x9db28886 __semwait_signal + 10
	1   libsystem_c.dylib             	0x9b90d632 nanosleep$UNIX2003 + 218
	2   libsystem_c.dylib             	0x9b90d4de usleep$UNIX2003 + 60
	3   net.sourceforge.supertuxkart  	0x00252f94 protocolManagerAsynchronousUpdate(void*) + 52
	4   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	5   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	6   libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 7:: com.apple.NSEventThread
	0   libsystem_kernel.dylib        	0x9db2207a mach_msg_trap + 10
	1   libsystem_kernel.dylib        	0x9db21464 mach_msg + 68
	2   com.apple.CoreFoundation      	0x977b3246 __CFRunLoopServiceMachPort + 214
	3   com.apple.CoreFoundation      	0x977b2651 __CFRunLoopRun + 1521
	4   com.apple.CoreFoundation      	0x977b1df6 CFRunLoopRunSpecific + 390
	5   com.apple.CoreFoundation      	0x977b1c5b CFRunLoopRunInMode + 123
	6   com.apple.AppKit              	0x9aab1fa2 _NSEventThread + 291
	7   libsystem_pthread.dylib       	0x9701b794 _pthread_body + 138
	8   libsystem_pthread.dylib       	0x9701b70a _pthread_start + 155
	9   libsystem_pthread.dylib       	0x97018fa6 thread_start + 34

	Thread 0 crashed with X86 Thread State (32-bit):
	  eax: 0x00000000  ebx: 0x7dc81b30  ecx: 0xbffb40ac  edx: 0x00000000
	  edi: 0xa398b000  esi: 0x00000006  ebp: 0xbffb40c8  esp: 0xbffb40ac
	   ss: 0x00000023  efl: 0x00000206  eip: 0x9db2862a   cs: 0x0000000b
	   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
	  cr2: 0xa41e4a20
	  
	Logical CPU:     0
	Error Code:      0x00080148
	Trap Number:     132

**Comment by auriamg** [comment]
Hi, please let us know if this is something that happens repeatedly or if it happened only once. This seems to be a crash inside OpenAL, that may prove quite tricky to diagnose and fix :/

**Comment by qwertychouskie** [comment]
@akospalfi never responded, can this be closed?

**Comment by akospalfi** [comment]
Really sorry, I totally forgot it. I tried to repro the problem several times, but it never happened again. I think the issue can be closed.

**Comment by qwertychouskie** [comment]
It's OK, no big deal, just old issue crawling.

**Comment by qwertychouskie** [comment]
I think you forgot to actually click the "Close issue" button though... :)

**Comment by akospalfi** [comment]
Oh, (now really) closing the issue.. :)
