### ISSUE TITLE
Git stk doesn't work for me

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2369]
Output (with debug build):
........
[warn   ] GLWrap: OpenGL debug callback - API
[warn   ] GLWrap:     Error type : ERROR
[warn   ] GLWrap:     Severity : HIGH
[warn   ] GLWrap:     Message : GL_INVALID_OPERATION in glUniform(program not linked)
.....
(release build)
[info   ] shader: Compiling shader : coloredquad.vert
[info   ] shader: Compiling shader : coloredquad.frag
[error  ] GLWrap: Error in shader coloredquad.frag
[error  ] GLWrap: 0:3(1): error: #extension directive is not allowed in the middle of a shader

[error  ] GLWrapp: Error when linking these shaders :
[error  ] shader: coloredquad.vert
[error  ] shader: coloredquad.frag
[error  ] GLWrapp: error: linking with uncompiled shader
.............
It happens when the first loading screen is displayed.

Revert Added default precision qualifier in fragment shaders commit worked for me.....

System: Linux + gallium radeonsi driver (R7 250)

````
[info   ] IrrDriver: OpenGL version: 4.1
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Gallium 0.4 on AMD OLAND (DRM 2.43.0, LLVM 3.7.0)
[info   ] IrrDriver: OpenGL version string: 4.1 (Core Profile) Mesa 11.0.2
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Multi Draw Indirect Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] irr_driver: GLSL supported.

**Comment by leyyin** [comment]
I get the same problem on my Kubuntu 14.04 machine (intel 4000 GPU).
```
[warn   ] GLWrap: OpenGL debug callback - API
[warn   ] GLWrap:     Error type : ERROR
[warn   ] GLWrap:     Severity : HIGH
[warn   ] GLWrap:     Message : GL_INVALID_OPERATION in glUseProgram(program 64 not linked)
[warn   ] GLWrap: OpenGL debug callback - API
[warn   ] GLWrap:     Error type : ERROR
[warn   ] GLWrap:     Severity : HIGH
[warn   ] GLWrap:     Message : GL_INVALID_OPERATION in glUniform(program not linked)
```
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.9
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.5.9
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

**Comment by tomreyn** [comment]
Works with Mesa 11.0.4 (xorg-edgers driver backports) on Ubuntu 14.04, Radeon HD 4670.

Git revision: 08e3a9ea13eb2c5aa7612968b64d6e851fa58c05

Release build type.

```
[info   ] IrrDriver: OpenGL version: 3.1
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Gallium 0.4 on AMD RV730 (DRM 2.36.0, LLVM 3.6.0)
[info   ] IrrDriver: OpenGL version string: 3.1 (Core Profile) Mesa 11.0.4
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] irr_driver: GLSL supported.
```

**Comment by deveee** [comment]
I reverted it for now because it causes issues with mesa. I personally had this issue with intel HD4000 and mesa 11.0.2.

Maybe it just needs to be declared in other place.

**Comment by Elderme** [comment]
I'm sorry, I've broken shader compilation with your drivers.

I think precision qualifiers have to be defined after extensions activation. Can you test this branch?
https://github.com/Elderme/stk-code/tree/issue_2369

**Comment by deveee** [comment]
It looks that it's hard to write something on graphics side that works with every driver ;)

Now it works for me on intel with mesa and with proprietary nvidia drivers.

**Comment by Benau** [comment]
@Elderme Yep, your branch works!

**Comment by nado** [comment]
No error with mesa gallium.

**Comment by auriamg** [comment]
Great, maybe you can make a pull request @Elderme ? Let's hope this time it works for everyone

**Comment by Elderme** [comment]
Yes, I hope I will not break anything and maybe solve asterix issue.
