### ISSUE TITLE
Lazy loading char for fallback font on mingw seems to fail

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2370]
Using offical mingw-deps with 32bit mingw-5.2.0, the following screen is displayed without chinese word on loading:

![default](https://cloud.githubusercontent.com/assets/3252341/10876073/41caf102-8174-11e5-8d2c-d31f2c94af11.jpg)

(this happen to all characters than use fallback font to display title too)

With further debug, seems that mingw is having problem with this: 
GUIEngine::getFont()->getSpriteNoFromChar(p) == WrongCharacter

seems that mingw will get a wrong sprite number from the bold font, but it's too difficult to explain.

Anyway I fixed it with https://github.com/Benau/stk-code/commit/d851e0661207f45bf56b7b3a7e028721bb5c9ec5, I also remove the WrongCharacter define as it's useless anyway.

@deveee can you confirm if that happens to your mingw setup too?

**Comment by deveee** [comment]
It works for me with 32-bit mingw 5.1 and with 64-bit mingw 4.9.2. I don't have installed version 5.2 atm. I checked it with chinese traditional and chinese simplified and in both cases I see some characters on loading screen.

But your patch works for me too.

In dependencies for 32-bit mingw I just copied files from visual studio dependencies. This is the same library as in official VS build. The 64-bit version I compiled myself using mingw.

Btw. do you need libpng and zlib support enabled in freetype library? As I see freetype library is compiled with zlib support:
```
deve@deve:/home/Dokumenty/programowanie/supertuxkart/supertuxkart-git/dependencies/dll$ objdump -x freetype6.dll | grep "DLL Name"
	DLL Name: zlib1.dll
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
```

I assume that zlib is useless for libfreetype if we don't use libpng and I compiled 64-bit libfreetype without zlib support. Correct me if I'm wrong.

**Comment by Benau** [comment]
Then maybe it's problem with 5.2 (buggy gcc with mingw 5.2??),  I think I can leave that patch a while..

IIRC, freetype will use its internal copies of zlib if no shared lib is used. Also the freetype lib in offical 32bit one is from gnu32win, which is 2.3.5, don't know if it's a good idea to have different version with different platfrom...

I can provide a freetype 2.6.1 +harfbuzz 1.0.6 depending-each-other 32bit dlls too if you like, which my harfbuzz branch use.

**Comment by Benau** [comment]
I use the same detect new character method as Benau@d851e06 in #2374, tested fully in msvc and mingw 5.2, they all work fine

if #2374 is merged you can close this issue too

**Comment by auriamg** [comment]
#2374 was merged so closing this issue as fixed
