### ISSUE TITLE
Wilber is just black

### ISSUE THREAD

**Issue by Jehan** [supertuxkart/stk-code#2376]
Hi,

The Wilber character is just full black. It seems to be the only character with such a problem. Maybe a texture issue?

![screenshot from 2015-11-09 12-35-55](https://cloud.githubusercontent.com/assets/794997/11032814/c9ea6d00-86de-11e5-9660-317e2b3a6681.png)

**Comment by auriamg** [comment]
Hi, this is a known issue, please see issue #1943
