### ISSUE TITLE
Invisible boxes, bananas and karts. After upgrade.

### ISSUE THREAD

**Issue by stas730** [supertuxkart/stk-code#2384]
[SORRY FOR BAD ENGLISH. I PLAYING RUSSIAN VERSION]
I installed latest version from PPA. Before upgrade I see object on all map.
I see this message: "Your video driver are outdated. Please, update".
I DON'T have videocard. $(lspci | grep -i VGA) output: 00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 09).
I'm not a programmer. Need fix. Or downgrade to 0.8.1-2 working version?

**Comment by Benau** [comment]
VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 09) is a "onboard" videocard!!!!!!

seems that u are using i915..... (can u display lsmod?)

and this driver may not support opengl3.... (which 0.9.x stk requires) sorry about that.....

**Comment by auriamg** [comment]
What is your version of mesa? On Linux, upgrading to a newer mesa often helps

Note that you can still try to play the game, it might work - though a few glitches may occur

**Comment by stas730** [comment]
$(lsmod)
Module                  Size  Used by
pci_stub               12550  1 
vboxpci                22959  0 
vboxnetadp             25636  0 
vboxnetflt             27518  0 
vboxdrv               332607  3 vboxnetadp,vboxnetflt,vboxpci
ctr                    12905  2 
ccm                    17496  2 
ib_iser                46305  0 
rdma_cm                42264  1 ib_iser
iw_cm                  35447  1 rdma_cm
ib_cm                  41612  1 rdma_cm
ib_sa                  24846  2 rdma_cm,ib_cm
ib_mad                 41997  2 ib_cm,ib_sa
ib_core                71296  6 rdma_cm,ib_cm,ib_sa,iw_cm,ib_mad,ib_iser
ib_addr                14387  2 rdma_cm,ib_core
iscsi_tcp              17989  0 
libiscsi_tcp           20301  1 iscsi_tcp
libiscsi               47036  3 libiscsi_tcp,iscsi_tcp,ib_iser
scsi_transport_iscsi    85826  4 iscsi_tcp,ib_iser,libiscsi
ip6t_REJECT            12813  1 
xt_hl                  12465  6 
ip6t_rt                13259  3 
nf_conntrack_ipv6      14318  8 
nf_defrag_ipv6         26163  1 nf_conntrack_ipv6
ipt_REJECT             12485  1 
xt_LOG                 17446  10 
xt_limit               12541  13 
xt_tcpudp              12756  18 
xt_addrtype            12563  4 
nf_conntrack_ipv4      14318  8 
nf_defrag_ipv4         12649  1 nf_conntrack_ipv4
xt_conntrack           12664  16 
ip6table_filter        12711  1 
ip6_tables             17820  1 ip6table_filter
nf_conntrack_netbios_ns    12585  0 
nf_conntrack_broadcast    12541  1 nf_conntrack_netbios_ns
nf_nat_ftp             12645  0 
nf_nat                 21038  1 nf_nat_ftp
nf_conntrack_ftp       14056  1 nf_nat_ftp
arc4                   12536  2 
uvcvideo               71465  0 
videobuf2_vmalloc      13048  1 uvcvideo
nf_conntrack           87794  8 nf_nat_ftp,nf_conntrack_netbios_ns,nf_nat,xt_conntrack,nf_conntrack_broadcast,nf_conntrack_ftp,nf_conntrack_ipv4,nf_conntrack_ipv6
iptable_filter         12706  1 
ath9k                 122222  0 
ip_tables              17988  1 iptable_filter
videobuf2_memops       13170  1 videobuf2_vmalloc
bnep                   18895  2 
ath9k_common           24878  1 ath9k
x_tables               22067  13 ip6table_filter,xt_hl,ip_tables,xt_tcpudp,xt_limit,xt_conntrack,xt_LOG,iptable_filter,ip6t_rt,ipt_REJECT,ip6_tables,xt_addrtype,ip6t_REJECT
videobuf2_core         48344  1 uvcvideo
v4l2_common            15132  1 videobuf2_core
rfcomm                 58045  0 
samsung_backlight      13725  0 
ath9k_hw              430710  2 ath9k_common,ath9k
videodev              131265  3 uvcvideo,v4l2_common,videobuf2_core
bluetooth             391253  10 bnep,rfcomm
media                  20899  2 uvcvideo,videodev
snd_hda_codec_realtek    70475  1 
ath                    24182  3 ath9k_common,ath9k,ath9k_hw
mac80211              559100  1 ath9k
6lowpan_iphc           18262  1 bluetooth
snd_hda_codec_generic    62931  1 snd_hda_codec_realtek
snd_hda_intel          29285  3 
dm_multipath           22373  0 
snd_hda_controller     29252  1 snd_hda_intel
cfg80211              418839  4 ath,ath9k_common,ath9k,mac80211
snd_hda_codec         120371  4 snd_hda_codec_realtek,snd_hda_codec_generic,snd_hda_intel,snd_hda_controller
snd_hwdep              13272  1 snd_hda_codec
snd_pcm                87194  3 snd_hda_codec,snd_hda_intel,snd_hda_controller
snd_seq_midi           13324  0 
snd_seq_midi_event     14475  1 snd_seq_midi
joydev                 17113  0 
snd_rawmidi            25722  1 snd_seq_midi
scsi_dh                14458  1 dm_multipath
coretemp               13201  0 
snd_seq                56592  2 snd_seq_midi_event,snd_seq_midi
serio_raw              13251  0 
snd_seq_device         14137  3 snd_seq,snd_rawmidi,snd_seq_midi
snd_timer              28648  2 snd_pcm,snd_seq
lpc_ich                16877  0 
snd                    66670  16 snd_hda_codec_realtek,snd_hwdep,snd_timer,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_seq_device
soundcore              14599  2 snd,snd_hda_codec
shpchp                 32143  0 
mac_hid                13059  0 
nfsd                  243348  2 
auth_rpcgss            48978  1 nfsd
nfs_acl                12733  1 nfsd
nfs                   206050  0 
parport_pc             32021  0 
ppdev                  17391  0 
lockd                  78518  2 nfs,nfsd
lp                     13299  0 
sunrpc                252074  6 nfs,nfsd,auth_rpcgss,lockd,nfs_acl
fscache                56756  1 nfs
parport                40836  3 lp,ppdev,parport_pc
binfmt_misc            13140  1 
dm_mirror              21756  0 
dm_region_hash         20121  1 dm_mirror
dm_log                 18072  2 dm_region_hash,dm_mirror
hid_generic            12503  0 
usbhid                 47035  0 
hid                    95946  2 hid_generic,usbhid
psmouse                91277  0 
i915                  808682  3 
ahci                   25622  2 
libahci                26970  1 ahci
sky2                   52961  0 
i2c_algo_bit           13197  1 i915
drm_kms_helper         55007  1 i915
video                  19475  1 i915
drm                   255469  5 i915,drm_kms_helper

**Comment by deveee** [comment]
This is most probably gen4 graphics card and it supports up to OpenGL 2.1 on linux and 2.0 on windows.

I suggest something totally different (but for your own risk :P). Downgrade mesa drivers to the version 7.11.2 because it is 2x faster for these graphics cards than mesa 10. I have intel i965gm (gen4 too) in one laptop and I see that huge difference.

You probably won't be able to run current STK version, but the version 0.8.1 will work faster for you.

And I'm closing this ticket because we officially support only graphics cards with OpenGL 3.x and newer.
