### ISSUE TITLE
Missing kart models

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2387]
At least the recently added karts (amanda, gavroche) are missing in the media repo!
(Marked as major since have have already lost .blend files in the past)

**Comment by CreativeForge** [comment]
All files of these two karts are aviable since January 2015
https://app.box.com/s/7gr5lvholccs28qii66a216hnimsq93i
https://app.box.com/s/hdli8gq62v2bwbs2790zsyf5pvrkbgsm

I'm myself not able toupdate the repo.

**Comment by auriamg** [comment]
I've added the files to the media repo, thanks!
