### ISSUE TITLE
Battle AI improvements

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2388]
I have noticed a few minor things that could be improved with the (upcoming) battle AI:

- [x] The AI can easily get stuck, and hit the same object over and over again. It should somehow detect that it is stuck, and then perhaps trigger a 'reverse and turn' sequence for a few frame, to get away from the obstacle.
- [x] I think the Ai tried to hit me with a swatter a couple of times, but without success. I think that was because the AI hit me straight on, so it was too far away to trigger the swatter. Then we are pushed away from each other, and it repeated (though sooner or later the AI was somehow on the side and did hit me).
- [x] The AI reverse VERY rapidly. I am aware that karts will be faster in reverse (at least faster accelerate, not faster top speed), though it appeared(visually/subjectively) that the AI is faster than a player kart reversing. 
- [x] Not entirely related to AI, but with a swatter a kart can be hit more than once. Perhaps the invulnerability period from racing should be used? Or trigger a rescue (i.e. new start position) after a hit??

**Comment by hiker** [comment]
I could reproduce the swatter problems: the swatter animation is started when the kart gets close enough, but before the animation is finished (and the actual hit happens), the collision occurs, which can push the target kart out of swatter range (in my case I did not accelerate the target kart at all, so it was just pushed away in a frontal collision).
I added the following line to BattleAI::update:

+    m_kart->setPowerup(PowerupManager::POWERUP_SWATTER, 1);

Not sure how to fix this best - don't push more if one of the karts in a collision has a swatter? Mark kart as going to be hit when the animation starts (i.e. hits when animation starts, not when it finishes)? 

I also noticed that (at least once or twice) my kart was squashed after being hit with the swatter. We probably don't want that.

**Comment by Benau** [comment]
I think I understand the problem now:

Seems that you want AIs to kit kart with swatter without crashing it, otherwise it will bounce off.
To do that I think I can change the target point left/right a bit...

Is that correct?

**Comment by Benau** [comment]
(To have better result, use this stadium navmesh to test if wanted)
http://pastebin.com/nDUM5Ev7

https://github.com/supertuxkart/stk-code/compare/master...supertuxkart:battleAI?expand=1

I improved a lot for 1 and 3, now AI can almost get unstuck (not always detect correctly)

For u-turn reverse issue, now they behave like human players, ie you can do the same like AIs, comment and test welcome!

For swatter issue, I think I can change the target point by consider the angle...

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/ba706f4476a44fd6ad9b4383973119ad9f5b7b0c

Now AI should make less collision with karts when using swatter

**Comment by hiker** [comment]
I think it would be better if using the swatter in a front on collision would work (and not avoiding the front on collision). Racing towards an opponent with the swatter ready would seem more intuitive than trying to aim to the side of a kart. What do you think?

**Comment by hiker** [comment]
Re swatter, here a suggested solution:
- [ ] Make the swatter disappear after one hit
- [ ] Detect a hit with a kart at the time the swatter animation is triggered, i.e. before a collision happens that might push the kart away

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/140a229f711317e811b8b3c570eec5f979ce5b09

Don't know if correct fix....

**Comment by Benau** [comment]
@hiker can you confirm the swatter work for you?

**Comment by hiker** [comment]
Looking good now, thanks!@
