### ISSUE TITLE
Incomplete track documentation

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2390]
http://supertuxkart.sourceforge.net/Track_Maker's_Guide#Interaction is empty, and thus I don't know how to make an object ignore collisions (drive through) without getting ignored by the exporter.

**Comment by qwertychouskie** [comment]
Can probably be closed with the new docs from @MTres19 .

**Comment by auriamg** [comment]
Closing since the documentation has indeed been improved a lot
