### ISSUE TITLE
Old Mine waterfalls not animating

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2392]
When saying waterfalls, I am thinking of these (and also a couple other places in the track):
![mines-waterfall](https://cloud.githubusercontent.com/assets/5515261/11616295/940e0440-9c77-11e5-90bb-6e70865eb4ab.jpg)

When checking the blend file, the texture is set to animate 'mine_water_alpha.png' which exists. Animation Y speed is set to 0.5, which should be correct. However upon investigating the resulting scene.xml file, I found there are two lines referencing this texture. One at line 23, reading
```
<animated-texture name="mine_water_alpha.png" dy="-0.5000" />
```
and another at line 447 or so (made a small change which added a line)
```
<animated-texture name="mine_water_alpha.png" dy="0.5000" />
```

Trying to debug further, I removed the minus in the first line, so they should be consistent and not animate in the opposite direction, possibly cancelling each other out. This did not have any visible effect in the track, so I tried removing the entire first line. Surprisingly, this did not appear to help either, so now I'm stuck and I'm not sure how to debug further, and I create this ticket to try getting help from someone who might.

**Comment by auriamg** [comment]
Found out why : The name of the texture that should be animated is "mine_water_reset.png", NOT mine_water_alpha.png :)
