### ISSUE TITLE
No shadows nor global illumination

### ISSUE THREAD

**Issue by Elinvention** [supertuxkart/stk-code#2397]
In settings I can't turn on shadows and global illumination (they are greyed out).

Graphics card is AMD Radeon R7 370 using Mesa.

glxinfo | grep OpenGL:

```
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD PITCAIRN (DRM 2.42.0, LLVM 3.7.0)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.0.6
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

Terminal output:

```
[warn ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


```

**Comment by auriamg** [comment]
It is related to file data/graphical_restrictions.xml, many features on gallium are restricted to some versions. I version the version of gallium is incorrectly detected

Can you try removing those lines in graphical_restrictrions.xml ?

```
  <card contains="Gallium"        os="linux"    version="<10.3"    disable="BufferStorage"/>
  <card contains="Gallium"        os="linux"    version="<10.3"    disable="DriverRecentEnough"/>
  <card contains="Gallium"        os="linux"    version="<10.6"    disable="GeometryShader4"/>
  <card contains="Gallium"        os="linux"                       disable="TextureCompressionS3TC"/>
```

**Comment by deveee** [comment]
These graphics restrictions have effect only for older mesa versions. Current mesa supports OpenGL 4 now, so maybe it could work after some tweaks. Now we request OpenGL 4.3 context, and the driver still can't create it (the warning ```X Error: GLXBadFBConfig```), so it fallbacks to context 3.3. But atm. I don't know which precisely extensions we need for proper working and if they are available in mesa or not.

**Comment by deveee** [comment]
We require GL_ARB_geometry_shader4 for shadows and global illumination and AFAIK this extension is unfortunately not available in mesa yet. You can look at the log to confirm it. If this extension is available, there should be a line:
```
[info   ] GLDriver: ARB Geometry Shader 4 Present
```

**Comment by Elinvention** [comment]
Indeed that line is not present. So let's hope someone implements that extension soon... Thank you.

**Comment by lightonflux** [comment]
The tracks using the new engine are super dark for me in 0.9.1 can this be related to global illumination? (Intel HD4000)

**Comment by deveee** [comment]
@lightonflux if you use intel graphics card on linux, it may be this bug:
https://github.com/supertuxkart/stk-code/issues/2190

It should work with current git version of STK. The fix/workaround is 
also applied in debian testing and jessie-backports packages.

W dniu 06.01.2016 o 13:36, lightonflux pisze:

**Comment by lightonflux** [comment]
That was it. Works flawelessly with the debian packages.

**Comment by auriamg** [comment]
Thanks, closing this issue

**Comment by lightonflux** [comment]
@auriamg I meant the darkness on intel, not the initial problems with feature detection described by @Elinvention .

**Comment by auriamg** [comment]
Oh ok

**Comment by Elinvention** [comment]
Well, in the end, this doesn't seem to be STK's fault but a missing feature from Mesa. As far as I'm concerned, there is no problem with feature detection as removing those lines from data/graphical_restrictions.xml didn't change anything at all.

I found this commit: http://patchwork.freedesktop.org/patch/65980/

>Since all drivers support OpenGL 3.2 geometry shaders,
>there is no reason to keep the ARB_geometry_shader4.

I know nothing of OpenGL, but does this mean we should use different extensions to use Mesa?

**Comment by deveee** [comment]
I saw this commit. It's also written in mesa sources in one place. But
intel added it recently to their drivers on windows, so there is a chance
that they will add it to mesa too. We should look if there is relatively
easy way to make shadows working on mesa using different extension.

**Comment by deveee** [comment]
AFAIK they indeed don't want to implement ARB_geometry_shader4 in mesa. Basically geometry shaders are available in core OpenGL 3.2 and offer the same functionality, so they have no intentions to do it.

This affects quite a lot of people. I mean all intel graphics cards on linux (recent models should be powerful enough to play STK with shadows) and open-source AMD drivers (which offer now quite good performance and OpenGL 4.x support, so more people will use it).

I think that we should modify it to use core OpenGL 3.2 functions (or at least fallback to it) instead of ARB_geometry_shader4 extension.

Does someone know why this one particular extension has been used?

**Comment by Elinvention** [comment]
:+1: to add support for Mesa.

**Comment by nado** [comment]
You mean core OpenGL 3.2 ? Not sure of what you mean.

**Comment by deveee** [comment]
It should be fixed in this commit: https://github.com/supertuxkart/stk-code/commit/edfc7d285c6d14460ebbb59dc937e69574a049b3

You need at least mesa 11.2 to make it working.

I checked it with intel, nouveau and software rendering. I hope that it will work with radeon drivers either.

**Comment by deveee** [comment]
I disabled all extensions that has been added since mesa 10.3 by setting:
```
export MESA_EXTENSION_OVERRIDE="-GL_ARB_arrays_of_arrays -GL_ARB_clip_control  -GL_ARB_compute_shader  -GL_ARB_direct_state_access  -GL_ARB_fragment_layer_viewport  -GL_ARB_framebuffer_no_attachments  -GL_ARB_get_texture_sub_image  -GL_ARB_pipeline_statistics_query  -GL_ARB_program_interface_query  -GL_ARB_shader_clock  -GL_ARB_shader_draw_parameters  -GL_ARB_shader_image_load_store  -GL_ARB_shader_image_size  -GL_ARB_shader_storage_buffer_object  -GL_ARB_shader_subroutine  -GL_ARB_shader_texture_image_samples  -GL_ARB_tessellation_shader  -GL_ARB_texture_barrier  -GL_EXT_polygon_offset_clamp  -GL_EXT_shader_samples_identical  -GL_KHR_context_flush_control  -GL_NV_texture_barrier"
```
to make sure that it wasn't a problem with some missing extensions. And it still works fine. So it was most probably a bug in mesa that it was crashing in older versions.

@Elinvention are you able to check current git STK on your radeon graphics card?

**Comment by Elinvention** [comment]
Yes, I confirm that this bug is fixed on STK git. Now I can enable both global illumination and shadows.

Thank you very much for your work!
