### ISSUE TITLE
Xiph.org graphics in media preferences

### ISSUE THREAD

**Issue by GreenLunar** [supertuxkart/stk-code#2398]
Since I do not know whether another cart with another fish (we already have the OpenBSD fish) is a good idea, I propose to feature the Xiph.org Foundation fish and parrot in Audio and Video preferences, which should be easier than modeling a new character.

| name | for | image |
| --- | --- | --- |
| Xiph.org | main | http://xiph.org/images/logos/fish_xiph_org.png |
| Vorbis | music | http://www.vorbis.com/images/logos/vorbisdotcom.png |
| Theora | video | http://theora.org/images/logos/fish_theora_org.png |
| Speex | sound | http://www.speex.org/images/logos/parrot_speex_org-3.png |

ping @xiph

**Comment by GreenLunar** [comment]
ping @xiph

**Comment by auriamg** [comment]
Well this is very late, but github is not the right place for kart suggestions. Github is more for bugs and programming tasks, suggestions are better suited for the forum
