### ISSUE TITLE
Problems with up/down/left/right keys on Thinkpad tablets (x60t/x61t)

### ISSUE THREAD

**Issue by karbrueggen** [supertuxkart/stk-code#2399]
Supertuxkart:
[info   ] main: ==============================
[info   ] main: SuperTuxKart, 0.8.1.
[info   ] main: Irrlicht version 1.8.0 (1.8.0)
[info   ] main: ==============================
[info   ] irr_driver: GLSL supported.

My machine:
Linux stacy 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

loaded modules:
http://sprunge.us/eNRE

detected input devices (input.xml):
http://sprunge.us/IEae

It seems, there is a problem with that thinkpad related tablet stuff. I can't get the keys up/down/left to work. Strangly only key right works. If I map this keys on the letter keys, there is still no difference.

But I found this thread on the internet, wich pushed me in the right direction.
http://forums.bodhilinux.com/index.php?/topic/5868-cannot-turn-left-right-or-accelerate-in-supertuxkart-solved/
Nevertheless, that does not work for me. 

I tried to disable the "ThinkPad HDAPS accelerometer data" and "ThinkPad HDAPS joystick emulation" ingame, but I can not push the buttons, 'cause there was grey. I removed the input.xml and started over. Now - ironically - I _can_ disable these two devices. 

As Arthur mentioned on the irc, maybe there is a need to blacklist these devices permanently.

**Comment by qwertychouskie** [comment]
Is this still an issue with STK 0.9.2?

**Comment by brion** [comment]
I have a similar issue on an old MacBook Pro in 0.9.2 -- https://github.com/supertuxkart/stk-code/issues/2691 -- I had to exit to main menu, then go back into the options, and *then* the "disable" button was no longer greyed out on the false gamepad device. It looks like you simply can't make changes during gameplay?

**Comment by hiker** [comment]
Closing this as outdated.
