### ISSUE TITLE
Kart wheels off ground when karts are turning

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2400]
There is some 'artificial' leaning done in stk (see Kart::updateGraphics), which simulates the leaning of a kart when turning. But atm (not sure since when) certain kart (e.g. tux) very obviously lose contact with the ground when turning at high speed (normal driving speed, no powerup).

It appears that either the values for leaning are wrong, or perhaps the wheels should move a bit more down(?)

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/f147d8e662eef17c558267f5f8b0faea595563f0

The only changes till now is DEGREE_TO_RAD being moved to kart.cpp, other than pre-computed

**Comment by hiker** [comment]
Turns out that this was already the case in 0.9.1.

**Comment by hiker** [comment]
It would be great to get some feedback if this looks better now. You need to drive in a circle for a bit (using an arena recommended ;)  )
