### ISSUE TITLE
Temple battle arena flood bugs

### ISSUE THREAD

**Issue by Odd0002** [supertuxkart/stk-code#2401]
2 bugs I observed when playing the Temple battle arena:

1. If you play a game and let the arena flood (to the point of losing a wheel when in the water) before winning, if you click on "Restart", when the game starts again you will lose a wheel before the countdown to start the battle begins (tested with 3 AI players, all lost at least 1 wheel).

2. If you fall into lava while the arena is flooded, you will lose a wheel from the lava, respawn in the flooded area, and then lose more wheels for being in the water.

**Comment by auriamg** [comment]
In latest SVN I moved the start positions out of floodable areas, should fix both issues
