### ISSUE TITLE
Missing collision in Cocoa Temple

### ISSUE THREAD

**Issue by Cobiskuit** [supertuxkart/stk-code#2402]
Found an interesting bug in Cocoa Temple, I can pretty easily get out of bounds in the first major turn. I'm not sure if this is specific to my system, but I suppose here is a good way to find out. The video linked here explains pretty well what I mean:

https://youtu.be/Fa4WnMojfzE 
(Video is set to Unlisted with comments off, let me know if you have a problem seeing it)

I'm running Arch Linux, 64-bit, using an AMD/ATI card. The video is a little laggy, I had to turn the visual settings all the way down to record the screen, and even then it was slow. However, I was able to replicate the bug with higher settings, and the recording software not running.

Any other info you need, feel free to let me know. Kidna new to github, so bare with me. And thank you! Big fan of the game.

Edit: I'm using version 0.9.1, for clarification.

**Comment by Elinvention** [comment]
I can confirm this bug. I was also able to drive on that green surface underneath the map indefinitely, it seemed not to end.

**Comment by qwertychouskie** [comment]
Also in "Carnaval del cacao" add-on race.

**Comment by Benau** [comment]
Actually the "wall driving" of the track is not completed, for example, AI will ignore them.

There is some work done, but not merged:
https://github.com/lurk26/stk-code/tree/walldriving

**Comment by qwertychouskie** [comment]
Is that the right link?  The latest commit was on Aug 9, 2014, before 0.9.0 even.

**Comment by qwertychouskie** [comment]
Any updates on this bug?  it is very easy to fall off and not get reset.  For new players that do not know they can manually trigger a reset (I did not know until I stumbled across it in the controls settings), this could get very frustrating.

**Comment by Benau** [comment]
Fixed in latest asset
