### ISSUE TITLE
Check compute shaders extension on mesa before release

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2403]
They added recently GL_ARB_compute_shader extension for intel ivybridge and newer. But at least for now it doesn't work as expected for my intel HD 4000 (ambient occlusion looks even worse than before):
![zrzut ekranu z 2015-12-18 12-24-05](https://cloud.githubusercontent.com/assets/5108558/11896188/9fe41258-a584-11e5-824f-24705f40f51c.png)

This can be easily workarounded by adding this line to graphics restrictions:
```
<card contains="Intel"          os="linux"                       disable="ComputeShader"/>
```
We should check before next release if this is still an issue, or if they eventually fixed it.

**Comment by Arthur-D** [comment]
Wouldn't it be best to disable by version?
18. des. 2015 12.43 p.m. skrev "Deve" <notifications@github.com>:

**Comment by deveee** [comment]
Sure, but this extension has been added just few days ago, so maybe they will fix it soon. Here is bug report for mesa:
https://bugs.freedesktop.org/show_bug.cgi?id=93437

**Comment by deveee** [comment]
Ok, this is actually our bug because we only check if compute shader is available. But intel drivers on linux report only OpenGL 3.3 version, and thus these extensions need to be enabled manually in the shader.

Generally, we need something like this in shader.cpp file:
```
    code << "#extension GL_ARB_shader_image_load_store : enable\n";
    code << "#extension GL_ARB_compute_shader : enable\n";
    code << "#extension GL_ARB_arrays_of_arrays : enable\n";
```

**Comment by deveee** [comment]
Ok, the .comp shaders can be now compiled also on OpenGL 3.x drivers, which report that all required extensions are available, so this bug has been fixed.

Though I noticed a bit strange behavior, that AO is shaking on intel driver when we use compute shader, so I disabled it in graphics restrictions for now.
