### ISSUE TITLE
New colorfull speedfore.png picture

### ISSUE THREAD

**Issue by qaugustijn** [supertuxkart/stk-code#2404]
I have make a new speedfore.png:
![speedfore](https://cloud.githubusercontent.com/assets/16267411/11898738/784d8aa6-a59a-11e5-9737-709fa52266e5.png)

The old speedfore has only the colors orange and red
The new speedfore has the colors green, orange and red.

Is this picture better then the old?

The directory of this picture is: data / gui / speedfore.png

**Comment by Benau** [comment]
...

**Comment by auriamg** [comment]
Hi, one issue I have with your picture is that the edges are aliased (pixelated) whereas in the original the edges are smooth

Otherwise, this image is a fairly small change - let's just say we weren't especially looking to change the speedometer, there are many other things that are more important to improve in STK

**Comment by qaugustijn** [comment]
![speedfore](https://cloud.githubusercontent.com/assets/16267411/11917206/8c693030-a6fd-11e5-842d-8f8f3a411452.png)

Is this better?

I have edit the speedometer / speedfore because I thinks that the old speedfore didn't looks great with only yellow, orange and red.

**Comment by auriamg** [comment]
Sorry for the delay, everyone was away for the holidays

Sorry about that but we're pretty happy about the current speedometer and no one ever felt like we needed green in there - its orange color matches the orange supertuxkart theme. And I know it may not be too visible in-game, but the original is still smoother and this one more pixelated, so we'd rather keep the current higher quality speedometer
