### ISSUE TITLE
Can't use nitro while turning left

### ISSUE THREAD

**Issue by Datamine** [supertuxkart/stk-code#2410]
Hit the forward and right keys simultaneously. You can then press 'n' to nitro, and the blue exhaust flames appear (if you are playing as Tux). If you hit the forward and left keys simultaneously, the blue exhaust flames do not appear. I haven't checked whether you gain speed as you should while using nitro.

**Comment by Flakebi** [comment]
Hi, that's probably an issue with your keyboard. It looks quite similar to #2185.

**Comment by Datamine** [comment]
I suspect you're right. I'll close this issue since it is, at the very least, a duplicate.
