### ISSUE TITLE
Untextured elements on Intel GPU

### ISSUE THREAD

**Issue by Anthony-Gaudino** [supertuxkart/stk-code#2413]
I installed the game on an old notebook that runs Windows 7 x86 that has an Intel I3, with Intel GPU.

When I run the game I don't get any textures for the fonts and other GUI elements. See screenshot bellow:
![supertuxcartgui](https://cloud.githubusercontent.com/assets/2439728/12012785/94732864-aceb-11e5-8a75-f3fadda1724d.jpg)

I tried changing the game settings on the configuration file but I got the same result.

Is this a known issue, is there something I can do to make it work?

**Comment by auriamg** [comment]
Can you please tell us which gpu exactly you are using? STK requires an HD3000 or better to work, so if yours is older than that it may explain. Also make sure you have the latest version of the driver

**Comment by tomreyn** [comment]
In case it helps (sorry if you already know all of this)... To get this system info on Windows you can do as follows:
Press Windows key, then in the search field type "msinfo32" (without the quotes) and press Enter.
This information can then be copied to clipboard ("Edit" menu)  and pasted (and posted) to https://gist.github.com. Finally, the resulting Internet address can be referenced here.

**Comment by Anthony-Gaudino** [comment]
It says `Intel HD Graphics (Core I3)`, its an I3 M330 and has latest drivers.

Looking at https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units it seems this CPU is from 2010, and HD Graphics 3000 was only introduced on 2011, so I should have paid more attention while reading the game requirements and notebook specs.

**Comment by deveee** [comment]
It looks like you have gen5 (ironlake) graphics card. You can look at stdout.log file, which OpenGL version you have. These graphics cards can support OpenGL 3.x, but Intel doesn't really care about it. I remember that there was some work (or at least some plans) to support it on linux. But I really don't know what about windows.

If you have OpenGL 3.x support and it doesn't work, you can force to use old GL 2.1 version by setting force_legacy_device to true in config.xml file. It will look buggy, but it will at least run.

If you have only OpenGL 2.1 and the lastest drivers, then you can't do much about it.

**Comment by Anthony-Gaudino** [comment]
Thank you @deveee.

I looked at the log and it shows this:

```
[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: Intel
[info   ] IrrDriver: OpenGL renderer: Intel(R) HD Graphics
[info   ] IrrDriver: OpenGL version string: 2.1.0 - Build 8.15.10.2993
```

I changed the setting `force_legacy_device` to true as suggested and it worked, but as you said there's some graphics issues, but nothing that breaks the game.

**Comment by deveee** [comment]
It looks strange for me. If you have only OpenGL 2.1, then legacy context should be used automatically. Could you send full stdout.log file with disabled force_legacy_device parameter?
