### ISSUE TITLE
Found a bug in Shiny Suburbs

### ISSUE THREAD

**Issue by qaugustijn** [supertuxkart/stk-code#2415]
I found a bug in Shiny Suburbs (city): If you race this track in reverse and you choose the additional driveline, the end of this driveline has a lower height then the main driveline. You cannot drive to the main driveline. Look at this picture:
![bug_in_city](https://cloud.githubusercontent.com/assets/16267411/12049997/208e7218-aeef-11e5-93cd-9e968e9ef9e7.png)
I have fix this bug only in a older version of this track. Is there a newer version of this track?

**Comment by SilverLuke** [comment]
Same bug in "quicksand" in reverse.

**Comment by auriamg** [comment]
The city issue is now fixed in svn

**Comment by auriamg** [comment]
Sand track fixed too
