### ISSUE TITLE
Wrong character in title font

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2417]
I didn't have a time for debugging yet. I just noticed that one character looks wrongly in one place. It should be uppercase 'Ą', but it is lowercase 'ą' instead.

![zrzut ekranu z 2016-01-03 00-30-23](https://cloud.githubusercontent.com/assets/5108558/12076572/8ceadafe-b1b1-11e5-9e09-8008aac09af0.png)

**Comment by Benau** [comment]
Because Ą is not used in Polish PO file, all I get preload characters from.

In IRC, we discuss whether we should disable capitalization in title for all languages, but may need more glyph pages, not sure what you like...

**Comment by Benau** [comment]
Fixed, close when music branch merge, sorry for wrong branch pushing

**Comment by deveee** [comment]
Thanks a lot!
