### ISSUE TITLE
Error sending activation email.

### ISSUE THREAD

**Issue by juangl** [supertuxkart/stk-code#2418]
Displayed error:

```Supertuxkart the admin email is not set. could not send email. please contact a website administrator```

**Comment by auriamg** [comment]
Can you explain where you were / what you were doing when you saw that error message?

**Comment by juangl** [comment]
when I will sign up and it should send me an activation email. :sandal:

**Comment by cap44** [comment]
@juangl can you try now? it should be fixed

**Comment by juangl** [comment]
Yes, I was fixed.
