### ISSUE TITLE
Can't set graphics to native display resolution

### ISSUE THREAD

**Issue by lightonflux** [supertuxkart/stk-code#2422]
The resolution of my display is just not available in the options. The resolution is 2560x1600px. 

Does STK use a list of hard coded resolutions? Can i add my resolution ot an xml or something.

Thankful for all help.

**Comment by deveee** [comment]
Generally we get resolutions list from system and we filter only very low resolutions (we require at least 1024x768).

I assume that you are on linux? If so, the resolutions list should be the same as reported for your primary monitor by ```xrandr``` command. 

Maybe you have two monitors and the 2560x1600 is not the primary one?

**Comment by lightonflux** [comment]
Yes its on linux.

	
     $ xrandr
	Screen 0: minimum 8 x 8, current 2560 x 1600, maximum 16384 x 16384
	DVI-I-0 disconnected (normal left inverted right x axis y axis)
	DVI-I-1 connected primary 2560x1600+0+0 (normal left inverted right x axis y 
	axis) 646mm x 406mm
	   2560x1600     59.86*+
	   1280x800      59.91  
	HDMI-0 disconnected (normal left inverted right x axis y axis)
	DP-0 disconnected (normal left inverted right x axis y axis)
	DVI-D-0 disconnected (normal left inverted right x axis y axis)
	DP-1 disconnected (normal left inverted right x axis y axis)

**Comment by deveee** [comment]
So in STK options you see 1280x800 resolution, or only the hardcoded 1024x768?

Could you give a bit more information? Especially:
- which STK version do you use
- what is your xrandr version
- which OS do you use
- do you use wayland or standard X
- if you compiled STK yourself, did you set some additional flags?

Could you also attach your stdout.log file?

If you want, you can also run this test:
http://deve.koliber.pl/stk/xrandr-test.cpp
It should be compiled using command
```g++ xrandr-test.cpp -o xrandr-test -lXrandr -lX11```
This is basically what we do in STK. If this test will report ```Is primary id``` and ```Current resolution: 2560, 1600``` then it should work in STK too. If not, maybe it will say us what's wrong.

**Comment by hiker** [comment]
Closing now, please reopen if you can provide the requested information.
