### ISSUE TITLE
Supertuxkart online account name problem

### ISSUE THREAD

**Issue by tancrackers** [supertuxkart/stk-code#2424]
I registered for a STK account under this name:
Avian Flue

I tried to log in here:
http://addons.supertuxkart.net/login.php?action=submit

I cannot log in because:
"Your username can only contain alphanumeric characters"

I can log into my online account within the program, but not onto the addons. website.

Also, I cannot re-register because I have already used my email address.

**Comment by auriamg** [comment]
So after verification, it seems that we may need to clarify what characters are allowed in STK usernames

The STK game itselfs allows any characters, whereas the stkaddons website seems restricted to ^[a-zA-Z0-9]+$

I would tend to conclude that STK is too permissive, and stk-addons is too restrictive - I think the username should at least support characters like periods, dashes, underscores. Probably spaces shouldn't be accepted though

@leyyin any thoughts on being more permissive on usernames for stk-addons? I can update the core game with appropriate validation

**Comment by Benau** [comment]
Maybe online username more restrictive, local name allow any?

In STK, it seems to "copy" online username from local name when first register, may need to deal with this issue more seriously after networking is done!

**Comment by leyyin** [comment]
@auriamg the problem is that the API allows the registering of users with those kind of names :), it's not the core game fault. Also I agree that we should allow periods, dashes, underscores.

Now the problem is the users who already have a username with a whitespace. 
Maybe modify their usernames so that it does not contain a whitespace and send them an email notifying them of the change?

**Comment by auriamg** [comment]
@leyyin that sounds good to me

So probably the API should perform the same validation as the login page, does that sound good?

**Comment by leyyin** [comment]
@auriamg Yes that sounds good (sorry for the delayed response). I will probably try to fix it this Saturday or Sunday.

**Comment by leyyin** [comment]
Sorry for the delay.
 @auriamg now we allow usernames with periods, dashes, underscores and you can't create any new accounts with a space in the username.
@tancrackers You can try to log in with your existing account (that has a space in the username), old accounts can still log in.

**Comment by tancrackers** [comment]
Awesome. I can log in and whatnot.
Thanks!

**Comment by auriamg** [comment]
Seems to work fine, thanks!
