### ISSUE TITLE
Missing Hungarian Ö Ő Ű characters

### ISSUE THREAD

**Issue by urbalazs** [supertuxkart/stk-code#2425]
There are missing Hungarian characters (Ö, Ő, Ű) from title font bitmap file. I attached them as PNG.
![title_font_2-missing](https://cloud.githubusercontent.com/assets/1006118/12371307/df23e090-bc2e-11e5-9740-3776a7e6ebbc.png)

**Comment by Benau** [comment]
It would would be good if you try git STK, bitmap font is replaced by TTF file now.

Sorry for your duplicated work

BTW, nice super-fast Hungarian translation!

**Comment by urbalazs** [comment]
OK, but can you check, whether the new TTF file supports the special Hungarian characters? There is a dummy sentence, which contain all of them: "árvíztűrő tükörfúrógép" or in uppercase: "ÁRVÍZTŰRŐ TŰKÖRFÚRÓGÉP" (this means "flood-resistant mirror drill" in English :P ). If the TFF supports them, you can close this issue.

**Comment by Benau** [comment]
Say so, (direct copy your text to po file)

![2016-01-17 00-12-34](https://cloud.githubusercontent.com/assets/3252341/12373281/11409e4e-bcaf-11e5-8438-6236c65e52d7.png)
