### ISSUE TITLE
Tutorial broken in OSX package

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2431]
OSX package seems to include an outdated scripting.as file, the tutorial is therefore broken. It is unknown if the OSX package includes more outdated files

EDIT: turns out I had a SVN conflict on that specific file, at lease no other file should be impacted

**Comment by BuddhaWay** [comment]
=) Hey I found this!!! =) sorry im excited

**Comment by BuddhaWay** [comment]
I don't think i've ever reported a bug. Sorry just excited and stroking my ego

**Comment by auriamg** [comment]
A new binary is now available on the downloads page that fixes this issue
