### ISSUE TITLE
?Driver too old for an ATI Radeon HD 4890

### ISSUE THREAD

**Issue by Tom-Pom** [supertuxkart/stk-code#2437]
Hi . I try to run the 0.9.1 version and it keeps telling me that my video driver is too old.
I tried to upgrade it to the latest (2015) and downgrade it after( to2012)
I checked the minimal requirements of the game and my card should be supported (minimal : 4xxx)

Here is the PID / VID for my ATI Radeon HD 4800 Series
PCI\VEN_1002&DEV_9460&REV_00

What do you think?

![image](https://cloud.githubusercontent.com/assets/8494601/13016109/2d001330-d1bd-11e5-967e-842fe4b16f73.png)
![image](https://cloud.githubusercontent.com/assets/8494601/13016116/38f0f808-d1bd-11e5-8d6d-e02863fb335a.png)
![image](https://cloud.githubusercontent.com/assets/8494601/13016231/bb2b1cb8-d1bd-11e5-9498-d0124da204fa.png)

**Comment by Tom-Pom** [comment]
Solved :+1: The ati 4890 dont support graphics quality over 2

**Comment by auriamg** [comment]
In general you didn't say which OS you are using, too. On Linux, you need a fairly recent version of mesa to get advanced effects
