### ISSUE TITLE
Some problems with 2nd start (Russian edition)

### ISSUE THREAD

**Issue by KOMMIKs** [supertuxkart/stk-code#2440]
Hello. I tried to run this game "supertuxkart.exe" version 0.9.1, but at this ['Screen from twitter'](https://pbs.twimg.com/media/Cba9JYsUMAAsNxu.jpg) you can see that language "Russian" is missed. Where I can find file of the language or run with English language? 
OS: Win7 HB 64-bit 
Default language of my OS: Russian.
1 year ago this game perfectly well worked (last release) on that PC.
How to solve this problem with starting up of the game?
My [twitter](https://twitter.com/supertuxkart/status/700314539108233217).
Thank you.

**Comment by Benau** [comment]
It's more like a driver version other than language missing.

Could you tell us what is your graphic card and driver version you are using?

**Comment by KOMMIKs** [comment]
Benau, Hello.
My graphic card: 1st Intel HD Graphics date of produce 10.01.2012 / version: 8.15.10.2622 - ID	PCI\VEN_8086&DEV_0046&SUBSYS_10681462&REV_02
2nd: Nvidia GeForce 310M  1Gb - ID	PCI\VEN_10DE&DEV_0A70&SUBSYS_10681462&REV_A2
I didn't change anything (MSI-168a - notebook/[CX623](https://ru.msi.com/product/notebook/CX623.html#hero-overview))
Version STK : 0.8.1

**Comment by cap44** [comment]
Your GeForce chip supports OpenGL 3.3, yet the Intel GPU only supports
OpenGL 2.1, so SuperTuxKart should run on your laptop as long as the NVIDIA
GPU is used as the main GPU
On Feb 19, 2016 3:33 PM, "KOMMIKs" <notifications@github.com> wrote:
>
> Benau, Hello.
> My graphic card: 1st Intel HD Graphics date of produce 10.01.2012 /
version: 8.15.10.2622 - ID PCI\VEN_8086&DEV_0046&SUBSYS_10681462&REV_02
> 2nd: Nvidia GeForce 310M 1Gb - ID
PCI\VEN_10DE&DEV_0A70&SUBSYS_10681462&REV_A2

**Comment by KOMMIKs** [comment]
cap44, I see. But font is like bricks, there's no letters anymore. ;-(

**Comment by deveee** [comment]
I see sometimes something similar (white screen with black squares) when:
- graphics drivers support only OpenGL 3.1 (this can be usually solved by upgrade to current drivers, which support OpenGL 3.3)
- OpenGL 2.1 context is created, but drivers report for some reason that they have OpenGL 3.1, and then we assume on our side that we have GL 3.1 context.

This may be bug with drivers or that we don't handle properly some specific cases.

Try to run STK on your nvidia graphics card and maybe update your drivers. I hope this will help.

**Comment by KOMMIKs** [comment]
deveee & cap44, Thanks. I launched with GPU Nvidia and game - ok. I don't know why the game show me black squares, but now everything is ok.

**Comment by Benau** [comment]
Glad you can play, enjoy!
