### ISSUE TITLE
" / " to "/" without spaces

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2443]
Suggest chaning " / " to "/":
Eggs: %d / %d

> Eggs: %d/%d

**Comment by auriamg** [comment]
why?

**Comment by nado** [comment]
It’s more readable to have spaces.

**Comment by scootergrisen** [comment]
Ok but then change the other strings that use / without spaces.
So they are all the same.

I also found this string that use " / ":
    Game type (Goals limit / Time limit)

But other then those two the all use without space.
I don't care if its one way or the other i just saw the "error" while translating.

**Comment by qwertychouskie** [comment]
Can probably be closed as excessively minor, if someone wants the create a PR, they can.

**Comment by auriamg** [comment]
Changing the string would break all existing translations, making it slightly more readable (subjectively) is not worth asking all translators to translate the string again for such a minor gain
