### ISSUE TITLE
Progress not being saved in story mode

### ISSUE THREAD

**Issue by tancrackers** [supertuxkart/stk-code#2444]
Whenever a match finishes with user in first place, the points do not register in story mode. Therefore, progress cannot be made further into the game.

Supertuxkart 0.9.2
Arch Linux

**Comment by nado** [comment]
Did you actually win the challenge or did you simply finish the race in first position ? Read carefully the winning conditions.

**Comment by tancrackers** [comment]
OK I need to stop doing things half-asleep.
Sorry about that!
