### ISSUE TITLE
Game crashes when changing resolution or fullscreen. [Linux - Multiple Distros]

### ISSUE THREAD

**Issue by Cityscape4** [supertuxkart/stk-code#2450]
[stdout.log.1.txt](https://github.com/supertuxkart/stk-code/files/170258/stdout.log.1.txt)
[stdout.log.2.txt](https://github.com/supertuxkart/stk-code/files/170259/stdout.log.2.txt)

STK 0.9.1 crashes when changing display settings in-game, including changing to: fullscreen, different screen settings, graphical effects level.

When running the game from term with -info attached, I've got the following errors when the game crashed:
*** Error in `supertuxkart': free(): invalid pointer: 0x00000000039c4270 *** 

*** Error in `supertuxkart': double free or corruption (!prev): 0x00000000042393f0 ***

This issue affects multiple distributions (all amd64) and different hardware configurations.

Tested on:
Toshiba L655D Laptop with AMD HD 4250 using Radeon driver.
Crashes on both Debian 8 Jessie and Ubuntu 14.04 based distros.

Also tested on:
Dell Inspiron 5458 with Intel HD 5500 and Nvidia 920M.
Game crashes when using the Intel card and when using Nvidia card (proprietary driver), both cards have been tested.
Crashes on OpenSuse 42.1 Leap, Debian Testing (Stretch), Ubuntu 15.10, and Ubuntu 14.04 based distros.

This is 2 completely different computers, and 3 completely different GPUs (AMD, Intel and Nivida) that changing any graphics settings the causes the game to crash!  On the tested distros the STK packages were downloaded from distro repositories. On a few of them I tried the static binary, it produced the same result.

**Comment by Benau** [comment]
Possibly duplicate of #2419, do you have any input devices attached?

**Comment by Cityscape4** [comment]
It might be, I'm probably the Adam you mentioned in that thread because I did speak with you in IRC a few months ago, and we didn't get the issues resolved.

The only input device I might have would be a usb mouse.

**Comment by Cityscape4** [comment]
Okay, I think this is a duplicate of #2419, I read through it and I also have a Microsoft mouse. So I unplugged it and changing graphics settings now works! :smile: 

So now my questions are:
1. Is this being fixed for the next version?
2. Can we get a notice about this "Known Issue" put on the downloads page of the website? We don't want people trying out the game, getting frustrated over the bug and give up and not play anymore. I haven't played STK for almost a year because of this bug (before I finally got around to filing this report.) We should make sure others know how to fix this problem, Microsoft wireless mice are very common so this might affect a lot of people.

**Comment by Benau** [comment]
I tried to reproduce it by ln -s event0 js0 in /dev/input, but STK didn't crash if I change resolution...

There is a https://github.com/denilsonsa/udev-joystick-blacklist, which may help too.

**Comment by auriamg** [comment]
Can any developer reproduce this issue? It would be nice to fix it, unfortunately it may be difficult until a developer can actually reproduce it

**Comment by freechelmi** [comment]
Easily repduced at every try to change the resolution which render the game impossible to play .

Ubuntu 15.10 , STK 0.9.5 from repository.

**Comment by Benau** [comment]
@freechelmi do you have such devices mentioned above?

**Comment by freechelmi** [comment]
Just a an USB Mouse/keyboard.

I've played hours of 0.8.2 on 14.04.1 , I'm sure this is related to new mesa drivers

**Comment by Benau** [comment]
Do you know how to run STK in a debugger / can you join #supertuxkart irc in freenode?

**Comment by freechelmi** [comment]
Yes , We can say I'm a "power user" so I could do this, does it include rebuild with debug flags ?
Here is  at least paste the current output. only the last line concern the full screen switch.

http://paste.ubuntu.com/15375331/

**Comment by deveee** [comment]
Should be fixed in 29e4d4a0bcfc69e7ceba75f8f30b4d9142df625a.

**Comment by auriamg** [comment]
@deveee can you explain your fix? I'm not sure I understand how your commit would fix anything?

**Comment by deveee** [comment]
As I said in the commit, SEvent::SJoystickEvent::NUMBER_OF_BUTTONS is constant value and is equal to 32. So in header file there was declared bool m_buttonPressed[32] for every gamepad.

My wireless mouse detected as a gamepad says that it has 69 buttons. We respect it in this code in GamePadDevice constructor:
```
    if(m_configuration->getNumberOfButtons()<button_count)
    {
        config->setNumberOfButtons(button_count);
    }
```
and in this case number of buttons is set to 69.

And then in function:
```
void GamePadDevice::setButtonPressed(const int i, bool isButtonPressed)
{
    m_buttonPressed[i] = isButtonPressed;
}   // setButtonPressed
```
we write for example m_buttonPressed[68], which is out of array.

Now we alloc m_buttonPressed[button_count], so we shouldn't write out of array anymore.

Of course we should also detect that this mouse is not a gamepad, but this is another task.

Btw. bool m_buttonPressed[SEvent::SJoystickEvent::NUMBER_OF_BUTTONS] has been there since 2009 ;)

**Comment by hiker** [comment]
It might be worth sending this to the irrlicht team as well :)

Thanks!
    Joerg
