### ISSUE TITLE
Water not shown on Cocoa Temple race track when Advanced Pipeline turned off

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2459]
The water is not shown on the Cocoa Temple race track (and add-on variant) when the Advanced Pipeline is turned off.

**Comment by qwertychouskie** [comment]
Any updates?  This bug is less relevant to me now, because performance improvements in the git version allow me to use the Advanced Pipeline now, but for those on older hardware, the lack of visible water is confusing.

**Comment by deveee** [comment]
@qwertychouskie there is no performance improvements in current git version on graphics side. Just few bugs are fixed. Maybe your graphics drivers work better now ;)

It's little probable that someone will fix this soon. I'm currently working on these two issues:
https://github.com/supertuxkart/stk-code/issues/2463
https://github.com/supertuxkart/stk-code/issues/1751
and it's rather hard to fix if you didn't write this code yourself.

**Comment by qwertychouskie** [comment]
Maybe a bug was fixed that enabled a performance-increasing feature to work properly, and thus be enabled.  BTW, I am using Intel graphics, though I plan on testing on a system with a different graphics card sometime to see if the problem dependent on the driver or not.
