### ISSUE TITLE
My ears don't like the crash audio (crash.ogg)

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2460]
When the karts crashes into each other the crash the crash.off file play.
But that sound becomes annoying after some times.
Its like its to hard of a sound. Or to sudden of a loud sound.

**Comment by Benau** [comment]
crash.off -> crash.ogg?

Did you mean you find the sound annoying because it's too loud or play too much?

**Comment by scootergrisen** [comment]
Yeah ogg.

Its just to hard of a sound.
Like holding a cooking pot to the ear and hitting it.
When you hear it like like 100 times its annoying.

**Comment by Benau** [comment]
Try turn off sound effect in game?

**Comment by scootergrisen** [comment]
I would like sound effect. Its just that crash sound i don't like the sound of.

**Comment by Benau** [comment]
Why not replace the ogg file yourself?

**Comment by scootergrisen** [comment]
Yes thats whats im suggestion.
In STK but not just on my computer.
I dont have a good crash sound but maybe someone could make/find a better crash sound that are nicer for the ears when you hear that sound a lot of times.

**Comment by Benau** [comment]
![i](http://static.zerochan.net/Demotivational.Poster.full.825185.jpg)

**Comment by scootergrisen** [comment]
I dont see how that helps.
I'm suggestion to change the crash sound in STK.

**Comment by auriamg** [comment]
We are definitely open to using a better sound effect, unfortunately none of use are soung engineers, so if someone out there is able to produce one (or more) improved sound effects, we would most welcome it!

**Comment by scootergrisen** [comment]
Another idea could be to have multiple crash sounds that are a bit different and maybe play them at different volumes depending on how hard you crash into each other.
That way the sound would not be so monotome... or what ever its called when its the exact same sound over and over again.

**Comment by Cyberpangolin** [comment]
What about these?

[boumkart.zip](https://github.com/supertuxkart/stk-code/files/335830/boumkart.zip)

If you wish to use them, I release them under the WTFPL. It means you can do anything, even re-licensing them ;). Maybe they are note "crashy" enough, but anyone can improve them.

**Comment by auriamg** [comment]
Well yeah they sound like wooden marbles, not like crashing karts

**Comment by scootergrisen** [comment]
I agree that the sound is not correct. Like it does not really sound like karts hitting each other.
But then again it a pinguin driving the kart so maybe the game is not aming to be realistic.

The first file crashkart-01.wav sounds fine to be and could be used for something.
But i think no matter what sound is used that its not good to hear the same sound all the time and that maybe there should be multiple different crash/collision sounds depending oh what you hit, karts, walls, other stuff. And that the volume was depending on have hard the collision is.

I noticed when i hit the walls in the level under water there are no sound.

**Comment by rogue-spectre** [comment]
Do you like this sound for an alternate sound ? http://soundbible.com/1120-Bounce.html

**Comment by scootergrisen** [comment]
I suppose the ballon sound could be thought off as the tires hitting each other some times.
And the other times it could be a more metal on metal sound.

I don't know why but the sound sounds distorted when played in STK 0.8.1 as compaired to being played in a medie player.
In STK 0.8.1 the sound sounds more bass and not so good/clear.
Maybe this have improved in newer version. I will try in Windows with a newer version.

**Comment by rogue-spectre** [comment]
we can also assume that karts have bumpers ? So the sound of the collision is more like "plastic like"

**Comment by scootergrisen** [comment]
Maybe different karts can have different sound depending on the kart design.
The ballon sound might be good for the Xue kart. The one with the mouse and hover kart. It has a rubber skirt or something instead of wheels. So that ballon sound seem good for the specific kart.

That way if some karts use different sounds you don't end up hearing the same sound over and over again, but a mixture of different sound.

**Comment by qwertychouskie** [comment]
@scootergrisen Sounds good. (Pun very much intended :D)

**Comment by Benau** [comment]
New SFX is updated

**Comment by scootergrisen** [comment]
Yiiiihaaa. Cant wait to test it.
