### ISSUE TITLE
Maybe change the intro music

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2461]
When i start STK i have several times found the audio level way to high and the music to be to "hard".
It may be that i have bad control over my volume control but maybe it would still be better to have a more soft/mellow intro music that starts slowing and it not so loud and hard on the ears.

Like the sound of the waves at the beach or some birds or what ever could be fun.

**Comment by Benau** [comment]
Sorry, this issue page is not intended for suggestion, next time have better post a forum for idea

**Comment by scootergrisen** [comment]
ok sorry.
