### ISSUE TITLE
Suggest improve this string ("SuperTuxKart may connect to a se...")

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2465]
When STK starts i get this long string and Yes and No buttons. But the question is hidden inside the middle of the string and there are no newlines and the URL is not clickable.

> SuperTuxKart may connect to a server to download add-ons and notify you of updates. We also collect anonymous hardware statistics to help with the development of STK. Please read our privacy policy at http://privacy.supertuxkart.net. Would you like this feature to be enabled? (To change this setting at a later time, go to options, select tab 'User Interface', and edit "Connect to the Internet" and "Send anonymous HW statistics").

Maybe something like this would be better...

> SuperTuxKart may connect to a server to download add-ons and notify you of updates. We also collect anonymous hardware statistics to help with the development of STK.
> 
> To change this setting at a later time, go to options, select tab 'User Interface', and edit "Connect to the Internet" and "Send anonymous HW statistics".
> 
> Please read our privacy policy at <makelink>http://privacy.supertuxkart.net</makelink>.
> 
> Would you like this feature to be enabled?

Instead of "Would you like this feature to be enabled?" maybe better to call it "Would you like to enabled X?" and then find a name for the feature. Maybe something like "automatic download, updates notifications and submit statistics" or what ever short name could be found.

And maybe show this part with smaller letters or maybe a another color:
To change this setting at a later time, go to options, select tab 'User Interface', and edit "Connect to the Internet" and "Send anonymous HW statistics".

**Comment by auriamg** [comment]
This seems very minor, probably not worth breaking all existing translators for... Your suggestions are mostly about moving text around a bit, no major gain there,

Also, quite a few of the things you suggest are unfortunately not doable to technical limitations of our current engine (for instance clickable links or colored bits of texts)

So sorry, nothing like that is planned for the moment

**Comment by scootergrisen** [comment]
Ok but things like this will make me want to not report bugs and other things and use my time on other projects.
