### ISSUE TITLE
Lowest volume setting is not silence

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2466]
I would expect when i slide the volume control all the way down that there would be no audio playing.
But in STK the lowest setting (1) still plays audio.

Also maybe instead of 1-10 it should be 0-10 or 0-9 so the lowest is 0.

**Comment by nado** [comment]
There’s a box to check if you want to disable volume.

**Comment by scootergrisen** [comment]
I know.

**Comment by nado** [comment]
So, to me it makes sense that the lowest volume ≠ from disabling the volume, so the lowest volume should be the minimum hearable.

**Comment by scootergrisen** [comment]
Where have you ever found such a volume control that still plays audio when you turn it all the way down?

**Comment by Benau** [comment]
Actually by changing min_value="1" to "0" in https://github.com/supertuxkart/stk-code/blob/master/data/gui/options_audio.stkgui will satisfy your wish, although it's not a correct way which simply press the disable button is better.

Try open a pull request to see if it gets allowed.

**Comment by scootergrisen** [comment]
But have you ever tried a volume control that played sound when you turn it all the way down?

**Comment by nado** [comment]
Yes, I have found a few and cant remember them and it seems normal when you have a checkbox to mute the sound.

**Comment by scootergrisen** [comment]
If the checkbox is for muting maybe it should say "Mute".

**Comment by nado** [comment]
What does it say ? Disable ? Same.

**Comment by scootergrisen** [comment]
It works fine with min_value="0" for music and sound effects. Just tested.

Checkbox says "Enabled".
Maybe not the best name for a checkbox.
"Enabled" and "Disabled" sounds more like the state of the checkbox. Is it checked or not.
It sounds silly to say "Enabled is enabled" or "Enabled is checked".

If min_value is 0 then maybe there are no reason to have a enabled/mute checkbox?

Then again maybe it would be nice to have a "Mute all audio" to play the game without audio and without having to check/uncheck multiple checkboxes.

**Comment by Benau** [comment]
the min_value 0 is a quick hack for just for you, the proper fix is to detect whether this widget is zero, and then SFXManager::get()->toggleSound(false) or music_manager->stopMusic().

Not sure if @auriamg wanna make this screen too complex

**Comment by scootergrisen** [comment]
Yeah no reason to play audio at zero volume.

If you dont want the screen to be complex you could remove the checkboxes and then write "Muted" or something like that when the value i 0.

Maybe the value showed for the user should be from Muted/0% to 100%.
Instead of 0 - 10.
Or maybe just remove the numbers so the user only see the graphic bar.

**Comment by nado** [comment]
I liked the Mute checkbox :(. It allows me to quickly switch from usual volume (better to play in multi) to muted (like when I play alone and prefer to listen to music from my media player).

**Comment by scootergrisen** [comment]
Yeah i like "Mute" to. But right now is says "Enabled".
