### ISSUE TITLE
Offering Design Help

### ISSUE THREAD

**Issue by elioqoshi** [supertuxkart/stk-code#2468]
Hi guys!

I'm Elio, designer at Mozilla and Fedora and former video game developer (I worked on an unofficial Tomb Raider game).

I'd love to contribute to the game with design works, if needed! You can check more of my work on my blog and Dribbble as well: https://elioqoshi.me

Hope I can help!

**Comment by auriamg** [comment]
Hi,

thanks a lot for your interest! However this is a bug tracker, so not really a good place to discuss a topic like that. I suggest joining on IRC ( http://supertuxkart.sourceforge.net/Community ) or otherwise the mailing list or the forum.

Thanks, see you over there
