### ISSUE TITLE
Add motion blur lines on screen edges when on high speed

### ISSUE THREAD

**Issue by elioqoshi** [supertuxkart/stk-code#2469]
In SSASR there is a nice effect of animated lines on screen edges when in high speed, which adds to the motion blur. Can we have something similar?

https://www.youtube.com/watch?v=K4st1foZULQ

**Comment by auriamg** [comment]
Actually, STK already has motion blur! It's disabled on the lower graphical levels though. Also, it's only active when using zippers (speed bonuses, either collected in gift boxes or on the floor), so it can be missed. But we do have it! :)

**Comment by elioqoshi** [comment]
@auriamg Yes, I noticed it! Wouldn't it make sense to enable it gradually on higher speeds (not only via the powerups). That is, also after getting bonuses for longer drifting. 

Also, I was talking about adding also more opaque lines as sprites to the screen, apart the motion blur, like this: 

![blur lines](https://cloud.githubusercontent.com/assets/5436686/14631823/9984cc4e-0615-11e6-9419-9bd5e57d0b3e.jpg)

What do you think?

**Comment by auriamg** [comment]
I don't know, on expert difficulty you will probably go close to the max most of the time, that would mainly make the screen blurry... not that cool

**Comment by elioqoshi** [comment]
I mean adding the sprites, not raising the blurriness :)

**Comment by cap44** [comment]
There's a way to indicate that you are traveling at high speeds in STK, but I'm not sure how this can be done by the developers 

I think that the camera should rumble (vibrate) when you are going very fast instead of blurring the screen. What do you think?

**Comment by qwertychouskie** [comment]
STK already has camera vibrations: https://github.com/supertuxkart/stk-code/issues/49 ;)
