### ISSUE TITLE
Can't see track at the “track join section” in XR591 thanks to “fake wall”

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2472]
I have spotted a problem with the XR591 track when driving it in reverse: At the part where the track splits the first time (viewed from reverse), you face the directional arrows and see them right on the track. It looks like you will be driving into a wall but you can drive right through it.
This is not good since you can't see the track anymore! Please fix this.

Seen in version 0.9.1.

I can kinda see the intention here: Probably this is done to help drivers driving forwards find the right way when the track joins again. It is a hack since the fake walls can only be seen from one side.
But even for driving forwards it is dangerous since it obstructs your view towards the *other* part of the track; karts can suddenly appear through the wall without warning.
I think the best solution would be to remove this hack altogehter. Instead, I would put the arrows somewhere else where they don't obstruct anyone's view.

**Comment by Benau** [comment]
Or easier fix, no drive in reverse for xr591?

**Comment by qwertychouskie** [comment]
Easier, but not better, as we should be supporting reverse for more tracks over time, not less.

**Comment by Wuzzy2** [comment]
Don't kill reverse driving for XR591, this is just dumb. XR591 was perfectly drivable in reverse for many STK versions. Only recently it became broken with the addition of that strange invisible wall thing.

**Comment by auriamg** [comment]
Fixed in SVN, thanks
