### ISSUE TITLE
Update track preview images

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2473]
Version 0.9.1:
Some track preview images are really outdated and/or available in low resolution only. Since the tracks have been updated heavily in the last releases, the preview images should reflect that.

Someone should check all tracks and update the preview images, if neccessary.
The following images need updating for sure:
* Blackhill Mansion
* Fort Magma
* Shiny Suburbs
* Hacienda
* Northern Resort
* Shifting Sands (looks blurry)
* XR591
* Subsea
* Minigolf

This list may not be complete.

**Comment by Benau** [comment]
Subsea is replaced in 0.9.2

**Comment by Benau** [comment]
Do you want all images of preview rendered with advanced pipeline on?

**Comment by Wuzzy2** [comment]
What?
Please just update the images at the best quality you can get and make it so they look not blurry in preview. Everything else doesn't make sense. Remember there are 2 image sizes now, the other one is larger than in the track selection screen.

**Comment by Benau** [comment]
Do you want to make the screenshots >256x256?

As I can see, Hacienda and Fort Magma have 256x256 resolution

And XR591 has a cursor captured :/

Or other improvement?

**Comment by Wuzzy2** [comment]
Yes. Just use the resolution you see *after* you clicked on a track in the track list. There a bigger screenshot appears. Use this size.

And all the tracks I mentioned in the first post need updated preview anyways because the tracks have seen some graphical changes in the past. This includes XR591.

**Comment by auriamg** [comment]
The ones that changed most have been fixed in SVN. A few more may need a minor update but it should be much better now

**Comment by auriamg** [comment]
Done
