### ISSUE TITLE
Many cheats in Shiny Suburbs

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2476]
There are many cheats in Shiny Suburbs.  Ghost:  http://jacobspctuneup.tk/shinysuburbscheats.replay

**Comment by qwertychouskie** [comment]
Another ghost: http://jacobspctuneup.tk/shinysuburbscheats2.replay

**Comment by auriamg** [comment]
This track was actually designed with many intentional (but poorly balanced) shortcuts. I will leave this ticket open since this is a real issue, but the most likely fix is that this will go away when we completely remake this track

**Comment by qwertychouskie** [comment]
Going to close as this track will likely be replaced by Candela City in 0.9.3
