### ISSUE TITLE
no graphic effects on ASUS Radeon HD7750 / Win7

### ISSUE THREAD

**Issue by goerob** [supertuxkart/stk-code#2480]
hello, I have a ASUS Radeon HD7750, Win7 64bit and SuperTuxCart9.1 but absolutly no effects. No shadows, no lightning, nothing.

There are no errors in the stdout.log. But a warning:
[warn   ] Graphics: Can not find version for '4.0.12422 Core Profile Context 13.152.0.0' 'ASUS HD7750 Series' - ignored.

[stdout.zip](https://github.com/supertuxkart/stk-code/files/243586/stdout.zip)

**Comment by auriamg** [comment]
It's a bit hard to tell, there is nothing wrong in those logs. I assume you already did but better ask, did you verify in the options if the various graphical effects are actually enabled? Since STK failed to detect your driver version, maybe they're just disabled by default

**Comment by Flakebi** [comment]
The card name doesn't contain 'AMD' or 'ATI' so our OpenGL version detection doesn't know what version we can rely on. Probably a detection for strings like 'ASUS HD7750 Series' should be added in the [graphics restrictions file](https://github.com/supertuxkart/stk-code/blob/master/src/graphics/graphics_restrictions.cpp#L188).

**Comment by goerob** [comment]
All the options are enabled. I have this problem since v0.9.0. The version 0.8 works well, without any problems.

I added some screenshots. The graphic level is set to 6 and all options are enabled. But I can edit the graphic options only in the main screen. When the race ist started, the options are not available and some strange character is visible intead of the graphic level (third screenshot).

I have a intel i5 3570k CPU with a build in graphic card. Maybe stc uses the cpu graphic instead of the Radeon? Is there a debug mode, which provides more info than the stdout?

![farm-2016 05 01_14 21 33](https://cloud.githubusercontent.com/assets/18750902/14941802/2cf8fe68-0fa9-11e6-974d-326bed1954e8.png)
![scotland-2016 05 01_14 11 26](https://cloud.githubusercontent.com/assets/18750902/14941806/4002e4ba-0fa9-11e6-9a5f-688ed92c53f3.png)
![scotland-2016 05 01_14 12 20](https://cloud.githubusercontent.com/assets/18750902/14941807/4c3ef5fc-0fa9-11e6-86a5-eeb64235c8c1.png)

**Comment by deveee** [comment]
@goerob You can try to delete all restrictions from graphical_restrictions.xml file. Maybe you are accidentaly affected by some of them. 

You can also try to update your drivers, because they seem to be a bit outdated. Based on this line from graphical restrictions file:
```<card contains="Radeon"         os="windows"  version="<14.300"  disable="DriverRecentEnough"/>```
it looks that we need at least version 14.300 and your graphics card reports only 13.152.0.0. It supports OpenGL 4.x, so I suppose that it shouldn't be a problem to install current drivers.

Actually I'm not sure if we should apply graphics restrictions if we don't have information about drivers version. Currently we assume that empty version string is lower than every real version and we apply every ```version="<(...)"``` for detected graphics card.

**Comment by goerob** [comment]
Thank you @deveee, your hint solved the problem. 

I had the newest drivers from ASUS. But it turned out, that ASUS stopped updateing the drivers in 2013. So I installed now a driver pack from AMD and stk looks good now. I hope the new drivers are fully compatible and will have no bad side effect on other applications.

If anybody else have this problem, you can download a autodetect graphic card app from AMD. But be warned. The app installed much more than only graphic drivers on my system. It installed also some gaming and video recording stuff, scanned my hdd for 15 minutes and started video recording automaticly, when I lunched stk again.

**Comment by auriamg** [comment]
Glad it's solved! I think this ticket can now be closed
