### ISSUE TITLE
Ability to launch cinematic from ingame

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2482]
Currently if we want to use the cinematic capabitilites of stk we must create a scene who has "intro cut scene" as name or change the hardcoded value which is not better.

The best solution IMHO would be in artist debug mode to show cinematic tracks along regular tracks and if we choose them, simply play the cinematic.

**Comment by auriamg** [comment]
That's not exactly what you had in mind, but it's now possible to launch cutscenes from the terminal like this :
```
supertuxkart --cutscene=debug_cinematic --no-start-screen 
```

hopefully this helps?

**Comment by LoadingPleaseWait** [comment]
Should this issue be closed? It looks like it has been resolved.
