### ISSUE TITLE
End of race music does not play when applause plays

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2484]
Also, I get this in the terminal:

    [warn   ] MusicOgg: Music not playing when it should be. Source state: 4116

**Comment by auriamg** [comment]
this is usually a harmless warning indicating the music can't keep up (maybe  a busy CPU), Do you hear any problem?

**Comment by qwertychouskie** [comment]
As stated in the title, at the end of the race, when `gp_end.ogg` plays, `race_finish.ogg` does not play.

**Comment by hiker** [comment]
That was fixed in 12ea4bc76fc12e307363459a69489637c8765803.

**Comment by hiker** [comment]
Arg, copy&pasted in the wrong tab.

**Comment by qwertychouskie** [comment]
Quick fix: replace `gp_end.ogg` with http://jacobspctuneup.tk/gp_end.ogg

**Comment by Benau** [comment]
It's going to be replaced soon with ozoneone new fanfare and win/lose music

**Comment by qwertychouskie** [comment]
I think it would be nice to have the other in the meantime, though.

**Comment by qwertychouskie** [comment]
So it is 0.9.2-rc1, and this regression still hasn't been fixed...  I just updated the copy on my server:  http://jacobspctuneup.tk/gp_end.ogg.  This version has the volume of the applause turned down a bit so that the music can be heard better, and also has proper metadata.  Feel free to use it.

**Comment by qwertychouskie** [comment]
The link is currently having problems but should work in a few minutes, in the meantime use this link: http://173.51.255.115/gp_end.ogg

**Comment by auriamg** [comment]
Thanks, I like your sound. I've commited it!
