### ISSUE TITLE
“invisible wall” in track Industry in STK 0.9.1

### ISSUE THREAD

**Issue by fdik** [supertuxkart/stk-code#2485]
In track Industry there is an “invisible wall” since STK 0.9.1, which makes gameplay annoying. It is near the two silos on the lower right corner just after the garage. In older versions it works as expected.

**Comment by auriamg** [comment]
Hi,

thanks for the report but Industry is an add-on track and not an official one, so it's not supported by us. I'm not sure if the author of this track is still around or can be contacted - or maybe someone can just volunteer to help fix the track and submit a new version.

However I will be closing this issue because this bug tracker only contains issues regarding the "official" game

**Comment by qwertychouskie** [comment]
But if it is since 0.9.1, that means a change in the game caused it...

**Comment by auriamg** [comment]
Okay I took a look at the track in physics debug mode and indeed that is pretty weird, there is nothing there to block the path. Deserves investigation.

@hiker, if you have time to check maybe you have an idea?

**Comment by auriamg** [comment]
Okay after verification, the issue happens because of these objets :

```
  <object type="animation" model="tanks-1.b3d" xyz="196.383804 13.968287 -72.800652" hpr="-90.000009 -0.000000 0.000000" scale="1.000000 1.000000 1.000000" >
  </object>
  <object type="animation" model="tanks-2.b3d" xyz="128.880447 16.859999 85.656441" hpr="-90.000009 -0.000000 0.000000" scale="1.000000 1.000000 1.000000" >
  </object>
``` 

these objects have a large cubic collision shape that is too large. I think this is a modelling issue, the game is behaving correctly

**Comment by qwertychouskie** [comment]
Yes, removing those lines seems to fix it.  Maybe someone with admin access to the add-ons site can update the add-on with those lines removed.

**Comment by qwertychouskie** [comment]
Version with the lines removed:

[198998373556af7cdb86f4b.zip](https://github.com/supertuxkart/stk-code/files/560855/198998373556af7cdb86f4b.zip)

If someone could upload this as a new revision, it would be appreciated. (The site wouldn't let me since I didn't create the add-on.)

**Comment by qwertychouskie** [comment]
This bug can be closed now that the new version of Industry has been uploaded.
