### ISSUE TITLE
Transparent objects are solid in legacy pipeline

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2488]
The opengl 2.1 based pipeline doesn't look that bad. The major problem seems to be that transparent objects on the track are not transparent. It makes it look ugly and also causes some problems, such as solid bubblegum shield, which hides a kart.

If we would fix the problem with transparency, it would be relatively playable. I also remember that on mailing list someone wrote an email about working current STK version for Android. It is probably based on irrlicht GLES version and it is also affected by missing transparency effect.

Maybe just wrong material types are set for transparent objects?

I'm marking this as minor because we officially support only shader-based pipeline.

**Comment by qwertychouskie** [comment]
What is funny is the legacy pipeline looks better than the modern one with the advanced pipeline turned off...

**Comment by qwertychouskie** [comment]
I also noticed sometimes objects get a colored tint that rapidly changes.

**Comment by Benau** [comment]
I updated legacy opengl branch

It was solid because vincent removed normal map renderer which seems to be required by fixed pipeline transparency, now I added it back for fixed pipeline

I have some more fixes coming

**Comment by Benau** [comment]
All problems mentioned here in legacy pipeline are fixed in legacy_opengl branch, @deveee can you try to see if it works for you?

I also made some improvement to #2667

Or I merge now?

**Comment by qwertychouskie** [comment]
I will test soon.

**Comment by deveee** [comment]
I didn't have a time to look at this yesterday.

All your commits look fine for me. And legacy renderer looks now reasonably good :) I tested it under intel ironlake and I didn't notice any issues so far.

I also checked the GLES2 fixed pipeline. It probably has some differences in irrlicht code, because bubblegum or subsea track are still solid. But at least grass is transparent now :) But anyway I wouldn't care that much about GLES2 irrlicht-based pipeline. It's useful only for running STK under emulator and the android port will require GLES >= 3.0 anyway.

Also I'm not sure... do you think that the kart shadow is now good enough to enable it as a fallback for newer graphics cards when dynamic shadows are disabled in options?

**Comment by Benau** [comment]
Let me deal with issue one by one

**Comment by SuicSoft** [comment]
@devee Will GLES 2.0 be compatible the legacy pipeline on Android ?
