### ISSUE TITLE
Imbalanced teams in soccer mode when players cooperate

### ISSUE THREAD

**Issue by mitros123** [supertuxkart/stk-code#2490]
In soccer mode, when players cooperate (they enter the same team), the AI karts are not distributed in a way that the teams will be equal in numbers. This results in heavily imbalanced teams, depending on the number of AI karts. Perhaps a menu can let the player choose how many karts each team should have?

Noticed with two players, perhaps that is the case with more players as well.

**Comment by Benau** [comment]
I think a menu for AI team choosing may not so easy, as the soccer screen has no idea whether the soccer field support AI (has navmesh)

**Comment by Benau** [comment]
Now number of AIs will auto-balance in https://github.com/supertuxkart/stk-code/commit/bb01c83d6e1138b533eef66eabeae00437cd8a9e
