### ISSUE TITLE
Turning off Animated Scenery does not actually turn it off

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2491]
Turning off Animated Scenery does not actually turn it off, e.g. grass in Cocoa Temple still waves.  GPU Info:

product: 2nd Generation Core Processor Family Integrated Graphics Controller [8086:126]
vendor: Intel Corporation [8086]
bus info: pci@0000:00:02.0
version: 09
width: 64 bits
clock: 33MHz
capabilities:
    Message Signalled Interrupts,
    Power Management,
    vga_controller,
    bus mastering,
    PCI capabilities listing,
    extension ROM
configuration:
    driver: i915
    latency: 0
resources:
    irq: 28
    memory: f7800000-f7bfffff
    memory: e0000000-efffffff
    ioport: f000(size=64)

**Comment by qwertychouskie** [comment]
Oops, forgot, Ubuntu 16.10, but also had problem with 16.04

**Comment by auriamg** [comment]
It does turn off a lot of stuff (like particles), but we may need to revisit that option now that we have a new shader-based pipeline, and update what it does to make more sense with modern engines

**Comment by qwertychouskie** [comment]
If nothing else, the name should be changed (preferably before 0.9.2).  In the future, it would be nice to have an option to turn off animated scenery, such as waving grass and animated figures on sidelines, as these take many system resources.

**Comment by hiker** [comment]
Not before 0.9.2, we have already declared a string freeze (and it has been like this for a while now).

**Comment by Benau** [comment]
Quick way to disable waving grass:
In stk_mesh Material::ShaderType getMeshMaterialFromType(video::E_MATERIAL_TYPE material_type, force return Material::SHADERTYPE_ALPHA_TEST for case SHADERTYPE_VEGETATION

But the color of the resulting object is dark, reason unknown

For  "animated figures on sidelines", as they don't have a "straight frame" like karts, so it may be very strange for them to be non-animated.

**Comment by deveee** [comment]
I had the problem with too dark grass in GLES renderer. The reason was that wrong material was used ;) I don't remember precisely, but it probably uses different shader than other objects.

**Comment by MTres19** [comment]
Grass uses a shader to move it based on vertex coloring (same with palm trees actually). Probably disabling the shader makes the vertex coloring show up.

**Comment by Benau** [comment]
We decided that grass is not costly at all, skeletal animation is, so I add an option to disable it also for LOD animated model, now you should see beach girls and monkeys stand still in island!
