### ISSUE TITLE
Linear tracks

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2493]
For the newer gift package there will be a linear track (aka only a long road from A to B), similar to mario kart 8 mount wario.

https://www.youtube.com/watch?v=_fF11_qvJcY

STK is currently not able to manage that kind of track and it raises a few issues:

1) How do we manage the lap count ?
My suggestion is to add "checkpoint" which will act as lap counter, and have an option to force the number of "laps" to be always the same. If a track has 3 check points it will have always 3 laps.

2) How do we manage the win/loose animation ?
I see 3 ways of doing that:
-> A plaza at the end where all characters are simply present and static with their win/loose animation
-> A camera placed somewhere in the track showing a beautiful landscape (probably the easiest) with the score screen
-> A small roundabout at the end where characters can turn endlessly around it

Of course we can always improve after the release

**Comment by samuncle** [comment]
Here is a linear track example (blend & stk track included)

https://drive.google.com/file/d/0B9jjDvqB8YxFMl82bVZGdXVqaDQ/view?usp=sharing

**Comment by hiker** [comment]
1) What are the advantages of a non-looped track?
2) Can't we use the cannon to move the kart back from 'end' to start?

**Comment by qwertychouskie** [comment]
Something like how DK Summit does it makes sense:

https://www.youtube.com/watch?v=sQmgwUnhU2M

**Comment by hiker** [comment]
@qwertychouskie +1
I think STK can already declare any check lines to be lap lines, just the exporter atm automatically adds the start line as lap line.
