### ISSUE TITLE
Jerkyness

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2497]
Best seen around 1:23: http://jacobspctuneup.tk/STKJerkyness.mkv.  Note that it is not usually this bad, just somewhat noticeable in certain sections of certain races, usually linked with low FPS.

**Comment by qwertychouskie** [comment]
product: 2nd Generation Core Processor Family Integrated Graphics Controller [8086:126]
vendor: Intel Corporation [8086]
bus info: pci@0000:00:02.0
version: 09
width: 64 bits
clock: 33MHz
capabilities:
	Message Signalled Interrupts,
	Power Management,
	vga_controller,
	bus mastering,
	PCI capabilities listing,
	extension ROM
configuration:
	driver: i915
	latency: 0
resources:
	irq: 28
	memory: f7800000-f7bfffff
	memory: e0000000-efffffff
	ioport: f000(size=64)

**Comment by auriamg** [comment]
Your STK appears to berunning at 10 frames per seconds

You mention you are using "2nd Generation Core Processor Family Integrated Graphics Controller", I'm afraid this is a very weak graphics chip that was never designed for games, and will porobably be unable to run any but the least demaning games

**Comment by qwertychouskie** [comment]
The low FPS was caused by the screen capture program.  A reboot made the problem better, so the extra jerkiness was just related to needing a reboot, but the jerkiness has happened on other occasions, too.  Also, at 1:23, the jerkiness was happening although it was running at 30 FPS.  It almost seems like the camera is moving forward and backward very quickly.

**Comment by auriamg** [comment]
Ok, now  I understand what you mean. This is a very old issue, see #49

Closing as duplicate, let's track the bug in the original ticket

**Comment by SuicSoft** [comment]
@qwertychouskie What track are you using in the video

**Comment by qwertychouskie** [comment]
The add-on track "Industry".  You may want to see [this](https://github.com/supertuxkart/stk-code/issues/2485#issuecomment-218341905) to fix the invisible wall issue (remove those lines from scene.xml in ~.local/share/supertuxkart/addons/tracks/industry/).
