### ISSUE TITLE
Low-resolution icon for random function

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2500]
The icon for the randomly pick track/arena fuction is very low-resolution, and is quite noticeable in the arena picker.

**Comment by qwertychouskie** [comment]
Re-exported version: http://jacobspctuneup.tk/random.png

**Comment by auriamg** [comment]
Ok thanks, committed

However 512x512 is a bit needlessly large, I committed 256x256 which is already twice as large as the one we currently had and should be good enough, I think. Otherwise the "fix" is to get more arenas so that each screenshot is smaller ;)

**Comment by qwertychouskie** [comment]
Wow, #2500... STK has come a long way...
