### ISSUE TITLE
Grand Paradisio Island : bad reset point in reverse

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2503]
Driving in reverse and going out of the road to the left where the shortcut would begin in normal make us reset in the shortcut, but there is a wall that block the access to the road.

I had to drive back to the jump before getting back to the race.

I will try to provide a screenshot soon.

![gran_paradiso_island-2016 05 16_14 37 44](https://cloud.githubusercontent.com/assets/750258/15289666/0c63297c-1b74-11e6-932f-38df0fe6e4b9.png)
![gran_paradiso_island-2016 05 16_14 37 56](https://cloud.githubusercontent.com/assets/750258/15289667/0c67f920-1b74-11e6-820c-028aef3f37ce.png)

**Comment by auriamg** [comment]
Fixed in git/svn
