### ISSUE TITLE
Better GP win/loose scenes

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2508]
The GP win and loose scenes are defiantly showing their age, and really should be redone.

**Comment by Arthur-D** [comment]
So I assume you will do this yourself?

**Comment by qwertychouskie** [comment]
Unfortunately, I have pretty much no blender knowledge, but I do have some ideas.  In Mariokart Wii, for the GP win scene, they picked an iconic track, and added a celebration.  I think it would make sense to do it similarly, but with "Carnaval del cacao", as it is basically "Cocoa Temple", an iconic track for Supertuxkart, but with some of the celebration already added in.  For the GP loose scene in Mariokart Wii, they put the kart(s) sadly overlooking the celebration form a distance.  I think it would make sense to do it similarly.

**Comment by Arthur-D** [comment]
Making tickets that amount to wishes with a lot of work needed isn't very helpful to be honest. Everyone can see that the story scenes are not very good, and that the overworld could use more work, or as in this case the win/lose animations could be redone. But with no one around to actually do these things, making tickets for them is most likely a waste of time and they will just stay open and unsolved for a long time, possibly even years.

**Comment by auriamg** [comment]
Yup, Arthur-D is right. It is true that much modelling in STK needs to be improved, but tickets are not going to improve that, and we are already well aware of that. Closing this since tickets should be used to track specific bugs

**Comment by qwertychouskie** [comment]
Working on a new gpwin scene, current progress: https://jacobspctuneup.tk/gpwin.zip

**Comment by auriamg** [comment]
@qwertychouskie you appear to have reused a B3D file from an existing track without a blender file, is that the case? A new scene would need to be made in blender, we cannot work from B3D files without their blender source. This scene is also needlessly large. So definitely something must be done specifically for a GP scene in blender

**Comment by qwertychouskie** [comment]
From the track's page: No source files have been uploaded for this addon yet.
I couldn't find the source for cocoa temple either...

**Comment by Benau** [comment]
https://supertuxkart.net/Source_control

See media repo

**Comment by qwertychouskie** [comment]
I check the media repo, not there as for as I could see...

**Comment by Benau** [comment]
30_chocolate

**Comment by qwertychouskie** [comment]
OK, trimmed down the B3D, v2 is at the same link.  Note that I have not yet trimmed down the extra library objects from scene.xml.

**Comment by qwertychouskie** [comment]
V3 uploaded, same link: https://jacobspctuneup.tk/gpwin.zip

**Comment by deveee** [comment]
@qwertychouskie sharing the .blend file is mandatory if you want to include your work into the game. Look at our sources at sourceforge. Every (even minor) modification is made in .blend file and then our exporter is used to create b3d and xml files. I mean .blend is a "source" file and .b3d is a binary data.

**Comment by qwertychouskie** [comment]
This is the blend I used for the b3d: https://jacobspctuneup.tk/chocolate_12-qwerty.blend.  The XML is hard coded, so it is the source.  BTW, just to make it clear, it is definitely not finished not, just posting the WIP for suggestions and such.

**Comment by auriamg** [comment]
Let me make it very clear : "The XML is hard coded" is not acceptable and your scene will be rejected if it involves a manually modified XML file. Scenes must be made entirely in blender, with no modification to the xml

**Comment by Benau** [comment]
Also I think a win/loose scene should have as little polygon as possible...

**Comment by qwertychouskie** [comment]
@samuncle do you have the source files for "Calnaval del Cacao"?

**Comment by qwertychouskie** [comment]
@samuncle do you have the source files for "Calnaval del Cacao"?

**Comment by samuncle** [comment]
Yes, I have to check in my archives. Do you want the blend of the track or the one used in the trailer?

**Comment by qwertychouskie** [comment]
Both would be preferred, if easily accessible.

**Comment by qwertychouskie** [comment]
@samuncle Did you ever find that file?  I am hoping to get the new scene done before 0.9.3.

**Comment by qwertychouskie** [comment]
@samuncle bump?

**Comment by qwertychouskie** [comment]
@samuncle I'd love to get this into 0.9.3, but really need at least one of those files to do so.
