### ISSUE TITLE
Program keeps crashing

### ISSUE THREAD

**Issue by John6479** [supertuxkart/stk-code#2509]
This is the error message that I received:

---
## SuperTuxKart crashed :/

SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 RegisterProcTableCallback
 RegisterProcTableCallback
 RegisterProcTableCallback
 RegisterProcTableCallback
 RegisterProcTableCallback
 RegisterProcTableCallback
 RegisterProcTableCallback
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 asFreeMem
 SetManipulationInputTarget
 CallWindowProcW
 CallWindowProcW
 glDebugEntry
 SetManipulationInputTarget

**Comment by Benau** [comment]
Could you post the "stdout.log" file in %APPDATA%/supertuxkart/0.8.2 ? (you can paste that path in the address bar of windows explorer)

**Comment by MTres19** [comment]
I used to get errors like this on Intel HD 4600 graphics after updating to Windows 10. I had to battle my way through Device Manager to manually update the drivers, then it worked. But it might be a different error.

**Comment by John6479** [comment]
I do have WIndows 10; do you happen to remember how you solved the issue in Device Manager?

Here's the stdout.log file:

[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is 'C:\Users\A\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\A\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\A\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\A\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/fonts/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/po/'.
[verbose  ] translation: GetLocaleInfo langname returns 'en'.
[verbose  ] translation: GetLocaleInfo tryname returns 'US'.
[verbose  ] translation: Env var LANGUAGE = 'en_US'.
[verbose  ] translation: Language 'English (United States)'.
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_no.po: warning: ignoring, unknown language
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: Intel
[info   ] IrrDriver: OpenGL renderer: Intel(R) HD Graphics 5500
[info   ] IrrDriver: OpenGL version string: 4.3.0 - Build 20.19.15.4331
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: ARB Multi Draw Indirect Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Geometry Shader 4 Present
[info   ] irr_driver: GLSL supported.
[info   ] GUIEngine: scale: 0.512000
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : texturedquad.frag
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : uniformcolortexturedquad.frag
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\A\AppData\Roaming/supertuxkart/0.8.2/grandprix/
[info   ] ClientNetworkManager: Host initialized.
[info   ] ClientNetworkManager: Ready !
[info   ] shader: Compiling shader : colortexturedquad.vert
[info   ] shader: Compiling shader : colortexturedquad.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : object_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : normalmap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_object_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_normalmap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/DiffuseIBL.frag
[info   ] shader: Compiling shader : utils/SpecularIBL.frag
[info   ] shader: Compiling shader : IBL.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/SunMRP.frag
[info   ] shader: Compiling shader : sunlight.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlight.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : object_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : objectref_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : object_unlit.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : splatting.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : objectpass_spheremap.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : detailed_object_pass2.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_objectref_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : instanced_object_unlit.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : instanced_objectpass_spheremap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_detailed_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_grass_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : passthrough.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : tonemap.frag
[verbose  ] RaceManager: Nb of karts=1, ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] material: Track uses deprecated texture 'grass.jpg'
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 42
[warn   ] SFXManager: Throttling sfx - queue size 43
[warn   ] SFXManager: Throttling sfx - queue size 44
[info   ] Script: allchallenges: unlocked_challenges=4, challenges=25
[info   ] Script: allchallenges: unlocked_challenges=4, challenges=25
[info   ] Script: allchallenges: unlocked_challenges=4, challenges=25
[info   ] Script: allchallenges: unlocked_challenges=4, challenges=25
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : importance_sampling_specular.frag

**Comment by MTres19** [comment]
Download the **ZIP file** of the driver from [here](https://downloadcenter.intel.com/download/25948/Intel-Graphics-Driver-for-Windows-10-and-Windows-7-8-1-15-40-?product=86210), and extract it to a folder. Make sure you have the proper version---probably the 64-bit version. (I hope this is the right driver---based on the log, it should be.)

Open the start menu and type devmgmt.msc, then press enter.

Under "Display adapters" find your GPU and right click on it. Then click on "Update Driver Software..."

Choose "Browse my computer".

Choose "Let me pick from a list of device drivers..."

Choose "Have disk...", then click "Browse".

Browse to the "Graphics" folder inside the folder you extracted. The file igdlh64.inf or igdlh.inf (depending on whether you chose 32-bit or 64-bit) will be automatically selected. Click "Open".

Click "OK" in the "Install from Disk" dialog. The driver should install. Your screen might go blank for a moment, too.

That should work, at least, I think that's what I did. I disclaim all liability, of course. :) Also, this way, the driver might not automatically update---just a warning.

**Comment by John6479** [comment]
OK, I'll give that a shot.  Thanks!

**Comment by John6479** [comment]
It seems as if that fixed the problem (the program isn't crashing with that error message anymore), but now it's freezing up and not displaying any information.  Should I open up another error ticket?  Is there a log that I could post?

**Comment by deveee** [comment]
Do you have enough skills to compile and run it under debugger? It would
say where it prrcisely crashes.

The stdout.log looks fine for me.

**Comment by John6479** [comment]
Unfortunately, I do not...I'm a complete novice at these sorts of things.  I assume it's rather difficult to learn?

**Comment by John6479** [comment]
Just as an update, I installed an older version of SuperTuxKart, and it seems to be working perfectly (knock on wood).

**Comment by MTres19** [comment]
v0.8.1? That would kinda be expected since it doesn't use much (if any) advanced OpenGL.

By the way, it's only Intel graphics you have in your computer, right? Not a dual-GPU setup?

**Comment by John6479** [comment]
I'm pretty sure it's just Intel graphics.

**Comment by Benau** [comment]
Can you try the 0.9.2 release candidate?

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/

**Comment by hiker** [comment]
Closing this. Please use 0.9.3 and reopen if this is still an issue.
