### ISSUE TITLE
Blackhill Mansion objects on road

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2515]
There are Halloween objects erroneously committed which are in the way for the AI (and players). See beginning of track.

**Comment by auriamg** [comment]
Fixed in SVN

**Comment by SuicSoft** [comment]
@auriamg Is the Ravenbridge mansion track replacing Blackhill mansion ?

**Comment by qwertychouskie** [comment]
I'm sure it will eventually, but it is not complete yet.
