### ISSUE TITLE
Explosion sound effect replacement

### ISSUE THREAD

**Issue by OzoneOne** [supertuxkart/stk-code#2517]
I found an explosion sound that I feel is an improvement over STK's current sound effect: https://www.freesound.org/people/ryansnook/sounds/110113/
The sound was made by ryansnook and is licensed under CC BY-NC.

I have edited the sound to work in-game by converting it to mono, trimming silence off the end and exporting it to OGG:
[explosion.ogg.zip](https://github.com/supertuxkart/stk-code/files/317760/explosion.ogg.zip)

**Comment by qwertychouskie** [comment]
I personally like the current one better...  Just my opinion though.

**Comment by auriamg** [comment]
I agree our explosion sound could use an improvement, but this one really doesn't do : there is very bad clipping/distortion in the sound, the sound was probably louder than the mic could handle, or otherwise there was bad post-processing applied

**Comment by MTres19** [comment]
Isn't CC-BY-NC also not DFSG-compatible...? The Debian wiki only mentions CC-BY-SA-NC as being incompatible, but it doesn't say CC-BY-NC is compatible either.

**Comment by hiker** [comment]
Agreement seems to be not to change to this explosion sound - closing.
