### ISSUE TITLE
Antediluvian Abyss track is trailer version, not the finished version

### ISSUE THREAD

**Issue by MTres19** [supertuxkart/stk-code#2520]
It looks like the trailer version of Antediluvian Abyss was exported instead of the finished version: 
![abyss-2016 06 16_17 56 34](https://cloud.githubusercontent.com/assets/18179456/16138897/1b599f56-3410-11e6-88b7-2fbb89308ec1.png)

Not a big deal, of course---most people wouldn't notice. I didn't notice it myself until now.

**Comment by auriamg** [comment]
FIxed, thanks
