### ISSUE TITLE
Lighting effect displacement in 0.9.1 & 0.9.2-RC1

### ISSUE THREAD

**Issue by OzoneOne** [supertuxkart/stk-code#2524]
I have been experiencing a visual bug relating to lighting effects in the 0.9.1 stable release and in the 0.9.2 release candidate 1. It looks like all glow effects are being displaced above the objects that are producing the glow. I've taken a few screenshots to better illustrate the issue (the bug happens in all tracks, not just the tracks in the screenshots).

![lightingbug_mine](https://cloud.githubusercontent.com/assets/19967619/16175221/9c72dc4e-3639-11e6-9d63-a25c3d52d339.jpg)
![lightingbug_candela](https://cloud.githubusercontent.com/assets/19967619/16175220/9c690e76-3639-11e6-810f-088f77afedb7.jpg)
![lightingbug_volcan](https://cloud.githubusercontent.com/assets/19967619/16175222/9c748cba-3639-11e6-9cde-a2d9323dd04e.jpg)

The outline effect around item boxes and nitro canisters is not affected, and looks normal.

I am running STK on Mac OS 10.11.5
Processor: 2.2 GHz Intel Core i7
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB

I originally made a forum post about the issue here: http://forum.freegamedev.net/viewtopic.php?f=17&t=7014&sid=3cb6780cf1b9dede023eeee04f05af46

**Comment by qwertychouskie** [comment]
Can you test with various graphics settings and see which one triggers the problem?

**Comment by OzoneOne** [comment]
It happens consistently as long as the advanced graphics pipeline is turned on. Turning on or off any of the extra effects (bloom, ambient occlusion, etc.) doesn't change the problem - so it isn't caused by any of these effects in particular.

Turning off the advanced pipeline disables the lighting effects completely (as expected).

**Comment by leilei-** [comment]
The Intel HD should support the advanced pipeline.  It's intended to handle DX11-tier stuff at the least.

I did notice some corruption on the screen when an explosion is near the bottom half of the screen though, it may be related.  I can't get a screenshot since explosions happen quickly for me to react to snap one

**Comment by samuncle** [comment]
it seems to be caused by: either the volumetric fog, or the bloom, probably not the glow. Glow is only utilized to outline items and bonuses.

I also had an effect similar with god rays (sun's rays). One of the thing that triggered it was restarting a new race but not restarting the game.

**Comment by qwertychouskie** [comment]
Can you try it on Linux with the latest driver from the Intel site and see if it has the same problem?

**Comment by qwertychouskie** [comment]
If you use Ubuntu 16.04, you do not need to download the driver, as the driver included is the latest.  Otherwise, see https://01.org/linuxgraphics/downloads/intel-graphics-installer-linux-1.4.0.

**Comment by auriamg** [comment]
@qwertychouskie he is using mac OS, asking people to change OS is not an acceptable way to resolve bugs

**Comment by qwertychouskie** [comment]
All I am looking for is a test with a LiveUSB or something along those lines to help narrow down where the bug is.

**Comment by MTres19** [comment]
@qwertychouskie As far as my understanding goes, even live DVDs or flash drives are difficult with macOS. I think you have to jump through hoops with Bootcamp and even then it's hard since that's for Windows, not Linux.

However, I did read about Krita having problems with OpenGL on macOS. I seem to recall it had to do with mixing OpenGL >= 3.0 functions and old OpenGL 1.x or 2.x functions. But that might not be related.

**Comment by qwertychouskie** [comment]
Actually, for a Linux LiveUSB, all you have to do is press ALT (Command) when you hear the start-up chime and select the USB drive as the boot source.

**Comment by deveee** [comment]
@OzoneOne Could you check if it was fixed in this commit?
https://github.com/supertuxkart/stk-code/commit/46619ec62a7e74f464c7910de2c3bbefd6f14dd3

The bug in gaussian blur was causing lighting displacement for me and it's quite possible that this is the same bug.

**Comment by OzoneOne** [comment]
@deveee Yes, it's fixed for me fixed now! Thanks everybody
