### ISSUE TITLE
race_finish_victory.ogg plays much quieter than race_finish.ogg

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2527]
The file itself is fine, but it plays really quietly in the game.

**Comment by qwertychouskie** [comment]
I should also add that this is a regression from 0.9.1, and thus should be fixed before release 0.9.2 if possible.

**Comment by auriamg** [comment]
It only appears softer because it's mixed with the applause. It's already pretty much as loud as it can be. Besides you are the one who provided the sound file.

Won't fix, this is excessively minor, and will probably be replaced by a new victory song for next release anyway

**Comment by qwertychouskie** [comment]
After much in-game testing, I got a version that I like: http://jacobspctuneup.tk/race_finish_victory.ogg
It also has more complete metadata, using info from `License.txt`.  Could this version get merged?

**Comment by qwertychouskie** [comment]
@auriamg Could you merge this version before 0.9.2?  Not trying to nag, but very aware that 0.9.2 is coming very soon.

**Comment by auriamg** [comment]
Sorry this is too late, the packages were already made when you posted the new version. Fixes should be proposed before the release candidate to make sure to get them in

**Comment by qwertychouskie** [comment]
Can you at least get the updated file in the assets repo for those like me who use the Git version?

**Comment by auriamg** [comment]
Look sorry but there barely is any difference between your sound and the one currently in-game. As said, we are probably going to replace it anyway, I don't have time to replace files with such minor differences that almost no one is going to notice

**Comment by qwertychouskie** [comment]
The difference is much more noticeable in-game, (at least for me,) but it's OK if you can't merge it.
