### ISSUE TITLE
STK fails to build with current Angelscript version

### ISSUE THREAD

**Issue by FireBurn** [supertuxkart/stk-code#2528]
Even with no narrowing warnings the build then fails elsewhere

[build.txt](https://github.com/supertuxkart/stk-code/files/337518/build.txt)

**Comment by qwertychouskie** [comment]
Try building 0.9.2-rc1 instead to see if the bug has already been fixed.
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/

**Comment by FireBurn** [comment]
Yes it happens with 0.9.2-rc1 too
[build.txt](https://github.com/supertuxkart/stk-code/files/337635/build.txt)

**Comment by qwertychouskie** [comment]
Try without `-DUSE_SYSTEM_ANGELSCRIPT=ON`.

**Comment by FireBurn** [comment]
Yes that worked

**Comment by qwertychouskie** [comment]
Locally merging the changes in https://github.com/supertuxkart/stk-code/pull/2525 should fix the issue (though this will break compilation using Clang).

**Comment by ignatenkobrain** [comment]
To support new angelscript you need to locally cherry-pick: https://github.com/supertuxkart/stk-code/pull/2525/commits/6289b5fc298ac4bb48f426e3325a9bf514a603f1

but as said clang has bug...

**Comment by auriamg** [comment]
We build on OSX using clang, so if an update triggers a clang bug that could be trouble for us. What is the clang issue exactly?

**Comment by qwertychouskie** [comment]
See https://github.com/supertuxkart/stk-code/pull/2525#issuecomment-228756578.

**Comment by auriamg** [comment]
I'm sorry, I appreciate your want to update to a new version, but at the moment we have something that works file, but if we update we're getting more problems. We'd need clang to be fixed, or angelscript to work around that bug, before we can upgrade

**Comment by nado** [comment]
@FireBurn does it bother you if I make a patch from your commit https://github.com/supertuxkart/stk-code/pull/2525/commits/6289b5fc298ac4bb48f426e3325a9bf514a603f1 to use in the gentoo ebuild of stk ?

**Comment by FireBurn** [comment]
Not at all

**Comment by nado** [comment]
Sorry, I got confused, I wanted to ask to @ignatenkobrain :/ It’s already PR’d, I guess this is okay, but I still prefer to credit the right person.

**Comment by ignatenkobrain** [comment]
@nado ;) Unfortunately bug in clang is still not fixed.

**Comment by nado** [comment]
That’s why its nice having someone here providing the patch for package maintainers of distributions not supporting older versions of angelscript.

**Comment by LinuxDonald** [comment]
New clang version should come this week.
