### ISSUE TITLE
`[warn   ] Irrlicht: PNG warning: iCCP: known incorrect sRGB profile` shows up many times in terminal

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2533]
According to http://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile, "Libpng-1.6 is more stringent about checking ICC profiles than previous versions."

**Comment by qwertychouskie** [comment]
Also see https://wiki.archlinux.org/index.php/Libpng_errors.

**Comment by deveee** [comment]
IIRC you can just run optimize_data script and it should fix these warnings
too.

And the second sentence in the link that you mentioned: "You can ignore the
warning." ;)

**Comment by qwertychouskie** [comment]
I saw that, but the extra warnings make it hard to find important ones.  Not a big deal, but would be nice to have fixed.

**Comment by Benau** [comment]
Fixed now
