### ISSUE TITLE
Suggest changing the string "Play the tutorial"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2535]
I don't like when links and other stuff starts with "click here".

So i suggest changing:
"Click here to play the tutorial"

To:
"Play the tutorial"

Or even better:
"Start the tutorial"

If we go with start then maybe change this string to:
"Press fire to play the tutorial"

> "Press fire to start the tutorial"

**Comment by Benau** [comment]
![img](http://i2.kym-cdn.com/photos/images/facebook/000/043/917/hatersgonnapanda.jpg)

**Comment by qwertychouskie** [comment]
Is this really worth a whole bug?  If @scootergrisen wants, they can open a PR, but this should probably be closed as excessively minor.

**Comment by deveee** [comment]
I noticed that I already translated it as "click here to start the tutorial" :P And we don't use "click here" anywhere else (i.e. we don't have "click here to start a race", but just "start a race"), so it would give better consistency in naming. But indeed it's very minor.
