### ISSUE TITLE
Get "Not responding" dialog on Windows 7

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2536]
STK 0.9.2 on Windows 7.

First time i run STK i get a dialog from Windows that the program is not responding.

Maybe some adjustments could be made to avoid this dialog.

**Comment by auriamg** [comment]
This also happens on OSX, probably we should let things "breath" a little while loading. Not exactly sure how, though

**Comment by scootergrisen** [comment]
When ever i start STK and also change resolution or toggle fullscreen the characters icons load at the bottom of the screen which seems to be the heayeste things to load.
Would it perhaps be a good idea to wait loading this untill they are needed?
I mean if you load lets say Tux but you start a game without Tux does Tux really need to be loaded?
Or perhaps wait and load some stuff untill you start the first game.

**Comment by Arthur-D** [comment]
All character models need to be loaded for the kart selection screen or
looking through several karts before deciding will take more time and not
look smooth. However one optimization would be to only load the last
selected category of karts, so for example if you selected the addons
category only the addon karts would be loaded at startup. Of course, if you
select the All category all models need to be loaded.
3. jul. 2016 1.02 p.m. skrev "scootergrisen" <notifications@github.com>:

**Comment by auriamg** [comment]
@Arthur-D  this is not fully accurate, we could in theory stream the models when needed, though this is probably non-trivial. This is however not the only way to fix the non-responsive issue

**Comment by qwertychouskie** [comment]
See http://stackoverflow.com/questions/6997310/busy-application-leads-to-false-not-responding-state-on-windows-7-wm-update#answer-6997423.

**Comment by SuicSoft** [comment]
@auriamg When loading a track on my laptop using Windows 10 it also shows not responding. This does not happen on elementary OS (I triple boot Windows 10 , elementary OS and Remix OS)

**Comment by qwertychouskie** [comment]
According to https://stackoverflow.com/questions/402832/avoiding-not-responding-label-in-windows-while-processing-lots-of-data-in-on?noredirect=1&lq=1, it seems STK just needs to call [PeekMessage()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644943(v=vs.85).aspx) every few seconds.

**Comment by auriamg** [comment]
This is basically correct but PeekMessage is windows-only, a more proper fix would be to split the loading process so that either it runs in a separate thread (may be difficult since OpenGL is not multithread-safe) or otherwise simply split loading into smaller chunks and let the event loop run after each chunk

**Comment by deveee** [comment]
More proper is irr device -> run() and indeed it helps a bit when it's
executed every few seconds. But some things may be not initialized before
the game is loaded. Also what if user will try to close a window before
it's fully initialized?

2017-07-25 0:46 GMT+02:00 auriamg <notifications@github.com>:

**Comment by Benau** [comment]
maybe something like this
```
        g_device->setEventReceiver(NULL);
        g_device->run();
        g_device->setEventReceiver(EventHandler::get());
```
inside engine.cpp renderLoading, this will also allow showing render icon for OSX
