### ISSUE TITLE
Window uses generic icon

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2538]
STK 0.9.2 on Windows 7.

When i run STK in window mode there is just a generic icon on the window/task bar.

I suggest adding the STK icon to the window.

**Comment by auriamg** [comment]
I cannot reproduce this issue, I get a "Tux" icon in the task bar

**Comment by scootergrisen** [comment]
If i try chaning the icon in Windows i get %ProgramFiles%\SuperTuxKart\icon.ico not found.
So it seems "it" tries to get the icon from this path that does not exists:
C:\Program Files\SuperTuxKart
It should get it from:
C:\Program Files (x86)\SuperTuxKart

So some difference between 32-bit and 64-bit version.
It seem when i run STK in window mode i can see the icon on the task bar but not the window switcher.
But in fullscreen they are both generic.

**Comment by auriamg** [comment]
Ah are you by chance using the 64-bits version of STK? That could explain it

**Comment by deveee** [comment]
The 64-bit version doesn't have an installer, shortcuts etc.

But I wonder why do we use the .ico file for shortcut. This icon is linked with .exe file as a resource and it should be enough to create a shortcut. There is no need to use separate .ico file. It is 
```CreateShortCut "$SMPROGRAMS\$STARTMENU_FOLDER\SuperTuxKart.lnk" "$INSTDIR\supertuxkart.exe" "" "$INSTDIR\icon.ico"```
in our windows installer.

**Comment by qwertychouskie** [comment]
Actually, when a 32-bit program (STK) is run, references to `%ProgramFiles%` return `C:\Program Files (x86)\`, see http://stackoverflow.com/questions/9594066/how-to-get-program-files-x86-env-variable/9608782#9608782.

**Comment by qwertychouskie** [comment]
@scootergrisen Try clearing the icon cache, see http://www.sevenforums.com/tutorials/49819-icon-cache-rebuild.html.

**Comment by qwertychouskie** [comment]
@scootergrisen Did clearing the icon cache fix it?

**Comment by Alayan-stk-2** [comment]
Running 0.9.3 or git on Linux Mint 18.3, I also get a generic window icon on my taskbar.

If I use the version in the repos of my distro (which is 0.9.2), I get a STK icon. I suspect the difference is in the packaging difference, not in the game version.

**Comment by scootergrisen** [comment]
Now i run SuperTuxKart 0.10.0-rc1 and first i saw the correct icon in the task bar but generic icon in the window switcher (Alt+Tab).

Then i cleared the icon cache and now both icons are generic.

**Comment by qwertychouskie** [comment]
Did you restart the computer after clearing the cache?  Also, if you launched STK after clearing the cache but before rebooting, it might cause problems.

**Comment by scootergrisen** [comment]
I clear icon cache and restart computer without starting SuperTuxKart 0.10.0-rc1 64 bit.
Then i start Windows 7 and start STK and first time it had generic icon on task bar.
![1](https://user-images.githubusercontent.com/1836590/55951387-69e47200-5c57-11e9-9851-27209cc3fb72.jpg)

Close STK and start STK again and now it have the correct STK icon on the task bar.
![2](https://user-images.githubusercontent.com/1836590/55951396-6ea92600-5c57-11e9-8d59-46ea8ad4679c.jpg)

But always generic icon in window switcher (Alt+Tab).
![windowswitcherwindows7](https://user-images.githubusercontent.com/1836590/55951372-5df8b000-5c57-11e9-90b7-f40c4c10fc3e.jpg)

Sometimes the icon on the task bar turns into a kind of generic document icon.
![3](https://user-images.githubusercontent.com/1836590/55951404-749f0700-5c57-11e9-962d-c9dc197b7b11.jpg)

Sometimes i get blinking as if something else have been loaded.
Perhaps supertuxkart.exe is loading something else?
I saw this in other software i think it was Vim there an .exe was loading another .exe or something like that which gave problem with the icon.
![blink](https://user-images.githubusercontent.com/1836590/55951473-9ef0c480-5c57-11e9-994a-85b8b4458503.gif)

Perhaps the icons in supertuxkart.exe does not contain the required icon size for the window switcher?

Can someone compare the icon sizes in supertuxkart.exe 32 bit and 64 bit to see if they contain the same sizes?

**Comment by scootergrisen** [comment]
Now i got a dialog with the title "SuperTuxKart crashed :/" which also have a generic icon.
The string is at https://github.com/supertuxkart/stk-code/blob/master/src/utils/crash_reporting.cpp#L110
Maybe it can help someone.

**Comment by Benau** [comment]
can you try the 1.1-rc1 and see if you see tux kart icon?

**Comment by scootergrisen** [comment]
Only time i see the generic icon now is using Alt+tab just after running the installer during the "Verifying installer" dialog.
I see the STK icon both on the process bar and in the dialog. But the Alt+tab list have generic icon.

**Comment by Benau** [comment]
you mean you only see generic icon from alt+tab for the installer?

**Comment by scootergrisen** [comment]
Only time i see the generic icon now is during "Verifying installer" which usually is the first few seconds after you run the exe file.
![v](https://user-images.githubusercontent.com/1836590/71319177-222b1100-249b-11ea-8dd1-9894714f784a.gif)
When the "Verifying installer" dialog goes away the icon is the STK icon.

**Comment by Benau** [comment]
Ok then this is nsis problems.....
