### ISSUE TITLE
Speed bar don't show correct value

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2539]
STK 0.9.2 on Windows 7.

For some reason there are problems with the bars that show how fast the different karts are.

The speed bar is always near the left and some karts seem to give the bar a negative value so it just seem all karts have near 0 speed.

**Comment by Benau** [comment]
![img](http://www.phrases.org.uk/images/picture-is-worth-a-thousand-words.jpg)

**Comment by qwertychouskie** [comment]
I get this sometimes, try restarting the game.

**Comment by scootergrisen** [comment]
Strange i can't see to get it to fail and i'm not sure if it was Linux og Windows.
I will try some more testing once in a while and see if i can get it to fail again.
