### ISSUE TITLE
Some characters are not showed correctly (like æ) in Debian Jessie

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2540]
When running STK 0.9.2 or a previous version on Linux (Debian Jessie) there is are a problem with some characters that are not showed correctly.

On the very first screen in my language it says "INDLæSER" (LOADING in english).
The æ is not showned correct like the other characters and are blurred.
Same goes for other characters on other pages.

I think i talked with someone about it on IRC and i think it turned out that Debian Jessie was using a older version of some library that caused it and updated that library fixed it... i think.

Anyway i don't know what the correct way to fix it would be, its just a shame that the very first screen the user seen have a problem... in my language at least.

**Comment by Benau** [comment]
Because your system locale is not installed properly, so to uppercase function in scalsble font failed

**Comment by scootergrisen** [comment]
![stk6](https://cloud.githubusercontent.com/assets/1836590/16540488/e4026fe8-4066-11e6-9143-1c2ece6e5d21.png)
![Uploading stk7.png…]()

**Comment by scootergrisen** [comment]
I don't if it was you i talked about it some time ago but could you collect info about how to fix it for Debian Jessie.
Is this a general problem on Linux distributions or just Debian Jessie?

**Comment by Benau** [comment]
... or easier, no more capitalization for title font

**Comment by scootergrisen** [comment]
I would prefer to fix the problem.
Some strings will start with a big character.

**Comment by auriamg** [comment]
A better fix might be to replace std::towupper by a replacement that is unicode-aware and can produce upper-case characters, for instance maybe http://site.icu-project.org/ ( http://userguide.icu-project.org/transforms/casemappings )

However, as pointed out by Benau, if you install the corresponding locale on your system it should also work. Since people are unlikely to play the game in locales they don't use, this is fairly minor

**Comment by scootergrisen** [comment]
I was talk on IRC i think how to do it but i forgot.
Maybe someone that know how could write it here so maybe it can help other people to.

**Comment by scootergrisen** [comment]
I don't think it helps installing corresponding locale. Are you sure that should fix it?
I think i talking to someone on IRC about it before and it was a problem with a library i think.
Maybe because stuff in Debain Jessie is not using the new version.
But i don't remember the solution.

**Comment by scootergrisen** [comment]
Perhaps this is the solution:
https://gist.github.com/Benau/93c9b9cc356c5a9bb1c1

**Comment by auriamg** [comment]
I've suggested to Benau that similar solution could be used, but maybe only for "special" characters, not trying to make a full list

**Comment by Benau** [comment]
New font render engine is used, should be fixed in git

**Comment by scootergrisen** [comment]
I tried installing SuperTuxKart 1.1.0-rc1 installer-64bit.exe and i am pretty sure i saw "Indl ser" with a missing "æ" at least the first time i launched STK.
Should be "Indlæser".

It's "Indlæser" now so i don't know why i saw "Indl ser" the first time.
Maybe it needed to be rendered to cache one time before "æ" can be used.

How do i clean the font cache if such exists?

**Comment by Benau** [comment]
there is not font cache......

**Comment by scootergrisen** [comment]
Maybe its because i had version x installed and then i install newer version so i have multiple versions at the same time and perhaps the new version is trying to use old settings or something.

**Comment by scootergrisen** [comment]
I can't seem to take screenshot during the loading screen.
But it looks like this. "æ" is missing on first start of STK. But then after restating STK the "æ" is there.
![indl_ser](https://user-images.githubusercontent.com/1836590/71522547-74b66400-28c5-11ea-9eee-930dd3eba7bc.gif)

**Comment by Benau** [comment]
Probably your gpu is too busy that moment...
