### ISSUE TITLE
Change path .../0.8.2/... to something without version number

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2541]
Would it not be a good idea to change the path that have /0.8.2/ in them to something without a version number?

Its a little strange/confusing that when i run STK 0.9.2 the path is called /0.8.2/.

Can be seen in the terminal when starting STK:
[error  ] UserConfig: Could not read user config file '/home/[USERNAME]/.config/supertuxkart/0.8.2/config.xml'.

**Comment by auriamg** [comment]
This is an internal/technical name that users usually do not see, so the name is not very important. Unless someone has a grooundbreaking suggestion to make, at the moment we seem to have very little to gain by changing it. It's just the number of the version where file formats were last changed, I don't have any really better idea to propose

**Comment by scootergrisen** [comment]
I just think it would be more logical that STK 0.9.2 would use:

    /home/[USERNAME]/.config/supertuxkart/0.9.2/'.

If the user have both STK 0.8.2 and STK 0.9.2 on the system i would be confusing that STK 0.9.2 would load the files from:

    /home/[USERNAME]/.config/supertuxkart/0.8.2/'.

The version i have with apt-get in Debian Jessie is 0.8.1-2+b2 and that seem to use a blank version number so when i start it from terminal it says:

    [info   ] FileManager: User directory is '/home/[USERNAME]/.config/supertuxkart/'.
    [debug  ] main: Error messages and other text output will be logged to /home/[USERNAME]/.config/supertuxkart//stdout.log.

**Comment by Arthur-D** [comment]
Most people will start the game from an icon on the desktop or menu and
will not see what our internal versioning looks like. It does not need to
be logical for the few that do, since they should look at  Credits or their
package version number (assuming they follow ours).
3. jul. 2016 1.23 p.m. skrev "scootergrisen" <notifications@github.com>:

**Comment by deveee** [comment]
It was discussed many times. The version number will be changed when we will break compatibility with older versions. The config from 0.9.2 is compatible with 0.9 (aka. 0.8.2), so there is no reason to change it.

There are two ways to solve this:
- make an importer that will copy files from 0.8.2 directory to 0.9.2 firectory in the first run
- use different version numbers, for example 0.8.2 will be 0.1, and then when we will break compatibility, we will use 0.2 directory etc. But then people still will complain that version 0.9.2 uses config from 0.1 directory :-P

And there is probably still opened (or closed ;) ) similar bug report somewhere.

For now I'm closing it as wontfix.

**Comment by deveee** [comment]
Oh, this is actually already closed :)

**Comment by scootergrisen** [comment]
It seems it it not entirely true that the normal user never have to see the path because screenshots seems to be stored inside.
Unless you don't consider screenshots something that a normal user would use.
