### ISSUE TITLE
Some [warn   ] [IrrDriver Temp Logger]

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2543]
When downloading STK 0.9.2 (not using apt-get) and running in Debian Jessie i get these warnings that someone might want to know about so maybe they can be fixed:

```
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:
```

**Comment by auriamg** [comment]
Could you please post the full lost, so that we may get more context as to where this error happens?

**Comment by scootergrisen** [comment]
Here are all the terminal ouput from startering the game with run_game.sh and quitting the game.

    Running 64-bit version...
    [verbose  ] main: Error messages and other text output will be logged to /home/[USERNAME]/.config/supertuxkart/0.8.2/stdout.log.
    [info   ] [FileManager]: Data files will be fetched from: 'data/'
    [info   ] [FileManager]: User directory is '/home/[USERNAME]/.config/supertuxkart/0.8.2/'.
    [info   ] [FileManager]: Addons files will be stored in '/home/[USERNAME]/.local/share/supertuxkart/addons/'.
    [info   ] [FileManager]: Screenshots will be stored in '/home/[USERNAME]/.cache/supertuxkart/screenshots/'.
    [info   ] [FileManager]: User-defined grand prix will be stored in '/home/[USERNAME]/.local/share/supertuxkart/grandprix/'.
    [info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
    [info   ] [FileManager]: Asset 1 will be loaded from 'data/gfx/'.
    [info   ] [FileManager]: Asset 2 will be loaded from 'data/grandprix/'.
    [info   ] [FileManager]: Asset 3 will be loaded from 'data/gui/'.
    [info   ] [FileManager]: Asset 4 will be loaded from 'data/library/'.
    [info   ] [FileManager]: Asset 5 will be loaded from 'data/models/'.
    [info   ] [FileManager]: Asset 6 will be loaded from 'data/music/'.
    [info   ] [FileManager]: Asset 7 will be loaded from 'data/replay/'.
    [info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
    [info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
    [info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
    [info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
    [info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
    [info   ] [FileManager]: Asset 13 will be loaded from 'data/ttf/'.
    [info   ] [FileManager]: Asset 14 will be loaded from 'data/po/'.
    [verbose  ] translation: Env var LANGUAGE = 'da_DK.utf8'.
    [verbose  ] translation: Language 'Danish (Denmark)'.
    Adding language fallback da
    Irrlicht Engine version 1.8.0
    Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64
    [warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig
    
    [warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:
    
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:
    
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:
    
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:
    
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:
    
    
    [warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:
    
    
    [info   ] IrrDriver: OpenGL version: 3.3
    [info   ] IrrDriver: OpenGL vendor: X.Org
    [info   ] IrrDriver: OpenGL renderer: Gallium 0.4 on AMD REDWOOD
    [info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.3.2
    [info   ] GLDriver: AMD Vertex Shader Layer Present
    [info   ] GLDriver: ARB Buffer Storage Present
    [info   ] GLDriver: ARB Base Instance Present
    [info   ] GLDriver: ARB Texture Storage Present
    [info   ] GLDriver: ARB Uniform Buffer Object Present
    [info   ] GLDriver: ARB Explicit Attrib Location Present
    [info   ] irr_driver: GLSL supported.
    [info   ] Freetype Environment: Loading fonts...
    [info   ] Freetype Environment: DPI for Normal Font is 25.
    [info   ] Freetype Environment: DPI for Title Font is 54.
    [info   ] Freetype Environment: DPI for Digit Font is 38.
    [info   ] ScalableFont::loadTTF: Created 15 glyphs supporting 16 characters for high-res digits font Sigmar using 1 glyph page(s).
    [info   ] ScalableFont::loadTTF: Created 61 glyphs supporting 88 characters for bold title font Ubuntu using 1 glyph page(s).
    [info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu using 1 glyph page(s).
    [info   ] shader: Compiling shader : texturedquad.vert
    [info   ] shader: Compiling shader : texturedquad.frag
    [info   ] shader: Compiling shader : texturedquad.vert
    [info   ] shader: Compiling shader : uniformcolortexturedquad.frag
    [info   ] shader: Compiling shader : colortexturedquad.vert
    [info   ] shader: Compiling shader : colortexturedquad.frag
    [info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
    [info   ] GrandPrixManager: Loading Grand Prix files from /home/[USERNAME]/.local/share/supertuxkart/grandprix/
    [verbose  ] Thread: Start waiting 2886746.936000
    [verbose  ] Thread: Stop waiting 2886748.943000
    [verbose  ] Thread: Waited for more than 2.000000 seconds for thread to become deleteable
    [info   ] Thread: News manager not stopping, exiting anyway.

**Comment by auriamg** [comment]
Does this prevent the game from running correctly, or is it only warnings?

I think it might be irrlicht experiencing issues with its first attempt, but then succeeding when it falls back to another config

**Comment by deveee** [comment]
They are just harmless warnings.

The ```[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig``` line means that STK wasn't albe to create OpenGL 4.3 context, and that then it successfully created 3.3 context because the line is displayed only once. 

The shaders compilation errors are there since STK 0.9 for mesa drivers. These shaders are from irrlicht code, not from our data directory, and most probably we don't use it at all. It can be solved by adding ```if (!useCoreContext)``` line somewhere in irrlicht. 

I'm marking it as minor because it doesn't break anything.

**Comment by scootergrisen** [comment]
I have no problem running the game.
