### ISSUE TITLE
Suggest changing filename of "icon.ico"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2551]
Maybe change filename:
icon.ico

To:
supertuxkart.ico

**Comment by deveee** [comment]
Omg, change the icon name??? Where this icon is used at all? The icon is linked with exe file as a resource, so the .ico file is not needed at all in already compiled package.

There is 10000 more important things to do in STK. If you want to do something useful, you can for example try to reproduce this bug and provide logs from valgrind:
https://github.com/supertuxkart/stk-code/issues/2169
There is a chance that when you will start a race, it will print a message about uninitialized variable, already deleted object or overwritten part of memory in the code related to sound effects.

I'm closing this ticket as invalid.
