### ISSUE TITLE
Suggest changing "Apply new resolution" to "Apply"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#2552]
When i go change the resolution og fullscreen in STK the button is called "Apply new resolution".

But if i only want to change the graphics settings like and still use the same screen resolution the button name don't make sense.

So maybe change button name to just "Apply".

**Comment by auriamg** [comment]
I've been patient but let me state things more clearly. This bug tracker is meant to report **bugs, crashes, problems that prevent gameplay, spelling errors, etc.**  

Please filter what you post to only post actual problems and not whatever unimportant trivialities cross your mind.

BTW: for this specific case, the "apply" button is a popup so the scope is very clear and there is no ambiguity as to what it does. The "Apply new resolution" button is not, so we need to change its text a bit to indicate what it does.

**Comment by qwertychouskie** [comment]
Besides, graphics quality level changes are applied immediately, so the "Apply new resolution" button is not needed for this.

**Comment by auriamg** [comment]
They are needed when you use a gamepad. With a mouse you can click on the one you want, but with a gamepad you need to cycle through the list to get the one you want
