### ISSUE TITLE
support of nouveau driver ?

### ISSUE THREAD

**Issue by manonam** [supertuxkart/stk-code#2555]
Hi all, 
First, thanks a lot for the very good game.
I have read that: #2386 (which speaks about nouveau)
Can we hope for having nouveau driver (opensource alternative to nvidia's drivers) working one day ?

- Using the debian package of stk: version 0.8.1-2+b2
I could play only in small resolution (changes in setting were uneffective).

- And using latest git version: the game starts, but as soon as I click on Solo or Multiplayer, it crashes with:
`
...
[0m[info   ] shader: Compiling shader : utils/getLightFactor.frag[0;;m
[0m[info   ] shadernouveau: kernel rejected pushbuf: Argument invalide
nouveau: ch0: krec 0 pushes 53 bufs 54 relocs 0
nouveau: ch0: buf 00000000 00000005 00000004 00000004 00000000
nouveau: ch0: buf 00000001 00000016 00000004 00000004 00000000
nouveau: ch0: buf 00000002 00000011 00000002 00000002 00000000
nouveau: ch0: buf 00000003 00000007 00000002 00000002 00000002
nouveau: ch0: buf 00000004 00000008 00000002 00000002 00000002
nouveau: ch0: buf 00000005 0000000b 00000002 00000002 00000002
nouveau: ch0: buf 00000006 0000000a 00000002 00000002 00000002
nouveau: ch0: buf 00000007 00000006 00000004 00000000 00000004
nouveau: ch0: buf 00000008 000001f6 00000002 00000002 00000002
nouveau: ch0: buf 00000009 000001fe 00000004 00000004 00000000
nouveau: ch0: buf 0000000a 000001da 00000002 00000002 00000002
nouveau: ch0: buf 0000000b 0000025e 00000004 00000004 00000000
nouveau: ch0: buf 0000000c 00000207 00000002 00000002 00000002
nouveau: ch0: buf 0000000d 0000028e 00000004 00000004 00000000
nouveau: ch0: buf 0000000e 0000029c 00000002 00000002 00000000
nouveau: ch0: buf 0000000f 0000028f 00000002 00000002 00000002
nouveau: ch0: buf 00000010 0000029d 00000002 00000002 00000002
nouveau: ch0: buf 00000011 0000000d 00000004 00000004 00000000
nouveau: ch0: buf 00000012 00000290 00000004 00000004 00000000
nouveau: ch0: buf 00000013 00000294 00000004 00000004 00000000
nouveau: ch0: buf 00000014 00000297 00000004 00000004 00000000
nouveau: ch0: buf 00000015 00000299 00000004 00000004 00000000
nouveau: ch0: buf 00000016 0000028c 00000004 00000004 00000000
nouveau: ch0: buf 00000017 0000029a 00000002 00000002 00000002
nouveau: ch0: buf 00000018 0000029b 00000002 00000002 00000002
nouveau: ch0: buf 00000019 0000029e 00000004 00000004 00000000
nouveau: ch0: buf 0000001a 0000029f 00000004 00000004 00000000
nouveau: ch0: buf 0000001b 000001ee 00000002 00000002 00000002
nouveau: ch0: buf 0000001c 000002a1 00000004 00000004 00000000
nouveau: ch0: buf 0000001d 000002a0 00000002 00000002 00000002
nouveau: ch0: buf 0000001e 000002a2 00000004 00000004 00000000
nouveau: ch0: buf 0000001f 00000209 00000002 00000002 00000002
nouveau: ch0: buf 00000020 000002a3 00000004 00000004 00000000
nouveau: ch0: buf 00000021 000002a4 00000002 00000002 00000002
nouveau: ch0: buf 00000022 000002a5 00000002 00000002 00000002
nouveau: ch0: buf 00000023 00000270 00000002 00000002 00000002
nouveau: ch0: buf 00000024 00000262 00000002 00000002 00000002
nouveau: ch0: buf 00000025 00000012 00000002 00000002 00000002
nouveau: ch0: buf 00000026 00000013 00000002 00000002 00000000
nouveau: ch0: buf 00000027 00000203 00000002 00000002 00000000
nouveau: ch0: buf 00000028 00000291 00000004 00000004 00000000
nouveau: ch0: buf 00000029 00000205 00000002 00000002 00000000
nouveau: ch0: buf 0000002a 000002a8 00000004 00000004 00000000
nouveau: ch0: buf 0000002b 000002a7 00000002 00000000 00000002
nouveau: ch0: buf 0000002c 00000277 00000002 00000002 00000002
nouveau: ch0: buf 0000002d 00000278 00000002 00000002 00000002
nouveau: ch0: buf 0000002e 00000271 00000002 00000000 00000002
nouveau: ch0: buf 0000002f 0000027c 00000002 00000002 00000000
nouveau: ch0: buf 00000030 0000028d 00000002 00000002 00000000
nouveau: ch0: buf 00000031 00000298 00000002 00000002 00000000
nouveau: ch0: buf 00000032 00000265 00000002 00000000 00000002
nouveau: ch0: buf 00000033 00000276 00000002 00000002 00000002
nouveau: ch0: buf 00000034 000002aa 00000004 00000004 00000000
nouveau: ch0: buf 00000035 000002a9 00000002 00000002 00000002
nouveau: ch0: psh 00000000 0000000000 000000ae20
nouveau: 	0x20010e08
nouveau: 	0x00001b02
nouveau: 	0x8000036d
nouveau: 	0x80000372
nouveau: 	0x800005a3
...
`
do you think it should go to nouveau's bug list instead ? or is it a bug in calling 
`pushbuf: Invalid argument `

Thx

**Comment by MTres19** [comment]
Install the package `mesa-utils` and post the output of `glxinfo | grep OpenGL`.

I think glxinfo provides the name of your graphics card, but if not, what is it?

**Comment by deveee** [comment]
I was testing STK with nouveau before 0.9.2 release and it was working surprisingly good for me. I had only black screen in windowed mode, but in fullscreen mode it was working fine, even with shadows, global illumination, texture compression etc.

Maybe try to run it with current mesa version to see if it still crashes?

This indeed looks like bug in drivers (this shader compiles fine with other mesa drivers), but I can't say it for sure. Maybe @imirkin could say something more.

**Comment by MTres19** [comment]
The fact that packaged version of STK is 0.8.1 makes me doubt that Mesa is up-to-date either. Perhaps whatever older version of Mesa is being used simply doesn't support OpenGL 3.1.

**Comment by auriamg** [comment]
Indeed knowing the version of mesa would help. The terminal output from STK would also be helpful

**Comment by manonam** [comment]
I was trying to compile / run latest git version with old dependences. so I think the problem came from that.
I upgraded to debian testing (stretch), and I can now run without problem* both the package version 0.9.1-3+b1 and the git latest.
for info:
`
glxinfo | grep OpenGL
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVD9
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.2
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
`
`VGA compatible controller: NVIDIA Corporation GF119 [GeForce GT 610]`
*: The game works well with nouveau but with special effect value to 2. not more (else it lags).

So I think it is ok to close this issue.
Thank you !
