### ISSUE TITLE
I can't configure controllers

### ISSUE THREAD

**Issue by Danfun64** [supertuxkart/stk-code#2557]
This issue was already mentioned by @Daimanu06 in #2240, but I feel like I should point out that this is also a general issue, as I have experienced the same issue with both a Logitech f310 (xinput mode) and a Wii classic controller pro. 

I'm using Xubuntu 16.04 64-bit, and am currently using the official 0.9.2 binary....

edit: I get the same exact issue when using STK on Windows 10.

**Comment by auriamg** [comment]
Is there a developer who can reproduce this issue and investigate?

**Comment by LoadingPleaseWait** [comment]
I've attempted to reproduce the issue on Ubuntu 16.04 with an Xbox 360 controller but I haven't been able to find any bugs with reconfiguring my input devices. I tried with the 0.9.2 branch and the official release binary. Are you only having issues with those two controllers?

**Comment by Danfun64** [comment]
IDK. Sorry. I don't have any other controllers to test atm.

**Comment by LoadingPleaseWait** [comment]
I'll try to borrow a Wii controller from a friend. Are you able to play other games using those controllers?

**Comment by MTres19** [comment]
I've never had this problem with an old Gravis Destroy Tiltpad—I believe Windows shows it as a generic "HID-Compliant Gamepad". But this seems to be about more advanced controllers, and I haven't tried to reconfigure it recently anyway.

**Comment by Danfun64** [comment]
I tested other games with both controllers and in both cases they worked correctly.

**Comment by LoadingPleaseWait** [comment]
My friend was unable to connect his wiimote to his computer so I would go with what others are saying.

**Comment by Danfun64** [comment]
For the record, I can bind controls in 0.8.1-updates. Must have been a change that happened after 0.8.1 that broke things...

**Comment by Danfun64** [comment]
Something I found out today. I have less problems configuring the controllers when only one is connected at a time. Maybe it has to do with them being two different types of controllers?

**Comment by qwertychouskie** [comment]
@Danfun64 A lot of gamepad issues were recently fixed, can you test the Git version to see if your issue is fixed?

**Comment by auriamg** [comment]
...or just wait for next version which should come soonish

**Comment by qwertychouskie** [comment]
@Danfun64 Could you test this with 0.9.3 and see if it's still an issue?

**Comment by Danfun64** [comment]
I haven't played STK in a while. I'll try to get things set up again within a week.

**Comment by Danfun64** [comment]
Sorry for taking so long. I can only change the controls properly if I select using the gamepad. If I try to either use the enter key or click on the control I want to be changed, it immediately accepts whatever "input" had been received.

**Comment by Danfun64** [comment]
I tested with 17b83ac321e620b0bb36fa8990da945fe5dde1a1

**Comment by Benau** [comment]
For linux can you try compile latest git?
For windows can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200427/SuperTuxKart-git20200427-win.zip/download

**Comment by Alayan-stk-2** [comment]
Please open a new ticket if the issue persists in STK 1.2 In the meantime, I'll close this as not applicable anymore as we now rely on SDL2 for gamepad handling.
