### ISSUE TITLE
A small error in the french translation

### ISSUE THREAD

**Issue by Cyberpangolin** [supertuxkart/stk-code#2558]
in fr.po, "vous" and "tu" are confused and used without any distinction in Nolok's speech. My suggestion is to change all to "tu", because it's mainly used. Then, it would look a bit more "french" and less "translated". 2 strings are concerned:

```

msgid "What's wrong, little hippies? Your great gnu leader is missing?"
 msgstr "Qu’y a-t-il, petits hippies ? Votre chef le grand gnu est absent ?"

```

Should be: 

 ```

msgid "What's wrong, little hippies? Your great gnu leader is missing?"
msgstr "Qu’y a-t-il, petit hippie ? Ton chef le grand gnu a disparu?"

```

(note: I changed "est absent" to " a disparu" too.)
.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.

```
msgid ""
" But you pathetic little twerps will never be able to beat me - King of the "
"Karts!"
msgstr "Mais jamais de pathétiques petits abrutis comme vous ne réussiront à me vaincre moi, le roi du karting !"

```

```

msgid ""
" But you pathetic little twerps will never be able to beat me - King of the "
"Karts!"
msgstr "Mais jamais un pathétique petits abruti comme toi ne réussira à me vaincre, moi, le roi du karting !"
```

**Comment by auriamg** [comment]
Hi,

the best way to fix that is actually to go on Transifex and contribute better translations yourself :) do you think you would be interested in doing that?

**Comment by farfadet46** [comment]
Maybe you can change the word "abruti" because it's a bad word, i think 'idiot' is more appropriate.

**Comment by nado** [comment]
There are so much more faults in your translated strings… You mix plural and singular forms everywhere. Why change a plural form to a french singular form too ?

And "abruti" or "idiot" are now kinda equals in meaning, but "abruti" looks more like old familiar french form, when "idiot" is more widely used now.

**Comment by auriamg** [comment]
As mentionned previously, github is not the right place for translations, if you wish to contribute please go on transifex
