### ISSUE TITLE
Better support for 2 wheeled vehicles

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2560]
Sara's 'bikes' tilt in the wrong direction (motor bikes would lean in the opposite direction from karts).
- [x] Fix support for modifying characteristic in kart.xml file
- [ ] adjust Sara model to have a negative lean max="" value

**Comment by hiker** [comment]
I am not sure if the exporter need to be modified to support setting of kart characteristics (see svn r16714). The .blend files for sara need to be adjusted, though it might be worth tuning the leaning a bit first.

**Comment by hiker** [comment]
Auria, can you check if the exporter needs updating, and to update the .blend files for sara?

**Comment by auriamg** [comment]
@hiker, you are referring to this part right? Could you explain how it works, I'm not sure how that works and what should appear in the interface
```
<lean max="*0-10"/>
<lean max="*0-6.6"/>
```

**Comment by hiker** [comment]
That is part of the kart characteristic syntax which we received a while ago. It basically takes the existing base value (i.e. from data/kart_characteristics.xml, and then applies the formula, i.e. "old value * 0 -10"  ... or setting it to -10. I admit I don't like the syntax currently being used (e.g. I can't simply write '-10', since this will be interpreted by the code as 'old value - 10'.
It might be worth improving that code a bit that we can use (e.g.) 'x' to indicate the current value, then we could distinguish the different cases better:
x+5   --> increase the base value by 5
5     --> overwrite the base value with 5
-5 --> overwrite base value with -5.
But that's for a different ticket ;)

Ideally the exporter should allow the user to specify any arbitrary xml entries to overwrite/extend kart characteristics. So a simple string where those entries could be listed should be sufficient.

**Comment by Benau** [comment]
Some ideas: some karts when doing leaning looks strange...

like Gnu, Xue (karts without wheels), Sara the wizard(snowmobile can't have leaning when turning even in real life?)

<lean max="*0"/> can disable leaning for them...

**Comment by qwertychouskie** [comment]
I personally think Xue leaning is fine, and after some testing, a negative value for Gnu (I tried -10.0) seems good.

**Comment by auriamg** [comment]
Exporter done in SVN
