### ISSUE TITLE
Different timer may lead to different game behaviour

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2562]
https://github.com/supertuxkart/stk-code/compare/fix_timer

if(World::getWorld()->getTime()-m_time_last_crash < 0.5f) return; will always be true in the past, if timer is count backwards (like in follow the leader/ soccer mode with time target)

Now further "grep -rn ", and (for example)float Kart::getStartupBoost() const has usage of this function too,
@hiker, does it need a "getTimeSinceStart" too?

Also there are quite more files are using this fuction...

**Comment by Benau** [comment]
( World::getWorld()->getTime() - powerup_manager->getBallCollectTime()) in void Powerup::hitBonusBox(const Item &item, int add_info) and     if(time - m_collision_times.back() < 0.2f) in void AIBaseController::crashed(const Material *m) might be affected too

**Comment by Benau** [comment]
In follow the leader:

gdb float Kart::getStartupBoost()
```
(gdb) p t
$5 = 29.8490009
(gdb) p startup_times
$6 = std::vector of length 2, capacity 2 = {0.300000012, 0.5}
```

guess affected...

**Comment by hiker** [comment]
As far as I see (from a quick look):
getStartupBoost needs to have time since starts.
Powerup::hitBonusBox() as well
AIBaseController::crashed() as well

Not sure if this is complete ;(

**Comment by Benau** [comment]
Branch merged
