### ISSUE TITLE
STUN code issues

### ISSUE THREAD

**Issue by AlexanderOlkhovskiy** [supertuxkart/stk-code#2566]
I've been experimenting with STK STUN code (to be more precise with [f2c26f0](https://github.com/supertuxkart/stk-code/blob/f2c26f06f1b30f592824e128e11fb71022df3353/src/network/protocols/get_public_address.cpp) revision of `get_public_address.cpp`; see https://github.com/AlexanderOlkhovskiy/stk-stun-test) and noticed some issues:

1. STUN message in `createStunRequest` is sent with an extra 0 byte, which makes it invalid.
The 21th zero byte was there since the initial implementation (in [613e97d](https://github.com/supertuxkart/stk-code/blob/613e97d0d6bb477d51412dbf09709df810a0e6a5/src/network/protocols/get_public_address.cpp#L99), possibly for logging purposes or something), but up to [2e8ddb1](https://github.com/supertuxkart/stk-code/commit/2e8ddb1c50bc3c9330588fa0550cf59f3d0aaf95#diff-c208624252b1f063eefe43c371de3cf5L111) only 20 bytes were sent.

2. First 5 bytes in STUN response are ignored when it's parsed, which breakes the parsing.
This is caused by explicitly skipping these 5 bytes in the `NetworkString` constructor since [be815e42](https://github.com/supertuxkart/stk-code/commit/be815e42346fc9634d722fe332aa29742c2dc376#diff-b4533c5fb73987094f3b3716db1cdf07R314), what is probably intended for STK's own network messages, but not for STUN one.

3. First "STUN response doesn't contain the magic cookie" error message is misleading, since it actually returned after the "STUN Message Type" field (first two bytes) check.
Initially the corresponding 'if' condition was shared between message type and magic cookie check, but in [1eb3b6f](https://github.com/supertuxkart/stk-code/commit/1eb3b6f74eb1a8eb5f606be9ffcb25db3c541e0e#diff-c208624252b1f063eefe43c371de3cf5L135) they were split and the message was duplicated for both checks.
The message should say something like "STUN response has an invalid message type".

**Comment by hiker** [comment]
Hi,

yes, I am aware that the WAN code was not fully updated, since I focused on the LAN code. This will be fixed once I go back to WAN, but your analysis will certainly make this easier ;)

Thanks a lot!
   Joerg
