### ISSUE TITLE
STK contains non-free Ubuntu Font Family files

### ISSUE THREAD

**Issue by Vincent-C** [supertuxkart/stk-code#2570]
( Forwarded from Debian BTS [#830751](https://bugs.debian.org/830751) )

STK 0.9.2 ships with the following files in the source tarball (which get installed as part of the game's data files):

```
data/ttf/Ubuntu-B.ttf
data/ttf/Ubuntu-R.ttf
```

These ttf files are Ubuntu Font Family fonts, which violate the Debian Free Software Guidelines according to Debian's ftpmasters [1], with rationale provided at [2]; further discussion can be found at [3]. It's also worth pointing out that Fedora considers these fonts non-free as well [4].

As Debian's STK maintainer, I'd obviously prefer if these files were stripped from the source tarball and not used in-game (there are a host of other free fonts to choose from), but if that's not possible, would you prefer that I move STK out of Debian main into the non-free repo, or that I choose to replace those fonts myself (and thus make this a Debian/Ubuntu-specific change)? I don't want to diverge from upstream unnecessarily but I can't really do much else when it comes to DFSG violations.

@ignatenkobrain If I'm not mistaken, you maintain the Fedora supertuxkart package, right? Just a heads up.

[1] http://lists.alioth.debian.org/pipermail/pkg-fonts-devel/2011-April/006515.html
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603157#30
[3] https://bugs.launchpad.net/ubuntu-font-licence/+bug/769874
[4] https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4

**Comment by ignatenkobrain** [comment]
Thanks for notifying me! Yes, I'm maintainer of STK in fedora. Actually, not only those fonts are there (just realized this).
```
/usr/share/supertuxkart/data/ttf
/usr/share/supertuxkart/data/ttf/FreeSans.ttf
/usr/share/supertuxkart/data/ttf/FreeSansBold.ttf
/usr/share/supertuxkart/data/ttf/LICENSE
/usr/share/supertuxkart/data/ttf/NotoNaskhArabicUI-Bold.ttf
/usr/share/supertuxkart/data/ttf/SIL Open Font License.txt
/usr/share/supertuxkart/data/ttf/SigmarOne.otf
/usr/share/supertuxkart/data/ttf/Ubuntu-B.ttf
/usr/share/supertuxkart/data/ttf/Ubuntu-R.ttf
/usr/share/supertuxkart/data/ttf/ubuntu-font-licence-1.0.txt
/usr/share/supertuxkart/data/ttf/wqy-microhei.ttf
```

I would prefer if all of those fonts will be stripped.

**Comment by Benau** [comment]
You want to use fontconfig in stk?

**Comment by Vincent-C** [comment]
FWIW, I think the Ubuntu font licensing issue is the more serious issue here since it prevents several distros from actually packaging and distributing STK to begin with; let's figure out a solution for that first? We can probably come back to the issue of embedded font files in the source tarball later...

**Comment by bochecha** [comment]
For the record:

* Fedora also considers the font nonfree: https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4
* Canonical was asked to do something about it some 3 years ago: https://bugs.launchpad.net/ubuntu-font-licence/+bug/1211154

**Comment by bochecha** [comment]
Since @Benau asked me to chime in...

@Vincent-C As a Fedora packager myself, I agree with @ignatenkobrain that bundling fonts is not great, and something could probably be done about that.

But you're entirely right that it is a second issue, and it doesn't need to block fixing the licensing issue, which is much more pressing.

**Comment by Benau** [comment]
Instead of using FreeSans all the time (which requires changing enum in STK), @bochecha suggested a better font which has similar style (cantarell font), and doesn't even need re-compile to test:

https://github.com/supertuxkart/stk-code/tree/cantarell

Result:
![screenshot](https://cloud.githubusercontent.com/assets/3252341/16723549/237c1d36-473d-11e6-8a00-3195adbcaffc.jpg)

@hiker, @auriamg, good one?

**Comment by Benau** [comment]
Old ubuntu font for comparison:
![screenshot](https://cloud.githubusercontent.com/assets/3252341/16723718/36a8a09a-473e-11e6-9a1a-66e7de64a062.jpg)

**Comment by ignatenkobrain** [comment]
looks perfect for me

**Comment by auriamg** [comment]
The font has been changed to Cantarel in latest master, this should resolve this issue.

The change has also been pushed to the 0.9.2 branch
https://github.com/supertuxkart/stk-code/tree/0.9.2-branch

Regarding packaging fonts... You can always open a new ticket if you want, but expect that we will probably treat this with a lower priority, we are a multiplatform game and on windows and OSX (as well as our own linux static binaries), i.e. anything not using a package manager, bundling the font is by far the easiest way to go, so I don't think we will rush to change that.
