### ISSUE TITLE
Camera angle in minigolf track messed up after race finished

### ISSUE THREAD

**Issue by tobbi** [supertuxkart/stk-code#2576]
Once the minigolf track is finished, the camera angle is messed up so once you play another round, you're playing with a very weird angle that doesn't allow you to see where you're going AT ALL.

**Comment by auriamg** [comment]
Indeed the end camera is not reset when selecting "restart"

**Comment by MTres19** [comment]
I think I actually had this same problem in Antediluvian Abyss recently (on STK git from just a few days ago), and that doesn't use fixed end cameras either.

**Comment by OzoneOne** [comment]
This also happened to me in Oliver's Math Class while using a recent git version. Restarting the race from the results screen did not reset the camera to behind the player kart. When I then paused and restarted the race again, the camera corrected itself.
