### ISSUE TITLE
Unclear attribution and missing source for Boom_boom_boom.ogg

### ISSUE THREAD

**Issue by Vincent-C** [supertuxkart/stk-code#2577]
( Forwarded from Debian BTS [#832062](https://bugs.debian.org/832062) )

STK's source tarball contains the following file:
```
data/music/Boom_boom_boom.ogg
```
for which attribution is apparently unclear (the credits mention Matt Thomas as the creator, but the bug reporter seems to have credible evidence that Matt Thomas may not actually have been the creator of Boom_boom_boom.ogg?). I'll just quote the bug reporter directly:

```
Supertuxkart contains a song called "Boom boom boom" in Ogg Vorbis
format. According to the credits and debian/copyright, this song is
created by Matt Thomas, and is licensed under the GNU GPL v3 or later.
The source of the .ogg file is missing. Although what consists the
source of media assets can be unclear, I would like to point out that
there is also a module tracker version of this song, which can
reasonably considered the source, as it contains the score, the samples
used and can be editted in any module editor:

https://modarchive.org/index.php?request=view_by_moduleid&query=38184

This module contains the following text:

> -kbx128-  march 1993
> music for a crap amos
> game written by my
> brother.(only joking)

There is also some doubt that Matt Thomas and kbx128 are the same
person:

http://forum.freegamedev.net/viewtopic.php?t=6562&p=66000
```

**Comment by auriamg** [comment]
This song was added to the project quite a long time ago so it's pretty unclear, but agreed we should probably just replace it

**Comment by qwertychouskie** [comment]
http://forum.freegamedev.net/viewtopic.php?f=18&t=7062&p=70586#p70586

**Comment by akien-mga** [comment]
> http://forum.freegamedev.net/viewtopic.php?f=18&t=7062&p=70586#p70586

Uh-oh. Given that many tracks were inspired from this tune, I think it would be worth trying to get in touch with the original author and ask if they would relicense under a STK-compatible license. Given the impact their little tune had on the game, I'm pretty sure they would agree provided we can find a proper contact address.

**Comment by stephenjust** [comment]
It might be easiest to contact the author through his website or twitter: https://vimster.bandcamp.com/, @vimster

**Comment by Legimet** [comment]
You can find the Boom_boom_boom.mod file in the source of the original TuxKart: http://tuxkart.sourceforge.net/downloads.html

**Comment by SuicSoft** [comment]
@Legiment That page about the original TuxKart is quite interesting.

**Comment by deveee** [comment]
We certainly should do something with this issue because linux distributions may eventually want to remove us from repositories :P There are 3 bugs that preventing us from merging to Debian testing:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830751
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832062
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830748

Also note that STK 0.9.1 can't be compiled with gcc 6 without patching and distributions are moving/moved to gcc 6 already.

The problem with fonts licensing is already fixed. Maybe we should just replace this boom boom song by something other and make a quick bug-fix 0.9.2.1 release?

**Comment by Legimet** [comment]
I pointed to the origin of Boom_boom_boom.mod, in the original TuxKart. Including the mod file should be sufficient for distributions, so it doesn't have to be replaced.

**Comment by akien-mga** [comment]
> I pointed to the origin of Boom_boom_boom.mod, in the original TuxKart. Including the mod file should be sufficient for distributions, so it doesn't have to be replaced.

See http://forum.freegamedev.net/viewtopic.php?f=18&t=7062&p=70586#p70586:

> Look at the bottom of this page: http://wayback.archive.org/web/20120215 ... r/vim.html
Attribution-**NonCommercial-NoDerivs** 2.0 Generic

If that's the true license, that's plain nonfree.

**Comment by Legimet** [comment]
Has anybody contacted him?

**Comment by qwertychouskie** [comment]
> You can find the Boom_boom_boom.mod file in the source of the original TuxKart: http://tuxkart.sourceforge.net/downloads.html

The history goes back even further: https://sourceforge.net/p/supertuxkart/code/492/log/?path=/trunk/tuxkart/mods/Boom_boom_boom.mod

**Comment by deveee** [comment]
I've sent him a message on the https://vimster.bandcamp.com/ website a while ago. I asked him about contacting with us on the mailing list or IRC channel to make some clarifications about the license.

And if it's not possible to use the original "boom boom" song, I think that we should just use other song until proper song will be composed/found. The "bay" and "farm" songs are not thaaat bad for Math Class...

**Comment by qwertychouskie** [comment]
Minigolf also has to be considered, it uses the same song.

**Comment by hiker** [comment]
Note that I have email Steve Baker to see if he can shed any light on this. But I agree with otherwise replacing the song. Not sure about the work by the musicians which might 'reference' the melody :(

**Comment by akien-mga** [comment]
There seems to be some news from the original composer: http://forum.freegamedev.net/viewtopic.php?f=17&t=6562#p70946 :)

**Comment by deveee** [comment]
I was talking with Vim on email.

Here is the last message that I received from him:
```
Okay that license sounds fine to me. We'll go with that one. Hopefully that
clears things up. Seems daft for some small tune but I guess it had to be
right.

Keith

On Mon, 3 Oct 2016, 11:13 Deve, <deveee@gmail.com> wrote:

> Hi Keith,
>
> It depends on how do you want to allow to do with your song.
>
> The best solution for us is CC-BY-SA:
> https://creativecommons.org/licenses/by-sa/4.0/
> - it is typical Creative Commons license, used for the most of artist
> stuff in open-source projects (textures, 3d models, sounds etc...)
> - it doesn't contain the non-commercial restriction, so that it's not
> considered as non-free by linux distributions
> - it allows to remix this song, which allows us to use our songs that
> partially depend on your song
> - it will allow us to use your "Boom boom boom" song and also our
> songs in Supertuxkart game
>
> Second solution:
> If you really want to have the non-commercial restriction (I
> understand that you may want to have it), then you could at least
> write a clause that you allow to use our already made songs (Gran
> Paradiso etc...) under CC-BY-SA license. In this case:
> - we won't lose our already made work
> - practically these songs will be re-licensed from "CC-BY-NC" to
> "CC-BY-SA" because all authors agree to re-license it
> - we will need to replace the "Boom boom boom" song by something other
> because it will be still under CC-BY-NC license
>
> If you want, you can ask OzoneOne for the full list of songs that he
> made and that depend on "Boom boom boom".
>
> Again sorry if I am annoying, but this situation is a bit problematic
> for us. This song was available in STK for a very long time and we
> were sure that it is really free.
>
> Best regards,
> Deve
```

It basically means that he accepts the CC-BY-SA license.

I asked him if he could write it officially on the forum, but I didn't receive any response.

I hope that this is enough to finally solve the licensing issues. I can attach full email message as a documentation if it's needed.

Regarding to missing source files, the .mod file and lossless .wav file are available in our media repo:
https://sourceforge.net/p/supertuxkart/code/HEAD/tree/media/trunk/music/mods/

I corrected the information about the author and license in this commit:
https://sourceforge.net/p/supertuxkart/code/16762/
