### ISSUE TITLE
Clean out old branches

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2583]
There are many branches which have already been merged, and are now just cluttering the list.
List:
- [ ] 2360_fix_attempt
- [ ] dijkstra-test
- [ ] fix_2073
- [ ] gles
- [ ] legacy_opengl
- [ ] lensdust
- [ ] lensflare2
- [ ] new_server
- [ ] revert_improved_bloom

All these say "This branch is x commits behind master."

**Comment by konstin** [comment]
Duplicate of #1293

**Comment by nado** [comment]
Maybe close #1293 and keep this one since qwertychouskie already made a list ?

**Comment by konstin** [comment]
It doesn't matter which one we close as the list isn't complete.

**Comment by nado** [comment]
Also, it would be nice to get a proper tag for 0.9.1 and 0.9.2
