### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2584]
```
[error  ] LeackCheck: leaks detected!!
[error  ] LeackCheck: 

* * * * WARNING * * * * WARNING * * * * MEMORY LEAK! * * * *
[error  ] LeackCheck: 2 watched objects leaking.
[error  ] LeakCheck: Undeleted object at /tmp/stk-code-master/src/online/request.hpp : 65
    (No stack information available)
[error  ] LeakCheck: Undeleted object at /tmp/stk-code-master/src/io/xml_node.hpp : 61
    (No stack information available)
```
Latest git, Ubuntu Yakkety, compiled in debug mode.

**Comment by auriamg** [comment]
Thanks, but this leak report is unimportant. STK very probably exited while a thread was still going on, so it's not really a leak, it's just that the other thread wasn't done when STK shut down

**Comment by qwertychouskie** [comment]
It is constantly reproducible though, every time.  Even just launching and them closing STK triggers it.

**Comment by auriamg** [comment]
I am unable to reproduce this issue on my end

**Comment by hiker** [comment]
This can depend on the threading implementation, network connectivity (e.g. when can curl be aborted, how long does it take to abort a thread) on one hand, and usability on the other (how long should the user wait before STK really finishes). So yes, up to two messages from the addon handling core (one currently running, and one from trying to abort the running one) can happen.

**Comment by qwertychouskie** [comment]
The thing is, on my end, it is impossible *not* to reproduce, even with all network connectivity turned off.  @auriamg Do you have STK compiled in debug mode?

**Comment by Benau** [comment]
If this annoys you, you can build STK in release mode

Also, maybe try to turn off "Connect to the Internet" in game menu?

**Comment by qwertychouskie** [comment]
That is what I meant by "even with all network connectivity turned off".  It doesn't annoy me much, but since it said `* * * * WARNING * * * * WARNING * * * * MEMORY LEAK! * * * *`, I thought I should at least report it. :)

**Comment by Benau** [comment]
Maybe don't use online account?

**Comment by qwertychouskie** [comment]
OK, logging out seems to get rid of it, but that raises a new issue: shouldn't the logout be automatic when the internet connectivity is turned off?
