### ISSUE TITLE
Test gpwin button missing

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2587]
In the code, there is a button for testing `gpwin`, among other buttons for testing, but these do not show up in the interface.

STK compiled in debug mode, artist debug turned on.

**Comment by Benau** [comment]
Did you mean main_menu_screen.cpp?

#define DEBUG_MENU_ITEM 1 in line 18

**Comment by qwertychouskie** [comment]
How do I get the buttons then?

**Comment by Benau** [comment]
Change #define DEBUG_MENU_ITEM 0 in main_menu_screen.cpp to #define DEBUG_MENU_ITEM 1

And recompile

**Comment by qwertychouskie** [comment]
OK, thanks.
