### ISSUE TITLE
Artist debug mode menu does not have enough camera/kart target entries

### ISSUE THREAD

**Issue by RQWorldblender** [supertuxkart/stk-code#2592]
Up to 20 karts, including the player ones, are supported. However, the debug menu lists only the first 8 karts, and when I start a race with more than 8, and switch to any of those targets, it can become impossible to switch back to other AI karts 9 up to 19, or even the player kart(s). I think that either the debug menu needs to have either 20 static menu entries for the 20 supported karts, or more optimally, show entries based on how many karts are in play, so that, for example, if there are only 4 karts, then only 4 entries should be listed, or if there are 16 karts, then 16 entries should be listed. The screen size should also be taken into consideration, so that lower entries can reached at all.

**Comment by Benau** [comment]
Actually I added this function for debug (AI debug) mostly, not for watching real race for normal players.

**Comment by hiker** [comment]
Those are debug functions, which assume a proper knowledge of what is happening, and when it is safe to use them. Unless you have an STK development need to do, we won't spend any time on this.
