### ISSUE TITLE
Add startup boost for AI karts

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2594]
Best I can tell, there is no startup boost for the AI karts.  Before this was not very noticeable, but since #2586 it is much more noticeable.  Optimally:
  - Whether or not an AI kart gets a boost should be random,
  - The amount of boost should be random,
  - The probability of getting a boost should be higher on harder difficulties and lower on easier difficulties,
  - The probability of getting a bigger boost should also be higher on harder difficulties and lower on easier difficulties.

**Comment by auriamg** [comment]
AI karts already have started boosts, I just tested it.

Maybe you are playing on the lower difficulties, where opponents don't do it to give players a chance.
