### ISSUE TITLE
Particles glitches on Radeon HD 7640G fglrx 15.302

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2597]
It's related to this comment:
https://github.com/supertuxkart/stk-code/issues/2595#issuecomment-238857343

@SuicSoft Could you provide the stdout.log file?

You can also try to disable texture compression. It sometimes causes some graphical glitches.

**Comment by SuicSoft** [comment]
@deveee Will disabling texture compression reduce FPS ?

**Comment by SuicSoft** [comment]
@deveee Disabling texture compression seems to have fixed it. I haven't noticed much of a FPS change

**Comment by SuicSoft** [comment]
@devee My fglrx driver version is **15.302**. Can you edit the title

**Comment by SuicSoft** [comment]
Since fglrx is now unsupported I think this should be closed

**Comment by deveee** [comment]
Fglrx is now unsupported on linux, so closing as invalid
