### ISSUE TITLE
Recommended GPU for running STK at max settings

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2598]
What GPUs are recommended to run STK at max settings above 30 FPS

**Comment by nado** [comment]
I have a GTX970 and its pretty stable >55fps

**Comment by MTres19** [comment]
I propose this discussion be moved to the [forum](http://forum.freegamedev.net/viewforum.php?f=17)—this is not a bug. (Well, maybe it is, if you need a GTX 970 to get 55 fps, but I think the team already knows that there are some performance issues... :/)
