### ISSUE TITLE
Font artifacts when STK is started without advanced lighting

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2599]
See attached screenshots:
![zrzut ekranu z 2016-08-11 02-01-45](https://cloud.githubusercontent.com/assets/5108558/17575444/8c1f1f48-5f69-11e6-8e27-5df9f771a764.png)
![zrzut ekranu z 2016-08-11 02-01-54](https://cloud.githubusercontent.com/assets/5108558/17575445/8c1ff346-5f69-11e6-8abb-42f3bef25ea3.png)

I'm not 100% sure if this is fully reproducible for everyone. When I want to reproduce it, the advanced lighting option must be already disabled before STK starts. When STK is already started I can switch between advanced and non-advanced lighting and it doesn't change the fonts.

**Comment by qwertychouskie** [comment]
0.9.2 or git?

**Comment by deveee** [comment]
git as always ;)

**Comment by Benau** [comment]
(Assume git and if you can reproduce later)

Can you "dump glyph page" in debug menu and see if the glyph page of bold face is correct?

Also what happen if you press "reload all fonts"?

**Comment by Benau** [comment]
Actually after i go to RTT which has newest commit, the fonts corrupted :/

**Comment by deveee** [comment]
Reload all fonts doesn't change anything.

Here are the files:
![bold_0](https://cloud.githubusercontent.com/assets/5108558/17575686/d66151c8-5f6b-11e6-86ca-453b47cd33d9.png)
![digit_0](https://cloud.githubusercontent.com/assets/5108558/17575688/d689eef8-5f6b-11e6-9f06-ac2ef58158e0.png)
![regular_0](https://cloud.githubusercontent.com/assets/5108558/17575687/d688898c-5f6b-11e6-90df-3875ec193771.png)

I was checking it with this commit: 8e8433f08ce6f8ba4b5cd6278231c2e64e92aca0 and it was broken for me either. But I can check once again, maybe I did something wrong.

**Comment by deveee** [comment]
I can confirm, 8e8433f08ce6f8ba4b5cd6278231c2e64e92aca0 is broken for me too, so this is not a bug in my lastest commit.

I also noticed that before kart selection screen is opened, the fonts look fine.

I can look at this more carefully tomorrow. Now it's too late for me.

**Comment by deveee** [comment]
Just an idea, but maybe uninitialized camera in kart selection screen after the camera refactoring?

**Comment by Benau** [comment]
I notice that when the glyph page is dumped, the size of it is 512x512 (which should be 1024x1024)

change     virtual unsigned int getGlyphPageSize() const OVERRIDE     { return 1024; } to return 512 in bold_face.hpp seems to work fine, although 1024 has been used since the new font code is done, i don't understand why :/

**Comment by qwertychouskie** [comment]
Also, one of them is 256x256.

**Comment by Benau** [comment]
it is intended, because you are not going to change the digit font later, so small size is used

**Comment by Benau** [comment]
Turns out because of m_high_definition_textures..., it disables >512 size of texture usage, so do you think it's good to have bold face to use 512x512 too?

I chose 1024 because of its high DPI, so you can prevent create too much glyph page (although we have lazy loading characters for bold font too now, so at most only 2 glyph pages are required anyway)

**Comment by Benau** [comment]
Or we can add sth like  if( (UserConfigParams::m_high_definition_textures & 0x01) == 0) set 512, 1024 otherwise for that virtual function

**Comment by deveee** [comment]
The MAX_TEXTURE_SIZE is indeed partially broken, even in advanced pipeline (totally broken in fixed pipeline). You can see it when you set very low value in irr_driver.cpp, for example:
```att.setAttribute("MAX_TEXTURE_SIZE", core::dimension2du(32, 32));```
It causes the images in tabs to be displayed wrongly:
![zrzut ekranu z 2016-08-11 21-08-59](https://cloud.githubusercontent.com/assets/5108558/17601474/a2101ca4-6008-11e6-9090-82f6d5bc2ecd.png)

Generally it is caused by wrong usage of getSize() and getOriginalSize() in irrlicht. The second one should be used in most cases.

But I didn't look at fonts code, so I don't know if this is the reason.

**Comment by Benau** [comment]
I meant: when you somehow disable "Use high definition textures" in that dialog (see irr_driver.cpp:671, it forces to resize all texture to 512x512, if a texture size is larger than that value. Which bold face use a 1024x1024, and when you resize it, the rectangle in spritebank of fontwithface unchanged, so you will see shrinked glyphs.

**Comment by Benau** [comment]
I think the icons display wrongly because it uses spritebank (which font uses it too)

**Comment by Benau** [comment]
@devee can you see if https://github.com/supertuxkart/stk-code/commit/aa15b0070e4f955f085a0b1a31862200085aa8fe works for you?

**Comment by Benau** [comment]
actually the attempt to resize the texture to 32x32 is describe here:
https://github.com/supertuxkart/stk-code/issues/2050

**Comment by Benau** [comment]
Now this should be the correct fix (save old max size before addTexture, revert saved value after setTexture)

I think we can fix #2050 by introduce this to icon widget (STKmodifiedspritebank)?

**Comment by deveee** [comment]
Button icons should be fixed in this commit: https://github.com/supertuxkart/stk-code/commit/1481da97186e77462ef5a87b27d25a77de0c3fd3

Also images in list items are too small, but I didn't find the reason yet.

Now fonts work fine. Though the fix looks a bit hackish. Again, I don't know this code, but maybe is it possible to read proper texture dimensions from irrlicht using texture->getSize() and texture->getOriginalSize() ?

**Comment by Benau** [comment]
I borrowed this from old code:
https://github.com/supertuxkart/stk-code/commit/27dec2fbf8a4e722d841afb0e96ef049e632ce99

Actually because the font texture is not loaded from file, but generate on-the-fly by computer, so not sure if I know a better solution

**Comment by deveee** [comment]
Ok, so we can close it as fixed. Thanks a lot!
