### ISSUE TITLE
Rename the SuperTuxKart Properties panel under "Object"

### ISSUE THREAD

**Issue by MTres19** [supertuxkart/stk-code#2602]
I know, I know. This is super trivial. But I've written most of the new track making tutorial referring to the "SuperTuxKart Object Properties panel." Just referring to the "SuperTuxKart Properties panel" could be quite confusing, but there's also the possibility for confusion if someone looks and sees "SuperTuxKart Properties" under the Blender's object properties but not "SuperTuxKart Object Properties as it's referred to in the tutorial.

Thanks in advance.

**Comment by auriamg** [comment]
Hmm it is indeed trivial, but considering it takes 30 seconds to change I actually changed it in SVN, I see how it could help avoid ambiguity
