### ISSUE TITLE
Laptop sometimes freezes when playing SuperTuxKart

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2603]
Sometimes when I am playing STK my laptop completely freezes and can only be turned off with the power button (not even RESUIB).Before it freezes the FPS goes to 1 - 3 FPS (and creates a slideshow) for about 5 seconds and then freezes.The laptop can run Prime95 with a max temperature of 81°C (I tested 1 hour) so it is not overheating and more like a problem with STK (memory leak ?)<br /><br />HP Pavilion g7 2269wm with AMD A8-4500M and Radeon HD 7640G with latest Catalyst Linux drivers from AMD website.

Also how can I monitor the temperature while playing STK.I tried GLXOSD but it does not work for STK although it works for NeverBall

**Comment by LoadingPleaseWait** [comment]
Try using psensor for temperature monitoring. I've used it before and it can graph the temperature of each of your cores in either celsius or fahrenheit.

**Comment by SuicSoft** [comment]
I played 3 laps of **Cocoa Temple** , 3 laps of **Gran Paradiso Island** and 10 laps of **Nothern Resort** and got a maximum temperature of 89°C (since STK also is GPU intensive).

![screenshot from 2016-08-14 19 19 45](https://cloud.githubusercontent.com/assets/13938848/17649667/3a96aa28-6258-11e6-8e3a-08520ade8e64.png)

Room temperature is 28 - 33°C

**Comment by LoadingPleaseWait** [comment]
Your system shouldn't get that hot. That is troubling.

**Comment by auriamg** [comment]
Unfortunately, I've myself had problems in the past where linux was overheating my laptop when the GPU was running at (or close to) 100%. Unfortunately, that's more likely a driver issue (and maybe fan settings) and not something that STK can do anything about

**Comment by SuicSoft** [comment]
@LoadingPleaseWait I web search shows that these temperatures are OK for a laptop

**Comment by SuicSoft** [comment]
@LoadingPleaseWait @auriamg  Laptops are meant to get hot and can handle high temperatures (see http://www.tomsguide.com/answers/id-2700695/safe-temps-laptop-gaming.html) and my temperature is below 90°C.My laptop will shutdown / halt if the temperature goes above 100°C.

**Comment by qwertychouskie** [comment]
You could also try blowing out the computer with an air compressor, if there is a lot of dust in the vents reducing air flow this could contribute to high temps.

**Comment by MTres19** [comment]
@qwertychouskie That doesn't fix the problem of the drivers not recognizing this and clocking down the GPU. I recommend removing the proprietary Catalyst drivers, though perhaps there was some reason for them?

**Comment by qwertychouskie** [comment]
I know it doesn't fix the driver problem, but it may help lower the temps anyway, and [is a generally recommended maintenance practice.](http://www.howtogeek.com/194479/how-to-clean-the-dust-out-of-your-laptop/)

**Comment by SuicSoft** [comment]
@qwertychouskie The laptop has been cleaned recently and has new thermal paste

**Comment by SuicSoft** [comment]
@MTres19 STK is very slow and cannot use a graphics setting of 3 or higher when using the open source drivers

**Comment by deveee** [comment]
@SuicSoft Now I am even more confused. You wrote in https://github.com/supertuxkart/stk-code/issues/2595#issuecomment-238857343 that you cannot use graphics level 3 or higher with PROPRIETARY drivers. At least in your stdout.log I see
```[info   ] IrrDriver: OpenGL version string: 4.3.13399 Core Profile Context 15.201.1151```

And btw. please use the forum for similar topics, really... "STK sometimes freezes the laptop" doesn't provide any useful info and nobody will be able to reproduce it anyway. And still this is most probably problem with your OS, drivers or hardware. Single application shouldn't be able to freeze whole computer.

**Comment by SuicSoft** [comment]
@deveee I think that this should go the the forum

**Comment by SuicSoft** [comment]
@deveee When this happens there is a ticking sound coming from the speakers (same one used for the time bomb in STK).So this seems to be related to STK , not my laptop

**Comment by SuicSoft** [comment]
Seems to be fixed after upgrading elementary OS Loki with Liquorix kernel 4.7 and oibaf's PPA.

**Comment by auriamg** [comment]
Glad to know it's fixed
