### ISSUE TITLE
Rerverse Bug on Grand Paradiso Island 

### ISSUE THREAD

**Issue by Ludsky** [supertuxkart/stk-code#2604]
Hello, on the track : Grand Paradiso Island, we can't play with reverse mod.

One day, my kart fallen on the second road (wooden road) and when i rescue, i rescue on this road,; i'm blocking on this road 
![blockgranparadiso](https://cloud.githubusercontent.com/assets/21077512/17730281/56864394-6468-11e6-87a2-22da496f1e32.PNG)

**Comment by Benau** [comment]
Duplicated of #2503
