### ISSUE TITLE
[Addons] [Kart] Texture problem

### ISSUE THREAD

**Issue by Ludsky** [supertuxkart/stk-code#2607]
Hello,

Penny have a problem with texture, problem with light i think ....

![pennylight](https://cloud.githubusercontent.com/assets/21077512/17830050/25b60dac-66c1-11e6-98b6-30d053e1fb8b.PNG)
![pennylight2](https://cloud.githubusercontent.com/assets/21077512/17830051/25ff41b6-66c1-11e6-9ba0-983e896bf035.PNG)

It's same for : BigBugBunnyRider

![bigbuckbunnybugriderlight](https://cloud.githubusercontent.com/assets/21077512/17830065/664c5254-66c1-11e6-9cd7-9fea58496282.PNG)

and same for Famanouille :
![framouillelight](https://cloud.githubusercontent.com/assets/21077512/17830074/7f5d10d0-66c1-11e6-84e1-d1946f951ba0.PNG)

**Comment by auriamg** [comment]
Hi, this is the wrong bug tracker. Bugs about add-ons (modelling and texturing) do not belong on github. They can be reported to the author of each addon.
