### ISSUE TITLE
[Addons] [Track] Mystery Island Texture problem

### ISSUE THREAD

**Issue by Ludsky** [supertuxkart/stk-code#2608]
Mystery Island have a problem with light, very very so light

![mystery island light 2](https://cloud.githubusercontent.com/assets/21077512/17830085/b229083e-66c1-11e6-89cd-8342e5f70b89.PNG)

![mystery island light](https://cloud.githubusercontent.com/assets/21077512/17830093/ce710834-66c1-11e6-8ed5-66a6d86c636a.PNG)

**Comment by auriamg** [comment]
Hi, this is the wrong bug tracker. Bugs about add-ons (modelling and texturing) do not belong on github. They can be reported to the author of each addon.
