### ISSUE TITLE
[Addons] [Track] Nostalgia Texture problem

### ISSUE THREAD

**Issue by Ludsky** [supertuxkart/stk-code#2609]
Nostalgia have a problem with texture Missing (Sky, lava....)

![nostalgiatexture](https://cloud.githubusercontent.com/assets/21077512/17830110/1320476a-66c2-11e6-8916-6c240195d36e.PNG)
![nostalgiatexture2](https://cloud.githubusercontent.com/assets/21077512/17830111/13269160-66c2-11e6-8fd9-ac025915a2e6.PNG)
![nostalgiatexture3](https://cloud.githubusercontent.com/assets/21077512/17830112/139b4000-66c2-11e6-8615-ece0781b56cd.PNG)
![nostalgiatexture4](https://cloud.githubusercontent.com/assets/21077512/17830113/140ec96c-66c2-11e6-8660-f60a4dd54539.PNG)

**Comment by auriamg** [comment]
Hi, this is the wrong bug tracker. Bugs about add-ons (modelling and texturing) do not belong on github. They can be reported to the author of each addon.
