### ISSUE TITLE
warning: comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by aapo** [supertuxkart/stk-code#2613]
stk-code/src/tracks/check_line.cpp:174
    stk-code/src/tracks/check_line.cpp:215
    stk-code/src/tracks/check_line.cpp:218
    warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (kart_index == -1)

And indeed: 

    unsigned int kart_index

**Comment by auriamg** [comment]
Yes, though in this case -1 is just a synonymous for 0xFFFFFFFF. So there's no bug, just annoying warnings. Feel free to shut the warnings by adding the proper casts if you wish though there is no real issue

**Comment by nado** [comment]
Or instead of cast you can use UINT_MAX
```
#<cstdint>
...
if (kart_index == UINT_MAX)
```

**Comment by nado** [comment]
Fixed in 4c0b4d80780cb35f4e36fbf8f96970c3723b0fae
Can be closed

**Comment by deveee** [comment]
Define something like INVALID_KART_INDEX or change the kart index to signed integer seems to be better solution, but indeed the warning should be now fixed. Thanks!
