### ISSUE TITLE
All languages 'broken' (several translated messages out-of-date)

### ISSUE THREAD

**Issue by aapo** [supertuxkart/stk-code#2614]
Commit 96a10ce9 drops e.g. several "(only in multiplayer games)" -substrings, and it then breaks every localization.
These are updated to the supertux.pot, but not to the *.po -files.

**Comment by auriamg** [comment]
This is normal, sometimes the game evolves and we change texts. When the next release approaches, we will sync translations to transifex and ask our translators to help us bring the translations up to date
