### ISSUE TITLE
Irrlicht version used in STK is 4 years old

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2616]
Newer versions have been released (see http://irrlicht.sourceforge.net/) but we are still using an old version from 2012. Updating Irrlicht will probably improve performance since the new version does not use `glBegin` / `glEnd` (which are deprecated)

**Comment by Benau** [comment]
Actually we have forked irrlicht, also we use the *.cpp in graphics folder for rendering mostly

**Comment by SuicSoft** [comment]
@Benau I still think that our fork should be based on the latest version and not an outdated one from 2012
