### ISSUE TITLE
[Suggestion] Sparking effect when karts touch each other or metal objects

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2618]
Having a spark :zap: effect when metal touches metal would be a nice graphical addition to our game.But it should only happen if a kart touches metal or another kart , not if it touches a wooden tree :deciduous_tree: or something.

There should be more sparks if the kart is moving faster against the rubbing object and less sparks if it is  moving slowly against it so it won't look ugly and fake :smiley:.

**Comment by Benau** [comment]
Please make suggestion in forum, thank you
