### ISSUE TITLE
SuperTuxKart git version not building although Travis CI passes

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2619]
I have forked the STK repo to https://github.com/SuicSoft/stk-code and I am trying to build the **master** branch (which I have not modified).

<pre>
suici@-HP-Pavilion-g7:/mnt/storage/princ/Documents/Programming/stk-code/cmake_build$ <b>make VERBOSE=1 -j8</b>
... Hidden ...
[ 32%] Linking CXX static library libbulletcollision.a
cd /mnt/storage/princ/Documents/Programming/stk-code/cmake_build/lib/bullet && /usr/local/bin/cmake -P CMakeFiles/bulletcollision.dir/cmake_clean_target.cmake
cd /mnt/storage/princ/Documents/Programming/stk-code/cmake_build/lib/bullet && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/bulletcollision.dir/link.txt --verbose=1
/usr/bin/ar qc libbulletcollision.a  CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btDbvt.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btGhostObject.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/btUnionFind.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btBox2dShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btBoxShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btCollisionShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btCompoundShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConcaveShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConeShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btCylinderShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btEmptyShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btShapeHull.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btSphereShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btContactProcessing.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btGImpactBvh.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btGImpactShape.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/gim_box_set.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/gim_contact.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/gim_memory.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/Gimpact/gim_tri_collision.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp.o CMakeFiles/bulletcollision.dir/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp.o
/usr/bin/ranlib libbulletcollision.a
make[2]: Leaving directory `/mnt/storage/princ/Documents/Programming/stk-code/cmake_build'
[ 32%] Built target bulletcollision
make[1]: Leaving directory `/mnt/storage/princ/Documents/Programming/stk-code/cmake_build'
make: *** [all] Error 2
</pre>

**Comment by Benau** [comment]
can you provide full log?

**Comment by Benau** [comment]
Also, did you try to build your irrlicht_update before? Please make sure you have remove the whole build folder when switch back to master.

Unrelated: what you were doing will not work (use the latest version of STK)

**Comment by SuicSoft** [comment]
@Benau Here is the build log http://paste.ubuntu.com/23105961/

I have run `make clean`. Should I also delete the cmake_build directory

**Comment by Benau** [comment]
nothing interesting in your log, and yes please make sure you have clean everything (or you can build STK outside stk-code folder)

**Comment by SuicSoft** [comment]
@Benau I passed the 32% after cleaning up  the build.Right now at 55% (about 3 minutes since I started)

**Comment by deveee** [comment]
@SuicSoft this log file doesn't contain any error messages. If you made it by using ```make >file.txt``` then maybe try to use ```make &> file.txt``` . Or maybe try to use just make (without -j8) so that error message will be shown at the bottom.
