### ISSUE TITLE
Smooth LOD transition using noise transparency

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2623]
One of the issue of the current SuperTuxKart engine is Level of detail popping. We can't really have LoD near the player because the popping will be noticed and big things like trees are forced to be rendered even when far away because otherwise they might pop.

While experimenting with Godot Engine I came with a solution that can be implemented in SuperTuxKart.

1) When an object is selected to be hidden we temporarily replace it with an alpha tested material:
-> The material has as an input texture the diffuse texture of the normal material
-> The alpha layer is a noise texture in gray scale.
-> There is a variable, the amount of noise causing alpha tested transparency

2) When the object must fade out, we increase the alpha test factor and more part will be progressively hidden, when the factor is at 100% the object is fully invisible and we can safely hide it

3) When an object fade it, we decrease the alpha test factor (in ~ 1 sec) until everything is visible. Once everything is visible we change the temporary dither material to the normal material of the object (to reduce the amount of different materials)

4) It seems fine but isn't it just eye candy ?
IMHO this will allow use to decrease the drawing distance of most LOD objects. By allowing closer to the player transitions we will decrease the overall details of the game without too much popping.

A similar code was done for lighting. They appear progressively

![transition](https://cloud.githubusercontent.com/assets/6406045/18178309/244bf9c4-707e-11e6-8f6a-833cd68a1c28.jpg)

**Comment by tobyplowy** [comment]
yeh this is a big problem
i think this wuld be a nice addition

**Comment by Benau** [comment]
Not doable with sp, or you are going to mess up the simple shader picking system
