### ISSUE TITLE
Path for shaders is hardcoded

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2625]
I am trying to get the shaders to be used from another directory (see https://github.com/SuicSoft/stk-code/blob/shader_optimization/sources.cmake , it also gives the **-- Using optimized GLSL shaders** message which shows that it not to do with my coding) but it does not use the new shader directory.

I have tried deleting and re adding the `cmake_build` directory and running `make clean` but it still doesn't work.The shader directory is most likely hard coded somewhere

**Comment by Benau** [comment]
If you really want to have it non-hardcoded, it's your task to make it smartly choose one for your optimized GLSL shaders, not our job to do that

**Comment by SuicSoft** [comment]
@Benau Then why does the cmake.sources have an option to change it.Didn't you test it when you added that code (maybe it has broken recently)

**Comment by deveee** [comment]
cmake.sources doesn't have an option to change it

**Comment by SuicSoft** [comment]
@deveee @Benau Then what is https://github.com/supertuxkart/stk-code/blob/master/sources.cmake#L5
