### ISSUE TITLE
Missing/incomplete licenses for many assets

### ISSUE THREAD

**Issue by MTres19** [supertuxkart/stk-code#2630]
Many items in the assets repository either have no license at all, or were modified and never updated to reflect added authors.

I think licenses in the assets repository are more important since they're shipped with the game and are more likely to be scrutinized by Debian. However things in the media repo should ideally have a license too.

(By the way, it might be a good idea to use CC-BY-SA 4.0 where possible since it's more international.)
## Music
- [x] theGreatFair.ogg
## Sound Effects
- [ ] bowling_shoot.ogg
- [ ] exotic-birds.ogg
- [ ] exotic-birds_2.ogg
- [ ] jump.ogg
- [x] lenautile_restaurant.ogg
- [ ] plopp.ogg
- [ ] race_finish_victory.ogg
- [ ] rain.ogg
- [ ] river_loop.ogg
- [ ] sara_airport_pa.ogg
- [ ] waterfall_loop_2.ogg
- [ ] WilhelmScream.ogg (Is this supposed to be a joke?)
## Textures
- [ ] ants.png
- [ ] city_bricks.png
- [ ] clouds.png
- [ ] confetti.png
- [ ] displace.png
- [ ] explode_spark.png
- [ ] generickartshadow.png (could probably be removed)
- [ ] genericskybox_*.jpg
- [ ] gfx_*
- [ ] motif.png
- [ ] noise.png
- [ ] particle_water.png
- [ ] rain.png
- [ ] round_shadow.png
- [ ] sandgrass.png
- [ ] skidmarks.png
- [ ] sky_genericKartPreviewSky_side_a.png
- [ ] slipstream.png
- [ ] snowyroad.png
- [ ] stk\* (Yes, really)
- [ ]  stktex*
- [ ] summersky_*
- [ ] tree_zen.jpg (tree_zenRed.jpg mentioned, but does not exist)
- [ ] water-splash.png

**Comment by OzoneOne** [comment]
lenautile_restaurant.ogg is CC0: https://www.freesound.org/people/Alcappuccino/sounds/263528/
theGreatFair.ogg is CC BY-SA (I say this as its co-author).

**Comment by hiker** [comment]
Work in progress.

**Comment by hiker** [comment]
Still work in progress.

**Comment by FabioPedretti** [comment]
Hi, I noticed this Debian issue, due to licensing problems STK may be removed from Debian 11:
https://bugs.debian.org/cgi-bin/bugreport.cgi?archive=no&bug=990368

**Comment by Benau** [comment]
We already have patch ready to allow removing those karts in stk-code without affecting online players

**Comment by FabioPedretti** [comment]
Great, maybe you could send the patch or some info to 990368@bugs.debian.org, to avoid STK being removed from Debian, it's one of the release blocker bugs blocking Debian 11.

**Comment by Benau** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990368#22

I think those so-called stk fans just want stk removed from debian because it's not as free as they want anyway, in other word trolls ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

For the ??? licenses need some more time to replace / sort them out, but keep in mind they exist for a while anyway

**Comment by Benau** [comment]
not sure @Vincent-C is still active in debian-games..... maybe he can merge my patch quick...

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) plopp and jump are replaced and "deki" (reiner) comes stk irc and I explained to him ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

**Comment by deveee** [comment]
Good, thanks a lot
