### ISSUE TITLE
SuperTuxKart-0.9.2 fails to start on OSX with ... FreeType not found

### ISSUE THREAD

**Issue by klaus-halfmann** [supertuxkart/stk-code#2633]
Supertuxkart failed to start on OSX 10.11.6. I have FreeType installed via MacPorts, though.
I cannot start it via the Finder, when doing via the commandline I get:
$ /Applications/Spiele/supertuxkart.app/Contents/MacOS/supertuxkart 
dyld: Library not loaded: @executable_path/../Frameworks/FreeType.framework/Versions/2.4/FreeType
  Referenced from: /Applications/Spiele/supertuxkart.app/Contents/MacOS/supertuxkart
  Reason: image not found

I could fix this by some tricks I found on the net (but that needs X-Code tooling)

cd /Applications/supertuxkart.app/Contents/MacOS
$ install_name_tool -change  @executable_path/../Frameworks/FreeType.framework/Versions/2.4/FreeType  /Applications/supertuxkart.app/Contents/Frameworks/FreeType.Framework/Versions/2.4/FreeType supertuxkart 

Now I can run it from the Terminal, but still not from the finder:

**Comment by auriamg** [comment]
Just a clarification, is this a self-built STK or using the official package from our website?
Since you mentionned macports I would assume self-built but would like to confirm that.

Otherwise, macports installs dependencies Unix-style, if you want to build STK you should use our official dependencies package ( see https://supertuxkart.net/Building_and_packaging_on_OSX )

Otherwise, make sure you copy FreeType.framework inside your app buncle where it's looking

**Comment by klaus-halfmann** [comment]
I used the official build .dmg file.
I assume there _may_ have been a kind o collision with MacPorts.

--
klaus.halfmann@arcor.de

**Comment by auriamg** [comment]
Can you verify if the file mentionned in the error message ( @executable_path/../Frameworks/FreeType.framework/Versions/2.4/FreeType ) does exist for you? I just downloaded a fresh copy from our website and everything seems to be in order

**Comment by klaus-halfmann** [comment]
Hello auriamg,

the File was available at the relative location from Contents/MacOS/supertuxkart 
../Frameworks/FreeType.framework/Versions/2.4/FreeType so if @executable_path 
would point tho this it would be correct. 

Lets try again on this other Mac we have: (older one is an older iMac with a dual Core)

Started from the DiskImage directly, ok
Now starting for the „Applications“ folder, ok.

On the original Mac we copied it so some „Games“ Subfolder of applications.

I will try again of that big mac.. later.

I think you can reduce the priority of the bug to low.

--
klaus.halfmann@arcor.de

**Comment by qwertychouskie** [comment]
@klaus-halfmann Are you still able to reproduce this issue with 0.10-beta1?

**Comment by klaus-halfmann** [comment]
I will try tomorrow, but thanks for asking.

--
              |          __    klaus.halfmann@arcor.de
+--------+    |   |\  | |  \
| +----+ |    v   | \ | |__/   Klaus Halfmann
| |... | |   .^.  |  \| |      Bommersheimer Weg 60
| |..  | |  <   >      |       61348 Bad Homburg
| +----+ |   'v'       |
|_____==_|+==-------------==+  GERMANY
 |      | |   --__  __--    |
 +------+ +-------==--------+  06172/492497

**Comment by klaus-halfmann** [comment]
Hello Qwerty,

I download version 0.9.3 it has no Problems loading an seems playable.
I will give it a try next weekend, whatever it was I think you
can close that bug.

Thanks for caring from a widelands developer.

--
              |          __    klaus.halfmann@arcor.de
+--------+    |   |\  | |  \
| +----+ |    v   | \ | |__/   Klaus Halfmann
| |... | |   .^.  |  \| |      Bommersheimer Weg 60
| |..  | |  <   >      |       61348 Bad Homburg
| +----+ |   'v'       |
|_____==_|+==-------------==+  GERMANY
 |      | |   --__  __--    |
 +------+ +-------==--------+  06172/492497
