### ISSUE TITLE
Stack trace not working on windows

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2642]
Most windows stack traces we receive do not have symbol/line number information. It works for me, so something is wrong with the installation, or pdb file. The executable contains the absolute path to my build directory, but according to https://msdn.microsoft.com/en-us/library/ms241613.aspx if the absolute path does not work, pdb files from the current directory will be used.

**Comment by Benau** [comment]
Notice: the current stack trace code will not work if we provide 64bit msvc stk

**Comment by hiker** [comment]
The windows32 problem is fixed in 01be8002531256bdaaab6ba63bba27125762eebb. 
Leaving this open for now to see what we can do in case of 64-bit windows binaries.

**Comment by hiker** [comment]
Before someone else tries: I got it mostly working, just need to cleanup the code a bit (and make x64 and x86 more similar if possible).

**Comment by hiker** [comment]
Waiting for #900 to be merged in, then this can be closed.

**Comment by hiker** [comment]
Closing this, since it will be finished with the upcoming release.
