### ISSUE TITLE
1st place isn't "winning" in Olivers Math Class in version 9.2.

### ISSUE THREAD

**Issue by LiamM32** [supertuxkart/stk-code#2645]
I'm playing SuperTuxKart stable version 9.2 in Story mode.  I have gotten first place twice on Oliver's Math Class on Expert difficulty, both times driving as Wilbur.  However, Wilbur played his _losing_ animation at the end of the race, and I didn't have the trophy icon on my map afterwards or any indicator that I "won".
Then I tried playing it on _Intermediate_ difficulty.  After I won, I had Wilbur's "winning" animation and then the cutscene with the key opening the treasure chest and my map now had a silver trophy icon, all as it should.  So it seems like the game understands that I "won" on Intermediate difficulty but not Expert.
However, none of this is true on other tracks, in which I get the full effects of winning on Expert.

**Comment by Benau** [comment]
According to challenge, you need to finish the race in 01:05:00 and at first place.

If either is not satisfied, lose animation will be played.

Did you finish the race within the time limit?

**Comment by LiamM32** [comment]
I see.  Well then, I think that the time limit should be slightly longer in Olivers Math Class, and more significantly longer for Antedeluvian Abyss.  It should be a failsafe in case if the player is lucky and all the other karts happen to take too long.
The time limit should definately not be shorter than it would take for a single AI kart at that difficulty level to complete the track on their own.

**Comment by auriamg** [comment]
If you are playing at "Expert" difficulty then you should expect a challenge :) It's not a bug that the game is challenging on the highest difficulty. Hint, learn to skid, this helps a lot with difficult challenges

**Comment by LiamM32** [comment]
Yeah, I know.  But I think that it's better if the challenge is to beat the other karts.  On some tracks, the time limit is enough for the AI karts to complete the race but not the two that I mentioned.
