### ISSUE TITLE
Multiple Issues with 0.9.2

### ISSUE THREAD

**Issue by feralshade** [supertuxkart/stk-code#2646]
Before upgrading to 0.9.2:
- 'your OpenGL appears to be too old...requires OpenGL 3.1 or better'.

After upgrading:
(that, plus...)
- system hangs when loading a TTY or Alt-tab.

- numeric keypad keys are misinterpreted when attempting to bind/re-bind controls, creating conflicts.  ex)nitro set to {up arrow}, accelerate set to {numkey8}...it'll display both as set to {up arrow}

OS: ubuntu 16.04
glxinfo | grep OpenGL:
> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) Q45/Q43 x86/MMX/SSE2
> OpenGL version string: 2.1 Mesa 12.1.0-devel
> OpenGL shading language version string: 1.20
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 2.0 Mesa 12.1.0-devel
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
> OpenGL ES profile extensions:

lspci | grep VGA:
> 00:02.0 VGA compatible controller: Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03)

I tried apt-get update, upgrade, etc, from the oibaf graphic driver repository as well and it had no effect.  I tried googling a resolution but couldn't find anything directly applicable, and am now highly exasperated due to my inexperience with Linux.  Please help if possible. Thanks in advance!

**Comment by auriamg** [comment]
Your gpu or OpenGL drivers appear to support only OpenGL 2, but SuperTuxKart requires OpenGL 3.1 or better

**Comment by qwertychouskie** [comment]
Desktop or laptop? If you are using a desktop, you really should look into something [like this](https://www.amazon.com/EVGA-GeForce-Profile-Graphics-02G-P3-3733-KR/dp/B00L5GZ8GE/).

**Comment by qwertychouskie** [comment]
Because the OpenGL 2.1 pipeline is known to be buggy and is not supported.

**Comment by feralshade** [comment]
@qwertychouskie 
Recently my Alienware laptop crashed after 8 years, so in the meantime I've been booting off an Ubuntu external drive at local library computers--so hardware modifications aren't an option in this situation. (although, the OpenGL error started when I used these systems, so it may be hardware-rooted).

I remember a long time ago Windows  (sorry for using the "W" word) came out with Direct-X to allow a software alternative to obsolete/poor-performing graphics cards.  Along those lines, is there something reliable that I can use here to "emulate" OpenGL 3.1 support...or 3.1 itself?

If the general verdict is that it's abolutely a hardware thing, I'm fine with waiting it out for a few months...the game's playable, just the graphics are a bit wonky...but error messages are annoying to routinely encounter, so i'm hoping there's sonething I can do on the software side.

...As for the other errors....
even before the OpenGL thing, I tried 0.9.2-RC1 several months ago and experienced the other 2 errors (the process-shifting thing and the keypad nonresponsiveness thing).  I got so frustrated that I uninstalled it and returned to 0.9.1, where the controls worked fine (still do, on that release).  On the current 9.2 though (i upgraded again because I like using the current version of something), if I bind 1 action to the "Home" key, 1 action to the "num7" key, and 1 action assigned to the "num5" key, it'll say that all 3 actions are assigned to "Home" and that there is a conflict.
This affects me personally because I usually use the numeric keypad for acceleration and steering and the direction arrows for other actions. For example, the up arrow to 'Nitro' and the num8 key to 'Accelerate'...but it shows up as both being "Up" so in-game, I can't accelerate
...yeah, I can reassign keys to compensate, but adjusting to a new configuration can cost you seconds on the track.

**Comment by deveee** [comment]
Regarding to emulate OpenGL 3.1 support, you can use software rendering. If you have strong CPU, it should run smooth on lowest settings. You can run:
```LIBGL_ALWAYS_SOFTWARE=1 supertuxkart```

The error message can be disabled in config.xml file. You can set ```old_driver_popup``` to false.

I fixed the numpad keys rather long time ago, but it looks that it is broken again in current version. I must look what happened.

**Comment by qwertychouskie** [comment]
> For example, the up arrow to 'Nitro' and the num8 key to 'Accelerate'...but it shows up as both being "Up" so in-game, I can't accelerate

It sees you need to turn "Numlock" on.

**Comment by deveee** [comment]
It looks that numpad keys have been broken since this modification in CIrrDeviceLinux.cpp: 2096532d0e654a2f67c968879a86e1b4b8298007

@Benau could you check if it can be easily fixed? Previously it was just using keys defined in keymap:
```
	KeyMap.push_back(SKeyMap(XK_KP_0, KEY_NUMPAD0));
	KeyMap.push_back(SKeyMap(XK_KP_1, KEY_NUMPAD1));
	KeyMap.push_back(SKeyMap(XK_KP_2, KEY_NUMPAD2));
...
```

**Comment by Benau** [comment]
see: http://irrlicht.sourceforge.net/forum/viewtopic.php?f=4&t=50484

Seems that XwcLookupString doesn't work with numpad...

**Comment by deveee** [comment]
We can use ```mp.X11Key = XkbKeycodeToKeysym(display, event.xkey.keycode, 0, 1);``` (with last parameter set to 1) and first check if there is a numpad key pressed. If not, then use standard ```mp.X11Key = XkbKeycodeToKeysym(display, event.xkey.keycode, 0, 0);```
Or we can also try to read numlock state. It can be probably done using ```XGetKeyboardControl```, but I'm not sure if we want to check it on every event...

**Comment by deveee** [comment]
Here is a quick and ugly workaround:
```
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
index 374d7f6..d9a7f57 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
@@ -1264,8 +1264,13 @@ EKEY_CODE CIrrDeviceLinux::getKeyCode(XEvent &event)
 {
 	EKEY_CODE keyCode = (EKEY_CODE)0;
 
+	bool numlock_enabled = event.xkey.state >> 4;
 	SKeyMap mp;
-	mp.X11Key = XkbKeycodeToKeysym(display, event.xkey.keycode, 0, 0);
+	mp.X11Key = XkbKeycodeToKeysym(display, event.xkey.keycode, 0, numlock_enabled ? 1 : 0);
+	
+	if (mp.X11Key < XK_KP_0 || mp.X11Key > XK_KP_9)
+		mp.X11Key = XkbKeycodeToKeysym(display, event.xkey.keycode, 0, 0);
+		
 	// mp.X11Key = XKeycodeToKeysym(XDisplay, event.xkey.keycode, 0);	// deprecated, if we still find platforms which need that we have to use some define
 	const s32 idx = KeyMap.binary_search(mp);
 	if (idx != -1)
```

But I don't know if this is 100% correct, because the X11 documentation is rather poor :/ 

I also noticed that there is more issues. When I try to assign keys: [  ]  ;  '  ` etc. I see only the "?" character. But these keys are assigned properly anyway. Maybe just these characters are not loaded from font file?

And also when I try to asssign the key to  =, I see in options  + character instead.

**Comment by nado** [comment]
>>And also when I try to asssign the key to =, I see in options + character instead.
Seems + is the uppercase key of = on qwerty keymaps and the letters being shown uppercase, I guess it is logical.

**Comment by deveee** [comment]
Numpad keys should be fixed in this commit:
https://github.com/supertuxkart/stk-code/commit/5c4b61a26e622d40b21fe93cc1d0c9eda132baab

It works for me, but it would be nice if someone could test it.

Regarding to the = key, it is not available in irrlicht at all as a key name. But it looks that it doesn't matter that much. It's just a name of the key and it can be named + and everyone will know which button is this.

**Comment by deveee** [comment]
Displaying some special characters such as parenthesis, semicolon etc. on linux should be fixed in this commit:
https://github.com/supertuxkart/stk-code/commit/8092cfc0a7fa84e02657d582312eae256045914b

Again some testing is welcome because we have a lot of languages, keyboard configurations etc...

The ```system hangs when loading a TTY or Alt-tab.``` is not our bug, but most probably something wrong with graphics drivers (I often had similar issues with gen4 intel graphics card), so I assume that we can close it as fixed.
