### ISSUE TITLE
3 player split screen broken

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2651]
```
glViewport(viewport.UpperLeftCorner.X, viewport.UpperLeftCorner.Y, viewport.LowerRightCorner.X, viewport.LowerRightCorner.Y);

```
This line 288 in render.cpp seems to be blamed

**Comment by deveee** [comment]
I will look at this

**Comment by deveee** [comment]
It should be something like this:
                glViewport(viewport.UpperLeftCorner.X,
                           irr_driver->getActualScreenSize().Height -
viewport.LowerRightCorner.Y,
                           viewport.LowerRightCorner.X -
viewport.UpperLeftCorner.X,
                           viewport.LowerRightCorner.Y -
viewport.UpperLeftCorner.Y);

Actually it should be handled in camera->activate(), but sometimes it
doesn't work becuase we mix
irr_driver->getVideoDriver()->setViewPort(m_viewport); and glViewport(...)
functions.

The
    if (area == ViewPort)
        return;
in setViewPort function could be just removed to fix this.

I will check it more carefully later.

**Comment by deveee** [comment]
It should be fixed in this commit:
https://github.com/supertuxkart/stk-code/commit/850b23db1f501fef812e1025b056bdb2a4757789

I also fixed SSAO, RSM and normals vizualization in multiplayer games.
