### ISSUE TITLE
Medium / heavy karts acceleration bug

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2656]
![screenshot](https://cloud.githubusercontent.com/assets/3252341/19510305/30374e22-95d2-11e6-8645-6073092cd3ce.jpg)
Medium / heavy karts have initial power-increase in kart_characteristics.xml the smallest value, so when it starts to accelerate on very steep hill, its power is not enough to climb as shown in screenshot (in gift package las dunas arena). (Light has "5 4 3" which is enoguh)

Easy fix, make that surface "hasGravity", or something else?

**Comment by auriamg** [comment]
Will be fixed in next version
