### ISSUE TITLE
Low FPS on High Settings

### ISSUE THREAD

**Issue by alexeysvrv** [supertuxkart/stk-code#2657]
Hi. I Have low FPS on High settings(12/12/12-25/25/25) on my GeForce GT440, proprietary driver, Phenom X4 965. Ubuntu 14.04, Kernel 4.2, MATE 1.8. SuperTuxKart 0.9.2

**Comment by auriamg** [comment]
Hi,

the GT440 is a low-to-mid-end GPU from 6 years ago, so it is quite normal that it cannot run modern games at high settings. For older / less powerful GPUs, the medium or low settings are recommended

According to http://www.game-debate.com/hardware/?gid=468&graphics=GeForce%20GT%20440 , this GPU is unable to run most modern games, so STK is actually doing a better backwards compatibility job than most games - you can't expect to run STK on high graphics however

**Comment by SuicSoft** [comment]
Try the latest STK git version. I used to get 20 FPS at high on my 7640g but now with git I am getting 40 - 60. Also with git I can run it at 20 FPS at ultra settings (before only 7 FPS)
