### ISSUE TITLE
Add option for disabling rendering of lights other than the sun

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2663]
This would help performance on low-end cards...

**Comment by auriamg** [comment]
There is already an option that disable lighting, that's disabling the advanced pipeline. We are aware there are some performance issues in the new pipeline and that the fallback could perhaps be better but this ticket tells us nothing that we don't already know

**Comment by qwertychouskie** [comment]
I meant to disable extra lights.  Commenting out all the `<light params></light>` tags and all torch library objects brought minimum performance on Cocoa Temple up from 10 FPS to about 18 (until my card started heating up), and the overall experience was much better.  I don't want all lighting disabled, just the unnecessary ones.
