### ISSUE TITLE
Find better way for closing threads

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2665]
Currently we set following parameter after creating a thread:
```
pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
```

Unfortunately this feature is not available on Android.

It seems to be unused in audio thread, but I see at least one "pthread_cancel" function call in network thread. 

This causes that the window is never closed when you press "Quit" button. You can still force to close the game by just removing it from taskbar. But it would be nice to have it working properly.

@hiker do you want to look at this? In worst case I can probably just use kill signal to handle closing the thread.

**Comment by SuicSoft** [comment]
@devee Probably just use C++11 std::thread which should be supported on all platforms.

**Comment by hiker** [comment]
I've disabled the console (which should never have been disabled). For now I'd prefer to leave the console in the code (though I doubt it works atm ;) ) - would save me some time if I need some debugging code later on (the console causes a crash on exit on windows in release mode, which is not that easy to fix - ideally I'll remove it and add the functionality if I need to  to the debug menu).

Does this solve the problem for now? We can remove the calls to setcancelstate, since this is the default anyway (and all other threads don't need it anyway), if it helps compiling.

**Comment by SuicSoft** [comment]
@devee Also where can I download your Android port

**Comment by deveee** [comment]
Thanks for quick answer. 

This unfortunately doesn't help. It seems to be a problem with threads because it was working fine before I added sound and networking support (I mean that quit button was closing the app).

I tried to run it under debugger to see if this is a problem with threads or with something other, but I received corrupted/incomplete backtrace. I just get these few lines in console:
```
11-09 21:19:45.280  2486  2500 D SuperTuxKart: Start waiting 1254035.456000
11-09 21:19:47.282  2486  2500 D SuperTuxKart: Stop waiting 1254037.458000
11-09 21:19:47.283  2486  2500 D SuperTuxKart: Waited for more than 2.000000 seconds for thread to become deleteable
11-09 21:19:47.283  2486  2500 I SuperTuxKart: News manager not stopping, exiting anyway.
```

Btw. totally removing pthread_setcancelstate doesn't matter that much because I can always use #ifndef ANDROID. But if you want to have it cleaner, then why not ;)

Actually it's not that high priority because the game is still playable, but I would like eventually try to fix this. I will try to find the reason of this bug later.

**Comment by deveee** [comment]
Ok, it looks that there is several issues. For example the "News manager not stopping" message, which is displayed even if internet connection is disabled in options :P It was under emulator, maybe that was the reason that timeout has been reached.

I eventually solved it by setting ANativeActivity_finish(app->activity); at the end of android main function. There are some articles that suggest to use this function, even though it's not used in official android examples.

But your commit was probably needed anyway :)

**Comment by SuicSoft** [comment]
@deveee Where can I download the Android port and compile it so I can see if it works on my phone
