### ISSUE TITLE
Persistent Challenge Timer

### ISSUE THREAD

**Issue by GetHandle7** [supertuxkart/stk-code#2666]
When I play a story mode challenge with a count-down timer, that timer persists for all other tracks I play (including strange behavior with follow-the-leader timers where it counts up from the timer value instead of down to zero) and shows "challenge failed" after the timer runs out, regardless of whether I am playing a timed challenge or just a regular single player track. This bug does not actually prevent the challenge from being completed, and it does not persist when the program is terminated and restarted. If I play another challenge with a count-down timer, the previous timer is replaced with the count-down timer of the current challenge.

Version 0.9.2 downloaded for Linux as .tar file. Running on Mint 18.

Screenshots:
Follow the leader before timed track (correctly starts at 0:30 and counts down)
![stk_enterprise_normal](https://cloud.githubusercontent.com/assets/18090724/20232235/c7c54b44-a834-11e6-85bc-6833a21eaae8.png)

Timed track (mine) (starts at 2:50)
![mine_2_50_timer](https://cloud.githubusercontent.com/assets/18090724/20232239/cf914bca-a834-11e6-8add-be70c2451151.png)

Follow the leader after timed track (starts at 2:20 and counts up to 2:50 for elimination)
![stk_enterprise_after_mine](https://cloud.githubusercontent.com/assets/18090724/20232238/cc6aaa04-a834-11e6-9c0d-3ccc375626bc.png)

Regular single player downloaded track (carnaval del cacao) after timed track (counts down from 2:50 when it should count up from 0:00)
![carnaval_after_mine](https://cloud.githubusercontent.com/assets/18090724/20232241/d1466676-a834-11e6-9489-7cb94bf3b7fe.png)

**Comment by qwertychouskie** [comment]
I think there were some timer-related commits in `master` since 0.9.2, could you try and see if is an issue in the latest version?

sudo add-apt-repository [ppa:stk/daily](https://code.launchpad.net/~stk/+archive/ubuntu/daily) && sudo add-apt-repository [ppa:asdfghrbljzmkd/stk-test](https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test) && sudo apt update && sudo apt install supertuxkart

**Comment by Benau** [comment]
in world.cpp:485 (git master)
race_manager->setTimeTarget(0.0f);

The timer will always get reset now

**Comment by auriamg** [comment]
Or, to clarify Benau's pos : this has been fixed for next version :)
