### ISSUE TITLE
Kart shadow is broken

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2667]
Old kart shadow, which is used as a fallback when shadows are disabled in options, is currently broken.

Actually there are two issues:
1. This kart shadow is not displayed at all on most graphics cards. It's because:
```
    if (!CVS->supportsShadows())
    {
        m_shadow = new Shadow(m_kart_properties.get(), m_node,
                              -m_kart_model->getLowestPoint());
    }
```
It is created only if geometry shaders are not available at all. If shadows are available, but they are just disabled in options, this condition still returns true.

It's trivial to fix and it should be just
```if (!CVS->isShadowEnabled())```

2. It looks buggy. Sometimes it looks that it is displayed below ground and sometimes it is misplaced when you run fast on a hill - see attached screenshots:
![zrzut ekranu z 2016-11-14 22-32-07](https://cloud.githubusercontent.com/assets/5108558/20283789/b8e0dfde-aaba-11e6-8b8b-5e835d865b68.png)
![zrzut ekranu z 2016-11-14 22-33-08](https://cloud.githubusercontent.com/assets/5108558/20283788/b8e079c2-aaba-11e6-9e20-8b1e07fc60dc.png)

We should fix this or totally remove it, because it still works in this way on some hardware (for graphics cards with OpenGL < 3.3)

**Comment by SuicSoft** [comment]
@devee I also noticed this issue.The legacy pipeline seems to have the part shadow working

**Comment by qwertychouskie** [comment]
@SuicSoft Not really... (At least for me.)

**Comment by hiker** [comment]
Hi

> Old kart shadow, which is used as a fallback when shadows are disabled
> in options, is currently broken.
>
> Actually there are two issues:
>
>  1. This kart shadow is not displayed at all on most graphics cards.
>     It's because:
>
...

> It's trivial to fix and it should be just
> |if (!CVS->isShadowEnabled())|
That's indeed an easy fix that should be applied.


>
>  2. It looks buggy. Sometimes it looks that it is displayed below ground
>     and sometimes it is misplaced when you run fast on a hill - see
>     attached screenshots:
>     zrzut ekranu z 2016-11-14 22-32-07
>     <https://cloud.githubusercontent.com/assets/5108558/20283789/b8e0dfde-aaba-11e6-8b8b-5e835d865b68.png>
>     zrzut ekranu z 2016-11-14 22-33-08
>     <https://cloud.githubusercontent.com/assets/5108558/20283788/b8e079c2-aaba-11e6-9e20-8b1e07fc60dc.png>
 From memory: the shadow position is based on a single raycast, so if 
the terrain is not even enough, it will partially disappear or hover in 
the air.

>
> We should fix this or totally remove it, because it still works in this
> way on some hardware (for graphics cards with OpenGL < 3.3)
I see three options:
1) we accept this for older hardware (I am quite happy with this ;)  )
2) Instead of using the centre of kart raycast, we use the 4 raycast for 
the wheels to get the quads for the shadow. This would need some scaling 
(wheel positions might not be same as shadow size), plus in really bad 
terrains (e.g. if the middle of the kart is the top of a small hill) it 
might still have artifacts.
3) Remove it.

I am happy with 1) tbh ;)

Cheers,
    Joerg

**Comment by deveee** [comment]
I just checked STK 0.8.1 and it was working properly in the past.

The problem is the when I will fix the isShadowEnabled bug, then it will be enabled for every hardware :P So the first option ```we accept this for older hardware``` means that we shouldn't touch anything and it won't be displayed as a fallback when shadows are disabled in options.

It looks really bad for me, especially when you run fast on a hill or when you are falling down. I'd say that we should totally disable it (or fix if someone wants to do it).

**Comment by Benau** [comment]
```
m_shadow->update(isOnGround() && !emergency,
    getTrans().inverse()(m_terrain_info->getHitPoint()).getY() -
    - m_skidding->getGraphicalJumpOffset()
    - m_graphical_y_offset
    - m_kart_model->getLowestPoint());
```
That will fix "run fast on a hill or when you are falling down", but not disappearance on non-flat ground which requires recalculation of quad.

**Comment by Benau** [comment]
deve can you see if latest commit the kart shadow is good for you?
It use dynamic draw call features (4 wheel raycasts in world position, so it will subdata 48 * 4 bytes each frame for each kart, but should not affect performance)

and let me think if there can be some good fix than subimage the fb texture....

**Comment by Benau** [comment]
Fixed
