### ISSUE TITLE
Image not stable

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2669]
Hi, 

I noticed that the rendered image is not stable, and it depends on which kart i use, and sometimes the position were i stand. I noticed it with adimum, konqui, suzanne, amanda, tux… and the worst with puffy, tested on "Oliver's Math Class". It's easily noticeable when your kart is stopped. 

Visuals effects to minimal 
fullscreen 1920x1080. 
Graphic card : Quadro K2000M

do you need extra infos ?

Good night ;)

**Comment by Arthur-D** [comment]
Hi, what do you mean with "not stable"? Kart shaking? Camera shaking? Something else? Also, what graphics driver, driver version and operating system do you use?

**Comment by rogue-spectre** [comment]
The kart shaking and the camera. For some of the kart you can just see the kart shaking a little, and for others the kart and the camera. 

Xubuntu 14.04.5 64bits (kernel 3.13.0-101-generic)
Nvidia drivers 352.63

**Comment by rogue-spectre** [comment]
+ does it on :
Xubuntu 14.04.5 64bits (kernel 3.13.0-101-generic)
Graphic Card : Nvidia Quadro K600
Drivers 367.57 (from ubuntu repositories)

**Comment by rogue-spectre** [comment]
With STK 0.9.2, i just see the kart shaking with the normal view but the camera shakes with the backward view.

**Comment by qwertychouskie** [comment]
@rogue-spectre This should be fixed in Git.  Can you retest with the latest code?  You should be able to test it with:
```
sudo add-apt-repository ppa:stk/daily
sudo add-apt-repository ppa:asdfghrbljzmkd/stk-test
sudo apt-get update
sudo apt-get install supertuxkart
```

**Comment by Benau** [comment]
camera shaking is fixed for a long time, and so as the kart shaking when stop(related to #2939)
