### ISSUE TITLE
Useless Girl Inside a House - Northern Resort

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2671]
There is a girl inside one of the houses of northern resort. We can't see her from the outside, and since we should not be able to get inside… she's useless ;)

![useless_girl](https://cloud.githubusercontent.com/assets/2879782/20577515/fc921536-b1c2-11e6-9c19-5df03297043c.png)

**Comment by Jiikuy** [comment]
Maybe an easter egg?
