### ISSUE TITLE
Trees, lights, start pillars not solid - Zen Garden

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2673]
On Zen Garden, some trees, the start pillars and light supports are not solid

![bug_light](https://cloud.githubusercontent.com/assets/2879782/20578519/0631c06e-b1c8-11e6-980f-2d819858c495.png)
![bug_pillars](https://cloud.githubusercontent.com/assets/2879782/20578521/0636773a-b1c8-11e6-8125-495105e9aabc.png)
![bug_tree2](https://cloud.githubusercontent.com/assets/2879782/20578520/06336f54-b1c8-11e6-839a-8fd139ce6485.png)

**Comment by auriamg** [comment]
Fixed in SVN
