### ISSUE TITLE
Collision too strong

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2674]
Hi, 
       when hitting something static even with a very small speed the kart is projected. I agree that a repulsion force can/must happens, but the kart must have a smaller speed after the impact than before. For instance in the Blackhill Mansion, on the stone bridge before the arrival, if your kart hit the bridge perpendicular to the road, it can make several bumps between the too sides of the bridge before stopping and without touching the speed after the first hit.

**Comment by qwertychouskie** [comment]
This is fixed in git, can be closed.

**Comment by auriamg** [comment]
It does feel a lot better in latest git, I think this can indeed be closed
