### ISSUE TITLE
Too large Hit-box light supports - Blackhill Mansion

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2675]
The light supports have a too large hit-box on Blackhill Mansion Track. On the screenshot here, if a go a little further a hit it.

![bug_hitboxlight](https://cloud.githubusercontent.com/assets/2879782/20605205/74a9808e-b26a-11e6-908a-22034379b3fa.png)

**Comment by SuicSoft** [comment]
I also noticed this in Northern Resort

**Comment by rogue-spectre** [comment]
the wood support to modify
https://svn.code.sf.net/p/supertuxkart/code/media/trunk/library/streetFurniture/stklib_woodPostLamp_a
it seems the flag to modify is interaction on the blender file (set to physics or draw on simpler outline and add physicsonly ?), i'll try to do this and see

**Comment by auriamg** [comment]
Fixed in SVN
