### ISSUE TITLE
Big Nitro hitbox too small

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2678]
Hi, 
         Trying to get the second nitro on ramps of Oliver Math Class, i noticed that sometimes i don't get it whereas i'm passing right on it. Here a little video 

![optimised](https://cloud.githubusercontent.com/assets/2879782/20640732/21a7ce1c-b3e7-11e6-9625-88b85bd4fc1f.gif)

**Comment by Arthur-D** [comment]
Actually, as far as I know, all collectibles only have a single point in the middle where you collect it. So there's not a hitbox, but a hitpoint, which explains why this happens.
I do agree that it looks bad especially with the big nitro in your video, you pass through most of it but apparently misses the hitpoint. So I think collectibles should probably get at least one other test point for the physics, for example:
                          |           |
Visual boundary |  +  +  | Visual Boundary
                          |           |

Eventually:
                          | +       |
Visual boundary |           | Visual Boundary
                          |       + |

With four points, commonly referred to as a hitbox:
                          |  +  +  |
Visual boundary |           | Visual Boundary
                          |  +  +  |

However, I think some level design, or rather collectibles placement, is made with the single point in mind, so for example in a relatively tight row of small nitros you might visually touch more than one nitro but you only collect one, leaving more for those behind you. I am unsure how much this is the case though, and in any case collectibles can be moved to accommodate for two collision points or a proper hitbox.
