### ISSUE TITLE
Text in legacy pipeline is fuzzy

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2679]
Plus the bottom of the text is cut off a tiny bit.
![Screenshot](http://i.imgur.com/vfIS0z9.png)

**Comment by auriamg** [comment]
the legacy pipeline is offered as a fallback only but is not officially supported. Also the text remains quite readable in your screenshot, there's no real issue there.

**Comment by SuicSoft** [comment]
@qwertychouksie What GPU do you have ?

**Comment by qwertychouskie** [comment]
Intel HD 3000 in Linux, Mesa git.  Will retest after merging of the new texture branch, might be fixed.
