### ISSUE TITLE
SuperTuxKart 0.9.2.1?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2680]
Since the release of STK 0.9.2, [144 issues were closed](https://github.com/supertuxkart/stk-code/issues?utf8=%E2%9C%93&q=is%3Aissue%20closed%3A%3E2016-06-26%20), [34 PRs merged](https://github.com/supertuxkart/stk-code/pulls?utf8=%E2%9C%93&q=is%3Apr%20merged%3A%3E2016-06-26%20), and [836 changes were commited to master](https://github.com/supertuxkart/stk-code/tree/0.9.2-branch).  Maybe it's time for a bugfix release?

**Comment by auriamg** [comment]
This is a bug tracker, meant to report bugs and issues. Please do not use the bug tracker for such suggestions, this is not the right place to do so.

Also, we are fully aware of what has changed since last version and we are capable of planning releases.
