### ISSUE TITLE
Cocoa Temple - Improve boost ramp under gear

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2683]
Hi,
       I think the boost under the gear needs three improvements. The first on should be to reduce the power of the boost because it's impossible to take it without hitting the wall when getting back on the road. On the following gif, i take it with a limited speed and i hit the wall.
   
![shortcut2](https://cloud.githubusercontent.com/assets/2879782/21083078/a78cc9b2-bfe8-11e6-88b4-a31dde82d568.gif)

The second improvement (minor) could be to adjust the ramp in order to be at the same level as the road.

The third one is to adjust the camera motion. With the gif we can see two changes of camera. It seems that the camera gets locked when the kart begins to get under the gear, so we see the kart go away and then when the kart is no longer under the gear, the camera suddenly comes back to a normal view of the kart. (maybe this needs an other ticket ?)

**Comment by Benau** [comment]
3 wishes come true at once in spm
