### ISSUE TITLE
Menu - Kart selection - Speed ratio

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2684]
I noticed that the evaluation of speed given in the kart selection menu is a little wrong. Here two screenshots with suzanne's kart which is one with the greatest speed and sara's kart which is one whit the smallest speed. 
   
![bug_speedbar1](https://cloud.githubusercontent.com/assets/2879782/21083191/4be2b948-bfeb-11e6-9dd3-0053bb69c76e.png)
![bug_speedbar2](https://cloud.githubusercontent.com/assets/2879782/21083192/4be540aa-bfeb-11e6-9e3f-675491899f45.png)

**Comment by rogue-spectre** [comment]
i just restarted the game and the speed is correct…

**Comment by rogue-spectre** [comment]
I get it, the first time you get into the kart selection menu, the speed bar is influenced by the level of difficulty of the last game launch but not by the difficulty of your last race launch. 

So there is a bug ;)… that could be converted into a feature if the race option menu is placed before the kart selection menu. 

Sorry it's a duplicate of https://github.com/supertuxkart/stk-code/issues/2539

**Comment by auriamg** [comment]
Fixed, thanks for precisely describing how to reproduce!
