### ISSUE TITLE
Shortcut - Rescue too soon - Gran Paradiso

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2686]
On the shortcut  of Gran Paradiso Island (the one leading to the airplane landing), if you get near of the edges of the bride, you can get "saved" by thunderbird without having the need to. Here a screenshot

![bugthunderbird](https://cloud.githubusercontent.com/assets/2879782/21083450/32c097e0-bff1-11e6-9429-2da519fddf99.png)

**Comment by Benau** [comment]
Fix in svn
