### ISSUE TITLE
Wrong camera target after restarting split screen 3 strike battle

### ISSUE THREAD

**Issue by LoadingPleaseWait** [supertuxkart/stk-code#2687]
If one player wins the 3 strike battle, the other player's part of the screen will look at the wrong kart after clicking the restart button. It is possible that the player who lost might even be looking at the kart of the player who won the previous game. The losing player is still able to control his kart and the camera target can still be changed to the correct kart in artist debug mode.
![stadium-2016 12 13_03 16 03](https://cloud.githubusercontent.com/assets/6393711/21135368/4b81bb46-c0e7-11e6-8a5e-e0bed6ea5f13.png)

**Comment by auriamg** [comment]
Also needs to be fixed in multiplayer follow-the-leader
