### ISSUE TITLE
Can't turn right on 2010-ish MacBook Pro (must disable "applesmc" input device)

### ISSUE THREAD

**Issue by brion** [supertuxkart/stk-code#2691]
This looks similar to https://github.com/supertuxkart/stk-code/issues/1167 -- with STK 0.9.2 in Fedora 25 on a 2010 MacBook Pro, I can't turn right using the right arrow key, while the left, up, and down keys work as expected for turning left, accelerating, and decelerating.

If I go into the input options, a mysterious gamepad device called "applesmc" is visible; if I quit back to main menu, go into the options for the device, disable it, and then go back into the game, the right arrow key works as expected.

![input-devices](https://cloud.githubusercontent.com/assets/103075/21219575/2bfb0276-c26a-11e6-98fa-4228e3d31be1.jpg)

Thanks everybody for all your work on STK -- it's a fun game that I've spent hours playing in the past, glad to see it's still under development. :)

**Comment by SuicSoft** [comment]
@brion AppleMC seems to control the accelerometer which is likely reason it is an input device. Does anything change when you tilt you laptop.

My laptop also has an accelerometer but STK has disabled it though it works with Neverball (quite fun ! :)

**Comment by brion** [comment]
@SuicSoft ha yes! If I re-enable it, tilting left and right turns left and right. Unexpected but pretty fun if one's actually intending to play that way. ;) Not sure why it breaks the right arrow key though...

**Comment by brion** [comment]
Aaaaah I see, whichever direction the laptop is slightly tilted in, the arrow key in that direction fails to do anything. I think it's trying to "very slightly" turn based on the faux-joystick and that's somehow disabling the "turn a lot" arrow key from doing anything.

**Comment by auriamg** [comment]
I have committed a fix that should cause STK to ignore "applesmc". If you are building from source (latest git), it would be nice if you could confirm that it fixes the issue. Otherwise, that will have to wait for next release

**Comment by auriamg** [comment]
I will assume that one with a mac is able to confirm that the fix works, so I'll just close this ticket as fixed. If the issue should happen again after next release, please let us know

**Comment by brion** [comment]
I managed to build from source on the MacBook Pro and can confirm it's no longer showing the faux joystick device; arrow keys work as expected. Thanks! :)
