### ISSUE TITLE
Xiaomi mipad game controller not detected (and working with emulators) + Android version sugesstion

### ISSUE THREAD

**Issue by mitcoes** [supertuxkart/stk-code#2695]
The Xiaomi mipad bluetooth game controller would be a great game controller 

And also great for a future Android version if it is planned, that I bet would be a hit on Smart TVs and TV Boxes (almost sold out this north winter holidays).

And the Android adds revenue can help this amazing project to improve.

**Comment by qwertychouskie** [comment]
@mitcoes Actually an Android version should be coming soon :)

https://play.google.com/store/apps/details?id=org.supertuxkart.stk

**Comment by hiker** [comment]
Can you check with 0.9.3? I am closing this ticket now, please reopen if this is still an issue. Note that there might not be much we can do if this controller needs 'special' code, since none of us devs have this controller.
