### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Jiikuy** [supertuxkart/stk-code#2696]
Here are some bugs i found:
1. Flying in Soccer mode
2. Driving on the ice in Snow Peak
3. Driving on the ground of Cocoa Temple
4. & 5. Driving on the ground of Fort Magma

https://youtu.be/pTYZG8y8jpY

**Comment by auriamg** [comment]
For the "Flying in Soccer mode" issue, I am unable to reproduce it, is there a specific procedure to follow to make this issue happen?

For the other issues of driving off-track, we are currently unable to prevent all of them, you'll just need to press the rescue button...

**Comment by Jiikuy** [comment]
I don't really know how and when it happens, but sometimes it does.

**Comment by Benau** [comment]
Actually after hiker physics fix adiumy is lessy likely to topple over, and when re-export to .spm for all tracks I have corrected all without-rescue-plane issue
