### ISSUE TITLE
omp parallel sections cause crashes

### ISSUE THREAD

**Issue by vlombart** [supertuxkart/stk-code#2697]
On the 0.9.2 version (and also 0.9.1) my computer uses100% CPU in the kart selection screen (display of rotating kart is really slow).
And during the races the game hangs most of the time and eventualy crashes.
(My computer : Intel i7, 6Go RAM, Windows 10, AMD Radeon HD 5800)

I downloaded the 0.9.2 code and compiled it under visual studio 2015 and reproduced the problem in debug mode. I solved the problem by removing the 5 lines containing #pragma omp parallel section in the file graphics/stk_scene_manager.cpp. (In short, I removed parrallel processing and have not seen any performance issues in sequential processing).
After rebuilding in release mode and replacing the exe in my game directory, the problem never occured again.

I have looked at the current code for this cpp file, and a lot of things have changed. So you may have already solved the problem for the next release, but I wrote this bug just in case it helps.

**Comment by auriamg** [comment]
Hi, this is the first time we hear of such an issue, to my knowledge no one else has ever experienced this. I don't know how experienced you are with code, do you think you might be able to diagnose what is going on for you?

**Comment by Flakebi** [comment]
The 100% CPU usage on Windows is because OpenMP on Windows uses busy waiting by default.

You can switch that off by setting the environment variable `OMP_WAIT_POLICY` to `passive` (see also #1918).

**Comment by vlombart** [comment]
Hi. I confirm that the OMP_WAIT_POLICY set to passive solve the 100% CPU on the kart selection screen. However with a binary having the original omp parallel section + WAIT_POLICY to passive, the game still hangs (2 times over 3 tests) : it just freezes in the middle of the race. While the binary without the parallel section has not hung yet (tested on more than 10 runs).

**Comment by qwertychouskie** [comment]
One thing I would try is updating the BIOS/UEFI.  On one computer I was playing STK on, it would sometimes crash, but when I updated the BIOS (well, UEFI on that computer), it fixed it.

**Comment by nado** [comment]
qwerty, you are suggesting to do something potentially harmful to the computer if done wrong, without any proof besides wild testing based on personal exp. That’s dangerous and we dont have any data to suggest that update.
Besides, the "var env" workaround seems to work, so its highly probably unrelated.

**Comment by qwertychouskie** [comment]
First, it the workaround is just a workaround.
Second, it did not fix all the problems:
> ... (It freezes in windowed screen, but that's another problem which occurs also with the binary without the parallel sections)
Third, I am aware of the issues it can cause if not done right, but if @vlombart is able to compile STK in debug mode and figure out a workaround, it is safe to assume that @vlombart is able to update a BIOS correctly. :)
Fourth, I have updated a lot of BIOSes, at least 5 according to a quick count (though I know there are many more that I am not counting), from a Dell Latitude C600 with a Pentium III (from version A0somthing to A23, which fixed a lot of issues), to a Dell Inspiron 3520 with a Core i5, all without issue, so the suggestion comes from experience, not just "wild testing".
Fifth, it was a "one thing I would try", not a "one thing you must try". ¯\_(ツ)_/¯

Also, @vlombart you could try updating the drivers for your chipset, graphics card, etc. first as that has less risk involved.

**Comment by vlombart** [comment]
Hi all. Everything is already to the latest available version (cpu, motherboard, graphic card, and bios).
The passive mode "seems to solve (or hide)" that issue. Game was crashing during races 8 times over 10 before and now it is about 1 time over 10.
There are still some other issues (still crashes sometimes - a lot less than before, and freezes in windowed screen), but I don't think that they are all related => I'll write other specific issues when I'll have figured out more precisely the problem and its occurrence.
But even if the workaround really does something positive, it is not clear to me on how it really solves the problem : because instead of looping to load CPU in active mode, threads just waits gently in passive mode, but the game behavior should stay about the same.

**Comment by deveee** [comment]
In current git version there was at least one commit that fixes infinite loop:
https://github.com/supertuxkart/stk-code/commit/150e40e4e8413b775cceca79ca795f4283dff5c7

And if it occurs more frequently when CPU usage is 100%, can this be overheating?

If you are able to reproduce it under debugger, you can send us a stack trace that should be available when the crash ocurred. Also when application hanged (which may be an infinite loop), you can pause execution and see what it actually does atm.

**Comment by Benau** [comment]
Stragus who contribute the graphics_utils/mipmap/* suggests that we get rid of the omp parallel for in draw calls upload completely, as it only use very few cpu cycles, and 50% of cpu time is wasted on busy waiting

Actually, he thinks the synchronization overhead is worse than the gain, In other words, it's slower with omp parallel

And some of these branches can perform GL calls if certain features aren't supported, meaning you would have GL calls coming from other threads (a very bad idea)

**Comment by Benau** [comment]
No more omp
