### ISSUE TITLE
Game is not running for me :(

### ISSUE THREAD

**Issue by drpeppercan** [supertuxkart/stk-code#2698]
I did confirm that I have both libraries glibc and gcc, higher versions than those requested:
ldd (Ubuntu GLIBC 2.23-0ubuntu5) 2.23
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Also found libgcc_s.so.1 and libstdc++.so.6 libraries. I found them both here: "/usr/lib/i386-linux-gnu".

I read [here](http://ubuntuhandbook.org/index.php/2015/04/install-supertuxkart-0-9-ubuntu-14-04/) that I needed to have this library too: libopenal1. 
According to Synaptic I have it, version: 1:1.16.0-3

So since just right-clicking the run_game.sh file and select "Run" is not doing a thing, I went in a Terminal and tried this, but only got some errors :(
```
sudo ./run_game.sh
Running 64-bit version...
[error  ] FileManager: Could not file 'supertuxkart.0.9.2'in any standard location (esp. ../data).
[error  ] FileManager: Last location checked '/usr/local/share/supertuxkart/data/'.
[fatal  ] FileManager: Set $SUPERTUXKART_DATADIR to point to the data directory.
```
What next?
Thanks in advance for your help :)

Specs: Ubuntu 16.04-64 bit, Full computer specs: Intel® Core™ i5-6400 CPU @ 2.70GHz × 4, 16 RAM, GeForce GTX 950/PCIe/SSE2, Nvidia binary driver - version 367.57 (proprietary, tested)

**Comment by qwertychouskie** [comment]
Your download probably got corrupted, try deleting the zip and folder and trying again.

**Comment by drpeppercan** [comment]
Wow! That was fast :)
Thanks I'll try that.

Happy holidays

**Comment by hiker** [comment]
Where did you get your version from? Is it our static binary? Can you send me the directory structure where you unpacked the files?

You appear not to have the assets/data files - and I think it's somewhat unlikely that our compressed file uncompresses, and then has only errors in the data directory.

**Comment by drpeppercan** [comment]
It's working now!
After downloading it twice, it finally is working!

I found this direct link: [Download SuperTuxKart 0.9](https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/), at this [page](http://ubuntuhandbook.org/index.php/2015/04/install-supertuxkart-0-9-ubuntu-14-04/)

I just unpacked it in my /home/javier/Downloads directory.

Thanks a bunch for helping :)
My daughter enjoys very much the previous version. I can't wait for her to see this new version, is going to love it! :)
