### ISSUE TITLE
Not loading all karts and restricting the number of karts displayed

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2703]
While trying to improve performances I just did a small test.

I removed all kart and kept only 4 of them in the game. Two things radically changed

1) Loading times where cut by 90%, I got an almost instantaneous startup
2) VRAM Usage was also reduced

We should find a way to not load all karts and maybe restrict the number of players, like maximum 10 players and only load  those then

**Comment by deveee** [comment]
When you remove most karts and set non-hd textures size to 256x256, you can
reduce RAM usage from 850MB to something around 150MB.

I agree that we shouldn't load all karts on startup. If someone has a lot
of add-on karts installed,he may be not able to start STK at all if he
don't have enough RAM. It would be useful on Android devices where we have
limited RAM. I thing that 1GB should be enough (STK uses 125MB in basic
configuration), but we can't load all karts on startup when we want to
include it in the package.


2016-12-24 20:01 GMT+01:00 samuncle <notifications@github.com>:

**Comment by Benau** [comment]
You can have instant start-up if are using lastest master + release build + your gpu supports buffer storage and pixel buffer object
