### ISSUE TITLE
Lives don't get displayed in arena battles with 20+ players

### ISSUE THREAD

**Issue by Jiikuy** [supertuxkart/stk-code#2705]
If i play an arena battle on large add-on maps like Two Towers, i can't see my lives on the side, so i don't know when i will be out.
![bildschirmfoto vom 2016-12-26 14-57-07](https://cloud.githubusercontent.com/assets/17340937/21482988/a1dd728e-cb7b-11e6-987a-e83eb3f32482.png)

**Comment by Benau** [comment]
I actually tell the arena maker to lower the starting position number, but he seems to forget about it:/

Also addon is not meant to be supported by us, and play with battle mode > 10 karts maks no sense anyway

**Comment by CodingJellyfish** [comment]
Cause of https://github.com/supertuxkart/stk-code/issues/5084, could solve it while not reopening this one with https://github.com/supertuxkart/stk-code/issues/3832
