### ISSUE TITLE
Bump in the road in the mines

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2708]
At this specific spot in the mines, there is a little bump in the road. If you hit it really fast (use zippers just before), the kart is thrown into the air

![](https://puu.sh/t5m5D/61d45b75ce.png)

**Comment by kitokofox** [comment]
It's not a race.. it's not a race..
I'll tell myself not to go too fast.

**Comment by SuicSoft** [comment]
I noticed this and ignored it

**Comment by auriamg** [comment]
Fixed in SVN
