### ISSUE TITLE
STK 0.9.1 doesn't run in fullscreen and don't allow me to change resolution

### ISSUE THREAD

**Issue by cpcbegin** [supertuxkart/stk-code#2710]
STK only runs in window mode in 1024x768 mode, if I try to change to fullscreen or change the resolution the game crashes.
I enclose an screenshot and information of lspci of my i7 with 8Gb RAM
[lspci.txt](https://github.com/supertuxkart/stk-code/files/678558/lspci.txt)

![stk_bug](https://cloud.githubusercontent.com/assets/10259216/21564015/7888950c-ce88-11e6-9a25-5fa93c718753.png)

**Comment by Benau** [comment]
Can you try 0.9.2 of stk?

It should have fixed the crashing changing resolution like #2450

**Comment by Benau** [comment]
Also, you do have usb wireless mouse connected? If so try remove it and see if it fixes the crash

**Comment by SuicSoft** [comment]
@cpcbegin What is your GPU , CPU , etc ?

**Comment by cpcbegin** [comment]
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Motherboard: Gigabyte Technology Co., Ltd. H81M-DS2
RAM: 8Gb
Graphic controller:  Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
NVIDIA Corporation GF119 [GeForce GT 610] (rev a1)
Open GL render: GeForce GT 610/PCIe/SSE2
Open GL version: 4.4.0 NVIDIA 340.98
OS: Ubuntu 16.04.01 xenial 64 bits
BIOS: American Megatrends Inc. F3 07/25/2013

**Comment by deveee** [comment]
If you are using the version from our website or self-compiled, you can run it under gdb. They should contain some basic symbols and it's better than nothing. If you have gdb installed, just run
```
gdb /path/to/stk
r
```
and after crash
```
bt
```
Or if you can compile it in debug mode, it will provide more information.

Btw. on the screenshot it looks that you run STK in windowed mode and it doesn't have decorations. Don't you run Mir session or so?

I can check how it works under Unity, I have Ubuntu 16.04 too. I didn't test STK under Unity for a very long time.

**Comment by deveee** [comment]
I sometimes get a crash on startup with ```pure virtual method called``` in current git version, but it never happened for me under gdb.

**Comment by hiker** [comment]
Closing this because of the 0.9.3 release. Please reopen if this is still an issue.
