### ISSUE TITLE
Hacienda has some art quirks.

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#2711]
![supertuxkart_2016-12-30_09-32-21](https://cloud.githubusercontent.com/assets/11599732/21566721/b77f33f2-ce73-11e6-81aa-ac017725eed5.jpg)
![supertuxkart_2016-12-30_09-34-52](https://cloud.githubusercontent.com/assets/11599732/21566724/ba5bce00-ce73-11e6-803e-f82b0802ceec.png)
Apparently these boxes defy physics.

**Comment by auriamg** [comment]
This is already fixed in svn, and will be available in next version
