### ISSUE TITLE
Getting Many Goals in Soccer Mode Makes Results Look Weird

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#2713]
![supertuxkart_2016-12-30_16-13-54](https://cloud.githubusercontent.com/assets/11599732/21572774/131583a6-ceab-11e6-8554-66a4b10b24bd.png)

It's the Spanish dream!

**Comment by auriamg** [comment]
How did you manage to score 28 goals? The game should end after 10 goals max
