### ISSUE TITLE
Can Go Out-Of-Bounds in Snow Peak

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#2714]
![supertuxkart_2016-12-30_20-40-02](https://cloud.githubusercontent.com/assets/11599732/21575124/38387b50-ced0-11e6-9e6f-cd7070ceabea.png)

you have to fly off the track very fast in order to do this, via the ledge I'm looking at.

**Comment by Benau** [comment]
duplicate of #2696
