### ISSUE TITLE
Snow Peak has a bunch of weird things.

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#2715]
More of a Snow Peak focused report.

https://puu.sh/t6l3w/84e0ec7e15.zip

1. Trees are excessively buggy. they don't fare well to karts.
2. The obvious out-of-bounds.
3. The random unintended shortcut.

The zip contains a demo of me screwing around in Snow Peak for a while.

**Comment by Benau** [comment]
all fixed with re-exported with .spm
