### ISSUE TITLE
Build failed on mint 18.1

### ISSUE THREAD

**Issue by v1993** [supertuxkart/stk-code#2716]
While building last version I got this error:

    [ 34%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o
    In file included from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.h:25:0,
                     from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:8:
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:65:33: error: expected ')' before 'PFNGLBLENDEQUATIONPROC'
             typedef void (APIENTRYP PFNGLBLENDEQUATIONPROC) (GLenum mode);
                                     ^
    In file included from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.h:25:0,
                     from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:8:
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1214:3: error: 'PFNGLPROVOKINGVERTEXPROC' does not name a type
       PFNGLPROVOKINGVERTEXPROC pGlProvokingVertexARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1215:3: error: 'PFNGLPROVOKINGVERTEXEXTPROC' does not name a type
       PFNGLPROVOKINGVERTEXEXTPROC pGlProvokingVertexEXT;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1219:3: error: 'PFNGLBLENDFUNCINDEXEDAMDPROC' does not name a type
       PFNGLBLENDFUNCINDEXEDAMDPROC pGlBlendFuncIndexedAMD;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1220:3: error: 'PFNGLBLENDFUNCIPROC' does not name a type
       PFNGLBLENDFUNCIPROC pGlBlendFunciARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1221:3: error: 'PFNGLBLENDEQUATIONINDEXEDAMDPROC' does not name a type
       PFNGLBLENDEQUATIONINDEXEDAMDPROC pGlBlendEquationIndexedAMD;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1222:3: error: 'PFNGLBLENDEQUATIONIPROC' does not name a type
       PFNGLBLENDEQUATIONIPROC pGlBlendEquationiARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlProvokingVertex(GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2298:52: error: 'pGlProvokingVertexARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_provoking_vertex] && pGlProvokingVertexARB)
                                                        ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2300:57: error: 'pGlProvokingVertexEXT' was not declared in this scope
      else if (FeatureAvailable[IRR_EXT_provoking_vertex] && pGlProvokingVertexEXT)
                                                             ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlBlendFuncIndexed(GLuint, GLenum, GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2352:54: error: 'pGlBlendFunciARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_draw_buffers_blend] && pGlBlendFunciARB)
                                                          ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2354:59: error: 'pGlBlendFuncIndexedAMD' was not declared in this scope
      else if (FeatureAvailable[IRR_AMD_draw_buffers_blend] && pGlBlendFuncIndexedAMD)
                                                               ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlBlendEquationIndexed(GLuint, GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2368:54: error: 'pGlBlendEquationiARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_draw_buffers_blend] && pGlBlendEquationiARB)
                                                          ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2370:59: error: 'pGlBlendEquationIndexedAMD' was not declared in this scope
      else if (FeatureAvailable[IRR_AMD_draw_buffers_blend] && pGlBlendEquationIndexedAMD)
                                                               ^
    lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:1910: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o' failed
    make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o] Error 1
    CMakeFiles/Makefile2:372: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed
    make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    [ 34%] Building CXX object lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o
    In file included from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.h:25:0,
                     from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:8:
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:65:33: error: expected ')' before 'PFNGLBLENDEQUATIONPROC'
             typedef void (APIENTRYP PFNGLBLENDEQUATIONPROC) (GLenum mode);
                                     ^
    In file included from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.h:25:0,
                     from /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLDriver.cpp:8:
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1214:3: error: 'PFNGLPROVOKINGVERTEXPROC' does not name a type
       PFNGLPROVOKINGVERTEXPROC pGlProvokingVertexARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1215:3: error: 'PFNGLPROVOKINGVERTEXEXTPROC' does not name a type
       PFNGLPROVOKINGVERTEXEXTPROC pGlProvokingVertexEXT;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1219:3: error: 'PFNGLBLENDFUNCINDEXEDAMDPROC' does not name a type
       PFNGLBLENDFUNCINDEXEDAMDPROC pGlBlendFuncIndexedAMD;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1220:3: error: 'PFNGLBLENDFUNCIPROC' does not name a type
       PFNGLBLENDFUNCIPROC pGlBlendFunciARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1221:3: error: 'PFNGLBLENDEQUATIONINDEXEDAMDPROC' does not name a type
       PFNGLBLENDEQUATIONINDEXEDAMDPROC pGlBlendEquationIndexedAMD;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:1222:3: error: 'PFNGLBLENDEQUATIONIPROC' does not name a type
       PFNGLBLENDEQUATIONIPROC pGlBlendEquationiARB;
       ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlProvokingVertex(GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2298:52: error: 'pGlProvokingVertexARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_provoking_vertex] && pGlProvokingVertexARB)
                                                        ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2300:57: error: 'pGlProvokingVertexEXT' was not declared in this scope
      else if (FeatureAvailable[IRR_EXT_provoking_vertex] && pGlProvokingVertexEXT)
                                                             ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlBlendFuncIndexed(GLuint, GLenum, GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2352:54: error: 'pGlBlendFunciARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_draw_buffers_blend] && pGlBlendFunciARB)
                                                          ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2354:59: error: 'pGlBlendFuncIndexedAMD' was not declared in this scope
      else if (FeatureAvailable[IRR_AMD_draw_buffers_blend] && pGlBlendFuncIndexedAMD)
                                                               ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h: In member function 'void irr::video::COpenGLExtensionHandler::extGlBlendEquationIndexed(GLuint, GLenum)':
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2368:54: error: 'pGlBlendEquationiARB' was not declared in this scope
      if (FeatureAvailable[IRR_ARB_draw_buffers_blend] && pGlBlendEquationiARB)
                                                          ^
    /home/v/compile/stk-code/lib/irrlicht/source/Irrlicht/COpenGLExtensionHandler.h:2370:59: error: 'pGlBlendEquationIndexedAMD' was not declared in this scope
      else if (FeatureAvailable[IRR_AMD_draw_buffers_blend] && pGlBlendEquationIndexedAMD)
                                                               ^
    lib/irrlicht/CMakeFiles/stkirrlicht.dir/build.make:1910: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o' failed
    make[2]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/source/Irrlicht/COpenGLDriver.cpp.o] Error 1
    CMakeFiles/Makefile2:372: recipe for target 'lib/irrlicht/CMakeFiles/stkirrlicht.dir/all' failed
    make[1]: *** [lib/irrlicht/CMakeFiles/stkirrlicht.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by SuicSoft** [comment]
What version of GCC are you using

**Comment by v1993** [comment]
`gcc --version` said: `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

**Comment by nado** [comment]
Post the complete build.log please.

**Comment by v1993** [comment]
Where can I find build.log? Or I just need to post output of `make --debug`?

**Comment by nado** [comment]
The output of `make -j1` should be enough, if there’s cmake issue, its in `build/CMakeFiles/CMakeError.log`

**Comment by deveee** [comment]
I assume that you have ```mesa-common-dev``` installed? 

If so, does the ```/usr/include/GL/glext.h``` file contain PFNGLPROVOKINGVERTEXPROC, PFNGLPROVOKINGVERTEXEXTPROC and other definitions?

Also could you find the ```OPENGL_INCLUDE_DIR``` in CmakeCache.txt in your build directory? It should be: ```OPENGL_INCLUDE_DIR:PATH=/usr/include```. Maybe cmake found local copy of glex.h somewhere?

**Comment by v1993** [comment]
Ok, I found in CmakeCache.txt this: `OPENGL_INCLUDE_DIR:PATH=/usr/local/include`. After removing `/usr/local/include/GL` and CmakeCache.txt all is fine!
