### ISSUE TITLE
GNOME/Nautilus: Icon too big

### ISSUE THREAD

**Issue by rugk** [supertuxkart/stk-code#2718]
When you go to `/usr/share/applications` in Nautilus you'll see that the icon of SuperTuxKart is way too big in contrast to all other icons:
![stkiconsize](https://cloud.githubusercontent.com/assets/11966684/21587836/e788ca9e-d0e0-11e6-89dd-6f1bc3d7d942.png)

supertuxkart v0.9.1-3~bpo8+1 from Debian repos

**Comment by deveee** [comment]
Do you know what Gnome developers think about it?
Currently we install 32x32 and 128x128 icons. We can add more sizes, but tbh. I think that it should be handled globally in Gnome for all applications.

And actually Nautilus works in the same way when you open typical directory with images that have different sizes and aspect ratio. Some of them are bigger than other.

And unfortunately SuperTux still doesn't have hi-res icon :(

**Comment by rugk** [comment]
> Do you know what Gnome developers think about it?

No idea.

I only see that it works for most applications, but some games (such as STK) have too big icons. I never noticed this for image files (probably because they are all bigger than 256x256px).

**Comment by deveee** [comment]
I had a quick look and on freedesktop they say that we should provide at least 48x48 icon and optionally different sizes. So you can see if adding 48px icon helps. But IMO we can't decide how the icon looks in external applications and they will do what they want anyway. It's possible to generate all icons sizes automatically using imagemagick, but it's unnecessary another dependency for simple thing. So if 48px icon won't help, I think that we should close it as invalid.

**Comment by rugk** [comment]
Just wanted to reproduce this in a new Nautilus version and there it works as expected. You can still add the icon though, if you want… (or if it helps to stay compatible to the FreeDesktop specification)

**Comment by deveee** [comment]
That's fine that it works in newer Nautilus. I changed the small icon to 48px anyway, maybe it will be better in other places now.
