### ISSUE TITLE
Update copyright year in source files to 2017

### ISSUE THREAD

**Issue by SuicSoft** [supertuxkart/stk-code#2719]
Some of the source files still says copyright 2015 and should be updated to 2017

**Comment by nado** [comment]
Copyright headers should be updated when a change in the file occured, because the copyright covers a period during which what is copyrighted was done. So there’s no point in modifying the license header each year.

**Comment by auriamg** [comment]
We might update them eventually, but really this is completely unimportant.

**Comment by SuicSoft** [comment]
@auri
