### ISSUE TITLE
Start failed in Windows 7

### ISSUE THREAD

**Issue by Leslii** [supertuxkart/stk-code#2720]
I am using win7 x86, and installed STK 0.9.2 but when I run the game it seems it doesn't fully loads the game. There is a screenshot of my problem:
https://postimg.org/image/6eafygtwp/
Thanks in advance for help.

**Comment by Benau** [comment]
Could you try to set force_legacy_device parameter to "true" in config.xml file? It can be found in %appdata%\supertuxkart\0.8.2. It's just an idea, but maybe it creates OpenGL 3.1 context even if it doesn't really support it.

Also can you post your stdout.log there too?

**Comment by Leslii** [comment]
thank you it helped but still says I should install the latest video driver. I also can't change the screen resolution.
stdout.log
[info   ] [FileManager]: Data files will be fetched from: '../data/'
[info   ] [FileManager]: User directory is 'C:\Users\Farshad\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\Farshad\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\Farshad\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\Farshad\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../data/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../data/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../data/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../data/po/'.
[verbose  ] translation: GetLocaleInfo langname returns 'en'.
[verbose  ] translation: GetLocaleInfo tryname returns 'US'.
[verbose  ] translation: Env var LANGUAGE = 'en_US'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] IrrDriver: OpenGL version: 4.0
[info   ] IrrDriver: OpenGL vendor: ATI Technologies Inc.
[info   ] IrrDriver: OpenGL renderer: ATI Mobility Radeon HD 5650   
[info   ] IrrDriver: OpenGL version string: 4.0.9902 Compatibility Profile Context
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: ARB Geometry Shader 4 Present
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[info   ] Freetype Environment: Loading fonts...
[info   ] Freetype Environment: DPI for Normal Font is 18.
[info   ] Freetype Environment: DPI for Title Font is 24.
[info   ] Freetype Environment: DPI for Digit Font is 28.
[info   ] ScalableFont::loadTTF: Created 15 glyphs supporting 16 characters for high-res digits font Sigmar using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 93 glyphs supporting 150 characters for bold title font Ubuntu using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu using 1 glyph page(s).
[info   ] GrandPrixManager: Loading Grand Prix files from ../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\Farshad\AppData\Roaming/supertuxkart/0.8.2/grandprix/
[warn   ] OpenGL: Driver is too old!
[verbose  ] Thread: Start waiting 8869.448000
[verbose  ] Thread: Stop waiting 8871.449000
[verbose  ] Thread: Waited for more than 2.000000 seconds for thread to become deleteable
[info   ] Thread: News manager not stopping, exiting anyway.

**Comment by deveee** [comment]
I never had any radeon graphics card, but it looks that version 4.0.9902 is something around Catalyst 10.5, which is rather outdated.

In graphics restrictions we have:
<card contains="Radeon"         os="windows"  version="<14.300"  disable="DriverRecentEnough"/>
which suggests that we need at least catalyst 14.3 for proper working.

Could you also post the stdout.log file when force_legacy_device parameter is disabled? We could then see if it should be enabled by default for this graphics card. Or maybe it will at least give some hints.

We already have force_legacy_device enabled for versions <= 3.1.8787 because it doesn't really have GL 3.1 support even if it reports that it has. But GL4.0 drivers should work fine in basic configuration...

**Comment by qwertychouskie** [comment]
Well, if it says your driver is out dated, try updating it. :)
http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%207%20-%2032

**Comment by deveee** [comment]
One more thing that you can do is to add these lines to graphics_restrictions.xml in data directory:
```
  <card contains="ATI"            os="windows"                     disable="TextureCompressionS3TC"/>
  <card contains="ATI"            os="windows"                     disable="UniformBufferObject"/>
```
so that STK renderer will run in basic configuration. Other extensions should be unrelated.

Though indeed updating your drivers should be the simplest way to make it working.

**Comment by deveee** [comment]
@Leslii Could you post the stdout.log file when force_legacy_drivers is disabled? Maybe there are some shaders compilation errors.

**Comment by hiker** [comment]
Closing this for now because of the 0.9.3 release and no answer for a long time. Please reopen if this is still an issue with 0.9.3
