### ISSUE TITLE
Sound distance dependency

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2733]
Hi,

I notice that some sounds don't seem to be dependent on the distance which there are emitted. 
The behaviour is different in solo compared to multiplayer. To noticed it clearly i  first disable music and only keep sounds. 

 - First I launch a race without any bot and let it play for some minutes, in order to listen if there are not wanted sounds. I just hear the engine and sounds from the environment, everything is fine here

- In solo mode i launch the race with the maximum number of bots (19). I let the race play without moving my car and i listen. I hear 
     car shock 
     bubble explosion
at the same level when they happens near or at the opposite of the track.

- In multiplayer mode (2 players), maximum number of bots (18). I let the race play without moving the two cars and i listen. I hear
     Bomb Tic tac + explosion
     Bowling ball + strike
     Basket Ball
     Swatter
I i don't hear car engine.

Same problem in arena mode

**Comment by auriamg** [comment]
This is normal. In split screen multiplayer it is not possible to use positional sounds (positional with regards to what, anyway, there are 2 to 4 listeners. THat's not supported by OpenAL.)

**Comment by rogue-spectre** [comment]
the intensity of the sound could use just the closest car which can ear it ?

**Comment by auriamg** [comment]
This is not supported by OpenAL as far as I know, this would probably require writing a new audio system which would be a major effort

**Comment by qwertychouskie** [comment]
Maybe let OpenAL independently calculate the volume level and position for each sound and only play the louder of the two.  (Disclamer: I know pretty much nothing about OpenAL, so there is a large chance that this idea is pretty much impossible to implement. :)
