### ISSUE TITLE
multiplayer - Grand Prix - STK crashes when continue to second race

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2734]
Hi,

When playing a grand prix STK crashes at the end of the first race when using enter to go to the second race before the button continue is displayed.

[fatal  ] RaceResultGUI: Incorrect event 'top' when things are unlocked.

**Comment by Benau** [comment]
[fatal  ] RaceResultGUI: Incorrect event 'bottom' when things are unlocked.

It happens when odd0002 pressed enter on the results screen before the button showed up, before the button telling him a challenge was unlocked (after winning a gold medal)

auria wanna use the same fix in line 333?
