### ISSUE TITLE
pine tree LOD transition

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2740]
Hi,
      Here a small bug. The pine tree transition isn't smooth. The height of branches changes between two levels of details + the orientation of branches too, on one lod it's going up and the other going down. Here a gif

![pine](https://cloud.githubusercontent.com/assets/2879782/22029177/06cea2e8-dcda-11e6-8a5a-3493e564bfca.gif)

It can be seen in "Around the lighthouse"

**Comment by Benau** [comment]
#2623

**Comment by Arthur-D** [comment]
The rotation issue is still interesting I'd say. Maybe LOD objects should be automatically rotated to align with the original object?

**Comment by auriamg** [comment]
As far as I know there is no rotation issue, the two models of the pine tree just don't match very well

**Comment by stkAnon** [comment]
Yeah— sorry, this object isn't very well done. I was trying to recreate Unigine Valley (or as close to it as possible) in STK, so I wanted this model to have both extremely detailed LOD for close-ups and very low LOD for mass-populating forests. It looked pretty— almost realistic— in still screenshots of large gatherings, but doesn't work too well in more practical places.

I did end up making another LOD'd tree that has lower base polycounts, much smooth LOD transitions, and also just better, more natural design. Oh and its single model's organized as a patch of five variants on the same tree, for constructing large forests with fewer library nodes, but you can always split them up into separate objects. I'd suggest maybe replacing this object with that model.

The original download link from my original forum [post](http://forum.freegamedev.net/viewtopic.php?f=18&t=6005) still works. The current model should be called "pine", while I think the replacement I'm suggesting is named "spruce".
