### ISSUE TITLE
Objects not solid - Cornfield Crossing

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2741]
Hi,

Here some objects which are not solid in Cornfield Crossing

Starting pillars 
![cornfield_start-pillar_ns](https://cloud.githubusercontent.com/assets/2879782/22030722/d0ff2d2c-dcde-11e6-9910-fcf7d1c0a996.png)

Straw support in the Barn - Important since if one falls here the rescue is not done well. Or let the edge of the road begin at the entrance of the top of the barn.
![cornfield_barn_ns](https://cloud.githubusercontent.com/assets/2879782/22031425/deea9118-dce0-11e6-85f2-70ff45402e5d.png)

Palettes
![cornfiel_palette_ns](https://cloud.githubusercontent.com/assets/2879782/22030422/d75c4282-dcdd-11e6-95f4-e8125fa97084.png)
![cornfiel_palette2_ns](https://cloud.githubusercontent.com/assets/2879782/22030424/d762ebe6-dcdd-11e6-9248-21568b3db2a5.png)
![cornfiel_palette3_ns](https://cloud.githubusercontent.com/assets/2879782/22030423/d7602488-dcdd-11e6-9f04-3cd52abc44f9.png)

Nice track by the way ;)

**Comment by samuncle** [comment]
Hi,

Thanks for the bug report, I just corrected the pallet. However the straw support won't be physical since it seems it would be more of an annoyance, I tend to avoid to put such detail as physical.

I implemented walls inside the barn to avoid to go outside
