### ISSUE TITLE
Cornfield - Wrong thunderbird rescue Jump

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2742]
Hi,

If one falls from the top of the barn, there is no quick automatic rescue, and if rescue is activated the kart is released something like 2 meters before the entrance at the top of the barn, and fall into the water again.

![cornfield_jump](https://cloud.githubusercontent.com/assets/2879782/22031056/cd6c597c-dcdf-11e6-963f-f9958f80c218.png)

**Comment by auriamg** [comment]
Tweaks were made in SVN, but issues remain. See https://youtu.be/VZ6g0kWq8nU

**Comment by auriamg** [comment]
Reducing priority because it's a lot rarer now

**Comment by auriamg** [comment]
The weirdness at the end of the video is caused by this line in cannon_animation.cpp returning a weird value (I've seen a vector of length 42)

`m_delta = kart->getXYZ() - m_previous_orig_xyz;`
