### ISSUE TITLE
gamepad control override keyboard 

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2743]
Hi,

Here a bug between keyboard and gamepad.

1 - Start the game with a gamepad plugged
2 - Start a single player race using only keyboard and mouse
3 - Play a little with keyboard - ok
4 - During the race use the gamepad

5 - Now some keys of the keyboard do not work (right or left turn, speed)

**Comment by Alayan-stk-2** [comment]
An user on the IRC reported a similar issue:
[20:00] <svito> keyboard accelerate and brakes stop working after I use gamepad ones at least once

**Comment by Alayan-stk-2** [comment]
LLS couldn't reproduce the issue. Since the game had extensive changes for gamepad handling with the use of SDL2, I guess it's probably fixed.
