### ISSUE TITLE
Antediluvian Abyss - Polish track

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2745]
Hi,

I noticed that sometimes wheel were jumping on Antediluvian Abyss. I have just seen why. There is a "wrong closure" of the track just before the arrival. Here two screenshots

![abyss_mesh2](https://cloud.githubusercontent.com/assets/2879782/22079598/c03547cc-ddbc-11e6-9cf7-cc010b78b45d.png)
![abyss_mesh](https://cloud.githubusercontent.com/assets/2879782/22079599/c07050ba-ddbc-11e6-9052-413c8e959c9b.png)

**Comment by Benau** [comment]
fixed with .spm

**Comment by Benau** [comment]
Also I would recommend update spm exporter, there is a bug having problem spliting more than 16bit vertices before (now fixed)

Otherwise underlight texture in abyss would be missing
