### ISSUE TITLE
The kart selection screen cuts some characters while playing the win animation

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2747]
Most noticeable the animation of Xue and elephant go out of the rendered rectangle.

![Screenshot](https://i.imgur.com/oHpNMrd.png)

**Comment by qwertychouskie** [comment]
The solution is to make separate animations for the selection screen for all of the characters, this may take a while though...

**Comment by Benau** [comment]
Not sure if deveee think this is too harsh for xue, or wrong warm up exercise before race (lol!)
![output](https://user-images.githubusercontent.com/3252341/31069233-14b98c4c-a74b-11e7-999f-b785b65944ce.gif)

Anyway u can close this ticket if you likes this (it's already committed)
