### ISSUE TITLE
The basketball flickers/moves too fast at some positions

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2748]
I noticed this at some places in Harvest/Cornfield Crossing. When activating a basketball before the ramp with the cannon, the ball changes its position often and fast which doesn’t look smooth at all.

**Comment by qwertychouskie** [comment]
Might be related to https://github.com/supertuxkart/stk-code/issues/2735

**Comment by hiker** [comment]
Should be fixed in 0.9.3
