### ISSUE TITLE
Refactoring Shaders

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2750]
After some discussion with Hiker yesterday who find the kart too dark we think it's a good idea to add a rimlight effect to the characters. However before that I think a refactoring of the whole shader system is needed.

While a rimlight shader is relatively straightforward and easy to do, the current situation makes it very difficult to include or remove a shader. A lot of cases must be considered:

1. Two versions of the same shader must be done
2. Inside the sader, two more cases must be considered (if it uses bindless textures or not)
3. Add a shader for RMS pass and shadow pas (also with bindless texture).

To quote a comment in geometry_passes.cpp

> Adding a solid material:
> 
> You need to consider twice before adding a new material : in the worst case a material requires 8 shaders :
> one for each solid pass, one for shadow pass, one for RSM pass, and you need to double that for instanced version.
> 
> You need to declare a new enum in MeshMaterial and to write the corresponding dispatch code in getMeshMaterialFromType
> and to create a new List* structure for non instanced.
> 
> Then you need to write the code in draw_calls.cpp that will add any mesh with the new material to their corresponding
> lists : in handleSTKCommon for the standard version and in the body of prepareDrawCalls for instanced version.

Adding or removing a shader should be a straightforward operation involving one or two steps instead of this complex procedure.

While the majority of objects in the game are fine with a generic shader, we have cases where a dedicated shader would be better:

1. Better performances: Currently the solid pass and alpha tested pass uses the same shader with a branching inside which kills the GPU performances. It's better to have a few dedicated shader instead of a big one with several options
2. By combining various small textures we can create complex terrain like a shader which put automatically snow in every horizontal surface of a rock no matter what's the rotation. This can increase the variety with almost no cost. Currently if we want to do that we need either to add a bunch of shader or to have a bunch of rocks with different texture and it takes space in the VRAM
3. Easier for devs and artists to tweak the engine, like in the case of the rimlight around the karts.
4. The code duplication in all those shader makes the whole thing difficult to understand prone to error (example here of code duplication https://paste.fedoraproject.org/532371/50190181/raw/)
5. In the vast majority of cases artists only need to manipulate what happen between the texture read and the output.

Roadmap for the refactoring

- Start by removing the instanced_* shader, and use ifdef statement instead. It will reduce the number of code duplication
- Separate shader in 3 category
- - Internal shader, used by the engine internally like SSAO. Those shader aren't often changed and mostly hardcoded.
- - Material shader, used as a module into the sytem and easily configurable, interchangeable
- - Utils (already existing), to put various useful functions
- 
- Identify what are the part in common and what are the difference between the redundant parts to create a "custom" shader parser, that would be able to automatically generate from one file all versions. In theory it could be XML based but that would be probably too verbose
- Re implement hardcoded materials into custom shader.

New structure of a custom SuperTuxKart shader for a material:

- Flags (Define some basics
-- Unlit (if it's ignored by lights)
-- Don't cast shadow (Ignored by the shadows, useful for performances
-- Solid  / Alpha Tested / Alpha Additive / Alpha blending

- Built variables available to the shader (only sent if the shader needs them)
-- Time: (useful to create animations like moving textures)
-- Kart position:
-- Wind direction
-- We can add more if needed

- Output values for a custom vertex shader
-- TODO: Add a list

- Output values for a custom fragment shader
-- Base color
-- Specular map
-- Roughness map
-- Emit map
-- Normal map
-- Ambiant occlusion map
-- Discard (if the flag alpha testing is enabled)
-- Alpha (If the flag additive or alpha blending are enabled)

- Output for a custom geometry shader
-- TODO: Add a list

**Comment by samuncle** [comment]
I made a quick example to show how the future solid shader might looks like. This shader would be only the basic shader with no random color, only diffuse, normal map, gloss map and affected by the light and casting shadow

- In the material.xml only this would be sufficient. Flags like alpha blend etc aren't relevant here
`<material name="concrete.png" shader="solid.mat" normalmap="concrete_nm.png" glossmap="concrete_gloss.png"/>`

shader/custom_materials/solid.mat would contain something like

```
// This shader is used by solid material textures and objects.

// Configuration flags
FLAGS = {
UNLITt="false",
CAST_SHADOWS="true",
PASS="solid"
}

// The vertex shader part.
// Since we don't have to manipulate the vertex we can use the general vertex shader
VERTEX_SHADER = {
#include GENERIC_VERTEX
}

// The fragment shader part
FRAG_SHADER = {

// Input (the name is the same name like defined in the material.xml)
uniform sampler2D diffusemap;
uniform sampler2D normalmap;
uniform sampler2D glossmap;
in vec2 uv_0;

// Read the various textures
vec3 color = texture(diffusemap, uv_0)
vec3 nor = texture(normalmap, uv_0)

float spec = texture(glossmap, uv_0).r
float gloss = texture(glossmap, uv_0).g
float emit = texture(glossmap, uv_0).b

// This is the output for a shader with no alpha blending,additive or testing
fragment_output(
color, // color output
spec, // specular map
gloss, // roughness
nor, // normal map
1, // Ambient Occlusion map (not used in this case
}

// The geometry shader part (same as the vertex shader, since we don't manipulate geometry)
GEO_SHADER = {
#include GENERIC_GEO
}

```

**Comment by datahead8888** [comment]
I don't know the STK code as of yet, but these are my current thoughts.  My thought would be to separate the GLSL code from the configuration.  Thus all snippets of shader code would be defined in other files, and solid.mat would reference the shader pieces it wants to use (either through an id system, shader file names, or GLSL function names).  The .mat file would also be free to specify any additional configurations such as colors, etc.  You could have a ShaderBuilder class that then builds the shaders at run time (or build time if you want).

Combining code with configurations sounds a bit risky to me.  It can be difficult to say with certainty that a snippet of GLSL code will never be reused elsewhere in the project.  Separating code from configuration also promotes modularization.

The branching and code duplication concerns you cited in the current STK shader implementation are both valid concerns.  I wouldn't view three uniform variables of concern for code duplication, but I'm sure there are much larger instances of duplication that can result.

As I mentioned to samuncle in a chat discussion, it would be worth asking people on OpenGL forums what they usually do in these cases, explaining the known options to them.  Two sites I would suggest posting at are:
* The Kronos forums - OpenGL Shading Language - https://www.opengl.org/discussion_boards/forumdisplay.php/15-OpenGL-Shading-Language?s=62933ae6afbf73a64f7c9772dd8bbd23
* The Gamedev.net OpenGL/Vulkan forum - https://www.gamedev.net/forum/25-opengl-and-vulkan/
--If you need me to, I could try to make the posts, but I probably will not describe the STK code as well as you.

> and you need to double that for instanced version

Why would the number of shader implementations double in this case?  I didn't follow the discussion here.

**Comment by Benau** [comment]
I think sam way will require writing a powerful interpreter, so i will use this instead:
```xml
<spshader>
    <!--
        name: The name of the shader.

        fallback-shader: The name of the shader to be used when advanced
                         lighting is off, make sure that shader is loaded first

        transparent: If Y, than this shader will be used in transparent pass.

        drawing-priority: The larger this number, the later the meshes using
                          this shader will be drawn.

        use-alpha-channel: if Y, this shader is going to access alpha channel
                           from mesh texture layers. It's used to hint STK not
                           to encode colorization mask for this material using
                           this shader which it will overwrite the alpha
                           channel.

        use_tangents: If Y, than meshes using this shader will have tangents
                      and bitangents defined and you can access them in shader.

        srgb: sample mesh texture layers in srgb or not (in 6 Ys / Ns), when
              advanced lighting is off, srgb will always be false.

        You can only specific 1st and shadow pass of shader in .xml
    -->
    <shader-info name="solid" fallback-shader="" transparent="N"
                 drawing-priority="0" use-alpha-channel="N" use_tangents="N"
                 srgb="Y Y N N N N"/>
    <!--
        use-function: Specify function to be run before drawing meshes with
                      this shader:

            alphaBlendUse will be suitable for drawing alpha blend material

            additiveUse will be suitable for drawing additive material

            ghostUse will be suitable for drawing object with translucent
            effect with face culling and depth buffer writing on

        unuse-function: Specify function to be run after drawing meshes with this
                        shader (none at the moment).

        vertex-shader: Specify the vertex shader, it will search in the
                       directory of the location of this xml file first, if not
                       found it will search in the official shader directory.
                       Notice: if you use #stk_include in your shader file, STK
                       will only search the include header in official shader
                       directory.

        fragment-shader: Specify the fragment shader, searching rule is the
                         same as above.

        skinned-mesh-shader: Specify the skinned mesh version of the vertex
                             shader, searching rule is the same as above. You
                             have to make sure the uniforms and the textures
                             used in both skinned mesh / non-skinned mesh
                             shader are the same.
    -->
    <first-pass use-function="" unuse-function="" vertex-shader="sp_pass.vert"
        fragment-shader="sp_solid.frag" skinned-mesh-shader="sp_skinning.vert">
        <prefilled-textures>
            <!--
                prefilled-textures: Define the prefilled textures used in
                                    shaders, they will be the same for all
                                    meshes drawn using this shader.

                    name: name of the texture, it will search using the order in
                          pushed texture searching directory.

                    srgb: sample in srgb or not

                    sampler: nearest, nearest_clamped, bilinear,
                             bilinear_clamped, trilinear,trilinear clamped
                             and semi_trilinear are possible right now.
            -->
        </prefilled-textures>
    </first-pass>
    <shadow-pass use-function="" unuse-function="" vertex-shader="sp_shadow.vert"
        fragment-shader="white.frag" skinned-mesh-shader="sp_skinning_shadow.vert">
        <uniforms>
            <!--
                uniforms: Define the uniforms in shader with the name of the type
                          (int, float, vec3).
            -->
            <uniform name="layer" type="int"/>
        </uniforms>
    </shadow-pass>
    <!--
        uniform-assigners: List of uniform assigners functions to be auto-run
                           when "use" the shader which set the above uniforms,
                           currently there are:

            shadowCascadeUniformAssigner will set the current shadow
            cascade being drawn.

            windDirectionUniformAssigner will set the wind direction.

            zeroAlphaUniformAssigner should be used in transparent shader.

            fogUniformAssigner will set 0 / 1 if fog is enabled in track.

            ghostAlphaAssigner will set ghost (kart) color based on sun color
            of track.

            You have to specify the uniform name in shader together with the
            bundled uniform-assigners.
    -->
    <uniform-assigners>
        <uniform-assigner name="layer" function="shadowCascadeUniformAssigner"/>
    </uniform-assigners>
</spshader>
```
Check https://github.com/supertuxkart/stk-code/compare/non_hardcoded_shader...Benau:non_hardcoded_shader, it is not compilable or finished and just a pre-view.
 
Basically it will move the current hardcoded shader initialization in sp_base.cpp to xml and let the manager create the shader itself runtime (should be doable since no template is used). I will only expose the use of vertex and fragment shader for xml (because that's all card supports).

Not too complex?

**Comment by Benau** [comment]
actually deve i think the kart selection in advanced pipeline off issue is probably tonemap shader mis-used (not neccessary when advanced pipeline off) in renderToTexture, in https://github.com/supertuxkart/stk-code/commit/45957af6f828d57e3dca5535df9fd4c6dedb9bff, I directly use the FBO_COLORS if advanced pipeline off, but it is as dark as in track now, do you want to remove all * 0.73 in *.frag?
so everything (including kart selection) is normal

**Comment by Benau** [comment]
Yes, it use threaded texture loader, but it is a complete re-design make use of std::function and std::thread

**Comment by Benau** [comment]
![screenshot](https://user-images.githubusercontent.com/3252341/35211251-ac9188ba-ff90-11e7-9ced-ba1692c0ea30.jpg)
Basically if you use my way than when advanced pipeline off, the texture is wysiwyg, before it is darker (don't care?)

**Comment by deveee** [comment]
ok

**Comment by Benau** [comment]
Now custom xml shader is merged and the first demonstration is in stk-assets/sps_splatting.xml
it has the minimal settings (no shadow, because i don't think there is any need for the terrain to cast shadow, but it can be added), you can refer sps_0_solid.xml in data/shaders for detail instructions.

And auria don't mind this?
![screenshot](https://user-images.githubusercontent.com/3252341/35234660-e1bdeeb0-ffdc-11e7-862d-f2abf138edc9.jpg)
(because the blender material system only takes layer 1 texture into account, in order to specifiy the uv2, i have to force duplicate the image and make 1 more entry for them, for something like this in materials.xml:
```xml
  <material name="dirt.jpg" shader="splatting" uv-two-tex="splat2.png" tex-layer-2="dirt.jpg" tex-layer-3="grass2.jpg" tex-layer-4="snow.png" tex-layer-5="rock_grey.jpg"/>
  <material name="dirt.jpg" shader="splatting" uv-two-tex="splat.png" tex-layer-2="dirt.jpg" tex-layer-3="grass2.jpg" tex-layer-4="rock_brown.jpg" tex-layer-5="sand2.jpg"/>
```

**Comment by deveee** [comment]
I tested it and now disabled advanced lighting has exactly the same colors as gles legacy pipeline. And indeed it looks much more correct.

Do you still want me to test texture compression for intel on windows? Actually I have current drivers with GL 4.0 and IIRC (not 100% sure) texture compression was working for me for STK <= 0.9.3. I can try with older drivers if you want.

**Comment by Benau** [comment]
yes sure
