### ISSUE TITLE
Kart clean up

### ISSUE THREAD

**Issue by MatthewsSam** [supertuxkart/stk-code#2752]
Here is a list of stuff to do for all karts. Headlights can of course have all forms and shapes. Only the light emitter is automatically added to all karts

Adiumy (done):
Beastie (done):
Emule (done):
Pidgin (done):
Gimp (done):
Amanda (done):
Hexley (done):
Sara the wizard (done):
Xue (done) however we should animate the light see #2755 
Suzanne: (done):
Sara the racer:(done)

Gnu:
Special case smoke exhaust Should be disabled and the kart don't have headlights

Konqui:
- [x] headlight 3D model (front)
- [x] headlight 3D model (back)
- [x] blue lens flare (front)
- [x] red lens flare (back)
- [x] Exhaust

Gaveroche:
- [ ] headlight 3D model (front)
- [ ] headlight 3D model (back)
- [ ] blue lens flare (front)
- [ ] red lens flare (back)
- [x] Exhaust

Nolok:
- [x] headlight 3D model (front)
- [x] headlight 3D model (back)
- [x] blue lens flare (front)
- [x] red lens flare (back)
- [x] Exhaust
Texture too dark and not using the new engine materials

Puffy:
- [ ] headlight 3D model (front)
- [ ] headlight 3D model (back)
- [ ] blue lens flare (front)
- [ ] red lens flare (back)
- [ ] Exhaust
Texture too dark and not using the new engine materials

Tux:
- [x] headlight 3D model (front)
- [x] headlight 3D model (back)
- [x] blue lens flare (front)
- [x] red lens flare (back)
- [x] Exhaust

**Comment by Benau** [comment]
elePHPant will be replaced by kiki, which will have headlight

**Comment by TomaszGasior** [comment]
Is there any ability to restore PHP's elephant? :)

**Comment by Alayan-stk-2** [comment]
@samuncle Is this still relevant ?
