### ISSUE TITLE
Headlight object isn't animated

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2755]
I'm putting headlight in all karts, however the separated object isn't animated which causes problem especially for Xue's red light at the back

**Comment by Benau** [comment]
Forget what I have said about using alt-d to duplicate headlight model, it will not work if you mirror-x the object, because irrlicht doesn't support negative scaling from matrix

**Comment by Benau** [comment]
Actually now you can use alt-d if your headlights doesn't need to be mirrored-x, (for example if they have no backlights).

See gnu arabic_lantern.spm for example
