### ISSUE TITLE
STK on Windows 7 does not use both GPUs

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2756]
STK does not use both of the GPUs on my GTX 295.  Windows 7, latest driver for the card from Nvidia, STK 0.9.2 and Git.

**Comment by auriamg** [comment]
STK does not support using more than one GPU. supporting that would be a major effort for a very small percentage of our player base and is not something we plan.

**Comment by SuicSoft** [comment]
@qwertychouskie you can enable SLI for any game but STK might not be optimized for it.
