### ISSUE TITLE
Horrible performance on Xubuntu 16.(04?) with GTX 295

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2757]
STK git at max settings has about a quarter to half the FPS as on Windows 7.  Latest Nvidia driver for the card from the repos.

**Comment by MTres19** [comment]
So... blame nVidia. STK doesn't have different code for Linux. Also Ubuntu does not do a good job keeping the repos updated; try the nVidia website. Also check your DRi_PRIME environment variable if this is a hybrid/Optimus graphics system. Hybrid graphics don't work well on Linux. Anyway, the FAQ clearly states the hardware requirements, and your hardware does not seem to meet them.

**Comment by qwertychouskie** [comment]
The card itself is powerful enough, its performance is very similar to the recommended card: http://www.game-debate.com/gpu/index.php?gid=591&gid2=159&compare=Nvidia%20GeForce%20GTX%20660-vs-Nvidia%20GeForce%20GTX%20295
Also, I can get about 20-25 FPS on Windows 7 with the same settings using only 1 of the 2 GPUs (#2756).  Also, telling the Nvidia driver to render half of the frame with each GPU seems to slow things down, not speed them up (?!?).

**Comment by MTres19** [comment]
I still don't see how this is STK's fault, which I alluded to when I said
that STK has the same engine on Linux as on Windows. Did you try any other
demanding OpenGL tests? Also, a bug report is not very useful unless you
can provide more concrete information like profiler data or some theory as
to what code exactly causes this. It's also common that Linux drivers are
slower than Windows ones. In any case, this is not a Linux support forum.

**Comment by qwertychouskie** [comment]
Oops, didn't even think to try a cross-platform OpenGL test on Linux and Windows, sorry. :(  Well at least I have something to try now. :)  Closing, will re-open if tested to be STK specific.

**Comment by qwertychouskie** [comment]
Just thought I'd comment here for anyone else having this issue, it was fixed when I removed the Mesa Git PPA and upgraded Ubuntu to 16.10.

**Comment by SuicSoft** [comment]
@qwertychouskie You will probably get even more fps with Mesa Git PPA (padoka). The Ubuntu 16.10 updated the kernel which is why the problem was fixed.

**Comment by qwertychouskie** [comment]
I'm using the Nvidia binary drivers, so using a newer Mesa version should not make a difference.

**Comment by SuicSoft** [comment]
@qwertychouskie ok i thought you were using the foss drivers.
