### ISSUE TITLE
Cornfield - stunning stars drawed "behind" water

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2758]
Hi,

I noticed a little bug on Cornfield when all visual effects are activated. (I did not test all combinations just when there is no visual effects there is no stars).  To reproduce it  take a banana in order to have a bomb attached to your back and then go in front of a water area and wait to explode. You can see that the stars are drawed "behind" water. I could not reproduced it with the minigolf, so i assume the problem comes from the track. Here a screenshoot.

![cornfield_stars](https://cloud.githubusercontent.com/assets/2879782/22373641/e4d3456a-e4a2-11e6-8fa4-3ac645c7788e.jpg)

**Comment by samuncle** [comment]
that's almost impossible to correct without proper z sorting + all sort of complicated stuff, to avois distortion with the water

One option would be to try with alpha testing instead of alpha blending, but then the stars might look jagged.

I don't think we can fix this one

**Comment by Benau** [comment]
See irc log today for discussion

**Comment by Benau** [comment]
Actually with CPUParticleManager it is fixed
