### ISSUE TITLE
Cannot minimize when running in fullscreen

### ISSUE THREAD

**Issue by cromat** [supertuxkart/stk-code#2760]
Hi,

I have noticed that there is no way to minimize game when it-s played in fullscreen mode.

I've tried:
Ctrl+Super+Arrow Down 
Alt+Tab
Ctrl+Super+D
Ctrl+Alt+Numpad 0

I'm using Ubuntu 14.04 LTS.

**Comment by deveee** [comment]
Try current stable version, we are using WM fullscreen since 0.9, so that keyboard shortucts should work.
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/supertuxkart-0.9.2-linux.tar.xz/download

**Comment by auriamg** [comment]
Closing this ticket since it has been inactive for a while. Please reopen if the issue persists
