### ISSUE TITLE
Sound feedback / drift / offroad

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2761]
Hi 

i  noticed some little bugs related to motor sound feedback.

1 - When one gets a speed bonus from drifting, one can see his speed increase in the speed indicator, but there is no sound rewarding about the bonus (zipper sound could be used). In comparison when you take a zipper one is rewarded by hearing the motor overrunning + have a sound off the zipper.

2 - When going offroad with a smooth transition between the road and the "field", one can see the speed decrease  but the sound of the motor is kept at "maximum". When returning to the road one can hear the acceleration.

**Comment by auriamg** [comment]
We would need someone to desing and contribute sounds for this and we could add it.

As for your second point I'm not sure what you mean, you're saying that the sound doesn't change when leaving the track but changes back when going back on road, how is that possible? :) If you hear it change back when going back to the road that means it did change when leaving the road. Maybe you wanted something more noticeable

**Comment by rogue-spectre** [comment]
I took a video capture… better to explain 

https://www.youtube.com/watch?v=OrMH2ugJovQ&feature=youtu.be (currently processing)

- First you can hear the problem 2.
- Then you can hear an other problem the speed at maximum speed offroad is the same as the maximum speed on road. I first get to maximum speed on road, then i tried to keep this speed on road to hear that is not the same sound and then go to maximum speed on road.
