### ISSUE TITLE
Drift doesn't stop when flying

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2762]
Hi again ;)
  
I noticed that when you are drifting and for some reason you get to fly (for instance falling off a bridge), the drift continues in the air… it's a bet weird, and sometimes you can continue the drift after landing. I think the drift should be stop when the kart stop touching the road.

**Comment by Arthur-D** [comment]
This has been left in deliberately as a feature. While it's not realistic it fits with the rest of the game and what other arcade-style racing games often do.

**Comment by auriamg** [comment]
Indeed, this is unrealistic but STK is not a simulator and skidding doesn't give you a boost in real life anyway, so it's all pretty gamey. If you're good enough to use this feature, good on you!

**Comment by rogue-spectre** [comment]
I agree with you. Getting a boost because you drift is not realistic but it's a game feature rewarding the risk you take to drift. The thing is that the "drift effect" (the light under wheels) is due to the friction between wheels and the road, so it should not be visible when the kart flies ? 

Maybe if the kart take off when drifting, you should get the boost at this moment ?
