### ISSUE TITLE
Shaders linking error caused by wrong joint_matrices uniform type

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2763]
I just tested STK with older mesa version (10.3, intel drivers) and I received an error:
```
[error  ] Shader: Error when linking these shaders :
[error  ] shader: object_pass.vert
[error  ] shader: transparentfog.frag
[error  ] Shader: error: uniform `joint_matrices' declared as type `mat4[256]' and type `mat4[1024]'
```

It looks that some shaders are compiled with MAX_BONES=256 and some shaders with MAX_BONES=1024.

In console it says:
```[info   ] SharedGPUObjects: Hardware skinning supported, max joints support: 256```

It works fine with current mesa, but it reports max joints support: 1024, so in this case the types are same.

It's with OpenGL 3.x renderer, advanced lighting disabled.

**Comment by Benau** [comment]
what happen if you move SharedGPUObjects::init() to ShaderBasedRenderer::preloadShaderFiles() at the beginning

**Comment by deveee** [comment]
Moving SharedGPUObjects::init() to preloadSaderFiles() fixed the issue.
