### ISSUE TITLE
Segfault - Starting a race after lowering settings

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2766]
Hi, 
I noticed a segfault. To get it 

1 - set the settings to maximum (fullscreen or not)
2 -launch a race and quit it (or complete it)
3 - lower settings + Apply new resolution
4 - start a new race
5 - segfault

gdb gives 

      Program received signal SIGSEGV, Segmentation fault.
      0x0000000000a85f69 in BloomBlendShader::render (this=0x15fa2c00,  render_target_bloom_128=478, render_target_bloom_256=475, render_target_bloom_512=472)
            at stk-code/src/graphics/post_processing.cpp:384
            384							lensDustTex->getOpenGLTextureName());

backtrace

      #0  0x0000000000a85f69 in BloomBlendShader::render (this=0x16d4f300, render_target_bloom_128=484, render_target_bloom_256=481, render_target_bloom_512=478)
    at stk-code/src/graphics/post_processing.cpp:384
      #1  0x0000000000a82872 in PostProcessing::render (this=0x254c5c0, camnode=0x13f20a60, isRace=true, rtts=0x13f4da40)
    at stk-code/src/graphics/post_processing.cpp:1526
      #2  0x0000000000a5a9ae in ShaderBasedRenderer::renderPostProcessing (this=0xff2d340, camera=0x13f20980)
    at stk-code/src/graphics/shader_based_renderer.cpp:571
      #3  0x0000000000a5ba52 in ShaderBasedRenderer::render (this=0xff2d340, dt=0,0329999998)
    at stk-code/src/graphics/shader_based_renderer.cpp:835
      #4  0x0000000000b7ab9f in IrrDriver::update (this=0x1abf9d0, dt=0,0329999998) at stk-code/src/graphics/irr_driver.cpp:1845
      #5  0x0000000000c82c65 in MainLoop::run (this=0x30ec9e0) at stk-code/src/main_loop.cpp:239
      #6  0x0000000000cd5bf3 in main (argc=1, argv=0x7fffffffde68) at stk-code/src/main.cpp:1771

**Comment by Alayan-stk-2** [comment]
Confirmed. At first I didn't get it (changed the resolution setting before applying the changes), but trying again it segfaulted.
