### ISSUE TITLE
Remember number of AI karts per mode

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2770]
Right now, the value is shared across all mode. So say you prefer 11 AI karts in normal races and you do a 3-strike battle/football game ; your preferred value will have been forgotten for normal races.

Normal/time-trial/follow the leader may share a common value (they are quite similar modes) ; but it would be a small improvement to have different memorized value for 3-strike/football.

**Comment by cpdef** [comment]
i wanna go maybe to do this, but if not i found out that the value is also forgotten if u start an ghost replay (set to 1), so this should be also changed.

**Comment by Fantasmos** [comment]
Should we consider closing this issue, or leaving it until Grand Prix does it PER setup? I think it's fine to close up
