### ISSUE TITLE
Preferred GP AI winner

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2777]
Following a discussion on IRC with @hiker.

hiker: Alayan: you mean MK makes sure that the same two karts are always the first 2 ai karts?
hiker: Interesting ... I wonder how they do that :)
hiker: That would indeed be a nice tweak to make GPs more challenging

There are several possible implementations. The goal should be to do it only by affecting AI behavior, without cheats.

Ideas : 
- Don't select only one preferred AI kart, but two or three, so that the challenge is more consistent against random events.
- Make the other AI attack less the preferred karts
- Make the other AI dumber so that the preferred AI tend to be better ranked. To not make the SuperTux difficulty races easier than currently, new configurable AI improvements would be useful. In easier difficulty modes, the preferred AI could borrow some improvements of the next-tier of difficulty.

Another possibility would be to select more often than not the preferred AI among the better performing karts, but it's not wanted that there are better karts than other in the fist place.

Possible issues : 
- Making some AI karts dumber only in GP would create an unwanted-gameplay difference between normal races and GP races.

**Comment by stkAnon** [comment]
I always figured individual AI strengths were already slightly randomized for every event...

For the possible issue, you could also apply these changes to normal races. The only difference in grand prixes would then be that the handicaps/bonuses are persistently given to the same karts for every race in the event.

**Comment by Arthur-D** [comment]
I don't see how these suggestions are any less of "cheating" than doing it more directly, and it seems more complicated than it might have to be.

I suggest to select one AI randomly at start of GP which gets double the nitro when picking up canisters - not particularly visible what's going on, but it should do better on average than the other AI. Another possibility is to always give it 3 weapons when picking up items, maybe in combination with the nitro cheat above. But just increasing nitro might be enough.

Of course this would need to work consistently when saving/loading GP as well.

**Comment by Alayan-stk-2** [comment]
There are now between 1 to 4 "preferred AI karts", depending on the total of karts in the race. At the beginning of each GP race, the N best ranked AI karts receive the boosted status, which improve their item usage, nitro usage, and don't make rubber-banding slow them down more when another AI kart overtake them.

So, technically, this PR is implemented.

However, the boosted AI status is not that strong currently for expert/supertux (it doesn't affect pathing/skidding), so I'll leave this issue open until this advantage is

Longer races would also probably help boosted AIs to be more reliably on top - and by longer, I mainly mean "3 minutes" instead of "<2 minutes".

**Comment by Alayan-stk-2** [comment]
I don't expect new AI improvements before the next release, but I was actually positively surprised by the tendency of opponents I wanted to do badly in a race to come back in front when doing a few GP in SuperTux.

Longer races, and more AI improvements are still needed to make this more significant, but those will come regardless, so no need to keep this open to justify them.
