### ISSUE TITLE
Scene manager improvement

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2778]
Our render engine uses currently a scene manage which stores all objects in lists. While it was acceptable a few years ago, now due to the complexity of tracks the system needs something better.

To reduce the amount of polygon rendered we can separate the scene in objects and then compute the visibility of each objects. However, the current system must iterate the whole list at each frame in order to determine the visibility of an object which slows down when the scene have a lot of objects.

I talked about this issue in the opengl chan on freenode and a dev kindly wrote a roadmap describing what would need to be changed.

An overview of different systems of managing the scene

Space partitioning, multiple possibilities (pick one!)
- Regular grid ~ Uniform and regular 2D/3D array of cells
  - Pro: Very easy to implement
  - Pro: Very quick to resolve insertion points (to add/move objects), by simply dividing coordinates by cellsize
  - Con: Poor drawing performance *if* geometry distribution is not uniform (clumped and sparse)
  - Con: Sector boundaries will never quite match natural occluders
- Quadtree/Octree ~ Separation of the scene by two splitting planes recursively
  - Pro: Rather easy to implement
  - Pro: Can provide good balacing of geometry per sector
  - Pro: Very easy resolution of insertion points (to add/move objects)
  - Con: Poor performance to resolve insertion points (to add/move objects)
  - Con: Sub-optimal but okay'ish drawing performance
  - Con: Poor scalability with huge scenes
- Graph ~ Interconnected 2D/3D graphs of arbitrarily-sized axis-aligned sectors
  - Pro: Excellent drawing performance
    - Can provide excellent balancing of geometry per sector
    - Boundaries between sectors can be placed right where large static occluders are
  - Pro: Excellent scalability with huge scenes
  - Pro: Excellent performance for spatial traversal
  - Con: Somewhat more complicated to implement (especially the construction of optimal graphs)
  - Con: Resolution of intertion points (to add/move objects) can be complex:
    - A regular grid for quick lookup, followed by spatial traversal (through sector neighbors)
    - A tree of some sort, binary/quadtree/octree (bad for cache, not ideal)

**Comment by samuncle** [comment]
Preprocessing, step #1 (any space partitioning technique)
  - Prepare the space partitioning by chopping the static scene into sectors
    (trivial for regular grid, a little complicated for a quadtree, more complex for a graph)
  - Assign all triangles of the static mesh to a single sector
    - If a triangle overlaps many sectors, pick just one

Preprocessing, step #2 (any space partitioning technique)
  - For each sector, we want to build its "visibility list" to all other sectors
  - Shoot millions of rays (ray tracing) from uniform/random points within the sector
    - Each ray origin should be tested to ensure it's "inside" the visible region of the sector (not under the
      ground or in a mountain)
      - If a ray first hits a back-facing triangle, its origin was inside something (targeting a random nearby
        triangle is a valid strategy, we have no usable information if the ray doesn't hit anything)
  - Trace a ray for each valid origin:
    - Check what other sectors it traverses prior to intersection (add sector to visibility list if not present)
    - Resolve the (first) triangle intersected by the ray (add the triangle's sector to visibility list if not present)
  - To ensure the visibility of large dynamic objects, rays only passing "close" to a sector should still add it
    to the visibility list (rays passing within the maximum radius of dynamic objects)
    - Some sectors of the visibility list can be flagged "dynamic objects only", to reduce wasteful drawing


Drawing algorithm
  - Obtain the list of visible sectors from the camera's current sector (preprocessed above)
  - Test each visible sector against the frustum, discard if not visible
  - Sort the remaining list of sectors front-to-back (to reduce overdraw)
  - Group together all the geometry requiring the same shaders and/or textures (to reduce GL state change) 
  - Draw all the opaque geometry, the sectors and all the objects they contain
    - Ideally, figure out the proper balance of front-to-back sorting (reduce overdraw) and batching (reduce GL state change)
  - Draw all the transparent geometry, the sectors and all the objects they contain (sorted back-to-front)


Object management function/methods

AddObjectToScene()
  - Resolve in which sector the object resides
  - Add the object to the resolved sector
  - The object tracks/remembers its host sector

RemoveObjectFromScene()
  - Remove the object from its host sector

MoveObjectInScene()
  - Remove the object from its host sector
  - Resolve the new sector for the object
  - Add the object to the resolved sector
  - The object tracks/remembers its host sector

**Comment by Benau** [comment]
You can emulate drawing specific sector with ({g_sectors.begin() + x, g_sectors.begin() + y}); (or push_back custom Sector) in fix_2778 branch, only works in linux for now.

**Comment by Benau** [comment]
It is now in branch sp

**Comment by Benau** [comment]
Now I'm able to export animated mesh in a way usable in my engine now, so you only need to keep 1 exporter, also this new format features a "keyframe-only" mode exporting, useful for .blend without inverse kinetic or constraints.

@deveee assumed Xue is your favourite kart, which do you prefer (keyframed xue is 153k, all-framed is  518k, though compared to b3d 918k it is still smaller), a smaller mesh or better animated:

https://github.com/Benau/stk-code/blob/sp/allframed_xue.webm?raw=true
https://github.com/Benau/stk-code/blob/sp/keyframed_xue.webm?raw=true

Mainly left-right kart moving and the flying differ.

**Comment by deveee** [comment]
@Benau 153k looks much better than 518k :-P The allframed_xue is a bit more smooth, but I'm not sure if it will be noticeable during playing.

**Comment by Benau** [comment]
I've tried intel https://github.com/GameTechDev/MaskedOcclusionCulling with https://github.com/Benau/stk-code/commit/2bfa37ee6fd6c7d5df85f370d8dbbe459e8476cf, but it turns out all devices have the same performance despite drawing few 20k tris in cocoa temple, so sorry ![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) won't bloat stk-code for little to no gain for now

Anyone is welcomed to try that commit btw
