### ISSUE TITLE
AI item use improvements

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2780]
While working towards my new item ; I've taken a look on how AI manages item.

A few of them have some room for future improvements.

1)The switch.

Currently, the 1st won't ever use it. The code comment explain it's to wait for a better item, but that's weak. The other AI use it after waiting a bit of time, without any check.

Possible improvements : making the 1st use it, checking if there are item-box and no banana coming soon, or if the kart is about to pickup nitro - in these case wait, otherwise use.

2)The bowling ball.

There is a 5 seconds wait between two uses. The reasoning is that a bowling ball take some time to get to the opponent and AI should wait before selecting a target. The AI doesn't seem to take into account when karts are turning.

Possible improvements : reduce the wait time, 3 seconds is nearly always enough for this. When there are several opponents close, firing 2/3 balls in a row is also often interesting (at least as a player, tests should be conduced with the AI to tweak it properly). Making the AI better aim in turns would be good, but that would be pretty hard. Alternatively, restrict the conditions so the AI prefer to wait in these case unless it's more close than the normal. Another complex change would be to make the AI turn a bit to aim better.

3)The zipper

The code comment states that the zipper is used in place of nitro.

Improvements : AI should use zipper and a bit of nitro in big straight lines. Combining both is more powerful because nitro help unlocking the zipper's max_speed increase.

4)Nitro

Not using nitro when at >95% of max speed makes not much sense because nitro increases max speed.

That results in some nitro being stored, which isn't that bad, but it's actually more useful to use nitro when at full speed than when accelerating (it provides not much of a boost in acceleration, so loosing out on the max_speed means it's suboptimal).

AI also doesn't seem to make partial use of nitro. A small can offers 2 power boost, which help a skilled player to perform better than a non-skilled one. SuperTux AI should do it.

5)Swatter

A code comment indicate that it only checks the kart ahead and behind - so it may not activate the item in some (limited) cases.

6)Basket Ball

Not used if the potential user is shielded. The code comment is copy/pasted from the swatter one. However, swatter removes shield because it is a new attachment. That's not true of the basket ball, which should always be fired when not first.

7)The BubbleGum

Quite good, but should also be used when a banana is unavoidable ; and shouldn't drop them directly on the ground in the last lap, the shield is more valuable.

**Comment by Alayan-stk-2** [comment]
No offensive items are used when shielded, without checking on restricted mode. My first post noticed it for the basket ball, but this is also true for the cake, the plunger and the bowling ball.

The fix is quite simple, I've done it on my AI branch.

**Comment by Alayan-stk-2** [comment]
The #3143 pull request now greatly improve the switch utilization.

Further refinements are still possible in theory (like checking if using the switch will make a close enemy kart take a bad item) ; but they are not a priority given the complications for a small improvement.

**Comment by Alayan-stk-2** [comment]
The #3143 pull request should now make the nitro utilization very good, solving all the weaknesses noticed in this issue.

**Comment by qwertychouskie** [comment]
@Alayan-stk-2 can this be closed with the merge of the PR?

**Comment by Alayan-stk-2** [comment]
@qwertychouskie Not yet.

There is now #3183 which will improve things even more ; but there is still the zipper which the AI is not able to use effectively. Once the AI will be able to use the zipper in slight curves as a human can, I think it will be good enough to close this.

**Comment by Alayan-stk-2** [comment]
Another improvement to do : tell the AI that if a switch is currently active, trying to slowdown another kart with a bubblegum will instead grant it a free big nitro can.

**Comment by Alayan-stk-2** [comment]
Fixing some case where nitro is not used fast enough and the zipper issue will allow to close this one. I'd like to get it in for the next release.

**Comment by Alayan-stk-2** [comment]
Zipper improvements would require a deep rework of pathing AI so I'll consider this issue done with the latest nitro usage fixes.
