### ISSUE TITLE
Gran Paradisio invisible solide mesh

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2781]
See screenshoot.

![tuxbug2b](https://cloud.githubusercontent.com/assets/25536748/22741334/2b71ca0e-ee13-11e6-8229-15bcb6fb4d8b.png)

**Comment by MTres19** [comment]
Strange. I could not reproduce the problem. (Assets r16997)

**Comment by samuncle** [comment]
Idem I can't reproduce it :( even with the physic visualization I have no issues

**Comment by qwertychouskie** [comment]
Was able to reproduce: https://drive.google.com/open?id=0BzjStY528QA4eEFiNjVqZklwcHM

**Comment by MTres19** [comment]
Does this only cause problems at the edges of the track? If so, I think I've fixed it in r17260.

**Comment by qwertychouskie** [comment]
I think so.

**Comment by auriamg** [comment]
Fixed by MTres19, thanks
