### ISSUE TITLE
Music bug : another song played on top of the track song

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2782]
As the title say.

I don't know where the issue stems from, but I have the issue on the latest trunck ; while there wasn't a few days ago. So it must be a recent change which introduced this regression.

**Comment by deveee** [comment]
Is this duplicate of https://github.com/supertuxkart/stk-code/issues/2169 ?

**Comment by Alayan-stk-2** [comment]
Duplicate indeed. It's the same sound.

**Comment by deveee** [comment]
Ok, so closing as duplicate
