### ISSUE TITLE
The basket ball is too slow

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2783]
Currently, the basket ball is often too slow to catch up to the first kart, at least in a timely fashion.

The set speed is of 35. The max_speed of most karts is at 25. They may go faster with drifting and nitro, but let's assume the average speed is at 25. (NB : in Super Tux mode. I think the basket ball is not slower in easier difficulties while the karts are.)

This may seem like a noticeable difference, except it means that to catch up the basket ball need 3.5x the time separating the user of the ball and the first kart (1/(1-25/35)).

So when the user is 10 seconds behind the first, it takes 35 second for the basket ball to hit.

**When the user of the ball is 20 seconds behind, it takes 70 seconds for the basket ball to hit.**

(Side issue : when there are a lot of karts, those in bad positions shouldn't get a basket ball, it's useless for them and is ineffective even to slowdown the first)

If the first is able to drift correctly and get some nitro ; and he has no other accident ; he may well do half a race hunted by a basket ball without being hit. E.g. ; **on the lightouse track, I'm able to go faster than the basket ball.**

Increasing the basketball speed seems therefore a good idea - 40 would mean 2.7x the time at 25 and 4x at 30 ; 45 would mean 2.25x the time at 25 and 3x the time at 30. Both would still let some room to get to the finish lap in the end of a race or to get a bubblegum shield.

Another possible solution  would be to change the speed of the basketball according to its distance to the 1st kart - fast at the start but slower when it's closer. This would keep some fun trying to outrun the basket ball but making it harder.

**Comment by stkAnon** [comment]
I haven't played this game in a while, but I did quite like the speed of the basketball when I did— it was fast enough that it would hit you most of the time (coming from AI players), but slow enough that you could conceivably outrun it until it explodes on its own or collides into terrain. So you'd hear it launch or bouncing around the track, and then it'd be a frantic race to try and keep it from being able to catch up to you. IIRC I'd often get hit shortly after I crossed the finish line, presumably because of the AI taking over and slowing down.

Anyway you'd lose this dynamic if you made it much faster. It's not exactly like the blue shell in Mario, because it's still fallible and gives the leading player a chance to avoid it.

**Comment by hiker** [comment]
Not urgent.

**Comment by qwertychouskie** [comment]
This actually seems to be less of an issue since the basketball fixes in 0.9.3.  It still might make sense though to set the speed per gamemode (easier to outrun in Novice, deadly fast in SuperTux).

**Comment by Alayan-stk-2** [comment]
Actually, the biggest issue is that sometimes the basketball is launched by sometimes who is very far behind the first kart. I'm ok with the basketball being less deadly that the MK blue shell, but right now in 0.9.3 I've still been able to not be catched by one for a few dozens of seconds. That's very often enough to grab a bubblegum shield.

Part of this should be fixed by changing who gets this item.

What could be cool is to change the speed of the basketball depending on its distance to the first kart. When it's very far behind, it would catch pretty quickly, but when it gets closer, it slows down so there is some sport trying to outrun it long enough to catch a bubble gum. [EDIT : Damn, I already wrote the same thing at the end of my issue.]

When I get some free time to play with code, I'll try to code a changing speed patch.

Is there an easy way to measure time between the ball and the first kart ?

**Comment by hiker** [comment]
A speed increase should be fine (the ball is not actually a physics rigid body, it is moved by interpolation) - just check the looks of it, atm the ball already does not move smooth - maybe this could be improved as well? We need some feedback from @Benau to make sure it does not affect networking

**Comment by Benau** [comment]
[11:10] <Benau> i think alayan old patch for speedup basketball should work
[11:10] <Benau> as long as it's called every update()
[11:11] <Benau> and it has not use any m_* var
[11:11] <Benau> and as long as the m_* var is restore for every rewind it should work
