### ISSUE TITLE
Ghost time inconsistencies

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2786]
There are several ghost time inconsistencies.

First one ; when the player beat the ghost, the ghost's time in the results seems to be a projection of what it would have been (using the same method as for AI karts in normal race) ; while it should be the fixed time from the replay.

Second one ; the time I got in my records doesn't match the time in the replay selection. E.g. in a track ; I have 71.08s and 72.71s in the records ; while the ghost replays have saved 71.547s and 73.21s. I don't know for sure where the inconsistency comes from ; but it seems the ghost time has always around +0,5 seconds.

**Comment by Alayan-stk-2** [comment]
I did a ghost race and the issue still exist.

The commit supposed to fix it calls getFinishTime, but this function calculate the finish time by computing the average speed of the kart until that point and using that average and the distance remaining to produce a time. So if the player is faster than the ghost, a wrong time will be displayed.

What is needed is to get the exact value which is already stored in the ghost replay.

**Comment by Arthur-D** [comment]
Confirmed, there are definitely some timing issues. Whether that is due to just estimating the rest of the race or if it's the recent floats to int change I cannot say since I did not look at the code, but I did record a new ghost recording to test with to eliminate that being a direct source of difference.
