### ISSUE TITLE
Two (or more ?) levels of AI-item usage

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2789]
I started improving the AI item usage today. It struck me that it's the same AI used from intermediate to supertux.

The intermediate, and even expert, AI shouldn't master things perfectly (and the jump from novice where it is random would be harsh too).

I started by adding a new bool property to allow advanced mode for supertux (could be added to expert too if the lead devs so wish) ; however this may not be sufficient, especially depending on how we decide to tackle #2777.

So : 
- There should be at least two levels of AI-item usage.
- But it may not be sufficient. This is something I can not decide myself.

**Comment by Benau** [comment]
Sorry this is not bug but suggestion only
