### ISSUE TITLE
"About to pick an item" function

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#2790]
Several AI improvements depend of the ability to know if the kart is about to pick an item : using an item before collecting a new one ; using a bubbleshield before driving on a bubblegum ; not using a switch before collecting nitro/item box (though could benefit of even more knowledge) ; not using nitro/zipper if going into a banana/bubblegum ; and probably some others I can't think of right now.

This is code I don't really know how to do.

**Comment by Benau** [comment]
Sorry this is not bug but suggestion only
