### ISSUE TITLE
Unwanted kart shadow on dark tracks - missing image load store extension

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2792]
The shadow is visible always in the same place on dark tracks (when headlights are turned on).

It occurs when advanced lighting is enabled. It also seems to be related only to intel on windows. I couldn't reproduce it on nvidia graphics card.

Here is the screenshot
![hd4000bug](https://cloud.githubusercontent.com/assets/5108558/23076385/829611c6-f540-11e6-81ff-e49a6beee474.png)

On this screenshot it looks that this shadow is drawn on the wall, but it's always drawn in the middle of screen, no matter what is in front of you.

**Comment by qwertychouskie** [comment]
I had a similar/same issue in Intel HD 3000 on Linux, though it went away after i upgraded to a third-gen processor (HD 4000).
https://jacobspctuneup.tk/bug.mp4

**Comment by deveee** [comment]
Indeed it's reproducible also on linux with older mesa versions (I just checked the 10.3.2). The shadow is even bigger.

**Comment by deveee** [comment]
Actually it's not related to intel and can be reproduced on nvidia or with software rendering by just disabling the GL_ARB_shader_image_load_store extension in central_settings.cpp

**Comment by deveee** [comment]
Should be fixed in this commit:
https://github.com/supertuxkart/stk-code/commit/46619ec62a7e74f464c7910de2c3bbefd6f14dd3

It looks that it was broken since 2015:
e9c2f0ecf1b36782a8fa15a8af62d3bd0556d023
