### ISSUE TITLE
Languages list looks wrong on some resolutions

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2795]
I initially thought that it's related to very low resolutions, but I was able to reproduce it with 1280x1024:

![stk](https://cloud.githubusercontent.com/assets/5108558/23123113/551f10c0-f767-11e6-8d50-5a7dafe8ffe3.png)

**Comment by auriamg** [comment]
I am unable to reproduce the issue, any specific steps to take?

**Comment by deveee** [comment]
Maybe it's related to particular freetype version, i.e. wrong text length computation. No idea :( Currently it occurs for me under cygwin, but I think that I saw it somewhere else too.
And no, any specific steps to reproduce. I just run the game and open settings.

**Comment by deveee** [comment]
This is caused by wrong line endings and can be fixed with this patch:

```
diff --git a/src/utils/translation.cpp b/src/utils/translation.cpp
index eadd937..a85551b 100644
--- a/src/utils/translation.cpp
+++ b/src/utils/translation.cpp
@@ -204,6 +204,9 @@ Translations::Translations() //: m_dictionary_manager("UTF-16")
         {
             for (std::string line; std::getline(*in, line); )
             {
+                if (!line.empty() && line[line.length() - 1] == '\r')
+                    line.erase(line.length() - 1, 1);
+
                 std::size_t pos = line.find("=");
                 std::string name = line.substr(0, pos);
                 std::string localized_name = line.substr(pos + 1);
```

In my case, I made git pull on windows, and then I was running STK under cygwin. So it probably will look the same if you run STK on linux with CRLF files.

Though I have no idea what about using osx files on windows and windows files on osx etc.

And I'm not sure if we want to handle it somehow, or just don't care...

**Comment by deveee** [comment]
Now I think that it's a valid issue, because we have single src package on sourceforge for all platforms - linux, osx, windows. I don't know if someone ever tested stable src package compilation on osx nad windows (assuming that it was prepared on linux).

**Comment by hiker** [comment]
Yes, Benau created it on linux, and I just compiled on windows, and language selection looks fine.
