### ISSUE TITLE
Cannon data not exported correctly

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2797]
I noticed two issues with the blender exporter:
1) The 'target' data line is written incorrect. E.g in cornfield the coordinates of the target line are:
83.8, -131,1, 18.7   and  92.8 -128.7 18.7
but written to the scene.xml files are:
 target-p1="87.04 18.70 -133.65" target-p2="91.00 18.70 -125.16"
The start/check-line is written correctly.

2) The exporter writes: curvetype="bezier" , but stk expects this attribute to be called 'interpolation'So far I think all cannons are bezier, and stk defaults to bezier, so no harm done for now.

**Comment by auriamg** [comment]
Worked around for the moment by applying rotation to the line. The exporter should ideally handle that automatically, though

**Comment by hiker** [comment]
I have fixed cornfield (by manually adjusting the coordinates), but at least the tracks:
- cornfield crossing
- grand paradiso island
Math class has a cannon, but its coordinates appear to be fine. That's all the cannons I am aware of.

**Comment by hiker** [comment]
Also, cornfield-crossing's target line is a bit too wide, which causes karts that are to the very left or right when arriving to crash.

**Comment by auriamg** [comment]
The blender file for Cornfield Crossing has been updated

**Comment by Benau** [comment]
actually it can be as simple as 
+        start_pt1 = start.matrix_world * start.data.vertices[0].co
+        start_pt2 = start.matrix_world * start.data.vertices[1].co
+        end_pt1 = end.matrix_world * end.data.vertices[0].co
+        end_pt2 = end.matrix_world * end.data.vertices[1].co

Now you can even has scale in the cannon start / end
