### ISSUE TITLE
100% CPU usage even when game is closed

### ISSUE THREAD

**Issue by brmbrmcar** [supertuxkart/stk-code#2801]
There is an unkillable process that comes randomly for a few minutes then just vanishes called cc1plus, which uses 100% of the CPU. However, it  seems that files in tmp/stk-code-master are to blame. I am on Ubuntu 16.04, and installed SuperTuxKart from a ppa.

**Comment by deveee** [comment]
IIRC the ppa version is just a cron script that automatically compiles current STK version every day. Not sure if it's the best possible solution, but it's how it works and not really a bug. You can move this file somewhere else and just manually run sometimes to get current version.

**Comment by Benau** [comment]
you building software has nothing to do with stk bug reports

**Comment by SuicSoft** [comment]
@deveee Does the daily ppa run compile tasks on user's computers. If so we should use prebuilt packages instead to prevent people from getting lag , loud fan and low battery life on user's computers

**Comment by brmbrmcar** [comment]
Well I'm sorry. Maybe I should stop reporting serious issues to you, then someone on Steam or something where you have to pay sues you because their computer was completely destroyed.

**Comment by qwertychouskie** [comment]
That PPA is completely unofficial, it is just a script I wrote to make my life easier.  I updated the description of the PPA to make this more clear.  For the history of how this script came to be, see https://github.com/supertuxkart/stk-code/issues/1415.

**Comment by brmbrmcar** [comment]
You can't just dismiss this issue to do with the ppa.

**Comment by auriamg** [comment]
@brmbrmcar The PPA is not official, this is a third-party PPA not officially supported by the STK team. When  you use tools we did not make this is obviously out of our control.

**Comment by brmbrmcar** [comment]
*sigh*

**Comment by brmbrmcar** [comment]
I'll say this AGAIN, shall I? How can you dismiss this to do with the ppa?

**Comment by deveee** [comment]
I think that ```sudo apt-get install supertuxkart=0.9.1-3 -y``` should solve the issue.

**Comment by brmbrmcar** [comment]
Will that give me the latest version? And I still very much doubt the ppa is at fault here.

**Comment by Arthur-D** [comment]
https://en.oxforddictionaries.com/definition/unofficial
http://lmgtfy.com/?q=What+is+cc1plus

**Comment by brmbrmcar** [comment]
Stop taking the piss. I'm not bothering any more.
