### ISSUE TITLE
Aztec fountain is drawn incorrectly

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2802]
Here is how it was in STK 0.9.2:
![zrzut ekranu z 2017-03-02 20-46-39](https://cloud.githubusercontent.com/assets/5108558/23524319/657fbbf6-ff8a-11e6-8c22-8d71cd62419a.png)
and here is how it looks now:
![zrzut ekranu z 2017-03-02 20-50-21](https://cloud.githubusercontent.com/assets/5108558/23524329/6b89ca00-ff8a-11e6-80dd-c6032be37c26.png)

As far as I see, it uses two textures: stklib_aztecFountain_ao_a.png and stktex_generic_concreteA.png. It looks that in current git version only the second one is used, or maybe they are swapped.

**Comment by deveee** [comment]
It's caused by this commit: b669382b930a8934a1acdccf26dd12358264c685
@samuncle was it intended?

**Comment by MTres19** [comment]
Not sure how the "old" detail shader worked, but it appears to me that previously the detail shader simply mixed the two textures from the UV layers together. The decal shader layers them in a more intuitive way transparency in the second layer. (See the dirt tracks through the house in Cornfield Crossing.) The quick fix is to just use stktex_generic_concreteA.png the bottom/first UV layer and make stklib_aztecFountain_ao_a.png semitransparent and use it in the top/second layer. But first @samuncle needs to put the latest version in the media repo; the version in the media repo only has one UV map.

**Comment by qwertychouskie** [comment]
This should have  the 0.9.3 milestone, as it is a regression from 0.9.2. @samuncle any updates on getting this fixed?

**Comment by Benau** [comment]
Please re-open if you don't like me vertex paint them
