### ISSUE TITLE
Grass is too dark in legacy pipeline

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2808]
It can be fixed with this hack:
```
diff --git a/src/graphics/material.cpp b/src/graphics/material.cpp
index ce40bad..0177992 100644
--- a/src/graphics/material.cpp
+++ b/src/graphics/material.cpp
@@ -1010,6 +1010,16 @@ void  Material::setMaterialProperties(video::SMaterial *m, scene::IMeshBuffer* m
     if (m_shader_type == SHADERTYPE_VEGETATION)
     {
         m->MaterialType = video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF;
+
+        // A hack that makes the grass more bright in legacy pipeline, so that
+        // it looks more similar to our shader-based pipeline
+        if (!CVS->isGLSL())
+        {
+            m->AmbientColor  = video::SColor(255, 150, 150, 150);
+            m->DiffuseColor  = video::SColor(255, 150, 150, 150);
+            m->EmissiveColor = video::SColor(255, 150, 150, 150);
+            m->SpecularColor = video::SColor(255, 150, 150, 150);
+        }
     }
 
     if (m_disable_z_write)
```

There are only two things that look buggy in fixed pipeline:
- grass objects are too dark
- nitro/skidding particles are misplaced and cause slowdown

Everything other looks just fine, so it's IMO fully playable.

Though I don't want to spend more time on legacy pipeline, so if noone will find the proper fix, I suggest just to apply this patch before release.

**Comment by Benau** [comment]
because grass use vertex color to determine movement in our shaders, so can you make irrlicht shader to discard vertex color for video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF (or make a new EMT* just for grass)

**Comment by deveee** [comment]
I pushed the patch to master branch:
https://github.com/supertuxkart/stk-code/commit/724cb100e07151ac40b809a291db059ea2105e24
