### ISSUE TITLE
Interpolation changes causes visual glitches

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2809]
This commit
https://github.com/supertuxkart/stk-code/commit/ae375c50b60c962f6507d91390712b7df5ffc237

Causes big purple floating squares to appear in subsea, brown ones in cocoa temple, etc.
![abyss-2017 03 14_21 07 53](https://cloud.githubusercontent.com/assets/4296971/23929428/700f98e0-08fc-11e7-8e0d-bd771848f256.jpg)

**Comment by hiker** [comment]
Fixed in 698fe1a.
