### ISSUE TITLE
OpenMP evaluation

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2810]
OMP is used in a few places. Esp. on windows it causes a high load, and the benefit are between unclear and doubtful.  This ticket is used to collect information/measurements to decide if openmp should be removed.

**Comment by hiker** [comment]
sfx-manager used openmp to load the 48 sfx.
Without openmp from harddrive (potentially cached by the OS): 0.28 seconds
With openmp: 0.1 seconds

**Comment by hiker** [comment]
omp in draw_calls: I used default graphics settings (intel: 3), single kart, and just displayed cornfield crossing (1024x768, window)

Intel(R) HD Graphics 4600 with openmp: 58 fps
Intel(R) HD Graphics 4600 without openmp: 59 fps
GeForce GTX 960M/PCIe/SSE2 with openmp (level 3): 105-106 fps
GeForce GTX 960M/PCIe/SSE2 without openmp (level 3): 106-107 fps
GeForce GTX 960M/PCIe/SSE2 with openmp (level 5): 76 fps
GeForce GTX 960M/PCIe/SSE2 without openmp (level 5): 76-77 fps

**Comment by hiker** [comment]
The load() function in sfx_manager (which has the openmp in it) can be done by the thread, just move it to the beginning of mainLoop().

**Comment by Benau** [comment]
omp removed, now load() function leaved for hiker

**Comment by Benau** [comment]
moved
