### ISSUE TITLE
Error with transparent texture

### ISSUE THREAD

**Issue by Elbullazul** [supertuxkart/stk-code#2811]
hi,

sometimes, after a couple of games the game crashes and in the logs the following line appears:

> [fatal  ] STKMesh: Missing texture for material transparent

I checked the textures folder in /usr/share and transparence.png and transparence2.png exists. So why is it that the program crashes?

also, sorry if this is in the wrong repo

**Comment by Benau** [comment]
Do u use any addon track? Also which stk version are you using?

**Comment by Benau** [comment]
Actually 0.9.2 has no more fatal error about missing texture, consider update or build git stk

**Comment by Elbullazul** [comment]
@Benau will I lose progress on the gameplay?

**Comment by MTres19** [comment]
@Elbullazul If you are already using the 0.9.x series, no, you won't lose your progress in story mode.

**Comment by Elbullazul** [comment]
@MTres19 @Benau thanks guys for your help, it works even better with v0.9!
