### ISSUE TITLE
High frequency noise for materials

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2818]
An easy way to add extra details to textures without killing performances or filling the VRAM is to add a small resolution high frequency noise texture.

Example of such texture:
http://docs.garagegames.com/torque-3d/official/content/documentation/Artist%20Guide/Tutorials/images/ExampleDetailTex.jpg

Result in game
http://docs.cryengine.com/download/attachments/1048772/detailbumpmap.png?version=1&modificationDate=1260885076000&api=v2

The texture is sampled 8 or even 16 time the resolution of the UV map which allows to create high frequency noise and add a nice touch.

It would be interesting to be able to use it to artificially increase the details in our materials.
The cost is pretty minimal, it's "only" adding a 256 texture to a shader. We can even display it only when the player is close to the camera.

**Comment by Benau** [comment]
For sp you can add whatever shader you want
