### ISSUE TITLE
Cannot load sounds

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2821]
Just to not forget about it, because the problem still persists for me. It usually occurs when I run STK first time. When I run the game second time, then everything is ok.

Here are the errors in console:
```
[error  ] SFXBuffer: LoadVorbisBuffer() - couldn't open file!
[error  ] HTTPRequest: Can't open './.config/.local/share/supertuxkart/addons/news.xml.part' for writing, ignored.
[error  ] SFXBuffer: Could not load sound effect data/../../supertuxkart-assets/sfx/ball_bounce.ogg
[error  ] SFXBuffer: LoadVorbisBuffer() - couldn't open file!
[error  ] SFXBuffer: Could not load sound effect data/../../supertuxkart-assets/sfx/boing.ogg
[error  ] SFXBuffer: LoadVorbisBuffer() - couldn't open file!
[error  ] SFXBuffer: Could not load sound effect data/../../supertuxkart-assets/sfx/bowling_roll.ogg
[error  ] SFXBuffer: LoadVorbisBuffer() - couldn't open file!
[error  ] SFXBuffer: Could not load sound effect data/../../supertuxkart-assets/sfx/bowling_shoot.ogg
(...)
```

And here is the log from gdb:
https://github.com/supertuxkart/stk-code/files/853544/sfx_log.txt

**Comment by qwertychouskie** [comment]
How much free space do you have on your drive?  I sometimes let it drop to 0 bytes, and it messes with things...

**Comment by qwertychouskie** [comment]
`Failed to get the home directory, not an absolute path: ./.config`
Hmm... weird.

**Comment by hiker** [comment]
I was not able to reproduce it. Considering that we are talking of 0.2 seconds at startup, the easiest solution would be to just move the load call back to the main thread.

**Comment by deveee** [comment]
@Benau Do you want to fix it or I can just revert it?

It looks that it tries to access some sounds before loading in SFXManager::mainLoop() is finished.

**Comment by Benau** [comment]
git revert ce426d82cc5988b82b8f35eadfd3e61198df2159

**Comment by deveee** [comment]
Ok, reverted
