### ISSUE TITLE
Show the number of nitro points you have, vs how much you need in a nitro challenge

### ISSUE THREAD

**Issue by n3rdopolis** [supertuxkart/stk-code#2822]
Especially when playing XR591 in expert, it gets hard to see how many nitro points you have vs how many you need, especially as the bar gets closer...

It might make it a bit better to show a numerical counter of how many you have, vs how many you need.

**Comment by auriamg** [comment]
Maybe only in challenge mode (I see no point to doing that outside of challenges)
