### ISSUE TITLE
Suggestion: Make Volcano Island reversible

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#2827]
The Volcano Island track is not allowed to be driven in reverse and apparently the only reason for this is that there's a simple ramp on the road which you only can hop over in one direction.

All other parts of the tracks can be driven in reverse without problems.

It would be very nice if some artist could do a small redesign of this track in order to make it reversible.

One idea would be to add a second ramp which goes the other way, so you can jump in either direction.

Another idea would be to add a “sideway” which leads around the ramp, but this can only be accessed when you drive from the other direction.

**Comment by hiker** [comment]
One suggestion: we could add a <forward>  <backward> tags. Objects in those tags would only be used when driving in the corresponding direction. So in this example we could have two ramps on each side, but only one will be used depending on direction.

**Comment by auriamg** [comment]
Done in svn

**Comment by Wuzzy2** [comment]
Bravo! I appreciate that. :-)
