### ISSUE TITLE
Transparent objects are rendered differently when hardware skinning is enabled

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2828]
Not sure how much it matters, but I noticed that it works differently than before. You can see the bubblegum shield. Here is how it looks with hardware skinning:
![zrzut ekranu z 2017-03-29 20-59-37](https://cloud.githubusercontent.com/assets/5108558/24471691/32389d8c-14c3-11e7-8b19-b28b49bcdee8.png)
And here is how it was looking before (and without hardware skinning):
![zrzut ekranu z 2017-03-29 20-58-54](https://cloud.githubusercontent.com/assets/5108558/24471725/4b34df1c-14c3-11e7-9e7d-ce6669a9e2e8.png)

Previously it was using transparent fog shader with
```    
glDepthMask(GL_FALSE);
glDisable(GL_CULL_FACE);
```
so this is the main difference.

@Benau Can this be moved below glDisable(GL_CULL_FACE); or is this needed where it currently is?

**Comment by Benau** [comment]
The ListTranslucent* are used to render ghost kart (which is animated mesh, bubblegum maybe too) together, so we can have a ghost kart with cull face and depth mask on, so there is less artifacts (for example, with no cull face and depthtest, you will see the mouth of tux rendered penetrating his body!)

**Comment by qwertychouskie** [comment]
Is there any chance of getting this fixed soon?  It's starting to slightly annoy me... :)

**Comment by auriamg** [comment]
Does this affect other areas negatively, apart from the bubblegum? The bubblegum itself looks just fine and I don't see the need to "fix" anything there, it may even look better now than before

**Comment by qwertychouskie** [comment]
It's just weird to not see the other side of the bubble gum (and it is inconsistent between users using hardware skinning and those not).

**Comment by auriamg** [comment]
@deveee Have you seen more noticeable occurrences where this is problematic than with the bubblegum? If it's just the bubblegum I'd tend to close this as unimportant

**Comment by deveee** [comment]
I didn't find any other problems caused by this. I just noticed it when I was trying to find a reason why bubblegum in GLES renderer looks differently. But tbh. the bubblegum on second image looks better for me ;)

I will keep it opened with very minor priority. If it will cause issues in other places in future, it's easier to find a reason.

**Comment by Benau** [comment]
Fixed by SP
