### ISSUE TITLE
Unused cocoa_river_fast.ogg2 file

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2831]
In music directory we have ```cocoa_river_fast.ogg``` and ```cocoa_river_fast.ogg2``` while in ```cocoa_river.music``` there is only ```fast-filename = "cocoa_river_fast.ogg"```

@samuncle Can I remove the cocoa_river_fast.ogg2 file or do you need it?

**Comment by yamboy1** [comment]
If it's not referenced anywhere then I would delete it. Just try building the game without cocoa_river_fast.ogg2 and see if it works,

**Comment by qwertychouskie** [comment]
@deveee Here's the commit that added it for reference: https://sourceforge.net/p/supertuxkart/code/15699/

**Comment by yamboy1** [comment]
So clearly it's not needed

_Sent from my Vodafone Smart ultra 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by deveee** [comment]
It looks that nobody cares, so I removed it. Can be always restored from history.
