### ISSUE TITLE
Ciudad Catalina is in standard tracks

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2832]
Ciudad Catalina has been committed to the game in tracks, not wip-tracks, and additionally is marked as a standard track in its XML file. The problem with this is that it's unfinished and risks being accidentally shipped with the next release (the actual filtering I guess is based on the tracks folder, so most importantly it should be put in wip-tracks instead, but I may be wrong).

**Comment by auriamg** [comment]
@samuncle This is for you. Marking as major since it blocks the release

**Comment by MTres19** [comment]
@auriamg I fixed this in SVN.

**Comment by deveee** [comment]
It's still a bit messy because the tracks are in three groups: wip-tracks, nextgen and standard. But it's enough that they are in wip-tracks directory, so closing as fixed.
