### ISSUE TITLE
Nitro sound only plays when pressing the key

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2838]
The nitro sound plays only when the key for using nitro is pressed, but if you press the button only short, nitro is used for a longer time without the sound.
The sound should be played when nitro is used (and not only when the button is pressed).

**Comment by Alayan-stk-2** [comment]
Looking at the code to fix this, it appears this is related to a much worse bug.

    bool increase_speed = (m_controls.getNitro() && isOnGround());

The nitro will be consumed for min_nitro_time ; but the bonus speed won't be applied during all this time unless the key remains pressed.
