### ISSUE TITLE
Crashes vs Singularities

### ISSUE THREAD

**Issue by Danfun64** [supertuxkart/stk-code#2841]
I'm having some strange problems with the trunk versions of STK on my Windows system. If I try to compile a 64-bit version, everything runs fine at first, but once I enter a race it will crash sometime inbetween immediately and a few seconds in. So I tried to compile a 32-bit version, which doesn't crash, but instead results in effects like engine smoke and nitro not being rendered as well as strange graphical glitches on some maps that cover a large area of the game. The stdout.log files don't describe the problems at all...

**Comment by Benau** [comment]
Someone reported latest nvidia driver is crashing for stk, not sure it this is your case as in #2837

**Comment by Danfun64** [comment]
I'm running an ATI Radeon card on my computer, so the problems are probably not related.

Two things I forgot to mention. The 32-bit trunk build has audio crackling, and the official 0.9.2 windows exe runs exactly as its supposed to.

**Comment by deveee** [comment]
Are you able to make a regression test? If self-compiled STK 0.9.2 works for you, and current git version doesn't work, you can find which modification caused this problem.

If the 64-bit version crashes, you can compile it in debug mode, then run under debugger, and then you will get a stack trace that shows where it precisely crashes.

And I suggest to add a bit more information to the bug report - eg. graphics card model, drivers version, the stdout.log file, maybe some screenshots.

**Comment by hiker** [comment]
Which branch did you use for the 64 bit windows compilation? Afaik there is at least one potential bug fix in the win-64bit branch. Note that at this stage we are not yet supporting 64 bit windows officially (though we are getting close).

**Comment by deveee** [comment]
Also make sure that you have updated stk-assets. We added new sounds for kart collisions recently. I had a crash in Kart::update because these files were not available in sfx directory.

**Comment by Danfun64** [comment]
I compiled 0.9.2 with Visual Studio 2015 Community on 32-bit mode with the dependencies from Sourceforge...and I get the same kind of crashing that I got with the 64-bit trunk build.

Here's the debug log: https://paste.debian.net/hidden/96ed8098/

**Comment by deveee** [comment]
It's interesting crash, though atm. I have no idea about the reason.

Is it possible to add a breakpoint on exit in visual studio? Because now it just exits and doesn't crash, so we don't get the backtrace.

You can try to disable internet connection in STK, because these errors:
```
Exception thrown at 0x7634B782 in supertuxkart.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0217D194.
Exception thrown at 0x7634B782 in supertuxkart.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0217D29C.
```
are shown after curl http requests.

**Comment by Danfun64** [comment]
I wouldn't know how to "add a breakpoint on exit in visual studio"...not 100% how to get it on gdb either though...

**Comment by hiker** [comment]
You don't need to do anything special, just run stk inside of Visual Studio, and it should automatically stop. Then copy&paste the stack trace here.

**Comment by Danfun64** [comment]
When it "crashed", it didn't automatically stop. It just froze and hung.

**Comment by qwertychouskie** [comment]
What is the model of your graphics card and the version of the installed drivers?  Also, on one computer I was running STK on, STK would sometimes crash, but updating the BIOS/UEFI fixed it, so it may be worth a try.

**Comment by Danfun64** [comment]
I'm pretty sure that my BIOS has no updates.

As for the graphics card hardware and software: AMD Radeon HD 6520G using AMD Catalyst 15.201.1151-150821a-184724E. I don't think upgrading to 17.x will work...

**Comment by qwertychouskie** [comment]
The latest is 15.7.1: http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%207%20-%2064 (Win 7 x64) or http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%208.1%20-%2064 (Win 8.1 x64).

**Comment by Danfun64** [comment]
Just as i suspected, the driver upgrade didn't do anything.

**Comment by qwertychouskie** [comment]
What happens if you try running a build not built on your computer, e.g. the one from https://forum.freegamedev.net/viewtopic.php?f=17&t=7408?  It seems weird that the official 0.9.2 .exe runs correctly, but compiling the same code makes it not work.

**Comment by Danfun64** [comment]
I already tried that exe, same result.

**Comment by qwertychouskie** [comment]
Weird.

> I'm pretty sure that my BIOS has no updates.

I would double-check, just to be certain.  Other than that, I'm out of ideas, maybe someone else here knows what to do.

**Comment by Danfun64** [comment]
Double checked. have the latest BIOS. I don't see why the BIOS would be a problem. I was able to compile STK and have it run correctly with the same computer using Linux.

**Comment by auriamg** [comment]
@qwertychouskie I know you're trying to help but your suggestions don't always make sense... If you're not sure please let us handle the tech support. It is very unlikely that the BIOS has anything to do with that. Thank you

**Comment by qwertychouskie** [comment]
The reason for the BIOS suggestion is it actually fixed STK 0.9.2 crashing on a Lenovo gaming laptop I was playing it on.  Although it is usually not a problem, I mentioned it since it fixed a weird crash for me.

**Comment by Danfun64** [comment]
I just confirmed that I get this issue with the official 0.9.2 exe...though I didn't notice it at first...

**Comment by hiker** [comment]
Can you try reducing the graphical quality? Start with lowest quality, and if this works add in more features. If it's just a certain feature causing the problem, it might still be a driver issue and we can then disable this feature for this card and driver version.

**Comment by SuicSoft** [comment]
@Dafun64 try these drivers http://forums.guru3d.com/showthread.php?t=409002 (install them with driver enforcement disabled).I had some graphical glitches in stk and installing these drivers fixed it ;-)

**Comment by Danfun64** [comment]
Installed the new drivers. Same hanging/crashing issue. What did change was that I could no longer alt-tab out of Teeworlds/DDNet in fullscreen mode without enabling borderless window mode...

**Comment by Danfun64** [comment]
Thanks to this thread (http://forums.guru3d.com/showthread.php?s=e849fb31325a69cc569a6edf9c30443d&t=399547) I was able to find an older version of the drivers which works properly. Thanks for reminding me of guru3d!

**Comment by Danfun64** [comment]
For the record, so far it seems the newest version that properly works is 15.6 beta.
