### ISSUE TITLE
Characters on minimap only facing up

### ISSUE THREAD

**Issue by yamboy1** [supertuxkart/stk-code#2842]
Could you set the characters angle on the minimap to be the angle that they are facing in the game. Also could you say where the code to do this is.

**Comment by auriamg** [comment]
We have no plan to do this at this time. In any case, the icons are not intended to convey directions and would be pretty poor at that, rotating the current icons would just make them hard to read. Maybe if some direction arrow was added along the icon that may work... I definitely don't see the icons as they are now being rotated though

**Comment by yamboy1** [comment]
A direction arrow sounds like a great idea

**Comment by auriamg** [comment]
@hiker any opinion? My personal thoughts are along the lines of "this could be nice but is also very unimportant, so if someone contributes it why not but the core team likely won't work on that".

**Comment by yamboy1** [comment]
I could have a look into into it

**Comment by hiker** [comment]
TBH, I am not sure if it's worth the effort - what would you gain? Not much in a race, maybe a bit of information in battle mode?
I would suggest to first make a mock-up of what it might look like - I would imagine a battle with 8 karts and arrows to look rather confusing.

**Comment by yamboy1** [comment]
Yeah. Probably too much hassle to deal with.
