### ISSUE TITLE
Mac Pro Froze

### ISSUE THREAD

**Issue by tomihasa** [supertuxkart/stk-code#2845]
I downloaded the latest .dmg. I copied SuperTuxKart.app to Applications. I started the game. My computer froze and I had to force shutdown, because nothing worked. Mac Pro 8-Core (Early 2009), two 2.26 GHz Quad-Core Intel Xeon E5520 processors, 6 GB memory, ATI Radeon HD 4870 Graphics Upgrade Kit, 18x Superdrive, hard drive 1: 640 GB, hard drive 2: Samsung Spinpoint F3, 1 TB.

**Comment by qwertychouskie** [comment]
Weird.  Do you ever have this problem in other circumstances? What OS X/macOS version?  Have all software updates been ran (especially driver and UEFI firmware upgrades)?  I would run a RAM test, as STK 0.9.2 takes up a lot of ram, so maybe there are some faulty addresses up high that normally aren't used, but crash the computer when used.  Also, I would try blowing out the computer with an air compressor/canned air, as maybe the graphics card is switching to a higher performance state, then overheating.

**Comment by tomihasa** [comment]
I need to specify my problem: when I said my Mac froze what I meant is I still could move the mouse cursor, but nothing happened when I clicked a mouse button or pressed any key on keyboard. I did not hear any loud noise from the video card that can happen with GPU heavy games. I have OS X 10.11.6 and all software updates have been run.

In November 2016 I had a "white screen" problem I tried resolving by resetting NVRAM, but the real problem was because of incompatible old software (LineIn 2.1.1 and Soundflower 1.6.6 for recording), which I then removed.

I can not start Apple Diagnostics or Hardware Test by pressing D or Cmd+D, but I can use Safe Boot (Shift), Single-User Mode (Cmd+S) and Recovery Mode (Cmd+R).

**Comment by qwertychouskie** [comment]
It's Option+D, not Cmd+D, according to http://www.macissues.com/2014/03/21/how-to-run-and-interpret-apples-hardware-tests-on-your-mac/.

**Comment by qwertychouskie** [comment]
You can also try the good-ol' Unplug-the-computer-Hold-the-power-button-for-a-few-seconds-Plug-it-back-in.

**Comment by auriamg** [comment]
Hi, unfortunately this will likely be very hard to debug. An application should never be able to fully crash a computer so this might be a driver issue. Apart from checking if you have all your updates, I have no idea how to debug this

**Comment by tomihasa** [comment]
Probably there are not many Mac Pro Early 2009 users playing video games, so no big deal. I just wanted to test an open source game how it works with my machine as I have been looking at open source projects for the past two weeks out of curiosity. Thanks!

I do have an old Blackmagic Design Intensity Pro installed and I'm not plannning to remove it, as I need it. I also have Final Cut Studio 3 installed, if that means anything.

**Comment by qwertychouskie** [comment]
The first review at https://www.amazon.com/Blackmagic-Design-Intensity-Pro-Editing/dp/B001CN9GEA says that the drivers are trash. Maybe try temporarily removing the card and seeing if the issue persists?

**Comment by qwertychouskie** [comment]
You could also try downloading the latest software for it from here: https://www.blackmagicdesign.com/support/download/9d53d0685c754e728c46d6dd57841fc0/Mac%20OS%20X

**Comment by qwertychouskie** [comment]
Also, you could try forcing STK to use the OpenGL 2 renderer by setting `force_legacy_device` to `true` in ~/Library/Application Support/supertuxkart/0.8.2/config.xml.  It will look bad (the old renderer has a bunch of visual bugs in 0.9.2), but it might at least launch.

**Comment by qwertychouskie** [comment]
I should note that even if you do get it working (STK 0.9.3 should be out soon and might by worth a try), Macs generally have very bad OpenGL performance (see http://www.phoronix.com/vr.php?view=24774), and you would be much better off dual-booting Linux to play the game.

**Comment by Alayan-stk-2** [comment]
Not enough details to do anything, unlikely to still be relevant,, and the affected system is now 15 years old. Closing.
