### ISSUE TITLE
Cannon causing issues for basket ball

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2847]
Basket balls are not very useful in Cornfield Crossing since the ball explodes where the cannon ends. If possible it might be solved by letting basket balls travel in cannons as well.

**Comment by hiker** [comment]
Should be fixed in the  fix-ball-cannon branch.
@Arthur-D can't remember if you have already test it ... if not, can you?

**Comment by Arthur-D** [comment]
I think I did and that the result was positive, but I'm actually not sure. Wish I could go back three months to slap myself into commenting here if I did. ;)

**Comment by Arthur-D** [comment]
Oh and I can probably test next week, but at the moment I'm not at home.

**Comment by Arthur-D** [comment]
Confirmed fixed in fix-ball-cannon.

**Comment by qwertychouskie** [comment]
Um... The branch hasn't been merged, this should stay open until it is.

**Comment by Arthur-D** [comment]
You're right, I was a little too quick.

**Comment by qwertychouskie** [comment]
OK, now it can be closed :)
