### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ModdyLP** [supertuxkart/stk-code#2848]
Hello, i have trouble on starting the game. The forum is to bad, that i dont can post my problem there. 

Here is the Stracktrace, can anyone tell me why there is a problem:

```
---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 DrvValidateVersion
 BaseThreadInitThunk
 RtlGetAppContainerNamedObjectPath
 RtlGetAppContainerNamedObjectPath
---------------------------
OK   
---------------------------
```

**Comment by qwertychouskie** [comment]
`DrvValidateVersion`
Looks like an outdated graphics driver (just a guess).  What card do you have?  Also you could try the build from here: https://forum.freegamedev.net/viewtopic.php?f=17&t=7408
It has some fixes for buggy drivers (though I still recommend updating the graphics drivers if possible for best performance).

**Comment by ModdyLP** [comment]
I have the NVidea Geforce GTX 1070 OC with the latest driver updates. I have make an update 2 days ago. I dont want to build it on my own, because i have not the time and the space to do that.

**Comment by qwertychouskie** [comment]
The link is to a pre-compiled version.

**Comment by auriamg** [comment]
I presume this is on Windows

Open folder "%APPDATA%/supertuxkart/0.8.2" (you can paste that in the address bar of windows explorer) and paste here the contents of file "stdout.log" please, in case there's something there

but it does look like a driver issue at first glance
