### ISSUE TITLE
Add a prefix to irrlicht keycodes?

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2849]
Currently irrlicht keycodes cause conflicts with ```linux/input.h``` header. For example:
```
#define KEY_LEFT		105
#define KEY_RIGHT		106
#define KEY_END			107
#define KEY_F1			59
#define KEY_F2			60
#define KEY_F3			61
```
etc...

Additionally gcc doesn't complain about redeclaration, so you don't really have any idea why some keys stopped working.

Joystick support needs a workaround because of this:
```
// linux/joystick.h includes linux/input.h, which #defines values for various KEY_FOO keys.
// These override the irr::KEY_FOO equivalents, which stops key handling from working.
// As a workaround, defining _INPUT_H stops linux/input.h from being included; it
// doesn't actually seem to be necessary except to pull in sys/ioctl.h.
#define _INPUT_H
#include <sys/ioctl.h> // Would normally be included in linux/input.h
#include <linux/joystick.h>
#undef _INPUT_H
#endif
```

This header is also useful for Wayland (it contains mouse buttons names).

So maybe just add a prefix, i.e. something like:
```
		IRR_KEY_UNKNOWN          = 0x0,
		IRR_KEY_LBUTTON          = 0x01,  // Left mouse button
		IRR_KEY_RBUTTON          = 0x02,  // Right mouse button
		IRR_KEY_CANCEL           = 0x03,  // Control-break processing
```
to avoid more issues in future?

**Comment by hiker** [comment]
I was just told on irc that I am apparently supposed to agree to this. Yes, of course I agree :)

**Comment by deveee** [comment]
Ok, done in https://github.com/supertuxkart/stk-code/commit/0dba3c8f67d38a7f4f7847ba954bd0b9a2d35d20

I just wasn't sure if you are fine with it, prefer different solution, different prefix, or maybe you don't care.

Btw. do you need lib/irrlicht/media, lib/irrlicht/tests and visual studio project files in lib/irrlicht/source/Irrlicht? It only makes a mess and I always have to use ```grep -v vcproj``` ;p
