### ISSUE TITLE
Can not set up controller mapping if two Xiaomi gamepads are connected.

### ISSUE THREAD

**Issue by mplzik** [supertuxkart/stk-code#2851]
If two Xiaomi gamepads are connected when launching supertuxkart (Debian build, 0.9.2+dfsg-2), the mapping configuration screen can not be correctly used -- if I try to set up a key mapping, I'm not able to get out of the key assignment mode. 

If only one of the controllers is present, everything works as expected.

**Comment by qwertychouskie** [comment]
@emempi There were some fixes to the gamepad code recently, can you retry with the latest Git version?

https://code.launchpad.net/~stk/+archive/ubuntu/daily
https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test

**Comment by Benau** [comment]
Have time to try this beta build?https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200611/SuperTuxKart-git20200611-linux.tar.xz/download

**Comment by Benau** [comment]
It uses sdl2 for handling gamepad so it may be better

**Comment by Alayan-stk-2** [comment]
Please open a new ticket if the issue persists in STK 1.2 In the meantime, I'll close this as not applicable anymore as we now rely on SDL2 for gamepad handling.
