### ISSUE TITLE
Controls of one player lag if two Xiaomi gamepads are connected

### ISSUE THREAD

**Issue by mplzik** [supertuxkart/stk-code#2852]
When playing two-player game with two Xiaomi gamepads connected, actions of one player constantly lagged. This could be alleviated by pausing/resuming the game; but only for few seconds.

Note that this has been tested on a low-performance computer (and thus, might possibly result in event queue overflow?).

**Comment by Alayan-stk-2** [comment]
Please open a new ticket if the issue persists in STK 1.2 In the meantime, I'll close this as not applicable anymore as we now rely on SDL2 for gamepad handling.
