### ISSUE TITLE
Allow changing of advanced options in game

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2859]
It would be quite useful to have another tab in the options screen:
![options_advanced](https://user-images.githubusercontent.com/13989090/27239387-8c68d0a6-5285-11e7-9e75-e2ce0472b3a5.png)
That had options like Artist debug mode, force legacy device, disable compute shaders, enable azdo, etc.

**Comment by deveee** [comment]
I agree that we should have a way to disable compute shaders because it causes issues on some drivers. Maybe enable it only for adcanced lighting?

The other settings that you mentioned IMO shouldn't be available for end user.

**Comment by qwertychouskie** [comment]
Here's what I have so far:
![](http://i.imgur.com/ucDMBgl.png)

**Comment by auriamg** [comment]
I see no reason to offer most of these advanced options to the end user. Artist debug mode is just fine where it is in the config file, we do not want to give that to everyone. Experimental stuff should also not be offered. The most I would go is a single checkbox "disable recent OpenGL features" that could disable compute shaders, azdo, etc. but definitely NOT a full breakdown and definitely not so displayed so prominently
