### ISSUE TITLE
Use Travis to automatically upload builds to Coverity

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2866]
See https://scan.coverity.com/travis_ci.

**Comment by auriamg** [comment]
If someone does it, we could merge it I guess. But in the meantime, this is not a priority for us so has nothing to do on our todo-list.

**Comment by qwertychouskie** [comment]
I'd happily do it, though I would need access to Coverity to set it up.

**Comment by qwertychouskie** [comment]
I just sent an access request.
