### ISSUE TITLE
player.xml is in a hard to read encoding

### ISSUE THREAD

**Issue by Yetoo1** [supertuxkart/stk-code#2868]
I want to unlock all the levels for testing a bug on a level that is locked in the vanilla game. I read that the way to do this is to change the map in the player.xml to equal easy. But unfortunately, the entire file seems to be corrupted or unreadable to me. I don't know if the game purposely does this or if it's a bug, but it's annoying. I tried deleting the file and then starting the game again to create a new one, but the problem still persists. The file is attached but in txt form because git doesn't accept xml.

[players.txt](https://github.com/supertuxkart/stk-code/files/1095563/players.txt)

**Comment by Yetoo1** [comment]
Well that's strange, it actually displays normally. Whenever I tried to edit it with gedit or nano it shows corrupted, but when I view the contents with cat it's normal. Can someone explain?

**Comment by Yetoo1** [comment]
I was able to read it properly and edit it with vim, nano and gedit, from what I tested, still can't read this properly.

**Comment by deveee** [comment]
It's utf32 encoding and that's why some editors don't read it. Geany opened it without problems.

**Comment by Arthur-D** [comment]
GEdit can also open and edit it, but you need to set the encoding as mentioned above. Too bad it doesn't auto-detect properly.

**Comment by qwertychouskie** [comment]
Mousepad seems to be able to open it just fine  However, is there any reason this needs to be UTF-32?  UTF-8 is pretty universally supported, and might thus be a better idea.

**Comment by auriamg** [comment]
In git I believe this file is no longer utf-32 so it should be easier in future versions. But yes, for now just use an editor that supports utf-32, and make sure to select the proper encoding if it's not auto-detected
