### ISSUE TITLE
Add "onclick" option in .stkgui files

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2877]
E.g. :
```
<button label="Get it now" onclick="LinkHelper::OpenURL ('https://SuperTuxKart.net/Download')" >
```

**Comment by auriamg** [comment]
That would be hard to implement correctly in a cross-platform way (including all linux/unix variations), probably not worth the effort.

**Comment by qwertychouskie** [comment]
The idea is to allow calling functions in STK, I don't see how this changes depending on the platform...
