### ISSUE TITLE
Allow setting amount of exhaust per kart

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2878]
For example, Nolok's kart would probably have a lot of exhaust, while Gnu's carpet would have none (last time I checked flying carpets don't have internal combustion engines :).  This ideally should be settable in the Kart Properties panel of Blender.

**Comment by nado** [comment]
And what would be the effects of exhaust ?

**Comment by qwertychouskie** [comment]
The visual effect (it's in git only right now)

**Comment by Benau** [comment]
I will have kart.xml be able to specify ***.xml for a exhaust effect, if empty than no particle (for gnu and kiki), default to kart_exhaust.xml
