### ISSUE TITLE
Restart ghost kart replay

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2881]
Whole scene seems to be added multiple times when pressing "restart race" during watching the replay

**Comment by Benau** [comment]
Move Camera::createCamera(World::getWorld()->getKart(0)) from World::reset to World::init may help

**Comment by auriamg** [comment]
Can you clarify what you mean by "added multiple times"? What problematic symptoms do you see? I did a few tests and didn't notice any issue
