### ISSUE TITLE
Some karts have fake lights

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2886]
Some of the karts have fake lights, which are not always placed well like my screenshot shows (also real lights, which makes the fake lights a little redundant maybe). In any case I think all karts or no karts should have them, not just a select few.
![sara_fake_lights_bad_placement](https://user-images.githubusercontent.com/5515261/28684422-a05fc124-7304-11e7-8c48-dc3d2950378c.jpg)

**Comment by Benau** [comment]
I don't see the "fake cone" when reexporting, so probably sam doesn't svn commit sara the racer

**Comment by MTres19** [comment]
Or jymis.... Can't remember which Sara he added lights to...

**Comment by Benau** [comment]
Notice the wing mirror, back + front light are all brought back to spm and blend
