### ISSUE TITLE
Make crash sound volume relative to impact

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2888]
As the title says, it would be really nice if the crash sounds were played according to the relative physical impact, i.e. if you crash slowly you don't get full volume, but if you crash fast you do. Right now crashing sounds repetitive because it's always played at full volume as defined in sfx.xml. Maybe some formula could be used which takes relative velocity into account and auto-scales between 0.01 to 0.70 for example, but if the 0.7 value in sfx.xml changes it would scale between 0.01 and the new volume.

**Comment by auriamg** [comment]
Fixed by pulled request
