### ISSUE TITLE
Simplify getLightFactor for non-advanced lighting

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2889]
This is just a reminder for me.

For non-advanced lighting specular and diffuse textures are single color, so it should be enough to just use something like:
```
return diffuseMatColor * 0.73;
```

For GLES renderer in Hacienda it increases fps from 24 to 28 on my device.

**Comment by deveee** [comment]
@Benau Do you think that it's always true that specMapValue = 0.0 when advanced lighting is disabled?

**Comment by Benau** [comment]
yes

**Comment by deveee** [comment]
Ok, done in https://github.com/supertuxkart/stk-code/commit/bc6ff38b22e8b7457c21df7e438267d7fe935163
