### ISSUE TITLE
Possible to drive on walls

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2896]
Even boundaries:

https://jacobspctuneup.tk/menu_2017.08.05_14.54.36.webm

**Comment by Benau** [comment]
Fixed with .spm temple

**Comment by qwertychouskie** [comment]
@Benau That was just one example, it is possible to drive on any vertical surface.

I'm pretty sure it's related to https://github.com/supertuxkart/stk-code/commit/96bdf7705053bcf16345dc2646360d00a689cc88, karts used to slide on vertical surfaces, and now they don't.
