### ISSUE TITLE
Fade out property of billboard isn't working

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2897]
Hi everyone, while trying some ways of faking halo and other light effect unfortunately it seems the fadeout property of billboard isn't working

![billboard](https://user-images.githubusercontent.com/6406045/29006896-736217de-7aad-11e7-86b9-d1fb856ccc13.png)

**Comment by Benau** [comment]
I cannot test anymore in android 4.4 because I updated to latest RR

**Comment by deveee** [comment]
It shouldn't crash, in worst case it will have wrong color. If someone will confirm that it doesn't work, we can just add
```
#ifdef Needs_Vertex_Id_Workaround
    vertex_color = vec4(1.);
#endif
```

**Comment by Benau** [comment]
ok
