### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#2899]
There are some copyright/trademark issues with SuperTuxKart licensing.
1, Beastie is non-free. https://en.wikipedia.org/wiki/BSD_Daemon#Copyright
2. Blender logo is non-free (it is included in Suzanne kart). https://www.blender.org/about/logo/
3. All mascots except for Nolok can be trademarked. There can be some restrictions but I don't know about them.

**Comment by nado** [comment]
I dont think Blender logo will cause any problem : 

> Blender’s logo has been used in hundreds of ways. This was — and still is — considered to be an honest tribute to Blender, and the guidelines are not meant to make these uses “illegal” or “officially disapproved”. 

Concerning Beastie, this page holds contact information to get an approval from the rights owner http://www.mckusick.com/beastie/mainpage/copyright.html

**Comment by stas730** [comment]
Anyway, using non-free data is not good. If permission is required to use or commercial use is not allowed, it must not be included in SuperTuxKart (if we need a free game).

**Comment by auriamg** [comment]
For beastie, it says the original _image_ is copyrighted, we are not using that image, we are using a model that was made from scratch for STK. So unless you have information that the "beastie" name is itself copyrighted, I don't think there is a legal issue there. If someone wants to contact the author to make sure, why not though.

For the blender logo, while I really don't think we'd get in any trouble for that, it is true that we're not allowed to release an image containing it under CC-BY-SA. I guess if someone wants to remove the blender logo from the suzanne textures that would legally be the best thing to do, that's a little sad though

As for your third point, this is a little vague. While this is not a legal point, we have had contact with many of the projects from which the mascots come from and everyone we've talked to was okay with us using them. So I don't believe there is any real issue there so far.
