### ISSUE TITLE
How to disable nitrogen?

### ISSUE THREAD

**Issue by JasonJKi** [supertuxkart/stk-code#2903]
I was hoping to disable all form of boost and nitrogen from the race. Is there a line of code that I can control this feature?

**Comment by Arthur-D** [comment]
You can remove all nitro canisters from the tracks by opening each track's scene.xml file and removing the lines with nitro in them.

**Comment by qwertychouskie** [comment]
There is a way to disable the AI using Nitro in `stk_config.xml`.

**Comment by auriamg** [comment]
Apart from the manual mods mentionned above, I'm afraid there's no in-game option for that and none is planned at this time
