### ISSUE TITLE
Feature Request: Story Mode Cumulative Time Display

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#2907]
Hello, I would like to request a cumulative timer be added, to displayed after completion of story mode. Full game speedruns of this game are currently difficult to accurately time. Timing is currently done using external timers. Differences between loading times for different runners causes differences in the resulting time.

It could be displayed similar to the way that Grand Prix times are, but in the lower corner of that same window for a total story mode timer.

**Comment by qwertychouskie** [comment]
Random kinda-related note:  Load times have been dramatically reduced in STK git, does not completely fix the issue, but should help.

**Comment by auriamg** [comment]
This could indeed be interesting for highscores/etc. though I'm marking this as low priority because we have a lot of important things to do to keep us busy

**Comment by psypherium** [comment]
Partial implementation coded by Foulks availible here (Timer Mod) https://www.speedrun.com/stk/resources

**Comment by Alayan-stk-2** [comment]
Now that the F-Droid build exist, this is now the feature request with the most upvotes in the bug tracker.
