### ISSUE TITLE
Lighthouse track issue

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2910]
Ever since it was re-exported with the new file format, there's rocks in the middle of the road blocking the path

![lighthouse-2017 08 27_20 30 27](https://user-images.githubusercontent.com/4296971/29755480-aea3a8b6-8b66-11e7-81e8-f210117f5b4f.jpg)

**Comment by Benau** [comment]
Actually the .blend is not updated...., fixed

Let's hope no significant modification is done in between
