### ISSUE TITLE
Green valley : water missing

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#2911]
Since the track was re-exported, the waterfall and water on the ground are missing/weird in green valley

![greenvalley-2017 08 27_20 39 17](https://user-images.githubusercontent.com/4296971/29755558-f3cd7038-8b67-11e7-8352-4e38cf9a69d8.jpg)

**Comment by Benau** [comment]
You don't like the "displace" type water, otherwise I don't see what's wrong with it

**Comment by Benau** [comment]
Sorry the  for displace is indeed broken, now fixed.

So unless you don't like using displace in green valley, this can be closed

I don't think using displace shader for such simple track will cause slowdown, yet advanced pipeline-off fallback will just use a transparent shader
