### ISSUE TITLE
Camera not reset if falling into water does not happen

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2916]
When playing Cocoa Temple, on the bridge I almost fell down into the water, so the "falling into water" camera got activated. However since I did not actually fall into the water, my kart did not get reset and thus the camera did not get reset either. So the camera stuck in place while my kart could drive essentially out of camera. While a manual rescue resets the camera, it's a mild annoyance.

**Comment by Arthur-D** [comment]
Screenshot:
![cocoa_temple-falling_camera_no_reset](https://user-images.githubusercontent.com/5515261/29820038-597b2090-8cc3-11e7-80bf-df7877f17084.jpg)

**Comment by Arthur-D** [comment]
Reproduced twice in this video after a failed attempt. After the first of the successful attempts the camera did get reset reasonably fast but not as normal. The third attempt was the charm, and shows what happened to me when I reported the bug. Driving off into the distance like a lonely cowboy. :)

https://youtu.be/Wn8nwhIhLIE

**Comment by hiker** [comment]
Since we had this problem for a long time, it must be really rare, so postponing.

**Comment by Alayan-stk-2** [comment]
I just had it happening to me in Green Valley on the latest git. It's the first time I encounter the issue, so it definitely is rare, but it still can happen.

To be more precise, unlike in Arthur's video _I was auto-rescued_, but the camera was not reset after the rescue.

**Comment by Benau** [comment]
around kart.cpp:2051
```
        m_kart_gfx->updateTerrain(pk);

        for (unsigned i = 0; i < Camera::getNumCameras(); i++)
        {
            Camera *camera = Camera::getCamera(i);
            if (camera->getKart() != this) continue;
            if (camera->getMode() == Camera::CM_FALLING)
            {
                Log::info("","linpig");
                camera->setMode(Camera::CM_NORMAL);
            }
        }   // for i in all cameras for this kart
        return;
```
Not sure ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) or auria thinks that will fix it....

I cannot reproduce it at all, so I added a ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) logging, if you see that then it's fixed...

or maybe benau will just ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif) this commit anyway

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pigxm/cook_connect.gif)
