### ISSUE TITLE
Trees - Texture messed up

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2919]
![](http://i.imgur.com/dpuUg0y.png)

**Comment by qwertychouskie** [comment]
The weird thing is, it doesn't have the issue in Blender:
![](http://i.imgur.com/pQtWtPt.png)
Exporter issue?

**Comment by auriamg** [comment]
This is caused by the decimate modifier, the only proper fix I can see is to model LOD by hand instead of using the modifier
