### ISSUE TITLE
Winning/losing Animation for both Saras missing

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#2922]
I just noticed that the winning animation for sara-wizard is not not shown. Reason:
```
CAnimatedMeshSceneNode::setFrameLoop(s32 begin, s32 end)
{
   const s32 maxFrameCount = Mesh->getFrameCount() - 1;
   ...
   StartFrame = core::s32_clamp(begin, 0, maxFrameCount);
```
maxFrameCount is 128, but the start and end frames are 134 and 159 - so they get clamped away :(
That seems to be independent of spm or b3d format.

**Comment by Benau** [comment]
in sara the wizard .blend there is no keyframe for win / loose animation

**Comment by hiker** [comment]
I just checked again - there are markers in the animation, but no actual animation shown. So that means the exporter will contain the markers, stk will try to trigger animations, but nothing will happen.

Not sure what to do with this ticket - imho all karts in the main game should have win/lose animations. Otherwise - maybe remove the markers? Though that's not urgent anymore (now that #2628 is closed, which actually got triggered by the missing animations)

**Comment by Benau** [comment]
i meant the .blend contains marker, but no keyframes...

Anyway let me see if I can make sara to win / lose if I have some time...

**Comment by hiker** [comment]
Combined with #2420 - now we know it's not a bug in irrlicht or the exporter, but the animation is still missing in both Saras (just one has markers, so they will be exported, but there is no actual animation)

**Comment by Benau** [comment]
Both saras now have win lose animation, btw devee your static build works fine
