### ISSUE TITLE
STK - GPL3 or GPL3+?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#2923]
COPYING says that the license of the STK code is GPL3, but the headers of all the source files say GPL3+.  Which is correct?

Also see https://github.com/supertuxkart/stk-code/pull/2568

**Comment by Benau** [comment]
Sometimes things are subjectively correct, but an objective incorrect answered will be come up with due to your bad reputation

**Comment by hiker** [comment]
COPYING says GPL 2.0 and 3.0+, most files state 3.0, a few are still 2.0 (e.g. tinytext). So while we could think about upgrading the remaining 2.0 files, that's no problem.

**Comment by qwertychouskie** [comment]
Sorry, now looking back I mixed up the file's actual text and https://github.com/supertuxkart/stk-code/pull/2568#issuecomment-325843141. :whoops:
