### ISSUE TITLE
Rendering of Graphics to file 

### ISSUE THREAD

**Issue by JasonJKi** [supertuxkart/stk-code#2935]
Hello, 
I would like to save out the gameplay video. I was wondering if there is anyone has wrote a feature for recording the came play. If not, can someone guide me to the code on how the graphics are rendered to the screen?

Thank you in advance,
Jason

**Comment by qwertychouskie** [comment]
The current Git version has a built-in recorder, though you will have to compile it yourself.  See the readme for details.

**Comment by JasonJKi** [comment]
Oh alright thank you!
