### ISSUE TITLE
stk 0.9.1-3 on Mint 18.2

### ISSUE THREAD

**Issue by norricorp** [supertuxkart/stk-code#2937]
Hi,
I have installed on to Mint 18.2 (VM running in virtualbox) from repository.
If I start from command line, I get the following errors.
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[error  ] tinygettext: /usr/share/games/supertuxkart/data/po//en_GB.po line 2736 expected 'msgstr' or 'msgid_plural': ""
[error  ] tinygettext: /usr/share/games/supertuxkart/data/po//en_GB.po line 3793 expected empty line: "msgstr "Launchpad Contributions:\nAndi Chandler https://launchpad.net/~bing\nMichael Torpey https://launchpad.net/~mctorpey\nSTK-team https://launchpad.net/~stk""
Adding language fallback en
[warn   ] tinygettext: no.po: warning: ignoring, unknown language
[warn   ] tinygettext: no_NO.po: warning: ignoring, unknown language
[error  ] tinygettext: /usr/share/games/supertuxkart/data/po//en_GB.po line 2736 expected 'msgstr' or 'msgid_plural': ""
[error  ] tinygettext: /usr/share/games/supertuxkart/data/po//en_GB.po line 3793 expected empty line: "msgstr "Launchpad Contributions:\nAndi Chandler https://launchpad.net/~bing\nMichael Torpey https://launchpad.net/~mctorpey\nSTK-team https://launchpad.net/~stk""
Irrlicht Engine version 1.8.0
Linux 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64
OpenGL Warning: glXChooseVisual: bad attrib=0x186a0, ignoring
OpenGL Warning: glXChooseVisual: bad attrib=0x186a1, ignoring
Segmentation fault

I do have STK on Mint 16 in a VM and it works fine.
Is there a problem with newer Linux?

Regards

**Comment by auriamg** [comment]
Hi,

can you try tunning STK in gdb to capture a stack trace?

```
gdb supertuxkart
run
... make stk crash ...
bt
````

However, please note that running STK in a VM may not work correctly because 3D rendering / GPU use in VirtualBox is unstable

**Comment by qwertychouskie** [comment]
Also 0.9.1 is not the latest version, 0.9.2 is.

https://launchpad.net/~stk/+archive/ubuntu/dev

**Comment by norricorp** [comment]
I will get a stack trace.
Before that I will create a mint 18.2 VM in VMware and try the game with that to see if the problem is virtualbox.
Yes, I agree that it is not the latest but it is the version in the Ubuntu repository.

**Comment by norricorp** [comment]
So I tested with mint 18.2 in VMware, added vmtools to get 3d acceleration and the games runs but graphics are all over the place.
As has been said, not the latest version so perhaps the Ubuntu repo should be updated?
Or perhaps there is a problem with the new kernel?

**Comment by auriamg** [comment]
You can download the latest version from our website.
Driver issues are possible, I think VMWare has better support than Vbox but still I'm not sure it's fully stable, VMs are generally not meant for gaming, little we can do about that

**Comment by norricorp** [comment]
Have done various combinations. All on the same PC running host as windows 10
VMware / mint 16 / game 0.81-2 from repo: runs properly
VMware / mint 18.2 / game 0.91 from repo: does not run properly
VMware / mint 18.2 / game 0.92 from download: does not run properly.

The problems with Mint 18.2 may be because it is more demanding that Mint 16. Also graphics drivers are not installed by default (or at least can be skipped during install) so have to be installed afterwards if skipped.

Finally, in the download section, "Full game (.tar.xz). Includes 32-bit and 64-bit binaries. Extract and run run_supertuxkart.sh, which will automatically detect your architecture. ". There is no such file in the tar. There is run_game.sh which runs the game but does not install it as the repo does.

**Comment by deveee** [comment]
I sometimes run STK on Win7 using virtualbox, but I have to use force_legacy_device to make it working. I wouldn't really care if it doesn't work on VM. You can try real installation, i.e. using livecd/usb.

**Comment by auriamg** [comment]
STK 0.8 uses an older version of OpenGL so it makes sense that it would work.
I am going to close this ticket because there's really little we can do, it's just that VMs have limited OpenGL features. If you find a bug in a non-VM installation, please open a new ticket
