### ISSUE TITLE
Unable to steer left while looking backwards and accelerating

### ISSUE THREAD

**Issue by amtkhdkr** [supertuxkart/stk-code#2938]
I cannot steer left when looking backwards and accelerating. If I stop accelerating (but still looking back) then steering works fine.
Attached log with arguments "--keyboard-debug -R"
The only input I gave for approximately 15 seconds was "B + left arrow + up arrow"
Using latest git compiled on VS2017, Win10 Anniversary Update, wireless keyboard (Logitech mk260r), 1920x1080

[stdout.zip](https://github.com/supertuxkart/stk-code/files/1308581/stdout.zip)

Note that this is *not* reproducible when:
1.  (forward facing camera) steering left or right
2. (forward facing camera) accelerating + steering left or right
3. (backward facing camera) steering left or right
4. (backward facing camera) accelerating + steering right

Only problematic when:
1. (backward camera) accelerating + steering left

**Comment by qwertychouskie** [comment]
This sounds like a keyboard issue, see https://supertuxkart.net/FAQ.

**Comment by amtkhdkr** [comment]
Interesting, so if,suppose, my keyboard is not able to send out 3 keys correctly then why would a keyboard limitation only show up when (B + left + up) combination is used and not on (B + right + up)?

**Comment by qwertychouskie** [comment]
See https://www.sjbaker.org/wiki/index.php?title=Keyboards_Are_Evil

**Comment by auriamg** [comment]
Indeed, this is almost certainly a physical limitation of your keyboard. Your solutions include trying to find a different key binding that works better, or switch to a gamer's keyboard or a gamepad
