### ISSUE TITLE
Kart not fully rest in ground

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2939]
Benau: hiker1 1 more bug I would like to be fixed... current the kart_model update use m_speed to determine backpedal animation
Benau: and if the kart is sliding, it will negative
Benau: and cause wilber / suzanne / hexley "shaking" when idle
Benau: when you turn the kart
Benau: do you have a better suggestion instead of using m_speed from kart
hiker1: OK, open a ticket :)
Benau: possible to get from controller?
hiker1: Well, I would need to check why it is negative
hiker1: From memory: m_speed is length of linear velocity
hiker1: and then computes the angle to find if it's forwards or backwards
Benau: actually even on flat ground when you stop the kart it sometimes doesn't know how to fully "rest"
hiker1: Yes, that's a known issue ... that maybe I should address :P
hiker1: Karts actually slide a little bit at start time

**Comment by hiker** [comment]
Do you have an example when this happens? I assume you mean at start? Which kart, which track, which position?

**Comment by hiker** [comment]
In d7f5fb9e691439db6548415ad03e2975517085ea most of the flicker was removed (it still happens in some rare circumstances based on some variation in the physics numbers). @Benau , is this good enough?
If not, can you try the additional patch:
```
--- a/src/karts/kart.cpp
+++ b/src/karts/kart.cpp
@@ -2896,7 +2896,8 @@ void Kart::updateGraphics(float dt, const Vec3& offset_xyz,

     // m_speed*dt is the distance the kart has moved, which determines
     // how much the wheels need to rotate.
-    m_kart_model->update(dt, m_speed*dt, getSteerPercent(), m_speed, lean_height);
+    m_kart_model->update(dt, m_smoothed_speed*dt, getSteerPercent(),
+                          m_smoothed_speed, lean_height);

     // Determine the shadow position from the terrain Y position. This
     // leaves the shadow on the ground even if the kart is jumping because

```

Thanks!

**Comment by Benau** [comment]
Actually i found out if the wheels are shaking when the kart is idling, the back animation will shake too.

Unfortunately, those patches don't work me, there is still shaking. (maybe I have a high fps ~110 related?)

But if it takes too much time to dig into physics and find out the real reason, maybe we just use those hacks and release anyway, and find out the real cause later.

**Comment by hiker** [comment]
Hmm - could be. Perhaps try to limit the fps, but then again I have 105 as well.

Where do you see the problem? I am only trying kiki in soccer field. I might commit some debug code if  I can't reproduce the issue. I see it for a frame or two very rarely (say once or twice when I try to reproduce the problem, while previously it would happen more or less instantly :(

**Comment by Benau** [comment]
https://streamable.com/qgnoe
(already limit to 60fps)
What I meant "wheels shaking" is that, this happens for me ~80% of time, just start accelerate, stop, and when the kart stop the wheel has ~80% of time shaking.
