### ISSUE TITLE
Races are very dark again (since mesa update from 17.1.8-2 to 17.2.1-3)

### ISSUE THREAD

**Issue by cbxd** [supertuxkart/stk-code#2944]
Hi all,

Last April I opened a ticket about races being too dark to be playable. See ticket #2830 .
Well it has been happening once again since my Arch Linux system upgraded to mesa 17.2 branch.

Unfortunately, removing the version number in

`/usr/share/supertuxkart/data/graphical_restrictions.xml`
at line
`disable="FramebufferSRGBCapable"`
does not work this time.

I do not really know what to do to get STK working with mesa's latest version, even after reading mesa's changelog.

For now, the only workaround I have found is to stick to mesa version 17.1.8-2.

Do you have any ideas? It will be very appreciated.

Best regards,
Chris

**Comment by cbxd** [comment]
Forgot to mention: my STK version is 0.9.2 running on Arch Linux x86_64 with Linux 4.12 kernel, and intel i915 (using kernel DRM, not the intel video driver). Using the intel video driver does not solve the issue.

**Comment by deveee** [comment]
Current git STK should work (the crash on startup has been fixed).

Or you can use this patch for mesa:
https://lists.freedesktop.org/archives/mesa-dev/2017-September/169979.html
I hope that it will be merged soon.


2017-09-26 22:15 GMT+02:00 Christophe Bricheux-Duchossois <
notifications@github.com>:

**Comment by cbxd** [comment]
Ok, thanks a lot. I'll wait for the patch to be merged then!
Best regards,
Chris

**Comment by deveee** [comment]
In addition to above, current git STK should fallback to the path without srgb-capable framebuffer when our workaround failed. Or in worst case it's possible to manually disable it with
```
<card contains="Intel" os="linux" disable="FramebufferSRGB"/>
```
So it seems that there is nothing more we can do.
