### ISSUE TITLE
Find a way to have alternate kart (and add a purpose to easter egg mode)

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#2946]
Add a way to have variation of our karts (like same characters but slightly different kart/parameters/speed/etc).

It would allow to add more features/things to unlock. You could imagine to be able to unlock this with the Easter egg hunt mode, or by fighting in arenas (currently arenas nor eggs hunt aren't included in the story mode)

Of course it would be optional

**Comment by psypherium** [comment]
I think this is a great idea. It would also be nice to have an option to select a kart color tint, like in soccer mode with the red and blue, but for regular races. maybe even more colors.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/commit/bb0cf72635a9afdfd967686bb42766d2b42ab1db
Kiki the real color painter
https://streamable.com/6q5iz

btw @auriamg do you understand why sometimes some events are "lost"?
also after closing the dialog stk seems to miss some mouse hovering events / looks like hang
and is my stkgui correct?

**Comment by Benau** [comment]
branch merged
