### ISSUE TITLE
Karts in gpwin scene are barely visible

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2947]
Not sure if I'm blind, but the karts in new gpwin scene are IMO barely visible. They are very small in windowed mode and it's even worse on hi-dpi screens (for example my tablet that is 10'' and 1920x1200).

I think that the karts should be most important part of the scene. Maybe at least dynamically move the camera closer to the karts?

**Comment by deveee** [comment]
To be clear, on 1280x720 resolution, Xue is just an 48x48 icon:
![xue](https://user-images.githubusercontent.com/5108558/31034516-bb9efd14-a564-11e7-86c3-804e65d7ca4e.png)

**Comment by Benau** [comment]
https://www.youtube.com/watch?v=xq24QPM6F3c&feature=youtu.be&t=3326

Yes, watch it in youtube (imagine the youtube screen is the phone screen)

Maybe I can re-do a brand-new scene.....

**Comment by auriamg** [comment]
...or just zoom in the camera a bit

**Comment by auriamg** [comment]
Fixed in svn
