### ISSUE TITLE
Tiny Graphical Issue at 1440p

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#2949]
![screenshot at 2017-10-01 11-39-33](https://user-images.githubusercontent.com/12213882/31050678-e81bbf46-a69d-11e7-928c-55f122f2c04b.png)

There is a tiny line running through the screen under the main menu buttons when using 1440p.

**Comment by qwertychouskie** [comment]
Is this with "force_legacy_pipeline" enabled?

**Comment by psypherium** [comment]
Oh, I'm just running 0.9.2, I'm not building from source. I guess it's probably fixed in the latest code. Sorry to be a bother.

**Comment by qwertychouskie** [comment]
No problem.  I have some PPAs to make it easier:

https://launchpad.net/~stk/+archive/ubuntu/daily
https://code.launchpad.net/~asdfghrbljzmkd/+archive/ubuntu/stk-test

**Comment by psypherium** [comment]
I have now built it from these instructions https://github.com/supertuxkart/stk-code and i still see the issue. I didn't use any extra flags in the compile so i don't think "force_legacy_device" is enabled.

By the way, Cocoa temple runs like an absolute dream on this build, I can't wait for this code to go gold.

**Comment by qwertychouskie** [comment]
OK.  Do you have any sort of High-DPI scaling enabled?  If so, does the issue go away when disabled?

**Comment by psypherium** [comment]
I don't remember manually changing any DPI settings. Everything looks smaller on here compared to the 1080p screen next to it, so I don't think anything has been applied automatically either. It might be a strange driver idiosyncrasy, I'll try it with AMDGPU-PRO and see if the result is the same. 
By the way, is Candela City going to be added to story mode?

**Comment by psypherium** [comment]
I've built it on Ubuntu now, and the same problem. An AMD driver problem I think?

**Comment by deveee** [comment]
I don't think it's a driver problem. Maybe a minor issue in GUI engine. I sometimes see this line too, but atm. I don't know if it's related to some particular resolutions, non-hd textures or something other (I never looked at this).

**Comment by Benau** [comment]
@psypherium retry?
And i wonder if devee wanna pick this commit in 093 branch....

**Comment by psypherium** [comment]
Built and tested, it's fixed. Nice work. :1st_place_medal:
