### ISSUE TITLE
Feature Request: New Game+

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#2950]
It would be really cool if one could re-play the Story Mode with Supertux difficulty as an option.

**Comment by kompowiec** [comment]
u mad?
https://www.speedrun.com/saves/save_n6vtt.zip

**Comment by Benau** [comment]
I think he meant all challenges which will have a supertux option to be played with (currently only 3 options)

**Comment by kompowiec** [comment]
Yes, the above mentioned link it's save:
"Unlock all races **(SuperTux option is avaliable)** file unzip and you throw in [...] "

**Comment by Benau** [comment]
...maybe deveee can translate to polish .............
