### ISSUE TITLE
Hacienda track/challenge not feasible

### ISSUE THREAD

**Issue by krisovice** [supertuxkart/stk-code#2951]
It is impossible to win the challenge in easy mode (finish the track in 3:40), even with tons of nitro and speed ups and without driving faults.

**Comment by psypherium** [comment]
Disclaimer: I am not a dev, just a random guy. Hello, What version are you running? What kind of hardware are you running on? Maybe you are losing too many frames and having your time impacted. Here's an example of this challenge: https://youtu.be/-hY87h1Yc7c?t=1626 I hope you have a nice day.

**Comment by deveee** [comment]
I just tried Hacienda on easy and I have 2:48, so it's certainly feasible. But I can't really say if it's good for beginners.

**Comment by psypherium** [comment]
I just re-watched that vid i posted and noticed it was a 3:32. I think maybe it is a bit difficult. Hacienda with no drifting gives a 3:41. Also, try "Around the Lighthouse" on expert, it's harder than the final boss.

**Comment by krisovice** [comment]
Hi! Thanks for your prompt responses. I was running v 0.91 on mac os 10.12.16 i7 8GB and tried various screen resolutions and detail preferences when facing the issue, but it seems to be fixed with v 0.92, which I just installed.

**Comment by auriamg** [comment]
Actually, you were initially right, the hacienda challenge is much harder than intended for that difficulty level. I've ajusted it
