### ISSUE TITLE
Cannot upload add-on with .spm files

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2952]
Probably should go stk-addons bug tracker, but I'm not sure if people actually read it.

It looks that .spm files are not recognized:
```
Some invalid files were found in the uploaded add-on. These files have been removed from the archive: another_soccer_field_track.spm, invisible_wall.spm, pilka_track.spm, soccer_ball.spm, SomeModel2.spm, SomeModel.spm, stklib_jungleTree_b_main.spm, stklib_pinetree_a_lod_med.spm, stklib_redParrot_a_mainstklib_redParrot_a_main.spm
```

**Comment by deveee** [comment]
And another thing is that soccer fields are inside tracks category. Maybe they should go to arenas.

**Comment by auriamg** [comment]
Turns out the list of allowed extensions can be configured through the UI so that should work now

There is some code in there that actually reads the contents of the B3D, replacing that with a SPM parser should happen eventually.

**Comment by leyyin** [comment]
@deveee I actually muted this repo and I get notifications only from the other repos (addons, stats).
Regarding the wrong category, the addon category can be changed just by changing the type in the `addons` table (this should be safe for tracks <-> arenas).

@auriamg Please next time when you modify anything in the addons do a `git pull` on the server and do not make separate changes on the server :)
Also there are two branches:
- `master`
- `production` - the code on the server is based on this

I should probably update the README with some instructions regarding this.

Also everyone should check out the google doc that explains the STK servers infrastructure (it also contains some commands and instructions on how to do stuff like update code).

**Comment by hiker** [comment]
Most things are working now, the rest is not urgent and can be postponed.

**Comment by Benau** [comment]
Now leyyin merged my spm parser

**Comment by leyyin** [comment]
This is not in production btw, so not in the live version.

**Comment by leyyin** [comment]
It is live!
