### ISSUE TITLE
End cutscene is broken

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2955]
It works when you run cutscene from debug menu, but doesn't work when you actually finish fort magma challenge.

In first case it looks ok:
![zrzut ekranu z 2017-10-11 23-19-21](https://user-images.githubusercontent.com/5108558/31467650-00582ce4-aedb-11e7-9ed9-7b301ee814d1.png)

But in second case Gnu is still behind the wall:
![zrzut ekranu z 2017-10-11 23-18-12](https://user-images.githubusercontent.com/5108558/31467669-159fa6e0-aedb-11e7-8387-bb582714a226.png)

**Comment by auriamg** [comment]
I have been unable to reproduce this issue so far

**Comment by deveee** [comment]
It's reproducible for me on three different devices. I finished it on easy difficulty, but as far as I see it shouldn't matter.

Btw. Fortmagma on easy difficulty seems a bit hard. Not sure if it's intended, but I had to use a lot of skidding/nitro to win it.

**Comment by deveee** [comment]
Just an idea, maybe some materials overwrite default face culling during the race? Because it's the inner side of the wall that hides Gnu and normally it should be transparent.

**Comment by deveee** [comment]
Adding a 
```
<material name="castelwall.jpg" backface-culling="Y"/>
```
or just
```
<material name="castelwall.jpg"/>
``` 
to endcutscene/materials.xml solves the issue for me. But I don't think that it's possible to override a material with backface-culling=Y in exporter.

I will look for proper solution later, or you can do it yourself if you want.

**Comment by auriamg** [comment]
The bigger question is that the settings from fort magma appear to be still active, maybe the previous track isn't cleaned up correctly

**Comment by auriamg** [comment]
The immediate issue is fixed in SVN, I justed enabled back backface culling in fort magma. Ideally, we should find why material properties were not respected though

**Comment by deveee** [comment]
If you can't reproduce it, then maybe you have cache-overworld=false?

Anyway are you ok with removing backface-culling=N from castelwall.jpg material in overworld? It's only visible when you are inside the castle.

**Comment by auriamg** [comment]
no I was able to reproduce it, though I thought it was related to fort magma, not the overworld. That makes more sense - I have changed it in svn, should fix the issue?

**Comment by deveee** [comment]
It works for me now
