### ISSUE TITLE
Clarify that animated scenery is needed for particles

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#2956]
I found that if Animated Scenery is off, particles are no longer shown. While this is probably logical from a programmer's perspective, a user might regard Animated Scenery as purely animations of trees waving etc. Therefore it would be good to clarify that it's needed, but we are now in a string freeze so this will probably have to wait until after the 0.9.3 release.

**Comment by hiker** [comment]
I would actually say that the code needs to be changed so that particles are not affected by that setting anymore.

**Comment by qwertychouskie** [comment]
Or split it into two options:  "Particles", which has all, important only, and disabled; and "Animated Scenery", which is a checkbox.  Though @Benau mentioned that after his work on the engine, animated objects may perform the same as non-animated ones, so the option could just be renamed to "Particles" in that case.

**Comment by Benau** [comment]
Fixed by SP
