### ISSUE TITLE
Kart particles in multiplayer are not displayed correctly

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2960]
Strange things happen:
https://youtu.be/KGCUIadnSWo

Both GL/GLES behave the same.

**Comment by Benau** [comment]
cannot reproduce in amd and intel

**Comment by deveee** [comment]
It happens for me only on intel (I tried mesa git version too). I can't reproduce it on nvidia and with software rendering.

It happens for me since cpu particles were introduced. Previous commit works fine.

And actually it works when I add glFlush() at the end of CPUParticleManager::drawAll() function, or when I move m_draw_calls.setFenceSync(); below render particles (not sure if it's correct).

**Comment by deveee** [comment]
Actually it may have a sense, correct me if I'm wrong. First we prepare data for first player in uploadAll(), then we draw it in drawAll(). And then we have to wait until draw is finished before using uploadAll() for second player. Otherwise it may break data for first player because of memcpy(ptr,...) if drawing is not finished yet. And something like this happens.

**Comment by Benau** [comment]
well if it's working for you just git commit!

**Comment by deveee** [comment]
Ok, commited. Not sure if you want to optimize it, for example only if num_players > 1 or separate date for each player... For me there is no difference in performance on intel hd4000.
