### ISSUE TITLE
Normal race without time requirement has timers

### ISSUE THREAD

**Issue by AVerteC** [supertuxkart/stk-code#2962]
In the singleplayer campaign, Normal Races with the requirements showing 

- Required Rank 
- number of AI Karts 

and not showing

- Required Time

have a timer when racing the track. I'm not sure if this is intended.

**Comment by auriamg** [comment]
You mean on the overworld where you select challenges? I can't reproduce this issue
![overworld-2017 10 21_20 39 59](https://user-images.githubusercontent.com/4296971/31857018-3058f51e-b6a0-11e7-94a4-d3c9d0674574.jpg)

**Comment by AVerteC** [comment]
https://user-images.githubusercontent.com/8883261/31857084-e87e334c-b688-11e7-8a00-3f098785ba13.png

**Comment by auriamg** [comment]
Not all challenges have time requirements, this particular challenge simply has no time limit
