### ISSUE TITLE
Crash on Mac after Update to High Sierra (v. 10.13)

### ISSUE THREAD

**Issue by sirdis** [supertuxkart/stk-code#2963]
Hi,
after updating my Mac to High Sierra (v. 10.13) Supertuxkart crashes on startup (I never get to see the stk application window). Here is what I've done so far (to no effect).

- removed the app I had (though it was the current 0.9.2) and installed a freshly downloaded one
- completely removed the settings at ~/Library/Application Support/SuperTuxKart
- checked for OS-updates (none so far)
- searched for this bug on the internet (not found anything)

I attach the OS crash report and stk's log file. Take a look at the end of the crash report file for the computer's model and graphics information.

[stdout.log](https://github.com/supertuxkart/stk-code/files/1404332/stdout.log)
[crashreport.txt](https://github.com/supertuxkart/stk-code/files/1404334/crashreport.txt)

If there is anything more I can contribute with, please let me know.

Thanks so very much for any help,
sirdis

**Comment by Benau** [comment]
I quite surprise that mipmap generation will crash

**Comment by sirdis** [comment]
I just installed supertuxkart 0.9.3 rc-1. Now it works and I immediately let my lunch burn ;-)
So, either someone fixed the issue or it went away due to other changes. Whatever - I'm happy now. Thanks for the good game!
sirdis
