### ISSUE TITLE
Maybe Time Bomb "No Tagbacks" should expire after 2 to 4 seconds

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2973]
When someone "tags" you with a timebomb, you can't give it back to that person; you have to target somebody else. In case no one else is near, I suggest making the No Tagbacks rule expire after a short period. After a few seconds, the timebomb is able to return to sender if you touch the person who tagged you. The other person can have a good chance to escape, but you can have a fighting chance of not getting stuck with a bomb.

**Comment by Alayan-stk-2** [comment]
Adding an expiration time would complicate code, add sync issues in networking, add uncertainty (when do the time during which you can't pass the bomb back end ? The AI would be able to know, but even when looking at the bomb's clock, the player won't really be able to).

In most cases, you'll either have a third kart you can try to pass the bomb to, enough opportunity to avoid receiving the bomb in the first place, or some time to get a swatter or bubble shield to remove the bomb.
