### ISSUE TITLE
Switching from Windowed to Fullscreen hangs Windows 10

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2974]
1. I installed and ran STK 0.9.3-rc1 and was impressed by the improved load times.
2. I went to options and switched it from 1024x768 windowed to 1366x768 fullscreen.
3. The game attempted to switch. But mid-switch, the OS froze, my desktop wallpaper still showing. A process with an empty icon was in my taskbar.
4. The menu music continued to play, even after I closed the lid on my laptop.
5. I had to do a hard shutdown by holding the power button.

SPECS:
Acer Aspire ES 15 ES1-572-321G
Intel Core i3-7100U, HD Graphics 620
Windows 10 1703
[stdout.log](https://github.com/supertuxkart/stk-code/files/1424655/stdout.log)
(I started playing again an hour or two after the hang, which is why it has gameplay info in it later on 😅)

**Comment by auriamg** [comment]
I cannot reproduce this issue on my own Windows 10 computer, so this will be hard to fix (it may be dependent on your drivers for instance)

**Comment by Alayan-stk-2** [comment]
Not enough info to do anything.
