### ISSUE TITLE
Novice AI karts tend to have bombs on them more often than hard AI

### ISSUE THREAD

**Issue by n3rdopolis** [supertuxkart/stk-code#2981]
Hi

So I am testing in novice on the Android version, as I get used to the touch controls...
One thing I noticed is that since the AI tends to run into bananas more often, it increases the chance that there is a bomb ticking on them. (noticing it mostly on the Barnyard one where there are more bananas in the path)

IMHO, this introduces a different aspect of difficulty. There is a more likelihood that there is a larger penalty if the player accidentally drifts into an AI kart, and they are more likely to have a bomb on them, it will pass to the player more often.

I would suggest maybe reducing the probability that when a novice AI kart crashes into a banana of them getting the bomb powerdown a bit. (that is if the powerdown is decided when the kart comes in contact with the banana, vs when the banana spawns in)

Thanks

**Comment by Alayan-stk-2** [comment]
The karts in the novice and medium difficulty don't actively try to pass bombs to other karts. It only tries do so in expert and SuperTux.

So even if they have bombs more often in lower difficulties, I doubt this makes things much more difficult ?

**Comment by n3rdopolis** [comment]
It makes it  harder for the player to pass the AI karts, since if they graze into an AI kart, with a bomb on it, while passing with nitro, or a zipper, they now have the bomb. And since AI karts in novice don't avoid bananas as much as harder levels, they are more likely to have a bomb

**Comment by Alayan-stk-2** [comment]
Sure, sometimes, if the player drives badly (it is his own fault in the first place to not take some margin when overtaking a kart with a bomb), he will get a bomb from the AI kart.

Admittedly, a novice is expected to not drive well, but in the end his inputs still matter. The one taking care to avoid touching AI karts with a bomb deserve to have an easier time than the one who doesn't.

Often, too, the AI kart will not pass the bomb on anybody, will explode, and will lose time. So, assuming the novice will lose a little time by getting bombs from AI, on average he will lose less time than if the AIs had not hit a banana at all each time they got a bomb.

Making the banana behavior different depending on difficulty, and making it different between humans and AI, creates additional complexity, breaks rule uniformity between humans/AI ; all which is unwarranted for such a minor difference.

I'll also note that rubberbanding has been tweaked and that in novice, AI karts will begin to slow down when they are still several seconds behind the player. Assuming that novice was too hard in the first place, this should have a much more significant impact than any tweak to bananas and bombs.
