### ISSUE TITLE
Path search problem

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2982]
Hi,  
    just launch 0.9.3-rc1(launched run_game.sh into the supertuxkart-0.9.3-rc1-linux from cli and gui) and i got karts in double, tracks in double in the list.

It happens that i had a old stk-assets at the same level of supertuxkart-0.9.3-rc1-linux… so moving one of the directory elsewhere removed the double. But it seems that the is some problem in the search path ?

![double_karts](https://user-images.githubusercontent.com/2879782/32142395-df7ecaea-bc96-11e7-8664-3fafdba77cf8.png)

![double_track](https://user-images.githubusercontent.com/2879782/32142402-f33a1bc0-bc96-11e7-9fe3-b45872dbefec.png)

**Comment by Benau** [comment]
Elephpant should be dead anyway without double?
0.9.2 assets got mixed up?

**Comment by rogue-spectre** [comment]
Yeah moving the directory elsewhere Elephant not here, old konqi neither…

**Comment by deveee** [comment]
As I see when it finds ```./data``` directory, it shouldn't check other locations. The only possibility is that you may have ```../../stk-assets```,  ```../../supertuxkart-assets```, or defined SUPERTUXKART_ROOT_PATH environment variable.

**Comment by rogue-spectre** [comment]
No SUPERTUXKART_ROOT_PATH given by env command…

**Comment by deveee** [comment]
Ok, so I will add the SUPERTUXKART_ASSETS_PATH that can overwrite the ```../../stk-assets``` and will set it in run_game script.

And it may happen on Windows too, but it's less likely, because probably nobody has stk-code in Program Files.

**Comment by deveee** [comment]
Now it should be enough to set 
```
export SUPERTUXKART_DATADIR=.
export SUPERTUXKART_ASSETS_DIR=./data/
```
so I will add it to the script for final release.
