### ISSUE TITLE
Candela ShortCut Idea

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2984]
In candela city the gear is not solid… making it solid (+ maybe a little wider) + adding little ramps to be able to catch up the track would add a nice and not so easy "shortcut".

![idea_shortcut](https://user-images.githubusercontent.com/2879782/32142599-c5822a66-bc9a-11e7-9035-cc9b08b6369a.png)

**Comment by Benau** [comment]
Can u post issue per track please? In 2983
