### ISSUE TITLE
Las dunas, zippers not working

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#2985]
0.9.3-rc1

Yellow zippers in Battle map Las dunas are not working… (for now there are working on others tracks)

![accel_not_working](https://user-images.githubusercontent.com/2879782/32142701-f67eedf0-bc9c-11e7-95ec-b04cf99e62a1.png)

**Comment by Benau** [comment]
Zipper is already working, see the nitro jumping platform

For the others I think it will just make you more likely to lose control than fun, especially there is no absolute direction in arena, and samuncle didn't put "booster_alphaTest" material below those checker anyway

**Comment by qwertychouskie** [comment]
@Benau The zipper on the jump is iffy though, if the kart moves to slowly or to quickly it doesn't work, also it is a bit too powerful IMO.
