### ISSUE TITLE
Put the Android version on F-Droid

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#2987]
Since there is now an Android version available, a lot of people would appreciate, if they could get it via F-Droid. In fact this has been one of the top comments on the reddit discussions about the Halloween Update.

Would you include this app in F-Droid? And in case you don't want to do it yourself, would you mind if I submitted it for inclusion? I know the license permits this, but F-Droid explicitly wants to know if the authors support the inclusion.

**Comment by deveee** [comment]
Some work has been already done by Boris Kraut:
https://f-droid.org/wiki/page/org.supertuxkart.stk
https://gitlab.com/fdroid/rfp/issues/98

But he doesn't contribute to F-Droid anymore, so I don't know if they are still interested to put STK there.

**Comment by rugk** [comment]
Any news here? [This issue is the most upvoted issue](https://github.com/supertuxkart/stk-code/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) in this repo, so people seem to want this. :smile: 

(Also being on F-Droid is also always some advertisement for the game.)

**Comment by Benau** [comment]
done https://f-droid.org/en/packages/org.supertuxkart.stk/
