### ISSUE TITLE
[Bug] Weird hidden third button on Failed Challenge menu takes you back to Race Setup?

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2991]
1. Failed a challenge in Story Mode
2. The option to go back to the overworld was selected. (#2988)
3. With the XBOX 360 joystick, I pressed down. Nothing appeared to be selected.
4. Pressed down again, and the selection wrapped around (?) back to Restart, which is the top button.
5. Pressed down to select "Go back to overworld" (or whatever it's called) again
6. Repeated step 3, confused
7. Pressed Confirm (A) when nothing appeared to be selected, and I ended up at the Race Setup menu, where you choose a game mode and difficulty.
8. Clicked the back arrow. This took me to the Main Menu.
Perhaps there's a hidden third button somewhere doing that? My screen was Windowed, 1280x720. I'm on Windows 10.

**Comment by auriamg** [comment]
Fixed by recent pull request
