### ISSUE TITLE
[Polishing] Fade In/Out Transition between Loading Screens

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2992]
I've been playing this game for a long time and I'm really excited about how well it's coming together. One relatively minor feature that could go a long way in enhancing the "Feel" of the game is a fade-to-black transition between the menus and the in-game racing environment.

To explain how it could work, I'm assuming the "Loading..." screen is a scene that the program jumps to whenever an environment needs to load. This scene could be modified so that instead of showing a background, icon, and text, it does the following:
1. Takes a screenshot of the game and blits it onto the screen
2. Prints "Loading..." in the corner in white
3. Quickly fades the screenshot to black

Code would also be added to the in-game racing environment so that it always fades from black when the race or the overworld starts. Other than the Loading text disappearing, the result is a seamless transition.

**Comment by auriamg** [comment]
Yes, we could improve the loading screens, but considering we are a very small team in dire need of manpower and we have much more important features to do (like network support), this very minor and unimportant request simply will not fit in our timeline. Also, it could be argued that the fade in/out will just make the loading screen longer. So no, this is not something we plan to do at this time

**Comment by qwertychouskie** [comment]
@kryptot7 Yeah, the GUI definitely needs more transitions.  Unfortunately, the current GUI engine is very limited, so seemingly simple things, like transitions, are actually quite complex, and each transition used has to be hard-coded. :(  Hopefully someday STK will get a better GUI engine (libCEF-based would be awesome, [just look at these buttons in all of their transition-filled glory!](https://jacobspctuneup.tk/STK/newgui/buttondemo.html)), but until then, STK will probably have very few animations in the GUI.
