### ISSUE TITLE
Boost sound is a bit underwhelming (Solution included)

### ISSUE THREAD

**Issue by kryptot7** [supertuxkart/stk-code#2993]
The cartoonish "whoop!" noise that triggers when you use a boost item is a bit underwhelming. Fortunately, I found a much more fitting one here, and it's Public Domain.
http://soundbible.com/1794-Missle-Launch.html

**Comment by tobyplowy** [comment]
@kryptot7 i made this sound by combining some sounds in the sfx folder its not super good but it may help :D
[sound.zip](https://github.com/supertuxkart/stk-code/files/1425482/sound.zip)

**Comment by auriamg** [comment]
Maybe, but I'm not convinced by those sounds. The one in the original post is too long / to slow, a gameplay sound needs to be fast. Not quit sure about tobyplowy's version either, there's probably a way to make something more polished

**Comment by tobyplowy** [comment]
@auriamg I will give it another try

**Comment by tobyplowy** [comment]
@auriamg how about this?
[boost sound.zip](https://github.com/supertuxkart/stk-code/files/1425574/boost.sound.zip)
im more of a 3d modler and texture artist than a sound designer but i do agree with @kryptot7 the current boost sound is underwelming (also its a bit out of place)

**Comment by tobyplowy** [comment]
@auriamg how about this?
[boost sound.zip](https://github.com/supertuxkart/stk-code/files/1425574/boost.sound.zip)
im more of a 3d modler and texture artist than a sound designer but i do agree with @kryptot7 the current boost sound is underwelming (also its a bit out of place)

**Comment by auriamg** [comment]
I'm not an audio design expert either, but I must say I'm not quite convinced, the sound is quite "hard", almost sounds like a hard collision

**Comment by tobyplowy** [comment]
@auriamg maybe the nitro sound or a modefied version of it should I try again?

Abit offtopic (but I don't think it's worth opening an issue for it) I whant to help is there some texture/model work I can do

**Comment by tobyplowy** [comment]
@auriamg maybe the nitro sound or a modefied version of it should I try again?

Abit offtopic (but I don't think it's worth opening an issue for it) I whant to help is there some texture/model work I can do

**Comment by auriamg** [comment]
Anyway, since this is not a bug, github is not quite the right place for this. Maybe move this to the forum? In any case, we're not quite convinced by the suggested replacements, more 'professional' sounds would be preferred
