### ISSUE TITLE
Bowling ball does not always hit

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#2996]
E.g. in the old mine:

1. Stand still with face to a wall
1. Throw a bowling ball against the wall
1. Drive and touch the bowling ball
1. Result: The bowling ball changes its direction (physics work), but you don't get penalized/hit (no idea how I should call this ;) )

This happened to me very often when trying (> 50%).
A guess would be that it is somehow dependent on the speed of the kart, if I drive faster, I get hit.

**Comment by nado** [comment]
Have you tried against yourself or against other karts ? There's some kind of time limit during which you cant be hit by your own balls iirc.

**Comment by Flakebi** [comment]
Against myself only, seems a bit long then.

**Comment by hiker** [comment]
You can't hit yourself.
