### ISSUE TITLE
Countdown timer appearing on timeless challenge

### ISSUE THREAD

**Issue by tobyplowy** [supertuxkart/stk-code#2997]
![naamloos](https://user-images.githubusercontent.com/16853304/32202364-765fa916-bddc-11e7-9fe5-96397288c0ad.png)
this one is inposible to win on all dificultys

on easy the clock runs out just when i start the second lap

and on hard i get past halfway the second lap 

and on normal its inbetween the above

and im playing very good becouse the ai karts are very far away

![naamloos](https://user-images.githubusercontent.com/16853304/32203216-2170f0c6-bde2-11e7-9291-56b5e2ff5f3b.png)
this one is to hard to win on normal and hard,

i just need 10 seconds more to win (keep in mind that im playing extremly well and if i keep trying i will probably get there but for kids this wuld be inposible to win)

im still playing the storymode so i will probably find more inpisible levels

**Comment by tobyplowy** [comment]
@auriamg am I missing something or am I just playing bad?

**Comment by auriamg** [comment]
@tobyplowy I am not quite sure what you mean about the volcan island challenge because this challenge is not timed? You just need to be first, there is no time limit. I agree with the "normal" abyss challenge, will tweak it a bit. Not sure about the hard challenge yet, it's fine that hard is hard ;)

**Comment by tobyplowy** [comment]
> because this challenge is not timed?

I'm not sure what happened there but you are correct sorry for the false report :/

**Comment by tobyplowy** [comment]
@auriamg I don't think I'm done yet :/

**Comment by kitokofox** [comment]
I feel that the story mode is completely possible on all difficulty levels.
YEs the hard missions are hard but for their own good. What you could do is
try the level in time attack to practice it a bit and come back to the
level; you can most certainly outrun the CPUs on pretty much any track if
you know what you're doing.

**Comment by tobyplowy** [comment]
@kitokofox I was probably not playing very well that night (it was very late and it was also a long day)
But now I can actually beat all the race tracks :/

**Comment by tobyplowy** [comment]
@auriamg @kitokofox I managed to Trigger The bug (and yes it's definitely a bug) Again
On Vulcan island and this time I got video to show you it (I'm uploading it to YouTube at the moment)

**Comment by tobyplowy** [comment]
@auriamg @kitokofox so here is the video that shows it in action
https://www.youtube.com/watch?v=HgPOJ0XI_1A&feature=youtu.be
(i can still win the race but that timer is odd)

04:00 you can see me play it on easy and the timer runs out before i can finish the race but there shuldent be a timer

**Comment by tobyplowy** [comment]
@auriamg can you reproduce it?

**Comment by auriamg** [comment]
I tried reproducing the issue the way you described, but I haven't managed to reproduce it so far. If someone manages to reproduce it, or have any more information, that woulkd be welcome

**Comment by tobyplowy** [comment]
@auriamg shuld I record all the stamps (It Will Take a lot of time to upload)

**Comment by auriamg** [comment]
I attempted a fix, I think that should be ok now. Are you able to build from git? If yes, a test would be welcome. If no, you can test again on the next release candidate or release and report back?

**Comment by tobyplowy** [comment]
> Are you able to build from git?

No

> you can test again on the next release candidate or release and report back?

Can you tell me if a new release is out in this issue so I can test it asap

**Comment by qwertychouskie** [comment]
@tobyplowy What OS are you on?  I may be able to provide a build.

**Comment by tobyplowy** [comment]
@qwertychouskie Windows 10

**Comment by qwertychouskie** [comment]
Let me see if I can make a build...

**Comment by tobyplowy** [comment]
@qwertychouskie ok thanks

**Comment by tobyplowy** [comment]
@qwertychouskie when can you give me the test build?
I whant to test it as fast as possible

**Comment by tobyplowy** [comment]
> Let me see if I can make a build...

So can you?

**Comment by qwertychouskie** [comment]
@tobyplowy https://jacobspctuneup.tk/STK/0.9.3-rc1.2.1.zip

Sorry for the delay.

Launch `supertuxkart.exe` in `stk-code\build\bin\`

**Comment by tobyplowy** [comment]
@qwertychouskie thanks
I will have a look in like half an hour from now :)

**Comment by qwertychouskie** [comment]
@tobyplowy Try:

1. Extract the files somewhere
2. Open File Explorer where you extracted them, then go to `stk-code/build/`
3. Hold shift and right-click in an empty area, then select "Open folder in Command Prompt"
4. in the command prompt, type `bin\supertuxkart.exe` and hit enter

**Comment by tobyplowy** [comment]
@qwertychouskie i get this

![naamloos](https://user-images.githubusercontent.com/16853304/32353490-f93ba240-c025-11e7-8074-e6daadd5143a.png)

**Comment by qwertychouskie** [comment]
@tobyplowy Try `.\bin\supertuxkart.exe` instead.

**Comment by tobyplowy** [comment]
![naamloos](https://user-images.githubusercontent.com/16853304/32356299-8abfb6da-c034-11e7-9ba6-31bbb8e0f5c8.png)

i tryed some other stuff aswell but still doesent work (i think you will have to re compile it)
cant you use the same one used for the ones here https://supertuxkart.net/Main_Page

**Comment by qwertychouskie** [comment]
Ah, I see, you opened the cmd window in the "bin" folder instead of the "build" folder, `cd ..\` should fix that.

**Comment by tobyplowy** [comment]
@qwertychouskie it cannot find the path

also i did the command prompt in the build folder and i get this
![naamloos](https://user-images.githubusercontent.com/16853304/32356464-85a7a1ca-c035-11e7-9c62-8e14cb3ad497.png)

i have no idea what im doing so i will probbably have to wait for a release

**Comment by tobyplowy** [comment]
@qwertychouskie can you give me somting to copy paste in the terminal in the E:\Program Files\0.9.3-rc1.2.1\stk-code\build derectory?

**Comment by qwertychouskie** [comment]
```
cd "E:\Program Files\0.9.3-rc1.2.1\stk-code\build"
.\bin\supertuxkart.exe
```

**Comment by tobyplowy** [comment]
@qwertychouskie yeh i just cant run the exe
(i think someting is wrong with the exe in the build you have given me)

(im probably really wasting your time so i think i will just wait for the next release)

**Comment by qwertychouskie** [comment]
@tobyplowy Can you post the contents of `%appdata%\supertuxkart\0.8.2\stdout.log` ?

**Comment by tobyplowy** [comment]
@qwertychouskie sure
file [stdout.log](https://github.com/supertuxkart/stk-code/files/1439816/stdout.log)
and text

[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: User directory is 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from 'data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'en_AU'.
[verbose  ] translation: Language 'English (Australia)'.
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: GeForce GTX 1070/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 385.69
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Draw Indirect Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Bindless Texture Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: ARB Multi Draw Indirect Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: ARB Geometry Shader 4 Present
[info   ] irr_driver: GLSL supported.
[info   ] Freetype Environment: Loading fonts...
[info   ] Freetype Environment: DPI for Normal Font is 29.
[info   ] Freetype Environment: DPI for Title Font is 72.
[info   ] Freetype Environment: DPI for Digit Font is 44.
[info   ] ScalableFont::loadTTF: Created 15 glyphs supporting 16 characters for high-res digits font Sigmar using 1 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 93 glyphs supporting 150 characters for bold title font Ubuntu using 2 glyph page(s).
[info   ] ScalableFont::loadTTF: Created 98 glyphs supporting 101 characters for normal font Ubuntu using 1 glyph page(s).
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : texturedquad.frag
[info   ] shader: Compiling shader : texturedquad.vert
[info   ] shader: Compiling shader : uniformcolortexturedquad.frag
[info   ] shader: Compiling shader : colortexturedquad.vert
[info   ] shader: Compiling shader : colortexturedquad.frag
[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
[warn   ] TrackManager: Track 'candela_city' is not supported by this binary, ignored. (Track is version 7, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'cornfield_crossing' is not supported by this binary, ignored. (Track is version 7, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'icy_soccer_field' is not supported by this binary, ignored. (Track is version 7, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'lasdunasarena' is not supported by this binary, ignored. (Track is version 7, this executable supports from 6 to 6).
[warn   ] TrackManager: Track 'mansion' is not supported by this binary, ignored. (Track is version 7, this executable supports from 6 to 6).
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[error  ] GrandPrixData: The Grand Prix file 'data/grandprix/3_tothemoonandback.grandprix' contains a track 'mansion' that does not exist
[error  ] GrandPrixManager: Ignoring Grand Prix data/grandprix/3_tothemoonandback.grandprix (Unknown track)

[info   ] GrandPrixManager: Loading Grand Prix files from C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/grandprix/
[info   ] addons: Using cached addons.xml.
[info   ] HTTPRequest: Downloading https://addons.supertuxkart.net/dl/images/32999604857af930517f49.png
[error  ] EventHandler: Error while loading kart 'Kiki':
[error  ] Irrlicht: Could not load mesh, file format seems to be unsupported: data/karts/kiki/kiki.spm
[error  ] Kart_Model: Problems loading mesh 'data/karts/kiki/kiki.spm' - kart 'kiki' willnot be available.
[error  ] [KartPropertiesManager]: Giving up loading 'data/karts/kiki/kart.xml': Cannot load kart models
[error  ] ChallengeData: Undefined or incorrect value for 'gp' in challenge file 'data/challenges/gp3.challenge'.
[warn   ] unlock_manager: An error occurred while loading challenge file 'data/challenges/gp3.challenge' : Undefined or incorrect value for 'gp' in challenge file 'data/challenges/gp3.challenge'. challenge will be ignored.
[error  ] ChallengeData: Undefined or incorrect value for 'track' in challenge file 'data/challenges/mansion.challenge'.
[warn   ] unlock_manager: An error occurred while loading challenge file 'data/challenges/mansion.challenge' : Undefined or incorrect value for 'track' in challenge file 'data/challenges/mansion.challenge'. challenge will be ignored.
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : object_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : objectref_pass1.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : normalmap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_object_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_objectref_pass1.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/encode_normal.frag
[info   ] shader: Compiling shader : instanced_normalmap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/DiffuseIBL.frag
[info   ] shader: Compiling shader : utils/SpecularIBL.frag
[info   ] shader: Compiling shader : IBL.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/SunMRP.frag
[info   ] shader: Compiling shader : sunlight.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlight.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : linearizedepth.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : ssao.frag
[info   ] shader: Compiling shader : bilateralH.comp
[info   ] shader: Compiling shader : bilateralV.comp
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : object_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : objectref_pass2.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : object_unlit.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : splatting.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : objectpass_spheremap.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : detailed_object_pass2.frag
[info   ] shader: Compiling shader : grass_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_objectref_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : instanced_object_unlit.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : instanced_objectpass_spheremap.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_object_pass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_detailed_object_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_grass.vert
[info   ] shader: Compiling shader : utils/getLightFactor.frag
[info   ] shader: Compiling shader : instanced_grass_pass2.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : glow_object.vert
[info   ] shader: Compiling shader : glow_object.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : glow.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparent.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : passthrough.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : tonemap.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_color1.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_blend2.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : mlaa_neigh3.frag
[verbose  ] RaceManager: Nb of karts=1, ghost karts:0 ai:0 players:1

[info   ] Singleton: Destroyed singleton.
[warn   ] AnimTexture: Did not find animate texture 'clouds.png'
[warn   ] AnimTexture: Did not find animate texture 'clouds.png'
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : importance_sampling_specular.frag
[info   ] shader: Compiling shader : shadow.vert
[info   ] shader: Compiling shader : shadow.frag
[info   ] shader: Compiling shader : shadow.vert
[info   ] shader: Compiling shader : shadowref.frag
[info   ] shader: Compiling shader : shadow_grass.vert
[info   ] shader: Compiling shader : instanced_shadowref.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanciedshadow.vert
[info   ] shader: Compiling shader : shadow.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanciedshadow.vert
[info   ] shader: Compiling shader : instanced_shadowref.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanciedgrassshadow.vert
[info   ] shader: Compiling shader : instanced_shadowref.frag
[info   ] shader: Compiling shader : rsm.vert
[info   ] shader: Compiling shader : rsm.frag
[info   ] shader: Compiling shader : rsm.vert
[info   ] shader: Compiling shader : splatting_rsm.frag
[info   ] shader: Compiling shader : utils/getworldmatrix.vert
[info   ] shader: Compiling shader : instanced_rsm.vert
[info   ] shader: Compiling shader : instanced_rsm.frag
[info   ] shader: Compiling shader : slicedscreenquad_nvworkaround.vert
[info   ] shader: Compiling shader : rhpassthrough.geom
[info   ] shader: Compiling shader : rh.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : gi.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/decodeNormal.frag
[info   ] shader: Compiling shader : utils/SpecularBRDF.frag
[info   ] shader: Compiling shader : utils/DiffuseBRDF.frag
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : utils/SunMRP.frag
[info   ] shader: Compiling shader : sunlightshadow.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : fog.frag
[info   ] shader: Compiling shader : sky.vert
[info   ] shader: Compiling shader : sky.frag
[info   ] shader: Compiling shader : pointlight.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : pointlightscatter.frag
[info   ] shader: Compiling shader : gaussian6v.comp
[info   ] shader: Compiling shader : gaussian6h.comp
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : transparentfog.frag
[info   ] shader: Compiling shader : displace.vert
[info   ] shader: Compiling shader : white.frag
[info   ] shader: Compiling shader : displace.vert
[info   ] shader: Compiling shader : displace.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : dof.frag
[info   ] shader: Compiling shader : object_pass.vert
[info   ] shader: Compiling shader : colorize.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : godfade.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : gaussian3v.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : gaussian3h.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : godray.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getCIEXYZ.frag
[info   ] shader: Compiling shader : utils/getRGBfromCIEXxy.frag
[info   ] shader: Compiling shader : bloom.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : gaussian6h.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : bloomblend.frag
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : lensblend.frag
[info   ] shader: Compiling shader : pointemitter.vert
[info   ] shader: Compiling shader : flipparticle.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : particle.frag
[info   ] shader: Compiling shader : particle.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : particle.frag
[info   ] shader: Compiling shader : primitive2dlist.vert
[info   ] shader: Compiling shader : transparent.frag
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 41
[warn   ] SFXManager: Throttling sfx - queue size 42
[warn   ] SFXManager: Throttling sfx - queue size 42
[warn   ] SFXManager: Throttling sfx - queue size 42
[info   ] shader: Compiling shader : screenquad.vert
[info   ] shader: Compiling shader : utils/getPosFromUVDepth.frag
[info   ] shader: Compiling shader : motion_blur.frag
[info   ] shader: Compiling shader : coloredquad.vert
[info   ] shader: Compiling shader : coloredquad.frag
[info   ] Singleton: Destroyed singleton.
[verbose  ] RaceManager: Nb of karts=1, ghost karts:0 ai:0 players:1

[info   ] Singleton: Destroyed singleton.

**Comment by qwertychouskie** [comment]
@tobyplowy Hmmm, it seems you have an issue with STK versions getting confused. Let's try this:

1. Make a backup of the `supertuxkart` folder in `%appdata%`
2. Uninstall any installed STK versions.  0.9.3-rc1 should show up in add/remove programs, but the button to remove 0.9.2 might only be in the start menu.
3. Delete any STK-related files and folders in `E:\Program Files\`, `E:\Program Files (x86)\`, `C:\Program Files\`, `C:\Program Files (x86)\`, etc.
4. Remove any STK-related environment variables, see <https://www.computerhope.com/issues/ch000549.htm>.  Specifically look for `SUPERTUXKART_ROOT_PATH` and `SUPERTUXKART_ASSETS_PATH`.
5. Reboot
6. Download https://jacobspctuneup.tk/STK/0.9.3-rc1.2.1.zip and extract it to a directory
7. Extract the files somewhere
8. Open File Explorer where you extracted them, then go to `stk-code/build/`
9. Hold shift and right-click in an empty area, then select "Open folder in Command Prompt"
10. In the command prompt, type `.\bin\supertuxkart.exe` and hit enter

**Comment by tobyplowy** [comment]
@qwertychouskie i did all that and i get this popping up in task managger for acopple seconds 
(like it did before)
![naamloos](https://user-images.githubusercontent.com/16853304/32373825-7f8a6406-c09b-11e7-8f5c-dfb6c2adf6b9.png)
windows probleemrapportage translates to windows problemreporter (or error reporter)

also i tryed removing C:\Users\toby1\AppData\Roaming\supertuxkart\0.8.2

and it makes those files again if i run the exe 
this is what the stdout.log
[info   ] UserConfig: Could not read user config file 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/config.xml'.  A new file will be created.
[info   ] [FileManager]: Data files will be fetched from: '../../data/'
[info   ] [FileManager]: Data files will be fetched from: '../../data/../../stk-assets/'
[info   ] [FileManager]: User directory is 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/../addons/'.
[info   ] [FileManager]: Screenshots will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in 'C:\Users\toby1\AppData\Roaming/supertuxkart/0.8.2/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../../data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/../../stk-assets/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../../data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../../data/po/'.

incase you need it heres the config
[config.zip](https://github.com/supertuxkart/stk-code/files/1441020/config.zip)

**Comment by auriamg** [comment]
@tobyplowy Please note that qwertychouskie's build are unnofficial, so we cannot garantee they work correctly. You could simply wait for the next official build, which shouln't be too far off

**Comment by tobyplowy** [comment]
> You could simply wait for the next official build, which shouln't be too far off

I will I think thats best also wasn't the next Stable release the steam release?

**Comment by qwertychouskie** [comment]
@tobyplowy https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3-rc1/supertuxkart-0.9.3-rc1-win64.exe/download contains the fix and is a regular installer, might work.

**Comment by tobyplowy** [comment]
@qwertychouskie I Can't Do It anymore so i think is fixed :)

**Comment by tobyplowy** [comment]
@qwertychouskie yip after trying it some more I can confirm that it doesn't happen Any More :)
