### ISSUE TITLE
[STK on Windows 10] Unable to turn left while using Nitro boost

### ISSUE THREAD

**Issue by darth-crunchus** [supertuxkart/stk-code#2998]
Yeah, thought I'd report this.  You can still turn right whilst hitting "Go Baby, Go!", but left turns are not possible.  That being said, thanks for all your hard work, devs!  This game has REALLY come a long waysince I started playing it back in 2009.

**Comment by deveee** [comment]
Maybe change default keys for stk 0.9.4? Turning left doesn't work on so many keyboards. I'm always using z/x/a/s for nitro/skidding/backwards/rescue and I never had any issues on simple keyboards.

**Comment by qwertychouskie** [comment]
@deveee I use x/c/v/space for skidding/lookback/nitro/item and it works amazingly keyboard-wise and gameplay-wise.  Binding rescue close to frequently-used keys might result in a lot of accidental rescues.

**Comment by auriamg** [comment]
This sounds like "Why don't some keyboard keys work when pressed simultaneously?" from our FAQ: https://supertuxkart.net/FAQ

This is probably a physical limitation of your keyboard, your options would be to use a gaming keyboard or a gamepad instead

**Comment by darth-crunchus** [comment]
Considering that STK is the only game on my pc that acts that way, it's not my keyboard.  I can use multiple keys simultaneously on every other game I own.

**Comment by hiker** [comment]
It's not that your keyboard can not handle any 2 or 3 independent key strokes, it is just that it can not handle some combinations of keystrokes at the same time - so if you can press several keys at once in other games, try assigning the same keys in stk. Or just try a different key to verify if this fixes the problem.

**Comment by qwertychouskie** [comment]
I think it has to do with these keys specifically.  I run into this too for the default config, but everything is fine when I change the keys.

**Comment by auriamg** [comment]
More info here : https://www.sjbaker.org/wiki/index.php?title=Keyboards_Are_Evil , we've had many similar reports and that always turns out to be the cause, there's nothing we can do

**Comment by qwertychouskie** [comment]
@auriamg Changing the default config would fix it for many keyboards though.

**Comment by auriamg** [comment]
The current default was actually specifically designed to try and minise those issues, but since not all keyboards have the same limitations, we have never found a config that would work on all keyboards
