### ISSUE TITLE
Setup New Race while in Story Mode takes you out of it

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#3004]
I see this as a rather pointless button to be there if you're in Story Mode. It should take you back to the world map instead.

**Comment by auriamg** [comment]
Ok but if you don't like what this button does, simply don't click on it? You can click on "Exit race" to return to the world map

Maybe we could have slightly better labels such as "return to world map" but we don't quite have enough screen space for such long labels

**Comment by kitokofox** [comment]
My point is that it's a little misleading, as it takes you out of story mode altogether, when if you're playing story mode, you're in it for the story challenges instead.

**Comment by tobyplowy** [comment]
> "Set up new race" sounds like "let's try another story challenge"

@auriamg I have to agree it does sound very confusing

**Comment by auriamg** [comment]
I did a few tweaks, should be clearer now
