### ISSUE TITLE
Las Dunas Arena - bugs

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3005]
Floating fence:

![](http://i.imgur.com/t1AkJxU.png)

Opening that shouldn't be open:

![](http://i.imgur.com/LCmUKwS.png)

The giant tire is a ghost tire:

![](http://i.imgur.com/akydnzW.png)

**Comment by Benau** [comment]
I'm animating the wilber security.... I can do it altogether...
