### ISSUE TITLE
Multiplayer lan difficulty based on local single difficulty

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#3006]
Hi, 
We tried stk 0.9.3-rc1 over local lan with multiple players.
We made a few parties were we noticed that some of the players had a lower max speed than the others, so the parties were biased. We solved the problem by checking the difficulty set on single player mode and as we suspected the max speed on multi-player lan mode was depending on the one set in single player mode. So having the same single mode difficulty let us play in multi-player with the same max speed. So the difficulty set in multi-player lan mode has no effect, since we turned the single difficulty to hard and multi-player lan difficulty to easy and the speed was the one related to the hard level.

**Comment by qwertychouskie** [comment]
Actually multiplayer wasn't even supposed to be accessible as it is not complete.  The GUI has since been hidden in the 0.9.3 branch.

https://github.com/supertuxkart/stk-code/commits/0.9.3-rc1

**Comment by auriamg** [comment]
Right, closing this bug, everything under "Networking" is known to be unfinished
