### ISSUE TITLE
Nolok kart has story-mode power ups in normal races

### ISSUE THREAD

**Issue by n3rdopolis** [supertuxkart/stk-code#3016]
Hi

I am not sure if it is intentional or not, but it seems Nolok has the special different powerups in races that the Nolok kart is in, (instead of them being in only final race in story mode)

Thanks

**Comment by auriamg** [comment]
Yes this is intentional, and this is cosmetic only, they are not more powerful than their 'vanilla' equivalents. It's just "nolok's personal touch"
