### ISSUE TITLE
Oliver's Math Class 

### ISSUE THREAD

**Issue by bebehei** [supertuxkart/stk-code#3018]
When taking the "elevator" in Oliver's Math Class at the desk, you'll always get thrown against the pencil with your cart, rendering this part of the track unusable. It would be much better to drive through the pencil or have an additional ruler laying on it and building a ramp.

![screenshot from 2017-11-05 15-07-40](https://user-images.githubusercontent.com/2073458/32415529-55f6217e-c23b-11e7-8556-0ac89a174e37.png)

![screenshot from 2017-11-05 15-08-45](https://user-images.githubusercontent.com/2073458/32415528-55d8bc60-c23b-11e7-8311-e31652fde1fe.png)

Version: Installed via AUR `supertuxkart-git` version `17972+17321-1`. (When retrieving the version info, I found out this is quite old for git. So I rebuilt, but it's still reproducible.)

**Comment by Benau** [comment]
This is for easter egg hunt

Maybe auria wanna use scripting to hide the ruler in the first place if not easter mode....

**Comment by auriamg** [comment]
Benau that sounds like the simplest and best solution indeed

**Comment by Benau** [comment]
Done
