### ISSUE TITLE
Cannon on Cornfield Crossing

### ISSUE THREAD

**Issue by bebehei** [supertuxkart/stk-code#3021]
When jumping with the cannon on Cornfield Crossing, every Kart gets braked after landing on the top floor of the house. Until you drive down the ramp, the maximum achievable speed is the approximately half of the Kart's top speed. There is no difference if you had been boosted while entering the cannon or not.

Interestingly, If you don't enter the cannon with full speed, you'll also drive at the top floor that same speed.

I understand, that the cannon has a speed neutralizing effect. But I don't see, why there is a need to drive on the top floor with reduced speed. For the track, this part makes less fun.

**Comment by auriamg** [comment]
Actually, it is so because otherwise the karts would collide and crash in the steep downhill part right next after. So maybe it's not perfect, but considering our current physics engine, this is as good as it's going to get for now
