### ISSUE TITLE
Android: dialog to choose between touch and accelerometer input

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#3023]
From looking at various blog posts/comments it seems like a lot of people don't know they can choose to race with accelerometer input with the Android version. I suggest to add a dialog at first start where you can choose between the two input methods, and which also informs that you can switch input in options and change sensitivity etc for the accelerometer.

The downside is that we already have one dialog at first start, and adding more could be seen as nagging, but this would only apply to the Android version and I think most people would like to know both touch and accelerometer steering is available.

**Comment by Mrxx99** [comment]
I think this can be closed as this was fixed by @deveee 's commit https://github.com/supertuxkart/stk-code/commit/8f78d4e8913f854bc776aaed9efd52a88595821c and is live in the suptertuxkart beta on google play
