### ISSUE TITLE
i found some boundary breaks and some bugs 

### ISSUE THREAD

**Issue by tobyplowy** [supertuxkart/stk-code#3024]
NOTE some of these (if not all) may alredy be known also im using the latest stable from the website ;D

i found a copple of out of bounds bugs (thet means i can acsess areas i shuld not be able to)
also some skips and orther ood stuff 

i have a video to show all of it and showing how to reproduce (becouse explaining it wuld be inposible or extreemly hard)
https://www.youtube.com/watch?v=pM4j9ahIVgo&feature=youtu.be
im trying to find more and if i do another video will be uploaded

**Comment by tobyplowy** [comment]
It's also a completely fresh install I have no mods installed
(That's why I got the skidding achievement XD)

**Comment by Benau** [comment]
The rc 0.9.3 has corrected most rescue / track bug, yet you are using 0.9.2

**Comment by tobyplowy** [comment]
@Benau how do I get 0.9.3?

Also I spend like an hour and a half edeting that video :/

**Comment by tobyplowy** [comment]
@Benau it's not only rescue bugs there's other bugs shown in this video aswell you probably don't even watch the whole video!

**Comment by deveee** [comment]
The difference between 0.9.2 and 0.9.3-rc1 is a one and a half year of work. From what I see it's ~2000 commits in stk-code and ~400 commits in stk-assets. I hope that you understand that 0.9.2 is not best possible version for testing.

**Comment by tobyplowy** [comment]
@deveee Yes sorry I just wanted to help
I will try to get the newer version

Again I'm really sorry
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3-rc1/
Are this the newest versions shuld I test these?

**Comment by qwertychouskie** [comment]
In Cocoa Temple, the sticky walls, the bug under the river, and the "limbo" bug have been fixed, though the bridge collision shape is still weird, the gear still has no collision, and that texture seam is still there.  Northern Resort has the house fixed, though the shortcut is still available.  Gran Paradiso still lets you on the runway, and the shortcut is still unnatural.  Lighthouse still has the invisible walls and the missing fence posts, though the "weeeeee" is fixed (better physics in 0.9.3).  I didn't test Blackhill Mansion,  but it probably still needs fixing.  (Also see https://www.youtube.com/watch?v=TNGbVD1uSe4 for a similar thing in Nessie's Pond.)

**Comment by qwertychouskie** [comment]
@tobyplowy And yes, those are the newest files.

**Comment by auriamg** [comment]
@tobyplowy Yes it's always important to use the latest version, but maybe next time go for the bigger issues that most players can encounter and not necessarily as much emphasis on carefully designed procedures to break the game if you're trying really hard

**Comment by tobyplowy** [comment]
@auriamg  The Invisible Walls are very annoying and very unnatural
Why not do the thing Where If You hit an Invisible Wall you go through it but the camera stays behind but the kart keeps moving (not too far) and than gets picked up by the bird just as If You Were driving of the bringe with the odd hitbox and hitting the water

Also Why are the fence bars floating o.0

**Comment by auriamg** [comment]
I agree about invisible walls that are too close, and for more recent tracks I try to encourage samuncle to put them a bit further and to add visible obstacles too. For the fences, agreed, this a real little issue and a separate ticket could be opened (maybe a ticket per track could be opened, for "easy-to-encounter" issues)

**Comment by tobyplowy** [comment]
@auriamg so shuld i Take all the stuff I reported in the Above video and just make new issues for Every level?

**Comment by auriamg** [comment]
@tobyplowy Only the most important ones (leave out those where you need to be actively trying to break the game by purposefuly going off track, please), and those that haven't yet been fixe in 0.9.3 please. We're a small team so we don't always have the time for all the little details, so let's just go for the main important  ones and not all the little nitpicking please

**Comment by tobyplowy** [comment]
@auriamg ok
