### ISSUE TITLE
Follow the Leader with 0 CPUs Doesn't Work

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#3026]
![supertuxkart_2017-11-09_02-32-33](https://user-images.githubusercontent.com/11599732/32593662-bdc5b5d6-c4f6-11e7-9d1b-2769acb2c652.jpg)
![supertuxkart_2017-11-09_02-33-25](https://user-images.githubusercontent.com/11599732/32593671-c40e20f4-c4f6-11e7-814e-3b168f73543b.jpg)
You get softlocked after you get eliminated.

**Comment by kitokofox** [comment]
More info:

You can get a 0 CPU Follow the Leader race by picking 0 CPUs on another mode, then picking Follow the Leader, and choosing Gran Prix mode

**Comment by kitokofox** [comment]
https://puu.sh/yi4t9/2c78ef0363.png Also just got this crash when force-closing it.

**Comment by deveee** [comment]
It should be fixed now: https://github.com/supertuxkart/stk-code/commit/165b2fea9cd34abe35c2f76d7d05d07f559b3c31

But you can probably still force some strange behavior when you run single track in follow the leader with 4 players. It depends if spinner widget can have negative value, I didn't check.

**Comment by deveee** [comment]
Ok, should be fixed too.
