### ISSUE TITLE
in around the light house there are several floating fences

### ISSUE THREAD

**Issue by tobyplowy** [supertuxkart/stk-code#3028]
the title says it all :D
here are pictures of them
1
![lighthouse-2017 11 09_15 02 49](https://user-images.githubusercontent.com/16853304/32609519-47ef9182-c560-11e7-8fef-62cecfef0b98.png)
2
![lighthouse-2017 11 09_15 02 55](https://user-images.githubusercontent.com/16853304/32609520-48111f46-c560-11e7-9514-1781fc7dfb94.png)
3
![lighthouse-2017 11 09_15 03 03](https://user-images.githubusercontent.com/16853304/32609521-48291470-c560-11e7-9bff-6f093314481e.png)
4
![lighthouse-2017 11 09_15 03 34](https://user-images.githubusercontent.com/16853304/32609522-4840b3dc-c560-11e7-8d64-af760a6e1abd.png)
5
![lighthouse-2017 11 09_15 03 39](https://user-images.githubusercontent.com/16853304/32609523-48aa70a6-c560-11e7-8e1b-f1c1ca1faebe.png)

**Comment by MTres19** [comment]
Fixed in SVN (revisions 17443 and 17444).
