### ISSUE TITLE
[feature request] "be the first" race mode

### ISSUE THREAD

**Issue by mattia-b89** [supertuxkart/stk-code#3029]
"be the first" is a new way of race: you win if you are, or better stay, in the first position for at least one lap.
this means the race has no lap and could be an infinte-lap
PS: laps number in which a player win could be a custom value...

**Comment by auriamg** [comment]
Hi, maybe, though we have no plans for such a mode at this time. Please note that github tickets are meant for bug reports, whereas this is more of a feature wish, which are usually better suited for the forum. So we will keep this in mind, but we are a small team with limited time and have many more urgent tasks to work on and as such there is no plan for new modes at this time

**Comment by mattia-b89** [comment]
Thank you

On 10 Nov 2017 01:57, "auriamg" <notifications@github.com> wrote:

Hi, maybe, though we have no plans for such a mode at this time. Please
note that github tickets are meant for bug reports, whereas this is more of
a feature wish, which are usually better suited for the forum. So we will
keep this in mind, but we are a small team with limited time and have many
more urgent tasks to work on and as such there is no plan for new modes at
this time

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/supertuxkart/stk-code/issues/3029#issuecomment-343341868>,
or mute the thread
