### ISSUE TITLE
"Droid" (kart)

### ISSUE THREAD

**Issue by Symbian9** [supertuxkart/stk-code#3031]
Since Android now is supported OS, it would be cool add to preinstalled add-ons kart for "Droid" (or "Robot") as mascot of Android platform.
* https://en.wikipedia.org/wiki/Droid_(robot)#Trademark_use

I found that there was some "Android" kart, but it was now unavailiable and marked as buggy
* http://stkaddons.net/karts/android

So, as for me, need create some simple and good looking "Android" kart befote release of STK `v0.9.3`.

As start point propose concept of Android maskot on skate:

![Android mascot on skate](http://cdn.trendblog.net/wp-content/uploads/2013/06/white-android-logo_00039624.jpg)

Main color (sRGB): `164, 198, 57`
* https://en.m.wikipedia.org/wiki/Android_green

Here is 3D model (`.obj`) of "Android Robot" under terms of <a href="https://creativecommons.org/licenses/by/3.0/legalcode">CC-BY
3.0</a> license
* https://poly.google.com/view/9-bJ2cXrk8S
  * https://support.google.com/poly/answer/7418679

![Android Robot 3D](https://lh3.googleusercontent.com/FeNowFX1gMJpKkdOV0c2k3fePGEkzRcWfHXP549g3Tmfo79X89rVyR6F1iwRlU77)

P.S.: I would be happy to help make this model for STK ;-)

### REFERENCE
* https://www.wired.com/2010/10/android-robot-2/
* https://www.nytimes.com/2013/10/13/magazine/who-made-that-android-logo.html
* http://trendblog.net/the-story-of-the-android-logo/
* https://en.wikipedia.org/wiki/File:Android_robot_2014.svg
* https://android.stackexchange.com/questions/11400/what-are-the-names-of-the-various-versions-of-the-android-os-and-how-are-these

**Comment by auriamg** [comment]
Github should be used for bug reports, not feature requests. Please use the forum for feature requests

In the case of android, it is a brand owned by google ( https://developer.android.com/distribute/marketing-tools/brand-guidelines.html ) and comes with a lot of rules that make it probably hostile to use in a kart

**Comment by Symbian9** [comment]
> I'm no lawyer, but we generally just want to stay away from commercial products

"Android Logo" design defined as open-source by its author -- Irina Blok:
* http://www.irinablok.com/android
> The idea was to create the open source logo (very much like open source Android platform), that was released to the developer community without regular brand guidelines. Not unlike Linux Penguin, the logo helped to establish identity for the new product and generated excitement among engineers. Initially the logo was meant for developer community, but it quickly became consumer facing with millions of people creating their own versions of the logo every day.

So, there no any limitations on usage of its usage in STK or somewhere else.

**Comment by auriamg** [comment]
@Symbian9 as said above: "and even if legally it wasn't an issue, we wouldn't necessarily want to be doing publicity for google". STK is about having fun and colourful animals, not about promoting brands, I don't think we'd be comfortable including a commercial brand's logo even if it was legally possible

**Comment by Symbian9** [comment]
> commercial brand

Android Logo is opensource logo of Android community (see quote above). Can't understand why you  still call it commercial brand.

Where you see any commercial limitations on Android Logo?

**Comment by auriamg** [comment]
https://developer.android.com/legal.html

The "Android" name, the Android logo, and other trademarks are property of Google LLC
You may use the word "Android" in a product name only as a descriptor, such as "for Android" and the first instance should be followed by a TM symbol, "for Android™." In other messaging, the word "Android" may be used in text as a descriptor, as long as it is followed by a proper generic term (for example, "Android™ application"). Any use of the Android name must include footer attribution in your communications: "Android is a trademark of Google LLC."

**Comment by Symbian9** [comment]
Lets look inside
* https://developer.android.com/distribute/marketing-tools/brand-guidelines.html

I'm not propose use "Android" as name for such addon (I propose "Droid" or "Robot"), because if use *Android in text* then it has many limitations.

If use only graphical design of *Android robot* then there no any limitations, because its design licensed under CC-BY 3.0
> The green Android robot can be reproduced and/or modified as long as the following Creative Commons attribution line is included in the creative:
```
“The Android robot is reproduced or modified from work created and shared by Google and used according to terms described in the Creative Commons 3.0 Attribution License.”
```

Also, *Android logo* as brand is combination of *Android robot* and text `android` styled with *custom typeface*. I don't propose Android logo as brand!

**Comment by Symbian9** [comment]
> Any use of the Android name must include footer attribution in your communications: "Android is a trademark of Google LLC."

@auriamg, as just said above, *Android robot* (as graphics) is NOT trademark of Google
> Google retains all trademark rights to the Android robot.

**Comment by auriamg** [comment]
@Symbian9 Look drop it, okay? It's irrelevant. Maybe we can. Why _should_ we? We are not making this game to promote android or google products. Even if legally we _can_ (which I'm not quite sure of, I'd want a lawyer's advice first), we do not _want_ to. The android robot just doesn't fit in the STK universe, it does not fit with the other characters.

**Comment by Symbian9** [comment]
> The android robot just doesn't fit in the STK universe, it does not fit with the other characters

Really? I not agree with it, because *The Android robot* is mascot of open-source Android OS (AOSP) and it fit 
* https://supertuxkart.net/Making_Karts:_Ideas_and_Concept_Art
> **The Character**
> 
> First, choose a character. For SuperTuxKart, at least core STK, it should be a mascot related to some open-source software. ...
