### ISSUE TITLE
Badly adjusted playername for replays

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#3034]
The vertical adjustment of playername for replays is not very good. See attached screenshot. From looking at the screenshot, which of the replays would be Kitoko's?
![replay_username_badly_adjusted](https://user-images.githubusercontent.com/5515261/32681453-e0fce522-c66f-11e7-91a9-a15862a9a8c0.jpg)

**Comment by kitokofox** [comment]
Mine is the STK Enterprise replay with 122.967s
