### ISSUE TITLE
Multiplayer with multiple monitor

### ISSUE THREAD

**Issue by Oblomov** [supertuxkart/stk-code#3040]
This is an absolutely crazy idea, but let me throw it out there anyway.

On machines with multiple monitors, it'd be interesting to allow multiplayer by having multiple windows, one on each monitor.

I'm aware of the significant increase in computational power requirements, but with the right hardware this would allow nearly-network-like multiplayer on a local machine. And it might even be feasible (computationally-wise) on multi-GPU setups …

**Comment by Flakebi** [comment]
The idea is not that crazy actually: #1126

**Comment by Benau** [comment]
So duplicated

**Comment by Oblomov** [comment]
So apparently I fail at searching issues properly, but thanks 8-)
