### ISSUE TITLE
Fix typo in trailer

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3041]
There's a pretty obvious typo in the trailer:
'plateform'
that needs to be fixed before the 0.9.3 can be released.

**Comment by Benau** [comment]
https://transfer.sh/XdTDi/fix_1_st_scene_and_kiki.zip

Sam you can use this to fix the "light darken" in the 1st scene (for the stk dev team)

and non-moving-separated tail kiki jumping tail

**Comment by Benau** [comment]
![kiki_konqi](https://user-images.githubusercontent.com/3252341/32949776-f7d31694-cbde-11e7-9742-7ae258f77d5b.png)
not sure if auria / samuncle wanna use this as screenshot for 0.9.3...........

**Comment by Benau** [comment]
https://streamable.com/xwy2r
Animated version, auria wanna commit?
