### ISSUE TITLE
Forest near mountains in World Map is Inconsistent

### ISSUE THREAD

**Issue by kitokofox** [supertuxkart/stk-code#3044]
![supertuxkart_2017-11-14_10-51-08](https://user-images.githubusercontent.com/11599732/32789473-eb6bf2f2-c929-11e7-8d62-92deaeab902f.jpg)
Sometimes it uses actual geometry you can crash into, sometimes it doesn't. Sometimes it has texture mapped trees. Feels kind of strange to have all three types of tree in there.

**Comment by auriamg** [comment]
Yeah, we know the overworld has a lot of little issues, but it's unecessary to list them all individually as sooner or later the entire overworld map is going to be re-made. So we're not discarding the idea, it's just part of some bigger plan and this specific issue won't get fixed individually
