### ISSUE TITLE
Android: Look Back + Fire (on touch UI)

### ISSUE THREAD

**Issue by Symbian9** [supertuxkart/stk-code#3047]
Since there no easy way for "<kbd>Look Back</kbd> + <kbd>Fire</kbd>" during racing on Android devices with two-finger input, here is idea how this issue could be solved:
1. Press and Hold <kbd>Look Back</kbd> -- for keep look back;
2. Swipe Up to <kbd>Fire</kbd> (while Hold <kbd>Look-back</kbd>) -- for fire to back.

UPD: Also here is extended variant:
* Tap on <kbd>Fire</kbd> -- fire to front;
* Tap or Press and Hold <kbd>Look Back</kbd> -- for quick look back or keep look back;
* Press and Hold <kbd>Look Back</kbd> + Swipe Up to <kbd>Fire</kbd> -- for fire to back while keep look back;
* Press and Hold <kbd>Fire</kbd> + Swipe Down to <kbd>Look Back</kbd> -- for fire to back without look back.

P.S.: Some definitions on touch UI
* https://blog.mobiscroll.com/working-with-touch-events/
![Touch gestures](http://blog.mobiscroll.com/wp-content/uploads/slide-16-touch-gestures1.png)
* https://commons.m.wikimedia.org/wiki/File:Open_source_gesture_library.pdf#file

**Comment by a1batross** [comment]
+1 here.

**Comment by qwertychouskie** [comment]
Alternatively swiping down on the fire button to fire backwards might feel a bit more natural.

**Comment by Punkoivan** [comment]
Yes, one of this solution will be great.

**Comment by Symbian9** [comment]
> Alternatively swiping down on the fire button

Yes, why not ;-) Then additionaly need change buttons layout:
* Now we has
| <kbd>Fire</kbd> | <kbd>Nitro</kbd> |
| --- | --- |
<kbd>Look Back</kbd> and <kbd>Skidding</kbd>
* Need change to:
| <kbd>Look Back</kbd> | <kbd>Nitro</kbd> |
| --- | --- |
<kbd>Fire</kbd> and <kbd>Skidding</kbd>

**Comment by Punkoivan** [comment]
Why? Just "press" fire and swipe down to the "Look back" button.

**Comment by Symbian9** [comment]
> Why? Just "press" fire and swipe down to the "Look back" button.

Then need propper design actions:
* Tap on <kbd>Fire</kbd> -- fire to front;
* Tap or Press and Hold <kbd>Look Back</kbd> -- for quick look back or keep look back;
* Press and Hold <kbd>Look Back</kbd> + Swipe Up to <kbd>Look Back</kbd> -- for fire to back while keep look back;
* Press and Hold <kbd>Fire</kbd> + Swipe Down to <kbd>Look Back</kbd> -- for fire to back without look back.

**Comment by pelya** [comment]
Why not simply make 'Look Back' button a toggle, instead of holding it? These swiping gestures are not intuitive.

**Comment by Benau** [comment]
This is now possible:
1. Press and Hold <kbd>Look Back</kbd> -- for keep look back;
2. Swipe Up to <kbd>Fire</kbd> (while Hold <kbd>Look-back</kbd>) -- for fire to back.

And also true for all buttons (they have "linkage" now like your unlock screen pattern)
