### ISSUE TITLE
ALc.c:776: LockLists: Assertion `lockret == althrd_success' failed.

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3048]
Forwarded from Debian bug tracker: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873759

Package: supertuxkart
Version: 0.9.2+dfsg-2
Severity: important

Dear Maintainer,

A reliable one for once!

Whenever the addon level "On the Beach" (not the similarly-named level
"On The Beach" - note the 't'/'T') is chosen, STK aborts while loading
it.

$ coredumpctl gdb supertuxkart
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
           PID: 31702 (supertuxkart)
           UID: 1000 (ben)
           GID: 1000 (ben)
        Signal: 6 (ABRT)
     Timestamp: Wed 2017-08-30 12:30:31 PDT (4min 31s ago)
  Command Line: supertuxkart
    Executable: /usr/games/supertuxkart
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (ben)
       Boot ID: b567089063994f90b206df689d65a202
    Machine ID: a9f5005691f11289cd92098b52b4f3f9
      Hostname: joyplim
       Storage: /var/lib/systemd/coredump/core.supertuxkart.1000.b567089063994f90b206df689d65a202.31702.1504121431000000.lz4
       Message: Process 31702 (supertuxkart) of user 1000 dumped core.

                Stack trace of thread 31721:
                #0  0x00007f8e4e6fdfff __GI_raise (libc.so.6)
                #1  0x00007f8e4e6ff42a __GI_abort (libc.so.6)
                #2  0x00007f8e4e6f6e67 __assert_fail_base (libc.so.6)
                #3  0x00007f8e4e6f6f12 __GI___assert_fail (libc.so.6)
                #4  0x00007f8e50ef5ed3 n/a (libopenal.so.1)
                #5  0x00007f8e50f1227d n/a (libopenal.so.1)
                #6  0x00007f8e50efea98 alGetSourcei (libopenal.so.1)
                #7  0x000055fe5da0d0f3 _ZN14MusicOggStream6updateEv (supertuxkart)
                #8  0x000055fe5da0dce9 _ZN10SFXManager15reallyUpdateNowEPNS_10SFXCommandE (supertuxkart)
                #9  0x000055fe5da0ec46 _ZN10SFXManager8mainLoopEPv (supertuxkart)
                #10 0x00007f8e51c72494 start_thread (libpthread.so.0)
                #11 0x00007f8e4e7b3abf __clone (libc.so.6)

                Stack trace of thread 31707:
                #0  0x00007f8e4ec9be4e n/a (libgomp.so.1)
                #1  0x00007f8e4ec99898 n/a (libgomp.so.1)
                #2  0x00007f8e51c72494 start_thread (libpthread.so.0)
                #3  0x00007f8e4e7b3abf __clone (libc.so.6)

                Stack trace of thread 31708:
                #0  0x00007f8e4ec9be4e n/a (libgomp.so.1)
                #1  0x00007f8e4ec99898 n/a (libgomp.so.1)
                #2  0x00007f8e51c72494 start_thread (libpthread.so.0)
                #3  0x00007f8e4e7b3abf __clone (libc.so.6)

                Stack trace of thread 31709:
                #0  0x00007f8e4ec9be4e n/a (libgomp.so.1)
                #1  0x00007f8e4ec99898 n/a (libgomp.so.1)
                #2  0x00007f8e51c72494 start_thread (libpthread.so.0)
                #3  0x00007f8e4e7b3abf __clone (libc.so.6)

                Stack trace of thread 31710:
                #0  0x00007f8e51c7815f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x000055fe5dc5db2b _ZN6Online14RequestManager8mainLoopEPv (supertuxkart)
                #2  0x00007f8e51c72494 start_thread (libpthread.so.0)
                #3  0x00007f8e4e7b3abf __clone (libc.so.6)

                Stack trace of thread 31702:
                #0  0x00007f8e4656d77c n/a (libelf.so.1)

GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/games/supertuxkart...(no debugging symbols found)...done.
[New LWP 31721]
[New LWP 31707]
[New LWP 31708]
[New LWP 31709]
[New LWP 31710]
[New LWP 31702]
[New LWP 31715]
[New LWP 31716]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

warning: Could not find DWO CU gallivm/.libs/lp_bld_debug.dwo(0x705e1d0e169ca1fe) referenced by CU at offset 0x14078a9 [in module /usr/lib/debug/.build-id/62/a543423306e4787e29a78fbd94c9a2cdf8ff3d.debug]

warning: Could not find DWO CU gallivm/.libs/lp_bld_misc.dwo(0x3f68ad1a054cd591) referenced by CU at offset 0x1422424 [in module /usr/lib/debug/.build-id/62/a543423306e4787e29a78fbd94c9a2cdf8ff3d.debug]
Core was generated by `supertuxkart'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8e1d181700 (LWP 31721))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f8e4e6ff42a in __GI_abort () at abort.c:89
#2  0x00007f8e4e6f6e67 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f8e50f3c4a2 "lockret == althrd_success", file=file@entry=0x7f8e50f3e818 "/build/openal-soft-i1NYLO/openal-soft-1.17.2/Alc/ALc.c", 
    line=line@entry=776, function=function@entry=0x7f8e50f3f678 "LockLists") at assert.c:92
#3  0x00007f8e4e6f6f12 in __GI___assert_fail (assertion=0x7f8e50f3c4a2 "lockret == althrd_success", file=0x7f8e50f3e818 "/build/openal-soft-i1NYLO/openal-soft-1.17.2/Alc/ALc.c", line=776, function=0x7f8e50f3f678 "LockLists")
    at assert.c:101
#4  0x00007f8e50ef5ed3 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#5  0x00007f8e50f1227d in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#6  0x00007f8e50efea98 in alGetSourcei () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#7  0x000055fe5da0d0f3 in MusicOggStream::update() ()
#8  0x000055fe5da0dce9 in SFXManager::reallyUpdateNow(SFXManager::SFXCommand*) ()
#9  0x000055fe5da0ec46 in SFXManager::mainLoop(void*) ()
#10 0x00007f8e51c72494 in start_thread (arg=0x7f8e1d181700) at pthread_create.c:333
#11 0x00007f8e4e7b3abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

-- System Information:
Debian Release: buster/sid
  APT prefers testing-debug
  APT policy: (600, 'testing-debug'), (600, 'testing'), (500, 'unstable-debug'), (500, 'unstable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386, x32, arm64

Kernel: Linux 4.12.0-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages supertuxkart depends on:
ii  libbluetooth3             5.45-1
ii  libbz2-1.0                1.0.6-8.1
ii  libc6                     2.24-14
ii  libcurl3-gnutls           7.55.0-1
ii  libenet7                  1.3.12+ds-2+b1
ii  libfreetype6              2.8-0.2
ii  libfribidi0               0.19.7-1+b1
ii  libgcc1                   1:7.2.0-1
ii  libgl1-mesa-glx [libgl1]  13.0.6-1+b2
ii  libglu1-mesa [libglu1]    9.0.0-2.1
ii  libgomp1                  7.2.0-1
ii  libjpeg62-turbo           1:1.5.2-2
ii  libogg0                   1.3.2-1+b1
ii  libopenal1                1:1.17.2-4+b2
ii  libpng16-16               1.6.31-1
ii  libstdc++6                7.2.0-1
ii  libvorbis0a               1.3.5-4
ii  libvorbisfile3            1.3.5-4
ii  libx11-6                  2:1.6.4-3
ii  libxext6                  2:1.3.3-1+b2
ii  libxrandr2                2:1.5.1-1
ii  supertuxkart-data         0.9.2+dfsg-2
ii  zlib1g                    1:1.2.8.dfsg-5

supertuxkart recommends no packages.

supertuxkart suggests no packages.

-- no debconf information

**Comment by Alayan-stk-2** [comment]
I can't reproduce the old issue.

The crash mentioned in my own message above still existed, but a revision has now been pushed to the addon to fix the naming mismatch between the .b3d and the file the scene.xml is pointing at.
