### ISSUE TITLE
SuperTuxKart Loads opening and subsequent screens with colored blocks instead of readable type

### ISSUE THREAD

**Issue by LuigiWriter** [supertuxkart/stk-code#3049]
[I am using the issue Leslii opened Jan 4 #2720 as a Guide to try and give you as many answers in advance as I can.]
I have been playing SuperTuxKart 0.8.2 and have enjoyed it. 
0.8.2 works excellently in Windows 10 using Windows 8 compatibility.
Saw that SuperTuxKart 0.9.2  was available: 
### Here is what I did and the results
1. Downloaded the Windows supertuxkart-0.9.2.exe from:
	https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/supertuxkart-0.9.2.exe/download 
2. Installed 0.9.2
3. Loaded it and found it loads opening and subsequent screens with colored blocks instead of readable type [Game Mode screen?]
![stuxkart 9-2 10 er load w8 n 2017-11-15](https://user-images.githubusercontent.com/30986842/32883118-795c358a-ca84-11e7-8dc2-22bf22a013c5.png)

4. Clicking on blocks at the bottom leads to another screen [Type of Race?]
5. Clicking on blocks at the bottom leads to another screen [Possibly Kart Choice?]
![stuxkart 9-2 13 er ld freeze w8 n 2017-11-15](https://user-images.githubusercontent.com/30986842/32883193-afa8f29a-ca84-11e7-870d-d501a161ac73.png)

6. Only button which functions on this screen is [X] Exit.
7. I ran the Compatibility troubleshooter and setting compatibility to Windows 8  I received the same symptoms as in steps 3 – 6.
8. I tried several combinations including 

     1. Windows 7 and XT compatibilities.
     2. Windows 8 compatibility With
              1. Reduced color mode: 8-bit [256] color
              2. Override high DPI scaling behavior per “application”
              3. Disable full screen optimizations
              4. and even 640 x 480 screen resolution with 1 - 3
9. Searched Github and found only Issue #2720 which is similar but for Windows 7.
Now I hope you have some suggestions. As I do not know what changed between 0.8.2 and 0.9.2 that could be the cause.

### Operating System	Windows 10 Home 64-bit
	CPU	Intel Pentium P6100 @ 2.00GHz	43 °C
		Arrandale 32nm Technology
	RAM	3.00GB Dual-Channel DDR3 @ 532MHz (7-7-7-20)
	Motherboard	Intel Corp. Base Board Product Name (CPU)
	Graphics	Generic PnP Monitor (1366x768@60Hz)
		Intel HD Graphics (Toshiba)
	Storage	298GB TOSHIBA MK3265GSX (SATA)	33 °C
	Optical Drives	HL-DT-ST DVDRAM GT30F
	Audio	High Definition Audio Device
### Graphics
	Monitor	Name	Generic PnP Monitor on Intel HD Graphics
			Current Resolution	1366x768 pixels
			Work Resolution	1366x768 pixels
			State	Enabled, Primary
			Monitor Width	1366
			Monitor Height	768
			Monitor BPP	32 bits per pixel
			Monitor Frequency	60 Hz
			Device	\\.\DISPLAY1\Monitor0
	Intel HD Graphics
			Manufacturer	Intel
			Model	HD Graphics
			Device ID	8086-0046
			Revision	3
			Sub-vendor	 Toshiba (1179)
			Current Performance Level	Level 0
			Driver version	8.15.10.2900
				Count of performance levels : 1
					Level 1 - "Perf Level 0"

### From here consulting the Windows 7 Issue QnA I did the following:
1. Insured that the Windows 10 Latest Updates were installed 
2. Searched on line for newer Video driver but Driver version	8.15.10.2900 is latest. Per Intel and Microsoft.
Intel Corporation driver update for Intel(R) HD Graphics / Windows 10 and later upgrade & servicing drivers / Drivers (Video) / 11/26/2012 / 8.15.10.2900 / 26.0 MB
3. Found that it was already installed.
4. Tried Member Benau's suggestion made on Jan 4] 
       1. Could you try to set force_legacy_device parameter to "true" in config.xml file? It's just an idea, but maybe it creates OpenGL 3.1 context even if it doesn't really support it.
       2. I could not find “force_legacy_device” in either  config.xml and stk_config.xml and was careful that I was looking at the 0.9.2 versions.
       3. Also can you post your stdout.log there too? 
       4. This is the one generated by 9-2 found in \appdata\roaming\supertuxkart\ 
----------------------------------

[info   ] FileManager: Data files will be fetched from: ''
[info   ] FileManager: User directory is 'C:\Users\lui\AppData\Roaming/supertuxkart/'.
[info   ] FileManager: Addons files will be stored in 'C:\Users\lui\AppData\Roaming/supertuxkart/addons/'.
[info   ] FileManager: Screenshots will be stored in 'C:\Users\lui\AppData\Roaming/supertuxkart/screenshots/'.
[debug  ] translation: GetLocaleInfo langname returns 'en'.
[debug  ] translation: GetLocaleInfo tryname returns 'US'.
[debug  ] translation: Env var LANGUAGE = 'en_US'.
[debug  ] translation: Language 'English (United States)'.
[info   ] irr_driver: GLSL supported.
[warn   ] material: Track uses deprecated texture 'grass.jpg'

--------------------------------------------

5. There seems to be no comments on graphics unless irr_driver GLSL is pertinent.
6. Looked at the graphical_restrictions.xml file as suggested.

###  graphical_restrictions.xml

----------------------------------------

 `<?xml` version="1.0"?>`

 `<graphical-restrictions>`

   `<card` is="Intel(R) HD Graphics 3000" os="windows"                disable="UniformBufferObject"/>

   `<card` is="Intel(R) HD Graphics 3000" os="windows"                disable="AdvancedPipeline"/>

   `<card` is="Intel(R) HD Graphics 3000" os="windows"                disable="FramebufferSRGBWorking"/>

   `<card` contains="Intel"          os="osx"                         disable="GI"/>

   `<card` contains="Intel"                                           disable="TextureCompressionS3TC"/>

   `<card` contains="Intel"          os="windows"                     disable="HighDefinitionTextures"/>

  . . .

 `</graphical-restrictions>`

----------------------------------------

### Should any of these be changed or more added for the following Graphics Device?
Intel Model:	HD Graphics				
Manufacturer:	Intel
Device ID		8086-0046
Revision		3
Sub-vendor	 	Toshiba (1179)

I look forward to your questions and comments.
Thanks in advance for help.

**Comment by deveee** [comment]
It should be fixed in 0.9.3-rc1, you can try it.

And for 0.9.2 I don't remember if there was already possible to use ForceLegacyDevice in graphical_restrictions.xml, but you can at least change it in config.xml file.

Open %appdata%\supertuxkart\0.8.2\config.xml and change "force_legacy_device" to true.

But still I suggest to try 0.9.3, because legacy pipeline works much better there.

**Comment by LuigiWriter** [comment]
Thanks, Want to try  0.9.3-rc1 
Could you give me the address where I can download a windows version?

**Comment by deveee** [comment]
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3-rc1/

**Comment by LuigiWriter** [comment]
It Works! Sort of. small window only. 
full screen even with Win 8 compatibility freezes, cannot [alt]+[tab] to get out. have to do [ctrl]+[alt]+[del] and use task manager to end the process.
Wants OpenGL 3.1. Searched for any openGL driver for 
Intel HD Graphics
		Manufacturer	Intel
		Model	HD Graphics
		Device ID	8086-0046
and came up with none. from what I read this thing can only support OpenGL 1.1, perhaps 2.0. Ouch!
sounds like my options may be limited.

**Comment by LuigiWriter** [comment]
Also noticed all but 640x480 screen resolutions are grayed out in the display settings screen. 
Is this because of the OpenGL requirement not being met?
Or something else? 
Help me understand. I OpenGL something built into the graphics hardware, part of the firmware or something which, I saw the line "wraps around the graphic controller?"
After a freeze would a Windows dump file be a help. I have tried reading them and it is Turkish to me as the Greeks say.
Too many medical bills and too little income to just up and buy a new computer.
Thanks again for leading me to a new version I could sample.

**Comment by deveee** [comment]
This bug happened because ironlake generation of intel graphics cards in theory should be able to use OpenGL 3.x. I already saw a comment that someone hacked mesa drivers and was able to run STK with GL 3.1 on this hardware. Probably there is a bug in intel drivers for windows and it reports that GL 3.1 context was successfully created, but then it reports that it has only GL 2.1, so everything is messed.

You can't use GL 3.x renderer, because your graphics card doesn't really support it (or intel drivers don't support it). But as I said GL 2.1 fallback works fine in STK 0.9.3, it just has worse graphics.

STK works for me on ironlake Intel HD Graphics on Win7. But tbh. drivers for these graphics cards are very old and I don't think that Win10 is supported. This may be a reason that fullscreen causes a freeze for you.

I don't really understand what is the problem with resolutions? You mean that you can only use 640x480 and you can't select any other resolution? STK officially supports resolutions >= 1024x768, because for lower resolutions some GUI elements may look wrong. And typically 640x480 shouldn't be in the config screen at all. You can try to manually change it from terminal using ```supertuxkart.exe --screensize=1024x768``` or in ```%appdata%\supertuxkart\0.8.2\config.xml``` file.

**Comment by LuigiWriter** [comment]
supertuxkart.exe --screensize=1024x768 on 0.9.3-rc1 did the trick
the graphics option screen I get now is very different from the one I was getting when it was opening in  640x480 where putting an X in the full screen box meant getting a black screen, then, the Windows message "This program has stopped working"

Without 3.1 it must as you say drop to 2.1 but graphics are very improved over 0.8
Get normal screens [no distortion].
Get a choice of all the screen sizes including 1366x768 which I selected and it saved somewhere, since that information seems to be no longer kept in config.xml. 
double clicking supertuxkart.exe now opens in 1366x768 and seems fully functional.

Only challenge now is how to convert my 0.8.x challenges.xml to the 0.9.3 achievements.xml format.  Hope there is a help or wiki article.
All False for a challenge in Challenges.xml = 1 in achievements.xml ?
then easy=true = 2 in achievements.xml ?
then medium=true = 3 in achievements.xml ?
then hard=true = 4 in achievements.xml ?
Or is achievements.xml even the right file?

**Comment by LuigiWriter** [comment]
You have been a blessing. Can't thank you enough. @deveee  If there is a way of giving you a star let me know.
