### ISSUE TITLE
Some textures turn black under certain circumstances

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3050]
Since 0.9.3, Some textures turn black under certain circumstances.

Using AMDGPU non-pro drivers in Arch.

Tested on graphics level 6 and 4. Does not occur on graphics level 1

https://www.youtube.com/watch?v=5qWVcmVU09E

**Comment by deveee** [comment]
I saw something similar in Hacienda - the wall in the front was flickering and it was sometimes dark, sometimes bright. It was with advanced lighting enabled and I don't remember on which GPU it happened for me, but it wasn't AMD for sure.

**Comment by psypherium** [comment]
I am starting to think that this issue is somehow related to the shaky tires problem. Both issues tend to occurr mostly on Hacienda, classroom, and minigolf. I'm not %100 certain that they happen on any other map. If so, it is much rarer.

**Comment by Benau** [comment]
Fixed by SP
