### ISSUE TITLE
Potential 144htz graphics engine performance issue (Vsync option non-functional?)

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3052]
I'm sorry I keep changing the title.

FPS appears like it is locked to 111 fps. 111 fps on every graphics setting.
Ryzen 16 thread 4ghtz. rx480. 2933 ddr4 with lowered timings. EVO NVME m.2.

very rarely it will jump to 115 or 124, but never 144.

Setting my cpu scheduler to performance seems to help a little bit. I've tried running the program under the vblank_mode=0 variable and that doesn't seem to work, or to impact performance.

Is mentioning my thread count irrelevant? Is "no thread utilisation" a bug? I don't expect the engine to be multithreaded, I just thought i would ask and make sure it's not a bug.

The Liquorix kernel appears to allow the engine to utilise %13 of another core, a total of %113 out of %1600, under certain circumstances. Maybe the game engine could tap into the same thing that scheduler uses. I dont know what I'm talking about really. I hope some of this is helpful or interesting.

**Comment by leyyin** [comment]
Could you try to set the `max_fps` to a higher value in the `config.xml` file?
See FAQ section `Where is the configuration stored?`  https://supertuxkart.net/FAQ

**Comment by psypherium** [comment]
Ah, I see it is set to 120. This is a bug, please add a max-fps setting to the options.

**Comment by auriamg** [comment]
99% of our users have 60 Hz monitors and/or a GPU incapable of rendering STK > 120 FPS, so I would definitely not consider this a bug - it's also useless IMO to put this in the UI since so few users are affected by this. The very few users who want ultra-high framerates can simply edit the config file, it takes 2 minutes and isn't particularly hard
