### ISSUE TITLE
bug with latest release

### ISSUE THREAD

**Issue by s3boun3t** [supertuxkart/stk-code#3054]
I have update supertuxkart with ppa "https://launchpad.net/~stk/+archive/ubuntu/dev" on my artful 64 bits
and supertuxkart don't want boot
in terminal, I have : 
`[error  ] SPMeshLoader: 32bit index not supported.
[error  ] Irrlicht: Could not load mesh, file format seems to be unsupported: /usr/share/games/supertuxkart/data/models/thunderbird.spm
[fatal  ] referee: Can't find referee model 'thunderbird.spm', aborting.
AL lib: (EE) alc_cleanup: 1 device not closed
Erreur de segmentation (core dumped)`

**Comment by Benau** [comment]
PPA is not official, please use our latest linux binaries here:
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3

**Comment by qwertychouskie** [comment]
@s3boun3t I found the issue with the PPA, it should be fixed as soon as Launchpad finishes rebuilding the packages.  Sorry for the issue.

**Comment by s3boun3t** [comment]
ho, ok, thanks
