### ISSUE TITLE
Minigolf reverse FTL 

### ISSUE THREAD

**Issue by bebehei** [supertuxkart/stk-code#3056]
Playing Follow the Leader on minigolf track in reverse requires the leader kart to drive a single lap alone until it reaches the start again. Beginning from this point, the race works normal.

It looks like this bug appears only, when driving with 19 opponent carts. It seems like the leader kart is placed before and not behind the start line.

STK installed via AUR version `18101+17428-1` (stk assets revision 17428)

**Comment by bebehei** [comment]
The bug doesn't appear anymore with current revisions. I'm not sure, how this got fixed. There's exactly one commit done to `tracks/minigolf` in the assets repo since then.

So, I guess, this must have been a coding issue. Sadly my bisects didn't yield any valuable commits.

**Comment by qwertychouskie** [comment]
This was probably related to @Alayan-stk-2's recent finish line work.  (Maybe https://github.com/supertuxkart/stk-code/pull/3273?)

**Comment by Alayan-stk-2** [comment]
No, I don't think so. My changes only affected the computed finish time at the end, not the kart's position at the beginning.
