### ISSUE TITLE
Remember chosen kart per Gamemode

### ISSUE THREAD

**Issue by Fantasmos** [supertuxkart/stk-code#3057]
With the following merge taken place: https://github.com/supertuxkart/stk-code/commit/c59af9136c0f2317002d700186b69580eb144110 it should be possible to now to use "MapUserConfigParam" to store the kart per gamemode (similar to how it stores the number of AI per gamemode with m_num_karts_per_gamemode).

**Comment by auriamg** [comment]
Is it really necessary though? I'm not sure why you'd want a different kart per mode, usually you'd choose a kart based on your character preference

Another reason that makes this impossible, though, is that the kart is selected before the game mode, so on the kart selection screen we couldn't possibly know which game mode it will be. I don't think it's worth changing the entire UI flow just for that
