### ISSUE TITLE
Add information about BSD daemon copyright

### ISSUE THREAD

**Issue by ignatenkobrain** [supertuxkart/stk-code#3062]
I have contacted owner of BSD daemon (beastie) to give exception to use of daemon and he said that he is not opposed, but would like to get link to copyright on website. Could you please add it?

```
Hi,

I have been asked by the Fedora Project to confirm that Super Tux Kart
has permission to use the Bsd Daemon in one of its kart (as I am the
copyright holder of the BSD Daemon). Having not previously heard of
Super Tux Kart, I downloaded it to my Andriod phone (thanks for making
it avaiable there). As a free and open-source project, I have no
objection to you having a BSD Daemon kart. But I would like to get
an agreement with your project which consists of you acknowledging
that you use the BSD Daemon by adding to the BSD Daemon description
on the "Discover" page a statement:

        <a href="http://www.mckusick.com/copyright.html>
        BSD Daemon used with permission.</a>

IF you are not the right person to ask, please let me know who I 
should contact. Thanks,

        Marshall Kirk McKusick
```

I know that github is not really proper place for filing issues about website, but I have not found any better place.

**Comment by ignatenkobrain** [comment]
Just for the original mbox which I got: https://ignatenkobrain.fedorapeople.org/Re:_Usage_of__beastie__artwork_in_SuperTuxKart.mbox

**Comment by auriamg** [comment]
HI, I have added the link to the website, hopefully all should be good now

**Comment by ignatenkobrain** [comment]
@auriamg great, thanks a lot! There is still open question whether "Puffy" is allowed to use, I've got bugreport that it's not allowed, but more details are coming.
