### ISSUE TITLE
Minigolf uses wrong music, should use `bay.music`

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3063]
`bay.music` is now unused......
https://sourceforge.net/p/supertuxkart/code/14650/
https://sourceforge.net/p/supertuxkart/code/HEAD/tree/stk-assets/tracks/minigolf/track.xml
![](https://media.giphy.com/media/7Am7Ydb6CcjKg/giphy.gif)

**Comment by auriamg** [comment]
Fixed in svn
