### ISSUE TITLE
Joystick axis not operable in v0.9.3 win x64

### ISSUE THREAD

**Issue by gerrygk** [supertuxkart/stk-code#3064]
Hi, I recognised that STK v0.9.3 doesn't react to movements of my Logitech Extreme 3D's throttle axis. No idea what could be the reason. I've edited the input.xml manually, but without any positive effects.

Any ideas? Thanx in advance.

Gerry
OS: Win 7 x64

**Comment by gerrygk** [comment]
Btw: This axis works fine with other games, as the stick does...

**Comment by hiker** [comment]
Does the controller show up in the device list? Can you bind any keys?

Could you try using the gamepad visualisation as described in #3061?

**Comment by gerrygk** [comment]
Yes, the joy shows up and I can bind all keys and axes - except the throttle axis. While trying to bind it there's no reaction detectable.

**Comment by gerrygk** [comment]
Just used the gamepad visu. All axes and buttons detected correctly except throttle. It seems to be indicated as in down (0%) position (green bar from mid to left), but doesn't react to any axis movement...

**Comment by Benau** [comment]
can you try this beta zip https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200408/SuperTuxKart-git20200408-win.zip/download ?
