### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3065]
Add Nado's template:

(10:22:33 AM) nado: i wrote a issue template for the github repo, if you're interested in encouraging users to give more informations in first post https://gist.github.com/nado/0921cb5893ddd8e0b7370e9a648a2ad4
(10:23:10 AM) nado: you simply need to put in root directory or .github directory, and it prefills issue requests with this
(10:23:37 AM) nado: im not sure someone saw it last time i sent it and i added lines about gamepads

**Comment by nado** [comment]
To answer your question on IRC :
>> I assume people can just delete fields they don't want (I am thinking of opening tickets for myself or so)
Indeed they can, its a prefill, you are free to remove any line if not all.

**Comment by Benau** [comment]
merged
