### ISSUE TITLE
Remember login often fails

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3066]
I get this error

![stkcurlbug](https://user-images.githubusercontent.com/4296971/33235848-56e0e0b2-d210-11e7-88ca-1c2f16cdb811.jpg)

![stkbug](https://user-images.githubusercontent.com/4296971/33235852-6394f244-d210-11e7-96d8-f704fec34920.jpg)

**Comment by auriamg** [comment]
@leyyin Has anything certificate related changed lately? I know there was some discussion but I don't think that discussion was ever concluded

**Comment by leyyin** [comment]
@auriamg I did not change anything regarding the SSL

**Comment by hiker** [comment]
If this happens next time, can you check if:
1) the token is still in the config file (players.xml, search for saved-token)
2) the token is still in the DB on the server?
