### ISSUE TITLE
Handle a case when npot textures extension is missing

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3067]
Reported on the forum:
https://forum.freegamedev.net/viewtopic.php?f=17&t=7662&start=25#p75128

It happens for gles 2.0 devices that don't support npot textures. Atm. I can't find good statistics, but IIRC it should work on most android devices. And it's a core feature in gles 3.0. But anyway it should be easy to fix.

**Comment by Benau** [comment]
In stk_texture::resizeimage there is already check for npot case, maybe just return true if gles 2.0........

**Comment by deveee** [comment]
I can confirm that it works under emulator when I disable npot textures.

I will wait to see if there is more bug reports for different devices. This one happened on Android 4.3 that isn't even officially supported. Or if it affects only this one particular device, we can add it to graphical restrictions.

**Comment by deveee** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/458ffd461771fbc886ae9a7e5fbd6765fdfa3ded

Atm. used only for Android emulator. We can use it for some buggy drivers on android >= 4.4 if it will be needed.
