### ISSUE TITLE
Challenge completion scene is slow and frustrating

### ISSUE THREAD

**Issue by FLHerne** [supertuxkart/stk-code#3069]
On completing a Story Mode challenge, there's an scene where a chest rotates, is unlocked, shakes, opens, and then disgorges some items. These then slowly rotate toward the camera, and *eventually* there's some text to describe what I unlocked.

While this could be enjoyable to watch once, there are a couple of dozen challenges, and watching the same very slow animation repeatedly can become frustrating. The scene can be skipped, but there is no alternative display of which tracks etc. were unlocked; waiting through the animation is required if I would like that information.

**Comment by auriamg** [comment]
This is indeed a regression, in previous versions the first "skip" would skip the animation but still show what was unlocked
