### ISSUE TITLE
Don't use S3TC on normal maps

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3070]
Using texture compression on normal maps can cause bad artifacts:

![](https://camo.githubusercontent.com/d29acf773c2a72c8e0e2ac6a3c8752509a0b15d4/687474703a2f2f692e696d6775722e636f6d2f444669456a53692e706e67)

Also see <https://en.wikipedia.org/wiki/S3_Texture_Compression#Codecs>:

> Hand-drawn cartoon-like images do not compress well, nor do normal map data, both of which usually generate artifacts. ATI's 3Dc compression algorithm is a modification of DXT5 designed to overcome S3TC's shortcomings with regard to normal maps. id Software worked around the normalmap compression issues in Doom 3 by moving the red component into the alpha channel before compression and moving it back during rendering in the pixel shader.

Right now this is not a huge issue as very few things currently use normal maps, but once they become more common this might be a bigger issue.  I don't want to just disable texture compression though, as it gives me a big performance boost (integrated graphics with RAM in single-channel mode).

**Comment by samuncle** [comment]
I can confirm this. It's probably a good idea to also disable it on the gloss map. If you enable it and check in the night winter track, the map looks horrible.

**Comment by Benau** [comment]
you need to understand that if more gloss map / normal map / whatever "data type" map is used, than the no. of uncompressed texture space will be more if use your way
