### ISSUE TITLE
Mouse as a gamemaster

### ISSUE THREAD

**Issue by sjal** [supertuxkart/stk-code#3074]
If you select 'Multiplayer' using a mouse, after selecting the karts none of the players can actually select difficulty, map and the game mode because it says that only the game master may act at this point.

**Comment by sjal** [comment]
It's not reproducible in the 'Singleplayer'. It works fine there

**Comment by auriamg** [comment]
Do you mean that you click to access the multiplayer menu, but then everyone uses gamepads?

**Comment by sjal** [comment]
Everyone uses either a gamepad or a keyboard, it doesn't matter. Mouse is still treated as a gamemaster if he clicks on Multiplayer

**Comment by auriamg** [comment]
This issue no longer exists in the latest version of STK
