### ISSUE TITLE
Failing a challenge in Story Mode puts you to Singleplayer

### ISSUE THREAD

**Issue by sjal** [supertuxkart/stk-code#3075]
After you fail a challenge you get to choose a difficulty and a game mode (Race Setup), after pressing Cancel you return to main menu, if you proceed you get to choose a track and Singleplayer mode proceeds afterwards.

**Comment by RiderExMachina** [comment]
Can confirm on SuperTuxKart ver. 0.9.3.

**Comment by Alayan-stk-2** [comment]
Had it happening too. Annoying issue.

**Comment by Alayan-stk-2** [comment]
This only seems to happen with the FTL challenge.
