### ISSUE TITLE
STK cannot select Nvidia GPU as default when running on Windows Optimus machines

### ISSUE THREAD

**Issue by MillironX** [supertuxkart/stk-code#3076]
I can tell my Nvidia control panel to make SuperTuxKart use the Nvidia GPU by default
![capture02](https://user-images.githubusercontent.com/25492070/34129466-789d93aa-e401-11e7-9678-3e3543dfa5f0.png)

but then it always selects integrated graphics to run with by default
![capture01](https://user-images.githubusercontent.com/25492070/34129458-71273248-e401-11e7-93f9-9883d42e97eb.png)

I can reproduce this on a Windows 10 Pro machine with Nvidia GTX 1050 Ti (brand new), and a Windows 7 Professional machine with Nvidia GTX 960M (two years old). I contacted Nvidia, and they said the game would need an update to support Optimus.

**Comment by auriamg** [comment]
This is weird, on my own laptop everything is fine for me... I have no idea what is different for you, maybe something changed on Windows 10... Does anyone have any idea if anything special is required for optimus to work?

![tmpstk](https://user-images.githubusercontent.com/4296971/34134335-0374a1aa-e428-11e7-93db-bebdde24aa5f.jpg)

**Comment by qwertychouskie** [comment]
@MillironX Maybe it is because in the first screenshot you set it for the .exe, then in the second screenshot you check the .lnk in the start menu.

**Comment by MillironX** [comment]
@qwertychouskie That doesn't seem to matter. 
![capture03](https://user-images.githubusercontent.com/25492070/34181247-c0ba9278-e4ce-11e7-980a-0cf65e9eb4fc.png)

**Comment by hiker** [comment]
Can you check what is actually being used? Look at:
```
 %APPDATA%/supertuxkart/0.8.2/stdout.log
```
search for OpenGL vendor and check if this intel or nvidia.

I have the suspicion that the 'default' entry means system-wide default (and that auria has set her default to be auto (or nvidia)), NOT that the program is executed by that processor by default.

**Comment by MillironX** [comment]
@hiker Here are the appropriate lines from `stdout.log`
    [info   ] IrrDriver: OpenGL version: 4.3
    [info   ] IrrDriver: OpenGL vendor: Intel
    [info   ] IrrDriver: OpenGL renderer: Intel(R) HD Graphics 630
    [info   ] IrrDriver: OpenGL version string: 4.3.0 - Build 22.20.16.4771

**Comment by qwertychouskie** [comment]
This was fixed with https://github.com/supertuxkart/stk-code/commit/fd3a2099bc2991244e45d51cf38d4a946a3c82ea (and https://github.com/supertuxkart/stk-code/pull/4693 for AMD systems).

**Comment by Alayan-stk-2** [comment]
Closing, see qwerty's comment.
