### ISSUE TITLE
STK Crash, solutions?

### ISSUE THREAD

**Issue by BountyHunter420** [supertuxkart/stk-code#3077]
Both GTA5 and STK started crashing on startup, this is what I've got while trying to launch STK. Any solutions?

---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 DllCanUnloadNow
 DllCanUnloadNow
 PlaySoundW
 BaseThreadInitThunk
 RtlUserThreadStart
---------------------------
OK   
---------------------------

**Comment by auriamg** [comment]
HI, which version of STK are you using? Which OS version? What GPU do you have? Have you checked if there is a driver updater available for your GPU?

**Comment by BountyHunter420** [comment]
I found a solution. Apparently my external joystick vibration drivers were making both stk and gta5 crash on startup. I uninstalled those drivers and everything works fine.
