### ISSUE TITLE
Add command-line support for "weather_gfx", "steering_animations" and "hq_mipmap" config parameters

### ISSUE THREAD

**Issue by Eliasvan** [supertuxkart/stk-code#3078]
Title says it all.
This is useful for benchmarking.

**Comment by Benau** [comment]
hq_mipmap is not useful in benchmark, steering_animations will be combined with animated scenery in the future

**Comment by Benau** [comment]
Fixed by SP, notice hq_mipmap is not useful in benchmark so it's not added

**Comment by Eliasvan** [comment]
OK, thanks!
