### ISSUE TITLE
Feature:arena can continue race  if game over

### ISSUE THREAD

**Issue by annopnod** [supertuxkart/stk-code#3082]
player can view only ai playing arena if player game over
stop race if controller=1

**Comment by auriamg** [comment]
Sorry, I don't understand

**Comment by annopnod** [comment]
![sss](https://user-images.githubusercontent.com/6957642/34460087-f381a75c-ee36-11e7-8056-8302a95f432e.png)

**Comment by Benau** [comment]
Use artist debug mode?

**Comment by auriamg** [comment]
I am not sure why you want to see AIs playing? In any case, you cannot view the computed race because it didn't actually happen, the results you see are "plausible but random"
