### ISSUE TITLE
Track:fortmagma easter_eggs

### ISSUE THREAD

**Issue by annopnod** [supertuxkart/stk-code#3084]
i improve  easter_eggs.xml 
&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;!-- Generated with script from SVN rev 16387 --&gt;
&lt;EasterEggHunt&gt;
  &lt;easy&gt;
&lt;easter-egg x=&quot;-186.606735&quot; y=&quot;14.334146&quot; z=&quot;-95.399643&quot; h=&quot;-157.677280&quot; /&gt;
    &lt;easter-egg x=&quot;18.359320&quot; y=&quot;42.291218&quot; z=&quot;-117.812309&quot; h=&quot;87.032313&quot; /&gt;
    &lt;easter-egg x=&quot;-81.792114&quot; y=&quot;30.571165&quot; z=&quot;-39.632523&quot; h=&quot;-90.077587&quot; /&gt;
    &lt;easter-egg x=&quot;-66.236778&quot; y=&quot;7.006537&quot; z=&quot;-36.848446&quot; h=&quot;-74.948581&quot; /&gt;
    &lt;easter-egg x=&quot;-122.233841&quot; y=&quot;1.291243&quot; z=&quot;91.747429&quot; h=&quot;-107.033845&quot;/&gt;
  &lt;/easy&gt;
  &lt;medium&gt;
&lt;easter-egg  x=&quot;-92.539520&quot; y=&quot;1.291227&quot; z=&quot;92.905151&quot; h=&quot;-58.960693&quot;/&gt;
&lt;easter-egg  x=&quot;-159.039276&quot; y=&quot;2.667634&quot; z=&quot;-35.106308&quot; h=&quot;-172.789852&quot;/&gt;
&lt;easter-egg  x=&quot;-60.889675&quot; y=&quot;34.913273&quot; z=&quot;-117.724922&quot; h=&quot;95.805342&quot;/&gt;
&lt;easter-egg  x=&quot;34.729961&quot; y=&quot;42.291218&quot; z=&quot;-119.752075&quot; h=&quot;83.307715&quot;/&gt;
&lt;easter-egg  x=&quot;-43.616016&quot; y=&quot;38.300274&quot; z=&quot;-31.489227&quot; h=&quot;-79.316992&quot;/&gt;
&lt;easter-egg  x=&quot;-74.344803&quot; y=&quot;24.781883&quot; z=&quot;21.453810&quot; h=&quot;54.369382&quot;/&gt;
&lt;easter-egg  x=&quot;-39.056149&quot; y=&quot;14.034497&quot; z=&quot;-21.438211&quot; h=&quot;-179.512398&quot;/&gt;
&lt;easter-egg  x=&quot;-54.615108&quot; y=&quot;22.011497&quot; z=&quot;-86.713852&quot; h=&quot;-123.880439&quot;/&gt;
&lt;easter-egg  x=&quot;-101.436195&quot; y=&quot;29.639042&quot; z=&quot;-72.590248&quot; h=&quot;-31.231761&quot;/&gt;
&lt;easter-egg  x=&quot;-83.074104&quot; y=&quot;-0.018767&quot; z=&quot;-7.205997&quot; h=&quot;38.709930&quot;/&gt;
  &lt;/medium&gt;
  &lt;hard&gt;
&lt;easter-egg  x=&quot;-94.736488&quot; y=&quot;1.331571&quot; z=&quot;88.084404&quot; h=&quot;-80.533722&quot;/&gt;
&lt;easter-egg  x=&quot;-187.885361&quot; y=&quot;15.445596&quot; z=&quot;-103.531021&quot; h=&quot;-170.281028&quot;/&gt;
&lt;easter-egg  x=&quot;-121.077797&quot; y=&quot;26.550749&quot; z=&quot;-106.315704&quot; h=&quot;54.013102&quot;/&gt;
&lt;easter-egg  x=&quot;30.704510&quot; y=&quot;42.291218&quot; z=&quot;-112.892418&quot; h=&quot;17.440246&quot;/&gt;
&lt;easter-egg  x=&quot;-77.938210&quot; y=&quot;30.596983&quot; z=&quot;-43.546734&quot; h=&quot;-118.457801&quot;/&gt;
&lt;easter-egg  x=&quot;-73.725876&quot; y=&quot;31.473015&quot; z=&quot;-32.276993&quot; h=&quot;-54.159596&quot;/&gt;
&lt;easter-egg  x=&quot;-76.239906&quot; y=&quot;32.482803&quot; z=&quot;1.726957&quot; h=&quot;132.529671&quot;/&gt;
&lt;easter-egg  x=&quot;-70.428986&quot; y=&quot;30.571140&quot; z=&quot;-20.882145&quot; h=&quot;141.772556&quot;/&gt;
&lt;easter-egg  x=&quot;-65.046005&quot; y=&quot;23.580793&quot; z=&quot;12.970445&quot; h=&quot;95.293037&quot;/&gt;
&lt;easter-egg  x=&quot;-45.500813&quot; y=&quot;18.717445&quot; z=&quot;-74.809090&quot; h=&quot;-144.024770&quot;/&gt;
&lt;easter-egg  x=&quot;-87.399261&quot; y=&quot;26.716932&quot; z=&quot;-88.483612&quot; h=&quot;-52.492743&quot;/&gt;
&lt;easter-egg  x=&quot;-82.718269&quot; y=&quot;-0.018769&quot; z=&quot;-25.704506&quot; h=&quot;-49.068625&quot;/&gt;
&lt;easter-egg  x=&quot;-57.360641&quot; y=&quot;-0.018765&quot; z=&quot;3.759887&quot; h=&quot;-69.719887&quot;/&gt;
&lt;easter-egg  x=&quot;-60.199718&quot; y=&quot;-0.018763&quot; z=&quot;25.673748&quot; h=&quot;-48.384602&quot;/&gt;
&lt;easter-egg  x=&quot;-83.817894&quot; y=&quot;-0.018763&quot; z=&quot;25.053171&quot; h=&quot;109.144422&quot;/&gt;
  &lt;/hard&gt;
&lt;/EasterEggHunt&gt;

**Comment by auriamg** [comment]
What did you change?
In any case, these files are not hand-written, they are generated from the source blender file by an exporter, so it is useless to manually edit it by hand as they will be overwritten next time the track is exported. I'm not aware of any issue with this file, so I don't think the exported needs changes, either

**Comment by annopnod** [comment]
fortmagma can not support easter eggs mode
i open easter_eggs.xml

origin xml data
&lt;EasterEggHunt&gt;
&lt;easy&gt;&lt;/easy&gt;
&lt;medium&gt;&lt;/medium&gt;
&lt;hard&gt;&lt;/hard&gt;
&lt;/EasterEggHunt&gt;

I Enable Artist Debug Mode
And Play game  Right Click
And Click Print Position

**Comment by annopnod** [comment]
fortmagma can not support easter eggs mode
i try edit it work
i open easter_eggs.xml
origin xml data
<EasterEggHunt>
<easy></easy>
<medium></medium>
<hard></hard>
</EasterEggHunt>
**How to**
Enable Artist Debug Mode
And Play game Right Click
And Click Print Position

**Comment by annopnod** [comment]
you can view this video
https://www.youtube.com/watch?v=OtTJhEwc020

**Comment by hiker** [comment]
If you want to add an easter egg mode to a track, this MUST be done in blender. modifying XML code can not be supported.

**Comment by annopnod** [comment]
I'm not sure. I think
Print Position **equal** blender 3d  vector

stk-code/src/modes/easter_egg_hunt.cpp Line 62
Read Position egg

**Comment by auriamg** [comment]
@annopnod You don't seem to understand. If you want to make tracks, you need to read https://supertuxkart.net/Making_Tracks and follow this procedure
