### ISSUE TITLE
Item collection sound is not always full volume

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3086]
Sometimes when you get a box the sound is not played at full volume.

**Comment by auriamg** [comment]
That is very vague. Sound simulates physical properties using OpenAL and indeed it's intended, why do you think this is a bug?

**Comment by qwertychouskie** [comment]
`grab_collectable.ogg` sometimes plays at a volume barely audable, other times it plays normaly, and yet other times somewhere in between.  I'm guessing it might have been introduced with https://github.com/supertuxkart/stk-code/commit/a1689efa5f2ef889ecc78b82837d4db9f03dbe05 as I first noticed it around that time, and that seems to be the only commit that changed audio recently, though it could also be https://github.com/supertuxkart/stk-code/issues/2921 that caused it, I'll try to do a test soon.  This usually only happens when there are AI karts.

**Comment by qwertychouskie** [comment]
@auriamg Here is a video that shows the issue: https://jacobspctuneup.tk/STK/itemcollectaudiobug.webm

The issue can first be seen at the 20s mark.
