### ISSUE TITLE
Build failure in lib/graphics_utils/mipmap/cpusimd.h due to direct inclusion of intrinsics headers

### ISSUE THREAD

**Issue by chithanh** [supertuxkart/stk-code#3091]
## Description

Build failure in lib/graphics_utils/mipmap/cpusimd.h when certain CPU architectures are selected via -march=...

This is for -march=bdver2
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/tbmintrin.h:25:3: error: #error "Never use <tbmintrin.h> directly; include <x86intrin.h> instead."

cpusimd.h includes various intrinsics headers which are not meant to be included on their own. The issue is masked on some configurations however, where immintrin.h is included first.

## Steps to reproduce

Build with -mtbm or -mlzcnt or -march=bdver2 in CFLAGS

## Configuration

STK release version: 0.9.3

STK Source (ppa, distribution package, official bin,...): Gentoo package
If you did not download STK from the official website, please specify where you got it: Gentoo package

System: Gentoo Linux

Graphics card: AMD RADEON R7

CPU: AMD A12-9800

**Comment by nado** [comment]
Could you try changing the include line to reflect the compiler's advice and see if it's enough to fix it ?

**Comment by Benau** [comment]
can you replace cpusimd.h with this http://www.rayforce.net/cpusimd.h and see if it works for you?

**Comment by Benau** [comment]
@auriamg after https://github.com/supertuxkart/stk-code/commit/b1f1afb9c5ec19140f2c9f4e5d4f6f60180e54e3 can you retry the texture compression? (clean all caches and see if there is still 40 seconds loading)

Now it use "32" (high) quality, and i don't notice any serious slowdown, and it is significantly faster than with sse2. (and higher image quality)

This assume you OK to release stk for only sse2 CPUs, if we only do 64bit build than it's assumed yes for sse2 anyway, and sse2 is required for windows 8, and sse2 is more than 10 years ago

**Comment by qwertychouskie** [comment]
> SSE2 (Streaming SIMD Extensions 2), is one of the Intel SIMD (Single Instruction, Multiple Data) processor supplementary instruction sets first introduced by Intel with the initial version of the Pentium 4 in 2001.

I don't think STK would be playable on a Pentium 3 anyways ;)

**Comment by auriamg** [comment]
@Benau it's still very slow for me, even with your latest commit

**Comment by Benau** [comment]
assumed fixed, please use the above commit for fixes
