### ISSUE TITLE
Trophy in unlock cutscene spins off-center

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3092]
See https://jacobspctuneup.tk/STK/featunlocked_spinbug.webm

Tested with `master`, still valid as of 6/10/18.

**Comment by Alayan-stk-2** [comment]
I've had a look at the code, the rotation code is straightforward and doesn't seem to do anything special in case n == 0 (the trophy is first in the unlocked feature list).

I suspect the issue is in the trophy .spm model.

**Comment by qwertychouskie** [comment]
Here's a fixed blend: [trophy.blend.zip](https://github.com/supertuxkart/stk-code/files/2096035/trophy.blend.zip)

I also subsurfed it once to make it a bit less low-poly.

**Comment by auriamg** [comment]
Fixed in SVN

**Comment by Alayan-stk-2** [comment]
For some reason, I get this bug again with latest svn and code.

I mentioned in #3542 that another issue had become apparent after this fix, but I did not ask at all to revert this.

**Comment by Alayan-stk-2** [comment]
Happened only with the SuperTux cup (the filler platinum model).

Fixed in SVN.
