### ISSUE TITLE
Graphical glitch with the lamps in mines track

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3093]
The lamps look weird now
![mines-2018 01 13_10 24 34](https://user-images.githubusercontent.com/4296971/34907417-2806b0de-f84c-11e7-8569-782a6b612a43.jpg)

**Comment by Benau** [comment]
Auria can u reexport with the ao map deleted?

**Comment by Benau** [comment]
sam said he is ok to remove the ao, and it's now re-exported
