### ISSUE TITLE
Animated textures issue in Enterprise track

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3094]
The animated texture is invalid on the enterprise track

![stk_enterprise-2018 01 13_10 31 06](https://user-images.githubusercontent.com/4296971/34907477-07d322e2-f84d-11e7-9f14-71e040b1cae6.jpg)

**Comment by Benau** [comment]
Fixed

**Comment by Benau** [comment]
btw everyone please update to latest export script, it includes the ability to specify custom material shader and per-scene export tangents option (demonstrated in hexley.blend)
