### ISSUE TITLE
Triangles in transparent bubbles of the overworld are visible

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3095]
I'm not sure if this is a regression of the sp branch, but IIRC it was not there before.
The triangles at the backside of a bubble are visible (it seems like they are not shaded smoothly like the front side).

Graphics card: Radeon HD 6850 (radeo driver)

Edit: It seems to happen for two layers of transparency

![overworld-triangles](https://user-images.githubusercontent.com/6499211/34908065-f1e9e578-f889-11e7-8174-a142bc84a168.png)

**Comment by Benau** [comment]
Yes i know for a while

on windows /android it's fine

**Comment by Benau** [comment]
actually because some mesh vertex / triangles order got messed up when triangulation, let me see if there is a better way

**Comment by Benau** [comment]
Unfortunately this seems to be the limitation of triangulation of mesh in blender?
https://streamable.com/1ejxb
(you will see the same if you use triangulate modifier in blender)

Now i have no way but to disable triangulation if you don't export with tangents (overworld doesn't need perfect tangents anyway), you can re-open if you have better idea (solid mesh doesn't matter as it has depth test)

(rememeber svn up media repo and copy fixed export script!)
