### ISSUE TITLE
Animations get reset at the wrong time

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3097]
I suspect that animations get reset at the wrong time.
You can see it for example in the zipper animation or in the water and lava animations in the overworld.

Video: https://flakebi.de/flakebi/AnimationReset.mp4

**Comment by Benau** [comment]
auria / deve do you see the same too?

i cannot reproduce in my radeonsi / r600 (hd56700

**Comment by Flakebi** [comment]
@Benau: Changing 
```
uv = vec2(i_uv.x + (i_texture_trans.x * i_normal.w),
    i_uv.y + (i_texture_trans.y * i_normal.w));
```
to
```
uv = vec2(i_uv.x + i_texture_trans.x, i_uv.y + i_texture_trans.y);
```
as you proposed worked.

The animations are faster than before and without stutters.

**Comment by Benau** [comment]
(git reset to original repo first)

than your mesa driver has problem extracting .w from 10bit vector (like intel)
```
can you try edit the graphics restrictions file, add
<card contains="Radeon"      os="linux"     disable="Correct10bitNormalization"/>
<card contains="AMD"      os="linux"     disable="Correct10bitNormalization"/>
```
and see if it works

**Comment by Flakebi** [comment]
Adding the graphical restrictions works.

**Comment by Flakebi** [comment]
Output of `arb_vertex_type_2_10_10_10_rev-array_types` from piglit tests:
```
testing: RGBA SINT
testing: RGBA SNORM
Probe color at (25,5)
  Expected: 0.500000 0.250000 0.000000 1.000000
  Observed: 0.501961 0.250980 0.000000 0.333333
testing: RGBA UINT
testing: RGBA UNORM
testing: BGRA SNORM
Probe color at (85,5)
  Expected: 0.000000 0.250000 0.500000 1.000000
  Observed: 0.000000 0.250980 0.501961 0.333333
testing: BGRA UNORM
```

**Comment by Benau** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=105095

**Comment by qwertychouskie** [comment]
AFAIK this shouldn't be closed, the `graphical_restrictions.xml` file needs to get an entry for this.
