### ISSUE TITLE
background flag is pixelated after skin change

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3111]
## Description
If you change the Skin in the Options to a different one as your current you can see the pixels of the flag background, after restarting STK it is normal again. But if you change it again, it will again be pixeled until a restart

Before Changing: 
![menu-2018 02 02_11 27 03](https://user-images.githubusercontent.com/33566379/35729687-d45ac190-080f-11e8-9829-aff9100eefd0.png)
After Changing: (look at the borders between black and white)
![menu-2018 02 02_11 27 20](https://user-images.githubusercontent.com/33566379/35729688-d48af1a8-080f-11e8-811d-6938ee051ff0.png)

## Steps to reproduce
1. open STK
2. go into the options
3. change the skin
--> background flag is pixeled until a restart of STK

## Configuration

STK release version: 0.9.3 

STK Source (ppa, distribution package, official bin,...):
problem occured on:
- official release downloaded from official website
- latest self-build debug version from commit "Fix possible vao crash" (2 Feb 2018 6:41 AM)
- official android version form google play store

System: 
Windows 10 64bit, and Android 7.0 (Samsung Galaxy A5 2017) 

Graphics card: Intel HD Graphics 5500 898MHz

CPU: Intel Core i5-5200U 2.20GHz (2 Cores)

RAM: 4GB DDR3

Gamepads/keyboards models if related to the issue: unrelated

## Additional information

Please provide stdout.log, it is located in

* %appdata%\supertuxkart\ **0.8.2** (windows) /**btw: why is this folder called 0.8.2**

stdout.log
Dont't think there is something related to see in it

```

If an error message was shown, please copy paste the complete error message or a screenshot of it:
no error message nor any output in the debug output about this

**Comment by deveee** [comment]
Probably because you have disabled HD textures in options and it is reloaded as non-HD texture.
