### ISSUE TITLE
Add "Black Forest" track as official track

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3125]
It would be nice to have Black Forest as an official track (when it is finished, of course). It is very high quality, very fun to play, etc.  Many people probably do not go into the addons section and try different tracks looking for good ones.

https://forum.freegamedev.net/viewtopic.php?f=18&t=7739
https://github.com/supertuxkart/stk-code/files/1732294/forest_track.zip

cc @SvenAndreasBelting, the maker of the track

**Comment by Benau** [comment]
Please don't make suggestion in bug tracker, you are barely helping if that is the case, but just give nothing but trouble to us
