### ISSUE TITLE
Migrate assets repo away from utterly broken SourceForge?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3128]
## Description

SF has been udderly :cow2: broken for almost a month now (since Feb 13).  Services keep going in and out.  And SF hasn't been the most transparent (https://twitter.com/sfnet_ops), many times saying that a certain part has been fixed, only to either (a) have it still partially broken, or (b) have it soon break again.

Maybe it's time to move away from SF for the assets repo?  GitHub lets use git or SVN (https://help.github.com/articles/working-with-subversion-on-github/), the "giant repo" issue can be solved be just using `svn co https://github.com/supertuxkart/stk-assets` instead of `git clone https://github.com/supertuxkart/stk-assets`.  Moving `stk-assets` to GitHub also has allows people to easily make PRs to the assets, without even having to touch the command line, just using the web interface.

In the mean time, bash is your friend.  Once you successfully get a few files checked out, run:
```bash
while true
do
    svn cleanup
    svn up
done
```

## Steps to reproduce
```
$ svn co https://svn.code.sf.net/p/supertuxkart/code/stk-assets
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/supertuxkart/code/stk-assets'
svn: E160013: '/p/supertuxkart/code/stk-assets' path not found
```

**Comment by auriamg** [comment]
It's true that SF hasn't been working all that well. But as far as I understand, github does not support hosting true svn repositories, it merely offers a svn "view" on github repositories (if I'm wrong, got the documentation explaining?). We were told by github staff that our assets repository was too large for git, so even if an SVN frontend is supported, so long as the backend still uses git then the issue most likely remains
