### ISSUE TITLE
Sudden Reboot On Macbook

### ISSUE THREAD

**Issue by Oberlehrling** [supertuxkart/stk-code#3129]
Hi, STK is suddenly rebooting the system. 

Here is the Protokoll from the Mac:

Anonymous UUID:       2CA1C8F7-0666-0376-2D1B-E7AD2034A6FD

Thu Mar  8 20:23:39 2018

*** Panic Report ***
panic(cpu 3 caller 0xffffff7f94f769e9): "GPU Panic: mux-regs 5 3 7f 0 0 0 severity 3 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:3 power-state 0 3D idle HDA idle : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff912de5f000 0x0a5480a2, D0, P3/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.16.21/src/AppleMuxControl/kext/GPUPanic.cpp:162
Backtrace (CPU 3), Frame : Return Address
0xffffff811b00b3f0 : 0xffffff8011a4f606 
0xffffff811b00b440 : 0xffffff8011b7c654 
0xffffff811b00b480 : 0xffffff8011b6e149 
0xffffff811b00b500 : 0xffffff8011a01120 
0xffffff811b00b520 : 0xffffff8011a4f03c 
0xffffff811b00b650 : 0xffffff8011a4edbc 
0xffffff811b00b6b0 : 0xffffff7f94f769e9 
0xffffff811b00b710 : 0xffffff7f92a07441 
0xffffff811b00b7d0 : 0xffffff7f92ad31ca 
0xffffff811b00b810 : 0xffffff7f92ad3235 
0xffffff811b00b890 : 0xffffff7f92d4e7f0 
0xffffff811b00b9b0 : 0xffffff7f92af4d35 
0xffffff811b00b9d0 : 0xffffff7f92a0e048 
0xffffff811b00ba80 : 0xffffff7f92a0ba84 
0xffffff811b00bc70 : 0xffffff7f92a0cc41 
0xffffff811b00bd50 : 0xffffff7f929b861e 
0xffffff811b00bdb0 : 0xffffff7f94f475e7 
0xffffff811b00be10 : 0xffffff7f94f47966 
0xffffff811b00be30 : 0xffffff8012095ecc 
0xffffff811b00bea0 : 0xffffff8012095df6 
0xffffff811b00bed0 : 0xffffff8011a88ec4 
0xffffff811b00bf40 : 0xffffff8011a889b5 
0xffffff811b00bfa0 : 0xffffff8011a004f7 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.16.21)[B4DB1D7A-D4DE-3965-94DC-05CE8B9F2802]@0xffffff7f94f68000->0xffffff7f94f7afff
            dependency: com.apple.driver.AppleGraphicsControl(3.16.21)[2EB9A384-439B-3BDC-927C-34E390CB0E59]@0xffffff7f94f65000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[8794C760-FDD9-3664-ADED-4A9BBEC6E517]@0xffffff7f9260f000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E6C654E-4A8F-3C6B-BBFE-BA8A68C9C146]@0xffffff7f92334000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f92952000
            dependency: com.apple.AppleGraphicsDeviceControl(3.16.21)[F8503E88-24EF-3DBA-A4D6-FA1CE4C47427]@0xffffff7f94f36000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f929b6000->0xffffff7f92c1efff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E6C654E-4A8F-3C6B-BBFE-BA8A68C9C146]@0xffffff7f92334000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f929a6000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f92952000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.4)[5DCF031B-F81F-32A3-ADCD-18E16EAC7CF0]@0xffffff7f92c2a000->0xffffff7f92ed2fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f929b6000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E6C654E-4A8F-3C6B-BBFE-BA8A68C9C146]@0xffffff7f92334000
         com.apple.driver.AGPM(110.23.30)[87C1EF35-F7A2-3DEF-B666-88E94DBA5EDF]@0xffffff7f94f43000->0xffffff7f94f5bfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[8E6C654E-4A8F-3C6B-BBFE-BA8A68C9C146]@0xffffff7f92334000
            dependency: com.apple.driver.IOPlatformPluginFamily(6.0.0d8)[122FC50D-8A9C-37D8-9528-A38F45906EA9]@0xffffff7f93682000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f929a6000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f92952000
            dependency: com.apple.AppleGraphicsDeviceControl(3.16.21)[F8503E88-24EF-3DBA-A4D6-FA1CE4C47427]@0xffffff7f94f36000

BSD process name corresponding to current thread: kernel_task
Boot args: kext-dev-mode=1

Mac OS version:
17D102

Kernel version:
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
Kernel UUID: 18D901F1-4A03-3FF1-AE34-C26B2732F13C
Kernel slide:     0x0000000011600000
Kernel text base: 0xffffff8011800000
__HIB  text base: 0xffffff8011700000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 13221988475431
last loaded kext at 75548865268: com.apple.driver.AudioAUUC	1.70 (addr 0xffffff7f94676000, size 32768)
last unloaded kext at 245776897610: com.apple.driver.usb.AppleUSBUHCI	1.2 (addr 0xffffff7f93267000, size 135168)
loaded kexts:
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AGPM	110.23.30
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleMikeyDriver	280.12
com.apple.driver.AppleHDA	280.12
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.GeForceTesla	10.0.4
com.apple.driver.AppleIntelHDGraphics	10.0.4
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleMuxControl	3.16.21
com.apple.driver.AppleIntelHDGraphicsFB	10.0.4
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AGDCBacklightControl	3.16.2
com.apple.driver.eficheck	1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBCardReader	439.30.4
com.apple.driver.AppleIRController	352
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	407.30.1
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.driver.AppleFWOHCI	5.5.8
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.0.0
com.apple.nke.applicationfirewall	183
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	220.0.0
com.apple.IOBufferCopyEngineTest	1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.iokit.IOSurface	209.2.2
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSSE	1.0
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.4
com.apple.nvidia.classic.NVDAResmanTesla	10.0.4
com.apple.AppleGPUWrangler	3.16.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOFireWireIP	2.2.8
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	517.22
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleUSBMultitouch	261
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.CoreStorage	546
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.2
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOAHCISerialATAPI	267
com.apple.iokit.IOAHCIBlockStorage	301.40.2
com.apple.iokit.IOFireWireFamily	4.6.8
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro6,2, BootROM MBP61.005A.B00, 2 processors, Intel Core i5, 2,4 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54333531533643465238432D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3038352E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.2f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS547550A9E384, 500,11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus: 

Can somebody help?

**Comment by auriamg** [comment]
this looks like a crash in the GPU driver. Can you perhaps make sure you have all the updates, including the latest driver updates if any? If there are still crashes, that will be super hard to debug for us, as this would likely require Apple to be involved to produce a driver fix

**Comment by Alayan-stk-2** [comment]
Not enough info to do anything. Likely a driver issue.
