### ISSUE TITLE
GNOME 3's top panel and window border cut SuperTuxKart window on small screens

### ISSUE THREAD

**Issue by ssspacez** [supertuxkart/stk-code#3134]
The bottom panel that you can configure resolution on the welcome screen is **hidden** using GNOME 3 on a **14" laptop with 1366 x 768** resolution. 

GNOME 3 windows have a large top window border and there is a top panel too, so they **push the game window down enough pixels to cut the bottom of the game window**, so the bottom panel is hidden. You can still access the icons but you have to hover to the edge of the screen and know that there are icons there. 

I know the panel is there because I've played the game before but **new users** with the same configuration will have **no idea that there is a panel with icons there** and can think that the game is bad because it doesn't have options, close the window using the "X"(because some people won't see the Exit button) and uninstall the game.

Look at the bottom right of the window(orange section): 
https://imgur.com/a/NskqO

This is was installed on **Ubuntu 18.04 dev edition with communitheme**, so a lot of people with a similar setup will face this issue when the **LTS** is released. Probably on screens with less vertical space(wider or smaller screens) will be even worse, I think the panel will be completely hidden.

**Two suggested solutions:**

1) **Redesign** the welcome screen of the game. Move the bottom panel up some pixels to prevent the issue, or put the icons of the bottom panel vertically in some way, or any other design that put the bottom icons more in the middle of the screen.

2) Get the users monitor resolution and use **fullscreen mode by default**.

**Comment by deveee** [comment]
It's possible to read available space with netwm. So that if we have 1366x768 monitor and it reports 1366x700 (or 1300x768 or whatever), we can resize window to fit this size. Most window managers support netwm. Wayland does it better and you get configure event before window is actually displayed.

**Comment by deveee** [comment]
It may need some testing on different window managers, but it should be fixed in this commit: https://github.com/supertuxkart/stk-code/commit/38a4e06a6c24a593ed058fb0378d0918414c4847

I just assume that 1366x768 + windowed mode means "maximized window" and I let window manager to choose best size.

It should be possible to use _NET_REQUEST_FRAME_EXTENTS to get frame dimensions, then _NET_WORKAREA to get available space and compute real window size, but it's IMO overcomplicated.
