### ISSUE TITLE
Fix Adiumy kart

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3138]
@Benau wrote in a comment at #2958 that it "seems that AI controlling adiumy will have ~80% of the time finish the race last".

This is not a random fluke of those tests. This is something I've consistently observed ever since I remember playing STK with the 3-wheeled Adiumy kart. It was true several versions ago and is still true today.

Adiumy is pretty much always last in GP. That is, unless there are two Adiumy karts.

I've done a search on issues, and to my surprise there doesn't seem to be anything about it.

So I open this issue, because I think that having a kart so much worse at racing than the others is not good for the game.

**Comment by qwertychouskie** [comment]
Come on, it's an implementation of the "having better/worse karts in each GP" you were talking about. ;D

**Comment by Alayan-stk-2** [comment]
#3271 tracks the root cause of the Adiumy issue. No need to have this one open any longer.
