### ISSUE TITLE
Freeze and weird characters on story mode near bubble

### ISSUE THREAD

**Issue by ssspacez** [supertuxkart/stk-code#3140]
Approaching one of the **bubbles** in **story mode**, it **freezes** and **weird characters** appear on the screen. Also, the **map** disappear partially.

**Screenshot and log attached**, check middle and bottom left of the screen.

Specs:

Quality 2
Fullscreen
VSync enabled

STK release version:
Version: 0.9.3-1

STK Source (ppa, distribution package, official bin,...):
gnome-software

```
System:

Ubuntu 18.04 bionic (dev branch)
Kernel: x86_64 Linux 4.15.0-10-generic
Desktop: Gnome 3.27.92

CPU:       Dual core Intel Core i5-2410M (-MT-MCP-) 
           arch: Sandy Bridge rev.7 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9179
           clock speeds: min/max: 800/2900 MHz 1: 801 MHz 2: 800 MHz
           3: 801 MHz 4: 805 MHz
Graphics:  Card: Intel 2nd Generation Core Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0116
           Display Server: x11 (X.Org 1.19.6 ) driver: i915
           Resolution: 1366x768@59.97hz
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile
           version: 3.3 Mesa 18.0.0-rc4 (compat-v: 3.0) Direct Render: Yes

GPU: Intel HD Graphics 3000

```

![freeze](https://user-images.githubusercontent.com/34775187/37458940-4eb2539c-2825-11e8-8b3a-aba80b05d285.png)

[stdout.log](https://github.com/supertuxkart/stk-code/files/1815025/stdout.log)

**Comment by Benau** [comment]
Hey, can u try stk 0.9.3 on older mesa version first?

To me it's more like a driver bug than stk bug

**Comment by deveee** [comment]
I suggest to try older mesa version first to see how it works.

**Comment by ssspacez** [comment]
I don't know how to do this, sorry.

**Comment by qwertychouskie** [comment]
@ssspacez Could you install the latest updates and try again?  Mesa RC5 had a lot of fixes.
