### ISSUE TITLE
Donation button inside the game [Feature Request]

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#3141]
Put a link to https://supertuxkart.net/Donate somewhere inside the game, ideas:

-  Create a button named _Support_ or _Donate_ with an icon like the heart of the website(or any other icon), write a short description and put the donate link
- Put the link inside the _( i ) About_ screen

**Comment by auriamg** [comment]
This is not necessarily a bad idea, but (except by core team members) this bug tracker should be used to report bugs only, feature requests or ideas are better suited for the forum. The main difficulty I foresee here is opening the browser in a multi-platform way, including possibly exiting fullscreen

**Comment by qwertychouskie** [comment]
I do have some related code here:

https://github.com/qwertychouskie/stk-code/blob/update-notification/src/online/link_helper.cpp
https://github.com/qwertychouskie/stk-code/blob/update-notification/src/online/link_helper.hpp
