### ISSUE TITLE
Parachutes broken (float to tick conversion)

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3150]
I was in the process to revert parachute duration to floats when I noticed it had only recently been changed to use ticks with an int.

As the config files currently use floats, and as some other code parts expect floats, parachute are currently broken.

I don't know what exactly it does to the time they're active. The current implementation relies heavily on having floats.

It seems to break the AI who don't use parachutes. The AI calls getParachuteDurationOther in a comparison before using the item ; and it seems the comparison is now broken.

**Comment by hiker** [comment]
I am working on a huge patch, which likely will fix this as well, so please don't touch this issue atm.

**Comment by Alayan-stk-2** [comment]
Don't worry, I won't touch it. I just wanted to make sure it is known.

**Comment by Alayan-stk-2** [comment]
My observations are that the time the parachutes stay work fine.

So this let the AI utilization issue.

**Comment by Alayan-stk-2** [comment]
Don't happen anymore on a version close to the latest master.
