### ISSUE TITLE
Graphics not working correct on Linux Mint

### ISSUE THREAD

**Issue by dvbeek** [supertuxkart/stk-code#3151]
Version: 0.9.3
System: Linux Mint 17.3 'Rosa', Cinnamon 64-bit (2.8.8)
Graphics card: Intel Corporation Device 22b1
CPU: Intel Pentium N3700 @ 1.60GHz x 4

The story mode field does not display correctly (looks like the grass is missing) and also the tracks or not playable, because a lot of walls are missing, etc.

Stdout:

> [info   ] [FileManager]: Data files will be fetched from: './data/'
> [info   ] [FileManager]: User directory is '/home/dennis/.config/supertuxkart/0.8.2/'.
> [info   ] [FileManager]: Addons files will be stored in '/home/dennis/.local/share/supertuxkart/addons/'.
> [info   ] [FileManager]: Screenshots will be stored in '/home/dennis/.local/share/supertuxkart/screenshots/'.
> [info   ] [FileManager]: User-defined grand prix will be stored in '/home/dennis/.local/share/supertuxkart/grandprix/'.
> [info   ] [FileManager]: Asset 0 will be loaded from './data/challenges/'.
> [info   ] [FileManager]: Asset 1 will be loaded from './data/gfx/'.
> [info   ] [FileManager]: Asset 2 will be loaded from './data/grandprix/'.
> [info   ] [FileManager]: Asset 3 will be loaded from './data/gui/'.
> [info   ] [FileManager]: Asset 4 will be loaded from './data/library/'.
> [info   ] [FileManager]: Asset 5 will be loaded from './data/models/'.
> [info   ] [FileManager]: Asset 6 will be loaded from './data/music/'.
> [info   ] [FileManager]: Asset 7 will be loaded from './data/replay/'.
> [info   ] [FileManager]: Asset 8 will be loaded from './data/tracks/'.
> [info   ] [FileManager]: Asset 9 will be loaded from './data/sfx/'.
> [info   ] [FileManager]: Asset 10 will be loaded from './data/shaders/'.
> [info   ] [FileManager]: Asset 11 will be loaded from './data/skins/'.
> [info   ] [FileManager]: Asset 12 will be loaded from './data/textures/'.
> [info   ] [FileManager]: Asset 13 will be loaded from './data/ttf/'.
> [info   ] [FileManager]: Asset 14 will be loaded from './data/po/'.
> [verbose  ] translation: Env var LANGUAGE = 'en_US.UTF-8'.
> [verbose  ] translation: Language 'English (United States)'.
> [info   ] IrrDriver: OpenGL version: 3.3
> [info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
> [info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Cherryview 
> [info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.5.9
> [info   ] GLDriver: AMD Vertex Shader Layer Present
> [info   ] GLDriver: ARB Buffer Storage Present
> [info   ] GLDriver: ARB Base Instance Present
> [info   ] GLDriver: ARB Draw Indirect Present
> [info   ] GLDriver: ARB Texture Storage Present
> [info   ] GLDriver: ARB Texture View Present
> [info   ] GLDriver: ARB Shader Atomic Counters Present
> [info   ] GLDriver: ARB Multi Draw Indirect Present
> [info   ] GLDriver: ARB Uniform Buffer Object Present
> [info   ] GLDriver: ARB Explicit Attrib Location Present
> [info   ] GLDriver: EXT Texture Filter Anisotropic Present
> [info   ] GLDriver: ARB Texture Swizzle Present
> [info   ] GLDriver: ARB Pixel Buffer Object Present
> [info   ] GLDriver: ARB framebuffer sRGB Present
> [warn   ] irr_driver: Created visual is not sRGB-capable. Re-creating device to workaround the issue.
> [info   ] IrrDriver: OpenGL version: 3.3
> [info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
> [info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Cherryview 
> [info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.5.9
> [info   ] GLDriver: AMD Vertex Shader Layer Present
> [info   ] GLDriver: ARB Buffer Storage Present
> [info   ] GLDriver: ARB Base Instance Present
> [info   ] GLDriver: ARB Draw Indirect Present
> [info   ] GLDriver: ARB Texture Storage Present
> [info   ] GLDriver: ARB Texture View Present
> [info   ] GLDriver: ARB Shader Atomic Counters Present
> [info   ] GLDriver: ARB Multi Draw Indirect Present
> [info   ] GLDriver: ARB Uniform Buffer Object Present
> [info   ] GLDriver: ARB Explicit Attrib Location Present
> [info   ] GLDriver: EXT Texture Filter Anisotropic Present
> [info   ] GLDriver: ARB Texture Swizzle Present
> [info   ] GLDriver: ARB Pixel Buffer Object Present
> [info   ] GLDriver: ARB framebuffer sRGB Present
> [info   ] ShaderBasedRenderer: Preloading shaders...
> [info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
> [info   ] ShaderFilesManager: Compiling shader : object_pass.vert
> [info   ] ShaderFilesManager: Compiling shader : object_pass1.frag
> [info   ] ShaderFilesManager: Compiling shader : splatting.frag
> [info   ] ShaderFilesManager: Compiling shader : skinning.vert
> [info   ] ShaderFilesManager: Compiling shader : transparent.frag
> [info   ] ShaderFilesManager: Compiling shader : coloredquad.vert
> [info   ] ShaderFilesManager: Compiling shader : coloredquad.frag
> [info   ] ShaderFilesManager: Compiling shader : screenquad.vert
> [info   ] ShaderFilesManager: Compiling shader : tonemap.frag
> [info   ] ShaderFilesManager: Compiling shader : passthrough.frag
> [info   ] ShaderFilesManager: Compiling shader : alphatest_particle.vert
> [info   ] ShaderFilesManager: Compiling shader : alphatest_particle.frag
> [info   ] ShaderFilesManager: Compiling shader : simple_particle.vert
> [info   ] ShaderFilesManager: Compiling shader : simple_particle.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_object_pass.vert
> [info   ] ShaderFilesManager: Compiling shader : instanced_skinning.vert
> [info   ] ShaderFilesManager: Compiling shader : instanced_object_pass1.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_object_pass2.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_objectref_pass1.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_objectref_pass2.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_object_unlit.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_normalmap.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_grass.vert
> [info   ] ShaderFilesManager: Compiling shader : instanced_grass_pass2.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_objectpass_spheremap.frag
> [info   ] ShaderFilesManager: Compiling shader : instanced_detailed_object_pass2.frag
> [info   ] STKTexManager: 3 thread(s) for texture loading, each capacity 1 MB.
> [info   ] ShaderBasedRenderer: Geometry will be rendered with indirect draw policy.
> [info   ] irr_driver: GLSL supported.
> [info   ] ShaderFilesManager: Compiling shader : texturedquad.vert
> [info   ] ShaderFilesManager: Compiling shader : texturedquad.frag
> [info   ] ShaderFilesManager: Compiling shader : uniformcolortexturedquad.frag
> [info   ] ShaderFilesManager: Compiling shader : colortexturedquad.vert
> [info   ] ShaderFilesManager: Compiling shader : colortexturedquad.frag
> [info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/xml/news.xml
> [info   ] addons: Using cached addons.xml.
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/images/32999604857af930517f49.png
> [info   ] GrandPrixManager: Loading Grand Prix files from ./data/grandprix/
> [info   ] GrandPrixManager: Loading Grand Prix files from /home/dennis/.local/share/supertuxkart/grandprix/
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [info   ] HTTPRequest: Downloading 
> [verbose  ] RaceManager: Nb of karts=1, ghost karts:0 ai:0 players:1
> 
> [info   ] Singleton: Destroyed singleton.
> [warn   ] material: Track uses deprecated texture 'grass.jpg'
> [info   ] Script: allchallenges: unlocked_challenges=1, challenges=26
> [info   ] Script: allchallenges: unlocked_challenges=1, challenges=26
> [info   ] Script: allchallenges: unlocked_challenges=1, challenges=26
> [info   ] Script: allchallenges: unlocked_challenges=1, challenges=26
> [info   ] ShaderFilesManager: Compiling shader : sky.vert
> [info   ] ShaderFilesManager: Compiling shader : sky.frag
> [info   ] ShaderFilesManager: Compiling shader : transparentfog.frag
> [warn   ] SFXManager: Throttling sfx - queue size 41
> [warn   ] SFXManager: Throttling sfx - queue size 41
> [warn   ] SFXManager: Throttling sfx - queue size 41
> [warn   ] SFXManager: Throttling sfx - queue size 41
> [warn   ] SFXManager: Throttling sfx - queue size 41
> [verbose  ] irr_driver: Retrieved window location for config: 112 0
> [verbose  ] Thread: Start waiting 950063.511000
> [verbose  ] Thread: Waited 0.000000 seconds for thread to become deleteable.
> [verbose  ] Thread: Stop waiting 950063.511000
> [info   ] Singleton: Destroyed singleton.
> [info   ] Singleton: Destroyed singleton.
> [info   ] Singleton: Destroyed singleton.

**Comment by deveee** [comment]
Your drivers version is a bit old, you can check if it works with newer mesa version. You can also disable some graphical effects in setting to see if some particular features cause this issue.

**Comment by deveee** [comment]
Now I see that your GPU is gen8. I don't think that mesa 10.5 really supports these graphics cards. Please reopen if it still happens with newer mesa versions.

**Comment by qwertychouskie** [comment]
Yes, your OS is too old for your hardware.  Please upgrade to a newer version of the OS (Mint 18.3).
