### ISSUE TITLE
Forbid skidding when not on the ground

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3155]
Title is self-explanatory.

Currently, it is possible to skid while jumping. This doesn't affect the trajectory of the jump, but changes the kart orientation and makes the skidding counter increase. It is then possible, when landing on the ground, to use the bonus.

The easiest place to pull it off is at the big jump at the end of cacao temple, but it can be done in pretty much all the jumps.

As this is nonsensical, checks should be added to make sure that the kart is on the ground when skidding.

**Comment by deveee** [comment]
Here is Hiker's statement about this, maybe it should be written somewhere in a visible place :P
https://github.com/supertuxkart/stk-code/pull/2941#issuecomment-359989165

And similar issue:
https://github.com/supertuxkart/stk-code/issues/2762

And skidding itself doesn't have much sense - why do you run faster on a straight road while skidding?

**Comment by Alayan-stk-2** [comment]
Sorry, I searched for the keyword "skidding" in issues and somehow missed that one.
