### ISSUE TITLE
Wrong direction text is displayed twice

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3159]
At least in the german version, the text “wrong direction” is displayed twice:
![wrongdirection](https://user-images.githubusercontent.com/6499211/37682424-cf5e80fc-2c89-11e8-8d86-326d0bf3851d.png)

I think it should be shown only once.

**Comment by Mrxx99** [comment]
I also play in german and habe never seen this message twice.
I think it would be helpful for the developers if you would include more info, like which version you are using, release or debug, if debug which branch. And which system your on and cpu, gpu
The issue template is there for something ;)

**Comment by qwertychouskie** [comment]
I can confirm this on Intel HD 4000+Mesa git+STK `master`.  In my case it is often more than 2 and the lowest one flickers.

**Comment by Alayan-stk-2** [comment]
I also get the "wrong direction" message duplicated (or more, I had 5 copies the last time I saw it).

**Comment by auriamg** [comment]
This is related to the ticks refactor, now "checkForWrongDirection" may be called multiple times before "cleanupMessages" is called

**Comment by hiker** [comment]
Yes, very likely my fault :)
I am reopening this so that I don't forget.

**Comment by hiker** [comment]
I should clarify: while auria's patch fixes this, I want to check that I did not forget anything during the conversion - ideally auria's patch should not be necessary once everything is fixed.

**Comment by qwertychouskie** [comment]
Should https://github.com/supertuxkart/stk-code/commit/41cd33ce5542b636d48a6af178a745d1bf6e4e12 be reverted now?
