### ISSUE TITLE
Difficulty-specific objects

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3162]
Currently, there are objects specific to whether or not the track is in reverse (for ramps, e.g.).

A similar option to have difficulty specific objects would be useful : as easy and intermediate are much slower than expert and supertux ; a track which is lengthy but acceptable for higher difficulties will be too long, and thus boring, in lower difficulties. The issue already somewhat exists with Volcano Island ; and it could prevent including lengthier tracks.

Difficulty-specific objects would allow to add accelerators in some places (like Volcano Island's lava tunnel) for easier difficulties to keep the racing time in check.

**Comment by Benau** [comment]
So what's the point of this ticket while you don't make track for stk? (And the scripting engine can be extended as required)

Use the forum for idea next time
