### ISSUE TITLE
Story Mode points are not always counted properly

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3164]
## Description

In a few rare cases, the points of a challenge are not added upon completion. I had it happen to me twice. When another challenge is completed, the total will be updated properly. Returning to the menu and then to story mode may or may not fix it, I didn't test when it happened to me.

## Steps to reproduce

The occurrences are seemingly random. In most cases I had no issue.

The only possible lead I have is that I was trying to skip quickly the challenge success scene. If the point adding is somewhere here, it may have been short-circuited.

## Configuration

STK 0.9.3 release

**Comment by ssspacez** [comment]
Happened with me too, 0 points after winning.

**Comment by auriamg** [comment]
I have never reproduced this myself. I don't want to sound condescending, but are you 100% sure the challenges weren't already beaten? We've had a few similar bug reports in the past that were simply caused by confusion from players not realizing they were re-playing a challenge they'd already beaten

**Comment by Alayan-stk-2** [comment]
Absolutely 100% sure.

In fact, I even happen to have it captured on video. Look here : https://youtu.be/cKINc0UmN5s?t=36m48s

You can count the challenges on the map : 14 golds. You can see the points on the upper right : 130. I tried to enter the lighthouse challenge which requires 135 points and was blocked.

**Comment by auriamg** [comment]
This seems related to the feature unlocked cutscene being skipped. I attempted a fix, please let me know if you can reproduce the issue again

**Comment by Alayan-stk-2** [comment]
As it takes time to play the story mode, and I usually did it on regular 0.9.3 ; there will probably some time before I happen to test this on the git dev version.

From the look of the code change, it seems it would work.

I'll report back if I happen to encounter it again but I think in the meantime the issue can be closed.
