### ISSUE TITLE
Promoting SuperTuxKart on Facebook

### ISSUE THREAD

**Issue by anaufalm** [supertuxkart/stk-code#3166]
Wow, I've seen trailer of this game, and this is a really cool racing game, very interesting I really like it. May I share this game? So that people (gamers) know more about this cool game. I will promote it on facebook possible. ;)

**Comment by Alayan-stk-2** [comment]
Anyone can promote SuperTuxKart, of course, as long as you are careful to not say things which are untrue about it by error.

So you can certainly promote SuperTuxKart.

However, this github tracker is not the place for such questions. There is the forum or the IRC for this. This place is for developers and game development.

I suggest you to close this issue.

**Comment by anaufalm** [comment]
Yea of course, thanks before. I just introduce this game to make people
play this game on facebook. And I'll put your website link to the post to
make people easier download this game. :)

**Comment by anaufalm** [comment]
Ohh btw, can I take some screenshot on website wich will use on my post?

**Comment by auriamg** [comment]
Sure, feel free to reuse screenshots from our website. Please just make your post in a way that makes it clear enough this is a post from a fan, and not official promotion from the project's team
