### ISSUE TITLE
Driving backwards can make a kart appear first when it isn't

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3167]
The ranking estimate is only based on number of laps and position on track. Crossing the lap line and then going backwards makes the game get it completely wrong.

Video showing the issue : https://www.youtube.com/watch?v=srO3s_s6aos

**Comment by Alayan-stk-2** [comment]
Here is an idea about how to fix this : makes the game remember the previous distance of the kart ; and refuses to augment it if the position on the track says it should increase by say more than 200 (there needs to be margin for tracks with paths of different lengths). The minimum track length is of 500 at math's class, so going backwards wouldn't increase it anymore and so wouldn't make the game think the kart is first.

Then, distance may also be adapted as a sanity check for checkline/lap validation (to make it work better for addons track with only one checkline, as the main tracks have been fixed now).

**Comment by HybridDog** [comment]
You can't simply drive back and forth to get laps, so maybe there's already a mechanism to detect crossing the lap line in the wrong direction.

**Comment by Alayan-stk-2** [comment]
That's called checklines.

Yes, you can't win races that way (if there is only one checkline there are possible abuses however), but the displayed rank should be accurate.

**Comment by HybridDog** [comment]
I assume you have to pass the checklines one after another, so if there's a checkline between the last visited one and current position on track, the rank can be set as though you're waiting on the last visited checkline, e.g. after you drove backwards behind the lap line, there's at least one checkline between the lap line and your position (in the course's order), so your rank is set as though you're waiting on the lap line.
As side effect, if you miss a checkline (e.g. after driving to some place you're not supposed to reach), your rank does not keep up with the enemies' rank, thus you notice that you need to drive back or respawn for the checkline.

**Comment by Alayan-stk-2** [comment]
The downside of your proposal is that checking at what distance is a given checkline doesn't seem trivial, especially if there are checks in a place where there are multiple paths. It's more complicated to do properly.

The upside is indeed that a player would be aware of a missed checkline sooner, and ranking would be more accurate in the situation where a checkline has been missed.

**Comment by auriamg** [comment]
TrackSector::m_last_valid_graph_node might be usable to fix this

**Comment by auriamg** [comment]
@Hiker I attempted a fix in the linked branch, though I'm very much unsure what side effects this might have

**Comment by auriamg** [comment]
After a discussion with hiker, as I feared, this change may have a negative effect on the AI, since the AI also uses 'm_current_track_coords'. So this simple patch is not quite a good fix
