### ISSUE TITLE
Skidding locking out in the wrong direction

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3168]
I use a keyboard. If I press no left/right key while using the skid key, nothing happens. Usually, when I use the skid key with the left/right key pressed, the kart skids in the direction corresponding to the pressed key.

However, when I try to skid immediately after collecting the big nitro in Abysses, the kart skids in the wrong direction.

It has happened to me four times in a few minutes, so I paid more attention after the first time, and I can absolutely rule out having the wrong direction key pressed.

I thought about a manifestation of "keyboard are evils", but this would be very weird given the only three keys I had pressed where up, skid and left. Not only are they not placed in a way where left could be confused with right ; but I use this very often without issues.

EDIT : happened two more times. The issue is real, the only question is what is the cause. I have a bad framerate on that track (maybe 20-25 FPS) so it may play a role.

**Comment by Mrxx99** [comment]
I also had this issue several times but using a gamepad.

**Comment by Alayan-stk-2** [comment]
We can probably rule out an issue specific to the controller type then.

Were you turning in one direction, then soon after trying to skid in the other when the issue happened ?

For the instances I can recall (I had it happen outside of the nitro collecting place too, it was just very prone to it due to how I had to drive there), this was the case. However, there is some delay between the switching from one direction to another, and when the skid button was pressed the switch had already happened, so in theory the game should have the time to be aware of the new state. Maybe it's a lag issue ?

**Comment by Mrxx99** [comment]
I think it happened when e.g. I was turning left, changed to turning right and started skidding, but I am not shure, will pay more attention when it happens next time

**Comment by Alayan-stk-2** [comment]
I have an instance of the bug happening captured in a video : https://youtu.be/WlYWChV0egQ?t=616

By watching this in slow motion, I think I understand what's going on.

To simplify : 
- At T 0 ; my left key is pressed and my kart steers 100% left
- At T +1 ; I press my right key.
- At T +2 ; I press my skidding key. My right key is pressed, but my kart has not fully transitioned from left steer to right steer. **Because the kart is still in the dominant left steer phase of the transition, it locks out turning to the left while I'm pressing the right key.**

**Comment by deveee** [comment]
Some time ago I had it often on a phone. When you change direction quickly, then it seems to still remember the old direction. But it didn't happen for me for quite long time. And the only modification in multitouch device is that I always release opposite direction before setting left/right action. Anyway I don't know if it matters and I never looked at the details.

**Comment by qwertychouskie** [comment]
I also had this a lot on Android.  I wonder if it is a number of frames issue, and now that physics always runs at 120 tps it is less of an issue, as Android devices often have a low frame rate.

**Comment by Benau** [comment]
alayan beware network rewind when adding 0.1 delay to controller class!
