### ISSUE TITLE
Going in and out of the pause menu at the right time skips the thunderbird starting animation

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3172]
If the title is not clear enough, here is a small video : https://www.youtube.com/watch?v=6rZ8ddxTQns

First case is when using the bug ; second is the normal animation.

I wouldn't be against a slightly faster animation, but that going in and out of the pause menu skips the thunderbird descent is weird.

**Comment by qwertychouskie** [comment]
Honestly, I'd be inclined to keep it, it's pretty harmless, and it keeps the speedrunners happy :)

**Comment by Benau** [comment]
Fixed in network branch
