### ISSUE TITLE
Weight class of karts are (very) unbalanced

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3188]
I suspected the issue from some time ; but after seeing closely how weirdly done are the kart_properties values ; I decided to run a test.

Putting 4 noloks, a gavroche (I used an older build to have the same test_ai, so it used my last player kart, but it's the same weight class as nolok) and 4 pidgins (heavy weight) against each other in time-trial races ; with the same AI for both.

I got +210 by doing so. The maximum possible in a race with those conditions is +10, and there was 42 races. Thats +5 per race. Those were only 4 laps race, which drags things towards 0 in comparison to longer tests.

The test confirms that medium karts are much much superior to heavies.

About specific tracks : all tracks where there is a risk of crashing/braking (and so a need to reaccelerate) had a much superior results for medium karts against heavies, but even on other tracks medium clearly dominated.

In normal races, where items force to reaccelerate often, the unbalance is probably even worse.

EDIT : new tests with noloks against wilbers (lightweight). Result : +252. Even worse. But in regular races with items, the better acceleration of lightweight karts at least partly compensate.

**Comment by psypherium** [comment]
IMHO:  Heavy karts should always get a better time on a track with many straight lines. Light karts should always win a track with many corners. Medium karts should have a good chance against both but not have any specific speciality.

Heavy karts need a higher max speed and slower acceleration. Light karts need better acceleration. Medium karts don't need much change.

**Comment by Alayan-stk-2** [comment]
Light karts already have a very good acceleration. I don't think they need an even better one. I think that 8% less of max speed is too big to overcome in most situation. 4% less (compared to medium karts, can be more compared to heavies) looks plenty enough.

I agree about a higher max speed for heavy karts. The current max speed in SuperTux is 25. This is a very nice number, because 25*4=100. I'd keep medium kart at this speed and push heavies at 25,5 or 26. They already have a slower acceleration.

**Comment by Alayan-stk-2** [comment]
Fixed in the dev branch which will soon be merged back into master.

See #3331 and #3568
