### ISSUE TITLE
Add  text to hover above karts

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#319]
**Author: hikerstk**

See http://i769.photobucket.com/albums/xx340/Turbotrance/turbotrance_ebay_photos/mario-kart-wii-20080219051159780_64.jpg?t=1269883416
for example.

This should also be used to indicate who is the leader in a FTL race, and perhaps also team colors in case of team races (in the future).

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/263

**Comment by auriamg** [comment]
We've had that for a while, closing as outdated
