### ISSUE TITLE
No sound when reaching the target in nitro challenges

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3197]
## Description

The sound of target reaching in nitro challenges is not played when it should in some situations. This is disturbing when one rely on it.

## Steps to reproduce

Get to the target while using some nitro along the way. It looks like if the new nitro total is not _exactly_ the target, no sound will be played.

Exists both in current master and in 0.9.3

## Other

It would also be nice to have a sound played when going under the target after having reached it.

**Comment by auriamg** [comment]
```
void LocalPlayerController::collectedItem(const Item &item, int add_info,
                                          float old_energy)
{
    if (old_energy < m_kart->getKartProperties()->getNitroMax() &&
        m_kart->getEnergy() == m_kart->getKartProperties()->getNitroMax())
    {
        m_kart->playSound(m_full_sound);
    }
```

It should probably detect that the threshold was exceeded, and not strict equality
