### ISSUE TITLE
Last position on the overworld is shared across profiles

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3198]
All profiles share the same last position on overworld.

Expected behavior : it should be a profile-specific variable

Several players using the same STK instance with different profiles and completing the story mode over time is probably not a very common occurrence ; but it's also annoying when creating a new profile, launching story mode, and discovering that the position is not the default starting one.

**Comment by Benau** [comment]
Hows about reset that position to original start if you change player profile, you are speedrunner?

**Comment by Alayan-stk-2** [comment]
Could also work. Probably simpler to do, and yes it's a significant issue only for speedrunners as it means having to change the position, quit the overworld, create a new profile, and start gain ; compared to just traveling to the desired position in the (very) rare case with multiple players doing concurrently the story mode on the same box with different profiles.
