### ISSUE TITLE
Unlock notification when a kart is unlocked

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3209]
Currently, when a challenge is finished, there is an animation showing the cup won and the track/GPs which have been unlocked.

However, there is currently no notification at all that a kart or difficulty has become available (that's why I didn't notice that one of the sara kart is unlocked by candela city). It should be added in a way or another, so the player is aware of what he has unlocked.

- [x] Notification for karts
- [ ] Notification for difficulty
- [ ] Notification for reverse mode ??

**Comment by Mrxx99** [comment]
Sara could also fly out of the treasure chest :)
But don't know for difficulty, maybe the challenge symbol in the material of the cup?

**Comment by Alayan-stk-2** [comment]
If sara could fly out, then I need to figure out why this wasn't the case in my test...

For the difficulty unlocking, I'd suggest a specific separate screen rather than it coming out of the chest.

It's something which happen only once in the whole story mode, and it's rather important, so marking it in a way that can't be missed even if pressing continue quickly when the unlock chest animation happens would be better.

**Comment by auriamg** [comment]
Flying out of the chest is intended, and I'[m pretty sure there is code for that on the cutscene. Maybe it got broken

**Comment by Alayan-stk-2** [comment]
There is a nice comment before the "addUnlockedKart" function (which already exists) :
// unused for now, maybe will be useful later?

And indeed, the only place it is currently used is in the debug entry in the main menu (if compiled with the right debug define). So I wasn't dreaming.

It should be fairly easy to use the function properly.

**Comment by Alayan-stk-2** [comment]
It would also be nice in the unlock message ("You have unlocked Tux !") to add the reason of the unlock. e.g. "You have unlocked Sara the Racer for having completed this challenge" or "You have unlocked Amanda for having reached 190 points" (the number here would be with a %s in the translatable text).

**Comment by Wuzzy2** [comment]
For unlocking SuperTux, I suggest (as a simple fix) to just pop out the SuperTux icon from the treasure chest. And of course write the notification text.

After that, you can still do your separate screen, which I agree is an even better idea.

I don't understand what's the problem with “Reverse mode”. As far I understand, both directions are always unlocked.

**Comment by Alayan-stk-2** [comment]
> I don't understand what's the problem with “Reverse mode”. As far I understand, both directions are always unlocked.

The reverse mode is unlocked from the beginning _now_. But the idea is to make it an unlockable at some point in the future.

**Comment by Wuzzy2** [comment]
I don't really see the point, but OK … I have no strong feelings about it.

But tbh, I'd rather have reverse challenges in Story Mode itself. Currently, all challenges in Story Mode are forwards-only, which is a missed opportunity IMO.

**Comment by Alayan-stk-2** [comment]
> But tbh, I'd rather have reverse challenges in Story Mode itself. Currently, all challenges in Story Mode are forwards-only, which is a missed opportunity IMO.

We know and agree. The issue is that the current overworld is poor to add new challenges, and doubly so when doing two challenges on one track (you can't really fit two bubbles inside the shifting sand pyramid, for example). This should come, but almost certainly not in the next version.
