### ISSUE TITLE
Huge skips for many tracks

### ISSUE THREAD

**Issue by player352** [supertuxkart/stk-code#3219]
Some players discovered that for many tracks, more than the half can be skipped by messing with checkpoints. While this is impressive and good to get minimal times, this kind of breaks this game, as these are not hard to reproduce. I think this needs be fixed for 0.9.4.

Example: https://www.youtube.com/watch?v=tsEpHhJ9X0E

Broken tracks are: Oliver's math class, Nessie pond, green valley, blackhill mansion, fort magma. I might forgot some. They're somehow able to pass through the big door without doing all challenges too (watch around the end).
More over, it seems the grass on Nessie pond dosen't slow you down.

Other example: https://www.youtube.com/watch?v=Xqniag_Khho

This should be easily fixed by adding more checkpoints.

**Comment by Mrxx99** [comment]
Many shortcuts were already fixed in the development version,
See issue #3161 and #3163
Did you see any significant shortcuts that were not adressed there?

**Comment by auriamg** [comment]
Right, they are pretty much all fixed, so should be much better by next version :)
