### ISSUE TITLE
Race indicators are way too small in splitscreen multiplayer

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3221]
The title says it all, here is a picture showing the issue (on 0.9.3 but the scaling hasn't changed with the new meters) in 4:3.

![speedonitrosplitscreen](https://user-images.githubusercontent.com/25536748/39396542-2dcb6c48-4af0-11e8-945e-9a22856f1c0c.png)

Even in 1920x1080 it's just too small.

**Comment by auriamg** [comment]
doesn't seem so bad to me. In split screen, of course compromises will have to be made due to lack of screen space. You could submit a PR to make them slightly bigger,  but there won't be room to make them that much bigger

**Comment by Alayan-stk-2** [comment]
The novice player I played with had difficulty with its nitro especially (speed was less of an issue).

Their size in 2-players splitscreen is the same as in 4-players splitscreen afaict, while the screen assigned to the player is twice as wide (and when it's that wide, having bigger indicators on the side doesn't impede at all the view to drive).

I'll see if I can do a PR for this.

**Comment by Alayan-stk-2** [comment]
I tested it on master, and it seems fine. It was apparently fixed with #3104
