### ISSUE TITLE
The UI checkboxes are too similar between checked and unchecked states.

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3235]
Probably a minor issue, but the checkboxes in the UI look too much alike when checked and unchecked : the background color remain the same, and the cross itself has a small contrast with the background.

This will mostly affect users with a poor eyesight ; but even with a good eyesight, you need to look close to the checkbox itself to get its state ; the difference is too small for the peripheral vision to get it when looking half-a-screen away or so.

Changing the background color when checked or having a more contrasting cross (contrasting color and luminosity) would fix the issue.

**Comment by auriamg** [comment]
Agreed, actually I'd like it if some artist could work on crafting a new, better, GUI skin. The current GUI skin is serviceable, but could be better. Preferably, the new skin should come without being attached to a complete UI redesign that would take weeks/month to implement

**Comment by Alayan-stk-2** [comment]
With some UI skins, it's apparently even worse than what I saw with the ocean one.

![skin](https://user-images.githubusercontent.com/25536748/39830593-2ce8327c-53c2-11e8-9c91-5c9b41ad9423.png)
