### ISSUE TITLE
Placement of the item hud.

### ISSUE THREAD

**Issue by h6899** [supertuxkart/stk-code#3236]
I find the placement of item hud inconvinient, especially in Mulitplayer mode. Because the item hud is placed straight over the karts, it is difficult to see where to drive or shoot. It is an issue because you have to turn to see where other karts are, and then aim without seeing the target. My suggestion is to move the item hud to one of the corners. 

![temple-2018 05 03_17 17 05](https://user-images.githubusercontent.com/8750464/39593200-69d143ee-4f09-11e8-9779-29d57a752731.png)

**Comment by Alayan-stk-2** [comment]
With 16:9 resolutions, you may want to try vertical splitscreen with two players.

What is especially shocking in the picture is that there is a significant margin to display the item higher, closer to the border, but instead the items are displayed nearly over the karts.

All that said, having items more in a corner may be beneficial, I don't know.

**Comment by auriamg** [comment]
The current placement is ok in single-player I think, but I wouldn't mind moving it in split-screen only (even if only move it up a little more, and probably to the side a little)

**Comment by auriamg** [comment]
Fixed by pull request
