### ISSUE TITLE
Ignore this issue for now

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3237]
Just for me to track some TODOs.

- [ ] Change start/stop recording buttons to alert user when STK is not compiled with recorder support - will try PR soon

**Comment by auriamg** [comment]
@qwertychouskie If you want to take notes for yourself, a much better approach is to create a STK fork on github and open an issue in your own fork - there you can do whatever you want. We can't have personal notes on the official but tracker please.
