### ISSUE TITLE
Add the possibility to disable a control configuration without deleting it

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3241]
I'm not sure if this issue is relevant outside keyboards, but it at least exist for them.

It's currently not possible to have a configuration created but inactive. However, it can be handy to have stored configurations you only use in some situations.

The most obvious situation is having one single player configuration, and two/three multiplayer configurations (multiplayer with keyboards is actually quite playable with 2 or 3 keyboards to avoid the "keyboard are evil" issues). As those other configurations also get keys for moving in menus (selecting kart, etc) ; keeping them around means disabling those keys for normal inputs (i.e. : entering some name needing one of the affected keys). But deleting them means having to recreate them the next time they are needed, which is frustrating (especially as there is often some key which is mapped wrong when doing so, needing to check again, change again...)

The option to disable a configuration, but keeping it in memory for easy reuse by simple enabling, gives the best of both worlds.

**Comment by auriamg** [comment]
Gamepads have a "disable device" option, maybe something similar could be used
