### ISSUE TITLE
Icon for unlockable karts/difficulty is not clear

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3248]
(renamed from: "**Inconsistencies regarding SuperTux difficulty in story mode**")

## Description

The needed points for SuperTux get displayed wrong after reaching the limit.
@Alayan-stk-2 : This is regarding your PR #3207 

## Steps to reproduce
(don't know if all steps are necessary, but that's how I got this)

1. change from stable 0.9.3 with all challenges completed to latest git version
2. some challenges will be unsolved (because they were renamed), locked SuperTux icon will display 250 points needed to unlock (you will have less because of the now unsolved challenges)
3. complete challenges until you get 250 point or more (but less than 280, i had 254)

the locked SuperTux  icon will now display 280 points needed, but you can now choose SuperTux difficulty for the challenges.

**Comment by Alayan-stk-2** [comment]
The icon is not there to represent simply the points to get the SuperTux difficulty (it isn't even the SuperTux icon I put in black, iirc, but the intermediate or expert one), it's there to represent an unlockable. There is an earlier unlockable kart at 190 points you've got when converting over ; and there is a later one at 280 (look in your kart list, you should see it's locked).

**Comment by auriamg** [comment]
Some brainstorming from IRC :

> 6:29:04 PM - Auria: that's a bit what I feared, not sure the icon is clear enough
6:30:53 PM - Auria: maybe reuse the treasure chest unsed in the feature unlocked cutscene... unsure
6:31:10 PM - Alayan: But considering what is locked is already displayed in the kart selection screen, putting it that way may not make that much sense, at least when it's the only unlockable remaining
6:31:31 PM - Alayan: Unsure either. Thankfully, once we'll have a good idea, it shouldn't be hard to do
6:31:40 PM - Alayan: The chest is an interesting possibility
6:32:35 PM - Auria: having an icon for points could help too, visually. Let's say we change points into "Nolok coins"
6:32:42 PM - Auria: then story mode is about collecting nolok coins
6:32:50 PM - Auria: then trivially we can use the nolok coin icon to repesent that

**Comment by Wuzzy2** [comment]
How about replacing the icon with a key? It just seems so obvious. In order to unlock (!) a treasure chest (!!), you need a key (!!!) so you can put it into the keyhole (!!!!) and open it . :-)

**Comment by Mrxx99** [comment]
Key is a good idea but it needs to be clear that the number is not the amount of keys collected but the required points to get one

**Comment by Wuzzy2** [comment]
For the record: When I first saw the icon, I (correctly) assumed it was the required score for unlocking *something*. I did not think about SuperTux specifically.

But I can understand that some players might mistake it for SuperTux unlock, because of same shape of the icon.

I doubt the key icon will be problem with >50 points. :D But not sure about that.

Maybe key + question mark will do the trick?
Or maybe a treasure chest icon.
Or maybe treasure chest + key icon to represent “The Act Of Unlocking”(TM). :D

**Comment by Mrxx99** [comment]
![unlock_chest](https://user-images.githubusercontent.com/33566379/48983914-2c8ea600-f0f5-11e8-8a60-105907037dad.png)

**Comment by Wuzzy2** [comment]
Looks nice, but shouldn't the lock be open? :D

**Comment by Mrxx99** [comment]
why should the lock be open? It tells the user that something is locked until the required points a reached. It is also locked in the current icon:
![mystery_unlock orig](https://user-images.githubusercontent.com/33566379/48983992-509eb700-f0f6-11e8-9c21-792013d325a1.png)

**Comment by Wuzzy2** [comment]
The treasure chest is still an obvious improvement, of course.
It seems the lock metaphor goes both ways:

1) WHEN you reach the score, something unlocks
- or -
2) Something *stays* locked UNTIL you reach the score

Seems like the decision for open or closed lock has to be arbitrary. Oh well. In that case, it doesn't really matter, both seem to be right.

Long story short: Good new icon, it's fine.

**Comment by Mrxx99** [comment]
@Alayan-stk-2 

I hope the aliasing is now better. What do you prefer lock icon on the side or in the middle? (also @Wuzzy2 )

![unlock_chest2](https://user-images.githubusercontent.com/33566379/49039601-860fd700-f1c0-11e8-9f66-2df9a875adb6.png)

![unlock_chest3](https://user-images.githubusercontent.com/33566379/49039612-8f00a880-f1c0-11e8-89f2-dd55befd0f2b.png)

**Comment by Mrxx99** [comment]
actually I downscaled a 380 x 440 picture, which has indeed no transparency.

I took that picture:
![2018-11-25 14_52_01-window](https://user-images.githubusercontent.com/33566379/49040284-64175400-f1c2-11e8-9a20-151de510fc13.png)
where the chest also has no transparency and made every pixel of the chest dark

**Comment by Alayan-stk-2** [comment]
The original picture itself is quite aliased... Can you try to see if it is still as aliased when activating anti-aliasing in the graphics option ?

**Comment by Wuzzy2** [comment]
I am fine with the lock position on either place, but I am not fine with the poor aliasing. I 100% agree the “staircase” effect should be fixed.

**Comment by Mrxx99** [comment]
@Alayan-stk-2  So I went into Blender opened the model of the chest and did a black render one time with 4k resolution and one time with 128 pixel. You can try if you can downscale the 4k so that it looks better than the 128 pixel rendered one, I assume you have some knowledge in downscaling.

![black_chest_4096](https://user-images.githubusercontent.com/33566379/49044818-3553aa80-f1cf-11e8-9e5e-c80337aa8d97.png)

![black_chest128](https://user-images.githubusercontent.com/33566379/49044824-397fc800-f1cf-11e8-993f-ef1a555e8efd.png)

**Comment by Alayan-stk-2** [comment]
With some "advanced" interpolation which is probably useful only for upscaling, I got this

![mystery_unlock](https://user-images.githubusercontent.com/25536748/49047520-f5dd8c00-f1d7-11e8-8dc9-4eaf5b792a9f.png)

After doing a simple linear downscaling, I get this : 
![mystery_icon2](https://user-images.githubusercontent.com/25536748/49047796-de52d300-f1d8-11e8-868f-a79420658d24.png)

**Comment by Mrxx99** [comment]
@Alayan-stk-2 You were right, the second one was a wrong picture (that one I uploaded before). I now replaced the small one with that one actually rendered by blender.

**Comment by Alayan-stk-2** [comment]
@Mrxx99 But I used the 4K one as a base. I was simply surprised that the top and bottom of the chest are so far from being parallel
