### ISSUE TITLE
Navigation problems with gamepad (and keyboard) at some places

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3249]
## Description

When navigating with a gamepad there are some issues:

1. When you select soccer mode, it quickly skips the team selection screen.
Going back and selecting a team works.
2. You can't go out of soccer mode with a gamepad. You can go back til the team selection screen but from there you need keyboard/mouse to go back to mode selection.
3. If you watch a ghost race, you can't open the pause menu with the controller, only with keyboard
4. If you go to the addon menu and select an addon the focus is set to back, you will press left to select install, that is left of back, but then the focus is not visible anymore and you have to press up/down/left/right randomly until you somehow get the focus on install. you can get the focus immediately to install if you press up at start, but you first need to figure that out that you have to press up there to go left (this is also the same with the keyboard) 

## Configuration

STK release version: 0.9.3 til current git master

STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:

System:
Windows 10 64bit

Graphics card: Intel HD Graphics 5500 898MHz

CPU: Intel Core i5-5200U 2.20GHz (2 Cores)

Gamepads/keyboards models if related to the issue: NVIDIA SHIELD controller 2017

## Additional information
input.xml
<input version="1">

<keyboard enabled="true">
    <action name="steerLeft" id="37" event="1" character="0" />
    <action name="steerRight" id="39" event="1" character="53" />
    <action name="accel" id="38" event="1" character="53" />
    <action name="brake" id="40" event="1" character="53" />
    <action name="nitro" id="78" event="1" character="53" />
    <action name="drift" id="86" event="1" character="53" />
    <action name="rescue" id="8" event="1" character="53" />
    <action name="fire" id="32" event="1" character="53" />
    <action name="lookBack" id="66" event="1" character="53" />
    <action name="pauserace" id="27" event="1" character="53" />
    <action name="menuUp" id="38" event="1" character="53" />
    <action name="menuDown" id="40" event="1" character="53" />
    <action name="menuLeft" id="37" event="1" character="53" />
    <action name="menuRight" id="39" event="1" character="53" />
    <action name="menuSelect" id="13" event="1" character="53" />
    <action name="menuCancel" id="8" event="1" character="53" />
</keyboard>

<keyboard enabled="true">
    <action name="steerLeft" id="0" event="0" character="53" />
    <action name="steerRight" id="0" event="0" character="53" />
    <action name="accel" id="0" event="0" character="53" />
    <action name="brake" id="0" event="0" character="53" />
    <action name="nitro" id="0" event="0" character="53" />
    <action name="drift" id="0" event="0" character="53" />
    <action name="rescue" id="220" event="1" character="53" />
    <action name="fire" id="9" event="1" character="53" />
    <action name="lookBack" id="20" event="1" character="53" />
    <action name="pauserace" id="27" event="1" character="53" />
    <action name="menuUp" id="0" event="0" character="53" />
    <action name="menuDown" id="0" event="0" character="53" />
    <action name="menuLeft" id="0" event="0" character="53" />
    <action name="menuRight" id="0" event="0" character="53" />
    <action name="menuSelect" id="9" event="1" character="53" />
    <action name="menuCancel" id="20" event="1" character="53" />
</keyboard>

<gamepad name ="NVIDIA Controller v01.04" deadzone="4096" desensitize="0" analog="1"
         enabled="true">
    <action name="steerLeft" id="0" event="2" character="53" direction="0" range="0" />
    <action name="steerRight" id="0" event="2" character="53" direction="1" range="0" />
    <action name="accel" id="4" event="2" character="48" direction="1" range="1" />
    <action name="brake" id="3" event="2" character="53" direction="1" range="1" />
    <action name="nitro" id="8" event="3" character="53" />
    <action name="drift" id="7" event="3" character="53" />
    <action name="rescue" id="9" event="3" character="53" />
    <action name="fire" id="11" event="3" character="53" />
    <action name="lookBack" id="10" event="3" character="53" />
    <action name="pauserace" id="13" event="3" character="53" />
    <action name="menuUp" id="100" event="2" character="53" direction="1" range="0" />
    <action name="menuDown" id="100" event="2" character="53" direction="0" range="0" />
    <action name="menuLeft" id="101" event="2" character="53" direction="0" range="0" />
    <action name="menuRight" id="101" event="2" character="53" direction="1" range="0" />
    <action name="menuSelect" id="11" event="3" character="53" />
    <action name="menuCancel" id="13" event="3" character="53" />
</gamepad>

<gamepad name ="NVIDIA Controller v01.04 0" deadzone="4096" desensitize="0" analog="1"
         enabled="true">
    <action name="steerLeft" id="0" event="2" character="53" direction="0" range="0" />
    <action name="steerRight" id="0" event="2" character="53" direction="1" range="0" />
    <action name="accel" id="4" event="2" character="53" direction="1" range="1" />
    <action name="brake" id="3" event="2" character="53" direction="1" range="1" />
    <action name="nitro" id="8" event="3" character="53" />
    <action name="drift" id="7" event="3" character="53" />
    <action name="rescue" id="9" event="3" character="53" />
    <action name="fire" id="11" event="3" character="53" />
    <action name="lookBack" id="10" event="3" character="53" />
    <action name="pauserace" id="13" event="3" character="53" />
    <action name="menuUp" id="100" event="2" character="53" direction="1" range="0" />
    <action name="menuDown" id="100" event="2" character="53" direction="0" range="0" />
    <action name="menuLeft" id="101" event="2" character="53" direction="0" range="0" />
    <action name="menuRight" id="101" event="2" character="53" direction="1" range="0" />
    <action name="menuSelect" id="11" event="3" character="53" />
    <action name="menuCancel" id="13" event="3" character="53" />
</gamepad>

</input>

**Comment by Alayan-stk-2** [comment]
For the ghost race, this is a known (and annoying) issue.

Basically, all keys are disabled in "watch-only mode" except "look back" (and artist debug mode combinations). You can get in pause with escape, but if you've assigned this function to another key, that other key won't work. So with a gamepad, as you don't have an "escape" key on it, you can't do anything.

**Comment by Alayan-stk-2** [comment]
The issue in watch-only mode for ghosts should be fixed in the ghost improvements branch. I'm able to open the menu in-race and navigate in it with my keyboard (with a key other than escape assigned to the pause menu), and so if the gamepad has a correct binding it should work with it too.

**Comment by deveee** [comment]
1, 2, 4 are now fixed in current git and Alayan said that ghost race is fixed too.
