### ISSUE TITLE
Huge shortcuts in reverse

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3250]
- [x] Hacienda : aside from the "go through sand" shortcut, it's also possible to mostly avoid to do the loop. Video : https://www.youtube.com/watch?v=PYntpFwI9mo
- [ ] XR591 : look just after the start... https://www.youtube.com/watch?v=tkqKA9xVT7k - Otherwise, there are also big issues with the unevenness of the road (there are some instances at several points, but by far the worse is shortly before the end of a lap in reverse)
- [ ] Northern Resort : the shortcut involves jumping from one part to another where you're not supposed to. It also exists in normal direction, but it is much easier to pull off in reverse, see https://www.youtube.com/watch?v=RBxnx8l16-0

**Comment by auriamg** [comment]
Hacienda done

**Comment by auriamg** [comment]
XR591 done

**Comment by auriamg** [comment]
Northern resort done
