### ISSUE TITLE
Redo standard ghost replays

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3251]
The standard ghost replays must be redone before the next major releases : 
- To use the new ghost replay features
- Because there are some changes affecting gameplay (currently, I can only think of the nitro spending bugfix, there will probably be some others)
- Revamped tracks would also require an updated replay file

It should be only done when the RC is rather close, as to make sure that no gameplay changes will be introduced between the replay recording and the release.

The overall process is easy (I could do them or publish a list of track/karts/difficulty with time targets to match) However, I'm not sure what name should be displayed as the owner of the replay file - none at all would be weird ; should it be the kart's name, the replay's author nickname, or something like "STK team" ?

**Comment by hiker** [comment]
I am happy to leave it to the driver: either STK team, None, or the name of the creator.

**Comment by Arthur-D** [comment]
STK team would in my opinion be the better choice as it would be easier for everyone to remember where the ghost replays came from.

**Comment by Alayan-stk-2** [comment]
I have done replays for normal directions for the 18 tracks which are not expected to change before release. Hacienda, Green Valley/Black Forest and the mansion track have no standard replay yet.

The replays use this user name : 
 ☆★STK★☆

**Comment by Alayan-stk-2** [comment]
Waiting on the fixes for Ravenbridge Mansion and for the definitive Black Forest version to do the last two replays.

**Comment by Alayan-stk-2** [comment]
Replays for tracks with modified nitro (which was used by the replay ghost) have been updated, and a ravenbridge mansion replay has been added.

Waiting on the confirmation of the track which will ship in the next version (green valley or black forest) to do the last replay.

Also, if the next version is not named 0.10, the STK version info will have to be changed in all the standard replays.

**Comment by Alayan-stk-2** [comment]
Black Forest replay done. Now each track has a standard replay, and each kart has a replay too. All 4 difficulties have several replays, the track with a novice replay also got a SuperTux replay in reverse.
