### ISSUE TITLE
Cornfield crossing cannon/jump : possible to fall in water while visually going over the booster

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3255]
It happens on the left side of the cannon/jump.

Video showing the issue : https://www.youtube.com/watch?v=cJrkIa7kdgM

Picture showing a frame where the issue is obvious : 
![kart going through the booster](https://user-images.githubusercontent.com/25536748/40090356-9eae870a-58b1-11e8-923b-6fd8a74f6c91.png)

**Comment by auriamg** [comment]
Fixed
