### ISSUE TITLE
Distance "freezes" when going off-road

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3261]
This issue is very likely related to the patch fixing #3167. When going off-road, the distance for the kart remains fixed at what it was the last time the kart was on track.

While checking for checklines is important when interpolating the kart to be on a given track section based on his current position (avoiding interpolating the kart to be ahead of his real position) ; completely stopping the interpolation is indesirable.

The main effects are : 
- The positions computations will be less correct each time a track goes off-road, even slightly, a second or two, before going back on-road ; for example when cutting through grass on lighthouse.
- The distances stored in the v4 replays (and used for the live difference feature) are bogus when the kart go off-road.
- It may affect other pieces of code using that distance code. However, they probably shouldn't, as if they're trying to measure if a given kart is close, this isn't the most appropriate way of doing so.

A similar issue, for which I don't open a ticket yet as I'm not sure if it's different enough to warrant so, is that the distance "freezes" while in "cannons" (those things which move a kart from a position to another at a fixed speed, like in cornfield crossing). This usually isn't an issue for positions (you can't gain or lose a place while in them), but it still makes the distances for the live difference incorrect.

**Comment by auriamg** [comment]
That's expected, it's a known limitation of the fix to #3167. This should be fairly harmless as it's pretty rare to drive off-road for extensive periods of time. Fixing that would almost certainly enable cheats

**Comment by Alayan-stk-2** [comment]
Was fixed in https://github.com/supertuxkart/stk-code/commit/02859b673e2272bf5374145e0d79f55726baf6ff
