### ISSUE TITLE
Smaller karts have bigger turning radius

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3271]
Bigger karts like Wilber have a smaller turning radius, and smaller karts like Adiumy have a bigger turning radius, which is completely counter-intuitive (and also part of why the AI has so much trouble with Adiumy, though the equation for calculating the turn radius is also wrong).  Also see https://github.com/supertuxkart/stk-code/issues/3227, which is for the AI, but has some related info.

**Comment by Alayan-stk-2** [comment]
The goal should be to have all karts sharing the same weight-class having the same turn radius. It would make balancing much easier, and if then uniformity is judged to be an issue, the medium class (~50% of STK's karts) could be split in two.
