### ISSUE TITLE
Use UTF-8 rather than UTF-16 for some config/data files

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3274]
Some config/data files like players.xml are stored in UTF-16 format.

UTF-16 files are not well supported by some text editors (typically gedit ; and while those editors are at fault in not supporting it correctly, it creates real annoyances), they take more space (>95% of chars in those files are ASCII), they require a conversion layer. There is no upside I can think of in having them that way.

Considering that the next version will require a new config folder anyway, it may be a good opportunity to switch the encoding of those files from UTF-16 to UTF-8.

**Comment by auriamg** [comment]
Agreed, at the time utf-16 was used because we had to store the player name, which may contain accentuated characters, but we didn't have a UTF-8 converter. Now we have StringUtils::wideToUtf8 and StringUtils::utf8ToWide, so the original reasoning no longer holds and we should use utf-8.

**Comment by deveee** [comment]
Do you prefer convert string before writing to file and after reading from file? Or store player name and other data as utf-8 string and use utf-8 everywhere it's needed? Because in second case it would be huge modification.

**Comment by auriamg** [comment]
just this specific file, the first case you describe

**Comment by auriamg** [comment]
Work started in branch UTF8_Config ( 42d98f8ff12cda393bdf527fa20178fbf50400ee ) , not fully tested yet

**Comment by auriamg** [comment]
Fixed
