### ISSUE TITLE
Zipper speed limit properties do not take kart type into account

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#3278]
## Description
When testing a track I've been trying to make, I found that the min-speed property for zipper textures does not enforce light karts getting this speed, and thus they fail the jump. If I choose a medium or heavy kart I do get across like I should, even if I start at no speed. Similarly, the max-speed property which I've set to be the same as the min-speed does not make sure a heavy kart doesn't jump further than the medium kart. Currently, only medium class karts behave exactly like expected, and for the min-speed it's rather catastrophic as those never get across.

What I would expect with min-speed and max-speed set to the same value would be that all karts would get the exact same speed when jumping, and thus all land in the same spot (barring steering differences).

## Steps to reproduce
You can test the jump I have: https://cloud.pspodcasting.net/index.php/s/p68AX9wRYCWgKXZ
You'll have to drive for half a minute to get there (can move start position if wanted), but you only need to test a few times anyway.

STK Source (ppa, distribution package, official bin,...): git

**Comment by Alayan-stk-2** [comment]
Test case unusable ; the kart is rescued mid-air.

**Comment by Alayan-stk-2** [comment]
Considering that what matter is the speed when leaving the zipper, I added some prints.

Both medium and light karts have their min_speed set at 10.727. In instances where I wasn't rescued, the light kart could correctly cross the gap. And looking at the code, there is no reason at all for kart classes to affect this.
