### ISSUE TITLE
Better icon?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3285]
IMO STK's icon used the the launcher does not look all that good, and when small kinda just looks like a red blob.  My proposal is to use `gui/main_race.png` for 128x128 and smaller as it's simplicity means it looks like something more than a blob, and use `gui/logo.png` for all bigger sizes (e.g. Android app icon, gnome-shell launcher) as it is big enough to be properly visible.

I actually made a version of `main_race.png` from the svg in the media repo that looks a bit better as a small icon: [iconsmall.svg.txt](https://github.com/supertuxkart/stk-code/files/2082679/iconsmall.svg.txt) (remove the .txt)

Here's how it looks:

16:
![iconsmall16](https://user-images.githubusercontent.com/13989090/41136500-160bd138-6ac6-11e8-8477-fc0fe70cd21d.png)

32:
![iconsmall32](https://user-images.githubusercontent.com/13989090/41135780-b9ea0a44-6ac2-11e8-845d-12060483b252.png)

48:
![iconsmall48](https://user-images.githubusercontent.com/13989090/41186675-27e7d784-6b8a-11e8-9fca-610bff03f396.png)

64:
![iconsmall64](https://user-images.githubusercontent.com/13989090/41135792-bf61762e-6ac2-11e8-9291-7a5ddd158242.png)

128:
![iconsmall128](https://user-images.githubusercontent.com/13989090/41135804-ca94ed64-6ac2-11e8-9bb3-b89b50ff7d82.png)

And the full logo:
128:
![logo128](https://user-images.githubusercontent.com/13989090/41186709-9c462d42-6b8a-11e8-873f-5f59d712d219.png)

256:
![logo256](https://user-images.githubusercontent.com/13989090/41186712-a297ed2a-6b8a-11e8-89bd-cbdd033c41d3.png)

512:
![logo](https://user-images.githubusercontent.com/13989090/41186714-a9129d6c-6b8a-11e8-8d25-db8fa78c3ccd.png)

**Comment by Alayan-stk-2** [comment]
I agree that the launcher's icon doesn't look nice. I'm not so sure about the proposed replacement, however.

**Comment by qwertychouskie** [comment]
My icon:
![screenshot_2018-06-18_15-06-22](https://user-images.githubusercontent.com/13989090/41564929-6a56dd82-7309-11e8-9114-2ff75b152bdb.png)
`logo_slim`:
![screenshot_2018-06-18_15-07-46](https://user-images.githubusercontent.com/13989090/41564930-6a775076-7309-11e8-965b-08a2aa0316a3.png)

I think we need a forum poll.

**Comment by OzoneOne** [comment]
The steering wheel looks really good as an icon I think

**Comment by Benau** [comment]
You already did a poll in forum
https://forum.freegamedev.net/viewtopic.php?f=17&t=7968
