### ISSUE TITLE
Compiling network branch (past) on windows

### ISSUE THREAD

**Issue by Splamy** [supertuxkart/stk-code#3287]
When compiling, cmake specifies linking against the OpenSSL library `libeay32.lib`.
Starting from OpenSSL 1.1.0 `libeay32.lib` doesn't exist anymore and `libcrypto.lib` is used instead.
Linking against this library seems to work. I could successfully compile and run stk.

I am using stk commit d5b4d886ceba427786faea6726fd28ba2d6b133f
and OpenSSL 1.1.0g

I changed this line to test this:
https://github.com/supertuxkart/stk-code/blob/cb8f519bd996a3a08bb81113cdb507de48ac7489/CMakeLists.txt#L462

**Comment by Benau** [comment]
why don't you use our official dependencies? https://github.com/supertuxkart/dependencies/tree/master/windows_64bit/dependencies/lib

**Comment by Splamy** [comment]
Oops, i downloaded the one from [sourceforge]( https://sourceforge.net/projects/supertuxkart/files/SuperTuxKartDependencies/Windows/dependencies_for_0.9.3-64bit.zip ) as it was the first link in the (old) readme.
Well that would've made it easier.

**Comment by Benau** [comment]
U can use master from now on
