### ISSUE TITLE
Improve menu navigation with keyboard and gamepads

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3295]
Currently, STK menus are exclusively navigated from element to element with the up-down buttons (the tab button also do the same thing as the down button), and inside an element with the left-right button.

This is non-intuitive and can make accessing to a desired element with a keyboard/gamepad rather hard.

Ideally, up/down/left/right would find the closest matching element or sub-element situated in the required direction and switch to it.

Roadblocks to clear : 
- determine the relative position of the widgets
- make sure it's not possible to be trapped within an element having some kind of scrolling

**Comment by Mrxx99** [comment]
What's really confusing is the navigating in the addon manager. You have to press up or down to go to the side for the top filters

**Comment by Alayan-stk-2** [comment]
Most menus aren't too bad because they have been designed with this limitation in mind and so have a vertical flow ; or use specialized widgets which allow internal navigation in all directions.

The addon manager is a case where this would be useful, as reorganizing the filters to be aligned vertically would also require vertical tabs.

Then, add in something like #1844 to fill in the remaining place, and this menu should be much better.
