### ISSUE TITLE
The new checkline in Oliver Math Class can be too easily missed

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3301]
Steps to reproduce : 
1)Go fast over the second ruler
2)Make sure to go rightward enough so that the kart will go through the door, rather than hitting the wall straight ahead of the ruler.

With enough speed, the jump is high enough that the checkline is not triggered.

**Comment by deveee** [comment]
I moved the checkline to slightly different place and it should be fixed in current svn.
