### ISSUE TITLE
If the user keeps pressing a navigation key in a menu, it should navigate faster

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3304]
In a lot of programs allowing navigation with a key/button, keeping the key/button pressed long enough will trigger a faster navigation between items.

This is especially useful when navigating lists (language, addons, ghost replays) without the mouse, where the current navigation rate feels really sluggish.

EDIT : Also, several close separated inputs should not be throttled. This makes the menu feels very unresponsive.

**Comment by deveee** [comment]
I reverted the pull request, because it causes issues for navigation with gamepad:
https://github.com/supertuxkart/stk-code/issues/3527
And it behaves the same for my gamepad on linux too.

**Comment by Alayan-stk-2** [comment]
@deveee Do you have an idea of what exactly in the PR caused the gamepad bug ? It may be worth a try to see if it can be fixed while keeping the good behavior on keyboards.

**Comment by Benau** [comment]
you can latest master if good for you...

**Comment by Alayan-stk-2** [comment]
Looks good.
