### ISSUE TITLE
Missing character models on nouveau driver (NV5)

### ISSUE THREAD

**Issue by brion** [supertuxkart/stk-code#3308]
(First just want to say thanks to everyone who helps maintain this game -- it's good fun and has brought me plenty of joy over the years!:) )

## Description

Character and kart models are not appearing on my old MacBook Pro running Linux, unless I crank graphics settings all the way down to 0.

![broken models in stk](https://user-images.githubusercontent.com/103075/41488497-5b05905e-70a1-11e8-96e9-60a194a8bf7c.png)
![not right](https://user-images.githubusercontent.com/103075/41488501-5db081ec-70a1-11e8-8b4d-1b890329965c.png)

Workaround: set graphics settings to 0.

## Steps to reproduce

* install SuperTuxKart 0.93 from flathub or Fedora 28 repository
* launch
* start Story Mode
* notice the GNU guy and the evil bad guy are missing, though other models (houses, vehicles) are visible.
* notice that in character/kart selection and game play, only wheels are visible on the vehicles

## Configuration

STK release version: 0.93

STK Source: flathub package and Fedora 28 package, same results

System: 

* Fedora 28
* MacBook Pro 6,2 (2010 15" dual-GPU)

Graphics card: 
* Nvidia 330M (NV5), using nouveau driver

CPU: 
* x86-64 i7-something (2 core/4 threads)

Gamepads/keyboards models if related to the issue:
* n/a

## Additional information

[stdout.log](https://github.com/supertuxkart/stk-code/files/2107430/stdout.log)

**Comment by qwertychouskie** [comment]
I think this may have been fixed in the git version, could you try compiling it to see?

**Comment by brion** [comment]
@qwertychouskie can confirm still present on a local build from git master.

@deveee yeah looks like the same bug. Thanks for the pointer!

(Closing out as dupe of https://github.com/supertuxkart/stk-code/issues/3058 )
