### ISSUE TITLE
Resolution did not change using a setup. Where is a config file?

### ISSUE THREAD

**Issue by JTS2** [supertuxkart/stk-code#3330]
## Description

Supertuxkart version 0.9.2-2.mga6 did not change grafics display resolution. Choosing 16:9 1366 x 768 did not change resolution only restart the program in the same default resolution 4:3  1024 x 768.

Where is the config file for that? Can I write the new resolution to the config file directly?

Provide a description of your issue.
For any suggestions, please address them on the [forum](https://forum.freegamedev.net/viewforum.php?f=16).

## Configuration

STK release version:

STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:

System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue:

## Additional information

Please provide stdout.log, it is located in

* %appdata%\supertuxkart\0.8.2 (windows)
* ~/Library/Application Support/supertuxkart/0.8.2 (mac)
* $XDG_CONFIG_HOME/supertuxkart/0.8.2 or ~/.config/supertuxkart/0.8.2 (linux, and other unix based systems)

stdout.log
```

```

If your issue is related to the input config (gamepads, keyboards), please provide your file input.xml located in the same directory as stdout.log.

input.xml
```xml

```

If an error message was shown, please copy paste the complete error message or a screenshot of it.

error
```

```

**Comment by deveee** [comment]
Try STK 0.9.3, there was one fix related to changing resolution.
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3/supertuxkart-0.9.3-linux.tar.xz/download

And just to make sure, the 1366 x 768 is your default resolution that was set before STK was launched? Because you can only set resolution that is <= your desktop resolution.

**Comment by Alayan-stk-2** [comment]
@deveee Can this be closed ?

**Comment by deveee** [comment]
Please reopen if it still happens in current version.
