### ISSUE TITLE
Multiple GPLv3 violations

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3344]
(See https://github.com/supertuxkart/stk-code/pull/2647 for the original discussion.)

From https://www.gnu.org/licenses/gpl-faq.en.html#WindowsRuntimeAndGPL:

>You may link your program to these libraries, and distribute the compiled program to others. When you do this, the runtime libraries are “System Libraries” as GPLv3 defines them. That means that you don't need to worry about including their source code with the program's Corresponding Source. GPLv2 provides a similar exception in section 3.
>
> You may not distribute these libraries in compiled DLL form with the program. To prevent unscrupulous distributors from trying to use the System Library exception as a loophole, the GPL says that libraries can only qualify as System Libraries as long as they're not distributed with the program itself. If you distribute the DLLs with the program, they won't be eligible for this exception anymore; then the only way to comply with the GPL would be to provide their source code, which you are unable to do.

It seems linking against the versioned DLL is a violation of the GPL, as they are not technically a part of the OS.

There are a few potential options here:

1. Find a way to force VS to link against the unversioned DLL, which comes with Windows.  This may be hard because it is officially frowned upon. See https://stackoverflow.com/questions/10166412/how-to-link-against-msvcrt-dll-instead-of-msvcr100-dll-in-vc-10-0 and https://blogs.msdn.microsoft.com/oldnewthing/20140411-00/?p=1273

2. Only build with MinGW, which links against the unversioned DLL (see https://news.ycombinator.com/item?id=11964589).

3. Use the LGPL-licensed DLL from Wine/ReactOS: <http://source.winehq.org/git/wine.git/tree/HEAD:/dlls/msvcrt>  As long as STK has a copy of the DLL's code in the source, everything should be legal.

4. Something else that I'm not thinking of ;)

**Comment by qwertychouskie** [comment]
Uh oh, OpenSSL is also a problem: https://www.gnu.org/licenses/license-list.en.html#OpenSSL

**Comment by qwertychouskie** [comment]
I just found https://www.openssl.org/blog/blog/2017/03/22/license/ but this seems to have never been completed (the `LICENSE` file in the latest source is still the old one).

**Comment by hiker** [comment]
According to:
https://license.openssl.org/trying-to-find
it looks like they have found all contributors - so maybe they are getting close, and openssl becomes a none issue in the very near future??

**Comment by deveee** [comment]
Regarding to https://github.com/supertuxkart/stk-code/pull/2647 and just to write it in better place... I wonder if libvpx statically linked with msvc is gpl violation. I'm not sure, because we don't use it directly and openglrecorder is not GPL. But it's included in our package. Anyway using mingw version is simple.

If it's really so easy to violate GPL, what about our static packages? STK 0.9.3 contains openssl even though it doesn't use it directly (it's curl dependency). Can we consider that it's still system library if it's included in the package?

And I don't like the idea of using gnutls, because it has more dependencies - worse compatibility in different systems etc.

In worst case can we load it dynamically in runtime?

And regarding to "Linking against versioned msvcrt" most of our dependencies are compiled using mingw. It's not just because of GPL violation, but it's also to avoid depending on particular msvc version that may be not available in system. But main contributors use VS on windows and STK can be properly tested on this environment, so I don't think that mingw STK build will happen. I like the idea of using mingw though and I use it myself when I need windows builds.

**Comment by qwertychouskie** [comment]
I opened an issue in their repo (https://github.com/openssl/openssl/issues/6850), hopefully we'll get an answer soon.  What exactly is OpenSSL used for in STK?  It used to be you could use openssl or gnutls.

**Comment by qwertychouskie** [comment]
"The work is ongoing. It's going to be some while yet before we can do it. It won't be done in time for our 1.1.1 release." (https://github.com/openssl/openssl/issues/6850#issuecomment-410184899)

:(

**Comment by Benau** [comment]
use nettle?

**Comment by qwertychouskie** [comment]
Has anyone tried to use Nettle in the Windows builds yet?

As far as I can tell, linking against versioned MSVCRT libs is fine if you *don't* distribute the installer with STK.  The best option for official builds is probably MinGW, leaving MSVC for devs only.  Some info on getting the stacktrace on MinGW builds: http://theorangeduck.com/page/printing-stack-trace-mingw

**Comment by hiker** [comment]
I've created a VS static binary, and verified it on a clean installation of windows: The dynamic binary does not rnu (since I didn't install the redistributable package), but the static one works. I need to verify that this is still the case for 64 bit

**Comment by qwertychouskie** [comment]
Whether static or dynamic linking, it's still linking against a non-GPL-compatible library that is not eligible for the "System Library" exception.  Honestly Wine/ReactOS's msvcrt is probably the best option.  I'll try to test soon to verify that STK works with this version of the library.

**Comment by hiker** [comment]
We are now considering using mingw for the release, so am closing this ticket now.

**Comment by qwertychouskie** [comment]
@hiker Sounds great, though the OpenSSL issue still stands, this should be reopened until the Windows builds have been ported to avoid OpenSSL both directly and indirectly through Curl.  Also https://github.com/supertuxkart/stk-code/pull/3715 has not been merged yet.  (There was a small string change there, I'll force-push to remove the change since we entered string freeze.)

**Comment by Alayan-stk-2** [comment]
It appears that mingw wasn't used for the 1.0 release.

**Comment by Benau** [comment]
mingw is now used ![](https://lihkg.com/assets/faces/pigxm/whip.gif)
