### ISSUE TITLE
Story mode Mission difficulty selection screen sometimes can not be exited.

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3352]
Story mode Mission difficulty selection screen sometimes can not be exited.

I'm not exactly certain how to reproduce, sometimes it works normally.

**Comment by psypherium** [comment]
try with a profile from previous version maybe

**Comment by Alayan-stk-2** [comment]
I haven't had the issue atm. Without further steps to reproduce it reliably, it may be quite difficult to fix. I've read in the other issue that it's not easy for you to get footage ; but it could help greatly to understand how this happen.

**Comment by Alayan-stk-2** [comment]
After some investigation, this modal dialog handles its closing only in the case where a challenge is selected.

The only way to close it without selecting one is to press the cancel key, which calls a generic modal dialog closing, and it works just fine when I test it. I see no reason for it to work sometimes, and sometimes not, unless something intercepts the key press.

Please comment back if you can still reproduce this issue.
