### ISSUE TITLE
Crash after open on Lineage OS.

### ISSUE THREAD

**Issue by githubtefo** [supertuxkart/stk-code#3355]
## Description

Provide a description of your issue.
For any suggestions, please address them on the [forum](https://forum.freegamedev.net/viewforum.php?f=16).
The game screen move to a second plane immediately after open the app and the game never start.
## Steps to reproduce
Install from the F-droid store and open the app.
## Configuration
Lineage OS 14.1
STK release version:
last on F-droid
STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:
F-droid
System: 

Graphics card: 

CPU: 
Lineage OS 14.1
Gamepads/keyboards models if related to the issue:

## Additional information

Please provide stdout.log, it is located in

* %appdata%\supertuxkart\0.8.2 (windows)
* ~/Library/Application Support/supertuxkart/0.8.2 (mac)
* $XDG_CONFIG_HOME/supertuxkart/0.8.2 or ~/.config/supertuxkart/0.8.2 (linux, and other unix based systems)

stdout.log
```

```

If your issue is related to the input config (gamepads, keyboards), please provide your file input.xml located in the same directory as stdout.log.

input.xml
```xml

```

If an error message was shown, please copy paste the complete error message or a screenshot of it.

error
```

```

**Comment by githubtefo** [comment]
It was a ssd space issue. I deleted some files and now it works great!

**Comment by deveee** [comment]
Ideally I would like to show toast message when error ocurred. It would give you an information what happened. I already made some work and we get pause/focus/destroy events from UI thread, so maybe now toast messages would work too. I will try it later. And if not, then it's a wontfix until we will use pure native activity or java.
