### ISSUE TITLE
Version numbers for network protocol

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3359]
Atm there is a version number for the network protocol, but it is only 8 bit, so I heard the argument that even though we updated the protocol, we shouldn't update the version number, since we only have 8 bits. Which then results in (mostly client) crashes when they couldn't process a server state message.

We need to extend the version number to full 4 bytes. Also (not sure if this is already the case):
- grey out servers that have an unsupported network protocol version number
- maybe display the network version number in the server screen?

Imho we should use the 8 bits for a minor version, i.e. the protocol has changed, but is still compatible (example: we could decide to compress one value. Then a client should be able to check if the server's protocol version number is 'old', expect an uncompressed value, otherwise expect a compressed value - this way the two protocol versions would be compatible. That could be useful to add minor bug fixes or improvements without having to recompile all servers)

**Comment by Benau** [comment]
Use network capabilities as seen in c38278fbc1f060bd5ed731835e0e0d055443b9e7 for the same task
