### ISSUE TITLE
Track Abyss - missing glasses 

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#3360]
Hi,
    In the track Abyss, there are some missing glasses in one tunnel (cf. pictures) + some misaligned things.
Keep Cool ;)
![bug](https://user-images.githubusercontent.com/2879782/43675670-2894c2ec-97e4-11e8-9d82-1a56e9307f04.jpg)
![bug2](https://user-images.githubusercontent.com/2879782/43675671-2a569b00-97e4-11e8-94b8-6b4f7ede23a3.jpg)
![bug3](https://user-images.githubusercontent.com/2879782/43675672-2c7cddc2-97e4-11e8-808e-0ab09285cfca.jpg)

**Comment by Alayan-stk-2** [comment]
@Benau Still an issue
