### ISSUE TITLE
Track Abyss - Misaligned ground texture

### ISSUE THREAD

**Issue by rogue-spectre** [supertuxkart/stk-code#3363]
Hi,
     One can see in the picture that the stone ground texture is going a bit too far over the track. It can be spotted with the shadow.
![bug_stone](https://user-images.githubusercontent.com/2879782/43675860-6b0929d0-97e7-11e8-8d73-b2409d354ec8.jpg)

**Comment by Alayan-stk-2** [comment]
@Benau Still an issue
