### ISSUE TITLE
Display kart model info for replays

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3365]
Currently, if you want to know if a given replay uses e.g. Tux, Nolok, Kiki, Sara... you need either to open the replay file manually outside the game, or to watch the replay.

It would be better if it was possible to ascertain this directly in the replay list, or at least when opening the replay info dialog.

There is not much free space in the UI, however (you can already have up to 8 columns if you choose to show replays from all version, all difficulties ; 6 columns in the info dialog but there is less space for them, though the dialog itself could be expanded) ; so I'm not sure about the best way to proceed.

**Comment by Benau** [comment]
Display kart icon in the list(like addons / lobby icon)
