### ISSUE TITLE
Story Mode: Blackhill Mansion Expert Challenge wrong required time

### ISSUE THREAD

**Issue by Shaevor** [supertuxkart/stk-code#3369]
## Description

In the Blackhill Mansion Challenge, Expert has a required time of 2:10:00, the same as Intermediate. I suspect that the Expert time should be lower, because now it is not more challenging than the Intermediate Challenge.

## Steps to reproduce

In the Story Mode, go to the Blackhill Mansion Challenge (in the center of the map, on the right side of the central road segment) and press Fire to see the difficulty selection screen of the challenge.

## Configuration

STK release version: 0.9.3

STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:

System: Windows 10 64bit

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue:

**Comment by Alayan-stk-2** [comment]
Not applicable in current development version.
