### ISSUE TITLE
Unintuitive goal line in Las Dunas soccer

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3381]
The effective goal lines used for scoring don't match well visual cues. They're situated before the goalposts.

Worse, situations were you'd expect the ball to rebound on the goalposts lead to goals, which is confusing.

**Comment by Arthur-D** [comment]
Fixed in svn.

**Comment by Benau** [comment]
The goal line is now brought back again so server owners please svn up stk-assets again
