### ISSUE TITLE
Can't change player's name in multiplayer kart selection with keyboard/gamepad navigation

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3394]
Most certainly an unforeseen side effect of the recent spinner changes, as this screen does things differently with a custom spinner widget.

It does work with the mouse.

**Comment by deveee** [comment]
I can't also scroll tracks in track selection list with left/right keys. It's with 1280x720 and hidpi enabled, I didn't check if it matters.

**Comment by Alayan-stk-2** [comment]
Not related. I tested in my september 15th build, and it works perfectly fine ; all of my keyboard navigation changes predate this build. Doesn't happen either in one of my branch which is only a few days old.

Most likely related to #3519.

**Comment by deveee** [comment]
I think that setting a player in kart selection screen is important and it should be fixed before the release. Additionally it's not just kart selection screen, but all spinner widgets are affected. Left/right keys just change the focused arrow instead of the value.

And btw. it's possible to use up+right to select player's name for 1st player, so it's not that bad (could be worse :P).

**Comment by Alayan-stk-2** [comment]
> I think that setting a player in kart selection screen is important and it should be fixed before the release.

I agree.

>Additionally it's not just kart selection screen, but all spinner widgets are affected. Left/right keys just change the focused arrow instead of the value.

Not true. Left/right keys just change the focused arrow, but for most spinner widgets, the select key do work to change the value once the desired arrow has been selected.

Left/right is used for navigation, having it inside a spinner locks left/right keyboard navigation once the spinner gets selected, which is not desirable.

**Comment by deveee** [comment]
The behavior was changed in 41a3a1056ed880801416cf8927019065a288debf and it uses setSelectedButton() instead of setValue() for left/right key press. Any ideas?

**Comment by Alayan-stk-2** [comment]
SetSelectedButton is used to allow the left/right key press to choose the desired arrow key with keyboard navigation.

The issue appears on screens where the select action is overriden. For example, in the multiplayer kart selection, select/fire is used by the code which decide if a player is ready. This means the select command meant to change the player's name doesn't reach the widget and can't have the intended effect.

**Comment by deveee** [comment]
Yes, but if screen has on enter press event, then you can't change spinner value. It doesn't work with dialog windows, for example in kart color selection or touch device settings. And setValue() seems much more sensibie (it's one key press less and it seems more intuitive). Is there a reason to use setSelectedButton()?

**Comment by Alayan-stk-2** [comment]
Yes, I explained it previously : 
>Left/right keys just change the focused arrow, but for most spinner widgets, the select key do work to change the value once the desired arrow has been selected.
>
>**Left/right is used for navigation, having it inside a spinner locks left/right keyboard navigation once the spinner gets selected, which is not desirable.**

For example; in the addons screen, the right spinner was unusable with keyboard because of this.

**Comment by deveee** [comment]
Ok, I see

**Comment by Alayan-stk-2** [comment]
This is a tricky issue, a sort of bug whac-a-mole : squash one bug, another one appears. :(

My best guess on how to resolve this issue sensibly is to not have screen-wide select listening. For example, have a confirmation button to use instead.

**Comment by deveee** [comment]
Do you think that there is a reason to use
```if (w->m_event_handler == NULL) return EVENT_LET;```
in EventHandler::onWidgetActivated() ?

Because below in that function there is 
```
if (w->m_event_handler != NULL)
...
else
...
```

And it fixes spinner widgets in modal dialogs, because transmitEvent() is executed.

**Comment by Alayan-stk-2** [comment]
I have not reviewed that code - which file is it ?

But it certainly doesn't make sense to have a "if A if !A else" structure, so in any case this will require changes.

**Comment by deveee** [comment]
https://github.com/supertuxkart/stk-code/blob/master/src/guiengine/event_handler.cpp#L754

**Comment by Alayan-stk-2** [comment]
I looked up the file with git blame. This portion is not one I have touched at all with my PRs, it has been that way for years.

So, we need to figure out what this line is supposed to do... Do you notice any downside when removing it and using modal dialogs ?

Right now, I quite don't see the point.

From some code doc : 
`* Returns 'EVENT_LET' if user's event handler should be notified of a change.`
If the widget has no event handler, does it do anything in this case ?

**Comment by Alayan-stk-2** [comment]
The modal dialog fix makes sense.

That code badly need some cleanup. When I did my change this summer, I also added a FIXME because there is some duplication.

Are there some other screens besides the multiplayer selection screen where spinner cause known issues after the modal dialog fix ?

**Comment by deveee** [comment]
As far as I tested everything works. It's only not intuitive that up button moves you to back arrow instead of the spinner with player name and then you have to use right button to go to the spinner. But #3395 is tracking it.
