### ISSUE TITLE
Ready, Set, Go! Penalty Removal and Revving

### ISSUE THREAD

**Issue by TorbenCarrington** [supertuxkart/stk-code#34]
This ticket makes echo to this forum thread: http://forum.freegamedev.net/viewtopic.php?f=17&t=5028

Pressing the accelerate key to soon leads to a penalty that is frustrating, particularly to new players. We should have a way to make noise with the engine before the race.

Proposal:
- Remove the penalty time.
- Improve the startup boost mechanism to incorporate revving and potentially burning out.
- Adjust AI to work with the new setup.

**Comment by Alayan-stk-2** [comment]
Can this be considered done, considering the changes to the startup boost done because of networking ?
