### ISSUE TITLE
Add the possibility to rename input configurations

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3408]
Along with #3241, this can be useful to quickly remember the purpose of a configuration ; as a custom name can be much more useful than a simple "Keyboard N".

**Comment by GuillaumeBft** [comment]
Is it ok if I create a new dialog in "states_screens/dialogs/rename_config_dialog.hpp" ?

**Comment by Benau** [comment]
can you describle what are going to do with the dialog?

**Comment by GuillaumeBft** [comment]
A dialog with a textbox which contains the current name of the input configuration and below it, 2 buttons : accept and cancel.

**Comment by Benau** [comment]
you can use general textfield dialog for that

**Comment by GuillaumeBft** [comment]
Got it

**Comment by Benau** [comment]
now it's possible
