### ISSUE TITLE
Shader compilation stutter

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3418]
Some shaders are compiled just in time instead of being pre-compiled in a track's loading phase, resulting in noticeable stutter.

The issue is compounded on my machine by the fact that compiled shaders don't seem to be saved and reused over separate playing sessions.

**Comment by qwertychouskie** [comment]
Related: Compressing kart textures should happen when karts are loaded (game startup) not when clicking the Singleplayer button.
