### ISSUE TITLE
Allow server owner to choose approximate time duration for races

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3421]
This involves : 

- [ ] Establishing an automatic time estimation for races
- [ ] Communicating this estimation in the UI
- [ ] Add options for the server owner to choose a range of allowed estimated time (maybe simply give a few presets, here are some ideas : short (<2m) ; medium (>2m, <4m) ; long (>4m, <7m) ; very long (>7m) ; unrestricted)
- [ ] Communicate to players the server's settings in the UI

**Comment by Benau** [comment]
imo only configurable in user config, i would like to keep the ui simple

**Comment by Benau** [comment]
Edit auto-lap-ratio with 3.00000 and name your server "Alayan's long lap server" so people know
