### ISSUE TITLE
Skin property border_out_portion not taken into account during element positioning

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3423]
![screenshot](http://i.imgur.com/NbfxUEQ.png)

Skin for testing:
[skin.zip](https://github.com/supertuxkart/stk-code/files/2341711/skin.zip)

**Comment by auriamg** [comment]
Could you clarify what is the issue? I'm not sure what the issue here

**Comment by qwertychouskie** [comment]
The tabs run off the screen when using the `hborder_out_portion` and `vborder_out_portion` properties in a skin.

**Comment by auriamg** [comment]
yes? that's not a bug, that's as intended. as the name said, it's the part that is "out" of the widget's bounding box

**Comment by qwertychouskie** [comment]
Is there an similar property that is accounted for in the layout?  I need the images to stay within the button but the button to stay within the screen.  In fact I can't think of a situation where that space should not be accounted for in the layout.

**Comment by auriamg** [comment]
@qwertychouskie I don't think that can be done purely at skin level. Since your buttons have a shape that the GUI engine doesn't expect, you may need to modify the screen's XML file to provide more padding within the buttons
