### ISSUE TITLE
Restore only 3 hiscore entries?

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3424]
5 hiscore entries is a bit too much when hidpi_enabled is set to true in config.xml (mainly for android).

![zrzut ekranu z 2018-09-01 22-39-23](https://user-images.githubusercontent.com/5108558/44949765-c7e6e680-ae38-11e8-8fb7-9feb547291da.png)
![zrzut ekranu z 2018-09-01 22-42-23](https://user-images.githubusercontent.com/5108558/44949766-cd443100-ae38-11e8-8064-5be7f29b11ca.png)

It's a bit better on desktop, but "max-arena-players" has too little space anyway. And very long author names can wrap to second line.

The problem is that the entries can't be easily added/removed in runtime depending on available space.

... or I can hack it with ```widget->m_properties[GUIEngine::PROP_HEIGHT] = "0";``` if you don't care about warnings.

**Comment by Alayan-stk-2** [comment]
You could also ifdef the display of the 5th line in that screen depending on the hidpi preference ?

**Comment by deveee** [comment]
You can't easily ifdef (or I don't know easy way). You can use 
```
widget->setVisible(false);
widget->m_properties[GUIEngine::PROP_HEIGHT] = "0";
...
calculateLayout();
```
but then it complains that widget has no dimensions. And anyway the "max players supported" is currently broken on desktop version too.

**Comment by deveee** [comment]
@Alayan-stk-2 Maybe keep only 3 hiscores and add a button that opens dialog window with more hiscores? And then it may be even more than 5 entries or for all difficulties. And maybe increase hiscores version to keep compatibility with older STK?

**Comment by Alayan-stk-2** [comment]
Increasing highscore version could be done, too. Not sure if it's needed now that the profile version has changed, and considering everything apart the 3/5 would be still identical.

While I strove to keep compatibilities for replays ; highscores are a different beast. Many kind of changes make times hard to compare between versions : bugfixes (texture slowdown, shortcuts, nitro) and balance tweaks (red skidding behavior, maybe more coming). If one version is 5% slower/faster than another, mixing times from both doesn't make sense anyway.

I'll have a look at the reported UI issues.

By "for all difficulties", I assume you mean a method to consult highscores for all difficulties, not only the current one, without having to go back and forth in menus to change it ? This is a good idea, though before working on a significant UI change, I must ask : is the track info screen the best place to do this ? What should be the UI flow ? Maybe there's some opportunity here for a deeper improvement, feel free to suggest other related things.

**Comment by Alayan-stk-2** [comment]
@deveee Tell me if you notice any issue this time. I tested with hi-dpi and moved the track author/max supported player info in a special box, so it should be good.

**Comment by deveee** [comment]
It's much better now, thanks!
