### ISSUE TITLE
Segfault When Running to 0.9.3 After Running Git Build

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#3425]
Segfault When Returning to 0.9.3 After Running Git Build

Problem may have something to do with radeonsi_dri.so maybe a problem with the driver itself or how it is called.

Valgrind analysis here: https://gitlab.com/snippets/1751055

"Conditional jump or move depends on uninitialised value(s)"

**Comment by deveee** [comment]
It seems that it's related to hiscores:
```
Thread 1 "supertuxkart" received signal SIGSEGV, Segmentation fault.
0x000000000099591b in XMLNode::get(std::string const&, irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >*) const ()
(gdb) bt
#0  0x000000000099591b in XMLNode::get(std::string const&, irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >*) const ()
#1  0x0000000000992a0d in Highscores::readEntry(XMLNode const&) ()
#2  0x0000000000992fd2 in Highscores::Highscores(XMLNode const&) ()
#3  0x0000000000985f83 in HighscoreManager::loadHighscores() ()
#4  0x00000000009863f1 in HighscoreManager::HighscoreManager() ()
#5  0x0000000000a93ed8 in initRest() ()
#6  0x0000000000717c85 in main ()
```

0x000000000099591b is src/io/xml_node.cpp:191
0x0000000000992a0d is src/race/highscores.cpp:86

Kinda related to https://github.com/supertuxkart/stk-code/issues/3424 (one more reason to keep only 3 hiscores).

**Comment by deveee** [comment]
I reverted that commit until all issues will be properly fixed:
https://github.com/supertuxkart/stk-code/commit/0f1f876874b53f6723a5e7d3f5dc68214c5221de

You can remove your hiscore.xml file and it should work.

And actually before launching current git STK, you can run ```export HOME=./.config``` and it will save config in separate directory.

**Comment by psypherium** [comment]
Thankyou very much for the quick response. :)

Maybe if you want to keep a longer list of high-scores it could be in a section in the menu instead of the post-race screen, in a different file which causes no conflicts with previous versions, something the older versions don't even check for?

I hope you have a good day. :+1:

**Comment by psypherium** [comment]
Removing hiscore.xml did nothing, But removing highscore.xml one directory deeper in 0.8.2 folder fixed it
