### ISSUE TITLE
Credits are barely readable with the coal theme

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3433]
[20:13] Wuzzy heh. i like the new Coal theme. very dark
[20:14] Wuzzy but credits are poorly readable in Coal theme

The color of the credit text isn't directly managed by the skin, afaik, which is the root of the issue there.

**Comment by Alayan-stk-2** [comment]
I'm not entirely sure how to make the credits color skinnable.

It is manually defined at line 265 of credits.cpp currently, and there seems no easy way to retrieve a data I'd store in SkinConfig, so how the text is drawn would have to be rewritten to go through the skin.

Here are some color suggestion for the various themes, as I did testing for this : 
- Ocean : keep 0/0/75
- Coal : use 220/220/220 as for normal text, white is what fits best the theme and stands out the more
- Ruby : use 65/0/15
- Peach : use 65/15/0
- Forest : use 0/55/0 (at equal real brightness, green seems brighter for human eyes)

**Comment by qwertychouskie** [comment]
>  and there seems no easy way to retrieve a data I'd store in SkinConfig

Actually I'm currently working on that exact issue :)
https://github.com/STK-helper/stk-code/tree/new-skin-and-padding
It currently doesn't compile :(

**Comment by auriamg** [comment]
@Alayan-stk-2 Adding colors to the skin is fairly easy, near the bottom of the skin XML files, you can find a "colors" section. Then check method Skin::getColor in skin.cpp

**Comment by Alayan-stk-2** [comment]
There is a similar issue in the achievements list, the blue text doesn't fit well.
