### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by v1993** [supertuxkart/stk-code#3437]
## Description
I'm unable to connect to any online server.

## Steps to reproduce
Try to connect to any server.

## Configuration

STK release version: commit 02732e78be5ebcb319faf87ed409e60e097ff355 (built with zapcc)

STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it: git

System: XUbuntu 18.04 64-bit

Graphics card: (doesn't matter here)

CPU: (doesn't matter here)

Gamepads/keyboards models if related to the issue:

## Additional information

Console (related part):
```
[info   ] ConnectToServer: Trying connecting to 83.230.14.9:2760 from port 33536, retry remain: 3
[info   ] ConnectToServer: Connected to 83.230.14.9:2760
[info   ] STKHost: Listening has been started.
[info   ] ProtocolManager: A 11ClientLobby protocol has been started.
[info   ] ProtocolManager: A 15ConnectToServer protocol has been terminated.
[info   ] ClientLobby: Server will validate this online player.
[info   ] STKHost: 83.230.14.9:2760 has just disconnected. There are now 0 peers.
[error  ] STKHost: AB5:;> 2@5<O >6840=8O A>548=5=8O A A5@25@><.
[info   ] HTTPRequest: Sending userid=826&token=************************ to https://addons.supertuxkart.net/api/v2/server/clear-user-joined-server/
[info   ] STKHost: Listening has been stopped.
```
Error is about connection timeout. 

_Sent from my SCL-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by deveee** [comment]
HK servers probably should work and I will upgrade my servers soon too

**Comment by deveee** [comment]
STK Server is now working. And android beta packages are updated too.
