### ISSUE TITLE
Credits are hard to read in Coal theme

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3438]
## Description
If you select the Coal theme, the credits text is hard to read (dark blue on dark gray background).

## Steps to reproduce
* Select Coal theme
* Go to credits

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by qwertychouskie** [comment]
You're a few hours behind :P https://github.com/supertuxkart/stk-code/issues/3433

**Comment by Wuzzy2** [comment]
Closed as duplicate.
