### ISSUE TITLE
Time penalty warning overlaps with the "Ready? Set! Go!" text

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3439]
## Description
If you start early in a race and get the time penalty, the warning texts warning overlaps with the “Ready?” / “Set!” / “Go!”

## Steps to reproduce
* Start early in a race to get time penalty
* Look at your screen texts

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by Alayan-stk-2** [comment]
Related to the time penalty moved to the set phase instead of the go phase.
