### ISSUE TITLE
Text overshoots in various online dialogues

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3441]
## Description
Various menus in online mode have issues with string lenght. The text often overshoots.

Columns in server list are too crammed for the text:

https://i.imgur.com/wpXbgGG.png

String overshoots when connecting to server:

https://i.imgur.com/G7ZhxNG.png
https://i.imgur.com/ZNe9iWO.png

For the first screenshot, probably the table needs rethinking? I believe this is even an issue in English.
For the second screenshot, adding a few strategically line-breaks might fix this.
For the third screenshot, the text is clearly misplaced.

## Steps to reproduce
* Use German
* Go online, test out ALL the sub-menus

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by deveee** [comment]
Two of three cases are already fixed:
![zrzut ekranu z 2018-12-14 21-02-56](https://user-images.githubusercontent.com/5108558/50024889-184b1400-ffe4-11e8-8e38-eae78cd0adf2.png)
![zrzut ekranu z 2018-12-14 21-03-18](https://user-images.githubusercontent.com/5108558/50024900-1c773180-ffe4-11e8-8834-bd475cd2b670.png)

Not sure what about column names. I can add context for translations in the same way as in ghost replay screen, so that you can write shorter text in the table and it won't break other translations? Or maybe even use common "column_name" context.

**Comment by deveee** [comment]
No, there is:
```
void ServerSelection::beforeAddingWidget()
{
    m_server_list_widget->clearColumns();
    m_server_list_widget->addColumn( _("Name"), 3);
    m_server_list_widget->addColumn( _("Players"), 1);
    m_server_list_widget->addColumn(_("Difficulty"), 1);
    m_server_list_widget->addColumn(_("Game mode"), 2);
    if (NetworkConfig::get()->isWAN())
    {
        // I18N: In server selection screen, owner of server, only displayed
        // if it's localhost or friends'
        m_server_list_widget->addColumn(_("Owner"), 1);
        // I18N: In server selection screen, distance to server
        m_server_list_widget->addColumn(_("Distance (km)"), 1);
    }
}   // beforeAddingWidget
```
while ghost replay has
```
void GhostReplaySelection::beforeAddingWidget()
{
    m_replay_list_widget->addColumn(_C("ghost_info", "Track"), 9 );
    if (m_active_mode_is_linear)
        m_replay_list_widget->addColumn(_C("ghost_info", "Reverse"), 3);
    if (!m_same_difficulty)
        m_replay_list_widget->addColumn(_C("ghost_info", "Difficulty"), 4);
    if (m_active_mode_is_linear)
        m_replay_list_widget->addColumn(_C("ghost_info", "Laps"), 3);
    m_replay_list_widget->addColumn(_C("ghost_info", "Time"), 4);
    m_replay_list_widget->addColumn(_C("ghost_info", "Kart"), 1);
    m_replay_list_widget->addColumn(_C("ghost_info", "User"), 5);
    if (m_multiplayer)
        m_replay_list_widget->addColumn(_C("ghost_info", "Players"), 3);
    if (!m_same_version)
        m_replay_list_widget->addColumn(_C("ghost_info", "Version"), 3);

    m_replay_list_widget->createHeader();
}   // beforeAddingWidget
```
Can I add the context now or will it make a conflict with your work? Or you can use "column_name" for both.

**Comment by Alayan-stk-2** [comment]
My changes include some modification of the relative proportion of the columns, so adding context right now would create a conflict. But I can just backport your change in my branch quite easily, so go ahead.

I'm waiting on Benau to do something about alternating line color for lists (he told me he's going to do it) before committing my changes, as I also allowed word wrap (so a long translation for "Capture the Flag", etc. can fit on two lines) but this slightly hurt the perception of lines.
