### ISSUE TITLE
Tooltip of “Enable Player Handicaps” in User Interface settings is too long and does not fit into window

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3442]
## Description
The tooltip of “Enable Player Handicaps” in User Interface settings is too long and does not fit into the game window.

## Steps to reproduce
* Go to User Interface settings
* Hover “Enable Player Handicaps”
* Look if the tooltip fits

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by Alayan-stk-2** [comment]
Tooltips are centered on the mouse, even if that makes them not fit in the screen. Having the possibility to word wrap tooltips, have them not be centered under the mouse, or both, would allow to fix that kind of issue (I saw that somewhere else iirc)

**Comment by Alayan-stk-2** [comment]
Having an auto-wrap for tooltips would require significant code changes.

However, it is rather easy to wrap the text manually in the translatable text, the tooltip is appropriately resized then.

The english version is now fixed, and translators ought to make sure to use enough linebreaks for their language to fit too.
