### ISSUE TITLE
Terms of service dialog claims there is a checkbox, but there is none

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3443]
## Description
If you are about to create a new online account, there is a dialog which informs you about the ToS and asks you to accept or decline.
So far, so good, but in the text there is a claim that you have to tick a checkbox to proceed. Stupid thing is, there is no such checkbox. It's a lie!

## Steps to reproduce
* Go to accounts menu
* Create new online account
* Make the ToS dialog appear and read carefully what it says

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by qwertychouskie** [comment]
Dupe of https://github.com/supertuxkart/stk-code/issues/3434
