### ISSUE TITLE
When assigning keyboard key, game tells me I have to press the key “fully”

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3444]
## Description
When I am about to assign a keyboard key, the game tells me I have to press the key “fully”, which is funny. Probably the keyboard is confused with a controller?

## Steps to reproduce
* Go to control settings
* Configure keyboard keys
* Click any control to make the key config window pop up
* Read what it says
* Have a mild chuckle

## Configuration
Default.

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

System: GNU/Linux 64bit

**Comment by auriamg** [comment]
That's just because we use the same popup and text for keyboards and gamepads

**Comment by doutsh** [comment]
It's an easy fix, but it requires to add the new text to all the translation files (actually no ALL, as most of them don't translate this line for some reason)

**Comment by nebbii** [comment]
In which translation files has/hasn't this been fixed?

**Comment by auriamg** [comment]
@nebbii I don't understand your question. Nothing has been changed in the original version yet so translations are not affected as of now.

**Comment by 123survesh** [comment]
Hi I have made a PR for this issue #4075 . please do see if the approach I took is ok and tell me if its not I will try to work on it.
