### ISSUE TITLE
Put each checkbox in User Interface settings in its own line

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3447]
## Description
This is a suggestion.

I suggest to put each checkbox in User Interface settings in its own line, instead of trying to cram 2 checkboxes into the same line.

Justification: This will make most potential translation problems due to missing space disappear. In German I was forced to use abbreviations.
Note that even English is quite crammed, which is a red flag (if English is crammed, then other languages will likely run out of space).

STK release version: 32d192460e213fe221e6526d7f07364695a5d33c

**Comment by Alayan-stk-2** [comment]
The text is supposed to wrap and be on two lines, though it doesn't seem to work all that well.

I guess having them each on their own line, but with less vertical height between them could work too.

There needs to be enough space for some more options after the change, however.
