### ISSUE TITLE
Kart getting oversized wheels

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3455]
I have no idea why this bug happens.

However, I saw it once on my kart a few days ago, and today on an AI kart.

Look at Pigdin :
![oversizedwheels](https://user-images.githubusercontent.com/25536748/45640208-4b980880-bab2-11e8-9322-897937ffaac5.png)

**Comment by qwertychouskie** [comment]
Is it always the same kart (Pidgin) that has the issue or can any kart be affected?

**Comment by Alayan-stk-2** [comment]
I got the issue with the gavroche kart ; so I'd say "any kart can be affected".

**Comment by RiderExMachina** [comment]
I've had this happen to me but it's usually all karts when I'm on an early OpenGL version and on weak hardware.

**Comment by Alayan-stk-2** [comment]
I found the cause : **this happens when restarting a race when a kart is squashed**. The squashed kart will afterwards have oversized wheels.

**Comment by deveee** [comment]
```
    if (m_wheel_box)
    {
        m_wheel_box->getRelativeTransformationMatrix()
            .setScale(core::vector3df(1.0f, 1.0f, 1.0f));
    }
```
in Kart::reset() ?

**Comment by Alayan-stk-2** [comment]
I don't know.

I can tell you that the regression happened between June 20th and July 30th, so if this code was changed in this period, it is likely the culprit.

**Comment by deveee** [comment]
Ok so I will commit

**Comment by deveee** [comment]
There is also a timed slowdown in setSquash that is probably not restored on restart:
```
    m_max_speed->setSlowdown(MaxSpeed::MS_DECREASE_SQUASH, slowdown,
                             stk_config->time2Ticks(0.1f), 
                             stk_config->time2Ticks(time));
```
but no more time today.

**Comment by Alayan-stk-2** [comment]
I can confirm the wheel size issue is fixed. I will have a look at the slowdown.
