### ISSUE TITLE
Speed weighted objects broken in legacy pipeline

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3456]
Can be just disabled if too hard to fix.

![screenshot_2018-09-17-18-53-23](https://user-images.githubusercontent.com/5108558/45643801-332ceb80-babc-11e8-89b9-d97beef0f33d.png)

**Comment by deveee** [comment]
Just note that I tested it only with GLES and it sometimes happens and sometimes not (looks more like an unitialized memory). Also non-animated attachment (hat) works fine and it's not related to particular bone, because it behaves the same when attached to other bones. And IIRC Tux's lights were broken for me too. Something wrong when converting spm to legacy pipeline or in irrlicht animated mesh? No idea atm...

**Comment by Benau** [comment]
Try e7aa03f1bf9ebb2353fd8cce2aa64c48004e5999?
And you can update servers and android apk right now!(remember svn up stk-assets!)

**Comment by deveee** [comment]
Indeed it looks that it's fixed. And yesterday I noticed that enable ```updateAbsolutePosition();`` in CBoneSceneNode seems to fix it too.
