### ISSUE TITLE
Tracks road defects

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3461]
This issue is meant to keep track of all issues with track road terrains. It's not about how it could be more fun with a different layout, etc. but for basic issues like an uneven road provoking crashes, etc.

- [x] Snow Peak : the bridge and the road don't join each other smoothly. This can especially cause issues in reverse (and it's ugly). **[Fixed in SVN]**
![trackdefect_sp](https://user-images.githubusercontent.com/25536748/45884729-f5c6a780-bdb4-11e8-8d74-6b8856ec73c4.png)
- [x] Nessie's Pond : this track has general smoothness issues (which suspension compensate decently for the greatest part), but there is one spot with a weird shape which can cause the chassis to collide with the ground. **[Fixed in SVN]**
![trackdefect_np](https://user-images.githubusercontent.com/25536748/45912422-3a882800-be21-11e8-82b8-4b610e5fa8e8.png)
- [x] Volcano Island : there is one transition which isn't smooth at all and causes the chassis to collide with the ground at medium-high speeds. **[Fixed in SVN]**
![trackdefect_vi](https://user-images.githubusercontent.com/25536748/45929143-d020d600-bf4d-11e8-90f4-2d8536752987.png)
- [x] XR591 : there are two very noticeable bumps. In normal direction, they are down, so the kart just fall a bit (though the one in the sharp curve is annoying) ; but in reverse it causes the kart to jump upward and crash. **[Fixed in SVN]**
![trackdefect_xr2](https://user-images.githubusercontent.com/25536748/45884712-e9dae580-bdb4-11e8-8cd3-43de4091a5d2.png)
![trackdefect_xr1](https://user-images.githubusercontent.com/25536748/45884713-e9dae580-bdb4-11e8-914d-99bd25169619.png)
- [x] Shifting Sands : there is a small spot where the road goes down and up ; the suspensions can't compensate it when going at a medium to high speed (25+) and the chassis hits the road. **[Fixed in SVN]**
![trackdefect_ss](https://user-images.githubusercontent.com/25536748/45885207-1cd1a900-bdb6-11e8-8d0f-5a7695a80f32.png)

**Comment by auriamg** [comment]
Snow peak, XR591 and shifting sands done

**Comment by auriamg** [comment]
Volcano island fixed
