### ISSUE TITLE
Font scaling issues

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3471]
The rank indicator font is currently upscaled using setScale, and its blurriness is painfully obvious.

Regular text fonts also become blurry when modified with setScale, but afaik this is not really needed anywhere.

**Comment by Benau** [comment]
you can see if https://github.com/Benau/stk-code/commit/a96daa5efce3fdf008a805192e70db37a8a2d4f6 is good enough for you, but it will cause around 0.4ms of extra ttf to bitmap time...

![bottle](https://user-images.githubusercontent.com/3252341/80243919-aafcc800-869a-11ea-85bc-a872cfe4f9ee.png)

**Comment by Benau** [comment]
Assume you care because ![](https://cdn.lihkg.com/assets/faces/dog/treat.gif)![](https://cdn.lihkg.com/assets/faces/pig/dying.gif)

And I think re-upload font texture each frame is not good for performance anyway

**Comment by Alayan-stk-2** [comment]
Re-uploading each frame is definitely not good and the performance impact is not worth it for the first solution.

But until either we replace all usage of SetScale with something else or fix it to not be blurry, without a significant performance downside, this issue still tracks something that deserves to be improved.
