### ISSUE TITLE
Major unintended skips in several tracks

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3479]
The previously reported and patched skips involved validating one checkline and going back to the start line.

However, it is possible on several tracks to trick the game in validating two checklines and then the lap, faster than doing the track the intended way.

In some tracks, it is slower, but not by enough that it can't be used to confuse people in networking.

This apply to : 
- [x] Gran Paradiso Island. This video show s the trick in 0.9.3, but it is 100% applicable to latest git/svn : https://www.youtube.com/watch?v=y-cJ4J14gh8t **Fixed in SVN**
- [x] Northern Resort **Fixed in SVN**
- [x] Shifting Sands **Didn't exist in latest SVN**
- [x] Lighthouse (about equal in normal direction ; faster in reverse mode) **Fixed in SVN**
- [x] Hacienda **Fixed in SVN**
- [x] The Old Mine (allows to go faster on 1st lap, barely slower on subsequent laps)
- [x] Snow Peak (about equal)
- [x] Zen Garden (barely slower)
- [x] Abysses (slightly slower)

More regular skips exist for :
- [x] XR591 (reverse) - saves 2 or 3 seconds per lap, see https://www.youtube.com/watch?v=tZjC57NnbkA
- [x] STK Enterprise (reverse) - saves a few seconds, see https://www.youtube.com/watch?v=iV6p4-5YfOA
- [x] Abysses (reverse) - saves a tiny amount of time, see https://www.youtube.com/watch?v=opNN_4GblyE
- [ ] Northern Resort (normal direction and reverse), see https://www.youtube.com/watch?v=J8RJVpUTZ8Q . Also in reverse, by turning to the right at the end of the bridge to fall lower, it is possible to save 1 or 2 second. A checkline should prevent this.

**Comment by Alayan-stk-2** [comment]
Why was this pushed to 0.11 ?

Anyway I updated the list with some additional skips

**Comment by theTomasPat** [comment]
@Alayan-stk-2 Yeah I'll take a look! I seems like the last 3 cases just need an extra checkline or 2, is that correct? Also, I'm not familiar with the skip in Old Mine. Is there a video somewhere for it?

**Comment by Alayan-stk-2** [comment]
For the Old Mine, you basically go reverse, jump from the bridge, validate the first checkline, rescue, go reverse again to the second checkline, rescue...

So the fix is basically to add one or two additional checklines in other spots.

For any additional checklines, try to add it somewhere where the kart can't go around it and is very unlikely to "jump above" the checkline after a collision.

In the old mine, you may look at extending the checkline in the big curve, because it is still regularly missed when taking the interior.

**Comment by theTomasPat** [comment]
Here's 4 to start with. I'll be able to take a look a the rest tomorrow :)

[xr591.blend.zip](https://github.com/supertuxkart/stk-code/files/2917583/xr591.blend.zip)
[spaceship.blend.zip](https://github.com/supertuxkart/stk-code/files/2917640/spaceship.blend.zip)
[abyss.blend.zip](https://github.com/supertuxkart/stk-code/files/2917657/abyss.blend.zip)
[mines.blend.zip](https://github.com/supertuxkart/stk-code/files/2917728/mines.blend.zip)

**Comment by auriamg** [comment]
XR591, spaceship, abyss and mines committed to svn, thanks

**Comment by auriamg** [comment]
Snow peak done too.
For the trees, I'm slightly worried : in black forest, we had networking performance issues because the trees added too many physics objects to the track. We may want to address that issue before we add even more tree-physics to tracks

**Comment by Alayan-stk-2** [comment]
"I also widened the lapline for Zen Garden as well as add a few plants in the first turn to discourage cutting the corner and missing the first checkline."

@theTomasPat this sounds like a potential source of issues. Ideally, players should never be aware that there is a checkline to miss, and always have their lap validated as long as they go roughly along the intended path... It's better to extend the checkline into off-road grass than to later get people reporting that they had a lap not counted.

**Comment by Alayan-stk-2** [comment]
@theTomasPat Could you add a checkline to prevent both of the shortcuts shown at the end of this video in Northern Resort : https://www.youtube.com/watch?v=J8RJVpUTZ8Q ?

**Comment by theTomasPat** [comment]
@Alayan-stk-2 : "this sounds like a potential source of issues"

True. I widened the checkline but kept the plants in place. Hopefully there won't be any issues.

[ZenGarden_issue3479_20190307.zip](https://github.com/supertuxkart/stk-code/files/2944280/ZenGarden_issue3479_20190307.zip)

**Comment by Alayan-stk-2** [comment]
Nice. Don't forget the northern resort fix! It would be nice to ship it in the next release too.

**Comment by theTomasPat** [comment]
I haven't forgotten :) I hope to have a little bit of time this afternoon to do it. If not then I'll get it done sometime this weekend.

**Comment by auriamg** [comment]
The zen garden blend appears identical to the one we currently have in svn?

**Comment by auriamg** [comment]
Snow mountain committed, thanks

**Comment by theTomasPat** [comment]
@auriamg My mistake, I had compressed the wrong version of Zen Garden.

This is the most recent one.
[ZenGarden_issue3479_20190309.zip](https://github.com/supertuxkart/stk-code/files/2949028/ZenGarden_issue3479_20190309.zip)

**Comment by Mrxx99** [comment]
@Alayan-stk-2 Now the very fun jump in Snow Peaks does not work anymore :(
I don't think it saved any time and it always was risky enough to justify keeping it.

**Comment by auriamg** [comment]
I've committed zen garden
