### ISSUE TITLE
lenautile_restaurant.ogg not actually used?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3486]
AFAIK `lenautile_restaurant.ogg` is supposed to be used in Candela City, but it can't be heard anywhere in 0.9.3 or Git.

**Comment by Alayan-stk-2** [comment]
While the restaurant Le Nautile itself is easily found ; on the right at the end of the main road (boulevard Elysia) ; I confirm I can't hear the custom sound even when I'm just in front of the building.

**Comment by Benau** [comment]
Fixed in svn

**Comment by Alayan-stk-2** [comment]
The sound is now present, but it's very hard to hear it, even when trying. It's completely unnoticeable in an actual race with engine sounds and music.

The sound volume should be increased so that it can be noticed without having to try hard.

**Comment by Alayan-stk-2** [comment]
With the music volume slightly below the sound effect volume, it can now be easily heard when driving next to the restaurant.
