### ISSUE TITLE
Skidding has a larger turn radius, but tutorial/help say it is shorter

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3489]
Skidding has a larger turning radius than turning, but the tutorial says: "Skidding for a short while can help you turn faster to take sharp turns."  Also, the help text says: "Short skids help to take sharp turns."

Either skidding should have a shorter turning radius (this will be natural to MK players), or the tutorial and help text should be changed to make it clear skidding has a larger turning radius.

**Comment by hiker** [comment]
No, that's correct: while you skid you have a larger turn radius, but when you release you have a sharper angle.

**Comment by qwertychouskie** [comment]
This is very unclear to the average user (especially anyone who has ever played MK) and needs to be clarified in-game.

**Comment by Alayan-stk-2** [comment]
There is a reason why the text emphasizes _short_ skids, in both the tutorial and the help text. With repeated short skids (in fact, you just need to get the hop animation, release, and re-do), you can significantly reduce your turn radius at equal speed compared to normal turning.

Feel free to suggest a clearer formulation for the tutorial and the help text if you can think of one, though.
