### ISSUE TITLE
Remove the crashing sound when colliding with a rescue wall

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3491]
This sound (together with the noticeable delay between the collision and the rescue) alerts the player to the presence of an invisible wall which triggered the rescue.

It reveals the trick used by the game to rescue the kart, while that kind of trick (checklines, etc. are similar in that regard) should strive to be as invisible as possible to the player.

**Comment by qwertychouskie** [comment]
Agreed.  Also maybe Cornfield Crossing's boundary walls should rescue on collision.
