### ISSUE TITLE
The main menu UI is confusing in regard to multiplayer

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3497]
The online multiplayer is not accessed through the "multiplayer" button, but through the "online" button. As we get closer to the beta, and ultimately to the release, the current method is not good enough.

Expected behavior : the multiplayer button gives a choice between local multiplayer and online multiplayer.

Changing the available buttons could also work ; as long as the button labels match well what the buttons do.

**Comment by auriamg** [comment]
The easy quick-fix is to rename "Multiplayer" to "Local multiplayer" or "Split-screen"
Otherwise we could do as you describe and ask between local and network

**Comment by MSavoritias** [comment]
> The easy quick-fix is to rename "Multiplayer" to "Local multiplayer" or "Split-screen"
> Otherwise we could do as you describe and ask between local and network

I don't think this work too much because there is already a local multiplayer option in the menu under online. 
I think a combination of the first suggestion and also rename local multiplayer to LAN maybe since it is more common for local network multiplayer.
