### ISSUE TITLE
dynamic lighting in supertux cart causes flashing

### ISSUE THREAD

**Issue by theinventor143** [supertuxkart/stk-code#3505]
## Description
i installed this on my friends laptop and got it up and the levels i went throw it stated to flash .
i messed with the graphics and when i put it on graphics 2 it has no problems .
## Steps to reproduce
graphics setting 3
dynamic lighting enabled 
## Configuration

STK release version: 0.9.3
STK Source (ppa, distribution package, official bin,...):
If you did not download STK from the official website, please specify where you got it:

System: Linux mint

Graphics card: integrated

CPU: Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               78
Model name:          Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
Stepping:            3
CPU MHz:             500.016
CPU max MHz:         2300.0000
CPU min MHz:         400.0000
BogoMIPS:            4608.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d

**Comment by deveee** [comment]
+1 for glxinfo (or stdout.log file). I often see outdated drivers on systems with linux mint and your processor is relatively new. Another thing is that you can try current git STK, because it has some improvements in the graphical engine and it's possible that it will work in current version.

**Comment by j-420** [comment]
> What do you mean by "flashing" ? Either a detailed description or a video would be helpful.
> 
> What's the version of mesa (this kind of issue can be related to drivers) ? Give us the result of the following command in a terminal :
> `glxinfo | grep 'version'`
> 
> If the command is not available, install mesa-utils to be able to run it :
> `sudo apt-get install mesa-utils`

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by qwertychouskie** [comment]
I would recommend installing the latest Hardware Enablement stack (https://wiki.ubuntu.com/Kernel/LTSEnablementStack) when it becomes available.  Also you could try compiling the current git version of STK.

**Comment by qwertychouskie** [comment]
@theinventor143 Can you run `sudo apt-get install --install-recommends linux-generic-hwe-18.04 xserver-xorg-hwe-18.04` and re-test to see if this issue is still present?  Thanks!

**Comment by qwertychouskie** [comment]
@theinventor143 I think this issue is https://bugs.freedesktop.org/show_bug.cgi?id=110463, which should be fixed in the upcoming Mesa 19.2.  @Benau Can you close this for now, since it's a Mesa bug and not our bug?  It can be re-opened if the new Mesa release doesn't fix it.
