### ISSUE TITLE
Lap sometimes isn't counted

### ISSUE THREAD

**Issue by v1993** [supertuxkart/stk-code#3509]
## Description

I sometimes complete lap, but it isn't counted (AI karts probably too). Easiest track to reproduce — XR519 (Normal race, 9 AI kart, 10 laps tested). Seems like affects other tracks too, but much rare.

Also (XR519 too) reproduced in networked multiplayer.

## Steps to reproduce
See desc.

## Configuration

STK release version: git 14b04ebc189e71e998a2e6b6dc093d3cf760186a

System: XUbuntu 18.04

**Comment by Alayan-stk-2** [comment]
The issue was shown to me in a networked race ; it happened by going over the tunnel in XR591 rather than inside it.

Some checklines in some tracks can be missed by accident when they shouldn't, though most cases involve "accidentally jumping over the checkline" after a collision.

**Comment by hiker** [comment]
Easiest solution would be to add a this path as an alternative path (checklines can define their own dependency graph, so you can define that either of the two checklines must be crossed).
But we might also need to look at the 'height' when crossing a checkline, and tweaking this value. Note that there might be instances (e.g. a bridge over a checkline) where we do not want a checkline to be crossed too high above.

**Comment by Alayan-stk-2** [comment]
Going over the tunnel is not intended. However, adding an obstacle preventing from doing so while keeping with the track's theme need some modeling work. Auria had an inconclusive try.

Is the height value when crossing a checkline necessarily the same for all tracks ?

**Comment by Alayan-stk-2** [comment]
There is a checkline which can be missed in normal play in Snow Peak with a small jump or so.

**Comment by Qtamo** [comment]
Referencing your question in my duplicate @Alayan-stk-2 ,the karts were going normal direction (not reverse) in Volcano Island. That was the one that happened to the other player so I did not see it happen (if you need the players name I remember it). 
Today it also happened in a reversed mines online game (to me). I did fall off a bridge at some point if that might be when it happened.

**Comment by philshem** [comment]
This happened to me two times playing non-networked xr591 novice-level in story mode. The level requires less than 3:00:00 time and collecting 12 (or 15?) nitros, but when I complete the 2nd lap, I keep driving, and then when 3:00:00 hits on the clock, it says "challenge failed"

**Comment by afontenot** [comment]
This seems to happen to me about 75% of the time in XR591. I've failed the SuperTux level Grand Prix that ends in XR591 three consecutive times now because of this problem. Whatever the issue is with XR591, it's surprisingly easy to hit and doesn't require any weird skips. Let me know if there's something I can do to debug it.

**Comment by Fouks0** [comment]
Missed a Checkline today online in Xr591 normal race as well :| . Unfortunately I was not recording so I don't know where it happened. Looks like something is definitively broken.

**Comment by auriamg** [comment]
A recording (video or ghost race) of the issue would be most helpful so that we can know where it was missed. You can also run stk on the terminal with --check-debug and I try to identify which checkline you're missing (that switch makes checklines visible)

**Comment by Alayan-stk-2** [comment]
It's the checkline in the big curve after the road split and join back which is by far the most problematic in XR591.

**Comment by Fouks0** [comment]
I just tested with the visible Checklines. The one you talk about may indeed cause the issue as I often take this part very sharply and might occasionally miss that one.
But the one that should be the most problematic is the very last one. There is no speed penalty in brighter areas so I will always take that last turn very sharply, but there is a relatively large zone not covered by that Checkline.
I missed at least a Checkline in all the 3 Xr591 races I did online today and yesterday.

**Comment by Fouks0** [comment]
Pictures:
![Xr591Miss1](https://user-images.githubusercontent.com/42526046/59954940-c221c680-9487-11e9-9636-96bcd8c8b37a.png)
![Xr591Miss2](https://user-images.githubusercontent.com/42526046/59954941-c221c680-9487-11e9-9a5d-b40434ad5049.png)
Other Checklines should not be an issue.

**Comment by auriamg** [comment]
I have just tweaked the XR591 checklines, they should no longer be missable, thanks for the screenshots

**Comment by auriamg** [comment]
I've also tweaked the mine checkline, even  though this one was not so easy to miss.
