### ISSUE TITLE
Poly "leak" with skidding when game paused

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3511]
## Description

If you pause the game while skidding, the poly count will continue to increase.  Un-pausing the game won't get rid of the "leaked" polys.  The leaked polys seem to have a location, see screenshots.  I'm guessing the skidding is depositing skidmarks continually even when paused.

![screenshot_2018-10-11_13-20-52](https://user-images.githubusercontent.com/13989090/46895232-597c4780-ce2c-11e8-80a7-2d7ec627f4da.png)
Poly count after leaving it for a while

![screenshot_2018-10-11_13-21-18](https://user-images.githubusercontent.com/13989090/46895263-7a449d00-ce2c-11e8-9f45-ebcffe9da2ef.png)
"Looking" at the leaked polys

![screenshot_2018-10-11_13-21-29](https://user-images.githubusercontent.com/13989090/46895279-8af51300-ce2c-11e8-8b64-9b35c03e06d6.png)
Looking away

## Steps to reproduce

1. Skid
2. Pause the game while skidding
3. Watch the poly count continually increase

## Configuration

STK release version: git

**Comment by Alayan-stk-2** [comment]
Yeah, @deveee wrote this in a comment in #3427 : 
> Also poly count was increasing, probably because of particles, because I used skidding.
