### ISSUE TITLE
Performance issue in particle drawing

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3512]
I did some profiling tonight.

The longest frame-times I got were related to the "particle and text billboard draw" spiking to around 10000µs instead of <50µs on most frames.

After further profiling, this is the function call which takes much more time when the issue happens : 
`        glDrawArraysInstanced(GL_TRIANGLE_STRIP, 0, 4,
            (unsigned)m_particles_generated.at(p.second).size());`

In CPUParticleManager::drawAll()

I also tested to see how many times it is called (it's in a loop) - the maximum I got was 5 times in a drawAll call - and the sum of the m_particles_generated.at(p.second).size() - which never had a big frame-to-frame variance which could explain the issue.

For the record, I did my test runs in lighthouse but I expect the issue to show up on any track. I had graphics settings set to 3.

**Comment by Alayan-stk-2** [comment]
After additional testing, I can't reproduce the issue using my intel iGPU, making a nvidia issue looking more likely.

**Comment by deveee** [comment]
The only case when enabled/disabled particles make a difference in fps for me is on my tablet that has ~30fps with disabled advanced lighting. And it really matters only if you are in the middle of explosion and there are a lot of huge particles on the screen. I never had any other problems.

Actually it's possible to minimize the problem with explosion. For example you can check that maximum particle size must be <= 50% screen height. Anyway I think that it's too much of work and little gain.

**Comment by Alayan-stk-2** [comment]
The issue with my nvidia card is not about average fps or even fps. A second is a long time, long enough to have that kind of issue smoothed out. The issue is about abnormally long frame times (50-100% longer) which cause noticeable micro-stuttering.

If you can run the profiler for 20-30s ; and send me the report, I could analyze it.

**Comment by deveee** [comment]
I have stable ~30-50 for particles in profiler. And summarized time for all columns was ~10000-11000. For me it's sometimes not smooth when I have ~30 fps and maybe nvidia tries to use vsync.

And btw. fun fact that on nvidia I have 34fps in cocoa temple with GL and 51fps when I run it with GLES. Though the quality looks lower when I compare screenshots.
