### ISSUE TITLE
Add back button to select challenge dialog

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3518]
As far as I see it's the only place where you can't go back to previous screen by mouse click.

Maybe choose difficulty in similar way as in race setup screen and then add "back" and "start" buttons at the bottom of dialog? Not sure how to display requirements for all difficulties in this case though.

**Comment by Alayan-stk-2** [comment]
I don't think changing the difficulty selection setup would work well ; but I'd agree about having a back button available there.
