### ISSUE TITLE
GLES renderer doesn't use anisotropic texture filtering

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3521]
GLES:
![screenshot_2018-10-18_15-03-29](https://user-images.githubusercontent.com/13989090/47187142-d9505900-d2e7-11e8-8227-9f52cf5afb27.png)

GL:
![screenshot_2018-10-18_15-04-02](https://user-images.githubusercontent.com/13989090/47187144-dbb2b300-d2e7-11e8-80ea-865e0f24e665.png)

Also there is a slight but noticeable difference in the colors.

**Comment by Benau** [comment]
anisotropic texture filtering slow down on a phone very much

**Comment by qwertychouskie** [comment]
Anisotropic rendering is controlled by the "Rendered Image Quality" slider.  Even if it is slow on a phone, what about the e.g. Nvidia Shield TV?  It should be supported, though I agree it should be disabled by default on Android.

**Comment by auriamg** [comment]
@deveee Any opinion on this?

**Comment by qwertychouskie** [comment]
Hmm, it seems the lowest image quality option still uses 2x anisotropic filtering.  There would probably need to be a new preset to allow the current behavior to still be used on Android devices.  Probably the presets should be "Very Low" (new preset), "Low" (equivalent to current "Very Low"), "Medium" (equivalent to current "Low"), and "High" (equivalent to current "High").
