### ISSUE TITLE
Keyboard does not open when textfield selected with gamepad (Android)

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3528]
## Description

On Android when selecting a text field with the gamepad the keyboard does not open, on both normal Android and Android TV. But it opens when selecting it with a mouse

## Steps to reproduce

Use a gamepad with the android version and select a text field.

## Configuration

STK release version: SuperTuxKart Beta

STK Source (ppa, distribution package, official bin,...):
Google Play

System: SHIELD Android TV 2017 and Samsung A5 (2017)

Gamepads/keyboards models if related to the issue:

SHIELD Controller 2017

**Comment by Alayan-stk-2** [comment]
I think the idea was that if you use a keyboard, you don't need the visual keyboard to open because you already have a physical one.

However, while a gamepad use the same navigation system as a keyboard, it is not a keyboard and this assumption is wrong.

**Comment by deveee** [comment]
It detects if you connected a keyboard or only gamepad. But indeed atm. there is no way to open screen keyboard without mouse. Will be fixed. I hope that pressing select/fire button on text edit field is enough?

**Comment by Alayan-stk-2** [comment]
Pressing select when the text edit field is the current selection seems a good trigger.

**Comment by deveee** [comment]
It should work in current git, thanks for the report.

**Comment by Mrxx99** [comment]
@deveee Tanks for the fix. It does work now except for the login screen. There I get the message "You need to enter a password" as soon as I select on of the text fields and the keyboard does not show up.

**Comment by deveee** [comment]
Indeed, I was testing it on addons screen...

**Comment by deveee** [comment]
It should work now.
