### ISSUE TITLE
Issue with sun (light shaft)

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3531]
In tracks like Abyss and Zen Garden, the light shat does not work correctly.  This is because the sun is rotated 90 degrees from how it should be.  However, rotating it in Blender seems to have no effect in STK.

**Comment by auriamg** [comment]
you will need to be more precise, what is the issue? " does not work correctly" is too vague

**Comment by qwertychouskie** [comment]
Sun in git:
![](http://i.imgur.com/dgS0M8o.png)
Sun in 0.9.3 (correct):
![](http://i.imgur.com/kklQEmM.png)

**Comment by Alayan-stk-2** [comment]
Putting milestone to 0.10.0, as we should take special care at avoiding regressions slipping into the release.

**Comment by hiker** [comment]
@qwertychouskie , can you "git bisect" to find out where the bug was introduced?

**Comment by Alayan-stk-2** [comment]
Tested in Zen Garden and the issue shown in Qwerty's pictures is still there.
