### ISSUE TITLE
Gamepad issues

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3535]
I was trying to play with gamepad and I noticed that when I turn left, then it's smooth (it behaves the same as on keyboard), but when I turn right then it changes the direction immediately without smoothing.

It's caused by:
```
    // A digital input value is 32767 or -32768 (which then triggers 
    // time-full-steer to be used to adjust actual steering values.
    // To prevent this delay for analog gamesticks, make sure that
    // 32767/-32768 are never used.
    if(m_configuration->isAnalog())
    {
        if(*value==32767)
            *value = 32766;
        else if(*value==-32768)
            *value = -32767;
    }
```
in gamepad_device.cpp.

For my gamepad I have min -32767 and max 32767. And it's the same for both analog and dpad. So that -32768 never happens.

And second issue is that for dpad (without analog controls) it's much more comfortable when you smooth turning in the same way as on keyboard. And it seems that it always assumes that gamepad is analog?

It may be hard to detect if analog input was used, but maybe at least assume that -32767 is "max" too? So that at least turning left will behave the same as turning right? @hiker any opinions?

... or maybe -32768 is a bug, because in player controller there is ```if (steer_val > -32767)```. But it's 4 years old...

**Comment by hiker** [comment]
+-32768 is used for digital devices like keyboard etc. A gamepad should only deliver up to +-32767. This is how we distinguish if some input events are 'smoothed'.

**Comment by qwertychouskie** [comment]
IMO even analog inputs should be smoothed.  It look very weird when skidding and changing direction when they are not smoothed.

**Comment by Alayan-stk-2** [comment]
+1 to some steering smoothing with analog input.

Usually, the way the player will move the stick won't be as smooth, and this will show as qwerty pointed out.

It also changes gameplay depending on the control used - in theory, with an analog stick, it is possible to change direction faster than a keyboard player ever could, which in some situations can be significant.

**Comment by deveee** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/f3ef25d52594271f953d9db1db69a26a280309ff

Now it always smooth turning, so that non-analog gamepads work in the same way as keyboard. It also it gives more consistency when playing online, because you can't fully turn left/right immediately using analog controllers, so that there is no adventage over keyboards. It also seems that some smoothing gives better precision.

And that code shouldn't be needed anymore
```
    if(m_configuration->isAnalog())
    {
        if(*value==32767)
            *value = 32766;
        else if(*value==-32768)
            *value = -32767;
    }
```
but it's unclear for me if analog controllers are always [-32767, 32767] or maybe [-32768, 32767] for some systems/devices, so I just didn't touch it.
