### ISSUE TITLE
Karts should jump at Soccer mode.

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3537]
I think karts should jump because, the ball sometimes is too high and the kart can't reach it. That can lead to goals that can't be saved and during the match the ball is out of reach or bounds and you can't play well.

**Comment by Alayan-stk-2** [comment]
STK is not Rocket League and can't be Rocket League. Jumping would require additional controls, and would either create issues in other race modes, or a discrepancy in kart controls between race modes, neither of which is desirable.

It may be somewhat too easy to score a goal by lobbing the opponent kart, but having kart jumping is not an appropriate solution.

**Comment by qwertychouskie** [comment]
Maybe the plunger could pull the ball?  Could be interesting...

**Comment by Mensious** [comment]
Ok tomorrow i will create a new issue
