### ISSUE TITLE
Proposal for a reorganization of the options screen.

### ISSUE THREAD

**Issue by MSavoritias** [supertuxkart/stk-code#3541]
I recently started translating Supertuxkart to my language but once I came across the User Interface string I was confused as to what exactly that category represents.
To my understanding it is supposed to be about the interface like the color or the minimap setting. But then there is also the anonymous statistics option in there. And the Connect to Internet. And then you go to the player section and you have again connect to the internet and it gets confusing.
To keep things sort I have an idea about reorganising the options screen to maybe something easier to use. Here is my proposal:

The first tab is about the master profile of the particular copy of the game. The main player. Here we have the profile of the player and maybe the controls for him only. 

The second tab is the Interface. Which we have the interface category minus some things that don't make sense in my opinion to be there. Like the multiplayer handicaps or the connect to the internet option.

Third we have a multiplayer tab. Here we can move the settings like multiplayer handicaps the profile manager and split screen settings and the like. Also the controls interface here maybe or inside every individual profile.

Fourth the System tab with Video, Audio, Language. 

And last maybe it would be a good idea to have a privacy tab where we have the anonymous hardware statistics because right now there isn't an easy way to find it unless you know what you are looking for.
I am open to any suggestions.

**Comment by auriamg** [comment]
The problem with your suggestions is that they are made without context of what is possible or not with our GUI engine. Many of your suggestions are simply not doable at this time (ex: "Fourth the System tab with Video, Audio, Language.", there's not enough room on one screen to fit all of this)

**Comment by Alayan-stk-2** [comment]
It's true that several options in the UI tab are not really about UI.

I don't think that the suggested reorganization would fit.

But adding a new tab to have UI options truly about UI options and the new tab about the rest (like the internet options, handicap option...) makes sense.

The UI tab acts more like a "general" tab, so that would be my name suggestion for the tab inheriting the internet option and handicap option.

**Comment by MSavoritias** [comment]
> The problem with your suggestions is that they are made without context of what is possible or not with our GUI engine. Many of your suggestions are simply not doable at this time (ex: "Fourth the System tab with Video, Audio, Language.", there's not enough room on one screen to fit all of this)

Ok I am pretty new around here sorry for my ignorance. So we need to find a way to keep the tabs in the number they are now while being mindful of the space.

> It's true that several options in the UI tab are not really about UI.
> 
> I don't think that the suggested reorganization would fit.
> 
> But adding a new tab to have UI options truly about UI options and the new tab about the rest (like the internet options, handicap option...) makes sense.
> 
> The UI tab acts more like a "general" tab, so that would be my name suggestion for the tab inheriting the internet option and handicap option.

What if we merged the Video and Audio Tab and add the general tab so we can keep the tabs at the same number they are now. Video and Audio tabs Content can fit I think and we name it something like Game Settings or System Settings?

**Comment by Alayan-stk-2** [comment]
No, merging the video and audio tabs is not desirable.

The current UI is able to accommodate an additional tab (mind you, this menu is NOT organized as in 0.9.3, in case you have seen the translation string but not tested the git version).

**Comment by MSavoritias** [comment]
> No, merging the video and audio tabs is not desirable.
> 
> The current UI is able to accommodate an additional tab (mind you, this menu is NOT organized as in 0.9.3, in case you have seen the translation string but not tested the git version).

No actually I use the git version and I commented based on that. Your solution seems the most fitting then.

**Comment by qwertychouskie** [comment]
Maybe just rename the UI tab to "General"?  Seems like the simplest option.

**Comment by Alayan-stk-2** [comment]
![additional option tab](https://user-images.githubusercontent.com/25536748/48583734-25fb7400-e928-11e8-8ae1-5d4a25560f6a.png)

**Comment by Alayan-stk-2** [comment]
Done with https://github.com/supertuxkart/stk-code/commit/d8c9fd7fb63fb4de4aad5dcdd4ede23de2bf359d
