### ISSUE TITLE
Cup not correctly centered in unlock cutscene

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3542]
Probably related to the fix of #3092 ; as my Story Mode PR came before it.

![trophy off-center](https://user-images.githubusercontent.com/25536748/48149178-c4019580-e2bb-11e8-9fa9-c898c1ac7fd4.png)

**Comment by qwertychouskie** [comment]
Related to https://github.com/supertuxkart/stk-code/issues/3092?
