### ISSUE TITLE
Wrong checkbox behaviour in kart color dialog

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3545]
## Description

In the kart color dialog, the behaviour of the checkbox “Use original color” / “Pick a color from slider” is wrong.

As of: f696881208b1d5e74f5a380cb66302de6a7729ee

## Steps to reproduce
1. Open the kart color dialog in your
2. Tick the checkbox
3. Untick the checkbox

## Result

When you toggle the checkbox, the text changes.

When the checkbox is checked, the text says “Pick a color from slider”. You can then pick a color from the slider.
When it is unchecked, the text turns to “Use original color”. The slider is disabled and the original color is used.

**This is completely wrong.**
Checkboxes are not supposed to work like this, it's against basic usability principles. The text / meaning of a checkbox must never change for checking/unchecking it.

The second error is that when the checkbox labelled “Use original color” is NOT checked, this actually means that the original color IS used. This is also wrong.

A missing check mark in a checkbox should mean that the thing described in the text is disabled. If, and only if the check mark is there, then the described thing must be enabled.

## Possible solution

Replace the checkbox with that special multiple-choice widget with the two arrow buttons left and right. You see this often in the graphics options (I have no idea how this widget is called, it seems unique to STK).

And use “Use original color” and “Pick a color from slider” as its both entries.

**Comment by Benau** [comment]
alayan seems that you cannot use keyboard to toggle spinner in modaldialog!!
