### ISSUE TITLE
Bad use of widgets in soccer menu

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3546]
## Summary
The soccer game menu is a bit weird and confusing because it uses widgets in a confusing and unconventional way.
This issue is about poor usability.

## Steps to reproduce
1. Prepare a soccer game to go into the screen in which you select the soccer rules and teams
2. Look at the game rule widgets and test how they behave

## The problem
This issue is only about the widgets you use to select the game rules, nothing else.

Here's how the widgets look like now:

```
Number of goals until victory: [NUMBER]
Maximum duration (min): [NUMBER]
Game type: (Goal/time limt): [CHECKBOX]
```

One of the first two rows is always grayed-out, depending on the checkbox in the third line. This is kind of weird.

Why this is bad:
The problem is the meaning of the on/off state of the checkbox, which is not obvious from the text alone. Also, the game type comes *below* the settings that depend on the game type, rather than the other way around.
It also looks a bit ugly.

## Suggestion to simplify

My suggestion uses only 2 lines. The first line is always the same and looks like this:
```
Game type: [MULTIPLE-CHOICE WIDGET]
```

The multiple-choice widget (the widget with the two arrows left and right) allows to select the game type (goal limit / time limit).

The second line depends on what you selected in the first line. If you selected “Time limit”, the second line is:
```
Maximum duration (min): [NUMBER]
```

If you selected “Goal limit” instead, then the second line is:
```
Number of goals until victory: [NUMBER]
```

There are no more checkboxes and nothing will be grayed-out.

## Examples

Some examples to show you how it will look. Here are two possible example inputs from users:

```
Game type: Time limit
Maximum duration (min): 5
```

```
Game type: Goal limit
Number of goals until victory: 3
```

## Configuration

STK release version: f696881208b1d5e74f5a380cb66302de6a7729ee

STK Source: GitHub clone

## Further reading

https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/

**Comment by deveee** [comment]
I agree that it's ugly. The problem is that you can't easily modify widgets on runtime. For example if you hide a widget (which already needs a hack, because setVisible(false) is not enough), you have to recompute whole layout and reload screen to avoid empty space. It's the same with text. "Number of goals until victory" is longer than "Maximum duration (min)" and spinner widget won't be moved automatically when text is changed. Actually maybe it could be on left side...

**Comment by Wuzzy2** [comment]
Well, in this case, I suggest a variation:

```
Game type: [MULTIPLE CHOICE WIDGET]
Number of goals until victory: [NUMBER]
Maximum duration (min): [NUMBER]
```

Line 2 or 3 is grayed-out as needed.
