### ISSUE TITLE
Can't enter Fort Magma bubble in Story Mode

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3548]
## Description

Currently (be92acf0abf56d1d0906b086533ec744bbad3fd2), it is impossible to complete Story Mode because you cannot enter the Fort Magma bubble.

## Steps to reproduce
- Finish all challenges in Story Mode except Fort Magma
- Collect at least 190 points
- Drive through the open gate and try to enter the Fort Magma bubble

## Configuration

STK release version: be92acf0abf56d1d0906b086533ec744bbad3fd2
STK Source (ppa, distribution package, official bin,...): git clone from GitHub

System: GNU/Linux

**Comment by Alayan-stk-2** [comment]
Can you check if editing fortmagma.challenge fix the issue ? The file is in the data/challenges folder.

Replace : 
` <requirements trophies="190" challenges="25"/>`

By : 
` <requirements trophies="190" challenges="24"/>`

There are 21 tracks and 4 GP, but the Fort Magma challenge can't be completed before it's unlocked, so I suspect this is the issue.
