### ISSUE TITLE
If you finish a 1 kart "race", the game says that you have “won the race”

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3549]
## Description

If you completed all the laps in a nitro challenge (from Story Mode), but failed to complete the objective in time (not enough nitro / time's up), the game will write in a pink font the text “You have won the race!”.

This does not make sense.

## Steps to reproduce
- Play Shifting Sands in Story Mode (this is one of multiple nitro challenges)
- Complete all laps but make sure you will lose
- Watch what happens.

## Configuration

STK release version: be92acf0abf56d1d0906b086533ec744bbad3fd2

STK Source (ppa, distribution package, official bin,...):git clone from GitHub

System: GNU/Linux

**Comment by Alayan-stk-2** [comment]
As far as I can tell, this message appears in all races with only one kart, doesn't it ?

It seems that the fix would involve removing that message from all races with only 1 kart, rather than trying to make a special case for story mode challenges.

**Comment by Wuzzy2** [comment]
Yes, as far I remember, this message appears in all 1-kart “races”.
You're right, this message is pointless in one-kart races anyway.
