### ISSUE TITLE
Boost at race start no longer seems to work

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3550]
## Description
Is it just me, or does the starting boost no longer work in ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc? No matter how hard I try, I can no longer get that start boost.

## Steps to reproduce
1. Start a race
2. Hit the accellerate key exactly when the light turns green
3. Repeat 1 and 2 a few times to be sure it's not your fault.

You *should* get a little boost, if you timed it just right. This works in 0.9.2, but no longer in ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc, so this looks like regression to me.

Compare the behaviour of ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc with 0.9.2. In 0.9.2, your kart got a little boost, while in ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc, it now seems impossible to achieve. Yet AI karts seem to be able to pull this off reliably.

## Configuration

STK release version: ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc

STK Source (ppa, distribution package, official bin,...): git clone from GitHub

System: GNU/Linux

**Comment by qwertychouskie** [comment]
The boost has been moved to the beginning of "Set", but the AFAIK the "Penalty time" message has not yet been updated.
