### ISSUE TITLE
Time penalty message is wrong/outdated

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3551]
## Description

If I hit accellerate while the light is red and the text says “Ready?" I get a penalty.
The message says I must not accellerate before "Go".

This message was correct in 0.9.2, but is wrong in -dev. I was told the new rule is that the penalty happens if you accellerate before “Set!”.

## Steps to reproduce
1. Accellerate in “Ready?” phase
2. Read the penalty message

## Configuration
STK release version: ac02df76aa0887e38a1195d5bfb8c7ae2edd3bfc

**Comment by auriamg** [comment]
Fix by recent pull request
