### ISSUE TITLE
Add option for immediate race start for standalone-servers

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3554]
ATM a standalone server has a certain delay before a race is started. This can be quite annoying if you have a group of people who just want to play (in both directions - either because they have to wait, or maybe they agree to take a short break, and a game will start in between.

Ideally the first person to log into a standalone server should become an owner who can start a race. If that player logs out, another player becomes the owner (with an appropriate message).

**Comment by Benau** [comment]
The point of an ownerless server is to not have issue with some random jerk having owner powers to abuse on an official server

**Comment by Alayan-stk-2** [comment]
This is a setting which is decided by the server creator.

The "make the first player to enter" is already available to the server creator who wants it (for example, when I connect to "Netherlands Normal Race", I get owner status).

However, the ownerless servers have their use. The owner status confers a lot of power : kicking other players, making the next race start very fast, or never starting at all, etc. This is way too much power to give on official servers, like a ranked server.

Sure, the auto-start system isn't perfect. Maybe there could be some option the players could toggle in the UI between "wait more" and "start now" to influence the countdown, especially when the server is not full.

**Comment by hiker** [comment]
Benau, can you please be open for a discussion before closing a ticket.

I spell it out a bit clearer: the player becomes "an owner who can start a race". I did not mention to get the full right, the idea is that he can start a race earlier, without waiting for the timeout. The timeout could still be active (so I'll try to rename this ticket0, so if the owner e.g. has network problems or getting somehow interrupted (but still be the owner) ... or if that player is indeed destructive, all other players can still keep on going, though then with the delay.

**Comment by hiker** [comment]
@Alayan-stk-2 I don't understand this, I must be missing something - why do we need a status level?? All it takes is to add the existing 'start' button back in.And in my experience when playing with friends, we would usually have a bit of a chat after a race, either commenting, or asking for a break, or just saying "next". So, if you want a break, don't use a stand-alone server, but if you want to quickly race again, there is a button for you.

**Comment by Benau** [comment]
Alayan you can see if french translation doesn't have enough space or I remove the send button lol!
