### ISSUE TITLE
Giving up a race stores 59:59.999 in highscores

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3560]
## Description

Since b4df11666128b0f3d055dc00694bc5c41012246a, if you give up a race, you get into the highscore list with a time of 59:59.999. This is a regression from 0.9.2.

## Steps to reproduce
1. Start a race
2. Give up

## Notes
Probably this was introduced while fixing #3556.
@Alayan-stk-2

**Comment by Wuzzy2** [comment]
Well, it was just a guess, sorry. :D

So, the bug is that this time is *saved* into the highscore list. The time is preserved when I play the same race again.

However, this time is NOT shown in the map selection. (I made sure I hade same laps and reverse state selected.)

I also should note this happens no matter if the race is a single race or a race in GP.

**Comment by Alayan-stk-2** [comment]
Actually, giving up the race not at the very start, but a bit later gives even more hilarious results.

The standard formula used to compute times in other circumstances when the race is ended before some players have finished is also applied there. So by using zippers at the start, it's possible to do in 15s a highscore which is only approximately 60% worse than a real good time on the track !
