### ISSUE TITLE
Required time in ghost race challenges of Story Mode is not shown before the race

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3563]
## Description

If you open a ghost race challenge in Story Mode, the time you have to beat is not shown.

## Steps to reproduce
1. Start STK
2. Enter Story Mode
3. Go to Cocoa Temple and press “Shoot” (currently, this is a ghost race)

## Configuration

STK release version: b4df11666128b0f3d055dc00694bc5c41012246a

STK Source (ppa, distribution package, official bin,...): GitHub, git clone

**Comment by Alayan-stk-2** [comment]
You need to beat the ghost, you don't need to know the exact time before. You can see during the race how you fare compared to the replay, you don't need a countdown timer to evaluate your situation.

Also, the times are not well rounded times like with other time requirements.

**Comment by Wuzzy2** [comment]
No, no, I am not talking about a time limit, I am talking about the time the ghost will have. Or does the game really have no clue about the ghost time, i.e. it needs to simulate the ghost entirely to get the final time?

Are you saying the ghost time is secret? That seems pointless as you will obviously see it after you reached the finish line. ;-)

My rationale was: Gameplay-wise, a ghost race looks identical to a time-trial race against 0 karts and a time limit.
So for consistency's sake, I thought the time of the ghost should be shown before hand.

I was NOT requesting an exact countdown timer.

But none of this is important.

**Comment by Alayan-stk-2** [comment]
> No, no, I am not talking about a time limit, I am talking about the time the ghost will have. Or does the game really have no clue about the ghost time, i.e. it needs to simulate the ghost entirely to get the final time?

It would be in theory possible to display the replay's time without copy-pasting it with a time requirements in the challenge's definition. This way wouldn't need to have a countdown timer. It would be additional work, however.
 
> Are you saying the ghost time is secret? That seems pointless as you will obviously see it after you reached the finish line. ;-)
> 
> My rationale was: Gameplay-wise, a ghost race looks identical to a time-trial race against 0 karts and a time limit.
It is true that what the player need to accomplish is identical in both cases.

But there is a significant difference in how it goes during the race : with the simple time-trial with a time limit, the only information you have about well you're going is provided by the countdown timer. Providing the require time before hand is useful for somebody having some memory, to gauge how much of the time has elapsed.

With the ghost replay, you can know directly if you're currently ahead or behind the ghost, and by how much. Granted, the speed with which the replay kart goes isn't uniform all along. In most cases, the 1st lap is showing a good example to emulate, while lap 2 and 3 are weaker. But nonetheless, displaying the required final time is much less useful.

Now, the ghost time is not a secret. But I do think that at least for the first time, there is some fun in the uncertainty about what will be necessary at the end.

And my point about the fact that those times are "not well rounded" is that displaying "01:45.013", "01:58.925", "02:33.89", "04:14.349" (actually, I think it would be rounded to the closest centisecond) is much less elegant than when a nitro challenge displays "02:08.00", "02:35.00", "03:10.00", "04:20.00". A minor thing for sure, but which adds up with my other motivations to not have it displayed.

**Comment by Wuzzy2** [comment]
Is this an official rejection?

**Comment by Alayan-stk-2** [comment]
If it was only my opinion, it would be one. I'm leaving open still, in case the project leader and/or many players share your opinion.

**Comment by hiker** [comment]
I admit I don't see a good reason to display the time (then we could just not display the ghost at all). Without time it has a bit of a feeling that you actually play against an 'unknown' entity,. gives (imho) a bit more of suspense.
