### ISSUE TITLE
Possible to get 1 race/lap achievements in the overworld, in battle, in soccer

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3564]
## Description
If you skid 5 times in the Story Mode world map, you get the achievement “Skid-row”.

## Steps to reproduce
1. Create new profile
2. Go to Story Mode
3. Skid 5 times in the world map

Expected result: Nothing happens
Actual result: You get the achievement “Skid-row”.

Why this is wrong: The achievement says I have to skid 5 times in row *in the same lap*. The world map does not have laps.

So either the achivement description or the achievement trigger should be fixed.

## Configuration

STK release version: b4df11666128b0f3d055dc00694bc5c41012246a

**Comment by Alayan-stk-2** [comment]
It is also possible to get this achievement in battle or soccer mode.
