### ISSUE TITLE
No progress shown for “Gold driver” achievement

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3570]
## Description
In the list of achievements, the achievement “Gold driver” is the only achievement for which the column “Progress” is empty.

Note that “Gold driver” is also the only achievement with subgoals.

## Steps to reproduce
1. Open achievements menu

## Possible fix
One could calculate the progress column for achievements with subgoals like this:
For the progress (the number before the slash), calculate the sum of the progress of each subgoal
For the maximum progress (the number after the slash), calculate the sum of the maximum possible progress of each subggoal.

In Gold driver, this would lead to a maximum progress of 3 because there are 3 subgoals with a maximum progress of 1 each. Calculate the sum, and you get 1+1+1=3.

Another example:

Think of an achievement with 3 subgoals. The player has made the following progress in the subgoals:

3/5
2/5
9/20

The number for the progress column would be 14/30 because 3+2+9=14 and 5+5+20=30.

## Configuration

STK release version: b215bf4d228836a7cc9b04fc6ebca2a051cdf37f

**Comment by Alayan-stk-2** [comment]
The information it brings is poor in "and" cases (if one subgoal is to do 20 times an easy thing and 1 time a hard thing, the mixed number is not informative) and it gets worse with "or" conditions or deeper nesting.

A detailed progress view is accessible by opening the achievement's own dialog.

The progress column is meant for single-goal achievement, to save the player from having to open the dialog and not make that screen less informative than in 0.9.3.
