### ISSUE TITLE
No notification for unlocking SuperTux

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3571]
## Description
When you unlock SuperTux, there is no notification whatsoever, like for every other thing you can unlock.

## Steps to reproduce
1. Unlock SuperTux

Expected: In the treasure chest screen, there is at least a message like “SuperTux difficulty unlocked”
Actual: SuperTux is silently unlocked

## Configuration

STK release version: b215bf4d228836a7cc9b04fc6ebca2a051cdf37f

**Comment by Alayan-stk-2** [comment]
Duplicate of #3209
