### ISSUE TITLE
Cacti get slight magenta outline in Overworld when driving far away from them

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3584]
## Description
Cacti in the overworld get a slight magenta outline when you are far away.

Evidence:
https://i.imgur.com/k1H43VU.png

## Steps to reproduce
1. Story Mode, go into Overworld
2. Drive far away from the cacti and look at them

## Configuration

STK release version: 0221e2f6d1e3c438b7eaf7c4332f887d346fef18

System: GNU/Linux

CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz

Graphics card: Haswell-ULT Integrated Graphics Controller

Resolution: 1024×768

Graphics settings: Graphics quality level 2

But even at level 7, there seems to be a very slight magenta when I look closely at a screenshot.

**Comment by CodingJellyfish** [comment]
Looks like a graphical error. If you have reproduced this issue again, feel free to contact us.

**Comment by Wuzzy2** [comment]
I just tested this on version 1.4 on the aforementioned device again and the bug seems to be fixed. No more magenta pixels.

I also tested it on a different device and it also looks OK there.

Looks like the bug was fixed.
