### ISSUE TITLE
Big Letter font in Online Race

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3585]
## Description
When you start a online Race the letter font Is very big. As a result you can't look anywhere.

## Steps to reproduce
1. Start a online Race
2. Look the user names

## Configuration

STK release version: Git, 0221e2f
System:Gentoo

**Comment by Arthur-D** [comment]
What resolution do you use? I've tried at 800x600 and at 1600x900 but don't see nearly as big letters. Also I saw a screenshot you posted in our IRC channel, it looked like you had larger font than normal for the rank as well.

**Comment by Alayan-stk-2** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/faf5c440c2e7ff33f400d8bb26dcca65f9d5f035
