### ISSUE TITLE
The kart can drive on the sea

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3587]
## Descriptio
Fall and drive on the sea. Link:  https://peertube.mastodon.host/videos/watch/4fac78db-a4c5-4635-8260-b8e03778c52c

## Steps to reproduce
1.Start the race Around the Lighthouse
2.Drive on the sea

## Configuration
STK release version: Git, 0221e2f
System: Gentoo

**Comment by Alayan-stk-2** [comment]
Update your assets ?

This bug existed some time ago, but it has been fixed for a while. I can't reproduce at all.

**Comment by Mensious** [comment]
You were right i updated assets.Now it is working
