### ISSUE TITLE
Deterministic items are poor in battle mode

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3589]
The non-randomness of items at the beginning is not great in normal races, but bearable.

The beginning of a 3-strikes battle/FFA game is however really problematic. Each gift box will always give the same item when taken at the same time, and the first gift box will in most cases be taken at the same time in each battle as the players race to gift boxes.

The solution is to add a random seed generated (and for network, shared) at the beginning of each race/battle, much like in my unmerged PR.

**Comment by hiker** [comment]
I admit I don't see this as an issue - the items should change every 8ms, if you manage to be in the same 8ms at the same item every time then ... well done. I don't think this will give a noticeable advantage to anyone.

**Comment by Alayan-stk-2** [comment]
Isn't it 80ms and not 8ms, with 10 frames and not 1 frame ?

**Comment by Benau** [comment]
uint64_t random_number = item_state.getItemId() * 31 + world->getTicksSinceStart() / 10 + position * 23 + "a random number", which is configured at the begining of each race, ok alayan?

**Comment by Alayan-stk-2** [comment]
Yes, that's what I am asking for.
