### ISSUE TITLE
Non-ascii characters in replay author name not displayed

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3592]
Some characters don't work correctly in the replay list.

How to reproduce : 
1)Add a non-ascii character to the author name in a replay file, which is accepted for username. For my test, I first used the greek letter "Ψ", I could also reproduce with "é", and I suspect it hold true with others. I can use them in a username, it is properly rendered there, and if I restart STK, it is correctly/saved/rendered again.
2)Go into the replay list and find the replay with the modified author name.

Result : the non-ascii character is not displayed. Putting it in the middle of the name, a blank space is observed in the spot where the "Ψ" (or the "é", etc) is expected.

Potential cause : replay_play.cpp uses fgets to read characters.

**Comment by hiker** [comment]
You need to xml encode the characters - if using \&\#936; and \&\#233; it works for me.

**Comment by Alayan-stk-2** [comment]
Ok, I can confirm this. Not very practical when trying to edit by hand a name (very rare case, I know), but there is indeed no bug here. And that's better, no need to fix some code.
