### ISSUE TITLE
Cave X has poorly-placed grass which is ugly

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3593]
See #3569 for a detailed description of the issue - the only difference is that now karts can't collide with grass floating in the air, so it's only a visual issue, not a gameplay issue.

**Comment by CodingJellyfish** [comment]
We have new Cave X now. Close this please.

**Comment by qwertychouskie** [comment]
This issue still exists in the currently shipped version of Cave X:
![image](https://github.com/supertuxkart/stk-code/assets/13989090/c19c6375-a142-4851-ad77-00a06a26b8a5)
TBH it's not very noticable though, so maybe a `wontfix`.
