### ISSUE TITLE
Custom kart color does not show in GP win/lose screen.

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3597]
## Description
If you complete a GP with a custom kart color, your kart will show with its default color in the “win” or “lose” cut scene, instead of your custom color.

## Steps to reproduce
- Select a custom kart color for your profile
- Complete a GP and trigger the “win” or “lose” cut scene

## Configuration

STK release version: 95ecd55ce8f5c004f02642e41ba1cfaef0f21ec8

**Comment by Benau** [comment]
addons kart has no random color

**Comment by Alayan-stk-2** [comment]
@Benau I think you misunderstood what this issue is about.

**Comment by Wuzzy2** [comment]
## NEW steps to reproduce

1. Select a custom kart color for your profile (i.e. orange)
2. Play with Xue
3. Complete a GP and trigger the “win” cut scene
3. Complete a GP and trigger the “lose” cut scene

Expected: Xue is orange in the cut scene
Actual: Xue has default color in the cut scene
