### ISSUE TITLE
Message spam in 3-strikes battle when colliding with spare tire kart w/ full health

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3604]
## Description
If you hit a spare tire kart in 3-strikes battle but have all 3 lives left, there is a chance of your screen getting spammed by the same message (you cannot have more than 3 lives) over and over again.

## My wild guess
I guess this happens because STK detects lots of collisions in a short time.

## Steps to reproduce
1. Play 3-strikes battle on Las Dunas Arena with 9 opponents
2. Have all 3 lives left
3. Bump into a spare tire kart

## Configuration

STK release version: 95ecd55ce8f5c004f02642e41ba1cfaef0f21ec8

**Comment by Alayan-stk-2** [comment]
When hitting a spare tire kart while you have all 3 lives left, the spare tire kart should probably be removed from the arena. This would allow to deny a spare tire kart to your opponents (instead of hitting it with 3 lives being completely useless) and would also fix this UI issue.

**Comment by Wuzzy2** [comment]
100% agree, that's exactly what I suggested in the forums earlier! :D
