### ISSUE TITLE
Can always hear bubble gum pop sound, no matter how far away kart is

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3607]
## Description
In online racing, if the bubble gum of a kart far, far away goes “pop” you seem to be able to hear is at full volume still.

## Steps to reproduce
1. Race online
2. Wait until an opponent's bubble gum goes pop (the opponent must be far away)

Expected result: You don't hear it or very quietly only because the opponent is far away
Actual result: You hear the sound at full volume

Not sure if it's actually related to online racing, but that's just what I noticed when racing online.

## Configuration

STK release version: 0.10-git

**Comment by Alayan-stk-2** [comment]
As far as I know, this is not restricted to online races.

**Comment by n3rdopolis** [comment]
> As far as I know, this is not restricted to online races.

You're correct, happens in single player mode too

**Comment by auriamg** [comment]
That's because the "bubblegum_explode" sound is stereo, but should be mono

**Comment by deveee** [comment]
I converted bubblegum sound to mono.

There are more stereo sounds:
```
deve@deve:/home/Dokumenty/programowanie/supertuxkart/supertuxkart-assets/sfx$ find -iname "*.ogg" -exec sh -c 'file={}; if [ $(ogginfo $file | grep -c "Channels: 2") -gt 0 ]; then echo $file; fi' \;
./tractor_beam.ogg
./last_lap_fanfare.ogg
./rain.ogg
./WilhelmScream.ogg
./plopp.ogg
./gnu_flute.ogg
./metal_clang.ogg
./track_intro.ogg
./energy_bar_unfull.ogg
./pre_start_race.ogg
./race_finish.ogg
./dark.ogg
./start_race.ogg
./car_revup.ogg
./break.ogg
./goal_scored.ogg
```
But as far as I see it's mostly for cutscenes, so doesn't matter. The WilhelmScream matters, but it didn't play for me at all when I was hit by cannon ball.

Anyway bubblegum sound is fixed.
