### ISSUE TITLE
You can drive in the Sea Antediluvian Abyss

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3609]
## Description
You can drive in the sea when you pass through the middle of the window.
My video: https://streamable.com/rahmv
## Steps to reproduce
1. Start the Antediluvian Abyss
2. Go to the last 3 Windows on your left
3.Go throw the middle and you can drive in the sea

## Configuration

STK release version: Git (network) , d73e0d9
Latest Assets
System:Gentoo

**Comment by MarioCMFlys** [comment]
This happens on both the left and right windows
https://www.youtube.com/watch?v=fZ0G0-xM65w

**Comment by qwertychouskie** [comment]
Known bug, will be fixed along with many other bugs in this track once I finish my work on it.

**Comment by Alayan-stk-2** [comment]
As far as I can tell, this is now fixed in SVN
