### ISSUE TITLE
Missing ground in STK Enterprise

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3610]
## Description
My video: https://streamable.com/qjjhf

## Steps to reproduce
1. Start the STK Enterprise
2. Go and fall in the black hole

## Configuration
STK release version: Git (network), d73e0d9
Latests Assets
System: Gentoo

**Comment by Alayan-stk-2** [comment]
The issue doesn't seem to be a missing texture, the issue is there is no ground at all in that spot to apply a texture on.

**Comment by Mensious** [comment]
Ok sorry.

**Comment by Mensious** [comment]
Sorry i can't change the Title

**Comment by Mensious** [comment]
Ok i changed the Title

**Comment by theTomasPat** [comment]
I would like to work on this issue if no one else has claimed it yet.

**Comment by theTomasPat** [comment]
[spaceship_fix3610.zip](https://github.com/supertuxkart/stk-code/files/2766143/spaceship_fix3610.zip)

Here's a zip with only the blend file in it.

**Comment by auriamg** [comment]
I have committed the fix, thanks
