### ISSUE TITLE
The Boost is too much in Subsea

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3611]
## Description
When you drive in the Subsea track on the right road and take third boost your kart jumped and you lose the control.
My video: https://streamable.com/f9n9q

## Steps to reproduce
1. Start the Subsea
2. Drive in the right road
3.  and Take the third boost
## Configuration

STK release version: Git (network), d73e0d9
Latest Assets
System: Gentoo

**Comment by Alayan-stk-2** [comment]
Don't do bug reports about tracks which are not included in the main release. Old tracks available in the addons are unsupported.
