### ISSUE TITLE
Soccer: Parts of the HUD disappear after goal

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3621]
## Description
If you shoot a goal, parts of the HUD disappear, namely:

* Team scores / target score
* Time
* Speedometer

The HUD re-appears shortly after, when the ball respawns.

This is a bit irritating/annoying.

## Steps to reproduce
1. Play soccer with goal limit of at least 2
2. Shoot a goal

## Configuration

STK release version: 0.9.3

**Comment by Alayan-stk-2** [comment]
I agree it doesn't make sense for it to disappear in the middle of the match.

I think that the minimap stays ? I remember having changed code to do so, something similar can probably be done for the other UI elements, especially time and scores.

**Comment by Wuzzy2** [comment]
Yes, the minimap stays, oddly enough.
