### ISSUE TITLE
Modelling issues in Ravenbridge mansion

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3629]
Here is a list of issues I could find in the track which need fixing : 
- [x] Some spots with mud don't trigger a rescue at all
![missing rescue mansion](https://user-images.githubusercontent.com/25536748/49102182-705de880-f278-11e8-8d88-7d1ff10a63fa.png)
- [x] In other spots with mud, it is possible to fall through and get rescued only after having seen the track from under (which breaks immersion)
- [x] No splash effect when entering the water of the lake
- [x] Missing auto-rescue when entering the lake, making it possible to drive on its floor and see how the water is faked.
- [x] Missing auto-rescue when going off-track in the ascent towards the mansion at the beginning. Many newbies are unaware of the rescue key, and the AI will also first try to go back to the road by driving (which isn't possible).
- [x] No visual cue about the zipper speed boost which happens in the two spots where the kart jumps down from the mansion to the road outside it. Either there should be a clear zipper texture, or the speed boost should be removed. I question the point of having a speed boost at all, but even if keeping one, I would favor having it toned down like in Gran Paradisio Island.
- [x] Only half of the driveable area after the exit of the mansion (when the road is cut in two) is marked so for the AI. Both way should be marked, masking eventual inefficiencies of the AI with weird drivelines is bad practice as it hurts AI improvement. (EDIT : AI actually perform better with this added !)
- [x] The shortcut has two obvious shortcoming. First, the big nitro can is put too high over the road. Second, it uses a "cannon" to put back the kart onto the road. This is probably meant to avoid accidents. However, it makes the kart move seem much weirder than with a jump pad, and much less satisfying. A properly done zipper jump pad to exit a shortcut, like it is done in Cocoa Temple, is clearly better, it would only need minor tweaking so that the kart direction after the jump pad is somewhat more parallel to the main road than it is now.
- [x] The kart disposition at the start is terrible. The karts are tightly packed in the middle of the road. This almost guarantees that some slow starting kart will cause frustrating collision issues for others. The kart should occupy a greater proportion of the road width, and have a bigger distance to the kart in front of them and to those on the side.
![mansion start pos](https://user-images.githubusercontent.com/25536748/49112544-5ed60a00-f293-11e8-9004-e7ceb2bc19eb.png)
- [x] There is a spot where you can see "under the track" because some ground is missing (similar to issue 3610)
![mansion fall through](https://user-images.githubusercontent.com/25536748/52723510-f18e6700-2fad-11e9-90d5-6125664c31cb.png)
- [x] Make the off-road grass slow down.

**Comment by qwertychouskie** [comment]
Is Ravenbridge Mansion planned for inclusion into 0.10?  If so, can we get the source committed soon so these problems can be fixed?

**Comment by Alayan-stk-2** [comment]
It is planned for inclusion in 0.10, yes.

**Comment by theTomasPat** [comment]
I believe the source files for it are in the folder "20_mansion" in the media repo. Are those the latest files? And when was the last time this track has been updated? I'd like to help out with this track and I've identified plenty other points that could be addressed before it's ready for inclusion

**Comment by Benau** [comment]
The final one is in a private repo, the 20_mansion you see there is incompleted.

**Comment by theTomasPat** [comment]
Oh ok! Disregard my last comment then :)

**Comment by Benau** [comment]
https://streamable.com/5uzwm
?
