### ISSUE TITLE
Alien Signal issue with navmesh

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3637]
## Description

The gift package arena navmash does not cover the whole arena. 
Here I guessed how big the navmash should have been and also note the wholes in the navmesh:
![aliensignalnavmesh](https://user-images.githubusercontent.com/33566379/49250780-0f711480-f420-11e8-885f-3150cdf929e7.png)

In this video you can see that because of that the AI karts can't find the player if he is outside:
https://youtu.be/5agw3rD98vc

## Steps to reproduce
Start a three strikes battle in Alien Signal

**Comment by Benau** [comment]
[alien_signal.zip](https://github.com/supertuxkart/stk-code/files/6527453/alien_signal.zip)

![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Mrxx99** [comment]
Thank you very much it works fine now.
Is this also replaced in the donators pack on itch.io?
If yes you can close this issue.

**Comment by Benau** [comment]
We no longer ![](https://cdn.lihkg.com/assets/faces/dog/beg.gif) because ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) is ![](https://cdn.lihkg.com/assets/faces/cow/gold.gif)

Miniz will try to add CTF mode to it by the way ![](https://cdn.lihkg.com/assets/faces/mouse/cheerleading.gif)
