### ISSUE TITLE
Changing resolution causes crash.

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3639]
## Description

When changing resolution there is a crash as soon as you press any key to confirm the new resolution. If you don't press any key the resolution will reset normally without a crash.

## Steps to reproduce

Change resolution

## Configuration

STK release version: current git master

System: Windows 10 64-bit

Graphics card: NVIDIA GEFORCE GTX 1050

CPU: Intel Core i5-8250U

## Additional information
The crash was in abstract_state_manager.cpp
![grafik](https://user-images.githubusercontent.com/33566379/49329760-9d661000-f584-11e8-8b7b-9c7f5bc63d1f.png)
(It didn't have any crash message)

The crash happend in debug as well as in release configuration

error
```
Call stack:

 <no symbol available>
 purecall
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 <no symbol available>
 asCreateLockableSharedBool
 BaseThreadInitThunk
 RtlUserThreadStart
---------------------------
OK   
---------------------------
```

**Comment by deveee** [comment]
Does it happen when you explicitly press "confirm" button, for example by mouse? Because when this dialog window appears none of these buttons are hovered and it looks that it tried to close whole options screen when dialog window was still active (eg. using back arrow). 

It works for me on linux using mouse and keyboard.

**Comment by Mrxx99** [comment]
Pressing the button by mouse works fine.

It only seems to crash when pressing the up or down key on the keyboard. Pressing e.g. first left and then up or down it does not crash

**Comment by deveee** [comment]
No more time today, but indeed it crashes when I press down button.

In ```EventHandler::sendNavigationEvent()``` the ```getFocusForPlayer()``` returns ribbon widget. 

Maybe we can check if widget belongs to modal dialog. If not, then set it to null, so that proper default widget will be selected. Or reset focused widget before dialog window creation...
