### ISSUE TITLE
AI got stuck in Math Class

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3655]
Sara is getting stuck in a rescue loop in math class (non-network race)
https://youtu.be/m-pkjfQgV_4
She apparently tries to steer (front wheel turning), but not accelerating?? Didn't have an opportunity to debug - sorry. Not sure if it's actually the AI, or related to something else.

**Comment by hiker** [comment]
So far I have not been able to reproduce the issue, I tried similar races, increased the number of Sara's (in case that it is something kart specific), but it all is working fine so far :(  Even forcing a rescue on Sara at the same position did not trigger the problem.

**Comment by Alayan-stk-2** [comment]
The issue seems exceedingly rare since no new report has surfaced. It probably can still happen, as the relevant AI code wasn't changed before the 1.0 release.

The AI will be reworked from the ground up for 2.0, so there is no point tracking this issue anymore.
