### ISSUE TITLE
Sometimes there are no invisible walls where they are there not needed

### ISSUE THREAD

**Issue by Mensious** [supertuxkart/stk-code#3658]
## Description
When you are drifting suddenly, you collide the tube on the ground you Jump in saw and you can drive into. Video: https://streamable.com/p4n2j

## Steps to reproduce
1. Start the Las Dunas in 3 strikes battle mode
2. Right here In track (Las Dunas)

![right here](https://user-images.githubusercontent.com/44165312/50282267-e6f69c00-045a-11e9-921a-875a9fcf660f.png)
3. DO drift and collide the tube on the ground

## Configuration

STK release version: Git, efd502c
System: Gentoo

**Comment by Benau** [comment]
fixed
