### ISSUE TITLE
The puddle in Green Valley gets high above the ground to the right

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3663]
The puddle in Green Valley gets high above the ground to the right, which looks unrealistic. It should be even with the ground.
![greenvaley](https://user-images.githubusercontent.com/6499211/50408807-f6287180-07ed-11e9-8d73-483876d5345f.png)

**Comment by Benau** [comment]
seebi no more irc! (come and join us!)
and this track is going to be replaced soon anyway, sorry

**Comment by Flakebi** [comment]
Ah sorry, I often do not find the time to join :)
Ok, then it’s fine.
