### ISSUE TITLE
Kart positions are off in the Grand Prix win screen 

### ISSUE THREAD

**Issue by Flakebi** [supertuxkart/stk-code#3669]
Pidgin’s (2. place) position is before the stump, the other karts position is better, but could also be a bit more backwards.
![grandprixwin](https://user-images.githubusercontent.com/6499211/50578251-7c206a00-0e37-11e9-84bf-d6264e066110.png)

**Comment by qwertychouskie** [comment]
Wow, that's not right.  Not sure what changed, it was just fine when I revamped the scene and code.  @Benau / @deveee / @auriamg / @hiker did anything recently change with the code here?

**Comment by Flakebi** [comment]
Update: This happened only one time, it is fine for the second grand prix now

**Comment by qwertychouskie** [comment]
Do you have a way to reproduce the issue or was it just a one-time thing?  Was it a network race or just normal when it happened?

**Comment by Flakebi** [comment]
Hm, seems like I can’t reproduce it, I did the same grand-prix again (though beasty got second) and it looked good.
