### ISSUE TITLE
Image-based lighting confusion?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3674]
The defined IBL texture, as far as I can tell, only changes the reflection color.  The skybox texture is used for reflection.  Is this how it should be?  If the IBL texture is really only setting a color, what does this bring?

@Benau / @vlj / @samuncle Can you shed some light on how IBL/spherical harmonics works?

Also, I want to use `stk_generic_racingPattern_a.png` as a reflection texture in the kart selection screen (otherwise metallic parts look plasticy, e.g. the new Beastie's tailpipes), but setting a skybox texture shows the skybox on the kart selection screen.  Is there a way to set a reflection texture without having a visible skybox?

**Comment by samuncle** [comment]
The skybox is for the sky and reflection

The ibl is to have colored ambiant light check ibl on Google image

**Comment by samuncle** [comment]
BTW very good idea to add a skybox in the selection screen

An ibl texture would also help.

**Comment by Calinou** [comment]
Maybe the option could be renamed to "Environment mapping" or "real-time reflections" (if reflections are real-time)?

**Comment by auriamg** [comment]
IBL is the correct term : https://en.wikipedia.org/wiki/Image-based_lighting

Environment mapping and real-time-reflections are something else, the option as implemented in STK does not do reflections so it would be incorrect to call it that
