### ISSUE TITLE
SPM exporter doesn't seem to handle vertex colors well

### ISSUE THREAD

**Issue by MTres19** [supertuxkart/stk-code#3677]
For some reason the SPM exporter throws an error trying to export the library node `stklib_autumnTree_e`. It has something to do with the vertex colors—I pulled this library node from Sven's Black Forest track. For now I got it to export by removing the vertex colors but I didn't save the blend so the media repo copy still has the vertex colors even though the exported version in stk-assets does not. I have the latest version of the scripts, too, so that's not the problem.

**Comment by Benau** [comment]
blender 2.79?

try around line 687
```
-                    vertex_color = [min(int(vcolor.r * 255) , 255),\
-                    min(int(vcolor.g * 255) , 255), min(int(vcolor.b * 255) , 255)]
+                    vertex_color = [min(int(vcolor[0] * 255) , 255),\
+                    min(int(vcolor[1] * 255) , 255), min(int(vcolor[2] * 255) , 255)]
```

**Comment by MTres19** [comment]
Yep, that seems to have fixed it. And yes, Blender 2.79.

**Comment by Benau** [comment]
The exporter in blender_26 is now with the above patch

**Comment by qwertychouskie** [comment]
@Benau It seems you reverted part of the exporter when applying the patch.  Can you fix this?
