### ISSUE TITLE
Drive-on material sound can be heard even if the kart is standing or if the game is paused

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3678]
## Description
If a kart is standing for example on a wooden bridge like in Battle Island the "driving on wood"-sound is played even if the kart is not moving, also if the race result screen is shown.

## Steps to reproduce
example:
1. Start a multiplayer 3 strikes battle with two players on Battle Island
2. drive with one kart on the top of the wooden bridge and stop the kart (ensure it is not moving slowly downwards)
3. you now still here the wood sound
4. with the other kart hit the first kart 3 times but be sure to use a cake for the last hit and throw while not being on the bridge.
5. In the race result screen you can still hear the wooden sound

**Comment by Alayan-stk-2** [comment]
The standing still thing depends on the min_speed parameter of the SFX effect of the material. With any sensible value, there is no issue when standing still (and there is none currently in the mentioned test spot)
