### ISSUE TITLE
Unable to use 1080p with a 4k screen in fullscreen mode

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3689]
The bug doesn't exist in 0.9.3,but in the git version.
![5](https://user-images.githubusercontent.com/35170687/50770803-802f0a80-12c3-11e9-8af5-e90001aa4bc0.png)

**Comment by deveee** [comment]
From what I see based on the fps rectangle, it still thinks that the window size is 3840x2160 while real window size is 1920x1080. Does it happen on windows/linux/other?

And here is similar bug report:
https://github.com/supertuxkart/stk-code/issues/3614

**Comment by deveee** [comment]
Duplicate of #3726

**Comment by dumaosen** [comment]
The issue fixed miraculously on my computer.
