### ISSUE TITLE
More server states required

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3691]
Long term we want to support the following 5 server 'states' (states might not be the best word):
- official, ranked: a server we run, which is ranked
- official, unranked: a server which we run, which is not ranked
- ranked: a trusted server not provided by us that is ranked
- trusted: a truster server, i.e. a server we believe has not been patched 
- none (default): none of the above.

The support for 'official' server is mostly long term, when we add new states it might just be easiest to add it all at the same time.

We should avoid the term 'official' for all ranked server (which we have atm afaik), since we can't really do anything if a server run by someone else has a problem.

**Comment by qwertychouskie** [comment]
Maybe replace "none" with "community". (sounds nicer :)

**Comment by jpenguin** [comment]
If server has
    <server-configurable value="true" />

It would be nice to mention that in the s4rver list

**Comment by jpenguin** [comment]
If you call the servers run by core STK devs "trusted" it kinda implies that all other servers are hacked.  Maybe just Official/Volunteer/Modded

**Comment by jpenguin** [comment]
I agree, I'm saying the average steam user won't realize that

**Comment by hiker** [comment]
With #3745 waiting to be merged that fixes the name the user can see, the rest of this can be postponed till the next release.

**Comment by v1993** [comment]
Now server owners are:

1. `-`
2. `Trusted`
3. `cddepppp256server`

I think this looks pretty confising because

1. Most servers have no owners
2. `Trusted` is not an owner, it is state

**Comment by Benau** [comment]
option 3, we use ☆★STK★☆ (like ghost replay) for the owner field, and change the help to "Some of them are recommended servers with optionally ranked races."

this is less "weird" and translator can translate better.

and i have no intention to distinguish so-called official or trusted, esp there will never be pay-to-play ranked servers, or let people who only donate can join official servers is something that you want

**Comment by Benau** [comment]
@jpenguin we update the server code now it can listen to ipv6 address, have time to update play stk? (Visit irc for details)

**Comment by jpenguin** [comment]
I think I'll have time today, thanks.

**Comment by Benau** [comment]
not sure @jpenguin can update his servers for 1.1 (and addons list!)... (btw 1 playstk server seem to be gone, do you have coredumpctl gdb supertuxkart if it crashed?)

also do u see stk dual license mail.... ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by jpenguin** [comment]
I did get the license mail.  I just got home, I'll see about updating

**Comment by Benau** [comment]
jpenguin no reply the mail....

**Comment by jpenguin** [comment]
The new license sounds good to me.  I had to relaunch my servers, my ssh keys were lost.

**Comment by Benau** [comment]
thank you
...
you may also want to download some new addons..... (canyon 42!)
