### ISSUE TITLE
Minor issue in ghost replay table

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#3695]
See the screenshot:
![zrzut ekranu z 2019-01-09 23-12-45](https://user-images.githubusercontent.com/5108558/50934155-1dc33f00-1468-11e9-8a5b-f24c6d1680d8.png)

I'm not sure if it was intended to make the "SuperTux" text next to the icon, or maybe it should show only icon without text.

**Comment by deveee** [comment]
And btw. I also get
```
[error  ] Replay: Replay with UID of llu not found.
[error  ] Replay: Replay with UID of llu not found.
[error  ] Replay: Replay with UID of llu not found.
[error  ] Replay: Replay with UID of llu not found.
[error  ] Replay: Replay with UID of llu not found.
```

**Comment by Alayan-stk-2** [comment]
The icon should be displayed next to the difficulty name, not on it, this is definitely a bug.

As for the UID error, Benau reported it to me some time ago. IIRC, it is completely harmless, but a fix is needed to avoid the message being sent incorrectly.

**Comment by Alayan-stk-2** [comment]
I think that's good for now, no need to add many complications before we even have a use case for it, imho.
