### ISSUE TITLE
Something bad happens when the graphic level is 3 in Android

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#3699]
OS：Android
version：0.10beta1
The minimap and the kart displays badly when the graphic level is 3.
I will show you some pictures later.

**Comment by Mrxx99** [comment]
Can you change the title? It is not very informative.

**Comment by jpenguin** [comment]
The model of your device and/or the GPU please

**Comment by dumaosen** [comment]
Sorry, I pressed"commit"in mistake when I was typing the issue.
And the device is mate10 pro.

**Comment by dumaosen** [comment]
![default](https://user-images.githubusercontent.com/35170687/51064681-e0afa600-163b-11e9-91bb-7ee840fe8dcb.png)
![default](https://user-images.githubusercontent.com/35170687/51064688-e86f4a80-163b-11e9-89b3-68ee284baa25.png)

**Comment by qwertychouskie** [comment]
Hmm, seems like an RTT issue.  @Benau ?

@dumaosen Also make sure you have all device updates installed.

**Comment by dumaosen** [comment]
Sorry, but the issue only appears in level 3 and I can't get the exact option.

**Comment by dumaosen** [comment]
Waiting for feedback? I found the certain problem that the issue appears when the advanced pipeline on with no glow effect on my mate 10.

**Comment by Benau** [comment]
Driver bugs is difficult to fix, we can at best bypass it with some hacks in stk, but the best hope for you is to check if there is new rom for your phone to update...

**Comment by Benau** [comment]
so does it work if you enable glow effect?

**Comment by Alayan-stk-2** [comment]
I don't think a hack inside STK to go around this weird behaviour can be expected in a reasonable time frame, and hardware-specific issues lose relevance with time.
