### ISSUE TITLE
If you Esc in networked game, windows says “Pause” but game is not paused

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3700]
## Description
If you hit Esc in a networked game, the window/panel that pops up says “Pause” but the game is not actually paused (because it's a networked game, obviously).

## Steps to reproduce
1. Play a networked game
2. Hit Esc (to make the menu pop up)
3. See what the panel says on the top

## Configuration
STK release version: 43885eacf2f99128c42c31eb315d528a9d675abf

**Comment by Benau** [comment]
fix in 2bfa0f5
