### ISSUE TITLE
Online Multiplayer bots

### ISSUE THREAD

**Issue by mitros123** [supertuxkart/stk-code#3706]
## Description
There does not seem to be a way to add bots in online multiplayer.
I created a server, tried to play a battle or a soccer match, but while I could select the bot difficulty, I could not set the number of bots. As a result, none appeared. 

STK release version: 
0.10 beta. Basically master branch from 13-1-2019, compiled from source.

Suggestion: Please add an option "Add X bots", especially in battle or soccer modes.

**Comment by Benau** [comment]
the current design of network can only allow server to add bots

**Comment by Benau** [comment]
you can with latest master, use the command line with seperate stk instance bin/supertuxkart --connect-now=127.0.0.1:2759 (if u use default port) --no-graphics --network-ai=x (number) after you create your server (currently only possible for ffa)

**Comment by arendtio** [comment]
@Benau I tried your command on a LAN server and it seems to work just fine (version 1.0.2). I am not quite sure why you closed the issue as I think this is a valid request. I have no idea what your architecture looks like, but having a GUI option to enable bots when creating a server would be a lot more user-friendly ;-)

Great work by the way :-)

**Comment by MartinX3** [comment]
Yes, please reopen the issue ticket.
It is a valid wish for a todo list task :)
