### ISSUE TITLE
Add a way to avoid skinning for rigid part (kart)

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#371]
**Author: narann**

For now rigids parts are skinned in blender when they are animated.

I suppose this create some performance prob because rigid part could only have one transformation and with skinning it's one by vertex.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/315

**Comment by auriamg** [comment]
Now that we have gpu skinning this seems no longer relevant, skinning is fast enough now (and people on old computers can just disable animations).
