### ISSUE TITLE
Use graphics level 4 as default

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3711]
Since STK got a lot of optimizations, IMO the default level should be 4.

**Comment by dumaosen** [comment]
I agree, but IMO the Android version should leave it as it is because most of the tracks cannot reach 24 fps in level 4.

**Comment by Alayan-stk-2** [comment]
For people with integrated graphics, level 3 is definitely better, as the better FPS really matters.

On the other hand, for people with a decent standalone graphics card, level 4 or 5 isn't an issue even with a big resolution.

Unless we detect the hardware and change the default depending on it, level 3 seems a better default in my opinion (we're discussing only the computer version default here).

**Comment by Mrxx99** [comment]
Ideally on first launch the user will be asked if he wants to run a benchmark. Which runs the currently most demanding track with e.g. 10 AIs with different graphics levels

**Comment by qwertychouskie** [comment]
I can run level 4 quite well on Intel HD 4000 at 1366x768 fullscreen.  Maybe set default level based on availabe OpenGL level?  Level 1 or 2 for GLES3, Level 3 for GL3.3, Level 4 for GL 4.0+, Level 5 for GL4.5+, Level 5 for GLES3.2+ (e.g. Nvidia shield TV).  Alternatively, base it on a manufacturer/year mfg. combo?

**Comment by LoadingPleaseWait** [comment]
I think we should leave it as it is. My laptop cannot run STK at 4.

**Comment by Alayan-stk-2** [comment]
May be done through #3743, but otherwise the default will remain as is. Playable framerates are more important than eye-candy.
