### ISSUE TITLE
Unlimited (?) character limit for messages in online lobby 

### ISSUE THREAD

**Issue by mitros123** [supertuxkart/stk-code#3714]
When I enter a huge text in the lobby (before I press "send"), my game freezes. After some time it may unfreeze (or the game may start, but without ever showing the track voting screen). Please set a limit to the number of characters a message can be.

## Steps to reproduce
Log in to an online match, and in the lobby where players press "ready", write a long message. Ctrl-A to select all, Ctrl-C to copy, Ctrl-V to paste a few times. Soon the game will freeze.

STK release version: 
master branch, 16-1-2019

**Comment by hiker** [comment]
A quick test (randomly checking what the game is doing when it becomes too slow) seems to indicate that it is rendering of the text that is so slow. So limiting the number of characters should indeed fix this issue.

**Comment by TheMinefighter** [comment]
definitely needed: had a player called bice on the poland server for half an hour spamming extremely long messages covering the whole screen

**Comment by dumaosen** [comment]
See #3897

**Comment by Alayan-stk-2** [comment]
It was limited to 1000 characters here : https://github.com/supertuxkart/stk-code/commit/88adfbc8df4e8f155ed55cd81b9a5046cabda9b4

I limited it to 360 characters as in practice 1000 was still too high.
