### ISSUE TITLE
Poor wording of English Skid-row description

### ISSUE THREAD

**Issue by LoadingPleaseWait** [supertuxkart/stk-code#3716]
The current wording is "make 5 skidding in a single lap." The sentence has incorrect grammar which makes it more difficult to understand. Perhaps the description could be something like "Skid 5 times in a single lap."
https://github.com/supertuxkart/stk-code/blob/master/data/achievements.xml#L153

**Comment by hiker** [comment]
Fixed in 9059789ee8874387600f8c69ffb7f7fb7187d900.

Thanks!
