### ISSUE TITLE
Can't set non-native screen resolution (Intel graphics)

### ISSUE THREAD

**Issue by schirmeier** [supertuxkart/stk-code#3726]
(Ubuntu 18.04, supertuxkart 0.9.3-1) When I try to set a screen resolution lower than my notebook's native 2560x1440, STK asks me to confirm the new resolution, but the "confirm" button isn't labeled, and mouse clicks have no effect:

![screenshot1](https://user-images.githubusercontent.com/763202/51793159-33e93300-21bc-11e9-9378-26e606a0b1a4.png)
![screenshot2](https://user-images.githubusercontent.com/763202/51793160-39df1400-21bc-11e9-9899-4dc4c41505e1.png)

Working around this by setting the resolution on the command line (supertuxkart --screensize=1280x720) does not work either; the resolution seems correct, but the start screen's background image looks faulty, and mouse clicks have no effect:

![screenshot3](https://user-images.githubusercontent.com/763202/51793188-c2f64b00-21bc-11e9-9286-015240547dc2.png)

Keyboard works interestingly, but once I enter Singleplayer, the GUI's resolution seems to have changed to something larger than the screen, cutting off most elements:

![screenshot4](https://user-images.githubusercontent.com/763202/51793206-02249c00-21bd-11e9-825e-11f5aaae8728.png)

**Comment by schirmeier** [comment]
Note that in screenshots 2 to 4, I actually saw a screen resolution reduced to 1280x720 with the upper left quarter of the screenshot fullscreen.

**Comment by deveee** [comment]
It baheves for me the same when I simulate that ```XGetGeometry(display, window, &tmp, &x, &y, &Width, &Height, &borderWidth, &bits);``` returns incorrect width and height (for example desktop size rather than window size).

Now in current git you can force legacy fullscreen with ```export IRR_DISABLE_NETWM=1```
https://github.com/supertuxkart/stk-code/commit/cb8ee53edcfd760b517c419aa6ef4f9921aa6dce

Atm. I don't have better idea, sorry.

... or maybe it's possible to read current window size using netwm.

**Comment by deveee** [comment]
If you can compile yourself, does it work if you apply this patch?
```
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
index f999f8f15..f78660cdf 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
@@ -1231,6 +1231,8 @@ bool CIrrDeviceLinux::createWindow()
 	int x,y;
 	unsigned int bits;
 
+	XFlush(display);
+	XSync(display, false);
 	XGetGeometry(display, window, &tmp, &x, &y, &Width, &Height, &borderWidth, &bits);
 	CreationParams.Bits = bits;
 	CreationParams.WindowSize.Width = Width;
```

**Comment by deveee** [comment]
I reproduced it on kde on ubuntu 18.04. Actually not exactly the same case. For me XGetGeometry shows dimensions with decorations even though window is already changed to fullscreen.

And before reading window dimensions we check in a loop if window is already in fullscreen mode. So window manager shouldn't tell us that it's ready while it itsn't yet.

For me it's enough to add ```sleep(100, false);``` before XGetGeometry, but it's another ugly hack...

**Comment by schirmeier** [comment]
If it still helps you, I can compile STK myself. Or do you already have enough information?

If not, should I build the current git HEAD with the XFlush(...) patch? Or with sleep()? Or both?

**Comment by deveee** [comment]
@schirmeier It looks that in order to use WM fullscreen, we must support resizeable window. There is no solution to make it 100% correct, because window manager can change window size anytime.

Tbh. I really don't like the idea of using legacy fullscreen, because it means, that you can't use alt+tab, change sound volume, move window to another desktop, close with alt+f4 or anything...

Can you move changeResolution() just above XGetGeometry and then add sleep to see how much time it needs in your case to work correctly? It will be something like
```
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
index 17b26d0d1..8e9374028 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
@@ -702,7 +702,6 @@ bool CIrrDeviceLinux::createWindow()
 		SupportsNetWM = (len > 0);
 	}
 
-	changeResolution();
 
 #ifdef _IRR_COMPILE_WITH_OPENGL_
 
@@ -1226,7 +1225,10 @@ bool CIrrDeviceLinux::createWindow()
 	u32 borderWidth;
 	int x,y;
 	unsigned int bits;
-
+	
+	changeResolution();
+	sleep(100, false);
+	
 	XGetGeometry(display, window, &tmp, &x, &y, &Width, &Height, &borderWidth, &bits);
 	CreationParams.Bits = bits;
 	CreationParams.WindowSize.Width = Width;
```

Under Gnome I need less than 50ms, so it's never a problem.

**Comment by deveee** [comment]
It should work in current git (please test if you can). Solution is far from perfect, but to fix it properly we need support resizeable window and it needs a lot of work, so that it's not possible before the release.

**Comment by schirmeier** [comment]
The current git HEAD (commit 95b3527) seems to work for me, thanks!

**Comment by CodingJellyfish** [comment]
> It should work in current git (please test if you can). Solution is far from perfect, but to fix it properly we need support resizeable window and it needs a lot of work, so that it's not possible before the release.

yay
