### ISSUE TITLE
Bad starting positioning of karts in Golf track

### ISSUE THREAD

**Issue by RGB-es** [supertuxkart/stk-code#3727]
## Description
When the Golf track is run "backwards" the first kart on the grid is on top of the starting line. That makes that STK does not count the first lap of that kart unless you moves backwards and then forwards to actually "cross" the line.

## Steps to reproduce
1- Run the "End of the world" championship with all tracks in reverse
2- Win the first race :)
3- When you start at pole position on the Golf track and go ahead, STK does not count the first lap until you came back to the starting line, adding a lap to your race!

**Workaround**: when the race start, move backwards to get off (and behind) the starting line and then forwards to cross it.

## Configuration

STK release version: 0.9.3 

STK Source (PPA, distribution package, official binary, etc.): 

System: openSUSE 15.0 Games repository build

Graphics card: Intel integrated, 3rd gen

CPU: Intel core i3.3217U

**Comment by Benau** [comment]
It's fixed in 0.10 already
