### ISSUE TITLE
Improving some nitro and item placements

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3729]
The standard replays often make use the current nitro placements, so for tracks where nitro is changed, the replay will have to be redone if he make use of the changed nitro.

The following tracks exhibit item placements to improve : 
- [x] Northern Resort : I suggest moving the 2nd big nitro can to the outer edge of the curve instead of the inner edge. A big nitro can is a significant advantage and can justify taking a slightly longer trajectory. Having it in the fastest trajectory makes it too powerful, and gives too much of a penalty to a player unable to get the big nitro can because it has not yet respawned.
- [x] Volcano Island : Change the big nitro can right at the end (or the start from reverse) to a small nitro can. This small/big/small pattern is unusual, the big nitro in the middle is not hard to catch, and it gives too much of an advantage for the player getting it first and denying it to a player chasing behind. Also, a few well placed bananas (no wall, but enough to sometimes catch careless players) would spice it up.
- [x] Zen Garden : it should have much less item boxes inside the tunnel, and the very first item box after the start should be removed too.
- [x] Fort Magma : some nitro cans are uncatchable without crashing or losing time
- [x] Oliver's math class : remove the third serie of item boxes after the small fork in the road to avoid having too much item boxes.
- [x] Minigolf : remove the line of item boxes just after the starting line. It is too close to the start and there is already many boxes before and after the tunnel
- [x] Lighthouse : Remove the innermost two item boxes in the curve following the two item box on the left/two nitro on the right arrangement, leaving a choice : worse trajectory and item, or no item.
- [x] Black Forest : ~~I will write details when @MTres19 will have finished his work and the track is integrated. Assuming the abuse of bananas has already been fixed, it's about some nitro cans tweaks.~~ The track mostly suffers from some suboptimal nitro placements. Here are the changes I'd like : 1)Move the first serie of item boxes slightly farther from the start, halfway between the current position and the bridge. 2)In the first left main path, there is item box/nitro/item box to the left and banana to the right. It is quite easy to get nitro and 2nd item box together. Placements should be rearranged to avoid this. 3)On the main path after the section near the railroad, there is a single big nitro can in the middle of the road. Remove it altogether. 4)On the second main left path (around the monastery hill), there is three small nitro cans across the road, but put in a way that a player can take 2 or 3 of them. Change their position so only one can be taken. 5) On the first right main path, there is two nitros/item box/two nitros. Use a single small nitro can instead of the doubled version, nitro/box/nitro. 6) Also on the first right main path, there is an empty dead tree with 2 big nitro cans and an item box. Replace the second big nitro can by a small nitro can.
- [x] Candela City : place the big nitro can soon after the start more to the left (same distance to the banana as current version, but more behind it) and add an alternative small nitro can to the right. Replace the second big nitro can by a small one.
- [x] Green Valley : replace the 2nd big nitro can (the one closest to the end of the track) by 3 small nitro cans disposed so that a player can only get one.
- [x] Hacienda : the first serie of item boxes is very close to the start, too close. I would remove it and do a few related adjustements. In the building, replace the lone item box by two. In the canyon, put the first two item boxes a bit earlier, replace the second group of item boxes by two small nitro cans on the inner side of the curve and a big nitro on the outer, while replacing the nitro close to the end by item boxes.
- [x] Old Mine : remove the nitro close to the end that can't be taken without losing time even in easy
- [x] STK Enterprise : This track has an overload of item and nitro. I'd remove : 1) The nitro between the two close bananas (after the road has been split and reunited) ; 2)In the area following the tight curve with three small nitro cans, I'd remove two of the four nitro cans (one on each side) and the first two item boxes (keep the box/banana/box). 3) At the end of this section I'd remove the two small nitro cans left of the banana. 4)Remove the two small nitro can before the zipper jump pad.
- [x] Northern Resort bis : the first nitro and item box (in reverse) are quite close to the starting line and the player first on the start line is guaranteed to get them if he accelerate properly. There is already more than enough boxes and nitro in the track, so remove those.

**Comment by theTomasPat** [comment]
Fix for Northern Resort
[snowmountain.blend.zip](https://github.com/supertuxkart/stk-code/files/2839198/snowmountain.blend.zip)

**Comment by theTomasPat** [comment]
Fix for Zen Garden
[zenGarden.blend.zip](https://github.com/supertuxkart/stk-code/files/2848373/zenGarden.blend.zip)

**Comment by theTomasPat** [comment]
@Alayan-stk-2 : What do you think about adding bananas in these spots?

https://imgur.com/a/ABH6qCF

I figure putting some on the inside of the turn will force faster players to use slower lines and then that last one on the outside to add a little interest before the straight.

**Comment by theTomasPat** [comment]
Fix for Minigolf
[minigolf2b.blend.zip](https://github.com/supertuxkart/stk-code/files/2848486/minigolf2b.blend.zip)

**Comment by theTomasPat** [comment]
Fix for Around The Lighthouse
[lighthouse-terrain.blend.zip](https://github.com/supertuxkart/stk-code/files/2848495/lighthouse-terrain.blend.zip)

**Comment by Alayan-stk-2** [comment]
@theTomasPat The reason I didn't suggest bananas in the curves is that players would see them quite late. I think this would punish more decent players who don't know this by heart than very good players who would avoid them anyway.

Here with the yellow spots are banana placement ideas :

![volcanobanana](https://user-images.githubusercontent.com/25536748/52536486-7b92c180-2d5b-11e9-92db-ff85b7a81ee6.jpg)

**Comment by theTomasPat** [comment]
Sure! Is there anywhere else on the track that should have bananas?

**Comment by Alayan-stk-2** [comment]
I've raced around the track to check, and apart from the tunnel I don't see a suitable area for additional bananas without overdoing it.

**Comment by theTomasPat** [comment]
Oh ok! I wasn't sure about bananas in the tunnels and was kind of leaning against it. Do you think there should be more in there as well? What kind of pattern are you thinking?

**Comment by Alayan-stk-2** [comment]
I think we can leave the tunnel as is for now. We may always reevaluate this in the future.

**Comment by theTomasPat** [comment]
Sounds good!

Here's the fix for Volcano Island:
[volcan_island.blend.zip](https://github.com/supertuxkart/stk-code/files/2853416/volcan_island.blend.zip)

**Comment by auriamg** [comment]
The zen garden tweaks have been committed, thanks

**Comment by auriamg** [comment]
The minigolf tweaks have been committed, thanks

**Comment by auriamg** [comment]
The lighthouse tweaks have been committed, thanks

**Comment by auriamg** [comment]
The candela tweaks have been committed, thanks

**Comment by auriamg** [comment]
The fort magma tweaks have been committed, thanks

**Comment by auriamg** [comment]
The volcano tweaks have been committed, thanks

**Comment by theTomasPat** [comment]
My pleasure!

Do either of you know if the blend file in the media repo is the most recent? When I try exporting it, there's a LOT of differences to the official version in stk-assets.

**Comment by Alayan-stk-2** [comment]
I tested the fixes. Most are good, well done.

There is however a small issue for Candela City : the small nitro can is aligned with the banana, not the big nitro can. This means that instead of the intended big or small can possibility, it is possible to get both, which goes against the design idea of limiting nitro denial potential by having one of the two cans available for a kart close behind.

**Comment by theTomasPat** [comment]
Fair enough! I couldn't for the life of me get both nitros while playing SuperTux difficulty but setting it even to intermediate made it fairly easy to get them. I've moved the big nitro further to the left so getting both is practically impossible without also getting the banana or going off the track altogether.

I wonder though, would making it possible to get the item box AND the big nitro make too much of an advantage? Would it be better to change the pattern instead to something like this?
```
|         |
|    I    |
|    B    |
| n     n |
 \         \
  \         \

I = item
B = banana
n = small nitro
```

**Comment by Alayan-stk-2** [comment]
@theTomasPat I've updated the list in the first post to include several tracks I had not yet reviewed.

> I've moved the big nitro further to the left so getting both is practically impossible without also getting the banana or going off the track altogether.
> 
> I wonder though, would making it possible to get the item box AND the big nitro make too much of an advantage?

Why not move the small nitro as I suggested ?

The setup I complained about : 
```
|         |
|    N    |
|    B    |
| I     n |
 \         \
  \         \
```

The setup I suggested : 
```
|         |
|    N  n |
|    B    |
| I       |
 \         \
  \         \
```

Having the big nitro as an incentive to take risks with the banana is nice imho. Otherwise, yes it could be removed altogether.

**Comment by theTomasPat** [comment]
Oh! I guess I just misunderstood what you were asking for. It makes a lot more sense now.

Anyway, I changed it to your original request. I'm able to get both the item box and the big nitro in one go right now; not consistently but every few laps I'm able to get them. I'm not sure if that provides too much of an advantage to a player but I guess since the banana is so close, it's risky enough to merit a big nitro.

I've attached another zip with the updated blend file.
[candela_city.blend.zip](https://github.com/supertuxkart/stk-code/files/2872573/candela_city.blend.zip)

And I'll take a look at the updated list :)

**Comment by theTomasPat** [comment]
Here's the blend with changes for Hacienda
[hacienda.blend.zip](https://github.com/supertuxkart/stk-code/files/2872611/hacienda.blend.zip)

**Comment by theTomasPat** [comment]
Here are the changes for Oliver's Math Class
[olivermath.blend.zip](https://github.com/supertuxkart/stk-code/files/2877036/olivermath.blend.zip)

**Comment by auriamg** [comment]
Thanks, I've committed candela and olivermath. Hacienda appears to be unchanged compared to what we already have

**Comment by theTomasPat** [comment]
My mistake! I must have accidentally packaged the wrong blend file. I think I lost the one with my changes so I'll update this comment once I can recreate it. Sorry about that!

**Comment by Alayan-stk-2** [comment]
@theTomasPat For The Old Mine, I was thinking of (1) the big nitro you mention (2) the small nitro to the right of a banana soon after the wooden bridge section.

**Comment by theTomasPat** [comment]
[mines.blend.zip](https://github.com/supertuxkart/stk-code/files/2886753/mines.blend.zip)
[greenvalley.blend.zip](https://github.com/supertuxkart/stk-code/files/2886820/greenvalley.blend.zip)
[spaceship.blend.zip](https://github.com/supertuxkart/stk-code/files/2886862/spaceship.blend.zip)
[snowmountain.blend.zip](https://github.com/supertuxkart/stk-code/files/2887194/snowmountain.blend.zip)

I believe that's the last of the list, except for Black Forest.

**Comment by auriamg** [comment]
All improvements have been committed to svn, thanks

**Comment by Alayan-stk-2** [comment]
I tested the updated assets, the changes are good.

@theTomasPat Now that Black Forest is in svn, I have tested it and updated the first post of the issue to list the improvements to do.

**Comment by hiker** [comment]
@theTomasPat Thanks a lot for your work here!

I'll move this ticket to the next milestone, so that we have a clear list of outstanding issues for the RC/release. It appears that this is mostly finished anyway, and from what I have heard we might have to revisit Black Forest due to performance issues in networking anyway. But please commit any track improvement as you get them done, we will include as much as possible in the next release.

**Comment by Benau** [comment]
With https://github.com/Benau/stk-code/commit/c8faf5ae43305fab17dab4d21e19f0431c0e90f9 using https://github.com/Benau/stk-code/tree/network you can even play black forest in high ping with 10 players!

**Comment by Alayan-stk-2** [comment]
> I'll move this ticket to the next milestone, so that we have a clear list of outstanding issues for the RC/release.

I moved it to 0.10 because all the requested changes for already core tracks have been done and tested. As 95% of the change will be into 0.10 (or 1.0, next release in any case), I think it makes more sense to assign it to this.

Black Forest's improvement is not a blocker for next release, but I'm waiting for it to close the ticket as solved to make sure we don't forget it.

**Comment by deveee** [comment]
@Benau I cherry-picked this commit and made a quick test. Even in offline mode in debug build black forest is now ~50% faster for me (~40 fps, it was 29 before). I will try release build later. And I suppose that it should help for heavy tracks on android too.

**Comment by deveee** [comment]
On my tablet the difference is much smaller, but still an improvement:

with patch:
cocoa 25
candela 33
gran paradiso 30
candela arena 29
black forest 22

without:
cocoa 23
candela 32
gran paradiso 30
candela arena 27
black forest 21

Anyway as I understend it's just a side-effect of the fix for networking.

**Comment by theTomasPat** [comment]
Here's the changes to Black Forest to satisfy the checklist.

[forest.blend.zip](https://github.com/supertuxkart/stk-code/files/2898690/forest.blend.zip)
