### ISSUE TITLE
outdated INSTALL.md

### ISSUE THREAD

**Issue by lupoDharkael** [supertuxkart/stk-code#3730]
The info in [INSTALL.md](https://github.com/supertuxkart/stk-code/blob/master/INSTALL.md) is outdated.
After trying to build from source I found I needed the following new dependencies in Fedora:
`enet-devel glew-devel wiiuse-devel`

And set `-DBUILD_RECORDER=0` in the cmake command.

**Comment by hiker** [comment]
Can you post your log files? At least enet-devel should not be necessary (there should be a fallback to the one included in stk), and same for wiiuse-devel.
glew-dev is mentioned for Ubuntu, but not Fedora. Could someone with access to those systems check the correct name and update the install?

**Comment by lupoDharkael** [comment]
I tried again after removing the packages from my system. It seems to generate the CMake configuration just fine.
The following messages made me think I needed to install the packages:
```
-- Checking for module 'libenet>=1.3.4'
--   Package 'libenet', required by 'virtual:world', not found
-- Checking for module 'glew>=2.1'
--   Package 'glew', required by 'virtual:world', not found
```

Maybe it was not adding `-DBUILD_RECORDER=0` because it failed.

**Comment by deveee** [comment]
If you don't have libenet and glew installed, it will automatically fallback to our included libraries. It's mostly for linux distributions and doesn't really matter for end-user.

**Comment by qwertychouskie** [comment]
Also, the requirement for `-DBUILD_RECORDER=0` was just fixed in git.

**Comment by lupoDharkael** [comment]
closing this then.
