### ISSUE TITLE
Accept donations via Liberapay

### ISSUE THREAD

**Issue by asddsaz** [supertuxkart/stk-code#3731]
**Feature**: Accept donations via [Liberapay](https://www.wikipedia.org/wiki/Liberapay), a Free and Open Source recurring donation platform.

**Comment by qwertychouskie** [comment]
Between https://liberapay.com/on/github/supertuxkart/ and https://liberapay.com/on/twitter/supertuxkart/ €0.49 has been pledged, not huge but shows people are interested in using the platform.  @hiker Thoughts?

**Comment by Alayan-stk-2** [comment]
Not an issue in STK, please use the forum for that sort of suggestion.
