### ISSUE TITLE
Make "run_server.sh" more robust

### ISSUE THREAD

**Issue by Schwefelsaeure** [supertuxkart/stk-code#3733]
## Description

The script `stk-code/tools/run_server.sh` reads out the install location of SuperTuxKart by using `export DIRNAME="$(readlink -e "$(dirname "$0")")"`. This is error-prone when SuperTuxKart is installed for example under `/opt/supertuxkart` and placing only a (symbolic) link to its executable under `/usr/bin/` as `/usr/bin/supertuxkart`.

In this case, `"$(dirname "$0")"` extracts to `/usr/bin/` (and no changes are made by $(readlink ...). This leads to a wrong value for `DIRNAME` (`/usr/bin/` instead of `/opt/supertuxkart`).

Therefore, I recommend to use following snippet to read out SuperTuxKart's insall location:

```
export INSTALL_DIR=$(dirname $(readlink -e "$0"))
```

Firstly, `$(readlink -e "$0")` extracts the correct install location of SuperTuxKart. Then, `$(dirname ...)` strips down to the directory path.

## Steps to reproduce

`run_game.sh` which is shipped with latest beta release uses the same approach as `run_server.sh` (as described above).

1. Download SuperTuxKart for Linux: https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.10-beta1/supertuxkart-0.10-beta1-linux.tar.xz/download
2. `cd /opt`
3. `sudo tar xzf ~/Downloads/supertuxkart-0.10-beta1-linux.tar.xz` (requires `xz-utils` to be installed)
4. `ln -s /opt/supertuxkart-0.10-beta1-linux/run_game.sh /usr/bin/supertuxkart`
5. `supertuxkart`

Result: Game cannot be started because some libraries are not found (they are searched under `/usr/bin/lib-64` instead of `/opt/supertuxkart-0.10-beta1-linux/lib-64`.

**Comment by Schwefelsaeure** [comment]
Thanks, an keep up the good work! :)

**Comment by deveee** [comment]
Actually readlink dirname has a sense. It was there, because readlink returns absolute path and I didn't care about symlinks before.

Now in run_server.sh script there is:
```
export DIRNAME="$(dirname "$(readlink -f "$0")")"
```
And I changed it in run_game.sh locally too.
