### ISSUE TITLE
Story Mode: Audio in Grand Prix celebration cutscene continues after skipping

### ISSUE THREAD

**Issue by bluecat999** [supertuxkart/stk-code#3734]
## Description
After winning a Grand Prix in Story Mode, the game shows a celebration cutscene with podiums. This cutscene contains audio with background music and applause.
If this scene is skipped, the video fades to black but the audio continues playing. It would be expected that the audio fades out as well. This is noticeable when the audio for the treasure chest cutscene plays, as it contains two background music tracks playing at the same time.

## Steps to reproduce
1) Win any Grand Prix for the first time in Story Mode
2) When the first cutscene begins, skip immediately

## Configuration
STK release version: 0.9.3

Downloaded from https://supertuxkart.net/Download (direct link)

System: 
Windows 7 x64

Graphics card: 
GTX 1050

CPU: 
Intel Skylake

Gamepads/keyboards models if related to the issue: 
None

## Additional information
Cannot debug log at this point in time, let me know if not reproducible.

**Comment by Benau** [comment]
I made some commits to fix music handling, you can see if still see this with latest git m$ windoze .zip in preview release page ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Alayan-stk-2** [comment]
I tested. The audio continues playing before the treasure cutscene is loaded but I can't reproduce the two musics playing at the same time part. It seems just fine.
