### ISSUE TITLE
Cannot pause singleplayer game before race starts in 0.10 beta

### ISSUE THREAD

**Issue by Schyrsivochter** [supertuxkart/stk-code#3740]
## Description

In 0.9.3, a singleplayer game can be paused during the countdown to the start of the race. In the 0.10 beta, this is not possible any more. The first time a game can be paused is around one half to one second after the race has started.

## Steps to reproduce

* Play the 0.10 beta release.
* Start a singleplayer game.
* Press the keybinding for ‘pause game’ while Thunderbird is counting down. Expected behaviour: the game pauses, as it would in 0.9.3. Actual behaviour: nothing happens.

## Configuration

STK release version: 0.10-beta1

STK source: official tarball

System: Ubuntu 18.10 x86_64

Graphics card: Intel HD Graphics 620

CPU: Intel Core i5-7200U

## Additional information

stdout.log: [stdout.log](https://github.com/supertuxkart/stk-code/files/2829277/stdout.log)

**Comment by hiker** [comment]
This was apparently introduced in 969b56844b18d5fda17ba27e86ed4854f1b1e218 (well, and some others :) ). @Benau , why did you disable the pause menu during the thunderbird phase? Esp. in later commits this seems not to be the case in networking, i.e. in an online race you can get the pause menu during the thunderbird phase. Easy solution would be to just remove the if statement in modes/world.cpp:
```
if (NetworkConfig::get()->isNetworking() || getPhase() >= MUSIC_PHASE)
    new RacePausedDialog(0.8f, 0.6f);
```
completely.

**Comment by Benau** [comment]
because for 3172 to disable speedrunner hack, now further commit will "fix" the timer itself so the if is indeed unneeded, alayan can u check if remove if (NetworkConfig::get()->isNetworking() || getPhase() >= MUSIC_PHASE) is good for u in local player?

**Comment by Alayan-stk-2** [comment]
@Benau Pausing and unpausing still trigger a faster start countdown in latest master if I remove the condition.
