### ISSUE TITLE
On-screen text is hard to read

### ISSUE THREAD

**Issue by jebeld17** [supertuxkart/stk-code#3741]
## Description:
On-screen, in-game text is hard to read as the font is very small in comparison to the screen size and background images.

## Steps to reproduce:
1. Download and install Super TuxKart on platform of choice and run.
2. Set in-game screen resolution to recommended resolution for the monitor/panel. Apply changes.
3. Restart game and start a new random single-player race.

## Configuration:
STK release version: 0.9.3
STK Source (PPA, distribution package, official binary, etc.): https://play.google.com/store/apps/details?id=org.supertuxkart.stk
System: HTC U11 128GB(USA Unlocked)
Graphics card: Adreno 540
CPU: Qualcomm Snapdragon 835
Gamepads/keyboards models if related to the issue: On-screen

**Comment by qwertychouskie** [comment]
Can you try https://play.google.com/store/apps/details?id=org.supertuxkart.stk_beta and see if it is better?

**Comment by jebeld17** [comment]
Hey, and thank you for getting back so quickly.
Unfortunately, the text doesn't look a whole lot better, but the gradient added in this release does help in some situations (like when the background is blue).

What I think can help is to make the text much - much larger and to use a fun font that matches the theme of the background. This will increase the readability by drawing attention to the text in both context and physical space.

**Comment by Alayan-stk-2** [comment]
Text size is mostly acceptable in my opinion on a computer screen but I can imagine things being different on a small smartphone touch screen, especially for some texts which are already not big on a computer screen like the best lap times. I know some UI elements and texts are upscaled in Android already, but maybe the race GUI can take some additional improvements.

**Comment by jebeld17** [comment]
At the very least, I would like text size to be partially dependent on the
DPI/PPI density of the screen.
As Alayan said, it may not be worth while having giant text on a
27"/68.58cm 1080P screen, but it may on a 5.5"/13.9cm UHD display.

**Comment by Benau** [comment]
Can you try https://play.google.com/store/apps/details?id=org.supertuxkart.stk_beta again (now the font size can be changed and you can use modern theme for bold font)

**Comment by Alayan-stk-2** [comment]
Closing this, with the adjustable font size introduced in 1.1 this shouldn't be much of an issue anymore.
