### ISSUE TITLE
bad bars

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3752]
![_ _20190214214345](https://user-images.githubusercontent.com/35170687/52790477-9fc70900-30a1-11e9-9952-75be4f903871.png)
![_ _20190214214018](https://user-images.githubusercontent.com/35170687/52790479-a0f83600-30a1-11e9-971a-85066fd9cf52.png)
![_ _20190214214011](https://user-images.githubusercontent.com/35170687/52790482-a2c1f980-30a1-11e9-9d69-a0da3dce2138.png)

**Comment by Alayan-stk-2** [comment]
This is not a scroll bar, these are the bars showing the relative kart characteristics. They don't have to go all the way to the left, and especially not to the right.

Though it could look better with the peach skin (it's much nicer with the coal skin)

**Comment by qwertychouskie** [comment]
On my laptop it displays normally (1366x768), same with my mac at lower resolutions, but my mac at 1920x1200 displays wrongly.  It seems not just the bars are messed up here, but the border too.

For comparison, how it shows on my laptop:
![image](https://user-images.githubusercontent.com/13989090/52812490-6fa14b00-304c-11e9-9fec-ea9f612eff68.png)

The faulty line:
```
<element type="progress" state="neutral" image="common/scrollbar_bg.png"
      left_border="31" right_border="31" top_border="15" bottom_border="15"
      preserve_h_aspect_ratios="true" />
```
If `preserve_h_aspect_ratios` is set to false it fixes this issue.

Also the progress bars are not consistent between the skins.  IMO they should all look like the (fixed) Peach version.

**Comment by dumaosen** [comment]
![_ _20190215173704](https://user-images.githubusercontent.com/35170687/52847876-5da4d280-3148-11e9-8000-b470bdc895d7.png)
I meant those bars has too large space on the left ,and the frame in the left and in the right are too thick.
And the issue just appears in high resolution (1080p or higher).

**Comment by qwertychouskie** [comment]
Yes.  I'll open a PR to fix all the progress bars soon (and make them consistent between themes).

**Comment by Alayan-stk-2** [comment]
In my tests at 720p, I found the peach/ruby bars got too close from the vertical border and the forest/ocean/coal bars having more margin were nicer.

The coal bars also have the advantage of black on grey looking natural. Color on grey background doesn't look very good, it may be worth experimenting.

**Comment by dumaosen** [comment]
What's more, QwertyChouskie's new skin doesn't have the same issue... Maybe that's because you left too much left_border and right_border.
