### ISSUE TITLE
Mailserver does not use FQDN in HELO

### ISSUE THREAD

**Issue by Cyborgscode** [supertuxkart/stk-code#3761]
While registering an account for the new netplay version, we stumpled over an mailserver issue:

2019-02-20 19:55:28 H=online.supertuxkart.net (online) [192.241.165.79] X=TLSv1.3:TLS_AES_256_GCM_SHA384:256 CV=no rejected MAIL <no-reply@addons.supertuxkart.net>: invalid NON-FQDN HELO (online), please talk to your mailserveradmin about this

Your mailserver has a name "online.supertuxkart.net" use it. SMTP connections that have no FQDN in it's HELO  ( at least one . in his name ) are not recgonized as valid smtpserver around the world.

You ask why? Because usually this is a windows only problem, and spammer connecting from a hacked windows pc are identified with this rule. 

So please make the world a better place and change your mx helo identification to a FQDN as requested in this RFC:  https://tools.ietf.org/html/rfc2505

**Comment by leyyin** [comment]
Hi,

The issues with the email should be resolved now.
https://www.mail-tester.com/test-81nr5

Thanks.
