### ISSUE TITLE
In help screens, Weapons should have gift box icon instead of battle icon

### ISSUE THREAD

**Issue by BlueCatYellowCat** [supertuxkart/stk-code#3765]
In the general help screens, the Banana tab is represented by a banana as that is how it appears in the game. However the Weapons tab is represented with a battle icon. This is understandable, but it would be more obvious if represented by the gift box icon shown in the game.

This also demonstrates the naming inconsistency between those two tabs. Maybe "Power-ups" and "Hazards" would be an appropriate pair, or "Gifts" and "Bananas".

**Comment by Alayan-stk-2** [comment]
The tab has already been renamed a few months ago in the development version.

However, the icon suggestion is sensible.
