### ISSUE TITLE
Suggestion: Unlimited Nitro in Story Mode Map

### ISSUE THREAD

**Issue by BlueCatYellowCat** [supertuxkart/stk-code#3766]
In story mode, the player drives around an open map to pick challenges to play. This map is non-competitive and I think it is fair to say driving around this map is not the focus of the game. To drive from one end to the other is a little bit of a chore (and moreso if the game gets larger). It would be convenient if the player is allowed large or unlimited amount of Nitro to help speed this map up, if the player chooses so.

(As a side note, does anyone else think the mountain area needs more snow further down the mountains  so that it is visible to the driver?)

**Comment by qwertychouskie** [comment]
The Orerworld does have unlimited Nitro.  Also you can click the icons in the minimap to teleport.

**Comment by BlueCatYellowCat** [comment]
My mistake, you are correct. It was a temporary input issue of my own that made me think nitro was disabled. Closing issue.
