### ISSUE TITLE
ZLIB_1.2.9' not found  on (K)ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by batje** [supertuxkart/stk-code#3767]
## Description

I downloaded the latest beta 0.10 and I would like to login online. I do not remember the password of my account, so i press the ' Reset Password' button. That generates the following error in the console that I started Tux from:

> [info   ] HTTPRequest: Sending username=myusername&password=************&save-session=true to https://addons.supertuxkart.net/api/v2/user/connect/
> kde-open5: /home/me/bin/supertuxkart-0.10-beta1-linux/lib-64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
> [error  ] OpenURL: Command returned non-zero exit status
> 

## Steps to reproduce

Select a user
check the online tickbox
press 'Reset password' 

## Configuration

STK release version: 
0.10 beta1

STK Source (PPA, distribution package, official binary, etc.): 
sourceforge
System: 
(K)ubuntu 18.04
Graphics card: 
radeon
CPU: 
a not so fast one
Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log: (Can not find it, but this is from the console)
```

> [info   ] HTTPRequest: Sending username=myusername&password=************&save-session=true to https://addons.supertuxkart.net/api/v2/user/connect/
> kde-open5: /home/me/bin/supertuxkart-0.10-beta1-linux/lib-64/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
> [error  ] OpenURL: Command returned non-zero exit status
> 
```

input.xml:
```xml

```

Error message:
```
none is shown
```

**Comment by qwertychouskie** [comment]
What happens if you run `xdg-open https://online.supertuxkart.net/password-reset.php` in a terminal?  Also what happens when you run `kde-open5 https://online.supertuxkart.net/password-reset.php`?  Paste the output of both commands here.

**Comment by deveee** [comment]
It's because we use LD_LIBRARY_PATH to make sure that all libraries are available and this directory contains older zlib. So that web browser tries to use it instead of system zlib. And it's not just zlib, but other libraries too.

**Comment by qwertychouskie** [comment]
Is there an easy way to use a "default" library path when `exec`ing a command, without affecting STK spawning processes for e.g. server creation?

**Comment by hiker** [comment]
It should be possible to add a library path using -rpath when linking. I admit I am not sure if rpath would be inherited to the child process (LD_LIBRARY_PATH obvioulsy does), but I'd guess it doesn't - but certainly worth a try.

**Comment by batje** [comment]
Both xdg-open and kde-open5 commands work perfectly.

I noticed the error is different the first time I hit the password reset button:

Openurl: command returned non-zero exit status.

**Comment by deveee** [comment]
Atm. I don't know good solution. 

You can clear LD_LIBRARY_PATH and restore it after executing the command, so that stk server process can still use it. But if user already has his own paths in LD_LIBRARY_PATH, then it won't work for him.

Or I can set LD_LIBRARY_PATH_ORIG in run_game.sh if it will help you.

And -rpath will work only for direct STK dependencies and in this case zlib is a dependency of libpng, so we would need recompile all dependencies.

**Comment by deveee** [comment]
As I see eg. in Steam they define SYSTEM_LD_LIBRARY_PATH variable, that is used for xdg-open, so I will define the same in run_game.sh. @qwertychouskie Do you want to fix it yourself in STK?

**Comment by deveee** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/88c2ce7ee5ae0eedadb6895e540576b1027ce03e

**Comment by qwertychouskie** [comment]
Thanks!
