### ISSUE TITLE
Screenresolution change does not work on Surface Pro4 ( Linux )

### ISSUE THREAD

**Issue by Cyborgscode** [supertuxkart/stk-code#3768]
## Description

STK detects the screenresolution correctly as 3:2 28xxX18xx
but when i try to change it to 1920x1080  it does not do the change. Instead it tries to change it, the message with "do you accept this resolution ... bla bla 9 seconds counter" apears, but it never gets changed to 1920x1080. It stays at the 3k resolution. 

A SCALE Button would be helpfull, because the Intel HD gfxset can't handle massive 3d textures on 3k.

Caco Temple  i.e. drops to ->3<- FPS at a special place : 
the rotating ring, where you can speed jump throu and get fuel , right before the loop ends 

It's not the cpu whos responsible, as 4 cores with turbo boost are enabled. it the soc who has a performance problem. Interesstingly, Runes of Magic runs smooth.

## Configuration

STK release version: 

supertuxkart-0.10-beta1-linux

System: 

Fedora Linux 29 installed on Surface Pro4 i7 with IPS patched kernel. 

Graphics card:  Intel HD 54xx

**Comment by Alayan-stk-2** [comment]
When the "do you accept this resolution" message appears, I assume that you do click "yes" ?

If you let the counter run out it reverts to the original resolution.

**Comment by Cyborgscode** [comment]
i accept, but it does not switch down to fullhd.

**Comment by Cyborgscode** [comment]
one correction: it does not find 1920x1080, it finds 1280x720 .

I just started it up for you and the precise flow is:

a) selecting 16:9 1280x720
b) a short close of the screen
c) reopening it in the default 2736x1824 3:2 resolution
c1) restarting stk ( loading char icons in a chain, switch to prefs screen )
d) showing the countdown 
e) selecting : " keep this resolution "
BUT as of step c ,  1280x720 is no longer selected, 3:2 2736x1824 is again.

defacto a resolution change is not possible :D

**Comment by deveee** [comment]
I wonder if your monitor has 1280x720 resolution? You can check it in terminal with ```xrandr``` command. I'm asking because 1280x720 and 1024x768 resolutions are always added (may be useful eg. in windowed mode). And if you don't have this mode in system, then indeed it will use default resolution.

Anyway that's true that options screen should be more smart. There was already a bug report somewhere...

**Comment by Cyborgscode** [comment]
no. xrandr shows only the 3k resolution.

**Comment by deveee** [comment]
So 1280x720 is a lie :P Maybe it's because of your system configuration. Typically it should show more resolutions. 

You can at least use scale_rtts_factor=0.5 in ~/.config/supertuxkart/0.10-beta/config.xml so it will be scaled down and you will get a bit more fps. But it works only when advanced lighting is enabled.

**Comment by Alayan-stk-2** [comment]
Oh you tried to change the resolution while remaining in full screen mode ? It makes more sense...

1280x720 and 1024x768 are indeed added mostly for windowed mode, we should flag them to not allow them in fullscreen mode if the monitor doesn't support it... But what UI flow to use ? If someone is in windowed 1280x720 and tries to go fullscreen, what to do ? If someone is in fullscreen, should the option be hidden altogether ?

**Comment by deveee** [comment]
Make these resolutions gray/inactive if not available and if fullscreen checkbox is enabled? And update on checkbox click.

**Comment by Cyborgscode** [comment]
hmm.. gnome offers scaling as an option on a 3k display and is able to set fullhd resolution native. I wonder why gnome can, and stk can't set fullhd on the device.

**Comment by deveee** [comment]
STK uses libxrandr, so you should get the same resolutions as with ```xrandr``` command. Maybe you run gnome wayland session and it emulates xserver. If you don't care, you can choose gnome xorg session in gdm. Not sure if it's installed by default on fedora.

**Comment by Cyborgscode** [comment]
I could use x11 , but than the touch support in gnome, firefox aso won't work. Wayland is the only option if a tablet needs to work as a tablet right now ;)

I checked it:  It does not make any difference for this problem, if it runs under Wayland or X11.


BTW: that the next dream: a touch ui for STK . it would need to work under linux and windows, as both oses support i.e. the surface pro now.

**Comment by deveee** [comment]
Touch device is already working on wayland :) But you need to compile current STK version yourself, because the package on sourceforge doesn't have wayland support to avoid too many dependencies.

**Comment by Cyborgscode** [comment]
ok, understood.  But it won't effect this bug, i'm afraid ;)

Maybe i will, the i7 on that surface needs something to do anyway.

**Comment by deveee** [comment]
Fixed in https://github.com/supertuxkart/stk-code/commit/ebde41956603b2554fa52ae47c0982840f820fcb

**Comment by Alayan-stk-2** [comment]
I tested the fix, there is an issue. Here is what happens : 
1) I check full screen.
2) "1280x720" is correctly greyed out. It's the 4th resolution from the left.
3) If I use the left or right arrows, it switches the position of the resolutions but the 4th resolution from the left remains disabled.

This means that 1) a wrong resolution can appear disabled (and it's not selectable through direct click but if you use arrows once more it become selectable again) ; 2) it is still possible to select an unsupported resolution.

**Comment by deveee** [comment]
Indeed it must be updated on selection change too

**Comment by deveee** [comment]
Now I update it on scroll event too. Can you check if everything is ok?

**Comment by Alayan-stk-2** [comment]
I tested by scrolling with the buttons or the keyboard and the disable worked fine this time. :slightly_smiling_face:

**Comment by Cyborgscode** [comment]
do i need to compile it myself to test it or do you have a recompiled version ready?
