### ISSUE TITLE
Minor issues in Black Forest

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3771]
A few very minor issues
- [x] Wrong zipper arrow direction in reverse. Apply to the reverse-only jump pad and to the texture in the bottom of the road leading to the village on the hill. ~~**Fixed for the jump pad in SVN but NOT for the zipper in the bottom of the road from the hill**~~ **EDIT: now fixed there too**
![bf_issue1](https://user-images.githubusercontent.com/25536748/53312039-b34d4d80-38b3-11e9-99a8-53f594e35634.png)
- [x] The houses of the village are not solid for physics, so you can go through their walls and see grass...
- [ ] Texture transitions are notoriously difficult, but ideally when the road split into two the "border" part of the texture should not go in the middle of the side road.
![bf_issue2](https://user-images.githubusercontent.com/25536748/53312038-b34d4d80-38b3-11e9-82ce-553d2565cc79.png)
- [x] The names on the placards are not there. I think this is a texturing issue. See the screenshot above and look at the signs.
- [x] See the picture below.
![bf_issue3](https://user-images.githubusercontent.com/25536748/53312037-b34d4d80-38b3-11e9-86a9-5dbbfda37ab7.png)
- [x] At the end of the monastery path on the right, the tree with the light-colored trunk has a buggy hitbox which extends well beyond the visible trunk.
- [x] There is a tree floating in the air near the monastery path (drive in reverse to spot it, just right of the "stairs")

**Comment by theTomasPat** [comment]
So unfortunately I don't have time to work on the point about blending the paths but I've included fixes for the zippers, the water, and the houses. Maybe once work slows down a bit I'll be able to revisit the path blending but that might not be for a while. If someone else is able to address it, please have at it!

I wasn't able to recreate the texture issues on the signposts though so I didn't touch that.

I also modified stklib_autumnTree_b to narrow the physics object a little bit. This was done to help fix a collision problem on the tree at the corner of the end of the "shortcut", right before the finish line.

The zip file contains the updated house and tree .blend files, as well as a modified materials.xml file for the zippers and the modified forest.blend.

[BlackForest_issue3771_20190306.zip](https://github.com/supertuxkart/stk-code/files/2939188/BlackForest_issue3771_20190306.zip)

**Comment by auriamg** [comment]
I tried the black forest blend, but maybe checklines need to be reviewed, my lap was not counted :/

**Comment by theTomasPat** [comment]
Interesting. I haven't had any problems with checklines. I'll double check and update in a few minutes

**Comment by Alayan-stk-2** [comment]
Initial post updated with two additional issues

**Comment by Benau** [comment]
the tree and the house is svn commited

**Comment by Benau** [comment]
the trees are fixed together with the latest .blend by tomas

**Comment by Benau** [comment]
the sign.png has reversed mirror enabled, i disable it for now (because it's also used with the words), can u see if any sign is not correct?

**Comment by AndetSTK** [comment]
Also, it seems that a lot of the past changes of Black Forest may have interfered with the balancing of routes. From my tests, taking the left path is up to 2 seconds faster than taking the right path. And then if you follow the train tracks, the left path saves an addition 2 seconds. So you could lose a total of 4 seconds just by taking the wrong paths.

**Comment by Alayan-stk-2** [comment]
Closing as fixed, texture transitions won't be done in the foreseeable future. I'm opening a different issue for the nitro cans.
