### ISSUE TITLE
Add a complaint/ban system in Online Races

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#3772]
## Description
There should be a way to report nasty people and a ban system...
Alayan will understand from our latest session.

There is certainly many ways to implement this, let's discuss.

## Steps to reproduce
- Encounter some annoying people
- Read their nonsense or even vulgar messages
- We could also encounter people going wrong way in purpose to annoy others

**Comment by Benau** [comment]
add a report button with a text field in the player dialog when u press player name in lobby, and then server owner will be able to notice, and the he can take action if want

(not auto ban will happen)

**Comment by FinixFighter** [comment]
Maybe there could be a vote system. If someone encounters an annoying person, you can kick him, then all the players will be able to choose for kick him or not. This could also be managed with shortkeys.

**Comment by Alayan-stk-2** [comment]
No, mob rule is a bad idea.

**Comment by Benau** [comment]
![1](https://user-images.githubusercontent.com/3252341/57358419-f414ed00-71a7-11e9-802c-95747ac71ac1.jpg)
![2](https://user-images.githubusercontent.com/3252341/57358420-f5461a00-71a7-11e9-8c09-acc848a9d1fa.jpg)
And then it will be shown in server owner database for table "report", and the server owner can take action himself base on feedback from players

**Comment by Benau** [comment]
you can try this feature with git stk in hk servers now
