### ISSUE TITLE
Desync of position between client and server

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3773]
Ideally, a kart following approximately the track's path should always have his lap counted.

However, in a few track this is not always the case.

And I encountered this weird bug : my client thought that I had correctly validated a checkline, while the server thought I had missed it. For the rest of the race, my client told me I was first (which I should have been) while I got items which a player in 1st position should never get like a basket ball... The item prediction was wrong obviously because my position was wrong. And at the end, when the game told me I had validated my 4th lap and finished, there was some weirdness (my client wanted to hand over to the endgame controller) before I had to do yet another lap, confirming that my 1st lap never had been validated.

Fouks has a video of it from his viewpoint, he will likely publish it.

I used the beta release and played on Arthur server so no assets issue is involved.

**Comment by qwertychouskie** [comment]
Lap number and validated checklines should probably be part of the state.

**Comment by Fouks0** [comment]
Video made: https://www.youtube.com/watch?v=gDwegb_aQEk

**Comment by Alayan-stk-2** [comment]
So your client also thought I had correctly validated the first lap... This is really weird.

**Comment by Benau** [comment]
latest master already has lap / checkline validations, assume someone uses it in final release, you can see if it's happening again

**Comment by Benau** [comment]
poland / usa / hk server should have this fixed!

**Comment by Alayan-stk-2** [comment]
It hasn't happened again yet, but it was a rare issue in the first place. With checkline and lap validations now in the state, I'm closing this as fixed, and hopefully I won't have to reopen it in the future.
