### ISSUE TITLE
CMAKE fails - Fedora 29

### ISSUE THREAD

**Issue by Cyborgscode** [supertuxkart/stk-code#3776]
## Description

Following this: 

https://github.com/supertuxkart/stk-code/blob/master/INSTALL.md 

to compile stk, does end in a CMAKE Failure :

$ username@surface cmake_build]$ cmake ..
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/CMakeOutput.log".
See also "/home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/CMakeError.log".

CMakeFiles/CMakeError.log
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags:  

The output was:
No such file or directory

############################## BUT , the test shows, that it found cc in the right place :
$ cat CMakeFiles/CMakeOutput.log 
....

Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_7e53b/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_7e53b.dir/build.make CMakeFiles/cmTC_7e53b.dir/build
gmake[1]: Verzeichnis „/home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/CMakeTmp“ wird betreten
Building C object CMakeFiles/cmTC_7e53b.dir/feature_tests.c.o
/usr/bin/cc   -std=c90 -o CMakeFiles/cmTC_7e53b.dir/feature_tests.c.o   -c /home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/feature_tests.c
Linking C executable cmTC_7e53b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7e53b.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_7e53b.dir/feature_tests.c.o  -o cmTC_7e53b 
gmake[1]: Verzeichnis „/home/username/Programme/src/stk/stk-code/cmake_build/CMakeFiles/CMakeTmp“ wird verlassen

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Steps to reproduce

System:  Fedora 29 x86_64 i7

**Comment by deveee** [comment]
Stupid question but maybe you installed c compiler and not c++?

**Comment by Cyborgscode** [comment]
If the how-to is supplying an entire dnf install cmd, shouldn't it cover that? ;)

**Comment by deveee** [comment]
It should :P You can also install libegl and wayland libraries, so that after compilation you can enable touch device in settings in input devices tab and then play on a touch screen.

**Comment by Cyborgscode** [comment]
that would have been the next question: whats needed to compile it for touch and what are the arguments to mass to cmake to get a touch build. The compile instructions don't cover it.

**Comment by deveee** [comment]
You only need to make sure that cmake doesn't say that wayland support will be disabled because of some missing libraries. You don't need any special flags.

And wayland needs: egl, xkbcommon, wayland-client, wayland-cursor, wayland-egl.

And not sure if you can fix the dependencies for fedora as a fedora user?

**Comment by bkmgit** [comment]
It seems to build on Fedora 30 and is in the Fedora repositories:
https://koji.fedoraproject.org/koji/packageinfo?packageID=3886
The required listed from https://koji.fedoraproject.org/koji/rpminfo?rpmID=17356268 packages are

angelscript-devel
--
bluez-libs-devel
cmake
desktop-file-utils
fontpackages-devel
freealut-devel >= 1.1.0-10
freeglut-devel
freetype-devel
fribidi-devel
gcc-c++
git-core
libXrandr-devel
libcurl-devel
libjpeg-turbo-devel
libpng-devel
libsquish-devel
libtool
libvorbis-devel
mesa-libEGL-devel
mesa-libGLES-devel
openal-soft-devel
openssl-devel
pkgconfig(glew)
pkgconfig(libenet)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
wiiuse-devel

Made a pull request to update installation instructions

**Comment by jpenguin** [comment]
Fedora & opensuse instructions were written by me & I currently use Kubuntu; they may be out-of-date
