### ISSUE TITLE
Make these tux, medals and clocks scale bigger in higher resolution

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3792]
![_ _20190304191015](https://user-images.githubusercontent.com/35170687/53730004-aa5f0c00-3eb1-11e9-86b2-1bfe372c08e4.png)
![_ _20190304191043](https://user-images.githubusercontent.com/35170687/53730005-aa5f0c00-3eb1-11e9-9de7-22e0732b9b49.png)
![_ _20190304191322](https://user-images.githubusercontent.com/35170687/53730011-ac28cf80-3eb1-11e9-9547-49dac010410b.png)

**Comment by Alayan-stk-2** [comment]
Mmmm. isn't this a duplicate of #3682 ? These are just particular examples ?

**Comment by dumaosen** [comment]
Yes but all icons are fixed except these.

**Comment by qwertychouskie** [comment]
@dumaosen Is this fixed or is it still an issue?

**Comment by dumaosen** [comment]
> @dumaosen Is this fixed or is it still an issue?

Still an issue

**Comment by Staszek2312** [comment]
photokrzys
