### ISSUE TITLE
Karts aren't correctly placed after grand prix

### ISSUE THREAD

**Issue by wb9688** [supertuxkart/stk-code#3795]
## Description

The karts aren't correctly placed on the wood:

![Screenshot](https://user-images.githubusercontent.com/46277131/53797820-47b05380-3f37-11e9-9dd0-c43e428380ff.png)

## Steps to reproduce

1. Play a grand prix and win

## Configuration

STK release version: 7ff6f291d2da1d950142c2ec8cdb89a3c41af2fe

STK Source (PPA, distribution package, official binary, etc.): git

System: Intel NUC6i3SYH running Debian Unstable with a 1440p monitor

Graphics card: Intel HD Graphics 520

CPU: Intel Core i3-6100U

**Comment by qwertychouskie** [comment]
Can reproduce, for some reason the karts don't drive forward like they are supposed to.  This is a regression, @Alayan-stk-2 can you label it as such?

**Comment by deveee** [comment]
Fixed in current git
