### ISSUE TITLE
Libsquish causes build failure on ppc64le

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3797]
```
[  6%] Building CXX object lib/libsquish/CMakeFiles/squish.dir/alpha.cpp.o
cd /<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu/lib/libsquish && /usr/bin/powerpc64le-linux-gnu-g++   -DGLEW_NO_GLU -DSQUISH_USE_SSE=2 -DSUPERTUXKART_VERSION=\"git\" -I/<<PKGBUILDDIR>>/lib/bullet/src -I/<<PKGBUILDDIR>>/lib/glew/include -I/<<PKGBUILDDIR>>/lib/graphics_utils -I/<<PKGBUILDDIR>>/lib/libsquish  -g -O3 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -DNDEBUG   -msse2 -o CMakeFiles/squish.dir/alpha.cpp.o -c /<<PKGBUILDDIR>>/lib/libsquish/alpha.cpp
powerpc64le-linux-gnu-g++: error: unrecognized command line option ‘-msse2’
lib/libsquish/CMakeFiles/squish.dir/build.make:65: recipe for target 'lib/libsquish/CMakeFiles/squish.dir/alpha.cpp.o' failed
make[4]: *** [lib/libsquish/CMakeFiles/squish.dir/alpha.cpp.o] Error 1
make[4]: Leaving directory '/<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu'
CMakeFiles/Makefile2:376: recipe for target 'lib/libsquish/CMakeFiles/squish.dir/all' failed
make[3]: *** [lib/libsquish/CMakeFiles/squish.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
```
From https://launchpadlibrarian.net/413831922/buildlog_ubuntu-xenial-ppc64el.supertuxkart_0.10.0-0~201903051805~ubuntu16.04.1_BUILDING.txt.gz

Installing libsquish-dev seems to fix this, but it isn't available on Xenial.

**Comment by deveee** [comment]
```
diff --git a/lib/libsquish/CMakeLists.txt b/lib/libsquish/CMakeLists.txt
index 4c30ca1e8..fc627081c 100644
--- a/lib/libsquish/CMakeLists.txt
+++ b/lib/libsquish/CMakeLists.txt
@@ -14,7 +14,9 @@ CMAKE_MINIMUM_REQUIRED(VERSION 2.8.3)
 OPTION(BUILD_SQUISH_WITH_OPENMP "Build with OpenMP." OFF)
 
 if((${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm") OR 
-   (${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64"))
+   (${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64") OR
+   (${CMAKE_SYSTEM_PROCESSOR} MATCHES "powerpc64") OR
+   (${CMAKE_SYSTEM_PROCESSOR} MATCHES "ppc64"))
    OPTION(BUILD_SQUISH_WITH_SSE2 "Build with SSE2." OFF)
 else()
    OPTION(BUILD_SQUISH_WITH_SSE2 "Build with SSE2." ON)
```
?

**Comment by qwertychouskie** [comment]
Wouldn't it be more technically correct to check for x86 or x86_64 or AMD64 and enable SSE2 if it is true, else disable it?

Ref https://cmake.org/cmake/help/v3.14/variable/CMAKE_SYSTEM_PROCESSOR.html and https://cmake.org/cmake/help/v3.14/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html and https://superuser.com/questions/305901/possible-values-of-processor-architecture

**Comment by deveee** [comment]
Technically it would be better. But are you 100% sure that "x86 or i386 or i686 or x86_64 or AMD64" is complete list and it will never have any other value, eg. IA64? Most people use x86, so better not break it and you can experiment after release. And anyway I just wanted you to test that patch, because I don't have access to powerpc computer, so it's just a guess.

**Comment by deveee** [comment]
And btw. if you can test, then maybe for powerpc you can enable Altivec.

**Comment by qwertychouskie** [comment]
Still present in 0.10-rc1.  Just use whatever fix you think is best, its more important that this is actually fixed for 0.10.

**Comment by deveee** [comment]
Probably fixed in https://github.com/supertuxkart/stk-code/commit/157dc89cd2a67478f8939bdd8a6cba496f8a54cc but I have no real possibility to test and it seems that you didn't want to try yourself. Maybe I will try it with debootstrap + qemu later.

**Comment by qwertychouskie** [comment]
I just double-checked the launchpad builds and it seemed to work just fine.  Thanks for the fix!
