### ISSUE TITLE
Add emoji support/font to stk

### ISSUE THREAD

**Issue by UnMe0w** [supertuxkart/stk-code#3799]
It would be nice to send emojis on server lobbys.

**Comment by Benau** [comment]
If deve doesnt mind ~4mb font for it in apk, it will have unicode country flag too!

The code in server side(utf32 support) is done my network branch, so if this release includes it it would be good (so i can just do the client side next-next release)

**Comment by MiroslavRD** [comment]
The emojis should be EmojiOne emojis (Tux edit)

**Comment by UnMe0w** [comment]
Yes

**Comment by Benau** [comment]
![SuperTuxKart_2019-06-10-20-20-07](https://user-images.githubusercontent.com/3252341/59195023-73d61300-8bbd-11e9-8179-7eae785ee9a7.jpg)
Not sure deve wanna EmojiKeyboard public ScreenKeyboard himself lol

**Comment by Benau** [comment]
![1](https://user-images.githubusercontent.com/3252341/59788881-50b70c00-92ff-11e9-96df-ae7a3540e572.jpg)
Not sure deve wanna hide the button if native android keyboard is on lol
