### ISSUE TITLE
I'm making a PS2 homebrew of this game

### ISSUE THREAD

**Issue by MiroslavRD** [supertuxkart/stk-code#3801]
Hey guys, I'm making a PlayStation 2 homebrew of SuperTuxKart.
I will test it with PCSX2, and if you have a real PS2 then you're invited as beta tester.
The homebrew will have:

- Memory card icon overlay (it's shown on top left) (green=read, red=write) (you cannot disable this due to corruption of save data upon ejecting memory card) (DVD-R icon overlay is also shown, but the disc should be read-only)
- DUALSHOCK(R) 2 vibration and analog stick support
- Support for all controllers (including Gran Turismo Force driving wheels)
- Ability to use disc swap or USB for installing addons onto memory card
- Network Adapter compatibility
- And more...

**Comment by Benau** [comment]
make suggestion in forum

**Comment by MiroslavRD** [comment]
I'll develop myself
