### ISSUE TITLE
Regressions/issues in glossmaps/pbrdata

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3807]
Will update as I think of/come across more issues.

- [x] !!! The accuracy fix to PBR maps makes many karts have parts that are much more shiny than they are supposed to be, such as Tux's body and wheels, Gavroche's body, Hexley's body (less so, but still off) etc.

- [x] Tux's tailpipes and engine are not defined as metallic.
- [x] Tux's `wheel_gloss.png` is different in the media repo and stk-assets.  The one in the media repo has metalness defined for the "TUX" plate on the back of the kart, which is probably more correct.

- [ ] Xue's kart as a whole has completely non-reflective paint, this doesn't really fit the other karts.  Honestly I liked the old look better, maybe just revert? (sorry samuncle)

- [x] Kiki has a non-glossy kart.

- [x] `trak2_holes1a_gloss.png` in STK Enterprise should be removed, it makes the surface glossy when it doesn't make sense.

**Comment by qwertychouskie** [comment]
- [ ] !!! The accuracy fix to PBR maps makes many karts have parts that are much more shiny than they are supposed to be, such as Tux's body and wheels, Gavroche's body, Hexley's body (less so, but still off) etc.

- [ ] Tux's tailpipes and engine are not defined as metallic.
- [ ] Tux's `wheel_gloss.png` is different in the media repo and stk-assets.  The one in the media repo has metalness defined for the "TUX" plate on the back of the kart, which is probably more correct.

- [ ] Xue's kart as a whole has completely non-reflective paint, this doesn't really fit the other karts.  Honestly I liked the old look better, maybe just revert? (sorry samuncle)

- [ ] `trak2_holes1a_gloss.png` in STK Enterprise should be removed, it makes the surface glossy when it doesn't make sense.

**Comment by Benau** [comment]
mix(vec3(specMapValue / 2.0)?

**Comment by samuncle** [comment]
Hi,

1) I created a legacy shader that uses the old value so old texture will use this shader
2) Tux's kart was probably created before the new formula
3) we should then use the one in the repository
4) weird it should be reflective even more now since non metallic surface reflect the sky (edit I just cĥecked and it might be caused by the normal map which seems too strong).

I will fix the xue thing
5) yeah this needt to be removed

**Comment by qwertychouskie** [comment]
@samuncle Is it intentional that a Red value of about 60% results in extreme glossiness?  If you could please double-check the rendering calculations that would be appreciated, as I'm currently trying to adjust Tux's glossmaps to the new engine, but I'm getting the feeling that something is not right, it seems like some value may be getting doubled or something.

**Comment by Benau** [comment]
or do u think we can adjust the red channel of all pbr_data / gloss map like u in the past to remove g channel (using python / imagemagick?)

and i think you should come irc so we can discuss further....

**Comment by Mrxx99** [comment]
But only changing maps will not affect addons, so they will still look wrong, no?

**Comment by qwertychouskie** [comment]
For now the gloss change was reverted for 0.10, but IMO the whole rendering equation needs to be revisited for 0.11 to ensure correctness.

I am currently working on Tux's glossmaps, will try to get them into the final 0.10.

**Comment by qwertychouskie** [comment]
@Benau Please commit these updated files: [tux_update.zip](https://github.com/supertuxkart/stk-code/files/3051151/tux_update.zip)

**Comment by qwertychouskie** [comment]
Tux's fixed files are now committed.  @samuncle Can you please update Xue?  The new Xue isn't committed to the media repo, and from the looks of things the proper way to fix it is to use Substance Painter.

Alternatively, if samuncle isn't able to before 0.10, going back to the old Xue would be the best option.  I can update the old Xue's glossmaps for PBR.

**Comment by qwertychouskie** [comment]
Fix for Kiki's kart: [kiki_glossmap_fix.zip](https://github.com/supertuxkart/stk-code/files/3066480/kiki_glossmap_fix.zip)
