### ISSUE TITLE
Add text selecting/copying in the Online Chatbox

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#3811]
## Description

Sometimes, people share some text to copy like code or especially links (YouTube Stk videos/channels, screenshots links, etc.) via the Chatbox.

But we can't copy them and have to retype every character... I think that this will be a common situation, so it should be possible to select and copy text in the messages history like we can currently do in the message composition field.

**Comment by Benau** [comment]
selecting is really difficult ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif) ![](https://cdn.lihkg.com/assets/faces/pig/wail2.gif) ![](https://cdn.lihkg.com/assets/faces/pig/wail3.gif)

copying is now implemented in 5a585b85fb29684a478abbcfe0cac479882658ce, if you click the text after username, it will only copt the text after ":" ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
