### ISSUE TITLE
Support 0.10-beta config directory

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-code#3812]
By mistake the config directory was named 0.10-beta in the beta release. While config version number and STK release version are not necessarily coupled, I think the beta would cause a lot of confusion if we left it there.

In order to support our beta testers (i.e. avoid that they will start with a new config and will lose all their settings, progress, ...) I would suggest that only in the next release we add code that will check for config-0.10-beta if config-0.10 is not found. This would be only used for reading in the config (i.e. writing out would still go to a new config dir config-0.10), and would only go into the release branch for this release.

**Comment by Benau** [comment]
auria you can see if 94e090d14abdf36b7171cb47875fc96c39dd9abd from 0.10-rc1 branch works for u in msvc and osx (it use rename() ) (my linux mingw and android works)

**Comment by hiker** [comment]
This worked for me - I would suggest to also test if the config-0.10 directory does not exist: while rename fails (silently, we don't test for errors), there is no need to all the time try (and fail) with the rename (which could happen e.g. if a user starts the beta in between - be it by mistake, or maybe because he wants to compare something). Otherwise that's a good idea.

**Comment by Benau** [comment]
the check committed and all system we support are tested and work as expected
