### ISSUE TITLE
Maybe making ramdom people joining a server in control of that server isn't a good idea...

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3814]
![image](https://user-images.githubusercontent.com/13989090/55430795-d965ad80-5543-11e9-99e8-a9c391cb3d48.png)

At least for Trusted servers, let's disable this.  Community servers can do whatever they want, of course.

**Comment by Benau** [comment]
make suggestion in forum

**Comment by Alayan-stk-2** [comment]
Well this is a potential issue indeed with bad people "privatizing" an official server. But solutions are limited as well.

You should open that forum thread, qwerty.
