### ISSUE TITLE
Geometry detail is unaffected by graphics presets

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3816]
## Description
Go to the graphics/video settings. Select all of the presets and check out in the custom graphics settings dialog what has changed. Almost everything is affected by the presets, but one setting is not: Geometry detail: No matter what preset you choose, the geometry detail never changes. You must change it explicitly.

## What is expected
High graphics presets should have a high geometry detail. Low graphics presets should have a low geometry detail.

## Config
STK Source (PPA, distribution package, official binary, etc.): Git clone
System: GNU/Linux
Version: b03af63ab7c6b86abe6c4f6ce3df2c07ab68f5a9

**Comment by Alayan-stk-2** [comment]
Low geometry detail drops some elements from visible to invisible, for a rather small performance gain. Even on a low-end mobile intel CPU with integrated graphics, it is questionable. Does it really make a difference to reach a 720p @ 60FPS target on low-end machines ?

I'd rather lean to not make this option linked to the preset graphics options to avoid selecting the low preset automatically triggering the low option.

**Comment by Wuzzy2** [comment]
I don't understand the logic here. Why is the geometry detail completely ignoring the preset?

**Comment by Alayan-stk-2** [comment]
Done in https://github.com/supertuxkart/stk-code/commit/8dbf0a9922c483dbe358e06a0a2764fcb56f9eb5 ; after changes made in https://github.com/supertuxkart/stk-code/commit/553595fa63df496a95245f3dacc966c9085237c2 and other commits changed what is affected by geometry detail to focus on Auto-LoD
