### ISSUE TITLE
Name+Version+Description in Windows control panel

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3818]
I installed SuperTuxKart-0.10-rc1-installer-64bit.exe in Windows 7.

In control panel where you uninstall SuperTuxKart under name it says name+version+description.
![stk](https://user-images.githubusercontent.com/1836590/55675149-b4b06380-58be-11e9-895c-bddaec361c45.jpg)

I suggest removing the description from the name and moving the version information under the version column so its something like this:
![stk2](https://user-images.githubusercontent.com/1836590/55675198-3b654080-58bf-11e9-8471-0410c5e77305.jpg)

Maybe the publisher should be something else then SuperTuxKart.
At the bottom of https://supertuxkart.net/ it says "SuperTuxKart Team" so maybe that should be used as publisher.

**Comment by scootergrisen** [comment]
There is also a comments column where the string "3D open-source arcade..." could be moved to.
The comments column is not visible by default in Windows 7.

**Comment by scootergrisen** [comment]
The URL used in multiple columns is surrounded by " and " which perhaps should be removed.

    "https://supertuxkart.net"
    https://supertuxkart.net

Perhaps add a "/" at the end:

    https://supertuxkart.net/

**Comment by Benau** [comment]
![dw](https://user-images.githubusercontent.com/3252341/116732535-865dcd80-aa1d-11eb-9fb3-f9817292100d.png)
![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

Moving version number to its own tab may not work very well if there is non-number inside the tag, as you can see in regedit it's a integer only ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
