### ISSUE TITLE
Karts are a bit off on the winner's podium

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3821]
## Description
If you win a grand prix in Story Mode, there's a chance the karts are a bit off on the winner's podium.

## Steps to reproduce
1. Play the GP “At World's End” in Story Mode and SuperTux difficulty with Beastie.
2. Win.
3. Watch the winner's podium animation

Oddly enough, this does not seem to happen with 100% reliability. It only happend once to me so far and I do not know what exactly triggers this bug.

## Configuration
STK release version: 0.10-rc1
STK Source (PPA, distribution package, official binary, etc.): Git

**Comment by deveee** [comment]
Fixed in current git
