### ISSUE TITLE
Missing auto-rescues in ravenbridge mansion

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-code#3822]
From the forum :

>  Ravenbridge Mansion: the first time I got stuck in that trench/pit in the middle of the road, I fell onto the grassy edge and had to manually reset. It would be nice if the karts fell down into the reset zone since there is no other way to get out without manually resetting, unless you choose to steer into the pit. Maybe have that grassy part end as you drive forward, forcing you into the pit and respawning.

**Comment by BlueCatYellowCat** [comment]
From IRC:
>https://files.catbox.moe/oliaua.mp4 - It's nice to ride on the ledge there, but once you hit the wall there is nowhere to go. In a race, this could be annoying.

**Comment by Benau** [comment]
Fixed in irc

**Comment by Benau** [comment]
Fix in svn
