### ISSUE TITLE
Online game: Start race immediately on unanimous vote

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3825]
## Description
This is a suggestion for online racing. When players are voting for tracks, I suggest the game to start immediately if all players vote for the same game settings (track, laps, etc.) as there is no reason to wait any longer.

Currently, the race starts sooner when there is a majority, but with a short delay. I do not suggest to drop this behaviour, but to extend it with the behaviour above.

Summary:
* No majority: Start after time runs out (current behaviour)
* Majority: Start after delay (current behaviour)
* Unanimous vote: Start immediately

**Comment by Coeur-Noir** [comment]
…so last one to chose a track can't change his⋅her mind ?

**Comment by Benau** [comment]
Actually this becomes less interesting as sometimes players will change kart for some track now
