### ISSUE TITLE
XR591 Leaving the designed path

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3828]
## Description
When driving on XR591 you can get out of the course without getting reset by being fast enough on the left turnoff.
It seems the game tempts to reset the player but the lower path after the start stops that.
It can only be done when being fast otherwise the player is reset.

Video: https://streamable.com/hxj6c

## Configuration

STK release version: 0.10-rc1

STK Source: official binary

System: Ubuntu 18.10

**Comment by Alayan-stk-2** [comment]
Labelling this as minor as it doesn't allow to go faster.

This track is messy when it comes to rescue, checklines...

**Comment by Benau** [comment]
Fixed in svn
