### ISSUE TITLE
Snow Peak off course area

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3829]
## Description
When driving on Snow Peak at the right side after the start there are some rocks you can drive on but never get back on the road. It's clearly not intended as the player can also see through the map.
It would be best to either remove these rocks (and fall into the water) or get Thunderbird to prevent it.

Some videos:
https://streamable.com/kbqqd
https://streamable.com/7sl2g
https://streamable.com/64c6z

## Configuration

STK release version: 0.10-rc1

STK Source: official binary

System: Ubuntu 18.10

**Comment by Alayan-stk-2** [comment]
It's easy enough to get rescued, but I have to agree it's weird to be able to drive a bit without being able to get back on road.

I'm not keen on having all off-road trigger immediate rescues, but there is no real "exploration" to do there.

**Comment by Alayan-stk-2** [comment]
Snow Peak will be removed for 2.0, while changes for 1.5 would break compatibility.

Improving this could be useful for a future enhanced Snow Peak addon, but it is not relevant for the main-game issues tracker.
