### ISSUE TITLE
Total GP time stops counting at 59:59.999

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3831]
## Description
If you are crazy and play a huge GP that goes over 1 hour, the total racing time in the race result page stops counting the time.

Yes, I actually found this bug by legit playing. I played a GP will ALL THE TRACKS! And in both directions, too. :D

## Steps to reproduce
1. Create a huge GP with all tracks or even more
2. Play for over 1 hour (or somehow cheat your time)
3. Look at the race result page

### Expected result
The total racing time displayed for all players is displayed correctly.

### Actual result
The total racing time displayed for all players is 59:59.999 minutes and no longer increases.

### Suggested fix
Simply allow the minute counter to exceed 59. The upper bound should be much more generous. I don't think a hour counter should be added.

## Configuration
STK release version: bd7ff6cf3c22f6cf2f590d7cc2a6697d979e9e50
STK Source (PPA, distribution package, official binary, etc.): Git

**Comment by Alayan-stk-2** [comment]
The code converting the raw time into minutes/seconds also support hours (I added it a few months ago, the code had been done to be able to support the story mode timer), so I'd rather use hours than show 85 minutes or something like this.

**Comment by Wuzzy2** [comment]
OK.

**Comment by Wuzzy2** [comment]
Fix NOT confirmed in 1.0.0. Please re-open.

Image:
https://satoshiupload.com/images/UwXdKz2VfF.png

**Comment by Alayan-stk-2** [comment]
Works perfectly on my 1.0. Are you sure you're testing on the correct version ? Admittedly, I didn't bother to race for an hour to test it, I skipped the races, not that it should change anything. And AIs raced over an hour by themselves and got the correct times displayed.

**Comment by Wuzzy2** [comment]
Yes, I am absolutely sure this was in 1.0. Specifically, it's the package `supertuxkart-1.0-2` from Arch Linux.

When I only skip races like you say, the times actually go over 1 hour.
You actually have to reach the time by full races. Strange.

Maybe an easier way to test this by doing 1-lap races on OMC only and temporarily hardcode some bogus finish times instead of skipping?

**Comment by Wuzzy2** [comment]
## How to reproduce

1. Create a GP with 5 times Oliver's Math Class, 1 lap, forwards
2. Start a time-trial grand-prix on your new test GP, difficulty SuperTux, kart Hexley
3. Race 1: Complete normally with ca. 40 seconds
4. Race 2: Immediately give up as soon as you can (this will give you and many bots +59 minutes)
5. Race 3-5: Complete normally with ca. 40 seconds

After each race 3, 4 and 5, check out the list of times. Someone should get a 59:99.999 eventually.

**Comment by Alayan-stk-2** [comment]
For some reason, the time added to the total when skipping the 1st race will be almost two hours, but it will only about one hour when skipping the second one...

Hours are displayed only if someone reached > 2 hours.

**Comment by Alayan-stk-2** [comment]
Definitive fix for this issue : https://github.com/supertuxkart/stk-code/commit/fb99661d5d9fd3cf68a09e601dbc7707dce516d4
