### ISSUE TITLE
No rank shown in battle modes

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3832]
Your rank is not shown in the battle modes, CTF and soccer. The rank is normally displayed in the speedometer in races, but in the battle modes, CTF and soccer, this spot is left empty for now.

I suggest to support the rank display for these modes.

## How the rank should work

* FFA: The higher your score, the better your rank. The highest score gives you rank 1. It is possible to tie for a rank which will skip some lower ranks, i.e. If 2 players tie for rank 1, the rank 2 is skipped. This is common practice in sports.
    * For example: If there are 3 players with scores of 5 (player 1), 5 (player 2) and 3 (player 3), player 1 and player 2 both rank 1 and player 3 ranks 3.
* 3SB: Same as FFA, but here the number of lives is considered your “score”
* CTF and Soccer: You rank 1 if your team is in the lead or is tied for the lead. You rank 2 otherwise.

**Comment by Alayan-stk-2** [comment]
This is debatable for FFA and 3SB (I don't miss the rank indicator in these modes but opinions may vary), but this would be simply clutter in CTF and Soccer.

**Comment by Wuzzy2** [comment]
Yeah, I have no strong feelings about this, especially CTF/Soccer.

But it seems kinda useful for FFA and 3SB, esp. with many players.

**Comment by CodingJellyfish** [comment]
Make it easy:
When it's race, show rank
When it's battle, show score
When it's soccer, show nothing
