### ISSUE TITLE
Gran Paradisio bridge sound bug

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3837]
## Description
When driving on Gran Paradisio Island and jumping on the bridge the driving sound plays instantly even though the player is in the air.
When pausing the game the driving sound just continues.

Video: https://streamable.com/hnhfb

## Configuration

STK release version: 0.10-rc1

STK Source: official binary

System: Ubuntu 18.10

**Comment by Alayan-stk-2** [comment]
Fixed with https://github.com/supertuxkart/stk-code/commit/963c6de4cd6455ab91be98adc39f9b194c09f9a6
