### ISSUE TITLE
karts not placed on tree stumps (podium) after grandprix

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3839]
## Description
2 out of 3 karts are placed incorrect on tree stumps/podium after grandprix.

## Steps to reproduce
Complete pinguin playground grandprix and watch the 3 winner karts at the end.
2 are not placed correctly on the tree stumps.
They are placed right in front of the tree strumps instead.

## Configuration
STK release version: 
SuperTuxKart 0.10.0-rc1

STK Source (PPA, distribution package, official binary, etc.): 
https://datapacket.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/0.10-rc1/SuperTuxKart-0.10-rc1-installer-64bit.exe i think
System: 
Windows 7
Graphics card: 
Intel HD (gives warning about driver when starting STK)

**Comment by Benau** [comment]
It's fixed in latest git
