### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3841]
The TLS certificate for supertuxkart.net expired two hours ago (Sat, 13 Apr 2019 07:10:58 UTC)

See: https://www.ssllabs.com/ssltest/analyze.html?d=supertuxkart.net

Many Letsencrypt clients have an automatic renewal process to prevent this from happening.

**Comment by MinIsMin** [comment]
To add, for addons.supertuxkart.net there's no valid certificate even though the server is configured for TLS and even supports TLS 1.3 which the main website doesn't.
See: https://www.ssllabs.com/ssltest/analyze.html?d=addons.supertuxkart.net

**Comment by auriamg** [comment]
It looks like the certificate for supertuxkart.net has been renewed, everything seems ok to me.

Also, addons.supertuxkart.net is obsolete, you should now use https://online.supertuxkart.net/ which does have a certificate

**Comment by leyyin** [comment]
I just fixed it, very weird the server had a cron job for auto renewal but it did not work for some reason :man_shrugging: .
Also the  addons.supertuxkart.net is only used for the old clients and we can't use a proper cerificate there, pls use http://online.supertuxkart.net/

**Comment by MinIsMin** [comment]
Thanks, working fine.

addons.supertuxkart.net is actually used for downloading addon data via http from the client (0.10-rc1).
The assets file http://addons.supertuxkart.net/downloads/xml/assets.xml, icons
`[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/images/32999604857af930517f49.png`
and the addons are downloaded via http://addons.supertuxkart.net

**Comment by qwertychouskie** [comment]
Hmm, that does seem like an issue.  @MinIsMin Please open a new issue so we can get it fixed.
