### ISSUE TITLE
old reference to addons.supertuxkart.net in news.xml

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3842]
> Hmm, that does seem like an issue.  @MinIsMin Please open a new issue so we can get it fixed.

_Originally posted by @qwertychouskie in https://github.com/supertuxkart/stk-code/issues/3841#issuecomment-482853638_

addons.supertuxkart.net is (probably accidently) used for downloading all addon data by the client (0.10-rc1).

The https://online.supertuxkart.net/downloads/xml/news.xml references the assets file from the old server http://addons.supertuxkart.net/downloads/xml/assets.xml.
```
<?xml version="1.0"?>
<!DOCTYPE news
SYSTEM "../assets/dtd/news.dtd">
<news version="1" mtime="1555113602" frequency="0">
    <include file="http://addons.supertuxkart.net/dl/xml/assets.xml" mtime="1555113602"/>
    [...]
</news>
```
The assets.xml states to load all files from the old server so all icons (see console output of supertuxkart)
`[info   ] HTTPRequest: Downloading http://addons.supertuxkart.net/dl/images/32999604857af930517f49.png`
and the addon zips are downloaded from http://addons.supertuxkart.net

Changing the `include file` in https://online.supertuxkart.net/downloads/xml/news.xml fixes it.

**Comment by leyyin** [comment]
This is intended so that the old clients can download the files :man_shrugging:

**Comment by MinIsMin** [comment]
How I see it:

#### old client
http://**addons**.supertuxkart.net/.../news.xml -> http://**addons**.supertuxkart.net/.../assets.xml

#### new client
Currently is: https://**online**.supertuxkart.net/.../news.xml -> http://**addons**.supertuxkart.net/.../assets.xml
Should be: https://**online**.supertuxkart.net/.../news.xml -> https://**online**.supertuxkart.net/.../assets.xml

Why should new clients downgrade from HTTPS to HTTP and use the old server?
The **online** news.xml should reference the **online** assets.xml and not the old one.

Why use the new server to download the addon data with new clients? Online is
- significantly faster
- TLS secured

If it's the same file storage it would be best to add a redirect based on the subdomain (.htaccess would be easiest) to a variant of news.xml which references the online server
If not than simply change the news.xml file on online to reference the new server.

**Comment by leyyin** [comment]
There is only one `assets.xml` and `news.xml` shared by both servers.

**Comment by MinIsMin** [comment]
Okay, I got two questions:
- is there a schedule for the full migration to the online server for addon data?
- why is the hardcoded URL in the clients [...]/`dl`/xml/news.xml which always redirects to [...]/`downloads`/xml/news.xml? Why not use `downloads/`?

**Comment by leyyin** [comment]
`is there a schedule for the full migration to the online server for addon data?`
I don't really understand this questions, both servers run from the same VPS.

As for the second question, we use that redirection to track downloads (stats) directly from PHP (very old code)

**Comment by MinIsMin** [comment]
I mean the switch from **HTTP** addons.supertuxkart.net to **HTTPS** online.supertuxkart.net for addon data in the client.

Why not create a new xml file (run `generateNewsXML()` again with `ASSETS_XML_LOCATION_V2 = "online.stk"` and another output name) and let the new clients use the new one (e.g. news_v2.xml) so new clients can use the new HTTPS online.stk while old clients keep using the old HTTP one?

If you approve I can create a PR here and at stk-addons for that.

**Comment by leyyin** [comment]
Sure sounds good, but first create the PR for stk-addons.

**Comment by leyyin** [comment]
The changes are online.
See https://online.supertuxkart.net/dl/xml/online_news.xml
and https://online.supertuxkart.net/dl/xml/online_assets.xml

**Comment by MinIsMin** [comment]
Great!
Next would be either rewriting the URL serverside or changing [the hardcoded URL clientside](https://github.com/supertuxkart/stk-code/blob/edd1280dbcff3abfb2c4ef940afd7f3f8e647b10/src/addons/news_manager.cpp#L107).
Both could be done, rewriting would be for 0.10-rc1 and changing the hardcoded URL for the next client update but I think changing the URL clientside is enough.
