### ISSUE TITLE
Supertuxkart 0.9.3 can't start on MacOS using case sensitive filesystem 

### ISSUE THREAD

**Issue by mica100** [supertuxkart/stk-code#3843]
## Description
After installation the application icon is marked with a defect sign from Mac OS.

## Steps to reproduce
Download the mac package (dmg file). 
Copy the supertuxkart (app) to the application folder.
Try to start the application.

## Configuration

STK release version: 0.9.3

STK Source (PPA, distribution package, official binary, etc.): sourceforge dmg package for Mac

System: iMac, Mac OS Sierra

Graphics card: Radeon HD

CPU: i5

Gamepads/keyboards models if related to the issue: 
Keyboard

## Additional information
To workaround:

* open a Terminal
* run the following command

```
/Applications/supertuxkart.app/Contents/MacOS/supertuxkart
```

To fix the problem:

* Change the file Contents/Info.plist
```
<key>CFBundleExecutable</key>
<<< <string>SuperTuxKart</string>
---
>>>  <string>supertuxkart</string>
```

**Comment by Alayan-stk-2** [comment]
I assume this still apply to 0.10-RC1, but can you please install it and check ?

**Comment by mica100** [comment]
Yes. Also in 0.10. Same problem. Same fix needed.
