### ISSUE TITLE
Black forest nitro improvements

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3845]
After discussions with Andet, and tests showing that left path + tunnel path is noticeably faster (2 to 3 seconds), which isn't deserved looking at the relative difficulties, we've come up to the conclusion it's mostly down to the railroad path on bridge and tunnel, with some nitro cans which can be changed.

On the railroad, on the bridge, there is : big nitro, small nitro, big nitro. The big nitro should be replaced with small nitros.

Inside the tunnel, there are three small cans. Keep the one in the middle, remove the two others.

Unrelated nitro can improvement : in the house, remove the big nitro can under the table (it can't be accessed without colliding with the table first), and change the big nitro can in the inside door with a small one. The house path is a fun gimmick for exploration, which is decent in low difficulties, but stuffing it with too much nitro gives the wrong impression of it being important.

**Comment by Benau** [comment]
alayan konqi ghost needs to be redone!
