### ISSUE TITLE
Make it easier to play addon tracks in online multiplayer

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3850]
In online multiplayer it would be nice if it was easier to play the addon tracks when i get tired playing the standard tracks.

From what i can tell both the server and each player have to have the same addon track in order to be able to vote for that track.
So if a player dont have the track someone have to write what to do in the chat and the player have to remember it and leave the server, go to addons and search for the track and download it manually and rejoin the server and maybe wait for the current game to end to be able to play.
And then if a new player joins that does not have the track it prevents the track from being played it seems.

Instead of having to do that each time it would be nice if it can somehow be done in an easy way and maybe without leaving the server.

Like maybe players could see what tracks the server have even if the player dont have the track.
And then if you vote for the track it can say you dont have this track do you want to download it or something.

## Steps to reproduce
Start STK
Online > global network > find server
Join a game
click Ready and wait
select a kart
select addons

## Configuration

STK release version: 
SuperTuxKart 0.10.0-rc1

https://datapacket.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/0.10-rc1/SuperTuxKart-0.10-rc1-installer-32bit.exe i think

System: 
Windows 7

**Comment by Benau** [comment]
see #3635
