### ISSUE TITLE
Arrow and head blocks view in football

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3851]
When playing football there is a red/blue arrow on top of the kart.
I guess to show what team you are on.

With the camera angle being as it is the arrow is in the way of seeing what is in front of you.
Like you cant see the football/other players far away when you are pointing straight at it like at the beginning of each round (after a goal).

And the head of some characters/kart (like Sara) are high up so it also blocks the view.

So i guess maybe change the camera angle or maybe have a circle around the kart just like the mini map have a circle.
I guess if we have to make it like football the players should have different colors on but maybe not easy.

## Steps to reproduce
Start football game
Select Sara kart.
Notice how the arrow and Sara's head is in the way of seeing the football/others players far away.

## Configuration

STK release version: 
SuperTuxKart 0.10.0-rc1
sourceforge
System: 
Windows 7

**Comment by Benau** [comment]
![SuperTuxKart_2019-04-18-20-10-08](https://user-images.githubusercontent.com/3252341/56360095-10131780-6216-11e9-8442-b42f381bc5a4.jpg)
Update your graphic card to have kart color
