### ISSUE TITLE
HTTPS error donate.supertuxkart.net

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#3857]
http://donate.supertuxkart.net always redirects to https://donate.supertuxkart.net

The problem is that donate.stk.net has the certificate for piwik.stk.net and thus is rejected by any browser. It's a real problem since no one gets to the donation page using this link.

PS: blog.supertuxkart.net has no TLS support at all which would be nice to have as Google supports TLS certificates with custom domains for some time now.

**Comment by Alayan-stk-2** [comment]
@leyyin Could you look at this ?

**Comment by bkmgit** [comment]
There is a similar problem for http://privacy.supertuxkart.net/

**Comment by MinIsMin** [comment]
`privacy.supertuxkart.net` is working now but not `donate.supertuxkart.net`

**Comment by vampy** [comment]
Ups, did not see the issue until now, will have a look

**Comment by MinIsMin** [comment]
Any update on this?

**Comment by MinIsMin** [comment]
Still an issue...

**Comment by Benau** [comment]
try now? ![](https://lihkg.com/assets/faces/pigxm/lihkg.gif)

**Comment by MinIsMin** [comment]
Working now!

(blog.supertuxkart.net is still HTTP-only but that's minor)
