### ISSUE TITLE
Brake is reverse

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3858]
In keyboard options "Brake" is actually reverse because the kart will go backward if you keep holding it.

I guess there are no brakes on the karts.

## Steps to reproduce
Go to Options i the main menu.
select controls
select keyboard 0
Look for Brake.

## Configuration
STK release version: 
SuperTuxKart 0.10.0-rc1
STK Source (PPA, distribution package, official binary, etc.): 
sourceforge

**Comment by auriamg** [comment]
I guess the texte could be renamed into something like "brake/reverse" for clarity

**Comment by scootergrisen** [comment]
I would not call it something with "brake" since it does not brake.

**Comment by Alayan-stk-2** [comment]
It definitely brakes. It doesn't use a separate button from going in reverse because that would be pointless and stupid.

**Comment by scootergrisen** [comment]
So does it brake when you go forward?

**Comment by Alayan-stk-2** [comment]
Yes

**Comment by Yionnara** [comment]
My team and me will change it to brake/reverse in english and according to our nationality will change it in french too, but you are all free to change it in your own language.
