### ISSUE TITLE
Allow enabling screen joystick on other systems than Android

### ISSUE THREAD

**Issue by undevdecatos** [supertuxkart/stk-code#3859]
I have installed pmOS on my phone and installed stk on it, but can't play without external keyboard or wiimote.

**Comment by deveee** [comment]
Do you meen linux distribution postmarketOS? Touch device should work in wayland session if you will compile STK with wayland support.

**Comment by Mrxx99** [comment]
Maybe there could be an option in the settings to activate touch race UI?

**Comment by deveee** [comment]
There is ```multitouch_active="2"``` in config.xml, but atm. multitouch is supported only on android and wayland, so it's not really usable on other systems.

**Comment by UnMe0w** [comment]
Ok, it worked for me.

**Comment by 7wells** [comment]
Please apologise that I ask this question here after close:

Does this mean that on Android, it is possible to steer/accelerate/brake by touching fields (left/right/?) on the screen?

So far, I only see either the steering wheel or the tilting function (gyroscope, if available on the device).

The kids would prefer some touch fields, if that is possible.

Again, please accept my apologies if my question here is in the wrong place. And I really do not mean to appear as if requesting yet another feature. You guys surely have more important stuff. But please just give me a little note if my understanding was correct and by adjusting some setting in xml, some kind of touch fields are available. Sorry if I got that completely wrong. :blush:

**Comment by deveee** [comment]
I made something like this some time ago: https://github.com/deveee/stk-code/commits/simplified_stk
You can turn left/right by touching edges of the screen, there is autoaccelerate and autorescue. So that it should be easier for kids. I also simplified gui a bit to make buttons bigger.

**Comment by 7wells** [comment]
Oh, that's great! Can you please give a small hint how I can use that? I know how to compile for Android (also thanks to your and others' kind help). But I have no idea how to proceed with "simplified_stk". Thank you! :)
