### ISSUE TITLE
Creepy lights on the ears in rav mansion

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3865]
![image](https://user-images.githubusercontent.com/35170687/56495691-1c0a1c80-6529-11e9-8f72-485ab020ac20.png)

**Comment by auriamg** [comment]
I don't see any issue there? the sides of the ears are lit up by the kart's front lights, doesn't seem like a bug. Maybe it's not as pretty as it could be, but that's how the engine works atm

**Comment by Alayan-stk-2** [comment]
I agree, this doesn't look like a bug to me.

**Comment by Yionnara** [comment]
Not a bug at all, its clearly the vehicle's highlights. Nothing to do here.
