### ISSUE TITLE
Use plunger to grab boxes/nitro?

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3867]
Currently the plunger is not useful unless you are close to another kart, and since you get a lot of plungers in 1st, it makes them annoying and useless 95% of the time.

When watching a video, I saw an interesting game mechanic that would work quite well with a plunger: https://youtu.be/OTLREpMM9tE?t=750

In this case, instead of rolling something into the item box/nitro can, the plunger would grab the item box/nitro can and pull it into the kart.

@Alayan-stk-2 Thoughts?

**Comment by auriamg** [comment]
This is a bug tracker meant to track bugs with the game, this is not the appropriate location for brainstorming possible future improvements.

**Comment by CodingJellyfish** [comment]
Why this idea is so interesting and I really like it.

**Comment by FormalSnake** [comment]
it actually is really interesting
