### ISSUE TITLE
SuperTuxKart lacks IPv6 support

### ISSUE THREAD

**Issue by oyvinds** [supertuxkart/stk-code#3870]
Problem: I've setup a SuperTuxKart server on my LAN's Internet gateway. Starting SuperTuxKart and going "online" and global networking and find server and selecting my server results in connection failure. I see in the log ConnectToServer: Registering addr xx.xx.xx.xx:57771 where xx.xx.xx.xx is my external Internet IP. The gateway server running supertux gets informed the client is on itself (where that IP is) and everything fails.

If I launch it with
supertuxkart --connect-now=10.66.99.1:2759 --connection-debug
so it connects to the internal LAN IP I'm totally able to play and others can connect to the server and it works.

While solutions to this particular setup where a globally available SuperTuxKart server is on a gateway and you'd like to connect to it from a NAT IPv4 IP could and perhaps should be solved, the better long-term solution is, in my opinion, to add IPv6 support to SuperTuxKart. The above almost-blog-post long story about a NAT problem is a non-issue if SuperTuxKart's server simply starts listening on both IPv4 and IPv6 & clients try IPv6 if it has that and IPv4 if it doesn't or IPv6 fails.

**Comment by Benau** [comment]
You can connect to ipv6 global server now

**Comment by Benau** [comment]
btw server discovery on gateway should work in git now (if you enable ipv6 server and your lan clients have local link address) so stk in lan will [ff02::1]:2757 to all devices and it should detect the gateway server if you don't block udp ipv6 multicast
