### ISSUE TITLE
[ sad request ] report abuse ?

### ISSUE THREAD

**Issue by Coeur-Noir** [supertuxkart/stk-code#3872]
Hi,

…pity
![Capture du 2019-04-24 12-01-59](https://user-images.githubusercontent.com/1895947/56651381-2e9b6780-6689-11e9-881e-19a5a81d07ca.png)

Don't know if there are logs for the entire conversation but it was not friendly at all.

**Comment by Dafnik** [comment]
GitHub is a development platform, not a report system for users

**Comment by Coeur-Noir** [comment]
You're right Dafnik.

Maybe this might be seen as a request to add a report/abuse button somewhere.

Towards user ? Towards server ? It's quite sad to think about that.

But as servers are « public » anyone can say anything - just remind that insults and discrimination are not freedom expression.

**Comment by Dafnik** [comment]
I would implement it in a Minecraft kind of way. Mojang also doesn't ban your account if you are rude on one server but the individual owner of a server could do it.

**Comment by Alayan-stk-2** [comment]
The request for some report button already exist in an other ticket. This is not the place to report bad users. Signal them on the IRC or the forum.

Ceci dit, au moins un des types dans la conversation mérite clairement un ban (mamanaber).

**Comment by Coeur-Noir** [comment]
Hélas pas que lui...

Bref. Ok pour le closed puisque c'est une redite, désolé.

**Comment by UnMe0w** [comment]
Ils faut les ban ces fdp
