### ISSUE TITLE
More players in a server than the max-players limit

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3874]
Seems to happen when two players connect at about exactly the same time.

Labelling minor because it is rare, but it causes a stall on the following race/game until one player gets kicked.

**Comment by Wuzzy2** [comment]
Are you sure this is rare? Have you tested how commonly this bug occurs? In our play sessions today, it seemed to have happened more than just once … Correct me if I'm wrong.
