### ISSUE TITLE
Small suggestions for HUD improvements for challenges

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3878]
To improve the usefulness of the HUD in challenges a bit, I have the following suggestions:

1) In challenges with time limit, move the countdown clock to the top middle of the screen and make it larger and more visible, like in those old-school arcade racers.
2) In a challenge with a time limit, play countdown beeps for the final 10 seconds and make the countdown clock red in this time
3) When the time limit's up, display a big message in the center (!): “Time's up!”
4) In a race in which you need to get a certain rank, paint the rank display green when you are within the rank limit and paint it red when not.

**Comment by Alayan-stk-2** [comment]
I disagree with 1, moving the time indicator elsewhere would introduce many complications. Though maybe it could be made more visible. It could also be colored depending on how well the player is doing (green = continuing like that should win, red = continuing like that will fail it).

For 2, indeed an audio alert would be nice. Feel free to search an appropriate sound at opengameart or elsewhere to facilitate the introduction of tis feature.

For 3, why not.

For 4, why not again.

**Comment by Wuzzy2** [comment]
The problem I have with the countdown timer, it's easy to miss that the timer is counting down (instead of up). So making it distinct somewhat might help. I'm not totally attached to 1, could do in a different way.

Possible simple countdown sound: https://opengameart.org/content/countdown (countdown-a.ogg)

**Comment by CodingJellyfish** [comment]
Ill try to realise them

**Comment by Alayan-stk-2** [comment]
The following changes have been done in relation to the challenge UX:
- The countdown clock becomes colored yellow at 15s left and orange at 5s left.
- A sound alert ("countdown beep") is played in the last 5 seconds.
- Failing a challenge time-limit leads to a sad music and a "You were too slow" prompt, even when finishing first ahead of the AIs.
- The ends screen clearly displays (with red/green colored coding) which challenge requirements have been met or failed (time, rank, nitro).

I think this satisfies the point of this issue: making the player more aware of the challenge situation, especially when a time-limit is involved.

**Comment by Wuzzy2** [comment]
Yes. :+1:
