### ISSUE TITLE
Shortcut  in Snow Peak

### ISSUE THREAD

**Issue by rj1** [supertuxkart/stk-code#3879]
There is a shortcut in track "Snow Peak", allows you to skip driving across the wooden bridge. It takes a few practice tries but is easily replicated. 

Screenshots:

Shortcut start:
![SuperTuxKart_053](https://user-images.githubusercontent.com/625191/56701173-67583280-66c3-11e9-941f-296194a40f53.png)

Shortcut end:
![SuperTuxKart_054](https://user-images.githubusercontent.com/625191/56701177-69ba8c80-66c3-11e9-9907-102154d070f4.png)

STK release version: 1.0 

STK Source (PPA, distribution package, official binary, etc.): official binary

**Comment by Alayan-stk-2** [comment]
If you do this, you miss a checkline and your lap isn't counted. So this isn't an issue.
