### ISSUE TITLE
Excessive text and emojis entered into the chat will lag the client and crash the server

### ISSUE THREAD

**Issue by tehnull** [supertuxkart/stk-code#3880]
Pasting absurd amounts of text and emojis into any chat box causes client lag and eventually a server crash so hard you have to kill -9 the process.

The exact steps to reproduce are to copy this copypasta from [reddit](https://www.reddit.com/r/copypasta/comments/3runuo/longest_good_sh_post/) and paste it into any chat box in the game and hit enter.

STK release version: 1.0

Server compiled from source, client using default distribution package.  

System: Debian 9.8

Graphics card: Nvidia GTX 1080ti 11GB

CPU: Intel Xeon e5-1650 v1 ECC RAM

stdout.log: https://hastebin.com/gutanihica.cs unfortunately I do not have access to the server logs but that is my client log when it occurred.

**Comment by Benau** [comment]
![image](https://user-images.githubusercontent.com/3252341/59294431-0ce75580-8cb4-11e9-9d21-827d9b1e1c76.png)
It should be faster now (You need latest git server with proper utf32 /16 handling, 🇭🇰 server!)
