### ISSUE TITLE
No bots in LAN

### ISSUE THREAD

**Issue by Hi-Angel** [supertuxkart/stk-code#3884]
## Description

When creating LAN server, there's no option to add bots. This kind of defeats the purpose of LAN games, because LAN almost never has enough people to fill a server up.

## Steps to reproduce

1. In game menu go to: `Online → Local networking → Create Server`.

### Expected

Either the `Create Server` menu, or the one that appears after clicking `Create`, should have a button to add bots.

### Actual

Nor `Create Server` nor the menu after pressing `Create` has "bot" text anywhere.

## Configuration

STK release version: 1.0

STK Source: Archlinux Package

System: Archlinux

Graphics card: Radeon HD 6620G.

CPU: AMD A8-3530MX

**Comment by Luux** [comment]
Not only for LAN, I miss that online, too.

**Comment by Hi-Angel** [comment]
> Not only for LAN, I miss that online, too.

FWIW, I've found kind of workaround after reporting this, probably worth posting here. This command:

```
supertuxkart --connect-now=192.168.0.17:2759 --no-graphics --network-ai=6
```

would make 6 bots connect to the server running on the given IP:Port.

**Comment by Benau** [comment]
How about replace the GP track no with AI no for LAN game?![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)

**Comment by Benau** [comment]
![SuperTuxKart_2019-10-09-16-32-30](https://user-images.githubusercontent.com/3252341/66465020-a718a800-eab2-11e9-8dfa-60655c8c2611.jpg)
![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)![](https://user-images.githubusercontent.com/3252341/65811369-f96fe400-e1e9-11e9-8ad8-075d3a573ec7.gif)

**Comment by Hi-Angel** [comment]
Amazing, thanks!
