### ISSUE TITLE
Allow WAN without use of online.supertuxkart.net

### ISSUE THREAD

**Issue by DarkArc** [supertuxkart/stk-code#3886]
After some investigation, it seems SuperTuxKart only allows WAN play if a user is associated with the server, and a connection can be validated against online.supertuxkart.net.

This creates unnecessary coupling with online.supertuxkart.net. If online.supertuxkart.net is ever down, that inherently breaks multiplayer for all servers, and there's no option for direct connection.

---
Motivation:

I discovered this after struggling through what I originally believed to be a block on an IP range my game server resides on. Eventually it was determined that my host was blocking all traffic to/from digitial ocean due to a large number of attacks against their network.

**Comment by DarkArc** [comment]
Unfortunately as it turns out I reached out to the wrong group. I'm not sure who host online.supertuxkart.net, any help would be much appreciated.

**Comment by Alayan-stk-2** [comment]
The server list is retrieved by the clients from the addons website.

While the server could otherwise work independently, there would be no way for users to discover your server even exist, limiting its use to people to which you'd give the direct IP address to connect to (and as it's impractical, it wouldn't be used except possibly by your friends).

**Comment by DarkArc** [comment]
> While the server could otherwise work independently, there would be no way for users to discover your server even exist, limiting its use to people to which you'd give the direct IP address to connect to (and as it's impractical, it wouldn't be used except possibly by your friends).

I'm okay with that, it's been pretty standard that that be an option in my experience. Some groups also prefer to hide their servers -- ex for use in tournaments -- to prevent exposure to DDoS attacks.

**Comment by phkb01** [comment]
I second this, that would be very helpful. Just playing with friends is a very reasonable use.

**Comment by cgarz** [comment]
This should be an option.
Direct connection has been in most things for decades. It definitely wouldn't be impractical.
Certainly less impractical than telling everyone to install hamachi or something.

**Comment by Benau** [comment]
I added "LAN server can be connected too by typing your server public address (with port) in Enter server address dialog without relying on stk-addons." in NETWORKING.md, actually some stk fans already knows this https://github.com/supertuxkart/stk-code/issues/4295

![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by DarkArc** [comment]
This works for *W*AN servers?

**Comment by Benau** [comment]
if WAN player wants to connect your hidden server they need to type ip address anyway ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Benau** [comment]
you can disable validation player in xml so anyone without stk-addons account can connect by typing address too, some current stk servers already have that ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)
