### ISSUE TITLE
Will only auto login if internet connection was there as startup

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#3887]
If i start STK when the computer is connected to the internet i am logged in when STK starts.

But e.g. if i have just started my computer and the internet connection is still not established because it takes a little while and i start STK right away when STK is done loading i am not logged in.

So i either have to log in again in STK before i can go to online game or i have to quit STK and start STK again so that the internet connection is ready at the time STK starts.

Also i have tried that the password is not remembered even though i have selected to remember it so i have to go find the password which is a bit annoying because it not have forgotten the password had i wanted to launch STK untill the internet connection was there.

## Steps to reproduce
With internet connection available start STK and go to online and login and choose to remember password.
Close STK.
Disconnect system from internet.
Start STK.
Connect system to internet while STK is running.
STK will not log in automatically.
But when you restart STK it will.

## Configuration

STK release version: 
1.0.0
STK Source (PPA, distribution package, official binary, etc.): 
sourceforge
System: 
Windows 7

**Comment by luffah** [comment]
Minor but annoying...

**Comment by luffah** [comment]
@scootergrisen  FYI,  if you use compiled version of STK, you can workaround (the problem of credential vanishing) by commenting the code that remove the login. 
Then if you start STK with internet for training, you will see the connection error, but with the possibility to go back withou changing existing credentials. In this configuration, if you need to change your login, you just have to uncheck/check "Online" checkbox.

```diff
index 30f09a50d..9cfccb983 100644
--- a/src/states_screens/options/user_screen.cpp
+++ b/src/states_screens/options/user_screen.cpp
@@ -610,13 +610,20 @@ void BaseUserScreen::loginError(const irr::core::stringw &
 error_message)
     PlayerProfile *player = getSelectedPlayer();
     // Clear information about saved session in case of a problem,
     // which allows the player to enter a new password.
-    if(player && player->hasSavedSession())
-        player->clearSession();
-    player->setLastOnlineName("");
+    /* 
+     * if(player && player->hasSavedSession())
+     *     player->clearSession();
+     * player->setLastOnlineName("");
+     */
     makeEntryFieldsVisible();
     SFXManager::get()->quickSound("anvil");
     m_info_widget->setErrorColor();
     m_info_widget->setText(error_message, false);

```

If was fluent with CPP / GTK, i could propose a PR adding 2 buttons  "retry login" and "change credentials" (to show password input) when login fails. But that is not the case.
