### ISSUE TITLE
Portable version for Windows

### ISSUE THREAD

**Issue by huanghe2015** [supertuxkart/stk-code#3889]
Is it necessary for pack game as an installer?If not,it is possible to pack prebuilt files as a archive file?

**Comment by Benau** [comment]
You can check the portable version here (and for next release there will be portable version too, just unzip and click run_game.bat stk will auto start (and select 32 / 64bit)

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20190629/

**Comment by qwertychouskie** [comment]
Also, PortableApps.com has SuperTuxKart in its "repos", it's currently still at version 0.9.3 but according to https://portableapps.com/development/outdated it seems they are aware of the new version and thus it will probably be updated soon.
