### ISSUE TITLE
Powerup Manager Protocol Negotiation

### ISSUE THREAD

**Issue by DarkArc** [supertuxkart/stk-code#3898]
This is part one of practically implementing several changes I'd like to see in the SuperTuxKart powerup system.

We need to give the network a way to specify one of three different modes:
1. Default Client Side Prediction (most common)
    Use the default config, and predict powerups client side
2. Tweaked Client Side Prediction
    Exchange the server's powerup.xml file, and use this to predict powerups client side
3. Client Side Prediction Disabled
    Do not perform any prediction, only do what the servers says

Case 1, is going to be by far the most frequent, and is currently what happens.

Case 2, allows server owners to tweak their configuration files, and have this be updated in client side logic.

Case 3, allows server owners to completely replace the powerup backend with a custom implementation, and not have the client and server fight over what powerup to display resulting in an extremely buggy experience. This should preferably be used with low ping, but I don't see any reason to really restrict it -- even 200ms ping shouldn't be a big problem, I think the fighting is a bit jarring and distracting though.

**Comment by DarkArc** [comment]
I'd like to add this into 1.1 if at all possible. The primary issue I see is going to be how to handle the network traffic, as I don't see much setup for "large" server -> client data transfer like an XML file, or protocol versions to allow a server implementing this to downgrade its protocols to 1.0 and not break networking for 1.0 clients.

**Comment by Benau** [comment]
Overcomplicated

**Comment by DarkArc** [comment]
How is this overcomplicated?
