### ISSUE TITLE
STK crashes when using keyboard shortcuts of the debug menu during a race load screen

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3902]
The keyboard shortcuts for in-race actions are ignored in the menus, but not when the loading screen has started. However, not everything is ready for them at this point, so using them during the load screen crashes the game with a segfault.

**Comment by Benau** [comment]
hows aboot...
Use this in renderLoading
```
    irr_driver->getDevice()->setEventReceiver(NULL);
    irr_driver->getDevice()->run();
    irr_driver->getDevice()->setEventReceiver(GUIEngine::EventHandler::get());
    return;
```
so you can avoid the non-responding window / android anr, also should be good enough to "skip" event during loading
