### ISSUE TITLE
A little more pleasant control over the car

### ISSUE THREAD

**Issue by brigazvi** [supertuxkart/stk-code#3906]
The idea is to create a more subtle control system.
Today when the player presses the right button, he moves a lot, even if he wanted to make a slight curve.
The turn angle can be derived from the duration of pressing the button.
Long press = strong turn.
Easy touch of the button = Elegant lightweight curve.
I know that realism is not the goal of the game, but I thought it might improve the gameplay.

**Comment by Alayan-stk-2** [comment]
The kart does not turn instantaneously. It takes about 0.2s of pressing the right key to go from "go straight" to "turn to the right as much as possible".

Increasing the transition duration would make the kart significantly harder to handle and quick precise change of directions impossible.

It is already possible to be quite accurate in how you turn. With analog gamepads, by not pushing the direction stick to the maximum you can have an intermediate turn radius. And with keyboards, you simply need to be accurate and do quick short corrective maneuvers. I've got many time-trial records while only ever using a keyboard.

For vague or debatable suggestions, please use the forum.
