### ISSUE TITLE
can i translate thai

### ISSUE THREAD

**Issue by annopnod** [supertuxkart/stk-code#3911]
i am thai people
can i translate thai

**Comment by Benau** [comment]
you can join https://www.transifex.com/supertuxkart/supertuxkart/

**Comment by Benau** [comment]
https://supertuxkart.net/Translating_STK
I added the language Thai now and you can just login transifex with your github account, and then join the thai translation team.

**Comment by annopnod** [comment]
i can edit po file and upload after???

**Comment by Benau** [comment]
https://www.transifex.com/supertuxkart/supertuxkart/language/th/
Click supertuxkart.pot

And then click upload file

And not sure deve mind 1.4mb thai font lol

**Comment by Benau** [comment]
why do you use google translate for stk thai translation ![](https://cdn.lihkg.com/assets/faces/pig/shocked.gif)

also why do you add \n (newline) to some of the translation... it's not necessary and destroying the ui.... ![](https://cdn.lihkg.com/assets/faces/lm2/abomb.gif)
