### ISSUE TITLE
Many textures white with Android SuperTuxKart 1.0 on Sony Xperia XZ1 Compact

### ISSUE THREAD

**Issue by Alex-Esko** [supertuxkart/stk-code#3913]
Thank you very much for resurrecting this fond game.

## Description
Many textures are shown white on Xperia XZ1. With a Galaxy Tab A 2016 and the same source everything is fine.

## Steps to reproduce
Start game, enter single player. The eagle holding the traffic light is all white. In level "Nessis Teich" some textures are missing altogether. Shading is fine.
Regardless of graphic details.

## Configuration
STK release version: 1.0
STK Source: F-Droid
System: Android 9.0 running on Sony Xperia XZ1 Compact
Chipset: Qualcomm MSM8998 Snapdragon 835
Graphics card: Adreno 540
CPU: Octa-core Kryo

## Logfile
[stdout.tar.gz](https://github.com/supertuxkart/stk-code/files/3170675/stdout.tar.gz)

## Screenshots
![Screenshot_20190512-134953](https://user-images.githubusercontent.com/5099066/57588841-0cc03280-751b-11e9-877b-66ffbbe199fb.png)
![Screenshot_20190512-135013](https://user-images.githubusercontent.com/5099066/57588842-0f228c80-751b-11e9-950b-4e97ce035dc5.png)
![Screenshot_20190512-135029](https://user-images.githubusercontent.com/5099066/57588843-1184e680-751b-11e9-9935-e745e1a63629.png)
![Screenshot_20190512-135037](https://user-images.githubusercontent.com/5099066/57588846-19dd2180-751b-11e9-92b0-f57a90ddd06c.png)
![Screenshot_20190512-135128](https://user-images.githubusercontent.com/5099066/57588847-1e093f00-751b-11e9-971d-3142ee6727a3.png)

**Comment by Benau** [comment]
There is many cannot ```Cannot determine texture full path```...

Can u try to install stk from google play or install apk directly from https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.0/
?

**Comment by deveee** [comment]
Just a guess, but maybe you installed "broken" version with high quality assets (the apk was ~500MB) and then you made upgrade to current version, but it already found extracted assets in ```/storage/emulated/0/Android/data/org.supertuxkart.stk```, so it didn't extract it again. You can clean app data or delete ```/storage/emulated/0/Android/data/org.supertuxkart.stk/files/supertuxkart/data``` to force data extraction.

And maybe in future it should use some sum control rather than base on STK version number to make sure that correct assets are used.

**Comment by etam** [comment]
I have the same problem. I'm running LineageOS 14.1 (android 7.1.2) on Samsung Note 3 Neo (aka N7505).

I wiped whole `/storage/emulated/0/Android/data/org.supertuxkart.stk` and it didn't help.

I can't install armv7.apk from https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.0/ and  the installer says the package may be broken (md5 checksum is correct though).

**Comment by deveee** [comment]
To install the apk from sourceforge you need uninstall your current version first, because it's signed with different certificate.

**Comment by etam** [comment]
That did the trick! apk installed from sourceforge has no problems with textures.

I uninstalled it and reinstalled the updated one from F-Droid and it's also fixed, so there must be an issue that updated application did not fix previously unpacked broken files.

**Comment by Alex-Esko** [comment]
_Benau_ is right.
Deinstalling and reinstalling the game (also via F-Droid) solved the problem.

Improvement could be, like _deveee_ said, to use some sum control rather than base on STK version number if assets are correct.

**Comment by etam** [comment]
@Alex-Esko I think you should close the issue not when the cause is discovered, but when the solution is implemented.
