### ISSUE TITLE
Getting out of tracks into a "void"

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#392]
**Author: computerfreak97**

There is an issue with getting out of the tracks in just about all of the tracks. Setting as minor, but it is still an annoying and makes it look "unpolished"

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/336

**Comment by auriamg** [comment]
Closing this as too vague. More specific issues should be opened for each track where this issue exists, with screenshots of where it happens
