### ISSUE TITLE
Use description instead of numbers in font size spinner

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3923]
Extra small = 1
Small = 2
Medium = 3
Large = 4
Extra large = 5
Players may be cconfused with numbers. They may think they are absolute size in pixels (But they actually not).

**Comment by Alayan-stk-2** [comment]
Maybe there could be both numbers and texts.
1 - Very small
2 - Small
3 - Medium
4 - Large
5 - Very large
