### ISSUE TITLE
Cant Use nitro while turning left

### ISSUE THREAD

**Issue by fikrillah** [supertuxkart/stk-code#3924]
## Description
Cant Use nitro while turning left, it's either only nitro without turning or only turning left. but i can use nitro while turning right 

## Steps to reproduce
press nitro, and left in the same time

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): 

System: Archlinux

Graphics card: Nvidia 1060

CPU: ryzen 1400

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by loper12** [comment]
Try the latest version on git

**Comment by qwertychouskie** [comment]
@fikrillah 
From the FAQ:

Why don't some keyboard keys work when pressed simultaneously?

When playing with a keyboard, you may experience issues when pressing multiple keys simultaneously, for instance trying to use nitro while accelerating and turning. In such situations, some keypress may not register. This is however not a bug of SuperTuxKart, but a phyiscal limitation of your keyboard, most keyboards can only handle so many keys pressed at the same time ( for more detailed information, please check http://www.sjbaker.org/wiki/index.php?title=Keyboards_Are_Evil ). The solution is to use a gaming input device (gamepad, or gaming keyboard), or tweak the keys configuration to find keys that your keyboard will be able to register simultaneously.

Something that always seems to work for me is to shift the key assignments two keys to the left, so V is Nitro, C is look back, and X is skid.

@loper12 AFAIK the Git version doesn't have any changes is this regard.
