### ISSUE TITLE
In lobby, returning from character select menu does not allow re-entry to game

### ISSUE THREAD

**Issue by BlueCatYellowCat** [supertuxkart/stk-code#3932]
Steps to reproduce:

1) join lobby and wait until character select menu
2) press back button or Esc to return to lobby (maybe to read a chat message?)
3) attempt to rejoin game prior to start

Expected result: Be able to continue starting game.
Result: Cannot join game, can still spectate.

**Comment by Benau** [comment]
It's a feature sorry, see #3869

**Comment by BlueCatYellowCat** [comment]
Duplicate issue: #3932
