### ISSUE TITLE
supertuxkart donate page

### ISSUE THREAD

**Issue by annopnod** [supertuxkart/stk-code#3934]
change SuperTuxKart 0.9.3 to SuperTuxKart 1.0

![Screenshot from 2019-05-22 08-51-31](https://user-images.githubusercontent.com/6957642/58141818-e020bf00-7c6e-11e9-8061-130d4cdb450a.png)

can i  double purchased to donate it????

**Comment by Benau** [comment]
you help stk better by finishing thai translation!

**Comment by Benau** [comment]
![1](https://user-images.githubusercontent.com/3252341/59735242-612ba000-9287-11e9-8561-d46eab8dfa27.jpg)
And we will update it when we have new gift package
