### ISSUE TITLE
[LAN Game] History for recently entered IP addresses

### ISSUE THREAD

**Issue by Schwefelsaeure** [supertuxkart/stk-code#3937]
## Description

It would be useful if the menu "enter server IP address" would store the recently entered IP addresses so one can connect quickly to a server. See following GUI prototype:

<a href="https://ibb.co/0hhcbC4"><img src="https://i.ibb.co/0hhcbC4/STK-Prototype-IPHistory.png" alt="STK-Prototype-IPHistory" border="0"></a>

## Steps to reproduce

1. Start SuperTuxKart
2. Click "Online"
3. Click "Enter Server Address"

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): official binary

System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
It's done by 8add6fb ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
