### ISSUE TITLE
Many assets are wrongly raytraced

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#3938]
Don't raytrace tux's skin. It looks unrealistic.
![Screenshot_20190523_201252](https://user-images.githubusercontent.com/35170687/58252003-a7303980-7d97-11e9-91bb-adf645f5392a.png)
Autually Gavouroche has the same problem
The issue is for feature/raytracer-reflexion

**Comment by samuncle** [comment]
This is a known issue. The tux texture is probably set as metallic which then works as expected ^^. I will fix the textures now.

**Comment by samuncle** [comment]
# Karts that needs to be fixed:
Tux
Gaveroche
maybe hexley
Nolok (tires)
Sara (racer)

**Comment by dumaosen** [comment]
Also many trees in black forest, cocoa temple and rav mansion are raytraced

**Comment by CodingJellyfish** [comment]
Fixed a long time ago
