### ISSUE TITLE
Split Screen for 3 Players problem

### ISSUE THREAD

**Issue by TheUbunter7501** [supertuxkart/stk-code#3942]
Hello, Maybe this is not an error but I would like to know how I can independently adjust the split screen of 3 players that I like to split into 3 screens and not 4.
for an example I want to divide something like this:
https://i.ytimg.com/vi/9CKj6Khn4BY/maxresdefault.jpg
or this:
https://i.ytimg.com/vi/G7IRB47FwUU/maxresdefault.jpg

I hope you have a solution, I would appreciate it very much

**Comment by Benau** [comment]
See #2238
