### ISSUE TITLE
All background of dialogs are badly stretched

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3953]
It looks like this in 1024x768:
![Screenshot_20190607_225103](https://user-images.githubusercontent.com/35170687/59112972-bc4fbf80-8976-11e9-983a-3340713db661.png)
And like this in 3840x2160:
![Screenshot_20190607_225211](https://user-images.githubusercontent.com/35170687/59113045-e608e680-8976-11e9-81dc-0a933c070c55.png)

**Comment by qwertychouskie** [comment]
In the skins:
```
<!-- Stateless -->
<element type="window" image="modern/dialog.png"
      left_border="7" right_border="7" top_border="50" bottom_border="50"
      hborder_out_portion="1.0" vborder_out_portion="0.2" />
```
Changing 50 to 7 on the top and bottom "fixes" this, but then that section looks pretty pixelated.  I'll see if I can fix it in my theme branch.

**Comment by dumaosen** [comment]
@qwertychouskie It looks pixelated because it's stretched.
In someways just increase the resolution of dialog.png can fix this.
Anyway pixelated is often better than now it looks
