### ISSUE TITLE
Some track can't see start when it is reverted

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3954]
![Screenshot_20190607_225547](https://user-images.githubusercontent.com/35170687/59113325-67607900-8977-11e9-9bf5-c90e8ded57cc.png)
![Screenshot_20190607_225646](https://user-images.githubusercontent.com/35170687/59113422-8959fb80-8977-11e9-921b-ab5f5834e724.png)
![Screenshot_20190607_225749](https://user-images.githubusercontent.com/35170687/59113479-b0b0c880-8977-11e9-9176-067a504cc465.png)
![Screenshot_20190607_225854](https://user-images.githubusercontent.com/35170687/59113555-d5a53b80-8977-11e9-9ad7-297b4aac51bd.png)

**Comment by lecturegiver** [comment]
Checking in

**Comment by Benau** [comment]
All are fixed
