### ISSUE TITLE
fribidi.lib and freetype.lib wrong named for windows

### ISSUE THREAD

**Issue by Mrxx99** [supertuxkart/stk-code#3962]
## Description
when building I get the errors fribidi.lib an freetype.lib not found because they are named libfribidi.lib and libfreetype.lib in the dependecies folder

## Steps to reproduce
Try to build latest version with latest dependencies on windows (64 or 32 builds)

**Comment by Benau** [comment]
It should work if u remove your build folder completely and re-config with cmake (try?)

**Comment by Mrxx99** [comment]
removing build folder seemed to fix that, thanks

**Comment by Sabu100** [comment]
Okay thank you
