### ISSUE TITLE
Activation link

### ISSUE THREAD

**Issue by szepeviktor** [supertuxkart/stk-code#3963]
Hello!

My activation link is

`https://online.supertuxkart.net/register.php?action=valid&num;=RNLTcZ8J8WKW&user=162155`

it contains an invalid semicolon, after removing it activation succeeded.

**Comment by Sabu100** [comment]
your WhatsApp number pls

**Comment by szepeviktor** [comment]
I have no WhatsApp account, I've registered in-game.

**Comment by Sabu100** [comment]
Ok dear..

**Comment by szepeviktor** [comment]
Got it!!

The HTMl part of the email:

```html
 0; padding: 0 0 20px;" valign=3D"top"> <a href=3D"https://online.supertuxk=
art.net/register.php?action=3Dvalid&num=3DRNLTcZ8J8WKW&user=3D162155" class=
```

The ampersand is not HTML-encoded in the email -> my webmail "corrected" it.

Please do encode `&` in HTML.

**Comment by Sabu100** [comment]
If u have WhatsApp ican send

**Comment by szepeviktor** [comment]
I do not need activation, it is already activated.
I'm reporting the bug.

**Comment by Suprianto365** [comment]
Say hello

**Comment by leyyin** [comment]
First of all this email thread is super weird.
Second of all what webmail are you using?

**Comment by szepeviktor** [comment]
Horde.
pls see https://github.com/supertuxkart/stk-code/issues/3963#issuecomment-502474587

**Comment by leyyin** [comment]
This is a bug in that software, sorry but every other webmail interprets the email as it should.

**Comment by szepeviktor** [comment]
I think encoding ampersand as `&amp;` could solve it.
