### ISSUE TITLE
run_game.sh doesn't quote command-line arguments

### ISSUE THREAD

**Issue by programmerjake** [supertuxkart/stk-code#3964]
in the official version of supertuxkart 1.0 for linux, run_game.sh doesn't quote the command line arguments when passed to the actual binary, causing arguments that contain spaces to be split into multiple arguments.

I couldn't locate the source code for run_game.sh in git, so couldn't see if the bug is fixed in the latest git version.

```bash
"$DIRNAME/bin-64/supertuxkart" $@
```
The correct code would be
```bash
"$DIRNAME/bin-64/supertuxkart" "$@"
```

**Comment by deveee** [comment]
Will be fixed in next release, thanks.

**Comment by programmerjake** [comment]
mind posting the commit that fixes it?
Thanks

**Comment by deveee** [comment]
This file is not available in the repo, but I already fixed it locally.
