### ISSUE TITLE
Showing flags for bots in offline mode

### ISSUE THREAD

**Issue by adevairhpj** [supertuxkart/stk-code#3967]
![Screenshot_20190620_192929](https://user-images.githubusercontent.com/44653153/59950550-46eaf100-9444-11e9-8e73-f0e7671cce12.png)

**Comment by Benau** [comment]
Hmm probably the country flags in remotekartinfo should be clear after u played online...

**Comment by Benau** [comment]
try again canal? (lol)

**Comment by adevairhpj** [comment]
Bug fixed :)
