### ISSUE TITLE
Sending arabic text to the server's chat

### ISSUE THREAD

**Issue by Su20ma** [supertuxkart/stk-code#3973]
## Description
Sending Arabic text in chat inverses the chat and is a possible security threat.

## Steps to reproduce
1. Join a multiplayer server.
2. Have some messages in the chat.
3. Send a message containing only arabic text.
4. observe as the chat is flipped upside down.

## Configuration

STK release version:  0.10
STK Source: Official binary 
System: Arch
Graphics card: AMD Topaz XT Radeon R7 M440 
CPU: Intel Core i7-6500U

## Additional information
[stdout.log](https://github.com/supertuxkart/stk-code/files/3330547/stdout.log)

**Comment by Benau** [comment]
try git version?

https://streamable.com/zosr9

**Comment by Su20ma** [comment]
Looks fixed and the arabic text appear normal(connected and RTL). Is the official binary compiled with the fribidi library support?

**Comment by Benau** [comment]
The current 1.0 version has limited RTL supports

Next version will be even with harfbuzz + fribidi + libraqm!
