### ISSUE TITLE
The background layer in end race screen is applied above the text instead of below

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#3978]
Confirmed with both coal and ruby skins.

Instead of enhancing the contrast as intended by giving a more consistent background, this reduces it.

![BrokenUI](https://user-images.githubusercontent.com/25536748/60341674-99319200-99af-11e9-8560-fa0f9140d2b6.png)

**Comment by qwertychouskie** [comment]
I also reported this a few days ago on IRC: 

![](https://imgur.com/RHJv6bd.png)

It seems to have happened within the past week or 2.
