### ISSUE TITLE
Incorrect capitalization of "Nessie's pond"

### ISSUE THREAD

**Issue by LoadingPleaseWait** [supertuxkart/stk-code#3979]
The "p" in "Nessie's pond" should be capitalized. Nessie's Pond is a proper noun so the first letter in each word should be capitalized. Also, the current capitalization of the track is inconsistent with the capitalization of other tracks.

**Comment by Benau** [comment]
Fixed in svn, and lol I cannot connect to your super sweet Dallas server with my phone because you don't enable port forward!

**Comment by AndetSTK** [comment]
Also, "Around the lighthouse" and "Ravenbridge mansion" seem to have the same issue (should be "Around the Lighthouse" and "Ravenbridge Mansion").
