### ISSUE TITLE
Supertuxkart crashes when clicking exit in kart selection in story mode

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#3982]
![图片](https://user-images.githubusercontent.com/35170687/60390703-0f98d600-9b0f-11e9-8a7c-9e19ae4ddd64.png)

**Comment by Benau** [comment]
...i cannot reproduce,,, auria can you?

**Comment by Alayan-stk-2** [comment]
I cannot reproduce either.

**Comment by Benau** [comment]
Because here in main main screen: (can be reproduce by starting overworld with a locked kart)
```
            const std::string default_kart = UserConfigParams::m_default_kart;
            if (player->isLocked(default_kart))
            {
                KartSelectionScreen *next = OfflineKartSelectionScreen::getInstance();
                next->setGoToOverworldNext();
                next->setMultiplayer(false);
                StateManager::get()->resetAndGoToScreen(next);
                return;
            }
```
So getCurrentScreen() will be null if u press escape on the kartselection screen next, not sure auria thinks next->push(); is enough lol!
