### ISSUE TITLE
No sound in the recording

### ISSUE THREAD

**Issue by 4rLeQu1** [supertuxkart/stk-code#3985]
## Description

Hello everyone, I have a problem with video recording in the game. I use the mod debug to do this. Recording the video while I play doesn't cause any problems. By watching the recording (in mkv), the video and well but no sound.  However in the file "config" music and sfx are activated (true). Why is there no sound? I made a winrar archive with the result of the video recording and photos from the "config" file. link: https://www.mediafire.com/file/erckxu8q6kqz4e0/record_sound.rar/file

## Steps to reproduce

Nothing

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): 
Supertuxkart 1.0 fullgame 64 bit 

System:

Graphics card:

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Can u paste your stdout.log in .config/supertuxkart/config-0.10 when u are recording? And do u have pulseaudio on?

**Comment by 4rLeQu1** [comment]
pulse audio ? These an option ? I don't know, I have several "stdout.log" files (3).

**Comment by TARIKPHON85** [comment]
Désolé, c'est involontaire, merci Envoyé de mon iPhone

**Comment by 4rLeQu1** [comment]
Pas grave, as tu un problème similaire ?

**Comment by gouaic** [comment]
Non, j'espère que ce n'est pas un problème, merci beaucoup, je peux communiquer avec vous, en rupture d'activité, merci encore
Envoyé de mon iPhone

Le 3 juil. 2019 à 01:51, 4rLeQu1 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pas grave, as tu un problème similaire ?

**Comment by Benau** [comment]
They are spam, not sure auria can enable only >24 hours account can comment...

And can you make a recording, after that can you upload the stdout.log?

**Comment by Mrxx99** [comment]
For me on two Windows PCs there always wa no sound on recordings so I assumed it is noz implemented to have sound.
You are talking about the included recorder in STK, right?

**Comment by 4rLeQu1** [comment]
Yes, I'm talking about the recorder included in the game. After a registration I can't download "stdout.log".

**Comment by Benau** [comment]
You can paste the content of stdout.log here after u have recorded the video

**Comment by TARIKPHON85** [comment]
Okey , thanks for that

Envoyé de mon iPhone

**Comment by 4rLeQu1** [comment]
When a video recording and create there is a file "stdout.log" that this create. This file and the audio of the recording? If so, paste the content of "stdout.log" or, in the record? How to copy the content of "stdout.log", on my pc the file cannot be executed.

**Comment by gouaic** [comment]
I did not understand the meaning well, could you explain to me the pictures if possible,

Envoyé de mon iPhone

Le 4 juil. 2019 à 00:21, 4rLeQu1 <notifications@github.com<mailto:notifications@github.com>> a écrit :

When a video recording and create there is a file "stdout.log" that this create. This file and the audio of the recording? If so, paste the content of "stdout.log" or, in the record? How to copy the content of "stdout.log", on my pc the file cannot be executed

**Comment by Benau** [comment]
Then you can just use another recording to record stk
