### ISSUE TITLE
Losing against Nolok shows "You completed a challenge!"

### ISSUE THREAD

**Issue by MiroslavR** [supertuxkart/stk-code#3988]
## Description

I lost against Nolok and the UI showed the "You completed a challenge!" button instead of "Restart" and "Go back" at the end of the race. Upon clicking it the treasure chest unlocking cutscene was shown, revealing a golden cup. I was then taken back to the Overworld. Neither the ending cutscene, nor credits were shown and the minimap did not mark the challenge as completed either.

## Steps to reproduce

1. Lose against Nolok when the challenge is not yet completed.
2. Observe the UI at the end of the race acting as if you completed the challenge.

## Configuration

STK git version: 0de1a41c5a5a3b002a0583da343646d80dfa9116

**Comment by MiroslavR** [comment]
Hmm, I can't reproduce this again if I remove completion from `players.xml`. This might not even be related to the Nolok challenge. But there is definitely a bug somewhere.

**Comment by MiroslavR** [comment]
Looking at the code, this could happen if some previous challenge did not clear recently completed challenges (by calling `PlayerManager::getCurrentPlayer()->clearUnlocked();`).

**Comment by 15388734337** [comment]
> ## 描述
> 我输了Nolok，用户界面显示“你完成了挑战！” 在比赛结束时按钮而不是“重新启动”和“返回”。点击它后，显示了一个展开金杯的宝箱解锁过场动画。然后我被带回了Overworld。既没有显示结束过场动画，也没有显示出积分，小地图也没有将挑战标记为已完成。
> 
> ## 重现步骤
> 1. 当挑战尚未完成时，对Nolok失利。
> 2. 在比赛结束时观察用户界面，就像您完成了挑战一样。
> 
> ## 组态
> STK git版本：[0de1a41](https://github.com/supertuxkart/stk-code/commit/0de1a41c5a5a3b002a0583da343646d80dfa9116)

**Comment by CodingJellyfish** [comment]
Not reproducible

**Comment by Alayan-stk-2** [comment]
Maybe it has been fixed when trying to correct some issues, but I don't think so.

At least this possibility requires investigation:

> Looking at the code, this could happen if some previous challenge did not clear recently completed challenges (by calling `PlayerManager::getCurrentPlayer()->clearUnlocked();`).

**Comment by Alayan-stk-2** [comment]
After investigation, I think this has been fixed. Probably in an old commit like https://github.com/supertuxkart/stk-code/commit/71fec6780cb2d4f0d794096011497a4774ffb0fc, although I haven't tested old versions to confirm when exactly this happened.
