### ISSUE TITLE
Crash when use twin generic joystick

### ISSUE THREAD

**Issue by Nokia808** [supertuxkart/stk-code#3990]
## Description

When using generic twin joystick in multiplayer local mode, the game is crashed during gaming between 2 game. It seem that there is a key combination on such joystick that lead to such crash.

## Steps to reproduce

Play using local multiplayer mode with generic twin joystick

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): flatpak package from FlatHub / but also on official Fedora repository .rpm package

System: Fedora Linux 30 X64 Cinnamon edition

Graphics card: 
game configured to use hybrid VGA (Intel Corporation HD Graphic 5500 + Radeon R7 M265 2GB)
CPU: 
Intel core i7 5500 CPU @ 2.40 GH X 2
Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log: I do not when I locate it in flatpak installation from FlatHub
```

```

input.xml:
```xml

```

Error message: no error message at all ! Game crash suddenly. This issue is very old, since I was on Fedora 24, my 1st start with Linux.
```

```

**Comment by auriamg** [comment]
Do you think you could run stk in a debugger (gdb) and get us a backtrace?

```
gdb supertuxkart
run
... make it crash ...
bt
```

**Comment by deveee** [comment]
I did some tests simulating two the same gamepads and I didn't have any issues. The only "strange" thing I noticed is that in options there is "Device name (x2)" and you can't configure each gamepad separately. So maybe the crash is not related to gamepad names, but there is different reason.

**Comment by Alayan-stk-2** [comment]
Please open a new ticket if the issue persists in STK 1.2 In the meantime, I'll close this as not applicable anymore as we now rely on SDL2 for gamepad handling.
