### ISSUE TITLE
Sound while flying

### ISSUE THREAD

**Issue by Anard** [supertuxkart/stk-code#3991]
Description
When kart is flying, the sound of the road below continues.
For example in Gran paradisio island, when taking the short way on right, the kart flies a moment above wooden bridge and we hear the bridge's sound.

Little strange…
No sound would be better. Why not a special sound when flying.

**Comment by Mensious** [comment]
Yes! i see that. But it's not better no sound, it will be better to sound of Air or something.

**Comment by Alayan-stk-2** [comment]
Duplicate of #3837
