### ISSUE TITLE
Game won't load STK 1.0 and 0.9

### ISSUE THREAD

**Issue by luisvallejomohl** [supertuxkart/stk-code#3993]
## Description

I'm an ex-0.7 user, and I upgraded my STK to 1.0, but the tracks won't load. The GUI(i.e. the setup screen and options and addon control etc.) loads, but as soon as I try to use the tracks, it will show the loading screen, and the sounds play, but the track will never load. I tried 0.9, and I got the same problem, but when I used 0.8, it well and truly worked.

## Steps to reproduce

[Recording of problem](https://www.loom.com/share/d1021a94f6214a9d881d3153f68f2f28)
 - Install STK 1.0 or 0.9 using SourceForge
 - Restart computer
 - Open STK 1.0 or 0.9
 - Open Story Mode
 - Music will play, but the game won't load

## Configuration

STK release version: 
Issue in 1.0 and 0.9, works fine in 0.7 and 0.8

STK Source: SourceForge

System: Windows 64-Bit

Graphics card: NVIDIA® GeForce® MX230 graphics
CPU: Acer PC Aspire 38th Gen Intel® Core™ i7 processor
## Additional information

Video of problem: https://www.loom.com/share/d1021a94f6214a9d881d3153f68f2f28

**Comment by Benau** [comment]
do you have msvc debugger installed?

**Comment by Benau** [comment]
For quick fix you can try to edit %appdata%\supertuxkart\config.xml, edit force_legacy_device to = "true" instead

**Comment by Benau** [comment]
or you can try force supertuxkart to use the nvidia gpu instead of intel igpu,,,,

**Comment by 15388734337** [comment]
怎么处理

**Comment by luisvallejomohl** [comment]
> For quick fix you can try to edit %appdata%\supertuxkart\config.xml, edit force_legacy_device to = "true" instead
I tried to do do that, but apparently config.xml doesn't exist. How do you do the other methods?

**Comment by qwertychouskie** [comment]
Sorry, the correct path is `%appdata%\supertuxkart\config-0.10\config.xml` for version 1.0 (or `%appdata%\supertuxkart\0.8.2\config.xml` for version 0.9.3 or below).  Also, if you could post the output of `%appdata%\supertuxkart\config-0.10\stdout.log` after reproducing the issue that would be helpful.

**Comment by luisvallejomohl** [comment]
Thank you Benau and qwertychouskie! It now works!
