### ISSUE TITLE
Default to Nvidia GPU on Optimus systems

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#3996]
From http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf:

### Global Variable NvOptimusEnablement (new in Driver Release 302)

Starting with the Release 302 drivers, application developers can direct the Optimus driver at runtime to use the High Performance Graphics to render any application–even those applications for which there is no existing application profile. They can do this by exporting a global variable named NvOptimusEnablement. The Optimus driver looks for the existence and value of the export. Only the LSB of the DWORD matters at this time. A value of 0x00000001 indicates that rendering should be performed using High Performance Graphics. A value of 0x00000000 indicates that this method should be ignored.

**Example Usage:**
```
extern "C" {
    _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
}
```
_________________________________________________________________________
It might not work for all drivers/OS versions, but IMO it's worth having since it's a pretty small change.

**Comment by qwertychouskie** [comment]
There's also an AMD equivalent (https://stackoverflow.com/a/28179913):
```
extern "C"
{
    __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
}
```

**Comment by deveee** [comment]
The solution for nvidia works for me, so I already added it:
https://github.com/supertuxkart/stk-code/commit/fd3a2099bc2991244e45d51cf38d4a946a3c82ea

I have no possibility to test amd.

**Comment by Alayan-stk-2** [comment]
I can't test it either. Is there a reason to believe the stackoverflow taken as is could cause any issue ?

**Comment by Alayan-stk-2** [comment]
Another issue could be opened about the AMD part. Optimus is by far more common on laptops, however.

I'm marking this as done for 1.1.
