### ISSUE TITLE
Game depends on Nettle 6 not available on libnettle 3.5.1

### ISSUE THREAD

**Issue by Su20ma** [supertuxkart/stk-code#3998]
## Description
Games depends on Nettle_6 but the new libnettle 3.5.1 only provides Nettle_7, Some rolling release distros already shipped libnettle 3.5.1 which means anyone using those has to compile their own version of libnettle.

**Comment by Benau** [comment]
Actually you can use openssl as crypto backend for now(USE_CRYPTO_OPENSSL), as in the future it's apache2 anyway.

I will tell you details later as there could be some license change to stk too.

**Comment by Benau** [comment]
Now it's default to openssl now (nettle in stk-code will soon be removed)

**Comment by james165527** [comment]
Open #165527

*Yours sincerely,*
Mark James Agripo.

**Comment by james165527** [comment]
https://www.programmingsimplified.com/java/source-code/java-if-else-program


*Yours sincerely,*
Mark James Agripo.

**Comment by james165527** [comment]
https://www.w3schools.com/java/java_conditions.asp

https://www.jquery-az.com/java-if-else-if-and-else-statements-explained-with-5-examples/

*Yours sincerely,*
Mark James Agripo.

**Comment by james165527** [comment]
*Yours sincerely,*
Mark James Agripo.
