### ISSUE TITLE
Karts not visible in game

### ISSUE THREAD

**Issue by VcDoc** [supertuxkart/stk-code#4010]
## Description
The karts are visible in the menu but not during the game. This seems bizarre as everything else is rendered properly, even the tires on the karts. I can still play the game without any probs, but without the karts there, it is not very fun.

## Steps to reproduce
I just downloaded the game and ran it. When I started playing the carts weren't there so I experimented with multiple graphics configurations but the issue is still there

## Configuration

STK release version: The most recent one. 1.0.0

STK Source (PPA, distribution package, official binary, etc.): https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.0/SuperTuxKart%201.0%20installer-64bit.exe/download

System: Windows 10 v1903

Graphics card: Intel UHD 620

CPU: Intel i7-8550u

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log: [stdout.log](https://github.com/supertuxkart/stk-code/files/3402098/stdout.log)
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Try disable animated characters in setting?

**Comment by VcDoc** [comment]
It worked! Could anyone explain me why tho?

**Comment by Benau** [comment]
Maybe your GPU doesn't like texture buffer hardware skinning, maybe we can try using rgba texture for all platform lol deve!

I will publish a test binary for you later so you can test if it can be fixed

**Comment by deveee** [comment]
Texture buffer can be disabled by using ```<card disable="TextureBufferObject"/>``` in graphical_restrictions.xml. It's already disabled for nouveau.

And +1 for using rgba texture, because simple features seem more stable in drivers. And less difference between GL and GLES is better. In theory tbo should be slightly faster, but I didn't notice any performance difference.

**Comment by Benau** [comment]
So VcDoc can you edit in your ...program files/supertuxkart/data/stk_config.xml and change <card disable="TextureBufferObject"/> like deve said and reenable character animation?

**Comment by VcDoc** [comment]
I did as you guys said and the kart was showing in the race, but mid-race it became invisible again. It keeps coming back after a while but it disappears quickly. Maybe I did something wrong?

**Comment by VcDoc** [comment]
[Desktop.zip](https://github.com/supertuxkart/stk-code/files/3406621/Desktop.zip)
I have added the stk_config.xml and the graphical_restrictions.xml in the zip file

**Comment by xlf1024** [comment]
Can confirm: On internal graphics, at stk-graphics level 6, the cart was only visible in selection screen. After changing the graphics preset to 2, it worked (didn't test in between). After forcing the use of the dedicated graphics card in the Nvidia control panel and stk, the issue disappeared.

Hardware
HP Envy convertible laptop, integrated touchscreen
CPU: i5-8265
internal GPU: UHD Graphics 620
dedicated GPU: NVIDIA GeForce MX150

In case it helps: To my understanding, the screen is connected to the intel graphics only, i.e. the MX150 has to write to the intel card. However, this doesn't appear to be an issue here.

Are there special settings I could test for you? Meanwhile, I'm fine with using the MX150, where I haven't noticed any issues at stk's preset level 6 yet.

**Comment by PhamQuynh2** [comment]
https://dichthuattomato.com/dich-thuat-game-online-chuyen-nghiep-chuan-xac-tai-tomato-media/
