### ISSUE TITLE
Tabs appearence broken in the GP editor

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4011]
See picture below.

![GP_editor_tabs](https://user-images.githubusercontent.com/25536748/61397516-584fdd80-a8ca-11e9-9c72-daee8b9490ab.jpg)

Tested with 1.0 where it works as expected - tabs pointing below instead of above. I have not checked if this issue appears in other places of the UI.

**Comment by qwertychouskie** [comment]
I originally had a fix for this in https://github.com/supertuxkart/stk-code/pull/3992: https://github.com/supertuxkart/stk-code/compare/00d40f48243585bbae1962d76c85f5954df3d222..361e1617b3e21f6a5823e5f8623624cebae0c1d9, but @Benau wanted to work on a less-hackish solution.

The best way to fix this would be an override option in the XML to force a non-default flip direction, this way there should be no risk of regression.
