### ISSUE TITLE
Cannot find LAN server

### ISSUE THREAD

**Issue by MatejKovacic** [supertuxkart/stk-code#4014]
## Description

I have two computers and an Android phone connected to WiFi. On one computer I set up Online - Local Networking - Create Server. This machine has (LAN) IP 192.168.0.107 (running Ubuntu 18.04.2. LTS).
On this (server) machine I also open ufw firewall:
```
sudo ufw allow from 192.168.0.0/24 to any port 2757
sudo ufw allow from 192.168.0.0/24 to any port 2759
```
This machine also has tun0 device (VPN) connection, but the problem is the same if I shut down VPN and if I disable ufw firewall.

On the other machine ("client machine") I select Online - Local Networking - Find Server. And it says "No servers available".

However, if I go to Online - Enter server address, and enter 192.168.0.107:2759, I can start chat with other machine. But not a game.

In fact, I was able to connect to game server once but I am unable to find what exactly happened.

Anyway, this is console output from "client machine":

```
[info   ] Server Discovery: Broadcasting to 127.0.0.255:2757
[info   ] Server Discovery: Broadcasting to 192.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.0.255:2757
[info   ] Server Discovery: Broadcasting to 192.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.250.255:2757
[info   ] Server Discovery: Broadcasting to 192.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.122.255:2757
[info   ] Server Discovery: Broadcasting to 172.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 172.16.255.255:2757
[info   ] Server Discovery: Broadcasting to 172.16.1.255:2757
[info   ] Server Discovery: Broadcasting to 192.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.255.255:2757
[info   ] Server Discovery: Broadcasting to 192.168.158.255:2757
[info   ] Server Discovery: Broadcasting to 10.255.255.255:2757
[info   ] Server Discovery: Broadcasting to 10.10.255.255:2757
[info   ] Server Discovery: Broadcasting to 10.10.8.255:2757
[info   ] ServersManager: Sent broadcast message.
```
I can see there are several broadcast messages. This client machine has ufw enabled, and I have several network devices (please, don't ask :) ):

- anbox0 (192.168.250.1  netmask 255.255.255.0  broadcast 0.0.0.0)
- enp0s31f6 (not connected)
- lo (127.0.0.1  netmask 255.0.0.0)
- tun0 (10.10.8.11  netmask 255.255.255.0)
- virbr0 (192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
- vmnet1 (172.16.1.1  netmask 255.255.255.0  broadcast 172.16.1.255)
- vmnet8 (192.168.158.1  netmask 255.255.255.0  broadcast 192.168.158.255
- wlp61s0 (192.168.0.104  netmask 255.255.255.0  broadcast 192.168.0.255)

This is also my `ip route show`
```
default via 10.10.8.1 dev tun0 proto static metric 50 
default via 192.168.0.1 dev wlp61s0 proto dhcp metric 600 
10.10.8.0/24 dev tun0 proto kernel scope link src 10.10.8.9 metric 50 
10.10.9.0/24 via 10.10.8.1 dev tun0 proto static metric 50 
xx.xx.xx.165 via 192.168.0.1 dev wlp61s0 proto static metric 600 
169.254.0.0/16 dev anbox0 scope link metric 1000 
172.16.1.0/24 dev vmnet1 proto kernel scope link src 172.16.1.1 
192.168.0.0/24 dev wlp61s0 proto kernel scope link src 192.168.0.104 metric 600 
192.168.0.1 dev wlp61s0 proto static scope link metric 600 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.158.0/24 dev vmnet8 proto kernel scope link src 192.168.158.1 
192.168.250.0/24 dev anbox0 proto kernel scope link src 192.168.250.1 
```

OK, I assume it could be some network problem with my client machine, but Android device was also unable to find server. So I assume it is something else...

## Configuration

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): PPA

**Comment by Benau** [comment]
However, if I go to Online - Enter server address, and enter 192.168.0.107:2759, I can start chat with other machine. But not a game.

It's a feature that only the server owner can start the game(your .107 machine)

Does your phone connect too if you use the dialog too?

Also what happen if you type 192.168.0.255:2759 in dialog?

**Comment by MatejKovacic** [comment]
Yes, phone connects if I enter 192.168.0.107:2759 in the dialog, and we can chat, but not start a game.

And yes, I cannot connect to server, when server (owner) starts a server (and a game).

**Comment by Benau** [comment]
You need to wait for all players joined your server before click the button in servef

**Comment by MatejKovacic** [comment]
How do you mean that?

On a server I click Online - Local Networking - Create Server and then wait...

On a clients I select Online - Local Networking - Find Server?

I did that, but it says "No servers available"...

**Comment by Benau** [comment]
Use the dialog to enter server IP instead of find server button

Also have you tried 192.168.0.255:2759 in dialog?

**Comment by MatejKovacic** [comment]
Where is this dialog?

Online - Enter server address? Because (as I said), I entered 192.168.0.107:2759 there, and I can start chat with other machine. But cannot start a game.

![stk_online2](https://user-images.githubusercontent.com/3339198/61583895-0a8fdb00-ab3f-11e9-8995-8a73980f6f2f.png)

**Comment by Benau** [comment]
I say one last time, the enter ip dialog is a replacement for people when broadcast (using .255) doesn't work for them. So to make it playable for yourself please open a server and then replace the "Local Networking - Find Server" procedure with enter ip dialog. Don't start the game when your clients all-joined.

**Comment by Benau** [comment]
video https://streamable.com/d0u78

**Comment by TARIKPHON85** [comment]
Hellow 
I do not use any game for you, so I did not make any movement in your game, inserting the network mask is a big risk, for me ... Thank you in advance
Envoyé de mon iPhone
