### ISSUE TITLE
bowling ball boosts

### ISSUE THREAD

**Issue by tecan** [supertuxkart/stk-code#4016]
bowling balls because of size and inertia required when shot backwards should accelerate the karts. also slight(maybe not full weight) slowdown when shooting ahead to make gameplay more realistic. a bigger boost than normal may be preferred even. would integrate well with existing ai likely for visual appeal/functionality

**Comment by auriamg** [comment]
STK does not aim to implement realistic physics. This can be discussed I guess, but for STK it should be discussed on the grounds of whether it improves the gameplay, and not on the ground of whether the laws of physics are respected

**Comment by Alayan-stk-2** [comment]
Sorry, I'm not convinced it would fit well with the gameplay. Backward bowling balls are already powerful, and this complication for physics' sake would add a layer of confusion I think...
