### ISSUE TITLE
Support for more than 4 XBox controllers - Windows

### ISSUE THREAD

**Issue by supersmo** [supertuxkart/stk-code#4033]
## Description
Since XInput is used for XBox controllers in stk you are unable to use more than 4 of them on Windows. (XInput only supports 4 controllers and all XBox controllers are filtered from the DirectInput handling.) Since the game supports 8 local players it would be nice to have the possibility to disable XInput so the XBox controllers are accessed via DirectInput instead. Doing so would put the both triggers on the same axis (and no force feedback rumble support or detection of the guide button) but allow for more than 4 XBox controllers.

Although a hybrid XInput and DirectInput approach, where 4 XBox controllers are accessed via XInput and the rest are accessed via DirectInput is possible, it would be quite complex since there is no guarantee that the enumeration order is consistent across XInput and DirectInput and there is no way to get the hardware ID via XInput so one would have to do input correlation to figure out which controllers to filter out on the DirectInput side.

I've tested to compile stk with XInput disabled by changing:
https://github.com/supertuxkart/stk-code/blob/05684c92dc981b28f9d382e1e2434c0be7abe8d1/lib/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp#L149
to:
`activeJoystick.m_use_xinput = false;`
And was able to use more than 4 Xbox controllers so I have verified that it is possible.

My suggestion is to add an entry to stk_config.xml to add a possibility to disable XInput from there. e.g.
`<input use-xinput="true"/>`

**Comment by Benau** [comment]
we will switch to sdl2 for gamepad so this will not fixable...

or you are the same person in https://discourse.libsdl.org/t/supporting-more-than-4-xinput-capable-devices-on-windows-rfc/25666/5 ?

![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Benau** [comment]
actually we can use SDL_SetHint(SDL_HINT_XINPUT_ENABLED, "0"), maybe just an environment variable?

I don't really want to add some option that just specific to windows user, and not even a lot of windows user need to use more than 4 gamepad anyway

....let hope deve is safe from chinese virus lol!

**Comment by Benau** [comment]
https://github.com/spurious/SDL-mirror/commit/855a56085544014440407895a14d3a097273a404 seems that fixed in latest sdl!

**Comment by 7wells** [comment]
Hello, this is my first comment on GitHub ever, so please accept my apologies if this is maybe not to the point ot the wrong place to ask:

How can do many players (more than 4 on STK on Windows) play at the same time?

Or is it, so >4 players can only be discerned by their controllers, as their usernames are "connected" to their respective controllers?

Sorry for my dumb question, but else I wonder why so many controllers could be needed. Thanks for helping me understanding this. 😀

**Comment by Benau** [comment]
8 players
http://blog.supertuxkart.net/2018/08/summer-update.html

Probably you need more than 4 controllers

**Comment by 7wells** [comment]
Ah, thanks for the hint! 👍

**Comment by Benau** [comment]
@supersmo can you try https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210504-win.zip ? (notice the date may got "renewed" later, so just go releases page and download latest preview win.zip)

It uses SDL2 2.0.14 and should support more than 4 controllers (according to https://discourse.libsdl.org/t/sdl-2-0-14-released/28470) ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by supersmo** [comment]
I tested now. It didn't support more than 4 XBox controllers out of the box.
Not sure why it doesn't work. According to that documentation regarding features in 2.0.14 it looks like it should have worked considering the default values of the new flags. (Not sure about SDL_HINT_JOYSTICK_HIDAPI_XBOX flag maybe that needs to be activated to make use of the new feature.)

However, since it's using SDL2 now I can force it to disable XInput by creating the environment variable `SDL_XINPUT_ENABLED=0` and with that set I can use 8 XBox controllers with the limitations of XBox controllers under DirectInput/RawInput (Can't use both triggers at the same time and force feedback won't work and guide button doesn't work.

The new features sounds like it should fix those limitations via  SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT.

I tried fiddling with these environment variables (not 100% sure the variables can control the flags):
SDL_JOYSTICK_RAWINPUT=1  (should be the default already)
SDL_JOYSTICK_HIDAPI_CORRELATE_XINPUT=1  (should be the default already)
SDL_JOYSTICK_HIDAPI_XBOX=1  (not sure if this would be needed. default is 0)

But they didn't seem to have any effect since the game only picks up 4 controllers when SDL_HINT_XINPUT_ENABLED=1.

(I could try to set the flags in the TuxKart code and compile just to be sure that they are actually set but life is hectict at the moment so I don't know when I'd get around to it.)

**Comment by supersmo** [comment]
I just tested something that fixed it! 
I downloaded the official SDL2.dll for windows 64 bit and replaced the one in `.\stk-code\build-x86_64\bin` and it worked!
Are you by chance compiling an SDL2.dll from source? I'm suspecting some flags are messed up compared to the defaults for Windows.
Anyhow if you just use the SDL2.dll from here https://www.libsdl.org/release/SDL2-2.0.14-win32-x64.zip supertuxkart works with 8 XBox controllers out of the box.

**Comment by Benau** [comment]
We compile it with github actions ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

Turns out that cmake file of sdl2 doesn't do the RAWINPUT define, so i ```sed -i 's/#define SDL_JOYSTICK_XINPUT 1/#define SDL_JOYSTICK_XINPUT 1\n#define SDL_JOYSTICK_RAWINPUT 1/g' include/SDL_config.h``` myself ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif)

Can you try this dll? (strings SDL2.dll |grep RAWINPUT shows something as the official dll) ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif)

[sdl.zip](https://github.com/supertuxkart/stk-code/files/6431649/sdl.zip)

**Comment by Benau** [comment]
@supersmo in case you missed the previous message....

**Comment by supersmo** [comment]
Sorry for the slow feedback loop. I've downloaded the latest prevew build and replaced the SDL.dll with the SDL build you linked to and it works! 👍

**Comment by Benau** [comment]
good ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

Now @auriamg can you try that too to see if it will affect the gamepad names... (i hope it doesn't make your xbox gamepad becomes xxxx/yyyy again....)

**Comment by Benau** [comment]
we ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) https://github.com/supertuxkart/dependencies/commit/a7627b9b4b7f04559d5bad41874449806493e0e9 so all builds later will use that new dll, you can see if https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210514-win.zip works for you ![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

**Comment by 7wells** [comment]
@Benau 
The link seems to have been changed. I.e. for me, it does not work, but this one leads to the right direction:
https://github.com/supertuxkart/stk-code/releases/

What's the difference between these two?

SuperTuxKart-git20210514-switch.zip
SuperTuxKart-git20210514-win.zip

**Comment by Benau** [comment]
switch is for homebrew of switch console and win for windows

That link is downloadable for me
