### ISSUE TITLE
Moving to Blender 2.8

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#4034]
**Blender 2.8 was released a few days ago and I'm using it daily to see what it implies for our game.**

So far there are two major changes that affect us.
* 2.7x Addons aren't compatible.
* The complete removal of texture viewport, now everything regarding materials is done with nodes.

The good news is we can now define in Blender custom shader easily and it will probably simplify addons, since we can get rid of the custom panel for the texture materials.

eg: The current main shaders of SuperTuxKart implemented in Blender.
![Screenshot_20190806_215509](https://user-images.githubusercontent.com/6406045/62572922-22809200-b895-11e9-883e-40730cc6911f.jpg)

**1) Geometry, Materials and shaders**
* Each object needs to be exported with a reference to the material **and not the texture.**
* There is a blender in the media repository containing premade Blender shaders corresponding to our SuperTuxKart Shaders.
* You can link those shaders in your Blend
* You select your object, add a new material and set one of the premade shaders.
* You put whatever textures in the slot of the material.
* You get a similar result in Blender and in game.
* At export, the script check that to make sure slots have only a texture and not other nodes (since stk doesn't support node shader).
* The script writes the name of the material, the name of the shader used by the material and fill up the texture slots with the name of the textures specified by the user.

This allows a very nice flexibility since you can have one texture used in different materials (current not possible in SuperTuxKart, without copy pasting the texture.
This also integrate nicely with Blender.

**2) Physic properties**
* We still need to define properties for the physic/gameplay (friction, reset, etc).
* Those should be defined in materials not in the textures. We can still define custom properties in the material panel.

As with the shaders it allows to have two materials with the same texture and different physical properties.

**3) Converting old tracks**
This is one of the big issue and a major endeavor.

* Currently the easiest is to do this for karts since they are pretty much self contained Blend files.
* I have converted one of the karts to Blender 2.8 file so we can experiment with.
* It's actually not so hard to convert, and the result is really pleasant (you see much better what you are doing since we have the shaders of SuperTuxKart in blender).

I would say once we have the prototype of the new exporter, we can have script that:
* Take the textures and convert them to materials
* Copy the properties from the textures to the material panel.
* All other scene properties are actually in the same location they don't need specific changes.

If you want to experiment with Adiumy converted to Blender 2.8. Be aware that I removed the XMAS hat for now.

[adiumy.zip](https://github.com/supertuxkart/stk-code/files/3474043/adiumy.zip)

**4)But why doing this?**
Well first of all old versions of blender will be quickly unsupported and therfore we need to be sure to be compatible with the newest blender. The other very rewarding part is we can get an almost one / one view and directly see in blender how it will look in supertuxkart.

![Screenshot_20190806_224551](https://user-images.githubusercontent.com/6406045/62576034-50b5a000-b89c-11e9-9045-deceb9024eb7.jpg)

**Comment by samuncle** [comment]
So I started work on exporting materials. https://gist.github.com/samuncle/883491b8f875a74cfaefc13c2c763355

What is working:
The exporter will look for one of the premade shader group. It then goes through all texture slots (for color/vec3D input) and simply put the name of the texture in one of the STK texture slot.

Float are simply added as additional XML parameters.

Be aware THIS ISN'T to export physical properties of the terrain (like skidding particles, etc). This will be handled outside of the shader graph.

`<material> name="Material" shader="stk_pbr_shader" tex-layer-0="adiumy.jpg" tex-layer-1="adiumy.jpg" tex-layer-2="adiumy.jpg" colorization-factor="0.5887781381607056" </material>
`

**Comment by samuncle** [comment]
I just updated my script prototype. So far I bypassed the XML properties from stk_data because I think we can have more flexibility by implementing the UI in the code.

It also separate cleanly the interaction from the shader properties.

**Comment by samuncle** [comment]
I have a question @Benau or @auriamg 

What is the difference between the following material properties: 
* Reset kart (on drive) (whether to rescue kart if it ends up [driving] on this surface)
* How to react when kart touches this material (Rescue kart)

To me they look exactly the same. Any information?

**Comment by samuncle** [comment]
Okay so many properties are ported now for materials. They are located in the material panel (since textures where removed). All the names are the same.
![ supertuxkart28](https://user-images.githubusercontent.com/6406045/63211115-40e75880-c0f3-11e9-84a0-e6e272e2c20e.jpg)

I did however one change was to reorganize the panel into sub sections so you don't have to have all the properties open at the same time. They are grouped under 3 sub panel

Shader properties (things that can't be done in nodes for now)
Visual and Sound properties (for particles & sound effect)
Gameplay / Interaction (for all the interactive stuff (like collision, gameplay, etc).

The ground work is almost finished. The format of the material.xml shouldn't change much but we should check whatever we need/are still using all properties.

**Comment by auriamg** [comment]
> * Reset kart (on drive) (whether to rescue kart if it ends up [driving] on this surface)
> * How to react when kart touches this material (Rescue kart)

Only hiker would know the details for sure I think, it's a physics implementation thing. IIRC one detects "kart driving on material" (for ground, rougly speaking), and the other detects collisions (for walls, rougly speaking). In the physics engine those are different apparently

**Comment by qwertychouskie** [comment]
Pretty sure this is correct.  (In general, resetting objects should always have both selected, otherwise the kart e.g. won't reset if hitting the surface sideways instead of normally.)

**Comment by will-ca** [comment]
Hiker provided some potential details on the resets years ago in #1483:

> ...we have two kind of resets: one that is triggered on collision of the chassis with an object, the second one on driving on a specific terrain (i.e. texture)...

> ...(the raycast detecting the terrain is only done against the main track mesh, not against all physical bodies like your plane. The wheels on the other hand test collision against anything)...

How I interpreted these two options was that the "Reset on Drive" option would be tied to **driving** physics— I.E. it would be triggered if all the wheels were on the ground and the kart counted as "driving" on the surface (such as for being able to turn, the wheel animations, experiencing the slowdown effect, etc)— whereas "Reset on Touch" option would be tied to **rigid body** physics— I.E., being triggered if there was any intersection at all between the collision hulls of the kart and the affected polygons.

IIRC, there's also a third rest option that applies specifically to independent meshes/objects.

**Comment by Sockstah** [comment]
Since Blender's principled shader expects a color image for emission but STK uses grayscale I edited the group in the Adiumy example a little.
I also put the normalmap conversion in there just because it makes sense to be able to just plug the normal map directly into the shader.

![Screenshot_20191001_155949](https://user-images.githubusercontent.com/29517971/65971182-1580b900-e468-11e9-8a24-a19b1a97d738.png)

[adiumy.zip](https://github.com/supertuxkart/stk-code/files/3676867/adiumy.zip)

**Comment by james165527** [comment]
tell me your secret dude ! I'm listening ..
*Yours sincerely,*
Mark James Agripo.

**Comment by Benau** [comment]
blender 2.8 exporter is merged and completed
