### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [supertuxkart/stk-code#4036]
Please add the app on F-Droid for those who do not have the Google Play Store on their Android devices.

**Comment by deveee** [comment]
You didn't even check if it's there

**Comment by ristein** [comment]
is the f-droid version still updated?
the version lacks behind the one from playstore quite a lot...

**Comment by deveee** [comment]
AFAIK current build script for STK on f-droid has some issues and thus their build server complains. Also it may need some modifications for STK 1.2. Anyway I have impression that they don't care (or maybe no free time). You can always download apk from sourceforge/github.
