### ISSUE TITLE
STK

### ISSUE THREAD

**Issue by Chujinda** [supertuxkart/stk-code#4039]
## Configuration

STK release version: 

STK Source (PPA, distribution package, official binary, etc.): 

System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
I nuke the crap out of you

**Comment by james165527** [comment]
hey dude try this ! https://geekprank.com/hacker/

*Yours sincerely,*
Mark James Agripo.
