### ISSUE TITLE
(VideoMode) = From a screen of 1920x1080 to a screen 1440x900.

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#404]
**Author: ssta**

Hi, ...

Tested = From a screen of 1920x1080 to a screen 1440x900.

It made also that, when in portable version = Because computers, dont have the same screen and videomode.

1) The computer have 1920x1080 natif videomode.
2) The computer have 1440x900 natif videomode.

From 1) to 2) and start the game, it dont crash the computer, but really display the game. But it miss some part of the complete display. It's in 1440x900 but not display all the FullScreen games graphics of a real 1440x900. Only the upper left part of 1920x1080 on the 1440x900 videomode.

It display a fullscreen 1440x900, but inside not all graphics inside = it miss the right bottom section of the 1920x1080. = it dont have the section "quit exit".

Please "reset to videomode 800x600", when the last videomode in the supertuxkart game, is not in the videomode of the new screen.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/348

**Comment by auriamg** [comment]
Closing as outdated
