### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [supertuxkart/stk-code#4041]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [NetworkAIController](https://github.com/supertuxkart/stk-code/blob/f4a932271f6a0eca79ee1da8af6544dbb1aa9055/src/karts/controller/network_ai_controller.cpp#L32)
- [Physics](https://github.com/supertuxkart/stk-code/blob/0fe162a54aecee86c45dbb2d2411219a0e7182f9/src/physics/physics.cpp#L48)

**Comment by elfring** [comment]
Would you like to take [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") into account?

**Comment by Benau** [comment]
![](https://lihkg.com/assets/faces/pig/heard.gif)![](https://lihkg.com/assets/faces/pig/dance.gif)![](https://lihkg.com/assets/faces/pig/dance2.gif)
