### ISSUE TITLE
Donation Package Misnamed (itch.io)

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#4046]
![Screenshot from 2019-08-16 02-29-48](https://user-images.githubusercontent.com/12213882/63110161-21a2db00-bfce-11e9-8f76-149bb26972b5.png)

"Gift Package For Donators (1.0)" is actually the 0.9.3 package.

https://supertuxkart.itch.io/supertuxkart

**Comment by Benau** [comment]
Sorry about that, i hide it until we have real gift package for 1.1, you can also tell me later directly when it's released so you don't need to donate again.
