### ISSUE TITLE
framerate limiter

### ISSUE THREAD

**Issue by netpipe** [supertuxkart/stk-code#4050]
was wondering if a framerate limiter in settings could improve performance further.

**Comment by tecan** [comment]
While having the joystick plugged in STK runs alot slower too on suse 15. No resolution works good with it or display setting with Nvidia 1050 ti

**Comment by tecan** [comment]
can confirm it runs slower in github version of stk too

**Comment by programmerjake** [comment]
I've been getting around 115fps on stk git master from a few weeks ago on Mesa with X11 on my RX580 8GB and Ryzen 3900X with 32GB of memory even when switching to the lowest graphics setting. Since this is comparable to what I get on lowest settings on my Ivybridge laptop, I think that the framerate may be limited somehow. I have vsync disabled. I noticed that other people were getting 180ish fps on a different GPU (RX Vega 64, I think). I'm not using a joystick. Any ideas what I should change?

**Comment by programmerjake** [comment]
maybe it would be good to have a separate thread for input handling and have the graphics thread linearly extrapolate for a limited time when it runs faster. If the input thread has not responded in .1s, then the graphics thread should not extrapolate anymore since otherwise that would probably go crazy.

**Comment by Calinou** [comment]
I also can't reach more than 115 FPS on a GTX 1080 (NVIDIA 440.44 driver on Fedora 31).

**Comment by auriamg** [comment]
In your "config.xml" file (see https://supertuxkart.net/FAQ to find it), there is a framerate limiter set to 120 by default

max_fps="120"

first try editing that

**Comment by auriamg** [comment]
keep in mind going above 120 fps is not tested and may contain glitches. especially, the physics engine runs at 120 fps, so even if you let the graphics higher, I'm not sure how that would interact with physics. In order for the graphics to go at a higher framerate than the physics engine, we'd need to add interpolation between frames and we don't have that atm

**Comment by Benau** [comment]
Can u try this branch https://github.com/supertuxkart/stk-code/tree/sdl and see if there are still lag when playing gamepad?

(It uses SDL2 for gamepad now)

**Comment by programmerjake** [comment]
Copying some ideas from discord:

to render at >120Hz, with the input/physics still at 120Hz, switch the object and viewpoint position calculations to use `last_physics_position + time_since_last_physics_frame * last_physics_velocity`.

The main benefit is making the animations smoother, especially on really high FPS monitors (>200Hz).

To debug it without needing a high-refresh-rate monitor, change all the timing functions to scale the in-game time: think of it like the game is put into a VM where the VM's clock is artificially slowed down, making your monitor's 60Hz refresh rate look much higher from the perspective of the slowed-down game, allowing you to debug what happens on computers that really have a 144Hz (or higher) monitor.
Obviously, that debugging method will only work with non-networked games.

**Comment by Calinou** [comment]
@programmerjake Out of curiosity, what's the benefit of performing physics interpolation in the vertex shader rather than on the CPU? Most other engines don't seem to involve shaders for physics interpolation.

**Comment by programmerjake** [comment]
> @programmerjake Out of curiosity, what's the benefit of performing physics interpolation in the vertex shader rather than on the CPU? Most other engines don't seem to involve shaders for physics interpolation.

you definitely could just use the cpu. the benefit of using the vertex shader is that all of the object/mesh position buffers in GPU memory don't need to be rewritten every frame, which could involve multiple buffer -> buffer copy operations.

**Comment by qwertychouskie** [comment]
The framerate limit can now be configured in the graphics settings, this issue should be closed.  Further discussions about adding position interpolation should be moved to a dedicated issue.
