### ISSUE TITLE
Crash when playing in multiplayer local mode

### ISSUE THREAD

**Issue by anhnguyent93** [supertuxkart/stk-code#4051]
## Description

When playing with 2 or more AI karts in local multiplayer mode, the game is crashed. It is only crashed with the development version. Release version 1.0 works well.

## Steps to reproduce
1. Choose the local multiplayer mode.
2. Start a normal race with 2 AI karts.
3. All players pass a AI kart.
4. Slow down and let the AI pass. The game will be crashed

## Configuration

STK release version:

STK Source (PPA, distribution package, official binary, etc.): Github repository 

System: Windows 10 pro

Graphics card: Intel HD Graphics 4600 and NVIDIA Quadro K1100M

CPU: Intel Core i7-4810MQ

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```
![cmd](https://user-images.githubusercontent.com/36124550/63567670-228cbd00-c538-11e9-8e73-5152661d0b0b.PNG)

```

input.xml:
```xml

```

Error message:
```
![Capture](https://user-images.githubusercontent.com/36124550/63567682-28829e00-c538-11e9-9559-5ed2ed4e047a.PNG)

```

**Comment by Benau** [comment]
skidding_ai.cpp:1940
``
    // Distribute the AIs to players
``
Alayan i don't understand that code to fix this, sorry....

Because in release 1.0 the assert is removed so you don't crash

**Comment by Alayan-stk-2** [comment]
I couldn't reproduce this bug.

In any case, I rewrote the related code to only use integers, so if something funky happened with floats rounding leading to an out-of-range error, this is not the case anymore.

I'll assume this is fixed and close, but feel free to test with the latest master and report back here your results.
