### ISSUE TITLE
Change account email address

### ISSUE THREAD

**Issue by trymeouteh** [supertuxkart/stk-code#4059]
In the game your are able to change your online account password, but not your email address. Please add a feature to change ones email address.

**Comment by trymeouteh** [comment]
Is this a missing feature in the game?

**Comment by Muna58009924** [comment]
https://www.hashingadspace.com/register.php?ref=Muna246
Hello friend my link a joined please

**Comment by GuillaumeBft** [comment]
I worked on this issue and i saw that the email string is sent through an API to the multiplayer server at the register. There is a list of possible actions for the API somewhere ? Can I retrieve a email address to display it ?

**Comment by Benau** [comment]
.....not so easy (and requires changes to stk-addons)

**Comment by trymeouteh** [comment]
This is needed since any basic account management has a "change email" feature.

Is it possible to delete an account and signup again with the same username but with a different email?

**Comment by Benau** [comment]
It should work in latest git now ![](https://cdn.lihkg.com/assets/faces/pig/clap.gif)

**Comment by LuisAlfredo92** [comment]
So can we change our email now? :0
Where can we do it? Or are you referring to delete the account and create a new one with the same username?

**Comment by Benau** [comment]
![Screenshot from 2021-12-15 02-24-12](https://user-images.githubusercontent.com/3252341/146057514-bc1db5b4-d5ae-41d6-b010-f3428099a63f.png)
![](https://cdn.lihkg.com/assets/faces/mousexm/miracle_special.gif)
