### ISSUE TITLE
Time Trial races converts story mode countemparts' power-up layout

### ISSUE THREAD

**Issue by Wilker-a** [supertuxkart/stk-code#4062]
## Description
Whenever you play a track in Time Trial mode in Single Player, the layout of the powerups in the Story mode countempart of the track you play gets converted to the ones in Time Trial (in the Android release from F-Droid)

## Steps to reproduce
- choose a track to play in Time Trial
  - you start with 3 boost power-ups, track only contains turbo and parachute bananas, etc.

then get to the same map but via Story mode.

instead of the regular race layout (with presents and other stuff), there are only turbos and bananas, just like in Time Trial. plus, you get the boost power-ups at the beginning.

## Configuration
Release 1.0  
downloaded from F-Droid
Android 5.1.1

**Comment by xlf1024** [comment]
Can't reproduce, I still get presents as always, also no boost in the beginning

Track Cornfield Crossing
Android 9
Version 1.0 from F-Droid

@Wilker-a which track did you notice it on?

**Comment by Wilker-a** [comment]
i tried again with new maps (ones where it didn't happen yet) and i could not reproduce the bug... although some time ago did play some in multiplayer with time trial at Snow Peak, i am not sure how to test it, as it depends on having other people willing to try on the servers and stuff..

but other than that, it might have been a false alarm, sorry for that.

**Comment by Wilker-a** [comment]
btw why does the time trial races in Story work under the same criteria as the regular races (finish first, time limit only on ST difficulty)? should not they have something more (e.g time limit in every difficulty or something)?

**Comment by Alayan-stk-2** [comment]
@Wilker-a Beating the AI is enough of a challenge for many players. Not having time limits on lower difficulty makes balancing more consistent.

**Comment by Wilker-a** [comment]
i see. :3

it would be cool if time trials and nitro challenges worked like in Trackmania games though. because every difficulty works the same way, the difficulty isn't chosen. instead, the rewards should be given according to the performance criterias and stuff.
