### ISSUE TITLE
In-game chat issue

### ISSUE THREAD

**Issue by Anard** [supertuxkart/stk-code#4067]
Hi.
Yesterday, we was playing with anybody who tried to chat a long message during the game (about 5-7 lines).

1. First problem : the little yellow ball on the left of the message box is scaled to fit the box. Very very ugly when scaled 5-6 or 7 times !
2. Second : the box cover a large part of the screen.
Would it be possible to limit it to 2-3 lines and make it auto-scroll to show all content ?

**Comment by Benau** [comment]
![a](https://media.discordapp.net/attachments/588002848051036169/625584596456570881/unknown.png)

In git stk it limits to 5 lines at most, you need even little? (And i don't think auto scroll is a good idea, because in game chat is for short message)
