### ISSUE TITLE
Wrong icon used

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4070]
## Description

The 'General' icon in the help screen uses 'track_random.png' instead of 'options_general.png'
The slipstream icon's size is larger than the rest.
![Screenshot from 2019-09-28 00-01-37](https://user-images.githubusercontent.com/4726939/65811776-51bfcb00-e183-11e9-8ad5-2ef579aa3a6a.png)

The icon for 'Global networking' uses 'menu_multi.png', should be 'menu_online.png'.
![Screenshot from 2019-09-27 23-55-45](https://user-images.githubusercontent.com/4726939/65811721-76677300-e182-11e9-8f7a-8e9201db89fa.png)

The icon for 'There are 3 types of battle mode: ...' uses 'gift.png', but should be 'mode_3strikes.png'.
![Screenshot from 2019-09-28 00-12-23](https://user-images.githubusercontent.com/4726939/65811894-22aa5900-e185-11e9-8a1f-4d84d99f9976.png)

The icon for 'Battle' is actually 'weapons.png'. I think it should be 'mode_3strikes.png'.
![Screenshot from 2019-09-28 00-15-13](https://user-images.githubusercontent.com/4726939/65811907-55545180-e185-11e9-8120-131143dbf796.png)

## Steps to reproduce

Open STK

## Configuration

STK release version: git d205d80

STK Source: https://github.com/supertuxkart/stk-code

System: Ubuntu 19.04

Graphics card: NA

CPU: NA

Gamepads/keyboards models if related to the issue: NA

**Comment by Mrxx99** [comment]
For battle it is not the three strikes icon anymore because FFA was added as a mode in battle and the number three in the original icon would not fit for that

**Comment by jijn** [comment]
I see, maybe rename it to 'mode_weapons.png' for consistency?

**Comment by dumaosen** [comment]
Riso you can do it by yourself!

**Comment by risostk** [comment]
I would suggest renaming 'weapons.png' to 'mode_weapons.png' for consistency.
Moreover, why there are both 'gp_edit.png' and 'gpeditor.png'? I see 'gpeditor.png' is used on the home screen. Why not merge them into one?

**Comment by risostk** [comment]
Also curious why using 'gp_new.png' in soccer?

![image](https://user-images.githubusercontent.com/4726939/66020752-c6f60d80-e4ad-11e9-9ce8-5ee93f7acab8.png)

**Comment by deveee** [comment]
Do you want to make it fully configurable (eg. allow to use custom icons) or you just don't like the name used? Because in second case it's just a name. And in the first case, maybe these file names should be available in xml file and not hardcoded, so that you can use any icon you want (and can be different from cup_gold either).

**Comment by risostk** [comment]
@deveee Thanks. I recently tried to make a new icon set for stk, and noticed that the naming is a bit messy. Guess mostly due to historical reasons. It will be great to have the file names configurable in the xml file. I won't complain anymore :D

**Comment by Benau** [comment]
If it's named in a logical way, then you don't need configurable xml! ![](https://lihkg.com/assets/faces/pig/argue.gif)

**Comment by Benau** [comment]
Riso ok for now? ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by risostk** [comment]
I see the new PR. Still need more work. I'll work on it this weekend.

**Comment by Benau** [comment]
just for the record i don't feel like adding configurable xml for icon

**Comment by risostk** [comment]
@Benau No, I will just clean the file names a bit.

**Comment by Benau** [comment]
![](https://lihkg.com/assets/faces/pig/wine.gif)![](https://lihkg.com/assets/faces/pig/wine.gif)![](https://lihkg.com/assets/faces/pig/wine.gif)

**Comment by Benau** [comment]
![](https://lihkg.com/assets/faces/pig/clap.gif)![](https://lihkg.com/assets/faces/pig/clap.gif)![](https://lihkg.com/assets/faces/pig/clap.gif)
