### ISSUE TITLE
serious problem with online multiplayer server (global network)

### ISSUE THREAD

**Issue by mankanshoku** [supertuxkart/stk-code#4072]
## Description

serious problem with online multiplayer server

I have a problem creating a server
Once I believe it, my friends try to enter but are expelled directly. they cannot enter, only one of my friends managed to enter, I was using the android version of the game.
But my friends who use the windows version, and linux, cannot enter my server.
I clarify that this problem happens to all my friends, they are from Argentina. They tried to create servers too and we cannot enter the server they create. We can only enter the "Southland" server.
How can I solve this problem?
What router ports should be opened?

We have the latest version of the game, this problem happens when trying to create a server in the global network, for the local network if it works.
The operating system is windows 10.
Sorry for my bad English.

## Steps to reproduce

create a server in global network (localitation: argentina)

## Configuration

STK release version: last version (downloaded a few days ago)

STK Source (PPA, distribution package, official binary, etc.): 
https://sourceforge.net/projects/supertuxkart/
System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
you need to open 2757 port of router

actually you can use the "textgame" servers, any ping < 300ms is playable, as long as your network connection is stable

If your pc / router has a very strong firewall, then it's not suitable to host a server

**Comment by mankanshoku** [comment]
> 
> 
> you need to open 2759 port of router
> 
> actually you can use the "textgame" servers, any ping < 300ms is playable, as long as your network connection is stable
> 
> If your pc / router has a very strong firewall, then it's not suitable to host a server

hi! It still doesn't work, I already opened those ports on my router and deactivated the firewall, but it doesn't work, :(

**Comment by Benau** [comment]
can you post your server.log in .config/supertuxkart/config-0.10?

**Comment by Benau** [comment]
Well if one day digitalocean has brazil vps available we can conside an official stk servers there... ![](https://lihkg.com/assets/faces/pig/upset.gif)

**Comment by mankanshoku** [comment]
> 
> 
> can you post your server.log in .config/supertuxkart/config-0.10?

thanks for reply! I cant find that server.log in the game's folders, i'm in windows 10, that adress is for linux?

**Comment by mankanshoku** [comment]
> 
> 
> Well if one day digitalocean has brazil vps available we can conside an official stk servers there... ![](https://camo.githubusercontent.com/e1288da68ac8c53d0a898b491e94edbd25b90d35/68747470733a2f2f6c69686b672e636f6d2f6173736574732f66616365732f7069672f75707365742e676966)

that would be nice! im from argentina, if you want to put a server here, I can offer my help, I have a pc that is almost always on

**Comment by Benau** [comment]
looks for %appdata%/supertuxkart

**Comment by Benau** [comment]
No reply

**Comment by Benau** [comment]
There is a "[P7COM] - STK Argentina" now hosted by some stk fans! ![](https://lihkg.com/assets/faces/pig/dance2.gif)

**Comment by Boloyxaya** [comment]
Sorry i ma I am in very sorry head of myself that last the past pass
by.,now wit Reads and written in pair of person,say the best in walk
heath an mind heath, easy scene sense Greetings an Hi,buy Way Us Know.
Person,Me,in Colorado springs Co emailing & Mailing Address..home iam
