### ISSUE TITLE
Chinese logo

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4074]
I made a Chinese logo. Hope someone will do some polish for it.
![STK_CN](https://user-images.githubusercontent.com/35170687/66096623-2ea37a00-e5ce-11e9-9691-db52ad02cd2f.png)

**Comment by jojoHZhang** [comment]
awesome




------------------ 原始邮件 ------------------
发件人: "Du maosen"<notifications@github.com>; 
发送时间: 2019年10月3日(星期四) 中午11:09
收件人: "supertuxkart/stk-code"<stk-code@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [supertuxkart/stk-code] Chinese logo (#4074)




I made a Chinese logo. Hope someone will do some polish for it.
 
 
&mdash;

**Comment by risostk** [comment]
Not sure if the name is patented by QQ

**Comment by risostk** [comment]
Maybe just call it "STK赛车"?

**Comment by risostk** [comment]
How about?
![stk_logo_chinese](https://user-images.githubusercontent.com/4726939/66175570-eb71f700-e61f-11e9-88db-6e21afc2794c.png)

**Comment by jojoHZhang** [comment]
so disgusting,guy,change





------------------ 原始邮件 ------------------
发件人: "riso"<notifications@github.com>; 
发送时间: 2019年10月4日(星期五) 上午9:54
收件人: "supertuxkart/stk-code"<stk-code@noreply.github.com>; 
抄送: "修罗之血洗"<2499542694@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [supertuxkart/stk-code] Chinese logo (#4074)




How about?

**Comment by risostk** [comment]
@jojoHZhang Don't like the color, or the general design?

**Comment by jojoHZhang** [comment]
I think is the design




------------------ 原始邮件 ------------------
发件人: "riso"<notifications@github.com>; 
发送时间: 2019年10月4日(星期五) 上午10:00
收件人: "supertuxkart/stk-code"<stk-code@noreply.github.com>; 
抄送: "修罗之血洗"<2499542694@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [supertuxkart/stk-code] Chinese logo (#4074)




@jojoHZhang Don't like the color, or the general design?

**Comment by dumaosen** [comment]
Maybe jojoHZhang is a spam lol
STK飞车 isn't a good name because it cannot represent what "supertuxkart" means

**Comment by dumaosen** [comment]
also please fit the theme

**Comment by risostk** [comment]
maosen, what do you mean 'theme', the color?

**Comment by risostk** [comment]
![image](https://user-images.githubusercontent.com/4726939/66249643-614b9080-e6fc-11e9-8679-e769e910d1c3.png)

There are two ways of thinking:
(a) Be short so people can easily remember it, like Dota, CS, GTA.
(b) Tell people what the game is about, like 极品飞车

For SuperTuxKart, options are:
(a) STK飞车, STK
(b) 企鹅飞车, 超级企鹅卡丁车

SuperTuxKart is an open-source game. Currently, not so many people in China know it. We need a better name to promote it. Considering this, (b) may be more suitable. Adding 超级 may make people thinking it is a very cool game. I think 超级企鹅卡丁车 is a better name.

**Comment by dumaosen** [comment]
Theme is about everything. What i meant is your logo should be exactly the same look compared to the English logo except the words.
I thought of the name 超级企鹅卡丁车, but it's a bit long as a name.
Most games have <= 5 chars, like all games in your list.
logo should be 512x512 and may be like this:
  S T K   
--------
超级企鹅
 卡丁车

**Comment by risostk** [comment]
How about?
![Screenshot from 2019-10-05 23-43-02](https://user-images.githubusercontent.com/4726939/66264380-ea7cc900-e7c9-11e9-81c5-a20038224f32.png)
![Screenshot from 2019-10-05 23-43-07](https://user-images.githubusercontent.com/4726939/66264381-ec468c80-e7c9-11e9-8c67-0fc423c6d26a.png)

**Comment by Benau** [comment]
![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)

**Comment by dumaosen** [comment]
Oh pretty good!
Maybe we can make logo in french, german, italian...

**Comment by risostk** [comment]
@dumaosen Oh, That's too much work, and may not be a good idea considering the size of assets. We may end up packing a lot of logos we never use, as the image files take a lot of space compared to the language file. I think it can be the addon. People can choose to download the logo for their language.

**Comment by Alayan-stk-2** [comment]
"SuperTuxKart" is alright in many european languages, I don't think there is a point changing a name there.

**Comment by dumaosen** [comment]
> 
> 
> "SuperTuxKart" is alright in many european languages, I don't think there is a point changing a name there.

But Chinese, Japanese, Korean are not. Look at BoW, it has a good Chinese name so it promoted much better in China than STK.

**Comment by Alayan-stk-2** [comment]
I was answering to the suggestion of having a different name in french, german, etc.

**Comment by CodingJellyfish** [comment]
STK doesnt haave a suitable Chinese name
