### ISSUE TITLE
Update footer on website

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#4080]
Things to update in the footer on supertuxkart.net

- Make links HTTPS
  - Forum
  - Addons (see below)
  - IRC
- Change Addons link from `http://addons.stk.net` (server offline) to `https://online.stk.net`
- Update copyright year

**Comment by Benau** [comment]
the fixes should be done in https://github.com/konstin/stk-wiki-theme

Not sure auria has time to make stk-wiki-theme inside official supertuxkart repo... ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by MinIsMin** [comment]
Thanks for pointing it out, didn't know it existed.
Created a PR.

**Comment by MinIsMin** [comment]
I'm reopening this issue since the other repo got archived (see https://github.com/konstin/stk-wiki-theme/pull/41#issuecomment-568255913) and the footer is still not updated on the website.

Is there a new repo for the website?

**Comment by Benau** [comment]
Give me few days for all your stk website related questions....![](https://lihkg.com/assets/faces/pigxm/dance2.gif)

**Comment by Benau** [comment]
Here is the newest repo https://github.com/supertuxkart/stk-wiki-theme

It should have auto deploy working now ![](https://lihkg.com/assets/faces/pigxm/clap.gif)![](https://lihkg.com/assets/faces/pigxm/clap.gif)![](https://lihkg.com/assets/faces/pigxm/clap.gif)
