### ISSUE TITLE
How to add screen_ui minimap option

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4083]
## Description
Hello, this is not an issue. I just need some help to propose a feature.
I want to add minimap view in center of screen (especially for football mode).

I modified the code to add padding to the minimap in `race_gui.cpp`:
```c
// in IF OPTION block
m_map_padding_left   = (int)( (irr_driver->getActualScreenSize().Width   - m_map_width) / 2) ;
m_map_padding_bottom = (int)( (irr_driver->getActualScreenSize().Height  - m_map_height) / 2 ) ;

m_map_left          = (int)( 10.0f * scaling) + m_map_padding_left;
m_map_bottom        = (int)( 10.0f * scaling) + m_map_padding_bottom;
```

And started to add an option in `options_screen_ui.cpp` after the option "Hidden".
```c
//I18N: In the UI options, minimap position in the race UI 
minimap_options->addLabel( core::stringw(_("Centered on left")));
```

But i don't get how to forward the option in `race_gui.cpp` code in order to make the option usable.

Where variables defining concrete values  for "In the bottom-left" and "On the right side" can be found ? Which type is used to represent the option (int ?) ?

**Comment by auriamg** [comment]
github issues are probably not the best way to ask questions, as it is meant to report bugs.
I believe you are looking for src/config/user_config.hpp

```

    PARAM_PREFIX IntUserConfigParam        m_minimap_display
        PARAM_DEFAULT(IntUserConfigParam(0, "minimap_display",
                      "Minimap: 0 bottom-left, 1 middle-right, 2 hidden"));
```

**Comment by luffah** [comment]
thank you.
(Sorry, i'm so used to "feature request" label on repositories, that i didn't think these kind of questions could be asked elsewhere.)
