### ISSUE TITLE
Action Triggers give unexpected kart_id in scripting

### ISSUE THREAD

**Issue by BlueCatYellowCat** [supertuxkart/stk-code#4088]
## Description
Action Triggers appear to return the kart_id of the camera's kart, not the kart which entered the trigger. While this works fine in the tutorial track, this value is incorrect in any race with multiple karts.

relevant function:
void TrackObjectPresentationActionTrigger::onTriggerItemApproached()
at the bottom of https://github.com/supertuxkart/stk-code/blob/master/src/tracks/track_object_presentation.cpp

**However**, before this is fixed, I would like for a simple GetCameraPlayer() or GetLocalPlayer() function be created, as abusing this action trigger bug is currently the only way to always return the kart_id of the local player. This is useful in networked or multiplayer races if a track designer wants something to only happen for the kart which triggered the action trigger, so that AI karts or other players won't trigger it (an example of this in practice is the behavior of the secret path in 'Frozen Drive' track, currently available on the forum).

## Steps to reproduce
1) read the source code linked above
or
1) create a track with an action trigger, placed where AI karts will drive into it, which triggers a scripting function which prints the kart_id.
2) start a game with AI players (or local multiplayer instead)
3) notice that your kart_id is always printed regardless of who hits the action trigger

## Configuration
STK release version: 1.0 Release, still applies to HEAD as of this issue.

(Other items not applicable, this is an issue with a source code function)

**Comment by Benau** [comment]
Can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20191009/SuperTuxKart-git20191009-win.zip/download?
![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)

**Comment by BlueCatYellowCat** [comment]
> 
> 
> Can you try https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20191009/SuperTuxKart-git20191009-win.zip/download?
> ![](https://user-images.githubusercontent.com/3252341/65811367-f7a62080-e1e9-11e9-9a6b-d6aa237bc18e.gif)

This appears to fix the action trigger issue. Tested in multiplayer (vs. 10 AI karts) and in local multiplayer (2 STK instances).
