### ISSUE TITLE
Rescale font size in race screen

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4089]
## Description

The font size shows the time in the race screen (next to the icon) does not scale with the number of players. Thus looks relatively big and a bit busy if there are many players, see following images:
<img width="1348" alt="Screen Shot 2019-10-10 at 8 14 19 PM" src="https://user-images.githubusercontent.com/4726939/66617548-2b465a80-eb9b-11e9-8ffc-95560d911f1d.png">
<img width="1392" alt="Screen Shot 2019-10-10 at 8 15 19 PM" src="https://user-images.githubusercontent.com/4726939/66617552-2d101e00-eb9b-11e9-94d2-32332e81add5.png">

It is acceptable, but I would suggest to rescale the font a little bit for many players.

## Steps to reproduce

- Open STK
- Start a normal/time-trial race, choose 3AI / 19AI, Start!

## Configuration

STK release version: git edb338d

STK Source (PPA, distribution package, official binary, etc.): github.com/supertuxkart/stk-code

System: macOS

Graphics card: NA

CPU: NA

Gamepads/keyboards models if related to the issue: NA

**Comment by dumaosen** [comment]
Hi
Actually the fonts are way better tham those in 0.9.3. Try by urself lol!
Anyways i have added a fix in race_gui_base.cpp th give such space for large font. I think change the min value to 0.7 fontsize from a fontsize
