### ISSUE TITLE
[Meta-Tracker] GNU/Linux Mobile

### ISSUE THREAD

**Issue by WorryTheBirds12** [supertuxkart/stk-code#4091]
## Basic Information

**Description**: SuperTuxKart on GNU/Linux Mobile.
**Platforms**: TuxPhones has a list of them [here](https://tuxphones.com/all-linux-distributions-for-smartphones/)

## Solutions

Many others have been talking about adaptive layouts.
_TL_;_DR_ Basically, adapt the current Linux UI for smaller screens. :)

![adaptive-layout](https://coinsh.red/u/adaptive.jpeg)

### Alternative designs

Developing a separate applications or porting the Android application.

## Additional context

Preferably, the applications would be using a tarball to start.
Therefore, it is easier to port to a variety of mobile OSes.

______________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=81860638)](https://www.bountysource.com/issues/81860638-meta-tracker-gnu-linux-mobile)

**Comment by deveee** [comment]
Everyone knows that we should adapt for smaller/hidpi screens, we already do it for several years and I feel that it's a spam.
