### ISSUE TITLE
Laps text changes its size during race

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#4095]
On the screenshot the 2/3 is too small, but it sometimes goes back to normal.
![Zrzut ekranu z 2019-10-17 22-59-06](https://user-images.githubusercontent.com/5108558/67047174-108f5b00-f132-11e9-8d57-85cbd6a436a7.png)

**Comment by risostk** [comment]
This maybe related to my previous PR #4090.

**Comment by Alayan-stk-2** [comment]
I'm getting another weird UI issue that may be related.

![STK_bug_timer](https://user-images.githubusercontent.com/25536748/67239707-177ade00-f450-11e9-8e88-c8d0e6bb1ba4.png)

Steps to reproduce : 1)finish a timed challenge
2)go play another challenge, the timer will be wrongly positioned and the right of it will be cut off.
