### ISSUE TITLE
Vsync spinner

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4097]
I don't like "combo" issues, but these don't deserve separate issues : 
- Why is it not possible to "loop" with the spinner and go back from "half" to "disabled" ?
- Why put this Vsync option above the main graphics spinner ?
- What does "half" vsync do compared to "full" ? This isn't clear.

@deveee

**Comment by deveee** [comment]
See comments in https://github.com/supertuxkart/stk-code/commit/fc8f6a218ecf73b87e4504ff8672f7e68c2ed663

Typically half is 30 fps and full is 60 fps, but if you have 120hz monitor, then half will be 60 fps. And some drivers don't support half vsync, in this case half will work just like normal vsync. I'm not sure how to describe it better.

And allow to "loop" with the spinner should be ok.

**Comment by deveee** [comment]
Alayan better? And btw. text is cenered vertically now.
![screenshot2](https://user-images.githubusercontent.com/5108558/67089571-440ccc80-f1a8-11e9-9163-197398c34d48.png)

**Comment by Alayan-stk-2** [comment]
Better with the vsync spinner below the main options.

I added a tooltip explaining briefly what this option do and what full and half mean.
