### ISSUE TITLE
The kart characteristics icons are too small in the kart selection screen

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4098]
They look 3-4 times smaller than the kart icons, and require extra attention to properly identify.

There is also no reason for the bars to be so small in height, which is likely related to this small icon issue as they seem limited by the vertical height.

Local multiplayer suffered from this issue in 1.0 too, but it's because it is more space constrained, there is no reason for this to happen in single player.

**Comment by dumaosen** [comment]
Oh it's pretty eeasy to fix lol
