### ISSUE TITLE
Test on iPad

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4101]
## Description

I tested STK (testflight 2019-10-18) on my iPad. Here are some small issues I found:

1. The icons in the help screen look a bit small.
![IMG_0014](https://user-images.githubusercontent.com/4726939/67176110-50eb1500-f38e-11e9-98f2-56eb8d95bf49.PNG)

2. The vertical distances between 'Display FPS', 'Multiplayer split xxx', and 'Show other karts xxx' do not seem right.
![IMG_0015](https://user-images.githubusercontent.com/4726939/67176171-90196600-f38e-11e9-993d-19cdc24a32f9.PNG)

3. The controls look very big, especially the wheel. Need a large hand to touch the powerups. Would suggest to make it a bit smaller.
![IMG_0016](https://user-images.githubusercontent.com/4726939/67176210-bdfeaa80-f38e-11e9-8cfe-ec39edee80dc.PNG)

## Configuration

STK release version: testflight 2019-10-18

STK Source (PPA, distribution package, official binary, etc.): testflight

System: iPad (6th generation), iPadOS 13.1.3

Graphics card: PowerVR Series7

CPU: Apple A10

Gamepads/keyboards models if related to the issue: NA

**Comment by Benau** [comment]
what is the screen resolution you see in options menu video?

**Comment by Benau** [comment]
Not sure deve can gimme code to force stk to open at 2048x1536...

And you change wheel size by clicking touchscreen control in control option, maybe 110 size better?

**Comment by dumaosen** [comment]
Riso u can fix the first issue by yourself!
U just need to make the icon size in help screen to percentages.
The first issue is more obvious in ur 5K screen i think.
BTW the second one is fixed.

**Comment by Benau** [comment]
Try build 5 now? ![](https://lihkg.com/assets/faces/pigxm/clap.gif)

btw @Anard you can try build 5 too and see if the inverted accelerometer is fixed... ![](https://lihkg.com/assets/faces/pigxm/drum.gif)
