### ISSUE TITLE
The highscore list in track info doesn't update on kart number change

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4106]
Highscore data is tracked by lap number and AI number. Changing the number of AI through the spinner used to update the highscore data.

Bug didn't exist in 0.9.3 ; but it did exist in 1.0. Now trying to pinpoint the faulty commit.

EDIT : bug verified to have been introduced after 15/09/18.

**Comment by Alayan-stk-2** [comment]
Regression introduced in #3708 

@Mrxx99 Do you remember the reason why you removed this code line ? : 
`     race_manager->setNumKarts( race_manager->getNumLocalPlayers() + num_ai );`

**Comment by Mrxx99** [comment]
@Alayan-stk-2 I don't know anymore, I had to move quiet some things around for the FFA implementation, maybe it got somehow lost there, sorry
