### ISSUE TITLE
Rename "half" "full" to "Half FPS limit" "Max FPS limit"

### ISSUE THREAD

**Issue by dumaosen** [supertuxkart/stk-code#4118]
This issue is beginner friendly.
### Hint for beginners
We name widgets in either data/gui/screens or src/states_screens.
When the name is dynamic, we put it into code(often in init()). Otherwise we name it in XML files.
For selections in spinners, we only give name in code by this:
`vsync->addLabel(_("Full"));`
This means the vsync will have a new selection called "full".
It's easy to change it's content. Just change the string inside.

**Comment by Benau** [comment]
this even more confusing for "full fps rate"

**Comment by Alayan-stk-2** [comment]
Not needed with the tooltip.
