### ISSUE TITLE
Random tips when a user fail a challenge in story mode

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4120]
There is a lot of things that new players often don't know about the game that are important to perform better. But a new player usually won't read the help, or even do the tutorial, instead jumping straight into action.

While casual players will never be very good at the game, they'll enjoy it more if they can understand and use some basic concepts, like the rescue key. So having a selection of random tips that could be displayed to the player after a failed challenge could help giving some ideas on what to do better. Some will ignore it, but as long as it helps at least a few percents of casual players, it is worth it.

**Comment by dumaosen** [comment]
Alayan you can list some tips! I know you are an experted player.
Also it should have some following icons to help users understand.

**Comment by dumaosen** [comment]
@Alayan-stk-2 some additional ideas:
Show tips when game starts, and allows user to disable it.
Define those tips in an xml file. It needs a "tip manager".

**Comment by dumaosen** [comment]
after my latest pr #4135, i have got some new ideas to avoid a redesign: showing a new dialog after failing, so that it won`t take more space.

**Comment by dumaosen** [comment]
？

**Comment by CodingJellyfish** [comment]
?????????????????????
Why still here ???

**Comment by Rami-Slicer** [comment]
Some tips for tips where [] contains a control and is replaced with the corresponding keybind:
1. If you get stuck somewhere or lost, press [Rescue] to get back. 
2. After collecting bottles or cans, you can press [Nitro] to speed up faster!
3. If you find a track hard, you can practice in singleplayer mode with as many or few kart as you want.
4. Press [Skid] to skid, if you hold it for long enough you get a large speed boost.
5. You can look backwards by pressing [Look Behind]
6. Try combining various tricks like looking backwards and launching bowling balls or cupcakes!
7. If you see a yellow or orange arrow on the ground, drive over it for a large speed boost!
8. The bubblegum powerup shields you from all other powerups!

**Comment by CodingJellyfish** [comment]
Oh boy this issue is outdated please close it!
