### ISSUE TITLE
Ravenbridge Mansion's Pumpkins Hitboxes are too big

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#4125]
## Description
It is like there were invisible walls. Notable example is the latest pumpkin, you can see in the picture how large is the hitbox (I hit it as shown by the "folded" skidding marks).

![Pumpkin Hitbox](https://user-images.githubusercontent.com/42526046/68079795-af34e080-fdef-11e9-8cba-b595fa88c801.png)

## Steps to reproduce
Take turns near any or almost any pumpkin in Ravenbridge Mansion

## Configuration

Stk Latest Git, Latest Svn

**Comment by Benau** [comment]
I tried exact shape on it, you can see if it's better now ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
