### ISSUE TITLE
Online Lags

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#4127]
## Description

Well looks like there is no way to describe this issue specifically as people seem to be affected by different sort of lags, but there is definitively a problem at the Stk or its servers' end. Here are example of things that may happen (not just to me, other people also said such things in Chat):

* Get Thunderbird penalty time despite pressing after Set;
* Inputs becoming pretty off and kart very hard to control, or even so broken that we have things like having the Nitro button constantly pressed. Personally it happens pretty often, and in most cases suddenly during the race (also sounds become garbled) ;
* Being suddenly teleported somewhere else around;
* Go though the ground;
* Left showing 59:59.99 times;
* Maybe not directly related, but hitting walls is very badly handled online in general... (should I open a specific issue about this?);
* Probably a lot of other weird things...

Such problems don't seem to depend on the Ping as Alayan and me can for example experience such things in Strasbourg despite being very near and having like < 20 ms Ping... If everything was fine, we should never experience lag in this case... Also, I don't think that lag is caused by single players with bad connection. It can also happen with as little as 2 player (like yesterday in an 1 Vs 1 against Alayan)
Personally, every of the listed issues happened to me, and most in multiple servers, Strasbourg, Poland, Ipv6,... And I have a pretty good connection!
I am not talking about lags if for example, I play in Hong Kong, it is normal to have light Lag due to 250-300 ms Ping, but it is still pretty playable, as long as I am not hit by the "heavy lag"...

All I can say else is that many people seem to be affected as a good part of the Chat conversations is about lags... Something is definitively broken...

Hopefully Devs can eventually put an end to these lags that cause so many trouble online :p ! Though otherwise, when Lags do not happen, Online Races are pretty smooth.
Maybe I could even make a Lag Compilation video Lol

## Steps to reproduce

Just play online... It will eventually happen...

## Configuration

Stk Latest Git/Svn

Multiple people affected

## Additional information

In the second point, I am getting a lot of "Rewind [warn   ] RewindManager: Missing local state at ticks xxxx", and this lasts until the end of the race.

Alayan told me that he often gets other error messages as well

**Comment by Benau** [comment]
I can try to fix the missing local state ticks for you, also the "goes into ground/ plus improvemt the collision reaction".

But the rest you mentioned sound like some packet loss problem to me, as for myself i always see 0 packet loss to most stk servers, you can use artist debug mode to open the network debugging for that info

The only way to fix all those lag is to trust client data....

You have time later few hours to try something? ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by Fouks0** [comment]
In my case if you can fix "Missing local state at ticks xxxx", it would be great as it is the one that annoys me the most often. If we cannot do anything for the rest, it is what is it, lag cannot be entirely removed after all... Though, these other lags seem to affect a lot some people.
Fixing collisions would also be nice; this also happen when there is no lag.
Yeah, I might Stk a bit tonight and try to reach 8000 points :p Or lose 500 points because of Lags Lol

**Comment by Benau** [comment]
Maybe deve can update poland servers so alayan and fouks can see ranking changes in euro server! ![](https://lihkg.com/assets/faces/pig/dance2.gif)

**Comment by Benau** [comment]
you can try latest master and see if still see missing local state ticks (also @adevairhpj!)

**Comment by Benau** [comment]
For packet loss if your isp supports ipv6 u can try ipv6 button, maybe it works better (ipv6 is less busy?) ![](https://lihkg.com/assets/faces/pig/cook.gif)

**Comment by Alayan-stk-2** [comment]
I had one completely unplayable game the other day.

It was missing local state and put out an error message every 12 ticks (which matches the 10/s rate at which the server send data).
```
Rewind [warn   ] RewindManager: Missing local state at ticks 11
Rewind [warn   ] RewindManager: Missing local state at ticks 23
Rewind [warn   ] RewindManager: Missing local state at ticks 35
Rewind [warn   ] RewindManager: Missing local state at ticks 47
Rewind [warn   ] RewindManager: Missing local state at ticks 59
```

When I had an unstable ping on an US server, I was getting a lot of those : 
`[info   ] RewindQueue: Deleting state at 6419 because it's before confirmed state 6431`

**Comment by Fouks0** [comment]
So far it is looking good, though probably more sessions are needed to confirm that Lags improved.
I only saw "Missing local state at ticks" once during spectating...
Collisions seem to be much better now :D !

**Comment by Benau** [comment]
missing local state during spectate is won't fix because it's not started from the begining

**Comment by Fouks0** [comment]
Rip WaxPro losing 200 points in 4 races due to Lags Lol
I still have once a while the "Missing local state" lag, but just without the error message... Though it seem to happen less often.
But I suppose that there is nothing we can really do... I know nothing about networking and just suppose that the Devs already did their best...
So I am going to close this issue, just reopen it if needed...

**Comment by diegoroversi** [comment]
Still happening to me. Code compiled from master (commit 08f402c8255e0ff8d8e3f8acf9c43e0d3fcad8eb ) and after some playing, usually a couple of race, I get this warning:

Rewind [warn   ] RewindManager: Missing local state at ticks 31091
Rewind [warn   ] RewindManager: Missing local state at ticks 31103
Rewind [warn   ] RewindManager: Missing local state at ticks 31175
Rewind [warn   ] RewindManager: Missing local state at ticks 31187
[...]

  This warning stay here until I quit the server, and reconnect.

**Comment by Benau** [comment]
this can happen if your time cannot fully synchronized with the server before game start (usually because bad internet)

**Comment by diegoroversi** [comment]
I installed chrony instead of ntpd, and I have no more lag problems. 

Thanks.
