### ISSUE TITLE
stdout.log

### ISSUE THREAD

**Issue by adevairhpj** [supertuxkart/stk-code#4128]
At Benau's request, i'm sending the file "stdout.log" for the lags i'm experiencing recently.

[stdout.log](https://github.com/supertuxkart/stk-code/files/3820360/stdout.log)

**Comment by adevairhpj** [comment]
The "stdout.log" with "git pull". It became more stable and now I can play without problems ^ ^
[stdout.log](https://github.com/supertuxkart/stk-code/files/3821228/stdout.log)

**Comment by Benau** [comment]
he said stk is better now
