### ISSUE TITLE
PowerUp proposition 

### ISSUE THREAD

**Issue by LenAlyssa** [supertuxkart/stk-code#4129]
## Description
For a school work, my group and i are working on this game, we’re trying to add a new powerup.
We have 2 proposition :
The first one named flour, which blurry the vision of all the karts with better class.
The second one a spinach concoc that boost the player ( as the star in mario kart ) .

## Configuration

We've been first trying to add an object that act like an existent powerup , edited files:
stk-code/data/
.....................powerup.xml
.....................kart_characteristics.xml

stk-code/src/items
...................attachment_manager.cpp
...................attachment.hpp
...................powerup_manager.cpp
...................powerup_manager.hpp
...................powerup.cpp
                   

The problem we faced is the animation part, in particular the .spm files that we've been trying to understand without final result.

Could you give us your opinion which powerup is better and easier for a beginner, and some tips  considering that none of us had had configured animation before, but still motivated to work on it.

**Comment by Alayan-stk-2** [comment]
Hello,

It's nice that you're interested in STK. Your focus is on getting something done for your school to get a good grade, but my focus will be on actually making your work useful. A demo that doesn't end in the main game is of limited interest.

STK's Github issues are not a good place to make general suggestions or to discuss issues you encounter on your own branch, they are used to track things to fix/improve in the master branch.

Instead, you should post in our forum. I opened a related thread : https://forum.freegamedev.net/viewtopic.php?f=17&t=12690

I'll give you here a quick feedback, but **please direct answers and further questions to the forum**.

Gameplay:
- Blurring the vision is not the kind of effect I'd add more of in STK. The main issue is that it could be circumvented in online play.
- The Mario Kart star also allows the player to hurt other player besides the speed boost and defensive effect, which is undesirable. There is definitely a niche to be filled for another speed boost items for players in the back. The specifics matter.
- The name/visuals are best discussed with the game's community. It's easy to have an idea, but something that pleases a big part of the player base is preferable. I'm not convinced by the popeyish spinach concoction.

Coding:
- Existing powerups frequently require code in other places to work fully. The most obvious example is the AI code ; specific code is required to make the AI use the powerup, and especially use it intelligently.
- You need to modify other files to make the characteristics defined in the .xml do something.
- To make a speed boost work properly, you'll also need some updates to kart.cpp and max_speed.hpp, among others.
- A branch with your code would be useful.
- SuperTuxKart uses Blender with custom scripts for 3D models and animations. .spm files are generated by our export scripts in Blender. You should NOT be editing .spm files by hand. See https://supertuxkart.net/Community

**Comment by LenAlyssa** [comment]
Thank you for your answer and coding tips,
I understand that your focus is to make a useful work.
Even if it's a school work, we're really interested in it and we'll do our best!

**Comment by Alayan-stk-2** [comment]
I'm closing this issue now, please use the forum for further questions or to write about your concept.

**Comment by Yionnara** [comment]
I m searching too how to get xml properties inside cpp code, i found tools which could maybe help me but i dont understand how to use it : I create all get function like zipper in cpp code and i saw when i execute update_characteristics.py that it found my code and delete it, so it can generate it right ? Can someone help me ?

**Comment by Benau** [comment]
the update_characteristics.py is used to tweak kart properties, what do u need to do with current kart properties?

**Comment by Yionnara** [comment]
We are actually creating a new item, and to do it on the right way we thought that we needed to create xml getters to balance it easily. But i'm stuck because i don't understand what i should do... I just copy functions like others items but when i use it : game crash cause it can't retrieve my xml item characteristics...

**Comment by Yionnara** [comment]
It's fine, i find my mistakes, thx for your help.
