### ISSUE TITLE
Invisible wall in Fort Magma

### ISSUE THREAD

**Issue by adevairhpj** [supertuxkart/stk-code#4132]
There is an invisible wall in Fort Magma track, exactly at the point shown in the video below.

https://drive.google.com/open?id=1Sp6DKCghWPm8ly1zA6tmrSgZJrTTS5et

**Comment by Benau** [comment]
I cannot reproduce.... ![](https://lihkg.com/assets/faces/pig/arrested.gif)
https://streamable.com/bl82h

Do u use latest svn stk-assets?

**Comment by adevairhpj** [comment]
Yes. This video is from a month ago, but I tested it in the latest version and it still goes on.

**Comment by Benau** [comment]
can you enable physics debug view in artist debug mode and make a video?

**Comment by adevairhpj** [comment]
The recording is not available (I'll see this later), but basically I'm colliding into this green dash in front of me.

![fortmagma-2019 11 08_12 40 13](https://user-images.githubusercontent.com/44653153/68494804-6cc33780-0225-11ea-895d-da4d6beb7760.png)

**Comment by Benau** [comment]
green object! ![](https://lihkg.com/assets/faces/pig/knife.gif)

Try svn up again and retry?

**Comment by adevairhpj** [comment]
Fixed. Closing the ticket
