### ISSUE TITLE
(Android) [minor] Story mode intro movie unskippable

### ISSUE THREAD

**Issue by psypherium** [supertuxkart/stk-code#4142]
Tested on Android 10 with STK beta

**Comment by deveee** [comment]
It should be skippable with back button on navigation bar.

And do you suggest "continue" button like in unlock screen?
![Zrzut ekranu z 2019-11-23 00-11-40](https://user-images.githubusercontent.com/5108558/69466908-37baf700-0d86-11ea-858d-72d53b4462a5.png)

**Comment by psypherium** [comment]
Oh. I do not have a back button, or a navigation bar, only a horizontal line. I will try the swipe from edge back and see if it works.

I think a "continue" button would be good.

**Comment by deveee** [comment]
I added "continue" button to the intro and end cutscenes.

I wonder if it should be always visible, or maybe only after mouse/touch/keyboard click on screen? Any opinions?
