### ISSUE TITLE
Make 'Custom settings...' button width scaleable

### ISSUE THREAD

**Issue by adem4ik** [supertuxkart/stk-code#4145]
## Description

Current 'Custom settings...' button has fixed width.
![image](https://user-images.githubusercontent.com/4707112/69625722-aa66f380-1060-11ea-86c3-6a3cc0273ea3.png)
That results cutting of the text in some translations if the translator didn't check it in game:
![image](https://user-images.githubusercontent.com/4707112/69625664-80153600-1060-11ea-876e-37462247007e.png)
![image](https://user-images.githubusercontent.com/4707112/69625624-6aa00c00-1060-11ea-9464-9c3e6c589df3.png)
![image](https://user-images.githubusercontent.com/4707112/69625684-8d322500-1060-11ea-9d50-e4f985c29e70.png)
## Steps to reproduce

1) Change language to Spanish (es), French (fr), Italian (it), etc
2) Open Options - Graphics

## Configuration

STK release version: SuperTuxKart-git20191124-win

STK Source (PPA, distribution package, official binary, etc.): https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20191124/

System: Windows 10

Graphics card: Nvidia GTX 1060

CPU: Intel Xeon E3-1270 V2

## Additional information

There is 'Apply new resolution' button in the same graphics tab and it is scaleable.
![image](https://user-images.githubusercontent.com/4707112/69626684-8c9a8e00-1062-11ea-8a48-2f97f4c1c0b6.png)
![image](https://user-images.githubusercontent.com/4707112/69626774-c370a400-1062-11ea-9d96-a5bda7e5c319.png)
![image](https://user-images.githubusercontent.com/4707112/69626839-e69b5380-1062-11ea-9f00-72a6d04e718c.png)

**Comment by dumaosen** [comment]
fixed successfully

**Comment by adem4ik** [comment]
@dumaosen can you please provide a link to commit or pull request?
