### ISSUE TITLE
Option to select ai karts (bots) from the lobby in network games

### ISSUE THREAD

**Issue by doitux** [supertuxkart/stk-code#4147]
It would be great to have the option to select ai karts (bots) from the lobby in LAN games like you can do it in local games.

**Comment by Benau** [comment]
Not interesting

**Comment by doitux** [comment]
Really sad! For some online games with less players it would be a great fun to have bots with you, like in other online games.

**Comment by Benau** [comment]
Because playing with weak bots is not fun, also you said about lan games.

**Comment by doitux** [comment]
For me it is especially when playing on my own dedicated server with friends. Is there any option in the gui to add bots there which i was just missing until now?

**Comment by Benau** [comment]
There is for lan server in 1.1 stk

Did you create private wan server?

**Comment by Benau** [comment]
![SuperTuxKart_2020-01-27-22-25-25](https://user-images.githubusercontent.com/3252341/73182388-f5ca7a80-4153-11ea-9b1f-ee6604ef899d.jpg)
This is 1.1 stk

**Comment by doitux** [comment]
I'm running a dedicated server on my private server. 
In the server config i have set: <ai-handling value="true" />

The server is also 1.1:

`[admin@huxiwe ~]# cd games/supertuxkart-1.1-src/cmake_build/bin/
[admin@huxiwe bin]# ./supertuxkart --version
[info   ] main: ==============================
[info   ] main: SuperTuxKart, 1.1.
[info   ] main: ==============================
[admin@huxiwe bin]# ./supertuxkart --server-config=your_config.xml --network-console
`
When i connect the client i click "online" --> "enter server address". Than i type the IP of my server there. 

This is how the lobby looks like: 
![lobby](https://user-images.githubusercontent.com/1719554/73184519-de23cf80-411c-11ea-9660-e52fb9ccf1d2.png)

And this is how the settings look like: 
![settings](https://user-images.githubusercontent.com/1719554/73184645-13302200-411d-11ea-8fe8-e4dd438e3e11.png)

I would love to have on options for bots there. Is there a way to get it? Any switch in the server config file i was missing?

**Comment by Benau** [comment]
Not possible because the ai process is seperated (and really complicated to add such functionality)

You need to use another terminal and run bin/supertuxkart --connect-now=127.0.0.1:2759 --network-ai=x

**Comment by doitux** [comment]
I tried this before but i get: 

`[admin@huxiwe bin]# ./supertuxkart --connect-now=127.0.0.1:2759 --network-ai=6 
[verbose  ] main: Error messages and other text output will be logged to /home/admin/.config/supertuxkart/config-0.10/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: '../../data/'
[info   ] [FileManager]: User directory is '/home/admin/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/admin/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/admin/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/admin/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '../../data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '../../data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '../../data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '../../data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '../../data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '../../data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '../../data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '../../data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '../../data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '../../data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '../../data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '../../data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '../../data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '../../data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '../../data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '../../data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '../../data/tracks/'.
..:: Antarctica Rendering Engine 2.0 ::..
FreeBSD 12.0-RELEASE-p10 hostBSD 12.0-RELEASE-p10 DMR amd64
[info   ] HTTPRequest: Sending userid=56497&token=************************ to https://online.supertuxkart.net/api/v2/user/saved-session/
[info   ] GrandPrixManager: Loading Grand Prix files from ../../data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/admin/.local/share/supertuxkart/grandprix/
[info   ] STKHost: Host initialized.
[warn   ] LayoutManager: Widget 'timeout-message' has a height of 0 (left_space = 0, fraction = 1.000000, max_width = )

[info   ] ConnectToServer: SETUP
[info   ] ProtocolManager: A 15ConnectToServer protocol has been started.
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 58524, retry remain: 3
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 58524, retry remain: 2
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 58524, retry remain: 1
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 58524, retry remain: 0
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 24498, retry remain: 10
[info   ] ConnectToServer: Trying connecting to 127.0.0.1:2759 from port 24498, retry remain: 9
`

**Comment by Benau** [comment]
Do u know what is the server port (replace with 2759), the server log will tell you the private port of server

**Comment by doitux** [comment]
`Mon Jan 27 17:06:45 2020 [info   ] STKHost: Host initialized.
Mon Jan 27 17:06:45 2020 [info   ] STKHost: Server port is 2759
Mon Jan 27 17:06:45 2020 [info   ] ServerLobby: Resetting the server to its initial state.
Mon Jan 27 17:06:45 2020 [info   ] ProtocolManager: A 11ServerLobby protocol has been started.
Mon Jan 27 17:06:45 2020 [info   ] main: Creating a LAN server 'HL-Arena'.
`
So, it seems to be 2759, right?

**Comment by Benau** [comment]
Do you run that command in the server?

**Comment by doitux** [comment]
Yes! ;-)

**Comment by Benau** [comment]
try type your public ip address in server?

**Comment by doitux** [comment]
I tried this and than i get:
[info   ] ConnectToServer: SETUP
[info   ] ProtocolManager: A 15ConnectToServer protocol has been started.
[info   ] ConnectToServer: Trying connecting to my.pub.lic.ip:2759 from port 49484, retry remain: 3
[info   ] ConnectToServer: Connected to my.pub.lic.ip:2759
[info   ] ProtocolManager: A 11ClientLobby protocol has been started.
[info   ] STKHost: Listening has been started.
[info   ] ProtocolManager: A 15ConnectToServer protocol has been terminated.
[info   ] ClientLobby: Synchronous message of type 2
[info   ] ProtocolManager: A 11ClientLobby protocol has been terminated.
[info   ] STKHost: Listening has been stopped.

The server console displays than: 
Mon Jan 27 17:37:42 2020 [verbose  ] ServerLobby: Player refused: invalid player

**Comment by Benau** [comment]
well i don't understand why your freebsd is blocking loopback connection...

you can edit your server_lobby.cpp in server
```
    if (((encrypted_size == 0 || online_id == 0) &&
        !(peer->getAddress().isPublicAddressLocalhost() ||
        peer->getAddress().isLAN()) &&
        NetworkConfig::get()->isWAN() &&
        ServerConfig::m_validating_player) ||
        (ServerConfig::m_strict_players &&
        (player_count != 1 || online_id == 0 || duplicated_ranked_player)) ||
        (peer->isAIPeer() && !peer->getAddress().isLAN()) ||
        (peer->isAIPeer() &&
        ServerConfig::m_ai_handling && !m_ai_peer.expired()) ||
        (peer->isAIPeer() && m_game_setup->isGrandPrix()))
```
to
```
    if (((encrypted_size == 0 || online_id == 0) &&
        !(peer->getAddress().isPublicAddressLocalhost() ||
        peer->getAddress().isLAN()) &&
        NetworkConfig::get()->isWAN() &&
        ServerConfig::m_validating_player) ||
        (ServerConfig::m_strict_players &&
        (player_count != 1 || online_id == 0 || duplicated_ranked_player)) ||
        (peer->isAIPeer() &&
        ServerConfig::m_ai_handling && !m_ai_peer.expired()) ||
        (peer->isAIPeer() && m_game_setup->isGrandPrix()))
```
to allow ai connection from any address

**Comment by doitux** [comment]
Thx that works!
