### ISSUE TITLE
Unclear term - nitro efficiency vs nitro consumption

### ISSUE THREAD

**Issue by adem4ik** [supertuxkart/stk-code#4149]
## Description

There are 2 names of the same thing: `nitro efficiency` & `nitro consumption`. But their meanings are quite different, and mb even opposite:
_Higher efficiency is better, higher consumption is worse._

## Steps to reproduce

1) Open 'Singleplayer'
![image](https://user-images.githubusercontent.com/4707112/69715209-5243f600-1121-11ea-98c0-1d6197758ccd.png)

2) Open 'Help' - 'Kart classes'
![image](https://user-images.githubusercontent.com/4707112/69715320-80c1d100-1121-11ea-90cb-8033b1f8e822.png)

## Configuration

STK release version: SuperTuxKart-git20191124-win

STK Source (PPA, distribution package, official binary, etc.): https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20191124/

System: Windows 10

Graphics card: Nvidia GTX 1060

CPU: Intel Xeon E3-1270 V2

**Comment by Alayan-stk-2** [comment]
The bars in the kart selection screen have a "higher is better" meaning. To avoid ambiguity, the icon is labelled "nitro efficiency" to confirm that higher is better. If it was labelled "nitro consumption", it could be assumed that a bigger bar means it consumes more nitro and is worse.

In the help, this constraint doesn't exist and the text talks directly about nitro consumption. As the text says, lower is better.

Efficiency and consumption rate are twinned concepts, the inverse of each other. I don't feel the need to change how they are presented.

**Comment by adem4ik** [comment]
@Alayan-stk Currently selection screen has:
_Mass, Maximum speed, Acceleration, **Nitro efficiency**_
While help 'Kart classes' page has:
_Mass, Acceleration, Max speed, **Nitro consumption**_

I don't understand the point of using different (inverted) terms. If **Nitro efficiency** is what the player sees while selecting the kart, it should explained in the Help pages, not the **Nitro consumption**. Otherwise it may provide critical misunderstandings.

**Comment by BlueCatYellowCat** [comment]
I agree, the help message could be modified to "Nitro efficiency - The higher it is, the more speed you get from a can of nitro. A lighter kart will have higher nitro efficiency."
This way it is immediately obvious that a higher [nitro symbol] is higher speed from nitro. While the current documentation is technically correct, it is unnecessarily confusing to define the inverse attribute instead of the target attribute.

**Comment by dumaosen** [comment]
Fix by yourself!

**Comment by BlueCatYellowCat** [comment]
> 
> 
> Fix by yourself!

It can be good to first check a change is actually wanted/needed before fixing it.
