### ISSUE TITLE
Hard to read text on a kart selection screen with Peach theme

### ISSUE THREAD

**Issue by adem4ik** [supertuxkart/stk-code#4150]
## Description

It is quite hard to read long sentences on a kart selection screen:
![image](https://user-images.githubusercontent.com/4707112/69717769-1cedd700-1126-11ea-8413-756ce7cc5653.png)

Though it looks fine for short strings like kart names:
![image](https://user-images.githubusercontent.com/4707112/69717725-05aee980-1126-11ea-896b-31a1b8961ed2.png)

## Steps to reproduce

1) Change interface theme to Peach (also Forest/Ocean)
2) Open 'Single player'
3) Move mouse arrow over locked kart

## Configuration

STK release version: SuperTuxKart-git20191124-win

STK Source (PPA, distribution package, official binary, etc.): https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20191124/

System: Windows 10

Graphics card: Nvidia GTX 1060

CPU: Intel Xeon E3-1270 V2

## Additional information
Possible solutions:
- Add a background for the text
- Draw outlined font (like the one is used on the top of that screen)
- Draw font shadow

**Comment by Benau** [comment]
I think it should be better with #4314 ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
