### ISSUE TITLE
"Missing local state" strikes back

### ISSUE THREAD

**Issue by adevairhpj** [supertuxkart/stk-code#4152]
My old problem "missing local state" came back with the latest git version. And it is again interfering with the game.

Edit: This only happened in three moments. but nothing guarantees that it cannot happen again.

stdout.log](https://github.com/supertuxkart/stk-code/files/3906626/stdout.log)

**Comment by Benau** [comment]
Can you change client_lobby.cpp near line 463 to
```
    case CONNECTED:
        if (m_start_live_game_time != std::numeric_limits<uint64_t>::max() &&
            STKHost::get()->getNetworkTimer() >= m_start_live_game_time)
        {
            Log::info("","offset %d", STKHost::get()->getNetworkTimer() - m_start_live_game_time);
            finishLiveJoin();
        }
```
and give me the log if it happens again with long missing local state?

**Comment by Benau** [comment]
hmm you seem to enter live join / spectate in a weird way (do u see missing kart selection screen when game started? (also which server did you play)

(or is that you never live join / spectate in any case?)

**Comment by adevairhpj** [comment]
> hmm you seem to enter live join / spectate in a weird way (do u see missing kart selection screen when game started? (also which server did you play)
> 
> (or is that you never live join / spectate in any case?)

No. Everything was normal before that. I was on a Frankfurt server.

**Comment by adevairhpj** [comment]
> Can you change client_lobby.cpp near line 463 to
> 
> ```
>     case CONNECTED:
>         if (m_start_live_game_time != std::numeric_limits<uint64_t>::max() &&
>             STKHost::get()->getNetworkTimer() >= m_start_live_game_time)
>         {
>             Log::info("","offset %d", STKHost::get()->getNetworkTimer() - m_start_live_game_time);
>             finishLiveJoin();
>         }
> ```
> 
> and give me the log if it happens again with long missing local state?

The change to the .cpp file gave an improvement. I will close the topic for now and reopen if I encounter any problems.

**Comment by Benau** [comment]
lol that was only meant for debug purpose...

to test more you need to live join / spectate only.... (but seems that very few players have problem with live join / spectate)...
