### ISSUE TITLE
Flashing trees and shadows

### ISSUE THREAD

**Issue by Souravgoswami** [supertuxkart/stk-code#4153]
Hi, I have noticed since the update a year ago that both my computers can't render the trees and the tree shadows correctly.

For example,
https://mega.nz/#!Aepn3QiY!31So6ZyqBMwJLeHhvGj3FlZ5YFNyco-rbimz1IK6MbY
https://mega.nz/#!pGxVVaTS!wwC96kAieks_tOOZ3n2JWyD1XkGu8DHd-mgJOzIXeMg
https://mega.nz/#!Aa4RiQqC!N_lVkdSF7qaO9I3AJPLDCd2yCEcAy-LDzO3mnhrCpMs

The video quality got reduced for some reason. But you can see the flashes of the trees...

**Comment by Benau** [comment]
So intel drivers bug are not fixed....

**Comment by Souravgoswami** [comment]
Ummm I have got the update many times, it's not yet fixed. I am running `Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz` on my PC and i3 on my laptop as well...

**Comment by Benau** [comment]
You can try use the graphic level 2 and see if it works better....

(and tbh hd4xxx may not fast for shadow when u play stk online anyway)

**Comment by Souravgoswami** [comment]
Sorry for the late reply :(
I am actually using "Custom" graphics level!

**Comment by Alayan-stk-2** [comment]
This is an old issue for a very old CPU. Hopefully, this was fixed in later Intel drivers, maybe not with how problematic driver for old Intel iGPUs have proven to be, but there is no point in still keeping track of this issue.
