### ISSUE TITLE
camera forward-up-angle in normal camera mode 

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4154]
(very-minor issue) 

Does parameter forward-up-angle works as expected ?
## Description
In kart-characteristics.xml
camera forward-up-angle="60" 
have no effect on CM_NORMAL view.

## Configuration
STK release version: git fe346196525ea2d064911787b4ca107bbed89870

**Comment by Benau** [comment]
This option is ignore if smoothing of camera is enabled (which only useful in CM_REVERSE and CM_CLOSEUP atm)

**Comment by luffah** [comment]
It shall be added in <camera/> description.

**Comment by luffah** [comment]
Too, where smoothing can be desactivated ?

**Comment by Benau** [comment]
...probably static camera is too boring for racing...

you need to hack stk yourself

**Comment by luffah** [comment]
Note : only backward up angle is used for CM_REVERSE. For CM_CLOSEUP, angle is hardcoded.
