### ISSUE TITLE
Highscores for GPs

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#416]
**Author: kinsu**

Highscores are currently shown for tracks, but not for highscores.
They could be added with a little layout change, to also show the track's screenshot and the track list.

See http://forum.freegamedev.net/viewtopic.php?f=17&t=1090&p=16846#p16846

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/360 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/360 )

**Comment by qwertychouskie** [comment]
Hmm, patch doesn't apply anymore.  Seems the files have changed since...  Does anyone know if this patch has already been applied?

**Comment by Benau** [comment]
done
