### ISSUE TITLE
Compiling of supertux kart

### ISSUE THREAD

**Issue by havenash** [supertuxkart/stk-code#4167]
Hi, I downloaded the supertux kart and tried to compile it. However, an error always pop up when I tried to compile it. Here is the error:

![error](https://user-images.githubusercontent.com/58799740/70681726-4e92a080-1cd7-11ea-9c66-06542b1d3cf3.JPG)

Hope to hear from you soon. ThankYou!

**Comment by Benau** [comment]
have you actually checkout stk-assets?

**Comment by havenash** [comment]
what do u mean checkout the assets?

**Comment by Benau** [comment]
Hmm you should askhttps://github.com/supertuxkart/stk-code/blob/master/INSTALL.md

Check for windows section, also where and have you get the dependencies folder ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by havenash** [comment]
yes. we followed this closely, however around step 7, this error that i showed above came out

**Comment by Benau** [comment]
Can you show the full error log for cmake error?

**Comment by Ninja2421** [comment]
Here it is
![yeye](https://user-images.githubusercontent.com/58808529/70702001-4c950580-1d08-11ea-87a5-aae9d2c5f142.JPG)

**Comment by Benau** [comment]
You seem to have old / multiple version of cmake installed ![](https://lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by havenash** [comment]
what should we do?

**Comment by Benau** [comment]
uninstall all cmake and install latest cmake? ![](https://lihkg.com/assets/faces/pig/hehe.gif)

**Comment by havenash** [comment]
does it matter in which drive we use? must it be C drive? or is D drive okay?

**Comment by Benau** [comment]
try install cmake in c with default location (program files) ![](https://lihkg.com/assets/faces/pig/whip.gif)

**Comment by havenash** [comment]
does installing it in different drive affect?

**Comment by Benau** [comment]
Possible

**Comment by Ninja2421** [comment]
I tried installing cmake in my C drive but it still fails 
![image](https://user-images.githubusercontent.com/58808529/70706147-5884c580-1d10-11ea-8b87-a8427e752ee2.png)

**Comment by Benau** [comment]
You compile 32bit, so please put the dependencies folder in stk-code (not 64)

**Comment by Ninja2421** [comment]
I tried putting the 32bit dependencies folder but it told me that they couldn't find any dependencies folder.
![image](https://user-images.githubusercontent.com/58808529/70707702-bd8dea80-1d13-11ea-882b-34720f307ee6.png)

So I went ahead and put the 64bit on and this is the error they give me
![image](https://user-images.githubusercontent.com/58808529/70707601-7c95d600-1d13-11ea-8093-0c6d002331bd.png)

**Comment by Benau** [comment]
Try uncheck the USE_WIIUSE option

**Comment by Ninja2421** [comment]
Thank you so much! 
Now that I can build the application, I have met with another error. Sorry for the inconveince!
![image](https://user-images.githubusercontent.com/58808529/70709137-232fa600-1d17-11ea-81c5-906ae6a9abf8.png)

**Comment by Benau** [comment]
you need to put the stk-assets folder inside D:\year 3 sem 1\internship folder![](https://lihkg.com/assets/faces/pig/wine.gif)

**Comment by Ninja2421** [comment]
the stk-assets folder is in the same folder as the stk-code 
![image](https://user-images.githubusercontent.com/58808529/70766743-b6112480-1d99-11ea-9e37-6e910d5669a8.png)

**Comment by Benau** [comment]
you seem to put the build folder in the wrong way, INSTALL.md: ```and point 'Where to build the binaries' to a new directory called build or bld inside the stk-code directory.``` ![](https://lihkg.com/assets/faces/pig/play.gif)

so your build directory should be inside stk-code instead of SuperTuxKart-dev

**Comment by Ninja2421** [comment]
oh wow thank you so much! I finally able to build it properly

**Comment by Benau** [comment]
![](https://lihkg.com/assets/faces/pig/clap.gif)![](https://lihkg.com/assets/faces/pig/dance2.gif)
