### ISSUE TITLE
Alpine Linux sysctl.h build failure

### ISSUE THREAD

**Issue by PureTryOut** [supertuxkart/stk-code#4172]
I'm trying to package SuperTuxKart for Alpine Linux. This distribution uses Musl rather than glibc and this seems to cause an issue.

When compiling Irrlicht I get the following:

```
/home/builder/aports/testing/supertuxkart/src/stk-code-1.0/lib/irrlicht/source/Irrlicht/COSOperator.cpp:20:10: fatal error: sys/sysctl.h: No such file or directory
   20 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
```

Looking at [the source](https://github.com/supertuxkart/stk-code/blob/master/lib/irrlicht/source/Irrlicht/COSOperator.cpp#L17), it includes `<sys/sysctl.h>` unless the platform is Android. However, at least on Alpine Linux (and I guess this is due to using Musl), it should be `<linux/sysctl.h>` instead, just as on Android.

The following snippet fixes the issue.
```
diff --git a/lib/irrlicht/source/Irrlicht/COSOperator.cpp b/lib/irrlicht/source/Irrlicht/COSOperator.cpp
index ba9612fc9..70d6193af 100644
--- a/lib/irrlicht/source/Irrlicht/COSOperator.cpp
+++ b/lib/irrlicht/source/Irrlicht/COSOperator.cpp
@@ -14,7 +14,7 @@
 #if !defined(_IRR_SOLARIS_PLATFORM_) && !defined(__CYGWIN__)
 #include <sys/param.h>
 #include <sys/types.h>
-#ifdef ANDROID
+#if defined(ANDROID) || !defined(__GLIBC__)
 #include <linux/sysctl.h>
 #else
 #include <sys/sysctl.h>
```

I would PR this, but it seems Irrlicht gets auto-copied and modified using some script so I'm not sure what to do here.

**Comment by Benau** [comment]
No stk irrlicht is modified and has no relation to upstream irrlicht ![](https://lihkg.com/assets/faces/pigxm/snowhat.gif)

**Comment by PureTryOut** [comment]
So I can just submit this fix then?

**Comment by Benau** [comment]
yes ![](https://lihkg.com/assets/faces/pigxm/dance2.gif)
