### ISSUE TITLE
Windows start menu folder is placed inside folder of other software

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#4175]
I installed SuperTuxKart 1.1.0-rc1 installer-64bit.exe on Windows 7.

It seems the SuperTuxKart 1.1.0-rc1 folder in the Windows start menu is being placed inside the folder of another program (Avidemux 2.7 VC++ 64bits) by default.

If i run the installer it says this by default:

    Avidemux 2.7 VC++ 64bits\SuperTuxKart 1.1.0-rc1

**Comment by scootergrisen** [comment]
Also happens with 32 bit installer.

**Comment by Benau** [comment]
other stk fans / devs can you reproduce? ![](https://lihkg.com/assets/faces/pigxm/snowhat.gif)

**Comment by scootergrisen** [comment]
Strange... now i uninstalled STK and now i dont get that when running the installer again.

Now its just:

    SuperTuxKart 1.1.0-rc1

**Comment by scootergrisen** [comment]
I guess i could have clicked Avidemux 2.7 VC++ 64bits by mistake in the list.

It seems both the 32 bit and 64 bit use the same stuff.

So whatever was used in the 64 bit also seems to be used in the 32 bit installer.

**Comment by Benau** [comment]
![](https://lihkg.com/assets/faces/pigxm/pointing.gif)![](https://lihkg.com/assets/faces/pigxm/heard.gif)
