### ISSUE TITLE
Can't tell 64 bit and 32 bit apart

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#4176]
I tested both these on Windows 7:
SuperTuxKart 1.1.0-rc1 installer-64bit.exe
SuperTuxKart 1.1.0-rc1 installer-32bit.exe

It seems both the 32 bit and 64 bit installer is being installed as if they are both 64 bit.

They both use:
C:\Program Files\SuperTuxKart 1.1.0-rc1\

Same name in Windows start menu:
SuperTuxKart 1.1.0-rc1

Running installer/uninstaller does not say if you are using 32 bit or 64 bit.

In Windows control panel where you uninstall software there is only one SuperTuxKart even though both 32 bit and 64 bit editions are installed. So if you install from there you can't seem to know if you are uninstalling 32 bit or 64 bit.

I think C:\Program Files (x86)\ is for 32 bit software and C:\Program Files\ is for 64 bit software.

Inside STK about it does not say if it is 64 or 32 bit.

Not sure if this have anything to do with missing icon/generic icon and trying to fix that by using the same path for icons:
https://github.com/supertuxkart/stk-code/issues/2538

I guess for users only installing one copy of STK this is not a big problem.
But for people like me that want to test i would be nice to easily see what is 64 bit and what is 32 bit.

**Comment by Benau** [comment]
Maybe just keep 64bit installer?

32bit only windows are rare now and there is .zip installerless for them

**Comment by scootergrisen** [comment]
Still would be nice to know what you are running.
What if people ask "What version are you running. 32 bit or 64 bit?"
How are users suppose to see that?

With the zip file you can't even tell by the file name:
SuperTuxKart-1.1-rc1-win.zip

**Comment by Benau** [comment]
In taskmanager you can see supertuxkart.exe 32bit or not

.zip supports all architecture

**Comment by scootergrisen** [comment]
Ok there seems to be separate exe's for 32 bit and 64 bit.
But in the zip file there is both.

**Comment by Benau** [comment]
It should be improved for next release, and the "They both use: C:\Program Files\SuperTuxKart 1.1.0-rc1\" should be fixed also

You can see https://github.com/Benau/stk-code/releases for preview installers ![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)
