### ISSUE TITLE
[1.1] Update Wiiuse to 0.15.5

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#4178]
A new release of Wiiuse, https://github.com/wiiuse/wiiuse/releases/tag/0.15.5, was recently released to fix TR type Wiimotes on Windows.  At this point, TR Wiimotes should now work on every major platform.  It would be great for this new release to get into STK 1.1.

**Comment by Benau** [comment]
If you can pr yourself and test in linux... ![](https://lihkg.com/assets/faces/pigxm/dance2.gif)

Then i can create windows zip for you to test too ![](https://lihkg.com/assets/faces/pigxm/argue.gif)

**Comment by qwertychouskie** [comment]
Created PR: https://github.com/supertuxkart/stk-code/pull/4186

**Comment by DoggoOfSpeed** [comment]
This can be closed now, can't it?

**Comment by Benau** [comment]
seems that qwerty has no time to test in windows! ![](https://lihkg.com/assets/faces/pigxm/play.gif)
