### ISSUE TITLE
Improving the Tutorial

### ISSUE THREAD

**Issue by CodedOre** [supertuxkart/stk-code#4187]
While the tutorial is not bad and show most of the things you need to know about playing the game, I see a few issues here:
- [x] At first, a new player will likely not find it, since it is not at an prominent spot in the menu. So it can’t help people who don’t find it. Therefore I would suggest to show an dialog asking if you want to start it when a new profile is made.
- [x] Secondly, the current state of showing text boxes with the tutorial hints disturbs the game flow, especially on mobile devices. It also don’t make a good job on mobile because it can’t point on the on-screen buttons. So, i would suggest doing it like the tutorial in [Horizon Chase](https://youtu.be/diMMEOrUvc8) by slow down the game, highlight the button (or showing the keyboard key as icon) and showing the text and confirm it by doing the action. 
- [x] Lastly, the tutorial don’t show the option for fire backwards. So, instead of shooting the crates I would suggest this:
  After picking up the power up, we could drive in an AI-Kart to shoot at. After this, a second kart would appear behind the player, and the hints would show “Fire while looking back to fire backwards” (or something similar). The AI-Karts could come from an side street on the track, which would need an adapted map, but I think they should not appear out of nowhere.

**Comment by Benau** [comment]
2 is a bit complicated and not so interesting.....

For 3 maybe just after passing the shooting boxes scene tell player to shoot the behind boxes again? (We can use some scripting to reset the boxes to orginal place when the dialog is shown)

![](https://lihkg.com/assets/faces/lm2xm/nosee.gif)

**Comment by CodedOre** [comment]
I think especially 2 would be important to improve. It is kinda annoying to have the a constant stop and go with the action. Like I said, it disrupts the game flow and lowers the quality of the tutorial.
However I know my suggestion could be complicated to implement, since it required a lot of code not used by anywhere else, so maybe there is an better way.

I know that the tutorial is something you just opens one time and then visit „never“ again, but this is the moment a new player will (or should) see at first, so I think it would be good not to scare them away with an bad presentation.

**Comment by Benau** [comment]
or use messagequeue (the thing you see for ingame online chat) to push message and only dismiss the message after the require task is acomplished? ![](https://lihkg.com/assets/faces/pigxm/snowhat.gif)![](https://lihkg.com/assets/faces/pigxm/dance.gif)

**Comment by CodedOre** [comment]
MessageQueue could do it. As i see it, we have to create a MessageQueue-Implementation for the Scripting-Engine and adapt the Script of the Map.

However, i found in the Code a `TutorialMessageDialog`, but it didn´t seem to be used right now. Or do i see something not?

**Comment by CodedOre** [comment]
So, i have tested the Tutorial with using the now implemented `StaticMessage`, and it works definitely better, without the Stop and Go of the old method. I would say that point two on my list above is solved.

So, but as I am experiment with adapting the tutorial track (so we can implement the "fire backwards" option): In the forum is mentioned that @samuncle is working on an updated version of the now used map? Is this just improving graphics or also the track layout, so would this be also something to consider? I mean, an additional straight part for the "Fire Back"-Tutorial could be helpful, since we also have to consider that the Player needs to read the hint (and could keep accelerating) and also have to look back.

**Comment by Benau** [comment]
actually i think samuncle will be busy for a while so maybe you can just go on with the old track...

**Comment by CodedOre** [comment]
So, i have created a "prototype" for an updated Tutorial, [here is the map archive](https://github.com/supertuxkart/stk-code/files/4077344/tutorial.zip), and 
[the Blender file](https://github.com/supertuxkart/stk-code/files/4077360/tutorial-in-blender.zip).

Additionally i have moved the banana- and giftbox-section a little bit forward, so I could place the "shoot behind"-section as well. Otherwise it is only a few more trigger to discard Messages.



**I would not say this is final, since i don't had the opportunity to "test" it (with someone who is not familiar with the game). There are also still some flaws:**

- Right now the "shoot behind"-section is still without a real target. And i would still prefer to have an kart as an target, since this would something where the player could train targeting as well. So, my thought here was: We could implement the Tutorial as "Follow the Leader" and set the Player as leader, which should let the AI follow the Player, until we would throw him out after it was hit by the Player.
- This is really secondary, but the "Reset Pit" has an Bridge in the Blender File. Was it planned that the Player would drive on the Bridge which would collapse? This would at least be an valid reason to fall in the pit.

**Comment by Benau** [comment]
1 is too complicated and I don't have interests to implement it, and it would require many code to make it achievable with only scripting api...

For 2 there is auto rescue everywhere in the tutorial, the only place which required manually is the one which is a trigger (the large pit), the bridge will never collapse. Do you mean something else?

**Comment by Benau** [comment]
I added one more discard message after the shooting behind trigger and committed to svn, and i think we can collect some more feedback with stk beta in google play / testflight later

you have iphone or android? ![](https://lihkg.com/assets/faces/pig/dance2.gif)

**Comment by CodedOre** [comment]
I have both, an iPhone for the daily use and an Samsung which most time just laying around...

**Comment by CodedOre** [comment]
We should maybe add some line breaks, because at some points (Skidding and shoot behind) the text needs two lines and right now it breaks not ideallly...

**Comment by Benau** [comment]
...will update soon together with ipv6 improvements! ![](https://lihkg.com/assets/faces/mouse/solution.gif)

**Comment by Benau** [comment]
With https://github.com/supertuxkart/stk-code/commit/26dbf67d53a53883190278ba144fc271c8c2a9dc now possible for 1 ![](https://lihkg.com/assets/faces/pig/dance2.gif)

Not sure speedrunners want auto disable... ![](https://lihkg.com/assets/faces/pig/smile.gif)

Also I no longer see @Fouks0 in discord! ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by CodedOre** [comment]
Well, than it should all be set! Than this can be closed.
