### ISSUE TITLE
Unnecessary Bubble

### ISSUE THREAD

**Issue by DoggoOfSpeed** [supertuxkart/stk-code#4188]
## Description
When in the profile menu, a border and a bubble overlap.
![Screenshot_20191228_233910](https://user-images.githubusercontent.com/28051112/71549761-8aae4c80-29cb-11ea-82f6-5ce4dd908149.jpg)

## Steps to reproduce
Open the profile menu, and press on your icon.

STK release version: 1.1-rc1 (STK Beta on Android)

**Comment by Alayan-stk-2** [comment]
The bubble shows the active selected player, the square shows the currently selected UI item. When you navigate elsewhere in the screen, for example have a button in the row with "ok" select, the bubble stays in place, which is useful.

On mouse hover, the bubble stays showing the selected player while the square highlight the hovered player. It's a bit less good on touchscreens or keyboard, but overall the benefits are worth it.
