### ISSUE TITLE
[Suggestion] Move achievements to the Profile Menu

### ISSUE THREAD

**Issue by DoggoOfSpeed** [supertuxkart/stk-code#4189]
I would suggest moving the Achievement menu from here:
![Screenshot_20191228_235117](https://user-images.githubusercontent.com/28051112/71549873-ab77a180-29cd-11ea-8f34-566288930bb6.jpg)

To the profile menu:
![Screenshot_20191228_235425](https://user-images.githubusercontent.com/28051112/71549880-bc281780-29cd-11ea-9e91-35e2de7726ac.jpg)
## Reasons:
1. The achievement icon is very similar to create Grand Prix.
2. The achievements are Profile specific.
3. There are already too many icons in the bottom bar.

**Comment by CodingJellyfish** [comment]
I don’t think so. Icons inside user menu are for configuring, while achievement is not.

**Comment by Alayan-stk-2** [comment]
Going into settings -> players to access achievements is too cumbersome and would make the achievements page hidden for most players. Who would check there?

Its current location is good, and if the icon similarity with the GP editor is really a problem, the solution is a new icon.
