### ISSUE TITLE
Overstretched Icon (Mobile only)

### ISSUE THREAD

**Issue by DoggoOfSpeed** [supertuxkart/stk-code#4205]
## Description
The icon for accelometer is very streched in the pause menu. 
![Screenshot_20200108_101310](https://user-images.githubusercontent.com/28051112/71961354-cd5bfa00-31ff-11ea-95ee-87f144226fa0.jpg)

## Steps to reproduce
Open a match
Open the pause menu
Change your controls to accelerometer if they aren't already.

## Configuration
Huawei p20 lite
Android 9.0

STK release version: 1.1

**Comment by deveee** [comment]
Because it sets proportion to gyroscope_icon.png which is 512x512 and accelerometer icon is 256x512... Will fix later.

**Comment by deveee** [comment]
Fixed in 11cac8f63193ffd23755e5372756759de9426a86
