### ISSUE TITLE
AI players in LAN games not working

### ISSUE THREAD

**Issue by jwf1776** [supertuxkart/stk-code#4207]
I am not able to get AI players to appear in my LAN games in 1.1.0-rc1.

(Multi-player STK was one of the highlights of family xmas! thankyou!!)

Through the 'local networking' 'create a server' GUI, when I set the "number of AI karts" to some number like 3, no AI players appear in my 'normal race'.  (Human LAN players are able to join as expected).

RC1 change log indicates there is some new AI multiplayer functions but it is unclear how to activate this.

I note that this issue appears related to issue #4147.

I experimented with setting the `ai-handling value="true"` value in my server-config.xml but this did not change the result.

I note that it is unclear in the NETWORKING.md which (if any) server functions require a separate '--network-console' program instance or if setup through the multiplayer LAN game GUI gives the same results.

## Steps to reproduce
Through the GUI, 'local networking' -> 'create a server' GUI, set the "number of AI karts" to some number like 3.

## Configuration

STK release version:  windows x64 1.1-rc1

STK Source: official binary

System: windows 10 1909
Graphics card: old radeon
CPU: 4 core athlon

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```
[stdout.log](https://github.com/supertuxkart/stk-code/files/4035799/stdout.log)
```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Can you try the latest 1.1 binary? ![](https://lihkg.com/assets/faces/pig/dance.gif)

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.1/

**Comment by Benau** [comment]
now next version the ai no longer use process to start so it should always be connectable, you can try this preview zip:
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200312/SuperTuxKart-git20200312-win.zip/download

![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
