### ISSUE TITLE
Possible oversight in the Pumpkin Park track

### ISSUE THREAD

**Issue by Rami-Slicer** [supertuxkart/stk-code#4209]
## Description

On Pumpkin Park (and quite possibly other tracks), some walls on the track appear to be magnetic, causing karts to get totally stuck on the walls:
![Screenshot_20200109_215333](https://user-images.githubusercontent.com/40865625/72124663-31c7a800-332b-11ea-98e6-70533d093427.png)

## Steps to reproduce

1. Play in Pumpkin Park
2. Get a kart into the cul-de-sack area after the tunnel
3. Force it to touch a wall there with it's wheels oriented towards the wall
It might stick and not come even when cupcakes or bowling balls are used.

## Configuration

STK release version: 1.10

STK Source: Official Binaries

System: Kubuntu 19.04

**Comment by Benau** [comment]
duplicated of #1807
