### ISSUE TITLE
Enhancement request : allow to be spectator on full servers

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4221]
STK release version: 1.0

Spectate race and soccer match can be really interesting, unfortunately if a server is full, you cannot join to spectate. Does the option to allow guest to spectate on full server already been discussed ? Some opinion about performance issues or whatever ?

**Comment by Benau** [comment]
that's enet limitation

not so interesting to work on it atm...

**Comment by luffah** [comment]
I think many players could be interested.
Without changing enet, there could be a solution by attributing a both max players and max spectators (what is occur in real life...) server parameters, enet will only know a max number of logged users. 
If spectator mode is not managed by enet, it shall realizable.

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/dogxm/bye.gif)![](https://cdn.lihkg.com/assets/faces/pigxm/bye.gif)![](https://cdn.lihkg.com/assets/faces/mousexm/bye.gif)![](https://cdn.lihkg.com/assets/faces/catxm/bye.gif)![](https://cdn.lihkg.com/assets/faces/cowxm/bye.gif)https://github.com/supertuxkart/stk-code/pull/4689
