### ISSUE TITLE
motion steering doesn't work with 8bitdo sn30pro+ controllers

### ISSUE THREAD

**Issue by jg00dman** [supertuxkart/stk-code#4234]
All other buttons seem to work but it doesn't appear to be possible to assign motion control.

**Comment by Benau** [comment]
you need to wait until i rewrite gamepad code before putting stk on steam....

**Comment by jg00dman** [comment]
That sounds exciting... btw me and the kids are enjoying this game so much thanks!

**Comment by Benau** [comment]
Are you linux or windows user?

**Comment by Benau** [comment]
now it's sdl2 based controller so you need to rely on sdl2 for its support....
