### ISSUE TITLE
On PC, keys are often unresponsive

### ISSUE THREAD

**Issue by Cheddered-Off** [supertuxkart/stk-code#4235]
Hi,

I bought a refurbished laptop and installed windows 10 pro on it as a fresh install.  STK was one of the first things I installed, but it was version 1.0, now upgraded (although the "About" section still says it is 1.0, the rest of the game does not).  I am using a Dell Latitude E6540.  I am using the keyboard as input, no peripherals connected other than external HDD.  The only thing is that it's native resolution is 1366 x 768 pixels.

Since version 1.0 I have noticed that sometimes the keys seem inactive.  I first noticed when going very past, so thought I was just skidding...something that had never happened in previous versions and something I did not like either.  But there seemed more to it?  Then I noticed it happening when I was not going fast. I would press the arrow key, even release the other keys and yet I would just go straight on.  It seems when it happens, it is when I press three keys at a time, and the only solution is to release all the keys.

Now tonight I just found something new.  While playing Alpine-2 (Single Player - Standard - Tux - Novice - Normal Race), I noticed that keeping the up arrow depressed, twice caused Tux to slow to a halt.  No matter how hard the key was pressed, the game seemed unaware of the keyboard?  Again the only solution was to release all of the keys, when the keyboard was instantly responsive again.

The problem seems almost random, in that some things seem more likely to make it happen, but I cannot find anything that has reproduceabiltiy - At least not so far.

Downloaded the windows compiled binary from STK.

The graphics card is an Intel HD Graphics 4600,  The Laptop is using i7-4810MQ at 2.8GHz (not overclocked), with 8GB RAM.

[stdout.log](https://github.com/supertuxkart/stk-code/files/4296433/stdout.log)

[config-0.10.zip](https://github.com/supertuxkart/stk-code/files/4296438/config-0.10.zip)

Thank you for any help in finding out what this annoying problem is.

**Comment by Benau** [comment]
Maybe related to keyboard faq?
https://supertuxkart.net/FAQ

**Comment by luffah** [comment]
Yes, it looks like keyboard ghosting.

I got some issue with keyboard events too (mostly in network), but to restore state (removing my hands from keyboard was not enough), i had to rehit the key that didn't acknowledged the key release (KEY_UP). This does not seem to be only ghosting of keys.

Unfortunately, i didn't find a test case from this experience.

**Comment by Cheddered-Off** [comment]
Aaah, thanks for the help, even if it is bad news. I had read of keyboard ghosting, but never came across it before. So I did not pay that much attention to what I read. It did sound and feel like that was what was going on - Like the keyboard was locking up, because too many keys were being pressed. But I wanted to be sure because I have never seen it before and hoped I was wrong. I will have to get a USB keyboard then.

Thank you all for the cogent help!

**Comment by Alayan-stk-2** [comment]
Closing as it's a hardware limitation at play here.
