### ISSUE TITLE
[Potential] unintendedshortcut in X591

### ISSUE THREAD

**Issue by TheMinefighter** [supertuxkart/stk-code#4236]
## Description
I've found a shortcut in X591 by driving off-track; Rounds using it are counted; I believe it is not intended; it could be (if unintended) be fixed easily by increasing the size of the invisible wall placed there. Here is footage of it:
[SuperTuxKart 2020-03-06 17-59-32_Trim.zip](https://github.com/supertuxkart/stk-code/files/4299412/SuperTuxKart.2020-03-06.17-59-32_Trim.zip)
The same shortcut is available when using the left option; in my experience a tiny bit faster.
I've successfully used it in ranked races and it provides an advantage.

## Steps to reproduce
Ride the path shown; use mid air drifting to land in the right angle.

## Configuration
STK release version: 
1.1
STK Source (PPA, distribution package, official binary, etc.): 
Windows (offical buildl)
System: 
Win 10
Graphics card: 
IGP/Radeon Vega
CPU: 
R7 3700U

**Comment by Alayan-stk-2** [comment]
Hello !

Thank you for the report, it is appreciated.

However, this particular shortcut is well-known already, and deemed to have a good enough balance between difficulty and time-saved to be worth keeping.

If you notice other things that look incorrect, you might ask around the STK's IRC or discord channel to know if it's already known or intended, and if not open new tickets.
