### ISSUE TITLE
Don't kick the current host of the server for inactivity.

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4237]
Don't kick (the proprietary or) the current host of the server for inactivity, it just means the player is waiting or looking infos on the net.

**Comment by Benau** [comment]
are you waiting in lobby?

**Comment by Benau** [comment]
Btw you discord for benau if small question ![](https://lihkg.com/assets/faces/pig/cook.gif)

**Comment by luffah** [comment]
no, it is usual to warm up while waiting someone arrive in lobby. So starting to play alone

**Comment by Benau** [comment]
Only server created in gui ok?

The public server out there is not good place to do that...![](https://lihkg.com/assets/faces/pig/arrested.gif)

**Comment by luffah** [comment]
Yes, it is on the server created in gui.

Sorry for the lack of details.

**Comment by luffah** [comment]
As you want ...
