### ISSUE TITLE
How to implement a new camera type for soccer (with patch)

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4238]
## Description
Many idea of camera improvement exists for soccer mode :
 - mirror to see behind
 - a camera as public for spectator
 - add items (bubblegum is nice in soccer mode) // oups it is not linked to camera
  - ...

Here i got an example of camera suitable to soccer mode that show the ball everytime.
How (where) shall i add this camera ? using subtype of camera normal or designing a new camera model.
And how shall i add the setup of the camera type ? (in a perfect world maybe it shall be switchable during the match... but with which key ... )

```patch
diff --git a/src/graphics/camera_normal.cpp b/src/graphics/camera_normal.cpp
index 9cdcb9592..5a976aefe 100644
--- a/src/graphics/camera_normal.cpp
+++ b/src/graphics/camera_normal.cpp
@@ -24,6 +24,8 @@
 #include "input/device_manager.hpp"
 #include "input/input_manager.hpp"
 #include "input/multitouch_device.hpp"
+#include "modes/world.hpp"
+#include "modes/soccer_world.hpp"
 #include "karts/abstract_kart.hpp"
 #include "karts/explosion_animation.hpp"
 #include "karts/kart.hpp"
@@ -299,13 +301,30 @@ void CameraNormal::update(float dt)
         core::vector3df current_target = (m_kart->getSmoothedXYZ().toIrrVector()
                                        +  core::vector3df(0, above_kart, 0));
         m_camera->setTarget(current_target);
-    }
-    else // no kart animation
+    }     else // no kart animation
     {
         float above_kart, cam_angle, side_way, distance, cam_roll_angle;
         bool  smoothing;
         getCameraSettings(&above_kart, &cam_angle, &side_way, &distance, &smoothing, &cam_roll_angle);
         positionCamera(dt, above_kart, cam_angle, side_way, distance, smoothing, cam_roll_angle);
+
+        World* world = World::getWorld();
+        SoccerWorld *soccer_world = dynamic_cast<SoccerWorld*>(world);
+
+        if (soccer_world) {
+          m_camera->setNearValue(1.0f);
+
+          Vec3 ball_pos = soccer_world->getBallPosition();
+          Vec3 kart_pos = m_kart->getSmoothedXYZ();
+          Vec3 to_target=(kart_pos-ball_pos).normalize();
+          if ((kart_pos-ball_pos).length() < 10) {
+            ball_pos = (kart_pos - (to_target * 10));
+          }
+          ball_pos = (kart_pos + (ball_pos*2))/3;
+          m_camera->setTarget(ball_pos.toIrrVector());
+          Vec3 cam_pos = kart_pos + Vec3(0, above_kart*2, 0) - (to_target * distance * 2);
+          m_camera->setPosition(cam_pos.toIrrVector());
+        }
     }
 }   // update
```

**Comment by Benau** [comment]
if your patch is meant for a camera as public for spectator then they don't belong to here

you need a new camera mode (soccer spectate) so in ClientLobby::changeSpectateTarget after it loop through all karts it falls into there (cam->setMode(Cameraxxx)) ![](https://lihkg.com/assets/faces/pig/wine.gif)

I have no interests to add more keys to stk now especially reserved for future minimun key to work with some gamepad (switch joy con / siri remote!) ![](https://lihkg.com/assets/faces/pig/hehe.gif)![](https://lihkg.com/assets/faces/pig/hehe.gif)![](https://lihkg.com/assets/faces/pig/hehe.gif)

**Comment by luffah** [comment]
Yes it is first to spectate, but for gaming too.
Agree for the keys.

I was wondering about an option to setup a dynamic camera for soccer (that follow the ball WHEN it is out of screen) like in some games with complex camera management.  (an ui option ?)

So i have to declare a new CM_MODE. And put setMode in client_lobby.cpp.
I don't really agree if i put a dynamic view that is common with normal view of a kart when the ball is in front... but in a first time i should just make an extra view for each kart when current_idx goes out of index rang.

**Comment by Benau** [comment]
i don't see much sense for soccerball view in gaming and i don't want to add complex option to the ui (you already know the ball position in minimap) 

Or you meant handle when the ball fly out of the soccer field completely? (we have invisble wall in official field and most addon field so it won't fly too far)

actually there is a top or first person view for that purpose (in artist debug mode)

maybe you can bring riso "triangle arrow" to minimap for ball too....

you can adjust the kart list vector with ball and sort them according to distance to current target ![](https://lihkg.com/assets/faces/pig/dance.gif)

**Comment by luffah** [comment]
Complex option ? ok  . I note a bool option "Dynamic camera for soccer" is complex.

**Comment by Benau** [comment]
Is there any real usage other than fun?

**Comment by Benau** [comment]
If you want to see the ball when it's out of screen, why dont you just turn your kart or look back

**Comment by luffah** [comment]
Move the kart : Slower than just looking and in soccer mode it can be an error (autogoals, rebounce...) , you move your car (or bike) to look at right side ?

Anyway, a dynamic camera is to tiring (my opinion after testing). It is only something in spectator mode.

**Comment by luffah** [comment]
> Is there any real usage other than fun?

The entertainment.

**Comment by Benau** [comment]
lol you only have such entertainment when u are not in game (spectate)

when u are in game you already have too much to concentrate, esp when u look at the ball you may not be able to move / react with your kart quickly

not sure if you think riso "triangle circle" indicator is useful lol

**Comment by risostk** [comment]
I think a mirror to see behind is very useful, not only in soccer. May need double rendering?

**Comment by luffah** [comment]
> I think a mirror to see behind is very useful, not only in soccer. May need double rendering?

I was looking at this subject while i thought about trying something easier. Being usually enthusiastic about new ideas, i have some doubt about the addition of a mirror. 

Where to place it ? (race gui to rethink)
Is it really an improvement of fun ? (never seen a kart game with a mirror // all is in the minimap)

If you have a clear idea, i d like to see a screenshot of what it could look like.

_Sorry to put forum subjects in the git_

**Comment by risostk** [comment]
I was thinking about the one in NFS: https://user-images.githubusercontent.com/26389402/29680977-969a63a2-8906-11e7-86ac-7c2dff8b631a.png or in Kartrider: https://strategywiki.org/wiki/File:KR_GUI_1.jpg
I think in soccer it can provide a wider view of what's going on nearby (so more accessibility). For example, when trying to stop the ball/enemy using the back of the kart.
Agree it may not be the first thing to do, since we already have the look-behind function.

**Comment by luffah** [comment]
@risostk  Not convinced, given it shows GUI from other games.
Both of examples have a framed minimap, which will poorly adapt to soccer mode.

_Crazy* Kartrider_ have a very interesting mirror, that is in fact a blinking alert of the karts behind. That's why it can be placed at bottom-left and readable. Moreover the position is realistic.  This game have many interesting GUI ideas.

The issue still to rethink User Interface. Maybe  it imply to reduce or remove  the faces of characters on standings list.

I agree that the view of for soccer shall be wider, especially for looking backward (steering wheel is very sensitive when you drive in reverse; you need a more global view to drive in this case) ... wider and higher to have a better look on other karts angle.
Changing camera fov, or changing position of the camera can solve the problem too. (personnal setting)

**Comment by risostk** [comment]
I currently have an fov=110, it helped a bit, but not much. The minimap could help to know what's going on around. But imo it is not perfect.
- Putting the minimap in the middle: the blocked view is not nice, even it is transparent.
- Putting the minimap on the left: the eye needs to move between the front view and the minimap quite often, also not very nice.

Btw, I never see you play online. There are lot of good soccer players. You should try :D

**Comment by luffah** [comment]
@Benau Thanks for tips
@risostk I close the issue (but keep this in my bookmarks)
