### ISSUE TITLE
Kart direction or moving direction?

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4242]
The arrow in soccer field seems to give the moving direction (pink arrow) instead of the kart heading direction (black arrow). This is more obvious when skidding, see the following picture. But kart->getTrans() should provide the transformation of the kart, which gives the heading, not the moving direction (trans should have value even when kart does not move)?

<img width="619" alt="Screen Shot 2020-03-11 at 5 42 01 PM" src="https://user-images.githubusercontent.com/4726939/76471404-884f7200-63c0-11ea-9087-f3f4d9595ab9.png">

## Steps to reproduce

Go soccer and try to skid.

## Configuration

STK release version: git8b197b4a

**Comment by Benau** [comment]
The skidding rotation is graphical only..

**Comment by risostk** [comment]
Ok, but this visualized kart rotation does affect the angle when using items. For example, when shooting a cake or bowling, it will go along the black arrow, not the pink.
