### ISSUE TITLE
Minor text issue on battle restart

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4243]
Reported on the forums:
> So I Was Playing Some SuperTuxKart,
And Going Into Battle Mode.

> But I Think I Found A Typo.
The Restart Button Said "Restart Race".
It Should Be "Restart Battle" Right?

**Comment by luffah** [comment]
On last version, (played solo mode) restart button just say "Restart" and "Setup new Race",  but in client lobby it says "Start Race" .

**Comment by STK-FabianF** [comment]
The easiest thing would be replacing the word "race" by "game" in all of these strings, I guess.

**Comment by Alayan-stk-2** [comment]
But "game" is incorrect for actual races. A "game of football" is ok, a "game of formula 1" or a "game at Le Mans" when speaking about actual car races is awful.
