### ISSUE TITLE
Slow text rendering on some GPUs

### ISSUE THREAD

**Issue by icecream95** [supertuxkart/stk-code#4246]
On some GPUs (e.g. the Arm Mali range) text rendering is very slow.

For example, just enabling the story mode timer can increase frame times by more than 2ms.

Because the texture coords etc. are stored in uniforms, every 2D image drawn requires a separate GPU job which the kernel has to keep track of, and also the GPU can only draw one vertex and fragment job at once.

<br>

When inside the track portals on the overworld, the track name and other text causes the framerate to halve, and there are around 1,500 vertex / fragment job pairs per frame for 2D image drawing.

It seems that some text is rendered with many 2D images drawn per character, which explains how there can be 1,500 job pairs for less than 200 characters of text.

Even just pre-rendering characters to a new font texture, without trying to batch 2D image drawing, should be enough to remove most of the overhead from text drawing. 

<br>

STK release version: 1.1

STK Source: Compiled from Github release source tarball

Graphics card: Mali t760 (Panfrost driver)

CPU: RK3288

**Comment by Benau** [comment]
The font texture is already a glyph page

Do u think instanced rendering will help?

**Comment by icecream95** [comment]
The main problem is that some text is rendered with many 2D image draws per character:

![text](https://user-images.githubusercontent.com/29191311/76605809-fc7f4680-6575-11ea-888d-179b4c0af490.png)

**Comment by Benau** [comment]
thats for the black border

Let me see if instanced rendering will help a bit...

**Comment by icecream95** [comment]
The border and fill could be rendered to a second font texture, so that only one 2D image draw would be needed for each character.

**Comment by Benau** [comment]
The border and fill could be rendered to a second font texture is not practical for stk because we are already using glyph page per 1 type of font

can you try my private fork:
https://github.com/benau/stk-code
(https://github.com/Benau/stk-code/commit/fae119e69850f08debb80a2f21b975137ba11be6)

This will batch as much as quad to single vertex buffer as possible and bind 1 glyph page and draw them at once, and this improved performance a lot for all of my old devices

**Comment by Benau** [comment]
![SuperTuxKart_2020-04-26-20-26-16](https://user-images.githubusercontent.com/3252341/80307621-c384f380-87fc-11ea-98e9-85ce69363e56.jpg)
![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

Now it's in origin/batch btw

**Comment by Benau** [comment]
seems that every device i have tested have faster performance so this branch is merged

hope this is quicker for your driver ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by icecream95** [comment]
This does mostly fix the problem, but there is still a small performance dip of a couple of fps when a lot of text is rendered.
