### ISSUE TITLE
Cannot go fullscreen

### ISSUE THREAD

**Issue by amicharski** [supertuxkart/stk-code#4250]
## Description
I have an Acer Predator Helios 300 with a NVidia GeForce GTX 1060, my OS is Ubuntu KDE Neon, and when I go into options to enable Fullscreen under graphics, I have to confirm the resolution within 10 seconds, but the buttons to confirm it have no text on them and nothing happens when you click them.

## Steps to reproduce
Options > Graphics > Check off Fullscreen > Click on Apply new resolution

## Configuration

STK release version: 0.9.3

STK Source (PPA, distribution package, official binary, etc.): Discover Software Center

System: Acer Predator Helios 300

Graphics card: NVidia GeForce GTX 1060

CPU: Intel Core i7-8750H @ 2.20 GHz

RAM: 15.5GB

Operating System: Ubuntu KDE Neon 5.18

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
stk 0.9.3 is very old..... can u try stk 1.1?

**Comment by amicharski** [comment]
I am a beginner to Linux and I use an Ubuntu KDE Neon. How could I install the latest version of the game? When I install it from Konsole via ‘sudo apt install supertuxkart’, it installs v0.93.

**Comment by Benau** [comment]
try ```sudo snap install supertuxkart```
