### ISSUE TITLE
Wrong tracks are shown in unlock notification

### ISSUE THREAD

**Issue by mikeweilgart** [supertuxkart/stk-code#4254]
## Description

I recently downloaded STK 1.1 and decided to play through the story mode.

I had 75 points and had just unlocked Oliver's Math Class and Off the Beaten Track (GP).

I then played Off the Beaten Track in Intermediate mode, and won all 5 races.  On the challenge completion page, it showed that I thereby earned 21 points out of a possible 24; I got a silver trophy; and...it showed "tracks unlocked!" as Oliver's Math Class and Off the Beaten Track (GP).

The tracks it SHOULD have shown as unlocked - Candela City, Gran Paradiso Island, and Around the Lighthouse - did not appear on the challenge completion page.  (I determined which tracks should have been shown by looking at the story mode map afterwards; I now have 96 points total.)

## Configuration

STK release version: 1.1

STK Source (PPA, distribution package, official binary, etc.): PPA (Ubuntu 18.04)

System: Lenovo ThinkPad L540

(Further hardware info should not be relevant; seems to be a logic error.  In any case it's the default hardware that came with this laptop.)

## Additional information

[stdout.log](https://github.com/supertuxkart/stk-code/files/4396499/stdout.log)

**Comment by Alayan-stk-2** [comment]
Testing confirms https://github.com/supertuxkart/stk-code/pull/4980 fixes this
