### ISSUE TITLE
Kiki and Sara the racer karts doesn't match physics bounding box

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4260]
(stk v1.1)

## Description
Kiki and Sara the racer karts doesn't match physics bounding box.
This bug make Kiki and Sara the racer the less used kart in soccer mode. However Kiki's kart have a nice bounding box for soccer mode : its ratio 2 (width) / 3 (length) is nice for front attack. 

Why it is an issue ? the karts that sucks for soccer are female gendered. Too, Kiki and Sara represents major projects (especially for game makers). Aside, Hexley which represents a non free project have a good kart.

This fact sucks.

## Steps to reproduce
Setup artist debug mode, select the kart, start soccer mode, activate "Physics Debug" and observe the ball doesn't touch the side of the kart.

## Suggestions
(sorry, i suck at blender·ing...)

Add F1 style car bumper for Kiki.
Either design a true motorbike or a quad for Sara.

**Comment by Benau** [comment]
it's because of this
```
    // improve physics for tall karts
    if (kart_height > kart_length*0.6f)
    {
        kart_height = kart_length*0.6f;
    }
```

changing this affects network and will not be done anytime soon, also some stk fans think sara has a small hitbox is good for battle

no policital correctness please... ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif)

**Comment by luffah** [comment]
just don't kick me away like that, with network arguments.

I m talking about what we see and what does occur.
The hit box is a rectangular cuboid (with chamfers) and it is really embarrassing when your kart looks like a triangular prism.

**Comment by octocody** [comment]
Do it yourself then

**Comment by Benau** [comment]
The correct fix is support more shape, otherwise....
![Mingbai-idioms-snake-with-feet-author](https://user-images.githubusercontent.com/3252341/78657310-2a4c7680-78fb-11ea-90ba-b393c588602f.jpg)

**Comment by luffah** [comment]
ambitious

**Comment by Benau** [comment]
btConvexHullShape *hull = new btConvexHullShape(); in kart createPhysics may allow creating triangular shape

Need time to hack it.........
