### ISSUE TITLE
Allow password re-enter in multiplayer

### ISSUE THREAD

**Issue by rugk** [supertuxkart/stk-code#4272]
When you join a multiplayer server, after you enter the password, you get back to the "global network" screen.

What should happen: Allow me to re-enter password instantly.

**Edit:** wrong password, of course

**Comment by Benau** [comment]
only when password is wrong?

**Comment by rugk** [comment]
Yes, of course. If it is correct, you get into the lobby, so that should be no problem. :smiley:

**Comment by Benau** [comment]
Fixed in cc9980f2a498758731f89e3110ab5388d4ac9301 ![](https://cdn.lihkg.com/assets/faces/pig/drum.gif)
