### ISSUE TITLE
Missing bubble gum in egg hunt

### ISSUE THREAD

**Issue by mglisse** [supertuxkart/stk-code#4276]
## Description
In egg hunt mode, it seems like presents never give you bubble gum anymore. Was it considered useless? It can have various uses. For instance, before the pencil was added to Oliver's class, dropping some gum on the table so it would slow you down next time was the most natural way to get the egg on the table. Dropping gum and switching it to nitro can also be a way to get nitro on tracks that don't have it. I could imagine the shield being helpful in some contexts as well. I think reenabling bubble gum for egg hunt would enable some creative puzzles.

## Steps to reproduce
Play any track in egg hunt mode, find a blue box, and wait to see what bonus you get.

## Configuration
STK release version: 1.1
STK Source (PPA, distribution package, official binary, etc.): debian package
System: Linux
Graphics card: Quadro M2000M
CPU: i7-6820HQ

**Comment by Benau** [comment]
This mode is more like speedrunner tool now (items are useless for them)

You can see if Alayan cares ...

**Comment by Fouks0** [comment]
Not really sure why there are Item Boxes in Egg Hunt at the first place... They should be disabled here...
Unless we make possible to catch Eggs with Bowling Balls, in this case we should get only Bowling Balls from these Boxes...

**Comment by Benau** [comment]
Fouks no discord / irc! ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

https://forum.freegamedev.net/viewtopic.php?f=17&t=7773#p75662

Not sure stk fans want to hiker happy so when he installed stk someday later... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

Or stk is for teenagers anyway! ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

Btw egg has no collision shape for you to do that ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

**Comment by Alayan-stk-2** [comment]
Easter Egg mode currently use the soccer weight list rather than a custom weight list.

But even with a custom weight list, the problem remains that having the final egg hunt time dependent in any way on the item boxes is undesirable, so by design the powerups you get from the boxes have to be useless.

**Comment by qwertychouskie** [comment]
One option would be to use a seeded pRNG, so the items you get are the same every egg hunt run.  Another would be to just make the boxes only give one type of item (speed boost?)

**Comment by pedropaulosuzuki** [comment]
Not having the boxes could be interesting for 2.0. Helps to get players to focus on the main objective better.

But maybe they could only give the speed boost or something, idk.
