### ISSUE TITLE
`alphablend`: Render as lit, allow using pbrdata

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#4277]
Currently, the `alphablend` shader renders in a way similar to `unlit`, i.e. the light in the area doesn't affect the look of the transparent item.  The `alphablend` shader should render as a "lit" object and allow assigning a `pbrdata` map, as it will significantly improve the appearance of e.g. glass, by allowing it to reflect light as glass should.

**Comment by Benau** [comment]
you can create custom shader anyway?

**Comment by qwertychouskie** [comment]
1. Most/(all?) transparent objects would look better with lighting/PBRData than they do currently (without lighting)
2. Shaders are a big black box to me :P
3. From an initial poking, `combine_diffuse_color.frag` seems to be invoked directly in the CPP (though I may have no idea what I'm talking about lol)

**Comment by Benau** [comment]
not so interesting......

**Comment by Benau** [comment]
also the alphablend blends directly after combine diffuse so adding pbr data support require a lot of change....
