### ISSUE TITLE
Music titles should be translatable

### ISSUE THREAD

**Issue by huftis** [supertuxkart/stk-code#4281]
## Description
The titles of the music that plays in the background on each track are not translatable. They are descriptive English titles, and should be translatable, just like the level/track titles are (the music titles are sometimes even identical to the track titles). Here are a few examples of the music titles:

Scottish bagpipes
Ravenbridge Mansion
Landing in gran paradiso
SuperTuxKart Theme

(See also #4280 for making the *formatting* of the music titles translatable.)

## Steps to reproduce
Look in the .pot file. Note that none of the music titles are listed.

## Configuration
STK release version: 
Latest Git version.

STK Source (PPA, distribution package, official binary, etc.): 
Git

**Comment by Benau** [comment]
not sure auria / alayan can think of artistic french translation of Scottish bagpipes lol!

**Comment by Benau** [comment]
Hmm seems that some other language translator which plays stk also thinks this is useless (more difficult for stk fans to find song)


If more people has negative feedback this commit will be removed... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by huftis** [comment]
@Benau, I’ll make three quick points:

1. I too am a translator of SuperTuxKart, I would prefer to have the titles translatable; that’s why I opened this issue. Since some translators prefer to have the entire SuperTuxKart game translatable, it’s not ‘useless’. :)
2. If some translators prefer not translate the music title, they are still free too *not* translate them (i.e. to copy the English string to the translation). The same goes the level names and other parts of the game. So having the strings translatable is not a problem, but having them not translatable, for the translators who prefer them to be translatable, is.
3. The argument that having the titles translatable is a weak one. You can’t easily find the songs just by searching for them, e.g., by searching for ‘Scottish bagpipes’. To find a song, you’ll have to master SVN, find the SVN repository, checkout it out, figure out the music directory, and then find the correct .ogg file. Find the correct song out of the handfull of music files there is the *easy* part. And even then, having the English song name is of little help; the song ‘Scottich bagpipes’ is stored in `celtic.ogg`.

**Comment by Staszek2312** [comment]
Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>
________________________________

**Comment by Benau** [comment]
Most .music has the same file name as title anyway...

Also kimden said:
```
also i think josh woodward won't be happy with that kind of attribution
```

And not all stk translators play stk, if the translation source is confusing for them they will write some werid translation (check transifex issue)...

So unless alayan / auria strongly like this idea i will remove this commit in next translation source update

![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by BrunoRamalhete** [comment]
The music titles can be translated, altough they're not the most important thing to be translated in the game. The music titles translation can become confused in some languages. If this is difficult for some translators the commit can be removed.
