### ISSUE TITLE
No more kart held  powerups in soccer mode ?

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4284]
With recents commits (https://github.com/supertuxkart/stk-code/commit/0db86f6d52f2df9cea350141b59b06327fea2075), kart held powerups no more appear in soccer mode.

## Description
```shell
git checkout 0db86f6d52f2df9cea350141b59b06327fea2075
cd _build
make
#  check the option is on
grep karts-powerup-gui ~/.config/supertuxkart/config-0.10/config.xml 
#        karts-powerup-gui="true"
# launch stk
./bin/supertuxkart
# ... no more kart help powerups ?
```

**Comment by Benau** [comment]
you need to turn on in config.xml for soccer power or use f7 in artist debug menu

Because too many players find this blocking view
