### ISSUE TITLE
Textures not working for levels created with STK Editor

### ISSUE THREAD

**Issue by druedin** [supertuxkart/stk-code#4285]
## Description

When I create a new level with the STK editor, textures are not applied properly.

Expected behaviour: Level loads with the textures selected in the STK editor.

Observed behaviour: The splatter image ("splatt.png") is used as texture all over. Oddly, the textures of the ready-made objects (e.g. houses) are correct.

## Steps to reproduce

1. open SuperTuxKart Track Editor (Beta v0.03, bundled with STK 1.1)
2. create new track
3. use spade to create elevation in middle of track (helps see issue)
4. add simple drive line around elevation
5. save and export track
6. open SuperTuxKart
7. select track, play

In this case, splatt.png is all black, and the surface is all black.

4.1 use brush to add texture (helps see issue)
4.2 add one of the ready-made objects (helps see issue)

![stkeditor](https://user-images.githubusercontent.com/2881033/81339714-e641c280-90ae-11ea-911b-1a47a4060a3a.png)

In this case, splatt.png is colourful, and the surface is this image repeated.

![stkgame](https://user-images.githubusercontent.com/2881033/81339777-fce81980-90ae-11ea-828d-46f67576a78f.png)

The issue is visible at any graphic level in the settings

The level is fully playable.

## Configuration

STK release version: 1.1

STK Source (PPA, distribution package, official binary, etc.): https://supertuxkart.net/

System: Ubuntu 18.04.4 LTS

Graphics card: Intel Corporation HD Graphics 620 (rev 02)

CPU: Intel Corporation Xeon E3-1200

Gamepads/keyboards models if related to the issue: built-in keyboard

## Additional information

I'm not sure what to look for in stdout.log; GLDriver are all present, GLSL supported, STKTexManager complains about the missing screenshot.jpg from the test level and that no music was defined. Then there is "Material: Cannot determine texture full path: genericshadow.png".

The materials.xml looks superficially legit.

**Comment by Benau** [comment]
the stk track editor is in beta stage and not officially supported (also it's never bundled in any case)

that's because it uses splatting material which is removed in 1.0, you can try copy tracks/overworld/splatting.frag and sps_splatting.xml to your exported track folder and see if it works

**Comment by druedin** [comment]
Thanks for the clarification. No luck with copying the two documents.
As for "bundling", in my bin-64 and bin folders, there's an executable supertuxkart-editor (dated 14 November 2017).

**Comment by Benau** [comment]
Can u paste  the materials.xml here?

**Comment by druedin** [comment]
<materials>
  <material name="splatt.png" shader="splatting" splatting-texture-1="dirt.jpg" splatting-texture-2="grass2.jpg" splatting-texture-3="rock_brown.jpg" splatting-texture-4="sand2.jpg"/>
</materials>

**Comment by Benau** [comment]
stk 1.0 uses this rule:
```
 <material name="rock_grey.jpg" shader="splatting" uv-two-tex="splat2.png" tex-layer-2="dirt.jpg" tex-layer-3="grass2.jpg" tex-layer-4="snow.png" tex-layer-5="rock_grey.jpg"/>
```

you can adjust that materials.xml to those layout

or you can just use blender 2.79 to create track which is better supported anyway

**Comment by druedin** [comment]
I'm afraid I can't get this to work.
(1) If I put the line you have posted into materials.xml, I get a warning in the console, which makes sense, as there is no file "splat2.png" in the folder. The warning I get is: "[warn   ] Material: Cannot determine texture full path: splat2.png", but it still shows the "splatt.png" from the STK Editor (as in the image I posted).
(2) If I change uv-two-tex="splat2.png" to uv-two-tex="splatt.png", there is no warning in the console, and I get the picture above.
(3) if I copy the file "splatt.png" into "splat2.png" (now there are two png in the folder) and set the materials.xml to "splat2.png", I still get the picture above.
(4) if I delete the splatt.png (now there is only splat2.png in the folder) and have materials.xml point to splat2.png, I get an entirely white world. In the console I get the warning "[warn   ] Material: Cannot determine texture full path: splatt.png", but materials.xml doesn't refer to this file at all.
(5) if I put the absolute path of the texture files, I get "[warn   ] Material: Cannot determine texture full path: /home/xyz/SuperTuxKart-1.1-linux/data/textures/rock_grey.jpg"
(6) copying the textures to the folder doesn't make a difference.

#3 and #4 puzzle me a bit, because in these cases no file in the folder of the track refers to splatt.png, yet STK is looking for it.

Blender is a different kind of beast...

**Comment by Benau** [comment]
...or you can just use 0.9.3 to play stk track produced by track editor

**Comment by druedin** [comment]
Many thanks. I guess we'll leave it at this.
