### ISSUE TITLE
The game crash when another fullscreen window is focused with some tracks

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4286]
The game crash/freeze when another fullscreen window is focused **while playing** (Alt+Tab during race).

The bug occur with addons Tournament Field and Nitro Soccer Field,
when **fullscreen** mode and **depth of field blur** are activated both _(the game have to be 
restarted for test)_.

Logs tends to reveal that the game literally freeze.
Music continue, but no other sound effect is played. 

This may be a bug with the track itself. Or not.

_Edit : i got this bug sometimes in lobby too_

## Configuration
STK Source : (recent version)
code git 5d3ccb54b07e6bde742a8692992d8a7f8aea4aa2
assets svn r18272
        
System: Debian 10.1

Graphics card: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)

CPU: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz

## Additional information

Last lines of stdout.log:
```
[verbose  ] RaceManager: Nb of karts=8, ghost karts:0 ai:7 players:1

[info   ] Track: Overall scene complexity estimated at 28
[info   ] ShaderFilesManager: Compiling shader: /work/Games/kart/supertuxkart.git/data/shaders/importance_sampling_specular.frag
[info   ] ShaderFilesManager: Compiling shader: /work/Games/kart/supertuxkart.git/data/shaders/sky.vert
[info   ] ShaderFilesManager: Compiling shader: /work/Games/kart/supertuxkart.git/data/shaders/sky.frag
[info   ] ShaderFilesManager: Compiling shader: /work/Games/kart/supertuxkart.git/data/shaders/dof.frag
[info   ] ShaderFilesManager: Compiling shader: /work/Games/kart/supertuxkart.git/data/shaders/passthrough.frag
```

**Comment by Benau** [comment]
When loading your track?
![](https://cdn.discordapp.com/attachments/376132466152308738/708903028828143636/f4d529b61d6fd5e6.webp)

**Comment by luffah** [comment]
Procedure (without video config part): 
- solo mode
- select kart
- select soccer mode
- select track (Tournament Field or Nitro Soccer Field)
- start race
- go towards the ball 
- when at ~3m of the ball, hit keys Alt+Tab to focus to a fullscreen Firefox window
- release keys, and do again Alt+Tab to focus to SuperTuxKart

**Comment by Benau** [comment]
guess this your window manager bug...

**Comment by luffah** [comment]
Really common config here :
```
Package: xorg
Version: 1:7.7+19ubuntu7.1

Package: xfwm4
Version: 4.12.5-1ubuntu0.18.04.1
```

**Comment by luffah** [comment]
(i'll  look on the computer on which the issue is raised in the week-end)

**Comment by Benau** [comment]
no reply.... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by luffah** [comment]
i know ... i rarely use the mentioned laptop

**Comment by luffah** [comment]
sdl version works better

**Comment by luffah** [comment]
I close the issue since i fail to reproduce it :(
