### ISSUE TITLE
Add Indicator for Items Coming up from Behind

### ISSUE THREAD

**Issue by TheMadScientist1234** [supertuxkart/stk-code#4288]
Like in Mario Kart Wii or Crash Team Racing there is a indicator for items about to hit you. It doesn't have to be all items (for example it would ruin the point of bowling balls if you got an indicator about them). But it would allow for the bubblegum to be more useful as opposed to just an item for the basketball when you check behind in first.

**Comment by Benau** [comment]
Alayan suggested something like this ago and rejected because it makes the screen too busy, and i think the show other powerup give you some hints already which should be enough
