### ISSUE TITLE
Limit Usernames to a reasonable length

### ISSUE THREAD

**Issue by Riesi** [supertuxkart/stk-code#4295]
## Description
The UI becomes pretty unreadable with players that paste entire Wikipedia articles as names.
![image](https://user-images.githubusercontent.com/27691485/82689661-24b4b100-9c5b-11ea-99e5-4ae8f49a0255.png)

## Steps to reproduce
Paste a really long message as an offline name.

Thanks in advance!

**Comment by Benau** [comment]
why you would want to play with someone who is trolling in lan servers....

**Comment by Benau** [comment]
```
        core::stringw name;
        data.decodeStringW(&name);
        if (name.empty())
            name = L"unnamed";
```
you can try add something like if (name.size() > 15) name = name.subString(0, 15); in server_lobby.cpp around 3548 (git stk-code) and see if it's fixed in server side

![](https://cdn.discordapp.com/attachments/588002848051036169/713346678823845938/freehk.webp)

**Comment by Riesi** [comment]
Yes, that limits the username for other clients. Something along those lines could be merged.
Thanks!

**Comment by Benau** [comment]
so that works for you?

**Comment by Riesi** [comment]
yes, I added it after the empty check.
```
core::stringw name;
data.decodeStringW(&name);
if (name.empty())
    name = L"unnamed";
if (name.size() > 15)
    name = name.subString(0, 15);
```

**Comment by Benau** [comment]
see https://github.com/supertuxkart/stk-code/commit/f316a83c63ac0b1bde2267c9d8d382ce13fe4b21
