### ISSUE TITLE
Numbers of placements?

### ISSUE THREAD

**Issue by 7wells** [supertuxkart/stk-code#4302]
Is it possible to add/show the numbers of the placements left of the usernames when a race is finished?

When there are 20 karts/players on the lap, this would help to see one's own placement. Yeah, I can also count with me fingers. 😉 So if this is not worth it, no problem at all.

Maybe I shall learn more about GitHub and coding to propose some lines myself. 🤗

**Comment by Benau** [comment]
usually when race finished it goes result screen directly?
or you meant in online race where you can change camera target (and you can know in gui too)

btw i suggest you use our forum for feature request, this is a bug tracker

**Comment by 7wells** [comment]
I answered in the forum (thanks for reminding me), so my comment here can be closed. Thank you.
