### ISSUE TITLE
Server ownership

### ISSUE THREAD

**Issue by ddrv** [supertuxkart/stk-code#4303]
## Description

I host a server. When I am not on it, the owner is the one who first connected to the server.
When I connect to my server, I do not become the owner.
Is this a bug or a feature?

## Steps to reproduce

1. Host a server (not ownerless)
1. Do not connect to it
1. Wait for someone to connect to the server (he will automatically become the owner of the server)
1. Connect to the server
1. Become a slave in your kingdom

## Configuration

|Parameter|Value|
|---|---|
|version|`1.1`|
|source|[compiled](https://github.com/supertuxkart/stk-code/tree/68e21856cfec9b0984f15a40251011740cd2a5cb) by `cmake` with `-DSERVER_ONLY=yes` option|
|CPU|`x86_64`|

**Comment by Benau** [comment]
the server created with console is "public domain", only the server created in gui is always fully controlled by yourself

**Comment by Benau** [comment]
btw why you are creating a server with password if it's intented to be play (publicly)?

**Comment by ddrv** [comment]
@Benau This is the server for our company.
Can I hope for the option of returning ownership when connecting to the server?

**Comment by Benau** [comment]
actually the server owner in game only handles the start of each game and kicking of players... if you are real server owner you can kick players in console anyway (or with the sqlite database)

it has very much less power than you think

btw I suggest you use lan server instead and your company collegue can just type stk.ddrv.ru (or whatever address) in enter server address to connect, so you don't even need online account to play

we will regularly clear private server in the list (if there are too many of them)

**Comment by ddrv** [comment]
@Benau we used a lan server, but then a pandemic started and we switched to remote mode. We are no longer connected by a local network.

**Comment by Benau** [comment]
it's still connectable as long as it has a public address (lan server == doesn't poll stk-addons database for connection (for dealing with firewall), it still listens to 0.0.0.0:2759 in enet)
