### ISSUE TITLE
Xbox One S Controller which works perfectly cannot connect to SuperTuxKart.

### ISSUE THREAD

**Issue by ZibiCat** [supertuxkart/stk-code#4311]
Hello,

I've been trying to use an Xbox One S controller connected via USB to play SuperTuxKart. I have downloaded it from here; 

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/git20200604/SuperTuxKart-git20200604-win.zip/download

The controller either doesn't appear in input settings or doesn't accept any button presses.

The controller works fine on anything else; any source game (valve) and Dolphin emu to name a few things it works fine on.

When it does appear it's called "Controller (Xbox One For Windows)".

The contents on it inside input.xml are below;

![image](https://user-images.githubusercontent.com/35573770/84793376-e9549a80-afec-11ea-97d8-81f4c7a074d6.png)

Any help getting it working would be greatly appreciated. Thanks a ton! If you need any more info just ask. :)

**Comment by Benau** [comment]
maybe deve can make a simple sdl2 app to test ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif)

**Comment by Benau** [comment]
Also not sure ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif)can ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) benau/master...

**Comment by Benau** [comment]
Actually something like this already exists ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
https://generalarcade.com/gamepadtool/

Can you try the windows version and report result? ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by ZibiCat** [comment]
I can't even select it via the app, it doesn't show up. :(

**Comment by 7wells** [comment]
Have you tested your controller with the Windows 10 tool? You can invoke it by entering **joy.cpl** in the Windows search box.

**Comment by Benau** [comment]
so seems that sdl2 doesn't support your controller..... ![](https://cdn.lihkg.com/assets/faces/rip/mouse.gif)

**Comment by ZibiCat** [comment]
Yeah, it works with joy.cpl, that's a bummer. Thanks.
