### ISSUE TITLE
Weird Tab behavior

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4313]
## Description
Update 3:
Here is a video: https://youtu.be/scELt5ywrpk

Update 2:
I checked all older STK versions: 0.7, 0.7.1b, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.1. This issue exists in all releases since 0.6.2.
Before release 1.0, this issue is barely noticeable. But since 1.0, it is quite noticeable, especially with the new Coal skin.

-------
Update:
This is also an issue for official skin.
![Screenshot from 2020-06-18 21-45-20](https://user-images.githubusercontent.com/4726939/85091458-0d5eda00-b1ad-11ea-8231-ffbb6c2ccc6c.png)
![Screenshot from 2020-06-18 21-45-23](https://user-images.githubusercontent.com/4726939/85091465-1059ca80-b1ad-11ea-8d69-109d81d548c5.png)

------------------------------
The 'down' state of a Tab is lost when other Tabs are focused. This happens for both tab and verticalTab.
For example, here the 'neutral' state is filled black, the 'focused' state is a purple bar on the left, and the 'down' state is filled purple.
The first time the Option screen is opened, the 'General' tab is in the 'focused' state, even it is selected by default. When I move the mouse to any of the checkboxes, the 'General' tab becomes 'down' state.
![Screenshot from 2020-06-17 22-38-14](https://user-images.githubusercontent.com/4726939/84975528-49ca0180-b0eb-11ea-8ec3-09f79553a138.png)

When I move the mouse to the 'Audio' tab, the 'General' tab becomes 'focused' state, see blow.
![Screenshot from 2020-06-17 22-20-30](https://user-images.githubusercontent.com/4726939/84974949-e7bccc80-b0e9-11ea-993f-a26fe84fdb78.png)

For me, this behavior is weird, thus this issue.

## Steps to reproduce

1. Use a skin that you can distinguish different tab state 'neutral', 'focused', and 'down'.
2. See the description before.

## Configuration

STK release version: git 65b13cf

**Comment by auriamg** [comment]
<element type="tab" state="focused" image="tab_focus.svg"
<element type="tab" state="down" image="tab_focus.svg"
focus and down both use the same image
they should probably be different?

**Comment by risostk** [comment]
Hi auria, thanks. It is not a setting problem. Actually the official skin behaves the same. I have updated the description above.

**Comment by auriamg** [comment]
Ok but I fail to see the issue here? One state is meant to indicate that the tab is selected, the other state is meant to indicate that the mouse is over. I don't see any abnormal

**Comment by risostk** [comment]
Hi, let me try to explain it more carefully:
The tab has three states: neutral, focus (mouse is over), and down (the tab is selected). In official skins, neutral and down states use the same image, so let's focus on this scenario and the Coal skin right now. In the Coal skin, the focus state has a white border.
1. The first time the Option screen is opened, it is like this. You can see the General tab has a white border, which means it is at the focus state. Notice that my mouse is not on the General tab.
![Screenshot from 2020-06-19 19-40-01](https://user-images.githubusercontent.com/4726939/85187376-dcda7700-b264-11ea-8637-47f3387728bb.png)
2. Then I move the mouse to a checkbox, you can notice that the white border on the General tab disappears. Actually the General tab is at the down state right now.
![Screenshot from 2020-06-19 19-43-17](https://user-images.githubusercontent.com/4726939/85187420-35aa0f80-b265-11ea-905c-096fd18307a5.png)
3. Then I move the mouse to another tab, both the Audio and General tabs becomes focused, indicated by the white border.
![Screenshot from 2020-06-19 19-44-59](https://user-images.githubusercontent.com/4726939/85187468-7b66d800-b265-11ea-86c2-00632ef88c00.png)

I don't know if this is the behavior you expect. What I expect is that the selected tab (aka. the General tab) remains selected, until another tab is selected, not jumping between the selected and down state.

This jumping behavior is quite noticeable with my skin, where I use a colored button for the down state and a black button with a thin left line for the focus state. The jumping between color and black is quite annoying. That's why I make the down and focus state share the same image. If you want to reproduce it with my [skin](https://github.com/risostk/stk-skin), you need to change to
<element type="tab" state="down" image="tab_focus_down.svg"

**Comment by OmarElKhatibCS** [comment]
Hello It doesn't behave the same here , on my machine it work normal as it should.

**Comment by risostk** [comment]
Hi, thanks. I am using the one built from latest git. Also, I can confirm that I can reproduce the same behavior with STK beta in Google Play and the one in testflight iOS.

**Comment by Alayan-stk-2** [comment]
I've noticed this weird behavior a long time ago. Not critical, but annoying. Some tweaks would be useful.

**Comment by CodingJellyfish** [comment]
I tried to fix it, but I found that leave it as it is is quite OK, since one of the foci represents keyboard and the other one represents mouse.

**Comment by CodingJellyfish** [comment]
Closed as the comment above.
