### ISSUE TITLE
Feature request: separate brake and reverse buttons

### ISSUE THREAD

**Issue by JamesPeters667** [supertuxkart/stk-code#4318]
During braking, as the kart stops its forward motion it automatically reverses. In some circumstances, that reverse motion may be unintended. When combined with the direction you're steering, that reverse motion can result in an awkward transition to steering in the wrong direction. 

Imagine driving forward while steering right, and wanting to completely stop the kart but keep the steering wheel pointed to the right. As you continue "past" stopping and automatically transition into reverse, that rightward steering direction (while in reverse) spins the kart in the other direction. There's currently no way to just "hold down on the brake" and be guaranteed the kart won't "steer in the opposite direction" when the kart transitions from forward to reverse motion, since brake is the same button as reverse.

Having a separate brake button is what I'm requesting.

The current combined brake/reverse button is ok as it is. Alongside a separate brake button, a person would be able to use it as just a reverse button (after they've finished braking), or to use that reverse/brake combination button if they want.

**Comment by 7wells** [comment]
Interesting topic!

I do not know by the top of my head, but does the yellow icon on the right side not show the current speed, so one can release the brake just in time, i.e. when the speed is zero before reverse starts?

And how about STK on mobile devices where forward, neutral, and reverse are shown on the left hand side? How is it would be this affected?

**Comment by JamesPeters667** [comment]
If my eyes have to leave the primary focus area (where I'm driving) to look at the speed indicator, it's likely I'll collide with an object or possibly leave the track in that situation. I only need to brake "hard" when I'm suddenly in trouble and want to react quickly.

Plus I use a modified xml configuration which makes the game about 50% faster most of the time. :) 

I don't know how this would affect mobile, or if it would at all. The ability to have separate brake and reverse buttons shouldn't prevent the possibility of having them combined. It's also possible that the reverse function could be the current function: brake until forward motion stops, but then go in reverse. The only separate button that would be required is braking, since that's the button I'd want to make exclusive in its operation. (There's no danger in hitting reverse instead of brake while moving forward, if they perform the same function.)

**Comment by Benau** [comment]
We need to have a uniform control for mobile and desktop STK, and i don't think it's possbile to add more control there due to fingers ![](https://cdn.lihkg.com/assets/faces/pig/pointing.gif)

Also please use forum for feature request ![](https://cdn.lihkg.com/assets/faces/pig/pointing.gif)
