### ISSUE TITLE
Pressing the "select" key during GP result is bringing up the "abort GP" dialog

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4326]
There are two main UI issues : 
- When the select button (not escape button) is pressed, the expected behavior in this situation is to speed up results display, if the game allows such a speed up. The abort screen should only pop if the input set to work as back/escape is pressed.
- The dialog default option is "yes" (abort, throwing away the previous race results) instead of "no" (closing the dialog box). This means that just spamming the "select" key/button will exit the GP. With "no" as a default, it would bring up the dialog and then close it, requiring a deliberate left or right key press to switch the option to "yes".

**Comment by dlrudfh** [comment]
Do you mean that when the abort confirmation message pops up, is it correct that you want the cursor to default to the cancel button like the attached picture, not the existing yes button? And do you want to set this only in the GP abort window?
![1234](https://user-images.githubusercontent.com/80889873/142864054-8affc061-540f-41cc-ba1e-f9b98af4c807.PNG)

**Comment by Benau** [comment]
actaully after https://github.com/supertuxkart/stk-code/commit/93ab5a75c1d2b7145c78498da2c0efdd1a7b0a71#diff-b5ef91ce7cb209efdc1b47f68b81fda920687fc6d0d48215ac2b8d53c095b74b and latest commit it is no longer an issue ![](https://cdn.lihkg.com/assets/faces/pig/cut.gif)
