### ISSUE TITLE
The "blur effect" selector isn't always set to disabled when using graphics level <= 2 (old renderer)

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4327]
The UI still prevents increasing the spinner's value above 0.

Setting graphics level to 3 and back to 2 correctly disables the blur effects level spinner.

The spinner isn't also correctly disabled when accessing graphic options from the in-race menu.

**Comment by Benau** [comment]
not sure alayan mind remove "motion blur" in the future anyway because no stk fans seem to like and it (and it's name confusing) ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

and we can improve depth of field so it look better for quality side ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Alayan-stk-2** [comment]
Motion blur and depth of field are common movie-derived video game settings that in most situations make the game look worse and harder to play. It makes sense to keep them for those who like it, but increasing the main graphical settings shouldn't ever enable effects that arguably make the game look worse for a majority of player while lowering performance (FPS).

**Comment by Benau** [comment]
btw motion blur and dof can be live-disabled / enabled anyway

maybe when we ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) vulkan stk we can allow as many option as possible for live adjusting! ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

**Comment by 7wells** [comment]
Will STK with Vulkan still work on Amazon's Fire TV (4K) Stick?

Is it possible to let STK adjust the settings, so they fit best to the hardware? (a "gold middle" between max. FPS and best GFX effects)

**Comment by Benau** [comment]
maybe something like this ![](https://cdn.lihkg.com/assets/faces/pigxm/dance.gif)
```
    if (!found)
    {
        //I18N: custom video settings
        gfx->setCustomText( _("Custom") );
    }

    // Enable the blur slider if the modern renderer is used
    getWidget<GUIEngine::SpinnerWidget>("blur_level")->
        setActive(UserConfigParams::m_dynamic_lights);
    updateTooltip();
} // updateGfxSlider
```
