### ISSUE TITLE
Buggy camera configuration

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4335]
I did nothing in my camera configuration and just clicked apply button, but my camera position changed. 
Using Huawei M6
![Screenshot_20200723_102359_org supertuxkart stk](https://user-images.githubusercontent.com/35170687/88247079-0e64b900-cccf-11ea-90ad-5fac3e013b87.jpg)
![Screenshot_20200723_102413_org supertuxkart stk](https://user-images.githubusercontent.com/35170687/88247038-ed9c6380-ccce-11ea-9f6c-7fba83bed746.jpg)
For steps to reproduse see the video below. 
https://videos.supertuxkart.net/videos/watch/0697b6f0-ef09-4018-9247-8515be37beb0

**Comment by Benau** [comment]
Can you post your dialog screenshot?
