### ISSUE TITLE
Mouse input does not work when stk 1.2 rc1 runs on Xwayland

### ISSUE THREAD

**Issue by glaubersm** [supertuxkart/stk-code#4339]
## Description
Mouse clicks have no effect when I run stk 1.2 rc1 on Wayland session of KDE Plasma 5.19.3 desktop environment.

## Steps to reproduce

use a linux distribution running KDE Plasma desktop environment
start Wayland session of KDE Plasma desktop environment
run stk 1.2 rc1 (my stk runs on Xwayland, not natively on Wayland)
click on any button: nothing happens

## Configuration

STK release version: 1.2 rc1

STK Source (PPA, distribution package, official binary, etc.): 
tar.xz file downloaded from sourceforge.com

System: Arch Linux

Graphics card: 00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

CPU: intel celeron G1820

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Hmm this needs sdl2 fixing

**Comment by Benau** [comment]
Or try SDL_VIDEODRIVER=wayland for native wayland of sdl2 stk

**Comment by glaubersm** [comment]
Mouse input works when stk runs natively on Wayland. Thanks.
But stk can not be maximized when running in windowed mode.
Is this a known issue?

**Comment by Benau** [comment]
window resizie is only possible in game or main menu because guiengine limitation

**Comment by Benau** [comment]
in any case report this bug to sdl2 so it can be fixed upstream (or deve!)
