### ISSUE TITLE
Can't rebind controls when using a Steam Controller

### ISSUE THREAD

**Issue by mikeage** [supertuxkart/stk-code#4340]
## Description
I'm currently playing SuperTuxKart using Steam Controllers. However, I can't remap any buttons; as soon as I select a button, it immediately gets set to Axis 8, even though I didn't choose that axis (and don't appear to have the axis mapped to any buttons!)

The steam controllers (which only work if I add the game to Steam and run from there) are detected as XBox controllers

If I run with --gamepad-visualisation, I can set that it's permanently active.

Modifying input.xml directly works. 

## Steps to reproduce
Add STK to Steam as a non-steam game.
Open "Big Picture Mode"
Set controller preset as "Gamepad"
Launch STK
Options -> Controls -> XBox, try to remap a control.

## Configuration

STK release version: 1.1

STK Source (PPA, distribution package, official binary, etc.): win64 installer from SF

System: amd a8-6600k

Graphics card: amd a8-6600k

CPU: amd a8-6600k

Gamepads/keyboards models if related to the issue: Steam Controllers

## Additional information
stdout.log:
```
TBD -- will add soon
```

input.xml:
```xml
TBD -- will add soon
```

**Comment by Benau** [comment]
Try this? https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.2-rc1/SuperTuxKart%201.2.0-rc1%20installer-64bit.exe/download

**Comment by Benau** [comment]
Btw it may even work here without using steam because sdl2 has hidapi

**Comment by mikeage** [comment]
When run from within Steam, each controller is detected separately (as XInput, not an XBox controller), and can be customized in the UI without any problems!

Outside of Steam, multiple controllers are not detected as unique devices, and while they function for navigation (but not for driving), they do not appear in the "Controls" section; only Keyboard 0 is shown. 

I'm closing this, as the main issue is apparently already resolved in the tip. Thanks!
