### ISSUE TITLE
Rename the "modern" skin

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4344]
The name "modern" implies that our other themes (including the default one) are somehow obsolete or outdated.

This is not something that we want, so another name should be found.

Ping @qwertychouskie

**Comment by risostk** [comment]
How about 'Cartoon', since this theme is more cartoon looking.

**Comment by Alayan-stk-2** [comment]
The "Cartoon" name has been chosen.

**Comment by qwertychouskie** [comment]
Cartoon seems like a perfect name :)
