### ISSUE TITLE
Have a transition animation between normal and jump kart animations

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4353]
As pointed out by D_ft Kid on Discord, the kart instantly transitions from one to the other and back, which doesn't look very good.

Having some decent estimation of when the kart will back on the ground may be helpful, as if the transition animation from normal to jump takes too long, it might not work very well (the transition back can happen once touching the ground so it's less of an issue). Alternatively, ensuring the transition animation is short enough would do.

**Comment by Benau** [comment]
https://drive.google.com/file/d/1sxSMvC5h42-5kiGvz-czQLbMnkk3H1XW/view
![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

**Comment by Benau** [comment]
even soccer works now ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
https://drive.google.com/file/d/1pzE3sBrOvqvZoKANwq2AeImSXCSvhTTP/view
https://drive.google.com/file/d/1sAso5JQRDR2mW05L2FnEmzdeq5481rHH/view
