### ISSUE TITLE
PC Mod Support? Ex: Adding new karts, racers, etc

### ISSUE THREAD

**Issue by ThisNekoGuy** [supertuxkart/stk-code#4359]
## Description

Was just thinking it would be cool to have custom characters and karts as mods but implemented in a way that doesn't break online support :p

**Comment by Alayan-stk-2** [comment]
The game already support addon karts.

On many servers, it's possible to use an addon kart even if other players don't have it, the only downside is that they'll see you as Tux.

**Comment by ThisNekoGuy** [comment]
Apologies, I'm new to the game and didn't realize <_>
