### ISSUE TITLE
Fullscreen minimizes when losing focus

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#4360]
## Description

When playing Stk, I have a second monitor that I use for other stuff, notably online while waiting that everyone presses Ready in a Lobby. It used to be fine but now, Stk minimizes when it loses focus, which is annoying as I cannot read the Lobby's messages and need to restore the "window" each time to continue playing.

## Steps to reproduce

Play in Fullscreen on 1 monitor out of 2 or more, make Stk lose focus by doing something with the other screen.
There is no issue if playing windowed.

## Configuration

STK release version: 1.2, maybe a few commits later...
STK Source (PPA, distribution package, official binary, etc.): GitHub
System: Debian 10
Graphics card: Rx 560
CPU: Ryzen 7 3700X

## Additional information

```
..:: Antarctica Rendering Engine 2.0 ::..
[info   ] IrrDriver: OpenGL version: 4.5
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Radeon RX 560 Series (POLARIS11, DRM 3.36.0, 4.19.0-10-amd64, LLVM 7.0.1)
[info   ] IrrDriver: OpenGL version string: 4.5 (Core Profile) Mesa 18.3.6
```

**Comment by Benau** [comment]
try
```
	if (CreationParams.Fullscreen)
		SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0");
```
in CIrrDeviceSDL.cpp ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Fouks0** [comment]
That seems to work fine :D !

**Comment by deveee** [comment]
I'm not near the computer atm but it should be possible to use
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
before launching STK, so no need to recompile

**Comment by Benau** [comment]
Lol fouks should know that invulnerbility cannot exist in stk online design! ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif)

**Comment by Benau** [comment]
Oops look the wrong column names sorry, someone reported fouks "invulnerbility hack?" lol
