### ISSUE TITLE
create ARM64 release for windows

### ISSUE THREAD

**Issue by dwcares** [supertuxkart/stk-code#4363]
## Description
Windows supports ARM64 builds on devices like Surface Pro X. [Windows on ARM docs](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm)

**Comment by Benau** [comment]
maybe possible after vulkan

**Comment by Benau** [comment]
will you willing to help test later (have such device?) ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Benau** [comment]
can i build with llvm-mingw arm(64/32) without UWP?

**Comment by Benau** [comment]
Hmm if https://forum.level1techs.com/t/i-didnt-expect-windows-on-arm-to-support-opengl-or-vulkan-yet-i-am-still-disappointed/126339 still holds true today then it's not going to happen...![](https://cdn.lihkg.com/assets/faces/lm2/abomb.gif)

If your company ⁦❤️⁩ opensource so much then please make a vulkan to directx bridge ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Benau** [comment]
@dwcares do you have an arm windows device to test?

With https://github.com/Benau/stk-code/commit/988dc399d9be750ba24844788131c8cb2328a44c it should be possible to compile

I can give you a precompiled binary to test ![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210428-win.zip ![](https://cdn.lihkg.com/assets/faces/cow/hehe.gif)

run directly the stk-code/build-mingwa64/bin/supertuxkart.exe ![](https://cdn.lihkg.com/assets/faces/cow/plan.gif)

it's compiled with LLVM MinGW aarch64-w64-mingw32-* ![](https://cdn.lihkg.com/assets/faces/cow/gold.gif)

**Comment by Benau** [comment]
we have an installer now too: https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20210430-installer-aarch64.exe
