### ISSUE TITLE
Leaving and rejoining an online FFA game will make you lose your points obtained before

### ISSUE THREAD

**Issue by STK-FabianF** [supertuxkart/stk-code#4365]
## Description
In online Free-For-All games, if a player leaves the game and later uses the live join button to rejoin, he will start from zero again never minding how many points he already had before. In my opinion, this is an issue that should be fixed. It just happens that people get kicked from a game for high ping, get disturbed in real life for a few seconds and so on and leave the game or are even forced to do so for such reasons. The player didn't do anything bad at all, so there is no reason for him to have to start from zero after having done a good game before.

## Steps to reproduce
1. Join any online FFA game.
2. Do some hits and watch your count.
3. Leave the game (into lobby or leaving the server).
4. Rejoin it using the live join possibility and see your count being back to zero.

**Comment by Benau** [comment]
I don't want to bloat server code to store just your point

**Comment by STK-FabianF** [comment]
This issue probably should be reopened, because as far as I'm aware there hasn't been any change in the main game code. Some forks apparently have workarounds, too.
The way it's handled in main game STK is simply a major issue in my opinion and I'd appreciate if someone was able to find a fix or workaround.

**Comment by Alayan-stk-2** [comment]
Leaving a FFA game and then rejoining it seems like a very very niche use case. Stopping to play the game for some time because one is disturbed is common, choosing to quit the server is another matter. Sure, you'd give easy points to others by not moving, but that seems fair enough for being AFK.

There would also potentially be ways to abuse a full rejoin system that remembers your full points, by strategically denying points to opponent.

**Comment by STK-FabianF** [comment]
It's not as niche as you think. Sometimes connection to server is lost for some reason, and most servers also kick after some certain time of inactivity.
Also since you lose your points for going back to lobby, players rather stay in the game despite being afk and therefore serve as a "point farm" for other players.
Abusing is a possibility I didn't consider indeed. Maybe the better solution is to deduct a point for leaving the game, just like it's done for hitting a banana as well. The way it's handled currently is the worst of all imo.

**Comment by Alayan-stk-2** [comment]
Full rejoin support with a point deducted for leaving the game seems fair enough. I have more urgent things to work on, but I would be open to the idea of merging a patch that does it if someone wants to provide it.
