### ISSUE TITLE
UBPorts port?

### ISSUE THREAD

**Issue by Qiangong2** [supertuxkart/stk-code#4371]
## Description

What is required for STK to work on UBPorts? Looking at the code, clickable should be able to compile the linux version fine, but it also needs mobile controls (being a mobile OS). Also, some targets use Wayland (such as the Pinephone), and others use Mir (Halium-Based devices). 

This discrepancy only applies to arm64 devices, as all arm32 devices are halium-based. So really, 3 different versions of STK would need to be created.

**Comment by Qiangong2** [comment]
Okay, I started working on it, but now I get an error when using cmake on freetype:

https://paste.ubuntu.com/p/WtmtJ6rFhs/

Any help would be appreciated

**Comment by Benau** [comment]
From irc i assume you succeed now

**Comment by Qiangong2** [comment]
Not quite, but it looks like the issue is more on the irrlicht end than STK specifically as we're having similar issues porting minetest

**Comment by Benau** [comment]
for the record you don't need X11 at all in current stk, because sdl2 does the window creation

**Comment by Benau** [comment]
minetest irrlicht is so much different than stk's

**Comment by Qiangong2** [comment]
> minetest irrlicht is so much different than stk's

Then maybe it isn't due to irrlicht if your version fully supports wayland. Keep getting a libvorbis error too, even though it is installed
