### ISSUE TITLE
Capture player moves and trends

### ISSUE THREAD

**Issue by yahavb** [supertuxkart/stk-code#4376]
## Description

This is not an issue but more like a question. I am trying to build an anti-cheat tool that captures player moves in the game and determine if the player is legit or a bot. I like playing stk so I figure I will use this game with its `--network-ai` support. 
I planned to sniff the traffic using tcpdump and isolate the AI moves (packets) from the legit player but the tcpdump is super noisy so I wonder if the game provides. Is there a cleaner way to do it? Or stream the player moves to some whare else (or write to disk) 

## Steps to reproduce

1/Start an STK game server

2/connect with the client e.g., `SuperTuxKart.app/Contents/MacOS/supertuxkart --connect-now=44.234.46.21:7181`

3/start few AI bots e.g., `SuperTuxKart.app/Contents/MacOS/supertuxkart --connect-now=44.234.46.21:7181 --network-ai=1 --no-graphics`
 
4/ capture the player moves

## Configuration

STK release version: 

```
/cmake_build/bin/supertuxkart --version
[info   ] main: ==============================
[info   ] main: SuperTuxKart, 1.1.
[info   ] main: ==============================
```

STK Source (PPA, distribution package, official binary, etc.): 
git
System: 
Linux
Graphics card: 
N/A
CPU: 
N/A
Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
the network-ai is too weak compared to real players and no one uses this in real life.... ![](https://cdn.lihkg.com/assets/faces/pig/arrested.gif)

but anyway because of its nature it can be easily determined by checking the "ticks" it sends, it sends according periodically according to network-ai-frequency ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

look game protocol and rewind queue ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by yahavb** [comment]
thanks! I enabled the `GameProtocol:Controller action` by adding `--log=0 --connection-debug` and I now see in the server logs for object moves in https://github.com/supertuxkart/stk-code/blob/6e17d5180233e9b271e3add6aa806d67845f9c79/src/network/protocols/game_protocol.cpp#L99 

I understand what `a.m_ticks, a.m_kart_id` means but not `a.m_action,a.m_value,a.m_value_l,a.m_value_r`

Also, is that what you mean by "look game protocol and rewind queue"?

Thanks again!

**Comment by Benau** [comment]
action is the player action (left , right, accel...) value_* are keypress value

ticks % frequency will tell if they are sent by computer instead of human

**Comment by yahavb** [comment]
Yeah just saw 
```
num PlayerAction
{
    PA_BEFORE_FIRST = -1,

    PA_STEER_LEFT = 0,
    PA_STEER_RIGHT,
    PA_ACCEL,
    PA_BRAKE,
    PA_NITRO,
    PA_DRIFT,
    PA_RESCUE,
    PA_FIRE,
    PA_LOOK_BACK,
    PA_PAUSE_RACE,

    PA_MENU_UP,
    PA_MENU_DOWN,
    PA_MENU_LEFT,
    PA_MENU_RIGHT,
    PA_MENU_SELECT,
    PA_MENU_CANCEL,

    PA_COUNT
};
```

Alright, I think I have enough, I will play a bit against bots and see who wins. Thanks again!
