### ISSUE TITLE
Increase density in the GP editor

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4378]
The track icons are big and the number of displayed tracks is low.

I tested two resolutions, 1280x720 and 1600x1024, and two font sizes, large and small. Smaller font size did nothing to help, and the bigger resolution actually displayed an even lower number of elements. I suspect it's because tracks pictures are set to fit in height, so any taller aspect ratio makes the issue even worse.

When selecting a track to add to the GP, one need to go through the list of tracks, and each time a track is added, the list reverts to its default position. With only a small number of tracks displayed at a time, it makes it tedious to find and select a given track.

For mobile phones who have small screens and massive resolutions, icons shouldn't be made too small however.

**Comment by CodingJellyfish** [comment]
![image](https://github.com/user-attachments/assets/a53fd86c-e763-4761-9524-b11fcda845f7)
I can't imagine even more density than this on 1600x1000

**Comment by CodingJellyfish** [comment]
A search bar is added in edit track screen, which should make selection of certain tracks a lot easier.

**Comment by Alayan-stk-2** [comment]
> I can't imagine even more density than this on 1600x1000

It's denser than it used to be, although I don't know what commit changed that. Back in may (last time the 2.x branch was synced with master), it was not that dense, although better than when this issue was opened, as the commit I made back then already helped.

If anything, I'm concerned about text being too small. I'll have to look.

The search bar is nice I suppose.
