### ISSUE TITLE
Changing language settings in race looks possible but doesn't work

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4380]
When pausing the game in-race, the "language" tab is accessible, and the language list isn't greyed-out/disabled ; once can scroll through the list, select items, and try to validate a change (e.g. double-click on the language name).

But no change is actually applied.

Either the language selector should be disabled or the language change should be made to work.

**Comment by kolAflash** [comment]
In 1.4 the language selection is still there while being in race. The language selection simply doesn't react to input events.  
I think that's too obscure / unclear behaviour. Users won't know why they can't click anything and think it's a bug in the game.

I propose to replace the language list with a message _"language can't be switched when a race is running"_ or _"to switch language, quite the race and select options from the game's main menu"_.

&nbsp;

Possible duplicate: #4441 _Can't change UI language during match on Android_

**Comment by Alayan-stk-2** [comment]
Actually fixed with https://github.com/supertuxkart/stk-code/commit/9f4a190245f94df7feb322059672e501b48a5ce1 ; see https://github.com/supertuxkart/stk-code/issues/5163
