### ISSUE TITLE
Motion Control via OpenXR [feature request]

### ISSUE THREAD

**Issue by Sur3** [supertuxkart/stk-code#4382]
OpenXR is the new standard for VR/AR and supports multiple controllers giving 6DOF.
It would be nice to be able to leverage the power of OpenXR in STK by being able to steer via motion controls.
In addition also supporting OpenXR's HMD features would allow real 3d experience.

**Comment by Benau** [comment]
maybe ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by Sur3** [comment]
Why is this closed?

**Comment by PureTryOut** [comment]
I would love this personally, steering using my Valve Index controls sounds really cool. Why did you close this @Benau?

**Comment by Benau** [comment]
Because input handling is done by sdl2 already

Adding more custom code is too much trouble atm

Maybe one day sdl2 will support motion control too
