### ISSUE TITLE
It is not possible to turn left if nitro is activated

### ISSUE THREAD

**Issue by AsciiWolf** [supertuxkart/stk-code#4389]
## Description
When player is pressing the "N" button and nitro is active, it is not possible to turn left. Turning right works fine. I am not sure whether this is intended or not.

## Steps to reproduce
1. Play some track in SuperTuxKart.
2. Wait until you collect some nitro.
3. Press and hold "N" to activate the nitro.
4. Press and hold turn left key.

## Configuration
STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): [Flathub](https://flathub.org/apps/details/net.supertuxkart.SuperTuxKart)

System: Linux Mint 20 Mate

Graphics card: Radeon RX 550 4G OC

CPU: AMD Athlon(tm) 64 X2 Dual Core Processor 5400+

Gamepads/keyboards models if related to the issue: IBM Corp. NetVista Full Width Keyboard

(I have tried this on multiple various computers with multiple Linux distributions and there was the same issue on all of them.)

## Additional information
stdout.log: [stdout.log](https://github.com/supertuxkart/stk-code/files/5247645/stdout.log)

input.xml: [input.xml.txt](https://github.com/supertuxkart/stk-code/files/5247649/input.xml.txt)

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/read.gif) https://supertuxkart.net/FAQ
```
Why don't some keyboard keys work when pressed simultaneously?
When playing with a keyboard, you may experience issues when pressing multiple keys simultaneously, for instance trying to use nitro while accelerating and turning. In such situations, some keypress may not register. This is however not a bug of SuperTuxKart, but a phyiscal limitation of your keyboard, most keyboards can only handle so many keys pressed at the same time ( for more detailed information, please check http://www.sjbaker.org/wiki/index.php?title=Keyboards_Are_Evil ). The solution is to use a gaming input device (gamepad, or gaming keyboard), or tweak the keys configuration to find keys that your keyboard will be able to register simultaneously.
```
![](https://cdn.lihkg.com/assets/faces/pig/fan.gif)

**Comment by AsciiWolf** [comment]
Thanks, it makes sense, although it is a little bit weird that turning right works fine, but turning left was not working on four keyboards (four different computers) that I tried.
