### ISSUE TITLE
only accents are displayed in the menus

### ISSUE THREAD

**Issue by oupala** [supertuxkart/stk-code#4390]
## Description

I'm trying to play supertuxkart on ra raspberry pi 3B+ which is running raspberry pi os latest version.

When I enable OpenGL by the `/boot/config.txt` file, performance are good but I do not see any menu any more, except accent (game is localized in french). I'm seeing `    ê     ` instead of `Prêt`.

## Steps to reproduce

- enable OpenGL using the [following process](https://www.raspberrypi.org/forums/viewtopic.php?t=223592#p1371578)
- install and start supertuxkart
- there is no menu any more

## Configuration

STK release version: 0.8.2

STK Source (PPA, distribution package, official binary, etc.): distribution package from raspberry pi os

System: raspberry pi os 32 bits

Graphics card: raspberry pi 3 B+

CPU: raspberry pi 3 B+

## Additional information

stdout.log:
```
$ supertuxkart 
[verbose  ] main: Error messages and other text output will be logged to /home/pi/.config/supertuxkart/0.8.2/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/games/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/pi/.config/supertuxkart/0.8.2/'.
[info   ] [FileManager]: Addons files will be stored in '/home/pi/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/pi/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/pi/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/games/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/games/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/games/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/games/supertuxkart/data/gui/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/games/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/games/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/games/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/games/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/games/supertuxkart/data/tracks/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/games/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/games/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/games/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/games/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/games/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/games/supertuxkart/data/po/'.
[verbose  ] translation: Env var LANGUAGE = 'fr_FR.UTF-8'.
[verbose  ] translation: Language 'French (France)'.
Adding language fallback fr
Irrlicht Engine version 1.8.0
Linux 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l
[info   ] IrrDriver: OpenGL version: 2.1
[info   ] IrrDriver: OpenGL vendor: Broadcom
[info   ] IrrDriver: OpenGL renderer: VC4 V3D 2.1
[info   ] IrrDriver: OpenGL version string: 2.1 Mesa 19.3.2
[warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
[info   ] GrandPrixManager: Loading Grand Prix files from /usr/share/games/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/pi/.local/share/supertuxkart/grandprix/
[warn   ] OpenGL: OpenGL version is too old!
[verbose  ] RaceManager: Nb of karts=4, ghost karts:0 ai:3 players:1

[info   ] This work was NOT networked: This is NOT a network world.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[verbose  ] Thread: Start waiting 2377492.791000
[verbose  ] Thread: Stop waiting 2377494.799000
[verbose  ] Thread: Waited for more than 2.000000 seconds for thread to become deleteable
[info   ] Thread: News manager not stopping, exiting anyway.
[info   ] Singleton: Destroyed singleton.
$ 
```

input.xml:
```xml

```

Error message:
```

```

**Comment by deveee** [comment]
It's known to be working on Rpi3 + VC4:
https://forum.freegamedev.net/viewtopic.php?f=17&t=8133

But maybe better try to compile STK with OpenGL ES renderer. I suppose it will work faster and maybe with less bugs. Also package from Debian Bullseye (testing) for arm architecture should already be built with GLES renderer. And IIRC you may need increase memory for your GPU, probably somewhere in /boot/config.txt.

**Comment by oupala** [comment]
I have no idea on how to compile supertuxkart. I will give a try to the Bullseye version.

**Comment by deveee** [comment]
You can try this package:
https://www.dropbox.com/s/va3748wujmplm2v/SuperTuxKart-git20200918-linux.tar.xz

It's untested, because I don't have access to rpi at home.

**Comment by oupala** [comment]
It is very difficult to install STK from the Bullseye repository as the dependencies make it very hard to install all required dependencies (in particular libc6). So I could not try to install version 1.2+ds-1 of this package from Bulleye, it would maybe require to upgrade the whole distro.

But I tested the package that @deveee compiled (see previous message) and I can confirm that it is working well, even the menus, while OpenGL is installed. I only get a warning because the version of OpenGL of my raspberry pi os it too old (`OpenGL version: 2.1`).

Thanks a lot for this test!

**Comment by Benau** [comment]
maybe ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) can update linux_builder.sh so it can ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) arm build too

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif) arm build in release page so this issue can be closed ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)![](https://cdn.lihkg.com/assets/faces/mouse/bye.gif)![](https://cdn.lihkg.com/assets/faces/mouse/bye.gif)
