### ISSUE TITLE
Mobile: BUG: Start the App and no Touch response

### ISSUE THREAD

**Issue by Dtrieb** [supertuxkart/stk-code#4392]
STK release version: 1.2 (Beta User)
STK Source: Google Play Store
Device and system: Pixel 4 XL

I updated to the last version on Google PlayStore and after I started the game no response of my Touch.

I cleared the cache and try again with no luck!

**Comment by Benau** [comment]
do you have a keyboard (or mouse) to connect with phone and see if there is any touch device visible in configuration screen? ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

and if you have another android phone this works too https://play.google.com/store/apps/details?id=io.appground.blek&hl=en_US ![](https://cdn.lihkg.com/assets/faces/pig/cook_connect.gif)

**Comment by Dtrieb** [comment]
Yes there is a Touch Device (see screenhot).
![photo_2020-09-21_13-52-08](https://user-images.githubusercontent.com/3650284/93763460-c51ee000-fc11-11ea-8eee-c50e38ccb9a3.jpg)

But it only worked with a keyboard connect with USB to the phone.

**Comment by Benau** [comment]
so your stk receives touch input only when keyboard is plugged in? ![](https://cdn.lihkg.com/assets/faces/pig/dying.gif)

**Comment by Dtrieb** [comment]
no it receives no touch input.

**Comment by Benau** [comment]
according to our pre-launch report pixel 4 works fine... maybe you can try reinstall stk completely and see if it fixes your issue

and it seems that you are the first person who experienced this bug ![](https://cdn.lihkg.com/assets/faces/pig/wail2.gif)

**Comment by Dtrieb** [comment]
I have completely reinstall STK and it didn't work.
I show you in the video:

[https://youtu.be/LSqgBp32gkc](https://youtu.be/LSqgBp32gkc)

**Comment by deveee** [comment]
What was wrong with CIrrDevice*... :P

Is it possible that STK is opened with low resolution? Because in specs I see ```1440x3040``` and the screenshot has only ```1280×606```. Maybe STK receives touch events in full resolution but the window is much smaller... I don't have better idea atm.

**Comment by Dtrieb** [comment]
I think the screenshot is not the real size.
I try to look into the game options.

**Comment by Benau** [comment]
possible to paste the output of adb logcat | grep "SuperTux\|Irrlicht\|DEBUG\|SDL" ? ![](https://cdn.lihkg.com/assets/faces/mouse/please.gif)

**Comment by Dtrieb** [comment]
> possible to paste the output of
> `adb logcat | grep "SuperTux\|Irrlicht\|DEBUG\|SDL"` ? ![](https://camo.githubusercontent.com/04e796914bf8ab5bfb11f4c1e4a04ee5547c5228/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f6d6f7573652f706c656173652e676966)

How can I make this under Win 10?

**Comment by deveee** [comment]
I suppose that using logcat directly on a phone would be easier (not sure if it's possible on all phones without root though). On windows you need android sdk and make some mess with drivers.

Do you remember what was the latest version that was working for you? Was it stable 1.1 or newer beta version?

**Comment by Dtrieb** [comment]
It works under 1.1 beta after the update to 1.2 beta it didn't work.

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) look discord for details!

**Comment by Dtrieb** [comment]
A log file from a friend (Android 11)
[tux.txt](https://github.com/supertuxkart/stk-code/files/5262380/tux.txt)

**Comment by Benau** [comment]
Fix in https://github.com/spurious/SDL-mirror/commit/6fe5bd1536beb197de493c9b55d16e516219c58f ![](https://cdn.lihkg.com/assets/faces/pig/cook_connect.gif)

**Comment by Benau** [comment]
@Dtrieb From what I remembered you reported that gamepad with android 11 is not working too? ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

If so can you try this apk and see if it's fixed https://drive.google.com/file/d/1oHOoaLoc1ShlhWtXL-7BVn-5coFUnikg/view?usp=sharing ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif)

**Comment by Dtrieb** [comment]
Sorry no it didn't work! @Benau

**Comment by Benau** [comment]
can you try this one ![](https://cdn.lihkg.com/assets/faces/mouse/there.gif) https://drive.google.com/file/d/1ijFEPbm4Hw3Kpk6cmUXqBQFNMgCjQ7Mq/view?usp=sharing

and when you press some button / axis in gamepad you should see something like this: ![](https://cdn.lihkg.com/assets/faces/mouse/scratching.gif)

![abc](https://user-images.githubusercontent.com/3252341/116840840-e9ac5300-ac09-11eb-96d6-b3f4188b95f4.jpg)

Can you upload the screenshot here? ![](https://cdn.lihkg.com/assets/faces/mouse/cheerleading.gif)

**Comment by Dtrieb** [comment]
Here is the screenshot:
![Screenshot_20210503-100357](https://user-images.githubusercontent.com/3650284/116853899-11de8680-abf7-11eb-9ebf-0e04aee8232b.png)

**Comment by Benau** [comment]
I will ![](https://cdn.lihkg.com/assets/faces/pig/fan.gif) an update in google issue tracker....

**Comment by Dtrieb** [comment]
Screenshot with 2 lines:

![Screenshot_20210503-151749](https://user-images.githubusercontent.com/3650284/116880846-c93cc280-ac22-11eb-9f44-c4beda84984c.png)
