### ISSUE TITLE
Many timeouts on requests to official server

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4394]
Hello,

On stk-code.git commit e97d33d6f538ee9123ec5010948f36ebcf73310b September 21, 
I have (often) an unusually high latency on reaching the official server.
The side effect is when i got that, the game looks like to crash, i kill the game and  my account is logged out.

Below the part that is slow (it take 10 seconds)
```
[info   ] HTTPRequest: Sending userid=175432&token=************************ to https://online.supertuxkart.net/api/v2/user/poll/
[error  ] XMLRequest::afterOperation: curl_easy_perform() failed: Timeout was reached
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/api/v2/server/get-all/
```
Lines that follows after this long request.
```
[error  ] Online Player Profile: Poll request failed
[info   ] NetworkConfig: System is dual stack network.
```

I did a ping some seconds after : it was quite fast.
```
PING online.supertuxkart.net (192.241.165.79) 56(84) bytes of data.
64 bytes from online.supertuxkart.net (192.241.165.79): icmp_seq=1 ttl=53 time=91.0 ms
```

**Comment by Benau** [comment]
nothing is changed in network code which can affect libcurl... ![](https://cdn.lihkg.com/assets/faces/pig/dying.gif)

**Comment by luffah** [comment]
Strange... i never encountered so much freeze on loading network server's list.

**Comment by luffah** [comment]
I test with version 1.2 on same machine. No similar timeout.

**Comment by ADBeveridge** [comment]
I have this issue on an iMac with Linux installed. Supertuxkart will only load addons and login to supertuxkart account when on wired ethernet. Otherwise it will not work,
