### ISSUE TITLE
Retouch Request: Game Rebalancing

### ISSUE THREAD

**Issue by MosayIC** [supertuxkart/stk-code#4403]
## Description
Brief: I was disappointed with this game, and so I made what changes I could. I'm very happy with the outcome. The carts are faster and they play much more differently from each other now. Instead of fighting hard and staying in middle of track, I find myself even enjoying a race I'm losing (and I usually lose.)

If there were anything I'd like to do, it would be to design more catch-up mechanics for a player who is lagging behind. Expert computer characters leave me in that position often. My zipper idea appears to already be implemented. I would also have rescue to the same thing; transporting the player to where third place once had been once per lap after the first lap (for the bottom tier 5 racers.)

The included files go in your data folder; top level

*EDIT*Raised base acceleration to implement a renewed sense of speed and frenetic response.

*EDIT* Changed the turn radius of the base kart toward a slower base turn; Attempting to reach an experimental number of 4 interruptions.

*EDIT* Raised the amount of nitro gained from canisters, large and small, to raise the relief gained and thus pleasure gained. The races appear to still be competitive.

*EDIT* Raised the potency and lowered the required skill gap of the slipstream due to conflicts with silly and/or goofy play.

*EDIT* Balanced the karts. In play against computers, the winners are not determined by cart weight. Every balance problem is now determined by AI personality, which I'm not sure how to access.

*EDIT* Removed the speed limits on the game modes. They made play more difficult to enjoy.

Assistance Request

*Request* Please test in multiplayer for any consistancies that shouldn't be there and relay those back to me.

*Request* Please take note of these tips:

A light kart cannot compete unless they boost for an entire race and use every opportunity for speed boosting. Every factor here has been made easier if I was able to do so.

A heavy kart cannot compete unless they combine braking and skid.

A medium kart will can compete if they use the games systems to take and keep a lead.

Some Feature Requests

*Request* I would like to implement a high likelihood that a player who is far behind other players and (a smaller but higher chance for) a player who is in the leading 6 positions will pick up a zipper; but I don't know how. I think the alteration in favor for the player who is behind is done already.

*Request* I would like to impliment a fix. The files that I rebalanced are trending off the ingame chart, but it seems like they (the karts) are balanced as light, medium, and heavy and can now consistently keep up with low and high level computers. I think its true, since its a change from when light was leading every race by a wide margin. I would like to change the kart select chart to a higher value so that the values remain in the boxes.

*Request* I would like to change the numbers of AI racers in each type of race. I would have done this myself, and once I had stumbled into the file to do so within, but I've lost it. 
Best: 11
Hard: 9
Medium: 7
Easy: 5

*Request* Where the items switch with visible timing between good and bad items, I would like to change the feature to blink back and forth (at an interval of one of .45, .75, 1, or 1.5 seconds,) but I really don't know how to make the change. This really seems like an illusion of choice point, where the player presently doesn't feel good about their experience of having the rug pulled from under them, a change of the item every second would seem like a different experience entirely. I think. 

*Request* Make fire an option for starting a race, and make enter an option for opening a level start window in story mode. Switching between fire and enter in story mode feels awkward.

*Request* I would like to lower the gear ratios, instead of lowering the max speed, on easier difficulties. I just don't know how to.

*Request* I would like to implement a custom difficulty level, allowing the player (or online host?) to determine what features will be added (like item switching) or withheld (like slipstream).

Request: Test and consider using 'C' and 'V' for Skid and Nitro in the default settings. The long reach over has annoyed me once during play already.

## Steps to reproduce
Please test.

[STK retouch.zip](https://github.com/supertuxkart/stk-code/files/5360918/STK.retouch.zip)

## Configuration

STK release version: v1.2

STK Source (PPA, distribution package, official binary, etc.): distribution package

System: Windows 10

Graphics card: GeForce GTX 1060

CPU: Intel Core i7

## Additional information

input.xml:

There is no error to post. I'm not sure how to post this in an alternative way. Issues related to controls are listed above in the feature requests.

**Comment by Alayan-stk-2** [comment]
If you want to discuss game balance, use the forum at https://forum.freegamedev.net/viewforum.php?f=16
