### ISSUE TITLE
What formula do you use to create the distribution of points in GP?

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4404]

**Comment by qwertychouskie** [comment]
https://supertuxkart.net/About_player_rankings

(I believe the formula was slightly tweaked for STK 1.2, not sure if that doc was updated.)

**Comment by STK-FabianF** [comment]
The page isn't updated, but I don't think this was what he was asking for anyway, it's about Grand Prix

**Comment by anonymous7002** [comment]
50, 43, 37, 32, 28, 24, 21, 18, 15, 13, 11, 9, 7, 6, 5, 4, 3, 2, 1, 0
Yes, this indeed.

**Comment by Benau** [comment]
look void  STKConfig::getAllScores(std::vector<int> *all_scores, int num_karts) in stk_config.cpp:605 ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

It doesn't use math formula (like scores = 2n) but a mapped vector ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by anonymous7002** [comment]
So what does this mapped vector do? How does it create the points for each number of karts?
