### ISSUE TITLE
Driving on planks sound still plays while pausing

### ISSUE THREAD

**Issue by RedstonekPL** [supertuxkart/stk-code#4407]
## Description
When you pause while driving in the barn, in Cornfield Crossing, the sound of driving on wood still plays.

## Steps to reproduce
1. Play on Cornfield Crossings
2. Pause when you're in the barn (or whatever this wooden building is)

## Configuration

STK release version: 1.2.0

STK Source (PPA, distribution package, official binary, etc.): Official binary from Github

System: Windows 10 2004 version

CPU: Intel Core i5-10600

**Comment by Mrxx99** [comment]
Dupicate of #3678
