### ISSUE TITLE
Advertise F-Droid availability on the download page

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/stk-code#4416]
On: https://supertuxkart.net/Download

Add a `Get on F-Droid` (that links to https://f-droid.org/en/packages/org.supertuxkart.stk/ ) also do not redirect straight to Play store if Android is pressed.

**Comment by Benau** [comment]
Fdroid is not official or deve!

Not so good to advertise it likes delayed release now

**Comment by licaon-kter** [comment]
> Fdroid is not official 

That's true, and that's **a given** since F-Droid builds itself apps from source, also that's not a secret. :+1: 

> Not so good to advertise it likes delayed release now

Delayed because we can't enable autoupdate, yes.
Delayed because someone needs to update the build recipe _(I did it this time, but I took me a while since I'm not familiar with the flow)_, yes.
Delayed because F-Droid cycle come at random, yes.
Delayed because F-Droid has certain issues, yes.

Then again, this is not a security app, I can play using 1.1 (F-Droid) and 1.2 (official), so a delay does not affect anything really.

**Comment by Alayan-stk-2** [comment]
I'm not too keen on putting in the official downloads page a build we don't have direct control over.

On the other hand, I don't like the google play store much. But we're also providing direct APK downloads.

**Comment by licaon-kter** [comment]
Right, good thinking, how far is STK from being reproducibly build?

**Comment by Benau** [comment]
1.2 has way more features than 1.1 for players ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif)

if deve has no strong opinion it will ![](https://cdn.lihkg.com/assets/faces/pig/cut.gif) this ticket

**Comment by licaon-kter** [comment]
@Benau 1.2 is already available on F-Droid since last week, as I updated the metadata.

Your rat/pig emoji based communication system leaves a lot to be desired, unfortunately.
