### ISSUE TITLE
Allow make.sh to build multiple arches

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/stk-code#4417]
Currently for F-Droid [we need to do](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.supertuxkart.stk.yml#L166-235):

```
      - export COMPILE_ARCH=armv7
      - bash ./generate_assets.sh
      - bash ./make.sh -j`nproc`
      - cp -r libs/* tmp_lib/
      - bash ./make.sh clean
      - export COMPILE_ARCH=aarch64
      - bash ./generate_assets.sh
      - bash ./make.sh -j`nproc`
      - cp -r libs/* tmp_lib/
      - bash ./make.sh clean
      - export COMPILE_ARCH=x86
      - bash ./generate_assets.sh
      - bash ./make.sh -j`nproc`
      - cp -r libs/* tmp_lib/
      - bash ./make.sh clean
      - export COMPILE_ARCH=x86_64
      - bash ./generate_assets.sh
      - bash ./make.sh -j`nproc`
      - cp -r tmp_lib/* libs/
```

We need to do this because
* we can't compile a new arch unless the assets are there
* we can't compile a new arch if an old one was build earlier
* we need to run clean between arches
* but clean deletes assets
* but clean deletes previously built libs

What if we have a list `COMPILE_ARCH="armv7 aarch64 x86 x86_64"` so we generate assets only once and clean up doesn't nuke `libs/*` ?

_(you use bundles for Play and I'm not sure how these changes would matter)_

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/read.gif)https://github.com/supertuxkart/stk-code/blob/master/tools/android_builder.sh ?

**Comment by licaon-kter** [comment]
Yes and no, that would generate one APK per arch.

To quote from current F-Droid metadata: `The resulting APK is ~112Mb per arch, but per arch lib is only 10-20Mb so either we have 4 APKs (one per arch) each 112Mbs (we keep 3 versions so this means 12 APKs!!!!) or one for all at 140Mb.`

Thanks for the link, will test asap.

**Comment by licaon-kter** [comment]
I'll look asap

**Comment by Benau** [comment]
Check latest origin/master ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif), I have fully tested it

![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) it auto ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif) debugging symbol in google play now, so that next time you login there you should see line number and file.cpp
![Screenshot from 2021-09-25 14-11-34](https://user-images.githubusercontent.com/3252341/134764698-c6cc3699-ad07-4373-b77f-468a004368ca.png)

**Comment by Benau** [comment]
![Screenshot from 2021-09-30 01-45-57](https://user-images.githubusercontent.com/3252341/135321656-9c1a4ba9-a574-4af6-90f2-e76759cc7af7.png)
It works ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
though ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) has no idea why it (always) crashes here, maybe ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) can tell (need to get rid of exit(-1)?)

**Comment by licaon-kter** [comment]
> it should be COMPILE_ARCH=aarch64 ./make_deps.sh
I've read https://github.com/supertuxkart/stk-code/blob/1.3/android/make_deps.sh#L56 so I thought it works

Will retry...

**Comment by licaon-kter** [comment]
Yes, I saw your comment before, using it now since it's faster for me to test building, will see how it goes with -full too.

**Comment by licaon-kter** [comment]
How do I exclude x86 exactly without sed removing all it's mentions from make.sh?

I can make_deps.sh for each one of the other 3 arches, via COMPILE_ARCH, but make.sh is run only once to generate the APK, and I've tried like this and fails to make the APK.
