### ISSUE TITLE
Connection Refused:  Game data is incompatible

### ISSUE THREAD

**Issue by reni11111** [supertuxkart/stk-code#4418]
When I wanna connect to most of the servers it works fine, but when I connect to soccer's TOURNAMENT servers (like Netherland Tournament / Frankfurt TOurnament ....)it always shows this error: 
Connection Refused:  Game data is incompatible.

I am using Ubunto 20.04 (the same happened when I had 18.04 installed).
I have installed the last version.

**Comment by Alayan-stk-2** [comment]
Then contact the server owners and try to figure out with them what's the issue. It's not a bug in STK itself.

**Comment by STK-FabianF** [comment]
This error message mostly appears when you are missing a required kart, track or arena. In soccer tournament's case, you will need the "Tournament Field" addon in order to connect, otherwise you'll get the error message.

**Comment by reni11111** [comment]
Thank you fabian, 
all the best by smexy_renaldo
