### ISSUE TITLE
The track intro sound does not play if music is enabled, but sound is disabled

### ISSUE THREAD

**Issue by RQWorldblender** [supertuxkart/stk-code#4422]
## Description

The track intro sound is considered to be part of SFX, but it plays more like music. However, it plays only if both music and SFX are enabled.

## Steps to reproduce

1. Disable sound effects
2. Start any race
3. The track intro sound does not play with this configuration

## Configuration

STK release version: 1.2+git

STK Source (PPA, distribution package, official binary, etc.): git

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/pull/2475 ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by RQWorldblender** [comment]
Okay, I understand after reading the pull request. I now have moved this to become about having it play if music is enabled, but sound is disabled.
