### ISSUE TITLE
Game master has harder quickstart

### ISSUE THREAD

**Issue by SimonDanisch** [supertuxkart/stk-code#4423]
## Steps to reproduce
I swapped controllers with the other players and swapped being game master, and after doing that a lot, it became clear that the game master always has it harder to nail the quickstart. As game master my rate of success drops from 9/10 to 1 out of 10, and likewise for the other players - so pretty significant!

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): 

System: ubuntu 

Graphics card: gtx 1650

CPU: i7

Gamepads/keyboards models if related to the issue: 

Multiple controller (ps3, noname)

Is this a bug or a feature?

**Comment by Benau** [comment]
coincidence ![](https://cdn.lihkg.com/assets/faces/pig/nope.gif)

**Comment by Benau** [comment]
do you play online mode?

**Comment by SimonDanisch** [comment]
>coincidence

I've been always the game master playing at home, and my friend started making fun of me, how I can never nail quickstart :D 

When she tried teaching me, it got so ridiculous, that we started to suspect the controller, but that wasn't it - so we started testing it very thoroughly, and now I'm 99% sure, that it's being the game master (or maybe the user that first joins? But it's not handicapped or anything). We swapped everything around, and played in each configuration at least 10 games and wrote down how often we were able to do quickstart. Every time, non gamer master was able to get quickstart when pressing anywhere between set and start, while for the game master, it was a mystery when one actually needs to press to make it work.

I played a bit online, and always thought it would reduce the difficulty to nail quick start, because I was nailing it almost 100% of the time - and now I realize, that playing locally I'm usually the game master, while online I'm never ;)

If it makes a difference, to unlock all maps I went to `players.xml` and replaced all `solved=none` -> `solved=hard`, but that should have been the only fiddling I did.

**Comment by Benau** [comment]
I cannot reproduce with my gamepad with splitscreen ![](https://cdn.lihkg.com/assets/faces/mouse/cry.gif)

maybe when you become game master you were nervous ![](https://cdn.lihkg.com/assets/faces/mouse/bye.gif)

**Comment by SimonDanisch** [comment]
>maybe when you become game master you were nervous  

Haha :D 

I'll see if I can reproduce on my windows laptop & after reinstall. 
I'm also getting original xbox one controller tomorrow - so far I've only been playing with some cheap noname controllers (ps3 imitation & some others) - so I can do some more controller tests.

**Comment by Alayan-stk-2** [comment]
I'm very skeptical about a true bug that would penalize the game master because of how weird it is.

But I'd like to hear if you can still reproduce it on your side. @SimonDanisch

**Comment by SimonDanisch** [comment]
I don't have any of this installed anymore... But I'm pretty sure, that my tests to pin this down were very exhaustive... Not sure why nobody else runs into it, maybe its something weird in the driver of those cheap controllers 🤷

**Comment by Alayan-stk-2** [comment]
Okay thank you.
