### ISSUE TITLE
XR591: Shortcut has one-sided mesh that can block player

### ISSUE THREAD

**Issue by bluecat999** [supertuxkart/stk-code#4426]
Image: https://files.catbox.moe/mxgqmb.jpg

A player attempting this shortcut can crash into the invisible wall without understanding why.

I am willing to model this fix if wanted.

**Comment by bluecat999** [comment]
Here is a fixed .blend file
[xr591.blend.zip](https://github.com/supertuxkart/stk-code/files/6960486/xr591.blend.zip)
It's a simple cosmetic change so it should be fine for next release.

I also noticed that the invisible wall collisions on that section of the track extend beyond the visible walls. I'm happy to fix those for next major version but it would be good to get feedback from racers on whether to remove the extra parts of invisible wall or add an obstacle in its place.
![Untitled](https://user-images.githubusercontent.com/16522958/128843656-68460416-3413-4325-b95f-a9dc0ae209c2.png)

**Comment by Benau** [comment]
Some stk fans oppose these changes by the way, you can look matrix history and reply.... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

**Comment by Benau** [comment]
it's ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif)ed
