### ISSUE TITLE
Scripting: TrackObject::moveto function is broken

### ISSUE THREAD

**Issue by bluecat999** [supertuxkart/stk-code#4427]
Example track: https://files.catbox.moe/2gl3w7.zip

In this track, the moveto function is triggered when you drive to an action trigger close to the two cubes.

The static cube is graphically moved to the destination (further down the track, above the first U-turn) but its collision physics do not update.
The movable cube moves but is returned immediately, so it looks like nothing happened.

**Comment by Benau** [comment]
duplicated of #3268
