### ISSUE TITLE
[Feature Request] Allow adding bots to lan and wan multiplayer servers

### ISSUE THREAD

**Issue by major-mayer** [supertuxkart/stk-code#4428]
Hi I really enjoy playing this game with my friends during the Corona crisis and recommend it to everyone that I know.
However, sometimes playing with just 3, or 4 guys is a bit lame. It would be much better if there would be a possibility to add bots to the servers, that fill up the rest of the open slots.

I know about the option to start SuperTuxKart with the `--network-ai` and i've already tried it out on my local server and even created a Dockerfile for this, but really that's just a hack.
It takes quite an amount of resources (maybe that's just the price of bots), confuses the other players in the server browser, because the server always seems to be full, you need 2 separated processes  and after 1.2 I don't get my script running again...

So i would like to propose the feature to add a configuration entry that allows to enable this in the configuration file, or what would be even better in the GUI when you are creating a match (except for mobile devices of course).
It doesn't seem so hard to implement for me, because the "AI"  for the bot karts already seems to be present in some way and it would just need small adjustments in the server browser.

I think this is a very important feature, and if it helps I could also sponsor it a bit, at least as far as I can as a student ;)

**Comment by Benau** [comment]
every one can add bots to server in 1.2 (lots of such servers exist).... ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

it still needs 2 processes, it cannot be integrated properly without lots of rewrite ![](https://cdn.lihkg.com/assets/faces/pig/dying.gif)

what do you mean by "after 1.2 I don't get my script running again"? try only start the ai instance after the main server fully started ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by major-mayer** [comment]
All right, seems that i missed the possibility to add bots in the release notes of 1.2 :smile: 
So it seems that i found the reason why my script didn't start again. 
When you create a server with max 8 players, then it's not possible to simply add 8 bots anymore (when someone joins the bot count is reduced automatically), but when you add only 7 it seems to work.

So here is the command that I'm using:
```
supertuxkart --connect-now=localhost:2759 --disable-polling --network-ai=$stk_aikarts --login=$stk_aiuser --password=$stk_aipw # before
supertuxkart --connect-now=localhost:2759 --network-ai=7 #now
``` 

Is this the correct way to add bots to the server? And i don't need a seperated account for the bots anymore and the the disable polling parameter is also not required?

**Comment by Benau** [comment]
yes yes ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif)

**Comment by major-mayer** [comment]
Great I will close this then
