### ISSUE TITLE
STK doesn't/refuses to open in Ubuntu 16.04 LTS.

### ISSUE THREAD

**Issue by SwissGameing2351** [supertuxkart/stk-code#4430]
I am currently running Ubuntu 20.10. STK on 20.10 works fine, however, on 16.04 not.
I installed it via snap store, but it refuses to open.
Tried to run it via terminal, also doesn't work. 
Is there a way to fix it? My hardware components meet the requirements.

**Comment by deveee** [comment]
Try to install package from official website. I think it should work.

**Comment by mrkubax10** [comment]
Any news?

**Comment by Benau** [comment]
Ubuntu 16.04 is outdated by the way, please update to latest ubuntu....
