### ISSUE TITLE
Mobile control : implementing auto forward

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4432]
Suggestion for moblie from a new player (addicted to other kart games):

Have an option for mobile to auto accelerate when no key is pressed.

~~Given that in STK, you could brake or reverse, i suggest to keep the backward key and disable acceleration when pressing in the blue zone.~~ Edit : forget that

Note : too, the zone to press to accelerate is unclear (wheel control mode),  hard to see where is the maximum acceleration.

**Comment by luffah** [comment]
Replacing release of brake key by accel  key could be enough to experiment the feature.
I see how to implement the thing locally but in network context, it looks more complicated ... 
```diff
diff --git a/src/karts/controller/player_controller.cpp b/src/karts/controller/player_controller.cpp
index 7117d7ec1..6669d7830 100644
--- a/src/karts/controller/player_controller.cpp
+++ b/src/karts/controller/player_controller.cpp
@@ -201,10 +201,13 @@ bool PlayerController::action(PlayerAction action, int value, bool dry_run)
         }
         else
         {
-            SET_OR_TEST_GETTER(Brake, false);
-            SET_OR_TEST_GETTER(Accel, m_prev_accel/32768.0f);
-            // Nitro still depends on whether we're accelerating
-            SET_OR_TEST_GETTER(Nitro, m_prev_nitro && m_prev_accel);
+            PlayerController::action(PA_ACCEL, 65535.0f, false);
+            /* 
+             * SET_OR_TEST_GETTER(Brake, false);
+             * SET_OR_TEST_GETTER(Accel, m_prev_accel/32768.0f);
+             * // Nitro still depends on whether we're accelerating
+             * SET_OR_TEST_GETTER(Nitro, m_prev_nitro && m_prev_accel);
+             */
         }
         break;
     case PA_NITRO:
```

**Comment by Benau** [comment]
actually player who wants auto acceleration can use accelerometer / gryoscope control

the design of steering wheel is not suitable for auto acceleration or will lead to confusing control ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by luffah** [comment]
I got some argument on my side too :p i know you are someone busy.

Gyroscope is really boring when your screen reflect light. Too, if you brake with gyromode , you'll have to press again on accel after releasing the brake key.

I  asking to the person and tried myself.
and gave this change as a test to the person that really prefer this mode (probably because it is  similar to Mario Kart auto forward option).

On desktop side, i really prefer to not to have to continuously press on forward key.

About steering wheel, it works pretty well with this option activated.
I don't wish to propose the option as default know.
(Too, given the wheel is too small for my phone, i ll soon propose a PR to have an alternative and larger multi-touch input mode )

**Comment by Benau** [comment]
if you need auto acceleration, use accelerator / gyroscope

**Comment by Benau** [comment]
you also forgot about gamepad control in desktop

**Comment by Benau** [comment]
probably just one option (auto acceleration) in mobile control, and those handling should only be done in mobile control class (without messing up local player controller class).

**Comment by Benau** [comment]
change m_controller->action(PA_ACCEL, Input::MAX_VALUE); in MultitouchDevice::updateAxisY at line 496 will do the same thing

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/f8e2ac3232c6fc918d94da7c8777c17bd6d0650c ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

or ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) like this or not!

**Comment by luffah** [comment]
I'll look that .. personally, i like to have this option as a desktop version user (it helps me to avoid ghost keys on my keyboard configuration).  But i could keep this as a personal hack given desktop version still well playable. Or maybe adding this parameter for my case, in keyboard device, even with i would like to have it too for a gamepad `0_0`.

**Comment by Benau** [comment]
I ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) an apk for u / ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif)!

https://drive.google.com/file/d/1LKAhz2DGP8h3zB-ycOmnNnVQHk6qK7Zv/view?usp=sharing

**Comment by luffah** [comment]
thx .. i was into building it.

**Comment by luffah** [comment]
I like this version. Retried without the option, and customizing all; better than i expected but I still think it is more comfortable with auto-acceleration.

For desktop part, better not to include that finally : it would be easy to for the user to use another program to keep the key entered.

Is there any possibility to push something like in master ?

**Comment by Benau** [comment]
Wait 1 more day for deve......

**Comment by Benau** [comment]
Also i ![](https://cdn.lihkg.com/assets/faces/pig/whip.gif) main branch
