### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by DALEK-77** [supertuxkart/stk-code#4433]
## Description

We should have discord rich presence, instead of having to do manual detection. I'm on mac, so i'm not sure if this is already on other platforms (e.g, Linux, which I used to use)

## Configuration

STK release version: 

STK Source (PPA, distribution package, official binary, etc.): That's kinda tough. I _did_ download from the Homebrew package manager, but it downloaded the binary from the STK sourceforge.

System: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

Graphics card: Intel Iris Plus Graphics (Ice Lake) - 64 EUs and 1536 MB shared memory

CPU: Intel Core i5-1038NG7

Gamepads/keyboards models if related to the issue: I mainly use a DualShock 3 (PS3) gamepad, as well as the inbuilt keyboard at times.

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
no linking proprietary software ![](https://cdn.lihkg.com/assets/faces/pig/nope.gif)
