### ISSUE TITLE
Support for Feral's gamemode

### ISSUE THREAD

**Issue by stephanlachnit** [supertuxkart/stk-code#4434]
It would be cool if SuperTuxKart could add support for [Feral's gamemode](https://github.com/FeralInteractive/gamemode), it might help to improve the performance on weaker setups a bit.

Currently, support can be added via [3 possible ways](https://github.com/FeralInteractive/gamemode/blob/master/lib/README.md): including `gamemode_client.h` as header (requires `-ldl`), linking dynamically against libgamemodeauto or linking statically against libgamemodeauto. None of these force the user to have gamemode installed, however linking dynamically obviously requires libgamemodeauto to present somewhere (either shipped or on the system).

The easiest way is probably to add a build option (which is disabled by default) which loads the `libgamemodeauto` pkg-config file, i. e. linking against the shared library. Users compiling themselves or distros can then use it and ensure it is actually installed, without any effect on prebuild binaries.

**Comment by stephanlachnit** [comment]
Working on a PR rn.

**Comment by Benau** [comment]
If there is no significant gain please dont do that, we have no control on how 3rd party software will behave ![](https://cdn.lihkg.com/assets/faces/pig/nope.gif)

For example this https://github.com/supertuxkart/stk-code/issues/4391 ![](https://cdn.lihkg.com/assets/faces/pig/shocked.gif)

**Comment by stephanlachnit** [comment]
gamemode is very simple, I wouldn't worry about stuff like #4391. Let me quickly go through on how it works:

- `libgamemodeauto` tries to load `libgamemode`, if that fails nothing happens
- `libgamemode` tries communicates with a daemon via dbus, telling it that this application requested "gamemode"
- the daemon can change the cpu gov, IO priority etc. to boost performance

Thanks to that architecture 90% of the magic doesn't even happen in the linked libraries, they are tiny and basically failsafe (remember that Feral ships them on their binaries, so I'm sure they did enough QA to ensure that it works).
To ensure that the daemon works there is a test program, and at least in Debian that is checked constantly by the CI.

If you're still unsure, take a look at the code, it's really very tiny: [1](https://github.com/FeralInteractive/gamemode/blob/master/lib/client_impl.c) & [2](https://github.com/FeralInteractive/gamemode/blob/master/lib/gamemode_client.h)

I wouldn't expect significant performance gains, at least not on modern setups. It can help on systems with a CPU bottleneck.
