### ISSUE TITLE
support for Korean translation

### ISSUE THREAD

**Issue by sooyeon73** [supertuxkart/stk-code#4436]
Hello,
In order to help Korean users use the supertuxkart, I have completed translation of .md files in my forked repository, and incomplete Korean translation in transifex.

I'd appreciate if you check my repository & transifex : 
https://github.com/sooyeon73/stk-code
https://www.transifex.com/supertuxkart/supertuxkart/language/ko/

thanks.

**Comment by Benau** [comment]
The md file will not needed to be translatable, only transifex needs to be updated
