### ISSUE TITLE
Can't change UI language during match on Android

### ISSUE THREAD

**Issue by adem4ik** [supertuxkart/stk-code#4441]
## Description

UI language can't be changed during the race on Android. But it works fine from the main menu.
![Screenshot_20201207-164848](https://user-images.githubusercontent.com/4707112/101353266-bbba2100-38ac-11eb-8d6f-9ed602783ec5.jpg)

## Steps to reproduce

1) Run STK
2) Open "Singleplayer" - start any type of race
3) Press "pause" button after loading
4) Open "Option" - "Language" and try to select any language

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Google Play

System: Android 7.1.2

Graphics card: Mali-T720

CPU: MediaTek MT6735P

Smartphone: Dexp Ixion M350

Screen resolution: 1280х720

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
The gui engine (which preloaded with translation) cannot be easily reloaded during game ![](https://cdn.lihkg.com/assets/faces/pig/nope.gif)

**Comment by adem4ik** [comment]
@benau Then I guess the whole "Language" section should hidden in the Settings during the match. Or at least there should some kind of indication in this section for end user like "Language can't be changed during the race". For now it just looks broken even if it intended to be so.

**Comment by Benau** [comment]
Maybe

**Comment by Benau** [comment]
sorry it won't be done as too many places need to be changed
