### ISSUE TITLE
Camera settings gui : presets are no more customizable

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4442]
Hello, talking about a feature i added : Camera settings in Interface menu.

It was expected to select a preset, and adjust it a little with custom button. (preset name was automatically found given the settings)

In latest versions, it is no more possible to customize from presets. It make this really unconfortable.

(The change to do is probably to remove a condition on "Custom.." button)

**Comment by Benau** [comment]
you can only make custom change with "custom" present, but it can now remember the custom setting too.

**Comment by luffah** [comment]
that was the case.... 
I think this change has been made on misunderstanding or wrong usage

**Comment by luffah** [comment]
The "Custom..."  button was in fact "Customize this preset and store it in 'Custom' preset".
Looks like it have been misunderstood. And i had misunderstanding when i was using it...
Ok a little disappointed,  i was proud of my tricky thing :p

A way to do, that would be convenient recover this behavior, is to add a button with selection list in the popup to load others presets value.

**Comment by luffah** [comment]
Anyway this issue is really minor.

**Comment by Benau** [comment]
stk fans want to save custom setting so it doesn't get reset when choosing another preset ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

**Comment by luffah** [comment]
you still don't understand how it works
