### ISSUE TITLE
Track is dark (Windows)

### ISSUE THREAD

**Issue by henfri** [supertuxkart/stk-code#4443]
## Description
The track is very dark - one cannot see it

## Steps to reproduce
Start STK 1.2 (64 bit) under Windows 10 with default settings on AMD Ryzen Mobile

## Configuration

STK release version: 
1.2 Windows 64 bit

STK Source (PPA, distribution package, official binary, etc.): 
sourceforge (because the github download even after multiple tries never succeeded on Windows or Linux (wget)

System: 
HP Envy x360

Graphics card: 
AMD Radeon Vega (in CPU). 512MB Video Memory allocated

CPU: 
AMD Ryzen 4700 U

## Additional information

stdout.log:
https://gist.github.com/henfri/f47aaf1411d8ddc30f7c1ba779958742

![hacienda-2020 12 13_14 43 26](https://user-images.githubusercontent.com/5280909/102013804-aaf92780-3d52-11eb-9bd2-6b4b9697ca4f.png)

**Comment by Benau** [comment]
You can try edit the config.xml in the same directory of stdout.log, and make the option force_legacy_device to true to make it work for now

**Comment by henfri** [comment]
Hello,

that helped. 
Is that something that could be auto-detected in a future version?

Regards
Hendrik

**Comment by Benau** [comment]
Not that easy because it's driver related problem

**Comment by qwertychouskie** [comment]
@henfri It may be worth reporting the bug to AMD if updating your driver doesn't fix the issue.

https://www.reddit.com/r/Amd/comments/8ym927/report_driver_bugs_to_amd_they_do_read_it/

**Comment by Benau** [comment]
see if it's better with vulkan stk later
