### ISSUE TITLE
QUESTION: Why did players drop so hard?

### ISSUE THREAD

**Issue by Niwla23** [supertuxkart/stk-code#4444]
![grafik](https://user-images.githubusercontent.com/46248939/102280198-f9fab480-3f2c-11eb-8ccb-159543f96a22.png)
This is from online.supertuxkart.net, I am wondering why they dropped in no time from very high to very low. Was it a bug in the counting system?

**Comment by qwertychouskie** [comment]
The graph you see isn't actually of clients, but of requests to the STK server.  Versions of STK before 1.2 would download the thumbnails for all addons automatically, whereas 1.2+ download them on-demand, therefore greatly reducing the number of requests to the STK server.
