### ISSUE TITLE
Increase max number of laps

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4446]
Currently, the max number of laps you can set for a race is 20, and you can't increase it from config files.

**Comment by billsmithsmithbill22** [comment]
Hello,
In tracks_screen.cpp in /scr/states_screens/online/, there appears to be a soft limit on line 440. If you recompile it with this, you might be able to increase it. I'm not really familiar with the code, but this might help you if you recompile. Good luck!

if (UserConfigParams::m_num_laps == 0 ||
            UserConfigParams::m_num_laps > **_20_**)
            UserConfigParams::m_num_laps = 1;`
