### ISSUE TITLE
Build on Raspberry Pi as Package

### ISSUE THREAD

**Issue by billsmithsmithbill22** [supertuxkart/stk-code#4447]
Hello,
I followed the instructions to install STK and build it from source on the Raspberry Pi ([https://www.raspberrypi.org]). Is there a way for precompiled binaries for the Pi so they can be easily installed with apt-get? It would make it easier for me and would make installing on the popular Raspberry Pi, often used in education, much easier. When I tested it and turned up the graphics memory, I was able to get good quality graphics at fast frames rates. This would allow SuperTuxKart to be expanded to reach more people with little knowledge of Linux. I have the Pi 3B and the 3B+, so I can't vouch for the new Pi 4.

System: 
Raspberry Pi 3B+

CPU: 
Broadcom Arm Cortex A36 Quad Core

**Comment by Benau** [comment]
we can make a static build for you (the linux tar xz you see in our release page), but probably not apt-get

![](https://cdn.lihkg.com/assets/faces/mousexm/pray.gif)

**Comment by billsmithsmithbill22** [comment]
Hello,
Just realized that I can search the Debian repo and get the correct ARM version for the package. Makes it a lot easier to do than building from source like I did the other day!

Thanks for your help!

**Comment by deveee** [comment]
If you use open source mesa drivers, then the current package from debian repo should work. Or I built static package for arm some time ago
https://www.dropbox.com/s/va3748wujmplm2v/SuperTuxKart-git20200918-linux.tar.xz?dl=0
Or if you use closed-source broadcom driver then hardware acceleration is possible too with sdl2, but it probably needs some fixes in stk.
