### ISSUE TITLE
Too big fonts and too wide dialogs when using 1:1 aspect ratio

### ISSUE THREAD

**Issue by baryluk** [supertuxkart/stk-code#4448]
## Description
I noticed that STK does play pretty good on my monitor, which has 1:1 aspect ratio, but there is room for improvement.

Here are some screenshots, some of which show suboptimal sizing of fonts (too large), and other minor issues.

![Screenshot at 2020-12-21 23-16-09](https://user-images.githubusercontent.com/110322/102831773-7cc7b780-43e4-11eb-9fe7-1dea3234b9fc.png)
![Screenshot at 2020-12-21 23-19-52](https://user-images.githubusercontent.com/110322/102831775-7d604e00-43e4-11eb-9e1f-200d8eb92cdf.png)
![Screenshot at 2020-12-21 23-20-16](https://user-images.githubusercontent.com/110322/102831776-7d604e00-43e4-11eb-9fb4-4b1d793925e5.png)
![Screenshot at 2020-12-21 23-23-18](https://user-images.githubusercontent.com/110322/102831777-7df8e480-43e4-11eb-8cf7-10e6bb3ebf3e.png)
![Screenshot at 2020-12-21 23-23-34](https://user-images.githubusercontent.com/110322/102831778-7df8e480-43e4-11eb-8ba8-96ac2072b4a5.png)
![Screenshot at 2020-12-21 23-24-01](https://user-images.githubusercontent.com/110322/102831780-7e917b00-43e4-11eb-90f6-0cc9be1532db.png)
![Screenshot at 2020-12-21 23-24-20](https://user-images.githubusercontent.com/110322/102831781-7e917b00-43e4-11eb-8e67-24864c619b35.png)
![Screenshot at 2020-12-21 23-24-47](https://user-images.githubusercontent.com/110322/102831783-7f2a1180-43e4-11eb-9daf-ce2a1bb35905.png)
![Screenshot at 2020-12-21 23-25-09](https://user-images.githubusercontent.com/110322/102831784-7f2a1180-43e4-11eb-8508-82dd9c65eeb1.png)
![Screenshot at 2020-12-21 23-25-25](https://user-images.githubusercontent.com/110322/102831785-7fc2a800-43e4-11eb-9141-89283ce55602.png)
![Screenshot at 2020-12-21 23-25-54](https://user-images.githubusercontent.com/110322/102831786-7fc2a800-43e4-11eb-941c-3012c6e069b7.png)
![Screenshot at 2020-12-21 23-26-16](https://user-images.githubusercontent.com/110322/102831787-7fc2a800-43e4-11eb-9f26-6e39bd9c66cb.png)
![Screenshot at 2020-12-21 23-26-31](https://user-images.githubusercontent.com/110322/102831788-805b3e80-43e4-11eb-97ee-47dedf5ccd47.png)
![Screenshot at 2020-12-21 23-26-49](https://user-images.githubusercontent.com/110322/102831789-805b3e80-43e4-11eb-9925-f6c028286c6c.png)
![Screenshot at 2020-12-21 23-27-02](https://user-images.githubusercontent.com/110322/102831790-80f3d500-43e4-11eb-999b-b148539e2060.png)

## Steps to reproduce

Set the game in window of size 1920x1920, or fullscreen at that size.

## Configuration

STK release version: 1.2+ds-1

STK Source (PPA, distribution package, official binary, etc.): Debian testing

System: Debian testing

Graphics card: amdgpu, AMD Fury X

Monitor: EIZO FlexScan EV2730Q  using DisplayPort

```
$ xrandr 
Screen 0: minimum 320 x 200, current 4480 x 1920, maximum 16384 x 16384
DisplayPort-0 disconnected primary (normal left inverted right x axis y axis)
DisplayPort-1 connected 1920x1920+0+0 (normal left inverted right x axis y axis) 476mm x 476mm
   1920x1920     59.94*+  29.94  
   2048x2048     59.41  
   1920x1200     59.88  
   1920x1080     60.00    60.00    59.94  
   1600x1200     60.00  
   1680x1050     59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.94  
   1280x960      60.00  
   1280x800      59.94  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
   720x400       70.08  
DisplayPort-2 connected 2560x1600+1920+0 (normal left inverted right x axis y axis) 641mm x 401mm
   2560x1600     59.97*+
   1920x1200     59.95  
   1920x1080     60.00  
   1600x1200     60.00  
   1680x1050     59.95  
   1280x1024     60.02  
   1440x900      59.89  
   1280x800      59.97  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       60.00    59.94  
   720x400       70.08  
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
$
```

**Comment by Benau** [comment]
Change font size yourself?

**Comment by Benau** [comment]
STK screens are optimized for landscape screen, changing that would require rewrite all screen and dialog ![](https://cdn.lihkg.com/assets/faces/pigxm/snowhat.gif)

**Comment by baryluk** [comment]
Changing font, didn't really help.
