### ISSUE TITLE
Can't resize window on Gnome 3.38/Ubuntu 20.10

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#4460]
Tested on both 1.2 and git, I can no longer resize the STK window.  Things worked fine in the past, I suspect the issue happened with the upgrade from Ubuntu 20.04 to 20.10, though I just noticed it today.  I logged into my XFCE session and STK was resizable just fine there.

What's weird is that the SDL2 test app at https://stackoverflow.com/questions/44507711/how-to-correctly-refresh-sdl2-window-after-resizing can be resized just fine, so it looks like some weird interaction specifically between Gnome and STK.

**Comment by Benau** [comment]
stk doesn't use SDL_WINDOW_RESIZABLE but set resize later

but everything works fine in my gnome 3.38.2 arch linux ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by qwertychouskie** [comment]
Definitely a Mutter issue after some testing.  Opened https://gitlab.gnome.org/GNOME/mutter/-/issues/1595 to track issue upstream.
