### ISSUE TITLE
Add battery low & empty notification for Gamepad

### ISSUE THREAD

**Issue by h6899** [supertuxkart/stk-code#4470]
## Description
When the Gamepad's battery gets low or empty, the player has no indication if the battery is low or empty. When the battery is empty, the game should be paused and tell the player to charge or replace the batteries.

## Steps to reproduce
Pair a Bluetooth Gamepad and get 0% battery while in race.

**Comment by Benau** [comment]
This only useful in offline games....... ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

**Comment by qwertychouskie** [comment]
A low battery notification (similar to how the chat popups work) would still be useful in online, so your can plug in your gamepad or quit the server before the next race starts.

**Comment by Benau** [comment]
well notification with message queue is ok, but pausing the game too strict.............. ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by Benau** [comment]
you can see if latest master work for message queue based notification ![](https://cdn.lihkg.com/assets/faces/mouse/medicine.gif)

```
joystick/hidapi/SDL_hidapi_switch.c:1205:            joystick->epowerlevel = SDL_JOYSTICK_POWER_LOW;
joystick/hidapi/SDL_hidapi_ps4.c:692:            joystick->epowerlevel = SDL_JOYSTICK_POWER_LOW;
joystick/hidapi/SDL_hidapi_ps5.c:808:            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_LOW);
joystick/hidapi/SDL_hidapi_xbox360w.c:84:        joystick->epowerlevel = SDL_JOYSTICK_POWER_LOW;
joystick/hidapi/SDL_hidapi_xboxone.c:813:            SDL_PrivateJoystickBatteryLevel(joystick, SDL_JOYSTICK_POWER_LOW);
joystick/windows/SDL_windows_gaming_input.c:550:                    joystick->epowerlevel = SDL_JOYSTICK_POWER_LOW;
joystick/windows/SDL_rawinputjoystick.c:1682:                        ePowerLevel = SDL_JOYSTICK_POWER_LOW;
joystick/windows/SDL_xinputjoystick.c:406:                ePowerLevel = SDL_JOYSTICK_POWER_LOW;
joystick/iphoneos/SDL_mfijoystick.m:962:                            ePowerLevel = SDL_JOYSTICK_POWER_LOW;
```
Only those drivers will work with SDL2 ![](https://cdn.lihkg.com/assets/faces/mouse/vampire_special.gif)
