### ISSUE TITLE
Unable to move

### ISSUE THREAD

**Issue by Epsilqn** [supertuxkart/stk-code#4471]
## Description

The game locks the player in place when going off-road.

## Steps to reproduce

Play the game and drive off road. 

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Ubuntu apt repos

System: Ubuntu Budgie 20.04

Graphics card: RX 470 4GB

CPU: R5 3600

Gamepads/keyboards models if related to the issue: 

## Additional information
https://www.youtube.com/watch?v=BYWxOM_4gIY

stdout.log: https://cdn.discordapp.com/attachments/696787668486324294/803094642912526386/stdout.log

**Comment by Benau** [comment]
we are unable to prevent all of those glitches so you need to use your rescue button wisely ![](https://cdn.lihkg.com/assets/faces/pig/wail2.gif)
