### ISSUE TITLE
Game only detects one input when selecting karts with multiple Gamepads

### ISSUE THREAD

**Issue by h6899** [supertuxkart/stk-code#4475]
## Description

When two or more players try to select a kart in "Splitscreen Multiplayer", the game only detects one input from the gamepads.

## Steps to reproduce

Connect two gamepads.
Go to "Splitscreen Multiplayer"
Navigate the select kart menu with both of the gamepads at the same time.

## Configuration

STK release version: git

STK Source: Git master branch
System: Arch Linux [5.10.11 Kernel]
Graphics card: Vega 8 Mobile
CPU: AMD Ryzen 5 2500U
Gamepads: ShanWan Gioteck PS3 Wired Controller

**Comment by Benau** [comment]
do you see 2 controllers in (or x2) in option menu (post input device screenshot plz) ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

**Comment by h6899** [comment]
![Screenshot from 2021-01-29 19-25-50](https://user-images.githubusercontent.com/8750464/106314872-a9d07b00-626a-11eb-977c-9644e2e728fa.png)

**Comment by Benau** [comment]
not sure ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) can emulate identical gamepad with (kernel hacking!) ![](https://cdn.lihkg.com/assets/faces/mouse/solution.gif)

**Comment by Benau** [comment]
can you post the output of ```./bin/supertuxkart --gamepad-debug``` with you pressing buttons on both gamepad? ![](https://cdn.lihkg.com/assets/faces/pig/cut.gif)

it looks like this:
```[info   ] InputManager: axis motion: gamepad_id=1 axis=0 value=32767```

in theory ```gamepad_id``` should be different for each gamepad ![](https://cdn.lihkg.com/assets/faces/pig/champagne.gif)

**Comment by h6899** [comment]
```
[info   ] InputManager: axis motion: gamepad_id=0 axis=0 value=32767
[info   ] InputManager: axis motion: gamepad_id=1 axis=0 value=128
[info   ] InputManager: axis motion: gamepad_id=1 axis=0 value=32767
[info   ] InputManager: axis motion: gamepad_id=0 axis=1 value=128
[info   ] InputManager: axis motion: gamepad_id=0 axis=1 value=-32768
[info   ] InputManager: axis motion: gamepad_id=1 axis=0 value=128
[info   ] InputManager: axis motion: gamepad_id=0 axis=0 value=128
[info   ] InputManager: axis motion: gamepad_id=0 axis=1 value=128
```
The game seems to detect when i press a button on both of the gamepads at the same time, but i can not navigate the menu with two inputs at the same time.

It seems to work fine when in a race.

**Comment by Benau** [comment]
can you try origin/4475 branch now? ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by h6899** [comment]
The game freezes in 4475 branch when navigating the menu with gamepad.

**Comment by Benau** [comment]
```    for (auto it = m_gamepads_timer.begin(); it != m_gamepads_timer.end();)```
Use this instead in line 205 src/input/input_manager.cpp ![](https://cdn.lihkg.com/assets/faces/pig/wine.gif)

**Comment by h6899** [comment]
It is fixed now, thank you.
