### ISSUE TITLE
The game should not quit when pressing the "Cancel/Back" button with a gamepad in the Main Menu

### ISSUE THREAD

**Issue by h6899** [supertuxkart/stk-code#4477]
When in the Main Menu, the game quits when pressing the "Cancel/Back" button with a gamepad.
This can be very annoying or confusing because players either don't know the button quits the game or they press the button by accident.

Players should still be able to quit the game with the Escape key or the quit button in the menu.

**Comment by Benau** [comment]
i honestly don't think so because this hold true even for escape key, if there is no more people in the team agree with you i will close this issue

**Comment by Benau** [comment]
or a dialog to confirm

**Comment by Benau** [comment]
it's a bit complicated to filter out events in ```onEscapePressed``` (or auria!) ... anyone here will find a confirmation dialog annoying when you press esc / gamepad quit button in main menu? ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
