### ISSUE TITLE
No email received after registration

### ISSUE THREAD

**Issue by pervoj** [supertuxkart/stk-code#4479]
## Description

I registered, but even after 5 hours no email was received.

## Steps to reproduce

Create new account

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Flatpak

System: Linux Mint 20.1 Cinnamon

Graphics card: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

CPU: Intel© Core™ i5-2520M CPU @ 2.50GHz × 2

**Comment by Benau** [comment]
stk addons account "pervoj" is activated

seems that gmx email domain doesn't like stk addons mail, next time use protonmail or other popular email account please

**Comment by pervoj** [comment]
Thank you!
