### ISSUE TITLE
Weird flickering issue

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-code#4480]
I'm trying to create a map and I have this weird flickering issue. As you can see when driving it just flicker all over the place and lights seems off. This is exported with Blender 2.8 exporter.

[MiningPit42_2021.02.09_21.53.15.webm.zip](https://github.com/supertuxkart/stk-code/files/5954215/MiningPit42_2021.02.09_21.53.15.webm.zip)

I tried to disable shadows and also ambient occlusion but it persist.

Edit: I added the blender file if you want to try it
[MiningPit42.zip](https://github.com/supertuxkart/stk-code/files/5954234/MiningPit42.zip)

**Comment by samuncle** [comment]
I found, its tilling mitigation when it does not have normal maps

**Comment by Benau** [comment]
i assume the current "auto export tangent" code will fix this ![](https://cdn.lihkg.com/assets/faces/cow/gold.gif)
