### ISSUE TITLE
Unintuitive default gamepad controls

### ISSUE THREAD

**Issue by PureTryOut** [supertuxkart/stk-code#4481]
## Description
Today I tried playing STK with both a PS3 and a PS4 controller and while they work great, the default button mapping is strange and I had to adjust them before I could properly play a race. I'm used to the controls from games like Super Mario Kart (on multiple platforms) and I'm guessing even more modern PC racers use different mappings by default.

Acceleration for some reason is mapped to the equivalent of triangle, however it's the one button the player will _always_ and _constantly_ use during a race. Normally games use the equivalent of the X button for that, as it's most close to your hand and easily reachable without accidentally pressing other buttons. Reverse is mapped to the equivalent of the square button, while the equivalent of the circle would make more sense for most people.

The defaults I would suggest:
- accelerate on the equivalent of the X button
- reverse on the equivalent of the circle button
- fire on the equivalent of the square button
- look back on the equivalent of the left or right shoulder (my preference goes to left)

This would mean the equivalent of the triangle button would be unused, which I'm sure can be used for some new function in the future or something.

Of course this is all subjective and I wouldn't mind if most people would disagree, but being different from every other racing game is a bit strange and not something you should strive for.

## Configuration

input.xml as I have mapped it now personally:
```xml
<gamepad name ="Sony PLAYSTATION(R)3 Controller" deadzone="4096" desensitize="0" enabled="true" configName="">
     <action name="steerLeft" event="2" id="0" direction="0" range="0" />
    <action name="steerRight" event="2" id="0" direction="1" range="0" />
    <action name="accel" event="3" id="0" />
    <action name="brake" event="3" id="1" />
    <action name="nitro" event="3" id="4" />
    <action name="drift" event="3" id="5" />
    <action name="rescue" event="3" id="8" />
    <action name="fire" event="3" id="3" />
    <action name="lookBack" event="3" id="6" />
    <action name="pauserace" event="3" id="9" />
    <action name="menuUp" event="2" id="1" direction="0" range="0" />
    <action name="menuDown" event="2" id="1" direction="1" range="0" />
    <action name="menuLeft" event="2" id="0" direction="0" range="0" />
    <action name="menuRight" event="2" id="0" direction="1" range="0" />
    <action name="menuSelect" event="3" id="0" />
    <action name="menuCancel" event="3" id="1" />
</gamepad>

<gamepad name ="Wireless Controller" deadzone="4096" desensitize="0" enabled="true" configName="">
     <action name="steerLeft" event="2" id="0" direction="0" range="0" />
    <action name="steerRight" event="2" id="0" direction="1" range="0" />
    <action name="accel" event="3" id="0" />
    <action name="brake" event="3" id="1" />
    <action name="nitro" event="3" id="4" />
    <action name="drift" event="3" id="5" />
    <action name="rescue" event="3" id="8" />
    <action name="fire" event="3" id="3" />
    <action name="lookBack" event="3" id="6" />
    <action name="pauserace" event="3" id="9" />
    <action name="menuUp" event="2" id="1" direction="0" range="0" />
    <action name="menuDown" event="2" id="1" direction="1" range="0" />
    <action name="menuLeft" event="2" id="0" direction="0" range="0" />
    <action name="menuRight" event="2" id="0" direction="1" range="0" />
    <action name="menuSelect" event="3" id="0" />
    <action name="menuCancel" event="3" id="1" />
</gamepad>
```

**Comment by Benau** [comment]
see https://github.com/supertuxkart/stk-code/issues/2438#issuecomment-620965010

**Comment by Benau** [comment]
you can see if qwertychouskie thinks this new one is good... i don't think we will ever have a mapping making everyone happy anyway ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by Benau** [comment]
also we don't try to and will not copy how other racing does ![](https://cdn.lihkg.com/assets/faces/pig/whip.gif)

**Comment by PureTryOut** [comment]
@qwertychouskie what do you think? I find mainly the accelerate button not being the bottom one weird to be honest, I think almost everybody will expect that button to be accelerate, and they will have to press some random buttons first to find out which is the actual accelerate button.

**Comment by qwertychouskie** [comment]
The main consideration I had when creating the current mapping is that it allows using all functions without having to move your fingers between buttons; Y as Accel allows using A (Look Back) and B (Fire) with the back of your finger while the tip is on Y (Accel).  Coming up with a decent config is quite hard as STK has more functions that need to be mapped than most kart racers (e.g. Nitro, and firing backwards requiring two simultaneous inputs).  That being said, I'm always open to improvements (I actually primarily play with a keyboard), but coming up with a good config that allows performing a multitude of actions simultaneously is quite tricky.
