### ISSUE TITLE
Emule seems to have two headlight models, one unused

### ISSUE THREAD

**Issue by Mstrodl** [supertuxkart/stk-code#4490]
## Description

Emule's kart seems to have the unused models `headlight_1.spm` and `headlight_2.spm`. The xml file calls for `HeadLight_1.spm` and `HeadLight_2.spm`. This causes some issues on case-insensitive filesystems. The capital lettered ones have larger filesizes, so I'm not sure what the difference is.

STK release version: Latest stk-assets repo as of 2021-02-19

STK Source (PPA, distribution package, official binary, etc.): SVN

**Comment by Benau** [comment]
you sure you svn cleanup? ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

this is my directory: ![](https://cdn.lihkg.com/assets/faces/pig/dance3.gif)
```
Emule_dif.png	   emule_icon32.png  Emule_properties_dif.png	 emule.spm	   HeadLight_2.spm  materials.xml	   wheel-rear-left.spm
Emule_eyes.png	   emule_kart.jpg    Emule_properties-gloss.png  emule_wheels.jpg  kart.xml	    wheel-front-left.spm   wheel-rear-right.spm
emule_icon128.png  Emule_light.png   emule_shadow.png		 HeadLight_1.spm   licenses.txt     wheel-front-right.spm
```
try rm -rf emule and svn up again ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

**Comment by Mstrodl** [comment]
Oops. Sorry, I forgot how weird svn is. Nice pig.
