### ISSUE TITLE
no email for activation coming

### ISSUE THREAD

**Issue by wengolsky** [supertuxkart/stk-code#4492]
hi,

i*ve trying to register, giving an email adress and passwort. all is good, till the moment where i should get an email with the activation link. but no email coming...

I've tried with multiple emails, nothing happens. And no, my spam folder doesnt got any email...

**Comment by wengolsky** [comment]
additional information:
email adress from t-online.de
username: tom_97

**Comment by Benau** [comment]
tom_97 activated
Next time dont use *.de email domain, they seem to filter stk addons address
