### ISSUE TITLE
icon art for tux kart

### ISSUE THREAD

**Issue by RodrigoDornelles** [supertuxkart/stk-code#4496]
This icon was on my old HDD unusued, it was made by me. Although unfashionable,
I think it can be used in some aspect, feel free to use it as you want!

![image](https://user-images.githubusercontent.com/29123479/109650405-ef1eeb80-7b3b-11eb-9dd2-6b28a4e1a950.png)

**Comment by Alayan-stk-2** [comment]
That's a cool icon but that's not an issue so I'm closing this.
