### ISSUE TITLE
online account

### ISSUE THREAD

**Issue by liamlarge** [supertuxkart/stk-code#4497]
wont let me create an online account

Error message: unable to connect to the serve. check your internet connection or try again later.
```

```

**Comment by Benau** [comment]
can you visit online.supertuxkart.net in browser?

**Comment by liamlarge** [comment]
yes i can and i have created an account on that website....but when i try and log in on the game it doesnt let me

**Comment by Benau** [comment]
same error message everytime?

what stk version are you using

**Comment by liamlarge** [comment]
yes...
1.2.0

**Comment by Benau** [comment]
everything is fine in my linux, do you get stk from your distro?

otherwise try this: https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210206-linux.tar.xz

**Comment by liamlarge** [comment]
what do you mean 'distro'?

**Comment by liamlarge** [comment]
also who can join in when you set up a local server

**Comment by Benau** [comment]
linux distribution

anyone in your local LAN network can join (without an account)

honestly nothing we can help because you seem to be the only one having this problem ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
