### ISSUE TITLE
Unable to enter password for LAN servers

### ISSUE THREAD

**Issue by timoschwarzer** [supertuxkart/stk-code#4507]
## Description
STK does not ask for a password when connecting to a password-protected LAN server.

## Steps to reproduce
1. Start a LAN server with a password: `supertuxkart --no-graphics --server-password=123 --lan-server=Server`
2. Connect to it with `supertuxkart --connect-now=127.0.0.1:2759`

STK now complains about the wrong password, but does not allow the user to enter a correct one.

![image](https://user-images.githubusercontent.com/8849554/112225138-a0d9a580-8c2c-11eb-9f03-2078e4de5df3.png)

Interestingly, when starting STK with a wrong password - e.g. `supertuxkart --server-password=456 --connect-now=127.0.0.1:2759` - it _does_ ask for a password.

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Arch Repositories

**Comment by Benau** [comment]
Branch is merged thank you![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)
