### ISSUE TITLE
Servers should have this feature to prevent specific players from getting the crown

### ISSUE THREAD

**Issue by King-Mucus** [supertuxkart/stk-code#4509]
## Description

STK has a great community. However, some great players have the habit of trolling others when they get the crown. Some set the difficulty to beginner and others don't start the race, complaining about unrelated things or delving deeper and deeper on chats that invariably end up disappointing other people in the room. Some of them end up even leaving the server in frustration.

I'm a firm believer that it is counterproductive banning great players that are great to play with. The banality of bans is closely related to internet bigotry and widespread exclusive behavior in society as a whole.

As such, it would be much better to have a setting in the .xml configuration files of the servers to prevent specific players from getting the crown when they are not alone in the room. This would save a lot of drama in the servers and in the forums as well. And we would not lose some great players to play with in the server.

## Steps to reproduce

Just get the crown on a server and start delving endlessly on the topic of your preference (or disgust)

## Configuration

STK release version: 

STK 1.2, but also applies to GIT version, I believe.

STK Source (PPA, distribution package, official binary, etc.):

**Comment by Benau** [comment]
we have ownerless server to deal with that, if that doesn't fix your issue then we have tried to permanently ban some annoying players too

list of restricted player is no good because anyone can recreate an account (and we already have something similar)

If you encounter such people just report in irc / discord so we can take action ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by King-Mucus** [comment]
Please bear in mind that people could and do create additional accounts as a workaround for permanent bans. In addition, as I mentioned, it would be bad to permanently ban players who are great to be with and are simply superb without the crown.

Alas, if there is an option to automatically kick an idle player in 60 seconds after a race had already started, I see no reason to implement a similar feature for idle players holding the crown. You could just force them to go to /spectate 1 mode and then assign the crown to somebody else.

This would save a lot of drama and prevent careless AFK newbies from disturbing others.
