### ISSUE TITLE
Please clarify the relationship between Antarctica engine, stk, and Irrlicht in the documentation.

### ISSUE THREAD

**Issue by poikilos** [supertuxkart/stk-code#4510]
You've said at the [0.9.1 release topic](http://irrlicht.sourceforge.net/forum/viewtopic.php?f=6&t=51015) on Irrlicht forums that you forked Irrlicht and that the fork is called Antarctica. The topic says to see the [blog entry](https://blog.supertuxkart.net/2015/10/supertuxkart-091-is-released.html) for the release for details but the entry doesn't mention Antarctica specifically. If I look through the supertuxcart GitHub account, I see that the export add-on for Blender has antarctica in the name. If I look through the stk-code, I do not find a clear delineation between the engine and the game. Is Antarctica entirely inseparable from stk-code now and in this repo? Games using Irrlicht may want some kind of maintained fork of it due to the upstream project being dead.

The STK [wiki entry for Antarctica](https://supertuxkart.net/Antarctica:_Technical_Details) says "It turned out to be much easier to write a new renderer from scratch instead of patching our copy of the massive Irrlicht codebase." Does that mean that the fork is somewhere but entirely unused? Or is it nowhere? Is Antarctica really a fork of it at all then?

If you've made changes to Irrlicht, some game using it could utilize whatever changes you made if you made it available on GitHub even if you set it to "archived." Should other games switch to it? Or should they switch to Antarctica? Is Antarctica even atomic or is it now a renderer within this repo that isn't seperable or compatible with Irrlicht at any level?

I also have heard of <https://github.com/Devsh-Graphics-Programming/Nabla> (formerly named IrrlichtBAW), but I'm not sure whether it is too different for developers maintaining Irrlicht games to use. It doesn't work on mobile yet and only Android is even mentioned as planned.

**Comment by Benau** [comment]
Antarctica is just a bad name like china virus

Yes it is not separated nor easily achievable

You should probably use godot if you start a project from scratch

Current antarctica is not a good example for study / production.. too many badly optimized stuff

When i redo the render engine it will be more modularized

**Comment by poikilos** [comment]
I was mainly talking about games already using Irrlicht, especially Minetest, which has probably not enough manpower to change engines to something drastically different, with different types especially. Therefore if, somewhere online, you upload the improvements you made to Irrlicht before giving up on it, that would be helpful too.

**Comment by Benau** [comment]
I think the best change for minetest for now is our sdl2 and font code which don't contain too many stk specific code and written in a clearer manner

I dont think those changes will be used / accept upstream irrlicht because they don't like "bloaty" code / extra deps

Just ask in irc / discord so i can give you details ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)
