### ISSUE TITLE
"Your account is not active" error when signing into my SuperTuxKart account

### ISSUE THREAD

**Issue by TimmyFan809** [supertuxkart/stk-code#4511]
## Description
I keep receiving this error message when I try to log into my SuperTuxKart account. This issue is prevalent on both the main website and the SuperTuxKart game login screen itself. This issue happens on multiple accounts, and they all fail to log in.

## Steps to reproduce
Log into a SuperTuxKart account on either the website or the game itself. The message "Your account is not active" appears. This message occurs regardless of what computer I sign onto. I have received this message on both the official website and logging into SuperTuxKart itself.

## Configuration

STK release version: 1.2.0

STK Source (PPA, distribution package, official binary, etc.): 
Official Binary: https://supertuxkart.net/Download

## Additional information

stdout.log:
```

```

Error message:
```
![Capture](https://user-images.githubusercontent.com/81609529/113214139-e0585100-922d-11eb-87e5-c76137a78537.PNG)
![Capture](https://user-images.githubusercontent.com/81609529/113214288-1d244800-922e-11eb-9710-43b67003fcc6.PNG)

```

**Comment by auriamg** [comment]
I disabled your account because you kept uploading multiple copies of the volcano tracks despite warnings to stop doing so.

**Comment by TimmyFan809** [comment]
Thanks for the quick response.
