### ISSUE TITLE
Bunny ears are backwards

### ISSUE THREAD

**Issue by iwoithe** [supertuxkart/stk-code#4513]
## Description

As seen in the following screenshots, the bunny ears are backwards.

![bunny_ears_bug_back](https://user-images.githubusercontent.com/73422868/113466197-56a0c180-9481-11eb-820e-edb4ab504887.png)
![bunny_ears_bug_front](https://user-images.githubusercontent.com/73422868/113466200-599bb200-9481-11eb-8f6e-345216007cd7.png)

## Steps to reproduce
1) Start any race in SuperTuxKart

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Official Binary

System: Windows

Graphics card: Intel(R) HD Graphics 615

CPU: Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz

## Additional information

I know someone who has the app on their phone (android) where this is also happening.

**Comment by sisco0** [comment]
It seems the code related to adding these ears is present at the line below. A further study of the model file would lead to a result.
https://github.com/supertuxkart/stk-code/blob/0dd3c62a435d78704429d76862c7f051a5410437/src/main.cpp#L500

**Comment by sisco0** [comment]
I finally came up with a solution by modifying the mesh file, the file attached should be unzipped and it should replace the original `easter_ears.spm` file which is located under `SuperTuxKart-1.2-linux/data/models`.
**Attached file:** [easter_ears.zip](https://github.com/supertuxkart/stk-code/files/6251871/easter_ears.zip)

I attach a _GIF_ recording as evidence below.
![ezgif-7-32f09d13bc5c](https://user-images.githubusercontent.com/25695302/113467388-f584d980-93ff-11eb-908b-95204de39a91.gif)

**Comment by Benau** [comment]
They are now fixed in our latest repo, thank you ![](https://cdn.lihkg.com/assets/faces/mouse/miracle_special.gif)
