### ISSUE TITLE
Bots in multiplayer

### ISSUE THREAD

**Issue by aRheem0nd** [supertuxkart/stk-code#4516]
So, after about two years, there are still no way to add bots in multiplayer for the battle and soccer modes. Is there any command or something?

**Comment by Benau** [comment]
it's difficult to add bots to those modes due to architure difference

you can still use the sane --network-ai=x command used for racing mode, but the bots may or may not work when playing live joining or leaving

sorry about that ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)
