### ISSUE TITLE
[Feature request] Please add mouse control!

### ISSUE THREAD

**Issue by bananasmoothii** [supertuxkart/stk-code#4520]
Please add the ability to control a kart only with the mouse! Controls could be:
- mouse position compared to initial position: forward, backward, left and right
- left click: skid
- middle click: turbo
- right click: throw / use
- double middle click: pause
- scroll down: see behind
- scroll up: come back to the road if we fell down
Of course a sensibility setting would be great.
Thanks in advance !

**Comment by Benau** [comment]
duplicated of https://github.com/supertuxkart/stk-code/issues/1832 ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
