### ISSUE TITLE
[fatal  ] FileManager: Set $SUPERTUXKART_DATADIR to point to the data directory.

### ISSUE THREAD

**Issue by samuelbeepdev** [supertuxkart/stk-code#4521]
## Description

Popup error when trying to launch STK for Windows. Appears on both folder and installer builds.

## Steps to reproduce

Download a 64-bit windows build or the standalone folder build and run run_game.bat or supertuxkart.exe.

## Configuration

STK release version: Latest (1.2)

STK Source (PPA, distribution package, official binary, etc.): Official win10 binary and win10 standalone folder

System: Windows 10 Pro 20H2

Graphics card: NVIDIA GeForce MX250

CPU: Intel Core i7 10th Gen

## Additional information
No logfile. game won't even launch

Error message:
```
[fatal  ] FileManager: Set $SUPERTUXKART_DATADIR to point to the data directory.
```

**Comment by Benau** [comment]
nothing at all in %appdata%\supertuxkart\config-0.10 (you can enter that in the Explorer and it will take you there)?

maybe you are having permission problem

**Comment by samuelbeepdev** [comment]
Now able to get around it by launching run_game.bat. What starting directory should I use for launching the exe directly (e.g. through steam)? It's a bit of a pain to navigate to the folder every time.

**Comment by Benau** [comment]
Try make use of shortcut, that's what the official installer does
