### ISSUE TITLE
Please consider moving to an ethical code forge

### ISSUE THREAD

**Issue by throwaway1037** [supertuxkart/stk-code#4526]
I would like to contribute to SuperTuxKart, but do not wish to agree, nor promote others to agree, to the GitHub TOS and Privacy Policy.

GitHub also sends proprietary JS to the browser, is run in the backend by secret, proprietary software, and is operated by an unethical corporation.

I suggest an instance of a libre software code forge be run on the STK website instead, such as gitweb, cgit, stagit, Gitea, etc. This would allow STK to impose ethical TOS, not track people, only send libre JS to the browser, and have freedom over the software running in their own server.

**Comment by Benau** [comment]
We cannot afford the bandwidth price for self hosing gitweb, sorry about that
