### ISSUE TITLE
Politics / feature : dethrone tyranic kickers 

### ISSUE THREAD

**Issue by luffah** [supertuxkart/stk-code#4528]
## Description
On public server, this  often happen one people just kick everybody he·she don't want to see  in teams.

I suggest to add  something like a dethroning feature for  people that remove crown when you kick more than N time in X seconds. (giving the crown to a "neutral player" — not the kicked one — if possible)

**Comment by Benau** [comment]
the correct way to deal with them is to use ownerless server, i have no intention to bloat the server code anymore, you are free to implement it in custom server code

**Comment by luffah** [comment]
ok  -> i ll ask to server owner then to use ownerless server
