### ISSUE TITLE
Precision of dtex in sunlightshadow shader is too low

### ISSUE THREAD

**Issue by icecream95** [supertuxkart/stk-code#4533]
## Description

The precision of the `dtex` sampler in the [sunlightshadow.frag](https://github.com/supertuxkart/stk-code/blob/master/data/shaders/sunlightshadow.frag) shader is only `mediump`, though more than 16 bits of precision are needed for shadows to be rendered without artefacts.

This could be fixed by replacing the declaration of `dtex` in the shader with:

```
#ifdef GL_FRAGMENT_PRECISION_HIGH
uniform highp sampler2D dtex;
#else
uniform sampler2D dtex;
#endif
```

, which has the advantage of still using mediump for other textures, potentially improving performance compared to using `highp` for all samplers.

The shader is unlikely to be used in environments without highp support (desktop GLSL supports precision specifiers since GLSL 1.30, though they are no-ops), so it would probably be safe to rip out the ifdef and always use highp.

![stk-precision2](https://user-images.githubusercontent.com/29191311/118348121-35f97a80-b59c-11eb-840d-292dee39967a.png)

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Compiled from source

Graphics card: Mali G72 (Panfrost)

**Comment by Benau** [comment]
```
The shader is unlikely to be used in environments without highp support (desktop GLSL supports precision specifiers since GLSL 1.30, though they are no-ops), so it would probably be safe to rip out the ifdef and always use highp.
```
What do you mean by that?

maybe it can be
```
#if defined(GL_ES) && defined(GL_FRAGMENT_PRECISION_HIGH)
uniform highp sampler2D dtex;
#else
uniform sampler2D dtex;
#endif
```
![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

**Comment by icecream95** [comment]
> maybe it can be
> 
> ```
> #if defined(GL_ES) && defined(GL_FRAGMENT_PRECISION_HIGH)
> uniform highp sampler2D dtex;
> #else
> uniform sampler2D dtex;
> #endif
> ```

That should work too and might make it clearer that setting precision only has an affect for GLSL ES shaders.

**Comment by Benau** [comment]
by the way iPhone shadow improves after this fix ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif)

let me test some android devices... ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif)

if works we can ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif) and ![](https://cdn.lihkg.com/assets/faces/pig/cut.gif) this issue
