### ISSUE TITLE
Using the sq3lite database from Networking.md

### ISSUE THREAD

**Issue by Luca-Hummel** [supertuxkart/stk-code#4538]
## Description
I am trying to use the database for my server and read the [Networking.md](https://github.com/supertuxkart/stk-code/blob/master/NETWORKING.md#server-management-since-11).

So i am running the command `sqlite3 stkservers.db` inside the folder with all the .xmls, I guess that means running it inside the folder config-0.10, or am I wrong?

After running the command, Im copying the code specified in the Networking.md. Following happens:

```
user@OpenMediaVault:~/IntData/Config/STK/KIMDEN/config-0.10$ sqlite3 stkservers.db
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> CREATE TABLE IF NOT EXISTS (table name above)
   ...> (
   ...>     host_id INTEGER UNSIGNED NOT NULL PRIMARY KEY, -- Unique host id in STKHost of each connection session for a STKPeer
   ...>     ip INTEGER UNSIGNED NOT NULL, -- IP decimal of host
   ...>     ipv6 TEXT NOT NULL DEFAULT '', -- IPv6 (if exists) in string of host (only created if IPv6 server)
   ...>     port INTEGER UNSIGNED NOT NULL, -- Port of host
   ...>     online_id INTEGER UNSIGNED NOT NULL, -- Online if of the host (0 for offline account)
   ...>     username TEXT NOT NULL, -- First player name in the host (if the host has splitscreen player)
   ...>     player_num INTEGER UNSIGNED NOT NULL, -- Number of player(s) from the host, more than 1 if it has splitscreen player
   ...>     country_code TEXT NULL DEFAULT NULL, -- 2-letter country code of the host
   ...>     version TEXT NOT NULL, -- SuperTuxKart version of the host
   ...>     os TEXT NOT NULL, -- Operating system of the host
   ...>     connected_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Time when connected
   ...>     disconnected_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Time when disconnected (saved when disconnected)
   ...>     ping INTEGER UNSIGNED NOT NULL DEFAULT 0 -- Ping of the host
   ...> ) WITHOUT ROWID;
Error: near "(": syntax error
sqlite> 
sqlite> 

```

So idk, I need better instructions on how to use this. I dont know how exactly I can get it to work and create the database.

Thanks!

**Comment by Benau** [comment]
You need to replace (table name above) with a real table name

**Comment by Luca-Hummel** [comment]
okay and I can name it to anything I want?

> You need to replace (table name above) with a real table name

okay and I name it any way I want or how does.it work? im sorry im quite nooby in this i mever worked with databases

**Comment by Benau** [comment]
well if you don't understand then you should just disable it, it will not affect the server performance

the database exists "just for fun stats" anyway

**Comment by Benau** [comment]
just expand ```v(server database version)_(your_server_config_filename_without_.xml_extension)_stats``` into sth like ```v1_abc_stats``` if you have a abc.xml server xml config
