### ISSUE TITLE
Session not valid after a few hours of running the server

### ISSUE THREAD

**Issue by Luca-Hummel** [supertuxkart/stk-code#4539]
Somebody already asked this question [here](https://github.com/supertuxkart/stk-code/issues/4305) , but the answer isnt really helping me, since my server doesnt need nat penetration or anything. It is fully port forwarded and everyone can join like they want. I want to add 2 bots though.  Still, after some time the issue described in the link happens and it says "session not valid" and i have to restart the server.

so, what can I do to not have this happening? Does the setting in the serverconfig.xml that asks if the server is behind a firewall play a role?

**Comment by Benau** [comment]
from my testing it's not true, your server is still behind a firewall

There are 3 tries until it works (with a mapped port)

**Comment by Benau** [comment]
and by the way thats only related to your network enviroment and not something server_config.xml can fix

**Comment by Luca-Hummel** [comment]
> and by the way thats only related to your network enviroment and not something server_config.xml can fix

How exactly do you know which one is my server? and if you know which on it is, then how did you test if it is behind a firewall? I port forwarded for sure so all the connection to the server are open

**Comment by Benau** [comment]
```
[info   ] ConnectToServer: Trying connecting to 88.153.244.3:2759 from port 53261, retry remain: 3
[info   ] ConnectToServer: Trying connecting to 88.153.244.3:2759 from port 53261, retry remain: 2
[info   ] ConnectToServer: Trying connecting to 88.153.244.3:2759 from port 53261, retry remain: 1
[info   ] ConnectToServer: Trying connecting to 88.153.244.3:2759 from port 53261, retry remain: 0
[info   ] ConnectToServer: Trying connecting to 88.153.244.3:2759 from port 2758, retry remain: 10
[info   ] ConnectToServer: Connected to 88.153.244.3:2759
```
if it's port forwarded it should be connected at first try ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by Benau** [comment]
it seems that you are hosting a server with a domestic internet connection (not some cloud internet out there like digitalocean), if so then it can be your ISP problem too

**Comment by Luca-Hummel** [comment]
So the initial issue was, that the session times out. I didnt know why. Now I know that if the server isnt connectible because of a firewall or else, then the described issue happens and the server has a not valid session after some time. Since the solution to this is to make the server connectible correctly, I can close this issue.

**Comment by kimden** [comment]
I might still have this problem while I'm sure all the needed ports are open. In fact, it happened for me that the user was initialized very recently, yet starting a server could be denied because no user was registered.

I will provide more info when I'm more aware of under which circumstances it happens for me (I'm kinda confused why and what is happening, seems to depend on random), and either reopen it or create a new issue.
