### ISSUE TITLE
Pressing enter in the addons search does not work

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4540]
## Description
If you type in something into the addons search and press enter, it doesn't work (the search does not start) while the focus is still on the text input field (which is pragmatically speaking almost always the case).

Oddly, if you type in something into that searchfield, then move focus *away* from the text input field (for example, on the "Karts" tab), and *then* press enter, the search works.

This doesn't mean the search is completely broken; clicking on the magnifying glass always works. At the very least, it is an usability issue since "pressing enter on the search field starts the search" is standard practice and it seems this behavior was the intention here anyway.

## Steps to reproduce
1. Go to addons menu
2. Type in "tux" and press enter. (Make sure to not lose focus of the text input field!)

I expect the search to start but it does not start.

## Configuration
Version 1.2.
I'm on GNU/Linux (tested on Arch Linux).

**Comment by Benau** [comment]
Addons searching is now improved in git stk-code
