### ISSUE TITLE
STK Discord Server

### ISSUE THREAD

**Issue by FS-Schach** [supertuxkart/stk-code#4543]
Hello,
I would like to create a discord server for Super Tux Kart, also official - may I do that?
I have big knowledge in discord so I think I am able to do that.
I also created already an unofficial but it is in development…
https://discord.gg/FgrKNgPZ8R

Best regards FS-Schach

BTW: I am also playing STK and it makes much fun.

**Comment by Benau** [comment]
STK doesn't promote non-free chatting software, please use IRC instead ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by Benau** [comment]
Unofficial discord exists still: https://discord.gg/m272UTf

**Comment by 2gn** [comment]
> Unofficial discord exists still: https://discord.gg/m272UTf

The link is dead. Could you give me another one?

**Comment by kimden** [comment]
> The link is dead. Could you give me another one?

https://discord.gg/u2AJDpF
