### ISSUE TITLE
Show duration survived in 3 Strikes Battle

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4544]
After 3 Strikes Battle, the game shows 'Eliminated' next to all eliminated players. I wish the game would show the duration they survived.

**Comment by Benau** [comment]
maybe @mrkubax10 can ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif) it...

**Comment by mrkubax10** [comment]
I'll do this

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/cut.gif) by c6c7679
