### ISSUE TITLE
Soccer ball can fly out of soccer field

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4546]
## Description

It is possible for the soccer ball to fly out of the Soccer Field map.

(thankfully, the ball just resets after that so it doesn't break the game but it is still irritating)

## Steps to reproduce
1. Play Soccer Field
2. Try to shoot the soccer ball very high so it flies out of the arena

## Configuration
STK release version: 1.2
STK Source (PPA, distribution package, official binary, etc.): Arch Linux

## Additional information

Here is video evidence in the Unofficial Soccer Tournament June 2021:
https://www.youtube.com/watch?v=wundrb9i8gs (at minute 31:12)

Note the Unofficial Soccer Tournament is a modded server to my knowledge but IIRC it doesn't modify physics. And IIRC, I have seen this bug a plenty of times before, including standard soccer games, but I always forgot to report it.

**Comment by Benau** [comment]
Soccer and Icy are now ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif) with top invisible wall to prevent that from happening again
