### ISSUE TITLE
display rank order numbers on match result screen

### ISSUE THREAD

**Issue by lokpro** [supertuxkart/stk-code#4550]
## Description
Should display order numbers on the match result screen, helpful for many-kart(like 20) matches.
![match result screen](https://149366088.v2.pressablecdn.com/wp-content/uploads/2019/12/supertuxkart-v1.1.jpg)

**Comment by Benau** [comment]
maybe only do that if > 10 players

**Comment by lokpro** [comment]
I don't know if 10 is easy to count or not :D
As now, we always play 20 karts, I and my children count our ranks every time we finished a race.

**Comment by Benau** [comment]
fixed by kuba pr ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

maybe ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) can ![](https://cdn.lihkg.com/assets/faces/mouse/potion.gif) linux build ![](https://cdn.lihkg.com/assets/faces/mouse/miracle_special.gif)

**Comment by deveee** [comment]
http://31.media.tumblr.com/cdee4e1b4a85c30141ebf368149b04a8/tumblr_n5kaovBJUF1s2wio8o1_500.gif
