### ISSUE TITLE
Compilation fails with error: ‘SDL_GameControllerRumble’ was not declared

### ISSUE THREAD

**Issue by eltomito** [supertuxkart/stk-code#4554]
## Description

Compilation fails, because error: ‘SDL_GameControllerRumble’ was not declared in this scope 

## Steps to reproduce

1) checkout stk-code commit 7bf9a0a4a84ba142c491e736e666cd580562e5c4
2) try to compile stk-code on Ubuntu 18.04 with SDL 2.0.8 (where pkg-config --modversion sdl2 says: "2.0.8")
3) cd cmake_build; cmake ..; make
4) watch the compilation fail about half way through as described above

## Configuration

STK release version: git, commit 7bf9a0a4a84ba142c491e736e666cd580562e5c4  - May 21, 2021
https://github.com/supertuxkart/stk-code/commit/7bf9a0a4a84ba142c491e736e666cd580562e5c4

System:  Ubuntu 18.04
Graphics card: intel built in
CPU:  Intel i5-2340

## Additional information

I confirmed that the previous commit compiles fine, so the referenced commit is pretty much sure to be the culprit.

It seems that the SDL_GameControllerRumble function was only implemented in SDL 2.0.9, so STK should check for that version before using it. There's a relevant discussion of that in the Riust-SDL project: https://github.com/Rust-SDL2/rust-sdl2/issues/865

It seems the whole body of the ```SDLController::doRumble()``` function in ```input/sdl_controller.cpp``` should be enclosed in
```#if SDL_VERSION_ATLEAST(2,0,9)```

Error message:
```
/home/tomas/src/supertuxkart/stk-code/src/input/sdl_controller.cpp: In member function ‘void SDLController::doRumble(float, float, uint32_t)’:
/home/tomas/src/supertuxkart/stk-code/src/input/sdl_controller.cpp:274:9: error: ‘SDL_GameControllerRumble’ was not declared in this scope
         SDL_GameControllerRumble(m_game_controller, scaled_low, scaled_high, duration_ms);
         ^~~~~~~~~~~~~~~~~~~~~~~~
/home/tomas/src/supertuxkart/stk-code/src/input/sdl_controller.cpp:274:9: note: suggested alternative: ‘SDL_GameControllerName’
         SDL_GameControllerRumble(m_game_controller, scaled_low, scaled_high, duration_ms);
         ^~~~~~~~~~~~~~~~~~~~~~~~
         SDL_GameControllerName
CMakeFiles/supertuxkart.dir/build.make:1979: recipe for target 'CMakeFiles/supertuxkart.dir/src/input/sdl_controller.cpp.o' failed
make[2]: *** [CMakeFiles/supertuxkart.dir/src/input/sdl_controller.cpp.o] Error 1
CMakeFiles/Makefile2:358: recipe for target 'CMakeFiles/supertuxkart.dir/all' failed
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by eltomito** [comment]
I found the commit in SDL that added the SDL_GameControllerRumble function and if I understand it right, it first appeared in SDL 2.0.9:
https://github.com/libsdl-org/SDL/commit/d2042e1ed4e0808103168bf1bf2135601b969c4f

**Comment by Benau** [comment]
I recommend either update SDL2 or use or static linux build, ![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) by ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif)! https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20210714-linux-64bit.tar.xz

otherwise you are missing (great!) rumble effect from your super gamepad ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) i'm not a fan of disney btw, duckduckgo darkoutpost disney![](https://cdn.lihkg.com/assets/faces/pig/arrested.gif)
