### ISSUE TITLE
User is logged out after changing local name

### ISSUE THREAD

**Issue by mettesuvanto** [supertuxkart/stk-code#4558]
## Description

Changing the local name requires the user to input their password, but the password field does not appear on screen. User is also logged out when changing the local name. To get the password field appear on screen user needs to either go back and re-enter the login page or change the local name again. With the second option user can’t input their username to the field. To get the username field accept input user needs to try to log in without username and after that user can type login information normally.

## Steps to reproduce

1.	Go to the login page 
2.	Click “rename” 
3.	Write new local name 
4.	Click “ok” 
*”Password is needed” message appears on screen but no password field appears* 
5.	Click “rename” and then “ok” 
*Username and password fields appear, but the former does not accept input* 
6.	Write password in the password field 
7.	Click “ok” (not getting logged in, but after that username field accepts input and user can type login information normally) 

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): github

System: Windows 10

Graphics card: Intel UHD Graphics

CPU: Intel® Core™ i5-1035G1

**Comment by Benau** [comment]
needs few days until a fix.....

**Comment by mrkubax10** [comment]
Maybe this can be fixed by just not checking password when user changes local name, it's just local name so it isn't very important
