### ISSUE TITLE
Separate Kart Type/Class Selection

### ISSUE THREAD

**Issue by lottieratworld** [supertuxkart/stk-code#4568]
A feature I would really enjoy is a separate option in the kart selection screen to choose the Kart Type independently from the kart. The options could simply be Default (the default behavior, type based on your kart's actual stats), Light, Medium, and Heavy. This way you can always have your preferred kart type and stats even on karts that are normally a different type.

As an example of this feature in another game, take a look at Crash Team Racing: Nitro Fueled's engine swapping feature, which lets you pick the engine class independently from your character choice, with the character-dependent engine option being called Classic.

**Comment by Benau** [comment]
This can not be done untile next major release

And I think it's good idea to not have this feature so in online you can know your opponent kart specs by just looking at the kart

**Comment by Alayan-stk-2** [comment]
I think it's too confusing. Right now, it's easy to remember the kart class of the karts and to know the kart class of any kart you see, if you allow to pick a custom class for any kart there is no easy way left to know the class of a different kart.
