### ISSUE TITLE
Cannot define custom particle effects for karts

### ISSUE THREAD

**Issue by bluecat999** [supertuxkart/stk-code#4569]
## Description
It appears that only particle effects already present in the data folder or current track can be used in the kart's exhaust particle option. This prevents new custom particle effects to be made for a specific kart.
Attempting to use a particle effect placed in the kart addon's folder will crash the game.

## Configuration
STK release version: 1.2 & quick review of current git source code

**Comment by Benau** [comment]
The crash is fixed in ad531ba and I have no intention to allow custom particle effects for now as it will break old stk version

maybe this can be reconsider for next-next version (after more people switching to new stk version)

**Comment by bluecat999** [comment]
Shouldn't it remain open set to a further milestone (like 2.0) as a feature request?
