### ISSUE TITLE
Audio output locked

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4570]
## Description
If you change the audio output source when the game is open, the game audio will still play from the previous audio output, forcing you to restart the game to use the new audio output.

## Steps to reproduce
1. Open the game.
2. Change the audio output source.
3. The game audio will still play from the previous audio output.

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): binary

System: Windows 10 64-bit

**Comment by Benau** [comment]
Only sdl "mojoal" is smart enough to fix it, maybe next stk release will use it instead

Using official OpenAL is not fixable
