### ISSUE TITLE
No Touch Screen Input - Android 11

### ISSUE THREAD

**Issue by pebkacs** [supertuxkart/stk-code#4572]
## Description
I downloaded Super Tux Kart v1.2 (205) a couple of months ago on my Pixel 3 (Android 11, F-Droid).  To my recollection, I was able to play it without any issues at that time.  Since then, I've had at least one update to my OS, and now there is no touch input response after launching Tux Kart.

## Steps to reproduce
1. Launch Super Tux Cart on my Pixel 3 (Android 11)
2. Try (unsuccessfully) to touch any buttons

## Configuration
v1.2 (205) on F-Droid

System: 
Google Pixel 3

## Additional information

stdout.log: Can't locate it anywhere
```

```

input.xml: Same issue as stdout.log
```xml

```

Error message: None
```

```
## Troubleshooting
* Cleared app cache
  * No change
* Deleted app data
  * No change
* Reinstalled app
  * No change
* Rebooted phone
  * No change
* Pressing the "back" button on the phone allows me to bypass the initial screen where you select your control type (steering wheel, etc)

**Comment by Benau** [comment]
duplicated of #4392, you can download latest apk on https://github.com/supertuxkart/stk-code/releases/tag/preview

**Comment by pebkacs** [comment]
Thanks a bunch!  I'm surprised I could not find that post in my search.  That works great for me as well.  Looking forward to the next release.  Thanks for all you do!
