### ISSUE TITLE
Reflections in glossy material have incorrect position

### ISSUE THREAD

**Issue by bluecat999** [supertuxkart/stk-code#4574]
## Description
When using a gloss map to create reflections, the reflections are at an incorrect angle/position. This is very obvious when using highly reflective materials, a car in front of a glossy object often can't be seen in the reflection, and reflections in meshes keep moving when you drive past them.

## Steps to reproduce

This can be tested by using any highly-reflective material, when using graphics settings >= 4.
Here is a track covered in many fully-reflective surfaces for testing. These issues can be seen just by driving around.
[aCrystalineTestway.zip](https://github.com/supertuxkart/stk-code/files/6954792/aCrystalineTestway.zip)
Here is an example image from that track:
![Screenshot](https://user-images.githubusercontent.com/16522958/128713432-67275e0a-74fb-478b-a974-a5e6b8a271db.png)

## Configuration

STK release version: STK 1.2

STK Source (PPA, distribution package, official binary, etc.):  Official binary

System: Linux

Graphics card: NVIDIA

**Comment by CodingJellyfish** [comment]
Investigated, caused by inaccuracy in normal decoding&encoding.

**Comment by qwertychouskie** [comment]
I have a local branch where normal encoding/decoding isn't a thing, the offset is still there.  `minRayStep` definitely shouldn't be anywhere near as high as it is, but changing to a value closer to what would be expected flips everything upside-down.

**Comment by CodingJellyfish** [comment]
![image](https://github.com/supertuxkart/stk-code/assets/35170687/081f5e24-ca40-4f00-8d54-0f007abc51ad)

**Comment by qwertychouskie** [comment]
That looks much better, though it is a bit weird that the skybox has a bokeh effect while the reflection doesn't, perhaps the shader passes should be re-ordered?

**Comment by CodingJellyfish** [comment]
![image](https://github.com/supertuxkart/stk-code/assets/35170687/06cb9459-df17-434e-a5c5-a6ef9ca09ae6)
Good quality bad performance version
