### ISSUE TITLE
Rocket start not working in specific circumstances

### ISSUE THREAD

**Issue by anonymous7002** [supertuxkart/stk-code#4578]
## Steps to reproduce
1. Bind select and Accelerate to the same button.
2. Start a cup.
3. When the first cup race is finished, press the button bound to Select and Accelerate to start the next race.
4. Attempt a rocket start (accelerating at Set)
5. The kart stays in place. Rocket start only works if you have pressed the button in between the presses to start the next race and to do the rocket start.

## Configuration

STK release version: 1.2

STK Source (PPA, distribution package, official binary, etc.): Official binary

System: Windows 10 64-bit

Gamepads/keyboards models if related to the issue: Logitech F310

**Comment by Benau** [comment]
I think it's sdl limitation and cannot be fixed in stk side, for now please dont bind them as same button
