### ISSUE TITLE
add random and reversed starting order for GP

### ISSUE THREAD

**Issue by lokpro** [supertuxkart/stk-code#4581]
Hi, in short, can random and reversed starting order be added to GP as an option? Thanks.

---

If you know the game [GeneRally](https://gene-rally.com) , you know it has 3 options for starting order - by points, reversed, and random.
As now, STK, winning karts always have advantage in the starting order. 

My little kid always complains she is starting at the last, and keeps losing :'(
If we can reverse the order, she will be soothed :)

Besides, the GP match can be more competitive in reverse order since more or less it is harder for karts to win again.

Last, randomised order will add fun and surprise whenever a race starts.

P.S. we always play 20 karts, so it matters.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/blob/6d29bb21ba3cb99f1257cd506bb093c2be33e9c5/src/config/user_config.hpp#L585

![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by lokpro** [comment]
Found it! \AppData\Roaming\supertuxkart\config-0.10\config.xml

It's ok for my need,
but I'd suggest to leave this issue open for maybe some nice person to add a friendly settings in the game and think about random order in the future.

**Comment by lokpro** [comment]
https://github.com/supertuxkart/stk-code/pull/4627/commits/825de9bd7b7d468bb5f5418befb72fe326c42b91 Add a user config option to randomize the player position at the star…

and

https://github.com/supertuxkart/stk-code/issues/4621#issuecomment-926994470 "stk prefers as little ui options as possible so please just make it an option in config.xml...."
