### ISSUE TITLE
Font color of the achievement list

### ISSUE THREAD

**Issue by risostk** [supertuxkart/stk-code#4585]
## Description
The font color of the list on the achievement page is different from every other lists. This is an issue for all official skins.
I looked at the code, but didn't find places where this color is set. Hope developers can help. Thx.

## Steps to reproduce
Go to
- Main page | Achievements
or
- Main page | Online | Your profile | Achievements
You can check the Friends Tab, the font color is same as text::neutral.

## Configuration
STK release version: git 26bb43d

**Comment by Benau** [comment]
that's ListWidget::emphasisItem

**Comment by risostk** [comment]
Thanks. I see what you mean. It is designed to like this: once the achievement is done, it will displace emphasis_text::neutral instead of text::neutral.
