### ISSUE TITLE
Abyss: Auto-rescue not activating

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#4586]
## Description
You can drive outside the track in the first curve of Abyss after the start
This is especially annoying for new users, as they are not saved and think there is a hidden path

Video: https://streamable.com/m8vtlx

## Steps to reproduce
1. Start on Antediluvian Abyss
2. Jump over the ledge in the first curve

## Configuration
STK release version: 1.2
STK Source: official binary
System: Ubuntu 20.04

**Comment by Benau** [comment]
It's fixed in latest stk-assets, thank you for your report ![](https://cdn.lihkg.com/assets/faces/pig/clap.gif)
