### ISSUE TITLE
website: 'Discover' page has old addons.stk.net link

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-code#4587]
On https://supertuxkart.net/Discover at the bottom under "...And many more!" there's an old link leading to addons.supertuxkart.net which is defunct for quite some time.

The new one https://online.supertuxkart.net/ should be here instead.

**Comment by Benau** [comment]
It's now fixed, thanks for the reminder ![](https://cdn.lihkg.com/assets/faces/pig/wine.gif)
