### ISSUE TITLE
[Newbie Question] How to install?

### ISSUE THREAD

**Issue by TheYellowArchitect** [supertuxkart/stk-code#4590]
Hello, I am a linux newbie, and a year ago or sth I had seen this game, but ignored it as some generic mario kart clone with bad graphics

I happened to see the trailer of 1.3 and I want to give it a try
I downloaded SuperTuxKart-1.3-rc1-linux-64bit.tar.xz from https://github.com/supertuxkart/stk-code/releases/tag/1.3-rc1

I use tar -xf and it unzips, and I can enter the folder and see `run_game.sh` with the following folders next to it: bin, data, lib.
When I type `run_game.sh` via terminal on its file location, I get
`zsh: command not found: run_game.sh` even with sudo chmod 777 (executable allowed)
As for my distro, I use artix with dwm pretty much

Any help is appreciated (I am a linux newbie), I really want to give it a try, maybe even play with friends to see how the netcoding holds up lol

**Comment by TheYellowArchitect** [comment]
Actually wait, opening it up again because I have way too many paths on $PATH, while it only needs the .sh file.

This is in my zshrc pretty much, any1 know how to put exclusively the `run_game.sh` inside?
```# Append our default paths
append_path '/usr/local/sbin'
append_path '/usr/local/bin'
append_path '/usr/bin'
append_path '/usr/local/bin/supertuxkart1.3/run_game.sh'
```

Typing `echo $PATH` literally returns all possible paths inside the game's folder

**Comment by Benau** [comment]
The tarball you download is not intended for installation... you need to ```./run_game.sh``` instead

You need to wait for official supertuxkart 1.3 from distro repo after final release

**Comment by Alayan-stk-2** [comment]
The issue tracker is to report issues with the code/game, not for general support questions.
