### ISSUE TITLE
1.3 rc run fails

### ISSUE THREAD

**Issue by antvrs** [supertuxkart/stk-code#4595]
## Description

run attempt results in:
Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  257
  Current serial number in output stream:  258

## Steps to reproduce

try to run from terminal

## Configuration

STK release version: 
1.3 rc

STK Source (PPA, distribution package, official binary, etc.): 

System: 
Fedora 34
Graphics card: 
intel hd4000 
CPU: 
intel i5 gen 3

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
You can try copy system libSDL2.so to lib folder inside SuperTuxKart-linux-1.3-rc1 and see if it works?

**Comment by antvrs** [comment]
System search doesn't locate libSDL2.so
 libSDL2-2.0.so.0 is already in that folder.
 stk  1.2 is installed. 
 Thanks for the quick response. 
 -A

**Comment by antvrs** [comment]
solved by replacing libSDL2-2.0.so.0 with the one from usr/lib. Closing, thanks again.
