### ISSUE TITLE
Crash in the Highscore manager

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4599]
I was testing the "grand prix highscore" feature.

I did a normal GP. At the end, after the podium screen, I went to the highscore manager and selected the Grand Prix tab. There was an entry for the newly completed GP. I double-clicked the entry to open the popup with the details.

At this point, the game segfaulted. I assume the highscore entry was malformed, but this should be handled gracefully by the manager instead of a crash.

Additional testing is required to establish what kind of malformed input can lead to crashes.

@RQWorldblender

**Comment by RQWorldblender** [comment]
I have been encountering those same issues myself, but it's just that I didn't know exactly what caused these segfaults. Additionally, I think that either grand prix high scores need more info, such as minor mode used, and what kind of reverse type, or grand prix high scores need to be removed entirely.

**Comment by mrkubax10** [comment]
My idea for adding more info is separating track highscores and grandprix highscores so they use different files. Additional informations were dropped because highscore.xml format is specialised for tracks and that would require format change.
