### ISSUE TITLE
The "custom" button for camera settings is confusing

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4603]
The spinner for camera settings has 3 possible values: "Standard", "Drone Chase" and "Custom". Then there is the "custom" button next to the spinner.

Changing anything is disabled if the spinner doesn't have the "Custom" value. This allows to see what are the settings used by "standard" and "drone chase" as reference, however it can be very confusing for a user that doesn't know how the spinner is working and just expects that clicking "Custom" will allow to customize.

**Comment by Benau** [comment]
too minor to be fixed sorry

**Comment by Alayan-stk-2** [comment]
I labelled it as "minor" for a reason but if no thought is given about a better UX, no fix will ever be made.
