### ISSUE TITLE
The end-race challenge info is wrong for GPs

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4604]
It checks the "rank 1" requirement against the place in the last race, not against the overall GP ranking. This is easily reproduced by giving up in the last race with enough points in front to win it anyway.

It probably also has no idea about the system allowing to get a lower-tier cup in GPs when not first. Considering it has been coded to tell the player about the more obscure "SuperTux time" in a lower difficulty, this is an oversight.

**Comment by Benau** [comment]
```c++
            bool position_passed = (kart->getPosition() <= c_data->getMaxPosition(difficulty) && lose_all == false)
                                || c_data->getMaxPosition(difficulty) == -1;
            bool time_passed = (kart->getFinishTime() <= c_data->getTimeRequirement(difficulty) && lose_all == false)
                                || c_data->getTimeRequirement(difficulty) <= 0.0f;
            bool energy_passed = (kart->getEnergy() >= c_data->getEnergy(difficulty) && lose_all == false)
                                || c_data->getEnergy(difficulty) <= 0;

            bool is_gp = RaceManager::get()->getMajorMode() == RaceManager::MAJOR_MODE_GRAND_PRIX;
            if (is_gp && RaceManager::get()->getKartGPRank(kart->getWorldKartId()) == 0)
            {
                position_passed = true;
                time_passed = true;
                energy_passed = true;
                lose_all = false;
            }

            bool all_passed = position_passed && time_passed && energy_passed;

```
<img src="https://cdn.discordapp.com/attachments/588002848051036169/882292555172159538/Kiki-Confused.png" width="200">

**Comment by Benau** [comment]
the above is not correct and need some more cooking........
![](https://cdn.lihkg.com/assets/faces/pig/cook.gif)
