### ISSUE TITLE
Wrong ranking for ties

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4607]
If you finish a Free For All battle game and multiple players have the same score, their ranks in the end screen are unequal.

For example, if two players play and both have 5 points, only one player is ranked 1, while the other one is ranked 2.

Tested in 7aeb0b0edf741be04f4561fe01081863a3cb0939 on GNU/Linux.

**Comment by Alayan-stk-2** [comment]
Only happens with 10 karts because below it, no rank number is shown.
