### ISSUE TITLE
Game says I finished 1st after nitro challenge

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4609]
When you finish one of the nitro challenges in Story Mode, the game tells me  in big letters "You finished the race 1st" (or something like that). This is technically correct but a little odd.
STK didn't do this in previous versions.
I suggest to change the finish message back to what it was before (I believe it was just that I finished the race without mentioning rank).

Maybe a more general solution is to not mention rank when I was the only racer, and just say I completed the race.

Tested in 7aeb0b0 on GNU/Linux.

**Comment by Benau** [comment]
Not important and too late for 1.3 to break translation
