### ISSUE TITLE
Story Mode Grand Prix challenge completion info disappears too quickly

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4610]
This is mostly an UX issue.

If you complete a grand prix in story mode (no matter if won or lost), there is now a new challenge completion text, telling you whether you have won the overall challenge or not.
This is a neat addition, but it comes one screen too early. When you finished the last race, the end screen has two parts:
The first part shows the times and ranks of the final race, and it is shown only for like 2-3 seconds.
Then comes the second part. The second part shows the overall GP scores and final rankings.

The challenge text is only shown in the first part, but not in the second part. Meaning this text disappears quickly.

But IMO it makes more sense to show the challenge text in the second part of the end screen, because that one doesn't go away without user interaction.
I suggest to either move the challenge completion text in the second part only, or to show it in both parts of the end screen.

How to reproduce:
* Complete a GP in Story Mode
* Closely watch the end screen(s)

Tested in 7aeb0b0 on GNU/Linux.

**Comment by Alayan-stk-2** [comment]
I noticed the same thing, but I'd say the latest race result disappearing so quickly without user input is by itself an issue.

**Comment by Alayan-stk-2** [comment]
This was fixed through 70070b3 adding a "continue" button before scrapping the first half of the GP results
