### ISSUE TITLE
Best times don't recognize times above 59:59.999

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4611]
If you finsh a GP with a total time greater than 59:59.999, this time is correctly shown in-game but when you go to the Best Times menu to review this time, your time is capped at 59:59.999.
Seems like the Best Times menu can't handle times that are longer than that.

Note: You can reach such a high time in GP easily by giving up on a single race in a GP because you'll get a penalty time of 1 hour.
You can also reach the time "legitimately" by playing a very long GP (I believe a GP with all tracks needs more than 1 hour).

Tested in 7aeb0b0 on GNU/Linux.

**Comment by Alayan-stk-2** [comment]
As previously high-scores only tracked GPs, this was not a relevant design consideration as even 20 laps of the longest track would fall well under an hour.

**Comment by mrkubax10** [comment]
My idea how to fix this without changing how highscores work is to save highscore only when user didn't skip all tracks

**Comment by Wuzzy2** [comment]
As a temporary solution (without changing highscore format, etc.), don't save the highscore at all when the maximum allowed time is reached. That way, oddities are avoided when you got a (fake) 59:59.999 time from an old version and later the real times above 1h come in

**Comment by mrkubax10** [comment]
Actually this also happens in kart times in race result after skipping at least one track but time here shows correctly

**Comment by Wuzzy2** [comment]
I don't believe by not saving highscore for skipping a track is actually fixing the bug.
The bug is that times above 59:59.999 don't saved. Whether this time was gotten by a really long racing time or skipping doesn't matter.
If you had a really long GP with no skips, you still can go above 59:59.999. Is the time still saved then? Has this been tested?

@mrkubax10 @Benau

**Comment by Benau** [comment]
61f513e  ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

maybe kuba pr can be reverted after this  ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by mrkubax10** [comment]
I already tested that high time shows because function estimateFinishTimeForKart doesn't work when player didn't move (because of division by zero). Overall this problem is not only related to highscores. Also I would like to know how you can get very high time without skipping tracks

**Comment by mrkubax10** [comment]
In my opinion times when player skipped track shouldn't be saved

**Comment by mrkubax10** [comment]
If you want to revert this pull request I'm fine with this
