### ISSUE TITLE
Formatting of track author field is inconsistent

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#4614]
(note: This issue is actually about `stk-assets` revision r18442 but I can't find the bugtracker for it.)

The way how the author(s)/designers(s) of tracks in STK are documented (in-game) is very inconsistent. It sometimes contains words that are not part of an author name, but the author info is never translatable. The word "and" and other words are used sometimes. Also, there are various inconsistencies. This annoyed me for a while now.
(Technically, I am talking about the contents of the "designer" field in `track.xml`.)

The problems in detail:

* Problem 1: Some tracks have multiple authors but are inconsistent in how the author list is formatted. Some use the literal word "and", others use "&", "&&", "," or other characters.
* Problem 2: Some tracks are overly detailled in the author field, mention who did what in the track. This is untranslatable, clutter and blows up the in-game info
* Problem 3: The name "Jean-Manuel Clémençon" occurs many time in the tracks, but in various inconsistent variations (lower/uppercase, cedille, gravis, etc.)

Suggested solutions:
* Use a consistent way to write author lists. I suggest to always use the exact string " & " as a separator (with spaces) between each author name. The "&" character is recognized in most languages and minimizes translation issues.
* Remove all extra descriptions from author info to keep it minimal; if neccessary, put it in a text file or whatever
* Find out the true name of Jean-Manuel Clémençon and apply it consistently. Unless it turns out this was intentional

Example for a track with 3 authors: "Gollum & Gandalf & Aragorn"

The goal here is to remove all additional words besides the author name from the field. The only exception is the " & " separator.
A nice benefit of this cleanup will be that a future version of STK might parse the author field to render a list or something like that, without needing to change the data format.

**Comment by Benau** [comment]
it's now all fixed, thank you for your report ![](https://cdn.lihkg.com/assets/faces/pig/clap.gif)

**Comment by Wuzzy2** [comment]
Not entirely. `gpwin.xmp` has "`QwertyChouskie, jean-manuel cl&#233;men&#231;on`". There's a comma.

**Comment by Benau** [comment]
Fixed too ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
