### ISSUE TITLE
Set a random starting position for the player karts

### ISSUE THREAD

**Issue by iwoithe** [supertuxkart/stk-code#4621]
## Description

I get annoyed when I start a race as I am always at the back. I would like this to change so that the (player) karts are in a random position (as well as the first race of a GP).

## Steps to reproduce

1. Click on ``Single Player`` and choose the player (I would presume that this issue also occurs in multiplayer but I haven't done a race in multiplayer yet)
2. Choose either ``Normal Race``, ``Time Trial`` or ``Follow the Leader``
3. Start the race (with AI karts)

## Configuration

STK release version: git

STK Source: Compiled from source and official binaries

## Additional information

If possible I would like to attempt this issue (I have successfully achieved what I would like). :slightly_smiling_face:

### Related issues

- https://github.com/supertuxkart/stk-code/issues/4581

**Comment by Alayan-stk-2** [comment]
On one hand that's the one area of the game where the player is treated "unfairly" compared to the AI.

On the other hand, it means that the starting position is not down to luck in story mode challenges and that different races are more comparable to each other. There is some value to this consistency, which is why many other kart racing games also put the player at the back of the field when starting a new race.

**Comment by iwoithe** [comment]
> On one hand [...] On the other hand

So could an option be added to the race setup menu (something like ``Set random player positions``) where the default is off?

**Comment by Alayan-stk-2** [comment]
Possibly yes, but it should not clutter the UI. Perhaps first focus on making it a working xml config option before we may consider an UI option.

It is important to make sure that this doesn't affect story mode nor break anything else.

**Comment by iwoithe** [comment]
This is how it looks so far. I need to revisit the GUI (too much padding/spacing).

https://user-images.githubusercontent.com/73422868/134753345-0b8b05d7-6ff6-4dcf-99f3-44b75c67d01d.mp4

> this doesn't affect story mode nor break anything else

It doesn't affect story mode or anything else (that I am aware of).

**Comment by Benau** [comment]
stk prefers as little ui options as possible so please just make it an option in config.xml....

**Comment by iwoithe** [comment]
> stk prefers as little ui options as possible

Okay. :slightly_smiling_face:

> just make it an option in config.xml

I'll work on this. I will ask questions if I get them.

**Comment by iwoithe** [comment]
Is ``config.xml`` the ``data/stk_config.xml`` file?

**Comment by Benau** [comment]
in $HOME/.config/supertuxkart/config-0.10/config.xml ![](https://cdn.lihkg.com/assets/faces/pig/smile.gif)

**Comment by iwoithe** [comment]
> in $HOME

Is that in the AppData directory on Windows?

**Comment by iwoithe** [comment]
I've now added this to ``config.xml``. Do I add something to the ``SuperTuxKart Options`` (or just leave it as is)?

**Comment by Benau** [comment]
no need to change ui

**Comment by iwoithe** [comment]
> no need to change ui

How would I change that setting in the game (or do I just leave it)?

**Comment by Benau** [comment]
leave it for now

**Comment by iwoithe** [comment]
> leave it for now

I will upload the PR within the next few days (I don't have the time to do it now).

**Comment by lokpro** [comment]
HI @iwoithe , does "random-player-pos" have effect on the first race only?

**Comment by lokpro** [comment]
I have reviewed the code. There is a bug. I can be the leader.
![image](https://user-images.githubusercontent.com/2010297/135635352-3ca67bb9-8267-4f93-9e4c-f2d00f81d3e5.png)

_RaceManager::startNew()_ adds AI karts, then player karts. The first kart will be the leader. Shuffling all karts can make me the leader.
https://github.com/supertuxkart/stk-code/blob/87fd3f221a2eddc1d1bcfefc17fc988b36a93e0b/src/race/race_manager.cpp#L494-L506

see below, I think you can add the _offset_ like this.
https://github.com/supertuxkart/stk-code/blob/87fd3f221a2eddc1d1bcfefc17fc988b36a93e0b/src/race/race_manager.cpp#L573-L589

**Comment by lokpro** [comment]
Second, as comment says, sorts should be done in _RaceManager::startNextRace()_
https://github.com/supertuxkart/stk-code/blob/87fd3f221a2eddc1d1bcfefc17fc988b36a93e0b/src/race/race_manager.cpp#L541-L545

```
    if (m_track_number == 0) // is first race
    {
       // if you only want to do random in the first race.
```

**Comment by lokpro** [comment]
Third, I think  _random-player-pos_ suits more in _<GpStartOrder>_ as there are hidden tweaks for start-order.
```
    <GpStartOrder
        most_points_first="false"
        player_last="false"
        random-player-pos="true"
    >
```

_<RaceSetup>_ are UI settings - was your original design.

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) (code!) later...

**Comment by iwoithe** [comment]
A few questions/answers...

> does "random-player-pos" have effect on the first race only?

Not that I am aware (when I implemented the UI checkbox it worked on more than just the first race).

> sorting should be done in RaceManager::startNextRace()

So move the code to ``RaceManager::startNextRace()``?

>  < RaceSetup > are UI settings

I didn't realise that. I'll change that.

> (code!) later...

What do you mean?

---

In the line

```cpp
player_last_offset = (int)m_player_karts.size();
```
what does ``(int)`` mean? Is it a type checker (I'm still learning C++)?

**Comment by Benau** [comment]
well iwoithe let me just do this for you...

**Comment by lokpro** [comment]
@iwoithe at least you can build the app :D   I have been struggling to figure out how to build. I only run the code in my brain.

**Comment by iwoithe** [comment]
>  I have been struggling to figure out how to build

What OS are you on? If you are on Windows take a look at [MSYS2](https://www.msys2.org) (it's what I've been using to compile C/C++ apps including SuperTuxKart). I've been more successful compiling software with MSYS2 than Visual Studio.

If you are on macOS I can't really help you as I've had no experience with it.
