### ISSUE TITLE
Change "standard" to "Standard"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#4622]
## Description
The string "standard" shoud be "Standard" multiple places.

## Steps to reproduce
Start STK
Select singleplayer
Bottom have 3 strings: "All", "standard", "Add-Ons"

Select a cart
Select normal race.
"standard" appear again.

Go back
Select Battle
"standard" appear again.

## Configuration
SuperTuxKart-1.3-rc1-installer-x86_64.exe
1.3-rc1
official binary

**Comment by qwertychouskie** [comment]
Can confirm, though on my system it's "standard".  Minor, but an issue nonetheless.

**Comment by scootergrisen** [comment]
> 
> 
> Can confirm, though on my system it's "standard". Minor, but an issue nonetheless.

Changed to "standard". I was using STK translated and just assumed it was "default".

**Comment by Benau** [comment]
Actually "standard" comes from kart.xml (and track.xml), changing this will break too many things and little benefit gain 
![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by qwertychouskie** [comment]
Would it be possible to add a "translation" of 'standard' to 'Standard' to the default language?  It's clearly translated for other languages anyways, though I'm not sure if there's a `.po` file for the default language.

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/smile.gif) is not in favour of using this ugly hack....

And qwerty can you reproduce logitech gamepad problem the (rude!) guy in irc?

**Comment by qwertychouskie** [comment]
IMHO it's better to add a translation than have inconsistencies in the user interface.  Though fixing the `track.xml`/`kart.xml` files likely wouldn't be a problem since STK 2.0 will break network compatibility anyways.

I tried my Logitech F310 gamepad in the official STK 1.3 build via run_game.sh and all seemed to work just fine.
