### ISSUE TITLE
Two settings that sounds the same: "Enable chatting online" and "Enable chatting in online games"

### ISSUE THREAD

**Issue by scootergrisen** [supertuxkart/stk-code#4623]
## Description
"Enable chatting online" and "Enable chatting in online games" sounds a lot like the same.
So i suggest making it more clear what the difference is if there is a difference or perhaps there only needs to be one of them.

## Steps to reproduce
Launch STK
Click Settings
Look at "Enable chatting online" and "Enable chatting in online games"

## Configuration
SuperTuxKart-1.3-rc1-installer-x86_64.exe
1.3-rc1
official binary

**Comment by Benau** [comment]
Second one means only disable chat in (playing) online games, and first one disable completely even in lobby

**Comment by scootergrisen** [comment]
Maybe the sub option should be idented so users can see it is a sub option of the parent.

**Comment by Benau** [comment]
![Screenshot_20210923-234321_SuperTuxKart](https://user-images.githubusercontent.com/3252341/134539961-aac1e529-6daa-4c21-aeed-8b69cbdce517.jpg)
![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by scootergrisen** [comment]
Graphics settings > Custom settings uses indentation for advanced pipeline.
I would get rid of the "Enable". It's not good text for checkboxes because then you are saying "I enable Enable chatting online" and "I disable Enable chatting online".
Let the checkbox state tell the user if the option is enabled or disabled.
If there is two options lobby and during gameplay then maybe combine the options to a dropdown list or one of those horizontal lists used in graphics settings > Advanced pipeline > Shadows whatever they are called.
Also when i disabled the parent option the checkbox of the child option is greyed out but the text of the child option stays the same so i suggest also greyout the text.

![billede](https://user-images.githubusercontent.com/1836590/134550258-2aa7184e-2309-435b-b116-0a8f984e0b83.png)
![x](https://user-images.githubusercontent.com/1836590/134552401-474b64d7-a6e9-4358-9d86-a50f9986598f.gif)
![x2](https://user-images.githubusercontent.com/1836590/134553664-09ea2f06-a667-4fc0-a070-531e22e20d52.gif)

Maybe the Show always login screen should also be a sub option of Connect to the internet if it is only during with an internet connection.
