### ISSUE TITLE
Sound quality regression in 1.3-rc1

### ISSUE THREAD

**Issue by akhilman** [supertuxkart/stk-code#4629]
## Description

All sound effects in the 1.3-rc1 sounds like high frequencies was faded.

## Steps to reproduce

1. Plug decent headphones;
2. Start race in 1.2 and 1.3-rc1 and compare sound quality.

## Configuration

* net.supertuxkart.SuperTuxKart 1.2 from FlatHub stable
* net.supertuxkart.SuperTuxKart 1.3-rc1 from FlatHub beta

System: Manjaro linux

Graphics card: AMD Radeon(TM) Vega 11 Graphics (RAVEN, DRM 3.40.0, 5.10.68-1-MANJARO, LLVM 12.0.1) (0x15d8)

CPU: AMD Ryzen 5 PRO 3400G with Radeon Vega Graphics

PipeWire 0.3.37 sound server.

## Audio samples
Samples recorded directly from STK output.

https://user-images.githubusercontent.com/180812/135189973-888015e5-6918-49b1-8032-2fae6581b1d6.mp4

**Comment by Benau** [comment]
you can try copy sfx/*.ogg from 1.2 and see if issue is fixed, otherwise i don't think we change sfx code in 1.3.

Unless they use a newer openal (or mojoal) which does pitch shifting differently (engine sound is handled by changing playing frequency)

**Comment by akhilman** [comment]
This is weird. This problem only shows up with my USB soundcard. With built-in sound card and HDMI audio output, STK plays the same audio in both versions.

There may be a problem with PipeWire or resampling.
