### ISSUE TITLE
current release for stk-assets missing?

### ISSUE THREAD

**Issue by Apfelwurm** [supertuxkart/stk-code#4633]
## Description

Hi together,
in the past i was getting the stk-assets for each version from https://svn.code.sf.net/p/supertuxkart/code/stk-assets-release/ but it seems there is no new asset version for 1.3 . Is this intentional and i have to use the latest one (1.1) instead to build stk?

Thanks!
Alex

**Comment by Benau** [comment]
Use this one https://github.com/supertuxkart/stk-assets-mobile/releases/download/1.3/stk-assets-full.zip
