### ISSUE TITLE
STK 1.3 "SSL peer certificate or SSH remote key was not OK"

### ISSUE THREAD

**Issue by CEHitchens** [supertuxkart/stk-code#4635]
## Description
Receiving STK news on the main menu does not work. Logging in to STK Online 'service' is not possible.
Running STK 1.3 on LinuxMint 20.2 using the "http://ppa.launchpad.net/stk/dev/ubuntu focal main" PPA

## Steps to reproduce
- Launch game
- Notice the "Error downloading news 'SSL peer certificate or SSH remote key was not OK' on the main menu
- Try to log in to the STK service, enter username, see some error message telling you that the connection to the server wasn't possible or to check the internet connection (which works.)

## Configuration
STK 1.3  (updated from 1.3rc1 today; thought it may be linked; rolled back that update; problem persists)
Linux Mint 20.2 Cinnamon

http://ppa.launchpad.net/stk/dev/ubuntu focal main

## Additional information

Please provide stdout.log, it is located in:
~/.config/supertuxkart/config-0.10 (Linux and other unix based systems)

stdout.log:
excerpt, related to error:
[info   ] HTTPRequest: Sending userid=XXXXXX&token=************************ to https://online.supertuxkart.net/api/v2/user/saved-session/
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[error  ] XMLRequest::afterOperation: curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[error  ] news: Error downloading news: 'SSL peer certificate or SSH remote key was not OK'.
[info   ] addons: Using cached addons.xml.

**Comment by Benau** [comment]
Try use this one instead https://github.com/supertuxkart/stk-code/releases/download/1.3/SuperTuxKart-1.3-linux-64bit.tar.xz 

Seems that if your system openssl is not compatiable with letsencrypt (stk addons certificate siging service)
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

maybe @qwertychouskie can rebuild the ppa with mbedtls?

**Comment by Benau** [comment]
or rebuild ppa with latest curl + openssl 3

**Comment by CEHitchens** [comment]
1st things 1st - thanks for your reply.

What I find strange though is that this is only a recent issue; last 1-3 days.
For at least 1 year (likely closer to 2) there had been no issue running it with this setup. Like I said, I just updated from 1.3rc1 to 1.3 today/yesterday which is why I rolled back the system to a state from right before the most recent update where the 1.3rc1 had no connectivity issues. I also looked at the apt installation history to see whether something related to this may have changed, I could not spot anything obvious. 

I'll roll back the system a whole week, which would be a state where I _know_ that STK1.3rc1 worked. And if it won't work having rolled back that one full week, somehow I would deduce from that, that it isn't a local problem, unless it were some change in ~/.config/supertuxkart/ (i.e. the latest STK1.3 update broke some configuration). My ~ is exempt from my system rollback. Wouldn't you agree?

**Comment by Benau** [comment]
no it wont work, just try the tarball i mentioned or switch to a distro which ship openssl 3

**Comment by Benau** [comment]
There is nothing wrong with local problem

**Comment by CEHitchens** [comment]
Benau, thanks for your efforts. 
Somehow though you totally skipped over the fact that things on the very same distro worked fine for 1+ to 2 years using the very same PPA.

I'll just wait and see what other suggestions / ideas may be shared here.

**Comment by Benau** [comment]
have you check this https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ ?

It has nothing wrong with your local stuff but some website certificate expires (which you have no control over)

and have you tried https://github.com/supertuxkart/stk-code/releases/download/1.3/SuperTuxKart-1.3-linux-64bit.tar.xz ?

Please reopen if the above doesn't work for you

**Comment by Benau** [comment]
There is no way to fix your issue if you intended to keep existing stk ppa

**Comment by Benau** [comment]
or if you don't want to try anything just wait until the ppa is rebuilt with latest curl + openssl (don't use system curl + openssl), @qwertychouskie maintain the ppa

**Comment by jhonny-oliveira** [comment]
Hi!

My case scenario and experiments:
Build in Ubuntu Focal (20.04).
Build in Ubuntu Hirsute (21.04).
Install package built on Focal in Focal: SSL error.
Install package built on Focal in Hirsute: no SSL error.
Install package built on Hirsute in Focal: fails to install - libc version.
Install package built on Hirsute in Hirsute: no SSL error.

At this point, it seems clear that the problem only happens in Ubuntu Focal. Therefore the remaining tests were done in Focal.

I tried downloading the xml with curl and it succeeds. Please, check the attached log: [SSL_validation_steps.log](https://github.com/supertuxkart/stk-code/files/7271847/SSL_validation_steps.log).
curl -L -v https://online.supertuxkart.net/dl/xml/online_news.xml

Just to double check, I have also reviewed the system. Both Let's Encrypt root/intermediate CAs and they are fine:
trust dump --filter "pkcs11:id=%C1%F1%26%BA%A0%2D%AE%85%81%CF%D3%F1%2A%12%BD%B8%0A%67%FD%BC;type=cert" | openssl x509 -text

At of today, the system only has two trusted root CAs expired, but they not related to the certificate used in https://online.supertuxkart.net.

Is it possible that the game is using some dependency library that drags along their own certs and it happens that this dependency has outdated trusted root CAs in LinuxMint 20.2  and Ubuntu Focal?

@Benau , any ideas? 

Thank you!
Jhonny

**Comment by Benau** [comment]
you can try copy latest https://github.com/supertuxkart/stk-code/blob/master/data/cacert.pem to installed 1.3 stk location and see if it works

the above method fixed windows stk binary at least

And if ```curl -L https://online.supertuxkart.net/dl/xml/online_news.xml``` fails for you, try:
```
sudo mv /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt /root
sudo sed -i 's#mozilla/DST_Root_CA_X3.crt#\#mozilla/DST_Root_CA_X3.crt#' /etc/ca-certificates.conf
sudo update-ca-certificates
```

basically try remove the expired certificate from the bundled list

**Comment by jhonny-oliveira** [comment]
Dear @Benau ,

Based on the latest cacert.pem you provided, I made a patch ([SSL_peer_certificate_or_SSH_remote_key_was_not_OK.patch.txt](https://github.com/supertuxkart/stk-code/files/7272036/SSL_peer_certificate_or_SSH_remote_key_was_not_OK.patch.txt)) and that solved the issue.

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by qwertychouskie** [comment]
@Benau If you push that commit to the 1.3 branch I'll update the packages in the PPA

**Comment by Benau** [comment]
Done

**Comment by qwertychouskie** [comment]
The PPA is now updated and should connect successfully.  If you encounter any more issues, let me know!

**Comment by CEHitchens** [comment]
Thank you very much for this extremely fast fix, @qwertychouskie
