### ISSUE TITLE
a way to disable addons?

### ISSUE THREAD

**Issue by lokpro** [supertuxkart/stk-code#4637]
Hi developers, what do you do to disable loading of add-ons to fasten startup of the game?

Commenting out the four lines does what I want.
https://github.com/supertuxkart/stk-code/blob/9bf537ab351f165555048fbc5df88193d8cd70f2/src/main.cpp#L1942-L1945

There are _--trackdir_, and _--kartdir_ cmd line params to add extra dirs.
Should we add something like _--disable-addon-track / kart_ for development or other purpose?

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/cook.gif) later or if lok knows how to ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif) a PR himself ![](https://cdn.lihkg.com/assets/faces/pig/dance4.gif)
