### ISSUE TITLE
Graphics Fail to Load on Samsung Galaxy Tab 2 7.0 (samsung-espressowifi)

### ISSUE THREAD

**Issue by antonialoytorrens** [supertuxkart/stk-code#4653]
## Description

Broken textures while playing the game.
Setting them at the lowest does not fix it.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): F-Droid package

System: LineageOS 13.0 (based on Android 6.0)

Graphics card: Imagination Technologies, PowerVR SGX 540

CPU: OMAP4 Espresso board

Gamepads/keyboards models if related to the issue: -

## Additional information

`adb logcat`:
[supertuxkart-espressowifi-logcat.txt.zip](https://github.com/supertuxkart/stk-code/files/7404304/supertuxkart-espressowifi-logcat.txt.zip)

### Screenshots
![espressowifi-stk-6](https://user-images.githubusercontent.com/47571676/138586331-a8f78494-817c-4b84-90c8-4da616e58694.jpg)
![espressowifi-stk-5](https://user-images.githubusercontent.com/47571676/138586332-5679c84f-502f-4404-aca3-70bfa0d6e5ae.jpg)
![espressowifi-stk-4](https://user-images.githubusercontent.com/47571676/138586333-bb262565-a4e7-49ae-a486-15667e7bf412.jpg)
![espressowifi-stk-3](https://user-images.githubusercontent.com/47571676/138586334-e1cb7ef3-5d6d-4334-82f5-603945625e5a.jpg)
![espressowifi-stk-2](https://user-images.githubusercontent.com/47571676/138586335-7b5ce32a-b4fc-4d52-89af-91da0aa46e4b.jpg)
![espressowifi-stk-1](https://user-images.githubusercontent.com/47571676/138586336-b50b438f-7bdd-48aa-9dab-695874f3ee0d.jpg)

#### Notes (a bit off-topic)
I have played on all of my devices. It works really well, great work! However, I have issues with Samsung Galaxy Tab 2 7.0.
Tested on:
* Huawei Ascend Y300-0100 (2013, Android 4.1) (fonts are not rendered well using cartoon theme, but using the STK default one works as expected. Old GPU issues)
* Motorola Moto G (1st generation) (2013, LineageOS 17.1)
* Xiaomi Redmi Note 5 (whyred) (2018, Android 9)
* Samsung Galaxy Note 8 (greatlte) (2017, Android 11)

**Comment by Benau** [comment]
will you possible to "hack" the apk yourself, add add
```xml
  <card vendor="PowerVR SGX 520" disable="NpotTextures"/>
  <card vendor="PowerVR SGX 530" disable="NpotTextures"/>
  <card vendor="PowerVR SGX 531" disable="NpotTextures"/>
  <card vendor="PowerVR SGX 535" disable="NpotTextures"/>
  <card vendor="PowerVR SGX 540" disable="NpotTextures"/>
  <card vendor="PowerVR SGX 545" disable="NpotTextures"/>
```
to data/graphics_restrictions.xml and see if it fixes your problem?

Otherwise i will prepare an apk later....

**Comment by antonialoytorrens** [comment]
Unfortunately putting this extra configuration in `data/graphical_restrictions.xml` does not fix the issue.
I have seen in the logcat that `OpenGL is too old`, so maybe the graphical issue cannot be solved?

**Comment by Benau** [comment]
how about `<card os="android" disable="NpotTextures"/>` only?

**Comment by Benau** [comment]
does it work? ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by antonialoytorrens** [comment]
Hello @Benau , sorry for my late response.


> how about `<card os="android" disable="NpotTextures"/>` only?

Yes, it works properly if we set this property :)

**Comment by antonialoytorrens** [comment]
I've dug more into this a little bit:

```
  <card contains="PowerVR SGX 520" disable="NpotTextures"/>
  <card contains="PowerVR SGX 530" disable="NpotTextures"/>
  <card contains="PowerVR SGX 531" disable="NpotTextures"/>
  <card contains="PowerVR SGX 535" disable="NpotTextures"/>
  <card contains="PowerVR SGX 540" disable="NpotTextures"/>
  <card contains="PowerVR SGX 545" disable="NpotTextures"/>
```

Looks like if we set `card contains=` instead of `card vendor=` also fixes the graphical issues.
