### ISSUE TITLE
Adding player id(uuid/guid) to GameProtocol logs

### ISSUE THREAD

**Issue by yahavb** [supertuxkart/stk-code#4660]
Not an issue just a question. 
I want to add to the  `Log::verbose("GameProtocol"...` prints of any type of the player id (uuid, guid etc). https://github.com/supertuxkart/stk-code/blob/6e17d5180233e9b271e3add6aa806d67845f9c79/src/network/protocols/game_protocol.cpp#L99

Before I start adding prints and try many combinations, is there an easy way to achieve that?

**Comment by yahavb** [comment]
fair enough. I want to look at player actions `a.m_ticks, a.m_kart_id, a.m_action, a.m_value, a.m_value_l,
                a.m_value_r` and train a model that can recommend better game outcome. The issue now is that I have only  `a.m_kart_id` but that changes in every game session. My first work on this was in https://aws.amazon.com/blogs/database/accelerating-your-application-modernization-with-amazon-aurora-machine-learning/ where I showed how to detect bots (network-ai) but that is not a real problem (actually a feature).

**Comment by Benau** [comment]
you don't need to detect bots using machine learning because they send update in fixed interval, human can't do that
