### ISSUE TITLE
Kart stuck in win animation

### ISSUE THREAD

**Issue by Bimi124** [supertuxkart/stk-code#4662]
When playing the map "Vulcan Island" with the kart "Sara the Racer", the kart gets stuck in the middle on the map. A video is attached below.
https://imgur.com/wdPmYjB

**Comment by Benau** [comment]
I see nothing (but xxx crap videos) from imgur.... can you upload it to streamable.com

Or do you mean AI stuck?

Or if you are playing with sara you can just press rescue to unstuck yourself...

**Comment by lokpro** [comment]
https://i.imgur.com/wdPmYjB.mp4

**Comment by Benau** [comment]
this is too minor to be fixed... sorry (fixing it requires using hardcoded hack)

and sara the racer is dead by the way, please update stk to 1.3...

**Comment by Bimi124** [comment]
Im sorry to tell you I'm using v1.4. This also works for other slow karts. Everything required to **solve** this issue is making the karts a little bit faster during the animation. Tux for example is fast enough.

**Comment by Bimi124** [comment]
Sorry for spamming reopen, wifi was slow.

**Comment by Benau** [comment]
there is no sara the racer in 1.3...

tux is fast enough because it's a different kart type, even we can make the "light" kart faster in win animation it can fail in other place too

**Comment by Bimi124** [comment]
Sorry again. I messed everything up and because I was writing on my phone I wasn't even able to check the version. I'm using STK 1.1 which is the current release on apt...
