### ISSUE TITLE
XBOX one S|X controller + xpadneo bluetooth driver - bad button mappings

### ISSUE THREAD

**Issue by Da-Boom** [supertuxkart/stk-code#4665]
## Description

I have a Xbox One S|X controller (USB C and the Share button) connected via bluetooth and the [xpadneo](https://atar-axis.github.io/xpadneo/) driver. I have been testing it with various games, and i noticed that i cannot assign certain buttons and other buttons are mislabeled - 

For instance RB (Right Button) is mislabelled as the Y button, The Y Button is mislabeled as the X button, And the X button does not work at ALL (i have tested in other games and software - such as retroarch, where it works totally fine

I have not checked other button mappings, but i know that the joysticks, triggers and at least the B button is properly labelled

I have also attempted some of the troubleshooting steps on the xpadneo driver website, to no avail

## Steps to reproduce

1. Install xpadneo
2. Get Xbox Controller Connected via bluetooth
3. Launch Supertuxkart
4. try to remap incorrect buttons

## Configuration

STK release version: 1.3 (latest in repo at time of reporting)

STK Source (PPA, distribution package, official binary, etc.): 

Manjaro Repositories

System: 
Linux 5.14.10-1-MANJARO

Graphics card: 
NVIDIA GeForce GTX 1070

CPU: Intel Core I5-4690

Gamepads/keyboards models if related to the issue: 
Xbox One S|X (connected via Bluetooth/[xpadneo](https://atar-axis.github.io/xpadneo/))

## Additional information

stdout.log:
(doesnt really reveal much - i did disconnect the controller once to test)

[stdout.log](https://github.com/supertuxkart/stk-code/files/7475482/stdout.log)

input.xml:

[input.txt](https://github.com/supertuxkart/stk-code/files/7475489/input.txt) -rename to .xml (wouldnt upload otherwise)

**Comment by Benau** [comment]
STK use SDL2 for input... does your other games use SDL2 too?

**Comment by Da-Boom** [comment]
Ahh crap... ok yeah, ive figured it out - Turns out SDL2.0 Uses a new API called `HIDAPI` - i think the version of xpadneo i have is a bit old, and it looks like in order to get it working for SDL2 with this version I have to disable `HIDAPI` using `SDL_JOYSTICK_HIDAPI=0`
