### ISSUE TITLE
SuperTuxKart in VR

### ISSUE THREAD

**Issue by JMcrafter26** [supertuxkart/stk-code#4667]
Hey stk team,
I love your game and  I am playing it a lot. I just had an idea, what about SuperTuxKart in Virtual Reality??? Wouldn't it be great? I hope you can do this, so I can fully enjoy the game. (Maybe you can look around with the vr glasses 🧐) 

Thank you! Have a nice day!

**Comment by Benau** [comment]
This issue tracker is for reporting bugs only....

**Comment by qwertychouskie** [comment]
To clarify, suggestions should be posted on the forum: https://forum.freegamedev.net/viewforum.php?f=16
