### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by dlrudfh** [supertuxkart/stk-code#4668]
It is not an issue, but I can't find a place to ask so I'm leaving my question here.
While playing the game in Korean, I found a few places where the translations were incorrect or not. Since this is my first attempt to contribute to github, I ask if it's okay to fix these parts.

An example of incorrect translations : 
"Press B to look behind.\n"
"Fire the weapon with space while pressing B to fire behind!"
-> "뒤를 돌아보려면 B를 누르세요.\n뒤에서 발사하려면 스페이스를 누르면서 B로 무기를 발사하세요." (X)
"뒤를 돌아보려면 B를 누르세요.\n뒤에서 발사하려면 B를 누르면서 스페이스로 무기를 발사하세요." (O)

Untranslated part : Alien Signal, Ancient Colosseum Labyrinth, etc.

**Comment by Benau** [comment]
you can help translating STK in https://www.transifex.com/signup/?join_project=supertuxkart (use sign-in with github button to avoid creating transifex account)

**Comment by Benau** [comment]
btw you don't need to request language for korean (korea), just translate the korean language in stk, and I assumed you joined the transifex team now (I see "dlrudfh" in transifex korean team)
