### ISSUE TITLE
Can't start on macOS : Gatekeeper stuck...

### ISSUE THREAD

**Issue by Sirix1995** [supertuxkart/stk-code#4669]
## Description
Hi ! I just downloaded SuperTuxKart 1.3 on my MacBook (an Early 2015 model with an i7 and 16 GB of RAM), the 1.2 version was working fine on it. When I started the new version, GateKeeper began it's check...But got stuck, with half of the progress bar filled. I tried several times, restarted the computer, checked if GateKeeper was allowing every developper, and...yes, so...I don't know what to do...

## Steps to reproduce
Simply download the last version on a Mac and try to run it...

## Configuration

STK release version: 
1.3

STK Source (PPA, distribution package, official binary, etc.): 
Official Binary

System: 
macOS Mojave 10.14.6

Graphics card: 
Intel Iris Graphics 6100

CPU: 
Intel Core i7-5557U @3.1 GHz

Gamepads/keyboards models if related to the issue: 
Integrated MacBook keyboard

**Comment by Benau** [comment]
need to see if any more users are having this issue....

**Comment by Sirix1995** [comment]
I see. It still don't work on my machine...I can't start the game...

**Comment by Benau** [comment]
Maybe this wil work https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20211111-mac.zip

**Comment by sky76** [comment]
I have exactly the same problem.
1.2 worked fine.
Installed 1.3 - GateKeeper gets stuck.
Tried setting the rights to 777 - did not help.
Uninstalled everything and the installed 1.3 - did not work.

So 1.3 does not work on macOS.

I have macOS Mojave.
iMac (Retina 5K, 27-inch, 2017)
4,2 GHz Intel Core i7
40 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by Benau** [comment]
1.3 works even on apple M1 devices so I think old (mojave?) macOS doesn't handle arm64 + x86_64 flat binary correctly

Try this one: https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20211125-mac.zip

**Comment by sky76** [comment]
Ok, I've tried SuperTuxKart-git20211122-mac, I will test it after today's session (just don't want to risk anything). ;) I'll post here the results.

**Comment by sky76** [comment]
I've tried https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20211125-mac.zip and the result was the same.

**Comment by Benau** [comment]
then no more idea for now...

**Comment by 70m4** [comment]
Hello, to start it, have a look here --> https://support.apple.com/en-is/guide/mac-help/mchleab3a043/mac
Just Control-click the app icon, then choose Open from the shortcut menu and click open

**Comment by sky76** [comment]
I tried that of course, because you have to do it with many apps. But that
was not the problem. The "endless loop check" comes afterwards.

Am Sa., 27. Nov. 2021 um 21:18 Uhr schrieb 70m4 ***@***.***>:

**Comment by qwertychouskie** [comment]
There were some recent commits to dylibbundler that may help things on newer macOS versions.

**Comment by sky76** [comment]
I used public 1.3 release and this one
https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20211125-mac.zip
on
a different machine running Mojave using "Open" context menu and both tries
weren't successful.

Am Di., 30. Nov. 2021 um 03:19 Uhr schrieb QwertyChouskie <
***@***.***>:

**Comment by Minnietheandroid** [comment]
Same here unfortunately, won't start on my High Sierra Intel macs. It gets about 2/3 through verifying and just stays there.

**Comment by srhinow** [comment]
the same gatekeeper-problem here. I try SuperTuxExtreme 1.3 on iMac 2013 Mojave

**Comment by Benau** [comment]
can you try https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20220117-mac.zip ? this is built natively instead of using cross-compiler

**Comment by srhinow** [comment]
No, this build isn't any better either. The progress bar stays there 
forever.

mit freundlichem Gruß

Sven Rhinow

----------------------------------
sr-tag Sven Rhinow Webentwicklung
----------------------------------
web:www.sr-tag.de
***@***.***

Telefon: 033981 - 50 54 85
Fax:     033981 - 50 54 86
Mobil:   0174 - 77 35 56 2

Am 17.01.22 um 01:32 schrieb Benau:

**Comment by Benau** [comment]
then probably this is unfixable sorry... you need to stick with 1.2 for old macos (< 10.15)

**Comment by Benau** [comment]
One last attempt ![](https://cdn.lihkg.com/assets/faces/mouse/yea.gif), try this https://github.com/Benau/stk-code/releases/download/preview/SuperTuxKart-git20220118-mac.zip (it's a signed archive), after you unzip it should be notarized:
```
spctl --assess --type execute -vvv SuperTuxKart.app
SuperTuxKart.app: accepted
source=Notarized Developer ID
```
Does it work now?

**Comment by sky76** [comment]
Unfortunately No, endless progress bar for at least 10 minutes... :(

**Comment by deveee** [comment]
From what I noticed, XprotectService crashes when verifying hangs. The crash report doesn't seem to be useful though...
[XprotectService_2022-02-03-223918_iMac-ja.crash.txt](https://github.com/supertuxkart/stk-code/files/8001101/XprotectService_2022-02-03-223918_iMac-ja.crash.txt)

**Comment by SeaMac** [comment]
I have the SAME Exact Issue. MacPro5,1 (2012 Pro tower with 12 cores) / System 10.13.6 Can't load STK 1.3 ... just noticed it last week. Where do I get the 1.2 version so I can PLAY this again??

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/releases/tag/1.2

Tbh mojave or older is eol so please update your os....

This issue will be closed after next stk release....

**Comment by Benau** [comment]
Can you try https://github.com/supertuxkart/stk-code/releases/download/appletest-rc1/SuperTuxKart-appletest-rc1-mac.zip ?

**Comment by srhinow** [comment]
yes with this rc-1 work this Game on my Mac OS 10.14.6 fine.

many thanks for your great work.

**Comment by SeaMac** [comment]
> Can you try https://github.com/supertuxkart/stk-code/releases/download/appletest-rc1/SuperTuxKart-appletest-rc1-mac.zip ?

This Fixes It!!!! This version of 1.2 Has the new racers that are in 1.3 ... AND Launches OK on Mac OS X 10.13.6 High Sierra ... Thank you SO Much!

![image](https://user-images.githubusercontent.com/5051781/192075412-2698ef8d-8c5c-4747-9cea-e5917b347d6f.png)

Pepper (Of Pepper and Carrot) is in this one ... and I definitely wanted to play as Her!!!

**Comment by Benau** [comment]
Try the final 1.4 release https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4-mac.zip ?

**Comment by sky76** [comment]
Wow, works great on macOS Mojave. Even starts much faster now (at least my individual experience). Thanks for your effort! :)

**Comment by srhinow** [comment]
yes 1.4 works fine also by my Mojave. Big thanks

**Comment by SeaMac** [comment]
1.4 (This Version) works excellently on High Sierra 10.13.6 and is EVEN MUCH Faster to Launch and Play ... noticeably so! Thank you SO Much for making the latest greatest version accessible to old Mac Tower Owners ... who can't afford Apple's Latest Tower ...
Happy Halloween!
