### ISSUE TITLE
Supertuxkart Blender addons don't work

### ISSUE THREAD

**Issue by LOLKARL** [supertuxkart/stk-code#4670]
I Trie to make my own Kart in Blender, but the SupertTuxKartpanel addon dosn't work.I tried to install it on different Blender versions and downloaded the addon from different sources, but there is always a error message when i try to aktive it in the Preferences

**Comment by Benau** [comment]
Make sure you copy everything including stkdata subfolder

And https://github.com/supertuxkart/stk-blender will for new version of blender

**Comment by LOLKARL** [comment]
Thank's now i could finally export my kart
