### ISSUE TITLE
Online account creation error

### ISSUE THREAD

**Issue by dlrudfh** [supertuxkart/stk-code#4672]
## Description
When I fill in an email to make online account, if you write an email and ends with a dot, an error text does not occur and goes to the next step. Accepting the terms and conditions will result in an incorrect error message.

## Steps to reproduce
email : hello@google.
error message : \&quot;hello@google.\&quot; is not a valid email address.

## Configuration
STK release version: 1.3.0

**Comment by dlrudfh** [comment]
I fixed this issue at code 'register_screen.cpp', and I wonder if I can give you a pull request.

**Comment by Benau** [comment]
sure
