### ISSUE TITLE
Confirmation dialog preferences

### ISSUE THREAD

**Issue by dlrudfh** [supertuxkart/stk-code#4677]
At the end of one race in the Grand Prix, if you select 'Abort Grand Prix' button, a dialog appears. The default selection of this dialog is set to 'Yes', pressing the select button immediately stops the Grand Prix. It's probably better to set the default selection to 'Cancel', since the dialog is just one more check in case the user accidentally hits the abort button.
I have attached a picture of my intentions.
![Inked123_LI](https://user-images.githubusercontent.com/80889873/142986560-728e04c9-1382-45f4-ab9f-2fb0aea3ab18.jpg)

**Comment by Benau** [comment]
maybe
