### ISSUE TITLE
Feature request: configurable internal resolution on Android

### ISSUE THREAD

**Issue by clavinet** [supertuxkart/stk-code#4682]
To save SoC load and prolong battery life, there could be a feature on STK Android to lower the internal resolution of the game.

Alternatively, a lower internal resolution could be used to render better looking graphics at the same framerate.

**Comment by qwertychouskie** [comment]
Check "Render resolution" in settings.  It's used by default in STK 1.3+

**Comment by clavinet** [comment]
You're right. I didn't find it at first because it's a percentage slider, and on the bottom you have just one output resolution so I assumed it's not configurable.
