### ISSUE TITLE
Graphics Fail to Load on Asus Eee Pad Transformer TF101 (asus-tf101)

### ISSUE THREAD

**Issue by antonialoytorrens** [supertuxkart/stk-code#4683]
## Description

Broken textures while playing the game.
The startup screen does not even load.

## Configuration

STK release version: 1.3

System: KatKiss (based on Android 6.0).

STK Source (PPA, distribution package, official binary, etc.): F-Droid package

Graphics card: NVIDIA Corporation, NVIDIA Tegra (ULP GeForce)

CPU: Nvidia Tegra 2 T20

Gamepads/keyboards models if related to the issue: -

## Additional information

adb logcat:
[supertuxkart-adb-logcat-asus-tf101.txt.zip](https://github.com/supertuxkart/stk-code/files/7614521/supertuxkart-adb-logcat-asus-tf101.txt.zip)

**Comment by antonialoytorrens** [comment]
Follow-up: Seems like an npot texture issue.
I've added `<card contains="NVIDIA Tegra" os="android"   disable="NpotTextures"/>` in `graphical_restrictions.xml` and I get sound working now.

However, the display panel looks like this:
![imatge](https://user-images.githubusercontent.com/47571676/143789205-242b5f11-bfa6-48ab-a769-1dda77954f3c.png)
I can hear in-game sound but no display.
[supertuxkart-adb-logcat_2-asus-tf101.txt.zip](https://github.com/supertuxkart/stk-code/files/7614554/supertuxkart-adb-logcat_2-asus-tf101.txt.zip)

Line 102 might be the cause of the issue:
```
11-28 22:40:58.603  3925  3942 V Irrlicht: Could not initialize display!
11-28 22:40:58.603  3925  3942 I SuperTuxKart: [info   ] [IrrDriver Logger]: Could not initialize display!
11-28 22:40:58.607  3925  3944 W art     : Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[12,tid=3944,Native,Thread*=0x43d06750,peer=0x12c8e100,"Thread-227"]
```

**Comment by Benau** [comment]
no they are just "fallback", I see
```
11-28 22:40:58.758  3925  3942 I SuperTuxKart: [info   ] [IrrDriver Logger]: GL_EXT_debug_marker GL_NV_platform_binary GL_OES_rgb8_rgba8 GL_OES_EGL_sync GL_OES_fbo_render_mipmap GL_NV_depth_nonlinear GL_NV_draw_path GL_NV_texture_npot_2D_mipmap GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_vertex_half_float GL_OES_mapbuffer GL_NV_draw_buffers GL_NV_multiview_draw_buffers GL_EXT_Cg_shader GL_EXT_packed_float GL_OES_texture_half_float GL_OES_texture_float GL_EXT_texture_array GL_OES_compressed_ETC1_RGB8_texture GL_EXT_texture_compression_latc GL_NV_texture_compression_latc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_NV_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_NV_get_tex_image GL_NV_read_buffer GL_NV_shader_framebuffer_fetch GL_NV_fbo_color_attachments GL_EXT_bgra GL_EXT_texture_format_BGRA8888 GL_EXT_unpack_subimage GL_NV_pack_subimage GL_NV_texture_compression_s3tc_update GL_NV_read_depth GL_NV_read_stencil GL_EXT_robustness GL_OES_standard_derivatives GL_NV_EGL_stream_consumer_external GL_NV_coverage_sample
11-28 22:40:58.770  3925  3942 I SuperTuxKart: [info   ] IrrDriver: OpenGL version: 2.1
11-28 22:40:58.771  3925  3942 I SuperTuxKart: [info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
11-28 22:40:58.771  3925  3942 I SuperTuxKart: [info   ] IrrDriver: OpenGL renderer: NVIDIA Tegra
11-28 22:40:58.771  3925  3942 I SuperTuxKart: [info   ] IrrDriver: OpenGL version string: OpenGL ES 2.0 14.01002
11-28 22:40:58.776  3925  3942 W SuperTuxKart: [warn   ] irr_driver: Using the fixed pipeline (old GPU, or shaders disabled in options)
```
later

Unfortuately if it doesn't work even with the most "compact" driver then I don't think we can do anything about it....

**Comment by Benau** [comment]
"compact" driver == the one bought you by irrlicht (which uses only GLES2 api)

**Comment by antonialoytorrens** [comment]
I see. It's expectable that it's not working on a very old device by the way.
However, I think putting `<card contains="NVIDIA Tegra" os="android" disable="NpotTextures"/>` can benefit other Tegra devices if they are capable of running the game. Most probably they will have the same `NpotTextures` error. What do you think?

**Comment by Benau** [comment]
I think only (very!) old nvidia tegra is affected...
