### ISSUE TITLE
Basketball is overpowered

### ISSUE THREAD

**Issue by dontfwiththestream** [supertuxkart/stk-code#4684]
Basketball is overpowered. A player can be far ahead and the basketball can entirely remove any lead, therefore removing skill from the equation. This pickup needs to be nerfed badly, or an option to disable it

## Steps to reproduce

Play the game

## Configuration

STK release version: 

Current/all

STK Source (PPA, distribution package, official binary, etc.): 

System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by CrystalDaEevee** [comment]
Basketballs may seem op but they're basically the equivalent to a blue shell, and just the blue shell, there are ways to avoid it
You can use basic methods like using bubblegum shield or reseting just before the hit (if the lead is safe or just on top of a zipper)
You can also try the alternative method of shooting at the basketball with items such as bowling balls, cakes or plungers.
In some cases you can go wide of the driveline and completly avoid it without it locking on onto you, or the basketball will hit something in the way or explode in a gap.

**Comment by kimden** [comment]
Basketball removes at most 2-3 seconds if the leader isn't prepared, for which there is usually plenty of time (to pick a bubblegum or any other item), so at least "removes any lead" isn't really true

One can escape it most of the time with enough skill and nitro. A few more basketballs running at the same time could indeed destroy your lead, but that's rather a question of balance, which should be first statistically investigated based on games I guess

Players usually say parachutes or swatters are overpowered, but this is an opinion too, so thanks I guess

**Comment by dontfwiththestream** [comment]
So then the concept of it being a kids game, or having a novice level is absurd then if advanced techniques (and luck) are required to play the game. 


As it stands the balance is horrible, as a novice level AI with a basketball can destroy all the progress that is made. Is this a game of skill or chance?

**Comment by dontfwiththestream** [comment]
Ok, how is it not a kids game with cartoonish graphics and effectively being a clone of other kids kart games? I guess I am wasting my time with this package looking for something for the whole family to play

**Comment by CrystalDaEevee** [comment]
You don't necessarily need advanced skills to avoid it, bubblegum is already a good a way to block a hit from it in all difficulties. Honestly what are you expecting from a "seek the leader" powerup, plus it's not even a common powerup. If it was then I guess we'd all see thru your issue.

**Comment by dontfwiththestream** [comment]
So, random chance ("just use the bubblegum!") and a poorly designed pickup ("what are you expecting from a 'seek the leader' pickup") means that the lack of enjoyment my family gets with this is our fault for simply not investing more time into a poorly designed game? Your answers to my complaint about the bb being overpowered (especially in a skill level marked "novice" have been essentially either stop being a novice or have better luck with the pickups. Both of which are not applicable if you are a novice

**Comment by CrystalDaEevee** [comment]
If this helps your case, you can actually disable basketballs.
If you go to the game's data folder and find the file "powerup.xml", you can edit it with, for example, Notepad, and manually set the chance values of the basketball in all the settings to 0.

**Comment by dontfwiththestream** [comment]
Yes it does. Thank you.
