### ISSUE TITLE
build warning occurs

### ISSUE THREAD

**Issue by rlawogns** [supertuxkart/stk-code#4690]
## Description
many warnings occur during build.
![image](https://user-images.githubusercontent.com/33611425/145024648-e5247838-f36c-4a67-bb64-d220093d6b2c.png)

Can I fix the code to reduce the warning?

**Comment by Benau** [comment]
They are harmless warnings so better do something more useful![](https://cdn.lihkg.com/assets/faces/pigxm/bye.gif)
