### ISSUE TITLE
Pasting a string on Wayland with Ctrl+V adds extra ``v`` to the end of the string

### ISSUE THREAD

**Issue by akhilman** [supertuxkart/stk-code#4694]
## Description
Can not login to my account from within a game. It was working but suddenly stopped. I changed my password and can log in to online.supertuxkart.net from the web browser, but the game shows error "Username or password incorrect" when I type exactly same credentials.

## Steps to reproduce

1. Run a game;
2. Go to online -> login;
3. Type credentials;
4. Get an error.

## Configuration

STK release version: 1.3

STK Source: https://flathub.org/apps/details/net.supertuxkart.SuperTuxKart 

System: 5.10.83-1-MANJARO x86_6 with GNOME 41.1

Graphics card: AMD Picasso (Vega 11)

CPU: Quad Core AMD Ryzen 5 PRO 3400G with Radeon Vega Graphics

## Additional information

stdout.log:
```
[info   ] HTTPRequest: Sending username=akhilman&password=*****************&save-session=true to https://online.supertuxkart.net/api/v2/user/connect/
```
[stdout.log](https://github.com/supertuxkart/stk-code/files/7703378/stdout.log)

Error message:
```
Username or password is invalid
```
![Screenshot from 2021-12-13 18-35-58](https://user-images.githubusercontent.com/180812/145805972-1bc6c98a-db2c-45a8-bd52-f3792178d549.png)

**Comment by Benau** [comment]
No idea  how it can happen... try reset the password one more time...

Do you use non-ascii characters in password?

**Comment by akhilman** [comment]
Great. After one more password reset it fixed by itself.

**Comment by akhilman** [comment]
Tested one more time.
If I type my password manually all works fine.
If I use Ctrl+C and Ctrl+V with same password on XOrg - it works.
If I use Ctrl+C and Ctrl+V with same password on Wayland - it fails.

Seems there is some problem with clipboard on SDL/Wayland.

**Comment by akhilman** [comment]
I get ``a wordv`` in the filed when I copy ``a word`` and paste it to a field in game on wayland.

**Comment by Benau** [comment]
This belong to sdl2 issue tracker probably...

**Comment by akhilman** [comment]
Ok. Closing for now.
