### ISSUE TITLE
Crash while trying to sign out after the login screen

### ISSUE THREAD

**Issue by Arthur-D** [supertuxkart/stk-code#47]
Some of the output before and backtrace:

>[error  ] OnlineScreen: Could not get the server list.
[info   ] ConnectToServer: Trying to connect to 3166765477:56598
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] ConnectToServer: Trying to connect to 3166765477:56598
[LayoutManager] WARNING: statically sized widgets took all the place!!
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] HTTPRequest: Sending action=poll&token=e85033cc74df6861094b764a&userid=6 to https://api.stkaddons.net/client-user.php
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] ConnectToServer: Trying to connect to 3166765477:56598
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] ConnectToServer: Trying to connect to 3166765477:56598
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] HTTPRequest: Sending action=poll&token=e85033cc74df6861094b764a&userid=6 to https://api.stkaddons.net/client-user.php
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[info   ] ConnectToServer: Trying to connect to 3166765477:56598
[debug  ] STKHost: Raw packet sent to 188.193.1.165:56598
[info   ] PingProtocol: Ping message sent
[debug  ] NetworkManager: EVENT received of type 1
[debug  ] ProtocolManager: Received event for protocols of type 0
*** glibc detected *** cmake_build/bin/supertuxkart: double free or corruption (fasttop): 0x00007f0748000910 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7f0779591b96]
cmake_build/bin/supertuxkart(_ZN15ProtocolManager14propagateEventEP19EventProcessingInfob+0x184)[0x965440]
cmake_build/bin/supertuxkart(_ZN15ProtocolManager18asynchronousUpdateEv+0x89)[0x965755]
cmake_build/bin/supertuxkart(_Z33protocolManagerAsynchronousUpdatePv+0x38)[0x963f75]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7f077b441e9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f07796073fd]
======= Memory map: ========
00400000-01222000 r-xp 00000000 08:1a 2135463                            /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart
01422000-01423000 r--p 00e22000 08:1a 2135463                            /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart
01423000-01427000 rw-p 00e23000 08:1a 2135463                            /home/magne/SuperTuxKart/supertuxkart-git/stk-code/cmake_build/bin/supertuxkart
01427000-01444000 rw-p 00000000 00:00 0 
02da8000-33dbd000 rw-p 00000000 00:00 0                                  [heap]
4110d000-411ab000 rw-p 00000000 00:00 0 
41e6c000-41e6e000 r-xs 00000000 00:11 45102445                           /tmp/glTvLbeP (deleted)
7f0744000000-7f0744021000 rw-p 00000000 00:00 0 
7f0744021000-7f0748000000 ---p 00000000 00:00 0 
7f0748000000-7f0748021000 rw-p 00000000 00:00 0 
7f0748021000-7f074c000000 ---p 00000000 00:00 0 
7f074c000000-7f074c021000 rw-p 00000000 00:00 0 
7f074c021000-7f0750000000 ---p 00000000 00:00 0 
7f0753fff000-7f0758000000 rw-s 00000000 00:13 45102458                   /run/shm/pulse-shm-1451875571
7f0758000000-7f0758040000 rw-p 00000000 00:00 0 
7f0758040000-7f075c000000 ---p 00000000 00:00 0 
7f075e3fd000-7f075e3fe000 ---p 00000000 00:00 0 
7f075e3fe000-7f075ebfe000 rw-p 00000000 00:00 0 
7f075ebfe000-7f075ebff000 ---p 00000000 00:00 0 
7f075ebff000-7f075f3ff000 rw-p 00000000 00:00 0 
7f075f7ff000-7f075f800000 ---p 00000000 00:00 0 
7f075f800000-7f0760000000 rw-p 00000000 00:00 0 
7f0760000000-7f0760131000 rw-p 00000000 00:00 0 
7f0760131000-7f0764000000 ---p 00000000 00:00 0 
7f0764291000-7f0764298000 r-xp 00000000 08:05 1566232                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f0764298000-7f0764497000 ---p 00007000 08:05 1566232                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f0764497000-7f0764498000 r--p 00006000 08:05 1566232                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f0764498000-7f0764499000 rw-p 00007000 08:05 1566232                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f0764499000-7f076449b000 r-xp 00000000 08:05 1441849                    /lib/libnss_mdns4_minimal.so.2
7f076449b000-7f076469a000 ---p 00002000 08:05 1441849                    /lib/libnss_mdns4_minimal.so.2
7f076469a000-7f076469b000 r--p 00001000 08:05 1441849                    /lib/libnss_mdns4_minimal.so.2
7f076469b000-7f076469c000 rw-p 00002000 08:05 1441849                    /lib/libnss_mdns4_minimal.so.2
7f076469c000-7f07646a8000 r-xp 00000000 08:05 1566230                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f07646a8000-7f07648a7000 ---p 0000c000 08:05 1566230                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f07648a7000-7f07648a8000 r--p 0000b000 08:05 1566230                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f07648a8000-7f07648a9000 rw-p 0000c000 08:05 1566230                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f07648a9000-7f07648aa000 ---p 00000000 00:00 0 
7f07648aa000-7f07650aa000 rw-p 00000000 00:00 0 
7f07650aa000-7f076535d000 r-xp 00000000 08:05 794730                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f076535d000-7f076555c000 ---p 002b3000 08:05 794730                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f076555c000-7f0765578000 r--p 002b2000 08:05 794730                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f0765578000-7f0765579000 rw-p 002ce000 08:05 794730                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f0765579000-7f07655c1000 r-xp 00000000 08:05 794189                     /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f07655c1000-7f07657c1000 ---p 00048000 08:05 794189                     /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f07657c1000-7f07657c2000 r--p 00048000 08:05 794189                     /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f07657c2000-7f07657c3000 rw-p 00049000 08:05 794189                     /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f07657c3000-7f07657da000 r-xp 00000000 08:05 1566246                    /lib/x86_64-linux-gnu/libnsl-2.15.so
7f07657da000-7f07659d9000 ---p 00017000 08:05 1566246                    /lib/x86_64-linux-gnu/libnsl-2.15.so
7f07659d9000-7f07659da000 r--p 00016000 08:05 1566246                    /lib/x86_64-linux-gnu/libnsl-2.15.so
7f07659da000-7f07659db000 rw-p 00017000 08:05 1566246                    /lib/x86_64-linux-gnu/libnsl-2.15.so
7f07659db000-7f07659dd000 rw-p 00000000 00:00 0 
7f07659dd000-7f07659e2000 r-xp 00000000 08:05 794265                     /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f07659e2000-7f0765be1000 ---p 00005000 08:05 794265                     /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f0765be1000-7f0765be2000 r--p 00004000 08:05 794265                     /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f0765be2000-7f0765be3000 rw-p 00005000 08:05 794265                     /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f0765be3000-7f0765c43000 r-xp 00000000 08:05 794668                     /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f0765c43000-7f0765e43000 ---p 00060000 08:05 794668                     /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f0765e43000-7f0765e45000 r--p 00060000 08:05 794668                     /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f0765e45000-7f0765e46000 rw-p 00062000 08:05 794668                     /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f0765e46000-7f0765e4a000 rw-p 00000000 00:00 0 
7f0765e4a000-7f0765e52000 r-xp 00000000 08:05 1445841                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f0765e52000-7f0766051000 ---p 00008000 08:05 1445841                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f0766051000-7f0766052000 r--p 00007000 08:05 1445841                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f0766052000-7f0766053000 rw-p 00008000 08:05 1445841                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f0766053000-7f0766095000 r-xp 00000000 08:05 1442761                    /lib/x86_64-linux-gnu/libdbus-1.so.3.5.8
7f0766095000-7f0766295000 ---p 00042000 08:05 1442761                    /lib/x86_64-linux-gnu/libdbus-1.so.3.5.8
7f0766295000-7f0766296000 r--p 00042000 08:05 1442761                    /lib/x86_64-linux-gnu/libdbus-1.so.3.5.8
7f0766296000-7f0766297000 rw-p 00043000 08:05 1442761                    /lib/x86_64-linux-gnu/libdbus-1.so.3.5.8Avbrutt (SIGABRT) (core dumped)

**Comment by Benau** [comment]
@Arthur-D can you try again in latest git?

**Comment by Arthur-D** [comment]
I do not seem to be able to reproduce this issue; closing.
