### ISSUE TITLE
Use Weblate for translations

### ISSUE THREAD

**Issue by comradekingu** [supertuxkart/stk-code#4702]
I did contribute [on Transifex](https://github.com/supertuxkart/stk-code/blob/fd7564d5080f3bd1e7b30c0a1921c19b395171a3/data/po/nb.po#L6) and [on Launchpad](https://github.com/supertuxkart/stk-code/blob/fd7564d5080f3bd1e7b30c0a1921c19b395171a3/data/po/nb.po#L4079)

I never accepted the updated Transifex terms for EU-GDPR, and the translation has since fallen behind.
Be that as it may, the main issue I am having is with libre software using and strings entering the closed Transifex TM.

Weblate is libre software and a much better tool.
The ability to see multiple languages at once and navigate between strings makes it much easier to use.

https://github.com/supertuxkart/stk-code/issues/4274 and https://github.com/supertuxkart/stk-code/issues/3087 are relevant

Edit: I can help with setup, either https://hosted.weblate.org/hosting/ or self-hosting.
https://hosted.weblate.org/projects/super-tux-party/ is already on Hosted Weblate :)

**Comment by Benau** [comment]
Sorry, atm https://github.com/supertuxkart/stk-website is done on transifex too and as far as I know weblate doesn't support .md file

Using transifex for both stk-code and stk-website allows same group of people doing similar thing

**Comment by Cwpute** [comment]
@Benau I'm kindly asking you reconsider this option and reopen this issue as Markdown file editing was made possible in Weblate 5.0 :)
See https://docs.weblate.org/en/weblate-5.3.1/formats/markdown.html
