### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by RandomPandaStudios** [supertuxkart/stk-code#4704]
Hi. I have a rather difficult problem with a SuperTuxKart that I downloaded a few years back.

Originally, I had downloaded SuperTuxKart 0.8.2 Portable from: https://portableapps.com
and everything worked fine, at least until I migrated most of my content from one computer to another, then it started to reject startups.

# Problem:
I don't know how this happened, whether I unintentionally deleted it or it got lost in the migration, but my SuperTuxKart Portable 0.8.2 is missing its data/shaders directory, and I can't seem to find a download for it... Even on Github, which is strange to me.

If I create a blank folder named "shaders" in the "data" folder, the app will start, but its completely blank, as all of the shaders are none existent basically...

Any solutions would be much appreciated, and apologies if my post does not below here, I searched and couldn't find a official contact-help method on the website.

**Comment by Benau** [comment]
Use latest release https://github.com/supertuxkart/stk-code/releases/tag/1.3 please, it has an installer-less archive too (which is very portable) ![](https://cdn.lihkg.com/assets/faces/mousexm/miracle_special.gif)

**Comment by lokpro** [comment]
In case you insist to try the 0.8.2. 
I found out https://github.com/supertuxkart/stk-code/tree/v0.8.1/data for you.
