### ISSUE TITLE
Accelerometer overrides gamepad steering input

### ISSUE THREAD

**Issue by DominikNovosel** [supertuxkart/stk-code#4705]
## Description

If the accelerometer or gyroscope is enabled in Controls/Touch Device, steering input from the gamepad is ignored.
Issue is resolved upon disabling either the input methods or the touch device itself, but this is moderately inconvenient.
## Steps to reproduce

1. Connect gamepad to device and run STK (the order in which this part is done doesn't appear to make a difference)
2. Make sure the accelerometer or gyroscope is enabled in Controls/Touch Device, and that Touch Device is enabled.
3. Start a race or tutorial and attempt to steer using the gamepad.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): Google Play Store

System: Android 11

Device: Xiaomi Redmi Note 8 Pro

Gamepads/keyboards models if related to the issue: Xbox Wireless Controller (second revision)

## Additional information
**requested info is inaccessible on Android**

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by DominikNovosel** [comment]
Thanks! Any idea when the next release will be out? If it won't be soon, how can I compile STK for Android? INSTALL.md is missing instructions for that.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20220104.apk ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

https://github.com/supertuxkart/stk-code/blob/master/android/README.ANDROID ![](https://cdn.lihkg.com/assets/faces/pig/dance2.gif)

https://github.com/supertuxkart/stk-code/blob/d4ed01b46721ac87dd6781c8ee8c32cbefe52c66/src/states_screens/race_gui_multitouch.cpp#L115 ![](https://cdn.lihkg.com/assets/faces/pig/dance3.gif)

**Comment by DominikNovosel** [comment]
Thanks! What's with all the piglets? 😆

**Comment by Benau** [comment]
https://linuxreviews.org/Hong_Kong_Pig
