### ISSUE TITLE
Problems to get connection to supertuxkart server

### ISSUE THREAD

**Issue by shoemac** [supertuxkart/stk-code#4708]
## Description

Supertuxkart on my PC shows the following message in the bottom line: "SSL peer certificate or SSL remote key was not OK". It works fine for over one year. But now I get this message. I cannot download new karts, tracks etc.

## Steps to reproduce

I had a look at my firewall but it is turned off by default.

## Configuration

STK release version: 
1.1

STK Source (PPA, distribution package, official binary, etc.): 
distribution package (Linux Mint 20.2 / Ubuntu 20.04)
System: 
PC
Graphics card: 
AMD Radeon RX 550
CPU: 
AMD Ryzen R6 2600
Gamepads/keyboards models if related to the issue: 
sharkoon keyboard
## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```
SSL peer certificate or SSL remote key was not OK
```

**Comment by Benau** [comment]
Please update stk to 1.3 thank you, see https://github.com/supertuxkart/stk-code/issues/4635
