### ISSUE TITLE
Save data gets wiped when running out of disk space

### ISSUE THREAD

**Issue by hyarsan** [supertuxkart/stk-code#4709]
## Description

When running low on disk space, SuperTuxKart wipes its save data because it fails to save it properly. This has happened a few times to me, and it's very annoying that my story mode save is gone.

## Steps to reproduce

Back up SuperTuxKart's save data to somewhere safe, make sure you have 0 bytes remaining on the drive where SuperTuxKart is installed, launch it, and exit it.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): distribution package

System: Manjaro Linux

**Comment by qwertychouskie** [comment]
I've also run into this multiple times in the past.

**Comment by Benau** [comment]
in [de09566](https://github.com/supertuxkart/stk-code/commit/de09566b4a74de06a4cdf230538ed59d0ec2a465) ![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) even handles all configs xml currently used so it should no longer an issue ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)
