### ISSUE TITLE
Segmentation fault on some maps in multiplayer 

### ISSUE THREAD

**Issue by rodin-ia** [supertuxkart/stk-code#4710]
## Description
Hi, catching the "Segmentation fault" error on three standard maps (Ravenbridge Mansion, Nessie's Pond, Cocoa Temple) in LAN mode.
The error occurs after the card has loaded and the start time starts counting.

## Steps to reproduce

1. Start STK server with supertuxkart parameters --server-config = server_conf.xml --lan-server = raspberry --network-console
2. Connect to the server from any two clients, I tried
Ubuntu 21.10 (x64) / Ubuntu 20.04 (x64) / Android 11
3. Choose one of the three tracks (Ravenbridge Mansion, Nessie's Pond, Cocoa Temple), any car.
4. The error occurs after the card is loaded and the start time starts counting. 

## Configuration

Network server
STK release version: 1.3 (armv7) github
STK server launched on raspberry without GUI.
Raspbian GNU / Linux 10 (buster)
Linux raspberry 5.10.63-v7l + # 1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU / Linux

STK Cleint
STK release version: 1.3 (x64)/ 1.1 (x64) / 1.3 (Android 11)

STK Source (PPA, distribution package, official binary, etc.): 
github / default ubuntu ppa / f-Droid

coredump for each card in the attachment 

[server_conf.log](https://github.com/supertuxkart/stk-code/files/7834078/server_conf.log)
[server_conf.xml.txt](https://github.com/supertuxkart/stk-code/files/7834083/server_conf.xml.txt)
[Cocoa Temple.txt](https://github.com/supertuxkart/stk-code/files/7834074/Cocoa.Temple.txt)
[Nessie's Pond.txt](https://github.com/supertuxkart/stk-code/files/7834075/Nessie.s.Pond.txt)
[Ravenbridge Mansion.txt](https://github.com/supertuxkart/stk-code/files/7834076/Ravenbridge.Mansion.txt)

**Comment by Benau** [comment]
recompile stk-code with cmake .. -DAS_MAX_PORTABILITY, this seems to affect specific rpi only ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by Benau** [comment]
Or use [this](https://github.com/supertuxkart/stk-code/files/7834470/stk.zip) executable and see if it works on your pi ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif)

**Comment by rodin-ia** [comment]
Thanks, with the new binaries on all maps, the network game works great!
