### ISSUE TITLE
Publish on Steam

### ISSUE THREAD

**Issue by jesperjackson** [supertuxkart/stk-code#4716]
**Have you considered publishing on Steam?**

I think you should, it would bring both exposure as well as distribution and installation infrastructure. You will also get the option to allow cloud play, enabling users to play everywhere on their phone, set-top-box, etc with for example GeForce Now. Also with the Steam Deck launching this would be a great opportunity to get new and non tech savvy people to play your game.

The fee is $100. If you need help with the fee I could donate some and also help by asking if others would like to donate. You can set the game as Early Access if you don’t feel it’s fully complete, that’s what [SuperTux](https://store.steampowered.com/app/1572920/SuperTux/) did when they just recently released on Steam.

As for publishing on Steam you can use [SteamShim](https://github.com/icculus/steamshim) by icculus to interact with the Steam SDK, It even works for GPL projects. Using the Steam Runtime Soldier is the recommended way of distributing on Steam, it works on all distributions that Steam runs on, it works with Steam's Flatpak version and it works with distributions with immutable file systems, such as Fedora Silverblue and SteamOS.

**Comment by Benau** [comment]
not a priority at the moment sorry
