### ISSUE TITLE
Checking health of the UDP endpoint

### ISSUE THREAD

**Issue by yahavb** [supertuxkart/stk-code#4717]
## Description
I want to run stk game server behind network-load-balancer https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html and need to provide health indication. I am currently checking in the container if the listening port is in listen mode e.g., `netstat -anp | grep 8081` but want to have something more accurate. I tried to simply

```
#!/usr/bin/python3

import socket

with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:

    message = b'hello'
    addr = ("54.213.133.167", 8081)

    s.sendto(message, addr)

    data, address = s.recvfrom(0)
    print(data.decode())
```

and saw the request arriving in the server side

``` 
root@stkarm-59ffd8f8f7-m9ls7:/# tcpdump udp port 8081 -vv -X
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
05:12:36.074025 IP (tos 0x20, ttl 28, id 55526, offset 0, flags [none], proto UDP (17), length 33)
    24-104-73-24-ip-static.hfc.comcastbusiness.net.14002 > stkarm-59ffd8f8f7-m9ls7.8081: [udp sum ok] UDP, length 5
	0x0000:  4520 0021 d8e6 0000 1c11 9990 1868 4918  E..!.........hI.
	0x0010:  c0a8 0a0d 36b2 1f91 000d 3989 6865 6c6c  ....6.....9.hell
	0x0020:  6f 
```
but no response to the client. 

I tried to use `nc` but here is get something I am not sure is reliable. When sending to the listening port I get `[udp/sunproxyadmin] succeeded!` but I also get other `[udp/*] succeeded!` for ports that are not listening. 
I see `sunproxyadmin` configured in my Mac so I don't think it is stk server related. 
```
[stk]$nc -z -v -u  54.213.133.167 8081
Connection to 54.213.133.167 port 8081 [udp/sunproxyadmin] succeeded!
[stk]$nc -z -v -u  54.213.133.167 8080
Connection to 54.213.133.167 port 8080 [udp/http-alt] succeeded!
[stk]$nc -z -v -u  54.213.133.167 8080
Connection to 54.213.133.167 port 8080 [udp/http-alt] succeeded!
[stk]$nc -z -v -u  54.213.133.167 8081
Connection to 54.213.133.167 port 8081 [udp/sunproxyadmin] succeeded!
[stk]$nc -z -v -u  54.213.133.167 8032
Connection to 54.213.133.167 port 8032 [udp/pro-ed] succeeded!
[stk]$nc -z -v -u  54.213.133.167 1234
Connection to 54.213.133.167 port 1234 [udp/search-agent] succeeded!
[stk]$nc -z -v -u  54.213.133.167 7894
Connection to 54.213.133.167 port 7894 [udp/*] succeeded!
[stk]$nc -z -v -u  54.213.133.167 8081
Connection to 54.213.133.167 port 8081 [udp/sunproxyadmin] succeeded!
```

I can live with netstat but wanted to see if you know of a simple way to achieve that.

**Comment by Benau** [comment]
Maybe you can code a simple C enet progam to enet_host_connect the address (or https://pypi.org/project/pyenet/)

**Comment by yahavb** [comment]
thanks - will do.
