### ISSUE TITLE
Wrongly says invalid email

### ISSUE THREAD

**Issue by B0pol** [supertuxkart/stk-code#4718]
## Description

I was trying to create an account in game and it says invalid email when actually my email is valid. The format of my email is accountname@e.email

## Steps to reproduce

Try to create an account with an @e.email account.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): f-droid

System: Android

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Fixed with 3d4cb58 ![](https://cdn.lihkg.com/assets/faces/tiger/lihkg2.gif)
