### ISSUE TITLE
[Suggestion] Bubble Gum in soccer mode

### ISSUE THREAD

**Issue by GladiosAnimations** [supertuxkart/stk-code#4734]
## Description
hey, i was wondering. why we cant get bubble gum in soccer mode?
i mean it can be kinda annoying but hey, it should have a role in soccer!
------------------------------------------------------
sorry if i did something wrong. im trying my best!

**Comment by GladiosAnimations** [comment]
okay i did something with the size.. sorry

**Comment by Benau** [comment]
You can adjust stk_config.xml to fit your needs, we won't change the powerup setting for now.

**Comment by lokpro** [comment]
I can't find this option in stk_config.xml.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/blob/master/data/powerup.xml sorry

**Comment by lokpro** [comment]
good
