### ISSUE TITLE
[MSVC][std:c++latest] stk-code failed to build with /std:c++latest on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [supertuxkart/stk-code#4735]
Hi All,

The MSVC team recently added stk-code as part of RWC testing. And we found some errors when building stk-code with '/std:c++latest'. We added `/D_HAS_AUTO_PTR_ETC=1 /D_HAS_STREAM_INSERTION_OPERATORS_DELETED_IN_CXX20` as workaround since they have been deprecated. Could you please help look at this issue? Thanks in advance.

**Repro steps:**
1. git clone https://github.com/supertuxkart/stk-code F:\gitP\supertuxkart\stk-code
2. cd F:\gitP\supertuxkart\stk-code
3. set PATH=F:\tools\build2\bin;%PATH%
4. set PATH=F:\tools\7-Zip;%PATH%
5. curl https://github.com/supertuxkart/dependencies/releases/download/1.3/dependencies-win-x86_64.zip -O -L
6. 7z x dependencies-win-x86_64.zip -oF:\gitP\supertuxkart\stk-code -aoa
7. set _CL_= /std:c++latest
8. mkdir F:\gitP\supertuxkart\stk-code\build_amd64
9. cd F:\gitP\supertuxkart\stk-code\build_amd64
10. msbuild /m /p:Platform=x64 /p:Configuration=Release SuperTuxKart.sln /t:Rebuild

**Build log:**[build.log](https://github.com/supertuxkart/stk-code/files/8105766/build.log)

**Error info:**
F:\gitP\supertuxkart\stk-code\src\tracks/track.hpp(547,1): error C3861: 'random_shuffle': identifier not found 
F:\gitP\supertuxkart\stk-code\src\utils\string_utils.cpp(835,63): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char32_t)': attempting to reference a deleted function
F:\gitP\supertuxkart\stk-code\src\utils\string_utils.cpp(835,63): error C2088: '<<': illegal for class [

**Comment by Benau** [comment]
try something like
[std::random_device](http://en.cppreference.com/w/cpp/numeric/random/random_device) rd;
[std::mt19937](http://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine) g(rd());
std::shuffle(m_start_transforms.begin(), m_start_transforms.end(), g);

try something like
output << U"&#x" << std::hex << std::uppercase << utf32[i] << ";";

**Comment by Benau** [comment]
the `attempting to reference a deleted function` for ostream should be fixed, and I don't think `random_shuffle` worth fixing (it's c++20 problems and we have no intention to use it for now) ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

And `random_shuffle` works in g++ when using std=c++20 btw ![](https://cdn.lihkg.com/assets/faces/pig/whip.gif)
