### ISSUE TITLE
Cannot join server I create

### ISSUE THREAD

**Issue by Noexpert** [supertuxkart/stk-code#4744]
I'm using v 1.3 on three devices in the **same** location / LAN:

- Win 10 PC
- Win 10 laptopn
- Android 10

All three can create a server private, however none can actually join a server created on the other devices.
It just waits for a while and then the message appears "Cannot connect to server XXX".

Same issue with local networking.
None of the devices can see the server created by the other devices.

Note: all devices can join other online servers, but they cannot join servers that we create.

**Comment by Benau** [comment]
Make sure your network doesn't block port 2757 and 2759

**Comment by Noexpert** [comment]
OK thanks that worked.

But I only needed to do that on one PC.

On the other machine (remote), I did not have to open any ports.
Could that be because it's using NAT penetration, as described [here](https://github.com/supertuxkart/stk-code/blob/master/NETWORKING.md)?

> At the moment STK has a list of STUN servers for NAT penetration which allows players or servers behind a firewall or router to be able to connect to each other, but in case it doesn't work, you have to manually disable the firewall or port forward the port(s) used by STK.

**Comment by Benau** [comment]
Maybe
