### ISSUE TITLE
Use AI in GP

### ISSUE THREAD

**Issue by ShuffleWire** [supertuxkart/stk-code#4745]
Hello,

## Description
I want to be able to race GP on a server with IA karts with my friends. It's could seems a bit silly to do want to do so, but the IA is about as strong as us, and having them make the game much more fun !
It's (kinda) a follow up to https://github.com/supertuxkart/stk-code/issues/4147

## Steps to reproduce
Run an instance of STK as **LAN** server : `supertuxkart --lan-server=foo`
Run an instance of STK to create ai : `supertuxkart --connect-now=127.0.0.1 --network-ai=2 --no-graphics`
Run an instance of STK kart for me, to be able to play : `supertuxkart`

The issue is that I get the error message : `Player refused: invalid player`
However, it turn out that it's not the use of the loopback address causing problem, it's because there is the condition : 
`(peer->isAIPeer() && m_game_setup->isGrandPrix())` which forbid the connection of the ia peer.
Note that the fix proposed in https://github.com/supertuxkart/stk-code/issues/4147 is not the correct one (for me), I don't have to remove the line `(peer->isAIPeer() && !peer->getAddress().isLAN())` (BTW trying to connect on the server from another PC (not using loopack, then) didn't change anything. I don't know what this issue was about, in the end :/ )

Conclusion: Should it be possible to lets the user connect AI to GP ? It seems very arbitrary not do so...
We just have to remove the line 3646 of server_lobby.cpp

## Configuration

STK release version: 4a93bea96248c11fee6d69b111c6bd339f38db51 from git

System: Debian 11
Graphics card: None
CPU: i9-8950HK

**Comment by Benau** [comment]
Does it work if you remove that line?

**Comment by ShuffleWire** [comment]
Yes indeed ! I't work just fine :)

**Comment by ShuffleWire** [comment]
Ok just a feedback : I've just tried with friends with AI SuperTux, and clearly the AI are not strong... I was struggling to chase them in one player mode (or in LAN, but with a game set up with the gui from STK), but now I could win so easily, as if they were in medium (or easiest) difficulty, something like that...
Is the difficulty level of the server well applied to AI kart ? 
I've of course set the difficulty level of the server in the conf file to 3 (SuperTux), and this is confirmed by the GUI (server mode is SuperTux)
I've tried to apply this parameter like that as well :  
`supertuxkart --connect-now=127.0.0.1 --network-ai=2 --no-graphics --difficulty=3` but it changed nothing

**Comment by Benau** [comment]
network ai is dumb because they are 'emulated'

**Comment by ShuffleWire** [comment]
I see... that's unfortunate ! Is there a big reason why the regular AI could not be used ?

Other way to achive AI in GP : is it possible to open a local (LAN) server from STK GUI (online/create server) and play a GP (and follow the leader as well, they both don't show up...) ?

**Comment by Benau** [comment]
Ftl is not supported in online

**Comment by kolAflash** [comment]
It's still not recognisable from the game UI, that AI karts and Grand-Prix are exclusive to each other.  
I think this should be made more clear to the user. Else non technical users just won't understand what's happening.

Ideally there should be a checkbox when launching a multiplayer game. Right above the slider for the number of AI bots or GP tracks. The checkbox should have some explaining text like:  
_"enable Grand-Prix mode (disables AI bots)"_  
So when checked, the AI slider becomes the GP slider.

Workaround: `~/.config/supertuxkart/config-0.10/config.xml` -> `wan-server-gp="false"`  
https://www.reddit.com/r/SuperTuxKart/comments/1336in9/comment/jk1ugu7/
