### ISSUE TITLE
escalating extra time in follow the leader mode

### ISSUE THREAD

**Issue by Drahteselpilot** [supertuxkart/stk-code#4746]
## Description
When playing in follow the leader mode on some community tracks the AI leader tends to rescue very regularly leading to an infinite race because the extra time leads the timer to rise continuously. This could be avoided by a minimum time between subsequent rescues or by limiting the extra time when subsequent rescues are done.

## Steps to reproduce

This happens for example in the extreme run track by skindoorminiz.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): F-Droid

System: Android

Graphics card: -

CPU: Snapdragon

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Alayan-stk-2** [comment]
There is little point in playing follow-the-leader on a track that the AI can't handle to the point of the leader rescuing every few seconds.
