### ISSUE TITLE
segfault on raspberry pi 4, supertuxkart from snap (1.3 rev 650)

### ISSUE THREAD

**Issue by msalat** [supertuxkart/stk-code#4747]
## Description

When running some courses from snap-supertuxkart I'll get a segfault (reproducable).

## Steps to reproduce

Graphics to lowest level, 
"Beastie" Car, normal race, "Nessies Teich".

At the moment (or shortly before) the first frame appears, I'll get a "Speicherzugriffsfehler" (segmentation fault).

## Configuration

STK release version: 
1.3 rev 650

STK Source (PPA, distribution package, official binary, etc.): 
raspberry pi os, snap

System: 
Raspberry Pi 4

Graphics card: 
VideoCore VI

CPU: 
Cortex-A72

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```
...
Failed to register allocate at 2 threads:
BLOCK 0:
P   1 S   2       ldvpmv_in t2, 13
P   2 S   4       ldvpmv_in t4, 14
P   3 S   5       nop t5; ldunif (0x00000021 / 0.000000)
P   4 S   6 E   5 ldvpmv_in t6, t5
P   4 S   8       ldvpmv_in t8, 15
P   5 S   9 E   2 add t9, t2, t6
P   5 S  10 E   4 add t10, t4, t6
P   5 S  11       nop t11; ldunif (0x00000400 / 0.000000)
P   6 S  12       nop t12; ldunif (0x00000010 / 0.000000)
P   7 S  13 E  12 ldvpmv_in t13, t12
P   7 S  14 E   8 add t14, t8, t6
P   7 S  15 E   9 max t15, t9, 0
P   7 S  16 E  10 max t16, t10, 0
P   7 S  18 E   6, E  13 add t18, t13, t6
P   6 S  19 E  14 max t19, t14, 0
P   6 S  20 E  15 min t20, t15, t11
P   6 S  21 E  16 min t21, t16, t11
P   6 S  23 E  18 max t23, t18, 0
P   6 S  24 E  19 min t24, t19, t11
P   6 S  37 E  11, E  23 min t37, t23, t11
P   4             mov tmut, t20
P   4             mov tmub, 0
...
```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/issues/4710 ?
