### ISSUE TITLE
Android: Cornfield Crossing: Camera is rotating while driving through building

### ISSUE THREAD

**Issue by fdroidiordf** [supertuxkart/stk-code#4750]
I've attached a video showing the error:
https://user-images.githubusercontent.com/56148672/159117387-ee9b9919-db17-4485-8da5-63d6da77b96c.mp4

I'm using the F-Droid version of STK 1.3 on Android 10 and switched to the gyroscope sensor, just in case that is relevant.

**Comment by Benau** [comment]
@pelya will you have time to take on look on this, it's always reproducible...

**Comment by pelya** [comment]
I won't, I'm in the army now

**Comment by deveee** [comment]
@pelya Good luck!

**Comment by Benau** [comment]
Gyroscope is never working in walldriving surface atm... ![](https://cdn.lihkg.com/assets/faces/pig/wail.gif)

Not sure @pelya and ![](https://cdn.lihkg.com/assets/faces/mouse/smile.gif) think ![](https://cdn.lihkg.com/assets/faces/mouse/there.gif) https://github.com/Benau/stk-code/commit/7a13722b8cffea50374d0e18de95a61f12f85586 makes more sense

**Comment by Benau** [comment]
apk for test https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20220414.apk

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/mouse/miracle_special.gif)
