### ISSUE TITLE
Infinite race glitch

### ISSUE THREAD

**Issue by Insurgent-X** [supertuxkart/stk-code#4760]
## Description

Sometimes when racing in the Old Mine stage, if you go faster than the other karts and go first place during the first lap, you will somehow switch to last place and the race gets stuck on the first lap, thus it does not finish.

## Steps to reproduce

1. Launch STK.
2. Select Singleplayer and choose a kart. Then select the Normal Race mode and select Old Mine.
3. Set the number of AI karts to around 9. Then start the race.
4. Collect a powerup. If it turns out to be a zipper, press space to use it and surpass the AI karts.
5. If you go as fast as possible and pass the finish line, the glitch will activate. Your kart's icon will move beneath the other kart icons, the lap number does not change, and the race does not end. The AI karts seem to be unaffected as they win after three perceived laps.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): Official binary

System: Windows 10

Graphics card: Intel Iris Plus Graphics 655

CPU: Intel Core i5-8259U

## Additional information

This seven-minute video demonstrates the glitch:
https://www.youtube.com/watch?v=Ul_armold34

**Comment by Benau** [comment]
you can try our git 'latest preview release', but we have
```
------------------------------------------------------------------------
r18467 | benaustk | 2021-10-20 09:55:15 +0800 (Wed, 20 Oct 2021) | 1 line

Fix mines lapline extension
```
which should fix this issue already
