### ISSUE TITLE
Logged out

### ISSUE THREAD

**Issue by rebokdev** [supertuxkart/stk-code#4767]
## Description
After running from menu I'm logged out

## Steps to reproduce

run STK from terminal: launching normal
but if you run STK from menu you are loged out

## Configuration

STK release version: 1.3

both ppa and flatpak

System: zorin os 16 core

Graphics card: NVIDIA corporation:TU116M [GeForce GTX 1660 Ti Mobile]

CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

-->
stdout.log: https://mega.nz/file/PAg01RAZ#VmI8mkM7SNlvTd5IYXiidrNXcKnjl_yxdJY2vCHyFJY
```

```

**Comment by Benau** [comment]
Make sure you have 'Remember password' on, otherwise check our official static package

**Comment by rebokdev** [comment]
89,3 gb free space
and from ppa

**Comment by Benau** [comment]
There is nothing interesting in your log file, if no further details are provided there is nothing we can do

**Comment by Benau** [comment]
Also can you clarify 'logged out'? Your stk login credential expires or system logged out (reboot) completely?

**Comment by rebokdev** [comment]
Not from STK
but from os
i'm logged out from os

**Comment by Benau** [comment]
Then you need to check your linux distro settings and see if some packages conflict each other.....
