### ISSUE TITLE
Cannot join a LAN server

### ISSUE THREAD

**Issue by Noexpert** [supertuxkart/stk-code#4769]
Using the instructions [here](https://github.com/supertuxkart/stk-code/issues/4744), I've opened ports 2759 and 2757.
I'm now able to connect to a private server over WAN.

I now want to connect over LAN.
I'm not able to connect to a server created on any machine over LAN.

I've also tried connecting to ipaddress:2759 or 192.168.0.255:2759 as described [here](https://github.com/supertuxkart/stk-code/issues/4014), but not luck.

What am I doing wrong?

**Comment by Benau** [comment]
cannot help you further if only tiny information is provided...

**Comment by Noexpert** [comment]
Both machines are on v 1.3 and attempting to connect over LAN (local networking).
Machine A creates a server.
On machine B, the message says "No server is available".

On the router ports 2759 and 2757 are open but they are **not** forwarded to any machine (so, no port forwarding).

I've tried to connect directly to the other machine using the ipadrress and port 2759.
Same issue.

On other occasions, I get the following message: "No player available for connecting to server.".

Let me know if you'd like more info.

**Comment by Benau** [comment]
You don't need port forward in router, enable those port in your machine

**Comment by Noexpert** [comment]
Both machines are Win10.
STK is allowed on Windows firewall and **all** ports UDP and TCP are open.
![1](https://user-images.githubusercontent.com/10177518/165135642-95458ea1-d50e-4358-b24f-7f6b00fa0449.JPG)

I can connect over WAN.
I cannot connect over LAN, which doesn't make sense.

**Comment by Benau** [comment]
because wan uses a stun server which penetrate the firewall (most of the time)

if you know wireshark you can try to run on both machine and see if the packet deliver / recieve at both end

**Comment by PulsarFX** [comment]
@Benau My solution to this, after spending too much time with it:
Make sure your Wireless Access Point allows communicating between wifi devices. That is: you've got to be able to ping the other wifi device. 
I had one Linux PC with ethernet, one Linux Laptop and two android devices with wifi. The only machine that could see and join LAN servers, created by the wireless devices, was the ethernet PC. 
On my fritz repeater, I had to enable the checkbox under Security settings:  "The active WiFi devices shown below are allowed to communicate with each other"  /  "Die unten angezeigten aktiven WLAN-Geräte dürfen untereinander kommunizieren".

After that, not only could I ping in any direction, but also STK LAN games worked marvelously. :+1: :racing_car: 

I think, with more and more wifi access points, this hint could be added to the FAQ
