### ISSUE TITLE
Feature Request: Implement AMD FSR for upscaling when using lower render resolutions

### ISSUE THREAD

**Issue by Firlaev-Hans** [supertuxkart/stk-code#4777]
## Description
On my low end laptop, STK doesn't run well at 1080p unless I disable the advanced graphics pipeline, but then the game looks absolutely horrible.
So instead I turned down the render resolution to 50% and left the fancy graphics turned on, which looks significantly nicer, but of course everything is a bit blocky now at this low resolution.

Implementing AMD FidelityFX Super Resolution 1.0 to upscale the image when the render resolution is below 100% should be simple enough to do (they officially support only DX11/12 and Vulkan but OpenGL should work too).
It would greatly enhance the experience for players on low end devices like this as it could look much better than the current upscaler and the performance impact is minimal.

Alternatively, NVIDIA Image Scaling could also be used, which works in much the same way and produces similar results (note that I'm **not** talking about DLSS which is not open source and harder to implement).
FSR 2.0 could also be an option once it is open sourced soon™ but may also be harder to implement than FSR 1.0, though it would offer even better looking images at even lower render resolutions.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): Flatpak

System: Fedora 36 x86_64

Graphics card: Integrated Radeon Vega 3 graphics

CPU: AMD Ryzen 3200U

## Additional Information

[FidelityFX Super Resolution on GitHub](https://github.com/GPUOpen-Effects/FidelityFX-FSR)

[Integration Documentation for FSR 1.0](https://raw.githubusercontent.com/GPUOpen-Effects/FidelityFX-FSR/master/docs/FidelityFX-FSR-Overview-Integration.pdf)

[NVIDIAs alternative open source upscaler](https://github.com/NVIDIAGameWorks/NVIDIAImageScaling)

**Comment by Benau** [comment]
Judging from the code of AMD FSR I don't think it's conservative enough to use it for all platforms we support (namely moltenvk or android which has weaker shader support)

**Comment by Firlaev-Hans** [comment]
> Judging from the code of AMD FSR I don't think it's conservative enough to use it for all platforms we support (namely moltenvk or android which has weaker shader support)

Fair point but I still would have liked to see this implemented as an optional feature (which could simply be disabled on some platforms). I'd assume most players are on Linux or Windows anyways.
But if you don't want to implement it regardless, I guess that's fine. Current upscaler + anti-aliasing doesn't look _too_ bad. FSR would just be a nice enhancement for those of us that _can_ use it.

**Comment by mirh** [comment]
If you are really concerned about potatoes FSR lite is also a thing
https://gist.github.com/atyuwen/78d6e810e6d0f7fd4aa6207d416f2eeb
