### ISSUE TITLE
Cocoa-Temple level too difficult on expert level

### ISSUE THREAD

**Issue by Leo987543** [supertuxkart/stk-code#4778]
## Description
The Cocoa-Temple is too difficult, Nitro, sliding, velocity booster, nothing helps.
The player is practically guaranteed to fail on this level at expert difficulty

## Steps to reproduce
Playing Cocoa Temple in Story Mode on expert difficulty

## Configuration

Version 1.1 out of the Ubuntu repository

System: Linux Mint 20.3 64Bit Cinnamon

Graphics card: Intel 3rd Gen Core processor Graphics

CPU: Intel Core i33217U (4) @ 1.800GHz

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:

Problem not related to error log, no software bug

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/issues/3673
