### ISSUE TITLE
Engine sounds are revved at the start of the race

### ISSUE THREAD

**Issue by Natan-P** [supertuxkart/stk-code#4779]
Oops, I misclicked and sent the issue before I finished...

So, the sound of the engine starts up to idle immediately when the race starts, without any revving up. (silence, then immediately idle sounds, without anything in between)
I don't want you guys to fix that directly, I just want you to point me to the file that handles that, as I want to try and implement that myself.
Thank you!

**Comment by Benau** [comment]
Kart::startEngineSFX

but this may not work properly in networked race so better not bother it

**Comment by Natan-P** [comment]
Okay, thanks!
I think I'll still try anyway...
