### ISSUE TITLE
Exit modal text isn't centered

### ISSUE THREAD

**Issue by adem4ik** [supertuxkart/stk-code#4781]
## Description
Currently text on the exit modal window isn't centered. It does look unfinished.
![image](https://user-images.githubusercontent.com/4707112/173581174-febdb823-3932-4344-a117-084fa0d82660.png)

## Steps to reproduce
- Run the game
- Press Escape button

## Configuration

STK release version: 1.3 (also SuperTuxKart-git20220613-win.zip from GitHub)
STK Source: official binary
System: Windows 10 x64
Graphics card: Nvidia GTX 1060 6 GB
CPU: Intel Xeon E3 1270 v2
Gamepads/keyboards models if related to the issue: N/A

## Additional information
N/A

**Comment by Benau** [comment]
I don't think it's important enough to bloat the message dialog interface, not to mention there are various screen sizes. sorry...
