### ISSUE TITLE
Remove (or change the behavior of) "Penalty Time" in "Time Trial"

### ISSUE THREAD

**Issue by ShuffleWire** [supertuxkart/stk-code#4782]
## Description
When playing in time trial, especially alone, the "Penalty Time" given if we accelerate to soon is very annoying : if I mess up my start and got it, I immediately restart the race, no point doing a "Time Trial" with a initial penalty...

Could we, for instance (for Time Trial with 1 player only), remove "Set / Ready / Go", and simply start the timer when the player start moving the kart (ie accelerating) ?
I don't know if we must apply the initial bonus speed (I'm speaking about the bonus we get when starting to accelerate at the best moment), or not. But in fact we got zipper anyway, often to be used at the start of the race, and that should not influence that much the result...

Oh and one more thing : If I got the penalty time, and use a zipper at that exact moment, my kart move forward a bit, and it should not.

## Configuration
STK 1.2

**Comment by Benau** [comment]
initial bonus speed will make a difference if you compare the result with others

if you use zipper right in the beginning you are probably not making good use of it

**Comment by ShuffleWire** [comment]
Yes, Im not saying it doesn't make a difference, and I'm not always" using the zipper right at the beginning, it could be some second after.

But anyway, any good experienced player will try to maximize the initial bonus, at the risk of taking the penalty. But in fact the risk is none existent, given that they will immediately restart... So that remove the intended goal of the penalty, to avoid being "too greedy" with the initial timing (relevant in multiplayer, because you can't restart, in that case)

That not a big deal, however...

And I would like to pin point still the fact that "If I got the penalty time, and use a zipper at that exact moment, my kart move forward a bit, and it should not."
It could be a symptom of some deeper bug in the code, maybe, idk...
