### ISSUE TITLE
Cannot run bin/supertuxkart on ubuntu:

### ISSUE THREAD

**Issue by MxtApps** [supertuxkart/stk-code#4784]
## Description
I am able to run run_game.sh, but not bin/supertuxkart. First, there were missing libraries. I copied all them from lib/ to /usr/lib and then the error was the following: ./supertuxkart: symbol lookup error: ./supertuxkart: undefined symbol: _ZTISt15basic_streambufIcSt11char_traitsIcEE.

## Steps to reproduce
Run bin/supertuxkart on ubuntu.

## Configuration

Version: 1.3

Source: Official binaries from download page

System: Ubuntu 21.10

Graphics card: Mesa Intel® HD Graphics 620 (KBL GT2)

CPU: Intel® Core™ i3-7020U CPU @ 2.30GHz × 4

**Comment by Benau** [comment]
The official tarball is not meant to be installed...

**Comment by deveee** [comment]
Probably ```/usr/lib/x86_64-linux-gnu``` is correct path but if you will copy these libraries there, you will overwrite existing libraries, make a mess in your system and other apps will stop working.

If you want it "installed" in the system, you can extract STK to ```/opt/supertuxkart``` and then make a symlink with 
```ln -s /opt/supertuxkart/run_game.sh /usr/bin/supertuxkart```

Btw. Benau it's possible to set rpath to ```../lib``` in libraries, so you could just click on ```bin/supertuxkart``` and it would run without the ```run_game.sh```. But I'm not sure how it works if you fork process for server creation, so it would need some testing.

**Comment by Benau** [comment]
we don't use fork process for server creation anymore
