### ISSUE TITLE
Segmentation fault when launching game with custom track

### ISSUE THREAD

**Issue by golimarrrr** [supertuxkart/stk-code#4785]
## Description

The game runs fine after install, with the built in tracks. But I'm trying to create a custom track (probably a too complex one, as I'm using OSM2World and following this guide https://wiki.openstreetmap.org/wiki/SuperTuxKart) and when I try to load it the game doesn't open and shows "Segmentation fault" in the console

I tried to increase logging but even in the highest log level I can't find what causes the crash

## Steps to reproduce

Create custom map, copy it to the tracks folder, and launch it with
```$ supertuxkart --track=brivi3 --numkarts=1 --no-start-screen --log=0```

## Configuration

STK release version: 1.2+ds2-1 and 1.3

STK Source (PPA, distribution package, official binary, etc.): Debian11 package for 1.2, and SuperTuxKart-1.3-linux-64bit.tar.xz from Github

System: HP 250 G8

Graphics card: Intel Iris Xe

CPU: i5-1135G7

## Additional information

stdout.log:
```
[stdout.log](https://github.com/supertuxkart/stk-code/files/9126314/stdout.log)
```

input.xml:
```xml



```

Error message:
```
Segmentation fault
```

**Comment by Benau** [comment]
try coredumpctl gdb supertuxkart otherwise upload the track here

**Comment by golimarrrr** [comment]
This is the track folder (I had to remove some textures as the file was too big to upload, I guess they can be replaced with any other PNG)
[brivi3.tar.gz](https://github.com/supertuxkart/stk-code/files/9127142/brivi3.tar.gz)

**Comment by Benau** [comment]
```
<?xml version="1.0"?> encoding="utf-8"?>
<graph>
  <!-- First define all nodes of the graph, and what quads they represent -->
  <node-list from-quad="0" to-quad="-1"/>  <!-- map each quad to a node  -->
  <!-- Define the main loop -->
  <edge-loop from="0" to="-1"/>
</graph>
```
Your graph node .xml is invalid, please make sure your track has a working drive graph

**Comment by Benau** [comment]
Or you can delete quads.xml and graph.xml if you can try without AI
