### ISSUE TITLE
on wayland supertuxkart displays only a quarter of its content on wayland with recent versions of sdl2

### ISSUE THREAD

**Issue by lilydjwg** [supertuxkart/stk-code#4786]
## Description

![screenshot-2022-07-21_11:39:53](https://user-images.githubusercontent.com/440661/180126150-f23ca2b5-7507-4659-8f5e-3b3e72bdb013.png)

This is only the left-bottom quarter of content.

## Steps to reproduce

Run supertuxkart with sdl2 >= 2.0.22 on Wayland with dual monitors.

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): Arch Linux's package

System: Wayfire (a wlroots-based Wayland compositor) on Arch Linux

Graphics card: Intel Corporation HD Graphics 630

CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

Monitors: 1920x1080 and 3184x2160. Both report scale=2 to Wayland clients but the former is scaled down by the compositor to 1.5x.

## Additional information

Downgrading sdl2 and turn off fullscreen mode, this issue doesn't happen. There is no issue if I then make it fullscreen via the compositor's command. It only happens when stk turns itself fullscreen.

I reported this issue to [SDL](https://github.com/libsdl-org/SDL/issues/5941) since a change there caused this issue but they decided that it's stk's fault.

**Comment by Benau** [comment]
Try edit your stk-code/lib/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp and use SDL_WINDOW_FULLSCREEN_DESKTOP instead of SDL_WINDOW_FULLSCREEN ?

**Comment by Benau** [comment]
try https://github.com/supertuxkart/stk-code/commit/ca519d9adec9f49eea46062e3c1266dc2b82d9ba ?

**Comment by lilydjwg** [comment]
e991e0664069f918f8bd5b2727ce708435d9240f doesn't have this issue. However, it doesn't show my external monitor's 3840x2160 resolution, and the text is blurry (it's still fine in windowed mode).

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/issues/4776#issuecomment-1134212474

I think we will always use this flag with vulkan renderer (and you can scale down in game resolution using that spinner)

**Comment by Benau** [comment]
sdl2 doesn't seem to provide a function to tell which display is currently using before the window is created, which we are getting the list of video modes first
```c++
video::IVideoModeList* CIrrDeviceSDL::getVideoModeList()
{
	if (!VideoModeList.getVideoModeCount())
	{
		// enumerate video modes.
		int display_count = 0;
		if ((display_count = SDL_GetNumVideoDisplays()) < 1)
		{
			os::Printer::log("No display created: ", SDL_GetError(), ELL_ERROR);
			return &VideoModeList;
		}

		int mode_count = 0;
		if ((mode_count = SDL_GetNumDisplayModes(0)) < 1)
		{
			os::Printer::log("No display modes available: ", SDL_GetError(), ELL_ERROR);
			return &VideoModeList;
		}

		SDL_DisplayMode mode = { SDL_PIXELFORMAT_UNKNOWN, 0, 0, 0, 0 };
		if (SDL_GetDesktopDisplayMode(0, &mode) == 0)
		{
			VideoModeList.setDesktop(SDL_BITSPERPIXEL(mode.format),
				core::dimension2d<u32>(mode.w, mode.h));
		}

#ifdef MOBILE_STK
	// SDL2 will return w,h and h,w for mobile STK, as we only use landscape
	// so we just use desktop resolution for now
	VideoModeList.addMode(core::dimension2d<u32>(mode.w, mode.h),
		SDL_BITSPERPIXEL(mode.format));
#else
		for (int i = 0; i < mode_count; i++)
		{
			if (SDL_GetDisplayMode(0, i, &mode) == 0)
			{
				VideoModeList.addMode(core::dimension2d<u32>(mode.w, mode.h),
					SDL_BITSPERPIXEL(mode.format));
			}
		}
#endif
	}

	return &VideoModeList;
}
```
You can try something like 
```c++
		for (int d = 0; d < display_count; d++)
		{
			for (int i = 0; i < mode_count; i++)
			{
				if (SDL_GetDisplayMode(d, i, &mode) == 0)
				{
					VideoModeList.addMode(core::dimension2d<u32>(mode.w, mode.h),
						SDL_BITSPERPIXEL(mode.format));
				}
			}
		}
```

This should show the 2nd screen resolution, but it will only togglable after stk is started (due to the first reason)

**Comment by lilydjwg** [comment]
SDL_WINDOW_FULLSCREEN_DESKTOP fixed the blurry issue.

**Comment by lilydjwg** [comment]
On Wayland I don't think it's possible (currently) to tell which screen will be used. Usually they appear on my current using screen, but stk always starts on my laptop screen.

**Comment by lilydjwg** [comment]
Yes the above change makes it show all my screens' resolutions, but it seems that 1920x1080 and 3840x2160 have identical results. All the resolutions are shown, but stk is using a scaled version (3840x2160 / wayland buffer scale = 1920x1080 is shown as chosen). Anyway stk doesn't really change the monitor's resolution.

**Comment by Benau** [comment]
ok you can track https://github.com/supertuxkart/stk-code/issues/4776 for proper fullscreen (with vulkan driver only) support
