### ISSUE TITLE
Kart, thunderbird, parachute, and bomb not visible

### ISSUE THREAD

**Issue by ernugraha24** [supertuxkart/stk-code#4792]
## Description

I played supertuxkart 0.9.3 in year 2020, but no issues, then I update to 1.2 and 1.3 there is a problem that is kart, thunderbird, parachute, and bomb not visible

## Configuration

STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): [supertuxkart](https://https://supertuxkart.net/Download)

System: Raspberry pi 4 OS 64bit (Debian11)

Graphics card: I do not know

CPU: [VideoCore](https://en.wikipedia.org/wiki/VideoCore) IV

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by ernugraha24** [comment]
like this
![im](https://user-images.githubusercontent.com/111166348/184523365-3a5c588b-78c5-46cc-b39d-5b6fc62261d5.png)
sorry that is not parachute. that is bomb '_'

**Comment by Benau** [comment]
duplicated of https://github.com/supertuxkart/stk-code/issues/4334

either update to latest mesa or use that workaround posted there

**Comment by ernugraha24** [comment]
OK

**Comment by ernugraha24** [comment]
how to update mesa?
