### ISSUE TITLE
SuperTuxKart-1.4-rc1-src.tar.xz is missing

### ISSUE THREAD

**Issue by AMDmi3** [supertuxkart/stk-code#4796]
Source tarball is missing for [1.4-rc1](https://github.com/supertuxkart/stk-code/releases/tag/1.4-rc1). I'd like to use it to test FreeBSD port before the release.

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-code/releases/download/1.4-rc1/SuperTuxKart-1.4-rc1-src.tar.xz ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by AMDmi3** [comment]
Thank you! For the record, rc1 works fine on FreeBSD.
