### ISSUE TITLE
Latest version sets screen to low resolution, changes to graphics settings in game do nothing.

### ISSUE THREAD

**Issue by Organic-Marble** [supertuxkart/stk-code#4798]
When I started the game, my screen (s/n 1920x1080) was set to like 1024 x 640.  Changing settings in the game did nothing. When I set the game to run windowed I could fix my screen resolution, but I could not change the game settings still.

## Steps to reproduce

Just start the game.

## Configuration

STK release version: The one that was just put in the PPA.

STK Source (PPA, distribution package, official binary, etc.):  the PPA

System: 

Ubuntu MATE 20.04

Graphics card:  GTX 1050 Ti

CPU: -Processors-
Package Information	
Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz	

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Where is your stdout.log

**Comment by Organic-Marble** [comment]
I ppa-purged and went back to the supertuxkart  in the 20.04 repos

**Comment by Benau** [comment]
then how can you expect this issue to be fixed

**Comment by Organic-Marble** [comment]
I don't
