### ISSUE TITLE
Server List should display Human and CPU players separately

### ISSUE THREAD

**Issue by Fouks0** [supertuxkart/stk-code#4800]
For example it should show something like 0/13 + 2🤖 or so if there is nobody in Frankfurt 0 or 1 rather than 2/15...
And the sorting should ignore CPUs.

**Comment by Benau** [comment]
Fouks! ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)

![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) will add the client code so it can read ai count later....

btw can you update speedrun.com karts icon so that beastie is replaced by godette?

**Comment by Fouks0** [comment]
Thank you :D !

Updated, and Godette is super cool!

**Comment by Benau** [comment]
![Screenshot from 2022-09-22 10-43-20](https://user-images.githubusercontent.com/3252341/191648666-6006a8fe-f6d3-473a-8a1a-0ec496b82cce.png)
![](https://cdn.lihkg.com/assets/faces/pig/dance4.gif)

Now client can ![](https://cdn.lihkg.com/assets/faces/pig/read.gif) ai in https://github.com/supertuxkart/stk-code/commit/e4515e7454f400398b92f3141a9328eb8c8aebba

Server code later to avoid too many changes before release ![](https://cdn.lihkg.com/assets/faces/pig/fry.gif)

**Comment by Benau** [comment]
Server side handling has now been done in 9eda9f75591bdab6b97c2b1c1a76bce8fc778867 ![](https://cdn.lihkg.com/assets/faces/rabbit/agree.gif)
