### ISSUE TITLE
Not start in windows

### ISSUE THREAD

**Issue by fabrixx** [supertuxkart/stk-code#4801]
Supertuxkart 1.3 pee Windows 10 starts correctly but at the selection of players crash to and does not close anymore. Until some time ago it worked. I deleted the user data and reinstalled the 1.4. I lowered the graphics to a minimum. I have changed the resolution. Intel integrated graphics

## Configuration

STK release version: 

STK Source (PPA, distribution package, official binary, etc.): 

System: 

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

**Comment by Benau** [comment]
Try update your graphics driver or try edit your config.xml (see FAQ in stk website), use either vulkan render driver or force legacy device = true

**Comment by Benau** [comment]
Please comment if the workaround doesn't work for you
