### ISSUE TITLE
Windows `run_game.bat` doesn't account for arm32/aarch64 builds

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#4805]
Current `run_game.bat`:

```bat
@echo off
reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT

if %OS%==32BIT (
Pushd %~dp0\stk-code\build-i686\bin\
supertuxkart.exe
popd
)
if %OS%==64BIT (
Pushd %~dp0\stk-code\build-x86_64\bin\
supertuxkart.exe
popd
)
```

This only accounts for x86 and x86-64 systems, not arm32 and aarch64, despite these binaries being included in the package.

**Comment by Benau** [comment]
because there is no easy (or none) way to detect them ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

not sure if you have some idea... otherwise ![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) will ![](https://cdn.lihkg.com/assets/faces/pig/cut.gif) this issue........

**Comment by Benau** [comment]
or just fix stk-website instruction

**Comment by qwertychouskie** [comment]
Untested so far, but should theoretically work:

```bat
@echo off

if %PROCESSOR_ARCHITECTURE%==X86 (
Pushd %~dp0\stk-code\build-i686\bin\
supertuxkart.exe
popd
)

if %PROCESSOR_ARCHITECTURE%==AMD64 (
Pushd %~dp0\stk-code\build-x86_64\bin\
supertuxkart.exe
popd
)

if %PROCESSOR_ARCHITECTURE%==ARM64 (
Pushd %~dp0\stk-code\build-aarch64\bin\
supertuxkart.exe
popd
)

if %PROCESSOR_ARCHITECTURE%==ARM (
Pushd %~dp0\stk-code\build-armv7\bin\
supertuxkart.exe
popd
)

```

References: 
https://superuser.com/a/1441469
https://winaero.com/check-if-processor-is-32-bit-64-bit-or-arm-in-windows-10/

**Comment by Benau** [comment]
ARM STK fans on telegram doesn't have time / interests to test it so ![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) assumes it's working.

Please reopen if there is still an issue ![](https://cdn.lihkg.com/assets/faces/pig/wine.gif)
