### ISSUE TITLE
Nintendo Switch homebrew doesn't run in yuzu

### ISSUE THREAD

**Issue by davidhedlund** [supertuxkart/stk-code#4806]
* Downloaded https://github.com/supertuxkart/stk-code/releases/download/1.3/SuperTuxKart-1.3-switch.zip
* Added the file in the Nintendo Switch emulator yuzu, a thumb image is visible of SuperTuxKart, but when I'm clicking on it nothing happens. I could play other homebrew games in yuzu to it's not an emualtor issue.

**Comment by Mstrodl** [comment]
This seems like to sort of thing that belongs in a [bug report to yuzu](https://github.com/yuzu-emu/yuzu/issues) if you know it works on a real switch, because that's indicative of an emulator bug. I'll try to reproduce this though.

**Comment by Mstrodl** [comment]
STK launched fine for me
![image](https://user-images.githubusercontent.com/6877780/195373853-2efd43c4-0f5f-4547-9602-8533184dbe82.png)
None of the textures load though, I'm guessing due to yuzu's incomplete filesystem implementation (needed to load textures from the `/stk-data` folder on the sd card)

I built this from source using [the yuzu-git AUR package](https://aur.archlinux.org/packages/yuzu-git) 

Much of the testing for stk was done using Ryujinx, so you may have better luck/compatibility there. I'm not sure there's a good reason to be using an emulator for STK though unless you're trying to develop for the platform.

**Comment by davidhedlund** [comment]
Sorry for late reply and thanks a lot for spending so much time to help me. I filed it at https://github.com/yuzu-emu/yuzu/issues/9129

**Comment by davidhedlund** [comment]
I'll close it if they accept the issue. Stay tuned!

**Comment by Benau** [comment]
I can confirm it's working too (except for missing textures), make sure you put stk-data folder in sdmc folder (click file-> open yuzu folder, and choose sdmc)

![Screenshot from 2022-10-31 10-01-49](https://user-images.githubusercontent.com/3252341/198916194-7d50ec0e-76dd-4179-bc08-41690acbacec.png)

I don't think it's an emulator issue ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by vico93** [comment]
> Much of the testing for stk was done using Ryujinx, so you may have better luck/compatibility there.
Just FYI, i tried to test the game on 1.1.337 and it crashes Ryujinx when trying to load the .nro (and yes, the `stk-data` is in the `sdcard` folder of that emulator as well).

**Comment by Benau** [comment]
@Mstrodl full stacktrace is here for Ryujinx
```
00:00:03.592 |W| HLE.GuestThread.15 KernelSvc OutputDebugString: [verbose  ] main: Error messages and other text output will be logged to ./supertuxkart/config-0.10/stdout.log.

00:00:03.623 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: SuperTuxKart, PID: 92
   0x00000000091277b4	rtld:0x11277b4	
   0x0000000008203ae0	rtld:0x203ae0	
   0x00000000081f7ab8	rtld:0x1f7ab8	
   0x00000000080a2250	rtld:0xa2250	
   0x0000000008282808	rtld:0x282808	
   0x000000000802ea44	rtld:0x2ea44	
   0x0000000008014220	rtld:0x14220	


00:00:03.625 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000200026f80
	X[01]:	0x0000000009127690 (rtld:0x1127690)	=> 
	X[02]:	0x474e5543432b2b00
	X[03]:	0x0000000009179b40 (rtld:0x1179b40)	=> 
	X[04]:	0x0000000000000001
	X[05]:	0x0000000009989838
	X[06]:	0x0000000200026fb0
	X[07]:	0x0000000000000021
	X[08]:	0x0000000000000008
	X[09]:	0xfffffffffffffff0
	X[10]:	0x72616b7875747265
	X[11]:	0x6769666e6f632f74
	X[12]:	0x6f632f30312e302d
	X[13]:	0x6c6d782e6769666e
	X[14]:	0xffffffffffff0000
	X[15]:	0x0000000000000018
	X[16]:	0x000000000874b740 (rtld:0x74b740)	=> 
	X[17]:	0x0000000000000008
	X[18]:	0x0000000009ae8158
	X[19]:	0x0000000200026f80
	X[20]:	0x0000000009984de8
	X[21]:	0x000000000912d060 (rtld:0x112d060)	=> 
	X[22]:	0x0000000200026ee0
	X[23]:	0x0000000200026ef8
	X[24]:	0x0000000200026fa0
	X[25]:	0x0000000009bf1c70 (SP:-0x0f40)
	X[26]:	0x0000000000008000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000008000118 (rtld:0x0118)	=> 
	FP:	0x0000000009bf0d30 (SP)
	LR:	0x00000000091277b4 (rtld:0x11277b4)	=> 
	SP:	0x0000000009bf0d30 (SP)
	PC:	0x0000000009178080 (rtld:0x1178080)	=> 


00:00:03.671 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000917808c (opcode 0xd50320ff) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 150
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000917808c (opcode 0xd50320ff) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 150
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
```
Btw ![](https://cdn.lihkg.com/assets/faces/pig/smirk.gif) solved the issue for missing stk.nro in 440def908bf07ae7f94eb17d9d4bee413605a3bf, not sure happens because switch build tool update...
