### ISSUE TITLE
Game don't work with multiple monitors.

### ISSUE THREAD

**Issue by pmatulka** [supertuxkart/stk-code#4813]
When start game main monitor get disabled and game start on secondary monitor.
Main monitor disappear from Nvidia Settings and Monitor Settings and to turn in on again need to restart PC.
To start game on main monitor need to disable secondary monitor in Nvidia Settings or Monitor Settings before running game (just turning off don't work).

Error appear in:
SuperTuxKart-1.4-linux-x86_64.tar.xz
SuperTuxKart-1.4-rc1-linux-x86_64.tar.xz
SuperTuxKart-git20220829-linux-x86_64.tar.xz
SuperTuxKart-1.3-linux-64bit.tar.xz
SuperTuxKart-1.3-rc1-linux-64bit.tar.xz

Error don't appear in:
SuperTuxKart-1.2-linux.tar.xz

System: Linux Mint Mate 18.04, 20.04 and 22.04
GPU: Nvidia GTX 1060 6GB
CPU: Intel i7-4790

stdout.log:
[info   ] [FileManager]: Data files will be fetched from: '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/'
[info   ] [FileManager]: User directory is '/home/user/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/user/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/user/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/user/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/media/user/.../SuperTuxKart-1.4-linux-x86_64/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'pl_PL'.
[verbose  ] translation: Language 'Polish (Poland)'.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: SDL Version 2.24.1
[info   ] [IrrDriver Logger]: Using renderer: OpenGL 4.3.0
[info   ] [IrrDriver Logger]: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2: NVIDIA Corporation
[info   ] [IrrDriver Logger]: OpenGL driver version is 1.2 or better.
[info   ] [IrrDriver Logger]: GLSL version: 4.3
[info   ] IrrDriver: OpenGL version: 4.3
[info   ] IrrDriver: OpenGL vendor: NVIDIA Corporation
[info   ] IrrDriver: OpenGL renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
[info   ] IrrDriver: OpenGL version string: 4.3.0 NVIDIA 515.65.01
[info   ] IrrDriver: OpenGL total memory: 6144
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] GUI: Loading skin data from file: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/skins/peach/stkskin.xml
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/shaders/sp_normal_visualizer.frag
[info   ] HTTPRequest: Downloading https://online.supertuxkart.net/dl/xml/online_news.xml
[info   ] GrandPrixManager: Loading Grand Prix files from /media/user/.../SuperTuxKart-1.4-linux-x86_64/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/user/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[info   ] addons: Using cached addons.xml.
[warn   ] Material: Cannot determine texture full path: kiki.png
[warn   ] Material: Cannot determine texture full path: kiki_exhaust.png
[warn   ] Material: Cannot determine texture full path: genericshadow.png
[warn   ] Material: Cannot determine texture full path: small old konqi_shadow.png
[verbose  ] Thread: Start waiting 877692.372000
[verbose  ] Thread: Waited 0.010000 seconds for thread to become deleteable.
[verbose  ] Thread: Stop waiting 877692.382000
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.

**Comment by Benau** [comment]
probably some SDL2 change is affecting it and hard to find

if you use fullscreen try --render-driver=vulkan may work in 1.4

**Comment by Benau** [comment]
or try to put the 1.2 libSDL2.so into 1.4 lib folder

**Comment by pmatulka** [comment]
adding --render-driver=vulkan fix problem, with 1.2 libSDL2.so game crash.

**Comment by Benau** [comment]
do you always play stk in fullscreen? If so I can add a config.xml to use fullscreen desktop even for opengl

**Comment by pmatulka** [comment]
Yes I always play in fullscreen.
And I have exactly this same error with latest UT path from oldunreal team and adding --render-driver=vulkan fix problem there to.
Thank You <3

**Comment by Benau** [comment]
yes vulkan renderer is experimental, you can wait until i add the sdl fullscreen desktop option for opengl later

**Comment by pmatulka** [comment]
I need to issue bug report to SDL?

**Comment by pmatulka** [comment]
yes i know how to compile stk.

**Comment by Benau** [comment]
Fint the file CIrrDeviceSDL.cpp and comment out these lines:
```
#ifndef __SWITCH__
			if (!SDL_GetWindowWMInfo(Window, &Info))
				return;
#endif
```

and build stk, but when starting stk replace your system / local / whatever libsdl2-2.0.so with the one found in 1.2, and see if opengl fullscreen starts as expected

**Comment by pmatulka** [comment]
Can't download stk-assets, constantly get timeout error. I will try to compile without it, but lines You showed me to comment out are not commented already.

**Comment by Benau** [comment]
use this https://github.com/supertuxkart/stk-assets-mobile/releases/download/1.4/stk-assets-full.zip

i meant change that into:
```c++
	if (CreationParams.DriverType != video::EDT_NULL)
	{
		// create the window, only if we do not use the null device
		if (!Close && createWindow())
		{
			SDL_VERSION(&Info.version);

			// Switch doesn't support GetWindowWMInfo
#ifndef __SWITCH__
			//if (!SDL_GetWindowWMInfo(Window, &Info))z
			//	return;
#endif
#ifdef IOS_STK
			init_objc(&Info, &TopPadding, &BottomPadding, &LeftPadding, &RightPadding);
#endif
#ifdef ANDROID
			Android_initDisplayCutout(&TopPadding, &BottomPadding, &LeftPadding, &RightPadding, &InitialOrientation);
#endif
```

**Comment by pmatulka** [comment]
I'm sorry I am retarded or my english is just bad. Changed and compiling now.

**Comment by Benau** [comment]
archlinux user? try pacman -Syu first

**Comment by pmatulka** [comment]
I am to casual for arch, using Mint Mate.

**Comment by Benau** [comment]
otherwise make sure all your system dependencies are up to date (or downgrade some dependencies like gnutls above)

**Comment by Benau** [comment]
there is https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20221112-linux-x86_64.tar.xz now which you can either use old libsdl.so or use the option non_ge_fullscreen_desktop to use fullscreen desktop for gl drivers, can you try?

**Comment by pmatulka** [comment]
This build works fine with both SDL files, but needed to remove config files to be able to start it.

**Comment by Benau** [comment]
It's weird because this build has same sdl version like 1.4, you sure you started the correct build?

what config file?

**Comment by Benau** [comment]
I assume you problem is fixed
