### ISSUE TITLE
Build with system Spir-v?

### ISSUE THREAD

**Issue by limburgher** [supertuxkart/stk-code#4814]
## Description
I'm the Fedora package maintainer. When I try to build 1.4 as is, I get:
CMake Error at lib/shaderc/third_party/spirv-tools/source/CMakeLists.txt:391 (add_library):
  add_library cannot create ALIAS target "SPIRV-Tools" because target
  "SPIRV-Tools-shared" does not already exist.

CMake Error at lib/shaderc/third_party/CMakeLists.txt:62 (message):
  SPIRV-Tools was not found - required for compilation

I have spirv-tools-devel installed.

## Steps to reproduce
If I apply the attached patch, it builds, but cannot install due to bad deps:

  - nothing provides libSPIRV.so()(64bit) needed by supertuxkart-1.4-1.fc38.x86_64
  - nothing provides libglslang.so.11()(64bit) needed by supertuxkart-1.4-1.fc38.x86_64

## Configuration

stk 1.4 from github source tarball, on Fedora 37.

**Comment by limburgher** [comment]
[spirv-public.patch.txt](https://github.com/supertuxkart/stk-code/files/9913641/spirv-public.patch.txt)

**Comment by Benau** [comment]
you can patch it locally, but I think bundling shaderc will be get rid of completely next release (seems that you can glslc the shaders when building)

**Comment by Benau** [comment]
or do you think you can make stk link with system shaderc? (does fedora have shaderc package?)

**Comment by limburgher** [comment]
We do, and that did the trick. Thanks!

**Comment by Benau** [comment]
btw will you consider package https://packages.debian.org/unstable/libastcenc-dev, we use this library for texture compression in vulkan engine

**Comment by limburgher** [comment]
I'll look into it!
