### ISSUE TITLE
Suggestion: a feature to prompt screen breaks between races

### ISSUE THREAD

**Issue by wolftune** [supertuxkart/stk-code#4818]
## Description

My kid *loves* STK, and I'm working to make sure he uses computers with healthy practices. I've been thinking of installing SafeEyes (https://slgobinath.github.io/SafeEyes/) or similar, but there's no way to prompt that to pop up specifically at the end of races.

My wish would be if STK itself either worked with a tool like SafeEyes (triggering it) or had something similar built-in. At the end of each race, a prompt to take a break from the screen and stretch, look out the window, get a drink, and so on.

Ideally, it could be set whether or not to allow an override of the pausing.

**Comment by Benau** [comment]
Suggestion belongs to https://forum.freegamedev.net/viewforum.php?f=16&sid=3d453d14a07c9a9978d8b7a92c05e387, thank you
