### ISSUE TITLE
Gyroscopic control on iOS build is incredibly nauseating

### ISSUE THREAD

**Issue by krovellium** [supertuxkart/stk-code#4820]
I don’t know if this would go here or not, but the way the gyroscopic steering feature works in the iOS beta kinda makes me sick. I’m not sure if it’s just me, but thought i’d put this here anyways.

**Comment by Benau** [comment]
use steering wheel?

**Comment by krovellium** [comment]
Yeah that’s what i did but i just wanted to see if others thought the same

**Comment by Benau** [comment]
in reality only steering wheel can reach similar driving performance comparing to the desktop (with a keyboard) unless you have an MFI gamepad:

https://www.youtube.com/watch?v=mT2FC-f-cnc

experienced stk player 'george' uses only steering wheel on his phone, checkout his videos ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
