### ISSUE TITLE
--laps is not honored 

### ISSUE THREAD

**Issue by yahavb** [supertuxkart/stk-code#4824]
## Description
I am adding the `--laps` to the command line and I even see a message in the log that confirm the number of laps

```
ESC[0;;mESC[2;37mFri Nov 18 06:01:12 2022 [verbose  ] main: You chose to have 16 laps.
```
but the session always ends after 3 laps. 

## Configuration

```
+ /cmake_build/bin/supertuxkart --server-config=/stk-code/server_config.xml --port=41789 --owner-less --auto-connect --log=0 --connection-debug --difficulty=0 --max-players=4 --track=sandtrack --laps=16
```

**Comment by Benau** [comment]
--laps is for single race only and you need to edit m_default_vote->m_num_laps = t->getDefaultNumberOfLaps(); in server_lobby:2620 for per networked race config

**Comment by yahavb** [comment]
Do you mean replacing:

```
m_default_vote->m_num_laps = t->getDefaultNumberOfLaps();
```

with

```
m_default_vote->m_num_laps = (uint8_t)(UserConfigParams::m_num_laps);
```

Will that cause it use the `--laps` value? Or should I add another variable in server_config.xml? I could not see anything with laps in current version.

**Comment by Benau** [comment]
![gift](https://license.lihkg.com/img/main_image.924a4589.png)
it's done in [0fbbd7b](https://github.com/supertuxkart/stk-code/commit/0fbbd7bbaaebf154c9bf516bfaaf7ba2576664ed)
