### ISSUE TITLE
Unable to change the keyboard keymap after game lauch

### ISSUE THREAD

**Issue by rigobert9** [supertuxkart/stk-code#4826]
## Description
I am unable to change my keymap after launching the game, even by going out of the focus of the window, sticking me in the keymap with which I launched the game. I'm using different keymaps for writing and playing, but I need to close the game again when I accidentally launch it with the wrong keymap.

Sorry I can't help much on this issue, but I don't know at all if this could come from the game, SDL or from my X.org configuration, could anyone confirm this quirk ?

Thanks for your hard work on this great game !

## Steps to reproduce
- Launch the game with a specific keymap
- Change for another keymap, try it out on another running software (firefox on my side)
- Focus STK again
- Test out keys to check if they're still using the old keymap

## Configuration
STK release version: 1.3

STK Source (PPA, distribution package, official binary, etc.): supertuxkart-1.3-3.fc36.1.x86_64 on Fedora 36

System: Asus VivoBook 17, running Fedora 36 with KDE, on X.org

Graphics card: Radeon integrated graphics, AMD Renoir

CPU: AMD Ryzen 5 5500U (12 cores)

Gamepads/keyboards models if related to the issue: Integrated keyboard of the laptop

**Comment by Benau** [comment]
https://github.com/libsdl-org/SDL/pull/4315 the change was reverted later in ![](https://cdn.lihkg.com/assets/faces/fifa/dying.gif) but wayland should work https://github.com/libsdl-org/SDL/pull/4303

try stk with SDL_VIDEODRIVER=wayland supertuxkart and see if better ![](https://cdn.lihkg.com/assets/faces/pig/hehe.gif)

**Comment by rigobert9** [comment]
As expected, it does work in Wayland, but Wayland is currently broken for me. As for the idea of using SDL_VIDEODRIVER=wayland in X.org, it doesn't seem to work because it can't start Wayland, still dropping the log just in case:
`[verbose  ] main: Error messages and other text output will be logged to /home/rigobert9/.config/supertuxkart/config-0.10/stdout.log.
[info   ] [FileManager]: Data files will be fetched from: '/usr/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/home/rigobert9/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/rigobert9/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/rigobert9/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/rigobert9/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/share/supertuxkart/data/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US:fr'.
[verbose  ] translation: Language 'English (United States)'.
..:: Antarctica Rendering Engine 2.0 ::..
Unable to initialize SDL!: wayland not available
No display created: : Video subsystem has not been initialized
No display created: : Video subsystem has not been initialized
[warn   ] irr_driver: Unknown desktop resolution.
[warn   ] irr_driver: Cannot get information about resolutions. Disable fullscreen.
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Unable to initialize SDL!: wayland not available
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Unable to initialize SDL!: wayland not available
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Unable to initialize SDL!: wayland not available
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Unable to initialize SDL!: wayland not available
[fatal  ] irr_driver: Couldn't initialise irrlicht device. Quitting.
`

**Comment by Benau** [comment]
then you need to try recompile sdl of same version in fedora with the patch applied, may affect other apps which use sdl

Otherwise wait until wayland fedora is mature enough

**Comment by rigobert9** [comment]
I'll try it, glad to know the problem only affects me 1nd is exterior to the game. I might try to switch to fedora Silverblue so I can get more recent updates on libraries.
Thanks for the help in any case!
