### ISSUE TITLE
[MSVC][std:c++latest] STK_code failed with error C2666: 'Physics::CollisionPair::operator ==': overloaded functions have similar conversions

### ISSUE THREAD

**Issue by QuellaZhang** [supertuxkart/stk-code#4830]
## Description
After the MSVC team implemented [P2468R2 The Equality Operator You Are Looking For](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html), we got compiler errors with /std:c++latest like below. The way this fails is that the equality operator here https://github.com/supertuxkart/stk-code/blob/master/src/physics/physics.hpp#L84 is missing 'const'. Could you please look this issue? Thanks.

**Note:** this issue will be reproduced on next release version of VS(17.6 or later).

## Steps to reproduce

1. open VS2019 x64 tools command (Or VS2022)
2. git clone https://github.com/supertuxkart/stk-code F:\gitP\supertuxkart\stk-code
3. cd F:\gitP\supertuxkart\stk-code
4. set PATH=F:\tools\build2\bin;%PATH%
5. set PATH=F:\tools\7-Zip;%PATH%
6. curl https://github.com/supertuxkart/dependencies/releases/download/1.3/dependencies-win-x86_64.zip -O -L
7. 7z x dependencies-win-x86_64.zip -oF:\gitP\supertuxkart\stk-code -aoa
8. mkdir F:\gitP\supertuxkart\stk-code\build_amd64
9. cd F:\gitP\supertuxkart\stk-code\build_amd64
10. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCHECK_ASSETS=OFF ..
11. set _CL_=/D_HAS_AUTO_PTR_ETC=1 /D_HAS_STREAM_INSERTION_OPERATORS_DELETED_IN_CXX20 /std:c++latest
12. msbuild /m /p:Platform=x64 /p:Configuration=Release SuperTuxKart.sln /t:Rebuild > build.log

## Error info

build.log: [STK_code_amd64_build.log](https://github.com/supertuxkart/stk-code/files/10174330/STK_code_amd64_build.log)
```
three_d_animation.cpp
F:\gitP\supertuxkart\stk-code\src\physics/physics.hpp(113,21): error C2666: 'Physics::CollisionPair::operator ==': overloaded functions have similar conversions
F:\gitP\supertuxkart\stk-code\src\physics/physics.hpp(84,14): note: could be 'bool Physics::CollisionPair::operator ==(const Physics::CollisionPair &)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22618.0\shared\guiddef.h(192,15): note: or       'bool operator ==(const GUID &,const GUID &)'
F:\gitP\supertuxkart\stk-code\lib\bullet\src\BulletCollision/CollisionShapes/btCompoundShape.h(41,24): note: or       'bool operator ==(const btCompoundShapeChild &,const btCompoundShapeChild &)'
F:\gitP\supertuxkart\stk-code\lib\bullet\src\BulletCollision/BroadphaseCollision/btBroadphaseProxy.h(263,24): note: or       'bool operator ==(const btBroadphasePair &,const btBroadphasePair &)'
F:\gitP\supertuxkart\stk-code\lib\bullet\src\LinearMath/btTransform.h(247,24): note: or       'bool operator ==(const btTransform &,const btTransform &)'
F:\gitP\supertuxkart\stk-code\lib\bullet\src\LinearMath\btMatrix3x3.h(717,24): note: or       'bool operator ==(const btMatrix3x3 &,const btMatrix3x3 &)'
F:\gitP\supertuxkart\stk-code\src\physics/physics.hpp(84,14): note: or 'bool Physics::CollisionPair::operator ==(const Physics::CollisionPair &)' [synthesized expression 'y == x']
F:\gitP\supertuxkart\stk-code\lib\bullet\src\LinearMath\btMatrix3x3.h(717,24): note: or 'bool operator ==(const btMatrix3x3 &,const btMatrix3x3 &)' [synthesized expression 'y == x']
F:\gitP\supertuxkart\stk-code\lib\bullet\src\LinearMath/btTransform.h(247,24): note: or 'bool operator ==(const btTransform &,const btTransform &)' [synthesized expression 'y == x']
F:\gitP\supertuxkart\stk-code\lib\bullet\src\BulletCollision/BroadphaseCollision/btBroadphaseProxy.h(263,24): note: or 'bool operator ==(const btBroadphasePair &,const btBroadphasePair &)' [synthesized expression 'y == x']
F:\gitP\supertuxkart\stk-code\lib\bullet\src\BulletCollision/CollisionShapes/btCompoundShape.h(41,24): note: or 'bool operator ==(const btCompoundShapeChild &,const btCompoundShapeChild &)' [synthesized expression 'y == x']
C:\Program Files (x86)\Windows Kits\10\include\10.0.22618.0\shared\guiddef.h(192,15): note: or 'bool operator ==(const GUID &,const GUID &)' [synthesized expression 'y == x']
F:\gitP\supertuxkart\stk-code\src\physics/physics.hpp(113,21): note: while trying to match the argument list '(Physics::CollisionPair, Physics::CollisionPair)'
```

**Comment by Benau** [comment]
did you mean ![](https://cdn.lihkg.com/assets/faces/mousexm/there.gif) https://github.com/Benau/stk-code/commit/180694219cf2c17ecf57e358844b8aa38c55d855

**Comment by QuellaZhang** [comment]
Yes, that's what we expected :).
