### ISSUE TITLE
SuperTuxKart uses a ton of memory when you have lots of addon karts/tracks/arenas

### ISSUE THREAD

**Issue by searinminecraft** [supertuxkart/stk-code#4831]
## Description

SuperTuxKart really likes to eat up memory when you have tons of (addon) karts/tracks/arenas. I have a ton of addons (pretty much the entirity of stkaddons + unofficial ones), and the total memory usage would go up to 10GB+. and i was forced to not load all addon karts except the ones i want to use to save memory

## Steps to reproduce

1. Open SuperTuxKart with tons of addons
thats it.

## Configuration

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): Arch Linux (Installed on Artix Linux)

**Comment by Benau** [comment]
Use /vulkan and it should be better
