### ISSUE TITLE
blender

### ISSUE THREAD

**Issue by blender-girl** [supertuxkart/stk-code#4838]
Hi

I see there is a blender exporter repo.
I try to import a model format (don't know which yet) in irrlicht engine by exporting it in blender.
But this seems not easy because I have problems with almost all formats except OBJ but this has no animation or anything (only simple textures).

I have read you use irrlicht too.
Can you tell me if I can use the blender exporter for'use in official irrlicht and how to install/use it?

**Comment by qwertychouskie** [comment]
Back when STK used stock Irrlicht it used the B3D format, but nowadays little of Irrlicht remains in STK, even the mesh format in STK nowadays is a custom format called `SPM` (Space-Partitioned Mesh).

**Comment by blender-girl** [comment]
Is it maybe a good idea to make a separate project of the game engine of supertuxkart so people can use it independently in other games and also contribute to it? 
In addition the contributions to it will increase and those can benefit supertuxkart.
Also the blender exporter can be released somewhere and as a result it will be a very cool open source engine with easy to use blender exporter. 

That would also be good since nothing is happening with irrlicht anymore and trying to export using blender is becoming a nightmare.

Thx for considering!

**Comment by blender-girl** [comment]
And it could attract people to create 3D models which can also be contributed to supertuxkart.

**Comment by qwertychouskie** [comment]
if you're working on a project you'd be better off just using a well-supported engine like Godot or maybe Ogre.  SuperTuxKart's custom engine code is too interwoven into the rest of the code to really cleanly split into a separate engine project, nor would there be any real reason to do the effort anyways.

**Comment by blender-girl** [comment]
Ok.
Would you mind uploading a up to date blender exporter for STK to blender extensions when it's launched?
This would be interesting for contributors for STK.

https://code.blender.org/2022/10/blender-extensions-platform/

**Comment by qwertychouskie** [comment]
That would best be requested on the exporter repository (https://github.com/supertuxkart/stk-blender).

**Comment by blender-girl** [comment]
Ok!
