### ISSUE TITLE
Probably PEBCAK: Max. two players possible in LAN multiplayer mode?

### ISSUE THREAD

**Issue by digitalkram** [supertuxkart/stk-code#4841]
Hi,

Not sure if this is a bug or if I am just too stupid to configure it right.

## Description
With three devices (2x android and 1x pc/mac) I am able to create a LAN multiplayer server that the two other devices join. All are in the Lobby. 

However I only manage to have to have two devices actively playing. The third one sees a message "Next round you will be spectating the game."

The server has 8 slots/players configured and 0 bots. Am I supposed to be able to have three active players together or is it a maximum of two + spectators?

Thanks for any pointer in advance

**Comment by Benau** [comment]
Try reset your server_config.xml completely

**Comment by digitalkram** [comment]
Thanks @Benau for your response. It that possible on Android (non rooted)?

**Comment by Benau** [comment]
Not possible and you need reinstall stk completely

**Comment by Benau** [comment]
Make sure the device which you use to create the lan server is in an original state (ie unmodified stk)

**Comment by searinminecraft** [comment]
> Thanks @Benau for your response. It that possible on Android (non rooted)?

It is possible. If you're on Android 11 or above, either using a storage access framework capable (aka can access Android/data using SAF) file manager like MiXplorer, or you can execute this in adb shell (you must enable usb debugging in developer options):

```
$ adb shell
$ rm -f /sdcard/Android/data/org.supertuxkart.stk/files/supertuxkart/home/supertuxkart/config-0.10/server_config.xml
```

Or if you're on Android 10 or below, you can navigate to `Android/data/org.supertuxkart.stk/files/supertuxkart/home/supertuxkart/config-0.10/` using your file manager and delete `server_config.xml` from there.

**Comment by digitalkram** [comment]
@searinminecraft thanks a lot for taking the time to answer my question in detail!

I am going to close this issue now.
