### ISSUE TITLE
Make re-spawning gift and banana indicators optional?

### ISSUE THREAD

**Issue by bgstack15** [supertuxkart/stk-code#4846]
## Description
Starting in STK 1.4 (just reached Devuan Unstable in January 2023), gift boxes and bananas now show an indicator before they spawn. The indicator shows what will spawn within the next few seconds, but I wish to disable the indicators.

I have investigated disabling the indicators by using the old gift* assets which did not change the situation. I checked the config.xml and server_config.xml for possible options and also stk_config.xml and I just cannot find a way to disable these indicators.

## Steps to reproduce
Start a regular race with items, and let the bots get in front of you. When an item is picked up by a bot, shortly thereafter an indicator appears and then shortly after that the item itself respawns.

## Configuration
STK release version: 1.4
Devuan Unstable release 1.4+dfsg-1 which comes directly from Debian

**Comment by Benau** [comment]
STK prefers the least option, but actually you can achieve that by removing `data/textures/icon-*.png` files, proper handling has been done in latest commit though

**Comment by bgstack15** [comment]
Thank you so much for your quick response! This is perfect.
