### ISSUE TITLE
Game is too loud even on the lowest audio setting

### ISSUE THREAD

**Issue by aaronfranke** [supertuxkart/stk-code#4847]
## Description

I have the volume set to the lowest setting (1) but it's still way too loud. It's louder than Discord. I'm on macOS so there is no way to adjust the volume on the OS level, the app volume is the only volume slider.

Please allow me to adjust the volume farther down. Maybe change the slider to be 1 to 100 instead of 1 to 10.

## Steps to reproduce

Set the volume to 1 and notice that it's too loud.

## Configuration

STK release version: 1.4

System: macOS 13.1

**Comment by Benau** [comment]
You can edit the `volume_denominator` in your config.xml file for more steps. ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by Alayan-stk-2** [comment]
Also fixed without having to edit config files through the fix for #4938
