### ISSUE TITLE
SVN timeouts during build 

### ISSUE THREAD

**Issue by yahavb** [supertuxkart/stk-code#4848]
## Description
Building the game from sources the `svn co` fails because of a timeout from the subversion server. 
I think svn is throttling the job because I build stk docker image for arm64 and amd64/x86 processors. The problem is that `docker buildx build --push --platform linux/arm64,linux/amd64` issue two concurrent `svn co` commands that overwhelm the subversion server. 

Can we extend the svn.code.sf.net timeout to allow such build to process?

I am using supertuxkart to show how arm64 fits multiplayer games 

## Steps to reproduce

Per https://github.com/supertuxkart/stk-code/blob/master/INSTALL.md
run `svn co https://svn.code.sf.net/p/supertuxkart/code/stk-assets stk-assets` from scratch upon daily build process for both processors arch

The command:
```
docker buildx build --push --platform linux/arm64,linux/amd64
```
issue 
```
FROM $BASE_IMAGE
ARG SVN_STK
ENV SVN_STK=$SVN_STK
RUN svn co $SVN_STK stk-assets
```
That fails with the below:
```
#9 206.6 svn: E120106: ra_serf: The server sent a truncated HTTP response body.
#9 ERROR: process "/bin/sh -c svn co https://svn.code.sf.net/p/supertuxkart/code/stk-assets stk-assets" did not complete successfully: exit code: 1

#8 [linux/amd64 2/2] RUN svn co https://svn.code.sf.net/p/supertuxkart/code/stk-assets stk-assets
```

Full build scripts:
Base image- https://github.com/aws-samples/containerized-game-servers/tree/master/supertuxkart/server/base-image-multiarch-python3
stk-assets image - https://github.com/aws-samples/containerized-game-servers/tree/master/supertuxkart/server/stk-assets-image-multiarch
stk-code image - https://github.com/aws-samples/containerized-game-servers/tree/master/supertuxkart/server/stk-code-image-multiarch

**Comment by Benau** [comment]
We have no control over sourceforge svn server so please use https://github.com/supertuxkart/stk-assets-mobile/releases/download/git/stk-assets-full.zip in the meantime

**Comment by yahavb** [comment]
Perfect and  thanks.
