### ISSUE TITLE
Left/Right Swap as a Power Up

### ISSUE THREAD

**Issue by lignuxer983** [supertuxkart/stk-code#4851]
Unpredictability is what makes a kart game fun. It would be fun to have the option to make rivals disorientate themselves by swapping left/right controls for a prolonged set of time. Either by launching a projectile at them or coming in contact
with the banana peel.

**Comment by Alayan-stk-2** [comment]
Use the forum  at https://forum.freegamedev.net/viewforum.php?f=16 for suggestions
