### ISSUE TITLE
Update Haiku port

### ISSUE THREAD

**Issue by n0toose** [supertuxkart/stk-code#4852]
## Description

A [couple of patches for SuperTuxKart](https://github.com/haikuports/haikuports/blob/c46e363a676a47b6ea5ddddfca8953ce713318e7/games-action/supertuxkart/patches/supertuxkart-1.3.patchset) that essentially improve gameplay quality were introduced in 2021, but have not been upstreamed yet. Moreover, the port currently present in https://github.com/haikuports/haikuports should be updated.

**Comment by Benau** [comment]
We do not officially maintain the haiku port, sorry about that...

And unless haiku has real opengl 3.3 support those patches are mostly useless, last time I checked there's only 2.x support

**Comment by n0toose** [comment]
> We do not officially maintain the haiku port, sorry about that...

I'm the person that originally worked with you to create the port, just creating this issue to track my progress somewhere and keep you informed / connect this issue with any subsequent relevant pull requests. Some of these patches do set some "sane defaults" for the platform, which is why I'm interested in maybe upstreaming them so that we can keep our port more up-to-date, more easily.

**Comment by n0toose** [comment]
Or at least have some sort of place to discuss things like what you mentioned here: https://github.com/supertuxkart/stk-code/pull/4759#issuecomment-1086997889

Particle effects are currently disabled by default on Haiku, so.

**Comment by Benau** [comment]
file manager and cmakelist changes are upstreamed in 12a8b1d, and I don't think the remaining patch is necessary

**Comment by n0toose** [comment]
Okay, I'll wait until the next release to update this as it's more convenient because of the assets, thank you!

**Comment by Alayan-stk-2** [comment]
We don't handle keeping this port updated.
