### ISSUE TITLE
Some kart part is broken on raspberry pi

### ISSUE THREAD

**Issue by ernugraha2** [supertuxkart/stk-code#4858]
## Description

When I play supertuxkart no force legacy device, some kart with face like godette, sara and konqi has error on face

## Steps to reproduce

Editing sp_skinning.vert to make animated figure visible

## Configuration

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): supertuxkart.net

System: 
Debian 11 Gnome
Graphics card: 
VideoCore
CPU: 
Arm Cortex-72
Gamepads/keyboards models if related to the issue: Leaven K550

## Additional information

Error message:
```
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] Material: Cannot determine texture full path: no :3

```

**Comment by ernugraha2** [comment]
![2023-04-12-063330_1280x720_scrot](https://user-images.githubusercontent.com/125319087/231310800-905edbff-0b35-4891-95c1-44a0cef269e7.png)

**Comment by ernugraha2** [comment]
![2023-04-12-063414_1280x720_scrot](https://user-images.githubusercontent.com/125319087/231310864-3baa621c-a844-4af4-b3de-f35dda6ab26c.png)

**Comment by qwertychouskie** [comment]
If you're manually editing a shader to enable a feature that's specifically disabled on a platform, it's expected that you will have rendering issues.

On the raspberry pi 4, I'd suggest using the Vulkan renderer (`--render-driver=vulkan`), it gives much better performance on the RPi 4 and likely better compatibility too.

**Comment by ernugraha2** [comment]
@qwertychouskie That works, but if play the track will be Segmetation Fault

**Comment by ernugraha2** [comment]
Just i use other driver
