### ISSUE TITLE
Android - Confusing UI after race in story mode

### ISSUE THREAD

**Issue by Heizkoerper** [supertuxkart/stk-code#4859]
(Version 1.4 (311))

The screen with the statistics after a race you won in story mode is quite complicated in the way that it is not clear how to exit this screen again and continue.

Having to click on the trophy icon to continue after a race is quite unintuitive and more intuitive and self explanatory UI elements to do so would be a big improvement.

![image](https://user-images.githubusercontent.com/110174069/231867411-e58b22d4-1f54-4ade-b9d2-d25bef504e73.jpeg)

**Comment by qwertychouskie** [comment]
I think if you tap the trophy icon, it will continue.  That being said, this is bad UI/UX and should be changed so it's more clear.

**Comment by Heizkoerper** [comment]
Oh, indeed. Thank you for your help. I am going to modify the issue, so that it addressed  this more precisely.

**Comment by qwertychouskie** [comment]
Note to self: fix text going off screen
![image](https://user-images.githubusercontent.com/13989090/231925781-de5eae57-514b-4e1e-ba04-e07d1e631c2e.png)
