### ISSUE TITLE
Make it clear how to unban a user from a server 

### ISSUE THREAD

**Issue by CleanMachine1** [supertuxkart/stk-code#4869]
Downloaded from Ubuntu repos.

After banning a user in the network panel, "peer number", I am unsure on how to unban them, is their a command to do so?

What I did 

`kickban 1` 
which then banned the player, but how can I undo this without wiping the db

**Comment by Benau** [comment]
Use sql command on the table `ip_ban`

**Comment by CleanMachine1** [comment]
Yeah, that works, thanks!
