### ISSUE TITLE
How is the user report function used 

### ISSUE THREAD

**Issue by CleanMachine1** [supertuxkart/stk-code#4870]
I see that the server has a table for user reports, how can a user actually use these and report something?

**Comment by Benau** [comment]
![Screenshot_20230528-233927_SuperTuxKart](https://github.com/supertuxkart/stk-code/assets/3252341/1eaa61e2-44b1-4349-803d-e1e6cebe8799)

**Comment by CleanMachine1** [comment]
Thanks, makes sense, I thought it will be more of a function for reporting issues and it would be a command
