### ISSUE TITLE
Automatically put in spectator when there is more than 2 players

### ISSUE THREAD

**Issue by TimeZon3** [supertuxkart/stk-code#4874]
## Description
It says "You will be put into spectator next game" when there is more than two players in one server. I've tried servers that other players (in my friend group) created. I've tried waiting through the spectate. Note that this happens with other player (in that same friend group) too,

**Comment by kimden** [comment]
most likely you need to change `<max-players-in-game value="2" />` in your `~/.config/supertuxkart/config-0.10/server_config.xml` file (or another one if you are not creating server with ingame button) to a bigger value
