### ISSUE TITLE
[UI/UX] Cannot rate addons with keyboard/controller, only mouse/touchscreen

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-code#4876]
I ran across this while working on https://github.com/supertuxkart/stk-code/pull/4864, you can only give a rating to an addon (or change an existing rating) with a mouse or touchscreen, it's impossible to do with keyboard/controller/etc.

**Comment by qwertychouskie** [comment]
Now rating is completely broken for me, I can't open the voting dialog at all anymore.

**Comment by Alayan-stk-2** [comment]
To be investigated

**Comment by qwertychouskie** [comment]
Turns out I wasn't logged in.  There should be adialog saying you need to log in though, rather than just doing nothing when you click the button.
