### ISSUE TITLE
A couple of suggestions i have for custom karts.

### ISSUE THREAD

**Issue by bplx** [supertuxkart/stk-code#4878]
Now, I don't really know how to code that well. But i have 2 suggestions for SuperTuxKart. (Not really sure if this is the right place to put this). I came up with these after downloading some custom karts.

- I think it would be cool if karts could customize the "spare tires" in Battle Mode.
- Allow karts to customize where  the boost appears. I was playing a custom kart and i saw the boost was completely detached from the "thrusters" of the kart.

Now, i'm not a kart creator, just a player, so i'm really not sure how much extra work this would add for the kart creator. Let me know your opinions!

**Comment by qwertychouskie** [comment]
Nitro emitter position can be set by the kart author, so if the position is wrong for a particular kart, the maker just didn't set it correctly.

Custom models for spare tires would be cool.

**Comment by qwertychouskie** [comment]
> Let me just tack on another suggestion; custom UI themes? It's really not a big feature but i think it would be neat if you wanted to customize your game a bit more

You can drop additional UI skins in your `addons/skins` folder and it'll show up as an available option in the Skin spinner.

E.g.: ![image](https://github.com/supertuxkart/stk-code/assets/13989090/f113b2aa-50b7-4f75-b0e8-9b4ce2603368)

Here's some skins you can play with if you want: [cartoon-color-variants.zip](https://github.com/supertuxkart/stk-code/files/11854352/cartoon-color-variants.zip)

**Comment by Benau** [comment]
Please post your suggestion in forum ![](https://cdn.lihkg.com/assets/faces/mouse/there.gif) https://forum.freegamedev.net/
