### ISSUE TITLE
Unable to recover progress from players.xml file

### ISSUE THREAD

**Issue by anon1892** [supertuxkart/stk-code#4883]
## Description

I would have liked to save my progress in STK, because I reinstalled Linux. So, after reading issue #4086 I saved all the ~/.config/supertuxkart folder, and then reinstalled STK on my new Ubuntu. But after copying config files, it doesn't recover progress.
I looked, and I saved "0.8.2" folder, and STK create a new "config-0.10" folder.
I tried to copy all 0.8.2 content to 0.10, copy only players.xml, and tested a lot of things (like installing a previous version of STK). But I didn't succeed.

What do I need to do? Thank you

## Configuration

System: Linux Ubuntu 22.04 (previously on a old Ubuntu, so I think an old STK too)
STK release version: 1.4 (installed from PPA. Tried also woth latest GitHub package)
Graphics card: GTX 1050
CPU: Ryzen 5 1500X

**Comment by Benau** [comment]
that's not possible because 0.8.2 and 0.10 configuration are not compatible

**Comment by anon1892** [comment]
And there is no way to convert it or something ?

**Comment by Benau** [comment]
maybe manually copy each xml field will work

**Comment by anon1892** [comment]
Ok thanks, will try this weekend.
But when the version was changed (0.8.2 --> 0.10), there was no automatic update of the game progress?
If applicable, with which version this update occurs?

**Comment by Benau** [comment]
1.0

Actually, manually converting doesn't make much sense anyway, because the story mode of 0.9.3 and 1.0 is different.
