### ISSUE TITLE
Progress bar padding disappears when it fills 100%

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4891]
This is not a single case. This appears in every progressbar and it's quite noticable.
![image](https://github.com/supertuxkart/stk-code/assets/35170687/8bc7eabd-27a9-4295-8ab7-aa9fcb41cb38)

**Comment by qwertychouskie** [comment]
Does this also happen with the Cartoon theme, or only the classic themes?

**Comment by CodingJellyfish** [comment]
![image](https://github.com/supertuxkart/stk-code/assets/35170687/130d5669-7f2e-4e8a-ac78-ab2344f214ee)
The problem in modern skin is completely different. there's a gauge fill starting from wrong place in 0%

**Comment by CodingJellyfish** [comment]
> Does this also happen with the Cartoon theme, or only the classic themes?
I think I've found the exact problem on the classic themes, but I'm not familiar with the cartoon one. We need your help.
