### ISSUE TITLE
The scene winning Nolok still uses old model of GNU

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4898]
There's a new GNU model now and I think it's better to use that.

**Comment by qwertychouskie** [comment]
See related: https://forum.freegamedev.net/viewtopic.php?f=18&t=13078

**Comment by Alayan-stk-2** [comment]
Unless a 3D modeller is really interested in doing this, I think we'll keep it like this for 1.5.

Updating the look of these old bad-looking cutscenes is not worth delaying the release, and for 2.0 we will use different cutscenes.
