### ISSUE TITLE
The car is white-colored and the headlights shine but look like a part of the car and not a cone light like other karts

### ISSUE THREAD

**Issue by awab1433** [supertuxkart/stk-code#4905]
## Description

Please.. I need guidance in creating a cart from a .glb model: I got it to export and played with it, but is is discolored and lacking animation. Please guide. Thank you for all of you generous support, guys.

## Steps to reproduce

simply take the 3d model, and export it and boom, its there but soo discolored

## Configuration

STK release version: 
I think it is 1.8

STK Source (PPA, distribution package, official binary, etc.): 

System: HP

Graphics card: ??

CPU: ??

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```
My request does not relate to whatever these prompts are.

**Comment by qwertychouskie** [comment]
https://supertuxkart.net/Making_Karts

**Comment by awab1433** [comment]
Can you please tell me the steps?? I've gone through the website a lot and I do not understand. Please help me and thank you for your support.
________________________________

**Comment by qwertychouskie** [comment]
If you are looking for further help with assets development I suggest asking on the SuperTuxKart Discord server: https://discord.gg/u2AJDpF

Support with asset creation is outside of the scope of GitHub issues, as they are meant for bug tracking.
