### ISSUE TITLE
IA level in splitscreen

### ISSUE THREAD

**Issue by ShuffleWire** [supertuxkart/stk-code#4911]
## Description
Playing on Splitscreen, with Intermediate difficulty, IA kart are skidding, even if at that level they should not. In fact in solo mode they don't. It's seems like we are playing on the Expert mode (SuperTux beeing still faster, imo)

## Configuration
STK release version: main 1.4
STK Source (PPA, distribution package, official binary, etc.): Debian 12 repos
System: Debian 12

**Comment by Alayan-stk-2** [comment]
I cannot reproduce this issue on the dev version.

There is also no difference between singleplayer and splitscreen multiplayer on whether the AI chooses to skid or not.

Most likely, Expert was picked by error in the selection screen.
