### ISSUE TITLE
SuperTuxKart crashes on quit on MacOS

### ISSUE THREAD

**Issue by UnsolvedCypher** [supertuxkart/stk-code#4914]
## Description
SuperTuxKart crashes on exit with the following error:
![image](https://github.com/supertuxkart/stk-code/assets/3170853/87cc11d6-32c1-445b-aca4-2d295f06741b)

## Steps to reproduce
1. Open SuperTuxKart
2. Press escape
3. Confirm that you want to quit
4. Observe the error message

## Configuration

STK release version: 

Official binary, SuperTuxKart, 1.4

System: MacOS (Apple Silicon, M2 chip)

## Additional information
stdout.log:
```
https://pastes.io/7tjwb7jlu2 (too big for GitHub issue)

```

I am happy to provide other information or test other binaries if that helps. I see the following in the terminal:

Error message:
```
./supertuxkart terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Benau** [comment]
try run stk with lldb and paste the backtrack using bt, otherwise you seem to have install too many addons, try removing some of them

**Comment by UnsolvedCypher** [comment]
Thank you for taking a look, here's the backtrace:
```
2023-09-23 22:04:35.419041-0400 supertuxkart[1699:11917] AudioHardware-mac-imp.cpp:660    AudioObjectGetPropertyData: no object with given ID 0
Process 1699 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xbeaddd9fda28)
    frame #0: 0x000000010023b7b8 supertuxkart`KartModel::~KartModel() + 860
supertuxkart`KartModel::~KartModel:
->  0x10023b7b8 <+860>: ldur   x8, [x8, #-0x18]
    0x10023b7bc <+864>: add    x8, x1, x8
    0x10023b7c0 <+868>: ldr    w8, [x8, #0x10]
    0x10023b7c4 <+872>: cmp    w8, #0x1
Target 0: (supertuxkart) stopped.
```

**Comment by UnsolvedCypher** [comment]
Here's the backtrace with debug symbols:

```
2023-09-23 23:06:25.674111-0400 supertuxkart[14541:75951] AudioHardware-mac-imp.cpp:660    AudioObjectGetPropertyData: no object with given ID 0
Process 14541 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xbeaddd9fa1a8)
    frame #0: 0x00000001004a38c4 supertuxkart`KartModel::~KartModel(this=0x000000034c2e6a88, vtt=0x0000000101b58988) at kart_model.cpp:288:33
   285 	        {
   286 	            obj.getModel()->drop();
   287 	            irr_driver->dropAllTextures(obj.getModel());
-> 288 	            if (obj.getModel()->getReferenceCount() == 1)
   289 	            {
   290 	                irr_driver->removeMeshFromCache(obj.getModel());
   291 	            }
Target 0: (supertuxkart) stopped.
```

**Comment by Benau** [comment]
you can try print *this in the stack and see which (probably addon) kart it is and remove the bad kart yourself

**Comment by UnsolvedCypher** [comment]
I removed a bunch of addon karts and that solved my problem. Thank you!

**Comment by kimden** [comment]
Seems to be the same as #5240.
