### ISSUE TITLE
Players can guess who will win when they are far from each other

### ISSUE THREAD

**Issue by Gfrni** [supertuxkart/stk-code#4917]
With the current weapons, a player can attack its rivals only after getting close enough to them.
When they are not close to each other, **they have nothing to do**, and **they can guess who will probably win**, so the game will become boring until it finishes or the players somehow become close again.

Please add some long distance weapons. 
1. Attacking all the rivals ahead of the player.
2. Attacking only the first rival ahead of the player.

Regardless of whether the player can see the rivals or not.

**Comment by Benau** [comment]
players in irc suggested that parachute is good enough for such purpose, so nothing will be done
