### ISSUE TITLE
Make the sound volume control logarithmic

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4938]
Right now, STK's code multiply the volume proportionally for each level of the sound volume settings.

This means that the jumps at the top are tiny, for example 90% to 100% is +11%, while the jumps are the bottom are massive, for example 10% to 20% is +100%, and the 10% setting itself (the lowest non-muted settings) risks being too loud.

**Comment by CodingJellyfish** [comment]
Making it logarithmic is nice, but I should mention here that the current STK value adjustion is counted in %, which means it changes not in decibels but by the same way of system setting.
