### ISSUE TITLE
STK crashes when faced with an unknown difficulty in server selection

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4944]
Line 1314 of race_manager.cpp : 

```
        case RaceManager::DIFFICULTY_EASY:   return _("Novice");   break;
        case RaceManager::DIFFICULTY_MEDIUM: return _("Intermediate"); break;
        case RaceManager::DIFFICULTY_HARD:   return _("Expert");   break;
        case RaceManager::DIFFICULTY_BEST:   return _("SuperTux");   break;
        default:  assert(false);
```

Called from states_screens/online/server_selection.cpp:309
Called from states_screens/online/server_selection.cpp:562

All 1.X versions have the same assert, but 1.4 does not crash for me, only the git version.

This crash can be triggered when trying to display a list of online servers, if one of the server is a test server for the 2.X branch in SuperTux, so it is significant.

**Comment by qwertychouskie** [comment]
> All 1.X versions have the same assert, but 1.4 does not crash for me, only the git version.

Probably your 1.x builds are built in Release mode (or RelWithDebInfo), not Debug.

**Comment by Alayan-stk-2** [comment]
Good point !
