### ISSUE TITLE
Thunderbird rescue may be accidentally triggered on Android when holding the steering wheel

### ISSUE THREAD

**Issue by S0nter** [supertuxkart/stk-code#4960]
## Description
When you are driving on the road, Thunderbird suddenly rescues you.
This happened in local Multiplayer mode on three different Android devices. With both Linux and Android as host.

Here is a video of this bug:

https://github.com/supertuxkart/stk-code/assets/108224581/e8fdb13d-9893-4a99-b48a-bdd531aeb773

## Steps to reproduce
 1) Download the application from the [official 1.4 release](https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4.apk)
 2) Install it on an Android device
 3) Play for an hour or more in multiplayer

## Configuration
STK release version: **1.4**
STK Source: [**official binary**](https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4.apk), **Google Play** 

System: Android 13

**Comment by Alayan-stk-2** [comment]
Well, the issue is that you are touching the rescue icon ? It's very clear in your video that the Android rescue icon (the blue birdy circle next to the pause icon) gets activated each time the game rescues you.

The video ends with a sequence titled "the issue occurs while holding", so you seem aware that it's touching this area that triggers the rescue. What did you expect to happen ?

**Comment by S0nter** [comment]
Thank you for your reply!
Now I see that I've probably triggered rescue button there. Correct me if I'm wrong, but here are two issues right now:

I hold down the steering wheel and move finger up to the rescue button, it triggers. I think that it should behave the same as a pause button in this context (shouldn't be triggered).

Continuous rescuing when rescue button is not directly triggered. 

Here is a video for that:

https://github.com/supertuxkart/stk-code/assets/108224581/3be22807-7229-4b09-a302-4e2899473d25

**Comment by SecondLuke242014** [comment]
Youmpresssed the bird icon

**Comment by Anatoliy6463** [comment]
Oh, when I first played this game, I also encountered this problem, but, I switched to gyroscope, and after that, I just switched to PC
