### ISSUE TITLE
Some skin-themed icons are not properly reset when changing skin

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#4964]
All the attachment icons shown on top of the player kart icon (such a the parachute and the anchor when hitting a banana) are not properly reset when switching skins.

Steps-to-reproduce : 
- Start the game with a non-cartoon skin (resp. the cartoon skin)
- Enable the cartoon skin (resp. a non-carton skin)
- Start a race
- Hit a banana and look at the icon displayed on the kart icon in the list left of the screen.

@qwertychouskie

**Comment by qwertychouskie** [comment]
AFAIR this also used to be an issue with the powerup icons when you got a gift box, but I think that was fixed at some point.  Likely the same fix needs to be applied here.

For reference, here's the code that draws the currently held powerup icons, which does work: https://github.com/supertuxkart/stk-code/blob/master/src/states_screens/race_gui_base.cpp#L1203

`video::ITexture *iconItem = powerup->getIcon()->getTexture()` seems to be working as expected.

The plunger-in-face code also works as expected: https://github.com/supertuxkart/stk-code/blob/master/src/states_screens/race_gui_base.cpp#L1226

`powerup_manager->getIcon(PowerupManager::POWERUP_PLUNGER)->getTexture();`

Meanwhile, the attachment code is what is not working: https://github.com/supertuxkart/stk-code/blob/master/src/states_screens/race_gui_base.cpp#L1241

`attachment_manager->getIcon(kart->getAttachment()->getType())->getTexture();`

Seems like `powerup_manager->getIcon()` works properly, but `attachment_manager->getIcon()` does not.

**Comment by qwertychouskie** [comment]
Side note: `PowerupManager::unloadPowerups()` is a completely unused function, should probably be removed.

**Comment by qwertychouskie** [comment]
It seems that the powerup manager has an explicitly defined constructor that resets`m_all_icons`: https://github.com/supertuxkart/stk-code/blob/master/src/items/powerup_manager.cpp#L48

Meanwhile the attachment manager doesn't have any explicitly defined constructor.

Perhaps this is the difference?
