### ISSUE TITLE
Full resolution is not supported when a scale is set on Windows

### ISSUE THREAD

**Issue by CodingJellyfish** [supertuxkart/stk-code#4971]
For example, if you set 200% scale on Windows with a 2560x1440 screen, the biggest solution it can obtain is 1280x720 and everything is blurry inside.

**Comment by qwertychouskie** [comment]
https://github.com/supertuxkart/stk-code/issues/3614#issuecomment-626402946 is the proper solution, but was never implemented AFAIK.
