### ISSUE TITLE
Thunderbird removes bad items like Bomb or Handicap

### ISSUE THREAD

**Issue by Lulu-Games** [supertuxkart/stk-code#4976]
If you press the 'save' key (default backspace) thunderbird will save you. But it will also remove your handicap or bomb, if you have one. That is a a way to cheat!

**Comment by Alayan-stk-2** [comment]
Rescue removing a bomb, or any other type of attachment (parachute, anchor, swatter, shield) from the kart is intended behavior. If you want to test and discuss how effective it can be to use a last-second rescue against bombs, basket balls, etc., please go to the forum.
