### ISSUE TITLE
Character animations in sprites could be more beautiful

### ISSUE THREAD

**Issue by Erikcht** [supertuxkart/stk-code#4977]
Those arts i used IA from bing to create those reimaginations.
![OIG](https://github.com/supertuxkart/stk-code/assets/8018995/483f1e76-8a00-46d4-acea-88b3ae55f14e)
![OIG er6Xlaj1c](https://github.com/supertuxkart/stk-code/assets/8018995/c73f24a3-f91c-4109-a851-8c20fe87098d)

**Comment by Lulu-Games** [comment]
What do you mean with "sprites"? Sjpertuxkart works with 3D Models not with 2d graphics.

**Comment by Alayan-stk-2** [comment]
STK uses 3D models and animations, and using sprites is not a good solution.

It is absolutely true that kart animations are overall subpar, but that's a different issue.

**Comment by Anatoliy6463** [comment]
Wtf?! Sprites?! It's a 3D game, not 2D

**Comment by Lulu-Games** [comment]
Yes, I also haven't ever geared of sprites in a 3d game

**Comment by GNUAn** [comment]
@Lulu-Games left GitHub for an unknown time.
