### ISSUE TITLE
Suggestion: Gliders and custom bublegums

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#4982]
What about Gliders for karts? And what about a custom bubblegum shield for each kart? The Glider could be handled as an attachment. And for the karts wich haven't got their own Glider / Bubblegum model/s the default ones are used.

**Comment by searinminecraft** [comment]
Nolok actually has a custom bubblegum and swatter model, though they're hard coded into the game.

gliders though? what would they do?

**Comment by Rodrigopere** [comment]
[Uploading backup-20231226191534.json…]()

**Comment by Lulu-Games** [comment]
> Nolok actually has a custom bubblegum and swatter model, though they're hard coded into the game.
> 
> gliders though? what would they do?

I know but if nolok has one, it would be actually not so hard to implement. And Gliders: like they in Mario Kart; to fly

**Comment by Rodrigopere** [comment]
> What about Gliders for karts? And what about a custom bubblegum shield for each kart? The Glider could be handled as an attachment. And for the karts wich haven't got their own Glider / Bubblegum model/s the default ones are used.

**Comment by Anatoliy6463** [comment]
Cool idea!

**Comment by GNUAn** [comment]
R.I.P. @Lulu-Games

**Comment by Alayan-stk-2** [comment]
Gliders are not intended.
