### ISSUE TITLE
Docs: list whether ports are udp or tcp

### ISSUE THREAD

**Issue by irismessage** [supertuxkart/stk-code#4986]
## Description

At present https://github.com/supertuxkart/stk-code/blob/master/NETWORKING.md lists the port numbers but not the protocol. Firewalls can discriminate between the two so it should be clear which you need to open. I believe it is UDP not TCP

**Comment by Alayan-stk-2** [comment]
STK relies on ENet so yes it's UDP packets. Documentation has been updated.
