### ISSUE TITLE
Spectators remove addons from the lobby

### ISSUE THREAD

**Issue by kimden** [supertuxkart/stk-code#4997]
## Description
Spectators remove addons from the lobby, which means that anyone can effectively block the whole server from playing addons by just joining (for example) with a simple mobile account without any maps.

I can fix it myself later, or someone else can do it if they have a bit more time than me.

## Steps to reproduce

1. Make players A and B join the server, with A having a certain map M and B not having M.
2. Ask B to invoke `/spectate 1`
3. Start the game, there will be no map M.

## Configuration

STK release version: latest git but it happens since a few years anyway

**Comment by Alayan-stk-2** [comment]
I agree that a spectator being there should not limit the choice of the active players.
