### ISSUE TITLE
Make Nolok's castle require more points

### ISSUE THREAD

**Issue by Anatoliy6463** [supertuxkart/stk-code#4999]
## Description
So, I completed the SuperTuxKart and Nolok's castle requires only 190 points, I think it needs to be more challenging, also, i think there need to be more maps

## Configuration

SuperTuxKart 1.4

**Comment by Anatoliy6463** [comment]
Oh, it's 4999th issue! Let's celebrate! 🤣

**Comment by Alayan-stk-2** [comment]
It is designed so that it's possible to complete the game while only completing the challenges in Novice difficulty. So really the requirement is "complete all the other challenges in any difficulty" to unlock the final challenge.

**Comment by Anatoliy6463** [comment]
It's not completed
