### ISSUE TITLE
Make better textures and smoother 3D models

### ISSUE THREAD

**Issue by Anatoliy6463** [supertuxkart/stk-code#5000]
STK needs to get better textures and smoother 3D models, because most people think about STK as open source games and when they see it, they think it's a bad game and they switch back to proprietary games

**Comment by Anatoliy6463** [comment]
Hehe, 5000th issue.

**Comment by kimden** [comment]
I guess you can just contribute to it and/or invite some other texture makers and 3d modellers to collaborate? It doesn't seem like a repo issue at all, and discussions are usually on freegamedev forum or discord/irc/telegram/matrix channels of the game

**Comment by Lulu-Games** [comment]
The most models are actually good (look at Konqi)

**Comment by Lulu-Games** [comment]
But you are right, many people think, that it is bad quality, but it isn't

**Comment by Lulu-Games** [comment]
Yes it is a little bloat but it looks much better (and modern) than XFCE/LXDE or even GNOME

**Comment by Anatoliy6463** [comment]
Yeah, GNOME is even more bloated and it requires systemd(I hate systemd)

**Comment by Alayan-stk-2** [comment]
Extremely open-ended catch-all issue with no practical applicability. Yes, better texture and 3D models are needed, but this issue doesn't help the work on it.
