### ISSUE TITLE
Make Black Forest faster

### ISSUE THREAD

**Issue by Anatoliy6463** [supertuxkart/stk-code#5004]
Why Black Forest takes 8 minutes to beat?! There are only 3 leaps and usually, one leap takes a minute or slightly more, but Black Forest is very long. Nolok's castle is faster than Black Forest but, Nolok's castle needs to be longer than Black Forest

**Comment by Alayan-stk-2** [comment]
FYI Black Forest is only 2 laps. It takes more time to complete a default race than on other tracks but not unreasonably so.

**Comment by Anatoliy6463** [comment]
> FYI Black Forest is only 2 laps. It takes more time to complete a default race than on other tracks but not unreasonably so.

Oops, it has 2 laps, but IT TAKES 8 MINUTES

**Comment by Alayan-stk-2** [comment]
Sorry to say, but skill issue. In novice, which is very slow, without using any skidding or nitro and hitting 5 bananas, I still got a lap at 2m50s... Taking 4 minutes per lap requires driving very very slowly.

**Comment by Anatoliy6463** [comment]
> Sorry to say, but skill issue. In novice, which is very slow, without using any skidding or nitro and hitting 5 bananas, I still got a lap at 2m50s... Taking 4 minutes per lap requires driving very very slowly.

I played as Wilber, and he has a very slow car, you drives as Godette, right?

**Comment by Alayan-stk-2** [comment]
I think I used a medium kart. Even with a heavy the difference would only be 10%, but 4 minutes is 40% slower.
