### ISSUE TITLE
Disabling the game sound online still plays some part of sound

### ISSUE THREAD

**Issue by kimden** [supertuxkart/stk-code#5026]
## Description
Changing sound volume from non-zero to zero ingame results in complete removal of sound in local singleplayer, but not online. Basically the sound disappears, but the last played small part of the sound (which is usually kind of annoying) stays playing until the game ends. Considering this is the only way to change the sound volume online (there's no command in the lobby

Maybe related but less important thing, sometimes a player needs to go to ingame menu and back after changing the sound from 0 to non-zero, so that the sounds of all kart engines are heard.

[Video](https://youtu.be/nB9owyNo7p4) showing the bug online and its absence offline.

## Steps to reproduce
1. Turn sound effects on
2. Start the game on an online server
3. Try to disable the sound effects using settings menu while not quitting the game
4. Observe strange sound until the end of the game (unless you change sound settings again)

## Configuration

STK release version: latest git a254c7a

## Additional information

stdout.log seems to print nothing about sound during testing this.

**Comment by Alayan-stk-2** [comment]
Labelling as minor because there is rarely any point in removing the sound in the middle of the race, but I can confirm the bug on my end too.

**Comment by kimden** [comment]
Just to explain, I have to remove the sound in the middle of the game pretty many times when I'm asked to join a voice chat in between the games.

I don't want game sounds to prevent me from listening, and I cannot change it without leaving the server otherwise. I can agree there are less reasons to change the sound volume in the game if there's a lobby command for that. I don't mind if the issue is minor, though.
