### ISSUE TITLE
Allow to favorite tracks

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5028]
The favorite tracks would:
- Show up first in the list of tracks of their category, before other tracks. This is especially useful for addons.
- Receive a small visual distinctive sign (a small star, a small heart, a small tux... Something)
- Also have a special category where only favorite tracks (standards and addons) would show up.

The option to make a track favorite should be integrated in the UI and not require the player to go too much out of their way. Suggested locations (multiple locations can be done) are : 
- In the track selection screen itself. Probably something like clicking first a button to enter the "select favorites" mode and then clicking the track icons would trigger adding them to the favorites instead of going into the track info screen.
- In the pause menu when playing a track (suggested by CodingJellyfish)

**Comment by searinminecraft** [comment]
This can be very useful because I have so much addons and I keep forgetting the names of the favorite tracks I played before.

**Comment by Alayan-stk-2** [comment]
Done with https://github.com/supertuxkart/stk-code/commit/bf62de82ee6b6903c6a23f8c449e2c118aabf744, https://github.com/supertuxkart/stk-code/commit/ca80a1c5db2af607aaeec1c40a6785ab56eb7481 and https://github.com/supertuxkart/stk-code/commit/c61ab025780b98c1ad18a6a18b5160833277f2d3

This does not currently include a way to make arenas or soccer fields favorites. Most of the code needed for those could be shared or largely based on the code for tracks, but because the groups in TrackManager and the UI screens are different, this will require additional work.
