### ISSUE TITLE
request: video tutorial for making karts

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#5040]
Hi

I try to make new karts for STK but being not a programmer, it's hard to understand many things like the particles file etc
Is there somebody who wants to make a video tutorial showing a very easy to make kart and go through the steps from start to finish (using only Blender and GIMP)? It could be put on youtube as official STK channel.

In addition there could be made 1 installation video for the Blender add-on, SVN, ...
I found how to do this but it also took a lot of time because i'm not a programmer and never heard of SVN.

That would help me and a lot of other people who are only 3D designers. It could make the step less big for starting to make a kart.

Thanks

**Comment by awab1433** [comment]
Hmm, I'm not the person to help you but you are welcome to contact me in case you need any help
Discord user: awab1433
Hope this helps!

**Comment by Alayan-stk-2** [comment]
Fair request, but this is outside the scope of things tracked in this issues tracker.
