### ISSUE TITLE
bunny ears?

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#5043]
For some reason all karts have bunny ears. They don't appear when you select a kart but only in the game.
I use STK 1.4

![afbeelding](https://github.com/supertuxkart/stk-code/assets/165606399/4b0f1dac-f305-4c3c-be94-0da1f8f08808)

**Comment by qwertychouskie** [comment]
It's a seasonal thing for Easter.  Around Christmas they wear Santa hats.
