### ISSUE TITLE
supertuxkart: official OST

### ISSUE THREAD

**Issue by ghost** [supertuxkart/stk-code#5045]
Hi

I had an idea for supertuxkart.
What about releasing on the website an official soundtrack of supertuxkart? So it are just the OGG files found in the music folder.
People can download the soundtrack to play with their favorite music player.

It could offer the music in 2 formats:

- lossy: just the OGG files of the game itself
- lossless: the source files compressed using FLAC (if the original files are still available)

I hope you like my idea :)

**Comment by searinminecraft** [comment]
1. why when you can just copy and paste from PREFIX/data/music (not android though, theyre compressed). Does not seem to be necessary as the files there are high quality enough
2. This account is deleted...
