### ISSUE TITLE
Increase anisotropic filtering quality in the presets and don't offer x2 anisotropic filtering

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5076]
Currently, SuperTuxKart has 3 levels of anisotropic filtering supported through presets:
- x2 (lowest Image Quality preset, used by graphics presets 1 and 2)
- x4 (middle Image Quality preset, used by graphics presets 3 and 4)
- x16 (highest Image Quality preset, used by graphics presets 5 and 6)

Generally speaking:
- x2 looks like trash. When I used to play in Graphics 2, I strongly believed that STK was suffering from some serious bug.
- x4 is visibly subpar, but much more tolerable
- x16 looks fine

Visual demonstration of x2:
![BLUR](https://github.com/supertuxkart/stk-code/assets/25536748/5296e05f-1a35-4dbb-85bf-51958ef92f1d)

The performance cost of anisotropic filtering has been really small on any hardware that has come out for many years, whereas the visual impact is massive.

I intend to:
- Allow x4 on the lowest preset and have it used by graphics preset 1
- Use x16 on all other graphics presets.

Here is a comparison of performance for different settings on my iGPU:

![Anisotropic](https://github.com/supertuxkart/stk-code/assets/25536748/a2d6a743-3641-4867-8e99-73426968be6a)

**Comment by Alayan-stk-2** [comment]
Based on PocketMarty's tests, the VRAM impact of the anisotropic filtering setting is negligible, as I expected. It consumes some bandwidth, but that's already accounted for in FPS figures.

**Comment by qwertychouskie** [comment]
Can we look into using anisotropic filtering on GLES as well?  Last I saw, aniso was force-disabled for GLES.

**Comment by Alayan-stk-2** [comment]
> Can we look into using anisotropic filtering on GLES as well? Last I saw, aniso was force-disabled for GLES.

I don't know about this, but if it's disabled, it would indeed be very worth it to get it enabled.

@deveee @Benau Was this done only for performance reasons or were there compatibility issues?

**Comment by deveee** [comment]
I don't remember, maybe it wasn't available in gles.

**Comment by Alayan-stk-2** [comment]
As far as I can tell:
- The code checks for the support of GL_EXT_texture_filter_anisotropic
- This exists for GL ES https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_filter_anisotropic.txt
- I haven't found code testing for GL ES in relation to anisotropic filtering

So I would think it should work.

However, the people I asked to test don't have it working on their device, but this might be because their devices don't support it.

**Comment by Alayan-stk-2** [comment]
Image quality now works like this : 
- Anisotropic x4, low resolution textures
- Anisotropic x16, low resolution textures
- Anisotropic x16, HD textures
- Anisotropic x16, HD textures, HQ mipmap

**Comment by Alayan-stk-2** [comment]
It escaped my notice that the following commit by Benau : https://github.com/supertuxkart/stk-code/commit/9e65bec76179bc8640a924ba223cd0a86778f4cb

Partially reverted my fix.

Instead of 4/16/16/16, 1.5 shipped using 4/16/4/16, which makes no sense whatsoever.
