### ISSUE TITLE
Add new skin variants based on the cartoon skin

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5094]
Although I prefer to use standard skins, the cartoon skin is also quite popular. I think it would be nice to have some variants of the cartoon skin, and especially a dark-theme variant.

There are already files with the themed GUI elements, but to do this we need several more things:
- A way to properly handle the selection with many skins. I think we could have two spinners, one to select a "base skin" and one for its variants. But it would need to still handle custom skins added by the player to the folder.
- A clean way to properly reuse custom fonts and icons, it would not be acceptable to duplicate all the icons that the cartoon theme use.

**Comment by qwertychouskie** [comment]
The second point is already implemented via the `base_theme` parameter.

Also, looks like I did the work to make color variants but never sent a PR: [cartoon-color-variants.zip](https://github.com/supertuxkart/stk-code/files/15383398/cartoon-color-variants.zip)

**Comment by Alayan-stk-2** [comment]
Done with https://github.com/supertuxkart/stk-code/commit/fa0bb71c3ab3fc5eba83704f007a78a2aee459e7 and https://github.com/supertuxkart/stk-code/commit/06d503a54b583bd885bdcd29f9cc6c90b3782329

A new classic skin was also added with https://github.com/supertuxkart/stk-code/commit/8b4741133d7c732f4deeb893aade0316c1d39821
