### ISSUE TITLE
"Hide and Seek" Game Mode

### ISSUE THREAD

**Issue by Guillaume-gillard** [supertuxkart/stk-code#5097]
### Description:

I would like to suggest the addition of a new "Hide and Seek" game mode to SuperTuxKart. 
This mode could enhance the gameplay experience by leveraging existing map features that are already popular for hiding spots in the egg hunt mode.

### Feature Details:

1. **Game Mode Setup:**
   - Players can define the number of seekers and hiders before the game starts.
   - Seekers and hiders are randomly assigned from the pool of players.

2. **Gameplay Mechanics:**
   - The minimap should only display the locations of players within the same camp (seekers can see other seekers, hiders can see other hiders).
   - Seekers aim to find and tag hiders by shooting a "bowl ball" at them.
   - Once a hider is hit by a bowl ball, they are considered caught and switch teams or become spectators.

3. **Time Limit:**
   - A timer is implemented to ensure the game does not last too long. Once the timer runs out, the game ends, and the remaining hiders are declared the winners.
---

Thank you for considering this suggestion! I believe it would be a great addition to SuperTuxKart and provide a fun new way for players to enjoy the game.

**Comment by Alayan-stk-2** [comment]
Please first discuss suggestions in the forum at https://forum.freegamedev.net/ (best to keep a record later)

Or in the IRC https://web.libera.chat/?channels=#supertuxkart (best to get quick feedback)
