### ISSUE TITLE
Transfering online user credentials

### ISSUE THREAD

**Issue by symbuzzer** [supertuxkart/stk-code#5099]
Hello. I installed SuperTuxKart via PortMaster on my retro handheld console. However, since there is no on-screen keyboard support yet, I cannot enter user information to play online.

SuperTuxKart is already installed on my computer and my online account is open. Is there an easy way to convey this?

I tried copying the players.xml file but unfortunately it didn't work

**Comment by deveee** [comment]
STK has its own onscreen keyboard. IIRC it should be possible to enable it in config.xml.
