### ISSUE TITLE
Template-id not allowed for constructor in C++20

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5125]
Some code in lib/irrlicht/include/irrXML.h makes GCC scream.

The code doesn't have an intrinsic defect, the C++ standard has simply been changed and this makes the old code non-compliant with the new standard.

Although STK doesn't rely on any feature from the most recent C++ standards (iirc it can be compiled with a C++11 compliant compiler), the warnings during compilation with recent GCC versions are highly annoying and the fix should be rather simple.

**Comment by CodingJellyfish** [comment]
Oh no looks like the apple build crashed because of this
