### ISSUE TITLE
Add a search bar for karts

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertuxkart/stk-code#5142]
For users with many addons, finding a specific kart in the kart selection screen can sometimes take excessive time.

A search bar, similar to the search bar allowing to search for tracks, could sometimes be useful.

**Comment by STK-FabianF** [comment]
A search bar would be important for soccer fields and battle arenas as well.

**Comment by deveee** [comment]
I feel that such a feature is more for desktop application rather than for a game that people play just for fun. Or maybe for some speedrunners that can't lose 10 seconds to select a kart. At least for me it's not how a game for kids should look like. Or maybe you should make a car simulator for adults :P

**Comment by Alayan-stk-2** [comment]
I opened this ticket because Crystal requested the feature, and for those users with 200 or 300 karts, I can understand the appeal. It's a niche feature, but if it's useful to people who are strongly invested in the game, it's not pointless.

Since we already have such a search feature for tracks, it's not much of a stretch to have one for karts.

> I feel that such a feature is more for desktop application rather than for a game that people play just for fun. Or maybe for some speedrunners that can't lose 10 seconds to select a kart. At least for me it's not how a game for kids should look like. Or maybe you should make a car simulator for adults :P

I don't think such a feature distracts from the experience of most of the playerbase who is not going to use it, ignoring it would be quite easy. No?

**Comment by Nomagno** [comment]
I'm fairly sure tracks can not be searched for unless you're on a voting selection, so basically the search features currently don't work offline. Should be fixed for tracks and implemented for tracks, probably?

**Comment by CodingJellyfish** [comment]
Fixed in #5172
