### ISSUE TITLE
[Menu] Normal race and Lap trial have the same icon

### ISSUE THREAD

**Issue by pedropaulosuzuki** [supertuxkart/stk-code#5160]
## Description

This happens both on "Cartoon" and "Regular" themes.

### Cartoon
![Screenshot from 2024-08-18 18-38-40](https://github.com/user-attachments/assets/44d3ba46-5166-4116-b8a1-89e4e086fa91)

### Regular
![Screenshot from 2024-08-18 18-38-21](https://github.com/user-attachments/assets/a4e253d8-2d40-45f3-9851-26af4fea3243)

## Configuration

STK release version: 1.4

STK Source: Flatpak - net.supertuxkart.SuperTuxKart 1.4

**Comment by qwertychouskie** [comment]
This was already fixed in https://github.com/supertuxkart/stk-code/pull/4864

**Comment by pedropaulosuzuki** [comment]
> This was already fixed in #4864

That's good to hear! Maybe we could backport just [this commit](https://github.com/supertuxkart/stk-code/pull/4864/commits/4932a60a9b1d8374bab2beb01e78c35c9053efa9) to 1.4? Don't know if it is worth the effort, but would greatly benefit the visuals and attention to detail in the latest stable release.

**Comment by qwertychouskie** [comment]
Better to just try to get 1.5 out the door relatively quickly.  That fix is just one of many accumulated fixes.

**Comment by pedropaulosuzuki** [comment]
> Better to just try to get 1.5 out the door relatively quickly. That fix is just one of many accumulated fixes.

That's fair. One point is that stable distros like Debian might still keep only the 1.4 stable version, and they'd probably add minor bug fix releases, but not a whole point release, but we can probably live with that, not the biggest deal. Btw, do we have a release date estimate for 1.5 yet?
