### ISSUE TITLE
Language can't be changed during race even though it's not optically disabled.

### ISSUE THREAD

**Issue by Heinz14** [supertuxkart/stk-code#5163]
## Description
Language can't be changed during race even though it's not optically disabled.

![Super Tux Kart tip layer is over menu and settings during a race Unbenannt](https://github.com/user-attachments/assets/3ea65cab-acbd-4c60-8e16-4ca5f8d1ee3c)

## Steps to reproduce
1. start race
2. try to change the language

## Configuration
STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): Website

System: Win10

**Comment by searinminecraft** [comment]
well yes, they are disabled while in-game, just that theres no clear indication (e.g. faint text, grayed out, etc)

**Comment by Alayan-stk-2** [comment]
Visually disabling the list would have been complicated, so I simply disabled the tab (and the players tab too, as everything there is disabled anyways).
