### ISSUE TITLE
volume settings to weak; difference between highest and lowest volume too small

### ISSUE THREAD

**Issue by Heinz14** [supertuxkart/stk-code#5164]
## Description
volume settings to weak; difference between highest and lowest volume too small

## Steps to reproduce
change the volume

## Configuration

STK release version: 1.4

STK Source (PPA, distribution package, official binary, etc.): Website

System: Win10

**Comment by kimden** [comment]
There were some changes for sound scale already in git version, you can try later versions [here](https://github.com/supertuxkart/stk-code/releases/tag/preview)
