### ISSUE TITLE
Supertuxkart nintendo und 3ds


### ISSUE THREAD

**Issue by AlexanderjanSzawarzynski** [supertuxkart/stk-code#5166]
![SuperTuxKart.jpg](https://github.com/user-attachments/assets/b79678a2-bb8c-4bfa-b80d-7e3c184f771d)
Nintendo 3ds

**Comment by AlexanderjanSzawarzynski** [comment]
@dos1 > ![SuperTuxKart.jpg](https://github.com/user-attachments/assets/f5f3334a-ca3c-4cc5-b905-656634f9930d)
> 
>

**Comment by AlexanderjanSzawarzynski** [comment]
Wann kommt SuperTuxKart
3ds und PSP
![SuperTuxKart.jpg](https://github.com/user-attachments/assets/b635988d-8501-407c-8f00-3a49c3b5ee8d)

**Comment by AlexanderjanSzawarzynski** [comment]
Supertuxkart nintendo 3ds und Switch

**Comment by AlexanderjanSzawarzynski** [comment]
[](url)
![109650405-ef1eeb80-7b3b-11eb-9dd2-6b28a4e1a950](https://github.com/user-attachments/assets/6b7d241a-4de0-482c-b44e-4ef07c90dbcf)

**Comment by AlexanderjanSzawarzynski** [comment]
![pexels-dids-1367226](https://github.com/user-attachments/assets/4485565b-dc32-408b-bdbc-c07acbd7a9f2)
Supertuxkart 3ds und Wii U

**Comment by AlexanderjanSzawarzynski** [comment]
#2276 
[](url)
@qwertychouskie

**Comment by MatusGuy** [comment]
Hello. We Want Super  tux car on 3DS XL NEW. Thanks for super Team Coopearation! I hope to see you soon in the 3DS.

![Image](https://github.com/user-attachments/assets/d912a3f1-01bc-4b0c-a8b1-247e53e82b6e)

**Comment by CrystalDaEevee** [comment]
Hello. We Want Super tux car on Canon TS5150. Thank you my friends

![Image](https://github.com/user-attachments/assets/91b7a609-19c8-429a-9680-4f74f1ebae36)

**Comment by Frostwithasideofsalt** [comment]
stk?
![Image](https://github.com/user-attachments/assets/9adafe33-48a1-4a06-a344-6da449feec03)

**Comment by cyberfig** [comment]
supertux krat ninteno real in 2030

**Comment by cyberfig** [comment]
enjhoy for free

**Comment by cyberfig** [comment]
supertuxkart in soulja boy console

**Comment by cyberfig** [comment]
> stk? ![Image](https://github.com/user-attachments/assets/9adafe33-48a1-4a06-a344-6da449feec03)

tux pregenanante?

**Comment by MatusGuy** [comment]
Ah yes! Penny baby!

**Comment by cyberfig** [comment]
please rename issue to tux is not pregunttne in lastest nightly version

**Comment by Frostwithasideofsalt** [comment]
![Image](https://github.com/user-attachments/assets/fe7f8197-d990-43d6-b23c-e3416d823eaf)

**Comment by cyberfig** [comment]
![Image](https://github.com/user-attachments/assets/d864e15d-3d51-4d0f-9a2f-acbaa1359f29) pregan tux in stk nikey shoes

**Comment by cyberfig** [comment]
new irc bridge with stk pregnant tux ai chat

**Comment by RestlessDog** [comment]
Hello pedoton, STK en el Mighty Patch!!!

![Image](https://github.com/user-attachments/assets/0d4121a5-c4fd-4663-a99c-bf9fdb1aac1f)

**Comment by cyberfig** [comment]
(3ds)

**Comment by cyberfig** [comment]
stk mitty pach?

**Comment by MatusGuy** [comment]
(1ds)

**Comment by cyberfig** [comment]
👀👀👀👀👀👀

**Comment by cyberfig** [comment]
![Image](https://github.com/user-attachments/assets/1f77738d-a9ea-45a1-8360-888500585e35)

**Comment by cyberfig** [comment]
sorry for my bad scotland

**Comment by Frostwithasideofsalt** [comment]
> sorry for my bad scotland
its ok cause practice practice is importan

**Comment by CrystalDaEevee** [comment]
This game would be fire on my gaming toaster
![Image](https://github.com/user-attachments/assets/8e754577-42f6-45aa-9a8e-e71fcee519d1)

**Comment by cyberfig** [comment]
bro
this issue is a duplicate of #5166

**Comment by CrystalDaEevee** [comment]
endless loop!!

**Comment by cyberfig** [comment]
pregnant tux

**Comment by searinminecraft** [comment]
lock this issue down NOW, to put it simply, stk on those platforms is impossible due to the limited amount of RAM, VRAM, and CPU power.

# JUST LOCK THIS ISSUE DOWN

**Comment by deveee** [comment]
Lol every time I see my Samsung fridge I'm disappointed I can't play STK on it.
