### ISSUE TITLE
The "no limit" max-players-in-game parameter gets changed into the first used limit

### ISSUE THREAD

**Issue by KaziSykOS** [supertuxkart/stk-code#5173]
hello, i want to play with 4 friends but, only two first to join the server can play, the other #+2 player are with a sand clock (hourglass) logo, they can't play, only spectate the round between the first 2 player to join. Sorry if it is poor redacted, i am from Colombia.

**Comment by CodingJellyfish** [comment]
May I ask which server you and your friends were in?

**Comment by kimden** [comment]
Edit %appdata%/roaming/supertuxkart/config-0.10/server_config.xml, set <max-players-in-game value="2" /> to 8. STK somehow sets it to 2 automatically for many players, I assume there was an issue about that but cannot find it now.

**Comment by frankm24** [comment]
I have the same problem... How would I fix on MacOS?

**Comment by qwertychouskie** [comment]
> I have the same problem... How would I fix on MacOS?

See "Where is the configuration stored?" on https://supertuxkart.net/FAQ

**Comment by Alayan-stk-2** [comment]
> Edit %appdata%/roaming/supertuxkart/config-0.10/server_config.xml, set `<max-players-in-game value="2" />` to 8. STK somehow sets it to 2 automatically for many players, I assume there was an issue about that but cannot find it now.

This was mentioned here: https://github.com/supertuxkart/stk-code/issues/4874

I guess a look is needed as to why STK sets it at 2 by default for many players?
