### ISSUE TITLE
[Not Issue] Permission to publish 

### ISSUE THREAD

**Issue by jhayar0719** [supertuxkart/stk-code#5174]
hi this is not an issue , i just post it here because there's no Discussion tab on this repo . 

I'm currently porting this to ubuntu touch with input /touch keyboard support . I would like to ask permission to original Developer to allow me to publish it to open-store.io of Ubports whenever i finished porting this to ubuntu touch . 

also will PR my changes to your upstream branch 
Thank you

**Comment by CodingJellyfish** [comment]
Hi.
I would grant the permission after merging your promised PR.

**Comment by deveee** [comment]
I'm glad that someone is working on it.

I'm not sure what you mean by "original Developer". People come and leave. I personally just would like to keep it free for everyone and without ads. And you are free to do anything as long as you meet license requirements.

I wonder if it's possible to make a build script, so I can publish the package on github too?

I also wonder if you belong to the Ubuntu Touch organization?

**Comment by jhayar0719** [comment]
> Hi. I would grant the permission after merging your promised PR.

i see noted :) thanks 

> I'm glad that someone is working on it.
> 
> I'm not sure what you mean by "original Developer". People come and leave. I personally just would like to keep it free for everyone and without ads. And you are free to do anything as long as you meet license requirements.
> 
> I wonder if it's possible to make a build script, so I can publish the package on github too?
> 
> I also wonder if you belong to the Ubuntu Touch organization?   Not directly but just a user of ubports
