### ISSUE TITLE
Start benchmark mode from command line 

### ISSUE THREAD

**Issue by ektor5** [supertuxkart/stk-code#5177]
## Description

In the preview version there is a "Benchmark Mode" that can be selected from Graphical Setting Menu, but I was unable to find any combination of Command Line parameters to start it automatically. 

Using Benchmark Mode over Profile Mode is crucial for the following reasons:
- Cannot set unlimited FPS anymore (--max_fps=999 is deprecated)
- If setting Physics FPS to 1000, profiler seems to calculate FPS over that, not the actual rendering (look below)
- Better reproducibility with replay than with random kart laps 

The idea is to start it from Phoronix Test Suite or any automatized testing.
Is there a way to start "Benchmark Mode" from command line?

## Additional information

When using Profile mode, the output of `Average FPS` seems bound to Physics FPS set in `stk_config.xml`
MangoHud reports way higher numbers while rendering.

e.g. FPS = 120
```
[verbose  ] profile: Number of frames: 7805 time 66.822006, Average FPS: 116.802841
```

e.g. FPS = 1000
```
[verbose  ] profile: Number of frames: 65005 time 67.519005, Average FPS: 962.765991
````

Profile Mode command line:
```
./supertuxkart --no-start-screen --xmas=2 --easter=2 \
                        --profile-time=60 --screensize=2880x1800 --fullscreen \
                        --enable-glow --enable-bloom --enable-light-shaft --enable-dof \
                        --enable-motion-blur --enable-mlaa --enable-ssao --enable-ibl \
                        --enable-hd-textures --enable-dynamic-lights --anisotropic=16 \
                        --shadows=1024 --numkarts=8 --track=black_forest --render-driver=vulkan
```

## Configuration

STK Source (PPA, distribution package, official binary, etc.): 
https://github.com/supertuxkart/stk-code/releases/download/preview/SuperTuxKart-git20241001-linux-arm64.tar.gz

System: Snapdragon X Elite ARM64

**Comment by kimden** [comment]
> Better reproducibility over random kart laps

I thought it just plays the same pre-recorded ghost replay all the time...

**Comment by ektor5** [comment]
> > Better reproducibility over random kart laps
> 
> I thought it just plays the same pre-recorded ghost replay all the time...

The `profile-time` option? As far as I know, it should "autoplay" a track for just x seconds, you can also vary the number of karts with `numkarts`, while the `benchmark mode` just launches the replay, also disabling FPS limits
