### ISSUE TITLE
Wii U Port?

### ISSUE THREAD

**Issue by CrossScarDev** [supertuxkart/stk-code#5186]
If STK can run on the Switch it shouldn't be too hard to port it to the Wii U as they both use the same build system. In my experience porting Wii U apps to switch it wasn't too hard I just had to change some things related to update functions and then it worked just fine.

**Comment by qwertychouskie** [comment]
I don't think the Wii U supports OpenGL, which would mean a Wii U port would require a rewrite of the entire graphics pipeline.  Probably not going to happen.

**Comment by CrossScarDev** [comment]
Oh yeah I can only find opengl 1 for the wii u.

**Comment by CrossScarDev** [comment]
I'll close this issue now.
