### ISSUE TITLE
fps drops only on story mode

### ISSUE THREAD

**Issue by GaalDorn1k** [supertuxkart/stk-code#5203]
## Description
FPS drops on any map on story mode (drops from 111 fps to 32 fps)
On the same maps in single mode the fps is consistently high
The behavior does not depend on graphics quality settings

## Configuration

STK release version:
1.4

STK Source (PPA, distribution package, official binary, etc.):
from oficial site, from linux mint repo (the behavior is also reproduced on the flatpack package)

System: 
Linux Mint 22 Cinnamon
Kernel 6.8.0-48

Graphics card: 
rtx 3060 12 Gb 550 driver (the behavior is also reproduced on any other driver)

CPU: 
Ryzen 5 3600

Gamepads/keyboards models if related to the issue: 

## Additional information

while starting:
```
WARNING kartdirt shader is missing, fallback to solid
```

**Comment by CodingJellyfish** [comment]
Did you compared these two with the same AI count?

**Comment by GaalDorn1k** [comment]
@CodingJellyfish yes, I compared. The behavior does not depend on AI count. 9 karts or 1 kart - not different

**Comment by GaalDorn1k** [comment]
Also, after conducting several experiments in the evening, I discovered that in other games (including steam) frames periodically disappear. Moreover, the fps counter does not record this.

The problem apparently appeared after upgrading to the new mint 22. I didn’t play games for a couple of months after the upgrade, but today I decided to play)
Therefore, if appropriate, I would like to ask - how accurate is the frame counter in STK? Becouse STK frame counter seems to be registering it, but does not work dynamically - it always shows a certain value from the beginning of the race to the end

**Comment by GaalDorn1k** [comment]
After disabling compositor for fullscreen windows, I seem to have solved the problem. However, it's not clear why this worked for STK, which I always have running in a small window. Also I dont understand why the FPS counter shows low rate - about 40-50, sometimes 60. STK always gave the best performance on this computer

**Comment by CodingJellyfish** [comment]
Hmmmmmmmmmmmmmmm

**Comment by GaalDorn1k** [comment]
Hi! The problem turned out to be entirely hardware. 
I'm closing this topic
