### ISSUE TITLE
We need to talk about data propagation.

### ISSUE THREAD

**Issue by Nomagno** [supertuxkart/stk-code#5215]
Data propagation in SuperTuxKart, understood as the passing of information from one module/class of the code to another, is:
1. Inconsistent
2. Fragile
3. Inflexible/hard to modify
4. Hard to understand/confusing
5. Poorly documented

The issue is not necessarily that individual decisions don't make sense, it's rather that the flow of data feels completely arbitrary. A method is often passed the data it needs, but this data might be obtained by wildly different means from different callers (one direct, the other from the race manager, for example). But sometimes a class is assumed to have the correct information manually set by whoever instanced it. And I refuse to even get into how hard it is to sometimes grasp how something gets from the GUI to the codebase core without resorting to sorcery.

I'm sure most developers are aware of this to some level. I don't think anyone is willing to fix it, and I'm not sure anyone can be blamed as this is likely the result of long periods of one single person touching a part of the code, different from the others. I simply wanted to leave this written down somewhere.

Maybe some kind of decision towards future architecturing could be taken, and tried to be applied where possible for future features/changes?

Cheers.

**Comment by deveee** [comment]
Feel free to improve :)
