### ISSUE TITLE
Problem username and password  

### ISSUE THREAD

**Issue by Gaienhofen1** [supertuxkart/stk-code#5229]
I have completely forgotten my username and password. I have already forgotten my password. Please delete it completely or get a solution immediately!!!

**Comment by Alayan-stk-2** [comment]
STK provides a password reset option but it expects you to provide your username: https://online.supertuxkart.net/password-reset.php

If you can't find your username anywhere, I would need your email.

**Comment by Gaienhofen1** [comment]
doesn't work at all

Alayan-stk-2 ***@***.***> schrieb am Di., 24. Dez. 2024,
01:26:

**Comment by Alayan-stk-2** [comment]
I can't help without more information.

**Comment by Alayan-stk-2** [comment]
Closing because this isn't an issue with the codebase.

I need to know your email to be able to help more.

**Comment by Gaienhofen1** [comment]
Please  ***@***.***

Alayan-stk-2 ***@***.***> schrieb am Fr., 27. Dez. 2024,
11:45:

**Comment by Alayan-stk-2** [comment]
I'm sorry, when you give the address normally github auto-hides it to avoid scrappers getting it...

Github doesn't have a way to send PMs, so we need some workaround, unfortunately. Pick a solution:
- Send it to me on discord, username: _alayan_
- Write it in a comment on the STK blog and tell me you have done so (comments there get held up for approval so only I will see it)

**Comment by dixonSolutions** [comment]
Hello guys, is there any way I can reset my password, with forgotten username or recover my username, it may have had "rat", "jiji" or "rad", different cases as well, thanks for the help email is radr40662@gmail.com, here github, mask this r a d r 4 0 6 62 @ g m a i l . c o m
