### ISSUE TITLE
Client GP result screen shows point additions using local config instead of server

### ISSUE THREAD

**Issue by kimden** [supertuxkart/stk-code#5234]
## Description
An online GP server doesn't have to conform to scoring system used in local GPs. It can send any points.

The client has to use those points received from the server in three cases: (1) in the race results screen, showing +delta; (2) in the animation of current GP results screen, showing +delta, then slowly converting it into points on the screen; (3) after the animation, just showing the current GP standings.

Currently, the client uses points from the server in (1) and (3), and uses local GP scoring in (2), which leads to confusion, 

Illustrations:
(1)
![Screenshot from 2024-12-29 16-24-12](https://github.com/user-attachments/assets/44b1098f-f25b-4520-9928-8e3cc98123d8)

(2)
![Screenshot from 2024-12-29 16-24-15](https://github.com/user-attachments/assets/98b0fc56-68e7-4c7f-8184-c40bb5e99252)

(3)
![Screenshot from 2024-12-29 16-24-19](https://github.com/user-attachments/assets/5a1aa41e-2489-4ea1-8d0f-f0bfc2ea8495)

## Steps to reproduce

1. Start a GP with any server that has a GP scoring different from the default one (e.g. by modifying stk_config.xml)
2. Finish a game (preferably with more than one player, otherwise there's no animation, but the issue is visible there too as the server points for a single player can be nonzero)
3. Observe the result screens.

## Configuration

STK release version: latest git 4ea1a28ca26d34ae6a

**Comment by Alayan-stk-2** [comment]
Fixed with #5235
