### ISSUE TITLE
Challenges handling in addons

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#543]
**Author: hikerstk**

If an addon is loaded that includes a challenge, the challenge will not be loaded (only next time the game is started).  Similarly if an addon is removed, any challenges will still be available in game (which then might cause 'undesired behaviour' if the challenge would actually fulfilled, unlocking the addon).

Minor since atm we don't have any addons with challenges.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/487

**Comment by Alayan-stk-2** [comment]
Is the principle of an addon coming with a challenge still even valid ?

It would be incompatible with the overworld anyway.

**Comment by Alayan-stk-2** [comment]
There is still no addons which can add a challenge, and even if there was, the story mode would offer no way to access it. It would thus be an entirely new feature to create, and a defect in a non-feature is a non-defect.
