### ISSUE TITLE
Local export of armature

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#566]
**Author: auria**

For the ghost in crescent crossing : In blender, the armature is at approximately (-50.5, 5, -25.8) on the first frame.
A disassembly of the B3D file revealed that the locations of the bones are : 

```
    NODE 
        Name: Bone.001 
        Position: (-50.45, 5.50, -25.84) 
    NODE 
        Name: Bone.002 
        Position: (0.00, 0.82, 0.00) 
    NODE 
        Name: Bone.003 
        Position: (-50.45, 5.50, -25.84) 
    NODE 
        Name: Bone.004 
        Position: (0.00, 0.91, 0.00) 
    NODE 
        Name: Bone.005 
        Position: (-50.45, 5.50, -25.84) 
    NODE 
        Name: Bone 
        Position: (-50.45, 5.50, -25.84) 
```

So quite obviously saving in local coordinates fails for some bones 

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/510

**Comment by auriamg** [comment]
Removing milestone as the issue still exists, but does not block us at this time

**Comment by SuicSoft** [comment]
@auriamg Is Crescent Crossing track still included by default ?

**Comment by qwertychouskie** [comment]
No, it is in add-ons, but the problem with the exporter still exists.

**Comment by Benau** [comment]
see #1900 now working (even with instancing)
