### ISSUE TITLE
Alternative tux update issue

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#570]
**Author: auria**

I had alternative tux revision 6. I then updated to revision 7. After the update, the kart now had holes in them. After restarting STK, it is ok

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/514 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/514 )

**Comment by qwertychouskie** [comment]
> I believe this is done in irrlicht internally and MaterialManager maintains a pointer to it, but I couldn't figure it out exactly.

Is this still an issue, since Antarctica is used now?

**Comment by auriamg** [comment]
This is probably outdated, we can open a new ticket with updated info if necessary
