### ISSUE TITLE
Controller configuration impossible with a DualShock3

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#574]
**Author: mungewell**

On the latest release (upertuxkart-0.7.3-linux-glibc2.11-i386) I am unable to configure my DualShock3 controller. It is connected via USB and seen OK in the controller list.
## However when I attempt to assign a control, nothing is registered. On each attempted 'assign' the console reports

%% storing new axis binding, value=0 deviceID=0 button=0 axisDirection=+
%% storing new axis binding, value=32767 deviceID=0 button=1 axisDirection=+
%% storing new axis binding, value=32767 deviceID=0 button=2 axisDirection=+
%% storing new axis binding, value=0 deviceID=0 button=3 axisDirection=+
%% storing new axis binding, value=0 deviceID=0 button=4 axisDirection=+
%% storing new axis binding, value=0 deviceID=0 button=5 axisDirection=+
%% storing new axis binding, value=0 deviceID=0 button=100 axisDirection=+
%% storing new axis binding, value=0 deviceID=0 button=101 axisDirection=+
%% storing new axis binding, value=0 deviceID=1 button=0 axisDirection=+
## %% storing new axis binding, value=0 deviceID=1 button=1 axisDirection=+

I suspect that the problem is caused by the fact that all the buttons are pressure sensitive, and are reported as both an axis and a button.

In the 'not pressed' state the axis reads '-32767' and '32767' when fully pressed.
## jstest reports

simon@crankshaft:~/supertuxkart-0.7.3-linux-glibc2.11-i386$ jstest /dev/input/js1 
Driver version is 2.1.0.
Joystick (Sony PLAYSTATION(R)3 Controller) has 28 axes (X, Y, Z, Rz, (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null), (null))
and 19 buttons (Trigger, ThumbBtn, ThumbBtn2, TopBtn, TopBtn2, PinkieBtn, BaseBtn, BaseBtn2, BaseBtn3, BaseBtn4, BaseBtn5, BaseBtn6, BtnDead, BtnA, BtnB, BtnC, (null), (null), (null)).
Testing ... (interrupt to exit)
## Axes:  0:     0  1:     0  2:     0  3:     0  4:-32767  5:-32767  6:-32767  7:-32767  8:-32767  9:-32767 10:-32767 11:-32767 12:-32767 13:-32767 14:-32767 15:-32767 16:-32767 17:-32767 18:-32767 19:-32767 20:-32767 21:-32767 22:-32767 23:-32767 24: 32767 25:-30404 26:-32767 27:-32767 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off 13:off 14:off 15:off 16:off 17:off 18:off 

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/518

**Comment by qwertychouskie** [comment]
@joythorogood Is this still an issue for you?

**Comment by qwertychouskie** [comment]
@mungewell Is this still an issue for you?

**Comment by Alayan-stk-2** [comment]
Similar to #2240

**Comment by Alayan-stk-2** [comment]
No news for years, and I've seen someone reporting a Dualshock4 working correctly with the beta. Closing for now.
