### ISSUE TITLE
Vertex color weirdness

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#599]
**Author: auria**

Check the attached Rome track. The buildings are red, yet when you export to blender many are no longer red. Accessing the vertex colors via the python terminal shows that many vertex colors are indeed white. We need to figure out how blender stores their vertex info because in Blender the building is clearly red

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/543 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/543 )

**Comment by nado** [comment]
What’s the status on this ?

**Comment by auriamg** [comment]
Closing as outdated
