### ISSUE TITLE
Loading overworld is SLOW

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#602]
**Author: auria**

Since in story mode the player will visit the overworld often, it needs to load much faster.

A quick profiling session showed that ~66% of the loading time is spent in TriangleMesh::createCollisionShape, more specifically in new btBvhTriangleMeshShape, and even more specifically in btQuantizedBvh::buildTree. (the rest of the loading time is loading the textures and B3D files)

The btQuantizedBvh::unQuantize function stands out as taking over 14% of the loading time just on its own.

A few ideas to make it faster.
1) Don't recalculate this everytime the overworld is shown, since we will visit it often; instead cache the result and reuse it on next visit. This requires special-casing the overworld but should be quite doable. The initial load time would still be slow though.
2) Pre-calculate the data and serialize it in a file, if bullet supports that (I have seen some serialization support in bullet but not sure about btBvhTriangleMeshShape)
3) Create a simplified mesh for the physics only, so that it has less data to place in the tree. PAINFUL for the artist.
4) Ask the bullet people if there is something else that can be done ^^

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/546

**Comment by samuncle** [comment]
is it still the case ? for 0.8.2 aka 0.9

**Comment by qwertychouskie** [comment]
What is the situation now?  Also, are all tracks cached, or just the overworld?

**Comment by auriamg** [comment]
Load times have been improved a lot, should be good enough now
