### ISSUE TITLE
Switch all particle files to use the new syntax

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#621]
**Author: hikerstk**

With the old syntax

```
material file=
```

it is (at least sometimes) necessary to specify the texture in a materials.xml file so that it is preloaded.

The new syntax

```
material name=
```

does not need this anymore. After this support for file= should also be removed.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/565

**Comment by nado** [comment]
Is it still needed ?

**Comment by qwertychouskie** [comment]
Can be closed.
