### ISSUE TITLE
Buggy export

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#642]
**Author: auria**

See http://forum.freegamedev.net/viewtopic.php?p=27981#p27981
In blender, the hills are in front of the sky, yet in STK they end up mostly behind the sky

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/586

**Comment by nado** [comment]
What’s the status on this ?

**Comment by auriamg** [comment]
Closing as outdated, we can reopen a new ticket if we find similar issues in the new exporter
