### ISSUE TITLE
Support for 'cannon'

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#656]
**Author: hikerstk**

A 'canon' is a feature that quickly moves the kart from one point of a track to another. Basic support was added in r11021. To finish the work and make it useable, we need support for this in the exporter. The idea is that artists specify two check-lines like structures: the first one the start checkline (i.e. crossing this check line will trigger the canon), the second one the line where the karts will be released (Ideally, if you trigger at the left side of the first checkline, you will arrive at the left side of the second checkline etc, allowing the user to target where they want to be when they can drive again).

1) Support in the track exporter. The following data should be added to the check structures in the scene.xml file for each canon:
```
   <canon kind="canon" speed="50" min-height="-0.008819" 
           p1="227.982346 109.128738" p2="229.342407 90.069756"
           target-p1="92.126266 -13.22 -117.803696"
           target-p2="79.177559 -13.22 -140.231522"/>

```
Speed is the speed with which the kart should be moved (we might add acceleration/deacceleration later). p1, p2, min-height is the data for a check line (start check line, which will initiate shooting the kart). target-p1/p2 are the two end points of a line at which the kart should be end up (in 3d, not 2d as specified for the check-line). The following syntax is used to add support for an arbitrary curve (instead of a normal linear interpolation):
```
 <canon kind="canon" speed="..." min-height="..." p1="..." p2="...">
   <curve channel="RotZ" interpolation="bezier">
    <p c="1.000 20.000" h1="-18.067 35.565" h2="20.067 4.435"/>
...
   </curve>
   <curve channel="LocX" ...>
   </curve>
  </canon>
```
The curve data is basically the data structures already supported for IPOs in the exporter and STK.
[do we want support both for a simple linear interpolation, or only curves? Perhaps automatically add a curve for a linear interpolation automatically??](question:)

2) Once this is added, please reassign to me. The following improvements need to be added to STK:
- Add support for rotation
- Add support for curves
- Fix the camera handling
- Take the location where the first check-line is crossed into account to determine where the kart should end. The curves should then connect the left side of the first checkline with the left side of the right checkline, and STK would interpolate to give the right position.
- Potentially add support for (de)acceleration, adjust the physical velocity when releasing the kart.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/600

**Comment by qwertychouskie** [comment]
The exporter already has support for this (see https://supertuxkart.net/Physics), can this be closed?
