### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#755]
**Author: hikerstk**

Create a tutorial covering the following subjects (roughly sorted by difficulty):

- driving
  accelerate, steer, brake
- braking for sharp turns
- rescue
- items
- bananas
- nitro
- start boost
- skidding
- different skidding boosts
- slipstream

We can either use a special track just for the tutorial, and/or a simple plane as a track on which we place road cones (or bananas) left/right (and to fulfill a tutorial you would need to drive without hitting over any road cones). 
Perhaps use some ghost data to show what needs to be done, and/or allow people to 'follow the ghost'
Gnu should act as a teacher/mentor

Not all of this needs to be done for 0.8 though

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/699

**Comment by auriamg** [comment]
Tutorial is good enough for now
