### ISSUE TITLE
3 strikes battle

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#77]
**Author: auria**

3 strikes could use with improvements. The most obvious one is probably the replacing of bubble gum with something more useful; bubble gum is only useful in a racing environment, since it doesn't take any lives from you it's not too useful in 3 strikes. Some kind of mine instead could be useful. The same could be said of plungers and portable zippers (if we still get any of them in 3 strikes, don't remember)

Another idea : nitro is not too useful there, so maybe nitro could be changed to instead give some kind of shield

Arthur_D: sometimes, one the grassy 3 Strikes level, we could be rescued and put inside one of the monoliths

Arthur_D: sometimes, one the grassy 3 Strikes level, we could be rescued and put inside one of the monoliths

Arthur_D: also, it is possible to own the other person several times in a row if you have several cakes, since there is no "invincibility period" after a shot

Arthur_D: also, it is a bit hard when driving on the track with all the
hills because rescue makes you lose a life
Arthur_D: so you can actually lose all by yourself

So seems like we need some facilty so that rescue only makes you lose a life if you fell of into water or something, not if you just fall off a hill

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/21

**Comment by Benau** [comment]
P1 done in a branch, P2 the weight is adjusted so bowling it's chosen more, P3 may make the game too complex, P4 not fare in my opinion.

Any more wishes you want?

**Comment by auriamg** [comment]
A lot of improvements has been made, thanks to Benau. If we want more improvements, other more specific tickets should be opened.

**Comment by anonymous7002** [comment]
P3: add a parameter to config file
