### ISSUE TITLE
Add axis constraint billboard

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#788]
**Author: samuncle**

Add the ability to constrain a billboard on other axes

http://nehe.gamedev.net/article/billboarding_how_to/18011/#6

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/732

**Comment by Benau** [comment]
![20_newton-2016 11 18_10 16 32](https://cloud.githubusercontent.com/assets/3252341/20416182/261a3cc2-ad35-11e6-8b7e-6fd915528a2e.png)
It's working now
