### ISSUE TITLE
Gamepad wrong assigned and hard to change

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#798]
**Author: smaller**

Hi, I use an old Thrustmaster Firestorm Digital 3 Gamepad, which is recognized out of the box. But when I try to reconfigure the keys, only a "- axis 2" label is dispalyed instead of the key. When I press the specialkey for altering the linked key, the message "please press now the new key" immediately disappears :(
You can get luck and if you toggle the specialkey and the desired key fast enough, your desired key will be accepted. I guess it's a bug?

Attached my config (the HID is another IR remote control)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/742 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/742 )

**Comment by anaselli** [comment]
0.8.2 is affected i have a gamepad which cannot be changed in setting at all, and a joystick which always be set as "axis2 -"

**Comment by auriamg** [comment]
Many gamepad issues were fixed recently, probably this one was too. We can always reopen if more issues are found
