### ISSUE TITLE
Improve kart rendering on kart selection screen

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#80]
**Author: auria**
- models are clipped on sides (however this mostly happens for large karts like Gooey or Mozilla, that we planned to scale down anyway because they're too big, so this may actually be a non-issue; this may even be a feature, saying "kart too big")
- think about switching away from RTT, should be much faster this way for many people

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/24

**Comment by auriamg** [comment]
Closing as outdated
