### ISSUE TITLE
Improving quest complete animation

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#810]
**Author: smaller**

Hi even if the idea of the animation is quiet nice, but it could be more still improved:
- to long
- screenshot of new features is very static (and low res)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/754

**Comment by auriamg** [comment]
Closing as outdated. It's still not perfect but good enough for the moment
