### ISSUE TITLE
stk crashes when  input.xml is removed

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#848]
**Author: samuncle**

STK crashes when you launch it for the first time. But not after

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/792

**Comment by Flakebi** [comment]
I can't reproduce both of the issues, stk works fine for me when input.xml is removed and I only get "2 watched objects leaking" (they're related to online things, so it's the same as if the file exists).

**Comment by qwertychouskie** [comment]
I tried removing input.xml, STK (git version) launched just fine.  Can this be closed?
