### ISSUE TITLE
Refactor shader code to make it easier to add new shaders

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#859]
**Author: samuncle**

It would be cool if we can write a shader and specify it in blender instead hardcoding like we are doing now. Like textures and particles.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/803

**Comment by Benau** [comment]
duplicated of #2750 

I think with SP it is possible to add shaders in xml even without recompile stk
