### ISSUE TITLE
Wall in Fort Magma is not solid

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#876]
**Author: keewis**

The wall beneath the window in the room on the same level as the start is not solid. Was that intended?

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/820 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/820 )

**Comment by qwertychouskie** [comment]
So now you have me curious... where is the easter egg?

**Comment by qwertychouskie** [comment]
Finding the easter egg should be an achievement.

**Comment by Alayan-stk-2** [comment]
Should this be considered as an issue, if it is an intended easter egg ?

**Comment by Alayan-stk-2** [comment]
Closing as it's not really a bug, even if the easter egg could use some improvement along the rest of the track.
