### ISSUE TITLE
Official linux binary doesn’t run

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#898]
**Author: red-skull**

The official linux x64 binary doesnt run on my computers (Arch linux x64).
I get the following message:
./supertuxkart: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./supertuxkart)

I think I read the "CURL_OPENSSL_3" thing was removed due to security issue. (I'm not sure about it.)

So any user with a recent curl may encounter this problem. It should be only a matter of how the binary is built and have nothing to do with the code, since I never had problem when compiling STK myself and the package for 0.8 in Arch repo works correctly.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/842

**Comment by deveee** [comment]
The only issue which I noticed in current 0.8.2-beta package is that new radeon drivers need newer libstc++ library. I will check before release candidate if it's safe to use system library. It should be compatible backwards...

Current package shouldn't have problems with curl library, so ticket can be closed.
