### ISSUE TITLE
Texture Problems In BlackHill Mansion

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#902]
**Author: downdateneon**

I've noticed ALOT of texture stretching in Black Hill Mansion on the road leading to the mansion. Also there is a lot on the overhangs for the mansion and on the sides

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/846 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/846 )

**Comment by auriamg** [comment]
This track is being remade so this will no matter anymore
