### ISSUE TITLE
'Supertuxkart' letters in overworld are upside down

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#922]
**Author: keewis**

The word 'supertuxkart' which appears three times on the hulk of the brown ship (the one with the challenge bubble of 'Island') is upside down.

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/866

**Comment by qwertychouskie** [comment]
>  i changed this in my object-collection, can be replaced now

Why hasn't this been replaced yet then?

**Comment by Benau** [comment]
fix in r17591 by akastanley
