### ISSUE TITLE
View/Zoom options

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#928]
**Author: bunder2011**

I was wondering if STR could support zooming out, or first person view.  Thanks

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/872

**Comment by auriamg** [comment]
An FPS view is not a good fit for STK

As for "zoom" (aka camera distance or FOV? unclear). FOV is already configurable in a XML file. For camera distance, a first step would be to move that to a config file. Not everything needs to be in the UI if very few people are going to change it - I have nothing against moving camera distances from hardcoded values to config files though

**Comment by Alayan-stk-2** [comment]
FoV and distance are now configurable options.
