### ISSUE TITLE
Improved billboard

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#936]
**Author: samuncle**

A billboarded not rendered at the location of the entity but projected from the camera to the entity, then just a little bit beyond that so that the particle appears to always be surrounding the entity.

(Useful for fake light emission like lanterns, lamps).
More information [http://forum.freegamedev.net/viewtopic.php?f=18&t=4127&sid=39514b439fdf39ac40ca4246c825a58d]

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/880

**Comment by hiker** [comment]
Please reopen if this is still an issue.

**Comment by samuncle** [comment]
Nope it's not an issue. Now we have the proper way to do this (with emit map/glow)
