### ISSUE TITLE
Update translations from the addons server

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#956]
**Author: hikerstk**

It would be useful to be able to update translations using the addon mechanism (typically after a release people will notice that their language is not fully translated and work on it. By the time the next release comes, strings have changed again and translations will be incomplete).

The server side of this could be handled by us (so leaving only STK code to work on), but feel free to look at the server code if you want to.

Modify the io/file_manager.cpp to provide a translation directory as part of the addons directory structure (similar to screenshot).

Check the file src/translation.cpp, constructor of Translator - this defines the search path for translations.

Confirm that this works by adding some .po files into the addon structure and change some strings to see that it indeed works (check if stk needs to be restarted, which is acceptable).

The new translation directory must also be able to supply new fonts (esp. Asian fonts only contain characters actually used, so if an Asian translation is changed we likely also need new (Asian) fonts). Check file_manager for this as well, it contains location of the fond directory).

Main problem: should we donwload and install new fonts transparently for the user (probably not) - but if we use a GUI, where do we put a button? Suggestions welcome :)

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/900 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/900 )

**Comment by auriamg** [comment]
Closing as outdated, transifex provides a tool to do this
