### ISSUE TITLE
Spaces in data filenames

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#969]
**Author: curaga**

The following files in trunk/data have spaces in their names:

```
data/tracks/alpha-planetarium/mars clouds.b3d
data/tracks/alpha-planetarium/neptun ring (arc).b3d
data/tracks/alpha-planetarium/generic clouds.b3d
data/tracks/alpha-planetarium/saturn ring.b3d
data/tracks/overworld/Mushroom 7 side.png
data/tracks/overworld/Mushroom 3.png
data/tracks/overworld/Mushroom 3 side.png
data/tracks/overworld/Mushroom 2.png
data/tracks/overworld/Mushroom 7.png
data/tracks/overworld/Mushroom 1 side.png
data/tracks/overworld/Mushroom 1.png
data/tracks/overworld/Mushroom 2 side.png
data/tracks/xr591/tube 2.b3d
data/tracks/xr591/tube 1.b3d
data/karts/konqi/konqi eye.png
data/karts/konqi/konqiV1 shadow.png
data/karts/konqi/konqi vehicle texture up1.png
data/karts/konqi/konqiV2 wheel texture.png
```

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/913 ( attachements can be found at http://supertuxkart.sourceforge.net/TracFilesBackup/913 )

**Comment by deveee** [comment]
Also too long names are not wanted (we have a few in data/library). Standard filename size in tar archives is 99 characters. Longer filenames must be hacked for example by using "@longlink" command. Every untar application should support it, but in theory it can cause issues.

**Comment by auriamg** [comment]
That's not problematic, closing
