### ISSUE TITLE
small bug in story mode

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#988]
**Author: tavariz91**

As said on the forum:

Easy to reproduce:
Go into a bubble. The texts says "press fire to start the challenge".
So, make it: press [your level and then try to validate by pressing [fire](fire].
Select). It doesn't work... You have to use the [button.

I think it could be rally better to have the choice as in the multi-player menu (to "log in" new players).

The comportment should be improved to:
Go into a bubble. The texts says "press fire to start the challenge".
press [fire](select]) OR [(Actually only [fire](select]) works.)
select your level and validate it by pressing [OR [select](fire]).

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/932

**Comment by auriamg** [comment]
Closing as "not a bug", the texts were also updated a while  ago to make that clearer
