### ISSUE TITLE
nolok's "bubble gum" don't turn into nitro

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#989]
**Author: tavariz91**

Nolok's "poo"/"bubble gum" (I don't know what it exactly is) don't turn into nitro while using the box / banana transformer (I don't have the name (again) but I'm sure you'll understand me :) )

**Comment by Wuzzy2** [comment]
But doesn't give this an unfair advantage to Nolok in multiplayer races?
It is also very irregular, because all other kart's bubble gum will be affected, only Nolok's “slime” is safe from magic.
